export default {
  num: 10,
  transcript: 10,
  title: "El surgimiento de la Ilustración en Inglaterra",
  source: "",
  feed: [
    {
      type: "info",
      title: "La Ilustración como proyecto europeo",
      body: "La **Ilustración** es el movimiento intelectual que domina Europa entre finales del siglo XVII y finales del XVIII. Su convicción central es que la razón humana, ejercida con método y sin ataduras a la autoridad, puede iluminar tanto la naturaleza como la sociedad. De ahí el nombre: sacar a la luz lo que la tradición dejaba en la sombra.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como proyecto europeo",
      body: "No es un sistema único ni una escuela con un fundador. Es una actitud compartida por autores de países distintos, que discrepan entre sí pero coinciden en un diagnóstico: buena parte de las creencias heredadas —religiosas, políticas, morales— no resisten el examen racional y sobreviven sólo por hábito, por miedo o por interés de quienes se benefician de ellas.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como proyecto europeo",
      body: "Cada país le da a esa actitud un acento propio. Inglaterra la vive como continuidad: la revolución científica y la revolución política ya ocurrieron, y la Ilustración inglesa administra sus resultados. Francia y Alemania, en cambio, todavía tienen esas batallas por delante, y sus versiones de la Ilustración son más combativas. Empezamos por Inglaterra porque es la más temprana y la que da el modelo.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como proyecto europeo",
      body: "En inglés el movimiento se llama **Enlightenment**, literalmente «iluminación» o «acto de dar luz». La palabra comparte la misma metáfora que el francés Lumières y el alemán Aufklärung: en los tres idiomas, ilustrar es despejar una oscuridad. La diferencia está en qué oscuridad hay que despejar, y ahí es donde los tres modelos se distancian.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como proyecto europeo",
      body: "Esa metáfora lumínica no es decorativa: supone que la verdad ya está ahí, disponible, y que lo único que hace falta es apartar los obstáculos que impiden verla —la superstición, el dogma no examinado, la autoridad que se impone sin razones. La Ilustración no inventa verdades nuevas; se propone despejar el camino hacia verdades que la razón, bien empleada, puede alcanzar por sí misma.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como proyecto europeo",
      body: "Ese optimismo respecto de la razón es lo que distingue a la Ilustración de otros momentos críticos anteriores, como el escepticismo de Montaigne, que desconfiaba de las capacidades humanas de conocer con certeza. Los ilustrados no dudan de la razón: dudan de las instituciones y las tradiciones que dificultan su ejercicio libre. El objetivo es liberar una facultad que ya se supone capaz, no fundarla de nuevo.",
    },
    {
      type: "quiz",
      question: "A diferencia del escepticismo de Montaigne, los ilustrados…",
      options: [
        "dudan de que la razón pueda conocer el mundo",
        "dudan de las tradiciones, no de la razón misma",
        "creen que ninguna época alcanza certezas firmes",
        "niegan que la razón pueda juzgar la religión",
      ],
      answer: 1,
      explain: "El escepticismo de Montaigne desconfiaba de las capacidades humanas de conocer con certeza. Los ilustrados, en cambio, confían en la razón: lo que ponen en duda son las instituciones y tradiciones que dificultan su ejercicio libre.",
    },
    {
      type: "info",
      title: "El modelo inglés: reforma sin ruptura",
      body: "La Ilustración inglesa arranca hacia 1650 y se consolida en las primeras décadas del siglo XVIII, sin la fractura violenta que después vivirá Francia. Inglaterra ya atravesó su revolución política en el siglo anterior, con la guerra civil y luego la Revolución Gloriosa de 1688, que instauró una monarquía limitada por el Parlamento. La Ilustración llega, entonces, a un terreno ya relativamente pacificado.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo inglés: reforma sin ruptura",
      body: "Ese contexto explica su tono. No es un movimiento de oposición frontal a las instituciones, sino de reforma dentro de ellas: se discute la tolerancia religiosa, se revisan los fundamentos de la fe, se difunde la nueva ciencia, pero no se busca derribar la monarquía ni la Iglesia establecida. La crítica inglesa prefiere la vía del ensayo, la carta y el panfleto a la del tratado sistemático.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo inglés: reforma sin ruptura",
      body: "Esa preferencia por formas breves y persuasivas, en vez del sistema filosófico cerrado, tiene una razón práctica: un público más amplio, formado por comerciantes, profesionales y gentry, empieza a leer filosofía fuera de la universidad, en cafés y clubes de lectura. La Ilustración inglesa nace, en buena medida, para ese público nuevo, no para los claustros académicos.",
    },
    {
      type: "quiz",
      question: "La Ilustración inglesa prefiere la reforma porque…",
      options: [
        "ya resolvió sus grandes conflictos políticos",
        "carece de universidades donde discutir filosofía",
        "el rey impide cualquier crítica a la Iglesia",
        "sus filósofos rechazan la tolerancia religiosa",
      ],
      answer: 0,
      explain: "Inglaterra ya atravesó su revolución política con la guerra civil y la Revolución Gloriosa de 1688: la Ilustración llega a un terreno relativamente pacificado, por eso prefiere reformar las instituciones antes que enfrentarlas.",
    },
    {
      type: "info",
      title: "Newton y Locke como modelos de la razón ilustrada",
      body: "Los ilustrados ingleses no necesitan inventar sus héroes: ya los tienen. **Isaac Newton** (1643–1727) y los Principia (1687) muestran que la razón humana, aplicada con método, puede descifrar las leyes que gobiernan el universo entero sin apelar a causas ocultas ni a la autoridad de los antiguos.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y Locke como modelos de la razón ilustrada",
      body: "**John Locke** (1632–1704) ofrece el equivalente en el terreno del conocimiento y de la política. El Ensayo sobre el entendimiento humano (1690) explica cómo la mente construye sus ideas a partir de la experiencia, sin ideas innatas; los Dos tratados sobre el gobierno (1689) fundan el poder político en el consentimiento y no en el derecho divino de los reyes.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y Locke como modelos de la razón ilustrada",
      body: "Newton y Locke se convierten así en el modelo doble de la Ilustración inglesa: uno muestra lo que la razón puede hacer con la naturaleza, el otro lo que puede hacer con la mente y con la sociedad. Los ilustrados franceses y alemanes los van a citar constantemente, casi siempre a través de Voltaire, que los divulga en el continente.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y Locke como modelos de la razón ilustrada",
      body: "Lo que ambos comparten, y lo que la Ilustración inglesa retiene como lección, es el rechazo del sistema cerrado. Ni Newton ni Locke parten de primeros principios evidentes por sí mismos, al modo de Descartes o de Spinoza: observan, experimentan, corrigen. La razón ilustrada, en su versión inglesa, es más un método de indagación que un edificio de verdades.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y Locke como modelos de la razón ilustrada",
      body: "Ese contraste con el racionalismo continental es deliberado. Donde Descartes o Leibniz parten de principios evidentes por sí mismos y deducen a partir de ellos toda una metafísica, Newton se niega expresamente a especular sobre las causas últimas de la gravedad: describe cómo se comporta, no por qué existe. Su célebre frase «no finjo hipótesis» resume ese rechazo del sistema cerrado.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y Locke como modelos de la razón ilustrada",
      body: "Locke aplica el mismo espíritu experimental a la mente humana: en vez de suponer facultades innatas que expliquen de antemano cómo conocemos, propone observar paso a paso cómo se forman efectivamente las ideas a partir de las sensaciones y de la reflexión sobre ellas. Es, literalmente, un «ensayo»: una indagación abierta, no una demostración cerrada de antemano.",
    },
    {
      type: "quiz",
      question: "Lo que Newton y Locke comparten, según la clase, es…",
      options: [
        "partir de principios evidentes por sí mismos",
        "observar y corregir, no cerrar un sistema",
        "fundar el conocimiento en ideas innatas",
        "reducir toda ciencia a las matemáticas puras",
      ],
      answer: 1,
      explain: "Ni Newton ni Locke parten de principios evidentes al modo de Descartes o Leibniz: observan, experimentan, corrigen. Por eso la razón ilustrada inglesa es más un método de indagación abierta que un sistema cerrado de verdades.",
    },
    {
      type: "info",
      title: "El deísmo",
      body: "El terreno donde la razón inglesa se aplica con más audacia es la religión. El **deísmo** sostiene que la existencia de Dios y los principios básicos de la moral pueden conocerse por la sola razón natural, sin necesidad de revelación, de milagros ni de dogmas particulares de ninguna Iglesia. Dios queda como el autor racional del orden natural, no como el protagonista de una historia sagrada.",
    },
    {
      type: "info",
      continues: true,
      title: "El deísmo",
      body: "El deísta no niega a Dios; niega que haga falta un texto revelado para conocerlo. Le basta con mirar el orden del universo —el mismo que describe Newton— para inferir una causa inteligente. De ahí que el deísmo se presente como la religión «natural» o «racional», opuesta a las religiones «positivas» o «reveladas», con sus rituales, sus jerarquías y sus disputas doctrinales.",
    },
    {
      type: "info",
      continues: true,
      title: "El deísmo",
      body: "**John Toland** (1670–1722) lleva la tesis a su forma más provocadora en El cristianismo no misterioso (1696): sostiene que ninguna doctrina cristiana genuina puede ser contraria a la razón ni superior a ella, y que los llamados «misterios» de la fe son acumulaciones históricas, no verdades reveladas irreductibles. El libro le cuesta persecución y hasta la quema pública en Irlanda.",
    },
    {
      type: "info",
      continues: true,
      title: "El deísmo",
      body: "**Anthony Ashley Cooper, tercer conde de Shaftesbury** (1671–1713), templa esa audacia con un tono más sereno. En sus escritos, reunidos en Characteristics (1711), defiende que el ser humano posee un sentido moral natural, independiente de premios y castigos religiosos, y que el buen gusto estético y la virtud moral nacen de la misma armonía interior. Su Dios es más un principio de orden que un juez.",
    },
    {
      type: "info",
      continues: true,
      title: "El deísmo",
      body: "Para Shaftesbury, además, el sentido moral funciona de manera análoga al gusto estético: así como reconocemos espontáneamente la belleza de una obra de arte sin necesitar una demostración formal, reconocemos también, de manera inmediata, la belleza de una acción virtuosa. Esa idea —que lo bello y lo bueno comparten una misma raíz en la sensibilidad humana— va a influir después en toda una corriente de la estética británica del siglo XVIII.",
    },
    {
      type: "info",
      continues: true,
      title: "El deísmo",
      body: "Toland, por su parte, no se detiene en el cristianismo: en obras posteriores avanza hacia posiciones cercanas al panteísmo, sosteniendo que el movimiento es una propiedad esencial de la materia misma y no algo que Dios deba imprimirle desde afuera. Esa deriva lo acerca al Spinoza que la clase 4 ya presentó, y anticipa el materialismo que en Francia va a radicalizarse aún más con Diderot y d'Holbach.",
    },
    {
      type: "info",
      continues: true,
      title: "El deísmo",
      body: "El deísmo inglés no pretende destruir la religión: pretende depurarla, reducirla a lo que la razón puede justificar. Esa moderación es característica del estilo inglés y contrasta con lo que hará el materialismo francés unas décadas después, que sí llevará la crítica religiosa hasta el ateísmo declarado.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo describe al deísmo o a la religión revelada?",
      groups: ["Deísmo", "Religión revelada"],
      items: [
        { text: "Dios se conoce por la sola razón natural", group: 0 },
        { text: "Hacen falta milagros y un texto sagrado", group: 1 },
        { text: "No exige rituales ni jerarquías obligatorias", group: 0 },
        { text: "La verdad depende de la autoridad de una Iglesia", group: 1 },
        { text: "Dios es autor racional del orden, no protagonista de una historia", group: 0 },
        { text: "La fe se transmite por dogmas propios de un credo", group: 1 },
      ],
      explain: "El deísta no niega a Dios: niega que haga falta un texto revelado para conocerlo. Le basta el orden del universo para inferir una causa inteligente, contra las religiones «positivas», con rituales, jerarquías y dogmas particulares.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencian Toland y Shaftesbury dentro del deísmo?",
      options: [
        "Toland niega a Dios; Shaftesbury lo afirma",
        "Toland es provocador; Shaftesbury es más sereno",
        "Toland defiende la revelación; Shaftesbury la niega",
        "Shaftesbury ataca al cristianismo; Toland lo defiende",
      ],
      answer: 1,
      explain: "Toland lleva el deísmo a su forma más provocadora, casi panteísta, y paga con persecución. Shaftesbury lo tempera con un tono sereno: un sentido moral natural, análogo al gusto estético, que reconoce lo bueno con la misma inmediatez que lo bello.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la postura que conoce a Dios y la moral por la sola razón natural, sin revelación?",
      answers: ["deísmo"],
      explain: "El deísmo, central en la Ilustración inglesa (Toland, Shaftesbury) y después en Voltaire, deja a Dios como autor racional del orden natural, no como protagonista de una historia revelada.",
    },
    {
      type: "info",
      title: "Tolerancia y crítica de la superstición",
      body: "La otra gran batalla de la Ilustración inglesa es la **tolerancia** religiosa y política. Después de un siglo de guerras civiles con componente confesional, la lección que sacan los ilustrados es que ninguna Iglesia tiene autoridad racional suficiente para imponerse por la fuerza sobre las demás, y que la convivencia exige aceptar la pluralidad de credos.",
    },
    {
      type: "info",
      continues: true,
      title: "Tolerancia y crítica de la superstición",
      body: "Locke formula esa idea en la Carta sobre la tolerancia (1689): el Estado debe ocuparse de los bienes civiles —vida, propiedad, libertad— y dejar la salvación de cada uno a su propia conciencia, porque la fe no puede imponerse por decreto ni por la fuerza sin volverse hipócrita. Es un argumento a la vez religioso y político.",
    },
    {
      type: "info",
      continues: true,
      title: "Tolerancia y crítica de la superstición",
      body: "Locke escribe la Carta poco después de instalarse en Holanda, exiliado por sus vínculos con la conspiración contra el rey católico Jacobo II, y en un país que practicaba desde hacía décadas una tolerancia religiosa mucho más amplia que la inglesa. Esa experiencia directa de una sociedad plural y funcional le da al argumento un respaldo que no es sólo teórico.",
    },
    {
      type: "info",
      continues: true,
      title: "Tolerancia y crítica de la superstición",
      body: "Con todo, la tolerancia de Locke tiene límites explícitos: no la extiende a los ateos, porque considera que quien no cree en Dios no tiene fundamento para respetar los juramentos y compromisos que sostienen la vida civil, ni tampoco, en la práctica, a los católicos, sospechados de obediencia a una autoridad extranjera, el Papa. La tolerancia inglesa nace amplia pero no universal.",
    },
    {
      type: "quiz",
      question: "La tolerancia de Locke, en la práctica, no alcanzaba a…",
      options: [
        "los protestantes de otras iglesias reformadas",
        "los ateos y también a los católicos",
        "los filósofos que defendían el deísmo",
        "los científicos que seguían a Newton",
      ],
      answer: 1,
      explain: "Locke no extiende la tolerancia a los ateos, porque cree que quien no cree en Dios no tiene fundamento para respetar los juramentos civiles, ni en la práctica a los católicos, sospechados de obedecer a una autoridad extranjera.",
    },
    {
      type: "info",
      continues: true,
      title: "Tolerancia y crítica de la superstición",
      body: "De la mano de la tolerancia viene la **crítica de la superstición**: la denuncia de las creencias que se sostienen por miedo, por costumbre o por manipulación clerical, y no por evidencia. Para los ilustrados ingleses, la superstición no es un error inocente, sino un instrumento de poder que mantiene a la gente sujeta a autoridades que no rinden cuentas ante la razón.",
    },
    {
      type: "info",
      continues: true,
      title: "Tolerancia y crítica de la superstición",
      body: "Ese combate contra la superstición no exige, en la versión inglesa, romper con la religión como tal. Se puede seguir siendo cristiano —muchos ilustrados ingleses lo son— y sostener a la vez que hay que limpiar la fe de todo lo que no soporte el examen racional. Esa combinación de reforma religiosa moderada, tolerancia civil y confianza en la ciencia es la marca de fábrica de esta primera Ilustración.",
    },
    {
      type: "info",
      continues: true,
      title: "Tolerancia y crítica de la superstición",
      body: "Un ejemplo concreto de ese combate es la actitud inglesa ante la caza de brujas: mientras en buena parte de Europa continental los procesos por brujería siguen activos entrado el siglo XVII, en Inglaterra la última ejecución por ese cargo ocurre en 1716, y hacia 1736 el Parlamento deroga directamente las leyes que la castigaban, tratándola ya como fraude y no como delito real. Ese giro legal es un síntoma de hasta dónde llegó la crítica de la superstición.",
    },
    {
      type: "quiz",
      question: "El fin de los procesos por brujería en Inglaterra muestra que…",
      options: [
        "la superstición también retrocedió en la ley",
        "el Parlamento nunca creyó en la existencia de brujas",
        "la Iglesia anglicana perdió todo poder político",
        "la tolerancia inglesa se volvió absoluta e ilimitada",
      ],
      answer: 0,
      explain: "En 1716 ocurre la última ejecución por brujería y hacia 1736 el Parlamento deroga las leyes que la castigaban, tratándola ya como fraude. Es un síntoma concreto de hasta dónde llegó la crítica ilustrada de la superstición.",
    },
    {
      type: "info",
      title: "El legado hacia el continente",
      body: "Hacia 1730 el ciclo inglés ya dio lo esencial de lo que va a exportar: Newton como modelo de método científico, Locke como modelo de teoría del conocimiento y de la política, el deísmo como religión racional y la tolerancia como principio de convivencia. Ese paquete cruza el Canal de la Mancha en la década siguiente.",
    },
    {
      type: "info",
      continues: true,
      title: "El legado hacia el continente",
      body: "Quien mejor lo transporta es un joven francés exiliado en Londres entre 1726 y 1729, que vuelve a su país deslumbrado por lo que vio: un régimen parlamentario, una ciencia sin trabas eclesiásticas, una filosofía empirista que le parece más sensata que la metafísica que le enseñaron en su educación jesuita. Ese autor es Voltaire, y con él la Ilustración adopta su segundo modelo, el francés.",
    },
    {
      type: "info",
      continues: true,
      title: "El legado hacia el continente",
      body: "Lo que Voltaire y, después de él, buena parte del continente van a admirar en el modelo inglés no es sólo un repertorio de doctrinas, sino un resultado institucional: que en Inglaterra la ciencia, la filosofía crítica y la disidencia religiosa moderada pudieran coexistir con el orden público, sin provocar el colapso que la ortodoxia continental temía. Esa prueba práctica es, en el fondo, el argumento más persuasivo que Inglaterra le ofrece a Europa.",
    },
    {
      type: "quiz",
      question: "El argumento más persuasivo que Inglaterra ofrece a Europa es…",
      options: [
        "que produjo más filósofos que Francia o Alemania",
        "que la disidencia convivió con el orden público",
        "que logró abolir la monarquía sin violencia",
        "que ningún disidente sufrió jamás persecución",
      ],
      answer: 1,
      explain: "Que la ciencia, la filosofía crítica y la disidencia religiosa moderada pudieran coexistir con el orden público, sin el colapso que la ortodoxia continental temía, es la prueba práctica más persuasiva que Inglaterra ofrece a Europa.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada nombre con su aporte a la Ilustración inglesa",
      pairs: [
        { left: "Newton", right: "Los Principia: leyes de la naturaleza sin causas ocultas" },
        { left: "Locke", right: "El consentimiento de los gobernados y la tolerancia civil" },
        { left: "Toland", right: "El cristianismo no misterioso: la fe sometida a la razón" },
        { left: "Shaftesbury", right: "El sentido moral natural, análogo al gusto estético" },
      ],
      explain: "Newton y Locke dan el modelo doble de método y de teoría política; Toland lleva el deísmo a su forma más audaz; Shaftesbury lo modera con una ética del sentido moral. Juntos arman el repertorio que Voltaire va a exportar al continente.",
    },
    {
      type: "info",
      continues: true,
      title: "El legado hacia el continente",
      body: "Ese contraste se vuelve todavía más nítido si se compara la suerte de Toland, perseguido pero no ejecutado por sus tesis, con la de pensadores continentales de audacia comparable en siglos anteriores, como Bruno o Vanini, condenados a la hoguera. Sin ser una sociedad plenamente libre para los criterios posteriores, la Inglaterra de 1650-1730 ya ofrece un margen de disidencia intelectual que buena parte del continente todavía no conoce.",
    },
  ],
};
