export default {
  num: 14,
  transcript: 14,
  title: "Kant: el giro copernicano",
  source: "",
  feed: [
    {
      type: "info",
      title: "El problema que Kant hereda",
      body: "El recorrido de este curso deja dos herencias incompatibles. El racionalismo sostuvo que la razón conoce la realidad por sí sola, porque la realidad misma está racionalmente estructurada. El empirismo respondió que todo conocimiento viene de los sentidos, y que lo que la razón agrega por su cuenta no es conocimiento sino costumbre.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Kant hereda",
      body: "Cada posición tiene un costo. El racionalismo consigue verdades necesarias y universales, pero no puede justificar por qué esas verdades se aplican a las cosas. El empirismo se apoya en algo firme, la experiencia, pero al hacerlo pierde la necesidad: si la conexión causal es un hábito, entonces la física de Newton no es conocimiento estricto.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Kant hereda",
      body: "Hume había llevado esta segunda línea hasta el final. Al reducir la **conexión necesaria** a una expectativa producida por la repetición, dejó sin fundamento tanto a la metafísica racionalista como a la ciencia natural. Ese resultado es el punto de partida de **Immanuel Kant** (1724–1804).",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Kant hereda",
      body: "Kant reconoció esa deuda con una frase célebre. En los Prolegómenos a toda metafísica futura (1783) escribió que la lectura de Hume interrumpió su «sueño dogmático» y le dio a sus investigaciones una dirección completamente nueva. El escepticismo de Hume no lo convenció, pero lo obligó a replantear la pregunta.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Kant hereda",
      body: "La respuesta es la **Crítica de la razón pura**, publicada en 1781 y reescrita en una segunda edición en 1787. Kant vivió toda su vida en Königsberg, en la Prusia oriental, y publicó esta obra a los cincuenta y siete años, después de una década de silencio dedicada exclusivamente a prepararla.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Kant hereda",
      body: "El título indica el giro. No se trata de una crítica a la razón en el sentido de un ataque, sino de un examen que la razón hace de sí misma: qué puede conocer, con qué derecho y hasta dónde. Antes de responder qué es la realidad, Kant pregunta qué está en condiciones de conocer quien pregunta.",
    },
    {
      type: "quiz",
      question: "Al reducir la conexión causal a un hábito, Hume dejó sin fundamento…",
      options: [
        "la necesidad de las leyes de la ciencia natural",
        "la existencia de los objetos fuera de nuestra mente",
        "la validez de las demostraciones matemáticas",
        "la distinción entre impresiones e ideas simples",
      ],
      answer: 0,
      explain: "Si la conexión necesaria es sólo una expectativa producida por la repetición, las leyes de Newton dejan de ser conocimiento estricto. Ése es el resultado que Kant llamó su despertar del «sueño dogmático», y el que se propone revertir.",
    },
    {
      type: "classify",
      question: "¿Cada tesis corresponde al racionalismo o al empirismo?",
      groups: ["Racionalismo", "Empirismo"],
      items: [
        { text: "La razón porta ideas innatas que no vienen de los sentidos", group: 0 },
        { text: "El espíritu es una tabla rasa antes de la experiencia", group: 1 },
        { text: "La matemática es el modelo ideal de todo conocimiento", group: 0 },
        { text: "La metafísica plantea pseudoproblemas sin objeto sensible", group: 1 },
        { text: "La realidad misma está racionalmente estructurada", group: 0 },
        { text: "Todo conocimiento de hechos es a posteriori", group: 1 },
      ],
      explain: "Kant toma de cada tradición lo que le parece irrenunciable: del racionalismo, que hay conocimiento a priori; del empirismo, que sin experiencia no hay conocimiento de objetos. Su problema es explicar cómo pueden valer las dos cosas a la vez.",
    },
    {
      type: "info",
      title: "Los juicios sintéticos a priori",
      body: "Para formular su problema, Kant necesita dos distinciones. La primera es entre juicios **analíticos** y **sintéticos**. En un juicio analítico, el predicado ya está contenido en el sujeto: «todo cuerpo es extenso» no agrega nada, sólo explicita lo que «cuerpo» significa. En un juicio sintético, el predicado agrega información nueva.",
    },
    {
      type: "info",
      continues: true,
      title: "Los juicios sintéticos a priori",
      body: "La segunda distinción es entre juicios **a priori** y **a posteriori**. Un juicio a priori vale con independencia de la experiencia, y por eso es universal y necesario. Un juicio a posteriori depende de la experiencia, y por eso es particular y contingente. Esta distinción ya circulaba en el debate entre racionalistas y empiristas.",
    },
    {
      type: "info",
      continues: true,
      title: "Los juicios sintéticos a priori",
      body: "Cruzar las dos distinciones da tres casillas que nadie discutía. Los juicios analíticos a priori son las verdades de definición, informativamente vacías. Los sintéticos a posteriori son los enunciados empíricos, informativos pero contingentes. Los analíticos a posteriori no existen: si el predicado ya está en el sujeto, no hace falta mirar el mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "Los juicios sintéticos a priori",
      body: "Queda una cuarta casilla, y ahí está todo el problema. ¿Hay **juicios sintéticos a priori**, es decir, juicios que agreguen información nueva sobre el mundo y que sin embargo valgan necesariamente, sin depender de la experiencia?",
    },
    {
      type: "info",
      continues: true,
      title: "Los juicios sintéticos a priori",
      body: "Kant responde que sí, y que de hecho son los juicios que sostienen las dos ciencias más sólidas que existen. «7 + 5 = 12» no es analítico: el concepto de la suma de siete y cinco no contiene el concepto de doce, y sin embargo el juicio es necesario. La geometría entera funciona así.",
    },
    {
      type: "info",
      continues: true,
      title: "Los juicios sintéticos a priori",
      body: "La física también. «Todo cambio tiene una causa» agrega algo que el concepto de cambio no contiene, y no es una generalización de casos observados: nadie lo abandonaría porque apareciera un contraejemplo, se buscaría la causa oculta. Es un principio que la investigación presupone en vez de demostrar.",
    },
    {
      type: "info",
      continues: true,
      title: "Los juicios sintéticos a priori",
      body: "Entonces la pregunta de la Crítica no es si existen esos juicios, sino cómo son posibles. Y la pregunta importa porque de la respuesta depende si la metafísica —que pretende hacer juicios sintéticos a priori sobre Dios, el alma y el mundo— es una ciencia posible o una ilusión.",
    },
    {
      type: "quiz",
      question: "¿Cuál de estos juicios es sintético a priori?",
      options: [
        "Todo cambio tiene una causa",
        "Todo cuerpo es extenso",
        "El agua hierve a cien grados",
        "Los solteros no están casados",
      ],
      answer: 0,
      explain: "«Todo cuerpo es extenso» y «los solteros no están casados» son analíticos: el predicado ya está en el sujeto. «El agua hierve a cien grados» es sintético, pero a posteriori. «Todo cambio tiene una causa» agrega información y sin embargo no se abandona ante un contraejemplo: se busca la causa oculta.",
    },
    {
      type: "short",
      question: "¿Cómo llama Kant al juicio que agrega información nueva y aun así vale necesariamente?",
      answers: ["sintético a priori", "sintéticos a priori"],
      explain: "Es la cuarta casilla que resulta de cruzar las dos distinciones, y la única problemática. Explicar cómo son posibles esos juicios equivale a explicar cómo son posibles la matemática y la física.",
    },
    {
      type: "info",
      title: "El giro copernicano",
      body: "Kant explica su solución con una analogía que quedó como el nombre de su método. Antes de Copérnico se intentaba explicar el movimiento de los astros suponiendo que giraban alrededor del observador. Copérnico probó lo contrario: suponer que el observador se mueve y los astros están quietos. El problema se resolvió invirtiendo el supuesto.",
    },
    {
      type: "info",
      continues: true,
      title: "El giro copernicano",
      body: "La metafísica, dice Kant, está en la situación de la astronomía anterior a Copérnico. Siempre supuso que el conocimiento debe ajustarse al objeto, y sobre ese supuesto no se entiende cómo podríamos saber algo del objeto antes de encontrarlo. Si el conocimiento copia lo dado, todo conocimiento tendría que ser a posteriori.",
    },
    {
      type: "info",
      continues: true,
      title: "El giro copernicano",
      body: "La inversión consiste en probar el supuesto contrario: que el objeto, en cuanto objeto conocido, se ajusta a las condiciones del sujeto que lo conoce. No que las cosas dependan de nuestros deseos, sino que aquello que llamamos «objeto de experiencia» está estructurado por las formas con que lo recibimos y lo pensamos.",
    },
    {
      type: "info",
      continues: true,
      title: "El giro copernicano",
      body: "Si es así, los juicios sintéticos a priori quedan explicados. Podemos saber algo de todo objeto posible antes de encontrarlo, porque lo que sabemos no lo extrajimos del objeto: lo pusimos nosotros como condición para que algo pueda presentarse como objeto. El conocimiento a priori es conocimiento de nuestra propia forma de conocer.",
    },
    {
      type: "info",
      continues: true,
      title: "El giro copernicano",
      body: "Es importante ver qué tipo de tesis es ésta. Kant no está diciendo que el sujeto invente el contenido de la experiencia: el contenido viene de afuera, es dado. Lo que el sujeto aporta es la **forma**. La experiencia es siempre el resultado de una materia recibida y de una forma impuesta.",
    },
    {
      type: "quiz",
      question: "El giro copernicano consiste en suponer que…",
      options: [
        "el objeto se ajusta a las formas del sujeto",
        "el sujeto descubre leyes que ya rigen en las cosas",
        "el conocimiento copia la estructura de lo real",
        "las cosas dependen de lo que cada uno imagina",
      ],
      answer: 0,
      explain: "La inversión no dice que las cosas dependan de nuestros deseos: el contenido de la experiencia sigue viniendo de afuera. Lo que el sujeto aporta es la forma, y por eso podemos saber algo de todo objeto posible antes de encontrarlo.",
    },
    {
      type: "info",
      title: "Espacio y tiempo como formas de la sensibilidad",
      body: "La primera parte de la Crítica examina la sensibilidad, es decir, la capacidad de recibir lo dado. Kant sostiene que el **espacio** y el **tiempo** no son cosas, ni propiedades de las cosas, ni relaciones extraídas de la experiencia: son las formas puras con que toda intuición sensible se organiza.",
    },
    {
      type: "info",
      continues: true,
      title: "Espacio y tiempo como formas de la sensibilidad",
      body: "El argumento tiene una parte negativa. No podemos haber aprendido el espacio de la experiencia, porque cualquier experiencia de algo exterior lo presenta ya localizado; el espacio no es un dato entre otros, es la condición de que haya datos exteriores. Podemos imaginar un espacio vacío, pero no podemos representarnos la ausencia de espacio.",
    },
    {
      type: "info",
      continues: true,
      title: "Espacio y tiempo como formas de la sensibilidad",
      body: "De ahí se sigue por qué la geometría es sintética a priori. Sus proposiciones no son definiciones, porque agregan información, y no son empíricas, porque no admiten excepción. Valen necesariamente para todo objeto posible de la experiencia externa porque describen la forma que ese objeto tendrá inevitablemente al presentarse.",
    },
    {
      type: "info",
      continues: true,
      title: "Espacio y tiempo como formas de la sensibilidad",
      body: "Esta tesis resuelve además una vieja disputa. Newton había tratado el espacio como algo absoluto y real, casi como un receptáculo divino; Leibniz lo había reducido a un sistema de relaciones entre cosas. Kant dice que ninguna de las dos: es una forma del sujeto, y por eso vale objetivamente para los fenómenos sin ser una cosa.",
    },
    {
      type: "quiz",
      question: "Para Kant, el espacio y el tiempo son…",
      options: [
        "formas puras de nuestra intuición sensible",
        "las relaciones que los cuerpos guardan entre sí",
        "receptáculos reales en los que están las cosas",
        "conceptos que el entendimiento abstrae de la experiencia",
      ],
      answer: 0,
      explain: "La segunda opción es la posición de Leibniz y la tercera la de Newton; Kant rechaza las dos. Como el espacio es una forma del sujeto y no una cosa, la geometría puede ser sintética a priori: describe la forma que todo objeto tendrá al presentarse.",
    },
    {
      type: "info",
      title: "Las categorías del entendimiento",
      body: "La sensibilidad sola no produce conocimiento. Recibir impresiones no es todavía juzgar. Hace falta el **entendimiento**, que unifica lo dado bajo conceptos. Kant condensa la relación entre las dos facultades en una fórmula que vale como resumen de todo su proyecto.",
    },
    {
      type: "info",
      continues: true,
      title: "Las categorías del entendimiento",
      body: "«Los pensamientos sin contenido son vacíos, las intuiciones sin conceptos son ciegas.» El racionalismo se quedó con la primera mitad: conceptos que operan sin intuición y producen construcciones vacías. El empirismo se quedó con la segunda: intuiciones sin estructura conceptual, que no llegan a ser conocimiento de nada.",
    },
    {
      type: "info",
      continues: true,
      title: "Las categorías del entendimiento",
      body: "Las **categorías** son los conceptos puros del entendimiento, los que no vienen de la experiencia sino que la hacen posible. Kant deriva doce, ordenadas en cuatro grupos: cantidad, cualidad, relación y modalidad. Entre las de relación está la que interesa especialmente a este recorrido, la de **causa y efecto**.",
    },
    {
      type: "info",
      continues: true,
      title: "Las categorías del entendimiento",
      body: "Acá está la respuesta a Hume, y conviene formularla con precisión. Hume tenía razón en un punto: la conexión necesaria no se encuentra en las impresiones. Kant acepta eso por completo. Lo que niega es la conclusión de que entonces la causalidad sea sólo un hábito psicológico.",
    },
    {
      type: "info",
      continues: true,
      title: "Las categorías del entendimiento",
      body: "La causalidad no está en la experiencia porque es una de las condiciones que hacen que haya experiencia objetiva. Sin ella no tendríamos una sucesión de percepciones desordenadas, sino que no tendríamos experiencia de un mundo en absoluto: no habría diferencia entre el orden de nuestras representaciones y el orden de los acontecimientos.",
    },
    {
      type: "info",
      continues: true,
      title: "Las categorías del entendimiento",
      body: "Es decir: Hume buscó la causalidad en el lugar equivocado. La buscó entre los contenidos de la experiencia, cuando pertenece a su forma. Y una forma no se prueba señalándola entre los datos, se prueba mostrando que sin ella los datos no constituirían experiencia alguna. Ése es el tipo de argumento que Kant llama **trascendental**.",
    },
    {
      type: "quiz",
      question: "¿Cómo responde Kant a la objeción de Hume sobre la causalidad?",
      options: [
        "Es una condición de la experiencia, no un dato",
        "La repetición constante sí prueba la conexión necesaria",
        "La causalidad se percibe en las impresiones mismas",
        "Es un hábito útil pero sin ningún valor objetivo",
      ],
      answer: 0,
      explain: "Kant le concede a Hume que la conexión necesaria no se encuentra entre las impresiones. Lo que niega es la conclusión: no está en la experiencia porque pertenece a su forma. Sin la categoría de causa no tendríamos percepciones desordenadas, no tendríamos experiencia de un mundo.",
    },
    {
      type: "quiz",
      question: "«Las intuiciones sin conceptos son ciegas» significa que…",
      options: [
        "recibir impresiones no es todavía conocer nada",
        "los sentidos engañan salvo que la razón los corrija",
        "sin experiencia sensible los conceptos quedan vacíos",
        "el entendimiento conoce sin ayuda de los sentidos",
      ],
      answer: 0,
      explain: "La fórmula tiene dos mitades y cada una apunta a una tradición. «Los pensamientos sin contenido son vacíos» va contra el racionalismo, que opera con conceptos sin intuición; «las intuiciones sin conceptos son ciegas», contra el empirismo, que se queda con datos sin estructura. La tercera opción es la otra mitad de la cita.",
    },
    {
      type: "info",
      title: "Fenómeno y cosa en sí",
      body: "El giro copernicano tiene un precio, y Kant lo paga explícitamente. Si los objetos que conocemos están estructurados por nuestras formas, entonces no conocemos las cosas tal como son con independencia de nosotros. Conocemos **fenómenos**: las cosas tal como se nos aparecen bajo las condiciones de nuestra sensibilidad y nuestro entendimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenómeno y cosa en sí",
      body: "Lo que las cosas sean en sí mismas, al margen de esas condiciones, queda fuera del alcance del conocimiento. Kant llama a eso la **cosa en sí** o el **noumenon**. No es un objeto misterioso escondido detrás del fenómeno: es el concepto límite que marca hasta dónde llega nuestra facultad de conocer.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenómeno y cosa en sí",
      body: "Hay que evitar dos malentendidos frecuentes. Esto no es escepticismo: el conocimiento de fenómenos es conocimiento estricto, objetivo y necesario, no una conjetura. Y no es idealismo subjetivo al modo de Berkeley: los fenómenos no son ideas en una mente, son objetos reales para todo sujeto con nuestra constitución.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenómeno y cosa en sí",
      body: "La fórmula que resume el resultado es que el conocimiento es objetivo pero limitado. Objetivo, porque las condiciones que lo estructuran no son las de un individuo sino las de cualquier sujeto racional finito. Limitado, porque sólo alcanza a lo que puede darse en una experiencia posible.",
    },
    {
      type: "quiz",
      question: "La cosa en sí es…",
      options: [
        "un concepto que marca el límite del conocer",
        "un objeto oculto detrás de lo que percibimos",
        "la idea de Dios en su uso puramente regulativo",
        "aquello que sólo la intuición intelectual alcanza",
      ],
      answer: 0,
      explain: "El error frecuente es imaginarla como un objeto escondido tras el fenómeno. No es un objeto: es el concepto que marca hasta dónde llega nuestra facultad de conocer. Y la limitación no es escepticismo, porque el conocimiento de fenómenos es estricto y objetivo.",
    },
    {
      type: "classify",
      question: "¿Cada tesis es de Kant o de Berkeley?",
      groups: ["Kant", "Berkeley"],
      items: [
        { text: "Hay algo dado desde fuera que la sensibilidad recibe", group: 0 },
        { text: "Existir es ser percibido por alguna mente", group: 1 },
        { text: "La materia es una hipótesis innecesaria", group: 1 },
        { text: "Conocemos los fenómenos, no la cosa en sí", group: 0 },
        { text: "Los objetos de experiencia son reales para todo sujeto", group: 0 },
        { text: "Las cosas sólo existen mientras alguien las percibe", group: 1 },
      ],
      explain: "Kant insistió en separar su idealismo trascendental del de Berkeley, que le parecía subjetivo. Para Berkeley no hay materia y los objetos son ideas en una mente; para Kant hay algo dado que la sensibilidad recibe, y los fenómenos son objetos reales para cualquier sujeto con nuestra constitución.",
    },
    {
      type: "info",
      title: "La crítica de la metafísica racionalista",
      body: "De esa limitación se sigue la consecuencia más destructiva de la Crítica. Si el conocimiento vale sólo dentro de la experiencia posible, entonces la metafísica racionalista, que pretende conocer objetos que por definición no pueden darse en ninguna experiencia, no es una ciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "La crítica de la metafísica racionalista",
      body: "Kant examina tres de esos objetos, que corresponden a las tres disciplinas de la metafísica de su época: el alma, el mundo como totalidad y Dios. En cada caso muestra que la razón, al intentar conocerlos, no llega a conclusiones falsas por descuido sino que cae en errores estructurales, inevitables.",
    },
    {
      type: "info",
      continues: true,
      title: "La crítica de la metafísica racionalista",
      body: "Sobre el alma, la razón razona mal sin advertirlo: del hecho de que todo pensamiento vaya acompañado de un «yo pienso» concluye que existe una substancia pensante simple e inmortal. Pero ese «yo pienso» es la forma de toda representación, no un objeto dado; tratarlo como objeto es un paso ilegítimo.",
    },
    {
      type: "info",
      continues: true,
      title: "La crítica de la metafísica racionalista",
      body: "Sobre el mundo como totalidad, la razón produce **antinomias**: pares de tesis opuestas, cada una con una demostración aparentemente válida. Se puede probar que el mundo tuvo un comienzo en el tiempo y que no lo tuvo, que hay libertad y que todo está determinado. La contradicción indica que la pregunta está mal planteada.",
    },
    {
      type: "info",
      continues: true,
      title: "La crítica de la metafísica racionalista",
      body: "Sobre Dios, Kant desmonta las pruebas de su existencia, y en particular la prueba ontológica que Descartes había usado como pieza central. El argumento es simple y demoledor: la existencia no es un predicado que se agregue al concepto de una cosa. Cien monedas pensadas y cien monedas reales tienen el mismo concepto.",
    },
    {
      type: "info",
      continues: true,
      title: "La crítica de la metafísica racionalista",
      body: "El resultado no es ateísmo ni la abolición de esas ideas. El alma, el mundo y Dios sobreviven como **ideas de la razón**, con un uso legítimo pero distinto: no constituyen objetos de conocimiento, orientan la investigación y sostienen la vida moral. Kant escribió que tuvo que limitar el saber para dejar lugar a la fe.",
    },
    {
      type: "quiz",
      question: "¿Por qué rechaza Kant la prueba ontológica de la existencia de Dios?",
      options: [
        "Porque la existencia no es un predicado de la cosa",
        "Porque parte de un concepto que nadie puede formarse",
        "Porque confunde la causa primera con el ser perfecto",
        "Porque ninguna prueba de la existencia de Dios es válida",
      ],
      answer: 0,
      explain: "Cien monedas pensadas y cien monedas reales tienen el mismo concepto: la existencia no agrega nada al concepto de una cosa, así que no puede extraerse de él. Kant rechaza también las otras pruebas, pero por razones distintas, no porque toda prueba sea inválida por principio.",
    },
    {
      type: "short",
      question: "¿Cómo llama Kant a los pares de tesis opuestas que la razón puede demostrar por igual?",
      answers: ["antinomias", "antinomia"],
      explain: "Se puede probar que el mundo tuvo un comienzo en el tiempo y que no lo tuvo, que hay libertad y que todo está determinado. Para Kant la contradicción no delata un error de cálculo: indica que la pregunta está mal planteada, porque aplica al mundo como totalidad una categoría que sólo vale dentro de la experiencia.",
    },
    {
      type: "info",
      title: "Qué cierra y qué abre",
      body: "Con esto se completa un arco que empezó en el siglo XVII. Descartes había buscado la certeza en el sujeto pero necesitó a Dios para garantizar que sus ideas correspondieran al mundo. Kant se queda con el sujeto y descarta la garantía: la correspondencia no hay que probarla, porque el objeto de la experiencia se constituye según las formas del sujeto.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué cierra y qué abre",
      body: "Frente a Leibniz, Kant conserva lo a priori pero le quita su pretensión de conocer substancias. Frente a Hume, salva la necesidad de la ciencia natural pero paga el precio de que esa necesidad valga sólo para los fenómenos. La física de Newton queda fundada; la metafísica tradicional, desalojada.",
    },
    {
      type: "match",
      question: "Uní cada pieza de la Crítica con lo que establece",
      pairs: [
        { left: "Estética trascendental", right: "El espacio y el tiempo como formas de la sensibilidad" },
        { left: "Analítica trascendental", right: "Las categorías y su aplicación legítima" },
        { left: "Dialéctica trascendental", right: "Las ilusiones de la razón sobre el alma, el mundo y Dios" },
        { left: "Giro copernicano", right: "El objeto se ajusta a las formas del sujeto" },
      ],
      explain: "Las tres partes del libro responden en cadena a la pregunta por los juicios sintéticos a priori: la sensibilidad aporta las formas de la intuición, el entendimiento las categorías, y la dialéctica muestra qué ocurre cuando esas categorías se usan fuera de la experiencia posible.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué cierra y qué abre",
      body: "Y se abre lo que viene. Una obra que hace de la razón el tribunal de todo lo que puede saberse es también el blanco perfecto para quien sospeche de ese tribunal. Cuatro años después de la Crítica, en el mismo Königsberg, alguien iba a preguntar con qué derecho la razón se juzga a sí misma sin recurrir a nada más.",
    },
  ],
};
