export default {
  num: 4,
  transcript: 4,
  title: "Mecanicismo y geometría moral: Pascal y Spinoza",
  source: "",
  feed: [
    {
      type: "info",
      title: "El mecanicismo del siglo XVII",
      body: "La filosofía natural del siglo XVII representa la naturaleza como una gran maquinaria: por eso se la llama **mecanicista**. Descartes, Hobbes, Gassendi, Boyle o Newton comparten esta imagen, pero no sus consecuencias: para Descartes el mecanicismo vale sólo para la materia, no para el pensamiento; Hobbes, en cambio, lo extiende a toda la realidad, incluida la mente humana.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanicismo del siglo XVII",
      body: "Como concepción filosófica, el mecanicismo entiende la naturaleza como un cuerpo infinito o un conjunto infinito de cuerpos elementales, carentes de fuerza propia, movidos únicamente por el choque con otros cuerpos. Esto excluye la **teleología** física de los antiguos: sólo son objetivas las propiedades cuantitativas de los cuerpos, mientras que colores, sonidos y sabores dependen de cómo los captan nuestros sentidos.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanicismo del siglo XVII",
      body: "El término «mecanicismo» es, sin embargo, ambiguo. Gassendi y Boyle explican mecánicamente el movimiento de cuerpos compuestos de corpúsculos o átomos indivisibles que se mueven en el vacío. Descartes, en cambio, sostiene que la materia es homogénea y continua, sin espacios vacíos entre sus partes: dos maneras distintas de imaginar la misma máquina universal.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanicismo del siglo XVII",
      body: "Algunos científicos formulan leyes mecánicas para explicar fenómenos naturales sin comprometerse con ninguna ontología: usan el mecanicismo como método, no como tesis sobre lo que en el fondo es real. Por eso conviene distinguir el mecanicismo como explicación científica de acontecimientos naturales según leyes de la mecánica, del mecanicismo como concepción filosófica de toda la realidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanicismo del siglo XVII",
      body: "Frente a esta generalización de la idea de máquina, los filósofos del siglo XVII reaccionan de maneras opuestas. Dos casos extremos permiten verlo con claridad: **Blaise Pascal** (1623–1662), que advierte sus límites, y **Baruch Spinoza** (1632–1677), que la lleva hasta sus últimas consecuencias en una ética construida con el método de la geometría.",
    },
    {
      type: "quiz",
      question: "¿Qué diferencia a Gassendi de Descartes dentro del mecanicismo?",
      options: [
        "Gassendi acepta átomos en el vacío, Descartes no",
        "Gassendi niega el movimiento, Descartes lo afirma",
        "Gassendi es teleólogo, Descartes es mecanicista",
        "Gassendi estudia la mente, Descartes sólo la materia",
      ],
      answer: 0,
      explain: "Gassendi y Boyle explican los cuerpos como átomos que se mueven en el vacío; Descartes sostiene que la materia es continua y homogénea, sin espacios vacíos: dos versiones distintas de la misma imagen mecanicista.",
    },
    {
      type: "info",
      title: "El espíritu de sutileza de Pascal",
      body: "Pascal reconoce las ventajas de la física matemática, pero advierte un peligro: aplicada sin límites, deja al ser humano sin ninguna clave para el sentido de su propia existencia. El orden medieval ubicaba a la persona en un cosmos cerrado, protegido por esferas celestes; la nueva física describe en cambio un universo infinito e indiferente.",
    },
    {
      type: "info",
      continues: true,
      title: "El espíritu de sutileza de Pascal",
      body: "Por eso Pascal distingue dos modos de comprensión. El **espíritu geométrico** sirve para conocer relaciones cuantitativas necesarias, pero es incapaz de aprehender el sentido de la existencia individual, la que cada uno vive en primera persona. Esa dimensión requiere del **espíritu de sutileza**, un modo de comprensión distinto, no reductible al cálculo.",
    },
    {
      type: "info",
      continues: true,
      title: "El espíritu de sutileza de Pascal",
      body: "Pascal no habla desde afuera de la nueva ciencia: fue matemático y físico antes que apologista de la fe, autor de trabajos sobre las cónicas, la presión de los fluidos y el cálculo de probabilidades. Su advertencia tiene, por eso, un peso especial: no rechaza el método geométrico por ignorancia de sus alcances, sino por haberlos explorado hasta el límite.",
    },
    {
      type: "info",
      continues: true,
      title: "El espíritu de sutileza de Pascal",
      body: "En los Pensamientos (1670), Pascal pone esta angustia en boca del hombre sin fe, perdido en un universo que ya no lo mira: «Veo esos aterradores espacios del universo que me encierran y me encuentro adherido a un rincón de esa vasta extensión, sin saber por qué estoy colocado en este lugar y no en otro […]. Sólo veo infinitudes por todas partes» (Pascal, Pensamientos, ed. Brunschvicg n.º 194).",
    },
    {
      type: "info",
      continues: true,
      title: "El espíritu de sutileza de Pascal",
      body: "Para Pascal, sólo la fe puede darle sentido a una existencia que la física matematizada ha vuelto radicalmente contingente: un átomo, una sombra que dura un instante entre dos eternidades. El espíritu geométrico describe el universo; sólo el espíritu de sutileza, y en última instancia la fe, puede orientar una vida dentro de él.",
    },
    {
      type: "info",
      continues: true,
      title: "El espíritu de sutileza de Pascal",
      body: "La advertencia de Pascal anticipa, en pleno siglo XVII, una preocupación que reaparecerá en la filosofía existencialista del siglo XX: la de un sujeto que conoce con precisión creciente las leyes del universo físico, pero que no encuentra en ellas ninguna respuesta sobre el sentido de su propia existencia individual.",
    },
    {
      type: "quiz",
      question: "Para Pascal, el espíritu de sutileza es necesario porque…",
      options: [
        "el geométrico no explica el sentido de existir",
        "el geométrico quedó superado por la física moderna",
        "los sentidos engañan y sólo la fe corrige el error",
        "las verdades matemáticas resultan poco confiables",
      ],
      answer: 0,
      explain: "El espíritu geométrico conoce relaciones cuantitativas necesarias, pero no alcanza el sentido de la existencia individual, que cada uno vive en primera persona; para eso Pascal reserva el espíritu de sutileza.",
    },
    {
      type: "short",
      question: "¿Cómo llama Pascal al modo de comprensión, distinto del cálculo, que capta el sentido de la existencia individual?",
      answers: ["espíritu de sutileza", "espiritu de sutileza"],
      explain: "Frente al espíritu geométrico, que conoce relaciones cuantitativas, Pascal reserva el espíritu de sutileza para captar de un solo golpe realidades que no se dejan calcular, como el sentido de la propia existencia.",
    },
    {
      type: "info",
      title: "La ética more geometrico de Spinoza",
      body: "En el extremo opuesto, Spinoza propone generalizar el método geométrico a toda la realidad, incluida la conducta humana, como único camino hacia la felicidad. Su obra principal, la Ética (1677), está escrita con la estructura de un tratado de geometría: demuestra proposiciones a partir de definiciones, axiomas y postulados, tal como los físicos habían aplicado ese método al estudio de la naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética more geometrico de Spinoza",
      body: "Spinoza no busca ante todo describir la realidad, sino alcanzar el verdadero bien: en el Tratado de la reforma del entendimiento sostiene que consiste en «comprender la relación que el alma tiene con toda la naturaleza». El conocimiento racional de esa relación —entre el yo finito y la naturaleza infinita— es, para Spinoza, la clave de la felicidad.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética more geometrico de Spinoza",
      body: "Esa relación es exactamente la que en el pasaje citado de Pascal aparecía como un abismo: un yo aislado y una naturaleza infinita, indiferentes entre sí. Donde Pascal ve dos términos heterogéneos que sólo la fe puede vincular, Spinoza ve una relación objetiva, cognoscible mediante el método geométrico, cuyo desconocimiento es la única causa de la infelicidad humana.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética more geometrico de Spinoza",
      body: "Spinoza distingue dos formas de entender esa relación. La incorrecta, dependiente de la imaginación y los prejuicios, concibe al ser humano como «un imperio dentro de otro imperio»: un agente que se cree dueño absoluto de sus acciones y ajeno a las leyes naturales (Spinoza, Ética, III, Prefacio, 1677). La correcta se alcanza mediante el método geométrico.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética more geometrico de Spinoza",
      body: "Creemos que nuestras acciones no siguen necesariamente de causas naturales previas, sino que nacen de una voluntad arbitraria capaz de proponerse cualquier fin. Imaginamos así que intervenimos desde fuera del orden natural y lo perturbamos. Para Spinoza, esta creencia en el libre albedrío es la ilusión central que hay que superar.",
    },
    {
      type: "quiz",
      question: "Que Spinoza describa al ser humano como «un imperio dentro de otro imperio» critica la idea de que…",
      options: [
        "tenemos una voluntad libre de causas naturales",
        "el alma humana existe separada del cuerpo",
        "el conocimiento matemático describe la realidad",
        "Dios creó el mundo por un acto arbitrario",
      ],
      answer: 0,
      explain: "Para Spinoza, creer que actuamos con un poder absoluto sobre nuestras acciones, ajeno a las leyes naturales, es la ilusión que describe como «un imperio dentro de otro imperio»: en realidad, todo modo se sigue necesariamente de la sustancia.",
    },
    {
      type: "info",
      title: "La sustancia única",
      body: "El método geométrico permite comprender que los seres humanos no son un imperio dentro de otro imperio, sino que están integrados en una totalidad única. Spinoza sostiene que sólo existe una **sustancia**, «Dios o la naturaleza» (Deus sive natura), y que todo lo que sucede en ella está determinado necesariamente según un orden necesario: el de las leyes naturales.",
    },
    {
      type: "info",
      continues: true,
      title: "La sustancia única",
      body: "Esa sustancia única expresa su esencia en infinitos atributos, de los cuales el entendimiento humano capta solamente dos: la extensión y el pensamiento. Todo lo que ocurre en la sustancia se llama **modo**: los cuerpos físicos son modos captados según el atributo de la extensión, y las ideas de esos cuerpos son los mismos modos captados según el atributo del pensamiento.",
    },
    {
      type: "info",
      continues: true,
      title: "La sustancia única",
      body: "De ahí se sigue que ni el alma ni el cuerpo son sustancias independientes: son el mismo modo, concebido «ya bajo el atributo del pensamiento, ya bajo el atributo de la extensión» (Spinoza, Ética, II, 21, escolio, 1677). Por eso los afectos y la conducta humana están determinados por leyes naturales, igual que cualquier otro acontecimiento de la naturaleza: no hay excepción posible.",
    },
    {
      type: "info",
      continues: true,
      title: "La sustancia única",
      body: "Esta tesis es la formulación más radical del **determinismo** en la filosofía moderna: todo lo que existe se sigue necesariamente de la naturaleza de la sustancia única, del mismo modo en que un teorema se sigue de sus axiomas. Nada en la realidad podría haber sido de otra manera, ni siquiera las acciones humanas que solemos atribuir a una voluntad libre.",
    },
    {
      type: "quiz",
      question: "¿Por qué el pensamiento y la extensión no son, para Spinoza, dos sustancias distintas?",
      options: [
        "son dos atributos de una sola sustancia",
        "porque el pensamiento no existe realmente",
        "porque sólo la extensión es objetiva",
        "porque Dios los creó por separado",
      ],
      answer: 0,
      explain: "Spinoza sostiene que sólo existe una sustancia infinita, expresada en infinitos atributos; el entendimiento humano capta sólo dos, extensión y pensamiento, que son maneras distintas de captar los mismos modos.",
    },
    {
      type: "info",
      title: "El conatus y la persistencia en el ser",
      body: "Cada modo particular, sea un cuerpo o una idea, tiene según Spinoza una tendencia a perseverar en su propio ser, a resistir aquello que amenaza con destruirlo. A esa tendencia la llama **conatus**: el esfuerzo por el cual cada cosa persiste en su existencia todo el tiempo que está en su poder.",
    },
    {
      type: "info",
      continues: true,
      title: "El conatus y la persistencia en el ser",
      body: "El conatus no es un fin que las cosas persigan libremente, sino la esencia misma actual de cada modo: lo que un cuerpo o una mente son, en tanto se resisten a dejar de ser. En los seres humanos, este esfuerzo se manifiesta como deseo cuando es consciente y como apetito cuando no lo es, y de él derivan todos los afectos que Spinoza analiza en la Ética.",
    },
    {
      type: "info",
      continues: true,
      title: "El conatus y la persistencia en el ser",
      body: "El conatus permite entender por qué Spinoza rechaza la idea de un libre albedrío arbitrario sin caer en el fatalismo o la resignación: perseverar en el propio ser, aumentar la propia potencia de actuar mediante el conocimiento racional, es la forma spinozista de la libertad, aunque esa libertad esté ella misma necesariamente determinada por la naturaleza de la sustancia.",
    },
    {
      type: "info",
      continues: true,
      title: "El conatus y la persistencia en el ser",
      body: "Cuanto más adecuado es el conocimiento que un modo tiene de sus propias causas, más activo y menos pasivo es: pasa de estar dominado por afectos que lo determinan desde fuera —el miedo, la esperanza, el odio— a comprender racionalmente su propio lugar en la sustancia única. Esa transición, y no la ilusión de un libre albedrío arbitrario, es lo que Spinoza llama libertad humana.",
    },
    {
      type: "short",
      question: "¿Cómo llama Spinoza al esfuerzo por el cual cada cosa persevera en su propio ser?",
      answers: ["conatus"],
      explain: "El conatus es la esencia actual de cada modo: el esfuerzo por seguir existiendo. En los seres humanos se manifiesta como deseo o apetito, y de él derivan, para Spinoza, todos los afectos.",
    },
    {
      type: "quiz",
      question: "Para Spinoza, alguien es más libre cuanto más…",
      options: [
        "comprende las causas de sus propios actos",
        "logra actuar sin ninguna causa que lo determine",
        "se aparta de las leyes de la naturaleza",
        "obedece los mandatos de su propia voluntad arbitraria",
      ],
      answer: 0,
      explain: "La libertad spinozista no es ausencia de causas, sino conocimiento adecuado de ellas: cuanto más comprendemos racionalmente nuestro lugar en la sustancia, menos determinados estamos por afectos pasivos externos.",
    },
    {
      type: "info",
      title: "Por qué confiar en el método geométrico",
      body: "Spinoza da dos razones para confiar en el método geométrico como vía de conocimiento de la relación entre el ser humano y la naturaleza. La primera es teológica: a diferencia del Dios judeocristiano, que crea el mundo por un acto de voluntad arbitraria que podría no haber ocurrido, el Dios de Spinoza es una sustancia cuya naturaleza necesaria produce todos los modos con la misma necesidad con que un teorema se sigue de sus axiomas.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué confiar en el método geométrico",
      body: "Esta primera razón es metafísica, no sólo metodológica: si la sustancia misma se comporta con necesidad lógica, entonces el método que mejor capta relaciones necesarias —la geometría, no la observación empírica ni la retórica— es también el que mejor se ajusta a la estructura real del mundo que se quiere conocer.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué confiar en el método geométrico",
      body: "La segunda razón tiene que ver con el rechazo de la **teleología**. La mecánica moderna renuncia a estudiar fines o propósitos y sólo admite causas eficientes, siempre anteriores a sus efectos. Spinoza radicaliza esta renuncia y la convierte en principio metodológico general: los geómetras no preguntan para qué existen las cosas, sólo de qué causas se siguen necesariamente.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué confiar en el método geométrico",
      body: "Otros filósofos del período conservan la teleología para ámbitos específicos —Leibniz la reserva para el estudio metafísico de las sustancias simples o mónadas—, pero Spinoza la elimina por completo. Para él, el prejuicio teleológico es el obstáculo fundamental que impide comprender racionalmente que estamos integrados en una cadena de causas necesarias.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué confiar en el método geométrico",
      body: "Al eliminar los fines de la explicación de la naturaleza, Spinoza también elimina la pregunta por el «para qué» de la existencia humana que angustiaba a Pascal. Donde Pascal ve un vacío que sólo la fe puede llenar, Spinoza ve una liberación: comprender que no hay fines ocultos es, para él, el primer paso hacia la verdadera felicidad.",
    },
    {
      type: "quiz",
      question: "La física mecánica moderna renuncia a la teleología porque…",
      options: [
        "sólo admite causas eficientes, anteriores a sus efectos",
        "considera que los fines son más importantes que las causas",
        "niega que los cuerpos tengan cualquier tipo de causa",
        "sólo estudia fenómenos morales, no físicos",
      ],
      answer: 0,
      explain: "La mecánica moderna estudia únicamente causas eficientes —anteriores en el tiempo a sus efectos— y renuncia a preguntar para qué ocurren las cosas. Spinoza radicaliza esa renuncia y la extiende a toda la metafísica.",
    },
    {
      type: "classify",
      question: "¿Cada posición es de Pascal o de Spinoza?",
      groups: ["Pascal", "Spinoza"],
      items: [
        { text: "Advierte que el espíritu geométrico no basta para vivir", group: 0 },
        { text: "Aplica el método geométrico a la ética humana", group: 1 },
        { text: "Encuentra el sentido de la existencia en la fe", group: 0 },
        { text: "Sostiene que no hay fines ocultos en la naturaleza", group: 1 },
        { text: "Se describe como un átomo perdido en el infinito", group: 0 },
        { text: "Busca la felicidad en el conocimiento de la necesidad", group: 1 },
      ],
      explain: "Pascal y Spinoza reaccionan de manera opuesta a la matematización del mundo: Pascal encuentra sus límites y busca el sentido fuera de la geometría, en la fe; Spinoza la extiende a la ética entera y halla en ella el camino a la felicidad.",
    },
    {
      type: "info",
      title: "El prejuicio teleológico y la libertad",
      body: "En el apéndice de la primera parte de la Ética, Spinoza explica cómo nace el prejuicio teleológico: los seres humanos actúan siempre con vistas a un fin y, como nacen ignorantes de las causas de las cosas, suponen que también la naturaleza entera —y Dios mismo— actúa por fines, incluso que todo fue creado en vista del ser humano.",
    },
    {
      type: "info",
      continues: true,
      title: "El prejuicio teleológico y la libertad",
      body: "Cuando la experiencia contradice ese prejuicio —cuando los beneficios y las desgracias caen indistintamente sobre piadosos e impíos— los seres humanos no lo abandonan: prefieren remitir lo inexplicado a la voluntad insondable de los dioses antes que revisar todo su modo de pensar. Así el prejuicio teleológico se perpetúa y engendra, a su vez, nuevos prejuicios sobre el orden del mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "El prejuicio teleológico y la libertad",
      body: "De esta concepción se sigue una idea de libertad muy distinta de la del sentido común: no consiste en actuar sin causas, sino en ser causa adecuada de las propias acciones a partir de la propia naturaleza, en vez de estar determinado desde fuera por afectos pasivos. Para Spinoza, la libertad no se opone a la necesidad natural: se realiza dentro de ella, mediante el conocimiento racional que la Ética se propone enseñar.",
    },
    {
      type: "quiz",
      question: "Según Spinoza, los seres humanos creen que la naturaleza tiene fines porque…",
      options: [
        "proyectan en la naturaleza su modo de obrar",
        "la ciencia todavía no explica las causas eficientes",
        "Dios se los reveló directamente en las Escrituras",
        "la experiencia siempre confirma que hay un plan divino",
      ],
      answer: 0,
      explain: "Spinoza explica el prejuicio teleológico por analogía: como los seres humanos actúan siempre con vistas a un fin, suponen que también la naturaleza —y Dios— actúan así, aunque la experiencia muestre lo contrario.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada término con su idea",
      pairs: [
        { left: "Pascal", right: "Advierte los límites del espíritu geométrico" },
        { left: "Spinoza", right: "Aplica la geometría a la ética y la naturaleza" },
        { left: "Conatus", right: "El esfuerzo por perseverar en el propio ser" },
        { left: "Sustancia única", right: "Dios o la naturaleza, causa de sí misma" },
        { left: "Teleología", right: "Explicar por fines, algo que Spinoza rechaza" },
      ],
      explain: "Cinco piezas centrales de la clase: Pascal marca el límite del método geométrico, Spinoza lo extiende a toda la realidad mediante la sustancia única y el conatus, y rechaza la teleología como el prejuicio que hay que superar.",
    },
    {
      type: "info",
      continues: true,
      title: "El prejuicio teleológico y la libertad",
      body: "Pascal y Spinoza representan así dos respuestas contrapuestas al mismo desafío: qué lugar le queda al ser humano en un universo descrito por completo mediante leyes mecánicas y geométricas. Pascal encuentra ese lugar fuera de la geometría, en la fe; Spinoza lo encuentra dentro de ella, en el conocimiento racional de la propia necesidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El prejuicio teleológico y la libertad",
      body: "Esta oposición seguirá atravesando la filosofía moderna: la pregunta por si la razón geométrica alcanza para explicar la totalidad de lo humano, o si hay una dimensión de la existencia —el sentido, la libertad, la fe— que excede necesariamente ese método, reaparecerá bajo formas nuevas en el racionalismo y el empirismo de las clases siguientes.",
    },
  ],
};
