export default {
  num: 6,
  transcript: 6,
  title: "Del estado de naturaleza al contrato",
  source: "",
  feed: [
    {
      type: "info",
      title: "El vocabulario contractualista",
      body: "La clase anterior presentó a Hobbes y a Locke como los grandes teóricos modernos del individuo: Hobbes en el Leviatán (1651) y Locke en los Dos tratados sobre el gobierno civil (1689), leídos por Macpherson bajo la clave del individualismo posesivo. Esta clase retoma a ambos para examinar de cerca el argumento que comparten —el contrato— y lo completa con un tercer autor, Jean-Jacques Rousseau.",
    },
    {
      type: "info",
      continues: true,
      title: "El vocabulario contractualista",
      body: "Los tres pertenecen a la tradición del **derecho natural** moderno que ya se mencionó a propósito de Grocio: parten de un **estado de naturaleza** hipotético, anterior a toda sociedad organizada, y derivan de él, mediante un **contrato social**, los derechos y los límites del poder político.",
    },
    {
      type: "info",
      continues: true,
      title: "El vocabulario contractualista",
      body: "La secuencia Hobbes–Locke–Rousseau cubre poco más de un siglo, de 1651 a 1762, y en ese lapso el contractualismo cambia de sentido en cada autor según qué problema busca resolver. Un mismo vocabulario —naturaleza, contrato, soberanía— sirve para argumentos casi opuestos entre sí.",
    },
    {
      type: "quiz",
      question: "¿Qué comparten Hobbes, Locke y Rousseau?",
      options: [
        "un estado de naturaleza hipotético y un pacto",
        "la misma idea del hombre antes de la sociedad",
        "la conclusión de que el poder debe ser limitado",
        "el rechazo del derecho natural moderno",
      ],
      answer: 0,
      explain: "Comparten el punto de partida y el método, no las conclusiones. El mismo vocabulario —naturaleza, contrato, soberanía— sirve en los tres casos a argumentos casi opuestos, según qué problema cada uno busca resolver.",
    },
    {
      type: "info",
      title: "Hobbes: el contrato como salida del miedo",
      body: "Para Hobbes, el estado de naturaleza es un estado de guerra de todos contra todos. No hace falta que la guerra sea permanente: basta con que no exista una autoridad común capaz de garantizar la paz para que cada uno viva bajo la amenaza constante de la violencia ajena.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "En ese estado no hay propiedad segura, ni industria, ni cultivo, porque nadie puede confiar en gozar del fruto de su trabajo. La vida, en la fórmula célebre del Leviatán, es solitaria, pobre, tosca, embrutecida y breve: no por maldad de nadie en particular, sino por la estructura misma de la situación.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "La causa de ese conflicto no es la maldad humana, sino la igualdad: todos los seres humanos son, en sus facultades naturales, lo bastante parecidos como para que cualquiera pueda matar a cualquiera, incluso al más fuerte, si actúa con astucia o se alía con otros.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "De esa igualdad de capacidades surge una igualdad de esperanzas de alcanzar los mismos fines, y de ahí la competencia, la desconfianza y el afán de gloria: las tres causas de discordia que Hobbes enumera. Ninguna de las tres exige mala voluntad; basta la racionalidad de cada uno persiguiendo sus propios fines en un contexto sin garantías.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "El estado de naturaleza hobbesiano no es, entonces, un estado de derechos garantizados, sino todo lo contrario: cada uno tiene derecho a todo, incluido el cuerpo del otro, y esa misma universalidad del derecho es la que produce la inseguridad de todos.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "La única salida racional es contractual: los individuos renuncian a su derecho ilimitado y lo transfieren a un soberano común, que concentra el poder suficiente para infundir el temor que antes faltaba entre iguales sin autoridad que los gobernara.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "Ese pacto no es entre los súbditos y el soberano, sino de los súbditos entre sí: cada uno se compromete frente a los demás a obedecer, a condición de que los demás hagan lo mismo. El soberano —persona o asamblea— queda fuera del pacto y por eso no puede romperlo ni puede ser depuesto legítimamente, salvo que deje de cumplir su única función esencial: garantizar la seguridad de los pactantes.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes: el contrato como salida del miedo",
      body: "El resultado es un poder prácticamente absoluto, porque para Hobbes cualquier límite institucional al soberano reintroduce la posibilidad de disputa sobre quién tiene la última palabra, y con ella el riesgo de recaer en el estado de guerra. La obediencia se debe mientras el soberano cumpla su función; el problema hobbesiano no es cómo limitar el poder, sino cómo constituirlo de manera estable.",
    },
    {
      type: "quiz",
      question: "Para Hobbes, la guerra de todos contra todos se origina en…",
      options: [
        "la igualdad de las facultades naturales",
        "la maldad natural del corazón humano",
        "la escasez de recursos que la naturaleza ofrece",
        "la ausencia de leyes divinas reveladas",
      ],
      answer: 0,
      explain: "Hobbes es explícito en que la causa no es la mala voluntad. Todos son lo bastante parecidos como para que cualquiera pueda matar a cualquiera, y de esa igualdad de capacidades surge una igualdad de esperanzas, y de ahí la competencia, la desconfianza y el afán de gloria.",
    },
    {
      type: "quiz",
      question: "En Hobbes, el pacto se celebra…",
      options: [
        "entre los súbditos, y el soberano queda fuera",
        "entre los súbditos y el soberano por igual",
        "entre el soberano y Dios como garante último",
        "entre las familias que componen la comunidad",
      ],
      answer: 0,
      explain: "Cada uno se compromete frente a los demás a obedecer, a condición de que los demás hagan lo mismo. Como el soberano no es parte del pacto, no puede romperlo ni ser depuesto legítimamente: de ahí que el poder resulte prácticamente absoluto.",
    },
    {
      type: "info",
      title: "Locke: el contrato como protección de derechos previos",
      body: "Locke retoma el vocabulario del estado de naturaleza y del contrato, pero para resolver un problema distinto. Su estado de naturaleza no es una guerra permanente, sino un estado de libertad e igualdad regido ya por una ley natural, accesible a la razón, que prohíbe dañar a otro en su vida, su salud, su libertad o sus posesiones.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el contrato como protección de derechos previos",
      body: "En ese estado, los individuos ya tienen derechos: sobre su propia persona y, por extensión, sobre el producto de su trabajo. Ese derecho previo a toda sociedad es lo que Macpherson, ya visto en la clase anterior, describía como el núcleo del individualismo posesivo lockeano.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el contrato como protección de derechos previos",
      body: "Locke explica la propiedad mediante la mezcla del trabajo propio con los recursos que ofrece la naturaleza, originalmente comunes: quien cultiva una tierra o recoge un fruto incorpora su trabajo a esa cosa y la hace suya, sin necesidad de un acuerdo previo de los demás. La única condición natural es dejar \"lo bastante y tan bueno\" para los demás.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el contrato como protección de derechos previos",
      body: "El problema del estado de naturaleza lockeano no es, entonces, la ausencia total de derecho, sino su fragilidad: cada uno es juez y parte en sus propias causas, no hay una autoridad imparcial que interprete la ley natural ni fuerza común que la haga cumplir.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el contrato como protección de derechos previos",
      body: "Eso produce lo que Locke llama \"inconvenientes\": abusos, disputas sin árbitro, que hacen inestable el goce pacífico de derechos que, a diferencia de los de Hobbes, ya existían plenamente antes de cualquier pacto.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el contrato como protección de derechos previos",
      body: "El contrato lockeano responde exactamente a ese problema: los individuos no renuncian a sus derechos, como en Hobbes, sino que ceden únicamente el derecho de hacer justicia por mano propia, a cambio de un poder común —legislativo y ejecutivo— que actúe como juez imparcial y proteja lo que ya les pertenecía antes del pacto. El gobierno es, para Locke, un fideicomiso: administra un poder que sigue perteneciendo al pueblo.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el contrato como protección de derechos previos",
      body: "De ahí se sigue una consecuencia que separa radicalmente a Locke de Hobbes: si el poder político existe para proteger derechos previos, un gobierno que los viola sistemáticamente traiciona su propio fundamento y pierde su legitimidad. Locke admite, en ese caso extremo, el derecho de resistencia: el pueblo puede disolver un gobierno que se ha vuelto tiránico y constituir uno nuevo.",
    },
    {
      type: "quiz",
      question: "En el contrato de Locke, los individuos ceden…",
      options: [
        "sólo el derecho de castigar por su cuenta",
        "todos sus derechos naturales al poder común",
        "la propiedad, que pasa a manos del legislativo",
        "su libertad natural a cambio de la seguridad",
      ],
      answer: 0,
      explain: "Es la diferencia central con Hobbes. Los derechos lockeanos ya existen plenamente en el estado de naturaleza; lo que falta es un juez imparcial. Por eso el gobierno es un fideicomiso que administra un poder que sigue perteneciendo al pueblo, y que pierde legitimidad si lo traiciona.",
    },
    {
      type: "classify",
      question: "¿Cada tesis es de Hobbes o de Locke?",
      groups: ["Hobbes", "Locke"],
      items: [
        { text: "El estado de naturaleza es una guerra de todos contra todos", group: 0 },
        { text: "La ley natural ya rige antes de todo pacto", group: 1 },
        { text: "El soberano no es parte del contrato", group: 0 },
        { text: "El pueblo puede disolver un gobierno tiránico", group: 1 },
        { text: "Cada uno tiene derecho a todo, incluso al cuerpo del otro", group: 0 },
        { text: "El gobierno administra un poder que sigue siendo del pueblo", group: 1 },
      ],
      explain: "La divergencia se explica por el diagnóstico. Si en el estado de naturaleza no hay derechos, como en Hobbes, el problema es constituir el poder y cualquier límite lo debilita. Si los derechos ya existen y sólo son frágiles, como en Locke, el poder está al servicio de un fin que puede traicionar.",
    },
    {
      type: "info",
      title: "Rousseau: la desigualdad como producto histórico",
      body: "**Jean-Jacques Rousseau** (1712–1778) introduce una diferencia de método antes que de doctrina. En el Discurso sobre el origen de la desigualdad entre los hombres (1755), no describe el estado de naturaleza como un punto de partida racional del que deducir derechos, sino como una hipótesis histórica: cómo pudo ser el ser humano antes de la sociedad, y cómo se llegó, paso a paso, hasta la desigualdad presente.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau: la desigualdad como producto histórico",
      body: "El ser humano natural de Rousseau —el \"buen salvaje\", aunque él nunca usa esa expresión— vive aislado, sin lenguaje elaborado, sin razón desarrollada, movido solo por dos principios: el amor de sí, instinto de autoconservación, y la piedad, repugnancia natural a ver sufrir a otro ser sensible. En ese estado no hay guerra hobbesiana, porque tampoco hay comparación ni rivalidad: cada uno se basta a sí mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau: la desigualdad como producto histórico",
      body: "La desigualdad, para Rousseau, no es natural sino histórica: nace cuando alguien cerca un terreno, dice \"esto es mío\" y encuentra gente lo bastante simple como para creerle. Ese es, en la lectura de Rousseau, el verdadero origen de la sociedad civil y de todos los males que la acompañan: la propiedad privada introduce la comparación, la vanidad, la dependencia recíproca y, finalmente, la desigualdad estable entre ricos y pobres.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau: la desigualdad como producto histórico",
      body: "Esta es la diferencia decisiva con Locke: donde Locke ve en la propiedad el resultado legítimo del trabajo, garantizado por la ley natural, Rousseau ve en ella el origen de la dominación, un pacto engañoso propuesto por los ricos a los pobres para consagrar, bajo la forma de leyes, una desigualdad de hecho. El contrato, en este primer relato de Rousseau, no resuelve el problema: lo institucionaliza.",
    },
    {
      type: "quiz",
      question: "Para Rousseau, la desigualdad se origina en…",
      options: [
        "el cercado de la tierra y la propiedad",
        "la diferencia natural de fuerza y de talento",
        "la aparición del lenguaje y del razonamiento",
        "el pacto que funda la soberanía del pueblo",
      ],
      answer: 0,
      explain: "La escena es célebre: la desigualdad nace cuando alguien cerca un terreno, dice «esto es mío» y encuentra gente lo bastante simple como para creerle. No es natural sino histórica, y ahí está la ruptura con Locke, que veía en la propiedad el resultado legítimo del trabajo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Rousseau al instinto de autoconservación del ser humano natural?",
      answers: ["amor de sí", "amor de si"],
      explain: "Junto con la piedad, la repugnancia natural a ver sufrir a otro ser sensible, son los dos únicos principios que mueven al hombre natural. En ese estado no hay guerra hobbesiana porque tampoco hay comparación ni rivalidad: cada uno se basta a sí mismo.",
    },
    {
      type: "info",
      title: "El contrato social y la voluntad general",
      body: "El contrato social (1762) propone la salida a ese diagnóstico: un pacto capaz de reunir la fuerza de todos en defensa de cada uno, sin que nadie deje de obedecerse a sí mismo y permanezca, por tanto, tan libre como antes.",
    },
    {
      type: "info",
      continues: true,
      title: "El contrato social y la voluntad general",
      body: "La fórmula rousseauniana consiste en que cada asociado se entregue por entero a la comunidad, y no a otro individuo particular: al no depender de nadie en especial, no pierde su libertad, sino que la recupera transformada en libertad civil, garantizada ahora por la fuerza de todo el cuerpo político.",
    },
    {
      type: "info",
      continues: true,
      title: "El contrato social y la voluntad general",
      body: "De ese acto de asociación surge un cuerpo colectivo regido por la **voluntad general**, que Rousseau distingue con cuidado de la mera suma de voluntades particulares, la llamada \"voluntad de todos\". Esta última solo suma intereses privados; la voluntad general apunta, en cambio, al bien común del cuerpo entero.",
    },
    {
      type: "info",
      continues: true,
      title: "El contrato social y la voluntad general",
      body: "Por eso la voluntad general puede exigir obediencia incluso a quien votó en contra: quien se opone a ella, sostiene Rousseau, se equivoca sobre su propio interés como miembro del cuerpo político, aunque tenga razón sobre su interés privado inmediato.",
    },
    {
      type: "info",
      continues: true,
      title: "El contrato social y la voluntad general",
      body: "De ahí la fórmula más provocadora del libro: quien se niegue a obedecer la voluntad general será \"obligado a ser libre\", porque esa obediencia es, para Rousseau, la condición misma de la libertad civil.",
    },
    {
      type: "info",
      continues: true,
      title: "El contrato social y la voluntad general",
      body: "Esa libertad civil es distinta de la libertad natural que se pierde al entrar en sociedad: ya no consiste en hacer lo que a cada uno se le antoje, sino en obedecer una ley que uno mismo, como parte del soberano, ha contribuido a darse.",
    },
    {
      type: "info",
      continues: true,
      title: "El contrato social y la voluntad general",
      body: "La **soberanía**, en este esquema, reside siempre en el pueblo reunido y es inalienable e indivisible: no puede transferirse a un rey ni a un parlamento de representantes, porque la voluntad general no se representa, se ejerce. En esto Rousseau se aparta tanto de Hobbes, que transfiere el derecho a un soberano ajeno al pacto, como de Locke, que confía el gobierno a instituciones representativas.",
    },
    {
      type: "quiz",
      question: "La voluntad general se distingue de la voluntad de todos en que…",
      options: [
        "apunta al bien común, no a intereses privados",
        "se expresa por mayoría en lugar de unanimidad",
        "la ejercen los representantes y no el pueblo",
        "vale para el gobierno y no para los ciudadanos",
      ],
      answer: 0,
      explain: "La voluntad de todos sólo suma lo que cada uno quiere para sí. La voluntad general apunta al bien del cuerpo entero, y por eso puede exigir obediencia incluso a quien votó en contra: para Rousseau, ése se equivoca sobre su interés como miembro del cuerpo político.",
    },
    {
      type: "quiz",
      question: "Para Rousseau, la soberanía no puede representarse porque…",
      options: [
        "la voluntad general se ejerce, no se delega",
        "los representantes siempre traicionan al pueblo",
        "el pueblo reunido no cabe en una asamblea",
        "la ley debe ser aprobada por unanimidad",
      ],
      answer: 0,
      explain: "La soberanía reside en el pueblo reunido y es inalienable e indivisible. En esto Rousseau se aparta de los dos anteriores: de Hobbes, que transfiere el derecho a un soberano ajeno al pacto, y de Locke, que confía el gobierno a instituciones representativas.",
    },
    {
      type: "match",
      question: "Uní cada pieza con lo que le corresponde",
      pairs: [
        { left: "Hobbes", right: "La inseguridad de una igualdad sin autoridad común" },
        { left: "Locke", right: "La fragilidad de derechos que ya existían" },
        { left: "Rousseau", right: "Una desigualdad producida por la propiedad" },
        { left: "Voluntad general", right: "El bien del cuerpo político, no la suma de intereses" },
      ],
      explain: "Los tres primeros son el problema que cada contrato resuelve, y explican por qué del mismo vocabulario salen un poder prácticamente ilimitado, uno limitado y revocable, y un proyecto de reconstruir la igualdad que la sociedad civil destruyó.",
    },
    {
      type: "info",
      title: "Tres soluciones a tres problemas",
      body: "Los tres autores comparten el vocabulario contractualista, pero lo ponen al servicio de diagnósticos distintos. Hobbes resuelve el problema de la seguridad frente a una igualdad que, sin autoridad común, produce guerra; su contrato funda un poder prácticamente ilimitado.",
    },
    {
      type: "info",
      continues: true,
      title: "Tres soluciones a tres problemas",
      body: "Locke resuelve el problema de la protección de derechos naturales ya existentes; su contrato funda, en cambio, un poder limitado y revocable, sujeto al fin que lo justifica. Rousseau resuelve el problema de una desigualdad producida históricamente por la propiedad; su contrato busca reconstruir, mediante la voluntad general, una igualdad y una libertad que la sociedad civil había destruido.",
    },
    {
      type: "info",
      continues: true,
      title: "Tres soluciones a tres problemas",
      body: "Este arco contractualista se adelanta al orden cronológico del curso: Rousseau escribe en 1762, ya avanzado el siglo XVIII, mientras las próximas clases retroceden a las polémicas racionalistas y empiristas del siglo XVII.",
    },
    {
      type: "info",
      continues: true,
      title: "Tres soluciones a tres problemas",
      body: "La razón de este adelanto es que el arco político examinado aquí y el arco gnoseológico que sigue corren en paralelo durante buena parte del período, y conviene recorrer primero uno de punta a punta antes de abordar el otro. Rousseau volverá a aparecer más adelante, como antagonista de Voltaire en el debate sobre la Ilustración francesa.",
    },
  ],
};
