export default {
  num: 2,
  transcript: 2,
  title: "La nueva ciencia: la matematización de la naturaleza",
  source: "",
  feed: [
    {
      type: "info",
      title: "La cuarta raíz: la nueva física",
      body: "Junto a las raíces religiosas, humanistas y escépticas de la filosofía moderna, hay un cuarto proceso decisivo: la transformación de la física durante el siglo XVII, que introduce la matemática en el estudio de la naturaleza. Esta clase examina esa transformación entre 1543 y 1687, y muestra que sus protagonistas la entendieron como la reactivación de una polémica antigua entre platónicos y aristotélicos.",
    },
    {
      type: "info",
      continues: true,
      title: "La cuarta raíz: la nueva física",
      body: "Frente a la física aristotélica que aún se enseñaba en las universidades, los nuevos físicos —partidarios de aplicar la geometría a la física— se presentan a sí mismos como **platónicos**. Comparten así, con las raíces examinadas en la clase anterior, el rechazo del **aristotelismo escolástico**, aunque desde el terreno de la ciencia natural y no de la religión o la moral.",
    },
    {
      type: "info",
      title: "La física aristotélica y la separación de los saberes",
      body: "Para entender la novedad del siglo XVII conviene partir de cómo Aristóteles concebía la relación entre física y geometría. Su física describe la naturaleza como un cosmos cualitativamente diferenciado y jerárquicamente ordenado, donde los cuerpos se mueven naturalmente hacia sus lugares propios: el fuego hacia el cielo, los cuerpos pesados hacia la tierra.",
    },
    {
      type: "info",
      continues: true,
      title: "La física aristotélica y la separación de los saberes",
      body: "En esa física, el movimiento y el cambio se explican por fines u objetivos propios de cada fenómeno: una parte central de la explicación científica es el estudio de esos fines, la **teleología**. Solo un agente exterior puede desviar violentamente a un cuerpo de su tendencia natural, produciendo lo que Aristóteles llama movimiento violento, opuesto al movimiento natural.",
    },
    {
      type: "info",
      continues: true,
      title: "La física aristotélica y la separación de los saberes",
      body: "Esta distinción entre movimiento natural y movimiento violento es solidaria de la distinción entre lugares naturales heterogéneos: cada elemento —fuego, aire, agua, tierra— tiene un lugar propio hacia el que tiende, y esa tendencia explica por qué se mueve como se mueve, sin necesidad de apelar a fuerzas externas constantes.",
    },
    {
      type: "info",
      continues: true,
      title: "La física aristotélica y la separación de los saberes",
      body: "Esta concepción exige mantener separadas la física y la geometría. La física estudia sustancias individuales captables por los sentidos —agua, tierra, minerales, seres vivos—; la geometría estudia magnitudes abstractas, asequibles solo a la razón. La extensión geométrica, para Aristóteles, no es algo real en la naturaleza, sino un accidente de la sustancia que la razón puede abstraer.",
    },
    {
      type: "info",
      continues: true,
      title: "La física aristotélica y la separación de los saberes",
      body: "Aristóteles resume esta idea al describir al matemático como quien procede \"eliminando previamente todas las cualidades sensibles [...] y solo deja la cantidad y la continuidad\" (Metafísica, K 3). La geometría de Euclides estudia, entonces, un dominio distinto del de los lugares naturales hacia los que se mueven las cosas físicas.",
    },
    {
      type: "quiz",
      question: "Para la física aristotélica, movimiento natural y geometría…",
      options: [
        "estudian objetos distintos y deben mantenerse separadas",
        "son la misma ciencia, con un único método",
        "la física reduce todo movimiento a la geometría",
        "la geometría depende por completo de los sentidos",
      ],
      answer: 0,
      explain: "La física estudia sustancias sensibles y sus lugares naturales; la geometría, magnitudes abstractas asequibles sólo a la razón. Para Aristóteles la extensión geométrica no es algo real en la naturaleza, así que ambas ciencias deben mantenerse separadas.",
    },
    {
      type: "info",
      title: "Galileo: el universo escrito en lenguaje matemático",
      body: "El cambio que proponen los físicos del siglo XVII frente a esa tradición —interrumpida solo por figuras excepcionales como Arquímedes— es tan grande que resulta difícil exagerar su importancia. La mecánica moderna explica el movimiento de los cuerpos reales partiendo del movimiento, imaginario, de cuerpos geométricos en un espacio vacío y homogéneo.",
    },
    {
      type: "info",
      continues: true,
      title: "Galileo: el universo escrito en lenguaje matemático",
      body: "Lo que Aristóteles reservaba a los matemáticos, la abstracción de toda cualidad no cuantificable, pasa ahora a aplicarse también a la física. **Galileo Galilei** (1564–1642) lo formula en una imagen célebre de su libro Il saggiatore: el universo es un libro escrito en caracteres matemáticos, y quien no conoce ese lenguaje no puede comprender los fenómenos naturales.",
    },
    {
      type: "info",
      continues: true,
      title: "Galileo: el universo escrito en lenguaje matemático",
      body: "Frente a la heterogeneidad aristotélica entre espacio geométrico y espacio físico, Galileo concibe el espacio físico como homogéneo y puramente cuantitativo: lo asimila, en los hechos, al espacio geométrico. Esa asimilación es el núcleo mismo de la matematización moderna de la naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "Galileo: el universo escrito en lenguaje matemático",
      body: "En su Diálogo sobre los dos máximos sistemas del mundo (1632), Galileo presenta esta polémica bajo la forma literaria de un diálogo. Salviati, su alter ego, expone las nuevas teorías físico-matemáticas ante dos interlocutores: Sagredo, el hombre neutral y bien dispuesto a aprender, y Simplicio, el ingenuo aristotélico que se niega a aplicar criterios matemáticos a los problemas físicos.",
    },
    {
      type: "match",
      question: "Uní cada personaje del Diálogo de Galileo con su papel",
      pairs: [
        { left: "Salviati", right: "Defiende la nueva física matemática" },
        { left: "Sagredo", right: "El interlocutor neutral y bien dispuesto" },
        { left: "Simplicio", right: "El aristotélico que rechaza los criterios matemáticos" },
      ],
      explain: "Galileo dramatiza en el Diálogo (1632) la polémica entre la vieja física cualitativa y la nueva física matemática, repartiendo los papeles entre tres interlocutores ficticios.",
    },
    {
      type: "info",
      continues: true,
      title: "Galileo: el universo escrito en lenguaje matemático",
      body: "La mecánica moderna presupone, entonces, una exigencia metodológica: considerar la naturaleza de manera puramente cuantitativa, dejando de lado cualquier cualidad que no pueda medirse o calcularse. Esa exigencia, sin embargo, no era interpretada de manera uniforme ni siquiera entre quienes la compartían: aceptar que la naturaleza debe describirse matemáticamente no obliga a aceptar una única respuesta sobre qué significa, en rigor, describirla así.",
    },
    {
      type: "info",
      continues: true,
      title: "Galileo: el universo escrito en lenguaje matemático",
      body: "Una comparación entre Galileo y **René Descartes** (1596–1650) permite ver dos versiones muy distintas de ese mismo programa antiaristotélico: ambos aplican la matemática a la física, pero entienden de un modo opuesto qué significa exactamente aplicarla y de dónde extrae esa aplicación su justificación última.",
    },
    {
      type: "quiz",
      question: "Cuando Galileo dice que el universo está escrito en lenguaje matemático, sostiene que…",
      options: [
        "la física debe deducirse de verdades metafísicas",
        "el espacio físico es homogéneo, como el geométrico",
        "la teleología explica el movimiento mejor que la geometría",
        "la naturaleza no puede conocerse racionalmente",
      ],
      answer: 1,
      explain: "Galileo asimila el espacio físico al espacio geométrico, homogéneo y cuantitativo, frente a la heterogeneidad cualitativa de los lugares naturales aristotélicos. Deducir la física de la metafísica es, en cambio, el camino de Descartes.",
    },
    {
      type: "info",
      title: "Dos platonismos: Descartes contra Galileo",
      body: "Ambos coinciden en que la naturaleza tiene estructura matemática y en que la geometría es condición de toda ciencia natural: comparten, como platónicos modernos, la prohibición inscrita en el frontispicio de la Academia platónica, \"no entre nadie que no sepa geometría\". Pero el propio Descartes es consciente de la distancia que lo separa de Galileo.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "En una carta a Mersenne del 11 de octubre de 1638, Descartes evalúa el libro de Galileo Discursos y demostraciones en torno a dos nuevas ciencias: reconoce que Galileo \"filosofa mucho mejor que el vulgo\" y \"trata de examinar las materias físicas mediante razones matemáticas\", coincidiendo en que no hay otro camino para hallar la verdad física.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "El reconocimiento, sin embargo, es tibio, y va seguido de una crítica de fondo: Galileo interrumpe sus demostraciones con digresiones continuas, señal de que no procedió por orden ni investigó \"las primeras causas de la naturaleza\". El resultado, para Descartes, es una física sin fundamento: un edificio sin cimientos.",
    },
    {
      type: "quiz",
      question: "La crítica central de Descartes a Galileo es que…",
      options: [
        "no funda sus leyes en las primeras causas",
        "aplica la geometría de manera incorrecta",
        "confunde por completo física y teología",
        "rechaza cualquier uso de la experiencia",
      ],
      answer: 0,
      explain: "Descartes reconoce que Galileo filosofa mejor que el vulgo y aplica bien las matemáticas, pero le reprocha digresiones y falta de fundamento: no dedujo sus leyes de las primeras causas de la naturaleza, es decir, de la metafísica.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "La diferencia de fondo es esta: para Galileo, que la naturaleza tenga estructura matemática es un postulado necesario para cuantificar su objeto de estudio. Para Descartes, en cambio, esa estructura debe deducirse de verdades metafísicas: demostrar geométricamente una ley física es deducirla como consecuencia necesaria de esas verdades.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "En Los principios de la filosofía, Descartes pretende deducir todas las leyes que rigen el movimiento de los cuerpos a partir de tres leyes primeras, tomadas como premisas: la ley de inercia, la ley del movimiento rectilíneo y la ley del choque.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "Esas tres leyes, a su vez, se deducen de los atributos de Dios: \"a partir de que Dios no está en modo alguno sujeto a cambio y a partir de que Dios siempre actúa de la misma forma, podemos llegar al conocimiento de ciertas reglas [...] leyes de la naturaleza\" (Principios, II, §37).",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "La existencia de ese Dios se infiere, a su vez, de la noción de Dios presente en el cogito indudable, que se estudiará en la próxima clase. Aplicar el método geométrico a la física significa, para Descartes, deducir la física entera a partir de la metafísica: primero se funda la existencia de Dios, después las leyes generales del movimiento, y solo al final los fenómenos particulares.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "Galileo, en cambio, sostiene que la física debe separarse de la metafísica y constituirse como ciencia autónoma. No problematiza la existencia del mundo natural ni necesita, por tanto, garantías metafísicas: le basta suponer que la realidad tiene estructura matemática y que esa estructura puede conocerse.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "Esta diferencia se refleja también en el lugar que cada uno asigna a la experiencia. Para Descartes, la experiencia sensorial no descubre las causas: en el mejor de los casos es un corolario de la ciencia, un indicio transitorio de la verdad. El conocimiento verdadero deduce los efectos a partir de causas contenidas en principios racionales a priori.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "Para Galileo, en cambio, la experiencia —no la experiencia cotidiana del lego, sino la observación controlada y la experimentación— es el punto de partida de la investigación de las causas. Los experimentos son los instrumentos con que el científico interroga a la naturaleza, formulando preguntas en el lenguaje matemático en que está escrita.",
    },
    {
      type: "quiz",
      question: "Para Galileo, a diferencia de Descartes, la experiencia…",
      options: [
        "es el punto de partida para investigar las causas",
        "sólo sirve como corolario transitorio de la ciencia",
        "debe eliminarse por completo de la física",
        "sustituye enteramente a las matemáticas",
      ],
      answer: 0,
      explain: "Para Descartes la experiencia es apenas un indicio transitorio de la verdad; para Galileo, en cambio, la observación controlada y la experimentación son el punto de partida de toda investigación de las causas.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos platonismos: Descartes contra Galileo",
      body: "Por eso Descartes reprocha a Galileo justamente sus experimentos: los ve como digresiones inútiles, propias de quien explica efectos particulares sin deducirlos de causas primeras. La oposición entre ambos autores respecto de física y metafísica se resume, entonces, en el papel que cada uno asigna a la experiencia dentro del conocimiento de la naturaleza.",
    },
    {
      type: "classify",
      question: "¿Cada posición es de Galileo o de Descartes?",
      groups: ["Galileo", "Descartes"],
      items: [
        { text: "La física debe separarse de la metafísica", group: 0 },
        { text: "Las leyes físicas se deducen de los atributos de Dios", group: 1 },
        { text: "La experiencia es el punto de partida de la ciencia", group: 0 },
        { text: "La experiencia es sólo un indicio transitorio", group: 1 },
        { text: "Basta suponer que la naturaleza es matemática", group: 0 },
        { text: "Hay que fundar la física en las primeras causas", group: 1 },
      ],
      explain: "Ambos son platónicos modernos: creen que la naturaleza tiene estructura matemática. Pero Galileo la trata como postulado autónomo de la física, mientras que Descartes la deriva de una metafísica fundada en Dios.",
    },
    {
      type: "info",
      title: "Copérnico, Kepler y la nueva astronomía",
      body: "Esta matematización de la naturaleza tiene su origen astronómico casi un siglo antes de Galileo. **Nicolás Copérnico** (1473–1543) propone en Sobre las revoluciones de los orbes celestes (1543) el modelo heliocéntrico: la Tierra y los demás planetas giran alrededor del Sol, y no al revés, como sostenía la astronomía ptolemaica adoptada por el aristotelismo medieval.",
    },
    {
      type: "info",
      continues: true,
      title: "Copérnico, Kepler y la nueva astronomía",
      body: "**Johannes Kepler** (1571–1630) perfecciona ese modelo al sustituir las órbitas circulares por elipses y formular las leyes matemáticas que rigen el movimiento planetario. Con Kepler, la astronomía deja de ser una descripción geométrica de apariencias y pasa a ser una física matemática de los cielos: las mismas leyes que rigen el movimiento explican también su causa.",
    },
    {
      type: "info",
      continues: true,
      title: "Copérnico, Kepler y la nueva astronomía",
      body: "El paso de Copérnico a Kepler es también un paso de la geometría a la física: Copérnico reordena los cuerpos celestes en un esquema más simple, pero conserva el prejuicio antiguo de que los movimientos celestes deben ser circulares y uniformes. Kepler rompe con ese prejuicio al mostrar que las órbitas reales son elípticas y que su velocidad varía según la distancia al Sol.",
    },
    {
      type: "quiz",
      question: "El aporte específico de Kepler sobre el modelo de Copérnico es…",
      options: [
        "reemplazar el heliocentrismo por el geocentrismo",
        "sustituir las órbitas circulares por elipses",
        "descubrir la ley de gravitación universal",
        "demostrar que la Tierra no se mueve",
      ],
      answer: 1,
      explain: "Copérnico ya proponía el heliocentrismo, pero conservaba las órbitas circulares. Kepler muestra que las órbitas reales son elípticas y que la velocidad orbital varía con la distancia al Sol; la gravitación universal es aporte posterior de Newton.",
    },
    {
      type: "info",
      continues: true,
      title: "Copérnico, Kepler y la nueva astronomía",
      body: "El historiador **Alexandre Koyré** (1892–1964) mostró que este proceso no fue solo un cambio de datos observacionales, sino una transformación filosófica profunda: el paso de un cosmos jerárquico y finito a un universo homogéneo e infinito, regido en todas sus partes por las mismas leyes matemáticas.",
    },
    {
      type: "info",
      continues: true,
      title: "Copérnico, Kepler y la nueva astronomía",
      body: "A esta lectura filosófica de la revolución científica, que subraya la deuda de sus protagonistas con el racionalismo matemático de Platón antes que con la observación empírica pura, se la conoce como **platonismo matemático**. Es la misma etiqueta, \"platónicos\", que Galileo y Descartes se atribuían a sí mismos frente a los aristotélicos de las universidades.",
    },
    {
      type: "quiz",
      question: "Según Koyré, la revolución científica del siglo XVII implica sobre todo…",
      options: [
        "el paso de un cosmos finito a un universo infinito",
        "el abandono completo de toda matemática",
        "la vuelta al modelo geocéntrico ptolemaico",
        "la separación total entre física y astronomía",
      ],
      answer: 0,
      explain: "Koyré describe la revolución científica como el pasaje \"del mundo cerrado al universo infinito\": de un cosmos jerárquico y finito a un espacio homogéneo, regido en todas sus partes por las mismas leyes matemáticas.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la lectura filosófica que ve en Galileo y Descartes una forma de platonismo aplicado a la física?",
      answers: ["platonismo matemático"],
      explain: "Es la etiqueta que sus propios protagonistas se atribuían frente a los aristotélicos de las universidades: la matemática como el conocimiento por excelencia y el modelo de todo saber racional.",
    },
    {
      type: "info",
      title: "Newton y la culminación del programa",
      body: "**Isaac Newton** (1643–1727) culmina este largo proceso en los Principios matemáticos de la filosofía natural (1687). Allí formula la ley de gravitación universal: una única ley matemática que explica tanto la caída de los cuerpos en la Tierra como el movimiento de los planetas alrededor del Sol.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y la culminación del programa",
      body: "Con esa unificación, Newton supera la vieja distinción aristotélica entre un mundo supralunar, incorruptible y regido por el movimiento circular perfecto, y un mundo sublunar, corruptible y regido por el movimiento rectilíneo hacia los lugares naturales. Para la física newtoniana no hay dos mundos con leyes distintas, sino un único universo homogéneo.",
    },
    {
      type: "quiz",
      question: "La ley de gravitación de Newton es revolucionaria porque…",
      options: [
        "explica con una sola ley los cielos y la Tierra",
        "demuestra que los planetas no se mueven",
        "separa definitivamente física y matemática",
        "vuelve a distinguir el mundo supralunar del sublunar",
      ],
      answer: 0,
      explain: "Antes, la física aristotélica distinguía un mundo supralunar regido por el movimiento circular y otro sublunar regido por el movimiento rectilíneo. Newton unifica ambos bajo una sola ley matemática: la gravitación universal.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y la culminación del programa",
      body: "Con Newton, el programa iniciado por Copérnico y desarrollado por Kepler y Galileo alcanza su forma más acabada: una física universal, matemática, aplicable por igual a una manzana que cae y a un planeta que orbita, sin distinción de reinos ni de sustancias.",
    },
    {
      type: "match",
      question: "Uní cada autor con su aporte a la nueva ciencia",
      pairs: [
        { left: "Copérnico", right: "El modelo heliocéntrico (1543)" },
        { left: "Kepler", right: "Órbitas elípticas, no circulares" },
        { left: "Galileo", right: "El universo escrito en lenguaje matemático" },
        { left: "Descartes", right: "Deducir la física de la metafísica" },
        { left: "Newton", right: "Una sola ley para los cielos y la Tierra" },
      ],
      explain: "Cinco pasos de un mismo proceso: la sustitución progresiva de la física cualitativa aristotélica por una ciencia matemática y universal de la naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "Newton y la culminación del programa",
      body: "Esta nueva concepción de la naturaleza —homogénea, cuantificable, regida por leyes matemáticas universales— será el trasfondo constante de la filosofía moderna que se examina en las próximas clases, empezando por la de Descartes, quien construye su metafísica precisamente para darle a esta física matemática el fundamento racional que Galileo no le había dado.",
    },
  ],
};
