export default {
  num: 15,
  transcript: 15,
  title: "Kant y la salida de la minoría de edad",
  source: "",
  feed: [
    {
      type: "info",
      title: "Una respuesta breve a una pregunta de coyuntura",
      body: "El texto más leído de Kant no es ninguna de las tres Críticas. Es un artículo de pocas páginas publicado en la Berlinische Monatsschrift en diciembre de 1784, titulado **«Respuesta a la pregunta: ¿qué es la Ilustración?»**.",
    },
    {
      type: "info",
      continues: true,
      title: "Una respuesta breve a una pregunta de coyuntura",
      body: "Conviene recordar de dónde venía la pregunta. La había formulado el teólogo Johann Friedrich Zöllner al pie de un artículo del año anterior, y no era una cuestión académica: los ilustrados alemanes estaban discutiendo qué era exactamente el movimiento del que se consideraban parte. Mendelssohn ya había respondido unos meses antes.",
    },
    {
      type: "info",
      continues: true,
      title: "Una respuesta breve a una pregunta de coyuntura",
      body: "Kant escribe, entonces, en una polémica en curso y para un público amplio. El texto no tiene aparato técnico ni terminología crítica. Sin embargo, sostiene una tesis que va bastante más lejos que la de sus contemporáneos, y que convirtió a estas páginas en la definición canónica de la época.",
    },
    {
      type: "quiz",
      question: "El artículo de Kant sobre la Ilustración fue…",
      options: [
        "una intervención breve en una polémica en curso",
        "el prólogo que abre la Crítica de la razón pura",
        "una conferencia leída en la Academia de Berlín",
        "un capítulo de su tratado sobre filosofía política",
      ],
      answer: 0,
      explain: "Son pocas páginas publicadas en la Berlinische Monatsschrift en diciembre de 1784, sin aparato técnico y para un público amplio. Kant no inaugura la discusión: responde a una pregunta que ya circulaba y que Mendelssohn había contestado meses antes.",
    },
    {
      type: "info",
      title: "La minoría de edad autoculpable",
      body: "La definición aparece en la primera línea: «La Ilustración es la salida del hombre de su **minoría de edad** de la que él mismo es culpable.»",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Cada término de esa frase hace trabajo. La palabra alemana Unmündigkeit designaba la condición jurídica del menor, de quien no puede disponer de sus bienes ni comparecer en juicio sin un tutor. Kant traslada esa figura legal al terreno del pensamiento: hay una minoría de edad intelectual, y consiste en no poder usar el propio entendimiento sin la dirección de otro.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Enseguida agrega la precisión decisiva. La minoría de edad es **autoculpable**, selbstverschuldet. Y lo es porque su causa no es la falta de entendimiento. Los hombres tienen entendimiento de sobra: lo que les falta es la decisión y el valor de usarlo por su cuenta.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "De ahí que el problema no sea intelectual sino, en el sentido amplio, moral. Si el obstáculo fuera una incapacidad, la Ilustración sería una cuestión de instrucción: habría que enseñar más. Si el obstáculo es una falta de resolución, entonces la Ilustración es algo que cada uno debe hacer, y que nadie puede hacer en su lugar.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Vale la pena detenerse en la metáfora jurídica, porque no es decorativa. El menor de edad no es alguien sin capacidades: es alguien cuyas decisiones, por disposición legal, valen sólo si otro las refrenda. Lo que le falta no es aptitud sino autorización, y en el caso que le interesa a Kant esa autorización se la niega uno mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Eso explica por qué la definición es tan exigente. No basta con haber leído mucho, ni con sostener opiniones correctas. Alguien puede repetir las tesis más avanzadas de su siglo y seguir siendo menor de edad, si las sostiene porque se las enseñaron y no porque las examinó. Lo que está en juego es quién realiza la operación, no cuál es el resultado.",
    },
    {
      type: "quiz",
      question: "Kant llama «autoculpable» a la minoría de edad porque…",
      options: [
        "falta la decisión de usar el entendimiento, no el entendimiento",
        "cada uno elige a los tutores que le dirigen el pensamiento",
        "los prejuicios se heredan y nadie los examina a tiempo",
        "el que no estudia se queda sin los saberes de su época",
      ],
      answer: 0,
      explain: "La precisión es decisiva: si el obstáculo fuera una incapacidad, la Ilustración sería una cuestión de instrucción y habría que enseñar más. Como el obstáculo es una falta de resolución y de valor, la Ilustración es un acto que cada uno tiene que realizar y que nadie puede hacer en su lugar.",
    },
    {
      type: "short",
      question: "¿Qué expresión latina de Horacio adopta Kant como lema de la Ilustración?",
      answers: ["sapere aude", "sapere aude!"],
      explain: "Se traduce «atrévete a saber» o, en la versión que Kant explicita, «ten el valor de servirte de tu propio entendimiento». Es un imperativo y no una descripción: exige coraje más que talento.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Kant nombra los dos vicios que sostienen la situación: la pereza y la cobardía. Es cómodo ser menor de edad. Si otro piensa por mí, no tengo que hacer el esfuerzo; y si me equivoco siguiendo a mi tutor, la responsabilidad no es mía. La minoría de edad no es sólo una condición padecida, es también una comodidad elegida.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Y describe a los tutores con ironía. Están los que se ofrecen amablemente: el libro que piensa por mí, el director espiritual que examina mi conciencia, el médico que decide mi dieta. No necesito pensar mientras pueda pagar; otros se encargarán del asunto molesto.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Pero también señala que los tutores tienen interés en que la situación continúe. Primero atrofian la capacidad de andar solos y después muestran el peligro de intentarlo. Kant usa la imagen de las andaderas: los prejuicios son andaderas, y el que consigue liberarse de ellas ya no camina bien, porque no aprendió nunca.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "La imagen tiene una consecuencia incómoda que Kant no esconde. Quien se emancipa de golpe da unos pasos torpes, y esa torpeza sirve de argumento a los tutores: miren lo que pasa cuando los dejan solos. La minoría de edad se justifica a sí misma produciendo la incompetencia que después denuncia.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "Por eso Kant insiste en que el peligro no es tan grande como se lo pinta. Los que se caen al principio terminan aprendiendo a caminar, y el riesgo de unos tropiezos es infinitamente menor que el de una humanidad permanentemente tutelada. Es un cálculo, y Kant lo hace explícito.",
    },
    {
      type: "info",
      continues: true,
      title: "La minoría de edad autoculpable",
      body: "De ahí el lema del texto, tomado de Horacio: **sapere aude**, ten el valor de servirte de tu propio entendimiento. Es un imperativo, no una descripción. La Ilustración no es un estado en el que uno se encuentra sino un acto que hay que realizar, y que exige coraje más que talento.",
    },
    {
      type: "info",
      title: "Por qué es más fácil para un público que para un individuo",
      body: "Hecha la exigencia, Kant reconoce su dificultad. A un individuo suelto le cuesta muchísimo salir de una minoría de edad que se le volvió casi natural. Le tomó cariño y es realmente incapaz de servirse de su entendimiento, porque nunca lo dejaron intentarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué es más fácil para un público que para un individuo",
      body: "La salida, entonces, es más viable colectivamente. Que un **público** se ilustre por sí mismo es casi inevitable si se le deja libertad, porque siempre habrá algunos que piensen por su cuenta, y su ejemplo se difunde. La Ilustración es un proceso social antes que una hazaña individual.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué es más fácil para un público que para un individuo",
      body: "Esto tiene una consecuencia práctica que Kant subraya: para la Ilustración no se necesita nada más que libertad, y la más inofensiva de todas: la libertad de hacer un uso público de la razón en todos los asuntos. No hace falta una revolución, hace falta que se pueda escribir y discutir.",
    },
    {
      type: "quiz",
      question: "¿Por qué le resulta más fácil ilustrarse a un público que a un individuo?",
      options: [
        "Porque siempre hay algunos que piensan solos y contagian",
        "Porque las instituciones educan más rápido que la familia",
        "Porque el número protege de las represalias del gobierno",
        "Porque el individuo carece de los libros que el público tiene",
      ],
      answer: 0,
      explain: "Al individuo suelto le cuesta muchísimo, porque le tomó cariño a una minoría de edad que se le volvió casi natural y nunca lo dejaron intentar. Colectivamente, en cambio, es casi inevitable si se deja libertad: el ejemplo de los pocos que piensan por su cuenta se difunde.",
    },
    {
      type: "info",
      title: "Uso público y uso privado de la razón",
      body: "Acá aparece la distinción más original del texto, y también la más fácil de malentender, porque Kant usa «público» y «privado» al revés de como los usamos hoy.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "El **uso público** de la razón es el que alguien hace en cuanto sabio que se dirige al conjunto de los lectores. No importa que hable de asuntos personales o desde su casa: lo público es la audiencia universal a la que se dirige. Ese uso, dice Kant, debe ser enteramente libre.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "El **uso privado** es el que alguien hace en el ejercicio del cargo o la función que le fue confiada. Ahí está actuando como pieza de una maquinaria, en nombre de otro, y ese uso puede legítimamente restringirse: si cada funcionario razonara a su gusto en el ejercicio del cargo, la maquinaria no funcionaría.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "Kant lo ilustra con tres ejemplos. El oficial que recibe una orden no puede discutirla en formación, pero como estudioso puede publicar observaciones sobre los errores del servicio militar. El contribuyente debe pagar el impuesto que le corresponde, y puede al mismo tiempo escribir sobre la injusticia de ese impuesto.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "El tercer ejemplo es el que a Kant le importa, y por eso lo desarrolla más. El clérigo está obligado a enseñar a su congregación conforme al credo de la iglesia a la que sirve, porque para eso fue contratado. Pero como sabio tiene plena libertad, e incluso el deber, de comunicar sus observaciones críticas sobre ese credo.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "Kant elige el caso religioso deliberadamente, y lo dice: la tutela en materia de religión es la más perjudicial y la más deshonrosa de todas. Es el terreno donde la minoría de edad está mejor instalada y donde los tutores tienen la autoridad más difícil de discutir, así que es ahí donde la prueba vale.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "El razonamiento sobre el clérigo tiene además un límite que Kant marca. Si llegara a convencerse de que el credo que enseña contiene algo contrario a la religión interior, entonces sí debe renunciar al cargo: puede enseñar lo que no comparte del todo, pero no lo que considera falso. La obediencia funcional no llega hasta la mentira.",
    },
    {
      type: "classify",
      question: "¿Cada situación es un uso público o un uso privado de la razón?",
      groups: ["Uso público", "Uso privado"],
      items: [
        { text: "El oficial publica un ensayo sobre los errores del servicio", group: 0 },
        { text: "El oficial recibe una orden en formación", group: 1 },
        { text: "El clérigo enseña a su congregación el credo de su iglesia", group: 1 },
        { text: "El clérigo escribe sus objeciones a ese credo como sabio", group: 0 },
        { text: "El contribuyente paga el impuesto que le corresponde", group: 1 },
        { text: "El contribuyente argumenta contra ese impuesto por escrito", group: 0 },
      ],
      explain: "Kant usa los términos al revés de como los usamos hoy. Lo público no es el lugar donde se habla sino la audiencia universal a la que se habla: el que escribe como sabio ante el mundo lector hace uso público, y debe ser libre. El que actúa en el cargo que le fue confiado hace uso privado, y puede ser restringido.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "La fórmula que resume la posición se volvió célebre en la versión que Kant atribuye a Federico II: razonad todo lo que queráis y sobre lo que queráis, pero obedeced. Es una combinación desconcertante de libertad intelectual ilimitada y obediencia civil, y hay que entender por qué a Kant no le parece una contradicción.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "El argumento es que la crítica sólo puede funcionar si es pública. Un funcionario que desobedece produce desorden y no convence a nadie; un autor que argumenta ante el público puede cambiar la ley por la que ese funcionario será juzgado mañana. La obediencia es el precio de mantener abierto el espacio donde la crítica opera.",
    },
    {
      type: "quiz",
      question: "«Razonad todo lo que queráis, pero obedeced» no es una contradicción porque…",
      options: [
        "el que desobedece no convence a nadie y produce desorden",
        "la obediencia es un deber moral anterior a la libertad",
        "la crítica pública sólo alcanza a los asuntos religiosos",
        "el súbdito recupera su libertad al dejar el cargo que ocupa",
      ],
      answer: 0,
      explain: "Para Kant la obediencia es el precio de mantener abierto el espacio donde la crítica opera. Un funcionario que desobedece produce desorden sin persuadir; un autor que argumenta ante el público puede cambiar la ley por la que ese funcionario será juzgado mañana.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "Hay además un límite que Kant impone en la otra dirección, contra las autoridades. Ninguna generación tiene derecho a comprometer a las siguientes con un credo inmodificable. Un contrato que suprimiera para siempre el progreso de la Ilustración sería nulo, porque atentaría contra la vocación misma de la humanidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "El argumento es más fuerte de lo que parece. Kant no dice que ese contrato sería inconveniente o injusto: dice que sería jurídicamente nulo, es decir, que carecería de validez aunque todos lo firmaran por unanimidad. Hay un derecho de las generaciones futuras que ninguna asamblea presente puede cancelar.",
    },
    {
      type: "quiz",
      question: "Un contrato que fijara un credo para siempre sería, según Kant…",
      options: [
        "nulo, aunque lo firmaran todos por unanimidad",
        "válido mientras el soberano decidiera respetarlo",
        "legítimo sólo en materia civil, nunca religiosa",
        "revisable por la generación que viniera después",
      ],
      answer: 0,
      explain: "Kant no dice que sería inconveniente o injusto: dice que carecería de validez jurídica. Hay un derecho de las generaciones futuras que ninguna asamblea presente puede cancelar, porque atentaría contra la vocación misma de la humanidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Uso público y uso privado de la razón",
      body: "Y con eso queda dibujado el mapa completo. Frente al Estado, el súbdito obedece y el sabio escribe. Frente al tiempo, ninguna época puede clausurar la discusión para las que vienen. La Ilustración no es un contenido que haya que difundir, es la condición de que la discusión siga abierta.",
    },
    {
      type: "info",
      title: "Época ilustrada y época de ilustración",
      body: "Hacia el final, Kant se pregunta si su tiempo es una época ilustrada, y responde con una distinción que suele citarse suelta: no vivimos en una época ilustrada, sino en una época de ilustración.",
    },
    {
      type: "info",
      continues: true,
      title: "Época ilustrada y época de ilustración",
      body: "La diferencia no es de matiz. Una época ilustrada sería una en la que los hombres ya son capaces de usar su entendimiento con seguridad y sin dirección ajena. Falta mucho para eso. Pero sí es una época en la que el campo se abrió, en la que los obstáculos van cediendo y el proceso está en marcha.",
    },
    {
      type: "info",
      continues: true,
      title: "Época ilustrada y época de ilustración",
      body: "Kant llama a su siglo el siglo de Federico, y elogia al monarca por un motivo preciso: por no considerar indigno de sí mismo decir que no le corresponde prescribir nada a sus súbditos en materia de religión. El elogio al despotismo ilustrado es real, y también es el punto donde el texto muestra su época.",
    },
    {
      type: "info",
      continues: true,
      title: "Época ilustrada y época de ilustración",
      body: "Conviene notar la asimetría que eso produce. Un gobernante ilustrado es el que tiene un ejército numeroso para garantizar la paz pública y al mismo tiempo permite la discusión sin restricciones. La libertad que Kant reclama es la de escribir, no la de decidir; el poder político no entra en discusión.",
    },
    {
      type: "info",
      continues: true,
      title: "Época ilustrada y época de ilustración",
      body: "Kant sostiene, eso sí, que la asimetría es transitoria. Un gobierno que deja pensar a sus súbditos termina descubriendo que puede tratarlos como algo más que engranajes, y la libertad de espíritu acaba influyendo sobre los principios del gobierno. La secuencia va de la libertad de pluma a la reforma política, no al revés.",
    },
    {
      type: "info",
      continues: true,
      title: "Época ilustrada y época de ilustración",
      body: "Cinco años después, la Revolución Francesa iba a poner esa secuencia a prueba en el sentido inverso. Vale registrar que el texto de 1784 apuesta explícitamente por la reforma gradual desde arriba, y que esa apuesta es inseparable de la Prusia en la que fue escrito.",
    },
    {
      type: "quiz",
      question: "«No vivimos en una época ilustrada, sino en una época de ilustración» quiere decir que…",
      options: [
        "el proceso está en marcha pero lejos de completarse",
        "la Ilustración ya alcanzó su forma definitiva en Prusia",
        "cada época se ilustra sobre los errores de la anterior",
        "los sabios están ilustrados y el pueblo todavía no",
      ],
      answer: 0,
      explain: "Una época ilustrada sería una en la que los hombres ya usan su entendimiento sin dirección ajena, y para eso falta mucho. Lo que Kant afirma de su tiempo es más modesto: el campo se abrió, los obstáculos van cediendo y el proceso empezó.",
    },
    {
      type: "info",
      title: "La distancia con Mendelssohn",
      body: "Puestas las dos respuestas de 1784 una al lado de la otra, la diferencia es nítida y vale la pena marcarla, porque separa dos maneras de entender el movimiento ilustrado.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Mendelssohn",
      body: "Para Mendelssohn, la ilustración es un conjunto de conocimientos: algo que un individuo o un pueblo poseen en mayor o menor medida, y que puede distinguirse de la cultura, que atañe a las destrezas prácticas y a los usos sociales. Es una magnitud, un grado de instrucción alcanzado.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Mendelssohn",
      body: "Para Kant no es un patrimonio sino un acto, y un acto que puede faltar aun teniendo todos los conocimientos del mundo. Un erudito que piensa lo que le dijeron que piense sigue siendo menor de edad. Lo que define la Ilustración no es cuánto se sabe, sino quién realiza la operación de pensar.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Mendelssohn",
      body: "De ahí que en Kant la Ilustración tenga la forma de un deber y de un proceso inacabado, mientras que en Mendelssohn tiene la de un estado que se puede medir y comparar entre naciones. La versión de Kant es más exigente, y también más difícil de dar por cumplida en cualquier momento histórico.",
    },
    {
      type: "match",
      question: "Uní cada término del texto de 1784 con lo que designa",
      pairs: [
        { left: "Minoría de edad", right: "No poder usar el entendimiento sin dirección ajena" },
        { left: "Sapere aude", right: "El valor de servirse del propio entendimiento" },
        { left: "Uso público", right: "El que se dirige al conjunto de los lectores" },
        { left: "Uso privado", right: "El que se ejerce en el cargo que se ocupa" },
        { left: "Época de ilustración", right: "Un proceso en marcha y no un estado alcanzado" },
      ],
      explain: "Las cinco piezas encajan en una sola tesis: la Ilustración no es un patrimonio de saberes sino un acto, exige libertad de pluma antes que reforma política, y por eso nunca puede darse por cumplida.",
    },
    {
      type: "quiz",
      question: "La diferencia central entre Mendelssohn y Kant sobre la Ilustración es que…",
      options: [
        "para uno es un saber que se posee y para otro un acto",
        "uno la defiende y el otro advierte contra sus peligros",
        "uno la limita a Alemania y el otro la piensa universal",
        "uno la funda en la religión y el otro en la política",
      ],
      answer: 0,
      explain: "Para Mendelssohn es una magnitud, un grado de instrucción que un individuo o un pueblo alcanzan, y distinguible de la cultura. Para Kant es una operación que puede faltar aun teniendo todos los conocimientos: un erudito que piensa lo que le dijeron sigue siendo menor de edad.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Mendelssohn",
      body: "Esa exigencia es, además, lo que la vuelve vulnerable. Si la Ilustración consiste en no aceptar ninguna autoridad ajena al propio entendimiento, queda una pregunta abierta: con qué autoridad se instala la razón como el tribunal que juzga a todas las demás. Ésa es la objeción que viene enseguida.",
    },
  ],
};
