export default {
  num: 1,
  transcript: 1,
  title: "Las raíces de la filosofía moderna",
  source: "",
  feed: [
    {
      type: "info",
      title: "Dónde empieza la filosofía moderna",
      body: "La filosofía moderna suele situarse entre el Discurso del método de René Descartes (1637) y la muerte de Hegel (1831). La fecha es una convención útil, no una ruptura tajante: muchos problemas y argumentos de este período no nacen de la nada, sino de tendencias culturales anteriores que fueron madurando durante los siglos XV y XVI.",
    },
    {
      type: "info",
      continues: true,
      title: "Dónde empieza la filosofía moderna",
      body: "Tres de esas tendencias —la Reforma luterana, el humanismo renacentista y el escepticismo renacentista— son muy distintas entre sí, y en buena medida opuestas. Comparten, sin embargo, un mismo adversario: el **aristotelismo escolástico**, el sistema doctrinal que las universidades medievales enseñaban desde su fundación.",
    },
    {
      type: "info",
      title: "El libre examen y el sacerdocio universal",
      body: "El cristianismo es una religión revelada: cuenta con un texto sagrado cuyo contenido, para el creyente, es necesariamente verdadero porque su autor es Dios. Pero un texto admite interpretaciones distintas, y de la interpretación correcta depende nada menos que la salvación del alma.",
    },
    {
      type: "info",
      continues: true,
      title: "El libre examen y el sacerdocio universal",
      body: "El catolicismo romano resolvía esa cuestión apelando, por un lado, a la tradición y a los concilios y, por otro, a una instancia última capaz de zanjar toda controversia: el Papa. La interpretación autorizada llegaba a los fieles a través de los sacerdotes, encargados de la enseñanza religiosa y del culto.",
    },
    {
      type: "info",
      continues: true,
      title: "El libre examen y el sacerdocio universal",
      body: "**Martín Lutero** (1483–1546) inicia la **Reforma** (1517) rechazando esa mediación eclesiástica. Su doctrina del **libre examen** sostiene que cada creyente, y no la Iglesia, tiene en sus manos la tarea de interpretar las Escrituras: la conciencia de cada uno debe reconocer por sí misma las verdades reveladas, sin depender de la tradición, los concilios ni la autoridad papal.",
    },
    {
      type: "info",
      continues: true,
      title: "El libre examen y el sacerdocio universal",
      body: "A esto se suma la doctrina del **sacerdocio universal**. En el catolicismo el sacerdocio es una profesión reservada a un estamento que monopoliza la administración de lo sagrado. Al rechazar la mediación eclesiástica, la Reforma convierte esa tarea en asunto de cada cristiano, que pasa a tener una relación directa con Dios, sin intermediarios.",
    },
    {
      type: "info",
      continues: true,
      title: "El libre examen y el sacerdocio universal",
      body: "Admitidas estas doctrinas, todo cristiano reformado debía poder leer la Escritura por sí mismo. Eso exigía alfabetización, una Biblia en lengua vernácula y ejemplares suficientes para todos. La Reforma trae consigo, entonces, un plan de alfabetización, la traducción del Nuevo Testamento al alemán hecha por el propio Lutero y su difusión mediante la imprenta recién inventada por Gutenberg.",
    },
    {
      type: "info",
      continues: true,
      title: "El libre examen y el sacerdocio universal",
      body: "Estas doctrinas son una raíz de la filosofía moderna porque le otorgan a la conciencia individual una nueva función: la de juez competente en el establecimiento de la verdad. Antes de la Reforma, esa conciencia se consideraba subordinada a autoridades externas, como los Padres de la Iglesia o el aristotelismo escolástico.",
    },
    {
      type: "info",
      continues: true,
      title: "El libre examen y el sacerdocio universal",
      body: "Descartes formulará después esta misma idea, ya desligada del irracionalismo luterano que desconfiaba de la razón y confiaba solo en el \"corazón\" del creyente. Al comienzo del Discurso del método afirma que \"el buen sentido es la cosa mejor repartida del mundo\": todo ser humano puede distinguir lo verdadero de lo falso por sí mismo, sin tradición ni autoridad externa.",
    },
    {
      type: "quiz",
      question: "Para la doctrina del libre examen, la interpretación correcta de la Biblia…",
      options: [
        "la establece el Papa junto con los concilios",
        "está al alcance de la conciencia de cada creyente",
        "sólo puede alcanzarla el estudio universitario",
        "depende de un acuerdo entre todas las Iglesias",
      ],
      answer: 1,
      explain: "Contra la mediación eclesiástica católica —tradición, concilios, Papa—, Lutero sostiene que cada creyente puede y debe interpretar por sí mismo las Escrituras, guiado por su propia conciencia.",
    },
    {
      type: "info",
      title: "El derecho natural tras las guerras de religión",
      body: "La Reforma no fue solo un cambio de conciencia religiosa: como fenómeno de masas, desató las guerras de religión que transformaron radicalmente el mapa político europeo. Antes de la Reforma, el Papa arbitraba en alguna medida los conflictos entre los príncipes, además de resolver las disputas de interpretación bíblica.",
    },
    {
      type: "info",
      continues: true,
      title: "El derecho natural tras las guerras de religión",
      body: "La Reforma desconoce esa autoridad moral internacional del Vaticano, y con ella desaparece el fundamento común sobre el que se apoyaba el derecho internacional vigente. Queda así abierto un problema nuevo y típicamente moderno: ¿en qué puede fundarse ahora el derecho entre las naciones?",
    },
    {
      type: "info",
      continues: true,
      title: "El derecho natural tras las guerras de religión",
      body: "**Hugo Grocio** (1583–1645) ofrece la solución característicamente moderna a ese vacío en Sobre el derecho de la guerra y de la paz (1625): un **derecho natural** racional, independiente de la voluntad de los príncipes, que la razón —común a todos los seres humanos— permite fundar como válido para todo ser racional, más allá de su nación o religión.",
    },
    {
      type: "info",
      continues: true,
      title: "El derecho natural tras las guerras de religión",
      body: "Esta solución tendrá largo alcance en la filosofía moderna. Los teóricos modernos del contrato, Thomas Hobbes, John Locke y Jean-Jacques Rousseau, profundizarán este mismo procedimiento: derivarán racionalmente los derechos de los soberanos de un pacto entre seres libres e iguales situados en un hipotético **estado de naturaleza**, previo a toda sociedad.",
    },
    {
      type: "info",
      continues: true,
      title: "El derecho natural tras las guerras de religión",
      body: "Por otra parte, filósofos como Herbert de Cherbury elaboran la idea de una **religión natural**: una religión derivada de la naturaleza humana —la razón— e independiente de los dogmas particulares de las religiones históricas. Su contenido se reduce al núcleo común a todas ellas: Dios providencial, deber moral, inmortalidad del alma.",
    },
    {
      type: "info",
      continues: true,
      title: "El derecho natural tras las guerras de religión",
      body: "Esas ideas de religión natural constituirán en el siglo XVII el tema central de la metafísica racionalista y, ya en el siglo XVIII, los postulados de la razón pura práctica que estudiará Immanuel Kant. La raíz religiosa de la Reforma desemboca así, por caminos indirectos, en problemas centrales de la filosofía moderna.",
    },
    {
      type: "quiz",
      question: "El derecho natural que propone Grocio busca fundar el derecho internacional en…",
      options: [
        "la autoridad moral del Papa sobre los príncipes",
        "la razón, común a todos los seres humanos",
        "la costumbre propia de cada nación",
        "la voluntad de los soberanos más poderosos",
      ],
      answer: 1,
      explain: "Tras la Reforma, la autoridad arbitral del Papa entre los príncipes desaparece. Grocio busca un fundamento secular: una razón común a todos los seres humanos, válida más allá de nación o religión.",
    },
    {
      type: "info",
      title: "El humanismo y la dignidad autónoma",
      body: "El **humanismo** renacentista italiano es otra raíz de la filosofía moderna, contemporánea de la Reforma pero opuesta a ella en su espíritu. Frente al sistema doctrinal medieval, que subordinaba toda la vida humana a la salvación del alma administrada por la Iglesia, el humanismo afirma la autonomía de la cultura respecto de los fines trascendentes.",
    },
    {
      type: "info",
      continues: true,
      title: "El humanismo y la dignidad autónoma",
      body: "Una figura representativa de este humanismo, aunque del lado del norte de Europa y no de Italia, es Erasmo de Rotterdam (1466–1536): como los humanistas italianos, confía en la cultura clásica y en la razón para criticar los abusos de la Iglesia, pero sin llegar a la ruptura de Lutero.",
    },
    {
      type: "info",
      continues: true,
      title: "El humanismo y la dignidad autónoma",
      body: "Esa autonomía presupone la dignidad del ser humano como un valor independiente de cualquier otro, y trae consigo una apertura nueva hacia la investigación de la verdad histórica. La idea misma de \"renacimiento\" es la rehabilitación de la Antigüedad pagana, sobre todo griega, como modelo ideal que la humanidad del siglo XV debía imitar.",
    },
    {
      type: "info",
      continues: true,
      title: "El humanismo y la dignidad autónoma",
      body: "Los humanistas se dedican al estudio y la traducción de manuscritos griegos en las nuevas \"academias\", centros de investigación y creación muy distintos de las universidades medievales. Esos manuscritos llegan a Italia en parte por la emigración de doctos bizantinos tras la caída de Constantinopla en manos turcas.",
    },
    {
      type: "info",
      continues: true,
      title: "El humanismo y la dignidad autónoma",
      body: "También llegan por otra vía: los concilios de Ferrara y Florencia habían acordado nuevas relaciones entre Roma y la Iglesia oriental, y el Papa envía embajadores a Constantinopla para ese acuerdo. Uno de ellos, el cardenal **Nicolás de Cusa** (1401–1464), regresa con manuscritos antiguos y con una idea nueva, la del infinito actual, decisiva para la metafísica del siglo XVII.",
    },
    {
      type: "quiz",
      question: "El humanismo renacentista, frente al orden medieval, afirma que…",
      options: [
        "la cultura vale sólo como medio de salvación",
        "la dignidad humana es un valor autónomo",
        "la razón debe subordinarse a la revelación",
        "sólo el clero puede acceder a la verdad",
      ],
      answer: 1,
      explain: "El orden medieval subordinaba toda la vida humana a la salvación del alma administrada por la Iglesia. El humanismo afirma, en cambio, la autonomía de la cultura y la dignidad humana como valor independiente.",
    },
    {
      type: "info",
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "Solemos concebir el universo como una totalidad de cosas distintas, clasificables en géneros y especies, ordenadas según un esquema objetivo e independiente de nuestro pensamiento. Nicolás de Cusa sostiene, contra esa concepción corriente, que ese orden y esa clasificación no son objetivos.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "Para Cusa dependen, en cambio, de las limitaciones de un entendimiento humano que, regido por el principio de no contradicción, parcela el infinito en distinciones y órdenes que en realidad no están en las cosas mismas. El entendimiento divino, regido por la coincidencia de los opuestos, ignora esas divisiones. A esta tesis la llama \"docta ignorancia\", título de una de sus obras más conocidas.",
    },
    {
      type: "quiz",
      question: "La \"docta ignorancia\" de Nicolás de Cusa sostiene que el orden del universo…",
      options: [
        "coincide exactamente con nuestras categorías",
        "depende de los límites del entendimiento humano",
        "sólo Dios puede llegar a desconocerlo",
        "se corresponde con la física de Aristóteles",
      ],
      answer: 1,
      explain: "Para Cusa, la clasificación que atribuimos al universo no es objetiva: es efecto de un entendimiento humano que, regido por el principio de no contradicción, parcela el infinito en distinciones que las cosas mismas no tienen.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "**Giordano Bruno** (1548–1600) retoma y radicaliza esta idea: para él, Dios es de una vez todo lo que puede ser, no una causa exterior sino el principio inmanente de un todo que nosotros dividimos, distinguimos y clasificamos según nuestras propias limitaciones.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "En Sobre el infinito universo y los mundos (1584), Bruno extrae las consecuencias cosmológicas de esta idea: existen infinitos mundos en un espacio infinito. Rechaza así la imagen medieval de una tierra central rodeada de esferas concéntricas, con el ser humano en el centro del universo visitado personalmente por Dios.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "Esa tesis resulta escandalosa porque parece incompatible con el carácter único e irrepetible de la encarnación de Cristo: si hay infinitos mundos habitados, esa encarnación podría repetirse en todos ellos. Los teólogos católicos la juzgan herética, y Bruno es condenado y muerto en la hoguera en 1600.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "Sus ideas cosmológicas inauguran, sin embargo, lo que el historiador **Alexandre Koyré** (1892–1964) llamó el pasaje \"del mundo cerrado al universo infinito\": el tránsito de un cosmos jerárquico y finito a un espacio homogéneo sin centro, que será el escenario de la física moderna.",
    },
    {
      type: "quiz",
      question: "A Bruno lo condenan por hereje porque su tesis de infinitos mundos…",
      options: [
        "niega que el universo tenga materia",
        "pone en duda la unicidad de la encarnación",
        "contradice las leyes del movimiento",
        "afirma que la Tierra no gira alrededor del Sol",
      ],
      answer: 1,
      explain: "Si existen infinitos mundos habitados, la encarnación de Cristo —que el dogma piensa como única e irrepetible— podría repetirse en todos ellos. Esa consecuencia es lo que los teólogos juzgan herético.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "Cusa y Bruno comparten la desconfianza hacia las representaciones antropomórficas de la naturaleza propias de la metafísica antigua reelaborada por los teólogos medievales. Para Bruno, lo que llamamos cosas particulares son solo manifestaciones de la totalidad del universo material, y Dios —o el uno— puede pensarse como el alma de ese universo, concebido como un animal viviente, universal e infinito.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "Esta idea de infinito actual, formulada por Cusa y radicalizada por Bruno, tendrá descendencia directa en la metafísica del siglo XVII. **Baruch Spinoza** (1632–1677) puede leerse como su continuador en tesis de la Ética (1677) sobre la unicidad de la sustancia y la identidad de Dios y la naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "El infinito actual: de Nicolás de Cusa a Bruno",
      body: "**Blaise Pascal** (1623–1662), en cambio, reacciona con angustia frente a ese mismo universo infinito. En sus Pensamientos (publicados póstumamente en 1670) describe la situación de un ser humano sin fe, que ya no encuentra sentido ni orientación en un espacio infinito, homogéneo, silencioso e indiferente.",
    },
    {
      type: "classify",
      question: "¿Cada reacción frente al universo infinito es de Spinoza o de Pascal?",
      groups: ["Spinoza", "Pascal"],
      items: [
        { text: "Dios y la naturaleza son una sola sustancia", group: 0 },
        { text: "Ese espacio infinito angustia al ser humano sin fe", group: 1 },
        { text: "La sustancia única explica toda la realidad", group: 0 },
        { text: "Un espacio homogéneo e indiferente da miedo", group: 1 },
      ],
      explain: "Ambos heredan la idea cusana y bruniana del infinito actual, pero la viven de modos opuestos: Spinoza la convierte en sistema racional (Dios sive natura); Pascal, en angustia existencial ante un universo sin sentido ni orientación.",
    },
    {
      type: "info",
      title: "El escepticismo de Montaigne",
      body: "El **escepticismo** renacentista comparte con las raíces anteriores la aversión al aristotelismo escolástico, pero rechaza además los motivos y las consecuencias de las disputas religiosas: tanto las que enfrentan a católicos y protestantes como las que oponen la Reforma al humanismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "Su obra de mayor influencia posterior son los Ensayos de **Michel de Montaigne** (1533–1592), publicados desde 1580. Montaigne ataca dos pretensiones que atribuye a la vanidad humana, y en particular a la de sus contemporáneos: el antropocentrismo y el etnocentrismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "Contra la pretensión antropocéntrica, sostiene en la \"Apología de Raimundo Sabunde\" que el ser humano se cree amo del universo por poseer la razón. Montaigne invierte el argumento: la inteligencia animal es superior, porque está orientada directamente por la razón divina, mientras que la razón humana es frágil y propensa a antinomias.",
    },
    {
      type: "quiz",
      question: "Contra la pretensión antropocéntrica, Montaigne argumenta que…",
      options: [
        "la inteligencia animal supera a la razón humana",
        "la razón humana no tiene ningún límite",
        "el ser humano no forma parte de la naturaleza",
        "los animales carecen de toda inteligencia",
      ],
      answer: 0,
      explain: "Montaigne invierte el argumento habitual: la conducta animal está guiada directamente por la razón divina, mientras que la razón humana es frágil, falible y cae fácilmente en antinomias y dudas.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "Esa fragilidad se manifiesta en las vacilaciones cotidianas de nuestra vida práctica, cuando la razón no basta para elegir entre cursos de acción alternativos. Una prueba adicional, para Montaigne, es que los filósofos nunca lograron acordar un sistema metafísico único y definitivo, pese a las pretensiones del dogmatismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "Los escépticos pirrónicos, además, se contradicen: niegan al ser humano toda capacidad de conocer, pero esa misma negación se formula ya como una pretensión de conocimiento. La actitud correspondiente a las capacidades humanas no es entonces ni la afirmación dogmática ni la negación pirrónica.",
    },
    {
      type: "quiz",
      question: "Montaigne objeta a los escépticos pirrónicos que…",
      options: [
        "niegan poder conocer y eso ya es conocer algo",
        "confían demasiado en la tradición aristotélica",
        "aceptan sin dudar cualquier opinión ajena",
        "se apoyan sólo en la revelación divina",
      ],
      answer: 0,
      explain: "Negar toda posibilidad de conocer es, en sí misma, una afirmación hecha con pretensión de conocimiento: los pirrónicos se contradicen al sostenerla. Por eso Montaigne prefiere la abstención del juicio.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "Montaigne propone en cambio la abstención del juicio, que permite la pregunta, la duda y la indagación autocrítica, bajo el lema \"¿Qué sé yo?\". Esta desconfianza en la razón humana es una tercera raíz de la filosofía moderna, distinta de la Reforma y del humanismo pero igual de decisiva.",
    },
    {
      type: "short",
      question: "¿Con qué pregunta resume Montaigne su actitud de abstención del juicio?",
      answers: ["qué sé yo", "¿qué sé yo?"],
      explain: "Es el lema del escepticismo de Montaigne: ni afirmación dogmática ni negación pirrónica, sino la pregunta abierta que permite seguir indagando sin pretender un saber definitivo.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "De ella surgirán, por un lado, la **duda metódica** que Descartes ejercitará en la primera de sus Meditaciones metafísicas (1641) para buscar un fundamento indudable del conocimiento. Por otro lado, alimentará las críticas al dogmatismo racionalista que más tarde desarrollará la tradición empirista británica.",
    },
    {
      type: "match",
      question: "Uní cada autor con su idea",
      pairs: [
        { left: "Lutero", right: "El libre examen: cada creyente interpreta la Biblia" },
        { left: "Grocio", right: "Un derecho natural racional para todas las naciones" },
        { left: "Bruno", right: "Infinitos mundos en un espacio infinito" },
        { left: "Nicolás de Cusa", right: "La docta ignorancia: el infinito excede al entendimiento" },
        { left: "Montaigne", right: "La abstención del juicio: \u2018¿Qué sé yo?\u2019" },
      ],
      explain: "Cinco raíces distintas de la filosofía moderna, unidas por el mismo desplazamiento: trasladar la autoridad de la tradición a la conciencia, la razón o la duda individual.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "Las tres raíces examinadas —la Reforma, el humanismo y el escepticismo— no convergen en una doctrina única ni en un programa compartido. Sin embargo, todas coinciden en desplazar la autoridad hacia el individuo: su conciencia, su dignidad, su capacidad de duda. Ese desplazamiento es el terreno común del que crecerá la filosofía moderna.",
    },
    {
      type: "info",
      continues: true,
      title: "El escepticismo de Montaigne",
      body: "A esas raíces se suma un cuarto proceso, de origen científico más que filosófico: la nueva concepción matemática de la naturaleza que se desarrolla en paralelo durante el siglo XVI y que alcanza su formulación decisiva en el siglo XVII, con Copérnico, Kepler, Galileo y Newton. Esa transformación, contemporánea de las anteriores y también enfrentada al aristotelismo escolástico, será el tema de la próxima clase.",
    },
  ],
};
