export default {
  num: 9,
  transcript: 9,
  title: "Hume: hábito y conexión necesaria",
  source: "",
  feed: [
    {
      type: "info",
      title: "El empirismo consecuente",
      body: "David Hume (1711–1776) representa la versión más sofisticada y radical del empirismo moderno. Su obra desarrolla hasta las últimas consecuencias la tendencia antimetafísica que ya estaba presente en Bacon, Locke y Berkeley: no sólo cuestiona los supuestos del racionalismo continental, sino que somete a examen crítico convicciones muy básicas del sentido común, entre ellas la misma noción de causa.",
    },
    {
      type: "info",
      continues: true,
      title: "El empirismo consecuente",
      body: "Esta tendencia antimetafísica, que Bacon dirige contra los ídolos de la razón dogmática y que Berkeley radicaliza al eliminar la materia como sustrato oculto, encuentra en Hume su culminación: los problemas metafísicos tradicionales —la existencia de Dios, la inmortalidad del alma, la sustancia— no son simplemente difíciles de resolver, sino que carecen de todo fundamento en la experiencia, y por eso mismo no pueden resolverse nunca por vía racional.",
    },
    {
      type: "info",
      continues: true,
      title: "El empirismo consecuente",
      body: "Frente a Descartes y Leibniz, para quienes la razón puede alcanzar verdades necesarias sobre la realidad misma, y frente a Locke y Berkeley, que ya habían restringido drásticamente el alcance de la metafísica, Hume se pregunta hasta qué punto la propia razón humana puede justificar racionalmente sus creencias más elementales sobre el mundo, incluida la creencia en que existen relaciones causales objetivas entre los hechos.",
    },
    {
      type: "info",
      continues: true,
      title: "El empirismo consecuente",
      body: "Hume expone su filosofía en dos obras principales: el Tratado de la naturaleza humana (1739), escrito en su juventud, y la más accesible Investigación sobre el entendimiento humano (1748), donde retoma y reformula sus argumentos centrales. En ambas se ocupa, entre otros problemas, del análisis de la noción de **conexión necesaria**, cuya relación con la libertad humana es uno de los puntos más discutidos de su pensamiento.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue a Hume de Locke y de Berkeley?",
      options: [
        "examina también las creencias del sentido común",
        "rechaza el empirismo y vuelve al racionalismo",
        "acepta las ideas innatas en el caso de las matemáticas",
        "sostiene que la materia existe con independencia",
      ],
      answer: 0,
      explain: "Locke y Berkeley ya habían restringido el alcance de la metafísica. Hume va más lejos: pone a prueba convicciones tan básicas como la de que existan relaciones causales objetivas entre los hechos, y concluye que la razón no puede justificarlas.",
    },
    {
      type: "info",
      title: "Impresiones e ideas",
      body: "Una novedad decisiva del análisis humeano consiste en diferenciar dos tipos de «percepciones» o estados de conciencia: **impresiones** e **ideas**. Las impresiones se perciben de modo directo; las ideas son derivadas de ellas, copias más débiles que la mente retiene, combina o recuerda después de haber tenido la impresión original.",
    },
    {
      type: "info",
      continues: true,
      title: "Impresiones e ideas",
      body: "Las impresiones son, a su vez, de dos clases: las de **sensación**, que provienen del mundo exterior a través de los cinco sentidos, y las de **reflexión**, que provienen de nuestra propia interioridad, como los estados de ánimo o los deseos. Tanto las impresiones como las ideas pueden ser simples o compuestas, y las impresiones, por ser directas, resultan siempre más vivaces e intensas que las ideas correspondientes: el sabor del chocolate es más intenso que su recuerdo.",
    },
    {
      type: "info",
      continues: true,
      title: "Impresiones e ideas",
      body: "El espíritu humano recibe impresiones a través de los sentidos y luego mezcla, compone y divide ese material según tres leyes psicológicas de asociación que Hume cree haber descubierto: semejanza, contigüidad y causalidad. Así podemos formar la idea de una montaña de oro, que nunca vimos, combinando las ideas de montaña y de oro, cada una derivada de impresiones reales; del mismo modo formamos la idea de Dios, reconociendo en nosotros ciertas facultades —conocer, querer, obrar— y atribuyéndoselas, sin límites, a un ser imaginado.",
    },
    {
      type: "info",
      continues: true,
      title: "Impresiones e ideas",
      body: "De este principio se sigue un criterio para juzgar la validez objetiva de una idea: quien carece de una impresión no puede tener la idea correspondiente —un ciego de nacimiento no tiene idea del color rojo—, y una idea es objetivamente válida sólo si concuerda con las impresiones de las que deriva. Frente a cualquier idea dudosa, Hume propone tres preguntas: de qué ideas simples se compone, de qué impresiones derivan esas ideas simples, y si realmente se corresponden con ellas.",
    },
    {
      type: "quiz",
      question: "El criterio de Hume para juzgar si una idea es válida es…",
      options: [
        "si concuerda con las impresiones de que deriva",
        "si puede formularse sin contradicción lógica",
        "si resulta útil para la vida práctica diaria",
        "si la comparten todos los seres racionales",
      ],
      answer: 0,
      explain: "Quien carece de una impresión no puede tener la idea correspondiente: un ciego de nacimiento no tiene idea del rojo. Ante una idea dudosa, Hume pregunta de qué ideas simples se compone, de qué impresiones derivan esas ideas simples, y si de veras se corresponden con ellas.",
    },
    {
      type: "classify",
      question: "¿Cada caso es una impresión o una idea, según Hume?",
      groups: ["Impresión", "Idea"],
      items: [
        { text: "El sabor del chocolate mientras se come", group: 0 },
        { text: "El recuerdo de ese sabor", group: 1 },
        { text: "Un dolor de muelas en este momento", group: 0 },
        { text: "La montaña de oro que nadie vio nunca", group: 1 },
        { text: "El deseo que se siente ahora", group: 0 },
        { text: "La noción de Dios como ser sin límites", group: 1 },
      ],
      explain: "Las impresiones se perciben de modo directo y son siempre más vivaces; las ideas son copias más débiles que la mente retiene, combina o recuerda. La montaña de oro y la idea de Dios son ideas compuestas: se forman combinando otras que sí derivan de impresiones reales.",
    },
    {
      type: "info",
      title: "La idea de causalidad puesta a prueba",
      body: "Entre las ideas que más fácilmente engañan sobre su propio origen está la de **causalidad**, admitida sin cuestionamientos tanto por la filosofía anterior como por la ciencia natural y el sentido común. Se supone que expresa una relación necesaria entre dos fenómenos sucesivos —causa y efecto— tal que, si el primero ocurre, es imposible que el segundo no ocurra; y se supone, además, que esa relación existe objetivamente en la realidad, se la conozca o no.",
    },
    {
      type: "info",
      continues: true,
      title: "La idea de causalidad puesta a prueba",
      body: "Esta doble pretensión —necesidad y referencia a hechos reales— resulta sospechosa para un empirista, porque el propio Hume ha establecido que todo conocimiento humano es o bien demostrativo (necesario, pero vacío de contenido fáctico) o bien fáctico (referido a la realidad, pero contingente). La idea de causalidad parece reclamar, imposiblemente, las ventajas de ambos tipos de conocimiento a la vez, y por eso Hume la somete al criterio empirista de validez.",
    },
    {
      type: "info",
      continues: true,
      title: "La idea de causalidad puesta a prueba",
      body: "Para exponer su crítica, Hume recurre al célebre ejemplo de la mesa de billar: una bola en movimiento choca contra otra que está en reposo y la pone en movimiento. Decimos entonces que el primer movimiento «causa» el segundo, o que le «transmite» una fuerza, dando por supuesto que la relación entre ambos es necesaria: si repitiéramos el experimento en las mismas condiciones, el resultado sería siempre exactamente el mismo.",
    },
    {
      type: "quiz",
      question: "¿Por qué le resulta sospechosa a Hume la idea de causalidad?",
      options: [
        "pretende ser necesaria y referirse a hechos",
        "no aparece en ninguna de las ciencias naturales",
        "es una invención reciente de los racionalistas",
        "supone que el futuro será distinto del pasado",
      ],
      answer: 0,
      explain: "Para Hume todo conocimiento es demostrativo —necesario, pero vacío de contenido fáctico— o fáctico —referido a la realidad, pero contingente. La causalidad reclama las ventajas de los dos a la vez, y por eso hay que someterla al criterio empirista.",
    },
    {
      type: "info",
      title: "El análisis de la conexión necesaria",
      body: "Aplicando su propio criterio, Hume descompone la idea compuesta de causación en cuatro ideas simples: la de causa (el movimiento de la primera bola), la de efecto (el movimiento de la segunda), la de sucesión temporal (la primera ocurre antes que la segunda), y la de **conexión necesaria** entre ambas, es decir la fuerza que supuestamente produce el segundo movimiento a partir del primero.",
    },
    {
      type: "info",
      continues: true,
      title: "El análisis de la conexión necesaria",
      body: "Las tres primeras ideas tienen impresiones correspondientes fáciles de identificar: vemos el primer movimiento, vemos el segundo, vemos que uno precede al otro. Pero por más atención que pongamos en la mesa de billar, en ningún momento vemos la fuerza transmitida de una bola a otra: lo único que observamos es la sucesión de dos movimientos, nunca el vínculo necesario que supuestamente los ata.",
    },
    {
      type: "info",
      continues: true,
      title: "El análisis de la conexión necesaria",
      body: "Tampoco puede tratarse de una idea de origen puramente racional o lógico, porque no hay contradicción alguna en imaginar que, tras el choque, la segunda bola se quede quieta, desaparezca o se hunda en la mesa: no es como afirmar que un mismo paño es a la vez verde y no verde, algo lógicamente imposible. Que la segunda bola se mueva después del choque es perfectamente imaginable de otro modo; sólo la experiencia repetida nos hace pensarlo como necesario.",
    },
    {
      type: "info",
      continues: true,
      title: "El análisis de la conexión necesaria",
      body: "Como la idea de conexión necesaria no proviene ni de la experiencia externa ni de la razón, Hume debe buscarle otro origen: lo encuentra en un **hábito** psicológico. Cuando hemos experimentado repetidamente en el pasado que a un tipo de hecho le sigue otro, y ese primer hecho vuelve a ocurrir, la mente proyecta hacia el futuro esa secuencia y espera que el segundo hecho también ocurra. Esa expectativa habitual, subjetiva, es lo único real detrás de la supuesta necesidad objetiva de la causalidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El análisis de la conexión necesaria",
      body: "Este hábito, aunque subjetivo, es enormemente útil para la vida práctica: sin él no podríamos prever que el fuego quema, que el pan alimenta o que no se puede respirar bajo el agua, y correríamos peligros constantes. Incluso los animales realizan inferencias de este tipo a partir de su experiencia previa. Pero su utilidad no lo convierte en una ley objetiva del mundo: sigue siendo, para Hume, una ley de asociación psicológica que nada nos dice sobre la estructura última de la realidad.",
    },
    {
      type: "quiz",
      question: "En el ejemplo de la mesa de billar, ¿qué es lo que Hume no encuentra?",
      options: [
        "la fuerza que pasa de una bola a la otra",
        "el movimiento de la segunda bola",
        "la sucesión temporal entre los dos hechos",
        "el choque entre las dos bolas",
      ],
      answer: 0,
      explain: "Las otras tres ideas simples tienen su impresión correspondiente: vemos el primer movimiento, vemos el segundo, vemos que uno precede al otro. La cuarta, la conexión necesaria, no se ve nunca: por más atención que se ponga, sólo se observa la sucesión.",
    },
    {
      type: "quiz",
      question: "Que la segunda bola se mueva tras el choque no es lógicamente necesario porque…",
      options: [
        "no hay contradicción en imaginar otro final",
        "la física de la época todavía no lo demostraba",
        "nadie repitió el experimento suficientes veces",
        "las leyes del movimiento admiten excepciones",
      ],
      answer: 0,
      explain: "Que la bola se quede quieta, desaparezca o se hunda en la mesa es perfectamente imaginable: no es como decir que un mismo paño es verde y no verde a la vez. Sólo la experiencia repetida nos hace pensar ese desenlace como necesario.",
    },
    {
      type: "short",
      question: "¿A qué le atribuye Hume el origen de la idea de conexión necesaria?",
      answers: ["el hábito", "hábito", "la costumbre", "costumbre"],
      explain: "Como la idea no viene ni de la experiencia externa ni de la razón, Hume le busca otro origen y lo encuentra en un hábito psicológico: la mente proyecta al futuro una secuencia que se repitió en el pasado. Esa expectativa subjetiva es lo único real detrás de la supuesta necesidad objetiva.",
    },
    {
      type: "info",
      title: "El problema de la inducción",
      body: "El análisis de la causalidad conecta con una dificultad más general que Hume plantea contra el método inductivo defendido por Bacon: ninguna cantidad de casos pasados observados —por muchos que sean— puede demostrar lógicamente que el futuro se comportará igual que el pasado. Que el sol haya salido todas las mañanas hasta hoy no prueba, con la necesidad de una demostración matemática, que vaya a salir mañana.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema de la inducción",
      body: "Esta dificultad, conocida después como el **problema de la inducción**, muestra que la inferencia de lo observado a lo no observado no descansa en ningún argumento racional concluyente, sino en la misma costumbre que explica la idea de conexión necesaria: esperamos que el futuro se parezca al pasado porque estamos habituados a que así ocurra, no porque podamos demostrarlo. Toda la física de su época, que pretende formular leyes universales a partir de la observación, queda así apoyada sobre un fundamento que la razón, por sí sola, no puede justificar.",
    },
    {
      type: "quiz",
      question: "El problema de la inducción consiste en que…",
      options: [
        "los casos pasados no demuestran los futuros",
        "la observación siempre contiene errores de medida",
        "no se pueden observar todos los casos posibles",
        "las leyes de la física cambian con el tiempo",
      ],
      answer: 0,
      explain: "Que el sol haya salido todas las mañanas hasta hoy no prueba, con la necesidad de una demostración matemática, que vaya a salir mañana. La inferencia de lo observado a lo no observado descansa en la misma costumbre que explica la conexión necesaria, y es la objeción directa al método inductivo de Bacon.",
    },
    {
      type: "info",
      title: "¿Y si la conexión viniera de adentro?",
      body: "Antes de aceptar que la idea de conexión necesaria no proviene de ninguna impresión externa, cabe preguntarse si no podría derivar de una impresión interna, de reflexión: la que sentimos, por ejemplo, cuando movemos voluntariamente un brazo. Hume examina esta posibilidad y la rechaza con tres argumentos.",
    },
    {
      type: "info",
      continues: true,
      title: "¿Y si la conexión viniera de adentro?",
      body: "Primero, si tuviéramos realmente una impresión del poder de la voluntad sobre el cuerpo, entenderíamos el mecanismo por el cual la mente mueve la materia; pero no lo entendemos en absoluto, aunque creamos sentir ese poder. Segundo, ese supuesto poder es arbitrario: podemos mover ciertos órganos y no otros, y sólo descubrimos por experiencia cuáles, nunca de antemano —algunas personas pueden mover las orejas, otras no, y ninguna sabe por qué antes de intentarlo—. Tercero, la anatomía revela una larga cadena de procesos intermedios entre la voluntad y el movimiento del cuerpo, de los que no tenemos ninguna conciencia directa: si tuviéramos una impresión genuina de ese poder, conoceríamos también esos procesos.",
    },
    {
      type: "info",
      continues: true,
      title: "¿Y si la conexión viniera de adentro?",
      body: "Hume extiende esta crítica a la doctrina ocasionalista, que atribuye a la voluntad divina el verdadero e inmediato principio de todo efecto, para no tener que explicar la conexión entre voluntad humana y movimiento corporal. La califica de «demasiado atrevida»: desemboca en conclusiones alejadas de la vida y la experiencia comunes, y trasladar el problema a un Ser Supremo no lo resuelve, porque seguimos sin tener ninguna impresión directa de cómo esa voluntad divina, o cualquier voluntad, produce sus efectos.",
    },
    {
      type: "quiz",
      question: "¿Por qué rechaza Hume que la conexión necesaria venga de sentir la propia voluntad?",
      options: [
        "no entendemos cómo la mente mueve el cuerpo",
        "la voluntad humana no produce ningún efecto",
        "sólo Dios tiene un poder causal verdadero",
        "las impresiones de reflexión no existen",
      ],
      answer: 0,
      explain: "Es el primero de tres argumentos. Los otros dos: el poder es arbitrario, porque descubrimos por experiencia qué órganos podemos mover y cuáles no; y la anatomía revela una cadena de procesos intermedios de los que no tenemos conciencia alguna. La tercera opción es el ocasionalismo, que Hume también rechaza por «demasiado atrevido».",
    },
    {
      type: "info",
      title: "Necesidad y libertad humana",
      body: "El análisis de la conexión necesaria tiene consecuencias directas para el problema de la libertad. Para Hume, la necesidad natural consiste enteramente en dos elementos: la conjunción constante entre dos tipos de hechos, y el hábito de la mente que infiere la presencia de uno a partir del otro. Este mismo patrón, sostiene, se observa también en la conducta humana: los mismos motivos van seguidos regularmente de las mismas acciones.",
    },
    {
      type: "info",
      continues: true,
      title: "Necesidad y libertad humana",
      body: "A partir de esto, Hume redefine la libertad: no la hace consistir en la ausencia de esa necesidad —no es libre quien actúa sin motivos que lo expliquen—, sino en la posibilidad de actuar o no actuar según lo que la propia voluntad decida, sin coerción externa. Definida así, la libertad resulta compatible con la necesidad, y no su opuesta: es «libertad de espontaneidad», no libertad de indiferencia respecto de toda causa.",
    },
    {
      type: "info",
      continues: true,
      title: "Necesidad y libertad humana",
      body: "Hume sostiene, además, que la necesidad no sólo es compatible con la moral, sino que la hace posible. Si los motivos, premios y castigos no determinaran de manera uniforme la conducta, la ley y la vida social serían imposibles: nadie podría prever el efecto de una pena o de una recompensa. Y si las acciones no procedieran necesariamente del carácter durable de quien las realiza, sino del puro azar, no podrían atribuirse a nadie ni merecer juicio moral alguno: la responsabilidad exige, precisamente, esa conexión entre el agente y su acto que la doctrina del azar rompería.",
    },
    {
      type: "quiz",
      question: "Hume define la libertad como…",
      options: [
        "poder actuar o no según la propia voluntad",
        "la ausencia de toda causa que determine el acto",
        "la capacidad de elegir entre el bien y el mal",
        "el conocimiento de las causas que nos mueven",
      ],
      answer: 0,
      explain: "No la opone a la necesidad: es «libertad de espontaneidad», ausencia de coerción externa, y no libertad de indiferencia respecto de toda causa. Hume sostiene además que la necesidad hace posible la moral: si las acciones surgieran del azar y no del carácter durable del agente, no podrían atribuirse a nadie.",
    },
    {
      type: "info",
      title: "Frente a Spinoza, y frente a lo que falta explicar",
      body: "La posición de Hume puede compararse con la de Spinoza, visto en una clase anterior. Ambos niegan el libre albedrío entendido como capacidad de elegir sin causa alguna: para Spinoza, todo lo que sucede está necesariamente determinado por la naturaleza única, de la que Dios es su fundamento inmanente; para Hume, la necesidad se reduce a la conjunción constante entre hechos y a la inferencia habitual de la mente, sin que exista ningún poder oculto que fuerce al efecto a seguir de la causa.",
    },
    {
      type: "info",
      continues: true,
      title: "Frente a Spinoza, y frente a lo que falta explicar",
      body: "También coinciden, pese a negar el libre albedrío, en conservar una noción de libertad: Spinoza la entiende como actividad, como el grado en que algo se sigue de la propia naturaleza sin coerción externa ni servidumbre a las pasiones; Hume la entiende como espontaneidad, como ausencia de violencia o coacción externa sobre la propia voluntad. Ninguno de los dos identifica la libertad con la indeterminación.",
    },
    {
      type: "match",
      question: "Uní cada pieza con lo que le corresponde",
      pairs: [
        { left: "Tratado de la naturaleza humana", right: "La obra de juventud, de 1739" },
        { left: "Investigación sobre el entendimiento humano", right: "La reformulación más accesible, de 1748" },
        { left: "Conexión necesaria", right: "La idea simple sin impresión que la respalde" },
        { left: "Hábito", right: "La expectativa que la repetición deja en la mente" },
        { left: "Libertad de espontaneidad", right: "Actuar sin coerción, compatible con la necesidad" },
      ],
      explain: "El recorrido va de un criterio —toda idea válida deriva de una impresión— a una consecuencia que Hume acepta sin poder resolver: si la necesidad causal es un hábito proyectado sobre el mundo, la ciencia natural queda sin fundamento racional.",
    },
    {
      type: "info",
      continues: true,
      title: "Frente a Spinoza, y frente a lo que falta explicar",
      body: "La crítica de Hume a la conexión necesaria deja, sin embargo, un problema abierto que él mismo no resuelve: si la necesidad causal no es más que un hábito subjetivo proyectado sobre el mundo, ¿qué fundamento racional queda para la ciencia natural, que supone precisamente que los fenómenos están conectados necesariamente según leyes? Hume acepta vivir con esta conclusión incómoda, apelando a la naturaleza y a la costumbre para seguir actuando como si el mundo fuera necesario, sin poder demostrarlo. Esa pregunta sin responder quedará pendiente hasta que, más adelante en este curso, la filosofía de Kant intente ofrecerle una salida distinta.",
    },
  ],
};
