export default {
  num: 8,
  transcript: 8,
  title: "El empirismo inglés: Bacon, Locke, Berkeley",
  source: "",
  feed: [
    {
      type: "info",
      title: "La experiencia como fuente del conocimiento",
      body: "Frente al racionalismo continental estudiado en la clase anterior, el **empirismo** inglés sostiene que todo conocimiento sobre la realidad se adquiere a través de los sentidos: la razón sólo ordena y compara los materiales que la experiencia le proporciona, pero no aporta contenido propio previo a ella. Esta tradición recorre Inglaterra entre 1620 y 1713, y culmina, ya en el siglo XVIII, con David Hume.",
    },
    {
      type: "info",
      continues: true,
      title: "La experiencia como fuente del conocimiento",
      body: "El origen de esta valoración de la experiencia puede rastrearse hasta la propia física del siglo XVII. Frente a la interpretación cartesiana de la nueva ciencia, en la que la experiencia sensorial era apenas un corolario secundario de la demostración racional, Galileo Galilei (1564–1642) había antepuesto la experiencia a los discursos abstractos y a la cultura libresca: para él, el conocimiento de los fenómenos naturales mediante la observación es el punto de partida de toda investigación de sus causas. Los empiristas ingleses radicalizan esta prioridad concedida a la experiencia.",
    },
    {
      type: "info",
      continues: true,
      title: "La experiencia como fuente del conocimiento",
      body: "Como con el racionalismo, conviene no imaginar al empirismo como una escuela homogénea: hay diferencias importantes entre Bacon, Locke, Berkeley y Hume, que discuten entre sí tanto como con los racionalistas continentales. Lo que los une es un rechazo compartido a la tesis de que existan principios racionales evidentes que se correspondan de antemano con la estructura objetiva de la realidad, tal como Descartes había intentado garantizar mediante la veracidad divina.",
    },
    {
      type: "info",
      continues: true,
      title: "La experiencia como fuente del conocimiento",
      body: "Puede contraponerse el empirismo al racionalismo atendiendo a los mismos cuatro puntos usados en la clase anterior. Frente a la razón como fuente privilegiada de conocimiento, el empirismo pone los sentidos; frente a una mente dotada de contenidos previos, una mente vacía que la experiencia va llenando; frente a la matemática como modelo ideal de saber, la observación metódica de la naturaleza; y frente a los grandes problemas metafísicos, la sospecha de que muchos de ellos son pseudoproblemas.",
    },
    {
      type: "quiz",
      question: "La tesis central del empirismo es que…",
      options: [
        "la razón ordena materiales que no aporta ella",
        "los sentidos engañan y la razón los corrige",
        "sólo la matemática alcanza conocimiento cierto",
        "la mente posee principios evidentes previos",
      ],
      answer: 0,
      explain: "Los empiristas no niegan que la razón haga algo: ordena, compara y abstrae. Lo que niegan es que aporte contenido propio antes de la experiencia. De ahí se siguen el rechazo de las ideas innatas y la sospecha de que muchos problemas metafísicos son pseudoproblemas.",
    },
    {
      type: "info",
      title: "Bacon y la crítica de los ídolos",
      body: "Francis Bacon (1561–1626) puede considerarse el primer empirista moderno. En el Novum Organum (1620), sostiene que el conocimiento de la naturaleza se ha visto obstaculizado por ciertos prejuicios que él llama **ídolos**: como los ídolos de las religiones animistas, fascinan y engañan a la vez a la mente humana, impidiéndole acceder directamente a los hechos.",
    },
    {
      type: "info",
      continues: true,
      title: "Bacon y la crítica de los ídolos",
      body: "Bacon distingue varios tipos de ídolos: los que provienen de la propia idiosincrasia de cada individuo, los que provienen del lenguaje y de la cultura compartida con los demás, y los que provienen de los sistemas filosóficos tradicionales, transmitidos acríticamente de maestro a discípulo. Contra el poder de estos ídolos, propone un método que reemplace la especulación por la observación metódica y sistemática de los hechos.",
    },
    {
      type: "info",
      continues: true,
      title: "Bacon y la crítica de los ídolos",
      body: "Ese método es la **inducción**: el procedimiento por el cual se establece la verdad de una proposición general a partir de la acumulación de casos particulares comprobados empíricamente. Así, la proposición «los cuerpos se dilatan con el calor» se sigue inductivamente de observar que el cuerpo 1 se dilata con el calor, que el cuerpo 2 también lo hace, que el cuerpo 3 también, y así sucesivamente. Aunque Hume rechazará después la validez lógica estricta de este procedimiento, la confianza baconiana en la experiencia como fuente del conocimiento se mantiene como núcleo de toda la tradición empirista posterior.",
    },
    {
      type: "info",
      continues: true,
      title: "Bacon y la crítica de los ídolos",
      body: "Para Bacon, este método inductivo no es un simple registro pasivo de observaciones sueltas, sino una disciplina que exige organizar sistemáticamente los datos recogidos, comparar casos positivos y negativos, y eliminar progresivamente las hipótesis que la experiencia contradice. Es, en ese sentido, un programa para toda una nueva ciencia experimental, pensado explícitamente como alternativa al método deductivo de la lógica aristotélica heredada de la escolástica.",
    },
    {
      type: "quiz",
      question: "Los ídolos de Bacon son…",
      options: [
        "prejuicios que estorban el acceso a los hechos",
        "las falsas religiones que la ciencia debe combatir",
        "los errores de cálculo en la observación empírica",
        "los principios de la lógica aristotélica heredada",
      ],
      answer: 0,
      explain: "Bacon distingue los que vienen de la idiosincrasia de cada uno, los que vienen del lenguaje y la cultura compartida, y los que vienen de los sistemas filosóficos transmitidos acríticamente de maestro a discípulo. Los llama ídolos porque, como los de las religiones animistas, fascinan y engañan a la vez.",
    },
    {
      type: "short",
      question: "¿Cómo llama Bacon al método que va de los casos particulares a la proposición general?",
      answers: ["inducción", "método inductivo"],
      explain: "«Los cuerpos se dilatan con el calor» se sigue de observar que el cuerpo 1 se dilata, que el 2 también, y así sucesivamente. Para Bacon no es un registro pasivo: exige organizar los datos, comparar casos positivos y negativos y descartar las hipótesis que la experiencia contradice.",
    },
    {
      type: "info",
      title: "Locke contra las ideas innatas",
      body: "John Locke (1632–1704) da al empirismo su formulación sistemática. En el primer libro de su Ensayo sobre el entendimiento humano (1690), se propone refutar uno por uno los argumentos con los que la tradición racionalista sostenía la existencia de ideas innatas, discutidas en la clase anterior a propósito de Descartes y Leibniz.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke contra las ideas innatas",
      body: "Contra el innatismo, Locke sostiene que la mente humana es, antes de cualquier experiencia, semejante a una **tabla rasa**: un papel en blanco sobre el cual los datos sensoriales pueden ir «imprimiéndose». Ninguna idea, ni siquiera las matemáticas o la de Dios, está presente en la mente al nacer; todas se forman a partir de lo recibido por los sentidos y de la reflexión posterior sobre esos materiales.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke contra las ideas innatas",
      body: "Para explicar la formación del conocimiento sin recurrir a lo innato, Locke distingue entre **cualidades primarias** y **cualidades secundarias** de los cuerpos. Las primarias —extensión, figura, movimiento, número— pertenecen objetivamente a los cuerpos mismos, con independencia de que alguien los perciba. Las secundarias —color, sonido, sabor, olor— no existen tal cual las percibimos en los objetos, sino que son el efecto que ciertas propiedades objetivas de los cuerpos producen en nuestros órganos sensoriales.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke contra las ideas innatas",
      body: "Esta distinción retoma, en clave empirista, la misma idea que ya aparecía en la física mecanicista: sólo lo cuantificable es plenamente objetivo, mientras que las cualidades sensibles dependen del modo en que el sujeto percibe. Locke, sin embargo, no deriva de esta física una metafísica de la sustancia única como Spinoza, sino una teoría del conocimiento centrada en el origen empírico de todas las ideas humanas, simples o complejas.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke contra las ideas innatas",
      body: "Locke distingue también, dentro de las ideas que la mente recibe o forma, entre **ideas simples** —las que llegan directamente por un solo sentido, o por reflexión sobre las propias operaciones mentales, y que la mente no puede fabricar ni destruir por sí sola— e **ideas complejas**, que el entendimiento construye combinando, comparando o abstrayendo a partir de las ideas simples ya recibidas. Toda la arquitectura del conocimiento humano se levanta, para Locke, sobre este material sensorial elemental.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke contra las ideas innatas",
      body: "Con esta arquitectura, Locke cree haber desactivado el problema que el racionalismo resolvía apelando a lo innato: cómo es posible que tengamos ideas generales y abstractas —como la de triángulo en general, sin ángulos ni lados determinados— si todo lo que percibimos son siempre casos particulares y concretos. Su respuesta es que esas ideas generales resultan de un proceso activo de abstracción que la mente realiza sobre las ideas particulares recibidas, no de un contenido ya presente de antemano en el entendimiento.",
    },
    {
      type: "quiz",
      question: "La tabla rasa de Locke afirma que…",
      options: [
        "ninguna idea está en la mente al nacer",
        "los sentidos no pueden engañarnos nunca",
        "las matemáticas se aprenden por costumbre",
        "la reflexión no produce ideas nuevas",
      ],
      answer: 0,
      explain: "La mente es, antes de toda experiencia, un papel en blanco sobre el que los datos sensoriales se imprimen. Ninguna idea, ni la de Dios ni las matemáticas, está presente al nacer: todas se forman a partir de lo recibido por los sentidos y de la reflexión posterior sobre esos materiales.",
    },
    {
      type: "classify",
      question: "¿Cada cualidad es primaria o secundaria según Locke?",
      groups: ["Primaria", "Secundaria"],
      items: [
        { text: "La extensión de un cuerpo", group: 0 },
        { text: "El color que vemos en él", group: 1 },
        { text: "Su figura", group: 0 },
        { text: "Su sabor", group: 1 },
        { text: "Su movimiento", group: 0 },
        { text: "El sonido que produce", group: 1 },
      ],
      explain: "Las primarias pertenecen objetivamente a los cuerpos, con independencia de que alguien los perciba. Las secundarias no existen tal cual las percibimos: son el efecto que ciertas propiedades objetivas producen en nuestros órganos sensoriales. Es la misma idea de la física mecanicista, trasladada a la teoría del conocimiento.",
    },
    {
      type: "info",
      title: "El conocimiento matemático y el conocimiento fáctico",
      body: "Para el empirismo, el conocimiento matemático —el **conocimiento demostrativo**— no tiene por objeto la realidad misma, como pretendían los racionalistas, sino que se reduce a un lenguaje abstracto sobre relaciones entre nociones definidas por convención. Es universal y necesario, pero justamente por eso no dice nada directo sobre lo que existe fuera de la mente.",
    },
    {
      type: "info",
      continues: true,
      title: "El conocimiento matemático y el conocimiento fáctico",
      body: "El **conocimiento fáctico**, en cambio, es el que versa sobre los hechos reales: es a posteriori, es decir, particular, contingente y dependiente enteramente de la experiencia. Esta distinción entre dos tipos de conocimiento —necesario pero vacío de contenido real, o contingente pero referido a hechos— será decisiva para la crítica de Hume a la idea de causalidad, que ocupará la próxima clase.",
    },
    {
      type: "info",
      continues: true,
      title: "El conocimiento matemático y el conocimiento fáctico",
      body: "Esta oposición entre conocimiento demostrativo y conocimiento fáctico tiene una consecuencia importante para las ciencias naturales: si el conocimiento matemático no dice nada sobre la realidad, y el conocimiento fáctico es siempre particular y contingente, entonces las leyes generales de la física, que pretenden ser a la vez necesarias y referidas a hechos, ocupan un lugar problemático que el propio empirismo tendrá que examinar con cuidado, y que será precisamente el punto de partida de la crítica humeana a la idea de causalidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El conocimiento matemático y el conocimiento fáctico",
      body: "De estas premisas se sigue también una actitud distinta hacia la metafísica. Mientras el racionalismo aborda sus problemas —la existencia de Dios, la inmortalidad del alma, la estructura de las sustancias— desde un punto de vista especulativo, el empirismo tiende a considerarlos pseudoproblemas: cuestiones que no remiten a ningún objeto de la experiencia sensorial, sino a productos de la imaginación humana proyectados como si fueran realidades.",
    },
    {
      type: "quiz",
      question: "Para el empirismo, el conocimiento matemático…",
      options: [
        "es necesario pero no dice nada de lo real",
        "es la única vía de acceso a la naturaleza",
        "depende de la experiencia igual que la física",
        "describe la estructura objetiva de las cosas",
      ],
      answer: 0,
      explain: "Se reduce a un lenguaje abstracto sobre relaciones entre nociones definidas por convención. Su contrapartida es el conocimiento fáctico, que sí versa sobre hechos pero es particular y contingente. Entre las dos casillas quedan incómodas las leyes de la física, que pretenden ser necesarias y referirse a hechos: de ahí arranca Hume.",
    },
    {
      type: "info",
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "George Berkeley (1685–1753) lleva el empirismo de Locke a una conclusión que el propio Locke no había extraído. Si, como sostiene Locke, sólo conocemos directamente nuestras propias ideas —nunca los objetos externos en sí mismos—, entonces la distinción entre cualidades primarias, supuestamente objetivas, y secundarias, meramente subjetivas, resulta insostenible: también la extensión, la figura y el movimiento sólo se nos dan como ideas percibidas, nunca como propiedades de una materia independiente de la mente.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "En los Principios del conocimiento humano (1710), Berkeley formula el principio que resume su filosofía: **esse est percipi**, ser es ser percibido. Para los objetos que no piensan —una mesa, una piedra, un color— existir no significa nada más que ser percibidos por una mente, sea la de un ser humano o la de Dios. No hay un «sustrato material» oculto detrás de las cualidades que percibimos, porque nunca tenemos experiencia de tal sustrato: sólo percibimos ideas, nunca la materia que supuestamente las causaría.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "De ahí que Berkeley defienda el **inmaterialismo**: la tesis de que no existe una sustancia material distinta de las mentes y sus percepciones. Negar la materia no significa, para Berkeley, negar la existencia de las cosas que vemos y tocamos —la mesa sigue estando ahí—, sino negar que detrás de esas cosas percibidas haya, además, una sustancia inerte e imperceptible que la física y la metafísica postulan sin ninguna evidencia empírica que las respalde.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "Una objeción obvia al inmaterialismo es que las cosas parecen seguir existiendo cuando nadie las percibe: la mesa de una habitación vacía no desaparece cuando cerramos la puerta. Berkeley responde que las cosas no dejan de existir porque las percibe, en todo momento, la mente infinita de Dios: la continuidad y el orden regular del mundo sensible dependen, en última instancia, de esa percepción divina permanente, que además explica por qué las percepciones humanas resultan tan ordenadas y previsibles.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "Berkeley no niega, por lo demás, que haya una diferencia entre percibir algo e imaginarlo: las ideas que llamamos «reales» —las que forman lo que llamamos el mundo físico— son más vivaces, más ordenadas y más independientes de nuestra voluntad que las que producimos libremente con la imaginación. Esa regularidad, para Berkeley, es obra de Dios, que las produce directamente en nuestra mente siguiendo leyes constantes, a las que la ciencia natural puede legítimamente describir sin necesidad de postular una materia detrás de ellas.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "Berkeley presenta el inmaterialismo no como una excentricidad, sino como la aplicación más consecuente del principio empirista según el cual todo conocimiento deriva de la experiencia: si nunca experimentamos la materia en sí misma, sino sólo ideas, entonces postular una materia detrás de las ideas es exactamente el tipo de especulación vacía que el empirismo había denunciado en la metafísica racionalista. Locke se detiene a mitad de camino; Berkeley completa el movimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "Berkeley insiste en que su tesis no es escéptica, sino que busca defender el sentido común contra las ficciones de los filósofos: quien niega la materia no niega ninguna de las cosas que efectivamente experimentamos, sólo niega una entidad abstracta, imperceptible por definición, que ni el sentido común ni la ciencia necesitan para explicar nada. Lo único que se pierde, según Berkeley, es un supuesto metafísico sin ningún respaldo empírico.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "El motivo de fondo de Berkeley es también religioso: le preocupa que el materialismo mecanicista del siglo XVII, al describir la naturaleza como una máquina autosuficiente regida por leyes ciegas, abra la puerta al ateísmo y al escepticismo respecto de la providencia divina. Al eliminar la materia y hacer depender el orden del mundo sensible directamente de la percepción de Dios, Berkeley cree devolverle a la divinidad un papel activo y permanente en la explicación de la naturaleza, papel que el mecanicismo tendía a volver superfluo.",
    },
    {
      type: "quiz",
      question: "«Esse est percipi» significa que…",
      options: [
        "para las cosas, existir es ser percibidas",
        "sólo existe lo que alguien puede demostrar",
        "la percepción es la única facultad fiable",
        "las ideas existen aunque nadie las piense",
      ],
      answer: 0,
      explain: "Vale para los objetos que no piensan: una mesa, una piedra, un color. No hay un sustrato material oculto detrás de las cualidades percibidas, porque de ese sustrato nunca tenemos experiencia. Berkeley no niega la mesa: niega la materia que se postula detrás de ella.",
    },
    {
      type: "quiz",
      question: "¿Cómo responde Berkeley a que las cosas parezcan seguir existiendo sin nadie que las vea?",
      options: [
        "Dios las percibe en todo momento",
        "la materia las sostiene mientras nadie mira",
        "seguimos recordándolas y eso las mantiene",
        "sólo existen las que alguien está mirando",
      ],
      answer: 0,
      explain: "La percepción divina permanente explica para Berkeley tanto la continuidad de las cosas como el orden regular del mundo sensible, es decir, por qué nuestras percepciones resultan tan previsibles. El motivo de fondo es religioso: le preocupa que el mecanicismo vuelva superflua a la providencia.",
    },
    {
      type: "quiz",
      question: "Berkeley presenta el inmaterialismo como…",
      options: [
        "el empirismo llevado hasta el final",
        "una refutación del empirismo de Locke",
        "un retorno a la metafísica racionalista",
        "una forma de escepticismo sobre el mundo",
      ],
      answer: 0,
      explain: "Si nunca experimentamos la materia en sí misma sino sólo ideas, postular una materia detrás de las ideas es exactamente la especulación vacía que el empirismo denunciaba en la metafísica. Y Berkeley insiste en que su tesis defiende el sentido común: no niega ninguna cosa experimentada, sólo una entidad imperceptible por definición.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "La secuencia entre estos tres autores tiene, entonces, una lógica interna: Bacon funda la confianza empirista en la observación metódica frente a la especulación; Locke la sistematiza como teoría del conocimiento y ataca frontalmente el innatismo racionalista; y Berkeley extrae, de esa misma teoría, la consecuencia que Locke no había querido sacar, mostrando que el empirismo llevado hasta el final no deja lugar para una materia independiente de toda mente que la perciba.",
    },
    {
      type: "match",
      question: "Uní cada autor con su aporte a la tradición empirista",
      pairs: [
        { left: "Bacon", right: "Los ídolos y el método inductivo" },
        { left: "Locke", right: "La tabla rasa contra las ideas innatas" },
        { left: "Berkeley", right: "El inmaterialismo: esse est percipi" },
        { left: "Galileo", right: "La observación antes del discurso abstracto" },
      ],
      explain: "La secuencia tiene una lógica interna: Bacon funda la confianza en la observación metódica, Locke la sistematiza como teoría del conocimiento, y Berkeley extrae la consecuencia que Locke no quiso sacar. Al dejar en pie sólo mentes e ideas, traslada el problema al análisis de las percepciones, que es el punto de partida de Hume.",
    },
    {
      type: "info",
      continues: true,
      title: "Berkeley: la consecuencia radical del empirismo",
      body: "Este paso resulta decisivo para el desarrollo interno de la tradición empirista: al eliminar la materia como sustrato objetivo del mundo sensible, Berkeley deja en pie únicamente las mentes que perciben y las ideas percibidas, y con ello traslada el centro del problema del conocimiento hacia el análisis de las propias percepciones y de las relaciones que la mente establece entre ellas. Ese será, precisamente, el punto de partida del análisis de David Hume, con el que la tradición empirista alcanza su forma más radical y su culminación crítica.",
    },
  ],
};
