export default {
  num: 12,
  transcript: 12,
  title: "La Aufklärung alemana y Mendelssohn",
  source: "",
  feed: [
    {
      type: "info",
      title: "Un tercer modelo de Ilustración",
      body: "Alemania —en rigor, un mosaico de principados, ciudades libres y reinos bajo el paraguas del Sacro Imperio— vive la Ilustración con un ritmo propio, llamado **Aufklärung**. Llega más tarde que la inglesa y con menos estridencia que la francesa: no hay aquí una monarquía absoluta única a la que enfrentar, ni una Iglesia estatal tan poderosa como para justificar el tono combativo de Voltaire.",
    },
    {
      type: "info",
      continues: true,
      title: "Un tercer modelo de Ilustración",
      body: "El resultado es una Ilustración más moderada, más ligada a las universidades que a los salones, y que busca conciliar la razón con la fe antes que oponerlas. Muchos de sus protagonistas son profesores, funcionarios o pastores, no aristócratas exiliados ni panfletistas perseguidos. La reforma se imagina desde dentro de las instituciones, con el apoyo de gobernantes ilustrados, no contra ellas.",
    },
    {
      type: "info",
      continues: true,
      title: "Un tercer modelo de Ilustración",
      body: "Esa diferencia de escenario político tiene una consecuencia directa: sin un único adversario centralizado —ni una corte como Versalles ni una Iglesia estatal como la anglicana— la Aufklärung se despliega en focos dispersos, cada uno ligado a una universidad o a una corte regional. Halle, Königsberg y Berlín funcionan como polos distintos, con climas intelectuales propios, antes de que Berlín termine imponiéndose como el centro de referencia.",
    },
    {
      type: "quiz",
      question: "La Aufklärung es más moderada que las otras dos Ilustraciones porque…",
      options: [
        "Alemania no tiene ninguna forma de censura religiosa",
        "no hay una monarquía ni Iglesia única que enfrentar",
        "sus universidades prohíben discutir filosofía",
        "el pietismo impide cualquier debate religioso",
      ],
      answer: 1,
      explain: "Alemania es un mosaico de principados sin una monarquía absoluta única ni una Iglesia estatal tan poderosa como la anglicana o la católica francesa: por eso su Ilustración es más moderada, ligada a universidades y busca conciliar razón y fe.",
    },
    {
      type: "info",
      title: "Wolff y la razón sistemática",
      body: "**Christian Wolff** (1679–1754) es quien le da a la Aufklärung su primer lenguaje filosófico. Profesor en Halle, construye un sistema racionalista ordenado y didáctico, heredero de Leibniz, que organiza toda la filosofía —lógica, metafísica, ética, política— en definiciones encadenadas y demostraciones más geométrico. Su ideal es que cualquier persona instruida pueda seguir el razonamiento paso a paso.",
    },
    {
      type: "info",
      continues: true,
      title: "Wolff y la razón sistemática",
      body: "Wolff escribe buena parte de su obra en alemán, no en latín, una decisión que en su momento es casi tan polémica como sus tesis: significa que la filosofía deja de ser propiedad exclusiva de los círculos académicos latinizados y pasa a estar disponible para un público burgués más amplio. Esa opción idiomática es, en sí misma, un gesto ilustrado.",
    },
    {
      type: "info",
      continues: true,
      title: "Wolff y la razón sistemática",
      body: "Su racionalismo sistemático le cuesta la expulsión de Prusia en 1723, acusado por sus adversarios pietistas de un determinismo que amenazaba la libertad moral y la fe cristiana. El episodio muestra la tensión de fondo que atraviesa toda la Aufklärung: cuánta autonomía puede darle la razón al individuo sin entrar en conflicto con la ortodoxia religiosa dominante.",
    },
    {
      type: "info",
      continues: true,
      title: "Wolff y la razón sistemática",
      body: "El detonante concreto de esa expulsión es un discurso de Wolff sobre la moral de los chinos, en el que sostiene que Confucio construyó un sistema ético válido sin apelar a la revelación cristiana, prueba, para Wolff, de que la razón natural basta para fundar la moral. Sus adversarios lo leen como una amenaza directa a la necesidad de la fe revelada, y logran que el rey Federico Guillermo I lo expulse con una amenaza de horca si no abandona Prusia en cuarenta y ocho horas.",
    },
    {
      type: "info",
      continues: true,
      title: "Wolff y la razón sistemática",
      body: "El episodio, lejos de silenciarlo, lo convierte en una celebridad europea: otras universidades lo reciben con honores, y cuando Federico II sube al trono en 1740 lo invita de regreso a Prusia entre honores públicos. Wolff vuelve a Halle convertido en símbolo de la Ilustración perseguida y después reivindicada, un antecedente directo del clima de tolerancia que Federico va a cultivar en su reinado.",
    },
    {
      type: "quiz",
      question: "A Wolff lo expulsan de Prusia en 1723 por defender que…",
      options: [
        "la ética de Confucio no necesita la revelación",
        "el rey debía ceder el trono al Parlamento",
        "el pietismo era la única religión verdadera",
        "Newton se equivocaba sobre las leyes naturales",
      ],
      answer: 0,
      explain: "El detonante es un discurso de Wolff sobre la moral de los chinos: sostiene que Confucio construyó una ética válida sin apelar a la revelación, lo que sus adversarios pietistas leen como una amenaza a la necesidad de la fe cristiana.",
    },
    {
      type: "info",
      title: "Pietismo y la vía alemana a la religión",
      body: "El **pietismo** es el movimiento religioso protestante que domina buena parte de la vida espiritual alemana del período, y frente al cual la Aufklärung tiene que definirse. Enfatiza la experiencia personal de la fe, la conversión interior y la práctica moral cotidiana por encima de la doctrina teológica formal y de la autoridad eclesiástica rígida.",
    },
    {
      type: "info",
      continues: true,
      title: "Pietismo y la vía alemana a la religión",
      body: "A diferencia del deísmo inglés o del materialismo francés, la Aufklärung no busca reemplazar la religión revelada por una religión puramente racional, ni mucho menos abolirla: busca hacerla compatible con la razón, mostrando que fe y entendimiento pueden reforzarse en vez de excluirse. Esa síntesis moderada es la marca distintiva del modelo alemán frente a los otros dos.",
    },
    {
      type: "info",
      continues: true,
      title: "Pietismo y la vía alemana a la religión",
      body: "El pietismo, además, no es sólo el adversario de la Aufklärung: es también, en parte, su cuna. Su énfasis en el examen íntimo de la propia conciencia y en la responsabilidad personal frente a Dios —sin intermediarios eclesiásticos rígidos— entrena, sin proponérselo, un hábito de introspección crítica que muchos ilustrados alemanes, formados en hogares pietistas, trasladan después de la religión a la filosofía moral y al examen racional en general.",
    },
    {
      type: "quiz",
      question: "El pietismo es, para la Aufklärung, a la vez…",
      options: [
        "su principal aliado político y su modelo científico",
        "su adversario religioso y en parte su cuna",
        "una secta marginal sin ninguna influencia real",
        "el origen directo del despotismo de Federico II",
      ],
      answer: 1,
      explain: "El pietismo es el principal adversario religioso de la Aufklärung, pero también entrena, sin proponérselo, el hábito de introspección crítica que muchos ilustrados alemanes trasladan después de la fe a la filosofía moral.",
    },
    {
      type: "info",
      title: "Federico II y el despotismo ilustrado",
      body: "**Federico II de Prusia** (1712–1786), rey desde 1740, encarna el **despotismo ilustrado**: un gobernante absoluto que aplica en su reino ideales asociados a la Ilustración —tolerancia religiosa, reforma legal, fomento de las ciencias y las artes— sin renunciar a la concentración del poder en su propia persona. Se define a sí mismo como «el primer servidor del Estado».",
    },
    {
      type: "info",
      continues: true,
      title: "Federico II y el despotismo ilustrado",
      body: "Bajo su reinado, Berlín se convierte en un centro atractivo para intelectuales de toda Europa: Federico invita a Wolff de regreso del exilio, correspondencia con Voltaire, funda y financia academias científicas. Ese mecenazgo real es decisivo para que la Aufklärung tenga, en Berlín específicamente, un espacio de discusión pública relativamente protegido.",
    },
    {
      type: "info",
      continues: true,
      title: "Federico II y el despotismo ilustrado",
      body: "Ese despotismo ilustrado tiene, sin embargo, límites claros: Federico tolera —incluso alienta— la discusión filosófica y religiosa, siempre que no cuestione su autoridad política ni el orden social vigente, empezando por la servidumbre campesina, que su reinado no toca. La libertad que Berlín ofrece a sus intelectuales es, en ese sentido, una libertad de cátedra y de pluma, no una libertad política en sentido pleno.",
    },
    {
      type: "quiz",
      question: "El despotismo ilustrado de Federico II tolera la discusión filosófica siempre que…",
      options: [
        "no cuestione su autoridad ni el orden social",
        "se publique únicamente en latín académico",
        "cuente con la aprobación previa de la Iglesia",
        "no mencione a ningún filósofo francés",
      ],
      answer: 0,
      explain: "Federico tolera e incluso alienta la discusión filosófica y religiosa, pero sólo mientras no cuestione su autoridad política ni el orden social vigente, empezando por la servidumbre campesina, que su reinado no toca.",
    },
    {
      type: "info",
      title: "La Berlinische Monatsschrift y el círculo berlinés",
      body: "En ese ambiente surge la **Berlinische Monatsschrift** («Revista mensual berlinesa»), publicada desde 1783, que se vuelve el órgano central donde los ilustrados berlineses discuten filosofía, religión y política de actualidad. Es en sus páginas donde va a plantearse, formalmente, la pregunta que define a toda una generación: qué es, en definitiva, la Ilustración.",
    },
    {
      type: "info",
      continues: true,
      title: "La Berlinische Monatsschrift y el círculo berlinés",
      body: "La revista nace de la llamada «Sociedad del Miércoles», un club privado de funcionarios, profesores y clérigos berlineses que se reúne para discutir en confianza cuestiones religiosas y políticas delicadas, con la condición de guardar el secreto de las deliberaciones. La Berlinische Monatsschrift es, en buena medida, el canal por el que ese debate reservado se vuelve público.",
    },
    {
      type: "quiz",
      question: "La Berlinische Monatsschrift nace ligada a…",
      options: [
        "un decreto oficial del propio Federico II",
        "un club privado que discutía temas delicados",
        "una orden directa de la Academia de Ciencias",
        "la censura eclesiástica de la Iglesia luterana",
      ],
      answer: 1,
      explain: "La revista nace de la Sociedad del Miércoles, un club privado de funcionarios, profesores y clérigos que discutía en confianza cuestiones religiosas y políticas delicadas: la Monatsschrift vuelve público ese debate reservado.",
    },
    {
      type: "info",
      title: "Moses Mendelssohn",
      body: "**Moses Mendelssohn** (1729–1786) es la figura central de esa Ilustración berlinesa. Nacido en una familia judía pobre de Dessau, llega a Berlín en 1743 prácticamente sin recursos y se forma de manera autodidacta en filosofía, matemática y lenguas clásicas, hasta convertirse en uno de los intelectuales más respetados de su tiempo, admirado incluso por Kant.",
    },
    {
      type: "info",
      continues: true,
      title: "Moses Mendelssohn",
      body: "Su condición de judío en una sociedad cristiana lo obliga a pensar la Ilustración también como un problema de tolerancia práctica, no sólo teórica: Mendelssohn defiende públicamente la emancipación civil de los judíos y sostiene, contra el prejuicio de su época, que la pertenencia a una fe distinta no priva a nadie de razón ni de virtud. En ese sentido, encarna él mismo el ideal de tolerancia que la Ilustración proclama.",
    },
    {
      type: "info",
      continues: true,
      title: "Moses Mendelssohn",
      body: "Su fama filosófica se consolida con los Diálogos sobre la inmortalidad del alma, titulados Fedón (1767) en homenaje al diálogo platónico, donde defiende con argumentos racionales, en un estilo elegante y accesible, la inmortalidad del alma humana. El libro lo vuelve célebre en toda Alemania como el «Sócrates alemán» y le gana el respeto de figuras como Kant, con quien mantiene correspondencia filosófica.",
    },
    {
      type: "info",
      continues: true,
      title: "Moses Mendelssohn",
      body: "En 1763 gana el primer premio de un concurso de la Academia de Ciencias de Berlín sobre la evidencia de las verdades metafísicas, superando a un joven Kant que presenta también un ensayo al mismo concurso y queda en segundo lugar. El episodio anticipa, de manera casi simbólica, el diálogo posterior entre ambos sobre qué significa ilustrar.",
    },
    {
      type: "quiz",
      question: "En el concurso de la Academia de Berlín de 1763…",
      options: [
        "Mendelssohn queda segundo, detrás de un joven Kant",
        "Mendelssohn gana el premio y Kant queda segundo",
        "Kant y Mendelssohn presentan el mismo ensayo",
        "ninguno de los dos presenta trabajos al concurso",
      ],
      answer: 1,
      explain: "Mendelssohn gana el primer premio sobre la evidencia de las verdades metafísicas, superando a un joven Kant que queda en segundo lugar: un episodio que anticipa, de manera simbólica, el diálogo posterior entre ambos.",
    },
    {
      type: "short",
      question: "¿Cómo se titula la obra de Mendelssohn sobre la inmortalidad del alma, en homenaje al diálogo platónico?",
      answers: ["Fedón"],
      explain: "Los Diálogos sobre la inmortalidad del alma, titulados Fedón (1767), vuelven célebre a Mendelssohn como el «Sócrates alemán» y le ganan el respeto de Kant.",
    },
    {
      type: "info",
      title: "La pregunta de Zöllner",
      body: "En diciembre de 1783, el teólogo **Johann Friedrich Zöllner** publica en la Berlinische Monatsschrift un artículo sobre el matrimonio civil en el que desliza, en una nota al pie, una pregunta que se vuelve célebre: «¿Qué es la Ilustración? Esta pregunta, que es casi tan importante como qué es la verdad, debería responderse antes de empezar a ilustrar». La nota interpela directamente a los colaboradores habituales de la revista.",
    },
    {
      type: "info",
      continues: true,
      title: "La pregunta de Zöllner",
      body: "La pregunta toca un nervio: si la Ilustración es el programa de toda una época, resulta llamativo que nadie haya definido con precisión en qué consiste. Varios pensadores responden en los meses siguientes en la misma revista, pero las dos respuestas que van a quedar como referencia son las de Mendelssohn y las de Kant, publicadas ambas en 1784, y que —vale anticiparlo— no coinciden entre sí.",
    },
    {
      type: "info",
      continues: true,
      title: "La pregunta de Zöllner",
      body: "El artículo de Zöllner que motiva la nota discute, en realidad, si conviene seguir celebrando matrimonios por rito religioso o reemplazarlos por un trámite puramente civil; Zöllner defiende conservar el rito religioso y sospecha que quienes proponen secularizarlo actúan «para ilustrar», sin que nadie haya explicado antes qué significa exactamente esa palabra. La pregunta nace, entonces, de una polémica concreta, no de un ejercicio puramente abstracto.",
    },
    {
      type: "quiz",
      question: "La nota de Zöllner sobre «¿qué es la Ilustración?» surge de un debate sobre…",
      options: [
        "si el matrimonio debía ser religioso o civil",
        "si Prusia debía declarar la guerra a Francia",
        "si había que traducir la Biblia al alemán",
        "si Wolff merecía volver a la universidad",
      ],
      answer: 0,
      explain: "El artículo de Zöllner discute si conviene seguir casando por rito religioso o reemplazarlo por un trámite civil; sospecha que quienes proponen secularizarlo actúan «para ilustrar» sin que nadie haya explicado qué significa eso.",
    },
    {
      type: "info",
      title: "La respuesta de Mendelssohn",
      body: "Mendelssohn publica su respuesta, «Sobre la pregunta: ¿qué significa ilustrar?», en septiembre de 1784. Su estrategia es distinguir con cuidado entre **ilustración**, **cultura** y el término más general de **educación** (Bildung), que él usa como paraguas que las contiene a ambas y que un individuo o un pueblo pueden alcanzar en distinto grado y de manera independiente.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Para Mendelssohn, la **cultura** es el conjunto de las habilidades prácticas y del refinamiento social que una comunidad desarrolla: las artes, los oficios, el gusto, las costumbres civilizadas. La **ilustración**, en cambio, es un tipo específico de saber teórico: el conocimiento racional que permite juzgar correctamente el valor y el sentido de las cosas de la vida, tanto teóricas como prácticas.",
    },
    {
      type: "quiz",
      question: "Para Mendelssohn, la diferencia entre cultura e ilustración es que…",
      options: [
        "la cultura es teórica y la ilustración es práctica",
        "la cultura es social y la ilustración, teórica",
        "son exactamente lo mismo bajo dos nombres distintos",
        "la ilustración sólo existe en individuos, nunca en pueblos",
      ],
      answer: 1,
      explain: "La cultura es el conjunto de habilidades prácticas y refinamiento social de una comunidad; la ilustración es el saber teórico que permite juzgar racionalmente el valor de las cosas. Un pueblo puede tener mucho de una y poco de la otra.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Un pueblo puede tener mucha cultura y poca ilustración —una sociedad refinada en las formas pero incapaz de fundamentar racionalmente sus juicios— o, a la inversa, mucha ilustración teórica y poca cultura práctica. El ideal, para Mendelssohn, es que ambas avancen juntas y en equilibrio, porque una cultura sin ilustración degenera en superstición refinada y una ilustración sin cultura queda inaplicable a la vida concreta.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Mendelssohn insiste, además, en que la Ilustración no es sólo asunto del individuo aislado: habla de una ilustración «del hombre» —como ser racional en general— y de una ilustración «del ciudadano»— referida al rol social de cada quien—, y advierte que ambas pueden entrar en tensión: lo que ilustra a alguien como persona no siempre conviene difundirlo sin matices en su función pública, si puede desestabilizar el orden social sin nada que lo reemplace.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Esa cautela —cuidar el ritmo con que se difunden ciertas verdades— distingue a Mendelssohn de la audacia despreocupada de Voltaire o de Diderot. Su Ilustración es gradualista: confía en la razón, pero también en que el progreso intelectual de una sociedad entera necesita tiempo, y que forzarlo de golpe puede producir más daño que bien.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Mendelssohn ilustra ese riesgo con un ejemplo propio de su condición de filósofo judío: si una verdad religiosa resulta insostenible ante el examen racional pero sostiene, en la práctica, la cohesión moral de una comunidad entera que todavía no está preparada para prescindir de ella, divulgarla sin más, de golpe y a todos por igual, puede destruir esa cohesión sin ofrecer nada sólido que la reemplace. La ilustración bien entendida, para él, avanza al ritmo que la cultura de un pueblo puede sostener.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Por esa misma razón, Mendelssohn distingue la ilustración de la mera sofisticación intelectual o del «librepensamiento» superficial: no alcanza con cuestionar creencias heredadas para estar ilustrado, si esa crítica no viene acompañada de un criterio racional sólido que oriente qué conservar y qué descartar. Ilustrarse sin cultura ni prudencia práctica, advierte, puede degenerar en un escepticismo destructivo que no construye nada en el lugar de lo que derriba.",
    },
    {
      type: "info",
      continues: true,
      title: "La respuesta de Mendelssohn",
      body: "Kant, unos meses después, va a responder a la misma pregunta de Zöllner de una manera distinta y más filosóficamente ambiciosa: no como un saber que se posee en mayor o menor grado, sino como un acto, una salida de un estado. Esa respuesta —y en qué se aparta exactamente de la de Mendelssohn— es materia de otra clase.",
    },
    {
      type: "classify",
      question: "¿Cada definición de la Ilustración es de Mendelssohn o de Kant, según lo que adelanta esta clase?",
      groups: ["Mendelssohn", "Kant"],
      items: [
        { text: "Es un saber que se posee en mayor o menor grado", group: 0 },
        { text: "Distingue la ilustración de la cultura como dos procesos", group: 0 },
        { text: "Avanza al ritmo que la cultura de un pueblo puede sostener", group: 0 },
        { text: "Es un acto, no un conjunto de saberes acumulados", group: 1 },
        { text: "Es la salida de un estado, no un grado de posesión", group: 1 },
      ],
      explain: "Mendelssohn trata la Ilustración como un saber gradual, distinto de la cultura. Kant, según adelanta esta clase, la piensa como un acto, una salida de un estado: su respuesta completa, publicada también en 1784, es tema de otra clase.",
    },
    {
      type: "short",
      question: "¿Con qué palabra alemana nombra Mendelssohn el concepto amplio que incluye tanto la cultura como la ilustración?",
      answers: ["Bildung"],
      explain: "Mendelssohn usa Bildung —educación, en sentido amplio— como paraguas que contiene tanto la cultura como la ilustración, dos procesos que un individuo o un pueblo pueden alcanzar en distinto grado y de manera independiente.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada nombre con su papel en la Aufklärung berlinesa",
      pairs: [
        { left: "Wolff", right: "El racionalismo sistemático, expulsado y luego reivindicado" },
        { left: "Federico II", right: "El despotismo ilustrado: reforma sin ceder el poder" },
        { left: "Zöllner", right: "La nota al pie que pregunta qué es la Ilustración" },
        { left: "Mendelssohn", right: "Distingue ilustración de cultura y responde en 1784" },
      ],
      explain: "Cuatro piezas del mosaico berlinés: el sistema de Wolff, el mecenazgo de Federico II, la pregunta de Zöllner y la respuesta gradualista de Mendelssohn, que deja planteada —sin resolverla aquí— la réplica de Kant.",
    },
    {
      type: "info",
      title: "Ilustración y cultura como programa alemán",
      body: "La distinción de Mendelssohn resume bien lo que distingue al modelo alemán de sus dos predecesores. Donde Inglaterra pregunta cómo tolerar la diferencia religiosa y Francia cómo desmontar el poder absoluto, Alemania pregunta qué es, exactamente, ilustrarse, y cómo se relaciona ese proceso con la formación integral —moral, estética, cívica— de una persona y de un pueblo. Es una Ilustración que se piensa a sí misma con una reflexividad que los otros dos modelos no necesitaron desarrollar con la misma urgencia.",
    },
  ],
};
