export default {
  num: 16,
  transcript: 16,
  title: "Hamann y la metacrítica de la razón",
  source: "",
  feed: [
    {
      type: "info",
      title: "El adversario de la puerta de al lado",
      body: "La objeción más radical a la Ilustración alemana no vino de Roma ni de la reacción política. Vino de Königsberg, la misma ciudad pequeña donde Kant vivió y enseñó, y de un hombre que lo conocía personalmente: **Johann Georg Hamann** (1730–1788).",
    },
    {
      type: "info",
      continues: true,
      title: "El adversario de la puerta de al lado",
      body: "Hamann y Kant se trataron durante décadas. Kant intentó conseguirle empleo, le prestó libros, discutió con él; Hamann leyó la Crítica de la razón pura antes de que se publicara, porque corrigió pruebas de imprenta. La crítica que sigue no es la de un extraño al proyecto ilustrado, es la de alguien que lo vio de cerca.",
    },
    {
      type: "info",
      continues: true,
      title: "El adversario de la puerta de al lado",
      body: "Su biografía explica en parte la posición. Empleado subalterno, sin cátedra ni carrera, Hamann pasó por una crisis religiosa en Londres en 1758 que lo devolvió a una lectura intensa de la Biblia. Desde entonces escribió como creyente, contra la pretensión ilustrada de una razón autosuficiente.",
    },
    {
      type: "info",
      continues: true,
      title: "El adversario de la puerta de al lado",
      body: "Escribió poco y de manera deliberadamente difícil: fragmentos, textos breves, prosa cargada de citas, ironías y alusiones. Le decían el mago del Norte. Ese estilo no es un accidente: Hamann desconfiaba de la exposición sistemática porque le parecía parte del error que quería denunciar.",
    },
    {
      type: "info",
      continues: true,
      title: "El adversario de la puerta de al lado",
      body: "Su primera obra importante, las Memorias socráticas (Sokratische Denkwürdigkeiten, 1759), ya trae el argumento central en germen. Contra los ilustrados que hacían de Sócrates un héroe de la razón, Hamann destaca su ignorancia declarada y su daimon: Sócrates sabía que no sabía y obedecía una voz que no podía justificar.",
    },
    {
      type: "info",
      continues: true,
      title: "El adversario de la puerta de al lado",
      body: "Hamann es también una figura de referencia del **Sturm und Drang**, el movimiento literario alemán de las décadas de 1770 y 1780 que reivindicó el genio, la pasión y la fuerza expresiva contra el buen gusto y la corrección racional. La generación de Herder y del joven Goethe lo leyó y lo tomó como maestro.",
    },
    {
      type: "quiz",
      question: "¿Qué vuelve particular la crítica de Hamann a la Ilustración?",
      options: [
        "Viene de alguien que conocía el proyecto desde adentro",
        "Viene de la jerarquía católica y de la reacción política",
        "Viene de un profesor rival que competía por su cátedra",
        "Viene de un autor que nunca leyó a los ilustrados alemanes",
      ],
      answer: 0,
      explain: "Hamann y Kant vivieron en la misma ciudad pequeña y se trataron durante décadas: Kant le buscó empleo y le prestó libros, y Hamann leyó la Crítica de la razón pura antes de que se publicara porque corrigió pruebas de imprenta.",
    },
    {
      type: "quiz",
      question: "En las Memorias socráticas (1759), Hamann opone al Sócrates de los ilustrados…",
      options: [
        "un Sócrates que declara su ignorancia y obedece a un daimon",
        "un Sócrates político, enemigo declarado de la democracia",
        "un Sócrates escéptico que niega toda verdad alcanzable",
        "un Sócrates piadoso que acepta la religión de la ciudad",
      ],
      answer: 0,
      explain: "Los ilustrados hacían de Sócrates un héroe de la razón. Hamann destaca lo contrario: que sabía que no sabía, y que seguía una voz interior que no podía justificar racionalmente. La figura anticipa toda su objeción posterior.",
    },
    {
      type: "info",
      title: "La carta a Kraus: la tutela no es autoculpable",
      body: "La respuesta de Hamann al artículo de Kant es inmediata y privada. El 18 de diciembre de 1784, apenas publicado el texto, escribe una carta a su amigo Christian Jakob Kraus donde desarma la definición punto por punto.",
    },
    {
      type: "info",
      continues: true,
      title: "La carta a Kraus: la tutela no es autoculpable",
      body: "Su blanco es el adjetivo. Kant había dicho que la minoría de edad es **autoculpable**, y en eso se apoyaba todo: si la culpa es del menor, la salida depende de su decisión. Hamann pregunta de quién es realmente la culpa cuando alguien fue mantenido en la incapacidad de pensar por sí mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "La carta a Kraus: la tutela no es autoculpable",
      body: "Su respuesta es que la culpa es del tutor, no del pupilo. Y agrega la observación que da vuelta el texto de Kant: el tutor que le echa al menor la culpa de su propia minoría de edad está agravando la tutela, no aliviándola. Es un maltrato disfrazado de exhortación.",
    },
    {
      type: "info",
      continues: true,
      title: "La carta a Kraus: la tutela no es autoculpable",
      body: "Después señala la incoherencia práctica. Kant exige valor para pensar y al mismo tiempo pide obediencia en el ejercicio del cargo; le concede al súbdito la libertad de escribir y le niega la de actuar. Hamann le contesta que ahí la Ilustración se vuelve inofensiva por diseño, y que una libertad que no toca nada no es libertad.",
    },
    {
      type: "info",
      continues: true,
      title: "La carta a Kraus: la tutela no es autoculpable",
      body: "Y llega a la formulación que resume su posición: no puede separar la Ilustración de la tutela. El proyecto que promete emancipar sustituye un tutor por otro. Donde antes estaban la tradición, la iglesia y la costumbre, ahora está la razón, con la misma pretensión de decidir en nombre de todos.",
    },
    {
      type: "quiz",
      question: "¿Qué le objeta Hamann a la palabra «autoculpable» de Kant?",
      options: [
        "Que la culpa es del tutor y no del que fue tutelado",
        "Que nadie es culpable de nada en materia de creencias",
        "Que la culpa recae sobre el Estado y no sobre la iglesia",
        "Que hablar de culpa introduce la religión donde no cabe",
      ],
      answer: 0,
      explain: "Para Hamann, el tutor que le echa al menor la culpa de su propia minoría de edad está agravando la tutela en vez de aliviarla: es un maltrato disfrazado de exhortación. De ahí su conclusión de que no puede separar la Ilustración de la tutela.",
    },
    {
      type: "info",
      title: "El purismo de la razón",
      body: "El texto donde Hamann convierte esa sospecha en un argumento filosófico es la **Metacrítica del purismo de la razón**, escrita en 1784 y publicada recién en 1800, después de su muerte. Son pocas páginas, densas, y son la primera objeción de fondo a la Crítica de la razón pura.",
    },
    {
      type: "info",
      continues: true,
      title: "El purismo de la razón",
      body: "El título dice el método. Kant hizo una crítica: examinó la razón para establecer sus límites. Hamann propone una **metacrítica**: examinar la facultad con la que Kant hizo ese examen. Si la razón se juzga a sí misma, ¿quién juzga al juez? La pregunta no es retórica, es la que estructura el texto.",
    },
    {
      type: "info",
      continues: true,
      title: "El purismo de la razón",
      body: "Y el objeto de la denuncia es lo que Hamann llama **purismo**: la pretensión de obtener una razón pura, depurada de todo elemento ajeno. Hamann identifica tres purificaciones sucesivas, cada una más ambiciosa que la anterior, y sostiene que la tercera es imposible.",
    },
    {
      type: "info",
      continues: true,
      title: "El purismo de la razón",
      body: "La primera purificación separa la razón de la tradición, de la fe y de la autoridad. Es el gesto fundacional de la modernidad, el que este curso vio nacer con Lutero y Descartes. La segunda la separa de la experiencia y de la inducción cotidiana: es el paso que da el racionalismo y que Kant conserva al buscar lo a priori.",
    },
    {
      type: "info",
      continues: true,
      title: "El purismo de la razón",
      body: "Hamann no discute que esas dos operaciones se hayan hecho. Discute qué queda después. Cada purificación se presenta como una liberación, y en cada una la razón se queda con menos: primero sin memoria, después sin mundo. Lo que va apareciendo no es una razón más limpia sino una razón más flaca.",
    },
    {
      type: "quiz",
      question: "El «purismo» que Hamann le imputa a Kant es la pretensión de…",
      options: [
        "obtener una razón depurada de todo elemento ajeno",
        "escribir en un alemán liberado de términos latinos",
        "fundar la moral sin apoyarse en ninguna revelación",
        "reducir la filosofía al método de las matemáticas",
      ],
      answer: 0,
      explain: "Hamann distingue tres purificaciones sucesivas: separar la razón de la tradición y la fe, separarla de la experiencia, y separarla del lenguaje. No discute que las dos primeras se hayan hecho; discute qué queda después de cada una.",
    },
    {
      type: "info",
      continues: true,
      title: "El purismo de la razón",
      body: "La tercera purificación es la que Kant intenta y la que Hamann considera un imposible: separar la razón del **lenguaje**. Para que existiera algo así como una razón pura habría que poder pensar sin palabras, y eso no ocurre nunca.",
    },
    {
      type: "info",
      title: "El lenguaje como condición de la razón",
      body: "El argumento central del texto es corto y tiene enorme consecuencia. No hay razón sin lenguaje. Todo pensamiento se ejerce en palabras, y no en palabras cualesquiera, sino en una lengua determinada, con su historia, su gramática y su vocabulario heredados.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Y el lenguaje no es puro en ninguno de los sentidos que Kant necesita. Es sensible, porque las palabras son sonidos y signos materiales. Es histórico, porque cada lengua es el producto de generaciones. Y es recibido, porque nadie inventa el idioma en el que piensa: lo aprende de otros antes de poder examinar nada.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "De ahí se sigue que la razón que Kant somete a crítica no es una facultad pura que después se expresa en palabras. Está hecha de palabras desde el principio. Sus categorías no son estructuras trascendentales descubiertas por análisis: son, sospecha Hamann, rasgos de la gramática del alemán y del latín escolástico elevados a condiciones del mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Por eso la Crítica no puede cumplir su programa. Se propuso determinar los límites de la razón usando exclusivamente la razón, y usó todo el tiempo un instrumento —la lengua— que no examinó y que no es racional en el sentido que ella exige. La crítica reposa sobre algo que no criticó.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Conviene ver la forma del argumento, porque es la misma que Kant había usado contra la metafísica. Kant mostró que la razón, al querer conocer lo que excede la experiencia posible, se excede a sí misma. Hamann le devuelve la operación: la razón, al querer conocerse a sí misma sin el lenguaje, se excede exactamente igual.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "No es entonces una objeción externa, de alguien que defiende la fe contra la filosofía. Es una objeción interna, que acepta el método trascendental y lo aplica un escalón más abajo. De ahí el prefijo: no una crítica más, sino una crítica de la crítica.",
    },
    {
      type: "quiz",
      question: "¿Cuál es el argumento central de la Metacrítica?",
      options: [
        "No hay razón sin lenguaje, y el lenguaje no es puro",
        "La razón no puede demostrar la existencia de Dios",
        "La experiencia sensible es la única fuente de saber",
        "Las categorías del entendimiento son sólo doce",
      ],
      answer: 0,
      explain: "Todo pensamiento se ejerce en palabras, y en una lengua determinada con su historia y su gramática heredadas. El lenguaje es sensible, histórico y recibido: nadie inventa el idioma en el que piensa. Una razón pura, separada de él, es una ficción.",
    },
    {
      type: "quiz",
      question: "Hamann llama «metacrítica» a su texto porque…",
      options: [
        "examina la facultad con la que Kant hizo su examen",
        "va más allá de Kant proponiendo un sistema nuevo",
        "critica a los críticos de Kant en vez de a Kant",
        "reúne las críticas dispersas que otros ya publicaron",
      ],
      answer: 0,
      explain: "Si la razón se juzga a sí misma, queda abierta la pregunta de quién juzga al juez. Y la forma del argumento es la misma que Kant había usado contra la metafísica, aplicada un escalón más abajo: no una crítica más, sino una crítica de la crítica.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Hamann encuentra en esto un argumento más específico contra la arquitectura de Kant. La Crítica separa dos troncos del conocimiento, la sensibilidad y el entendimiento, y hace de esa separación su punto de partida. Hamann responde que la palabra es el contraejemplo.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Una palabra es simultáneamente sensible e intelectual: es un sonido que se oye y un significado que se entiende, y no hay manera de tener uno sin el otro. Si el vehículo de todo pensamiento tiene esa doble naturaleza indivisa, entonces separar sensibilidad y entendimiento es una operación de análisis que rompe algo que en la experiencia real está unido.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Hamann sospecha, además, del origen de las categorías. Kant las presenta como el hallazgo de un análisis de la facultad de juzgar, pero las deriva de la tabla de los juicios de la lógica escolar, que es a su vez un producto histórico. Lo que Kant toma por la estructura necesaria de todo entendimiento posible sería la estructura contingente de una tradición gramatical.",
    },
    {
      type: "info",
      continues: true,
      title: "El lenguaje como condición de la razón",
      body: "Si eso es así, la pretensión de universalidad se cae. Las condiciones de posibilidad de la experiencia serían las condiciones de posibilidad de la experiencia de alguien que piensa en las lenguas europeas cultas del siglo XVIII. Es una sospecha, no una demostración, pero es la que va a reaparecer con fuerza mucho después.",
    },
    {
      type: "quiz",
      question: "¿Por qué es la palabra un contraejemplo a la arquitectura de la Crítica?",
      options: [
        "Porque es sensible e intelectual a la vez, sin división",
        "Porque cambia de significado según quién la pronuncie",
        "Porque no puede traducirse de una lengua a otra",
        "Porque se aprende antes de tener uso de razón",
      ],
      answer: 0,
      explain: "Kant hace de la separación entre sensibilidad y entendimiento su punto de partida. Pero una palabra es un sonido que se oye y un significado que se entiende, y no hay manera de tener uno sin el otro: separar las dos facultades rompe algo que en la experiencia real está unido.",
    },
    {
      type: "short",
      question: "¿Qué movimiento literario alemán de los años 1770 y 1780 tuvo a Hamann como referente?",
      answers: ["Sturm und Drang"],
      explain: "«Tempestad e ímpetu», por el título de una obra de Klinger. Reivindicó el genio, la pasión y la fuerza expresiva contra el buen gusto y la corrección racional de la estética ilustrada. Herder fue su teórico principal.",
    },
    {
      type: "info",
      title: "Fe en la base de la razón",
      body: "El otro apoyo de Hamann es una lectura de Hume, y es un giro que no se espera. Kant había recibido de Hume el problema y había respondido con las categorías; Hamann recibe de Hume una conclusión distinta.",
    },
    {
      type: "info",
      continues: true,
      title: "Fe en la base de la razón",
      body: "Si Hume mostró que la creencia en la conexión causal no puede fundarse en la razón ni en la experiencia, y que sin embargo la usamos constantemente y no podríamos vivir sin ella, entonces lo que mostró es que en la base de todo conocimiento hay una **creencia** que la razón no produce ni justifica.",
    },
    {
      type: "info",
      continues: true,
      title: "Fe en la base de la razón",
      body: "Hamann toma eso literalmente y lo extiende. La razón no se sostiene a sí misma: descansa sobre una confianza previa en el mundo, en los sentidos y en el testimonio de otros, que ninguna demostración alcanza. Y una razón que descansa sobre una fe no puede erigirse en tribunal de la fe.",
    },
    {
      type: "info",
      continues: true,
      title: "Fe en la base de la razón",
      body: "El movimiento es notable: Hume, que en Inglaterra funciona como el escéptico que disuelve la metafísica, se vuelve en manos de Hamann un argumento a favor de la religión. No porque pruebe nada sobre Dios, sino porque prueba que creer sin fundamento racional es la condición normal del conocimiento humano.",
    },
    {
      type: "info",
      continues: true,
      title: "Fe en la base de la razón",
      body: "Vale comparar las dos lecturas de Hume que dejó este curso. Kant lo leyó como el planteo de un problema que había que resolver, y lo resolvió mostrando que la causalidad es una condición del entendimiento. Hamann lo leyó como la constatación de un hecho que había que aceptar, y del que se sigue que la razón nunca fue autónoma.",
    },
    {
      type: "info",
      continues: true,
      title: "Fe en la base de la razón",
      body: "Las dos lecturas son honestas y la diferencia no es de erudición sino de propósito. Kant quiere salvar la ciencia; Hamann quiere mostrar que la ciencia también cree. Del mismo texto salen la fundamentación más ambiciosa del conocimiento moderno y la impugnación más radical de su autosuficiencia.",
    },
    {
      type: "classify",
      question: "¿Cada lectura de Hume es la de Kant o la de Hamann?",
      groups: ["Kant", "Hamann"],
      items: [
        { text: "Plantea un problema que hay que resolver", group: 0 },
        { text: "Constata un hecho que hay que aceptar", group: 1 },
        { text: "La causalidad es una condición del entendimiento", group: 0 },
        { text: "La razón descansa sobre una fe que no puede fundar", group: 1 },
        { text: "Lo que se salva con la respuesta es la ciencia", group: 0 },
        { text: "Lo que se muestra es que la ciencia también cree", group: 1 },
      ],
      explain: "Del mismo texto salen la fundamentación más ambiciosa del conocimiento moderno y la impugnación más radical de su autosuficiencia. La diferencia no es de erudición sino de propósito.",
    },
    {
      type: "info",
      title: "La lengua y el pueblo",
      body: "De la tesis sobre el lenguaje sale una consecuencia que va a tener un futuro largo. Si el pensamiento está atado a una lengua concreta, entonces no hay un sujeto racional universal: hay hombres que piensan en alemán, en francés, en hebreo, y esas lenguas no son envases intercambiables de un contenido común.",
    },
    {
      type: "info",
      continues: true,
      title: "La lengua y el pueblo",
      body: "Cada idioma lleva consigo una manera de dividir el mundo, una memoria y una sensibilidad. La lengua es la forma de vida de un pueblo, y la poesía —no la ciencia— es su expresión más alta. Hamann llamó a la poesía la lengua materna del género humano.",
    },
    {
      type: "info",
      continues: true,
      title: "La lengua y el pueblo",
      body: "Contra el universalismo abstracto de los ilustrados, esto propone atender a lo particular, lo histórico y lo concreto. La verdad no está en lo que queda después de despojar a los hombres de sus tradiciones, sino en esas tradiciones mismas. Herder va a desarrollar esta idea y el romanticismo la va a convertir en programa.",
    },
    {
      type: "quiz",
      question: "De la tesis de Hamann sobre el lenguaje se sigue que…",
      options: [
        "no hay un sujeto racional universal",
        "todas las lenguas son igualmente precisas",
        "la poesía debe subordinarse a la ciencia",
        "la traducción entre lenguas es siempre exacta",
      ],
      answer: 0,
      explain: "Si el pensamiento está atado a una lengua concreta, entonces hay hombres que piensan en alemán, en francés o en hebreo, y esas lenguas no son envases intercambiables de un contenido común. Cada idioma lleva una manera de dividir el mundo. Herder desarrolla la idea y el romanticismo la vuelve programa.",
    },
    {
      type: "info",
      title: "Lo que queda abierto",
      body: "Este curso termina acá, en 1784, y el punto de llegada no es una conclusión sino una discusión abierta. En el mismo año se publican la respuesta de Kant, la de Mendelssohn y la carta de Hamann, y las tres dicen cosas incompatibles sobre qué es la Ilustración y si hay que desearla.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que queda abierto",
      body: "Vale la pena medir la distancia recorrida. El curso empezó con la Reforma reclamando el derecho de cada creyente a interpretar por sí mismo, y con el escepticismo de Montaigne desconfiando de la costumbre. Termina con la razón instalada como tribunal universal, y con alguien preguntando si ese tribunal no es la vieja tutela con otro nombre.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que queda abierto",
      body: "Lo que sigue está fuera de este recorrido. La polémica sobre el spinozismo va a poner en cuestión si la Ilustración conduce al fatalismo y al nihilismo; Fichte, Schelling y Hegel van a intentar rehacer el sistema desde el punto en que Kant lo dejó; el romanticismo va a hacer suyas las objeciones de Hamann.",
    },
    {
      type: "match",
      question: "Uní cada pieza de la polémica de 1784 con su posición",
      pairs: [
        { left: "Mendelssohn", right: "La ilustración es un saber que un pueblo posee" },
        { left: "Kant", right: "Es la salida de la minoría de edad autoculpable" },
        { left: "Hamann", right: "No puede separarse la Ilustración de la tutela" },
        { left: "Zöllner", right: "Formuló la pregunta al pie de un artículo" },
      ],
      explain: "Las tres respuestas se publican el mismo año y dicen cosas incompatibles sobre qué es la Ilustración y si hay que desearla. El curso termina en esa discusión abierta, que es también el punto donde la modernidad deja de construirse y empieza a discutirse a sí misma.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que queda abierto",
      body: "Y ahí empieza el otro curso de esta app, «Contemporánea», que arranca en Nietzsche y cuya primera clase se llama justamente «La herencia de la Ilustración». El corte no es arbitrario: es el punto donde la modernidad deja de construirse y empieza a discutirse a sí misma.",
    },
  ],
};
