export default {
  num: 13,
  transcript: 13,
  title: "Lessing y la educación del género humano",
  source: "",
  feed: [
    {
      type: "info",
      title: "Un ilustrado a contramano",
      body: "**Gotthold Ephraim Lessing** (1729–1781) es, a la vez, uno de los nombres mayores de la Aufklärung y uno de los primeros en señalarle sus límites. Crítico literario, dramaturgo y filósofo, hijo de un pastor luterano, se forma en teología antes de dedicarse a las letras, y esa formación religiosa nunca lo abandona del todo, ni siquiera en sus obras más críticas de la ortodoxia.",
    },
    {
      type: "info",
      continues: true,
      title: "Un ilustrado a contramano",
      body: "Esa doble condición —ilustrado convencido y, al mismo tiempo, crítico agudo de lo que la Ilustración da por resuelto sin pensarlo del todo— es lo que vuelve a Lessing una figura de transición. No rompe con la razón como más tarde hará el Sturm und Drang, ni con la fe como hicieron los materialistas franceses; lo que hace es negarse a aceptar que ambas puedan reducirse la una a la otra sin pérdida.",
    },
    {
      type: "info",
      continues: true,
      title: "Un ilustrado a contramano",
      body: "Lessing ejerce, además, un oficio que lo distingue de los filósofos académicos de su tiempo: es dramaturgo y crítico de teatro profesional, autor de comedias y tragedias que renuevan el teatro alemán apartándolo del modelo clásico francés, y de una obra de teoría dramática, la Dramaturgia de Hamburgo (1767-69), que sienta las bases de una estética alemana propia. Esa práctica literaria constante moldea también su manera de argumentar en filosofía: por diálogo, por caso concreto, no por sistema.",
    },
    {
      type: "quiz",
      question: "¿Por qué es Lessing una figura de transición?",
      options: [
        "es ilustrado y crítico del movimiento a la vez",
        "abandona la razón para volver a la fe luterana",
        "escribe teatro en vez de tratados filosóficos",
        "vive entre la Ilustración y el Romanticismo",
      ],
      answer: 0,
      explain: "No rompe con la razón, como hará el Sturm und Drang, ni con la fe, como los materialistas franceses. Lo que se niega a aceptar es que razón y fe puedan reducirse la una a la otra sin pérdida.",
    },
    {
      type: "info",
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "Lessing lleva ese problema al teatro en **Natán el sabio** (1779), un drama ambientado en la Jerusalén de las Cruzadas donde conviven un mercader judío, un sultán musulmán y un caballero cristiano. La obra dramatiza, mucho antes de volverse tesis filosófica explícita, la pregunta que atraviesa toda la Ilustración alemana: si puede haber convivencia razonable entre credos que se consideran mutuamente excluyentes.",
    },
    {
      type: "info",
      continues: true,
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "El centro de la obra es la llamada «parábola de los anillos»: un padre lega a sus tres hijos anillos idénticos, y ninguno de ellos puede probar que el suyo es el original y verdadero. La parábola no dice que las tres religiones —la judía, la cristiana, la musulmana— sean falsas por igual, sino que ninguna puede demostrar racionalmente, de manera concluyente, su superioridad exclusiva sobre las otras dos.",
    },
    {
      type: "info",
      continues: true,
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "En la versión de Lessing, un juez sabio al que consultan los tres hermanos —cada uno convencido de tener el anillo verdadero— no falla a favor de ninguno: los invita, en cambio, a que cada uno viva de tal manera que su anillo demuestre su virtud con hechos, con amor y con tolerancia hacia los otros dos, dejando que sea un juez futuro, mucho más lejano en el tiempo, quien eventualmente distinga cuál era el auténtico, si es que hay alguno.",
    },
    {
      type: "info",
      continues: true,
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "El personaje de Natán está inspirado, según reconoce el propio Lessing, en su amigo Mendelssohn, con quien había compartido años antes una intensa colaboración filosófica en Berlín. Escribir a un judío como el protagonista más sabio y virtuoso del drama es, en sí mismo, una respuesta práctica al antisemitismo de su época, y un homenaje directo a la persona que mejor encarna, para Lessing, el ideal ilustrado de tolerancia.",
    },
    {
      type: "info",
      continues: true,
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "La obra le cuesta cara: Lessing la escribe después de que la censura religiosa de Hamburgo le prohíba seguir publicando sus escritos teológicos en prosa, y recurre al teatro, un terreno donde la censura era menos estricta, para seguir exponiendo las mismas ideas bajo otra forma. Es un gesto típico de Lessing: cuando un camino se cierra, encuentra otro sin abandonar la tesis.",
    },
    {
      type: "info",
      continues: true,
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "El origen de esa prohibición es la llamada «disputa de los fragmentos»: entre 1774 y 1778, Lessing, que trabaja como bibliotecario en Wolfenbüttel, publica por entregas fragmentos anónimos del teólogo racionalista Hermann Samuel Reimarus, muerto ya en 1768, que someten a una crítica radical los relatos bíblicos de milagros y la resurrección de Cristo. La polémica que desatan esos fragmentos es lo que finalmente le cuesta a Lessing la censura directa.",
    },
    {
      type: "info",
      continues: true,
      title: "Natán el sabio y la tolerancia dramatizada",
      body: "Su principal adversario en esa disputa es el pastor Johann Melchior Goeze, quien acusa a Lessing de socavar los fundamentos mismos del cristianismo. Es precisamente cuando el duque de Brunswick, presionado por esa polémica, le retira a Lessing el permiso de seguir publicando textos teológicos, que él decide trasladar la discusión al escenario, donde la censura previa no llega con la misma facilidad.",
    },
    {
      type: "quiz",
      question: "La parábola de los anillos sostiene que…",
      options: [
        "ninguna religión puede probar que es la verdadera",
        "las tres religiones son igualmente falsas",
        "la religión verdadera se reconoce por sus milagros",
        "el padre eligió deliberadamente engañar a sus hijos",
      ],
      answer: 0,
      explain: "No dice que las tres sean falsas por igual: dice que ninguna puede demostrar racionalmente su superioridad exclusiva. El juez no falla, e invita a cada hermano a que su anillo demuestre su virtud con hechos, dejando el veredicto a un juez futuro mucho más lejano.",
    },
    {
      type: "quiz",
      question: "Lessing acaba llevando sus tesis al teatro porque…",
      options: [
        "le prohibieron publicar textos teológicos",
        "el teatro le daba más ingresos que la filosofía",
        "abandonó la teología por falta de convicción",
        "el duque de Brunswick le encargó una obra",
      ],
      answer: 0,
      explain: "Entre 1774 y 1778 publicó fragmentos anónimos del teólogo Reimarus, muerto en 1768, que criticaban radicalmente los relatos de milagros y la resurrección. La polémica con el pastor Goeze llevó al duque de Brunswick a retirarle el permiso, y Lessing trasladó la discusión al escenario, donde la censura previa no llegaba igual.",
    },
    {
      type: "info",
      title: "Verdades históricas y verdades de razón",
      body: "El núcleo filosófico de la posición de Lessing es la distinción entre **verdades de razón** y **verdades históricas**. Las verdades de razón —como los teoremas de la geometría— son necesarias: se demuestran por sí mismas y cualquiera que entienda los términos puede verificarlas sin depender de ningún testimonio ajeno.",
    },
    {
      type: "info",
      continues: true,
      title: "Verdades históricas y verdades de razón",
      body: "Las verdades históricas, en cambio, son contingentes: dependen de que algo haya ocurrido de determinada manera en un momento y un lugar particulares, y sólo podemos acceder a ellas por testimonio, nunca con la certeza absoluta de una demostración. Los relatos de milagros y de revelación que sostienen al cristianismo —la resurrección, por ejemplo— pertenecen a esta segunda categoría.",
    },
    {
      type: "info",
      continues: true,
      title: "Verdades históricas y verdades de razón",
      body: "El problema, para Lessing, es que la teología tradicional pretende fundar verdades necesarias —la existencia de Dios, la validez eterna de una doctrina moral— sobre la base de verdades meramente históricas y contingentes. Esa operación le parece ilegítima: ningún testimonio histórico, por bien atestiguado que esté, puede darle a una doctrina la necesidad racional que sólo la razón misma puede fundar. Es lo que Lessing llama, en una imagen célebre, «el ancho foso feo» que separa los hechos históricos de las verdades racionales, y que ningún salto lógico logra cruzar.",
    },
    {
      type: "info",
      continues: true,
      title: "Verdades históricas y verdades de razón",
      body: "Lessing lo formula de manera muy concreta en su ensayo Sobre la prueba del espíritu y de la fuerza (1777): incluso si hubiera presenciado personalmente un milagro en el siglo I, esa experiencia le habría dado, a lo sumo, una verdad histórica contingente sobre lo que vio ese día. Pero él vive diecisiete siglos después, y sólo cuenta con relatos de segunda o tercera mano, cada vez más alejados del hecho original y por lo tanto menos ciertos, no más.",
    },
    {
      type: "info",
      continues: true,
      title: "Verdades históricas y verdades de razón",
      body: "Esta distinción coloca a Lessing a distancia tanto de la ortodoxia religiosa —que exige creer en la revelación literalmente y sin reservas— como del racionalismo más agresivo de un Voltaire o de un materialista francés, que directamente descarta el valor de la revelación. Lessing busca una tercera vía: conservar el valor de la tradición religiosa sin pedirle a la razón que la acepte como si fuera necesaria.",
    },
    {
      type: "classify",
      question: "¿Cada caso es una verdad de razón o una verdad histórica?",
      groups: ["Verdad de razón", "Verdad histórica"],
      items: [
        { text: "Un teorema de la geometría", group: 0 },
        { text: "La resurrección de Cristo", group: 1 },
        { text: "Lo que alguien atestigua haber visto", group: 1 },
        { text: "Algo que cualquiera puede verificar solo", group: 0 },
        { text: "Un milagro ocurrido en el siglo I", group: 1 },
        { text: "Algo que se demuestra por sí mismo", group: 0 },
      ],
      explain: "Las de razón son necesarias y no dependen de ningún testimonio ajeno. Las históricas son contingentes: dependen de que algo haya ocurrido de cierta manera en un lugar y un momento, y sólo se accede a ellas por testimonio. Los relatos de milagros y de revelación pertenecen a la segunda categoría.",
    },
    {
      type: "quiz",
      question: "«El ancho foso feo» de Lessing separa…",
      options: [
        "los hechos históricos de las verdades de razón",
        "la fe de los creyentes de la de los teólogos de oficio",
        "el Antiguo del Nuevo Testamento",
        "la razón ilustrada de la superstición popular",
      ],
      answer: 0,
      explain: "Ningún testimonio histórico, por bien atestiguado que esté, puede darle a una doctrina la necesidad racional que sólo la razón funda. En Sobre la prueba del espíritu y de la fuerza (1777) lo dice concreto: haber presenciado un milagro daría a lo sumo una verdad contingente sobre lo visto ese día, y él vive diecisiete siglos después, con relatos de tercera mano.",
    },
    {
      type: "info",
      title: "La revelación como pedagogía",
      body: "Esa tercera vía se despliega en su obra más importante en este terreno, **La educación del género humano** (1780), publicada de forma anónima poco antes de su muerte. La tesis central es que la **revelación** religiosa no es la comunicación de verdades que la razón no podría alcanzar nunca por sí misma, sino un atajo pedagógico: le da a la humanidad, en su infancia histórica, verdades que en principio también podría descubrir sola, pero más tarde y con más esfuerzo.",
    },
    {
      type: "info",
      continues: true,
      title: "La revelación como pedagogía",
      body: "La imagen que organiza todo el texto es la de la **educación**: así como un maestro le enseña a un niño primero verdades simples, adaptadas a su capacidad, y sólo después conceptos más complejos, Dios «educa» al género humano entregándole revelaciones sucesivas, cada una adaptada al estado de desarrollo moral e intelectual de la humanidad en ese momento de su historia.",
    },
    {
      type: "info",
      continues: true,
      title: "La revelación como pedagogía",
      body: "Lessing recorre así las etapas de esa educación: el Antiguo Testamento le enseña a un pueblo todavía infantil ideas rudimentarias, como la existencia de un único Dios, mediante premios y castigos terrenales concretos, porque es lo único que ese estadio de desarrollo puede asimilar. El Nuevo Testamento introduce ideas más elevadas —la inmortalidad del alma, una moral fundada en la virtud y no sólo en el castigo— porque la humanidad ya maduró para recibirlas.",
    },
    {
      type: "info",
      continues: true,
      title: "La revelación como pedagogía",
      body: "Lessing compara ese proceso con las etapas del aprendizaje escolar: al niño no se le enseña álgebra antes de que sepa contar, ni se le exige que entienda por qué una regla es cierta antes de que pueda simplemente aplicarla con confianza en el maestro. De la misma manera, a la humanidad «infantil» del Antiguo Testamento no podía exigírsele todavía una moral fundada en razones propias: necesitaba mandamientos concretos, respaldados por autoridad y por consecuencias tangibles.",
    },
    {
      type: "info",
      continues: true,
      title: "La revelación como pedagogía",
      body: "Ninguna de esas revelaciones es, entonces, un error a descartar ni una verdad definitiva a la que ya no se pueda agregar nada. Cada una cumplió su función histórica en su momento, y el proceso educativo continúa: Lessing especula con la posibilidad de una futura «edad de un nuevo Evangelio eterno», en la que el ser humano practique el bien por convicción racional propia, sin necesitar ya premios ni castigos externos que se lo impongan.",
    },
    {
      type: "info",
      continues: true,
      title: "La revelación como pedagogía",
      body: "Esta idea de progreso educativo transforma la historia entera en un proceso con dirección y sentido, no en una sucesión arbitraria de creencias que se reemplazan unas a otras sin conexión. Es una filosofía de la historia religiosa, en la línea de lo que en la propia Ilustración se pensaba sobre el progreso científico y político, pero aplicada al terreno de la fe.",
    },
    {
      type: "quiz",
      question: "Para Lessing, la revelación…",
      options: [
        "adelanta verdades que la razón hallaría sola",
        "comunica lo que la razón no alcanzará nunca",
        "es una superstición sin ningún valor",
        "debe creerse literalmente y sin reservas",
      ],
      answer: 0,
      explain: "Es un atajo pedagógico: le da a la humanidad, en su infancia histórica, verdades que en principio también podría descubrir sola, pero más tarde y con más esfuerzo. Las otras tres opciones son, en orden, la teología tradicional, el materialismo francés y la ortodoxia.",
    },
    {
      type: "quiz",
      question: "En el esquema de Lessing, el Antiguo Testamento…",
      options: [
        "enseña con premios y castigos terrenales",
        "ya contiene la doctrina de la inmortalidad",
        "es un error que el Nuevo viene a corregir",
        "se dirige a una humanidad ya madura",
      ],
      answer: 0,
      explain: "Le enseña a un pueblo todavía infantil ideas rudimentarias, como la de un único Dios, con consecuencias tangibles, porque es lo único que ese estadio puede asimilar. El Nuevo introduce la inmortalidad del alma y una moral de la virtud. Ninguna revelación es un error: cada una cumplió su función en su momento.",
    },
    {
      type: "short",
      question: "¿Qué figura organiza toda la explicación de Lessing sobre la revelación?",
      answers: ["la educación", "educación"],
      explain: "Así como un maestro enseña primero verdades simples adaptadas a la capacidad del niño, Dios educa al género humano con revelaciones sucesivas, cada una ajustada al estado de desarrollo moral e intelectual de la humanidad en ese momento.",
    },
    {
      type: "info",
      continues: true,
      title: "La revelación como pedagogía",
      body: "Lessing agrega, en los parágrafos finales del texto, una idea inesperada: sugiere la posibilidad de que un alma individual pueda regresar más de una vez a este mundo, en distintas etapas de la historia, para completar su propia educación junto con la del resto de la humanidad. No la presenta como un dogma sino como una conjetura razonable, y el pasaje muestra hasta qué punto está dispuesto a especular más allá de la ortodoxia cristiana sin abandonar el marco religioso.",
    },
    {
      type: "info",
      title: "El doble filo de Lessing frente a la Ilustración",
      body: "Que la revelación tenga una función pedagógica implica algo incómodo para el racionalismo ilustrado más estricto: que la razón sola, en un momento dado de la historia, todavía no basta. La Ilustración confía en que el individuo adulto puede prescindir de tutores y pensar por sí mismo; Lessing responde que la humanidad entera, como especie, todavía está en un proceso educativo del que no salió del todo, y que necesita guías —revelaciones, tradiciones— mientras dura ese proceso.",
    },
    {
      type: "info",
      continues: true,
      title: "El doble filo de Lessing frente a la Ilustración",
      body: "Esa reserva es lo que vuelve a Lessing una figura bisagra entre la Ilustración y su crisis posterior. No niega el valor de la razón —al contrario, confía en que la humanidad va a llegar, algún día, a prescindir de la revelación—, pero tampoco acepta la seguridad con que otros ilustrados descartan de un plumazo toda la tradición religiosa como mera superstición sin ningún valor cognitivo.",
    },
    {
      type: "info",
      continues: true,
      title: "El doble filo de Lessing frente a la Ilustración",
      body: "Esa misma incomodidad frente al racionalismo estricto de la Ilustración va a radicalizarse, pocos años después de la muerte de Lessing, en autores como Johann Georg Hamann, que llevan la crítica de la razón calculadora mucho más lejos que él, hasta cuestionar la posibilidad misma de una razón separada del lenguaje y de la fe.",
    },
    {
      type: "info",
      continues: true,
      title: "El doble filo de Lessing frente a la Ilustración",
      body: "Esa figura de Lessing como bisagra se aprecia bien si se lo compara con Mendelssohn, su amigo cercano y su modelo para Natán. Mendelssohn confía en que ilustración y tradición religiosa pueden convivir en equilibrio estable, sin que una deba subordinarse a la otra con el tiempo. Lessing, en cambio, piensa la relación como una etapa transitoria: la revelación es un andamiaje necesario sólo mientras la razón humana todavía no maduró para prescindir de él, y ese andamiaje, tarde o temprano, está destinado a caer.",
    },
    {
      type: "quiz",
      question: "Para Mendelssohn la relación entre razón y religión es estable; para Lessing es…",
      options: [
        "transitoria, un andamiaje destinado a caer",
        "conflictiva, y sin ninguna salida posible",
        "puramente política, no filosófica",
        "necesaria en todas las etapas de la historia",
      ],
      answer: 0,
      explain: "Mendelssohn confía en que ilustración y tradición religiosa conviven en equilibrio, sin que una deba subordinarse a la otra. Para Lessing la revelación es un andamiaje necesario sólo mientras la razón humana no maduró para prescindir de él.",
    },
    {
      type: "info",
      title: "El lugar de Lessing en el mapa de la Ilustración",
      body: "Lessing muere en 1781, un año después de publicar La educación del género humano, sin ver el desenlace de la controversia que su obra desata poco después de su muerte, cuando su amigo Friedrich Heinrich Jacobi revela que Lessing le había confesado simpatías spinozistas. Ese episodio, la llamada disputa del panteísmo, convulsiona a la cultura alemana y marca el final simbólico de la Ilustración como consenso tranquilo.",
    },
    {
      type: "info",
      continues: true,
      title: "El lugar de Lessing en el mapa de la Ilustración",
      body: "Con Lessing se cierra el arco de las tres Ilustraciones nacionales: la inglesa, confiada y reformista; la francesa, combativa y anticlerical; la alemana, reflexiva y conciliadora. Las tres comparten la fe en la razón, pero Lessing es quien mejor anuncia, desde dentro del propio movimiento, las preguntas que la próxima generación —empezando por Kant— va a tener que responder sobre los límites de esa razón.",
    },
    {
      type: "match",
      question: "Uní cada obra o episodio con lo que le corresponde",
      pairs: [
        { left: "Natán el sabio (1779)", right: "La parábola de los anillos y la tolerancia" },
        { left: "La educación del género humano (1780)", right: "La revelación como atajo pedagógico" },
        { left: "Disputa de los fragmentos", right: "Los textos de Reimarus contra los milagros" },
        { left: "Disputa del panteísmo", right: "Jacobi revela su spinozismo tras su muerte" },
      ],
      explain: "Lessing muere en 1781 sin ver la controversia que su obra desata: cuando Jacobi revela que le había confesado simpatías spinozistas, la disputa convulsiona la cultura alemana y marca el final simbólico de la Ilustración como consenso tranquilo.",
    },
    {
      type: "info",
      continues: true,
      title: "El lugar de Lessing en el mapa de la Ilustración",
      body: "La ironía final de esta historia es que el propio Lessing, muerto antes de ver las consecuencias, termina siendo reclutado después de su muerte tanto por quienes defienden la Ilustración como por quienes la atacan: unos lo leen como el ilustrado tolerante de Natán, otros como el crítico de la razón calculadora que anuncia el romanticismo. Esa doble lectura, más que un malentendido, confirma exactamente lo que esta clase quiso mostrar: Lessing no elige un bando, y esa ambigüedad es su aporte más duradero.",
    },
  ],
};
