// Diccionario filosófico del curso. Cada entrada se auto-linkea en las cards:
// agregar una entrada acá la vuelve clicable en todo el contenido.
//
// GENERADO por scripts/merge-glosario.mjs desde los glosario-*.md del curso.
// No lo edites a mano: editá el .md del bloque correspondiente y regenerá.
//
// Campos:
//   term  : nombre canónico que se muestra en el modal
//   aka   : formas que aparecen en el texto y deben detectarse (incluí el canónico)
//   kind  : 'autor' | 'concepto' | 'obra' | 'evento'
//   when  : fechas de referencia (autor: nacimiento–muerte; resto: época)
//   body  : explicación breve y en profundidad

export const GLOSSARY = {
  // ---------- autores ----------
  bacon: {
    term: "Francis Bacon",
    aka: ["Francis Bacon", "Bacon"],
    kind: "autor",
    when: "1561–1626",
    body: "Filósofo inglés, considerado el primer empirista moderno. En el *Novum Organum* (1620) denuncia los ídolos que distorsionan el conocimiento humano y propone el método inductivo como alternativa a la lógica deductiva escolástica para el estudio de la naturaleza.",
  },
  berkeley: {
    term: "George Berkeley",
    aka: ["George Berkeley", "Berkeley"],
    kind: "autor",
    when: "1685–1753",
    body: "Filósofo y obispo anglo-irlandés. En los *Principios del conocimiento humano* (1710) lleva el empirismo de Locke a su consecuencia más radical: niega la existencia de una materia independiente de toda mente que la perciba, y defiende el inmaterialismo bajo el principio esse est percipi.",
  },
  copernico: {
    term: "Nicolás Copérnico",
    aka: ["Nicolás Copérnico", "Copérnico"],
    kind: "autor",
    when: "1473–1543",
    body: "Astrónomo polaco que propone en Sobre las revoluciones de los orbes celestes (1543) el modelo heliocéntrico: la Tierra y los demás planetas giran alrededor del Sol, en lugar del modelo geocéntrico ptolemaico adoptado por la astronomía aristotélica medieval. Su propuesta, aunque conserva el prejuicio antiguo de las órbitas circulares, inaugura el proceso de matematización de la naturaleza que Kepler, Galileo y Newton llevarán a su forma madura.",
  },
  dalembert: {
    term: "Jean le Rond d'Alembert",
    aka: ["d'Alembert", "Jean le Rond d'Alembert"],
    kind: "autor",
    when: "1717–1783",
    body: "Matemático, físico y filósofo francés, codirector de la Enciclopedia junto con Diderot. Redacta el «Discurso preliminar» de la obra, que organiza el conjunto del saber humano según sus facultades —memoria, razón, imaginación— y presenta el proyecto enciclopédico ante el público culto de su época.",
  },
  descartes: {
    term: "René Descartes",
    aka: ["René Descartes", "Descartes"],
    kind: "autor",
    when: "1596–1650",
    body: "Filósofo y matemático francés, considerado por muchos historiadores el punto de partida de la filosofía moderna. Busca fundamentar racionalmente tanto la física matemática como la metafísica mediante una duda metódica que desemboca en el cogito y, a partir de él, en la demostración de la existencia de Dios como garante del conocimiento. Autor del Discurso del método (1637) y las Meditaciones metafísicas (1641), entre otras obras.",
  },
  dholbach: {
    term: "Barón d'Holbach",
    aka: ["Barón d'Holbach", "d'Holbach", "Paul-Henri Thiry"],
    kind: "autor",
    when: "1723–1789",
    body: "Filósofo francés de origen alemán, colaborador de la Enciclopedia y anfitrión de uno de los salones más frecuentados por los philosophes en París. Autor del Sistema de la naturaleza (1770), publicado bajo seudónimo, donde lleva el materialismo francés hasta el ateísmo declarado: sostiene que el universo es sólo materia en movimiento regida por leyes necesarias, sin lugar para un dios creador.",
  },
  diderot: {
    term: "Denis Diderot",
    aka: ["Denis Diderot", "Diderot"],
    kind: "autor",
    when: "1713–1784",
    body: "Filósofo y escritor francés, director junto con d'Alembert de la Enciclopedia (1751–1772). Autor del artículo «Filósofo» y de escritos como El sueño de d'Alembert, en los que avanza hacia el materialismo francés. Combina la energía editorial del proyecto enciclopédico con una escritura filosófica cada vez más audaz frente a la censura.",
  },
  dotti: {
    term: "Jorge Dotti",
    aka: ["Jorge Dotti", "Dotti"],
    kind: "autor",
    when: "siglo XX–XXI",
    body: "Filósofo argentino, historiador de las ideas políticas modernas y docente e investigador en la Universidad de Buenos Aires. Autor de estudios sobre el pensamiento político moderno y sobre la filosofía política alemana, usados como bibliografía de referencia para el contractualismo de los siglos XVII y XVIII.",
  },
  "erasmo-de-rotterdam": {
    term: "Erasmo de Rotterdam",
    aka: ["Erasmo", "Erasmo de Rotterdam", "Desiderius Erasmus"],
    kind: "autor",
    when: "1466–1536",
    body: "Humanista holandés, la figura más influyente del humanismo cristiano del norte de Europa. Editor crítico del Nuevo Testamento en griego y autor del Elogio de la locura (1511), combina la filología clásica con una crítica moral e institucional de los abusos del clero. A diferencia de Lutero, con quien mantuvo una polémica pública sobre el libre albedrío, nunca rompió con Roma: buscó reformar la Iglesia desde dentro mediante la educación y el retorno a las fuentes bíblicas y clásicas.",
  },
  "federico-ii": {
    term: "Federico II de Prusia",
    aka: ["Federico II de Prusia", "Federico II", "Federico el Grande"],
    kind: "autor",
    when: "1712–1786",
    body: "Rey de Prusia desde 1740. Encarna el despotismo ilustrado: aplica en su reino tolerancia religiosa, reforma legal y fomento de las ciencias y las artes sin renunciar a la concentración del poder en su propia persona. Bajo su reinado, Berlín se convierte en centro de la Aufklärung, con Wolff de regreso del exilio y correspondencia directa con Voltaire.",
  },
  galileo: {
    term: "Galileo Galilei",
    aka: ["Galileo Galilei", "Galileo"],
    kind: "autor",
    when: "1564–1642",
    body: "Físico y astrónomo italiano, protagonista central de la matematización moderna de la naturaleza. Sostiene, en Il saggiatore, que el universo está escrito en caracteres matemáticos y que solo quien conoce ese lenguaje puede comprender los fenómenos naturales; concibe el espacio físico como homogéneo y cuantitativo, asimilándolo al espacio geométrico. A diferencia de Descartes, sostiene que la física debe independizarse de la metafísica y fundarse en la experimentación controlada.",
  },
  "giordano-bruno": {
    term: "Giordano Bruno",
    aka: ["Giordano Bruno", "Bruno"],
    kind: "autor",
    when: "1548–1600",
    body: "Filósofo italiano que radicaliza la idea cusana del infinito actual: Dios no es causa exterior del mundo, sino principio inmanente de un todo único del que las cosas particulares son meras manifestaciones. En Sobre el infinito universo y los mundos (1584) sostiene la existencia de infinitos mundos en un espacio infinito, tesis incompatible con el dogma de la encarnación única de Cristo. Condenado por hereje, es quemado en la hoguera en Roma en 1600. Sus ideas inauguran, según Alexandre Koyré, el pasaje del mundo cerrado al universo infinito.",
  },
  goeze: {
    term: "Johann Melchior Goeze",
    aka: ["Johann Melchior Goeze", "Goeze", "pastor Goeze"],
    kind: "autor",
    when: "1717–1786",
    body: "Pastor luterano principal de Hamburgo, defensor de la ortodoxia bíblica, que encabezó la controversia pública contra Lessing a raíz de la publicación de los fragmentos de Reimarus. Su enfrentamiento con Lessing es el episodio que lleva a Lessing a trasladar su crítica religiosa del ensayo teológico al teatro, con Natán el sabio.",
  },
  grocio: {
    term: "Hugo Grocio",
    aka: ["Hugo Grocio", "Grocio"],
    kind: "autor",
    when: "1583–1645",
    body: "Jurista y filósofo neerlandés, fundador del derecho natural moderno. En Sobre el derecho de la guerra y de la paz (1625) busca un fundamento racional y secular para el derecho internacional, independiente de la autoridad religiosa del Papa, desacreditada tras la Reforma. Su procedimiento —derivar reglas universales de la razón común a todos los seres humanos— será retomado por los teóricos modernos del contrato social, entre ellos Rousseau.",
  },
  hamann: {
    term: "Johann Georg Hamann",
    aka: ["Johann Georg Hamann", "Hamann"],
    kind: "autor",
    when: "1730–1788",
    body: "Filósofo y escritor alemán, nacido en Königsberg, la misma ciudad de Kant, a quien conoció personalmente y trató durante décadas. Empleado subalterno, sin cátedra ni carrera académica, atravesó una crisis religiosa en Londres en 1758 que lo devolvió a una lectura intensa de la Biblia; desde entonces escribió como creyente contra la pretensión ilustrada de una razón autosuficiente. Le decían el mago del Norte por su estilo deliberadamente oscuro: fragmentos, textos breves, prosa cargada de citas, ironías y alusiones, elegido así porque desconfiaba de la exposición sistemática. En las Memorias socráticas (1759) opuso al Sócrates racionalista de los ilustrados un Sócrates que declara su ignorancia y obedece a un daimon que no puede justificar. Es una figura de referencia del Sturm und Drang y el maestro reconocido de Herder. Su objeción central a la Ilustración es que no hay razón sin lenguaje, y que el lenguaje es sensible, histórico y recibido, de modo que una razón pura es una ficción.",
  },
  hobbes: {
    term: "Thomas Hobbes",
    aka: ["Thomas Hobbes", "Hobbes"],
    kind: "autor",
    when: "1588–1679",
    body: "Filósofo inglés, uno de los fundadores del contractualismo moderno. En el *Leviatán* (1651) describe un estado de naturaleza de guerra de todos contra todos, del que los individuos escapan transfiriendo casi sin reservas su derecho a un soberano absoluto capaz de garantizar la paz civil.",
  },
  hume: {
    term: "David Hume",
    aka: ["David Hume", "Hume"],
    kind: "autor",
    when: "1711–1776",
    body: "Filósofo escocés, la figura más radical del empirismo. Autor del *Tratado de la naturaleza humana* (1739) y de la *Investigación sobre el entendimiento humano* (1748), donde analiza el origen de las ideas humanas y somete a crítica la validez objetiva de la noción de causalidad.",
  },
  kant: {
    term: "Immanuel Kant",
    aka: ["Immanuel Kant", "Kant"],
    kind: "autor",
    when: "1724–1804",
    body: "Filósofo alemán, nacido y muerto en Königsberg, en la Prusia oriental, ciudad de la que prácticamente no salió. Es la figura que cierra la filosofía moderna y abre la contemporánea. Después de una etapa formado en el racionalismo de Leibniz y Wolff, la lectura de Hume lo despertó, según su propia expresión, de su «sueño dogmático»: el escepticismo de Hume sobre la causalidad amenazaba tanto a la metafísica como a la física de Newton. Kant dedicó una década de silencio a responderle, y publicó la Crítica de la razón pura en 1781, a los cincuenta y siete años. Su solución fue el giro copernicano: en vez de suponer que el conocimiento se ajusta a los objetos, suponer que los objetos de la experiencia se ajustan a las formas del sujeto que conoce. De ahí se sigue que el conocimiento es objetivo pero limitado a los fenómenos, y que la metafísica tradicional —sobre el alma, el mundo y Dios— no es una ciencia posible. Completó el sistema con la Crítica de la razón práctica (1788), donde funda la moral en el imperativo categórico, y la Crítica del juicio (1790), sobre lo bello y lo teleológico. Su artículo «Respuesta a la pregunta: ¿qué es la Ilustración?» (1784) es la definición canónica del movimiento.",
  },
  kepler: {
    term: "Johannes Kepler",
    aka: ["Johannes Kepler", "Kepler"],
    kind: "autor",
    when: "1571–1630",
    body: "Astrónomo y matemático alemán que perfecciona el modelo heliocéntrico de Copérnico al sustituir las órbitas circulares por elipses y formular las leyes matemáticas que describen el movimiento planetario. Con Kepler la astronomía deja de ser una geometría de apariencias y pasa a explicar matemáticamente la causa del movimiento de los planetas, un paso decisivo en la matematización moderna de la naturaleza.",
  },
  koyre: {
    term: "Alexandre Koyré",
    aka: ["Alexandre Koyré", "Koyré"],
    kind: "autor",
    when: "1892–1964",
    body: "Historiador de la ciencia francés de origen ruso, autor de estudios clásicos sobre la revolución científica del siglo XVII. Describió ese proceso como el pasaje \"del mundo cerrado al universo infinito\": la sustitución de un cosmos jerárquico y finito por un espacio homogéneo e infinito regido por leyes matemáticas universales, y subrayó la filiación platónica, más que puramente empírica, del pensamiento de Galileo y sus contemporáneos.",
  },
  leibniz: {
    term: "Gottfried Wilhelm Leibniz",
    aka: ["Gottfried Wilhelm Leibniz", "Leibniz"],
    kind: "autor",
    when: "1646–1716",
    body: "Filósofo, matemático y científico alemán, creador junto con Newton del cálculo infinitesimal. Radicaliza el innatismo racionalista y desarrolla una metafísica de sustancias simples, las mónadas, expuesta en la *Monadología* (1714), que incluye la armonía preestablecida, el principio de razón suficiente y la teodicea.",
  },
  lessing: {
    term: "Gotthold Ephraim Lessing",
    aka: ["Gotthold Ephraim Lessing", "Lessing"],
    kind: "autor",
    when: "1729–1781",
    body: "Crítico literario, dramaturgo y filósofo alemán, hijo de un pastor luterano. Una de las figuras mayores de la Aufklärung y, a la vez, uno de los primeros en señalarle sus límites. Publica los fragmentos de Reimarus entre 1774 y 1778, lo que le cuesta la censura de sus escritos teológicos, y traslada entonces su crítica religiosa al teatro.",
  },
  locke: {
    term: "John Locke",
    aka: ["John Locke", "Locke"],
    kind: "autor",
    when: "1632–1704",
    body: "Filósofo inglés, figura central del empirismo y del contractualismo liberal. Autor del *Ensayo sobre el entendimiento humano* (1690), donde refuta el innatismo racionalista, y de los *Dos tratados sobre el gobierno civil* (1689), donde defiende derechos naturales previos al Estado y límites al poder político.",
  },
  lutero: {
    term: "Martín Lutero",
    aka: ["Martín Lutero", "Lutero"],
    kind: "autor",
    when: "1483–1546",
    body: "Fraile agustino y teólogo alemán, iniciador de la Reforma protestante (1517). Rechaza la mediación de la Iglesia romana en la interpretación de las Escrituras (doctrina del libre examen) y en la administración de lo sagrado (sacerdocio universal), y traduce el Nuevo Testamento al alemán. Sus tesis desatan las guerras de religión que fracturan el mapa político europeo durante los siglos XVI y XVII.",
  },
  macpherson: {
    term: "C. B. Macpherson",
    aka: ["C. B. Macpherson", "Macpherson"],
    kind: "autor",
    when: "1911–1987",
    body: "Politólogo canadiense, autor de *La teoría política del individualismo posesivo* (1962), estudio clásico sobre Hobbes y Locke. Sostiene que ambos comparten una imagen del individuo como propietario de sí mismo y de sus capacidades, previa e independiente de cualquier obligación social.",
  },
  mendelssohn: {
    term: "Moses Mendelssohn",
    aka: ["Moses Mendelssohn", "Mendelssohn"],
    kind: "autor",
    when: "1729–1786",
    body: "Filósofo alemán de origen judío, figura central de la Ilustración berlinesa. Autodidacta, llega a Berlín en 1743 y se forma en filosofía, matemática y lenguas clásicas hasta ganarse el respeto de Kant. Defiende la emancipación civil de los judíos y, en «Sobre la pregunta: ¿qué significa ilustrar?» (1784), distingue ilustración de cultura como dos procesos independientes.",
  },
  montaigne: {
    term: "Michel de Montaigne",
    aka: ["Michel de Montaigne", "Montaigne"],
    kind: "autor",
    when: "1533–1592",
    body: "Escritor y filósofo francés, la figura central del escepticismo renacentista. En sus Ensayos (publicados desde 1580) desarrolla una crítica de la presunción humana bajo dos formas, el antropocentrismo y el etnocentrismo, y propone la abstención del juicio —resumida en la pregunta \"¿Qué sé yo?\"— como actitud propia de una razón humana frágil y falible. Su desconfianza en la razón anticipa tanto la duda metódica cartesiana como las críticas empiristas al dogmatismo racionalista.",
  },
  montesquieu: {
    term: "Montesquieu",
    aka: ["Montesquieu", "barón de Montesquieu", "Charles-Louis de Secondat"],
    kind: "autor",
    when: "1689–1755",
    body: "Filósofo y jurista francés. En El espíritu de las leyes (1748) analiza cómo las leyes de cada pueblo dependen de factores concretos —clima, territorio, costumbres, religión— y no de un modelo único de buen gobierno. Formula la doctrina de la separación de poderes, tomando como referencia el gobierno mixto inglés.",
  },
  newton: {
    term: "Isaac Newton",
    aka: ["Isaac Newton", "Newton"],
    kind: "autor",
    when: "1643–1727",
    body: "Físico y matemático inglés que culmina el proceso de matematización de la naturaleza iniciado por Copérnico. En los Principios matemáticos de la filosofía natural (1687) formula la ley de gravitación universal, que explica con una sola ecuación tanto la caída de los cuerpos en la Tierra como el movimiento de los planetas, superando la distinción aristotélica entre un mundo supralunar y otro sublunar regidos por leyes distintas.",
  },
  "nicolas-de-cusa": {
    term: "Nicolás de Cusa",
    aka: ["Nicolás de Cusa", "el Cusano"],
    kind: "autor",
    when: "1401–1464",
    body: "Cardenal y filósofo alemán, autor de La docta ignorancia. Sostiene que el orden y la clasificación que atribuimos al universo no son objetivos, sino efecto de las limitaciones de un entendimiento humano regido por el principio de no contradicción; el entendimiento divino, en cambio, coincide en los opuestos e ignora esas divisiones. Su idea de un infinito actual, más allá de toda clasificación, influye decisivamente en Giordano Bruno y, a través de él, en la metafísica del siglo XVII.",
  },
  pascal: {
    term: "Blaise Pascal",
    aka: ["Blaise Pascal", "Pascal"],
    kind: "autor",
    when: "1623–1662",
    body: "Matemático, físico y filósofo francés. Trabajó en geometría, hidrostática y cálculo de probabilidades antes de volcarse a la apologética religiosa. En los *Pensamientos* (1670, publicación póstuma) advierte los límites del método geométrico para dar sentido a la existencia individual frente al universo infinito de la nueva física.",
  },
  reimarus: {
    term: "Hermann Samuel Reimarus",
    aka: ["Hermann Samuel Reimarus", "Reimarus"],
    kind: "autor",
    when: "1694–1768",
    body: "Teólogo y filólogo alemán, profesor en Hamburgo, que dejó inédita al morir una extensa crítica racionalista de los relatos bíblicos de milagros y de la resurrección de Cristo. Lessing publicó fragmentos de ese manuscrito entre 1774 y 1778 sin identificar a su autor, lo que desató la disputa de los fragmentos.",
  },
  rousseau: {
    term: "Jean-Jacques Rousseau",
    aka: ["Jean-Jacques Rousseau", "Rousseau"],
    kind: "autor",
    when: "1712–1778",
    body: "Filósofo ginebrino. En el Discurso sobre el origen de la desigualdad entre los hombres (1755) describe la desigualdad como un producto histórico, originado en la propiedad privada, y no como un rasgo del estado de naturaleza. En El contrato social (1762) propone un pacto fundado en la voluntad general que permita reconstruir, en la vida civil, la libertad e igualdad perdidas. Reaparece más adelante en el curso como antagonista de Voltaire en el debate sobre la Ilustración.",
  },
  shaftesbury: {
    term: "Shaftesbury",
    aka: ["Shaftesbury", "tercer conde de Shaftesbury", "Anthony Ashley Cooper"],
    kind: "autor",
    when: "1671–1713",
    body: "Filósofo inglés, autor de Characteristics (1711). Sostiene que el ser humano posee un sentido moral natural, independiente de premios y castigos religiosos, y que el buen gusto estético y la virtud moral nacen de una misma armonía interior: reconocemos lo bueno con la misma inmediatez con que reconocemos lo bello. Su Dios es un principio de orden, no un juez.",
  },
  spinoza: {
    term: "Baruch Spinoza",
    aka: ["Baruch Spinoza", "Spinoza"],
    kind: "autor",
    when: "1632–1677",
    body: "Filósofo neerlandés de origen sefardí, excomulgado de su comunidad judía por sus ideas. Autor de una metafísica monista expuesta more geometrico en la *Ética* (1677), según la cual sólo existe una sustancia infinita, identificada con Dios y con la naturaleza, de la que todo se sigue con necesidad.",
  },
  toland: {
    term: "John Toland",
    aka: ["John Toland", "Toland"],
    kind: "autor",
    when: "1670–1722",
    body: "Filósofo irlandés, uno de los primeros deístas ingleses. En El cristianismo no misterioso (1696) sostiene que ninguna doctrina cristiana genuina puede ser contraria a la razón, y que los «misterios» de la fe son acumulaciones históricas y no verdades reveladas irreductibles. El libro es quemado públicamente en Irlanda. En obras posteriores se acerca al panteísmo, cercano a Spinoza.",
  },
  voltaire: {
    term: "Voltaire",
    aka: ["Voltaire", "François-Marie Arouet"],
    kind: "autor",
    when: "1694–1778",
    body: "Escritor y filósofo francés, la figura central de la Ilustración francesa. Exiliado en Inglaterra entre 1726 y 1729, vuelve convencido de la superioridad del modelo inglés de tolerancia, ciencia y gobierno limitado. Deísta, enemigo declarado del fanatismo religioso y activo en campañas judiciales concretas, como la del caso Calas. Muere el mismo año que Rousseau, 1778.",
  },
  wolff: {
    term: "Christian Wolff",
    aka: ["Christian Wolff", "Wolff"],
    kind: "autor",
    when: "1679–1754",
    body: "Filósofo alemán, profesor en Halle, que le da a la Aufklärung su primer lenguaje filosófico sistemático: un racionalismo heredero de Leibniz, organizado en definiciones encadenadas y expuesto, por primera vez, en alemán y no en latín. Expulsado de Prusia en 1723 por presión pietista, vuelve en 1740 llamado por Federico II.",
  },
  zollner: {
    term: "Johann Friedrich Zöllner",
    aka: ["Johann Friedrich Zöllner", "Zöllner"],
    kind: "autor",
    when: "1753–1804",
    body: "Teólogo alemán que, en diciembre de 1783, publica en la Berlinische Monatsschrift un artículo sobre el matrimonio civil con una nota al pie que pregunta «¿Qué es la Ilustración?», y sugiere que habría que responderla antes de seguir «ilustrando». La pregunta motiva las respuestas de Mendelssohn y de Kant, ambas de 1784.",
  },
  // ---------- conceptoes ----------
  "a-priori": {
    term: "A priori",
    aka: ["a priori", "conocimiento a priori"],
    kind: "concepto",
    when: "siglo XVII–XVIII",
    body: "Tipo de conocimiento universal, necesario e independiente de la experiencia, del que la matemática es el ejemplo paradigmático para el racionalismo. Se opone al conocimiento a posteriori, particular, contingente y dependiente de la experiencia, propio del conocimiento fáctico defendido por los empiristas.",
  },
  apercepcion: {
    term: "Apercepción",
    aka: ["apercepción"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "En Leibniz, conciencia reflexiva que una mónada tiene de sus propias percepciones, distinta de la mera percepción confusa de las mónadas más simples. El alma humana alcanza apercepción; las mónadas inferiores perciben el universo sin ser conscientes de ello, como en un sueño sin reflexión.",
  },
  "aristotelismo-escolastico": {
    term: "Aristotelismo escolástico",
    aka: ["aristotelismo escolástico", "escolástica", "física aristotélica"],
    kind: "concepto",
    when: "siglos XIII–XVII",
    body: "Síntesis de la filosofía natural de Aristóteles con la teología cristiana, enseñada en las universidades medievales y todavía vigente en el siglo XVII. Concibe la naturaleza como un cosmos jerárquico y cualitativamente diferenciado, donde los cuerpos se mueven hacia lugares naturales heterogéneos según fines propios (explicación teleológica), y mantiene separadas la física, que estudia sustancias sensibles, y la geometría, que estudia magnitudes abstractas. Es el adversario común frente al cual se definen tanto las raíces de la filosofía moderna como la nueva ciencia del siglo XVII.",
  },
  "armonia-preestablecida": {
    term: "Armonía preestablecida",
    aka: ["armonía preestablecida"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Doctrina de Leibniz según la cual Dios ajustó de antemano, desde la creación, el desarrollo interno de cada mónada para que coincida con el de todas las demás, sin que interactúen entre sí. Explica también la relación entre alma y cuerpo, coordinados sin causación directa.",
  },
  aufklarung: {
    term: "Aufklärung",
    aka: ["Aufklärung"],
    kind: "concepto",
    when: "1750–1789",
    body: "Nombre alemán de la Ilustración. Designa su variante más moderada y universitaria, desarrollada en un territorio fragmentado en principados sin una única corte ni una única Iglesia estatal a la que enfrentar, y que busca conciliar la razón con la fe religiosa en vez de oponerlas. Su centro más activo es la Berlín de Federico II.",
  },
  categorias: {
    term: "Categorías",
    aka: ["categorías", "conceptos puros del entendimiento"],
    kind: "concepto",
    when: "1781",
    body: "Los conceptos puros del entendimiento en la filosofía de Kant: los que no provienen de la experiencia sino que la hacen posible. Kant deriva doce, ordenadas en cuatro grupos —cantidad, cualidad, relación y modalidad—, entre las que está la de causa y efecto. Su función se entiende desde la fórmula kantiana de que «los pensamientos sin contenido son vacíos, las intuiciones sin conceptos son ciegas»: la sensibilidad recibe lo dado y el entendimiento lo unifica bajo conceptos, y ninguna de las dos produce conocimiento por separado. Las categorías son también la respuesta a Hume. Hume tenía razón en que la conexión necesaria no se encuentra entre las impresiones, pero se equivocaba al concluir que fuera un mero hábito: no está en la experiencia porque pertenece a su forma, es una de las condiciones sin las cuales no habría experiencia objetiva de un mundo en absoluto.",
  },
  "causas-eficientes": {
    term: "Causas eficientes",
    aka: ["causas eficientes"],
    kind: "concepto",
    when: "siglo XVII",
    body: "En la física mecanicista moderna, las únicas causas admitidas para explicar los fenómenos naturales: siempre anteriores en el tiempo a sus efectos, explican por qué ocurre algo pero no para qué. Se oponen a las causas finales o teleológicas, propias de la física antigua.",
  },
  "circulo-cartesiano": {
    term: "Círculo cartesiano",
    aka: ["círculo cartesiano"],
    kind: "concepto",
    when: "1641",
    body: "Objeción de método señalada a la argumentación de Descartes en las Meditaciones: para demostrar que Dios existe y no engaña, Descartes se apoya en la claridad y distinción de sus ideas, pero necesita a su vez la garantía divina para confiar en que lo claro y distinto es verdadero. La prueba parecería presuponer, así, lo que debía demostrar.",
  },
  cogito: {
    term: "Cogito",
    aka: ["cogito", "yo soy yo existo", "pienso luego existo"],
    kind: "concepto",
    when: "1641",
    body: "Certeza cartesiana de la propia existencia como sujeto pensante, alcanzada al final de la duda metódica: aunque un genio maligno me engañe en todo lo demás, no puede hacer que yo no sea nada mientras piense ser alguna cosa. Es, para Descartes, el primer principio indudable sobre el que se funda el resto del conocimiento humano.",
  },
  conatus: {
    term: "Conatus",
    aka: ["conatus"],
    kind: "concepto",
    when: "siglo XVII",
    body: "En la filosofía de Spinoza, el esfuerzo por el cual cada cosa persevera en su propio ser mientras está en su poder. Es la esencia actual de cada modo particular; en los seres humanos se manifiesta como deseo o apetito, y de él derivan todos los afectos analizados en la *Ética*.",
  },
  "conexion-necesaria": {
    term: "Conexión necesaria",
    aka: ["conexión necesaria"],
    kind: "concepto",
    when: "1739",
    body: "Idea de un vínculo objetivo y necesario entre causa y efecto, tal que ocurrida la causa es imposible que no ocurra el efecto. Hume muestra que no deriva de ninguna impresión, externa ni interna, sino de un hábito psicológico proyectado sobre la sucesión de fenómenos.",
  },
  "contrato-social": {
    term: "Contrato social",
    aka: ["contrato social", "pacto social"],
    kind: "concepto",
    when: "siglo XVII–XVIII",
    body: "Procedimiento hipotético mediante el cual los individuos, saliendo del estado de naturaleza, acuerdan constituir un poder político común. Es el argumento compartido por Hobbes, Locke y Rousseau para fundar racionalmente la legitimidad y los límites del poder, aunque cada uno lo pone al servicio de un diagnóstico distinto del problema que el pacto debe resolver.",
  },
  "critica-de-la-superstición": {
    term: "crítica de la superstición",
    aka: ["crítica de la superstición", "superstición"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Denuncia ilustrada de las creencias sostenidas por miedo, costumbre o manipulación clerical y no por evidencia racional. Los ilustrados la consideran un instrumento de poder que mantiene a la gente sujeta a autoridades que no rinden cuentas ante la razón, y la combaten tanto en su versión religiosa como en prácticas concretas, como los procesos por brujería.",
  },
  "cualidades-primarias-secundarias": {
    term: "Cualidades primarias y secundarias",
    aka: ["Cualidades primarias y secundarias", "cualidades primarias", "cualidades secundarias"],
    kind: "concepto",
    when: "1690",
    body: "Distinción de Locke: las cualidades primarias —extensión, figura, movimiento, número— pertenecen objetivamente a los cuerpos; las secundarias —color, sonido, sabor, olor— no existen en los objetos tal como las percibimos, sino que son el efecto que ciertas propiedades objetivas producen en nuestros sentidos.",
  },
  deismo: {
    term: "deísmo",
    aka: ["deísmo", "deísta", "deístas"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Postura religiosa según la cual la existencia de Dios y los principios básicos de la moral pueden conocerse por la sola razón natural, sin revelación, milagros ni dogmas de una Iglesia particular. Dios queda como autor racional del orden natural. Fue central en la Ilustración inglesa (Toland, Shaftesbury) y en Voltaire, aunque este último siempre distinguió su deísmo del ateísmo del materialismo francés.",
  },
  "derecho-natural": {
    term: "Derecho natural",
    aka: ["derecho natural"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Conjunto de reglas de conducta que, según la tradición moderna inaugurada por Grocio, pueden derivarse racionalmente de la naturaleza humana, con independencia de la voluntad de los soberanos o de la autoridad religiosa. Sirve de fundamento a los sistemas contractualistas modernos, que derivan de él tanto el estado de naturaleza como los derechos y límites del poder político.",
  },
  "despotismo-ilustrado": {
    term: "despotismo ilustrado",
    aka: ["despotismo ilustrado"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Forma de gobierno en la que un monarca absoluto aplica reformas asociadas a la Ilustración —tolerancia, codificación legal, fomento cultural y científico— sin ceder poder político ni tocar el orden social vigente. Federico II de Prusia es su ejemplo de referencia.",
  },
  determinismo: {
    term: "Determinismo",
    aka: ["determinismo"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Tesis según la cual todo lo que sucede está necesariamente determinado por causas anteriores, sin margen para el azar ni para una voluntad libre indeterminada. Spinoza lo formula de manera radical: todo se sigue de la naturaleza de la sustancia única con la misma necesidad que un teorema se sigue de sus axiomas.",
  },
  "dialectica-trascendental": {
    term: "Dialéctica trascendental",
    aka: ["dialéctica trascendental", "antinomias", "ideas de la razón"],
    kind: "concepto",
    when: "1781",
    body: "Parte de la Crítica de la razón pura donde Kant examina qué ocurre cuando la razón intenta conocer objetos que no pueden darse en ninguna experiencia posible: el alma, el mundo como totalidad y Dios. Sostiene que en cada caso no se trata de errores por descuido sino de ilusiones estructurales e inevitables. Sobre el alma, la razón concluye ilegítimamente que hay una substancia pensante simple e inmortal a partir de que todo pensamiento vaya acompañado de un «yo pienso», que es una forma y no un objeto dado. Sobre el mundo produce antinomias: pares de tesis opuestas, cada una con demostración aparentemente válida, lo que indica que la pregunta está mal planteada. Sobre Dios desmonta las pruebas de su existencia, y en particular la ontológica que Descartes había usado, con el argumento de que la existencia no es un predicado que se agregue al concepto de una cosa. El alma, el mundo y Dios sobreviven como ideas de la razón con un uso regulativo —orientan la investigación y sostienen la vida moral— y no constitutivo.",
  },
  "duda-metodica": {
    term: "Duda metódica",
    aka: ["duda metódica", "duda hiperbólica"],
    kind: "concepto",
    when: "1641",
    body: "Procedimiento cartesiano que consiste en considerar provisionalmente falsa toda opinión sobre la que pueda caber la más mínima duda, con el fin de hallar un primer principio absolutamente cierto sobre el cual fundar el resto del conocimiento. Se despliega en cuatro argumentos —el engaño de los sentidos, el sueño, el error de cálculo y la hipótesis del genio maligno— de creciente radicalidad, hasta volverse \"hiperbólica\".",
  },
  empirismo: {
    term: "Empirismo",
    aka: ["empirismo", "empirismo inglés"],
    kind: "concepto",
    when: "1620–1776",
    body: "Tradición filosófica según la cual todo conocimiento de la realidad deriva de la experiencia sensorial, y la razón sólo ordena y combina los materiales recibidos por los sentidos. Se opone al innatismo racionalista. Sus principales representantes son Bacon, Locke, Berkeley y Hume.",
  },
  enciclopedismo: {
    term: "enciclopedismo",
    aka: ["enciclopedismo"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Convicción, encarnada en el proyecto de la Enciclopedia, de que organizar y divulgar sistemáticamente el saber humano es en sí mismo un acto político y emancipador, porque saca el conocimiento de manos de las universidades y los círculos eclesiásticos y lo pone al alcance de cualquier lector.",
  },
  enlightenment: {
    term: "Enlightenment",
    aka: ["Enlightenment"],
    kind: "concepto",
    when: "1650–1730",
    body: "Nombre en inglés de la Ilustración, literalmente «acto de dar luz». Designa específicamente su variante inglesa, más temprana y menos combativa que la francesa o la alemana, apoyada en la revolución científica de Newton y en la filosofía política y del conocimiento de Locke, y desarrollada en un país que ya había resuelto sus conflictos políticos y religiosos mayores.",
  },
  "escepticismo-renacentista": {
    term: "Escepticismo renacentista",
    aka: ["escepticismo renacentista", "escepticismo", "pirronismo renacentista"],
    kind: "concepto",
    when: "siglo XVI",
    body: "Corriente filosófica del Renacimiento que retoma el escepticismo antiguo (académico y pirrónico) para cuestionar la posibilidad de un conocimiento cierto, tanto en materia religiosa como filosófica. Comparte con la Reforma y el humanismo el rechazo del aristotelismo escolástico, pero además desconfía de las disputas dogmáticas entre católicos y protestantes. Su principal figura es Michel de Montaigne.",
  },
  "espiritu-de-sutileza": {
    term: "Espíritu de sutileza",
    aka: ["espíritu de sutileza"],
    kind: "concepto",
    when: "siglo XVII",
    body: "En Pascal, modo de comprensión distinto del geométrico, no reductible al cálculo ni a la demostración: capta de un solo golpe realidades complejas y matices —el sentido de la vida, los afectos, la fe— que el razonamiento matemático no puede aprehender por partes.",
  },
  "espiritu-geometrico": {
    term: "Espíritu geométrico",
    aka: ["espíritu geométrico"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Para Pascal, el modo de conocimiento propio de la matemática y la física modernas: procede por definiciones, axiomas y demostraciones rigurosas sobre relaciones cuantitativas necesarias. Pascal lo considera insuficiente para comprender el sentido de la existencia individual, que requiere del espíritu de sutileza.",
  },
  "esse-est-percipi": {
    term: "Esse est percipi",
    aka: ["esse est percipi", "ser es ser percibido"],
    kind: "concepto",
    when: "1710",
    body: "Principio central de la filosofía de Berkeley: para los objetos que no piensan, existir no significa nada más que ser percibidos por una mente. Las cosas no dejan de existir cuando nadie las percibe porque son percibidas permanentemente por la mente infinita de Dios.",
  },
  "estado-de-naturaleza": {
    term: "Estado de naturaleza",
    aka: ["estado de naturaleza"],
    kind: "concepto",
    when: "siglo XVII–XVIII",
    body: "Situación hipotética de los seres humanos antes de constituir una sociedad política, empleada por los teóricos modernos del contrato para fundar racionalmente el poder y los derechos. Cada autor le da un contenido distinto: guerra de todos contra todos en Hobbes, libertad regida por la ley natural en Locke, aislamiento pacífico anterior a la propiedad en Rousseau.",
  },
  fanatismo: {
    term: "fanatismo",
    aka: ["fanatismo"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Blanco central de la crítica religiosa de Voltaire: la adhesión ciega e intolerante a una doctrina, dispuesta a justificar la persecución o la violencia contra quien no la comparte. Su lema «aplastad a la infame» apunta a la superstición organizada institucionalmente que lo alimenta, no a la fe personal de cada individuo.",
  },
  "fenomeno-noumeno": {
    term: "Fenómeno y cosa en sí",
    aka: ["Fenómeno y cosa en sí", "fenómeno", "fenómenos", "cosa en sí", "noumenon", "noúmeno"],
    kind: "concepto",
    when: "1781",
    body: "La distinción con la que Kant paga el precio del giro copernicano. Si los objetos que conocemos están estructurados por nuestras formas de sensibilidad y entendimiento, entonces no conocemos las cosas tal como son con independencia de nosotros: conocemos fenómenos, las cosas tal como se nos aparecen bajo esas condiciones. Lo que las cosas sean al margen de ellas es la cosa en sí o noumenon, que no es un objeto escondido detrás del fenómeno sino un concepto límite que marca hasta dónde llega nuestra facultad de conocer. La tesis no es escéptica: el conocimiento de fenómenos es estricto, objetivo y necesario. Tampoco es el idealismo subjetivo de Berkeley: los fenómenos no son ideas en una mente particular, son objetos reales para todo sujeto con nuestra constitución. El resultado se resume diciendo que el conocimiento es objetivo pero limitado a la experiencia posible.",
  },
  "formas-sensibilidad": {
    term: "Espacio y tiempo como formas de la sensibilidad",
    aka: ["Espacio y tiempo como formas de la sensibilidad", "formas puras de la intuición", "formas de la sensibilidad"],
    kind: "concepto",
    when: "1781",
    body: "Tesis de la Estética trascendental de Kant. El espacio y el tiempo no son cosas, ni propiedades de las cosas, ni relaciones abstraídas de la experiencia: son las formas puras con que toda intuición sensible se organiza. El argumento es que no pudimos haberlos aprendido de la experiencia, porque cualquier experiencia de algo exterior lo presenta ya localizado; podemos imaginar un espacio vacío, pero no la ausencia de espacio. De ahí se sigue que la geometría sea sintética a priori: sus proposiciones valen necesariamente para todo objeto posible de la experiencia externa porque describen la forma que ese objeto tendrá inevitablemente al presentarse. La tesis resuelve además la disputa entre Newton, que trataba el espacio como algo absoluto y real, y Leibniz, que lo reducía a un sistema de relaciones: para Kant no es ninguna de las dos cosas, sino una forma del sujeto que por eso mismo vale objetivamente para los fenómenos.",
  },
  "genio-maligno": {
    term: "Genio maligno",
    aka: ["genio maligno", "hipótesis del genio maligno"],
    kind: "concepto",
    when: "1641",
    body: "Hipótesis cartesiana, formulada en la Primera Meditación, de un ser muy poderoso y engañador que emplearía todo su poder en hacer errar al sujeto sin que este se dé cuenta, incluso respecto de verdades matemáticas evidentes. Es el argumento más radical de la duda metódica y el que exige, para ser refutado, demostrar la existencia de un Dios que no engaña.",
  },
  "giro-copernicano": {
    term: "Giro copernicano",
    aka: ["giro copernicano", "revolución copernicana"],
    kind: "concepto",
    when: "1781",
    body: "Nombre que Kant le da a la inversión de supuestos sobre la que descansa la Crítica de la razón pura, por analogía con Copérnico. Así como la astronomía avanzó cuando dejó de suponer que los astros giran alrededor del observador y supuso que el observador se mueve, la filosofía avanza cuando deja de suponer que el conocimiento debe ajustarse al objeto y supone lo contrario: que el objeto, en cuanto objeto de experiencia, se ajusta a las condiciones del sujeto que lo conoce. La inversión explica cómo es posible el conocimiento a priori: podemos saber algo de todo objeto posible antes de encontrarlo porque eso que sabemos no lo extrajimos del objeto, lo pusimos nosotros como condición para que algo pueda presentarse como objeto. El sujeto no aporta el contenido de la experiencia, que sigue viniendo de afuera, sino su forma.",
  },
  habito: {
    term: "Hábito",
    aka: ["hábito", "costumbre"],
    kind: "concepto",
    when: "1739",
    body: "En Hume, disposición psicológica que se forma al observar repetidamente que un tipo de hecho sucede a otro, y que nos hace esperar el segundo cuando el primero vuelve a ocurrir. Es, para Hume, el verdadero origen de la idea de conexión necesaria y de toda inferencia causal.",
  },
  humanismo: {
    term: "Humanismo renacentista",
    aka: ["humanismo", "humanismo renacentista", "humanismo italiano"],
    kind: "concepto",
    when: "siglos XIV–XVI",
    body: "Movimiento cultural nacido en Italia que afirma la autonomía de la cultura y la dignidad del ser humano frente a la subordinación medieval de toda actividad a fines religiosos administrados por la Iglesia. Rehabilita la Antigüedad grecorromana como modelo a imitar, impulsa el estudio filológico de manuscritos clásicos en academias distintas de las universidades y prepara, junto a la Reforma y el escepticismo, el terreno cultural de la filosofía moderna.",
  },
  "ideas-innatas": {
    term: "Ideas innatas",
    aka: ["ideas innatas"],
    kind: "concepto",
    when: "siglo XVII",
    body: "En el racionalismo cartesiano, ideas que la razón encuentra en sí misma sin haberlas tomado de la experiencia sensible, como la idea de Dios o los axiomas matemáticos. Descartes las opone a las ideas adventicias, recibidas del exterior, y a las facticias, construidas por la imaginación. Son el punto de apoyo racionalista frente a las críticas empiristas posteriores.",
  },
  "ideas-simples-complejas": {
    term: "Ideas simples y complejas",
    aka: ["Ideas simples y complejas", "ideas simples", "ideas complejas"],
    kind: "concepto",
    when: "1690",
    body: "En Locke, las ideas simples llegan directamente por un sentido o por reflexión y la mente no puede fabricarlas ni destruirlas; las ideas complejas resultan de que el entendimiento combina, compara o abstrae a partir de ideas simples ya recibidas, incluidas las ideas generales o abstractas.",
  },
  idolos: {
    term: "Ídolos",
    aka: ["ídolos"],
    kind: "concepto",
    when: "1620",
    body: "En la filosofía de Bacon, prejuicios que fascinan y engañan a la mente humana e impiden el conocimiento verdadero de la naturaleza: los que provienen de la idiosincrasia de cada individuo, los del lenguaje y la cultura compartida, y los de los sistemas filosóficos tradicionales.",
  },
  ilustracion: {
    term: "Ilustración",
    aka: ["Ilustración", "ilustrado", "ilustrados"],
    kind: "concepto",
    when: "1650–1800",
    body: "Movimiento intelectual europeo, de finales del siglo XVII a finales del XVIII, que sostiene que la razón humana, ejercida con método y sin sujeción a la autoridad heredada, puede examinar críticamente la naturaleza, la religión y la sociedad. No es una escuela única sino una actitud compartida, con variantes nacionales: la inglesa, la francesa (Lumières) y la alemana (Aufklärung).",
  },
  "ilustracion-y-cultura": {
    term: "ilustración y cultura",
    aka: ["ilustración y cultura", "¿qué significa ilustrar?"],
    kind: "concepto",
    when: "1784",
    body: "Distinción de Mendelssohn, en «Sobre la pregunta: ¿qué significa ilustrar?» (1784), entre cultura —el refinamiento práctico y social de una comunidad— e ilustración —el saber teórico que permite juzgar racionalmente el valor de las cosas—. Un pueblo puede tener mucha cultura y poca ilustración, o a la inversa; el ideal es que ambas avancen en equilibrio.",
  },
  "impresiones-ideas": {
    term: "Impresiones e ideas",
    aka: ["Impresiones e ideas", "impresiones", "ideas humeanas"],
    kind: "concepto",
    when: "1739",
    body: "Distinción de Hume entre dos tipos de percepciones: las impresiones, recibidas de modo directo mediante los sentidos (sensación) o la propia interioridad (reflexión), y las ideas, copias más débiles de las impresiones que la memoria y la fantasía combinan y recuerdan después.",
  },
  "individualismo-posesivo": {
    term: "Individualismo posesivo",
    aka: ["individualismo posesivo"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Categoría acuñada por C. B. Macpherson para describir el supuesto compartido por Hobbes y Locke: cada persona es propietaria de su propia persona y de sus capacidades, sin deberle nada a la sociedad por ellas, y puede disponer libremente de sí misma para pactar con otros en pie de igualdad.",
  },
  individuo: {
    term: "Individuo",
    aka: ["individuo"],
    kind: "concepto",
    when: "siglo XVII",
    body: "En la filosofía política moderna, unidad última de análisis: una persona libre, igual a las demás e independiente de cualquier vínculo social previo, que decide voluntariamente asociarse con otras mediante un pacto. Se opone al modelo antiguo, para el cual la persona es ante todo miembro de una comunidad que la antecede.",
  },
  induccion: {
    term: "Inducción",
    aka: ["inducción", "método inductivo"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Procedimiento propuesto por Bacon para establecer proposiciones generales a partir de la acumulación de casos particulares comprobados empíricamente. Fue rechazado en su pretensión de necesidad lógica por Hume, aunque la confianza empirista en la experiencia como fuente de conocimiento se mantuvo.",
  },
  inmaterialismo: {
    term: "Inmaterialismo",
    aka: ["inmaterialismo"],
    kind: "concepto",
    when: "1710",
    body: "Tesis de Berkeley según la cual no existe una sustancia material distinta de las mentes y sus percepciones. No niega la existencia de las cosas sensibles, sino la de un sustrato material oculto detrás de ellas, del que nunca podemos tener ninguna experiencia directa.",
  },
  "lengua-razon": {
    term: "El lenguaje como condición de la razón",
    aka: ["el lenguaje como condición de la razón", "purismo de la razón", "purismo"],
    kind: "concepto",
    when: "1784",
    body: "Argumento central de Hamann contra Kant. No hay razón sin lenguaje: todo pensamiento se ejerce en palabras, y no en palabras cualesquiera sino en una lengua determinada que nadie inventa y que se aprende de otros antes de poder examinar nada. El lenguaje no es puro en ninguno de los sentidos que Kant necesita, porque es sensible —las palabras son sonidos y signos materiales—, histórico y recibido. De ahí se sigue que la razón que Kant somete a crítica no sea una facultad pura que después se expresa en palabras: está hecha de palabras desde el principio. Hamann agrega un contraejemplo a la arquitectura kantiana: la palabra es simultáneamente sensible e intelectual, sonido que se oye y significado que se entiende, de modo que separar sensibilidad y entendimiento rompe algo que en la experiencia real está unido. Y sospecha del origen de las categorías, que Kant deriva de la tabla de los juicios de la lógica escolar, un producto histórico. De la tesis se sigue además que no haya un sujeto racional universal, sino hombres que piensan en lenguas concretas: la idea que Herder desarrolla y el romanticismo convierte en programa.",
  },
  "libertad-y-determinismo": {
    term: "Libertad y determinismo",
    aka: ["libertad y determinismo", "problema de la libertad"],
    kind: "concepto",
    when: "siglo XVII–XVIII",
    body: "Discusión sobre si la libertad humana es compatible con la determinación necesaria de las acciones por causas anteriores. Spinoza y Hume, aun negando el libre albedrío indeterminado, sostienen nociones de libertad compatibles con la necesidad: como actividad racional en Spinoza, como espontaneidad sin coacción en Hume.",
  },
  "libre-examen": {
    term: "Libre examen",
    aka: ["libre examen", "doctrina del libre examen"],
    kind: "concepto",
    when: "siglo XVI",
    body: "Doctrina luterana según la cual cada creyente, y no la jerarquía eclesiástica, tiene la facultad y el deber de interpretar por sí mismo las Escrituras, guiado por su propia conciencia. Se opone a la solución católica, que confiaba la interpretación correcta de la Biblia a la tradición, los concilios y el Papa. Se considera una raíz de la nueva función que la filosofía moderna le asigna a la conciencia individual como juez de la verdad.",
  },
  lumieres: {
    term: "Lumières",
    aka: ["Lumières", "Luces francesas"],
    kind: "concepto",
    when: "1734–1789",
    body: "Nombre francés de la Ilustración. Designa su variante más combativa y literaria, desarrollada bajo una monarquía absoluta con censura eclesiástica activa, y centrada en la crítica del fanatismo religioso, la difusión del saber mediante la Enciclopedia y la reforma política. Sus principales figuras son Voltaire, Montesquieu, Diderot y d'Alembert.",
  },
  "matematica-universal": {
    term: "Matemática universal",
    aka: ["matemática universal"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Proyecto racionalista de tratar la matemática como una ciencia general de relaciones y proporciones, haciendo abstracción de sus objetos particulares, capaz de unificar bajo un mismo método a todas las ciencias y a la filosofía misma.",
  },
  "matematizacion-de-la-naturaleza": {
    term: "Matematización de la naturaleza",
    aka: ["matematización de la naturaleza"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Proceso por el cual los físicos del siglo XVII aplican el método geométrico al estudio de la naturaleza, abandonando la física cualitativa aristotélica en favor de una descripción cuantitativa del movimiento de los cuerpos. Sus protagonistas —Galileo y Descartes, entre otros— se conciben a sí mismos como platónicos frente a los aristotélicos de las universidades, aunque interpretan de modos muy distintos qué significa aplicar la matemática a la física.",
  },
  "materialismo-frances": {
    term: "materialismo francés",
    aka: ["materialismo francés"],
    kind: "concepto",
    when: "1750–1789",
    body: "Corriente radical de la Ilustración francesa, surgida del círculo de colaboradores de la Enciclopedia, que sostiene que sólo existe la materia en movimiento, sin espíritu ni alma inmaterial, y explica el pensamiento como función del cerebro. Avanza más allá del deísmo hasta el ateísmo declarado, sobre todo en d'Holbach.",
  },
  mecanicismo: {
    term: "Mecanicismo",
    aka: ["mecanicismo", "filosofía mecanicista"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Concepción de la naturaleza como una gran maquinaria regida por leyes necesarias, sin fuerzas ni fines propios en los cuerpos, que sólo se mueven por choque con otros cuerpos. Predicado tanto de teorías físicas (Newton) como de filosofías de la naturaleza (Descartes, Hobbes, Gassendi, Boyle), con consecuencias distintas según el autor.",
  },
  "metodo-geometrico": {
    term: "Método geométrico",
    aka: ["método geométrico", "more geometrico"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Procedimiento de exposición filosófica que imita la estructura de un tratado de geometría: parte de definiciones y axiomas y demuestra proposiciones a partir de ellos. Spinoza lo aplica a la ética humana, convencido de que la realidad misma se comporta con la necesidad de una demostración matemática.",
  },
  "minoria-de-edad": {
    term: "Minoría de edad",
    aka: ["minoría de edad", "minoría de edad autoculpable", "Unmündigkeit"],
    kind: "concepto",
    when: "1784",
    body: "Concepto con el que Kant define la Ilustración por su contrario. La palabra alemana Unmündigkeit designaba la condición jurídica del menor, que no puede disponer de sus bienes ni comparecer en juicio sin un tutor; Kant traslada esa figura legal al pensamiento. La minoría de edad intelectual consiste en no poder servirse del propio entendimiento sin la dirección de otro, y es autoculpable —selbstverschuldet— porque su causa no es la falta de entendimiento sino la falta de resolución y de valor. Kant nombra dos vicios que la sostienen, la pereza y la cobardía, y observa que también es cómoda: si otro piensa por mí no tengo que esforzarme, y si me equivoco siguiéndolo la responsabilidad no es mía. Los tutores, por su parte, tienen interés en perpetuarla: primero atrofian la capacidad de andar solos y después señalan el peligro de intentarlo. Kant usa la imagen de las andaderas para los prejuicios.",
  },
  monada: {
    term: "Mónada",
    aka: ["mónada", "mónadas"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "En la metafísica de Leibniz, sustancia simple, sin partes ni extensión, que constituye el elemento último de toda la realidad. Cada mónada representa el universo entero desde su propio punto de vista, con mayor o menor claridad, y no interactúa causalmente con las demás: «no tiene ventanas».",
  },
  ocasionalismo: {
    term: "Ocasionalismo",
    aka: ["ocasionalismo", "doctrina ocasionalista"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Doctrina, criticada por Hume, que atribuye a la voluntad divina el verdadero e inmediato principio de todo efecto, incluida la relación entre la voluntad humana y el movimiento del cuerpo. Para Hume traslada el problema de la conexión necesaria a Dios sin resolverlo.",
  },
  "parabola-de-los-anillos": {
    term: "parábola de los anillos",
    aka: ["parábola de los anillos"],
    kind: "concepto",
    when: "1779",
    body: "Relato central de Natán el sabio: un padre lega a sus tres hijos anillos idénticos, y ninguno puede probar que el suyo es el original. No afirma que las tres religiones representadas —judía, cristiana, musulmana— sean falsas por igual, sino que ninguna puede demostrar racionalmente su superioridad exclusiva; cada hijo debe demostrar con hechos la virtud de su fe.",
  },
  pietismo: {
    term: "pietismo",
    aka: ["pietismo", "pietista", "pietistas"],
    kind: "concepto",
    when: "siglo XVII–XVIII",
    body: "Movimiento religioso protestante que domina buena parte de la vida espiritual alemana del período. Enfatiza la experiencia personal de la fe, la conversión interior y la práctica moral cotidiana por encima de la doctrina teológica formal. Es el principal adversario religioso de la Aufklärung, aunque también entrena, sin proponérselo, el hábito de introspección crítica que muchos ilustrados alemanes trasladan a la filosofía.",
  },
  "platonismo-matematico": {
    term: "Platonismo matemático",
    aka: ["platonismo matemático"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Lectura filosófica de la revolución científica del siglo XVII, según la cual sus protagonistas conciben la matemática como el conocimiento por excelencia y el modelo de todo saber racional, en la línea de la tradición platónica antigua. Se distingue del racionalismo cartesiano en que no siempre exige, como Descartes, una fundamentación metafísica última: para Galileo, por ejemplo, basta con postular que la naturaleza tiene estructura matemática.",
  },
  "principio-de-razon-suficiente": {
    term: "Principio de razón suficiente",
    aka: ["principio de razón suficiente"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Principio formulado por Leibniz según el cual nada ocurre sin que haya una razón suficiente para que sea así y no de otro modo. Rige las verdades de hecho, contingentes, a diferencia del principio de no contradicción, que rige las verdades de razón, necesarias.",
  },
  "problema-de-la-induccion": {
    term: "Problema de la inducción",
    aka: ["problema de la inducción"],
    kind: "concepto",
    when: "1739",
    body: "Dificultad planteada por Hume: ninguna cantidad de casos pasados observados puede demostrar lógicamente que el futuro se comportará igual que el pasado. La inferencia inductiva se apoya en el hábito, no en un argumento racional concluyente.",
  },
  racionalismo: {
    term: "Racionalismo",
    aka: ["racionalismo", "racionalismo continental"],
    kind: "concepto",
    when: "1637–1780",
    body: "Tradición filosófica que sostiene que la razón, por sí sola, puede conocer la realidad tal cual es, porque ésta se encuentra racionalmente estructurada. Desconfía del conocimiento sensorial y defiende la existencia de ideas innatas. Sus principales representantes son Descartes, Spinoza y Leibniz.",
  },
  "religion-natural": {
    term: "Religión natural",
    aka: ["religión natural"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Idea de una religión derivada de la razón humana, independiente de los dogmas particulares de las religiones históricas o positivas, y reducida al núcleo que estas comparten: la existencia de un Dios providencial, un deber moral y la inmortalidad del alma. Elaborada por autores como Herbert de Cherbury, alimenta la metafísica racionalista del siglo XVII y, más tarde, los postulados de la razón práctica en Kant.",
  },
  "res-cogitans-y-res-extensa": {
    term: "Res cogitans y res extensa",
    aka: ["Res cogitans y res extensa", "res cogitans", "res extensa", "sustancia pensante", "sustancia extensa"],
    kind: "concepto",
    when: "1641",
    body: "Distinción cartesiana entre dos tipos de sustancia: la res cogitans, sustancia pensante cuya existencia se descubre en el cogito, y la res extensa, sustancia extensa que compone el mundo material y cuya existencia solo queda garantizada, en la Sexta Meditación, gracias a la veracidad divina. Es el fundamento del dualismo cartesiano entre mente y cuerpo.",
  },
  "sacerdocio-universal": {
    term: "Sacerdocio universal",
    aka: ["sacerdocio universal", "doctrina del sacerdocio universal"],
    kind: "concepto",
    when: "siglo XVI",
    body: "Doctrina luterana que niega que el sacerdocio sea una profesión reservada a un estamento eclesiástico particular y sostiene que todo cristiano tiene una relación directa con Dios, sin necesidad de intermediarios. Es la contrapartida institucional del libre examen: donde este traslada la interpretación de la Escritura a la conciencia individual, el sacerdocio universal traslada a cada creyente la función antes reservada al clero.",
  },
  "sapere-aude": {
    term: "Sapere aude",
    aka: ["sapere aude"],
    kind: "concepto",
    when: "1784",
    body: "Expresión latina tomada de una epístola de Horacio que Kant convierte en el lema de la Ilustración en su artículo de 1784. Se traduce como «atrévete a saber» o, en la versión que Kant explicita, «ten el valor de servirte de tu propio entendimiento». Lo importante es que es un imperativo y no una descripción: la Ilustración no es un estado en el que uno se encuentre sino un acto que hay que realizar, y que exige coraje más que talento. De ahí que alguien pueda repetir las tesis más avanzadas de su siglo y seguir siendo menor de edad, si las sostiene porque se las enseñaron y no porque las examinó: lo que define la Ilustración no es cuánto se sabe sino quién realiza la operación de pensar.",
  },
  "separacion-de-poderes": {
    term: "separación de poderes",
    aka: ["separación de poderes"],
    kind: "concepto",
    when: "1748",
    body: "Doctrina política formulada por Montesquieu según la cual el poder legislativo, el ejecutivo y el judicial deben estar en manos distintas, porque sólo el poder detiene al poder. Toma como modelo el gobierno mixto inglés e influye directamente en las constituciones liberales del siglo siguiente.",
  },
  "sintetico-a-priori": {
    term: "Juicio sintético a priori",
    aka: ["juicios sintéticos a priori", "juicio sintético a priori", "sintético a priori"],
    kind: "concepto",
    when: "1781",
    body: "Tipo de juicio cuya posibilidad es el problema central de la Crítica de la razón pura. Un juicio es analítico cuando el predicado ya está contenido en el sujeto («todo cuerpo es extenso») y sintético cuando agrega información nueva. Es a priori cuando vale con independencia de la experiencia, y por eso es universal y necesario, y a posteriori cuando depende de ella. La combinación problemática es la de sintético y a priori: un juicio que agrega información y sin embargo no admite excepciones. Kant sostiene que existen y que son la base de la matemática («7 + 5 = 12» no se sigue del análisis de sus conceptos) y de la física («todo cambio tiene una causa» no es una generalización empírica, sino un principio que la investigación presupone). Explicar cómo son posibles equivale a explicar cómo es posible la ciencia.",
  },
  soberania: {
    term: "Soberanía (Rousseau)",
    aka: ["Soberanía (Rousseau)", "soberanía"],
    kind: "concepto",
    when: "1762",
    body: "En Rousseau, el poder de dictar la voluntad general, que reside siempre en el pueblo reunido y que, a diferencia de lo que sostienen Hobbes y Locke, no puede transferirse ni representarse: solo puede ejercerse directamente, porque es inalienable e indivisible. Esta concepción de la soberanía popular distingue a Rousseau de los demás teóricos modernos del contrato.",
  },
  "sustancia-unica": {
    term: "Sustancia única",
    aka: ["sustancia única", "Deus sive natura", "Dios o la naturaleza"],
    kind: "concepto",
    when: "siglo XVII",
    body: "Tesis central de la metafísica de Spinoza: existe una sola sustancia infinita, causa de sí misma, a la que llama indistintamente «Dios» o «la naturaleza» (Deus sive natura). Todo lo que existe es un modo de esa sustancia única, expresada en infinitos atributos, de los cuales conocemos sólo la extensión y el pensamiento.",
  },
  "tabla-rasa": {
    term: "Tabla rasa",
    aka: ["tabla rasa", "papel en blanco"],
    kind: "concepto",
    when: "1690",
    body: "Imagen empirista, defendida por Locke, según la cual la mente humana, antes de cualquier experiencia, es semejante a un papel en blanco sobre el que los datos sensoriales van «imprimiéndose». Se opone directamente a la tesis racionalista de las ideas innatas.",
  },
  teleologia: {
    term: "Teleología",
    aka: ["teleología", "finalismo"],
    kind: "concepto",
    when: "antigüedad–siglo XVIII",
    body: "Explicación de los fenómenos por su fin o propósito, y no sólo por sus causas anteriores. La física mecanicista del siglo XVII la rechaza para el estudio de la naturaleza; Spinoza la elimina también de la metafísica, mientras que Leibniz la conserva para el estudio de las sustancias simples o mónadas.",
  },
  teodicea: {
    term: "Teodicea",
    aka: ["teodicea"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Intento de conciliar la existencia de un Dios todopoderoso y bueno con la presencia del mal en el mundo. Leibniz sostiene, en su teodicea, que Dios elige crear, entre infinitos mundos posibles, aquel con la mejor proporción entre bien y mal: «el mejor de los mundos posibles».",
  },
  tolerancia: {
    term: "tolerancia",
    aka: ["tolerancia", "tolerancia religiosa", "tolerancia civil"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Principio, central en la Ilustración inglesa y retomado por toda la Ilustración europea, según el cual ninguna Iglesia o credo tiene autoridad racional para imponerse por la fuerza sobre los demás. Locke lo formula en la Carta sobre la tolerancia (1689): el Estado debe ocuparse de los bienes civiles y dejar la salvación de cada uno a su propia conciencia.",
  },
  "uso-publico-razon": {
    term: "Uso público y uso privado de la razón",
    aka: ["Uso público y uso privado de la razón", "uso público de la razón", "uso privado de la razón", "uso público", "uso privado"],
    kind: "concepto",
    when: "1784",
    body: "Distinción de Kant en su artículo de 1784, fácil de malentender porque usa «público» y «privado» al revés de como se usan hoy. El uso público es el que alguien hace en cuanto sabio que se dirige al conjunto de los lectores, y debe ser enteramente libre; lo público no es el lugar donde se habla sino la audiencia universal a la que se habla. El uso privado es el que alguien hace en el ejercicio del cargo o la función que le fue confiada, actuando como pieza de una maquinaria y en nombre de otro, y puede legítimamente restringirse. Kant lo ilustra con el oficial, que obedece en formación y publica críticas como estudioso; con el contribuyente, que paga el impuesto y escribe contra él; y sobre todo con el clérigo, que enseña conforme al credo de su iglesia y como sabio comunica sus objeciones. La fórmula que lo resume, atribuida a Federico II, es «razonad todo lo que queráis, pero obedeced». El argumento de fondo es que la crítica sólo funciona si es pública: un funcionario que desobedece produce desorden, un autor que argumenta puede cambiar la ley.",
  },
  "veracidad-divina": {
    term: "Veracidad divina",
    aka: ["veracidad divina"],
    kind: "concepto",
    when: "1641",
    body: "Tesis cartesiana según la cual Dios, por ser infinitamente perfecto, no puede ser engañador. Una vez demostrada la existencia de Dios, su veracidad garantiza que las ideas percibidas con claridad y distinción por la razón humana son verdaderas, y permite así superar la duda metódica y fundar el conocimiento racional, incluida la física matemática.",
  },
  "verdades-de-razon-e-historicas": {
    term: "verdades históricas y verdades de razón",
    aka: ["verdades históricas y verdades de razón", "verdades históricas", "verdades accidentales de la historia"],
    kind: "concepto",
    when: "1777–1780",
    body: "Distinción de Lessing entre las verdades necesarias (como los teoremas de la geometría), demostrables por sí mismas, y las verdades contingentes (como los hechos históricos), accesibles sólo por testimonio y nunca con certeza absoluta. Para Lessing, ningún testimonio histórico —ni siquiera el de un milagro presenciado directamente— puede fundar una verdad necesaria: es «el ancho foso feo» que ninguna inferencia lógica logra cruzar.",
  },
  "verdades-de-razon-y-de-hecho": {
    term: "Verdades de razón y verdades de hecho",
    aka: ["Verdades de razón y verdades de hecho", "verdades de razón", "verdades de hecho"],
    kind: "concepto",
    when: "siglo XVIII",
    body: "Distinción de Leibniz entre dos tipos de verdad: las de razón son necesarias, su opuesto es contradictorio, y se conocen por análisis lógico, como las matemáticas; las de hecho son contingentes, su opuesto es posible, y dependen de la elección divina entre mundos posibles.",
  },
  "voluntad-general": {
    term: "Voluntad general",
    aka: ["voluntad general"],
    kind: "concepto",
    when: "1762",
    body: "En la teoría política de Rousseau, la voluntad que apunta al bien común del cuerpo político, distinta de la mera suma de voluntades particulares o \"voluntad de todos\". Obliga a todos los miembros del cuerpo político, incluidos quienes votaron en contra, porque desobedecerla es, para Rousseau, equivocarse sobre el propio interés como ciudadano. Su cumplimiento define la libertad civil.",
  },
  // ---------- obraes ----------
  "articulo-filosofo": {
    term: "artículo «Filósofo»",
    aka: ["artículo «Filósofo»", "artículo Filósofo", "«Filósofo»"],
    kind: "obra",
    when: "1765",
    body: "Artículo de la Enciclopedia escrito por Diderot a partir de un texto anterior de César Chesneau Dumarsais. Define al filósofo ilustrado como quien actúa guiado por la razón y por la experiencia, y no por la pasión, la costumbre o la autoridad ciega: un ciudadano razonable que busca el bien común dentro de la sociedad en la que vive, no un asceta apartado del mundo.",
  },
  "berlinische-monatsschrift": {
    term: "Berlinische Monatsschrift",
    aka: ["Berlinische Monatsschrift", "Revista mensual berlinesa"],
    kind: "obra",
    when: "1783–1796",
    body: "Revista mensual berlinesa, nacida de la Sociedad del Miércoles, un club privado de funcionarios, profesores y clérigos que discutía en confianza cuestiones religiosas y políticas delicadas. Se convierte en el órgano central de la Ilustración berlinesa y en el lugar donde Zöllner plantea, en 1783, la pregunta por la Ilustración.",
  },
  candido: {
    term: "Cándido",
    aka: ["Cándido", "Cándido o el optimismo"],
    kind: "obra",
    when: "1759",
    body: "Novela filosófica de Voltaire, escrita poco después del terremoto de Lisboa de 1755. Sigue las desventuras de su protagonista para mostrar lo absurdo del optimismo metafísico leibniziano —la tesis de que «todo está bien en el mejor de los mundos posibles»— frente a catástrofes reales: terremotos, guerras, esclavitud.",
  },
  "cartas-filosoficas": {
    term: "Cartas filosóficas",
    aka: ["Cartas filosóficas", "Cartas inglesas"],
    kind: "obra",
    when: "1734",
    body: "Obra de Voltaire, también conocida como Cartas inglesas: veinticinco cartas que presentan al público francés la ciencia de Newton, la filosofía de Locke, la tolerancia religiosa inglesa y el sistema político británico, en implícito contraste con el absolutismo francés. Prohibida y quemada apenas se publica.",
  },
  "critica-razon-pura": {
    term: "Crítica de la razón pura",
    aka: ["Crítica de la razón pura"],
    kind: "obra",
    when: "1781",
    body: "Obra principal de Kant, publicada en 1781 y reescrita en una segunda edición en 1787. Su pregunta es cómo son posibles los juicios sintéticos a priori, es decir, los juicios que agregan información nueva sobre el mundo y sin embargo valen necesariamente, sin depender de la experiencia. La matemática y la física están hechas de esos juicios, así que la pregunta es por el fundamento de la ciencia. La respuesta es el giro copernicano. El libro se divide en una Estética trascendental, que establece el espacio y el tiempo como formas puras de la sensibilidad; una Analítica trascendental, que establece las categorías del entendimiento y su aplicación legítima; y una Dialéctica trascendental, que muestra los errores inevitables en que cae la razón cuando pretende conocer más allá de la experiencia posible. Su resultado doble es que la ciencia natural queda fundada y la metafísica racionalista, desalojada. Kant lo resumió diciendo que tuvo que limitar el saber para dejar lugar a la fe.",
  },
  "derecho-de-la-guerra-y-de-la-paz": {
    term: "Sobre el derecho de la guerra y de la paz",
    aka: ["Sobre el derecho de la guerra y de la paz", "De iure belli ac pacis"],
    kind: "obra",
    when: "1625",
    body: "Tratado de Hugo Grocio que funda el derecho internacional moderno sobre bases racionales y seculares, en reemplazo del arbitraje que antes de la Reforma ejercía el Papa entre los príncipes cristianos. Formula un derecho natural válido para todo ser racional, con independencia de su nación o religión, y sienta el precedente metodológico de derivar reglas universales de la razón común a los seres humanos.",
  },
  "dialogo-sobre-los-dos-maximos-sistemas": {
    term: "Diálogo sobre los dos máximos sistemas del mundo",
    aka: ["Diálogo sobre los dos máximos sistemas del mundo", "el Diálogo de Galileo"],
    kind: "obra",
    when: "1632",
    body: "Obra de Galileo Galilei escrita en forma de diálogo entre tres personajes: Salviati, alter ego del propio Galileo, defiende la nueva física matemática; Sagredo es el interlocutor neutral y culto; Simplicio encarna al aristotélico que se niega a aplicar criterios matemáticos a los problemas físicos. Expone la defensa galileana del heliocentrismo copernicano y le vale a su autor el proceso de la Inquisición.",
  },
  "diccionario-filosofico": {
    term: "Diccionario filosófico",
    aka: ["Diccionario filosófico"],
    kind: "obra",
    when: "1764",
    body: "Obra de Voltaire organizada por entradas breves —«Dios», «tolerancia», «alma», «fanatismo»— que somete cada concepto de la tradición filosófica y religiosa a un examen irónico. Es el ejemplo más acabado del estilo voltaireano: exponer una posición con precisión hasta que su propio absurdo se revele por sí solo.",
  },
  "discurso-del-metodo": {
    term: "Discurso del método",
    aka: ["Discurso del método"],
    kind: "obra",
    when: "1637",
    body: "Obra de René Descartes en la que relata, en tono autobiográfico, su insatisfacción con la filosofía y las ciencias heredadas y expone las reglas de su nuevo método para alcanzar un conocimiento cierto. Incluye además las reglas de una \"moral provisional\" para orientar la vida práctica mientras dura la investigación filosófica, y la célebre afirmación de que \"el buen sentido es la cosa mejor repartida del mundo\".",
  },
  "discurso-sobre-la-desigualdad": {
    term: "Discurso sobre el origen de la desigualdad entre los hombres",
    aka: ["Discurso sobre el origen de la desigualdad entre los hombres", "Discurso sobre la desigualdad", "Discurso sobre el origen de la desigualdad"],
    kind: "obra",
    when: "1755",
    body: "Obra de Jean-Jacques Rousseau que narra, como hipótesis histórica y no como deducción racional, el paso de un estado de naturaleza pacífico y aislado a la sociedad civil desigual. Sitúa el origen de la desigualdad en el momento en que alguien cerca un terreno y logra que otros acepten su pretensión de propiedad, dando inicio a la comparación, la vanidad y la dominación entre los seres humanos.",
  },
  "dos-tratados": {
    term: "Dos tratados sobre el gobierno civil",
    aka: ["Dos tratados sobre el gobierno civil", "Dos tratados"],
    kind: "obra",
    when: "1689",
    body: "Obra política de John Locke, publicada en 1689. Sostiene que en el estado de naturaleza los individuos ya tienen derechos —a la vida, la libertad y la propiedad— que el pacto político no crea sino que busca proteger mejor, y que ningún gobierno legítimo puede violar.",
  },
  "educacion-del-genero-humano": {
    term: "La educación del género humano",
    aka: ["La educación del género humano"],
    kind: "obra",
    when: "1780",
    body: "Obra de Lessing, publicada de forma anónima. Sostiene que la revelación religiosa no comunica verdades inalcanzables para la razón, sino que las entrega a la humanidad en su infancia histórica de manera adaptada a su desarrollo, como un maestro que educa a un niño. El proceso continúa hacia una futura etapa en que la humanidad practique el bien por convicción racional propia.",
  },
  "el-contrato-social": {
    term: "El contrato social",
    aka: ["El contrato social"],
    kind: "obra",
    when: "1762",
    body: "Obra de Jean-Jacques Rousseau que expone su teoría del pacto político. Propone que cada asociado se entregue por entero a la comunidad, y no a un individuo particular, de modo que permanezca tan libre como antes bajo la forma de una libertad civil regida por la voluntad general. Sostiene que la soberanía, ejercida directamente por el pueblo, es inalienable e indivisible.",
  },
  enciclopedia: {
    term: "Enciclopedia",
    aka: ["Enciclopedia", "Diccionario razonado de las ciencias las artes y los oficios"],
    kind: "obra",
    when: "1751–1772",
    body: "Diccionario razonado de las ciencias, las artes y los oficios, dirigido por Diderot y d'Alembert, con la colaboración de más de ciento cincuenta philosophes, entre ellos Voltaire, Montesquieu y Rousseau. Reúne el saber disponible de la época y lo pone al alcance de un público amplio, deslizando bajo artículos técnicos críticas veladas a la religión y a la monarquía. Sufre censuras y condena papal, pero se completa en 1772.",
  },
  "ensayo-entendimiento-humano": {
    term: "Ensayo sobre el entendimiento humano",
    aka: ["Ensayo sobre el entendimiento humano"],
    kind: "obra",
    when: "1690",
    body: "Obra principal de John Locke, publicada en 1690. Refuta la tesis racionalista de las ideas innatas y sostiene que toda idea humana, simple o compleja, se origina en la experiencia sensorial o en la reflexión sobre las propias operaciones de la mente.",
  },
  ensayos: {
    term: "Ensayos (Montaigne)",
    aka: ["Ensayos (Montaigne)", "Ensayos", "los Ensayos de Montaigne"],
    kind: "obra",
    when: "1580",
    body: "Obra de Michel de Montaigne, publicada por primera vez en 1580 y ampliada hasta su muerte en 1592. Reúne reflexiones en primera persona sobre temas morales, políticos y filosóficos, escritas en un estilo digresivo y autobiográfico que inaugura el género del ensayo moderno. Incluye la \"Apología de Raimundo Sabunde\", crítica del antropocentrismo, y \"De los caníbales\", crítica del etnocentrismo europeo.",
  },
  "espiritu-de-las-leyes": {
    term: "El espíritu de las leyes",
    aka: ["El espíritu de las leyes"],
    kind: "obra",
    when: "1748",
    body: "Obra mayor de Montesquieu. Propone una ciencia comparada de la legislación basada en el examen empírico de leyes antiguas y modernas, y distingue tres formas de gobierno según el principio que las anima —la república por la virtud cívica, la monarquía por el honor, el despotismo por el miedo—, además de formular la separación de poderes.",
  },
  "etica-spinoza": {
    term: "Ética",
    aka: ["Ética", "Ética demostrada según el orden geométrico"],
    kind: "obra",
    when: "1677",
    body: "Obra principal de Spinoza, publicada póstumamente en 1677. Expone su metafísica, su teoría del conocimiento y su doctrina de los afectos con la estructura de un tratado de geometría: definiciones, axiomas y proposiciones demostradas, aplicadas al estudio de la conducta humana y la felicidad.",
  },
  fedon: {
    term: "Fedón",
    aka: ["Fedón", "Diálogos sobre la inmortalidad del alma"],
    kind: "obra",
    when: "1767",
    body: "Obra de Mendelssohn, titulada en homenaje al diálogo platónico, que defiende con argumentos racionales y un estilo accesible la inmortalidad del alma humana. Lo vuelve célebre en toda Alemania como el «Sócrates alemán».",
  },
  "investigacion-entendimiento-humano": {
    term: "Investigación sobre el entendimiento humano",
    aka: ["Investigación sobre el entendimiento humano", "la Investigación"],
    kind: "obra",
    when: "1748",
    body: "Obra de David Hume publicada en 1748, reformulación más accesible de los argumentos centrales del *Tratado de la naturaleza humana* (1739), entre ellos el análisis de la causalidad, la conexión necesaria y el problema de la inducción.",
  },
  leviatan: {
    term: "Leviatán",
    aka: ["Leviatán", "Leviathan"],
    kind: "obra",
    when: "1651",
    body: "Obra principal de Thomas Hobbes, publicada en 1651. Funda la legitimidad del Estado en un pacto entre individuos libres e iguales que, para escapar de la guerra de todos contra todos propia del estado de naturaleza, transfieren su derecho a un soberano con poder absoluto.",
  },
  "meditaciones-metafisicas": {
    term: "Meditaciones metafísicas",
    aka: ["Meditaciones metafísicas", "las Meditaciones"],
    kind: "obra",
    when: "1641",
    body: "Obra central de René Descartes, estructurada en seis meditaciones que recorren la duda metódica, el descubrimiento del cogito, la demostración de la existencia de Dios como garante de la veracidad del conocimiento racional, el origen del error y, finalmente, la demostración de la existencia del mundo material. Es la fuente principal de la metafísica racionalista del siglo XVII.",
  },
  metacritica: {
    term: "Metacrítica del purismo de la razón",
    aka: ["Metacrítica del purismo de la razón", "Metacrítica", "metacrítica"],
    kind: "obra",
    when: "1784",
    body: "Texto breve de Hamann escrito en 1784 y publicado recién en 1800, después de su muerte. Es la primera objeción de fondo a la Crítica de la razón pura de Kant. El título indica el método: Kant hizo una crítica, es decir, examinó la razón para establecer sus límites; Hamann propone examinar la facultad con la que Kant hizo ese examen, porque si la razón se juzga a sí misma queda abierta la pregunta de quién juzga al juez. El objeto de la denuncia es el «purismo», la pretensión de obtener una razón depurada de todo elemento ajeno. Hamann identifica tres purificaciones sucesivas: separar la razón de la tradición y la fe, separarla de la experiencia, y finalmente separarla del lenguaje. La tercera es imposible, porque todo pensamiento se ejerce en palabras y en una lengua determinada, con su historia y su gramática heredadas. La forma del argumento es la misma que Kant había usado contra la metafísica, aplicada un escalón más abajo.",
  },
  monadologia: {
    term: "Monadología",
    aka: ["Monadología", "La Monadología"],
    kind: "obra",
    when: "1714",
    body: "Breve tratado de metafísica de Leibniz, escrito en 1714, que expone de manera sistemática su doctrina de las mónadas como sustancias simples últimas de la realidad, la armonía preestablecida entre ellas y el principio de razón suficiente que rige el orden del universo.",
  },
  "natan-el-sabio": {
    term: "Natán el sabio",
    aka: ["Natán el sabio"],
    kind: "obra",
    when: "1779",
    body: "Drama de Lessing ambientado en la Jerusalén de las Cruzadas, donde conviven un mercader judío, un sultán musulmán y un caballero cristiano. Contiene la «parábola de los anillos», que sostiene que ninguna de las tres religiones puede demostrar racionalmente su superioridad exclusiva sobre las otras. El protagonista está inspirado en Mendelssohn.",
  },
  "novum-organum": {
    term: "Novum Organum",
    aka: ["Novum Organum"],
    kind: "obra",
    when: "1620",
    body: "Tratado metodológico de Francis Bacon, publicado en 1620, que critica los prejuicios o «ídolos» que impiden el conocimiento verdadero de la naturaleza y propone reemplazar la lógica deductiva de la escolástica por un método inductivo basado en la observación sistemática de los hechos.",
  },
  pensamientos: {
    term: "Pensamientos",
    aka: ["Pensamientos", "Pensées"],
    kind: "obra",
    when: "1670",
    body: "Obra póstuma e inconclusa de Blaise Pascal, publicada en 1670 a partir de fragmentos y notas destinadas a una apología de la religión cristiana. Contiene su distinción entre espíritu geométrico y espíritu de sutileza, y su descripción del ser humano perdido entre dos infinitos.",
  },
  principia: {
    term: "Principios matemáticos de la filosofía natural",
    aka: ["Principia", "Principios matemáticos de la filosofía natural", "Philosophiae Naturalis Principia Mathematica"],
    kind: "obra",
    when: "1687",
    body: "Obra de Isaac Newton que formula la ley de gravitación universal y las leyes del movimiento, unificando bajo un mismo sistema matemático la mecánica celeste y la mecánica terrestre. Culmina el programa de matematización de la naturaleza iniciado por Copérnico y desarrollado por Kepler y Galileo, y se convierte en el modelo de ciencia natural para buena parte de la filosofía posterior, incluido el criticismo de Kant.",
  },
  "principios-conocimiento-humano": {
    term: "Principios del conocimiento humano",
    aka: ["Principios del conocimiento humano", "Tratado sobre los principios del conocimiento humano"],
    kind: "obra",
    when: "1710",
    body: "Obra principal de George Berkeley, publicada en 1710. Argumenta que sólo existen mentes e ideas percibidas por ellas, y que la noción de una materia independiente de toda percepción es una abstracción vacía, sin respaldo en la experiencia que el empirismo reclama como fuente de todo conocimiento.",
  },
  "que-es-ilustracion-kant": {
    term: "Respuesta a la pregunta: ¿qué es la Ilustración?",
    aka: ["Respuesta a la pregunta: ¿qué es la Ilustración?", "Respuesta a la pregunta ¿qué es la Ilustración?"],
    kind: "obra",
    when: "1784",
    body: "Artículo breve de Kant publicado en la Berlinische Monatsschrift en diciembre de 1784, en respuesta a la pregunta que el teólogo Johann Friedrich Zöllner había formulado al pie de un artículo del año anterior. Es el texto más leído de Kant y la definición canónica de la época. Su tesis es que la Ilustración es la salida del hombre de su minoría de edad autoculpable, y que el obstáculo no es la falta de entendimiento sino la falta de decisión y valor para usarlo sin la dirección de otro. De ahí el lema tomado de Horacio: sapere aude. El texto sostiene además que para la Ilustración basta con la libertad de hacer uso público de la razón, distingue ese uso público del privado, y concluye que su época no es una época ilustrada sino una época de ilustración, es decir, un proceso en marcha y no un estado alcanzado.",
  },
  "sistema-de-la-naturaleza": {
    term: "Sistema de la naturaleza",
    aka: ["Sistema de la naturaleza"],
    kind: "obra",
    when: "1770",
    body: "Obra del barón d'Holbach, publicada bajo seudónimo. Expone la versión más radical del materialismo francés: el universo es sólo materia en movimiento, regida por leyes necesarias, sin lugar para un dios creador ni para un alma inmortal, y las religiones son invenciones humanas que explotan el miedo y la ignorancia con fines de dominación.",
  },
  "sobre-las-revoluciones": {
    term: "Sobre las revoluciones de los orbes celestes",
    aka: ["Sobre las revoluciones de los orbes celestes", "Sobre las revoluciones"],
    kind: "obra",
    when: "1543",
    body: "Obra de Nicolás Copérnico que expone el modelo heliocéntrico del universo, publicada el año de su muerte. Desplaza a la Tierra del centro del cosmos y la convierte en un planeta más en órbita alrededor del Sol, revirtiendo el orden geocéntrico de la astronomía ptolemaica y escolástica. Es el punto de partida de la revolución científica que culmina con Newton.",
  },
  "tratado-naturaleza-humana": {
    term: "Tratado de la naturaleza humana",
    aka: ["Tratado de la naturaleza humana", "el Tratado"],
    kind: "obra",
    when: "1739",
    body: "Primera gran obra de David Hume, publicada en 1739. Expone su teoría de las impresiones y las ideas, su análisis de la asociación de ideas y su crítica a la noción de conexión necesaria, base de todo su empirismo posterior.",
  },
  // ---------- eventoes ----------
  "caso-calas": {
    term: "caso Calas",
    aka: ["caso Calas", "Jean Calas", "affaire Calas"],
    kind: "evento",
    when: "1698–1765",
    body: "Jean Calas (1698–1762), comerciante protestante de Toulouse, es ejecutado en 1762 acusado sin pruebas sólidas de haber asesinado a su hijo para impedir su conversión al catolicismo. Voltaire encabeza una campaña pública en su defensa, reúne testimonios, presiona a la justicia y publica el Tratado sobre la tolerancia (1763) a partir del caso, hasta lograr en 1765 la rehabilitación póstuma de Calas.",
  },
  "disputa-de-los-fragmentos": {
    term: "disputa de los fragmentos",
    aka: ["disputa de los fragmentos", "Fragmentenstreit"],
    kind: "evento",
    when: "1774–1778",
    body: "Controversia pública desatada cuando Lessing publica, sin identificar a su autor, fragmentos del teólogo Reimarus que critican racionalmente los relatos bíblicos de milagros y la resurrección de Cristo. Su principal adversario es el pastor Johann Melchior Goeze. La disputa termina con la censura de los escritos teológicos de Lessing.",
  },
  "pregunta-de-1783": {
    term: "pregunta de 1783",
    aka: ["pregunta de 1783"],
    kind: "evento",
    when: "1783–1784",
    body: "Pregunta formulada por Zöllner en una nota al pie de la Berlinische Monatsschrift, que se vuelve el debate central de la Ilustración berlinesa: qué significa, exactamente, ilustrar. Mendelssohn y Kant responden por separado en 1784, con definiciones que no coinciden: Mendelssohn la trata como un saber que se posee en mayor o menor grado; Kant, como la salida de la minoría de edad.",
  },
  reforma: {
    term: "Reforma",
    aka: ["Reforma", "Reforma protestante", "Reforma luterana"],
    kind: "evento",
    when: "1517",
    body: "Movimiento religioso iniciado por Martín Lutero en 1517 que rompe la unidad del cristianismo occidental. Rechaza la autoridad del Papa y de la tradición eclesiástica como intérpretes últimos de la Biblia y traslada esa función a la conciencia de cada creyente. Además de su impacto religioso, desata las guerras de religión que obligan a repensar, sobre bases nuevas y seculares, el derecho internacional.",
  },
  "revolucion-gloriosa": {
    term: "Revolución Gloriosa",
    aka: ["Revolución Gloriosa", "Revolución de 1688"],
    kind: "evento",
    when: "1688",
    body: "Deposición del rey católico Jacobo II de Inglaterra y su reemplazo por Guillermo de Orange y María II, invitados por el Parlamento. Consolidó una monarquía constitucional limitada por el Parlamento y sentó, junto con la Carta de Derechos de 1689, el marco político estable sobre el que se desarrolla la Ilustración inglesa.",
  },
  "sturm-und-drang": {
    term: "Sturm und Drang",
    aka: ["Sturm und Drang"],
    kind: "evento",
    when: "1770–1785",
    body: "Movimiento literario alemán de las décadas de 1770 y 1780 cuyo nombre —«tempestad e ímpetu»— proviene del título de una obra teatral de Klinger. Reivindicó el genio, la pasión, la originalidad y la fuerza expresiva contra el buen gusto, la corrección racional y la imitación de modelos clásicos que dominaban la estética ilustrada. Sus integrantes fueron sobre todo jóvenes: el Goethe de Werther (1774) y el Schiller de Los bandidos (1781) son sus obras más conocidas. Hamann es una de sus figuras de referencia y Herder su principal teórico. El movimiento es importante para la historia de las ideas porque constituye la primera reacción interna contra la Ilustración alemana: no viene de la reacción política ni religiosa tradicional, sino de dentro de la cultura ilustrada, y anticipa buena parte de lo que el Romanticismo va a sistematizar.",
  },
};
