export default {
  num: 16,
  transcript: 17,
  title: "Los hijos de Husserl: en busca del otro",
  source: "https://www.youtube.com/watch?v=RXwWPT1RGWM",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "Esta clase recorre a un grupo de pensadores unidos por una biografía intelectual común más que por una escuela: todos estudian, leen de cerca o discuten con **Edmund Husserl** (1859-1938), fundador de la fenomenología, y todos terminan insatisfechos con un mismo punto ciego de su sistema. Entre ellos están **Martin Heidegger**, **Edith Stein**, **Jean-Paul Sartre**, **Emmanuel Levinas**, **Maurice Merleau-Ponty** y **Jan Patočka**; junto a ellos, desde una tradición vecina pero independiente, **Martin Buber**.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Casi todos nacen entre 1878 y 1908, en distintos puntos de una Europa que las dos guerras mundiales van a desgarrar: Stein en Breslau, Levinas en Kaunas, Patočka en Bohemia, Buber en Viena. Varios son judíos, y esa condición atraviesa sus biografías de un modo que la propia filosofía no puede mantener aparte: el exilio, la persecución, el frente de guerra son la circunstancia concreta desde la que piensan al otro.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El punto en común es este: la fenomenología de Husserl parte de la relación entre un **sujeto** y un **objeto**, y hereda de toda la filosofía moderna la obsesión por saber cómo un sujeto encerrado en su propia conciencia puede conocer un mundo exterior. Pero un objeto especial se cuela en ese mundo: **otro sujeto**, otra conciencia. Y ahí el aparato husserliano empieza a mostrar sus límites.",
    },
    {
      type: "quiz",
      question: "¿Qué tienen en común los pensadores de esta clase, más allá de estudiar con Husserl?",
      options: [
        "Quedan insatisfechos con el mismo punto ciego de su sistema",
        "Rechazan todos en bloque la fenomenología desde el comienzo",
        "Comparten todos la misma nacionalidad y formación filosófica",
        "Ninguno atraviesa nunca en persona las guerras europeas",
      ],
      answer: 0,
      explain: "Todos estudian, leen de cerca o discuten con Husserl, y todos terminan insatisfechos con un mismo punto ciego de su sistema: cómo pensar la relación con otro sujeto sin reducirlo a un objeto más.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "El trasfondo de todas estas respuestas es la **dialéctica hegeliana del amo y el esclavo**: la tesis de que ninguna conciencia se reconoce a sí misma en soledad, que la autoconciencia sólo se constituye reconociéndose en otra conciencia. Una vez planteado ese problema, ya no hay filosofía del siglo veinte que pueda evitarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Todos estos pensadores enfrentan además una versión del problema de la **alienación**, que la modernidad vuelve central: para Marx es estructural, el obrero separado de los productos de su trabajo y de sí mismo; para Hegel, en el amo y el esclavo, ninguno de los dos términos queda satisfecho, y la única salida es el **reconocimiento mutuo**. Lo constante es que la subjetividad nunca se resuelve en soledad: **siempre hay un otro**.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Sobre ese trasfondo, Husserl deja un problema específico sin resolver: su fenomenología describe con enorme precisión cómo un sujeto trascendental constituye el sentido del mundo, pero trata a los demás sujetos, en los hechos, como una variación más del objeto para mi conciencia. La generación siguiente —cada uno a su modo— busca una relación con el otro que no lo reduzca a esto.",
    },
    {
      type: "quiz",
      question: "¿Qué deja sin resolver Husserl, según la generación que lo sigue?",
      options: [
        "Trata a los demás sujetos como una variación del objeto",
        "Niega por completo la existencia de otras conciencias",
        "Confunde por completo la conciencia propia con la ajena",
        "Elimina toda diferencia posible entre sujeto y objeto",
      ],
      answer: 0,
      explain: "La fenomenología husserliana describe con precisión cómo el sujeto trascendental constituye el sentido del mundo, pero trata a los demás sujetos, en los hechos, como una variación más del objeto para mi conciencia.",
    },
    {
      type: "info",
      title: "Husserl y la respuesta epistemológica",
      body: "Husserl mismo cree haber resuelto el problema en la **Quinta meditación cartesiana**: ser un **ego trascendental** es ser una conciencia que constituye todo lo demás como objeto para sí. Su respuesta a cómo llegar entonces a otro sujeto es **epistemológica**: por **analogía, apareamiento o asociación**, infiero que el otro es también un sujeto, por comparación con mi propio yo. Imaginamos así una \"comunidad de egos\", de mónadas, donde cada yo sigue siendo el suyo, pero se supone que hay otros como el propio.",
    },
    {
      type: "info",
      continues: true,
      title: "Husserl y la respuesta epistemológica",
      body: "Esas otras mónadas cumplen además una función de confirmación: garantizan que vivimos en un mundo común. El ejemplo clásico es el de un **cubo**: desde ninguna posición se ven las seis caras a la vez, pero puedo deducir que existen, y una manera de confirmarlo es que otro observador, parado del otro lado, verifique las caras que a mí me faltan. El conocimiento, así, es **intersubjetivo**: los otros sujetos aportan puntos de vista adicionales y, a la vez, confirman que hay un solo mundo compartido.",
    },
    {
      type: "info",
      continues: true,
      title: "Husserl y la respuesta epistemológica",
      body: "Husserl llega a preguntarse si es concebible que coexistan pluralidades de mónadas sin comunión entre sí, constituyendo mundos separados, y responde que sería \"un puro absurdo\": la posibilidad misma de un mundo objetivo depende de que haya, en principio, una sola comunidad de sujetos que lo confirme desde ángulos distintos.",
    },
    {
      type: "info",
      continues: true,
      title: "Husserl y la respuesta epistemológica",
      body: "Aun con esa respuesta, el centro de gravedad de la fenomenología husserliana sigue siendo el **ego trascendental** singular: mi centralidad para mí mismo no es una tesis moral, es un hecho fenomenológico de partida. No hay acceso directo a la experiencia originaria de otro; el otro sólo puede tener, para mí, el sentido de otro existente en la medida en que **se constituye en mí** como tal.",
    },
    {
      type: "info",
      continues: true,
      title: "Husserl y la respuesta epistemológica",
      body: "En la reducción fenomenológica, lo único que no se pone entre paréntesis es el propio yo trascendental; los demás egos sí. A esa zona irreductible Husserl la llama la **esfera de lo propio** (Eigenheitssphäre).",
    },
    {
      type: "info",
      continues: true,
      title: "Husserl y la respuesta epistemológica",
      body: "Sus alumnos más próximos sienten que esa solución, aunque impecable como epistemología, es **existencialmente delgada**: seguir mirando al otro, en el fondo, como un objeto especialmente sofisticado no alcanza para dar cuenta de la experiencia real de estar con otros. Cada uno de los pensadores que siguen busca una comprensión más **gruesa** de la intersubjetividad, ensanchando el problema hacia la ontología, el cuerpo o la ética.",
    },
    {
      type: "quiz",
      question: "¿Cómo llega Husserl al otro sujeto, según su respuesta en la Quinta meditación?",
      options: [
        "Por analogía: infiere que el otro es un sujeto como yo",
        "Por una intuición directa e inmediata del otro sujeto",
        "Por revelación religiosa, sin mediación racional alguna",
        "Por deducción lógica pura, sin referencia al propio yo",
      ],
      answer: 0,
      explain: "Su respuesta es epistemológica: por analogía, apareamiento o asociación, infiero que el otro es también un sujeto, por comparación con mi propio yo. El ejemplo es el cubo: no veo todas sus caras, pero deduzco que existen.",
    },
    {
      type: "quiz",
      question: "¿Cómo llama Husserl a la zona del propio yo que no se pone entre paréntesis en la reducción?",
      options: [
        "La esfera de lo propio, el yo trascendental",
        "La actitud natural, previa a toda reducción",
        "El mundo de la vida, el Lebenswelt",
        "La conciencia intencional, sin ningún contenido",
      ],
      answer: 0,
      explain: "La esfera de lo propio (Eigenheitssphäre): en la reducción fenomenológica, lo único que no se pone entre paréntesis es el propio yo trascendental; los demás egos sí.",
    },
    {
      type: "info",
      title: "Heidegger: el ser-con",
      body: "Heidegger desplaza el problema con el concepto de **Mitsein**. El Dasein está siempre ya en el mundo, y ese mundo es un **Mitwelt**, un \"mundo-con\": estamos siempre ya arrojados a un mundo **con otros**, nunca primero solos y después acompañados. El Dasein es constitutivamente **Mitsein**, \"ser-con\"; en cierto sentido, la intersubjetividad es previa a la subjetividad, porque nunca hay un yo que no esté ya en compañía.",
    },
    {
      type: "info",
      continues: true,
      title: "Heidegger: el ser-con",
      body: "El único momento en que ese Mitsein se desarticula por completo es la **muerte**: la Jemeinigkeit, la \"mi-idad\" irreductible, porque nadie puede morir en lugar de otro. El foco de Ser y tiempo recae entonces en **cómo** se está en el mundo con otros: la distinción entre **autenticidad** e **inautenticidad**. La inautenticidad es caer en el das Man, el \"uno\" impersonal y conformista, disuelto en la habladuría (Gerede) y en la ambigüedad; la autenticidad exige un momento de soledad radical, la comprensión del propio ser-para-la-muerte, con esa Unheimlichkeit —no estar en casa— que Heidegger llama angustia.",
    },
    {
      type: "info",
      continues: true,
      title: "Heidegger: el ser-con",
      body: "Queda entonces una tensión sin resolver: matar es un acto intersubjetivo, pero **morir es siempre solitario**, y buena parte de Ser y tiempo termina ocupándose más de la relación entre un ente y el ser como tal que de la relación entre dos entes concretos. La pregunta por cómo estar auténticamente en el mundo con otros queda, en Heidegger, más planteada que resuelta.",
    },
    {
      type: "quiz",
      question: "Para Heidegger, ¿cuál es el único momento en que el Mitsein se desarticula por completo?",
      options: [
        "La muerte, porque nadie puede morir en lugar de otro",
        "El nacimiento, porque nadie elige nacer junto a otros",
        "El trabajo, porque cada tarea se hace en soledad",
        "El lenguaje, porque cada quien habla sólo para sí",
      ],
      answer: 0,
      explain: "El único momento en que el ser-con se desarticula es la muerte: la Jemeinigkeit, la «mi-idad» irreductible, porque nadie puede morir en lugar de otro. Matar es intersubjetivo, pero morir es siempre solitario.",
    },
    {
      type: "info",
      title: "Buber: el Yo-Tú",
      body: "Por fuera del linaje directo de Husserl, un contemporáneo llega a una respuesta paralela desde otra tradición. **Martin Buber** (1878-1965), nacido en Viena y formado en la cultura del jasidismo de Europa oriental, publica en 1923 Yo y Tú, el libro que lo hace central para el problema de la otredad.",
    },
    {
      type: "info",
      continues: true,
      title: "Buber: el Yo-Tú",
      body: "Buber distingue dos maneras básicas de estar en relación con el mundo. La actitud **Yo-Ello** (Ich-Es) es la del conocimiento y el uso: trato a lo que tengo enfrente como un objeto, algo que puedo describir, analizar, situar entre otras cosas. La actitud **Yo-Tú** (Ich-Du), en cambio, no describe ni analiza: es un encuentro directo, sin mediación, en el que el otro no es un caso de nada sino una presencia irrepetible a la que uno se dirige y no sobre la que uno habla.",
    },
    {
      type: "info",
      continues: true,
      title: "Buber: el Yo-Tú",
      body: "Ninguna de las dos actitudes anula a la otra, y ninguna relación Yo-Tú puede sostenerse indefinidamente: tarde o temprano el otro vuelve a convertirse en Ello, en objeto de descripción, y la vida humana oscila entre ambos registros. Pero cada relación Yo-Tú, por parcial que sea, es para Buber una manera de rozar lo que llama el \"**Tú eterno**\": toda relación auténtica con otro hombre contiene, aunque sea veladamente, una relación con Dios.",
    },
    {
      type: "info",
      continues: true,
      title: "Buber: el Yo-Tú",
      body: "Años más tarde Levinas dirá algo muy próximo: que tal vez no haya que distinguir con demasiada nitidez entre la trascendencia hacia el otro hombre y la trascendencia hacia Dios. Es uno de los pocos puentes explícitos entre dos tradiciones —la dialógica de Buber y la fenomenológica de Levinas— que llegan, por caminos distintos, a una misma intuición.",
    },
    {
      type: "info",
      continues: true,
      title: "Buber: el Yo-Tú",
      body: "Buber, judío y sionista, deja Alemania en 1938 huyendo de la persecución nazi y se instala en Jerusalén, donde enseña en la Universidad Hebrea el resto de su vida. Como en Stein, en Levinas y en Patočka, la pregunta filosófica por el otro no se separa, en su biografía, de la experiencia concreta de ser expulsado o amenazado por otros.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo describe la actitud Yo-Ello o la actitud Yo-Tú?",
      groups: ["Yo-Ello (Ich-Es)", "Yo-Tú (Ich-Du)"],
      items: [
        { text: "Trata al otro como un objeto que se describe y analiza", group: 0 },
        { text: "Un encuentro directo, sin mediación, irrepetible", group: 1 },
        { text: "Es la actitud del conocimiento y el uso", group: 0 },
        { text: "Roza, aunque sea un instante, el «Tú eterno»", group: 1 },
        { text: "Puede sostenerse de forma estable y prolongada", group: 0 },
        { text: "Nunca puede sostenerse indefinidamente en el tiempo", group: 1 },
      ],
      explain: "El Yo-Ello conoce y usa, trata al otro como objeto describible. El Yo-Tú es un encuentro directo e irrepetible que nunca dura: tarde o temprano el otro vuelve a ser Ello. Cada relación Yo-Tú, para Buber, roza el «Tú eterno».",
    },
    {
      type: "info",
      title: "Edith Stein: el cuerpo y la empatía",
      body: "Edith Stein nace a fines del siglo diecinueve en una familia judía ortodoxa de Breslau (hoy Wrocław). Pierde a su padre siendo muy chica y, como Beauvoir, pierde también la fe en la adolescencia: rompe con el judaísmo, se declara atea y busca en la filosofía una certeza que la psicología, que estudia primero, no le da. Al conocer la fenomenología de Husserl y su lema \"a las cosas mismas\", abandona todo para ir a estudiar con él.",
    },
    {
      type: "info",
      continues: true,
      title: "Edith Stein: el cuerpo y la empatía",
      body: "En 1913, poco antes de la Primera Guerra, se suma a una comunidad cercana de una docena de estudiantes de Husserl. Cuando estalla la guerra, en agosto de 1914, se vuelve una patriota alemana fervorosa: escribe que su vida individual dejó de importarle el día en que Alemania entró en guerra, porque todo lo que es pertenece ahora al Estado. Deja la universidad y se ofrece como enfermera en un hospital de la Cruz Roja en Austria-Moravia, antes de volver junto a Husserl para terminar su tesis.",
    },
    {
      type: "info",
      continues: true,
      title: "Edith Stein: el cuerpo y la empatía",
      body: "Cuando Husserl se traslada a Friburgo en 1916, casi no le quedan estudiantes: la guerra se los llevó a todos, incluidos sus propios hijos. **Adolf Reinach**, la gran promesa de la fenomenología, se ofrece como voluntario; el polaco **Roman Ingarden**, rechazado por el ejército por una afección cardíaca, vuelve a estudiar con Husserl. De ese círculo diezmado sólo quedan, en Friburgo, Ingarden y Stein.",
    },
    {
      type: "info",
      title: "La tesis sobre la empatía",
      body: "Stein escribe su tesis sobre el problema de la **empatía** (Einfühlung, literalmente \"sentir dentro de\"), y su aporte central es introducir algo que la obsesión husserliana con el ego trascendental había dejado afuera: el **cuerpo**. No se puede pensar un sujeto sin cuerpo, y esa convicción es inseparable de lo que Stein vivió en el hospital, en una época anterior a la penicilina y sin anestesia adecuada: el cuerpo herido, en dolor, agonizante, es lo que la convence de que no se puede filosofar ignorándolo.",
    },
    {
      type: "info",
      continues: true,
      title: "La tesis sobre la empatía",
      body: "Introduce entonces una distinción difícil de traducir: el **Leib**, el **cuerpo vivido**, experimentado desde adentro, y el **Körper**, el **cuerpo-objeto**, visto desde afuera. Cada uno tiene experiencia directa de un solo Leib, el propio; los cuerpos de los demás se experimentan siempre como Körper, desde afuera. La **empatía** es lo que nos permite imaginar que ese cuerpo ajeno visto desde afuera es también, para quien lo habita, un cuerpo vivido desde adentro —algo a lo que accedemos por analogía, nunca de manera directa—.",
    },
    {
      type: "info",
      continues: true,
      title: "La tesis sobre la empatía",
      body: "La empatía cumple, además, una segunda función: **devolverme mi propio yo**. Al imaginar cómo me ve otro, comprendo que no soy sólo sujeto para mí mismo, sino también **objeto para otros sujetos** —una idea que Sartre retomará y radicalizará—. Y cumple una tercera función, epistemológica: confirma que el mundo es real, porque no sólo yo veo lo que tengo delante, también lo ven los demás; el mundo percibido en primera persona y el mundo que se me da a través de la empatía de otros son, en el fondo, el mismo mundo visto de distintos modos.",
    },
    {
      type: "quiz",
      question: "En la distinción de Stein, ¿qué es el Körper frente al Leib?",
      options: [
        "El cuerpo-objeto, visto siempre desde afuera",
        "El cuerpo vivido, experimentado desde adentro",
        "La conciencia pura, sin ninguna base corporal",
        "El alma inmortal, distinta de cualquier cuerpo",
      ],
      answer: 0,
      explain: "El Leib es el cuerpo vivido, experimentado desde adentro; sólo tenemos experiencia directa del propio. El Körper es el cuerpo-objeto, visto desde afuera: así experimentamos siempre el cuerpo ajeno, salvando la distancia con la empatía.",
    },
    {
      type: "short",
      question: "¿Cómo llama Stein a la capacidad de imaginar que el cuerpo ajeno visto desde afuera es también un cuerpo vivido por dentro?",
      answers: ["empatía", "empatia", "einfühlung", "einfuhlung"],
      explain: "La empatía (Einfühlung, «sentir dentro de»): accedemos por analogía a que el cuerpo ajeno es también, para quien lo habita, un cuerpo vivido. Cumple además una función de confirmar el mundo compartido y de devolvernos el propio yo como objeto para otros.",
    },
    {
      type: "info",
      title: "Merleau-Ponty: el cuerpo vivido llevado al límite",
      body: "**Maurice Merleau-Ponty** (1908-1961) pertenece al mismo círculo parisino que Sartre y Beauvoir, con quienes funda en 1945 la revista Les Temps modernes, y en 1952 ocupa, siendo muy joven, la cátedra de filosofía del Collège de France. Su obra retoma la distinción de Stein entre cuerpo vivido y cuerpo-objeto, pero la lleva a sus últimas consecuencias en Fenomenología de la percepción (1945).",
    },
    {
      type: "info",
      continues: true,
      title: "Merleau-Ponty: el cuerpo vivido llevado al límite",
      body: "Para Merleau-Ponty, el cuerpo no es un objeto más entre los que habito de manera contingente: es el medio mismo a través del cual cualquier mundo, cualquier objeto y cualquier otro me son accesibles. No hay un punto de vista puro, desde ningún lugar, previo al cuerpo: percibir es siempre percibir desde un cuerpo situado, y por eso la vieja pregunta epistemológica por cómo el sujeto sale de su cabeza para llegar al mundo está mal planteada desde el comienzo, porque nunca hubo tal encierro.",
    },
    {
      type: "info",
      continues: true,
      title: "Merleau-Ponty: el cuerpo vivido llevado al límite",
      body: "Esto cambia también el problema del otro. Donde Husserl y Stein necesitan la empatía como un puente —inferir por analogía que el cuerpo ajeno esconde una conciencia como la propia—, Merleau-Ponty sostiene que el propio cuerpo reconoce al cuerpo del otro de manera inmediata, sin necesidad de inferencia: un gesto, una expresión, un movimiento se comprenden directamente porque el cuerpo propio ya sabe, de manera práctica, qué es moverse y gesticular. Es lo que llama **intercorporalidad**: la comunicación entre cuerpos antecede a cualquier razonamiento sobre otras mentes.",
    },
    {
      type: "info",
      continues: true,
      title: "Merleau-Ponty: el cuerpo vivido llevado al límite",
      body: "En su obra inconclusa Lo visible y lo invisible (publicada póstumamente en 1964), Merleau-Ponty radicaliza esto todavía más con la noción de **carne** (chair): mi cuerpo y el mundo, mi cuerpo y el cuerpo del otro, no son dos sustancias que después haya que conectar, sino variaciones de un mismo tejido sensible del que todos participamos. El problema del puente entre sujeto y objeto, el que persigue a la filosofía desde Descartes, deja de tener sentido si no hay, para empezar, semejante separación.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la intercorporalidad de Merleau-Ponty de la empatía de Stein?",
      options: [
        "No necesita inferencia: el cuerpo reconoce al cuerpo",
        "Depende por completo de un razonamiento por analogía",
        "Sólo funciona entre cuerpos de la misma cultura",
        "Niega que el cuerpo tenga ningún papel en el conocimiento",
      ],
      answer: 0,
      explain: "Donde Stein necesita la empatía como puente por analogía, Merleau-Ponty sostiene que el cuerpo propio reconoce al cuerpo del otro de manera inmediata: un gesto se comprende directamente porque el cuerpo ya sabe, de modo práctico, qué es moverse.",
    },
    {
      type: "info",
      title: "Sartre: la mirada del otro",
      body: "Stein no tiene la fuerza literaria de Sartre, pero anticipa buena parte de lo que él vuelve célebre. Sartre ve enseguida el riesgo **moral y existencial** de una noción demasiado liviana del otro, y lo formula con la metáfora de **le regard**, **la mirada**: en cada instante el otro me mira. Es esa mirada la que me permite advertir que el otro es un sujeto: cuando descubro que soy un **objeto para la conciencia de otro**, comprendo al mismo tiempo que ese otro no puede ser un mero objeto, porque sólo otro sujeto puede convertirme a mí en objeto.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre: la mirada del otro",
      body: "Un cambio radical del otro es necesario para que escape a la objetividad… es en y a través de la revelación de mi ser-objeto para el otro como debo poder captar la presencia de su ser-sujeto.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre: la mirada del otro",
      body: "La toma de conciencia de que el otro me mira tiene consecuencias enormes: todo el universo se desplaza de lugar, hay una descentralización radical que socava la centralidad que yo mismo ejercía sobre mi propio mundo. Y, con un fondo hegeliano explícito, no hay autoconocimiento sin el reconocimiento del otro sujeto: para afirmar la propia subjetividad hace falta ese reconocimiento, la misma estructura que organiza la dialéctica del amo y el esclavo.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre: la mirada del otro",
      body: "En El existencialismo es un humanismo, Sartre tiene un giro sorprendentemente kantiano —\"al decidir por mí, decido por todos\"—, cercano al imperativo categórico, del que él mismo parece incómodo. Y en la obra de teatro A puerta cerrada deja la frase que resume el lado más sombrío de esta mirada ajena: \"**el infierno son los otros**\".",
    },
    {
      type: "quiz",
      question: "Para Sartre, ¿qué revela el hecho de que el otro me mire?",
      options: [
        "Que soy objeto para otro, y por eso el otro es sujeto",
        "Que el otro es siempre, en el fondo, un mero objeto",
        "Que la mirada ajena no tiene ningún efecto real sobre mí",
        "Que sólo yo puedo mirar, y nunca puedo ser mirado",
      ],
      answer: 0,
      explain: "Cuando descubro que soy un objeto para la conciencia de otro, comprendo al mismo tiempo que ese otro no puede ser un mero objeto, porque sólo otro sujeto puede convertirme a mí en objeto.",
    },
    {
      type: "info",
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "**Emmanuel Levinas** nace en 1906 en Kaunas, entonces parte del Imperio zarista y hoy Lituania. Estudia filosofía en Francia y, a fines de los años veinte, va a Friburgo a formarse con Husserl, donde asiste también al seminario de su sucesor, Heidegger. Nacionalizado francés, se alista en el ejército al estallar la Segunda Guerra, cae prisionero de los alemanes y sobrevive porque es capturado como oficial francés: su condición de judío no llega a descubrirse, y eso lo salva de un destino que probablemente hubiera sido el Holocausto.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "Levinas da el paso más radical de todo el grupo. Si para Husserl al principio está la relación sujeto-objeto, y para Heidegger al principio está el Dasein ya arrojado al mundo, Levinas sostiene que **al principio está el otro**: la relación con el otro no es un problema derivado que la filosofía resuelve después de fundar la ontología o la epistemología, sino el fundamento mismo de ambas. De ahí su tesis de que la **ética es filosofía primera**: antes de preguntar qué es el ser o cómo conocemos, hay que dar cuenta de esa relación fundante con el otro.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "En Totalidad e infinito (1961), el concepto central es el **rostro** (visage): el encuentro cara a cara con otro, que no se deja reducir a ningún concepto ni categoría. Levinas contrasta el **infinito** con la **totalidad**: la totalidad es todo intento de encerrar al otro dentro de un sistema que yo domino; el infinito es la trascendencia absoluta del otro, que siempre excede cualquier idea que yo pueda hacerme de él.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "No es la insuficiencia del yo lo que impide la totalización, sino la infinitud del otro.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "El rostro del otro no puede poseerse, sólo **desearse**: hay, en Levinas, un \"deseo metafísico\" de lo absolutamente otro que nunca se satisface ni se cancela. Lo que funda y convoca al sujeto no es sólo el conocimiento, sino esa relación de deseo hacia lo que siempre queda más allá:",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "El extranjero que perturba el estar en casa consigo mismo… es el libre; sobre él no tengo poder; escapa a mi presa por una dimensión esencial.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "En esta relación cara a cara convergen epistemología, ontología y ética sin fases separadas, porque la otredad es, para Levinas, fundamentalmente ética: implica un **cuestionamiento de uno mismo** ante el otro, antes de cualquier decisión voluntaria. El rostro me interpela y me exige responder, incluso antes de que yo elija responder.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: el rostro y la ética como filosofía primera",
      body: "Levinas describe ese llamado del otro como un arrancamiento: el otro me saca del reposo en el ser, me expone, me obliga a verme desde su punto de vista y a rendir cuentas. Lo que la reducción fenomenológica hace en Husserl, o el ser-para-la-muerte en Heidegger —ese momento de sacudida que revela la propia existencia—, en Levinas no ocurre frente a la muerte sino frente **al otro**. El rostro del otro funciona, en este sentido, como una secularización de Dios: lo que está siempre más allá, lo que nunca puede poseerse ni agotarse, pero que sigue convocando.",
    },
    {
      type: "quiz",
      question: "¿Qué quiere decir que, para Levinas, «la ética es filosofía primera»?",
      options: [
        "La relación con el otro funda la ontología y el conocer",
        "La ética es sólo una rama más de la epistemología",
        "El ser se estudia siempre antes que cualquier relación ética",
        "La ontología resuelve por sí sola el problema del otro",
      ],
      answer: 0,
      explain: "Para Levinas, al principio está el otro: la relación con el otro no es un problema derivado que la filosofía resuelve después de fundar la ontología o la epistemología, sino el fundamento mismo de ambas.",
    },
    {
      type: "short",
      question: "¿Cómo llama Levinas al encuentro cara a cara con el otro, que no se deja reducir a ningún concepto?",
      answers: ["rostro", "visage"],
      explain: "El rostro (visage): el encuentro cara a cara con otro, irreductible a concepto. No puede poseerse, sólo desearse; funciona como una secularización de Dios, lo que siempre está más allá pero sigue convocando.",
    },
    {
      type: "info",
      title: "Patočka: la historia como solidaridad de los conmovidos",
      body: "**Jan Patočka** (1907-1977) es, cronológicamente, el último de estos hijos de Husserl: nacido en Bohemia, asiste en Friburgo tanto a Husserl como a Heidegger, y se convierte en el fundador de la fenomenología checa. Bajo el régimen comunista de Checoslovaquia, gran parte de su obra circula sólo en cátedras clandestinas y en samizdat, sin poder publicarse.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka: la historia como solidaridad de los conmovidos",
      body: "Su concepto tardío más influyente aparece en los Ensayos heréticos sobre la filosofía de la historia, escritos hacia mediados de los años setenta: la \"**solidaridad de los conmovidos**\". La tesis es que quienes atraviesan una experiencia que quiebra el orden habitual y dador de sentido de la vida cotidiana —el ejemplo paradigmático es el frente de batalla— quedan unidos por un vínculo que precede a cualquier programa político y que no depende de compartir opiniones ni intereses.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka: la historia como solidaridad de los conmovidos",
      body: "Ese vínculo es, en cierto modo, la respuesta de Patočka a la misma pregunta que persigue a todo el grupo: cómo pensar una relación con el otro que no lo reduzca a un caso más de objeto. Pero donde Levinas la encuentra en el encuentro cara a cara de dos personas, Patočka la sitúa en una experiencia histórica y colectiva de conmoción compartida.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka: la historia como solidaridad de los conmovidos",
      body: "En 1977 Patočka es uno de los fundadores y primer vocero de la **Carta 77**, la declaración checoslovaca en defensa de los derechos humanos, y muere pocos días después de ser sometido a un interrogatorio policial extenuante. Su propia biografía termina siendo, de manera literal, un ejemplo de la solidaridad de los conmovidos que había descrito: una filosofía del otro que desemboca en una práctica concreta del disenso político.",
    },
    {
      type: "quiz",
      question: "¿Qué es la «solidaridad de los conmovidos» de Patočka?",
      options: [
        "El vínculo entre quienes atraviesan una experiencia límite",
        "Una alianza basada en compartir opiniones políticas afines",
        "Un contrato social firmado tras una guerra devastadora",
        "Un sentimiento exclusivo de quienes ganan una guerra",
      ],
      answer: 0,
      explain: "Quienes atraviesan una experiencia que quiebra el orden habitual de la vida cotidiana —el frente de batalla, por ejemplo— quedan unidos por un vínculo que precede a cualquier programa político y no depende de compartir opiniones ni intereses.",
    },
    {
      type: "match",
      question: "Repaso: uní cada pensador con su respuesta al problema del otro",
      pairs: [
        { left: "Husserl", right: "Llega al otro por analogía desde el propio yo" },
        { left: "Heidegger", right: "El Dasein es siempre ya ser-con, Mitsein" },
        { left: "Stein", right: "La empatía tiende un puente entre Leib y Körper" },
        { left: "Sartre", right: "La mirada del otro me revela como objeto" },
        { left: "Levinas", right: "El rostro del otro funda la ética como filosofía primera" },
      ],
      explain: "Cada uno da una respuesta distinta al mismo problema heredado de Husserl: cómo pensar al otro sin reducirlo a un objeto más para mi conciencia. De la epistemología (Husserl) se pasa a la ontología (Heidegger) y luego a la ética (Levinas).",
    },
    {
      type: "info",
      title: "Cierre: la mirada, el llamado y la conmoción",
      body: "Toda esta generación pasa de la epistemología de Husserl a la ontología de Heidegger, y de ahí a un fuerte impulso ético que Levinas lleva al extremo. Para Sartre, el otro siempre me **mira**; para Levinas, el otro siempre me **llama**, me exige una respuesta antes de que yo decida darla; para Buber, el otro puede volverse, aunque sea por un instante, un Tú irrepetible y no un caso más de Ello; para Patočka, la experiencia compartida de la conmoción funda una solidaridad que ni la ideología ni el interés pueden reemplazar.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la mirada, el llamado y la conmoción",
      body: "Todos están marcados por las guerras que atraviesan. Levinas seculariza a Dios en el rostro del otro; Stein va en la dirección contraria: termina convirtiéndose al catolicismo y entra en un convento carmelita cuando el nazismo toma el poder en Alemania. A la propia Stein la universidad alemana le niega la habilitación necesaria para ser profesora por el solo hecho de ser mujer, aunque Husserl llega a escribir que, si la docencia estuviera abierta a las mujeres, ella sería la primera a quien recomendaría.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la mirada, el llamado y la conmoción",
      body: "Antes de todo eso, en Friburgo, Stein se cruza a menudo con un joven ayudante de Husserl al que apenas conoce como \"el pequeño Heidegger\". Esa cercanía temprana hará más amarga, años después, la adhesión de Heidegger al nazismo: la generación que buscó pensar al otro de la manera más honda termina viendo, en uno de los suyos, la negación más completa de ese proyecto.",
    },
  ],
};
