export default {
  num: 6,
  transcript: 7,
  title: "Henri Bergson: la revuelta contra el positivismo",
  source: "https://www.youtube.com/watch?v=fhIW-E9wZe8",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Henri Bergson** (1859-1941) nace en París, hijo de un compositor judío polaco y de una madre judía británica. Se forma en la École Normale Supérieure y en 1900 obtiene una cátedra en el Collège de France, donde sus clases se vuelven un acontecimiento mundano de la vida parisina, seguidas por un público que excede largamente al académico. En 1927 recibe el **Premio Nobel de Literatura**, distinción poco habitual para un filósofo y que reconoce, sobre todo, la calidad literaria de su prosa.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Cuatro obras ordenan su pensamiento. El Ensayo sobre los datos inmediatos de la conciencia (1889) introduce la **durée** y el problema del libre albedrío. Materia y memoria (1896) desarrolla su teoría de la memoria. La risa (1900) es su ensayo sobre lo cómico. La evolución creadora (1907), su obra de mayor repercusión pública, propone el **élan vital**; años después vuelve sobre el tiempo en Duración y simultaneidad (1922), donde polemiza con Einstein.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Bergson nace en 1859, el mismo año en que Darwin publica El origen de las especies, y quince años después de Nietzsche. Como buena parte de su generación, empieza como matemático, y esa formación deja huella profunda en su filosofía del tiempo: es de los pocos filósofos de su época capaces de seguir de cerca los debates técnicos de la matemática de su tiempo, y de ahí extrae varias de sus analogías centrales. Es, discutiblemente, el filósofo francés más influyente de la primera mitad del siglo XX.",
    },
    {
      type: "info",
      title: "El problema que hereda: el positivismo",
      body: "El término **positivismo** lo acuña **Auguste Comte** (1798-1857) en su Curso de filosofía positiva (1830-1842). Comte propone una **ley de los tres estados**: el pensamiento humano pasa de lo teológico, que explica los fenómenos por voluntades divinas o sobrenaturales, a lo metafísico, que los explica por esencias y fuerzas abstractas, hasta llegar a lo positivo, que se atiene sólo a lo observable, medible y verificable. Ese último estadio es el de la ciencia, y para Comte es también el destino final e irreversible de todo saber humano.",
    },
    {
      type: "quiz",
      question: "Según Comte, la ley de los tres estados describe el pensamiento pasando de…",
      options: [
        "lo teológico a lo metafísico y finalmente a lo positivo",
        "lo positivo a lo metafísico y finalmente a lo teológico",
        "lo individual a lo colectivo y luego a lo universal",
        "lo empírico a lo racional y finalmente a lo trascendente",
      ],
      answer: 0,
      explain: "Lo teológico explica los fenómenos por voluntades divinas; lo metafísico, por esencias y fuerzas abstractas; lo positivo se atiene sólo a lo observable y verificable, y es, para Comte, el destino final de todo saber.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el positivismo",
      body: "El positivismo hereda de la racionalidad ilustrada y del modelo de las ciencias duras la idea de que el conocimiento debe basarse en la **experiencia sensorial empírica**, como en un laboratorio: se prueba la teoría de la gravedad soltando una pelota y observando qué ocurre. Se atiende a lo concreto, material y fáctico, y se produce un **alejamiento deliberado de la metafísica**, de todo lo que está más allá de lo físico y lo tangible. El conocimiento válido es lo que puede verse, tocarse, gustarse, olerse, contarse y calcularse.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el positivismo",
      body: "Hay, además, un **ánimo** propio del positivismo: una racionalidad fría, materialista, antimetafísica y antiidealista, que a mucha gente le resultará deprimente aunque no pretendiera serlo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el positivismo",
      body: "Heredero directo de Comte es **Herbert Spencer** (1820-1903), la versión del positivismo con la que Bergson se forma: para Spencer el único conocimiento sólido está en las ciencias; en ética es utilitarista, sostiene que hay que actuar para el mayor bien del mayor número sobre bases prácticas; le interesa la evolución, entendida como adaptación directa del organismo a las limitaciones de su ambiente; y, como pensador ilustrado, cree en la perfectibilidad humana, en un avance progresivo hacia el equilibrio y en la eventual desaparición del mal.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el positivismo",
      body: "Bergson está inmerso en ese positivismo —son sus orígenes intelectuales— y luego se rebela por completo contra él, en lo que podría llamarse una **revuelta edípica** contra la tradición de la que se viene: un gesto que se repite una y otra vez en este período. Lo que rechaza no es la ciencia natural, sino los **supuestos mecanicistas** del positivismo, la idea de que la vida humana puede entenderse enteramente como una máquina, como partes que encajan, como fenómenos naturales reducibles a masas y movimientos. Hay, sostiene, otras dimensiones de la vida que ese método no puede captar.",
    },
    {
      type: "quiz",
      question: "¿Qué es lo que Bergson rechaza exactamente del positivismo?",
      options: [
        "Los supuestos mecanicistas, no la ciencia natural en sí",
        "La ciencia natural en su totalidad, incluida la física",
        "La idea de que existan hechos observables y medibles",
        "El uso de las matemáticas para describir la naturaleza",
      ],
      answer: 0,
      explain: "Lo que rechaza no es la ciencia natural, sino los supuestos mecanicistas: la idea de que la vida humana puede entenderse enteramente como una máquina, como partes que encajan.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el positivismo",
      body: "Bergson integra, junto con **Freud** y **Husserl** —los tres nacidos con pocos años de diferencia—, un mismo frente de rebeldía contra ese legado ilustrado. Cada uno ataca un flanco distinto: Freud, la transparencia de la conciencia; Husserl, la reducción de la experiencia a hechos físicos; Bergson, la idea de que el tiempo puede medirse como se mide el espacio.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el positivismo",
      body: "Los tres, además, comparten un rasgo generacional: son pensadores cosmopolitas, formados en más de una lengua y más de una tradición nacional, para quienes la Europa de fin de siglo es un espacio intelectual único antes que una serie de compartimentos separados.",
    },
    {
      type: "quiz",
      question: "¿Contra qué se rebelan Bergson, Freud y Husserl?",
      options: [
        "Contra el idealismo hegeliano y su fe en el Espíritu",
        "Contra el positivismo y su fe en lo medible",
        "Contra el ateísmo militante de Nietzsche",
        "Contra el contrato social y el liberalismo político",
      ],
      answer: 1,
      explain: "Los tres nacen dentro del clima positivista heredado de la Ilustración y luego se rebelan: hay dimensiones de la vida —el tiempo, la conciencia, lo inconsciente— que la observación empírica y el modelo de las ciencias duras no pueden captar.",
    },
    {
      type: "info",
      title: "El método de Bergson: pensar en dualidades",
      body: "Antes de entrar en sus tesis conviene notar cómo piensa Bergson, porque el método explica buena parte de sus conclusiones. Le gusta pensar en **dualidades** —como harán después los estructuralistas—: continuo frente a discreto, cantidad frente a calidad, ciencia frente a filosofía, materialismo frente a metafísica. A diferencia de Hegel, que se concentra en cómo la cantidad se vuelve calidad dentro de un mismo proceso, Bergson sostiene que ciertos ámbitos de la vida se captan de modo cuantitativo y otros exigen un modo cualitativo: son dos formas de pensar fundamentalmente distintas, no dos momentos de una misma progresión.",
    },
    {
      type: "info",
      continues: true,
      title: "El método de Bergson: pensar en dualidades",
      body: "En sus dualidades nunca hay términos absolutos: siempre hacen falta los dos, aunque uno esté privilegiado, porque a Bergson le resulta más profundo o más revelador. Es, además, un escritor literario, aficionado a la **metáfora** —aunque no tan lírico ni divertido como Nietzsche—, que tiende a **postular** sus ideas antes que a demostrarlas paso a paso: confía en la fuerza de la imagen y de la intuición más que en el argumento formal, un rasgo que sus críticos le reprocharán una y otra vez.",
    },
    {
      type: "quiz",
      question: "¿Cómo suele proceder Bergson para defender sus tesis?",
      options: [
        "Postulando ideas fuertes, apoyado en metáforas",
        "Demostrando cada tesis con silogismos formales",
        "Citando exclusivamente resultados experimentales",
        "Refutando a sus críticos uno por uno en público",
      ],
      answer: 0,
      explain: "Es un escritor literario, aficionado a la metáfora, que tiende a postular sus ideas antes que a demostrarlas paso a paso: confía en la imagen y la intuición más que en el argumento formal.",
    },
    {
      type: "info",
      title: "El tiempo no es espacio",
      body: "Antes de entrar en las tesis específicas de Bergson conviene fijar el vocabulario del tiempo que atraviesa el curso, porque Bergson se sitúa deliberadamente en uno de los extremos de cada distinción. El tiempo puede pensarse como **cíclico**, el de las estaciones y las festividades que vuelven sobre sí mismas, o como **lineal**, el que avanza con una dirección: el predominio de lo lineal es, precisamente, uno de los rasgos que definen a la modernidad frente a las sociedades tradicionales.",
    },
    {
      type: "info",
      continues: true,
      title: "El tiempo no es espacio",
      body: "También puede pensarse como **parejo**, el que avanza a un ritmo constante, o **a saltos**, el que se mueve de modo agitado, con desaceleraciones y estallidos súbitos —así lo piensa Hegel, con su transformación de la cantidad en calidad—. Y puede pensarse como **errante**, que simplemente serpentea sin destino, o como **direccional**, con una flecha que apunta hacia algún telos: esta última distinción es la que atañe estrictamente a la teleología.",
    },
    {
      type: "info",
      continues: true,
      title: "El tiempo no es espacio",
      body: "La distinción que más importa para Bergson, sin embargo, es otra: **continuo** frente a **discreto**, tomada de una analogía matemática que conviene tener presente porque va a organizar todo lo que sigue. Su primer punto de revuelta, el más fundamental de todos, es la idea de que el tiempo puede entenderse por **analogía con el espacio**, cortándolo en unidades cuantificables —segundos, minutos, instantes—, tal como lo entendía Spencer. Así como el espacio se mide en metros y milímetros y se cuantifica sin dificultad, la tradición filosófica **proyecta** esa misma comprensión sobre el tiempo, como si fueran de la misma naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "El tiempo no es espacio",
      body: "Para Bergson eso es un error, porque el tiempo no admite ese tratamiento cuantitativo: lo cuantitativo exige unidades **discretas**, separables, contables una por una, y el tiempo carece de ese tipo de articulación. El modelo cuantificable es apropiado para el espacio, pero no para el tiempo, que sólo puede entenderse desde **la experiencia** que se tiene de él —aquí es donde entra la subjetividad— como algo dinámico, irreversible y continuo, que no puede fragmentarse, contarse ni dividirse sin desnaturalizarlo.",
    },
    {
      type: "quiz",
      question: "¿Por qué, para Bergson, es un error medir el tiempo como se mide el espacio?",
      options: [
        "Porque el tiempo no existe realmente, es sólo una ilusión de la conciencia",
        "Porque el tiempo es duración continua, no partes sueltas",
        "Porque el espacio, en verdad, tampoco puede medirse con exactitud",
        "Porque sólo Dios puede conocer el tiempo verdadero",
      ],
      answer: 1,
      explain: "El tiempo real es flujo, no una fila de instantes. Cortarlo en segundos es como pasar un cuchillo a través de una llama: se divide lo desplegado, no el desplegarse. Es una multiplicidad cualitativa, no cuantitativa.",
    },
    {
      type: "info",
      continues: true,
      title: "El tiempo no es espacio",
      body: "Para nombrar esa experiencia usa la palabra **durée**, **duración**: el tiempo como **flujo**, no como sucesión de puntos discretos; algo que no puede fragmentarse, contarse ni representarse como una recta con marcas regulares. Es la misma intuición, con otro nombre, que ya aparecía en el **eterno retorno** de Nietzsche: la imagen de un río en el que siempre se está en movimiento y siempre hay conexión entre el pasado y el presente, sin que se produzca jamás un corte limpio entre uno y otro.",
    },
    {
      type: "short",
      question: "¿Cómo llama Bergson al tiempo vivido de la conciencia?",
      answers: ["durée", "duración"],
      explain: "La durée es el tiempo tal como se vive: continuo, cualitativo e indivisible, frente al tiempo espacializado que miden los relojes.",
    },
    {
      type: "info",
      title: "La analogía del continuo (Cantor)",
      body: "La distinción entre lo medible y lo no medible, entre lo contable y lo no contable, viene directamente de la matemática: de la distinción entre lo **continuo y lo discreto** que estudia el cálculo infinitesimal, y más precisamente de **Georg Cantor**, matemático próximo a Husserl, que en 1878 formula la **hipótesis del continuo** dentro de la teoría de conjuntos.",
    },
    {
      type: "info",
      continues: true,
      title: "La analogía del continuo (Cantor)",
      body: "En su forma más simple, esa hipótesis distingue entre distintos tipos de infinito: está el infinito del conjunto de todos los **enteros** —1, 2, 3, 4… que sigue indefinidamente, pero siempre con huecos entre un número y el siguiente— y el infinito, de otro orden, del conjunto de todos los **puntos de la recta numérica**, donde entre el 1 y el 2 hay infinitos puntos sin que exista ningún hueco entre ellos.",
    },
    {
      type: "quiz",
      question: "Para Cantor, ¿qué distingue el infinito de los enteros del infinito de los puntos de una recta?",
      options: [
        "Los enteros tienen huecos; los puntos de la recta, no",
        "Los enteros son finitos; los puntos de la recta, infinitos",
        "Sólo los enteros pueden ordenarse de menor a mayor",
        "La recta numérica no contiene ningún número entero",
      ],
      answer: 0,
      explain: "Entre el 1 y el 2 hay infinitos puntos sin hueco entre ellos; entre un entero y el siguiente, en cambio, siempre hay un hueco. Bergson toma de ahí la distinción entre lo discreto y lo continuo.",
    },
    {
      type: "info",
      continues: true,
      title: "La analogía del continuo (Cantor)",
      body: "Lo importante para Bergson es la distinción entre lo **discreto**, lo separado en unidades como 1, 2 y 3, y lo **continuo**, todo lo que hay entre esos números sin solución de continuidad. Se piensa el **espacio** como algo discreto y contable, pero el **tiempo**, sostiene Bergson, no puede asirse de esa manera.",
    },
    {
      type: "info",
      continues: true,
      title: "La analogía del continuo (Cantor)",
      body: "El tiempo no es como el conjunto de los enteros: es como el conjunto de todos los puntos de la recta, que sigue sin huecos y al que no se le puede abrir uno. Si se intenta cortarlo de todos modos, es como pasar un cuchillo a través de una llama: el filo atraviesa el fuego sin lograr partirlo en dos mitades separadas.",
    },
    {
      type: "info",
      title: "Tiempo, conciencia, totalidad",
      body: "Todas las demás distinciones de Bergson giran en torno a esta. El **espacio** se asocia a los objetos **inertes**, no animados; el **tiempo**, a la **conciencia**: para asir la subjetividad hay que asir antes la temporalidad. Bergson recurre a metáforas musicales y de fusión para describir esa experiencia: un análisis psicológico fino, dice, distingue una duración cuyos momentos heterogéneos se penetran unos a otros, de modo que por debajo del yo de estados bien definidos hay un yo en el que suceder significa fundirse en un **todo orgánico**.",
    },
    {
      type: "info",
      continues: true,
      title: "Tiempo, conciencia, totalidad",
      body: "Un análisis psicológico fino distingue una duración cuyos momentos heterogéneos se penetran unos a otros… por debajo del yo de estados bien definidos, un yo en el que suceder significa fundirse unos en otros y formar un todo orgánico.",
    },
    {
      type: "info",
      continues: true,
      title: "Tiempo, conciencia, totalidad",
      body: "El tiempo no es consecutivo, es continuo. Hay en esta idea un anhelo de **totalidad** cercano al de Hegel: la sensación de que la fragmentación de la vida cotidiana es una forma de alienación que hay que superar, y de que el pasado, lejos de desaparecer, coexiste siempre de manera virtual en el presente. Esa coexistencia virtual del pasado en el presente no es todavía, en este punto de la exposición, más que una intuición; más adelante, con la teoría de la memoria, Bergson intentará darle un fundamento más preciso.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que le corresponde",
      pairs: [
        { left: "Durée", right: "El tiempo como flujo continuo, no como puntos" },
        { left: "Cantor", right: "La distinción matemática entre lo continuo y lo discreto" },
        { left: "Spencer", right: "El positivismo evolucionista contra el que Bergson se rebela" },
        { left: "Espacio", right: "Lo cuantitativo, discreto y medible" },
        { left: "Conciencia", right: "Lo cualitativo, que sólo se aprehende en el tiempo" },
      ],
      explain: "Bergson piensa por dualidades: espacio/tiempo, discreto/continuo, cuantitativo/cualitativo. Toma de Cantor la matemática del continuo y la vuelve contra el positivismo de Spencer para defender la durée.",
    },
    {
      type: "info",
      title: "El gran salto: tiempo y libre albedrío",
      body: "Aquí aparece el movimiento filosófico más difícil de dar con Bergson: conectar el tiempo entendido como **continuo** con el **libre albedrío**. Bergson quiere una noción **antiteleológica** del tiempo, en la que el futuro no avance en una dirección fija sino que permanezca **abierto** según lo que se elija en cada momento. Contingencia, aquí, como lo opuesto del determinismo: siempre hay múltiples posibilidades abiertas, y el accidente y la elección juegan un papel real en cómo se resuelven.",
    },
    {
      type: "info",
      continues: true,
      title: "El gran salto: tiempo y libre albedrío",
      body: "Kant se había limitado a **postular** el libre albedrío: no podía probarlo mediante ningún argumento teórico, pero lo necesitaba como condición para fundar la moral, de modo que lo asume sin demostrarlo. Bergson, en cambio, intenta **probarlo**, y ahí el argumento se vuelve difícil de seguir: sostiene que el libre albedrío está inextricablemente unido al tiempo entendido como **multiplicidad cualitativa**, y que es precisamente la experiencia cualitativa del tiempo la que da lugar a actos libres, espontáneos, que no pueden determinarse de antemano por ninguna cadena causal.",
    },
    {
      type: "quiz",
      question: "¿Qué diferencia el tratamiento del libre albedrío en Kant y en Bergson?",
      options: [
        "Kant lo niega; Bergson lo afirma",
        "Kant lo postula; Bergson intenta probarlo",
        "Ambos lo demuestran con el mismo argumento",
        "Kant lo funda en el tiempo; Bergson en la razón pura",
      ],
      answer: 1,
      explain: "Kant no puede probar el libre albedrío, pero lo postula como condición de la moral. Bergson va más lejos: sostiene que el yo libre y espontáneo brota de la experiencia cualitativa y continua del tiempo —aunque, fiel a su estilo, lo postula más que lo prueba.",
    },
    {
      type: "info",
      continues: true,
      title: "El gran salto: tiempo y libre albedrío",
      body: "La duración pura es la forma que adopta la sucesión de nuestros estados de conciencia cuando nuestro yo se deja vivir, cuando se abstiene de separar su estado presente de sus estados anteriores… podemos concebir la sucesión sin distinción, como una penetración mutua, una interconexión y organización de elementos, cada uno de los cuales representa el todo y no puede distinguirse ni aislarse salvo por el pensamiento abstracto.",
    },
    {
      type: "info",
      continues: true,
      title: "El gran salto: tiempo y libre albedrío",
      body: "Ese yo libre y continuo atraviesa el flujo del tiempo, y ese flujo dinámico es la **precondición** de un yo que se autodetermina en su propio devenir: sin duración no habría, para Bergson, posibilidad alguna de libertad, porque toda decisión quedaría ya fijada de antemano por el estado anterior de las cosas.",
    },
    {
      type: "info",
      continues: true,
      title: "El gran salto: tiempo y libre albedrío",
      body: "El argumento, hay que decirlo, postula la unión entre duración y libertad más de lo que la demuestra paso a paso: es una intuición fuerte, sostenida por metáforas convincentes, pero no una prueba lógicamente cerrada. Esto anticipa además la **polémica con Einstein**, para quien el tiempo se compone de instantes, mientras que para Bergson el tiempo es, ante todo, flujo.",
    },
    {
      type: "info",
      title: "Materia y memoria (1896)",
      body: "La durée necesita un correlato en la vida mental concreta, y Bergson lo busca en la **memoria**. Distingue dos tipos radicalmente distintos. La **memoria-hábito** es motriz y repetitiva: aprender de memoria un poema recitándolo una y otra vez, hasta que el cuerpo lo retiene como un mecanismo casi automático, es el ejemplo que Bergson prefiere para ilustrarla. El **recuerdo puro**, en cambio, conserva cada acontecimiento pasado como algo único e irrepetible, sin fundirlo jamás en un hábito ni en una repetición mecánica.",
    },
    {
      type: "info",
      continues: true,
      title: "Materia y memoria (1896)",
      body: "La memoria-hábito pertenece al presente útil, al cuerpo que actúa y necesita respuestas rápidas y automáticas; el recuerdo puro pertenece al pasado en cuanto tal, y para Bergson ese pasado no desaparece nunca del todo: subsiste **virtualmente**, entero, y se actualiza de manera parcial y selectiva cada vez que la percepción presente lo convoca para algún fin práctico. De ahí la imagen, célebre entre sus lectores, de un **cono de la memoria**, cuya punta toca el presente en un solo instante mientras la base, mucho más ancha, contiene todo el pasado conservado, disponible en principio para ser convocado de nuevo.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de la memoria-hábito o del recuerdo puro?",
      groups: ["Memoria-hábito", "Recuerdo puro"],
      items: [
        { text: "Motriz y repetitiva, como aprender un poema de memoria", group: 0 },
        { text: "Pertenece al presente útil y a respuestas automáticas", group: 0 },
        { text: "Conserva cada acontecimiento como algo único e irrepetible", group: 1 },
        { text: "Subsiste virtualmente entero, sin perderse del todo", group: 1 },
      ],
      explain: "La memoria-hábito es el cuerpo que actúa rápido y automático; el recuerdo puro conserva el pasado en cuanto tal, y no desaparece nunca del todo: subsiste virtual, disponible para actualizarse.",
    },
    {
      type: "quiz",
      question: "¿Qué representa, en la imagen del cono de la memoria, la punta que toca el presente?",
      options: [
        "El instante en que el pasado virtual se actualiza",
        "El momento en que se olvida definitivamente algo",
        "El punto en que memoria-hábito y recuerdo puro se separan",
        "El límite entre la conciencia y el inconsciente",
      ],
      answer: 0,
      explain: "La punta del cono toca el presente en un solo instante; la base, mucho más ancha, contiene todo el pasado conservado, disponible en principio para ser convocado de nuevo.",
    },
    {
      type: "info",
      continues: true,
      title: "Materia y memoria (1896)",
      body: "Esta teoría de la memoria es la que sostiene, más atrás en la argumentación, la afirmación de que el pasado **coexiste virtualmente** con el presente: no es un dato adicional y curioso sobre el funcionamiento de la mente, es la prueba misma de que la duración no se pierde nunca del todo, sino que se acumula y se lleva encima, como una bola de nieve que crece con su propio movimiento a medida que rueda. Cada instante vivido queda así conservado, y en algún sentido disponible, aunque la conciencia despierta sólo convoque de él lo que necesita en cada ocasión.",
    },
    {
      type: "info",
      title: "Contra el finalismo y el mecanicismo",
      body: "En La evolución creadora (1907) Bergson vuelve a sus temas centrales, otra vez atacando a Spencer: le reprocha el falso evolucionismo que consiste en cortar la realidad ya evolucionada en pedazos no menos evolucionados, y luego recomponerla, postulando de antemano todo lo que en realidad habría que explicar desde cero. El libro refuta dos posiciones que Bergson considera estrechamente emparentadas: el **finalismo** y el **mecanicismo**.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "El **finalismo** es la idea de que la vida se mueve hacia un **telos** dado de antemano, el concepto aristotélico que también emplean Hegel y Marx cada uno a su modo. Bergson recurre a la imagen de la semilla de manzana: esa semilla no contiene, en miniatura, una manzana ya formada, pero tampoco se volverá jamás una piña ni ningún otro fruto, porque el resultado final está de algún modo precableado en ella desde el comienzo.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "A Bergson esta idea le resulta inaceptable, porque cuanto más determinismo hay en el proceso, menos espacio queda para el libre albedrío que quiere salvar a toda costa.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "El **mecanicismo**, en cambio, es la idea ilustrada de que la naturaleza entera funciona como una máquina cuyas partes encajan unas con otras, y que basta comprender cada parte por separado para comprender el todo. Una bicicleta, dice Bergson, se explica enteramente por sus engranajes, palancas, ruedas y tornillos, sin que haga falta apelar a nada misterioso.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "Ser antimecanicista no significa, aclara, deshacerse de las bicicletas: el pensamiento mecanicista sirve, y sirve bien, para entender cómo encajan las partes de un objeto inerte. Lo que no puede hacer es captar la **vida**, porque ve detalles, posiciones, números, funciones aislables, y ese es, para Bergson, un modo empobrecido de comprender cualquier cosa que esté viva.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del finalismo o del mecanicismo?",
      groups: ["Finalismo", "Mecanicismo"],
      items: [
        { text: "La vida avanza hacia un telos fijado de antemano", group: 0 },
        { text: "La semilla ya contiene, precableado, el fruto final", group: 0 },
        { text: "La naturaleza funciona como una máquina de piezas", group: 1 },
        { text: "Basta entender cada parte para entender el todo", group: 1 },
      ],
      explain: "El finalismo fija un destino único desde el comienzo (la semilla de manzana); el mecanicismo explica el todo por sus piezas (la bicicleta). Bergson rechaza ambos: la vida no tiene un fin fijo ni se reduce a sus partes.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "¿Cómo entender entonces la evolución? Para Bergson es **pluridimensional**, avanza en múltiples direcciones a la vez, y el movimiento se produce por **división**, porque las cosas se rompen en fragmentos que después siguen caminos distintos —en esto es, de algún modo, un precursor de ciertas ideas posmodernas—.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "Su analogía preferida es la de una **bala de cañón** frente a un **proyectil explosivo**: la bala va a un solo lugar, en línea recta, mientras que el proyectil estalla y sus fragmentos van en todas direcciones a la vez, con múltiples efectos simultáneos e imprevisibles. La vida, sostiene Bergson, se parece mucho más al proyectil que estalla que a la bala que sigue una trayectoria fija.",
    },
    {
      type: "quiz",
      question: "La imagen de la bala de cañón frente al proyectil que estalla ilustra que, para Bergson, la vida…",
      options: [
        "Se dirige con precisión hacia una meta única y predeterminada",
        "No avanza hacia un fin fijo: se dispersa y crea",
        "Es esencialmente destructiva y violenta",
        "Retrocede en círculos, como el tiempo cíclico premoderno",
      ],
      answer: 1,
      explain: "La bala de cañón es el finalismo (un solo destino); el proyectil que estalla es el élan vital: la vida crea en múltiples direcciones imprevisibles. Contra el finalismo y el mecanicismo, Bergson pone la creatividad y la elección.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el finalismo y el mecanicismo",
      body: "La fuerza que impulsa ese estallido múltiple es el **élan vital**, la **fuerza vital**: la idea de que hay una fuerza generadora que nos hace estar aquí, querer actuar, ser seres creativos capaces de producir novedad genuina y no sólo de repetir combinaciones ya dadas de antemano. El élan vital no es, para Bergson, una entidad mística separada de la vida orgánica: es más bien el nombre que le da a esa capacidad de la vida de diferenciarse y de inventar formas nuevas, algo que ni el finalismo ni el mecanicismo pueden explicar por sí solos.",
    },
    {
      type: "info",
      title: "La polémica con Einstein",
      body: "En Duración y simultaneidad (1922) Bergson retoma el problema del tiempo para discutir abiertamente con Einstein, que mide la relatividad del tiempo por **instantes** sucesivos. Para Bergson el tiempo tiene que ser **flujo**, y no una serie de instantes discretos, porque sólo entendido como flujo puede inyectársele libre albedrío y contingencia genuina: la duración es, en sus palabras, esencialmente una continuación de lo que ya no existe en lo que existe.",
    },
    {
      type: "quiz",
      question: "En su polémica con Einstein, ¿cómo entiende Bergson el tiempo?",
      options: [
        "Como flujo continuo, no como una serie de instantes",
        "Como una serie de instantes discretos y medibles",
        "Como una ilusión que la física ya superó",
        "Como algo idéntico al espacio tridimensional",
      ],
      answer: 0,
      explain: "Para Einstein el tiempo se compone de instantes sucesivos; para Bergson, sólo entendido como flujo puede inyectársele libre albedrío y contingencia genuina.",
    },
    {
      type: "info",
      continues: true,
      title: "La polémica con Einstein",
      body: "Escuchen una melodía con los ojos cerrados, sin yuxtaponer sobre el papel o un teclado imaginario notas que conservan una junto a otra… Reencontrarán, indivisa e indivisible, la melodía… Nuestra duración interior es algo así como esa melodía. Pero cuando intentamos cortarla, es como pasar de golpe una hoja a través de una llama: dividimos lo desplegado, no el desplegarse. No podemos dividir el desplegarse del tiempo… El tiempo real es espeso, no tiene instantes.",
    },
    {
      type: "info",
      continues: true,
      title: "La polémica con Einstein",
      body: "Si se piensa el tiempo como si fuera el espacio, y se cree que el pasado puede trocearse en unidades separadas, se termina proyectando lo mismo sobre el **futuro**, como si todo lo que aún no se ha desplegado ya estuviera ahí de antemano, oculto detrás de una pantalla que simplemente se corre a medida que pasa el tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "La polémica con Einstein",
      body: "Los actos ya no serían entonces un aporte genuino de novedad imprevisible, sino apenas una parte de un tejido dado de una sola vez desde siempre: no los introducimos nosotros en el mundo, sería más bien el mundo el que los introduce, ya hechos, en nosotros. Bergson rechaza de plano esa metafísica implícita en la representación espacial del tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "La polémica con Einstein",
      body: "El problema, para Bergson, es que no se puede espacializar mentalmente sólo una parte del tiempo y dejar el resto intacto: una vez que se empieza a desplegar el pasado como si fuera una línea de puntos, y se abole así la sucesión real que efectivamente se vivió, queda comprometido un despliegue **total** de todo el tiempo, pasado y futuro por igual.",
    },
    {
      type: "info",
      continues: true,
      title: "La polémica con Einstein",
      body: "Y entonces se termina culpando a la imperfección del conocimiento humano por ignorar un futuro que, según esa lógica errónea, ya estaría presente en alguna parte, esperando a ser descubierto. Como en el argumento sobre la libertad, Bergson postula esta conexión entre tiempo y contingencia más de lo que la demuestra con rigor formal.",
    },
    {
      type: "info",
      title: "Intelecto e intuición",
      body: "La última gran dualidad de Bergson es **intelecto** frente a **instinto**, y en su forma más elaborada y sofisticada, **intuición**. Se necesitan los dos, pero uno queda claramente privilegiado. El **intelecto** está hecho para pensar la **materia inerte**: es apropiado para cierto pensamiento racional y positivista sobre las cosas materiales, y sirve, por ejemplo, para ver cómo encajan las partes de una bicicleta —ser antimecanicista, insiste Bergson, no significa deshacerse de las bicicletas—.",
    },
    {
      type: "info",
      continues: true,
      title: "Intelecto e intuición",
      body: "El intelecto ve y analiza en **piezas y partes**, en lo separable; funciona por **representación**, y está cómodo, dice Bergson, sólo en lo discontinuo, lo inmóvil, lo muerto: tiene una incapacidad natural para comprender la vida en tanto vida.",
    },
    {
      type: "info",
      continues: true,
      title: "Intelecto e intuición",
      body: "El **instinto** —y su forma sofisticada, la **intuición**— es una perspectiva **interna, subjetiva y holística**, la que Bergson privilegia sin ambigüedad. El instinto, escribe, está moldeado sobre la forma misma de la vida y procede orgánicamente; si la conciencia que dormita en él llegara a despertar del todo, entregaría los secretos más íntimos de la vida misma.",
    },
    {
      type: "info",
      continues: true,
      title: "Intelecto e intuición",
      body: "La intuición aprehende la realidad no de manera representacional ni en partes separadas, sino directamente **desde adentro**, no simbólicamente sino de un modo vital y holístico: capta la multiplicidad no fragmentada en pedazos, sino de un solo golpe, como un todo, y está conectada con el tiempo tal como el intelecto está conectado con el espacio. Rechazar la intuición y quedarse sólo con el intelecto mecanicista es, para Bergson, un modo empobrecido de asir el mundo, que lo priva de creatividad y de vida.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al intelecto o a la intuición?",
      groups: ["Intelecto", "Intuición"],
      items: [
        { text: "Perspectiva externa y analítica: observa, mide, categoriza", group: 0 },
        { text: "Perspectiva interna, subjetiva y holística", group: 1 },
        { text: "Apropiado para pensar la materia inerte", group: 0 },
        { text: "Aprehende la vida desde adentro, de un solo golpe", group: 1 },
        { text: "Ve en piezas y partes, por representación", group: 0 },
        { text: "Es la facultad privilegiada por Bergson", group: 1 },
      ],
      explain: "El intelecto sirve para la materia inerte —ver cómo encajan las partes de una bicicleta— pero tiene «una incapacidad natural para comprender la vida». La intuición, forma sofisticada del instinto, capta lo orgánico directamente, sin trocearlo. Se necesitan ambos, pero la intuición es superior.",
    },
    {
      type: "info",
      title: "La risa (1900)",
      body: "En este ensayo, muy leído después en el campo de las artes, Bergson analiza la función de lo cómico. Lo cómico, sostiene, tiene que ver con lo que **no es consciente de sí**: es humorístico, específicamente, lo que carece de autoconciencia, lo que en un ser vivo revela, por su rigidez, la apariencia de un puro mecanismo.",
    },
    {
      type: "info",
      continues: true,
      title: "La risa (1900)",
      body: "La función de la risa es **romper ese mecanismo**, una operación cercana a la desfamiliarización que después formulará el crítico ruso Shklovski y a la reducción fenomenológica de Husserl: procedimientos distintos que persiguen, cada uno a su modo, la misma meta de permitir ver de nuevo con claridad algo que el hábito había vuelto invisible.",
    },
    {
      type: "info",
      continues: true,
      title: "La risa (1900)",
      body: "El arte —pintura, escultura, poesía o música— no tiene otro objeto que apartar los símbolos utilitarios, las generalidades convencionales y socialmente aceptadas, todo lo que nos vela la realidad, para ponernos cara a cara con la realidad misma.",
    },
    {
      type: "info",
      continues: true,
      title: "La risa (1900)",
      body: "Ese anhelo de asir lo real, la vida en su esencia sin el velo de las convenciones, es otra variación del viejo problema del puente entre sujeto y objeto que ya atormentaba a Hegel, aunque Bergson lo resuelva de un modo completamente distinto: no mediante la dialéctica, sino mediante el arte y la intuición.",
    },
    {
      type: "info",
      continues: true,
      title: "La risa (1900)",
      body: "Lo cómico es ese lado de la persona que revela su semejanza con una cosa; ese aspecto de los hechos humanos que, por su peculiar rigidez, da la impresión de puro mecanismo, de automatismo, de movimiento sin vida… Su corrección es la risa, un gesto social que señala y reprime cierta clase de distracción en los hombres y en los acontecimientos.",
    },
    {
      type: "info",
      continues: true,
      title: "La risa (1900)",
      body: "La risa es, entonces, un **correctivo** social contra el mecanismo irreflexivo: es la vida misma rompiendo, mediante la comedia, el modo automatizado en que a veces se congela sin que quien lo padece llegue a advertirlo. Reírse de alguien que resbala con rigidez de autómata, o de un personaje que repite siempre el mismo gesto sin adaptarlo a la situación, es —para Bergson— una manera social de señalar esa falta de flexibilidad vital y de empujar, mediante la vergüenza leve que produce la risa ajena, a recuperarla.",
    },
    {
      type: "quiz",
      question: "Según La risa, ¿qué provoca lo cómico y qué función cumple reírse?",
      options: [
        "La alegría espontánea; la risa sirve para reforzar los lazos afectivos",
        "La rigidez mecánica de lo humano; la risa la corrige",
        "La transgresión moral; la risa castiga el vicio",
        "El absurdo del lenguaje; la risa libera tensión nerviosa",
      ],
      answer: 1,
      explain: "Para Bergson reímos de lo que revela «puro mecanismo, automatismo, movimiento sin vida». La risa es un gesto social correctivo: antídoto contra el mecanismo irreflexivo, la vida rompiendo el modo automatizado. Coherente con toda su filosofía antimecanicista.",
    },
    {
      type: "match",
      question: "Uní cada obra o concepto con su núcleo",
      pairs: [
        { left: "La evolución creadora", right: "Refuta el finalismo y el mecanicismo" },
        { left: "La risa", right: "Lo cómico como rigidez mecánica; reír, un correctivo" },
        { left: "Élan vital", right: "La fuerza creadora que empuja la vida en direcciones divergentes" },
        { left: "Intuición", right: "Captar la vida desde adentro, no en partes" },
        { left: "Einstein", right: "Piensa el tiempo como instantes, no como flujo" },
      ],
      explain: "Todo el pensamiento de Bergson gira sobre una misma intuición: la vida y el tiempo son flujo continuo y creador, y el error es trocearlos como si fueran materia inerte —sea en la evolución, en el tiempo físico o en lo cómico.",
    },
    {
      type: "info",
      title: "Herencia",
      body: "Bergson muere en enero de 1941, a los 81 años, ya bajo la ocupación alemana de París. Judío de nacimiento y el filósofo francés más célebre de su tiempo, recibe de las autoridades una oferta de exención de algunas leyes antisemitas —los nazis admiraban su vitalismo— y la rechaza, llevando la estrella judía hasta el final de su vida. Se dice, aunque el dato es incierto y posiblemente apócrifo, que murió de un resfrío contraído mientras hacía la fila para registrarse como judío ante las nuevas autoridades de ocupación.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "Su influencia se ramifica en direcciones muy distintas entre sí. En Francia alimenta, décadas más tarde, la fenomenología de la percepción de **Maurice Merleau-Ponty**, que retoma la idea de un cuerpo vivido y temporalizado frente al cuerpo-objeto de la ciencia natural.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "En los años sesenta es objeto de la relectura que hace **Gilles Deleuze** en El bergsonismo (1966), que recupera la duración y la multiplicidad cualitativa para la filosofía francesa de posguerra, y que hará del élan vital uno de los antecedentes de su propia filosofía de la diferencia. Antes, en Estados Unidos, el pragmatista **William James** ya había encontrado en la durée un aliado para su propia crítica del intelectualismo y de la reducción de la experiencia a estados discretos y mensurables.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "El hilo que Bergson deja abierto es el del ser vivo como centro de una **contingencia radical**: cada vida que entra en el mundo introduce en él algo que no estaba precableado de antemano, algo genuinamente nuevo que ninguna cadena causal previa podía predecir del todo. Hannah Arendt llamará a esto, más tarde, **natalidad**: la llegada de un ser nuevo como inyección de imprevisibilidad radical en la historia, capaz de ir en múltiples direcciones que nadie puede anticipar.",
    },
    {
      type: "match",
      question: "Uní cada pensador con lo que retoma de Bergson",
      pairs: [
        { left: "Merleau-Ponty", right: "El cuerpo vivido y temporalizado frente al cuerpo-objeto" },
        { left: "Deleuze", right: "Relee la duración y la multiplicidad en El bergsonismo" },
        { left: "William James", right: "Encuentra en la durée un aliado contra el intelectualismo" },
        { left: "Hannah Arendt", right: "Llama natalidad a la novedad que cada nacimiento introduce" },
      ],
      explain: "La herencia de Bergson se ramifica: en la fenomenología del cuerpo (Merleau-Ponty), en la filosofía de la diferencia (Deleuze), en la crítica pragmatista al intelectualismo (James) y en la natalidad como imprevisibilidad radical (Arendt).",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "Esa idea de una temporalidad abierta, hecha de contingencia y de elección, tiene su reverso exacto en el debate que ocupa la clase siguiente: si el tiempo de la subjetividad individual puede describirse como flujo indeterminado, el tiempo de la historia colectiva que hereda el marxismo se piensa, en cambio, como una necesidad casi mecánica que avanza hacia un fin conocido.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "La pregunta que se abre entonces es si esa historia necesaria admite, después de todo, alguna forma de aceleración deliberada: el problema que Lenin hereda de la Segunda Internacional y que intenta resolver con la teoría del partido de vanguardia.",
    },
  ],
};
