export default {
  num: 12,
  transcript: 13,
  title: "El existencialismo francés",
  source: "https://www.youtube.com/watch?v=G9Ovu6Lxo28",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Jean-Paul Sartre** (1905-1980) nace en París. Estudia filosofía en Francia y Alemania, donde lo cautiva la fenomenología, aunque enseguida empieza a criticarla: en La trascendencia del ego (1937) objeta la reducción fenomenológica desde una perspectiva ya heideggeriana, sosteniendo que no puede haber tal suspensión de la creencia en el mundo porque estamos siempre ya en él.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Sirve como meteorólogo del ejército francés, cae prisionero de guerra en 1940 y usa el cautiverio para estudiar a fondo Ser y tiempo. Liberado, participa en la Resistencia hasta 1943 y en ese período escribe su obra central, El ser y la nada (1943). Con Simone de Beauvoir, Maurice Merleau-Ponty y Raymond Aron funda, terminada la guerra, la revista Les Temps modernes, y en octubre de 1945 da la conferencia pública El existencialismo es un humanismo, la versión resumida y más accesible de su filosofía.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Es un autor extraordinariamente prolífico —dramaturgo, novelista, filósofo, memorialista— y rechaza en 1964 el Premio Nobel de Literatura por considerarlo una institución burguesa. En los años de posguerra deriva hacia el marxismo y actúa, en buena medida, como apologista del estalinismo, silencioso ante los juicios-espectáculo de Europa del Este. Muere en 1980; un diario parisino tituló ese día: \"Francia ha perdido su conciencia\".",
    },
    {
      type: "info",
      title: "El problema heredado: de la intencionalidad al ser-en-el-mundo",
      body: "La fenomenología de Husserl buscaba trascender la conciencia subjetiva afirmando, a la vez, su primacía como lugar de todo sentido: la **intencionalidad** era el puente que permitía a la conciencia alcanzar el objeto sin abandonar su lugar central. Heidegger da el giro más radical: reformula la pregunta de modo que la distancia entre sujeto y objeto deje de ser un problema, porque el Dasein está siempre ya en el mundo, arrojado e involucrado en él, sin necesidad de puente alguno.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: de la intencionalidad al ser-en-el-mundo",
      body: "Quedaba abierta una pregunta: reemplazar al sujeto clásico por el Dasein, ¿es una radicalización del sujeto o su disolución? Sartre elige la primera lectura, y la lleva más lejos que el propio Heidegger: para él el Dasein es, si cabe, **más** sujeto todavía. Esa lectura se apoya, en parte, en una traducción francesa temprana de Dasein como \"realidad humana\", discutible pero influyente, que termina produciendo una versión casi cartesiana y radicalmente subjetivista de Ser y tiempo.",
    },
    {
      type: "quiz",
      question: "¿Cómo lee Sartre el Dasein de Heidegger?",
      options: [
        "Como la disolución definitiva y total del sujeto",
        "Como un sujeto aún más radical y subjetivo",
        "Como un simple objeto entre otros objetos",
        "Como un regreso a la cosa en sí kantiana",
      ],
      answer: 1,
      explain: "Heidegger dejaba abierta la pregunta de si el Dasein radicaliza o disuelve al sujeto. Sartre toma la versión radicalmente subjetivista: el Dasein es aún más sujeto, fuente de todo sentido y de toda elección.",
    },
    {
      type: "info",
      title: "El contexto histórico: la política sin centro",
      body: "Conviene situar el momento. La Revolución de 1789 deja a Dios apartado pero no muerto, y transforma súbditos en ciudadanos con derechos; 1848 mezcla liberalismo y nacionalismo con la aparición del Manifiesto comunista y su teleología de un tiempo que progresa hacia un destino. Hacia 1880 se declara la muerte de Dios, y en 1914 estalla la Primera Guerra: el orden europeo se hace añicos, caen los imperios, el mapa se rediseña sobre países nuevos que se presentan como democracias liberales y que, en su mayoría, no resisten.",
    },
    {
      type: "info",
      continues: true,
      title: "El contexto histórico: la política sin centro",
      body: "En el período de entreguerras (1918-1939) la izquierda y la derecha se radicalizan y el centro desaparece casi sin resistencia: Stalin consolida el poder hacia fines de los años veinte, Hitler llega al poder en 1933. Es una política de masas que aspira a controlar todos los aspectos de la vida. Ese contexto —altísimas apuestas, alternativas dramáticas, ningún lugar moderado desde el cual mirar sin involucrarse— es el que explica la obsesión de Sartre con la elección: todos están, quiéranlo o no, comprometidos.",
    },
    {
      type: "info",
      continues: true,
      title: "El contexto histórico: la política sin centro",
      body: "El nazismo y el estalinismo quedan, de ahí en más, de fondo en todo pensamiento europeo. Entre Polonia y Rusia, en lo que se conoce como las **tierras de sangre**, mueren millones de no combatientes entre 1933 y 1953, entre campos de concentración nazis, cámaras de gas, el Gulag soviético y hambrunas deliberadas. Ese es el trasfondo real del \"imperativo de la elección\" que el existencialismo francés convierte en su tema central.",
    },
    {
      type: "quiz",
      question: "¿Qué explica, según la clase, la obsesión de Sartre con la elección?",
      options: [
        "Un contexto sin centro moderado, de apuestas extremas",
        "Su lectura temprana y exclusiva de la ética kantiana",
        "El optimismo económico de la Francia de posguerra",
        "La ausencia casi total de conflictos políticos",
      ],
      answer: 0,
      explain: "Entre las dos guerras, izquierda y derecha se radicalizan y el centro desaparece: nazismo, estalinismo, las tierras de sangre. Ese contexto de apuestas altísimas y ningún lugar moderado explica la centralidad de la elección en el existencialismo francés.",
    },
    {
      type: "info",
      title: "El existencialismo de Sartre",
      body: "En la conferencia de 1945, El existencialismo es un humanismo, Sartre defiende al existencialismo de la acusación de pesimismo y toma con total seriedad la muerte de Dios y la consiguiente **absurdidad** de una vida sin garantía trascendente. Sigue a Heidegger en distinguir **ser** de **existir**: la abeja o la vaca pueden ser en el mundo, pero solo el ser humano además **existe**, en el sentido de que debe crearse a sí mismo mediante elecciones; no tiene una esencia previa, sino que su esencia consiste en su propia existencia.",
    },
    {
      type: "info",
      title: "La existencia precede a la esencia",
      body: "Dios cumplía, entre otras funciones, la de garantizar una naturaleza humana fija, una esencia pregada de antemano. Sartre invierte la fórmula: **la existencia precede a la esencia**. No hay naturaleza humana a priori; primero se es arrojado al mundo, y solo después, existiendo y eligiendo, cada quien elabora su propia esencia. \"El hombre no es nada más que lo que él hace de sí mismo.\"",
    },
    {
      type: "quiz",
      question: "«La existencia precede a la esencia» quiere decir que…",
      options: [
        "nacemos con una naturaleza humana ya fijada",
        "primero existimos y luego nos creamos",
        "la esencia de las cosas es más real que su existencia",
        "sólo existe aquello que podemos definir con conceptos",
      ],
      answer: 1,
      explain: "Dios garantizaba una esencia humana previa. Sin Él no hay naturaleza a priori: primero somos arrojados al mundo y después, eligiendo, elaboramos nuestra esencia. Somos pura posibilidad hasta que actuamos.",
    },
    {
      type: "info",
      continues: true,
      title: "La existencia precede a la esencia",
      body: "Si Dios ha muerto, dice Sartre, siguiendo a Nietzsche y a Dostoievski, entonces la humanidad misma queda como única creadora de valores, y no hay margen para lamentarse: hay que sacar las consecuencias de esa muerte hasta el final. Donde Heidegger habla de estar arrojado (Geworfenheit), Sartre insiste más en el **abandono**: arrojados al mundo y abandonados por un Dios que no existe.",
    },
    {
      type: "info",
      continues: true,
      title: "La existencia precede a la esencia",
      body: "El existencialista encuentra sumamente incómodo que Dios no exista, pues con él desaparece toda posibilidad de hallar valores en un cielo inteligible. Dostoievski escribió: \"si Dios no existiera, todo estaría permitido\"; y ese es el punto de partida del existencialismo.",
    },
    {
      type: "quiz",
      question: "Para Sartre, ¿qué se sigue de tomarse en serio la muerte de Dios?",
      options: [
        "Que hay que restaurar un orden moral religioso",
        "Que somos nosotros los creadores de los valores",
        "Que la moral sigue existiendo intacta sin Dios",
        "Que ya nada de lo que hagamos tiene la menor importancia",
      ],
      answer: 1,
      explain: "«Si Dios no existe, todo está permitido» (Dostoievski). Sin un cielo de valores, somos nosotros quienes los creamos, y quedamos arrojados y abandonados. Sartre reprocha al moralismo laico querer suprimir a Dios «al menor costo posible».",
    },
    {
      type: "info",
      title: "Nada y libertad radical",
      body: "Se es arrojado al mundo como pura posibilidad, como **nada**: Sartre sigue en esto a Heidegger, para quien la nada esencial es la muerte hacia la que avanzamos inexorablemente. Pero Sartre enfatiza otro aspecto de la nada, más cercano al nihilismo de la vanguardia de comienzos de siglo: si todo carece de fundamento último, esa misma falta de fundamento es **libertad radical**, el espacio en blanco desde el que cada quien se crea.",
    },
    {
      type: "info",
      continues: true,
      title: "Nada y libertad radical",
      body: "Queda atrás, con esto, todo determinismo: un mundo de contingencia casi total, aunque no completa. El límite que Sartre reconoce es lo que llama la **facticidad de la situación**: la libertad se ejerce siempre desde una posición concreta, no en el vacío.",
    },
    {
      type: "quiz",
      question: "¿Qué nombra la «facticidad de la situación» en Sartre?",
      options: [
        "Los límites dados dentro de los que somos libres",
        "La ausencia total de cualquier límite a la acción",
        "El destino que determina de antemano la vida",
        "Las leyes morales que Dios dejó escritas",
      ],
      answer: 0,
      explain: "Somos libres, pero dentro de una situación dada: puedo caminar, correr o saltar, pero no volar. La facticidad es ese «casi» que recorta la libertad casi total —lo ya dado, lo que no elegí— sin anularla.",
    },
    {
      type: "info",
      title: "En-sí y para-sí",
      body: "Sartre combina dos nociones, con ecos de la duración bergsoniana, para explicar esa tensión. El **en-sí** (en soi) es lo ya dado e inerte: lo que efectivamente ha ocurrido, quién se ha sido hasta este momento, muy cercano a la facticidad de la situación; no puede deshacerse. El **para-sí** (pour soi), en cambio, es lo fluido y dinámico: la posibilidad de ir más allá de lo que se ha sido, la negación del en-sí y su proyección hacia el futuro.",
    },
    {
      type: "info",
      continues: true,
      title: "En-sí y para-sí",
      body: "El presente es, en esta imagen, una frontera entre lo que ya fue —que no puede cambiarse— y la nada todavía abierta que se tiene por delante, el espacio para crearse de nuevo. Se es libre porque no se es solo en-sí sino también para-sí: la conciencia, dice Sartre, es \"un viento que sopla desde ninguna parte hacia el mundo\". Lejos de ser deprimente, esa nada es lo aún no determinado, y por eso mismo es también la posibilidad misma de la libertad.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al en-sí o al para-sí?",
      groups: ["En-sí", "Para-sí"],
      items: [
        { text: "Lo ya establecido e inerte que no se deshace", group: 0 },
        { text: "Lo fluido y dinámico, pura posibilidad", group: 1 },
        { text: "Quiénes hemos sido hasta este momento", group: 0 },
        { text: "La posibilidad de trascender hacia el futuro", group: 1 },
        { text: "Está muy cerca de la facticidad de la situación", group: 0 },
        { text: "Es la negación interna, la nihilación de lo dado", group: 1 },
      ],
      explain: "El en-sí es lo hecho, lo inerte, lo que no puede cambiarse; el para-sí es la conciencia como actividad, la posibilidad de ir más allá de quien uno ha sido. Somos libres porque no sólo somos en-sí, sino también para-sí: siempre más que nuestra facticidad.",
    },
    {
      type: "info",
      title: "Elección, decisionismo y mala fe",
      body: "El existencialista sartreano es, ante todo, un sujeto de **libre albedrío** que actúa siempre dentro de los límites de una situación dada: se puede elegir caminar o correr, no volar. Y en cualquier situación es necesario elegir, porque no elegir es también una forma de elección. El imperativo moral no está en **qué** se elige, sino en **que** se elija asumiendo la responsabilidad plena de la elección: no hay realidad fuera de la acción, y cada quien es solo lo que hace.",
    },
    {
      type: "short",
      question: "¿Cómo llamamos a la idea de que, arrojados a una situación, cada uno debe decidir por sí mismo —y no decidir también es decidir?",
      answers: ["decisionismo"],
      explain: "Decisionismo: como el hipopótamo que debe decidir solo si se queda o se va. En toda situación estamos obligados a elegir; lo que importa no es qué elegimos, sino que asumamos la elección.",
    },
    {
      type: "info",
      title: "Mala fe",
      body: "De ahí la **mauvaise foi**, la **mala fe**: no el sentido coloquial de actuar con motivos ocultos, sino un autoengaño en el que la misma conciencia es a la vez quien miente y quien recibe la mentira. Su forma más frecuente es refugiarse en un discurso determinista para evadir la propia libertad —\"no podía haber hecho otra cosa\", \"así soy yo\"— tratándose a uno mismo falsamente como si fuera un objeto y no un sujeto libre.",
    },
    {
      type: "quiz",
      question: "En Sartre, ¿en qué consiste la «mala fe» (mauvaise foi)?",
      options: [
        "Actuar con motivos ocultos hacia los demás",
        "Autoengañarse para evadir la responsabilidad",
        "Mentirle deliberadamente a otra persona",
        "Perder la fe religiosa tras la muerte de Dios",
      ],
      answer: 1,
      explain: "No es el sentido coloquial. Es un autoengaño: mentirse a uno mismo, casi siempre refugiándose en un determinismo —«no podía hacer otra cosa», «así soy yo»— para negar la propia libertad y no cargar con la responsabilidad de elegir.",
    },
    {
      type: "short",
      question: "¿Cómo llama Sartre al autoengaño con que negamos nuestra libertad para no cargar con la responsabilidad?",
      answers: ["mala fe", "mauvaise foi"],
      explain: "La mala fe (mauvaise foi): mentirse a uno mismo, tratarse como un objeto determinado —«tenía que ser así»— para escapar de la responsabilidad de elegir. Es análoga al das Man de Heidegger.",
    },
    {
      type: "info",
      continues: true,
      title: "Mala fe",
      body: "Hay también una forma inversa, menos común: negar la facticidad de la situación y creerse capaz de cualquier cosa por el solo deseo, viviendo en pura fantasía.",
    },
    {
      type: "info",
      continues: true,
      title: "Mala fe",
      body: "Sartre discute aquí con Freud: la idea de una conciencia limpiamente dividida entre inconsciente y consciente le resulta incorrecta, porque supone poder separar una parte opaca de una parte transparente. Para Sartre, toda la conciencia es **translúcida** —ni opaca ni del todo transparente—, y es precisamente esa translucidez la que hace posible la mala fe, la que permite mentirse a uno mismo sin dejar de saberlo.",
    },
    {
      type: "info",
      title: "Angustia, responsabilidad y elecciones sin inocencia",
      body: "La angustia sartreana, a diferencia de la heideggeriana, está ligada menos a la finitud que a la **responsabilidad**: quien elige no solo decide lo que será, sino que actúa, en cierto sentido, como legislador para toda la humanidad, y de ahí no puede escapar el sentimiento de una responsabilidad total. Libertad absoluta es responsabilidad absoluta, una carga que Sartre no presenta como cómoda ni liviana.",
    },
    {
      type: "classify",
      question: "¿Cada énfasis es más de Heidegger o de Sartre?",
      groups: ["Heidegger", "Sartre"],
      items: [
        { text: "El estar-arrojado (Geworfenheit)", group: 0 },
        { text: "El abandono por un Dios ausente", group: 1 },
        { text: "La angustia nace sobre todo de la finitud", group: 0 },
        { text: "La angustia nace sobre todo de la responsabilidad", group: 1 },
        { text: "La nada es ante todo el ser-para-la-muerte", group: 0 },
        { text: "La nada es ante todo libertad radical", group: 1 },
      ],
      explain: "Comparten el vocabulario —arrojados, la nada, la angustia—, pero con otro acento. Heidegger: estar-arrojado, ser-para-la-muerte, angustia ante la finitud. Sartre: abandono por el Dios ausente, la nada como libertad radical, angustia ante la responsabilidad de elegir.",
    },
    {
      type: "info",
      continues: true,
      title: "Angustia, responsabilidad y elecciones sin inocencia",
      body: "Hay situaciones históricas en las que esa carga se vuelve extrema y no existen elecciones inocentes: el ejemplo de Sartre es el del joven que, bajo la ocupación, debe optar entre quedarse a cuidar a su madre enferma o sumarse a la Resistencia. Cualquiera de las dos opciones implica renunciar a algo irrenunciable, y aun así hay que elegir.",
    },
    {
      type: "match",
      question: "Uní cada término del existencialismo de Sartre con lo que nombra",
      pairs: [
        { left: "Existencia y esencia", right: "Primero existimos; luego, eligiendo, nos creamos" },
        { left: "En-sí", right: "Lo ya establecido e inerte: la facticidad, lo hecho" },
        { left: "Para-sí", right: "Lo fluido: la posibilidad de trascender hacia el futuro" },
        { left: "Mala fe", right: "Autoengaño para evadir la responsabilidad de elegir" },
        { left: "Decisionismo", right: "En toda situación hay que elegir; importa que elijamos" },
      ],
      explain: "Sin Dios, la existencia precede a la esencia: somos en-sí (lo hecho) y para-sí (la posibilidad de trascenderlo). Condenados a la libertad, debemos decidir (decisionismo) y asumir la responsabilidad; huir de ella tratándonos como cosa determinada es mala fe.",
    },
    {
      type: "info",
      title: "Camus y el absurdo",
      body: "**Albert Camus** (1913-1960) nace en la Argelia francesa, en una familia pobre; su padre muere en la Primera Guerra cuando Camus es apenas un bebé, y lo cría su madre, analfabeta y con problemas de audición, en Argel. Estudia filosofía en la Universidad de Argel y trabaja como periodista antes de instalarse en París. En 1942 publica, casi al mismo tiempo, la novela El extranjero y el ensayo El mito de Sísifo; en 1947, La peste; en 1951, El hombre rebelde. Recibe el premio Nobel de Literatura en 1957 y muere en 1960, en un accidente automovilístico.",
    },
    {
      type: "match",
      question: "Uní cada obra de Camus con su año de publicación",
      pairs: [
        { left: "El extranjero y El mito de Sísifo", right: "1942" },
        { left: "La peste", right: "1947" },
        { left: "El hombre rebelde", right: "1951" },
        { left: "Premio Nobel de Literatura", right: "1957" },
      ],
      explain: "En 1942 publica casi juntos El extranjero y El mito de Sísifo; en 1947, La peste; en 1951, El hombre rebelde. Recibe el Nobel en 1957 y muere en 1960, en un accidente automovilístico.",
    },
    {
      type: "info",
      continues: true,
      title: "Camus y el absurdo",
      body: "Camus rechazó explícitamente la etiqueta de \"existencialista\", y con razón: su punto de partida no es la libertad radical de Sartre, sino el **absurdo**. El mito de Sísifo abre con una frase célebre: \"no hay más que un problema filosófico verdaderamente serio: el suicidio\". El absurdo no está en el mundo, que es simplemente indiferente, ni en la conciencia humana, que reclama sentido; está en el **divorcio** entre esa demanda humana de claridad y el silencio irracional del mundo frente a ella.",
    },
    {
      type: "quiz",
      question: "Para Camus, ¿dónde está el absurdo?",
      options: [
        "En el choque entre la demanda de sentido y el mundo mudo",
        "En el mundo mismo, que es hostil y cruel por naturaleza",
        "En la conciencia humana, que es puramente irracional",
        "En la imposibilidad total de comunicarse con los demás",
      ],
      answer: 0,
      explain: "El absurdo no está en el mundo, que es simplemente indiferente, ni en la conciencia humana, que reclama sentido: está en el divorcio entre esa demanda humana de claridad y el silencio irracional del mundo frente a ella.",
    },
    {
      type: "info",
      continues: true,
      title: "Camus y el absurdo",
      body: "Frente a ese divorcio, Camus rechaza dos salidas que considera formas de evasión. Una es el suicidio literal, que elimina el problema eliminando a quien lo formula. La otra es el \"suicidio filosófico\": el salto de fe hacia un sentido trascendente —religioso o ideológico— que niega el absurdo en lugar de sostenerlo. La única actitud honesta es la **rebeldía**, vivir sin apelación a nada externo, con la mayor lucidez posible sobre la propia condición.",
    },
    {
      type: "info",
      continues: true,
      title: "Camus y el absurdo",
      body: "El mito que da título al ensayo es el de Sísifo, condenado por los dioses a empujar eternamente una piedra hasta la cima de una montaña para verla rodar de nuevo hacia abajo. Camus lo lee como el héroe del absurdo: consciente de la futilidad de su tarea, y sin embargo dueño de esa conciencia, que es lo único que los dioses no pueden quitarle. La frase final del ensayo resume la posición entera: \"hay que imaginar a Sísifo feliz\".",
    },
    {
      type: "quiz",
      question: "Frente al absurdo, ¿cuál es la única actitud honesta para Camus?",
      options: [
        "La rebeldía: vivir sin apelar a nada externo",
        "El suicidio, que elimina el problema de raíz",
        "El salto de fe hacia un sentido trascendente",
        "La resignación silenciosa ante lo inevitable",
      ],
      answer: 0,
      explain: "Camus rechaza el suicidio literal y el «suicidio filosófico» —el salto de fe que niega el absurdo—: la única actitud honesta es la rebeldía, vivir con la mayor lucidez posible. Así lee también a Sísifo, consciente y dueño de su tarea inútil: «hay que imaginar a Sísifo feliz».",
    },
    {
      type: "info",
      continues: true,
      title: "Camus y el absurdo",
      body: "En El hombre rebelde (1951), Camus da un paso más: la rebeldía frente al absurdo no autoriza cualquier cosa, al revés de lo que sugiere la fórmula de que si Dios ha muerto todo está permitido. Rebelarse es reconocer un límite que no debe cruzarse, y hacerlo en solidaridad con todos los que también se rebelan: \"me rebelo, luego existimos\". Camus dirige esa idea, sobre todo, contra las revoluciones del siglo XX que justifican el terror y el asesinato en nombre de una historia con sentido garantizado.",
    },
    {
      type: "info",
      continues: true,
      title: "Camus y el absurdo",
      body: "Esa crítica —dirigida, sin nombrarlo siempre así, contra la violencia revolucionaria soviética y su justificación marxista— provoca en 1952 la ruptura pública con Sartre, tras una reseña muy dura de El hombre rebelde publicada en Les Temps modernes. El intercambio de cartas abiertas entre ambos hace visible una fractura de fondo en la izquierda francesa de posguerra: cuánto silencio, o cuánta complicidad, tolerar frente a los campos soviéticos en nombre de la causa histórica.",
    },
    {
      type: "quiz",
      question: "¿Qué provoca la ruptura pública entre Camus y Sartre en 1952?",
      options: [
        "Una reseña muy dura a El hombre rebelde en su revista",
        "Una discusión personal por la autoría de un guion",
        "El rechazo de Camus a sumarse a la Resistencia",
        "Una disputa por el jurado del Premio Nobel",
      ],
      answer: 0,
      explain: "La crítica de Camus a la violencia revolucionaria en El hombre rebelde (1951) provoca, tras una reseña muy dura publicada en Les Temps modernes, la ruptura pública con Sartre en 1952: una fractura de fondo en la izquierda francesa de posguerra.",
    },
    {
      type: "info",
      title: "Cierre: el compromiso de posguerra",
      body: "Sartre había defendido, desde el primer número de Les Temps modernes en 1945, la **literatura comprometida** (littérature engagée): el pensador no puede retirarse a una torre de marfil, tiene que tomar posición en el mundo. Esa misma exigencia lo lleva, en las décadas siguientes, a usar su libertad radical para optar por el determinismo marxista y a callar durante años frente a los crímenes del estalinismo, lo que el historiador Tony Judt llamó su \"gran ausencia\".",
    },
    {
      type: "quiz",
      question: "¿Qué defiende Sartre con la «literatura comprometida» (engagée)?",
      options: [
        "Que el escritor debe involucrarse en el mundo",
        "Que el arte debe ser puro y ajeno a la política",
        "Que hay que retirarse a escribir en soledad",
        "Que la literatura debe imitar a la ciencia",
      ],
      answer: 0,
      explain: "Contra la torre de marfil y la cabaña en el bosque, Sartre sostiene que los pensadores deben tomar posición e involucrarse en su época. Lo proclama al fundar Les Temps modernes en 1945.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el compromiso de posguerra",
      body: "Camus, en cambio, mantiene una posición más incómoda para ambos bandos de la Guerra Fría cultural: crítico del comunismo soviético sin abrazar el liberalismo occidental sin reservas, y atravesado, en sus últimos años, por el desgarro de la guerra de independencia de Argelia, su tierra natal, frente a la cual no logra tomar el partido claro que muchos de sus contemporáneos exigían.",
    },
    {
      type: "match",
      question: "Uní cada término de Camus con lo que nombra",
      pairs: [
        { left: "Absurdo", right: "El divorcio entre la demanda de sentido y el mundo" },
        { left: "Suicidio filosófico", right: "El salto de fe que niega el absurdo en vez de sostenerlo" },
        { left: "Sísifo", right: "El héroe elegido, consciente y dueño de su tarea inútil" },
        { left: "El hombre rebelde", right: "El límite que no debe cruzarse, ni en nombre de la historia" },
      ],
      explain: "Camus rechaza las dos salidas del absurdo —el suicidio y el suicidio filosófico— y elige la rebeldía lúcida, encarnada en Sísifo. En El hombre rebelde lleva esa idea a la política: rebelarse es reconocer un límite que ninguna causa histórica autoriza a cruzar.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el compromiso de posguerra",
      body: "Esa fractura entre libertad radical y compromiso revolucionario queda abierta, sin resolver, para la generación siguiente de la izquierda europea. La **Escuela de Fráncfort** la retoma con otro vocabulario y otro diagnóstico, ya no centrado en la elección individual sino en el capitalismo tardío y en la razón instrumental que lo sostiene.",
    },
  ],
};
