export default {
  num: 9,
  transcript: 10,
  title: "El modernismo y la vanguardia",
  source: "https://www.youtube.com/watch?v=QqoKiAquWRg",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "El **modernismo** —tercer término de la tríada modernidad / modernización / modernismo— nombra la respuesta estética de las artes europeas a la experiencia de la modernidad entre, aproximadamente, 1857 y 1930. La fecha de arranque suele fijarse en la publicación de Las flores del mal de **Charles Baudelaire** en 1857, procesado ese mismo año por obscenidad; el cierre simbólico llega hacia 1930, cuando la generación de la vanguardia radical se disuelve entre el suicidio, el exilio y la adhesión a los totalitarismos que se consolidan en esa década.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Conviene distinguir dos olas dentro de ese arco largo. Una **primera ola**, desde fines del siglo XIX, que expresa la incertidumbre de la modernidad mediante un giro intenso hacia adentro, de sesgo freudiano. Y una **segunda ola**, la propiamente llamada **vanguardia** (avant-garde), que estalla tras la Primera Guerra Mundial y da un salto en otra dirección: casi una **Aufhebung** hegeliana de ese giro interior, un movimiento por encima del yo, hacia una temporalidad radicalmente experimental que quiere romper con el pasado entero.",
    },
    {
      type: "info",
      title: "El problema que hereda: el yo que Freud dejó inestable",
      body: "El psicoanálisis freudiano deja planteado un doble pesimismo que la estética modernista hereda directamente. Hay, primero, un **pesimismo social**: no existe un \"felices para siempre\", ninguna organización social resuelve del todo las contradicciones cableadas en la condición humana; se las puede mitigar, redirigir —Freud llama a esto lo \"inhibido en su fin\", la manera en que un impulso agresivo puede canalizarse, por ejemplo, hacia el deporte—, pero nunca eliminar.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el yo que Freud dejó inestable",
      body: "Hay, además, un **pesimismo epistemológico**, todavía más determinante para lo que sigue: el yo nunca puede conocerse del todo a sí mismo, porque sus partes más esenciales permanecen ocultas en el inconsciente. No hay transparencia última ni momento en que todo se ilumine, y lo verdadero no coincide necesariamente con lo racional: el sujeto está lleno de deseos e instintos que ninguna introspección agota. Ese pesimismo epistemológico anticipa un problema que retomará más adelante la fenomenología de Husserl, en cierto sentido el alter ego filosófico de Freud dentro de este período.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el yo que Freud dejó inestable",
      body: "El modernismo es la traducción estética de ese diagnóstico: si la modernidad es incertidumbre, lugares oscuros, cosas ocultas y no racionales, el arte que le corresponde no puede seguir describiendo un mundo estable visto desde afuera.",
    },
    {
      type: "quiz",
      question: "¿Cuál es, según la clase, el pesimismo más determinante que el modernismo hereda de Freud?",
      options: [
        "El epistemológico: el yo nunca se conoce del todo a sí mismo",
        "El social: ninguna organización social resuelve las contradicciones",
        "El económico: ninguna sociedad logra eliminar la pobreza",
        "El religioso: Dios ya no puede ofrecer ningún consuelo",
      ],
      answer: 0,
      explain: "El pesimismo social dice que ninguna organización resuelve del todo las contradicciones humanas. Pero el epistemológico es más determinante: el yo no puede conocerse a sí mismo porque sus partes esenciales están en el inconsciente.",
    },
    {
      type: "info",
      title: "Baudelaire y la crisis de la representación",
      body: "La primera ola se remonta a Baudelaire, que rechaza la idea de que el arte deba representar sólo lo bello y lo bueno: para él, el arte tiene que abrazar también **lo feo, lo malo, lo obsceno, lo erótico**, el lado oscuro de la experiencia. Ese giro hacia adentro implica apropiarse de la propia subjetividad y admitir que no siempre es algo agradable de mirar.",
    },
    {
      type: "info",
      continues: true,
      title: "Baudelaire y la crisis de la representación",
      body: "El crítico **Pericles Lewis** describió este momento como una **crisis de la representación**: una crisis del arte y la literatura frente a la pregunta de cómo representar el mundo. ¿Debe el arte funcionar como un espejo o una cámara, mostrando el mundo objetivamente, en su mejor versión, como un jardín de flores? La primera ola responde que no necesariamente: quizás haya que representar cosas menos claras y menos amables, o representar cómo se ven las cosas **desde adentro**, que no es lo mismo que representarlas objetivamente.",
    },
    {
      type: "quiz",
      question: "Según Pericles Lewis, ¿qué crisis abre Baudelaire en el arte y la literatura?",
      options: [
        "Una crisis de cómo representar el mundo",
        "Una crisis del verso rimado frente al verso libre",
        "Una crisis del mecenazgo aristocrático del arte",
        "Una crisis de la censura estatal sobre la prensa",
      ],
      answer: 0,
      explain: "Lewis llama crisis de la representación a la pregunta de si el arte debe ser un espejo objetivo del mundo o mostrar cómo se ven las cosas desde adentro, subjetivamente: Baudelaire opta por lo segundo.",
    },
    {
      type: "info",
      title: "Temas: el alma desnuda, la alienación",
      body: "El positivismo utilitario —la misma crítica a la Ilustración que atraviesa el curso— había **drenado el color** del mundo: su cálculo constante lo había vuelto frío y uniforme. Al girar hacia adentro, la primera ola encuentra que las cosas son oscuras: hay mucho abatimiento metafísico, mucho de lo que Nietzsche llama la **búsqueda de Dios** —la búsqueda de un dios que nunca se encuentra, algo que se anhela y no está—, que se superpone con la **Sehnsucht** romántica, la nostalgia por lo que nunca llegó a ser.",
    },
    {
      type: "info",
      continues: true,
      title: "Temas: el alma desnuda, la alienación",
      body: "Aparece la idea del **alma desnuda**, llena de instintos irracionales y pasiones elementales; la obsesión con la alienación del individuo, con la desintegración del orden social, con la sensación de quedar por fuera de todo lo que tiene sentido; temas de colapso, apocalipsis, desesperación; la **ausencia de héroe**, la incapacidad de actuar o el miedo mismo a actuar. Hay una continuidad clara con el Romanticismo, pero sin su glorificación total de la pasión: si el Romanticismo todavía celebraba el desborde, la primera ola modernista lo experimenta como síntoma. Freud es, en este sentido preciso, el gurú intelectual del modernismo.",
    },
    {
      type: "info",
      title: "Kafka: La metamorfosis",
      body: "El texto que mejor cristaliza esta primera ola es La metamorfosis, de **Franz Kafka** (Praga, 1883-1924), figura asociada de manera indisoluble a Praga, ciudad del Imperio austrohúngaro y luego capital de la nueva Checoslovaquia. Kafka pertenece a un círculo de escritores judíos germanoparlantes de esa ciudad —entre ellos Max Brod y Franz Werfel—, a menudo descriptos como expresionistas de Praga, profetas de la alienación y la marginalidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "Kafka expresó como pocos qué significa sentirse alienado de todas las identidades disponibles a la vez: judío germanoparlante en la capital de un nuevo Estado checoslovaco, hablante de alemán que no se siente alemán, ciudadano checoslovaco que no se siente checo, judío que no está seguro de sentirse judío ni de creer en Dios. En una entrada de su diario, del 6 de enero de 1914, escribe: \"¿Qué tengo yo en común con los judíos? Apenas tengo algo en común conmigo mismo, y debería quedarme muy quieto en un rincón, contento de poder respirar\".",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "La metamorfosis, escrita en 1912 y publicada en 1915 —contemporánea, por lo tanto, de las Lecciones introductorias al psicoanálisis de Freud—, abre con una de las líneas más citadas de la literatura universal:",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "Cuando Gregor Samsa despertó una mañana de sueños intranquilos, se encontró en su cama transformado en un insecto monstruoso.",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "Despertar de sueños intranquilos —un gesto muy freudiano— y hallarse **irreconocible**, convertido en una monstruosidad, plantea preguntas que van directo al corazón del pesimismo epistemológico: ¿seguís siendo vos mismo? ¿Existe el yo si no hay un yo estable al cual referirlo? La subjetividad radical que reivindica la primera ola no implica, entonces, una subjetividad estable: al contrario, puede ser la forma más radicalmente inestable de subjetividad que exista.",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "Hay, además, un diálogo implícito con el marxismo en la novela: ¿se basan la identidad y el valor humanos en el **trabajo**, en la producción? ¿Qué le queda a Gregor cuando ya no puede ir a trabajar? La comparación entre la alienación kafkiana y la marxista es instructiva: en Marx la alienación es **estructural**, producida por la organización del trabajo en la línea de montaje; en Kafka es más bien **psicológica**, interna al modo en que el sujeto se experimenta a sí mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "Nunca se sabe con certeza si el insecto sigue siendo Gregor hasta el final; y, en cualquier caso, todos los personajes de la novela terminan absolutamente solos.",
    },
    {
      type: "info",
      continues: true,
      title: "Kafka: La metamorfosis",
      body: "En conjunto, la primera ola constituye un **esteticismo**: momentos de repliegue hacia el \"arte por el arte\", el mundo visto desde adentro, de manera subjetiva, con licencia plena para explorar cómo se ve la existencia desde ese lugar.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la alienación de Kafka de la de Marx?",
      options: [
        "En Marx es estructural; en Kafka, psicológica",
        "En Kafka es económica; en Marx, espiritual",
        "Son idénticas: ambas nacen de la línea de montaje",
        "En Kafka no hay alienación, sólo humor absurdo",
      ],
      answer: 0,
      explain: "Para Marx la alienación es estructural: la organización del trabajo en la línea de montaje aliena al obrero. En Kafka es psicológica: Gregor ya no puede trabajar y deja de reconocerse a sí mismo.",
    },
    {
      type: "info",
      title: "Fundamentos de la vanguardia: el estructuralismo lingüístico",
      body: "Si el modernismo arranca a mediados o fines del siglo XIX, la **Primera Guerra Mundial** marca un corte que inaugura el alto modernismo, o vanguardia propiamente dicha. Hay ahí un doble movimiento: primero el giro hacia adentro de la primera ola, hacia la subjetividad radical; luego una **huida de esa misma subjetividad**, que no vuelve al punto de partida sino que se instala en un territorio completamente distinto.",
    },
    {
      type: "info",
      continues: true,
      title: "Fundamentos de la vanguardia: el estructuralismo lingüístico",
      body: "Para entender la relación de la vanguardia con el lenguaje hace falta pasar por el **estructuralismo lingüístico** de **Ferdinand de Saussure**, que dicta sus cursos en Ginebra entre 1907 y 1911; el propio Saussure no llegó a escribir el libro que lo volvería célebre —sus alumnos tomaron apuntes de las clases y, tras su muerte, los editaron como el Curso de lingüística general (1916)—.",
    },
    {
      type: "info",
      continues: true,
      title: "Fundamentos de la vanguardia: el estructuralismo lingüístico",
      body: "De esas clases surgen cuatro ideas, en apariencia simples pero de consecuencias enormes: la lengua es **forma**, no sustancia; la lengua es **convención**, y todo significado es relacional, existe sólo dentro de un sistema dado; y todo estado de una lengua tiene un carácter **fortuito**, producto de una arbitrariedad histórica y no de un diseño deliberado —el esperanto es la excepción que confirma la regla—.",
    },
    {
      type: "info",
      continues: true,
      title: "Fundamentos de la vanguardia: el estructuralismo lingüístico",
      body: "La cuarta idea es la más determinante para lo que sigue: el **signo lingüístico** se compone de un significante, el sonido o la marca gráfica, y un significado, el concepto al que remite, unidos sólo por una relación **arbitraria** y sostenida por el hábito colectivo. \"Perro\" sigue nombrando al perro simplemente porque no es \"gato\" ni \"cerro\", no porque exista una conexión natural entre el sonido y la cosa.",
    },
    {
      type: "quiz",
      question: "Según Saussure, ¿por qué la palabra «perro» significa lo que significa?",
      options: [
        "Porque es arbitrario: se define por contraste con otros signos",
        "Porque sus sonidos se parecen naturalmente al animal",
        "Porque Dios o la biología fijaron esa correspondencia",
        "Porque su significado es idéntico en todas las lenguas",
      ],
      answer: 0,
      explain: "La relación entre significante y significado es arbitraria: nada en los sonidos obliga a referir esa cosa. El signo se sostiene por convención y por contraste con los demás signos del sistema.",
    },
    {
      type: "info",
      title: "La liberación de la palabra",
      body: "El estructuralismo permite pensar las palabras **desprendidas** de las cosas a las que refieren, y ese es el gran salto, la gran apertura que va a explotar la vanguardia: **desarticular significante y significado**. Si la relación entre ambos es arbitraria, nada impide manipular el significante como si fuera autónomo.",
    },
    {
      type: "info",
      continues: true,
      title: "La liberación de la palabra",
      body: "**Filippo Tommaso Marinetti** publica el manifiesto fundacional del futurismo italiano en el diario parisino Le Figaro el 20 de febrero de 1909, y en un manifiesto posterior, de 1913, dedicado a las \"**palabras en libertad**\" (parole in libertà), propone imágenes y analogías construidas con palabras sin trabas, sin sintaxis ni puntuación: eliminar toda restricción gramatical, jugar libremente con la tipografía y la ortografía.",
    },
    {
      type: "info",
      continues: true,
      title: "La liberación de la palabra",
      body: "Los **manifiestos** son, de hecho, uno de los grandes géneros propios de la vanguardia: llegan a producirse, en conjunto, muchos más manifiestos que obras. **Guillaume Apollinaire**, en Francia, hacia los años de la Primera Guerra, experimenta en la misma dirección con la tipografía en sus Caligramas (1918), borrando la frontera entre lo visual y lo verbal al construir diseños y figuras con las propias palabras del poema.",
    },
    {
      type: "info",
      title: "El corte radical: la palabra \"como tal\"",
      body: "La ruptura filosóficamente más radical llega con los **futuristas rusos** —**Velimir Jlébnikov** y **Alekséi Kruchónij**—, que en 1913 publican el manifiesto La palabra como tal (slovo kak takovoe). No se trata sólo de liberar la palabra de la gramática y la puntuación, sino de **cortar la conexión entre la palabra y su referente**, de modo que las palabras se vuelvan cosas en sí mismas, juguetes liberados con los que se puede hacer lo que se quiera.",
    },
    {
      type: "info",
      continues: true,
      title: "El corte radical: la palabra \"como tal\"",
      body: "Es una fuente inmensa de liberación: ahora la **forma lo es todo**, porque se ha divorciado la palabra de la cosa, y se invierte la jerarquía tradicional entre forma y contenido. El futurista ucraniano **Mijáil Semenko** declara en 1914: \"quiero palabras siempre nuevas cada día\".",
    },
    {
      type: "classify",
      question: "¿Cada gesto corresponde a la liberación de la palabra o al corte radical?",
      groups: ["Liberación de la palabra", "Corte radical"],
      items: [
        { text: "Marinetti elimina sintaxis y puntuación en sus manifiestos", group: 0 },
        { text: "Apollinaire dibuja figuras con las palabras del poema", group: 0 },
        { text: "Jlébnikov y Kruchónij cortan la palabra de su referente", group: 1 },
        { text: "Las palabras se vuelven cosas en sí mismas", group: 1 },
        { text: "Semenko pide palabras siempre nuevas cada día", group: 1 },
      ],
      explain: "Marinetti y Apollinaire liberan la palabra de la gramática y la disposición tipográfica tradicional. Jlébnikov y Kruchónij van más lejos: cortan la conexión entre la palabra y lo que nombra, y la vuelven una cosa en sí misma.",
    },
    {
      type: "info",
      title: "El formalismo ruso",
      body: "En 1915 se funda en Moscú el Círculo Lingüístico de Moscú, y al año siguiente, en Petrogrado, la sociedad conocida por su sigla **OPOYAZ**, en la que participan **Roman Jakobson** —uno de los teóricos estructuralistas más importantes del siglo—, **Víktor Shklovski** y **Ósip Brik**. Ambos grupos se dedican al estudio del **lenguaje poético** y su naturaleza autónoma, poniendo entre paréntesis —un procedimiento que será también central para Husserl— la referencia, para observar cómo funciona el lenguaje en sí mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El formalismo ruso",
      body: "El lenguaje poético es, para ellos, un lenguaje especial, distinto del cotidiano, que llama la atención sobre sí mismo en tanto lenguaje: sobre el significante, no sobre el significado. Es la **puesta al desnudo del procedimiento**, un lenguaje que se anuncia como significante en vez de pretender ser una cámara transparente sobre el mundo.",
    },
    {
      type: "info",
      title: "Ostranénie: extrañamiento",
      body: "El concepto más influyente de Shklovski es la **ostranénie**, que suele traducirse como **extrañamiento** o **desfamiliarización**. El lenguaje poético busca hacer que la cosa descrita **parezca extraña**, usando el lenguaje de un modo deliberadamente no transparente. Funciona como el **pharmakos** griego, a la vez veneno y remedio:",
    },
    {
      type: "info",
      continues: true,
      title: "Ostranénie: extrañamiento",
      body: "la enfermedad, para Shklovski, es que se transita el mundo **sonámbulo**, reconociendo las cosas sin verlas de verdad, de tan acostumbrados que se está a que sean lo que son —la taza, la lapicera, el perro, el árbol—. El lenguaje poético debe volverlas raras para despertar la percepción y permitir verlas de verdad. En El arte como procedimiento (1917), Shklovski escribe:",
    },
    {
      type: "info",
      continues: true,
      title: "Ostranénie: extrañamiento",
      body: "Y así, sin que se le rinda cuentas a nada, la vida se desvanece en la nada. La automatización devora las cosas, la ropa, los muebles, a nuestras esposas, el miedo a la guerra… Para devolver la sensación a nuestros miembros, para hacernos sentir los objetos, para hacer que la piedra se sienta pétrea, se le ha dado al hombre la herramienta del arte.",
    },
    {
      type: "info",
      continues: true,
      title: "Ostranénie: extrañamiento",
      body: "Esta idea de sacudir la percepción hacia un momento de claridad conecta con la función que Bergson atribuía a la risa como ruptura del automatismo, y anticipa el procedimiento de puesta entre paréntesis que Husserl elaborará para fundar la fenomenología.",
    },
    {
      type: "quiz",
      question: "¿Para qué sirve la ostranénie (extrañamiento) de Shklovski?",
      options: [
        "Para volver extrañas las cosas y verlas de verdad",
        "Para que la poesía sea más fácil y transparente",
        "Para eliminar por completo el lenguaje del arte",
        "Para copiar la realidad con la mayor exactitud posible",
      ],
      answer: 0,
      explain: "Vivimos sonámbulos, automatizando la percepción. El lenguaje poético usa las palabras de modo no transparente para volver raras las cosas y devolvernos la sensación: hacer que la piedra se sienta pétrea.",
    },
    {
      type: "info",
      title: "Rasgos generales de la vanguardia",
      body: "La vanguardia produce versos que no parecen referir a nada fuera de sí mismos, textos deliberadamente **autorreferenciales**, un rechazo de las distinciones disciplinarias tradicionales, del lirismo y del sentimentalismo, y una dosis considerable de narcisismo y autocomplacencia generacional: sus protagonistas suelen ser muy jóvenes, y comparten un sentido extraordinario, casi desmedido, de la propia importancia histórica.",
    },
    {
      type: "info",
      continues: true,
      title: "Rasgos generales de la vanguardia",
      body: "Hay en el movimiento **audacia**, juventud y rebelión: rechazo de toda regla vigente —de gramática, de puntuación, de arte, de cortesía, de convención social—, urgencia de escándalo y provocación, y un sentido agudísimo del tiempo que corre hacia adelante, con ecos del mismo espíritu que anima al leninismo. Es una batalla contra lo viejo y lo acartonado, contra la cultura burguesa, entendida al principio más en sentido rousseauniano —superficial, artificial, ostentosa, conformista— que estrictamente marxista.",
    },
    {
      type: "info",
      continues: true,
      title: "Rasgos generales de la vanguardia",
      body: "Un manifiesto futurista ruso de 1912 propone \"arrojar a Pushkin, Dostoievski, Tolstói, etcétera, por la borda del barco de vapor de la modernidad\": no se trataba de cancelar el pasado en el sentido contemporáneo del término, sino de cancelarlo para inaugurar deliberadamente el futuro. La vida es el aquí y ahora; todo lo que ya pasó es material de desecho.",
    },
    {
      type: "info",
      continues: true,
      title: "Rasgos generales de la vanguardia",
      body: "Leen a Nietzsche y toman la muerte de Dios lo más literalmente posible: si algo cae, hay que empujarlo, y la vanguardia se propone precisamente eso, empujar lo que ya está cayendo. Todo ha sido volado por el aire, todo es posible: una vertiginosa infinitud de posibilidades, sostenida por una glorificación explícita de la nueva generación frente a la anterior.",
    },
    {
      type: "quiz",
      question: "¿Qué sentido tiene, para la vanguardia, la consigna de arrojar a los clásicos por la borda?",
      options: [
        "No busca cancelar el pasado, sino inaugurar el futuro",
        "Busca destruir físicamente las obras del pasado",
        "Es sólo una broma sin ninguna intención real",
        "Busca que el Estado prohíba enseñar a los clásicos",
      ],
      answer: 0,
      explain: "El manifiesto futurista de 1912 propone arrojar a Pushkin, Dostoievski y Tolstói por la borda: no se trata de cancelar el pasado en sentido contemporáneo, sino de dejarlo atrás para inaugurar deliberadamente el futuro.",
    },
    {
      type: "info",
      title: "Del arte como representación al arte como transformación",
      body: "Aquí se produce el giro más radical en la cuestión de la representación. La primera ola sostenía que el arte debía representar la vida de manera subjetiva, no objetiva. La vanguardia va más lejos: quizás el arte no deba representar la vida en absoluto. El arte deja de ser un espejo de la vida para convertirse en un **martillo** con el cual crearla.",
    },
    {
      type: "info",
      continues: true,
      title: "Del arte como representación al arte como transformación",
      body: "Se pasa así del **arte como representación** al **arte como transformación**: cortada del todo la conexión entre significante y significado, ya no se trata de representar sino de **crear** desde cero. Ese movimiento llevará, con el tiempo, a una suerte de caída libre, porque el gesto que lo hace posible corta al mismo tiempo el suelo bajo los pies de cualquier obra.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de la primera ola o de la vanguardia?",
      groups: ["Primera ola", "Vanguardia"],
      items: [
        { text: "Giro hacia adentro, a la subjetividad (Baudelaire, Kafka)", group: 0 },
        { text: "Freud es el gurú; el alma desnuda y la alienación", group: 0 },
        { text: "El arte representa el mundo desde adentro, no objetivamente", group: 0 },
        { text: "La palabra se corta de su referente y se vuelve cosa", group: 1 },
        { text: "El arte ya no representa: es un martillo para crear vida", group: 1 },
        { text: "Salto por encima del yo, hacia una temporalidad experimental", group: 1 },
      ],
      explain: "La primera ola es un esteticismo del giro interior: mostrar el mundo subjetivamente, en clave freudiana. La vanguardia huye de la subjetividad y rompe el vínculo palabra-cosa: la forma lo es todo y el arte pasa de representar a transformar.",
    },
    {
      type: "info",
      title: "El internacionalismo de la vanguardia",
      body: "Ese internacionalismo no era sólo un hecho de circunstancia, sino un programa consciente. A fines del siglo XIX y principios del XX existía un **cosmopolitismo imperial tardío**: los imperios austrohúngaro y zarista eran espacios profundamente multiétnicos y multilingües, donde una misma persona podía moverse entre varias lenguas y culturas sin cruzar ninguna frontera estatal.",
    },
    {
      type: "info",
      continues: true,
      title: "El internacionalismo de la vanguardia",
      body: "En la Primera Guerra Mundial caen cuatro grandes imperios —el zarista, el austrohúngaro, el otomano y el alemán—, y en la conferencia de paz de Versalles, bajo el impulso del principio de autodeterminación de Woodrow Wilson, el mapa europeo se rehace en Estados nacionales donde, en teoría, las fronteras nacionales y las estatales deberían coincidir. La superposición nunca es perfecta —Checoslovaquia no es sólo de checos y eslovacos, Rumania no es sólo de rumanos—, pero el principio se impone, y con él la exigencia de pasaportes y fronteras reconocidas que antes no hacían falta.",
    },
    {
      type: "info",
      continues: true,
      title: "El internacionalismo de la vanguardia",
      body: "Frente a ese nuevo orden de fronteras, la vanguardia opone un **internacionalismo agresivo y autoconsciente**, empeñado en cruzarlas y violarlas. Shklovski escribe que el arte siempre fue libre respecto de la vida, y que su color nunca reflejó el color de la bandera que ondea sobre la fortaleza de la ciudad. Semenko declara sentirse sin límites, y publica un artículo explicando por qué el nacionalismo ucraniano es malo para la propia cultura ucraniana.",
    },
    {
      type: "info",
      continues: true,
      title: "El internacionalismo de la vanguardia",
      body: "En julio de 1921 los futuristas polacos —Jasieński, Stern, Wat, todos ellos de apenas diecinueve o veinte años— le escriben a Maiakovski proponiendo una gran revista internacional de poesía futurista en todas las lenguas, con colaboradores italianos, franceses, alemanes y españoles: todos aspiran a ser internacionales, a cruzar fronteras, en sintonía con su culto a la juventud y con la sensación compartida de que las reglas anteriores ya no rigen.",
    },
    {
      type: "quiz",
      question: "¿Cómo responde la vanguardia al nuevo orden de fronteras nacionales de posguerra?",
      options: [
        "Con un internacionalismo agresivo, empeñado en cruzarlas",
        "Aceptando el principio de autodeterminación de Wilson",
        "Replegándose en el idioma y la tradición de cada nación",
        "Pidiendo pasaportes únicos para todos los artistas",
      ],
      answer: 0,
      explain: "Tras Versalles se imponen fronteras y pasaportes nuevos. Frente a eso, la vanguardia opone un internacionalismo agresivo y autoconsciente: Shklovski dice que el arte nunca reflejó el color de ninguna bandera.",
    },
    {
      type: "info",
      title: "Futurismo italiano",
      body: "Fundado por Marinetti con el manifiesto de 1909, el futurismo italiano está más ligado a la modernización material, la tecnología, la velocidad, la vitalidad física y la agresividad: Marinetti llega a sostener que la guerra es \"la única higiene del mundo\". En 1914 visita a los futuristas rusos y el encuentro no funciona: los rusos estaban mucho más absortos en el lenguaje y en la palabra autoválida que en la exaltación de la máquina.",
    },
    {
      type: "info",
      title: "Futurismo ruso y polaco",
      body: "El futurismo ruso, con Jlébnikov y Kruchónij a la cabeza, se concentra en la experimentación radical con la palabra ya descrita. El futurismo polaco, inspirado en el ruso, combina esa misma fascinación por el lenguaje con momentos de entusiasmo tecnológico; en el almanaque Gga declaran: \"destrucción de las reglas que atan la creación, la virtud de la torpeza, libertad de la forma gramatical, la ortografía y la puntuación. Independientemente del creador, las palabras tienen su propio peso, sonido, color, su propio diseño; ocupan lugar en el espacio\". Es, de nuevo, la palabra hecha cosa.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del futurismo italiano o del futurismo ruso y polaco?",
      groups: ["Futurismo italiano", "Futurismo ruso y polaco"],
      items: [
        { text: "Exalta la tecnología, la velocidad y la agresividad", group: 0 },
        { text: "Marinetti llama a la guerra la única higiene del mundo", group: 0 },
        { text: "Termina sumándose a Mussolini y al fascismo", group: 0 },
        { text: "Se concentra en la experimentación radical con la palabra", group: 1 },
        { text: "Jlébnikov y Kruchónij encabezan la búsqueda", group: 1 },
      ],
      explain: "El futurismo italiano de Marinetti exalta la máquina, la velocidad y la guerra, y termina en el fascismo. El futurismo ruso y polaco, con Jlébnikov y Kruchónij, se concentra en la palabra misma como material de trabajo.",
    },
    {
      type: "info",
      title: "Cubismo",
      body: "En París, entre 1907 y 1914, **Pablo Picasso** y **Georges Braque** desarrollan el **cubismo**, la versión pictórica más influyente de esta misma crisis de la representación. Las señoritas de Avignon (1907), de Picasso, con sus figuras descompuestas en planos angulosos y su cita directa de máscaras africanas, suele señalarse como el punto de partida.",
    },
    {
      type: "info",
      continues: true,
      title: "Cubismo",
      body: "En su fase **analítica** (hacia 1910-1912) el cubismo fragmenta el objeto en facetas geométricas vistas simultáneamente desde varios ángulos, como si el ojo pudiera rodear la cosa en el mismo instante en que la mira de frente; en su fase **sintética** (desde 1912) incorpora colage de materiales reales —papel de diario, etiquetas— junto a la pintura. El gesto es paralelo al de los futuristas rusos con la palabra: así como estos separan el significante del significado, el cubismo separa la superficie pictórica de cualquier punto de vista único y estable.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue a la fase analítica de la fase sintética del cubismo?",
      options: [
        "La sintética incorpora collage de materiales reales",
        "La analítica ya usa recortes de diario y etiquetas",
        "La sintética vuelve a la perspectiva única y tradicional",
        "La analítica abandona por completo la figura humana",
      ],
      answer: 0,
      explain: "En la fase analítica (1910-1912) el cubismo fragmenta el objeto en facetas geométricas vistas desde varios ángulos; en la sintética (desde 1912) incorpora collage de materiales reales junto a la pintura.",
    },
    {
      type: "info",
      title: "Expresionismo alemán",
      body: "El **expresionismo** se organiza en Alemania alrededor de dos grupos sucesivos: **Die Brücke** (\"el puente\"), fundado en Dresde en 1905 por Ernst Ludwig Kirchner y otros, y **Der Blaue Reiter** (\"el jinete azul\"), fundado en Múnich en 1911 por Vasili Kandinski y Franz Marc.",
    },
    {
      type: "info",
      continues: true,
      title: "Expresionismo alemán",
      body: "Comparten con la primera ola modernista el interés por el alma desnuda y la angustia, pero lo llevan a la superficie del cuadro mediante colores violentos, líneas distorsionadas y figuras deformadas que expresan un estado interior antes que describir un objeto exterior. El círculo praguense de Kafka, Brod y Werfel, ya mencionado, comparte con este expresionismo alemán el énfasis en la alienación, aunque trabaje sobre todo en prosa y no en pintura.",
    },
    {
      type: "classify",
      question: "¿Cada dato corresponde a Die Brücke o a Der Blaue Reiter?",
      groups: ["Die Brücke", "Der Blaue Reiter"],
      items: [
        { text: "Se funda en Dresde en 1905", group: 0 },
        { text: "Kirchner es una de sus figuras fundadoras", group: 0 },
        { text: "Se funda en Múnich en 1911", group: 1 },
        { text: "Kandinski y Marc lo fundan", group: 1 },
      ],
      explain: "El expresionismo alemán se organiza en dos grupos sucesivos: Die Brücke, fundado en Dresde en 1905 por Kirchner, y Der Blaue Reiter, fundado en Múnich en 1911 por Kandinski y Marc.",
    },
    {
      type: "info",
      title: "Constructivismo",
      body: "El **constructivismo** ruso, con **Vladímir Tatlin** como una de sus figuras fundadoras —su proyecto de Monumento a la Tercera Internacional (1919-1920) es su emblema más citado—, apuesta por la utilidad: borra la frontera entre arte e ingeniería, entre arte y diseño, entre arte y vida, y concibe la obra como creación directa de las condiciones materiales de la existencia, en sintonía con el proyecto revolucionario bolchevique.",
    },
    {
      type: "info",
      title: "Dadaísmo",
      body: "El **dadaísmo** nace en Zúrich en 1916, en el Cabaret Voltaire fundado por Hugo Ball, con Tristan Tzara entre sus protagonistas más visibles. La estudiosa **Katerina Clark** lo definió como la \"**reificación de la contingencia**\": nada está predeterminado, cualquier cosa puede pasar en cualquier momento, y el movimiento convierte esa misma imprevisibilidad en una cosa exhibible.",
    },
    {
      type: "info",
      continues: true,
      title: "Dadaísmo",
      body: "Tzara —judío rumano instalado en la Suiza neutral durante la guerra— escribe que \"Dada nace en medio de la mezcla cosmopolita de Dios y el burdel\": una rebelión estética sin sistema, pura libertad que no apunta a nada fuera de sí misma. \"Estoy contra los sistemas —escribe—; el sistema más aceptable es, en principio, ninguno.\"",
    },
    {
      type: "info",
      title: "Surrealismo",
      body: "El **surrealismo** nace formalmente con el Manifiesto del surrealismo que **André Breton** publica en París en 1924, y vuelve explícitamente a lo freudiano: la asociación libre y el **automatismo psíquico**, exento de toda preocupación estética o moral, se proponen como método de acceso directo al inconsciente. **Max Ernst** define el collage surrealista como \"el acoplamiento de dos realidades que en apariencia no pueden acoplarse, en un plano que no les es propio\": la operación consiste, precisamente, en juntar elementos que no van juntos y dejar que de esa fricción surja un sentido nuevo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Breton al método surrealista de acceso directo al inconsciente, sin control consciente?",
      answers: ["automatismo psíquico", "automatismo"],
      explain: "El Manifiesto del surrealismo (1924) propone la asociación libre y el automatismo psíquico, exento de toda preocupación estética o moral, como vía directa al inconsciente que ya había descripto Freud.",
    },
    {
      type: "info",
      title: "El final de la vanguardia",
      body: "En síntesis: Marinetti y los futuristas italianos se desplazan hacia la **derecha** y terminan sumándose a Mussolini y al fascismo; la mayoría de los demás grupos —en especial los rusos— se desplazan hacia la **izquierda** y se suman a la Revolución Bolchevique. El mismo gesto de ruptura total con el pasado admite, se ve entonces, más de un destino político.",
    },
    {
      type: "info",
      continues: true,
      title: "El final de la vanguardia",
      body: "El nihilismo radical y la contingencia radical —la sensación de que no hay restricción alguna y todo es posible— resultan, con el tiempo, **existencialmente insoportables**. Es una experiencia emocionante mientras dura, como una caída libre, como esas atracciones que dejan caer al vacío: se salta, todo parece posible, pero falta por completo el suelo. Del momento vertiginoso y extático en que se cruza del arte-representación al arte-transformación no queda nada que sostenga después.",
    },
    {
      type: "info",
      continues: true,
      title: "El final de la vanguardia",
      body: "Uno de los futuristas polacos describe la revolución como \"una trágica dolorosa, un glorioso incendio en el que hay que quemarse, descender a la barbarie para descubrir en uno mismo la simple alegría de vivir… Dos caminos llevan de la negación al estado real de las cosas: el camino hacia el pasado y el camino hacia el futuro; al catolicismo o al comunismo. Nuestra libertad está en la libertad de elegir, nada más.\"",
    },
    {
      type: "info",
      continues: true,
      title: "El final de la vanguardia",
      body: "En 1927 **Maiakovski** —la pasarela entre la vanguardia y la Revolución Comunista, sobre todo para los futuristas polacos— los visita por fin en Varsovia: alto, deslumbrante, con una voz que hacía temblar las salas —\"una locomotora viva que habla\", \"el cielo desgarrado por un rayo\", escriben quienes lo vieron—. Ellos quedan extáticos, convencidos de que asisten al comienzo de un mundo nuevo. Lo trágico es que asisten, en realidad, al comienzo del fin.",
    },
    {
      type: "info",
      continues: true,
      title: "El final de la vanguardia",
      body: "Tres años después, en la primavera de 1930, llega desde Moscú un telegrama: \"Esta mañana Volodia [Maiakovski] se quitó la vida\". Deja una nota que dice: \"Lily, ámame. La barca del amor se estrelló contra lo cotidiano\". Ese salto hacia el \"todo es posible\" termina resultando existencialmente insoportable, y termina mal para buena parte de esta generación. Jakobson, años después, en su ensayo Sobre una generación que dilapidó a sus poetas (1930), describe a Marinetti como \"un hombre absolutamente inadecuado para la vida\".",
    },
    {
      type: "quiz",
      question: "¿Qué destino político distinto toman el futurismo italiano y la mayoría de los grupos rusos?",
      options: [
        "El italiano va a la derecha, los rusos a la izquierda",
        "Ambos terminan sumándose al mismo bando fascista",
        "Ambos rechazan cualquier compromiso político",
        "El italiano va a la izquierda, los rusos a la derecha",
      ],
      answer: 0,
      explain: "Marinetti y los futuristas italianos se suman a Mussolini y al fascismo; la mayoría de los grupos rusos se suman a la Revolución Bolchevique. El mismo gesto de ruptura admite más de un destino político.",
    },
    {
      type: "info",
      title: "Herencia",
      body: "La vanguardia deja, sobre todo, una lección incómoda: el gesto de romper con toda forma heredada —de representación, de sintaxis, de convención social— no desemboca por sí solo en ninguna dirección política determinada. El mismo impulso de cancelar el pasado para inaugurar un futuro absoluto alimenta tanto el fascismo italiano como el comunismo soviético, según qué núcleo de sus protagonistas lo tome en sus manos.",
    },
    {
      type: "match",
      question: "Uní cada movimiento de vanguardia con su rasgo",
      pairs: [
        { left: "Dadaísmo", right: "La reificación de la contingencia (Tzara)" },
        { left: "Surrealismo", right: "Automatismo psíquico, vuelta a lo freudiano" },
        { left: "Futurismo italiano", right: "Tecnología y agresión; termina en el fascismo" },
        { left: "Constructivismo", right: "Borra la frontera entre arte e ingeniería" },
        { left: "Formalismo ruso", right: "La ostranénie: volver extrañas las cosas" },
      ],
      explain: "La vanguardia es plural: el dadaísmo hace de la contingencia una cosa; el surrealismo vuelve a Freud con el automatismo psíquico; el futurismo italiano exalta la máquina y deriva al fascismo; el constructivismo funde arte y vida; el formalismo teoriza el extrañamiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "El vértigo de la libertad total, una vez agotado como experiencia estética, busca casi siempre algún sistema que lo contenga, y esa búsqueda de contención es, en buena medida, la historia política de Europa en las décadas siguientes.",
    },
  ],
};
