export default {
  num: 10,
  transcript: 11,
  title: "La fenomenología",
  source: "https://www.youtube.com/watch?v=8OCDFEn_hRE",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Edmund Husserl** (1859-1938) nace en Prossnitz (hoy Prostějov), Moravia, en el Imperio austrohúngaro, en una familia judía germanoparlante que más tarde abandona el judaísmo. A diferencia de otros pensadores judíos de su generación —Marx, Kafka, Freud—, sobre cuya relación con el judaísmo existe una enorme literatura, sobre Husserl casi no hay nada escrito en ese registro biográfico, lo cual es en sí mismo un dato: indica cuánto de su vida se disolvió por completo en la filosofía, hasta el punto de que quienes intentaron reconstruirla como personaje encuentran muy poco por fuera del trabajo intelectual.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Se forma primero en matemática, psicología y astronomía, y se doctora con una tesis sobre cálculo de variaciones, antes de volcarse a la filosofía bajo la influencia de **Franz Brentano**, filósofo y antiguo sacerdote católico que enseñaba en Viena. Una obsesión personal recorre toda su obra y también su vida cotidiana: la de **ver con claridad**. Se cuenta que tenía fascinación por los anteojos, aunque lo que en verdad le importaba no eran los marcos sino las lentes.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Era la posibilidad de ver el mundo con tanta precisión como para estar absolutamente seguro de que lo visto es real. El artista y novelista vanguardista Witkacy escribió que Husserl parecía \"anteojos, ojos y una barba flotando en el espacio\", una figura que nunca terminaba de estar del todo en el mundo real.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Se casa en 1887 con Malvine Steinschneider, también de origen judío; ambos se convierten al protestantismo antes de la boda. Llevan una vida burguesa metódica: mientras él se dedica por entero a pensar, ella administra la casa, cría a los tres hijos, recibe a los estudiantes de posgrado y transcribe y edita sus manuscritos. De joven, en Leipzig, entabla una amistad duradera con **Tomáš Masaryk**, futuro presidente fundador de Checoslovaquia.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Cuatro obras marcan las etapas del proyecto. Las Investigaciones lógicas (1900-1901), que rompen con el psicologismo y fundan la fenomenología como disciplina. Ideas relativas a una fenomenología pura (1913), la primera exposición sistemática del método, con la doctrina de la reducción y el ego trascendental. Las Meditaciones cartesianas, expuestas en París en 1929 y publicadas en francés en 1931. Y La crisis de las ciencias europeas y la fenomenología trascendental, escrita en los últimos años de su vida, que queda inconclusa a su muerte y se publica completa recién en 1954.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El menor de sus tres hijos, Wolfgang, muere combatiendo por Alemania en 1916, en el frente occidental. En 1928 se jubila de su cátedra en Friburgo y lo sucede su antiguo asistente, **Martin Heidegger**. En 1933, bajo las leyes raciales del nazismo y con Heidegger como rector de la universidad, se le retira el acceso a la biblioteca por su origen judío.",
    },
    {
      type: "match",
      question: "Uní cada obra de Husserl con lo que marca en su proyecto",
      pairs: [
        { left: "Investigaciones lógicas (1900-1901)", right: "Rompe con el psicologismo y funda la fenomenología" },
        { left: "Ideas relativas a una fenomenología pura (1913)", right: "Primera exposición sistemática del método" },
        { left: "Meditaciones cartesianas (1929-1931)", right: "Expuestas en París, publicadas luego en francés" },
        { left: "La crisis de las ciencias europeas (1954, póstuma)", right: "Obra final e inconclusa a su muerte" },
      ],
      explain: "Las cuatro obras marcan las etapas del proyecto husserliano: de la ruptura con el psicologismo a la exposición sistemática del método, y de ahí a la crisis final de las ciencias europeas, que la muerte le impide terminar.",
    },
    {
      type: "info",
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "La vanguardia europea de las primeras décadas del siglo —futurismo, dadaísmo— entendió que lo que cambiaba con ella no era solamente el arte o la literatura en sí mismos, sino la relación entre **arte y vida**. Cruzar de la representación a la transformación significaba que el mundo podía crearse de nuevo, casi ex nihilo: un desquicio que era a la vez emocionante y vertiginoso, y también aterrador. El poeta Alexander Wat describió la emoción de ser futurista como la alegría de \"un colapso fundamental, en el que ahora había lugar para todo, en el que todo era realizable\".",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "Existe una historiografía específica sobre la relación entre esa vanguardia y la cultura estalinista del realismo socialista. El teórico Boris Groys sostiene que el paso decisivo en la estalinización del arte no fue imponerle una ideología comunista, sino cruzar exactamente esa misma frontera, de la representación a la transformación: el arte dejó de funcionar como espejo del mundo para convertirse en un martillo destinado a moldearlo, abriendo un espacio para la ingeniería social a una escala antes inimaginable.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "Los vanguardistas que abrazaron el futurismo y el dadaísmo —contingencia radical, nihilismo radical entendido como libertad radical y espacio de experimentación— encontraron esa misma libertad tan **sin suelo** que terminaron huyendo de ella: había algo existencialmente insoportable en esa falta de fundamento. Ese **miedo a la falta de suelo** es el problema de fondo de esta clase. Parte de esa generación, incapaz de sostener la carga de su propia subjetividad, dio el salto del nihilismo y la contingencia radicales al extremo opuesto: el utopismo y el determinismo radicales, uniéndose a la Revolución Comunista.",
    },
    {
      type: "quiz",
      question: "Ante la libertad radical sin fundamento que proponía la vanguardia, ¿qué hizo parte de esa generación?",
      options: [
        "La sostuvo con entusiasmo creciente hasta el final",
        "Saltó al extremo opuesto, hacia el utopismo determinista",
        "Volvió en silencio al arte figurativo tradicional",
        "Buscó refugio en la disciplina religiosa organizada",
      ],
      answer: 1,
      explain: "Incapaz de sostener el peso de la propia subjetividad sin suelo, parte de la vanguardia dio el salto del nihilismo y la contingencia radicales al extremo opuesto: el utopismo y el determinismo radicales de la Revolución Comunista.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "El lingüista Roman Jakobson es la excepción dentro de ese cuadro: sobrevive cada catástrofe del siglo y funciona como **figura bisagra** entre la vanguardia, el estructuralismo lingüístico y la fenomenología. Es también quien mejor describió el destino de otro vanguardista, Maiakovski, que se suicida en abril de 1930: lo llamó \"un hombre absolutamente inadecuado para la vida\", una frase que remite otra vez a esa relación quebrada entre arte y vida.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "Nadie podría ser, a primera vista, más alter ego de esa vanguardia que **Edmund Husserl**. Si la vanguardia era la aspiración salvaje a romper toda convención, con la sensación de que el mundo había ardido y todo era posible, Husserl representa lo contrario: un estilo de vida burgués, metódico, sin escándalo alguno.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "Pero es un alter ego precisamente porque está en el **otro extremo de los mismos problemas conceptuales**: comparte con los modernistas de la primera ola y con Freud una noción radical de subjetividad, y con la vanguardia una aspiración al **maximalismo**, la convicción de que hay que llevar la propia posición hasta el final.",
    },
    {
      type: "quiz",
      question: "¿En qué sentido es Husserl el «alter ego» de la vanguardia?",
      options: [
        "Comparte su estética de ruptura y su vida bohemia",
        "Enfrenta el mismo problema con la respuesta opuesta",
        "Rechaza de plano la idea de una subjetividad radical",
        "Cree, como ella, que el mundo puede crearse de la nada",
      ],
      answer: 1,
      explain: "Comparten época y problema —la falta de fundamento, la subjetividad radical, el maximalismo—, pero donde la vanguardia salta a la caída libre sin suelo, Husserl busca desesperadamente un suelo absoluto de certeza.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "A través de todas las diferencias de temperamento, hay entre ambos mundos similitudes profundas, y son además estrictamente contemporáneos. Como generalización histórica puede decirse que la vanguardia será destruida por el estalinismo, y la primera generación de fenomenólogos, en buena medida, por el nazismo: se llega a ese momento del siglo XX en que las cosas terminan mal para casi todos los que intentaron resolver, cada uno a su modo, el mismo problema.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "Ese problema era, en el fondo, el de la **falta de fundamento**. La Primera Guerra es el momento en que Europa arde, en que \"todo lo sólido se desvanece en el aire\" y nadie sabe todavía cuáles serán las reglas nuevas: caen cuatro imperios, se rediseña el mapa entero, y de golpe hace falta un pasaporte para viajar de un lugar a otro. Esa sensación vanguardista de libertad radical —el salto a la caída libre porque nada es cierto— era a la vez fuente de éxtasis y de desesperación.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el miedo a la falta de suelo",
      body: "Para Husserl, ese sentimiento generalizado refleja el problema propiamente moderno de la filosofía: ¿dónde empezar?, ¿de qué se puede estar seguro? La pregunta remite de inmediato a **Descartes**, con quien Husserl está obsesionado, porque hizo la pregunta correcta: el experimento radical de sacar de la mente todo lo que se cree saber y empezar desde la nada, preguntando \"empezando por nada, ¿de qué puedo estar seguro?\".",
    },
    {
      type: "info",
      title: "Brentano y el origen de la intencionalidad",
      body: "Antes de Husserl hay que nombrar a su maestro. Franz Brentano enseña en Viena desde la década de 1870 y en 1874 publica Psicología desde un punto de vista empírico, donde busca un criterio que distinga lo mental de lo físico. Su respuesta es que todo fenómeno psíquico está dirigido hacia un objeto —se ama algo, se juzga algo, se desea algo—, mientras que ningún fenómeno físico tiene esa estructura de apuntar hacia afuera. A esa dirección hacia un objeto la llama **inexistencia intencional**, y ese concepto es el punto de partida de toda la fenomenología posterior.",
    },
    {
      type: "quiz",
      question: "Según Brentano, ¿qué distingue a todo fenómeno psíquico de uno físico?",
      options: [
        "Estar siempre dirigido hacia algún objeto",
        "Poder medirse con precisión de laboratorio",
        "Ser accesible sólo por introspección directa",
        "Depender enteramente de las leyes físicas",
      ],
      answer: 0,
      explain: "Brentano llama «inexistencia intencional» a esa dirección hacia un objeto —se ama, se juzga, se desea algo—, mientras que ningún fenómeno físico apunta de ese modo hacia afuera. Ese concepto es el origen de la intencionalidad husserliana.",
    },
    {
      type: "info",
      continues: true,
      title: "Brentano y el origen de la intencionalidad",
      body: "Por el aula de Brentano en Viena pasan, en años cercanos, Husserl, **Sigmund Freud** y **Tomáš Masaryk**. Husserl y Freud, además, comparten una biografía asombrosamente parecida: nacen con apenas tres años de diferencia, son ambos judíos austrohúngaros asimilados, estudian en Viena, se forman con el mismo Brentano y son, cada uno a su modo, rebeldes contra el positivismo con teorías de una subjetividad radical. Son, en ese sentido, alter egos el uno del otro: cada uno toma la apuesta por una subjetividad radical en una dirección opuesta.",
    },
    {
      type: "quiz",
      question: "¿Qué comparten Husserl y Freud además del aula de Brentano en Viena?",
      options: [
        "Haber nacido el mismo año en la misma ciudad austríaca",
        "Ser vieneses judíos asimilados con teorías radicales",
        "Haber compartido consultorio médico en Viena por años",
        "Militar los dos en el mismo partido político vienés",
      ],
      answer: 1,
      explain: "Nacen con apenas tres años de diferencia, son ambos judíos austrohúngaros asimilados que estudian en Viena y se forman con Brentano, y son cada uno a su modo rebeldes contra el positivismo con una teoría de subjetividad radical.",
    },
    {
      type: "info",
      continues: true,
      title: "Brentano y el origen de la intencionalidad",
      body: "Esa divergencia es exactamente la que importa para entender a Husserl. Para Freud, el yo esencial es lo más **oculto**, encerrado en un inconsciente al que la conciencia no tiene acceso directo. Para Husserl, en cambio, el yo depurado por el método fenomenológico —el ego trascendental— será enteramente **transparente** a sí mismo: todo luz, nada oculto, todo claro. Ambos toman la noción de intencionalidad heredada de Brentano, pero la llevan a resultados casi opuestos sobre qué puede saber la conciencia de sí misma.",
    },
    {
      type: "info",
      title: "El problema del puente y el predicamento egocéntrico",
      body: "Con Husserl vuelve, bajo otra forma, el **problema del puente**: ¿cómo sé que esta taza o esta silla existen de verdad y no son una proyección de mi conciencia? El punto de partida es la primera persona: yo soy el sujeto, y todo lo que está fuera de mí es objeto. (Más adelante, con la noción de intersubjetividad, el problema se complica todavía más: yo miro a otra persona y ella es objeto para mí, pero ella me mira a su vez y yo soy objeto para ella.)",
    },
    {
      type: "info",
      continues: true,
      title: "El problema del puente y el predicamento egocéntrico",
      body: "Los filósofos nombraron ese problema de mil maneras —mente y mundo, conciencia y ser, inmanente y trascendente, interior y exterior, sujeto y objeto—, pero todas describen lo mismo: nadie puede salir de su propia cabeza para verificar desde afuera cómo es el mundo en realidad. La fenomenología quiere liberar al pensamiento de ese **predicamento egocéntrico**, la idea de que la mente es una caja sin ventanas donde solo hay certeza del propio yo y de los contenidos de la conciencia.",
    },
    {
      type: "quiz",
      question: "¿Qué nombra el «predicamento egocéntrico» que la fenomenología quiere superar?",
      options: [
        "No poder salir de la propia cabeza para ver el mundo",
        "Que el yo depende por completo de la opinión ajena",
        "Que la ciencia moderna ignora todo dato subjetivo",
        "Que el lenguaje impide describir la propia experiencia",
      ],
      answer: 0,
      explain: "Es la idea de que la mente es una caja sin ventanas, donde sólo hay certeza del propio yo y de sus contenidos, sin poder verificar desde afuera cómo es el mundo en realidad. La fenomenología busca liberar al pensamiento de ese encierro.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema del puente y el predicamento egocéntrico",
      body: "Husserl busca una salida de esa caja: hacer que la conciencia estalle hacia afuera, hacia el objeto, con una pretensión de verdad objetiva mayor que la que Kant se permitió. Es el mismo problema que viene, al menos, desde Descartes, y del que Husserl no da por buena ninguna solución previa: Kant creyó haberlo resuelto tanto como era posible, pero Husserl no queda satisfecho con esa solución.",
    },
    {
      type: "info",
      title: "Términos: inmanente, trascendente, trascendental",
      body: "Antes de seguir conviene fijar un vocabulario que Husserl usa con precisión técnica. La pregunta que lo organiza es cómo puede el conocimiento **trascenderse a sí mismo** y alcanzar de modo confiable su objeto: cómo puede un sujeto pensante saber que existen, no solo sus propios procesos mentales, sino también aquello que esos procesos aprehenden.",
    },
    {
      type: "info",
      continues: true,
      title: "Términos: inmanente, trascendente, trascendental",
      body: "Llama **inmanente** a lo que está adentro de la conciencia, y **trascendente** a lo que está afuera, del otro lado de la frontera de la conciencia. Un tercer término, **trascendental**, no debe confundirse con el anterior: siguiendo el uso kantiano, designa las condiciones de posibilidad de esa trascendencia como conocimiento del objeto, es decir, lo que hace posible que la mente cruce la frontera hacia lo que está fuera de ella. Husserl retoma ese vocabulario kantiano y acuña, a partir de él, la noción de **ego trascendental**, que será central en todo su sistema.",
    },
    {
      type: "match",
      question: "Uní cada término técnico de Husserl con su sentido",
      pairs: [
        { left: "Inmanente", right: "Lo que está adentro de la conciencia" },
        { left: "Trascendente", right: "Lo que está afuera de la conciencia" },
        { left: "Trascendental", right: "Lo que hace posible cruzar hacia el afuera" },
      ],
      explain: "Husserl toma el vocabulario kantiano: inmanente y trascendente marcan el adentro y el afuera de la conciencia; trascendental nombra las condiciones que hacen posible ese cruce, y de ahí acuña la noción de ego trascendental.",
    },
    {
      type: "info",
      title: "El tercero contra el positivismo",
      body: "Husserl completa, junto a Bergson y Freud, un trío de rebeldes contra el positivismo decimonónico, y es el más difícil de situar porque su rebelión queda muy cerca de aquello contra lo que se subleva —el mismo fenómeno que Freud describió como el \"narcisismo de las pequeñas diferencias\": cuanto más pequeñas son las diferencias entre dos posiciones, más se obsesiona la gente con ellas—.",
    },
    {
      type: "info",
      continues: true,
      title: "El tercero contra el positivismo",
      body: "La fenomenología es una revuelta **subjetivista** contra el ideal de una ciencia sin sujeto, contra el modelo de las ciencias de laboratorio y la fantasía de una \"vista desde ninguna parte\", un punto arquimediano, una mosca en la pared que observa el mundo con objetividad total. **Emmanuel Levinas**, alumno tardío de Husserl y mucho mejor escritor que él, describió esa ciencia decimonónica como una aspiración al reino de la pura objetividad, de los objetos puros, \"como un salto a la nada\".",
    },
    {
      type: "info",
      continues: true,
      title: "El tercero contra el positivismo",
      body: "Lo que Levinas valoraba en la fenomenología era justamente el gesto contrario: que invierte la actitud científica clásica, porque la física de Newton se aparta del sujeto para mayor gloria del objeto y decreta la expulsión de todo elemento subjetivo. Esa sensación de que el positivismo era existencialmente empobrecedor, frío y seco —demasiada racionalidad, ¿y si no se quiere que dos más dos sea cuatro?— reaparece una y otra vez en los rebeldes contra él.",
    },
    {
      type: "quiz",
      question: "Para Husserl y Levinas, ¿qué le faltaba al positivismo decimonónico?",
      options: [
        "El rigor matemático de sus muchas mediciones",
        "Un sujeto, porque soñaba un saber sin nadie",
        "La fe en el progreso indefinido de la ciencia",
        "La atención a la lógica y a sus leyes puras",
      ],
      answer: 1,
      explain: "El positivismo aspiraba a una «vista desde ninguna parte», puro objeto sin sujeto —«un salto a la nada», decía Levinas—. La fenomenología invierte esa actitud: devuelve el sujeto al centro del conocimiento.",
    },
    {
      type: "info",
      title: "Contra el psicologismo",
      body: "Pero Husserl también se rebela contra lo opuesto: el **psicologismo**, la tesis de que la lógica, la verdad, la evidencia y el razonamiento son, en el fondo, meras actividades empíricas de la psique, reducibles a leyes sobre cómo funciona la mente humana. Si el positivismo le resulta frío y vacío de sujeto, el psicologismo le resulta demasiado relativo, atado por completo a la contingencia de una mente particular.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el psicologismo",
      body: "Busca, entonces, un lugar entre los dos: ni objetivismo sin sujeto ni verdad disuelta en psicología. A diferencia de otras oposiciones filosóficas más marcadas —razón frente a pasión, idealismo frente a materialismo—, acá la distancia entre lo que rechaza y lo que propone es mínima, y ahí está lo difícil de Husserl: se rebela contra cosas de las que queda apenas a un paso de distancia.",
    },
    {
      type: "classify",
      question: "¿Cada postura corresponde al positivismo o al psicologismo?",
      groups: ["Positivismo", "Psicologismo"],
      items: [
        { text: "Aspira a una «vista desde ninguna parte», sin sujeto", group: 0 },
        { text: "Reduce la verdad y la lógica a leyes de la mente", group: 1 },
        { text: "Toma como modelo la física y el laboratorio", group: 0 },
        { text: "Cree que sólo son seguras las reglas de la mente", group: 1 },
        { text: "Expulsa todo elemento subjetivo del conocimiento", group: 0 },
        { text: "Hace de la psique la medida de todo lo cierto", group: 1 },
      ],
      explain: "Husserl rechaza los dos extremos: el positivismo diluye el sujeto en el objeto puro; el psicologismo diluye el objeto en la mente. La fenomenología busca un lugar entre ambos, sin renunciar ni a la subjetividad ni a la verdad objetiva.",
    },
    {
      type: "info",
      title: "Descartes sí, Kant no",
      body: "Husserl admira a Descartes: la idea de partir de cero absoluto, dudando de todo lo dudable, le parece el gesto correcto. Descartes descarta todo aquello de lo que puede dudar —no puede estar seguro del contenido de sus pensamientos, tal vez los puso ahí un genio maligno—, pero sí puede estar seguro de que **está pensando**, y de ahí saca su certeza fundacional, el cogito ergo sum. Es el modelo de una filosofía que empieza sin presupuestos y construye hacia arriba desde la nada.",
    },
    {
      type: "info",
      continues: true,
      title: "Descartes sí, Kant no",
      body: "De **Kant**, en cambio, Husserl se distancia con dureza, aunque su propia solución queda, en más de un punto, a un paso de la kantiana —otra vez el narcisismo de las pequeñas diferencias—. Lo que no tolera es lo que llama la moderación radical de Kant: sí, hay un mundo real, pero no tenemos acceso a él tal como existe fuera de nuestra conciencia; la **Ding an sich**, la cosa en sí, es inalcanzable, así que conviene dejarla de lado y concentrarse en lo que sí puede conocerse.",
    },
    {
      type: "info",
      continues: true,
      title: "Descartes sí, Kant no",
      body: "Kant era, a su modo, alegre, optimista y razonable frente a ese límite. Husserl no lo tolera: le parece **fatalismo, rendición**. Que se renuncie a la posibilidad de alcanzar la cosa real le resulta insoportable, y esa misma sensación de que es insoportable es la clave para entender todo el proyecto husserliano. Frente al \"radicalismo en la moderación\" kantiano, Husserl adopta una actitud que bien podría resumirse como la del **\"sí, se puede\"**: sí es posible alcanzar claridad epistemológica y verdad absoluta, y todo su método consiste en intentar dejar atrás ese fatalismo kantiano.",
    },
    {
      type: "quiz",
      question: "¿Por qué Husserl rechaza la solución de Kant?",
      options: [
        "Porque Kant niega que exista un mundo real",
        "Porque renunciar a la cosa en sí le parece rendición",
        "Porque Kant reduce toda verdad al funcionamiento mental",
        "Porque Kant empieza su filosofía desde cero",
      ],
      answer: 1,
      explain: "Kant admite un mundo real pero declara inalcanzable la cosa en sí y propone concentrarse en lo conocible. A Husserl esa renuncia le resulta insoportable: cree que sí se puede llegar a la verdad absoluta.",
    },
    {
      type: "info",
      title: "Fenomenología: un método, no una teoría",
      body: "Husserl busca, como Descartes, un fundamento: empezar en cero absoluto, sin suponer nada de antemano. Lo que ofrece es menos una teoría que un **método**, un modo de intentar entender el mundo. Quiere una **ciencia rigurosa**, pero no positivista: romper con el positivismo y el empirismo y, al mismo tiempo, fundar todas las demás ciencias sobre una base que ellas mismas no pueden darse. Son, otra vez, aspiraciones maximalistas.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenomenología: un método, no una teoría",
      body: "El método arranca de dos términos: el **mundo** y el **yo**. Se supone, inicialmente, que el mundo existe, que los objetos existen y que es posible conocerlos. Los objetos pueden aparecer de maneras distintas según la perspectiva —una lapicera se ve distinta tirada en el piso que a la altura de los ojos, o bajo una luz tenue—, pero esa variación no vuelve imposible el conocimiento objetivo. El mundo es como el **horizonte**, el contexto en que todos los objetos se manifiestan, y solo hay uno: es el horizonte de todo lo demás.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenomenología: un método, no una teoría",
      body: "La segunda singularidad, la que verdaderamente importa, es el **yo**, el **ego**. Si el mundo es el todo más abarcador, el yo es una cosa **en** el mundo, pero de un tipo único: en cierto modo posee el mundo, es aquel a quien el mundo le es **dado**.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenomenología: un método, no una teoría",
      body: "\"Dado\" y \"**donación**\" (**Gegebenheit**) son palabras cotidianas del alemán a las que Husserl da un giro técnico: el mundo se da; el yo es especial porque es el **dativo de la manifestación**, aquel a quien el mundo es dado. La conciencia es, en ese sentido, el punto de partida absoluto de todo el método.",
    },
    {
      type: "quiz",
      question: "¿Por qué dice Husserl que el yo es el «dativo de la manifestación»?",
      options: [
        "Porque es aquel a quien el mundo le es dado",
        "Porque es quien decide qué existe y qué no",
        "Porque es el único objeto que no cambia nunca",
        "Porque es quien crea el mundo con su voluntad",
      ],
      answer: 0,
      explain: "«Dado» y «donación» (Gegebenheit) son palabras que Husserl tecnifica: el mundo se da, y el yo es especial porque es el dativo de la manifestación, aquel a quien el mundo le es dado. Ahí arranca el método.",
    },
    {
      type: "info",
      continues: true,
      title: "Fenomenología: un método, no una teoría",
      body: "En un ensayo de 1911, La filosofía como ciencia rigurosa, Husserl advierte que seguir el modelo de las ciencias naturales lleva casi inevitablemente a **reificar la conciencia**, a tratarla como si fuera una cosa material entre otras, lo que desde el inicio conduce al absurdo: la conciencia no puede estudiarse con los mismos instrumentos con que se estudia una piedra o un átomo, porque ella es la condición misma de que haya piedras o átomos para alguien.",
    },
    {
      type: "info",
      title: "El ego trascendental y el ego empírico",
      body: "Aquí aparece el punto conceptualmente más difícil del sistema: llegar a una noción radical de conciencia que no esté reificada, una conciencia que sea, en cierto sentido, \"una cosa que no es cosa\". Husserl distingue el **ego trascendental** del **ego empírico**.",
    },
    {
      type: "info",
      continues: true,
      title: "El ego trascendental y el ego empírico",
      body: "El **yo empírico** es el que cada uno es en la vida real: distinto física, fisiológica y psicológicamente de cualquier otro, con experiencias particulares —físicas, emocionales, históricas— que son contingentes según el lugar de nacimiento, el clima, la crianza. Cada yo empírico es particular y diferente de todos los demás.",
    },
    {
      type: "info",
      continues: true,
      title: "El ego trascendental y el ego empírico",
      body: "El **yo trascendental**, en cambio, es lo que Husserl busca desenredar de ese ego empírico particular: quiere llegar a un yo que sea, a la vez, lo más profundo, interior y esencial de cada uno y, simultáneamente, universal y genérico, el mismo para todos. La operación consiste en desenredar un ego empírico —reificado, particular— de un ego trascendental —universal—, entrando a la vez en lo más singular y volviéndolo universal.",
    },
    {
      type: "info",
      continues: true,
      title: "El ego trascendental y el ego empírico",
      body: "Dos analogías ayudan a verlo, aunque de manera desigual. El **agua** sabe y se ve distinta según de dónde venga —una botella, una canilla, el mar—, pero hay una fórmula universal, el H₂O, que es la misma en todos los casos: el ego trascendental sería algo así, una esencia común bajo la variación empírica.",
    },
    {
      type: "info",
      continues: true,
      title: "El ego trascendental y el ego empírico",
      body: "La **manzana** ofrece un ejemplo más preciso todavía: una descripción fenomenológica detalla cómo se ve una manzana particular —ladeada, con una manchita marrón cerca del cabo, el rojo virando a verde y amarillo hacia los bordes—; no hay dos manzanas iguales, y sin embargo hay una esencia casi platónica de \"manzanidad\" que hace de cada una una manzana y no otra cosa.",
    },
    {
      type: "info",
      continues: true,
      title: "El ego trascendental y el ego empírico",
      body: "Husserl aplica ese mismo razonamiento al yo, aunque la analogía funciona con mucha más comodidad para la manzana que para la persona: resulta más fácil aceptar que hay una esencia universal de \"manzanidad\" que aceptar que hay una esencia universal de \"yoidad\" detrás de cada conciencia particular. Aun así, la operación entera del sistema depende de que ese paso sea posible. Puede pensarse, en términos hegelianos, como una **Aufhebung** de la subjetividad empírica: elevada, negada como particular, pero con su esencia preservada en un nivel superior.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del yo empírico o del trascendental?",
      groups: ["Yo empírico", "Yo trascendental"],
      items: [
        { text: "Es particular: cada persona tiene el suyo", group: 0 },
        { text: "Es universal: el mismo para todos", group: 1 },
        { text: "Depende del cuerpo, la historia y el lugar", group: 0 },
        { text: "Es como el H₂O común a toda agua", group: 1 },
        { text: "Es contingente y cambia de una vida a otra", group: 0 },
        { text: "Es lo más íntimo y esencial de cada uno", group: 1 },
      ],
      explain: "El yo empírico es el particular y contingente de la vida real; el trascendental es a la vez lo más profundo de cada uno y algo universal, el mismo para todos —como el agua, distinta en cada lugar y sin embargo H₂O—. La fenomenología trabaja con este segundo yo.",
    },
    {
      type: "info",
      title: "Intencionalidad",
      body: "El yo que interesa a la fenomenología, el que ejecuta el método, es este ego trascendental, y su estructura no es la de un sujeto cartesiano encerrado en su cabeza: es la **intencionalidad**, término que Husserl toma de Brentano —y este, a su vez, de un uso aristotélico— y radicaliza. No es \"intención\" en el sentido cotidiano de un propósito (pensar en llamar a alguien); es una estructura de la conciencia misma.",
    },
    {
      type: "info",
      continues: true,
      title: "Intencionalidad",
      body: "Puede pensarse como una cuerda con una flecha imantada en la punta: la conciencia siempre está alcanzando y agarrando un objeto, estallando hacia él, conectada como por un imán.",
    },
    {
      type: "info",
      continues: true,
      title: "Intencionalidad",
      body: "El movimiento filosófico clave es que no hay que derivar el sujeto del objeto ni el objeto del sujeto: al principio está la **relación**, y esa relación no puede desconectarse. La intencionalidad es el **puente** entre ambos términos.",
    },
    {
      type: "short",
      question: "¿Cómo llama Husserl a la estructura de la conciencia que siempre está dirigida hacia un objeto?",
      answers: ["intencionalidad"],
      explain: "La intencionalidad: la conciencia es siempre conciencia de algo, estalla hacia el objeto. Husserl toma el término de Brentano. Es el puente que conecta sujeto y objeto, contra la imagen de la mente como caja cerrada.",
    },
    {
      type: "info",
      continues: true,
      title: "Intencionalidad",
      body: "Donde Kant decía que la Ding an sich es inalcanzable, Husserl reformula el problema —hay aquí, además, otra dificultad de traducción, porque tanto Sache como Ding se traducen al español como \"cosa\"— con otra fórmula: \"**las cosas mismas**\" (también \"los asuntos mismos\") son los objetos tal como se nos aparecen en la experiencia, tal como se nos dan, y no una realidad escondida detrás de la apariencia.",
    },
    {
      type: "quiz",
      question: "Frente a la «Ding an sich» inalcanzable de Kant, ¿qué propone Husserl?",
      options: [
        "Los objetos tal como se aparecen a la experiencia",
        "Una fórmula matemática que reemplaza al objeto",
        "Aceptar que el objeto es, en el fondo, incognoscible",
        "Un objeto ideal construido por pura deducción lógica",
      ],
      answer: 0,
      explain: "Donde Kant declara inalcanzable la cosa en sí, Husserl habla de «las cosas mismas»: los objetos tal como se nos aparecen y se dan en la experiencia, no una realidad escondida detrás de la apariencia.",
    },
    {
      type: "info",
      title: "La reducción fenomenológica: la epojé",
      body: "La **reducción fenomenológica** es el proceso por el cual la conciencia se eleva a este estado superior, se despoja de lo particular y piensa desde el ego trascendental. Se pasa de la **actitud natural** —aquella en la que se vive casi siempre, dando por sentado ingenuamente que el mundo existe— a la **actitud fenomenológica**, en la que la conciencia se sacude hacia un estado superior y reflexiona sobre sus propios contenidos.",
    },
    {
      type: "info",
      continues: true,
      title: "La reducción fenomenológica: la epojé",
      body: "Lo primero que hay que hacer es tomar la pregunta \"¿es real?, ¿existe el mundo?\" y **ponerla entre paréntesis**: el famoso **bracketing** fenomenológico, la **epojé**. No se trata de dudar ni de volverse escéptico: se **suspende** la pregunta, se la deja a un costado —se volverá a ella más tarde, aunque los críticos de Husserl sostienen que ese regreso nunca ocurre—.",
    },
    {
      type: "quiz",
      question: "El «bracketing» fenomenológico consiste en…",
      options: [
        "demostrar con certeza que el mundo externo existe",
        "dudar de todo, como en el método de Descartes",
        "suspender la pregunta por la existencia del mundo",
        "negar que los objetos existan fuera de la mente",
      ],
      answer: 2,
      explain: "Bracketing no es dudar ni negar: es poner la pregunta por la existencia entre paréntesis, dejarla en suspenso para describir con pureza cómo aparecen las cosas a la conciencia. La pregunta sigue ahí; sólo se corrió a un lado.",
    },
    {
      type: "match",
      question: "Uní cada término de la fenomenología con lo que nombra",
      pairs: [
        { left: "Intencionalidad", right: "La conciencia siempre dirigida hacia un objeto" },
        { left: "Ego trascendental", right: "El yo universal y esencial, el mismo para todos" },
        { left: "Bracketing", right: "Suspender la pregunta por la existencia del mundo" },
        { left: "Reducción fenomenológica", right: "El paso de la actitud natural a la fenomenológica" },
        { left: "«Las cosas mismas»", right: "Los objetos tal como se nos aparecen y se dan" },
      ],
      explain: "Las piezas del método: la conciencia alcanza el mundo por la intencionalidad; para verlo con pureza uno hace la reducción, pone entre paréntesis su existencia (bracketing) y se eleva al ego trascendental, para describir «las cosas mismas», los objetos tal como se dan.",
    },
    {
      type: "info",
      continues: true,
      title: "La reducción fenomenológica: la epojé",
      body: "La pregunta sigue ahí, no fue borrada, solo fue corrida, y ahora la atención se concentra en una **descripción exhaustiva** de los objetos tal como se dan a la conciencia pura, tal como los agarra la intencionalidad. El método es, en ese sentido, profundamente **descriptivo**.",
    },
    {
      type: "info",
      continues: true,
      title: "La reducción fenomenológica: la epojé",
      body: "A diferencia de la represión freudiana, donde lo apartado de la conciencia sigue actuando de manera oculta en el inconsciente, lo puesto entre paréntesis en la reducción fenomenológica no desaparece ni actúa a escondidas: queda simplemente suspendido, disponible para ser retomado en cualquier momento, sin ejercer mientras tanto ninguna presión sobre la conciencia. Esa diferencia es la que separa con más nitidez el proyecto de Husserl del de Freud, aun cuando ambos parten de una noción radical de subjetividad.",
    },
    {
      type: "info",
      continues: true,
      title: "La reducción fenomenológica: la epojé",
      body: "El método se aplica mejor extrapolado de su forma técnica estricta que en su formulación original. Pensar, por ejemplo, en un prejuicio como la homofobia o el racismo y preguntarse si puede ponerse temporalmente entre paréntesis qué es real y qué no, para concentrarse en una descripción exacta de lo que efectivamente se ve, es ya una forma de reducción fenomenológica en sentido amplio: ese \"ver puro\" es lo que Husserl persigue en su forma técnica.",
    },
    {
      type: "info",
      continues: true,
      title: "La reducción fenomenológica: la epojé",
      body: "El lenguaje de Husserl está obsesionado con **ver**, con la claridad epistemológica, con la fórmula que toma de Descartes, claritas et distinctio —**claridad y distinción**—. La ironía no pasó inadvertida a sus propios lectores: quien hizo de la claridad su obsesión central resultó, según coinciden casi todos sus comentaristas, un escritor extremadamente oscuro y difícil.",
    },
    {
      type: "info",
      continues: true,
      title: "La reducción fenomenológica: la epojé",
      body: "El sujeto humano sigue siendo, para Husserl, **fuente de todo sentido**. El contraste con el psicoanálisis es exacto: para Freud, lo esencial del yo es lo más **oculto**; para Husserl, al llegar a la conciencia pura, al ego trascendental, ese yo será **absolutamente transparente**, todo luz, nada oculto, todo claro. La conciencia pura implica, en su sistema, la **transparencia del sujeto para consigo mismo**.",
    },
    {
      type: "quiz",
      question: "Frente a Freud, ¿cómo concibe Husserl el fondo del yo?",
      options: [
        "Como algo oculto que se resiste a la conciencia",
        "Como algo absolutamente transparente y claro",
        "Como una ilusión que conviene disolver",
        "Como un mecanismo material y reificado",
      ],
      answer: 1,
      explain: "Son alter egos: para Freud lo esencial del yo es el inconsciente, lo más oculto; para Husserl, al alcanzar la conciencia pura el sujeto se vuelve todo luz, transparente para sí mismo y fuente de todo sentido.",
    },
    {
      type: "info",
      title: "El mundo de la vida y la crisis de las ciencias europeas",
      body: "En sus últimos años, ya expulsado de la universidad, Husserl retoma una idea que da nueva urgencia a todo el proyecto: el **Lebenswelt**, el **mundo de la vida**. Es el mundo concreto, prefilosófico y prescientífico en el que efectivamente se vive, el suelo de experiencia compartida que toda ciencia presupone y que, al mismo tiempo, la ciencia moderna tiende a tapar con su propio aparato conceptual.",
    },
    {
      type: "short",
      question: "¿Cómo llama Husserl, en sus últimos años, al mundo concreto y prefilosófico que toda ciencia presupone?",
      answers: ["Lebenswelt"],
      explain: "El Lebenswelt es el suelo de experiencia compartida, prefilosófico y prescientífico, en el que efectivamente se vive, y que la ciencia moderna tiende a tapar con su propio aparato conceptual.",
    },
    {
      type: "info",
      continues: true,
      title: "El mundo de la vida y la crisis de las ciencias europeas",
      body: "Desde Galileo, sostiene Husserl, la naturaleza se matematizó hasta el punto de sustituir el mundo vivido por un mundo de fórmulas, y esa sustitución terminó por olvidarse de sí misma: se empezó a confundir el modelo matemático, que era en su origen una herramienta construida para describir el mundo, con la realidad misma que ese modelo debía describir. El mapa terminó ocupando el lugar del territorio.",
    },
    {
      type: "info",
      continues: true,
      title: "El mundo de la vida y la crisis de las ciencias europeas",
      body: "Esa amnesia es, para Husserl, el núcleo de la **crisis de las ciencias europeas**, título de su obra final. Las ciencias positivas, cada vez más exactas y poderosas dentro de su propio dominio, se volvieron mudas frente a las preguntas que de verdad importan a la existencia humana concreta —qué sentido tiene la vida, cómo se debe vivir, qué es lo justo—, precisamente porque esas preguntas no admiten tratamiento matemático ni experimental. Una ciencia que solo sabe medir no puede, por definición, decir nada sobre el sentido.",
    },
    {
      type: "quiz",
      question: "Según Husserl, ¿por qué las ciencias positivas quedan mudas ante las preguntas de sentido?",
      options: [
        "Porque esas preguntas no admiten tratamiento matemático",
        "Porque los científicos las consideran de mal gusto",
        "Porque el Estado prohíbe investigar sobre ese tema",
        "Porque ya fueron respondidas por la teología cristiana",
      ],
      answer: 0,
      explain: "Las ciencias positivas, cada vez más exactas dentro de su dominio, no pueden pronunciarse sobre qué sentido tiene la vida o qué es lo justo, porque esas preguntas no admiten tratamiento matemático ni experimental.",
    },
    {
      type: "info",
      continues: true,
      title: "El mundo de la vida y la crisis de las ciencias europeas",
      body: "Husserl liga directamente esa mudez de las ciencias al hundimiento político de Europa en los años treinta: donde la razón renuncia a pronunciarse sobre el sentido de la existencia, avanza el irracionalismo, y de ahí a la barbarie hay un paso corto. La crisis de las ciencias no es, en su diagnóstico, un problema meramente académico, sino la raíz intelectual de la catástrofe política que está viviendo en carne propia.",
    },
    {
      type: "quiz",
      question: "¿Cómo liga Husserl la crisis de las ciencias con el hundimiento político de Europa?",
      options: [
        "Dice que si la razón calla, avanza el irracionalismo",
        "Cree que ambas crisis no guardan relación alguna",
        "Atribuye el hundimiento político a errores militares",
        "Sostiene que la ciencia exacta pudo evitar la guerra",
      ],
      answer: 0,
      explain: "Donde la razón renuncia a pronunciarse sobre el sentido de la existencia, avanza el irracionalismo, y de ahí a la barbarie hay un paso corto: la crisis de las ciencias es, para Husserl, la raíz intelectual de la catástrofe política.",
    },
    {
      type: "info",
      continues: true,
      title: "El mundo de la vida y la crisis de las ciencias europeas",
      body: "Cuando el hijo menor de Husserl muere combatiendo por Alemania, en 1916, la familia queda devastada; pasan apenas unas semanas y Husserl le escribe a un amigo que sí, eso ocurrió, pero que ahora \"la guerra está entre paréntesis\": la misma operación de la epojé aplicada, de manera casi desgarradora, al propio duelo. En 1933, ya expulsado de la universidad como \"no ario\" pese a haber sido un patriota alemán fanático durante la Primera Guerra, se encierra en su estudio y sigue tratando obsesivamente de clarificar la reducción fenomenológica.",
    },
    {
      type: "info",
      continues: true,
      title: "El mundo de la vida y la crisis de las ciencias europeas",
      body: "Lo hace porque cree, con la misma convicción de siempre, que Europa cayó en la barbarie porque la gente se dejó caer en una pérdida de fe en la razón y en la posibilidad de alcanzar la verdad absoluta, y que ese irracionalismo condujo directamente a la catástrofe. Para él las apuestas eran de **todo o nada**: o se llega a la verdad absoluta y a la claridad epistemológica pura, o el desenlace es el manicomio colectivo que ya empezaba a ver a su alrededor.",
    },
    {
      type: "match",
      question: "Uní cada término husserliano con lo que designa",
      pairs: [
        { left: "Inexistencia intencional", right: "La dirección de todo fenómeno psíquico hacia un objeto" },
        { left: "Predicamento egocéntrico", right: "La mente como caja sin ventanas, encerrada en sí misma" },
        { left: "Gegebenheit", right: "La donación del mundo al yo que lo recibe" },
        { left: "Lebenswelt", right: "El mundo de la vida, suelo de toda ciencia" },
      ],
      explain: "Un repaso del vocabulario técnico que arma el sistema husserliano, desde el concepto heredado de Brentano hasta la idea final de un mundo de la vida que la ciencia moderna tiende a olvidar.",
    },
    {
      type: "info",
      title: "Cierre: la herencia",
      body: "Husserl muere en 1938 sin haber completado La crisis, con Europa a un año de la guerra. Su sucesor en la cátedra de Friburgo, Martin Heidegger, fue también su alumno más importante, y en 1927 le dedica Ser y tiempo con una fórmula de admiración y deuda. Pero Heidegger toma el proyecto fenomenológico y lo desvía en un punto decisivo: en lugar de partir de un ego trascendental y un mundo puesto entre paréntesis, parte de la existencia humana ya arrojada en el mundo, antes de cualquier acto de conciencia que la conecte con los objetos.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la herencia",
      body: "Esa reformulación no abandona el vocabulario de Husserl —conserva la intencionalidad, la actitud natural, el problema del puente—, pero cambia el punto de partida: donde Husserl necesitaba un método para que la conciencia alcanzara el mundo, Heidegger sostiene que jamás hubo distancia que salvar, porque la existencia humana está siempre ya instalada en él.",
    },
  ],
};
