export default {
  num: 8,
  transcript: 9,
  title: "El psicoanálisis freudiano",
  source: "https://www.youtube.com/watch?v=xklKq36LxFM",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Sigmund Freud** (1856-1939) nace en Freiberg, Moravia, entonces parte del Imperio austrohúngaro, hijo de un comerciante judío asimilado y bastante pobre. La familia se muda a **Viena** hacia 1860, en medio de la flexibilización de las restricciones a los judíos del imperio, que atraía a Viena como meca de la inmigración judía. Freud crece sin educación religiosa, entra ateo a la universidad y sigue siéndolo toda su vida, aunque su condición de judío en el imperio marca su biografía entera.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Estudia **medicina** en Viena y en 1885-1886 viaja a París para formarse con **Jean-Martin Charcot** en el estudio de la histeria y la hipnosis, experiencia que orienta el resto de su carrera. De regreso en Viena colabora con el médico **Josef Breuer**, con quien publica en 1895 los Estudios sobre la histeria, el libro que presenta el caso de **Anna O.** —nombre clínico de Bertha Pappenheim— y el llamado **método catártico**, la cura por la palabra.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En 1886 se casa con Martha Bernays, del norte de Alemania; tienen seis hijos, la menor de los cuales, **Anna Freud**, será una discípula decisiva y una teórica del psicoanálisis por derecho propio. Vive y trabaja en Viena, en la Berggasse, hasta el **Anschluss** de marzo de 1938, cuando Alemania anexa Austria; parte entonces hacia Londres vía París y muere allí en septiembre de 1939, semanas después de estallar la Segunda Guerra Mundial.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Antes de la medicina, los primeros intereses de Freud fueron literarios: Shakespeare, los poetas alemanes clásicos, y una atracción de fondo por los grandes misterios de la existencia que nunca lo abandona del todo. Esa formación deja huella en un estilo que, incluso en sus textos más técnicos, recurre constantemente a la imagen literaria y al mito para nombrar procesos psíquicos que ningún vocabulario clínico previo describía con precisión.",
    },
    {
      type: "quiz",
      question: "¿Qué logra Freud durante su formación con Charcot y luego con Breuer?",
      options: [
        "Orienta su carrera al estudio de la histeria e hipnosis",
        "Descubre una cura farmacológica para la histeria",
        "Rompe con la medicina y se dedica sólo a la filosofía",
        "Formula ya en París la teoría del complejo de Edipo",
      ],
      answer: 0,
      explain: "En 1885-1886 viaja a París a formarse con Charcot en histeria e hipnosis; de vuelta en Viena colabora con Breuer, con quien publica en 1895 los Estudios sobre la histeria y el caso de Anna O., origen del método catártico.",
    },
    {
      type: "info",
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "La Revolución Bolchevique desemboca en una guerra civil de tres años y en la creación de la Unión Soviética. En 1924 Lenin muere de un derrame cerebral, y de la lucha de poder que sigue entre Trotsky y Stalin resulta vencedor Stalin; Trotsky, perseguido hasta México, es asesinado allí en 1940 por un agente soviético. Entre ambos se dirime una ruptura conceptual: frente a la fe leninista en una revolución obrera internacional inminente, que no llega, Stalin declara el \"**socialismo en un solo país**\"; Trotsky insiste en la **revolución permanente**.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "De ese contexto surge un Estado totalitario de un tipo antes desconocido: una ideología con pretensión de verdad absoluta, un movimiento mesiánico, instituciones de terror, monopolio de las comunicaciones y de las fuerzas armadas, y sobre todo un intento de **Estado panóptico** que borra la distinción entre lo público y lo privado. El nombre remite al panóptico, el diseño carcelario que Jeremy Bentham imagina a fines del siglo XVIII para que un solo vigilante, sin ser visto, pueda observar en cualquier momento a todos los reclusos.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "El poder soviético aspira a algo parecido a escala de un país entero, donde nadie puede saber si en ese instante está siendo observado y por eso se comporta como si siempre lo estuviera.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "Los bolcheviques toman al pie de la letra la idea ilustrada de la **perfectibilidad** humana: si se conoce el mundo, se lo puede remodelar, y los escritores e intelectuales al servicio del régimen se conciben como \"ingenieros de almas humanas\", encargados de producir un hombre nuevo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "Ese proyecto choca con un problema que ya habían enfrentado los revolucionarios franceses: quienes hacen la revolución llegan formados por el régimen que buscan destruir, con las marcas de la vieja opresión todavía encima. Es el problema de Moisés, que saca a los hebreos de Egipto pero debe esperar cuarenta años en el desierto a que muera la generación con mentalidad de esclavos, porque sólo la siguiente puede entrar en la tierra prometida: ¿pueden las personas transformarse a mitad de camino, o hace falta empezar de nuevo con la generación próxima?",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "La meta bolchevique es que la conciencia individual se identifique tan por completo con las leyes de la historia que no quede distinción entre el **yo** y el **nosotros**: la versión soviética, tomada al pie de la letra, de la fórmula hegeliana según la cual el Geist es \"el yo que es un nosotros y el nosotros que es un yo\". Todo lo subjetivo que no coincida con lo colectivo debe ser purgado.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: el sujeto bajo el totalitarismo",
      body: "La novela Nosotros (1924), de Yevgueni Zamiatin —inspiración reconocida de 1984 de Orwell—, lleva esa lógica a su extremo distópico: el \"nosotros\" se presenta ahí como del lado de Dios, y el \"yo\" como una tentación que hay que vencer.",
    },
    {
      type: "quiz",
      question: "¿Qué aspira a lograr el Estado panóptico soviético, según la clase?",
      options: [
        "Que cada quien actúe como si siempre lo observaran",
        "Que cada ciudadano vigile sólo a sus propios vecinos",
        "Que la policía secreta reemplace a todo el aparato judicial",
        "Que el Partido conozca sólo los delitos ya cometidos",
      ],
      answer: 0,
      explain: "El nombre remite al panóptico de Bentham: un vigilante que observa a los reclusos sin ser visto. El poder soviético aspira a algo así a escala de un país entero, borrando lo público y lo privado.",
    },
    {
      type: "info",
      title: "Freud invierte el modelo",
      body: "Freud entra en esta dialéctica yo/nosotros invirtiéndola: vuelve a la primera persona del singular, hace del individuo el punto de partida, y sólo desde ahí llega a una teoría de la sociedad. Agrega además un dualismo nuevo, interior al sujeto mismo: no sólo lo subjetivo frente a lo objetivo, sino **lo consciente frente a lo inconsciente**. Donde Rosa Luxemburg identificaba lo inconsciente con lo objetivo —la lógica del proceso histórico precede a la lógica subjetiva—, Freud perfora esa misma distinción hacia adentro de la subjetividad.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud invierte el modelo",
      body: "Freud es un pensador especulativo y a veces desmedido, un personaje casi salvaje en la audacia con que generaliza a partir de un puñado de casos clínicos vieneses hasta abarcar la condición humana entera. Algunas de sus ideas se descartaron hace tiempo, y otras hoy se consideran indemostrables o directamente erróneas; pero muchas se absorbieron tan hondo en el lenguaje común que ya no se le atribuyen conscientemente: **inconsciente**, complejo de Edipo, neurosis, actos fallidos —los llamados \"lapsus freudianos\"—, rivalidad entre hermanos, narcisismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud invierte el modelo",
      body: "Hablar hoy de un \"lapsus\" o de estar \"reprimido\" es, sin saberlo casi nunca, hablar en términos freudianos.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud invierte el modelo",
      body: "Como Marx, Freud es un teórico de la modernidad, y hace una pregunta parecida a la suya: por qué la vida moderna produce infelicidad. Donde Marx encuentra la respuesta en la estructura económica y en la explotación de una clase por otra, Freud la busca en la estructura misma de la mente y en el precio psíquico que exige cualquier forma de vida en común, sea cual sea el régimen económico que la organice.",
    },
    {
      type: "quiz",
      question: "¿Cómo invierte Freud el modelo bolchevique de fusionar el yo en el nosotros?",
      options: [
        "Vuelve al individuo y lo divide en consciente e inconsciente",
        "Diluye igual el yo en el nosotros, pero por otra vía",
        "Niega que exista el inconsciente y se queda con la conciencia",
        "Sostiene que el yo es transparente y plenamente racional",
      ],
      answer: 0,
      explain: "Donde el bolchevismo busca fundir el yo en el nosotros, Freud regresa a la primera persona del singular y suma un dualismo nuevo, consciente/inconsciente, que corta por dentro del propio sujeto.",
    },
    {
      type: "info",
      title: "Formación: de la neurología a la histeria",
      body: "En la década de 1870 Freud se forma en fisiología y neurología, en plena era positivista, con su inclinación materialista y empirista: la idea de que la biología y la psicología se explican por fuerzas puramente físicas. Rompe con eso al sostener que **la mente puede ser causa de sus propias enfermedades**, que las ideas mismas pueden enfermar —una tesis radical para la época, hoy asimilada sin más—.",
    },
    {
      type: "info",
      continues: true,
      title: "Formación: de la neurología a la histeria",
      body: "Interesado en la entonces llamada **histeria**, que se atribuía a un mal funcionamiento del útero y por eso se creía exclusiva de las mujeres, Freud se rebela contra esa explicación orgánica y busca la causa en estímulos mentales: retoma así, y radicaliza, el método catártico que había ensayado con Breuer en el tratamiento de Anna O.",
    },
    {
      type: "quiz",
      question: "¿Qué idea rompe Freud con el positivismo médico de su formación inicial?",
      options: [
        "Que la mente puede causar sus propias enfermedades",
        "Que la histeria sólo afecta a mujeres con daño en el útero",
        "Que toda enfermedad mental tiene siempre origen genético",
        "Que la neurología no tiene nada que aportar a la psiquiatría",
      ],
      answer: 0,
      explain: "Freud se forma en fisiología y neurología positivistas, pero rompe con esa tradición al sostener que las ideas mismas pueden enfermar, sin necesidad de una lesión orgánica que lo explique.",
    },
    {
      type: "info",
      title: "Del trauma real a la fantasía",
      body: "Freud plantea primero que la histeria es resultado de un **trauma infantil reprimido**, casi siempre algún tipo de abuso o seducción sexual, que vuelve disfrazado como síntoma neurótico: la gente puede enfermar por **recuerdos**, hechos reales con efectos reales sobre la salud. Es un planteo ya radical dentro del positivismo médico de la época.",
    },
    {
      type: "info",
      continues: true,
      title: "Del trauma real a la fantasía",
      body: "Después lo revisa: no hace falta que el hecho traumático haya ocurrido realmente, basta con que haya sido imaginado, fantaseado o deseado. Es una ruptura todavía mayor con el positivismo, porque la enfermedad puede no tener conexión con ningún hecho empírico tangible, y puede ser puramente mental. De ahí un **psicologismo**: la vida psíquica se explica en sus propios términos, no como derivación de un proceso biológico.",
    },
    {
      type: "info",
      continues: true,
      title: "Del trauma real a la fantasía",
      body: "Si hubiera que resumir en una fórmula esta primera etapa de la teoría freudiana, podría decirse que todo síntoma remite, en último término, a una represión de origen sexual: la variante de cada caso cambia, pero el mecanismo de fondo —un deseo inadmisible que se reprime y retorna disfrazado— se repite una y otra vez. Esa insistencia en lo sexual como causa última es, junto con la del inconsciente, la tesis que más escándalo produce en la Viena de fin de siglo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Freud al mecanismo que empuja un deseo inadmisible al inconsciente?",
      answers: ["represión"],
      explain: "Freud revisa su primera teoría: no hace falta que el trauma haya ocurrido realmente, alcanza con que haya sido fantaseado. Lo común a todo síntoma es ese mecanismo de represión de origen sexual.",
    },
    {
      type: "info",
      title: "El psicoanálisis como método",
      body: "Freud usa por primera vez el término \"**psicoanálisis**\" en 1896. En 1902 es nombrado profesor asociado en Viena, y en 1908 se funda la Sociedad Psicoanalítica de Viena, ciudad con la que el movimiento queda asociado de manera indeleble. Entre sus discípulos se producen escisiones tempranas: Jung rompe hacia 1913, Adler un poco antes, cada uno con su propia revisión de la teoría.",
    },
    {
      type: "info",
      continues: true,
      title: "El psicoanálisis como método",
      body: "Las ideas de Freud se popularizan durante la Primera Guerra Mundial, a partir de las conferencias universitarias de 1915-1917 que se vuelven el libro Lecciones introductorias al psicoanálisis (1917): ahí gana un público amplio, más allá del círculo médico vienés.",
    },
    {
      type: "info",
      title: "Primera tópica: consciente, preconsciente, inconsciente",
      body: "En La interpretación de los sueños (1899, publicado con fecha de 1900) Freud presenta su primer modelo de la mente, la **primera tópica**: divide la vida psíquica en tres capas, **consciente, preconsciente e inconsciente**. Es un modelo estructural, en el que las partes sólo se entienden en su relación con el todo, y la capa sumergida, el inconsciente, es la más causal y formativa, en un paralelo con la base y la superestructura marxistas.",
    },
    {
      type: "info",
      continues: true,
      title: "Primera tópica: consciente, preconsciente, inconsciente",
      body: "El inconsciente se induce a revelarse, pero nunca se revela del todo: es el asiento de deseos reprimidos que se escurren de forma insidiosa en síntomas, culpa y sublimaciones. Como todos tenemos algún trauma reprimido, se sigue que todos estamos, en algún grado, enfermos mentales.",
    },
    {
      type: "info",
      continues: true,
      title: "Primera tópica: consciente, preconsciente, inconsciente",
      body: "Freud sabe que esto es perturbador y se muestra a la defensiva:",
    },
    {
      type: "info",
      continues: true,
      title: "Primera tópica: consciente, preconsciente, inconsciente",
      body: "La primera de estas proposiciones desagradables del psicoanálisis es que los procesos mentales son esencialmente inconscientes, y que los que son conscientes no son más que actos aislados y partes de la totalidad psíquica. […] Al sostener que hay tal cosa como un pensar inconsciente y un desear inconsciente, el psicoanálisis ha perdido de entrada la simpatía de los espíritus sobrios y científicos, y ha incurrido en la sospecha de ser un culto fantástico ocupado en misterios oscuros e insondables.",
    },
    {
      type: "info",
      continues: true,
      title: "Primera tópica: consciente, preconsciente, inconsciente",
      body: "Parece una vana disputa de palabras discutir si la vida mental coincide con la conciencia o se extiende más allá de ese límite; sin embargo, aceptar los procesos mentales inconscientes representa un paso decisivo hacia una nueva orientación en el mundo y en la ciencia.",
    },
    {
      type: "quiz",
      question: "En La interpretación de los sueños, ¿qué modelo de la mente presenta Freud por primera vez?",
      options: [
        "Consciente, preconsciente e inconsciente",
        "Ello, yo y superyó, en tres instancias distintas",
        "Eros y Tánatos, como dos pulsiones opuestas",
        "Una sola instancia unificada y transparente",
      ],
      answer: 0,
      explain: "Es la primera tópica (1899): un modelo de capas donde el inconsciente es la más causal y formativa, en un paralelo con la base y la superestructura marxistas.",
    },
    {
      type: "info",
      title: "Infancia, sexualidad y complejo de Edipo",
      body: "El inconsciente empieza muy temprano: para Freud la infancia, incluso el nacimiento, es un momento formativo y necesariamente traumático. De ahí otra tesis perturbadora: **la sexualidad empieza en la infancia**. La definición freudiana de lo sexual es muy amplia, muy por encima del coito genital; la \"sexualidad infantil\" no implica que los bebés tengan relaciones sexuales, sino que tienen deseos que exceden lo genital.",
    },
    {
      type: "info",
      continues: true,
      title: "Infancia, sexualidad y complejo de Edipo",
      body: "Las neurosis son una cuestión de **grado**: todos somos reprimidos en la infancia, crecer es reprimir, vivir es reprimir; ser apenas un poco neurótico o francamente psicótico es un punto en un continuo, no una diferencia de naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "Infancia, sexualidad y complejo de Edipo",
      body: "El **complejo de Edipo** toma su nombre del Edipo Rey de Sófocles, destinado a matar a su padre y casarse con su madre pese a hacer todo por evitarlo. Freud plantea una etapa formativa en la que el niño transfiere su objeto de amor del pecho a la madre, la desea, resiente al padre que se interpone y llega a desear secretamente su muerte. No sostiene que la mayoría de los niños maten a sus padres: le basta con que el pensamiento aparezca, aunque sea de forma fugaz, en la mente o en un sueño.",
    },
    {
      type: "info",
      continues: true,
      title: "Infancia, sexualidad y complejo de Edipo",
      body: "Esos deseos se reprimen enseguida, se empujan al inconsciente, y desde ahí, como todo lo reprimido, tienden a volver.",
    },
    {
      type: "quiz",
      question: "¿Qué le basta a Freud para hablar de complejo de Edipo en un niño?",
      options: [
        "Que el deseo aparezca, fugaz, en un sueño",
        "Que efectivamente intente hacerle daño a su padre",
        "Que la madre fomente ese deseo de forma consciente",
        "Que el niño haya sufrido un abuso real y comprobable",
      ],
      answer: 0,
      explain: "Freud no dice que los niños maten a sus padres. Le alcanza con que la fantasía aparezca un instante o en un sueño: ese deseo se reprime enseguida y se empuja al inconsciente, de donde tiende a volver.",
    },
    {
      type: "info",
      title: "Segunda tópica: ello, yo y superyó",
      body: "En El yo y el ello (1923) Freud reformula el modelo en tres instancias —**ello, yo y superyó**—, conocidas como la **segunda tópica** o modelo estructural, que se superpone, sin reemplazarlo, al de consciente/preconsciente/inconsciente. El das Es, el ello, es puro deseo, básicamente inconsciente, y se subdivide en dos pulsiones que Freud postula como primordiales, sin derivarlas de nada anterior: **Eros**, la pulsión de vida —deseo, sexo, placer—, y **Tánatos**, la pulsión de muerte —agresión, destrucción, ira—.",
    },
    {
      type: "info",
      continues: true,
      title: "Segunda tópica: ello, yo y superyó",
      body: "El superyó (das Über-Ich) es la conciencia moral, no la conciencia a secas: la voz que juzga lo que está bien o mal, fuente de la **culpa**, y que Freud entiende como la sociedad internalizada. El yo (das Ich) queda en la posición de negociar constantemente entre las exigencias del ello y las prohibiciones del superyó: una vez aceptado el modelo, resulta obvio por qué el yo está siempre, en algún grado, en conflicto consigo mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Segunda tópica: ello, yo y superyó",
      body: "Freud necesita este segundo modelo porque el primero, el de consciente/preconsciente/inconsciente, no alcanza para explicar un hecho clínico incómodo: buena parte de la defensa contra un deseo inaceptable —la represión misma, el mecanismo que empuja algo al inconsciente— ocurre sin que el sujeto sea consciente de estar defendiéndose. El yo, entonces, no puede identificarse sin más con la conciencia: opera también él, en parte, de manera inconsciente, y de ahí la necesidad de una segunda topografía que distinga instancias antes que capas.",
    },
    {
      type: "info",
      continues: true,
      title: "Segunda tópica: ello, yo y superyó",
      body: "Ninguna de las tres instancias es buena ni mala en sí misma: el ello no es el villano ni el superyó el héroe. El sufrimiento neurótico surge, precisamente, cuando el equilibrio entre las tres se vuelve demasiado rígido o demasiado costoso de sostener, y el yo gasta en esa negociación interna una cantidad de energía psíquica que no le queda disponible para nada más.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde a la primera o a la segunda tópica?",
      groups: ["Primera tópica", "Segunda tópica"],
      items: [
        { text: "Divide la mente en consciente, preconsciente e inconsciente", group: 0 },
        { text: "Es el modelo de 1899, de La interpretación de los sueños", group: 0 },
        { text: "Divide la mente en ello, yo y superyó", group: 1 },
        { text: "Aparece en El yo y el ello, de 1923", group: 1 },
        { text: "Explica que la represión misma puede ser inconsciente", group: 1 },
      ],
      explain: "El primer modelo (1899) es de capas: consciente, preconsciente, inconsciente. El segundo (1923) es de instancias porque hace falta explicar que la represión misma, no sólo lo reprimido, puede operar sin que el sujeto lo sepa.",
    },
    {
      type: "match",
      question: "Uní cada instancia o pulsión con lo que le corresponde",
      pairs: [
        { left: "Ello (das Es)", right: "Puro libido y deseo, inconsciente" },
        { left: "Yo (das Ich)", right: "El que negocia entre las otras dos instancias" },
        { left: "Superyó (das Über-Ich)", right: "La conciencia moral: culpa y sociedad internalizada" },
        { left: "Eros", right: "La pulsión de vida: deseo, sexo, placer" },
        { left: "Tánatos", right: "La pulsión de muerte: agresión e ira" },
      ],
      explain: "El aparato psíquico freudiano es una estructura en tensión: el ello empuja (Eros y Tánatos), el superyó prohíbe y culpabiliza, y el yo media entre ambos. Como es un sistema cerrado, la energía reprimida no desaparece: vuelve por otra puerta.",
    },
    {
      type: "info",
      title: "Energía psíquica y el retorno de lo reprimido",
      body: "Freud concibe estas pulsiones como **universales**, cableadas en cualquier persona sin importar dónde viva o qué lengua hable; Hannah Arendt observó, no sin ironía, que si Freud no hubiera vivido rodeado de judíos austrohúngaros germanoparlantes que leían a Goethe y Shakespeare en Viena, quizá nunca se habría oído hablar del complejo de Edipo.",
    },
    {
      type: "info",
      continues: true,
      title: "Energía psíquica y el retorno de lo reprimido",
      body: "El yo funciona, además, como un **sistema energético cerrado**: la energía psíquica se traslada de una conducta a otra pero no desaparece, en un principio de **suma cero**. Hay mucha **sublimación**, y los deseos reprimidos, que no pueden eliminarse del todo, vuelven de alguna forma —el llamado **retorno de lo reprimido**—. El psicoanalista Yurko Prokhasko lo describió con una imagen simple: lo que se empuja por la puerta vuelve a entrar trepando por la ventana. La agresión frustrada, en particular, se vuelve hacia adentro, contra uno mismo.",
    },
    {
      type: "quiz",
      question: "¿Qué implica pensar el yo como un sistema energético cerrado?",
      options: [
        "Que la energía reprimida no desaparece, sólo cambia de forma",
        "Que toda la energía psíquica se agota con la edad",
        "Que el inconsciente no consume ninguna energía",
        "Que la sublimación elimina por completo el deseo",
      ],
      answer: 0,
      explain: "Es un principio de suma cero: lo que se empuja al inconsciente vuelve de alguna forma, como en la imagen de lo que sale por la puerta y entra de nuevo por la ventana. La agresión frustrada se vuelve hacia adentro.",
    },
    {
      type: "info",
      title: "La práctica analítica: la palabra y la transferencia",
      body: "El psicoanálisis es, en su forma más simple, sentarse a hablar con un analista para inducir al inconsciente a revelarse: no se revela del todo, pero algo se escurre por las grietas, y eso no cura mágicamente, aunque permite lidiar con ello. La técnica es la **asociación libre** —hablar lo más libremente posible, acostado en un diván, varias veces por semana— y no admite un tercero observando; por eso quien se forma como analista debe antes pasar por su propio análisis.",
    },
    {
      type: "info",
      continues: true,
      title: "La práctica analítica: la palabra y la transferencia",
      body: "Un concepto central de la técnica, la **transferencia**, no está en el planteo inicial pero se vuelve indispensable: en el curso del tratamiento el paciente proyecta sobre el analista sentimientos, deseos y conflictos que en su origen apuntaban a figuras parentales. Lejos de ser sólo un obstáculo, esa transferencia es el material mismo con el que trabaja el análisis: revivir el conflicto infantil frente al analista permite elaborarlo de un modo que la sola palabra sobre el pasado no alcanza a lograr.",
    },
    {
      type: "info",
      continues: true,
      title: "La práctica analítica: la palabra y la transferencia",
      body: "Lo muy **burgués** del dispositivo es que exige una inversión considerable de dinero y de tiempo libre: el psicoanálisis clásico nace, y se practica largamente, dentro de los límites de una clase social específica, la misma que tiene el ocio necesario para hablar de sí varias horas por semana durante años.",
    },
    {
      type: "info",
      continues: true,
      title: "La práctica analítica: la palabra y la transferencia",
      body: "El analista, además, se mantiene deliberadamente neutral y opaco: no da consejos, no cuenta su propia vida, no corrige ni aprueba, para que el paciente pueda proyectar sobre esa pantalla en blanco las figuras de su propia historia sin interferencias. Esa neutralidad técnica —que Freud llama, con otra palabra, **abstinencia**— es lo que permite que la transferencia se despliegue con la menor distorsión posible.",
    },
    {
      type: "quiz",
      question: "En la técnica analítica, ¿qué es la transferencia?",
      options: [
        "El paciente proyecta en el analista sentimientos parentales",
        "El analista le transfiere al paciente su propia experiencia",
        "El paciente cambia de analista en medio del tratamiento",
        "El síntoma pasa de un órgano del cuerpo a otro",
      ],
      answer: 0,
      explain: "El paciente proyecta sobre el analista sentimientos y conflictos que originalmente apuntaban a figuras parentales. Lejos de ser sólo un obstáculo, es el material con el que trabaja el análisis.",
    },
    {
      type: "info",
      title: "Del yo a la sociedad: la religión como ilusión",
      body: "Freud es ateo, y le dedica a la religión un ensayo propio, El porvenir de una ilusión (1927): la religión es, para él, una **ilusión** ligada a la relación infantil con el padre. El niño desea eliminar al padre y poseer a la madre, pero llega el momento en que descubre que el padre **no es omnipotente**, que no puede protegerlo de todos los horrores del mundo; entonces transfiere ese deseo de un padre todopoderoso a otra instancia, **Dios**.",
    },
    {
      type: "info",
      continues: true,
      title: "Del yo a la sociedad: la religión como ilusión",
      body: "Para Freud, Dios es un fenómeno infantil: se desea que exista un ser eterno y omnipotente que cuide, pero no existe, y esa es la ilusión religiosa. Llamarla \"ilusión\" no significa, aclara Freud, que sea necesariamente falsa en un sentido lógico, sino que su fuerza no proviene de ninguna evidencia, sino del deseo que la sostiene: se cree en ella porque hace falta creer, no porque los hechos la respalden.",
    },
    {
      type: "quiz",
      question: "Para Freud en El porvenir de una ilusión, ¿de dónde surge la idea de Dios?",
      options: [
        "De transferir a Dios el deseo de un padre todopoderoso",
        "De una revelación que el propio Freud no discute",
        "De un miedo racional y bien fundado a la muerte",
        "De la necesidad económica de organizar el trabajo",
      ],
      answer: 0,
      explain: "El niño descubre que su padre no es omnipotente, y transfiere ese deseo de protección total a otra instancia, Dios. Para Freud es una ilusión: no se cree por evidencia, sino porque hace falta creer.",
    },
    {
      type: "info",
      title: "El malestar en la cultura (1930)",
      body: "En este ensayo —también traducido como El malestar en la civilización— Freud retoma las discusiones ilustradas sobre el estado de naturaleza y la vida en sociedad. Por **civilización** entiende, en sentido amplio, tanto los logros materiales como el hecho mismo de vivir juntos. Se ubica del lado de quienes creen que la sociedad produce infelicidad, en una inversión del argumento rousseauniano: la civilización se basa en la represión tanto de Eros como de Tánatos, necesaria para la convivencia.",
    },
    {
      type: "info",
      continues: true,
      title: "El malestar en la cultura (1930)",
      body: "El estado de naturaleza es un estado de libertad, pero incluye una amenaza perpetua de violencia y agresión: convivir es **psíquicamente costoso**, porque el deseo de agredir y matar sigue ahí, reprimido, y cuanta más energía se gasta en vencerlo, menos queda disponible para el placer; esa agresión reprimida se vuelve hacia adentro. Si para Hobbes la sociedad cambia libertad por seguridad, para Freud cambia **felicidad por seguridad**: el **principio de placer** queda necesariamente reñido con el **principio de realidad** que hace posible la vida en común.",
    },
    {
      type: "info",
      continues: true,
      title: "El malestar en la cultura (1930)",
      body: "Creemos que la civilización se ha creado bajo la presión de las exigencias de la vida, a costa de la satisfacción de los instintos, y que en gran medida se recrea constantemente, ya que cada individuo que entra de nuevo en la sociedad humana repite ese sacrificio de la satisfacción instintiva en beneficio de la comunidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El malestar en la cultura (1930)",
      body: "Para Freud no hay alternativa: no sostiene que haya que vivir violando y matando, sino que esa tensión —entre lo que se desea y lo que la vida social permite— es, sin salida posible, la condición humana.",
    },
    {
      type: "quiz",
      question: "Según El malestar en la cultura, ¿qué intercambio impone la vida en sociedad?",
      options: [
        "Cambia felicidad por seguridad, reprimiendo los instintos",
        "Cambia seguridad por libertad, como plantea Locke",
        "Elimina por completo la agresión humana con educación",
        "Cambia razón por fe, y así restaura la religión",
      ],
      answer: 0,
      explain: "Donde Hobbes cambiaba libertad por seguridad, Freud dice que la civilización cambia felicidad por seguridad. Convivir exige reprimir los instintos, y esa represión drena la energía que iría al placer.",
    },
    {
      type: "info",
      title: "Freud frente a Marx",
      body: "Freud comparte rasgos de método con el marxismo, aunque llegue a ellos por un camino completamente distinto. Ambos tienen un alcance grandioso, una ambición de explicarlo todo desde un solo principio. Ambos proponen un modelo de dos capas en el que la superficie visible depende de algo oculto y más determinante: en Marx, la conciencia depende de la base económica; en Freud, la conducta consciente depende del inconsciente.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud frente a Marx",
      body: "Y ambos comparten cierto **determinismo monocausal** —no temporal, como en Marx, para quien todo avanza hacia un fin necesario, sino individual: hay en cada persona factores cableados de antemano que determinan buena parte de quién es—.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud frente a Marx",
      body: "Para Freud todo remite, en último término, a la represión; para Marx, todo remite a la lucha de clases. Simone de Beauvoir criticará más tarde la insuficiencia de ambas explicaciones monocausales para dar cuenta de la situación de las mujeres, que no se reduce sin más ni a lo económico ni a lo pulsional.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud frente a Marx",
      body: "Los dos son, además, estructuralistas antes de que exista la palabra: el sentido no está en los elementos aislados sino en cómo se relacionan entre sí, y las partes sólo se entienden juntas. Donde para Marx la religión es el opio de los pueblos, un narcótico que la clase dominante administra, para Freud es una ilusión infantil que obstruye el acceso a la realidad psíquica, pero en ambos casos cumple la misma función de consuelo que impide ver la verdad de la propia condición.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud frente a Marx",
      body: "La diferencia central es que Freud es **antimaterialista**: lo que la propiedad privada es para Marx, motor y objeto último del conflicto social, la sexualidad lo es para Freud, y la **culpa** ocupa en su sistema el lugar que el **poder** ocupará después en la obra de Foucault —dispersa, implícita en toda relación, sin un centro único desde donde se ejerce—.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud frente a Marx",
      body: "Freud objeta a los marxistas que no cuentan con **Tánatos**: creen que basta cambiar las condiciones materiales de producción para que desaparezcan los instintos agresivos, pero para Freud esos instintos están cableados en la especie, son anteriores al capitalismo y no los crea la propiedad privada, de modo que ninguna revolución social los va a eliminar.",
    },
    {
      type: "info",
      continues: true,
      title: "Freud frente a Marx",
      body: "Los marxistas, a su vez, verán en el psicoanálisis el último intento burgués de frenar la revolución disfrazándola de enfermedad individual.",
    },
    {
      type: "classify",
      question: "¿Cada tesis es de Freud o de Marx?",
      groups: ["Freud", "Marx"],
      items: [
        { text: "La raíz de todo es la represión sexual", group: 0 },
        { text: "La raíz de todo es la lucha de clases", group: 1 },
        { text: "La religión es una ilusión infantil", group: 0 },
        { text: "La religión es el opio de los pueblos", group: 1 },
        { text: "La agresión (Tánatos) está cableada, es anterior al capitalismo", group: 0 },
        { text: "Cambiando las condiciones materiales se supera la alienación", group: 1 },
      ],
      explain: "Freud y Marx comparten la ambición monocausal, pero cada uno pone otra cosa en el fondo: represión y sexualidad frente a lucha de clases y propiedad. Por eso Freud no cree en el «felices para siempre»: los instintos no se abolen cambiando las condiciones.",
    },
    {
      type: "info",
      title: "Herencia",
      body: "Para Freud, el yo **no es idéntico a sí mismo**: está siempre en conflicto consigo mismo y nunca es enteramente transparente para sí. No podemos conocernos del todo, porque lo más fundamental de nosotros permanece oculto en el inconsciente; hay en esto una herencia romántica, el yo como misterio que no se agota en la introspección.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "El psicoanálisis es, a la vez, una teoría de la personalidad, una teoría de la sociedad y una práctica clínica; puede describirse también como una teoría de la vida después de la muerte de Dios: rechaza a Dios, pero encuentra ventanas por las que ese anhelo de lo absoluto vuelve a colarse. A diferencia del marxismo, aquí no hay salida prometida: el análisis puede aliviar síntomas, pero el yo sigue en conflicto consigo mismo y ninguna reorganización social garantiza la felicidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "Esa imagen de un sujeto no transparente, dividido contra sí mismo y atravesado por fuerzas que no controla, es la que hereda el arte europeo de las décadas siguientes. El modernismo y las vanguardias —futurismo, dadaísmo, cubismo, expresionismo, surrealismo— encuentran en el inconsciente freudiano una fuente directa para fragmentar la forma y la voz narrativa tradicionales: la técnica del monólogo interior en la novela, el collage de imágenes sin conexión lógica, la desconfianza generalizada hacia un yo unificado que hable con una sola voz coherente.",
    },
    {
      type: "match",
      question: "Uní cada nombre u obra con lo que le corresponde",
      pairs: [
        { left: "Anna O.", right: "El caso que origina el método catártico" },
        { left: "La interpretación de los sueños", right: "El libro de 1899 con la primera tópica" },
        { left: "El yo y el ello", right: "El libro de 1923 con la segunda tópica" },
        { left: "El porvenir de una ilusión", right: "El ensayo de 1927 sobre la religión" },
        { left: "André Breton", right: "Funda el surrealismo con la escritura automática" },
      ],
      explain: "El psicoanálisis se arma en etapas: el caso de Anna O. con Breuer, la primera tópica en 1899, la segunda en 1923, y la crítica a la religión en 1927; su herencia llega intacta hasta el surrealismo de Breton.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia",
      body: "El caso más explícito es el del **surrealismo**: André Breton, formado parcialmente en psiquiatría y en contacto con la teoría freudiana, funda el movimiento con el Manifiesto del surrealismo de 1924, que propone la **escritura automática** —dejar fluir la mano sin control consciente— como método para acceder directamente al material que Freud había situado en el inconsciente. Donde el psicoanálisis busca ese material para curar un síntoma, el surrealismo lo busca para producir una obra: la cura y el arte convergen, por un momento, en el mismo territorio.",
    },
  ],
};
