export default {
  num: 20,
  transcript: 21,
  title: "Poder y arqueología: Michel Foucault",
  source: "https://www.youtube.com/watch?v=tyeGAGus-oY",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Michel Foucault** (1926-1984) nace en Poitiers y se forma en la École Normale Supérieure, donde obtiene la agregación de filosofía. Enseña en Túnez, Clermont-Ferrand y Vincennes antes de ocupar, desde 1970 y hasta su muerte, la cátedra de Historia de los sistemas de pensamiento en el Collège de France.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En 1971 funda, junto con otros intelectuales, el Grupo de Información sobre las Prisiones, que documenta las condiciones de detención en Francia y alimenta directamente la investigación de Vigilar y castigar. Muere en 1984, a los 58 años, de una enfermedad asociada al sida, cuando el virus recién empezaba a hacerse público y estaba doblemente estigmatizado: por el miedo al contagio y por su asociación con la homosexualidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Cuatro libros ordenan su obra en dos períodos. Historia de la locura en la época clásica (1961) y Las palabras y las cosas (1966) pertenecen al período **arqueológico**; Vigilar y castigar (1975) y el primer tomo de Historia de la sexualidad (1976) pertenecen al período **genealógico**, centrado en el poder. Entre ambos, La arqueología del saber (1969) expone su método.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Se forma en diálogo con Marx, Nietzsche, Heidegger, Sartre y Lévi-Strauss, y llega a la escena francesa después de Sartre y de Lévi-Strauss —de Sartre dirá que fue un hombre del siglo XIX intentando pensar el siglo XX—. Sostuvo que su desarrollo filosófico entero estuvo determinado por la lectura de Heidegger, aunque para varios comentaristas fue **Nietzsche**, leído a través de Heidegger, la influencia más decisiva.",
    },
    {
      type: "quiz",
      question: "¿Qué dice Foucault sobre la relación de Sartre con su propio siglo?",
      options: [
        "Que fue un hombre del siglo XIX intentando pensar el XX",
        "Que fue el primer pensador genuinamente posestructuralista",
        "Que superó por completo a Heidegger en su lectura del ser",
        "Que anticipó con exactitud el estructuralismo de Lévi-Strauss",
      ],
      answer: 0,
      explain: "Foucault llega a la escena francesa después de Sartre y de Lévi-Strauss, y juzga a Sartre como un hombre del siglo XIX que intentaba pensar el siglo XX: todavía atado a la soberanía del sujeto que Foucault busca disolver.",
    },
    {
      type: "info",
      title: "El problema que hereda: reemplazar a Dios, disolver al sujeto",
      body: "La modernidad europea giró en buena medida en torno a **reemplazar a Dios**: primero se lo relega a un costado, después se lo declara muerto, y queda un vacío que cumplía a la vez funciones epistemológicas, ontológicas y éticas. Tres candidatos ocuparon ese lugar: el **sujeto humano**, la **Historia** con mayúscula que avanza en el tiempo, y la **estructura** que mantiene unido el sistema.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: reemplazar a Dios, disolver al sujeto",
      body: "El estructuralismo de Lévi-Strauss fue, en ese sentido, el último gran intento de reemplazo: el significado deja de ser intrínseco y pasa a ser relacional, dependiente de un sistema, pero para eso hace falta postular una estructura estable y cerrada. Ya no hay Dios, hay estructura; ya no hay Historia con dirección propia, hay un sistema sincrónico que se explica a sí mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: reemplazar a Dios, disolver al sujeto",
      body: "Foucault empieza su obra en rebelión contra la tradición **fenomenológico-existencialista** y su noción de la **soberanía del sujeto**: la idea, que atraviesa por igual a Descartes, Husserl, Heidegger y Sartre, de que hay siempre un yo del que no se puede dudar —el cogito, el ego trascendental, el Dasein, la libertad radical—, un punto fijo desde el cual se ordena todo conocimiento posible.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: reemplazar a Dios, disolver al sujeto",
      body: "[La noción moderna de la soberanía del sujeto] ha desempeñado un papel constante para preservar, contra todo descentramiento, la soberanía del sujeto y las figuras gemelas de la antropología y el humanismo. Contra el descentramiento operado por Marx… opuso la búsqueda de una historia total; contra el descentramiento operado por la genealogía nietzscheana, opuso la búsqueda de un fundamento originario que hiciera de la racionalidad el telos de la humanidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: reemplazar a Dios, disolver al sujeto",
      body: "Foucault rechaza ese fundamento del sujeto y ocupa una posición liminal entre el estructuralismo y un posestructuralismo más radical, el que asumirá después Derrida. Con él, la agencia deja de residir en un yo soberano y se reubica en el **lenguaje**, en el **discurso**: el sistema de signos ocupa el lugar que antes ocupaba Dios, y sujeto y objeto quedan puestos entre paréntesis.",
    },
    {
      type: "quiz",
      question: "¿Qué comparten Descartes, Husserl, Heidegger y Sartre, según la crítica de Foucault?",
      options: [
        "El rechazo explícito de cualquier forma de subjetividad",
        "La convicción de que la Historia carece por completo de sentido",
        "Un yo fijo del que no se duda, origen de todo el saber",
        "Haber sido, todos ellos, discípulos directos de Nietzsche",
      ],
      answer: 2,
      explain: "El cogito, el ego trascendental, el Dasein, la libertad radical: distintos nombres para la misma soberanía del sujeto, un punto fijo desde el cual se ordena todo conocimiento posible. Foucault rechaza ese fundamento común.",
    },
    {
      type: "info",
      title: "Del lenguaje al discurso: el giro posestructuralista",
      body: "Foucault toma del estructuralismo la tesis de que el significado es relacional: Todo enunciado está especificado; no hay enunciado en general, libre, neutral, independiente. Un enunciado pertenece siempre a una serie o a un todo, juega un papel entre otros enunciados, se apoya en ellos y se distingue de ellos: siempre es parte de una red de enunciados.",
    },
    {
      type: "info",
      continues: true,
      title: "Del lenguaje al discurso: el giro posestructuralista",
      body: "Pero da un giro posestructuralista: a diferencia del sistema cerrado de Lévi-Strauss, para Foucault **la estructura nunca termina de cerrarse**; las fronteras de un discurso, como las de un libro, nunca son netas, y la red de referencias sigue abriéndose.",
    },
    {
      type: "info",
      continues: true,
      title: "Del lenguaje al discurso: el giro posestructuralista",
      body: "El desplazamiento del **lenguaje** al **discurso** —una noción más cargada, que apunta no sólo a las palabras sino a cómo una época entera habla de las cosas— permite estudiar el sentido sin apelar ni a un sujeto que lo produzca ni a una estructura que termine de cerrarlo.",
    },
    {
      type: "quiz",
      question: "¿Qué diferencia al «discurso» foucaultiano del sistema cerrado de Lévi-Strauss?",
      options: [
        "El discurso no depende en absoluto de la noción de diferencia",
        "El discurso no admite ningún tipo de análisis histórico",
        "Lévi-Strauss ya había abandonado la idea de sistema cerrado",
        "El discurso nunca termina de cerrarse del todo sobre sí",
      ],
      answer: 3,
      explain: "Foucault toma del estructuralismo la tesis de que el significado es relacional, pero da un giro posestructuralista: a diferencia del sistema cerrado de Lévi-Strauss, las fronteras de un discurso nunca son netas y la red sigue abriéndose.",
    },
    {
      type: "info",
      title: "El método arqueológico y la noción de episteme",
      body: "Foucault llama a su método **arqueología**: no una excavación en el mundo físico, sino en las capas del discurso. En Las palabras y las cosas (1966) —subtitulada, significativamente, \"una arqueología de las ciencias humanas\"— rastrea cómo cambió, en distintos períodos históricos, la organización profunda del saber occidental. El libro fue un éxito inmediato pese a su dificultad y lo convirtió en una figura pública.",
    },
    {
      type: "info",
      continues: true,
      title: "El método arqueológico y la noción de episteme",
      body: "El concepto central de ese libro es la **episteme**: el conjunto de reglas, en gran medida inconscientes, que en un período dado hace posible que ciertos enunciados cuenten como conocimiento verdadero y otros no. No es una teoría ni una escuela, sino el suelo compartido y anterior a cualquier teoría sobre el que las teorías de una época pueden formularse.",
    },
    {
      type: "info",
      continues: true,
      title: "El método arqueológico y la noción de episteme",
      body: "Foucault describe tres epistemes sucesivas en la cultura occidental. La renacentista, organizada por la **semejanza**: las cosas se conocen por sus parecidos y correspondencias. La clásica, de los siglos XVII y XVIII, organizada por la **representación** y el orden: conocer es tabular, clasificar, poner en cuadros. Y la moderna, que emerge a fines del siglo XVIII, organizada en torno a una figura nueva y paradójica: el **hombre**, sujeto que conoce y a la vez objeto de las nuevas ciencias humanas —biología, economía, filología—.",
    },
    {
      type: "short",
      question: "¿Cómo llama Foucault al conjunto de reglas inconscientes que hace posible, en una época, que algo cuente como conocimiento verdadero?",
      answers: ["episteme"],
      explain: "La episteme: no es una teoría ni una escuela, sino el suelo compartido y anterior a cualquier teoría sobre el que las teorías de una época se formulan. Foucault describe tres: la de la semejanza, la de la representación y la del hombre.",
    },
    {
      type: "info",
      continues: true,
      title: "El método arqueológico y la noción de episteme",
      body: "Ese enfoque rechaza explícitamente la prioridad del sujeto observador: Si hay un enfoque que rechazo es el que podría llamarse, en sentido amplio, fenomenológico, que da prioridad absoluta al sujeto observador, que atribuye un papel constituyente a un acto, que sitúa su propio punto de vista en el origen de toda historicidad; que, en suma, conduce a una conciencia trascendental. Me parece que el análisis histórico del discurso científico debe someterse, en última instancia, no a una teoría del sujeto cognoscente, sino a una teoría de la **práctica discursiva**.",
    },
    {
      type: "info",
      continues: true,
      title: "El método arqueológico y la noción de episteme",
      body: "Foucault busca el sentido, entonces, no en una teoría del sujeto cognoscente sino en la práctica discursiva misma. Es enfáticamente particularista: sostiene que el único conocimiento legítimo es el histórico, y se piensa a sí mismo como historiador de las ideas, de las instituciones y sobre todo de los **discursos y prácticas** que las sostienen.",
    },
    {
      type: "quiz",
      question: "¿A qué se somete, según Foucault, el análisis histórico del discurso científico?",
      options: [
        "A una teoría trascendental del sujeto que constituye el saber",
        "A la fenomenología, que da prioridad al sujeto observador",
        "A ningún tipo de análisis histórico, sólo al lógico o formal",
        "A una teoría de la práctica discursiva, no del sujeto",
      ],
      answer: 3,
      explain: "Foucault rechaza explícitamente el enfoque fenomenológico, que atribuye un papel constituyente al sujeto observador: el análisis histórico debe someterse a una teoría de la práctica discursiva, no a una teoría del sujeto cognoscente.",
    },
    {
      type: "info",
      title: "De la arqueología a la genealogía",
      body: "El período arqueológico —Historia de la locura (1961) y Las palabras y las cosas (1966), sistematizados metodológicamente en La arqueología del saber (1969)— describe discontinuidades en el discurso sin indagar demasiado en las luchas que las producen. A partir de los años setenta, con Vigilar y castigar (1975), Foucault se desplaza hacia la **genealogía**, término tomado de Nietzsche: ya no basta describir el discurso, hace falta rastrear las relaciones de poder que lo atraviesan.",
    },
    {
      type: "info",
      continues: true,
      title: "De la arqueología a la genealogía",
      body: "La diferencia es de énfasis más que de ruptura total. La arqueología pregunta qué contaba como verdad en una época dada; la genealogía pregunta, además, a través de qué luchas, exclusiones e instituciones concretas esa verdad se impuso sobre otras posibles. El poder, apenas presente como categoría explícita en los primeros libros, se vuelve central en los siguientes.",
    },
    {
      type: "quiz",
      question: "¿Qué agrega la genealogía a la pregunta que ya hacía la arqueología?",
      options: [
        "A través de qué luchas e instituciones una verdad se impuso",
        "Nada: son exactamente el mismo método con otro nombre",
        "El estudio de la episteme renacentista, ausente en la arqueología",
        "El rechazo total de cualquier análisis histórico del discurso",
      ],
      answer: 0,
      explain: "La arqueología describe qué contaba como verdad en una época; la genealogía, tomada de Nietzsche, pregunta además a través de qué luchas y exclusiones concretas esa verdad se impuso sobre otras. El poder pasa a ser central.",
    },
    {
      type: "info",
      title: "Historia de la locura: el gran encierro",
      body: "Historia de la locura en la época clásica (1961) reconstruye el surgimiento del manicomio en la Francia del siglo XVIII: edificios que antes alojaban leprosos y enfermos infecciosos pasan a alojar enfermos mentales. Foucault llama a ese proceso el **gran encierro** y lo lee, contra el relato progresista habitual, como una forma de control antes que de cuidado.",
    },
    {
      type: "info",
      continues: true,
      title: "Historia de la locura: el gran encierro",
      body: "El argumento es estructuralista en su forma: la definición moderna de **locura** es el prerrequisito del ideal ilustrado de **razón**, porque la razón sólo se define por oposición a lo que excluye. El manicomio es, en ese sentido, el lado oscuro de la Ilustración: la razón ilustrada sólo fue posible mediante la construcción de un concepto de sinrazón que la limitara.",
    },
    {
      type: "quiz",
      question: "¿Por qué el argumento de Historia de la locura es «estructuralista en su forma»?",
      options: [
        "La razón sólo se define por oposición a lo que excluye",
        "Porque Foucault cita allí directamente a Lévi-Strauss",
        "Porque trata a la locura como una enfermedad puramente médica",
        "Porque niega que exista ninguna relación entre razón y locura",
      ],
      answer: 0,
      explain: "Como el valor diferencial de Saussure, la razón sólo tiene sentido por contraste: la definición moderna de locura es el prerrequisito de la razón ilustrada, que se construye excluyendo y encerrando lo que llama sinrazón.",
    },
    {
      type: "info",
      title: "Vigilar y castigar: la prisión y el panóptico",
      body: "Vigilar y castigar (1975) estudia la creación de la **prisión** a fines del siglo XVIII, presentada tradicionalmente como una forma más racional y humana de castigo que la tortura pública, orientada a proteger a la sociedad y rehabilitar al condenado. Foucault sostiene que su función real es el **aislamiento y la vigilancia**, y conecta prisión, manicomio, escuela, hospital y fábrica como variantes de una misma lógica institucional de control.",
    },
    {
      type: "info",
      continues: true,
      title: "Vigilar y castigar: la prisión y el panóptico",
      body: "Su figura emblemática es el **panóptico**, diseño ideado por Jeremy Bentham hacia 1791: una torre de vigilancia central rodeada de celdas dispuestas en anillo, desde la cual un guardia puede observar a cualquier prisionero sin que éste sepa si en ese momento lo están mirando. La incertidumbre misma —nunca saber si se es observado— basta como instrumento de disciplina.",
    },
    {
      type: "info",
      continues: true,
      title: "Vigilar y castigar: la prisión y el panóptico",
      body: "El panóptico es, para Foucault, el modelo de la **sociedad disciplinaria** moderna: una sociedad que ya no necesita castigar el cuerpo en público, porque ha aprendido a hacer que cada individuo vigile su propia conducta por si acaso lo estuvieran observando. El poder disciplinario no reprime únicamente desde afuera: produce sujetos que se autorregulan.",
    },
    {
      type: "quiz",
      question: "¿Qué vuelve tan eficaz al panóptico como instrumento de disciplina?",
      options: [
        "Que el guardia observa a todos los presos en todo momento",
        "El castigo corporal público que reemplaza a la vigilancia",
        "Que cada prisionero puede ver a los demás desde su celda",
        "No saber nunca con certeza si se está siendo observado",
      ],
      answer: 3,
      explain: "El guardia puede observar sin que el preso sepa cuándo. Esa incertidumbre basta como instrumento de disciplina: el individuo termina vigilando su propia conducta por si acaso, sin necesidad de vigilancia constante real.",
    },
    {
      type: "info",
      title: "Poder y saber",
      body: "El concepto que organiza el período genealógico es el de **poder/saber**: no hay saber libre o inocente de poder, ni poder que no dependa de alguna forma de saber. El poder, para Foucault, no descansa —como supuso la Ilustración— en el dominio del mundo natural, sino en el saber mismo, en la capacidad de clasificar, medir y nombrar.",
    },
    {
      type: "info",
      continues: true,
      title: "Poder y saber",
      body: "El poder está en todas partes, no porque lo abarque todo, sino porque **viene de todas partes**.",
    },
    {
      type: "info",
      continues: true,
      title: "Poder y saber",
      body: "El poder está **radicalmente disperso**: no emana de un punto único ni de un sujeto que lo posea y lo ejerza sobre un objeto pasivo. No hay ámbito de la vida —ni siquiera la investigación científica, que se presenta como desinteresada— libre de relaciones de poder.",
    },
    {
      type: "info",
      continues: true,
      title: "Poder y saber",
      body: "El poder, además, **viene de abajo**: no hay una oposición binaria entre gobernantes y gobernados en la raíz de las relaciones de poder, que son relacionales e inmanentes a todo vínculo social, no algo añadido desde afuera. Donde hay poder, siempre hay **resistencia**: no hay escape del poder, pero tampoco sometimiento total a él.",
    },
    {
      type: "quiz",
      question: "¿Qué implica que, para Foucault, «donde hay poder, siempre hay resistencia»?",
      options: [
        "La resistencia siempre termina por eliminar todo tipo de poder",
        "El poder y la resistencia son fenómenos completamente ajenos",
        "Sólo el Estado central puede ejercer resistencia legítima",
        "No hay escape total del poder, ni tampoco sometimiento total",
      ],
      answer: 3,
      explain: "El poder está disperso, viene de abajo y de todas partes; por eso, donde se ejerce, siempre se abre también la posibilidad de resistirlo. Ni escapar del todo ni someterse del todo: ambos coexisten.",
    },
    {
      type: "info",
      continues: true,
      title: "Poder y saber",
      body: "Y el poder no es sólo **represivo**: es también **productivo**. No se limita a prohibir y castigar; produce discursos, produce categorías, produce sujetos. Esa dimensión productiva —no en sentido normativo, de algo bueno, sino de algo que fabrica— es lo que hace del método de Foucault una herramienta historiográfica y no sólo una crítica.",
    },
    {
      type: "info",
      title: "Biopoder",
      body: "En el tramo final de La voluntad de saber —el primer tomo de Historia de la sexualidad— Foucault agrega una pieza que completa el cuadro: el **biopoder**. Frente al poder soberano clásico, definido por el derecho de \"hacer morir y dejar vivir\", la modernidad instaura un poder que se define por la fórmula inversa: **hacer vivir y dejar morir**.",
    },
    {
      type: "info",
      continues: true,
      title: "Biopoder",
      body: "El biopoder opera en dos niveles simultáneos. Uno es anatómico e individual: la disciplina de los cuerpos que ya describía Vigilar y castigar, ejercida sobre cada organismo en particular. El otro es la **biopolítica** de las poblaciones: la gestión estadística de nacimientos, muertes, salud y enfermedad a escala de un conjunto humano entero.",
    },
    {
      type: "info",
      continues: true,
      title: "Biopoder",
      body: "Con el biopoder, la vida biológica misma —y no sólo la conducta o el alma del individuo— se vuelve objeto de gobierno. Es la culminación de la genealogía: allí donde la arqueología describía cómo cambia lo que se puede decir, la genealogía del biopoder describe cómo el poder llega a administrar la vida y la muerte de poblaciones enteras.",
    },
    {
      type: "short",
      question: "¿Cómo llama Foucault al poder moderno que se define por la fórmula «hacer vivir y dejar morir»?",
      answers: ["biopoder"],
      explain: "El biopoder, opuesto al poder soberano clásico («hacer morir y dejar vivir»). Opera en dos niveles: la disciplina anatómica de los cuerpos y la biopolítica, la gestión estadística de poblaciones enteras.",
    },
    {
      type: "info",
      title: "Historia de la sexualidad: la hipótesis represiva",
      body: "Historia de la sexualidad es, ante todo, una historia del discurso y una crítica de la **hipótesis represiva** —la idea, sostenida por ejemplo por Marcuse, de una mojigatería victoriana bajo el capitalismo burgués que reprimía y silenciaba el sexo—. Foucault pregunta no \"por qué estamos tan reprimidos\", sino **por qué no dejamos de hablar de que estamos reprimidos**, lo cual es, de hecho, otra forma de seguir hablando de sexo.",
    },
    {
      type: "info",
      continues: true,
      title: "Historia de la sexualidad: la hipótesis represiva",
      body: "Lo que está en cuestión es el hecho discursivo global, la puesta del sexo en discurso… estas técnicas de poder sobre el sexo no obedecieron a un principio de selección rigurosa, sino de diseminación e implantación de sexualidades polimorfas.",
    },
    {
      type: "info",
      continues: true,
      title: "Historia de la sexualidad: la hipótesis represiva",
      body: "Lejos de silenciarse, en los siglos XVIII y XIX la sexualidad sufrió una **explosión discursiva**: se la escrutó, categorizó y medicalizó como nunca antes. La homosexualidad, antes vista como un acto ocasional, pasa a definirse como una **categoría, un tipo, una especie**: el homosexual se convierte en una identidad, no ya en la descripción de una conducta puntual.",
    },
    {
      type: "quiz",
      question: "¿Qué pregunta Foucault en lugar de «por qué estamos tan reprimidos»?",
      options: [
        "Cuándo va a terminar por fin la represión sexual",
        "Quién es el responsable directo de tanta represión",
        "Si la represión sexual existió alguna vez de verdad",
        "Por qué no dejamos de hablar de que estamos reprimidos",
      ],
      answer: 3,
      explain: "Preguntar por qué no dejamos de hablar de la represión es notar que hablar de represión es, en sí mismo, seguir hablando de sexo: la hipótesis represiva de Marcuse ignora la explosión discursiva real de los siglos XVIII y XIX.",
    },
    {
      type: "info",
      continues: true,
      title: "Historia de la sexualidad: la hipótesis represiva",
      body: "En la confesión católica, el foco se desplaza del acto a los estímulos del deseo, categorizables y vigilables de manera más invasiva: la sociedad moderna resulta perversa no a pesar de su puritanismo, sino de manera directa, porque genera discurso con el fin de categorizar y controlar. Foucault mira la sexualidad no como una pulsión terca —no como Eros ni libido—, sino como un punto de transferencia especialmente denso para las relaciones de poder.",
    },
    {
      type: "info",
      continues: true,
      title: "Historia de la sexualidad: la hipótesis represiva",
      body: "El contexto biográfico ilumina esta obra: de manera análoga al miedo inicial frente a una enfermedad nueva y poco comprendida, el sida de comienzos de los años ochenta combinó terror al contagio y estigma sexual. Ese clima es el trasfondo inmediato de mucho de lo que Foucault escribe, en sus últimos años, sobre discurso, represión y confinamiento.",
    },
    {
      type: "info",
      title: "La Ilustración como línea recta",
      body: "Foucault entra en la conversación de Adorno y Horkheimer sobre la relación entre Ilustración y totalitarismo. Ellos trazan una línea dialéctica, hegeliana, en espiral. Foucault sostiene que la línea es, en cambio, **recta**: no hacen falta mediaciones dialécticas, porque el impulso de conocerlo todo, de clasificar y de controlar conduce de manera directa a la vigilancia y, en última instancia, al totalitarismo.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como línea recta",
      body: "La Ilustración es, en esta lectura, un momento de discontinuidad pero también de deshumanización: creciente aislamiento del individuo y creciente vigilancia. La modernidad es una historia de disciplina y vigilancia, con su fetiche por calcular, ordenar y clasificar todo lo que encuentra a su paso.",
    },
    {
      type: "quiz",
      question: "¿Cómo traza Foucault la línea entre Ilustración y totalitarismo, frente a Adorno y Horkheimer?",
      options: [
        "En espiral dialéctica, igual que Adorno y Horkheimer",
        "Niega que exista ninguna relación entre ambos fenómenos",
        "Sostiene que el totalitarismo antecede a la Ilustración",
        "Recta: clasificarlo todo lleva de manera directa al control",
      ],
      answer: 3,
      explain: "Adorno y Horkheimer trazan una línea dialéctica y hegeliana, en espiral. Foucault sostiene que la línea es recta: no hacen falta mediaciones, el afán de conocerlo y clasificarlo todo conduce directamente a la vigilancia.",
    },
    {
      type: "info",
      title: "El discurso como excavación",
      body: "El discurso, para Foucault, es una **actividad discontinua**, y la discontinuidad es la palabra clave de su método histórico. El historiador se vuelve **arqueólogo**, pero no en el mundo físico, sino en el de las palabras y las fuentes: excava capas de discurso, combinando lo sincrónico —la red de relaciones entre enunciados en un momento dado— con el momento de discontinuidad en que algo se desplaza.",
    },
    {
      type: "info",
      continues: true,
      title: "El discurso como excavación",
      body: "No he negado la posibilidad de cambiar el discurso; solo he privado al sujeto soberano de su derecho exclusivo e instantáneo sobre él.",
    },
    {
      type: "info",
      continues: true,
      title: "El discurso como excavación",
      body: "Ante ese desplazamiento no se pregunta **por qué** —no es una cuestión de causalidad— sino que se **describe** el cambio: el momento, por ejemplo, en que dentro de un mismo discurso revisionista \"el pueblo\" como colectivo singular empieza a contraponerse a \"las personas\" en plural. Sus historias avanzan así, en tres tiempos: descripción sincrónica, discontinuidad, nueva descripción sincrónica.",
    },
    {
      type: "info",
      continues: true,
      title: "El discurso como excavación",
      body: "La arqueología no es un retorno al secreto más íntimo del origen; es la descripción sistemática de un objeto-discurso.",
    },
    {
      type: "info",
      continues: true,
      title: "El discurso como excavación",
      body: "Ese método tuvo una escuela historiográfica concreta: el estudio de Stephen Kotkin sobre el estalinismo, Magnetic Mountain, muestra cómo el discurso soviético produjo un sujeto estalinista —el discurso creando al sujeto, y no al revés—, y dio origen a toda una generación de historiadores formados en su seminario de Columbia a comienzos de los noventa.",
    },
    {
      type: "quiz",
      question: "Ante un desplazamiento del discurso, ¿qué pregunta Foucault y qué evita preguntar?",
      options: [
        "Describe el cambio; evita preguntar por qué ocurrió",
        "Pregunta por qué ocurrió; evita describir el cambio en sí",
        "Pregunta por qué y también describe, con el mismo énfasis",
        "No hace ninguna de las dos cosas: sólo data los documentos",
      ],
      answer: 0,
      explain: "No es una cuestión de causalidad para Foucault: se describe el desplazamiento —sincronía, discontinuidad, nueva sincronía— sin indagar sus causas últimas. El estudio de Kotkin sobre el discurso estalinista sigue ese mismo método.",
    },
    {
      type: "match",
      question: "Uní cada concepto de Foucault con lo que nombra",
      pairs: [
        { left: "Episteme", right: "Las reglas inconscientes que definen qué cuenta como saber" },
        { left: "Panóptico", right: "La incertidumbre de ser observado, vuelta disciplina" },
        { left: "Poder/saber", right: "El poder disperso, productivo, que viene de todas partes" },
        { left: "Biopoder", right: "Hacer vivir y dejar morir: gobernar la vida de poblaciones" },
        { left: "Genealogía", right: "Rastrear las luchas que impusieron una verdad sobre otras" },
      ],
      explain: "Cada concepto describe una pieza del mismo movimiento: el saber de una época (episteme) está ligado al poder que lo produce y lo disputa (poder/saber, panóptico, biopoder), y la genealogía rastrea las luchas concretas detrás de esa verdad.",
    },
    {
      type: "info",
      title: "Cierre: el duelo por el sujeto perdido",
      body: "Foucault es a la vez objeto de la historia intelectual y una metodología para escribirla: hay una literatura que estudia su filosofía y otra que **usa** su método para escribir historia, sin necesidad de discutir sus premisas filosóficas de fondo.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el duelo por el sujeto perdido",
      body: "A diferencia de Derrida, que se ocupa casi exclusivamente de desarmar, Foucault deja una metodología productiva: se ha escrito mucha buena historia con sus herramientas, aunque no ofrezca una salida a la vigilancia y el control que describe. Esa posición liminal es la que Derrida juzgará todavía insuficiente: para él, incluso la arqueología conserva un exceso de estructura y de historia por desarmar.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el duelo por el sujeto perdido",
      body: "Foucault está ligado a la pérdida de fe en cualquier verdad absoluta o subjetividad estable anterior al discurso, y reconoce lo doloroso que resulta que a la muerte de Dios le siga la muerte del sujeto: en su manera de tratar el tema hay algo de duelo, no de regodeo, casi una nostalgia del sujeto perdido. Las palabras y las cosas cierra con una imagen que resume esa apuesta:",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el duelo por el sujeto perdido",
      body: "A todos los que aún quieren hablar del hombre, de su reino o de su liberación; a todos los que todavía se preguntan qué es el hombre en su esencia… solo podemos responder con una **risa filosófica**.",
    },
  ],
};
