export default {
  num: 5,
  transcript: 6,
  title: "Nietzsche y la muerte de Dios",
  source: "https://www.youtube.com/watch?v=MqbQ0loF3zM",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Friedrich Nietzsche** (1844-1900) nace en la provincia prusiana de Sajonia, hijo de un pastor luterano muerto cuando él era muy chico; lo crían cinco mujeres —abuela, madre, hermana y dos tías—. Estudia primero teología y después filología clásica en Bonn y Leipzig, con un fuerte interés paralelo por la música. En 1869, con veinticuatro años y sin doctorado terminado, recibe una cátedra de filología clásica en Basilea, que ejerce hasta 1879, cuando se jubila por motivos de salud.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Sus obras principales, en orden: El nacimiento de la tragedia (1872), La gaya ciencia (1882), Así habló Zaratustra (publicada en partes entre 1883 y 1885), Más allá del bien y del mal (1886), La genealogía de la moral (1887) y, ya en 1888, El ocaso de los ídolos, El anticristo y Ecce homo, publicados después de su colapso mental, entre 1889 y 1908.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En enero de 1889 se derrumba en una calle de Turín y no vuelve a recuperar la razón; muere once años después, en 1900. La voluntad de poder, título bajo el que suele citarse buena parte de su filosofía tardía, no es un libro que Nietzsche haya terminado ni autorizado: es una compilación armada después de su muerte por su hermana, Elisabeth Förster-Nietzsche, y por su amigo Peter Gast, a partir de notas sueltas de sus cuadernos.",
    },
    {
      type: "info",
      title: "El problema que hereda: Schopenhauer y Hegel",
      body: "Antes que con Hegel, Nietzsche se forma con **Arthur Schopenhauer** (1788-1860), cuyo El mundo como voluntad y representación descubre siendo estudiante y lee con devoción. Retomando la distinción kantiana entre fenómeno y cosa en sí, Schopenhauer identifica esa cosa en sí con una **Voluntad** ciega y sin meta, que se manifiesta en todo lo existente como un impulso incesante e insatisfecho: el deseo nunca se sacia del todo, y el sufrimiento es, por eso, la condición de fondo de la vida.",
    },
    {
      type: "quiz",
      question: "Para Schopenhauer, ¿qué es la Voluntad que subyace a todo lo existente?",
      options: [
        "Un impulso ciego y sin meta, siempre insatisfecho",
        "Una fuerza racional que ordena el mundo hacia un fin",
        "El mismo Espíritu que Hegel llama Geist",
        "Un dios personal que decide el destino de cada uno",
      ],
      answer: 0,
      explain: "Retomando la distinción kantiana entre fenómeno y cosa en sí, Schopenhauer identifica esa cosa en sí con una Voluntad ciega que se manifiesta como deseo insaciable: el sufrimiento es la condición de fondo de la vida.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: Schopenhauer y Hegel",
      body: "Para Schopenhauer el arte, sobre todo la música, ofrece un respiro momentáneo frente a esa Voluntad: la contemplación estética suspende por un instante el deseo. Pero su salida de fondo es pesimista —resignación, negación de la voluntad, un cierto ascetismo—. Nietzsche hereda el diagnóstico de un impulso ciego y doloroso en la base de la vida, pero va a rechazar esa salida: donde Schopenhauer pide resignación, Nietzsche va a pedir **afirmación**, incluido el sufrimiento.",
    },
    {
      type: "quiz",
      question: "Frente al sufrimiento de la Voluntad, ¿en qué se diferencian Schopenhauer y Nietzsche?",
      options: [
        "Uno pide resignación; el otro, afirmar la vida entera",
        "Uno niega el sufrimiento; el otro lo exagera sin razón",
        "Uno lo resuelve con la razón; el otro, con la fe",
        "Uno lo atribuye a Dios; el otro, a la sociedad",
      ],
      answer: 0,
      explain: "Nietzsche hereda el diagnóstico de un impulso ciego y doloroso en la base de la vida, pero rechaza la salida resignada de Schopenhauer: donde éste pide negación de la voluntad, Nietzsche pide afirmación, incluido el sufrimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: Schopenhauer y Hegel",
      body: "Con Hegel la relación es distinta: Nietzsche funciona casi como su **alter ego**, un anti-Hegel. Ve, como Hegel, antagonismos, violencia y contradicción por todas partes, pero rechaza de plano cualquier **Aufhebung**: no hay reconciliación, ni ahora ni al final de la historia. Las mismas tensiones dialécticas reaparecen en su obra, sólo que sin direccionalidad ni superación posible: la contradicción no se resuelve nunca en una síntesis superior.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: Schopenhauer y Hegel",
      body: "Hay, además, un fuerte componente de dolor entrelazado con placer —casi sadomasoquista— que en Hegel no aparece con esa intensidad: no sólo antagonismo, sino la pregunta de cómo hacer soportable la vida una vez comprendido lo despreciable de la condición humana. De su obra temprana:",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: Schopenhauer y Hegel",
      body: "Estirpe miserable y efímera, hijos del azar y la fatiga, ¿por qué me obligáis a deciros lo que sería más provechoso que no oyerais? Lo mejor de todo es algo que os está por completo vedado: no haber nacido, no ser, ser nada. Pero lo segundo mejor para vosotros es morir pronto.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: Schopenhauer y Hegel",
      body: "Como Freud —gran admirador suyo—, Nietzsche describe mejor lo que está mal que las soluciones que propone. Hegel construye un sistema; Nietzsche desarma sistemas, en un sentido que anticipa a la deconstrucción posterior: no ofrece un modo en que las piezas encajen, ni telos ni Aufhebung, pero lo hace de un modo visceral, colorido y creativo. Sobre la frase \"Dios ha muerto\" —una oración cortísima, de sintaxis simple— circulan, en consecuencia, interpretaciones muy dispares desde hace más de un siglo.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de Hegel o de Nietzsche?",
      groups: ["Hegel", "Nietzsche"],
      items: [
        { text: "Hay una reconciliación final de las contradicciones", group: 0 },
        { text: "Arma un sistema que pretende explicarlo todo", group: 0 },
        { text: "No hay reconciliación ni Aufhebung posible", group: 1 },
        { text: "Desarma sistemas; anticipa la deconstrucción", group: 1 },
        { text: "Entrelaza el dolor con el placer de modo extremo", group: 1 },
      ],
      explain: "Comparten la mirada sobre el conflicto y la contradicción, pero Hegel busca sistema, telos y reconciliación, mientras Nietzsche niega toda síntesis: desarma, sin dirección ni consuelo, con una intensidad de dolor y placer que en Hegel no aparece.",
    },
    {
      type: "info",
      title: "La etapa Wagner",
      body: "En 1870 estalla la **guerra franco-prusiana** (1870-1871), provocada por Bismarck para unificar los Estados alemanes dispersos en un Imperio, que se declara en 1871. Nietzsche se ofrece como camillero médico y vuelve con la salud arruinada, de la que nunca se recupera del todo. Poco antes, en 1869, entabla una amistad muy estrecha con **Richard Wagner**, el compositor, bastante mayor que él.",
    },
    {
      type: "info",
      continues: true,
      title: "La etapa Wagner",
      body: "El nacimiento de la tragedia (1872), el primer libro de Nietzsche, es producto de ese vínculo: está dedicado a Wagner, cuyos dramas musicales presenta como herederos directos de la tragedia griega. Su argumento central distingue dos impulsos artísticos opuestos, tomados de los dioses griegos **Apolo** y **Dioniso**.",
    },
    {
      type: "info",
      continues: true,
      title: "La etapa Wagner",
      body: "Lo apolíneo es el principio de la forma, la individuación y la mesura: el sueño, la imagen clara, la superficie bella que hace soportable la existencia. Lo dionisíaco es el principio de la **ebriedad** (Rausch), la disolución de los límites del yo, la música, el éxtasis que hunde de nuevo al individuo en una unidad primordial y caótica.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de lo apolíneo o de lo dionisíaco?",
      groups: ["Apolo", "Dioniso"],
      items: [
        { text: "Principio de la forma, la individuación y la mesura", group: 0 },
        { text: "La imagen clara y la superficie bella", group: 0 },
        { text: "El sueño ordenado y sereno", group: 0 },
        { text: "La ebriedad y la disolución de los límites del yo", group: 1 },
        { text: "La música y el éxtasis colectivo", group: 1 },
        { text: "Hunde al individuo en una unidad primordial", group: 1 },
      ],
      explain: "La tragedia griega nace de la tensión entre ambos impulsos: el coro dionisíaco, música y desmesura, y el héroe apolíneo, figura individual visible en escena.",
    },
    {
      type: "info",
      continues: true,
      title: "La etapa Wagner",
      body: "La tragedia griega nace, para Nietzsche, de la tensión entre ambos impulsos: el coro dionisíaco —música, desmesura— y el héroe apolíneo, figura individual visible en escena. Esa combinación permite mirar de frente la verdad terrible que resume el sátiro Sileno —que lo mejor sería no haber nacido— sin quedar destruido por ella, transfigurándola en belleza: **sólo como fenómeno estético existencia y mundo quedan eternamente justificados**.",
    },
    {
      type: "quiz",
      question: "Para el Nietzsche de El nacimiento de la tragedia, ¿qué justifica la existencia?",
      options: [
        "La razón y el progreso científico",
        "El arte y la creación estética",
        "El deber moral y la compasión",
        "La fe religiosa heredada de su padre",
      ],
      answer: 1,
      explain: "Frente a la verdad terrible de Sileno —que lo mejor sería no haber nacido—, sólo la transfiguración en belleza vuelve soportable, y justifica estéticamente, la existencia.",
    },
    {
      type: "info",
      continues: true,
      title: "La etapa Wagner",
      body: "Ese equilibrio se rompe, sostiene Nietzsche, con Eurípides y con Sócrates: el optimismo racionalista socrático, la fe en que el conocimiento puede corregir la existencia, desplaza a lo dionisíaco y mata a la tragedia como forma.",
    },
    {
      type: "quiz",
      question: "¿Qué rompe, según Nietzsche, el equilibrio entre lo apolíneo y lo dionisíaco?",
      options: [
        "El optimismo racionalista de Sócrates y Eurípides",
        "La llegada del cristianismo al imperio romano",
        "El exceso de música en los rituales dionisíacos",
        "La censura política de la tragedia ateniense",
      ],
      answer: 0,
      explain: "La fe socrática en que el conocimiento puede corregir la existencia desplaza a lo dionisíaco y, para Nietzsche, mata a la tragedia como forma.",
    },
    {
      type: "info",
      title: "La ruptura con Wagner",
      body: "Nietzsche termina rompiendo por completo con Wagner: fue tan apasionadamente wagneriano como después antiwagneriano, con la sensación de que Wagner se había \"vendido\" al materialismo, y con celos de por medio —de su fama, de su fuerza, de su esposa Cosima—. Se retira entonces cada vez más de la vida pública.",
    },
    {
      type: "info",
      continues: true,
      title: "La ruptura con Wagner",
      body: "Sigue en Basilea hasta 1879, cuando se jubila escandalosamente joven por motivos de salud, ya muy frágil. El resto de su vida sufre migrañas severas y pasa buena parte del tiempo en sanatorios, viviendo solo, alejado del alcohol, la cafeína y la comida picante, con pocas pertenencias y una salud que jamás termina de asentarse.",
    },
    {
      type: "info",
      continues: true,
      title: "La ruptura con Wagner",
      body: "En 1882 se enamora de **Lou Salomé**, una joven de la intelligentsia de San Petersburgo cercana al filósofo Paul Rée, y le propone matrimonio a través de Rée; es rechazado y queda destrozado. Le escribe entonces a un amigo:",
    },
    {
      type: "info",
      continues: true,
      title: "La ruptura con Wagner",
      body: "Estoy ejerciendo hasta la última gota de autodominio, pero he vivido en soledad demasiado tiempo, alimentándome demasiado de mi propia grasa, de modo que ahora me estoy quebrando como ningún otro hombre podría, en la rueda de mis propias pasiones. A menos que descubra el truco alquímico de convertir este fango en oro, estoy perdido.",
    },
    {
      type: "info",
      continues: true,
      title: "La ruptura con Wagner",
      body: "Sobrevive una foto conocida: Nietzsche y Rée tirando de un carro mientras Salomé, de pie sobre él, blande un látigo. De ahí la línea de Zaratustra —\"¿vas con mujeres? No olvides el látigo\"— que remite justamente a esa imagen, en la que es ella quien sostiene el látigo sobre los dos. Bertrand Russell comentó, sarcástico, que la opinión de Nietzsche sobre las mujeres era la objetivación de su propio miedo hacia ellas, y que \"nueve de cada diez mujeres le quitarían el látigo, y él lo sabía\".",
    },
    {
      type: "quiz",
      question: "¿Qué le reprocha Bertrand Russell a la visión de Nietzsche sobre las mujeres?",
      options: [
        "Que era la objetivación de su propio miedo hacia ellas",
        "Que nunca había conocido a una mujer intelectual",
        "Que copiaba ideas de Schopenhauer sobre el género",
        "Que ocultaba su admiración real por Lou Salomé",
      ],
      answer: 0,
      explain: "Russell comentó, sarcástico, que la visión de Nietzsche sobre las mujeres era la objetivación de su propio miedo hacia ellas, y que nueve de cada diez se lo quitarían, y él lo sabía.",
    },
    {
      type: "info",
      title: "Momentos clave de su pensamiento",
      body: "Nietzsche es un escritor fragmentario, aforístico, que no invita a lecturas holísticas. Es profundamente **psicológico**, obsesionado con el trauma de la modernidad y la alienación. Critica mucho a los románticos, pero conserva un fuerte elemento romántico en su recurrencia constante a la **pasión y la voluntad** —más importantes que el pensamiento—, en su defensa del instinto y el éxtasis, y en su escepticismo hacia el racionalismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Momentos clave de su pensamiento",
      body: "Pese a su antihegelianismo declarado, hay algo profundamente **dialéctico** en su pensamiento: en La genealogía de la moral escribe que \"todas las cosas grandes provocan su propia destrucción mediante un acto de autosuperación\". En Más allá del bien y del mal sostiene que lo verdadero y lo falso, lo bueno y lo malo, podrían estar \"insidiosamente emparentados, atados y entretejidos\", ser en su esencia una sola cosa.",
    },
    {
      type: "quiz",
      question: "Pese a su antihegelianismo declarado, ¿qué rasgo dialéctico conserva Nietzsche?",
      options: [
        "Que las cosas grandes provocan su propia destrucción",
        "Que la historia avanza siempre hacia una síntesis",
        "Que el Espíritu se realiza a través del Estado",
        "Que toda tesis encuentra su antítesis necesaria",
      ],
      answer: 0,
      explain: "En La genealogía de la moral escribe que todas las cosas grandes provocan su propia destrucción mediante un acto de autosuperación, y que lo verdadero y lo falso, lo bueno y lo malo, podrían estar íntimamente emparentados.",
    },
    {
      type: "info",
      continues: true,
      title: "Momentos clave de su pensamiento",
      body: "Esa misma fusión de placer y dolor aparece, en un registro casi extático, en La gaya ciencia:",
    },
    {
      type: "info",
      continues: true,
      title: "Momentos clave de su pensamiento",
      body: "Pero si uno soportara, si pudiera soportar esta inmensa suma de aflicciones de toda clase, si pudiera contenerla toda en una sola alma y concentrarla en un único sentimiento, ello daría por resultado, sin duda, una felicidad que la humanidad no ha conocido hasta ahora.",
    },
    {
      type: "info",
      continues: true,
      title: "Momentos clave de su pensamiento",
      body: "Y reaparece, ya como fórmula, en Zaratustra: \"¿alguna vez dijiste 'sí' a un solo placer? Entonces dijiste 'sí' también a todo dolor. Todas las cosas están encadenadas, entrelazadas, enamoradas.\"",
    },
    {
      type: "quiz",
      question: "«Si dijiste sí a un placer, dijiste sí a todo dolor» expresa que…",
      options: [
        "placer y dolor están entrelazados sin poder separarse",
        "hay que buscar el dolor para sentir más placer después",
        "el placer verdadero es indiferente al sufrimiento",
        "sólo el dolor tiene valor moral genuino",
      ],
      answer: 0,
      explain: "Es la misma fusión extática de La gaya ciencia, llevada a fórmula en Zaratustra: todas las cosas están encadenadas, entrelazadas, enamoradas.",
    },
    {
      type: "info",
      title: "Genealogía: el método",
      body: "El método que da nombre a La genealogía de la moral (1887) consiste en rastrear el origen histórico y contingente de los valores morales, en lugar de buscarles un fundamento racional o trascendente. Nietzsche sostiene, por ejemplo, que la palabra \"bueno\" no nació como opuesto de \"malo\" en sentido moral: nombraba, en boca de las castas nobles y guerreras, lo alto, lo fuerte, lo que ellas mismas eran, por oposición a lo \"bajo\" o \"plebeyo\". El juicio moral llega después, y con otro origen.",
    },
    {
      type: "quiz",
      question: "El método genealógico de Nietzsche consiste en…",
      options: [
        "rastrear el origen histórico de los valores",
        "buscar un fundamento racional para cada valor moral",
        "clasificar los valores según su utilidad social",
        "medir qué tan antiguo es cada valor moral",
      ],
      answer: 0,
      explain: "En vez de buscarles un fundamento racional o trascendente, rastrea de dónde vienen los valores: \"bueno\", por ejemplo, nombró primero lo alto y lo fuerte de las castas nobles, no lo opuesto de \"malo\" en sentido moral.",
    },
    {
      type: "info",
      continues: true,
      title: "Genealogía: el método",
      body: "Ese origen es lo que llama la **moral de esclavos**: el momento en que los débiles, incapaces de vencer a los fuertes en sus propios términos, invierten la valoración —\"los mansos heredarán la tierra\"— y convierten en virtud lo que antes era mera carencia de poder. Detesta el cristianismo precisamente por eso, por ser una religión **nihilista** que hace de la debilidad una virtud y promete su recompensa en un reino venidero; ve el mismo mecanismo igualitario en la democracia, que entiende como gobierno de la mediocridad.",
    },
    {
      type: "quiz",
      question: "¿Qué es la «moral de esclavos» para Nietzsche?",
      options: [
        "La ética de quienes fueron esclavizados legalmente",
        "La inversión que vuelve virtud a la debilidad",
        "El deber kantiano de tratar a todos como fines",
        "La moral aristocrática de los grandes hombres y héroes",
      ],
      answer: 1,
      explain: "El débil resentido invierte la valoración —«los mansos heredarán la tierra»— y convierte en virtud lo que antes era carencia de poder. Nietzsche ve ese mecanismo en el cristianismo y también en la democracia.",
    },
    {
      type: "info",
      continues: true,
      title: "Genealogía: el método",
      body: "Detesta también la **piedad** y la compasión, y siente una atracción ambivalente —admiración y humillación a la vez— por las figuras y los héroes fuertes: es un rasgo en el que pesa su propio autodesprecio, porque fue físicamente débil toda su vida adulta. Insiste en que el dolor no es sólo negativo, que puede abrazarse en vez de sólo soportarse —hay aquí un parentesco fuerte con Dostoievski—: \"lo que está cayendo, hay que empujarlo también\", dice Zaratustra, y agrega que nadie sabe todavía qué es el bien o el mal, \"salvo el que crea\".",
    },
    {
      type: "info",
      title: "La voluntad de poder",
      body: "En sus últimos libros, Nietzsche propone un principio explicativo único para toda forma de vida: la **voluntad de poder**. No es un simple instinto de autoconservación ni de dominio político, sino un impulso más amplio de expansión y autosuperación: toda fuerza viviente busca no sólo persistir, sino desplegarse más allá de sus límites actuales. Es la misma lógica que organiza la genealogía de la moral: los valores no describen un orden objetivo, sino que expresan qué tipo de fuerza —ascendente o decadente— los produjo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Nietzsche al impulso único que explica toda forma de vida?",
      answers: ["voluntad de poder"],
      explain: "No es sólo instinto de autoconservación ni de dominio político: toda fuerza viviente busca desplegarse más allá de sus límites actuales, y los valores expresan qué tipo de fuerza —ascendente o decadente— los produjo.",
    },
    {
      type: "info",
      title: "Zaratustra y el Übermensch",
      body: "Su figura más heroica es **Zaratustra**, vagamente basado en el fundador persa del zoroastrismo y construido como alter ego de Nietzsche: un profeta que baja de las montañas a hablarle a la gente, vulnerable, no invencible. Viene a entregar una doctrina, la del **Übermensch** (de über, \"sobre\", y Mensch, \"persona\"): otra palabra intraducible, a veces vertida como \"superhombre\", que funciona como una especie de **Aufhebung** del ser humano, aquello que supera toda mediocridad.",
    },
    {
      type: "info",
      continues: true,
      title: "Zaratustra y el Übermensch",
      body: "\"El hombre es algo que debe ser superado\", repite Zaratustra: él mismo no es un Übermensch —nunca se llega a conocer uno en el libro—, sino la cuerda tendida entre la bestia y esa figura por venir, una cuerda sobre un abismo:",
    },
    {
      type: "quiz",
      question: "El Übermensch de Zaratustra es, ante todo…",
      options: [
        "Un superhombre invulnerable que ya existe y gobierna",
        "Una meta por venir, algo que el hombre debe alcanzar",
        "El proletariado que hará la revolución",
        "El sabio que ha alcanzado la reconciliación con el todo",
      ],
      answer: 1,
      explain: "Zaratustra mismo no es un Übermensch, y nunca conocemos uno: es algo por venir. El hombre es una cuerda sobre el abismo, un puente hacia esa grandeza; expresa la necesidad de autocreación, no una raza ya realizada.",
    },
    {
      type: "info",
      continues: true,
      title: "Zaratustra y el Übermensch",
      body: "Yo os enseño el Übermensch. El hombre es algo que debe ser superado. ¿Qué habéis hecho para superarlo? … ¿Qué es el mono para el hombre? Un hazmerreír o una dolorosa vergüenza. Y justamente eso ha de ser el hombre para el Übermensch… El hombre es una cuerda tendida entre la bestia y el Übermensch, una cuerda sobre un abismo… peligroso el atravesar, peligroso el mirar atrás, peligroso el estremecerse y detenerse.",
    },
    {
      type: "info",
      continues: true,
      title: "Zaratustra y el Übermensch",
      body: "Como en Hegel, hay aquí una inquietud de fondo: quedarse quieto y satisfecho es imposible. La aspiración a la gran creación, a la **autocreación**, es la forma que toma en Zaratustra la voluntad de poder llevada a su extremo más afirmativo.",
    },
    {
      type: "info",
      title: "El eterno retorno",
      body: "Otro concepto central, previo a la muerte de Dios, es el del **eterno retorno**, sobre cuyo significado tampoco hay demasiado consenso. Una lectura lo acerca al imperativo categórico kantiano: vivir cada instante como si fuera a repetirse eternamente, actuando siempre de un modo que se desearía ver repetido. Otra lo lee como una afirmación de la **totalidad**: cada momento es integral al conjunto, ningún instante pesa más que el presente, y sólo el Übermensch tiene fuerza para abrazar esa repetición sin quebrarse.",
    },
    {
      type: "quiz",
      question: "Una lectura del eterno retorno lo acerca al imperativo categórico kantiano. ¿En qué consiste?",
      options: [
        "En vivir cada instante como si fuera a repetirse siempre",
        "En repetir literalmente cada acto tres veces seguidas",
        "En obedecer siempre la ley moral universal",
        "En negar que el tiempo tenga una dirección",
      ],
      answer: 0,
      explain: "Actuar siempre de un modo que se desearía ver repetido eternamente: cada momento pesa como si tuviera que sostenerse para siempre, sin apelar a una recompensa futura.",
    },
    {
      type: "info",
      continues: true,
      title: "El eterno retorno",
      body: "Una tercera lectura lo acerca a la filosofía de Henri Bergson: el tiempo como un río continuo, sin cortes, donde la eternidad es el núcleo mismo del tiempo y no debe confundirse con la infinitud.",
    },
    {
      type: "info",
      title: "La muerte de Dios",
      body: "En La gaya ciencia (1882) —die fröhliche Wissenschaft, la \"ciencia alegre\"— es un **loco** quien viene a dar la noticia, llegando siempre demasiado temprano o demasiado tarde:",
    },
    {
      type: "info",
      continues: true,
      title: "La muerte de Dios",
      body: "Dios ha muerto. Dios permanece muerto. Y nosotros lo hemos matado. ¿Cómo nos consolaremos nosotros, los asesinos entre los asesinos?",
    },
    {
      type: "info",
      continues: true,
      title: "La muerte de Dios",
      body: "Lo decisivo es que la afirmación no es \"no hay Dios\": no es ateísmo. Es la afirmación de que **algo ocurrió**, que se cruzó una frontera entre una situación en la que Dios vivía y otra en que está muerto, y que **lo hemos matado nosotros**. Dios está vivo, para Nietzsche, cuando organiza y estructura la sociedad humana, cuando da sentido y propósito a las actividades humanas dentro de un todo con una meta.",
    },
    {
      type: "info",
      continues: true,
      title: "La muerte de Dios",
      body: "**Dios es la creencia en un orden.** Tarde o temprano, sostiene, hay que llegar a la conclusión de que ese mundo donde todo encaja y tiene sentido no existe; cuando se llega a esa comprensión, Dios ha muerto.",
    },
    {
      type: "quiz",
      question: "«Dios ha muerto» significa, ante todo…",
      options: [
        "Una demostración atea de que Dios nunca existió",
        "Que se derrumbó la creencia en un orden con sentido",
        "Que hay que fundar una religión nueva que reemplace a la vieja",
        "Que la ciencia ya explicó todos los milagros",
      ],
      answer: 1,
      explain: "No es la tesis «no hay Dios», sino la constatación de que algo pasó: «lo hemos matado». Dios era la creencia en un orden; su muerte es reconocer que ese todo con sentido y meta no existe.",
    },
    {
      type: "info",
      title: "Nihilismo",
      body: "El mundo donde las contradicciones se resuelven y todo confluye armoniosamente —el telos hegeliano de la historia— nunca llega: no es que venga, es que ya se fue. Se busca totalidad, un propósito superior, pero no puede hallarse; se busca unidad, pero la vida es diferenciación y heterogeneidad, no confluencia. El resultado es una crisis a la que Nietzsche llama **nihilismo**, otro nombre para \"Dios ha muerto\": el momento en que los valores supremos pierden su valor y los principios que organizaban la realidad dejan de organizarla.",
    },
    {
      type: "info",
      continues: true,
      title: "Nihilismo",
      body: "Esa crisis no puede resolverse instituyendo un nuevo Dios o un sustituto, porque la raíz del problema está justamente en ese intento, condenado de antemano al fracaso. No hay principio ordenador que reponer. En cierto sentido, a Nietzsche no le importa si un dios existe o no realmente: importa si se **cree** que existe y se organiza la vida en consecuencia, o si se enfrenta a cara descubierta la diferenciación y la fragmentación que son, para él, la condición humana.",
    },
    {
      type: "quiz",
      question: "Para Nietzsche, lo que importa del nihilismo no es si Dios existe, sino…",
      options: [
        "si se cree en un orden y se vive en función de él",
        "si la ciencia puede demostrar su existencia",
        "si la mayoría de la gente sigue siendo religiosa",
        "si el Estado protege legalmente esa creencia",
      ],
      answer: 0,
      explain: "No hay principio ordenador que reponer: el problema no se resuelve instituyendo un nuevo Dios, porque la raíz está en el intento mismo de creer que existe un orden total con sentido.",
    },
    {
      type: "info",
      title: "Locura y muerte",
      body: "Tras su retiro Nietzsche es extremadamente prolífico, casi siempre aislado. En enero de 1889 le escribe a un antiguo colega de Basilea: \"Estimado profesor: al final preferiría ser profesor en Basilea antes que Dios, pero no me he atrevido a llevar mi egoísmo privado tan lejos como para desistir, por su causa, de la creación del mundo.\" Empieza a firmar sus cartas como \"Dioniso\" y como \"el Crucificado\", y ese mismo año se derrumba en las calles de Turín.",
    },
    {
      type: "info",
      continues: true,
      title: "Locura y muerte",
      body: "Lo internan en un asilo en Jena —la misma ciudad de los románticos de la revista Athenäum— y nunca vuelve a recuperar la cordura. Muere en 1900. Sobre la causa circulan varias teorías sin consenso firme: sífilis contraída durante la guerra, secuelas de su servicio como camillero, otras.",
    },
    {
      type: "match",
      question: "Uní cada concepto de Nietzsche con lo que nombra",
      pairs: [
        { left: "«Dios ha muerto»", right: "Se derrumbó la creencia en un orden que da sentido" },
        { left: "Übermensch", right: "Aquello que el hombre debe superarse para llegar a ser" },
        { left: "Moral de esclavos", right: "Convertir la debilidad en virtud (el cristianismo)" },
        { left: "Eterno retorno", right: "Vivir cada instante como si fuera a repetirse para siempre" },
        { left: "Nihilismo", right: "Cuando los valores supremos pierden su valor" },
      ],
      explain: "El núcleo de Nietzsche: caído el orden que daba sentido (la muerte de Dios), sobreviene el nihilismo; frente a la moral de esclavos, propone la autosuperación (Übermensch) y la afirmación total de la vida (eterno retorno).",
    },
    {
      type: "info",
      title: "La herencia",
      body: "Freud dirá después que Nietzsche \"tuvo un conocimiento de sí mismo más penetrante que cualquier hombre que haya vivido o que probablemente vaya a vivir\". Jugó con los conceptos de bien y mal, los invirtió, mostró su imposibilidad, pero hay en él también un duelo por esa misma imposibilidad: fue, pese a todo, un pensador profundamente preocupado por la moral y por la muerte de Dios, en una relación con esas categorías que anticipa la del sujeto perdido en Foucault —un duelo por lo que necesariamente debe perderse.",
    },
    {
      type: "info",
      continues: true,
      title: "La herencia",
      body: "La muerte de Dios es, para Nietzsche, un momento irreversible, como la toma de la Bastilla para Hegel: una vez declarada, no puede retirarse. De ese diagnóstico se sigue una pregunta que va a recorrer buena parte del pensamiento del siglo XX y que suele resumirse —aunque Nietzsche mismo no la formula exactamente con esas palabras— en una fórmula cercana a la que Dostoievski pone en boca de Iván Karamázov: si Dios ha muerto, ¿qué impide que todo esté permitido?",
    },
  ],
};
