export default {
  num: 23,
  transcript: 24,
  title: "La controversia Heidegger",
  source: "https://www.youtube.com/watch?v=DlWcK5PesPc",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Martin Heidegger** (1889-1976) publica **Ser y tiempo** en 1927 y al año siguiente sucede a Husserl en la cátedra de filosofía de Friburgo. El 21 de abril de 1933, apenas tres meses después de que Hitler llegara al poder, acepta el **rectorado** de esa universidad; diez días después se afilia al Partido Nazi. Renuncia al rectorado menos de un año más tarde, pero permanece afiliado al partido hasta el final de la guerra, en 1945.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "La controversia que ese episodio abrió no se cerró nunca. Tuvo una primera onda expansiva en la desnazificación de posguerra, un resurgimiento en 1987 con la publicación en Francia del libro de **Victor Farías**, Heidegger y el nazismo, que documentó con detalle de archivo la profundidad del compromiso, y una tercera ola desde 2014, cuando empezaron a publicarse los llamados **Cuadernos negros** (Schwarze Hefte), los cuadernos de trabajo filosófico privado que Heidegger llevó desde comienzos de los años treinta.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Esta clase reconstruye ese episodio y sus ecos a través de quienes lo atravesaron de cerca: **Hannah Arendt**, alumna y amante de Heidegger antes de 1933 y su interlocutora, con perdón de por medio, hasta el final de sus vidas; **Edith Stein**, compañera de Heidegger bajo Husserl, asesinada en Auschwitz en 1942; y **Paul Celan**, poeta judío superviviente del Holocausto que en 1967 visitó a Heidegger buscando una palabra que nunca llegó.",
    },
    {
      type: "quiz",
      question: "¿Qué tres oleadas reabrieron sucesivamente la controversia Heidegger?",
      options: [
        "La desnazificación, el libro de Farías y los Cuadernos negros",
        "La muerte de Heidegger, el juicio de Núremberg y la Guerra Fría",
        "El nacimiento de Arendt, el de Celan y el de Patočka",
        "La publicación de Ser y tiempo en tres ediciones sucesivas",
      ],
      answer: 0,
      explain: "La controversia tuvo una primera onda en la desnazificación de posguerra, un resurgimiento en 1987 con el libro de Victor Farías, y una tercera ola desde 2014 con la publicación de los Cuadernos negros.",
    },
    {
      type: "info",
      title: "El problema que hereda: ¿se puede separar al filósofo de su filosofía?",
      body: "Cuando estalla el compromiso de Heidegger con el nazismo, sus lectores quedan ante una pregunta que ningún otro caso del canon filosófico había planteado con esa urgencia: ¿la biografía de un pensador contamina su pensamiento, o el pensamiento tiene vida propia, separable de quien lo produjo? Con Nietzsche la sospecha ya rondaba —su hermana falsificó su legado en clave nazi—, pero ahí el propio pensador podía absolverse: no fue su decisión.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: ¿se puede separar al filósofo de su filosofía?",
      body: "Con Heidegger el compromiso fue **su** decisión, tomada en plena madurez intelectual, sostenida activamente durante meses y nunca retractada en público. Eso vuelve incómoda la separación cómoda entre el hombre y la obra: si su filosofía describe al ser humano como un Dasein radicalmente **incrustado** en su mundo, en su pueblo y en su época, esa misma filosofía dificulta excusarlo alegando que el nazismo fue un accidente externo al pensamiento.",
    },
    {
      type: "quiz",
      question: "¿Por qué el caso de Heidegger es más incómodo que la sospecha sobre Nietzsche?",
      options: [
        "Porque el compromiso fue su propia decisión, no un accidente ajeno",
        "Porque Nietzsche nunca fue leído por pensadores judíos después",
        "Porque Heidegger jamás llegó a afiliarse formalmente al partido",
        "Porque no hay ninguna prueba documental del compromiso de Heidegger",
      ],
      answer: 0,
      explain: "Con Nietzsche el propio pensador podía absolverse: fue su hermana quien falsificó el legado. Con Heidegger el compromiso fue su decisión, tomada en plena madurez y nunca retractada en público.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: ¿se puede separar al filósofo de su filosofía?",
      body: "Y sin embargo, la mayoría de quienes más tenían motivo de reproche —Arendt, Levinas antes de 1933, buena parte de una generación de alumnos judíos— no dejaron nunca de leerlo ni de considerarlo, con matices, el pensador más importante del siglo. Esa tensión sin resolver es el objeto real de la controversia: no si Heidegger fue nazi, que nadie discute, sino qué hacer, después, con su filosofía.",
    },
    {
      type: "info",
      title: "Friburgo, 1916-1928: Husserl, Stein, Heidegger",
      body: "En 1916, en plena Primera Guerra, Husserl acepta la cátedra de Friburgo. Solo dos alumnos lo siguen desde Gotinga, porque la guerra dispersó al resto de su círculo: **Edith Stein**, que trabajaba como enfermera de la Cruz Roja y escribía su tesis sobre la empatía, y el polaco Roman Ingarden. Stein se convierte en la asistente de Husserl: ordenar sus miles de páginas de manuscrito, casi ilegibles, es una tarea que ella misma describe como heroica.",
    },
    {
      type: "info",
      continues: true,
      title: "Friburgo, 1916-1928: Husserl, Stein, Heidegger",
      body: "Heidegger llega a Friburgo desde la teología católica y se suma al círculo de Husserl. En 1917 le escribe a su esposa que no puede aceptar la fenomenología de Husserl tal como está planteada: la juzga demasiado estrecha para la riqueza de la vida. En 1919, de vuelta de la guerra, le confía que cree haber superado ya a Husserl, pero que, por su carrera, tiene que seguir fingiendo adhesión a la fenomenología. Stein lo advierte y se lo escribe a Ingarden; Husserl, entusiasmado con su discípulo, no lo nota.",
    },
    {
      type: "info",
      continues: true,
      title: "Friburgo, 1916-1928: Husserl, Stein, Heidegger",
      body: "En 1923 Heidegger se traslada a Marburgo. Retirado a la cabaña de Todtnauberg, en la Selva Negra, escribe entre 1926 y 1927 el manuscrito de Ser y tiempo, que dedica a Husserl \"en amistad y admiración\" y le entrega, envuelto en flores, el 8 de abril de 1926, para su cumpleaños. En 1928, al jubilarse, Husserl consigue que Heidegger lo suceda en la cátedra de Friburgo: es, en ese momento, su heredero designado.",
    },
    {
      type: "quiz",
      question: "¿Quién advierte primero, en carta a Ingarden, que Heidegger ya se distancia de Husserl?",
      options: [
        "Edith Stein",
        "Hannah Arendt",
        "Karl Jaspers",
        "El propio Husserl",
      ],
      answer: 0,
      explain: "En 1919 Heidegger le confía a su esposa que cree haber superado a Husserl. Stein lo advierte y se lo escribe a Ingarden; Husserl, entusiasmado con su discípulo, no lo nota.",
    },
    {
      type: "info",
      title: "Hannah Arendt en Marburgo",
      body: "En 1924 llega a Marburgo, para estudiar con Heidegger, una alumna de dieciocho años nacida en Königsberg: **Hannah Arendt**. Heidegger, con treinta y cinco años, casado y con dos hijos, se enamora de ella casi de inmediato y le escribe cartas de amor. En 1926 Arendt se va a Heidelberg a completar su doctorado con el amigo de Heidegger, **Karl Jaspers**; en 1928, durante una visita, Heidegger rompe la relación.",
    },
    {
      type: "info",
      continues: true,
      title: "Hannah Arendt en Marburgo",
      body: "El vínculo, sin embargo, no se cierra ahí: atraviesa el resto del siglo, sobrevive al nazismo, a la guerra y al exilio de Arendt en Estados Unidos, y no se resuelve hasta 1950, después de que ambos hayan cruzado el abismo que se abre en 1933.",
    },
    {
      type: "short",
      question: "¿Quién rompe la relación con Arendt en 1928, y con quién completa ella el doctorado?",
      answers: ["jaspers", "karl jaspers"],
      explain: "Heidegger rompe la relación en 1928. Arendt se había ido antes a Heidelberg a completar su doctorado con el amigo de Heidegger, Karl Jaspers, uno de los pocos filósofos alemanes antinazis sin ambigüedades.",
    },
    {
      type: "info",
      title: "1929-1933: el ascenso del nazismo",
      body: "En 1929 llega a estudiar con Husserl y Heidegger un joven filósofo lituano, **Emmanuel Levinas**, que describirá a Heidegger como el discípulo más original de Husserl, cuyo nombre era ya, entonces, la gloria de la filosofía alemana. Esa admiración temprana, compartida por buena parte de una generación de estudiantes —muchos de ellos judíos—, es la que vuelve después tan difícil de asimilar lo que sigue.",
    },
    {
      type: "info",
      continues: true,
      title: "1929-1933: el ascenso del nazismo",
      body: "El 23 de enero de 1933 Husserl invita a Heidegger a celebrar el aniversario de su doctorado, y lo celebran juntos. En marzo los nazis llegan al poder. Arendt, que ya vive en peligro como judía, oye rumores de que Heidegger excluye a los judíos de sus seminarios y le escribe; él responde negando la acusación y agregando que, en todo caso, eso no podría afectar su relación con ella. En abril, una nueva ley racial destituye de su cátedra en Kiel al hijo de Husserl.",
    },
    {
      type: "info",
      continues: true,
      title: "1929-1933: el ascenso del nazismo",
      body: "**Husserl** —que se había convertido al protestantismo décadas antes, junto con su esposa, y no se identificaba como judío— queda igualmente alcanzado por esa ley: es un filósofo alemán que había creído formar parte sin reservas de la cultura que ahora lo excluye por su origen.",
    },
    {
      type: "quiz",
      question: "¿Cómo responde Heidegger cuando Arendt le pregunta por los rumores de exclusión de judíos?",
      options: [
        "Niega la acusación y minimiza el efecto entre ambos",
        "Confirma la acusación y le pide disculpas de inmediato",
        "Corta toda comunicación con Arendt sin responderle",
        "Le propone que ambos abandonen juntos Alemania",
      ],
      answer: 0,
      explain: "Arendt, que ya vive en peligro como judía, le escribe por los rumores; Heidegger responde negando la acusación y agregando que, en todo caso, eso no podría afectar su relación con ella.",
    },
    {
      type: "info",
      title: "El rectorado y el discurso rectoral",
      body: "El 21 de abril de 1933, ocho días después de la ley que expulsó a los judíos de las cátedras, Heidegger acepta el rectorado de la Universidad de Friburgo. El 1.º de mayo se afilia al Partido Nazi. El 27 de mayo pronuncia el discurso de asunción, La autoafirmación de la universidad alemana, que define liderar la universidad como comprometerse con la misión espiritual que el destino del **pueblo alemán** (Volk) impone a quien la conduce.",
    },
    {
      type: "info",
      continues: true,
      title: "El rectorado y el discurso rectoral",
      body: "El discurso no menciona a los judíos ni el antisemitismo: habla de **voluntad**, de sacrificio y del vínculo que ata a la **Volksgemeinschaft**, la comunidad étnico-nacional del pueblo, cuyas fuerzas hay que preservar arraigadas en \"el suelo y la sangre\". Cita a Nietzsche —\"Dios ha muerto\"— para presentar al nacionalsocialismo como la respuesta espiritual que Alemania necesita frente a ese vacío.",
    },
    {
      type: "info",
      continues: true,
      title: "El rectorado y el discurso rectoral",
      body: "El vocabulario es reconocible: es el vocabulario del Dasein arrojado a un pueblo y a una historia que no elige, vuelto ahora consigna política. Heidegger llama a los estudiantes a los sacrificios necesarios para salvar la esencia del pueblo y describe a Hitler —der Führer— como la realidad alemana presente y futura, cuya ley exige de cada acción una decisión y una responsabilidad. El decisionismo de Ser y tiempo, pensado para el individuo, se traslada aquí a la nación entera.",
    },
    {
      type: "quiz",
      question: "¿Qué desplazamiento filosófico opera el discurso rectoral de 1933?",
      options: [
        "Traslada el decisionismo individual a la nación entera",
        "Abandona por completo el vocabulario de Ser y tiempo",
        "Introduce por primera vez la noción de Dasein en la obra de Heidegger",
        "Rechaza explícitamente cualquier vínculo con el nacionalsocialismo",
      ],
      answer: 0,
      explain: "El discurso reconoce el vocabulario del Dasein arrojado a un pueblo y una historia que no elige, vuelto consigna política: el decisionismo pensado para el individuo se traslada aquí a la nación entera, encarnada en el Führer.",
    },
    {
      type: "info",
      title: "Retirada y ambigüedad",
      body: "Menos de un año después, en febrero de 1934, Heidegger renuncia al rectorado. En 1935, en unas conferencias publicadas luego como Introducción a la metafísica, dice, ya desilusionado, que lo que circula como \"filosofía del nacionalsocialismo\" no tiene nada que ver con la verdad interior y la grandeza de ese movimiento: una frase que, lejos de retractarse, sigue defendiendo alguna versión más pura de lo que el movimiento debía haber sido.",
    },
    {
      type: "info",
      continues: true,
      title: "Retirada y ambigüedad",
      body: "Ese mismo año, el joven filósofo checo **Jan Patočka**, que había estudiado con Husserl y asistido a clases de Heidegger en Friburgo, ayuda a organizar la visita de Husserl —ya expulsado de la vida académica alemana por su origen— a Praga, donde da las conferencias de las que saldrá su último libro, La crisis de las ciencias europeas. Husserl sostiene ahí que Europa se asoma al abismo de la barbarie porque el racionalismo ilustrado se interpretó de un modo demasiado superficial.",
    },
    {
      type: "info",
      continues: true,
      title: "Retirada y ambigüedad",
      body: "Ser y tiempo se reedita, mientras tanto, sin la dedicatoria a Husserl. En 1938 Husserl muere; Heidegger no asiste al funeral.",
    },
    {
      type: "quiz",
      question: "En 1935, ¿cómo se retracta Heidegger de la \"filosofía del nacionalsocialismo\"?",
      options: [
        "No se retracta: la ve como traición a la grandeza del movimiento",
        "Publica una disculpa formal y renuncia de inmediato al partido",
        "Reconoce públicamente haberse equivocado por completo en 1933",
        "Deja de usar cualquier vocabulario propio de Ser y tiempo",
      ],
      answer: 0,
      explain: "En Introducción a la metafísica dice que lo que circula como \"filosofía del nacionalsocialismo\" no tiene nada que ver con la verdad interior y la grandeza de ese movimiento: lejos de retractarse, defiende una versión más pura de lo que debía haber sido.",
    },
    {
      type: "info",
      title: "El destino de Edith Stein",
      body: "Stein no consigue nunca la **habilitación** que le habría permitido enseñar en la universidad: a la barrera de ser mujer se suma, después de 1933, la de ser judía. Se convierte al catolicismo, enseña en un colegio religioso y en 1933 ingresa a un convento carmelita. En 1939 las monjas la trasladan a un convento en los Países Bajos, buscando ponerla a salvo. El 2 de agosto de 1942 la Gestapo la detiene; días después es asesinada en las cámaras de gas de Auschwitz.",
    },
    {
      type: "info",
      continues: true,
      title: "El destino de Edith Stein",
      body: "Heidegger, que le había sucedido como asistente de Husserl, escribió al año siguiente que \"el planeta está en llamas\" y que solo de los alemanes podía venir una reflexión histórico-mundial capaz de salvar la esencia del hombre, si lograban preservar su germanidad. La frase, de 1943, no menciona a Stein ni a ninguna de las víctimas del exterminio ya en marcha.",
    },
    {
      type: "quiz",
      question: "¿Qué llama más la atención de la frase de Heidegger de 1943 sobre \"el planeta en llamas\"?",
      options: [
        "Que no menciona a Stein ni a ninguna víctima del exterminio en curso",
        "Que reconoce abiertamente el genocidio en marcha contra los judíos",
        "Que fue escrita en homenaje directo a Edith Stein",
        "Que Heidegger la retracta apenas un año después de escribirla",
      ],
      answer: 0,
      explain: "Heidegger, que había sucedido a Stein como asistente de Husserl, habla de salvar la esencia del hombre preservando la germanidad, pero la frase de 1943 no menciona a Stein ni a ninguna de las víctimas del exterminio ya en marcha.",
    },
    {
      type: "info",
      title: "Posguerra: desnazificación y culpa",
      body: "Heidegger conserva su afiliación al Partido Nazi hasta 1945. Terminada la guerra, la comisión de desnazificación de Friburgo consulta a **Karl Jaspers**, que no le habla desde 1933 y es uno de los pocos filósofos alemanes antinazis sin ambigüedades. Jaspers responde, en diciembre de 1945, que Heidegger combina la seriedad del nihilismo con la mistagogia de un mago, que sus talentos son quizá únicos en la Alemania contemporánea, y que debería poder seguir pensando y escribiendo, pero no enseñar todavía: los estudiantes, dice, son demasiado vulnerables.",
    },
    {
      type: "info",
      continues: true,
      title: "Posguerra: desnazificación y culpa",
      body: "La comisión prohíbe a Heidegger dar clases durante varios años. Poco después Jaspers escribe La cuestión de la culpa alemana, donde sostiene que la culpa alemana no es solo la de quienes cometieron los crímenes, sino también la de quienes, pudiendo resistir, prefirieron seguir con vida: \"somos culpables de estar vivos\", escribe, y no ve otra salida para los alemanes que una purificación desde la conciencia de esa culpa.",
    },
    {
      type: "quiz",
      question: "¿Qué recomienda Jaspers a la comisión de desnazificación sobre Heidegger?",
      options: [
        "Que pudiera seguir pensando y escribiendo, pero no enseñar todavía",
        "Que se le prohibiera para siempre publicar cualquier texto",
        "Que se lo procesara penalmente junto a los criminales de guerra",
        "Que retomara de inmediato sus clases sin ninguna restricción",
      ],
      answer: 0,
      explain: "Jaspers responde que Heidegger combina la seriedad del nihilismo con la mistagogia de un mago, con talentos quizá únicos, pero que debería poder seguir pensando y escribiendo sin enseñar todavía: los estudiantes, dice, son demasiado vulnerables.",
    },
    {
      type: "info",
      title: "Arendt y Heidegger: la reconciliación",
      body: "En febrero de 1950, ya instalada en Estados Unidos, Arendt vuelve a Alemania y visita a Heidegger y a su esposa Elfride. Ninguna de las dos disculpas que cada una esperaba de la otra —Elfride por el romance, Arendt por el nazismo de Elfride— llega a producirse. Días después Heidegger le escribe explicando, de un modo que a la distancia resulta difícil de leer, que su silencio de tantos años había sido para proteger la relación, no para negarla.",
    },
    {
      type: "info",
      continues: true,
      title: "Arendt y Heidegger: la reconciliación",
      body: "Arendt le responde que esa noche confirma \"toda una vida\", y le escribe también a Elfride que lo que hubo entre ambos \"nunca fue personal\". Desde ese reencuentro y hasta la muerte de Heidegger, en 1976, retoman una correspondencia sostenida: él vuelve a escribirle poesía, décadas después de la ruptura.",
    },
    {
      type: "info",
      title: "El perdón",
      body: "**Herbert Marcuse**, también alumno judío de Heidegger y también exiliado en Estados Unidos, le escribe en 1947 pidiéndole una explicación pública: no duda de que Heidegger se haya distanciado del régimen después de 1934, pero le reprocha no haber retractado nunca, ni siquiera tras 1945, su identificación inicial con el nazismo. Le recuerda que el propio Heidegger enseñó que no se puede separar al filósofo del hombre: uno puede equivocarse en política y reconocerlo, pero no puede equivocarse sobre un régimen que asesinó a millones de personas por su origen.",
    },
    {
      type: "info",
      continues: true,
      title: "El perdón",
      body: "Heidegger responde en 1948 que en 1933 esperaba del nacionalsocialismo una renovación espiritual y una salida a los antagonismos sociales, y que no ofreció una retractación pública porque eso habría significado el fin de su carrera y de su familia. Nunca pide perdón, ni a Marcuse ni a nadie; y sin embargo Arendt lo perdona, sin que medie ninguna petición de su parte.",
    },
    {
      type: "quiz",
      question: "¿Qué le reprocha Marcuse a Heidegger en 1947, más allá del compromiso de 1933?",
      options: [
        "No haber retractado nunca su identificación inicial con el nazismo",
        "No haber emigrado a Estados Unidos como el propio Marcuse",
        "Haber roto por completo con la fenomenología de Husserl",
        "No haber escrito nunca sobre la cuestión de la técnica",
      ],
      answer: 0,
      explain: "Marcuse no duda de que Heidegger se haya distanciado del régimen después de 1934, pero le reprocha no haber retractado nunca, ni siquiera tras 1945, su identificación inicial con el nazismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El perdón",
      body: "Ese gesto se vuelve, para Arendt, materia de reflexión filosófica. En La condición humana (1958) —libro que dedica en silencio a Heidegger— escribe que perdonar es la única acción capaz de deshacer, aunque sea parcialmente, lo irreversible: la única reacción que no se limita a reaccionar, sino que actúa de nuevo, sin quedar condicionada por lo que la provocó.",
    },
    {
      type: "info",
      title: "\"Solo un dios puede salvarnos\"",
      body: "Heidegger habla en público sobre su nazismo una sola vez: en una entrevista a la revista Der Spiegel, concedida en 1966 con la condición expresa de no publicarse hasta después de su muerte. Aparece en 1976, pocos días después de que muriera. Admite ahí que el nazismo pudo ser un error, pero insiste en que la civilización occidental sigue atravesando la crisis de un mundo sin Dios que ya había diagnosticado Nietzsche, y que frente a eso \"solo un dios puede salvarnos\".",
    },
    {
      type: "info",
      continues: true,
      title: "\"Solo un dios puede salvarnos\"",
      body: "Cuando la entrevista se publica, los alumnos de Jan Patočka —que había vivido la ocupación nazi de Checoslovaquia y perdido amigos en el Holocausto— le hacen llegar una copia de contrabando y le piden que responda. Patočka dice que en 1976 es obvio para cualquiera qué fue el nazismo, pero que la pregunta real es si eso podía estarle igual de claro a un alemán en 1933, y si ese alemán, en esas circunstancias, tenía otra opción que probarlo.",
    },
    {
      type: "quiz",
      question: "¿Cuál es, para Patočka, la pregunta real detrás del \"solo un dios puede salvarnos\"?",
      options: [
        "Si a un alemán de 1933 le era tan claro como a nosotros hoy",
        "Si Heidegger merece o no seguir siendo leído en las universidades",
        "Si el nazismo fue, en el fondo, un régimen defendible",
        "Si la entrevista debió publicarse antes de la muerte de Heidegger",
      ],
      answer: 0,
      explain: "Patočka dice que en 1976 es obvio para cualquiera qué fue el nazismo, pero que la pregunta real es si eso podía estarle igual de claro a un alemán en 1933, y si ese alemán tenía otra opción que probarlo.",
    },
    {
      type: "info",
      title: "Levinas: lo que no se perdona",
      body: "**Emmanuel Levinas**, que en 1929 había llamado a Heidegger el discípulo más original de Husserl, pierde en el Holocausto a buena parte de su familia. Ya en 1934, meses después del ascenso nazi, publica un ensayo temprano sobre la filosofía del hitlerismo que lee el nazismo como una filosofía de la encarnación y el arraigo biológico, sin nombrar todavía a Heidegger.",
    },
    {
      type: "info",
      continues: true,
      title: "Levinas: lo que no se perdona",
      body: "Después de la guerra, Levinas sigue leyendo y discutiendo con la filosofía de Heidegger durante el resto de su obra —la propia idea de la responsabilidad hacia el Otro que desarrolla puede leerse como una respuesta a la filosofía de la incrustación heideggeriana—, pero declarará, en distintas ocasiones, que hay algo en el silencio sostenido de Heidegger sobre el exterminio que le resulta particularmente difícil de perdonar.",
    },
    {
      type: "quiz",
      question: "¿Qué le resulta a Levinas particularmente difícil de perdonar en Heidegger?",
      options: [
        "El silencio sostenido sobre el exterminio, no el compromiso inicial",
        "Que Heidegger nunca haya leído la fenomenología de Husserl",
        "Que Heidegger jamás mencionara la ocupación de Francia",
        "Que Heidegger se negara a discutir con él después de la guerra",
      ],
      answer: 0,
      explain: "Levinas sigue leyendo y discutiendo con la filosofía de Heidegger toda su vida, pero declara que hay algo en su silencio sostenido sobre el exterminio —no ya el compromiso de 1933— que le resulta particularmente difícil de perdonar.",
    },
    {
      type: "info",
      title: "Paul Celan y la palabra que no llegó",
      body: "**Paul Celan**, poeta judío rumano nacido en 1920 en Czernowitz, sobreviviente del Holocausto e hijo de padres asesinados, escribe después de la guerra en alemán: la lengua que llama, a la vez, Muttersprache y Mördersprache, lengua materna y lengua del asesino. Su poema Todesfuge fija una imagen —\"la muerte es un maestro de Alemania\"— que Adorno citará al matizar después su propio juicio de que escribir poesía tras Auschwitz era un acto de barbarie.",
    },
    {
      type: "info",
      continues: true,
      title: "Paul Celan y la palabra que no llegó",
      body: "Hacia 1966-67 Celan, ya célebre, da un recital en Friburgo al que asiste Heidegger, admirador de su poesía. Este lo invita después a su cabaña de Todtnauberg; en el libro de visitas, Celan escribe que espera \"una palabra por venir\". Una semana más tarde escribe un poema sobre esa visita, donde repite la misma espera. No hay registro de qué se dijeron en la caminata.",
    },
    {
      type: "info",
      continues: true,
      title: "Paul Celan y la palabra que no llegó",
      body: "Tres o cuatro años después, en París, Celan se suicida arrojándose al Sena. La palabra que esperaba —algo del silencio de Heidegger sobre el exterminio— no llegó nunca.",
    },
    {
      type: "quiz",
      question: "¿Qué deja escrito Celan en el libro de visitas de Todtnauberg?",
      options: [
        "Que espera una palabra por venir de parte de Heidegger",
        "Un agradecimiento formal por la invitación recibida",
        "Una crítica explícita al silencio de Heidegger sobre el exterminio",
        "Una despedida definitiva, sin intención de volver a escribirle",
      ],
      answer: 0,
      explain: "Celan escribe que espera «una palabra por venir». Una semana después escribe un poema sobre esa visita repitiendo la misma espera; esa palabra —sobre el silencio de Heidegger frente al exterminio— nunca llegó.",
    },
    {
      type: "info",
      title: "Las oleadas de la polémica",
      body: "La controversia no terminó con la muerte de Heidegger. En 1987 se publica en Francia el libro de Victor Farías, Heidegger y el nazismo, que documenta con detalle de archivo la profundidad y la duración del compromiso, más allá de lo que Heidegger había dejado entrever. El libro provoca un debate público intenso, sobre todo en Francia, donde pensadores que habían sido lectores admirativos de Heidegger, como Lyotard, se ven obligados a repensar los términos de esa lectura.",
    },
    {
      type: "info",
      continues: true,
      title: "Las oleadas de la polémica",
      body: "Desde 2014 empiezan a publicarse los **Cuadernos negros** (Schwarze Hefte), los cuadernos de trabajo filosófico privado que Heidegger llevó desde comienzos de los años treinta. Contienen pasajes que vinculan el antisemitismo con categorías centrales de su propia filosofía de la historia del ser, y desatan una tercera ola de la controversia, ya no centrada en la biografía política de 1933 sino en el corpus filosófico tardío.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la ola de los Cuadernos negros de la ola de Farías?",
      options: [
        "Se centra en el corpus filosófico tardío, no en la biografía de 1933",
        "Demuestra por primera vez que Heidegger fue miembro del partido",
        "Absuelve a Heidegger de cualquier vínculo con el nazismo",
        "Se limita a repetir, sin archivo nuevo, lo que ya dijo Farías",
      ],
      answer: 0,
      explain: "El libro de Farías (1987) documenta con detalle de archivo la biografía política. Los Cuadernos negros (desde 2014) desatan una tercera ola centrada en el corpus filosófico tardío: pasajes que vinculan el antisemitismo con categorías centrales de su pensamiento.",
    },
    {
      type: "match",
      question: "Uní cada figura con lo que representa en la controversia Heidegger",
      pairs: [
        { left: "Jaspers", right: "Recomienda que Heidegger piense pero no enseñe todavía" },
        { left: "Arendt", right: "Rompe, se reconcilia en 1950 y termina perdonándolo" },
        { left: "Marcuse", right: "Le reprocha no haber retractado nunca su nazismo" },
        { left: "Patočka", right: "Pregunta si un alemán de 1933 podía verlo tan claro" },
        { left: "Celan", right: "Espera en Todtnauberg una palabra que nunca llegó" },
      ],
      explain: "Cada figura atraviesa la controversia desde un lugar distinto: Jaspers desde la desnazificación institucional, Arendt desde el perdón, Marcuse desde el reproche sin concesiones, Patočka desde la generosidad histórica, y Celan desde la espera incumplida.",
    },
    {
      type: "info",
      title: "Cierre: la verdadera controversia",
      body: "La controversia Heidegger no discute si Heidegger fue nazi: eso está probado y nadie lo niega. Discute qué significa eso para cómo se lee su filosofía, y para cómo se lee la obra de quienes, como Arendt, se formaron con él y siguieron pensando con y contra sus categorías toda la vida. Se ha argumentado que la misma idea de un Dasein siempre ya incrustado en su mundo, que ya no puede desarticularse limpiamente de él, abre una pendiente hacia la disolución del sujeto que puede desembocar tanto en la Volksgemeinschaft como, en último término, en las cámaras de gas.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la verdadera controversia",
      body: "En 1988, en un seminario sobre Heidegger dado en Alemania, un estudiante le preguntó a Derrida —judío él mismo— qué hacía con el hecho de que Heidegger hubiera sido nazi. Derrida respondió que eso no está en discusión, que se sabe; la pregunta real es otra: si Heidegger habría sido el filósofo que fue sin ese mismo elemento de su pensamiento que también lo acercó al nazismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la verdadera controversia",
      body: "Según relató después el crítico literario Hans Gumbrecht, presente en la sala, esa pregunta —si lo que vuelve grande a un pensamiento y lo que lo vuelve peligroso pueden ser la misma cosa— es la razón por la que una universidad tiene que poder seguir planteándola.",
    },
  ],
};
