export default {
  num: 17,
  transcript: 17,
  title: "Fichte y la Doctrina de la Ciencia",
  source: "",
  feed: [
    {
      type: "info",
      title: "Lo que Kant dejó abierto",
      body: "La Crítica de la razón pura fundó la ciencia y desalojó a la metafísica, pero no cerró el problema: lo desplazó. La generación que la leyó a fines del siglo XVIII no la recibió como un punto final sino como un edificio inacabado, con tres junturas a la vista que había que resolver.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que Kant dejó abierto",
      body: "La primera es la dualidad entre la cosa en sí y el fenómeno. Kant sostiene a la vez que la cosa en sí es incognoscible y que hace falta, porque explica nuestra pasividad al percibir y garantiza que el conocimiento no sea una invención subjetiva. Es un elemento imprescindible del sistema al que el sistema no puede acceder.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que Kant dejó abierto",
      body: "La segunda es la heterogeneidad radical entre la sensibilidad y el entendimiento. Kant separa los dos troncos del conocimiento con toda nitidez, y esa nitidez es lo que le permite su arquitectura. Pero si son de naturaleza tan distinta, ¿cómo se garantiza que las categorías a priori se apliquen efectivamente a lo que la intuición recibe?",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que Kant dejó abierto",
      body: "La tercera la reconoció Kant mismo: la brecha entre el ámbito de la necesidad —la naturaleza, que se conoce por intuición y entendimiento— y el de la libertad, que supone el ejercicio de la razón pura práctica. A tender ese puente dedicó su tercera obra crítica, la Crítica del juicio de 1790, sin que la cuestión quedara zanjada.",
    },
    {
      type: "quiz",
      question: "¿Por qué la cosa en sí resulta un problema dentro del propio sistema de Kant?",
      options: ["Porque Kant nunca llega a definir con precisión el término", "Porque el sistema la necesita pero no puede conocerla", "Porque contradice las formas puras de espacio y tiempo", "Porque sólo aparece en la segunda edición de la Crítica"],
      answer: 1,
      explain: "Kant sostiene a la vez que es incognoscible y que hace falta, porque explica nuestra pasividad al percibir y garantiza que el conocimiento no sea una invención subjetiva. Es imprescindible y a la vez inaccesible.",
    },
    {
      type: "info",
      title: "Idealismo trascendental y realismo empírico",
      body: "Antes de ver qué hicieron sus herederos con esas junturas, conviene precisar en qué consistía exactamente el idealismo de Kant, porque él se ocupó de distinguirlo de otros. El texto es la crítica del **cuarto paralogismo**, un pasaje de la primera edición que Kant suprimió en 1787, y donde sale al cruce de la duda sobre la existencia de los objetos exteriores.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo trascendental y realismo empírico",
      body: "El razonamiento que quiere desarmar es conocido: sólo lo que está en nosotros se percibe inmediatamente, la existencia de un objeto exterior únicamente puede inferirse como causa de la percepción, y toda inferencia de una causa a partir de un efecto es insegura. Kant precisa que quien razona así no niega los objetos exteriores: sostiene que nunca podemos estar seguros de ellos. Es el **idealismo empírico**, y se lo atribuye a Descartes y a Berkeley.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo trascendental y realismo empírico",
      body: "Frente a eso define su propia posición. El **idealismo trascendental** es la doctrina según la cual todos los fenómenos son meras representaciones y no cosas en sí; espacio y tiempo son formas de nuestra intuición, no determinaciones dadas por sí mismas. Se le opone el **realismo trascendental**, que toma espacio y tiempo como algo dado con independencia de la sensibilidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo trascendental y realismo empírico",
      body: "Y aquí viene el giro del argumento. Es el realista trascendental el que termina haciendo de idealista empírico: si uno supone que los objetos, para ser exteriores, tienen que existir en sí mismos prescindiendo de los sentidos, descubre después que ninguna representación alcanza para garantizar su realidad, y cae en la duda. El idealista trascendental, en cambio, puede ser **realista empírico**, porque admite la materia en cuanto fenómeno.",
    },
    {
      type: "classify",
      question: "¿Cada tesis corresponde al idealismo trascendental o al idealismo empírico?",
      groups: ["Idealismo trascendental", "Idealismo empírico"],
      items: [
        { text: "Los fenómenos son representaciones, no cosas en sí", group: 0 },
        { text: "Es compatible con un realismo empírico", group: 0 },
        { text: "Espacio y tiempo son formas de nuestra intuición", group: 0 },
        { text: "La existencia de los objetos externos queda en duda", group: 1 },
        { text: "Kant se lo atribuye a Descartes y a Berkeley", group: 1 },
        { text: "Nace de suponer que los objetos existen en sí", group: 1 },
      ],
      explain: "Kant separa su idealismo del de Descartes y Berkeley. La materia se vuelve dudosa sólo si antes se supuso, como hace el realista trascendental, que los objetos exteriores tienen que existir prescindiendo de los sentidos.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo trascendental y realismo empírico",
      body: "De todo esto se sigue un aporte que Fichte, Schelling y Hegel van a retomar: una noción nueva de verdad. Tradicionalmente era la adecuación del intelecto a la cosa; después del giro copernicano la cosa en sí ya no puede ser el criterio. El criterio pasa a ser la conformidad de la representación con las formas universales del conocimiento, algo que se juega enteramente dentro de la conciencia.",
    },
    {
      type: "quiz",
      question: "Después del giro copernicano, ¿en qué pasa a consistir el criterio de verdad?",
      options: ["En la adecuación del intelecto a la cosa conocida", "En la conformidad con las formas del conocimiento", "En la coincidencia entre lo que perciben varios sujetos", "En poder deducir el fenómeno a partir de la cosa en sí"],
      answer: 1,
      explain: "La cosa en sí ya no puede ser el criterio, porque queda fuera del alcance del conocimiento. El criterio se juega enteramente dentro de la conciencia, y por eso Fichte, Schelling y Hegel lo van a retomar y profundizar.",
    },
    {
      type: "info",
      title: "Los escépticos y la exigencia de sistema",
      body: "La distinción entre fenómenos y cosas en sí generó de inmediato lecturas incompatibles: unos entendieron un idealismo que negaba el mundo, otros encontraron apoyo para una lectura realista, porque en varios pasajes Kant habla de la cosa en sí como fundamento o causa de los fenómenos. Pero la acusación más seria fue la de conducir al escepticismo. G. E. Schulze, Salomon Maimon y Ernst Platner sostuvieron que la Crítica no lograba refutar a Hume: dejaba abierta la relación entre nuestras representaciones y las cosas tal como son en sí, y no aseguraba lo que prometía asegurar.",
    },
    {
      type: "info",
      continues: true,
      title: "Los escépticos y la exigencia de sistema",
      body: "La objeción de Maimon, en su Estudio sobre la filosofía trascendental de 1790, es la más filosa y ataca la segunda juntura. Si Kant estableció la heterogeneidad total entre sensibilidad y entendimiento, entonces es imposible garantizar que las categorías a priori se apliquen a las intuiciones a posteriori. La separación que funda el sistema es la que lo deja sin costura.",
    },
    {
      type: "quiz",
      question: "¿Contra qué parte del sistema kantiano apunta la objeción de Maimon?",
      options: ["Contra la separación entre sensibilidad y entendimiento", "Contra la idea de que el espacio es una forma pura", "Contra la deducción de las categorías desde la lógica", "Contra la refutación kantiana del idealismo empírico"],
      answer: 0,
      explain: "Si los dos troncos del conocimiento son totalmente heterogéneos, nada garantiza que las categorías a priori se apliquen a las intuiciones a posteriori. La separación que funda el sistema es la que lo deja sin costura.",
    },
    {
      type: "info",
      continues: true,
      title: "Los escépticos y la exigencia de sistema",
      body: "Frente a esto surge una convicción compartida: había que completar la filosofía kantiana y transformarla en un auténtico **sistema**, entendido como un conjunto de proposiciones derivadas de un principio fundamental, un Grundsatz. Carl Leonhard Reinhold (1757–1823) fue el primero en formular la exigencia y en proponer un candidato: la conciencia.",
    },
    {
      type: "short",
      question: "¿Cómo se llama el principio fundamental del que, según Reinhold, todo el sistema debería derivarse?",
      answers: ["Grundsatz", "principio fundamental"],
      explain: "Reinhold fue el primero en exigir que el idealismo trascendental se transformara en un verdadero sistema, derivado de un único Grundsatz. Él propuso la conciencia; Fichte va a proponer el Yo absoluto.",
    },
    {
      type: "info",
      continues: true,
      title: "Los escépticos y la exigencia de sistema",
      body: "La nueva generación siguió a Reinhold en el diagnóstico y no en la solución. Fichte, Schelling y Hegel estaban convencidos de que el idealismo trascendental había inaugurado el camino de la filosofía verdadera, pero vieron en la cosa en sí un elemento insostenible y en la falta de un principio único el defecto que había que reparar.",
    },
    {
      type: "info",
      title: "Fichte, de Rammenau a Jena",
      body: "**Johann Gottlieb Fichte** (1762–1814) nació en Rammenau, en una familia pobre. Se destacó pronto como un prodigio y el barón Ernst Haubold von Miltiz se hizo cargo de sus estudios en la escuela de Schulpforte, entre 1774 y 1780. Siguió teología en Jena y en Leipzig, y en 1788 viajó a pie a Zúrich a trabajar como preceptor.",
    },
    {
      type: "info",
      continues: true,
      title: "Fichte, de Rammenau a Jena",
      body: "Su encuentro con Kant fue un accidente laboral. De vuelta en Leipzig, en 1790, lo contrató como tutor un estudiante que necesitaba ayuda para entender la filosofía crítica. Fichte tuvo que estudiarla para enseñarla, y lo que encontró le cambió la vida.",
    },
    {
      type: "info",
      continues: true,
      title: "Fichte, de Rammenau a Jena",
      body: "«Desde que he leído la Crítica de la razón práctica, vivo en un mundo nuevo», escribe a su amigo Weisshuhn. «Principios que tenía por irrefutables se me han venido abajo; he visto probadas cosas que creía nunca podrían ser probadas, por ejemplo, el concepto de una libertad absoluta. ¡Es increíble el respeto por la humanidad, la fuerza que nos confiere este sistema!»",
    },
    {
      type: "info",
      continues: true,
      title: "Fichte, de Rammenau a Jena",
      body: "En 1791 viajó a Königsberg para conocer a Kant y durante la visita escribió su primera obra importante, el Ensayo de una crítica de toda revelación. Apareció en 1792 con el editor de Kant y sin nombre de autor. El descuido, sumado al lenguaje kantiano del texto, hizo que todos creyeran que era la esperada obra de Kant sobre filosofía de la religión.",
    },
    {
      type: "info",
      continues: true,
      title: "Fichte, de Rammenau a Jena",
      body: "Kant aclaró públicamente el malentendido, y el joven desconocido saltó a la fama de un día para el otro. Poco después, tras publicar algunos textos anónimos a favor de la Revolución Francesa, Fichte fue convocado a la Universidad de Jena para ocupar la cátedra que Reinhold había dejado vacante. Empezó a enseñar en 1794.",
    },
    {
      type: "quiz",
      question: "¿Por qué el Ensayo de una crítica de toda revelación hizo famoso a Fichte?",
      options: ["Porque Kant lo elogió en el prólogo de la segunda edición", "Porque salió sin firma y lo tomaron por obra de Kant", "Porque fue prohibido por la censura de Königsberg", "Porque respondía a la polémica sobre el spinozismo"],
      answer: 1,
      explain: "Apareció en 1792 con el editor de Kant y sin nombre de autor, y el lenguaje kantiano del texto hizo el resto. Kant aclaró públicamente el malentendido y el joven desconocido saltó a la fama.",
    },
    {
      type: "info",
      title: "La Doctrina de la ciencia",
      body: "Fichte fue publicando por entregas los apuntes que redactaba para sus oyentes, y esas entregas conforman el Fundamento de toda la Doctrina de la Ciencia, la primera versión de su sistema. La ambición declarada es la misma que la de Kant: encontrar el camino por el cual la filosofía se eleve al rango de una ciencia evidente.",
    },
    {
      type: "info",
      continues: true,
      title: "La Doctrina de la ciencia",
      body: "Eso supone establecer un principio fundamental de todo saber humano que sea absolutamente primero, completamente incondicionado, no demostrado ni determinado. Un principio así no puede encontrarse entre las determinaciones empíricas de la conciencia, porque es lo que las funda: es el fundamento de la conciencia y lo que la hace posible.",
    },
    {
      type: "info",
      continues: true,
      title: "La Doctrina de la ciencia",
      body: "**Doctrina de la ciencia** —Wissenschaftslehre— es el nombre que Fichte le da a su filosofía, y el nombre dice el programa. Es un saber del saber, una meta-ciencia, una reconstrucción del saber a partir de su último fundamento. Establece los elementos imprescindibles del conocimiento mostrando el conjunto de reglas necesarias del pensar.",
    },
    {
      type: "info",
      continues: true,
      title: "La Doctrina de la ciencia",
      body: "Pero no es un mero discurso epistemológico. En la medida en que es el fundamento de la experiencia empírica y no sólo el análisis de sus condiciones, la Doctrina de la ciencia constituye también una metafísica y una ontología. Es en ese paso donde Fichte va más lejos que Kant, aunque insista en que no hace otra cosa que completarlo.",
    },
    {
      type: "quiz",
      question: "¿Qué agrega la Doctrina de la ciencia respecto de un mero análisis de las condiciones del saber?",
      options: ["Que además funda la experiencia, y por eso es una ontología", "Que reemplaza el método trascendental por uno histórico", "Que restringe su alcance a las ciencias de la naturaleza", "Que renuncia a buscar un principio primero del saber"],
      answer: 0,
      explain: "Como Kant, reflexiona sobre la estructura del saber. Pero en la medida en que es el fundamento de la experiencia empírica y no sólo el análisis de sus condiciones, constituye también una metafísica y una ontología.",
    },
    {
      type: "info",
      title: "El Yo absoluto",
      body: "El principio fundamental que Fichte propone es el **Yo puro** o **Yo absoluto**: la subjetividad trascendental en cuanto condición última de posibilidad de toda acción particular de la conciencia, el conocimiento incluido. Es el fundamento absoluto sobre el que reposan todas las leyes de la conciencia y los principios que configuran lo objetivo.",
    },
    {
      type: "info",
      continues: true,
      title: "El Yo absoluto",
      body: "Hay que cuidarse de imaginarlo como una cosa. El Yo absoluto no es una sustancia, no es un ente, no existe en el mismo sentido en que existen los objetos del mundo. No es un resultado ni un producto: debe concebirse como pura producción. Es, en la fórmula de Fichte, «aquello cuyo ser consiste en ponerse a sí mismo como siendo».",
    },
    {
      type: "info",
      continues: true,
      title: "El Yo absoluto",
      body: "El término técnico es **Thathandlung**, acción productiva: un término compuesto donde están unidas la acción y el producto de la acción, porque no hay aquí un agente previo que después actúe. El ser del Yo es su actuar. Y dado que se afirma absolutamente, sin que nada exterior lo determine, su acción es enteramente libre.",
    },
    {
      type: "quiz",
      question: "¿Por qué insiste Fichte en que el Yo absoluto no es una sustancia?",
      options: ["Porque es una idea regulativa sin realidad efectiva", "Porque su ser no es otra cosa que su propio actuar", "Porque se identifica con la suma de los yoes empíricos", "Porque depende del mundo exterior para determinarse"],
      answer: 1,
      explain: "No es un resultado ni un producto sino pura producción. Thathandlung une en una sola palabra la acción y el producto de la acción, porque no hay aquí un agente previo que después actúe.",
    },
    {
      type: "info",
      continues: true,
      title: "El Yo absoluto",
      body: "De ahí la reivindicación con la que Fichte presenta su filosofía: es el primer y único **sistema de la libertad**. La acción originaria de autoposición del Yo garantiza la autonomía moral de los sujetos empíricos, que no son sino manifestaciones limitadas y finitas de ese Yo que es su fundamento ontológico.",
    },
    {
      type: "short",
      question: "¿Con qué término llama Fichte a la acción productiva en la que están unidos la acción y su producto?",
      answers: ["Thathandlung", "Tathandlung", "acción productiva"],
      explain: "El Yo absoluto es aquello cuyo ser consiste en ponerse a sí mismo como siendo. Como se afirma sin que nada exterior lo determine, su acción es enteramente libre, y por eso Fichte llama a su filosofía el primer sistema de la libertad.",
    },
    {
      type: "info",
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "El Fundamento fue acusado de oscuro y críptico, y en 1797 Fichte publicó en el Philosophisches Journal una Primera y una Segunda introducción a la Doctrina de la Ciencia, donde reexpone las mismas ideas para un público más amplio. La Primera introducción es el texto donde su posición se vuelve más clara y más incómoda.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "Empieza con una instrucción: «Desvía tu mirada de todo lo que te rodea y dirígela a tu interior». Explorada la propia conciencia, se encuentran dos clases de representaciones. Unas vienen acompañadas por el sentimiento de la libertad —las de la fantasía y la voluntad—; otras, por el sentimiento de la necesidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "Las primeras no plantean el problema de su fundamento: son así porque yo las determiné así. Las segundas sí, porque las referimos a una verdad que debe existir independientemente de nosotros. Explicar el fundamento de ese sistema de representaciones necesarias —o sea, de la experiencia— es, según Fichte, el problema entero de la filosofía. Y como el fundamento de algo cae siempre fuera de lo fundado, se sigue que si la filosofía debe indicar el fundamento de toda experiencia, entonces su objeto está necesariamente fuera de toda experiencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "¿Cómo se llega ahí? Por abstracción, «separar mediante la libertad del pensar lo unido en la experiencia». Lo que está unido en la experiencia son la cosa y la inteligencia que la conoce. Abstrayendo uno de los dos, el filósofo se eleva por encima de la experiencia, y se le abren exactamente dos caminos.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "Si abstrae de la cosa, obtiene una inteligencia en sí, y ese proceder se llama **idealismo**. Si abstrae de la inteligencia, obtiene una cosa en sí, y ese proceder se llama **dogmatismo**. Fichte concluye que sólo estos dos sistemas filosóficos son posibles: uno puede ser dogmático o idealista, y no hay una tercera opción.",
    },
    {
      type: "classify",
      question: "Según la Primera introducción, ¿cada rasgo es del idealismo o del dogmatismo?",
      groups: ["Idealismo", "Dogmatismo"],
      items: [
        { text: "Abstrae de la cosa y llega a una inteligencia en sí", group: 0 },
        { text: "Su objeto puede mostrarse a la conciencia", group: 0 },
        { text: "Se apoya en el sentimiento de libertad y la autonomía", group: 0 },
        { text: "Abstrae de la inteligencia y llega a una cosa en sí", group: 1 },
        { text: "Su objeto es, para Fichte, un mero invento", group: 1 },
        { text: "Convierte al hombre en una cosa entre las cosas", group: 1 },
      ],
      explain: "Fichte concluye que sólo estos dos sistemas son posibles, porque el fundamento de la experiencia cae fuera de ella y sólo se llega abstrayendo uno de sus dos elementos. Se puede ser dogmático o idealista, y no hay tercera opción.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "La diferencia entre los dos candidatos no es pareja. La cosa en sí es, para Fichte, un mero invento, un objeto producido por la representación de la inteligencia, porque jamás accedí mediante mis representaciones a una cosa en sí. El yo en sí, en cambio, sí puede mostrarse a la conciencia cuando abstraigo de todo lo demás y me concentro en mí mismo. Aparece además determinado en cuanto a su existencia —yo no me hice a mí mismo— pero determinable en cuanto a su naturaleza, porque pensar estos pensamientos y no otros depende de mi autodeterminación. Ésa es la ventaja del idealismo, aunque Fichte admite que no constituye una refutación del dogmatismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "Como ninguno de los dos puede refutar al otro, la elección del primer principio no es teórica. Es ética, y compromete a la persona entera. «La clase de filosofía que se elige depende de la clase de hombre que se es», escribe Fichte en el quinto parágrafo, en una de las frases más citadas de todo el idealismo alemán.",
    },
    {
      type: "info",
      continues: true,
      title: "Idealismo o dogmatismo: un dilema ético",
      body: "El dogmatismo rebaja al ser humano y niega su libertad: lo convierte en una cosa entre las cosas, lo hace depender de los objetos e impone el mecanicismo en todos los aspectos de su vida. El idealismo se caracteriza por el amor a la verdad, el sentimiento de libertad y la autonomía. La filosofía parte de un acto personal intransferible.",
    },
    {
      type: "quiz",
      question: "¿Por qué sostiene Fichte que elegir entre idealismo y dogmatismo es una decisión ética?",
      options: ["Porque ninguno de los dos puede refutar al otro", "Porque los dos parten de premisas morales explícitas", "Porque Kant ya había demostrado que el idealismo es falso", "Porque la ética precede a la teoría en todo sistema"],
      answer: 0,
      explain: "El idealismo tiene una ventaja, no una demostración: su principio puede mostrarse a la conciencia. Como el argumento no zanja la cuestión, decide la persona entera. La clase de filosofía que se elige depende de la clase de hombre que se es.",
    },
    {
      type: "info",
      title: "La distancia con Kant",
      body: "Fichte insiste en que no se está apartando: «mi sistema no es otro que el kantiano», escribe, y sostiene que ambos ven el asunto del mismo modo, es decir, que el objeto esté puesto y determinado por la facultad de conocimiento y no al revés. El fracaso de Kant, según él, no está en la doctrina sino en que ni uno solo de sus seguidores entendió de qué se hablaba.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Kant",
      body: "Pero la distancia se vuelve evidente en un punto preciso. El yo kantiano no determina ni las categorías ni las formas de la sensibilidad: simplemente las postula, y no explica su origen. Kant muestra la constitución del objeto, no cómo se origina. Fichte quiere un idealismo que muestre **genéticamente** cómo surge el objeto para la conciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Kant",
      body: "Ahí está el verdadero desacuerdo. Para Fichte, la legislación del actuar de la conciencia se deduce de la esencia misma de la inteligencia y no se toma de la experiencia, como según él hizo Kant. El fundamento de todo objeto es la libre legislación de un Yo absoluto, y de eso se sigue que la cosa en sí sobra: Fichte niega rotundamente su existencia, y sostiene que todo, incluso el mundo que percibimos como independiente de nosotros, es resultado de aquella acción originaria. Esa prioridad absoluta del Yo es lo que llevó a Hegel a caracterizar la posición fichteana como un **idealismo subjetivo**, con la reserva que el adjetivo implica.",
    },
    {
      type: "info",
      continues: true,
      title: "La distancia con Kant",
      body: "Al mismo tiempo se le ha llamado un **idealismo ético**, y con más justicia. Fichte otorga, como Kant, una clara prioridad a la razón práctica: el Yo es eminentemente activo y lo originario es la acción. En ese actuar determinado, la inteligencia siente los límites de su propio actuar, y no los de un mundo exterior que existiera con independencia de ella.",
    },
    {
      type: "quiz",
      question: "¿Cuál es el reproche concreto que Fichte le hace al yo de Kant?",
      options: ["Que lo reduce a una mera unidad lógica sin contenido", "Que postula las categorías sin explicar de dónde salen", "Que lo hace depender de la existencia de las cosas en sí", "Que no le atribuye ninguna función en la razón práctica"],
      answer: 1,
      explain: "Kant muestra la constitución del objeto, no cómo se origina. Fichte quiere un idealismo genético, que deduzca la legislación de la conciencia de la esencia misma de la inteligencia y no de su aplicación a la experiencia.",
    },
    {
      type: "info",
      title: "Jena, y lo que sigue",
      body: "La repercusión fue enorme y fue inmediata. Entre sus oyentes estaba Hölderlin, que en noviembre de 1794 le escribe a Neuffer: «Fichte es ahora el alma de Jena. No conozco a otro hombre de tamaña hondura y energía espiritual. Le escucho todos los días. Le hablo a veces».",
    },
    {
      type: "info",
      continues: true,
      title: "Jena, y lo que sigue",
      body: "Novalis y Friedrich Schlegel también presenciaron esas clases y adoptaron muchas ideas centrales de la doctrina. La influencia de Fichte sobre los círculos románticos, que empezaban a configurarse por entonces, fue decisiva: la primacía de la actividad libre sobre lo dado es la traducción filosófica de lo que el romanticismo estaba buscando en el arte.",
    },
    {
      type: "info",
      continues: true,
      title: "Jena, y lo que sigue",
      body: "Jena queda así convertida en la capital del movimiento. Es la universidad donde Fichte, Schelling y Hegel van a enseñar sucesivamente y desde donde se difunde el **idealismo alemán**, que se gesta hacia 1780 y cuyas ramificaciones llegan a mediados del siglo XIX. Nicolai Hartmann lo describió como un movimiento de una concentración especulativa sin par en la historia de la filosofía.",
    },
    {
      type: "match",
      question: "Uní cada nombre con lo que aportó a esta discusión",
      pairs: [
        { left: "Reinhold", right: "Exige convertir el criticismo en un verdadero sistema" },
        { left: "Maimon", right: "Denuncia el abismo entre sensibilidad y entendimiento" },
        { left: "Fichte", right: "Pone el Yo absoluto como principio primero del saber" },
        { left: "Hegel", right: "Bautiza la posición de Fichte como idealismo subjetivo" },
        { left: "Hölderlin", right: "Llama a Fichte el alma de Jena" },
      ],
      explain: "La Crítica dejó un hueco y cada uno responde a su manera: Reinhold pide sistema, Maimon señala la costura floja, Fichte propone el principio que la cierra, y la generación siguiente discute el resultado.",
    },
    {
      type: "info",
      continues: true,
      title: "Jena, y lo que sigue",
      body: "El rasgo que lo define es su densidad polémica: sistemas completamente influenciados unos por otros, que se superan mutuamente y discuten entre sí. El primero en discutirle a Fichte va a ser su seguidor más entusiasta, el joven Schelling.",
    },
  ],
};
