export default {
  num: 19,
  transcript: 19,
  title: "El romanticismo de Jena",
  source: "",
  feed: [
    {
      type: "info",
      title: "Qué fue el Romanticismo",
      body: "El **Romanticismo** es ante todo un fenómeno alemán, que se despliega aproximadamente entre 1770 y 1830 con centros en Königsberg, Weimar y Jena. No es una escuela filosófica con tesis compartidas sino un ánimo, una manera de sentir y de valorar que se expresa antes en la poesía y en la novela que en los tratados.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué fue el Romanticismo",
      body: "Que ese ánimo cristalice en los territorios de lengua alemana no es casual. A diferencia de Francia, unificada bajo una corona, una capital y una lengua administrativa, Alemania es un mosaico de más de trescientos estados, sin centro político ni cortesano. Lo único que sus habitantes comparten es la lengua, y eso vuelve a la lengua un asunto cargado. Hay además un desnivel humillante: la cultura francesa es el modelo de toda Europa culta, y Federico II de Prusia escribía en francés y despreciaba el alemán como lengua de establo. Buena parte de la energía romántica sale de ahí: de la necesidad de reivindicar lo propio contra un universalismo que hablaba con acento extranjero.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué fue el Romanticismo",
      body: "La primera oleada no se llama todavía romántica sino **Sturm und Drang** —tempestad e ímpetu—, activa desde 1770. Es un movimiento de jóvenes que reivindica el genio, la pasión y la fuerza expresiva contra el buen gusto y la corrección racional. El Werther de Goethe (1774) y Los bandidos de Schiller (1781) son sus obras emblemáticas.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué fue el Romanticismo",
      body: "Sus figuras de referencia son Hamann y Herder, que este curso ya encontró por el lado de la crítica a la Ilustración. Lo que en la clase de Hamann apareció como una objeción filosófica al purismo de la razón, acá vuelve convertido en programa: si la razón está hecha de lengua, historia y sensibilidad, entonces la poesía sabe más que la ciencia.",
    },
    {
      type: "quiz",
      question: "¿Por qué el Romanticismo cristaliza en los territorios alemanes y no en Francia?",
      options: ["Porque la censura francesa era mucho más severa", "Porque sin unidad política sólo tenían la lengua", "Porque la Ilustración no había llegado a Alemania", "Porque las universidades alemanas eran más libres"],
      answer: 1,
      explain: "Alemania es un mosaico de más de trescientos estados sin centro político ni cortesano, y encima con la cultura francesa como modelo dominante. De esa combinación sale la necesidad de reivindicar lo propio contra un universalismo que hablaba con acento extranjero.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "La Ilustración parte de la idea de un tiempo progresivo. La razón permite comprender el mundo cada vez mejor, ese conocimiento se acumula, y de la acumulación se sigue una mejora de las condiciones de vida y de las instituciones. El pasado es error y el futuro es corrección del error. De esa confianza se siguen varias creencias solidarias entre sí: que toda pregunta bien planteada tiene respuesta, que existe una verdad objetiva descubrible por cualquiera que razone bien, y que las verdades no pueden entrar en conflicto entre sí, porque un conjunto de proposiciones verdaderas forma necesariamente un todo coherente.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Ese optimismo resulta emocionalmente insuficiente para buena parte de una generación. No lo refutan: les resulta chato. La racionalidad y la convergencia armónica entre los intereses de todos describen un mundo sin tragedia, sin misterio y sin heroísmo, donde nada importante puede perderse porque nada importante está realmente en juego.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Y hay una sospecha más fuerte, que Rousseau ya había formulado: la posibilidad de que el progreso mismo sea la enfermedad. Que las ciencias y las artes no hayan mejorado las costumbres sino corrompido, que la civilización sea una pérdida disfrazada de ganancia, y que lo que llamamos avance sea distancia respecto de lo que fuimos.",
    },
    {
      type: "quiz",
      question: "¿Cuál es la objeción romántica de fondo al optimismo ilustrado?",
      options: ["Que su método era insuficientemente riguroso", "Que describe un mundo sin tragedia posible", "Que no supo apoyarse en las ciencias naturales", "Que confundía el progreso técnico con el moral"],
      answer: 1,
      explain: "No lo refutan: les resulta chato. Un mundo donde toda pregunta tiene respuesta y los intereses de todos convergen es un mundo donde nada importante está realmente en juego. Y detrás está la sospecha de Rousseau de que el progreso mismo sea la enfermedad.",
    },
    {
      type: "info",
      title: "La rebelión",
      body: "Si los géneros emblemáticos de la Ilustración son la teoría del contrato social y la Encyclopédie —el tratado y el diccionario, la exposición ordenada del saber—, los del Romanticismo son la **poesía**, el fragmento y la novela de formación. No es un cambio de estilo: es una tesis sobre qué forma tiene el conocimiento verdadero.",
    },
    {
      type: "info",
      continues: true,
      title: "La rebelión",
      body: "Frente a las palabras clave de la Ilustración —civilización, razón, progreso, método, claridad— el Romanticismo pone otras: **pasión, belleza, anhelo, creación, voluntad, genio**. Ninguna de ellas nombra algo que se pueda medir o compartir por demostración, y ahí está justamente el punto.",
    },
    {
      type: "info",
      continues: true,
      title: "La rebelión",
      body: "Hay también un giro estético hacia la naturaleza, y es un giro exacto. La metáfora de la Ilustración está en su propio nombre: la luz, el siglo de las luces, lo que se ve claro y distinto. Lo que el Romanticismo elige es lo contrario: el bosque, la niebla, la noche, la tormenta, la montaña, la ruina.",
    },
    {
      type: "info",
      continues: true,
      title: "La rebelión",
      body: "El emblema pictórico es El caminante sobre el mar de nubes (hacia 1818), de Caspar David Friedrich: una figura solitaria, vista de espaldas, frente a un paisaje que no domina y que se le ofrece como abismo. No estamos ante un objeto de conocimiento sino ante algo desproporcionado respecto de nosotros, y esa desproporción es el valor.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo pertenece a la Ilustración o al Romanticismo?",
      groups: ["Ilustración", "Romanticismo"],
      items: [
        { text: "El tratado y el diccionario como formas", group: 0 },
        { text: "Civilización, razón, método, claridad", group: 0 },
        { text: "La luz como metáfora central", group: 0 },
        { text: "El fragmento y la poesía como formas", group: 1 },
        { text: "Pasión, anhelo, creación, genio", group: 1 },
        { text: "El bosque, la niebla y la tormenta", group: 1 },
      ],
      explain: "No es un cambio de estilo sino una tesis sobre qué forma tiene el conocimiento verdadero. Frente a un mundo que se ve claro y distinto, el Romanticismo elige lo desproporcionado respecto de nosotros, y hace de esa desproporción el valor.",
    },
    {
      type: "info",
      title: "El Kant moral: deber, intención, dignidad",
      body: "Lo que el Romanticismo toma de Kant no es su epistemología sino su **filosofía moral**, construida en un registro casi opuesto. Este curso vio la Crítica de la razón pura, que limita el conocimiento a los fenómenos; falta la otra mitad, la Crítica de la razón práctica (1788), donde la libertad que allí quedaba fuera del saber se vuelve el eje de todo.",
    },
    {
      type: "info",
      continues: true,
      title: "El Kant moral: deber, intención, dignidad",
      body: "El argumento de Kant es que para que haya moral tiene que haber libertad. Si mis acciones fueran sólo eslabones de una cadena causal, alabarlas o condenarlas sería tan absurdo como alabar a una piedra por caer. La libertad no se puede demostrar teóricamente —es cosa en sí— pero la razón práctica la exige como condición de que la moral signifique algo. De ahí que lo que cuenta moralmente sea la **intención** y no la consecuencia. Una vez que uno actúa, la acción entra en redes causales que exceden por completo su control, y juzgar por resultados sería juzgar por la suerte. Lo único enteramente mío es el motivo por el que actué, y por eso nada es bueno sin restricción salvo una buena voluntad.",
    },
    {
      type: "info",
      continues: true,
      title: "El Kant moral: deber, intención, dignidad",
      body: "El criterio para evaluar ese motivo es el **imperativo categórico**: obrar sólo según aquella máxima que uno pueda querer que se vuelva ley universal. No manda contenidos concretos sino que somete la propia razón para actuar a una prueba de consistencia, y descarta hacer de uno mismo la excepción.",
    },
    {
      type: "quiz",
      question: "¿Por qué para Kant lo que cuenta moralmente es la intención y no la consecuencia?",
      options: ["Porque las consecuencias son difíciles de prever", "Porque la acción, una vez hecha, escapa a mi control", "Porque la moral se ocupa del carácter y no de los actos", "Porque el resultado depende del acuerdo de los demás"],
      answer: 1,
      explain: "Juzgar por resultados sería juzgar por la suerte, porque la acción entra en redes causales que exceden al agente. Lo único enteramente mío es el motivo, y por eso nada es bueno sin restricción salvo una buena voluntad.",
    },
    {
      type: "info",
      continues: true,
      title: "El Kant moral: deber, intención, dignidad",
      body: "Y de ahí sale su idea de **dignidad**. No sólo la razón, sino el libre albedrío, hace del ser humano un **fin en sí mismo** y nunca un simple medio. Todo lo que puede reemplazarse por otra cosa de valor equivalente tiene un precio; aquello que está por encima de todo precio y no admite equivalente tiene dignidad. La persona no se cotiza.",
    },
    {
      type: "quiz",
      question: "Según Kant, ¿qué diferencia tener precio de tener dignidad?",
      options: ["Que lo que tiene precio admite un equivalente", "Que lo que tiene dignidad no puede ser medido", "Que el precio lo fija el mercado y la dignidad la ley", "Que la dignidad se pierde y el precio permanece"],
      answer: 0,
      explain: "Todo lo que puede reemplazarse por otra cosa de valor equivalente tiene un precio; lo que está por encima de todo precio y no admite equivalente tiene dignidad. El libre albedrío hace del ser humano un fin en sí mismo y nunca un simple medio.",
    },
    {
      type: "info",
      title: "La primacía de la voluntad",
      body: "El legado kantiano para el Romanticismo se resume en la **primacía de la voluntad**. Si hay libre albedrío y si lo que vale moralmente es la intención, entonces lo decisivo de una vida no es lo que consigue sino lo que elige. El centro de gravedad de la persona se traslada del entendimiento a la voluntad.",
    },
    {
      type: "info",
      continues: true,
      title: "La primacía de la voluntad",
      body: "Los románticos toman entonces el cogito, ergo sum cartesiano y lo dan vuelta: **volo, ergo sum**, quiero luego existo. No soy en tanto pienso sino en tanto elijo, y no me constituyo contemplando el mundo sino actuando sobre él. Es la fórmula más económica de toda la mutación.",
    },
    {
      type: "info",
      continues: true,
      title: "La primacía de la voluntad",
      body: "Fichte le había dado a eso una arquitectura filosófica, como vimos: un Yo cuyo ser es su actuar, que no encuentra el mundo dado sino que en algún sentido lo produce, precisamente para tener frente a qué ejercer su libertad. Los románticos de Jena lo escucharon en clase y se llevaron esa idea sin la disciplina del sistema.",
    },
    {
      type: "short",
      question: "¿Con qué fórmula invierten los románticos el cogito, ergo sum de Descartes?",
      answers: ["volo ergo sum", "volo, ergo sum", "volo"],
      explain: "Quiero, luego existo. No soy en tanto pienso sino en tanto elijo, y no me constituyo contemplando el mundo sino actuando sobre él. Es la fórmula más económica de todo el desplazamiento del entendimiento a la voluntad.",
    },
    {
      type: "info",
      title: "Rousseau, el otro padre",
      body: "**Rousseau** es la principal figura de transición entre los dos ánimos, y según cuál Rousseau se lea es un pensador ilustrado o uno romántico. El del Contrato social pertenece a la Ilustración; el de las Confesiones y las Ensoñaciones inaugura otra cosa.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau, el otro padre",
      body: "Las Confesiones, publicadas después de su muerte, abren con la pretensión de mostrarse ante el lector tal cual es, sin adorno ni omisión, y de sostener que nadie es igual a él. Esa doble apuesta —la sinceridad radical como valor supremo y la singularidad como hecho— es el nacimiento de la **autenticidad** como criterio.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau, el otro padre",
      body: "Su idealización del estado de naturaleza funciona además como el **modelo de la nostalgia** en general: el anhelo por algo del pasado que en rigor nunca existió, y cuya pérdida se siente igual. Y su tesis de que el hombre de sociedad ya no se atreve a mostrarse como es, porque vive compitiendo por lucirse, le da al Romanticismo su diagnóstico de época.",
    },
    {
      type: "quiz",
      question: "¿Qué aporta el Rousseau de las Confesiones que no está en el del Contrato social?",
      options: ["La sinceridad y la singularidad como valores", "La fundación de la soberanía en el pueblo", "La crítica de la propiedad como origen del mal", "La educación como formación del ciudadano"],
      answer: 0,
      explain: "Abre con la pretensión de mostrarse tal cual es, sin adorno, y de sostener que nadie es igual a él. Esa doble apuesta es el nacimiento de la autenticidad como criterio, y su estado de naturaleza es el modelo de la nostalgia: el anhelo por algo que nunca existió.",
    },
    {
      type: "info",
      title: "Herder: lengua, pueblo y nación",
      body: "Así como del ánimo ilustrado sale el liberalismo, del Romanticismo sale el **nacionalismo**, y su fuente principal es **Johann Gottfried Herder** (1744–1803), discípulo de Hamann y de Kant. Su punto de partida es la tesis del maestro sobre el lenguaje, llevada de la teoría del conocimiento a la historia.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "Para Herder, lo que distingue a un pueblo es su lengua propia. Las palabras que una persona comparte con las demás no son un envase intercambiable de un contenido común: son un vínculo irreductible, que lleva una manera de dividir el mundo, una memoria y una sensibilidad que no se traducen sin pérdida.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "De ahí se sigue el rechazo de la escala única. No hay una civilización y varios grados de aproximación a ella, sino culturas, cada una con su centro de gravedad propio, que hay que juzgar por sus criterios y no por los nuestros. La pregunta ilustrada por el progreso de la humanidad se disuelve en una pluralidad de historias.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "Para acceder a ese centro de gravedad ajeno hace falta un método distinto del de las ciencias duras. No medir ni clasificar desde afuera, sino un ejercicio de identificación imaginativa —Einfühlung, sentir dentro— que reconstruya cómo era ser alguien de esa época y ese lugar. Es el origen de la hermenéutica y de la historia cultural.",
    },
    {
      type: "quiz",
      question: "¿Qué se sigue de la tesis de Herder sobre la lengua?",
      options: ["Que hay culturas y no grados de civilización", "Que la traducción exacta es siempre posible", "Que el progreso histórico puede al fin medirse", "Que la razón es idéntica en todos los pueblos"],
      answer: 0,
      explain: "Si la lengua lleva una manera de dividir el mundo que no se traduce sin pérdida, entonces no hay una civilización con grados de aproximación, sino culturas con su propio centro de gravedad, que hay que juzgar por sus criterios y no por los nuestros.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "La consecuencia política es enorme y Herder no la buscó. Si cada pueblo tiene un alma propia expresada en su lengua, entonces los pueblos con lengua e historia comunes deberían gobernarse a sí mismos. Herder era cosmopolita y antiimperialista, y de su idea salió el argumento que iba a rehacer el mapa de Europa.",
    },
    {
      type: "short",
      question: "¿Cómo llama Herder al ejercicio de identificación imaginativa con otra época o cultura?",
      answers: ["Einfühlung", "empatía"],
      explain: "Sentir dentro: reconstruir cómo era ser alguien de ese lugar y ese tiempo, en vez de medir y clasificar desde afuera. Es el origen de la hermenéutica y de la historia cultural, y la consecuencia política —que cada pueblo se gobierne— Herder no la buscó.",
    },
    {
      type: "info",
      title: "Schiller y la educación estética",
      body: "**Friedrich Schiller** (1759–1805) —dramaturgo del Sturm und Drang antes de volverse el gran teórico estético del movimiento— intenta en las Cartas sobre la educación estética del hombre (1795) reconciliar los dos ánimos en vez de elegir uno. El problema que lo mueve es el Terror: la razón sola había desembocado en sangre.",
    },
    {
      type: "info",
      continues: true,
      title: "Schiller y la educación estética",
      body: "Su diagnóstico es que el hombre moderno está partido en dos. Un **impulso sensible** lo ata a la materia, al cambio y a la necesidad; un **impulso formal** lo lleva hacia la ley, lo universal y lo permanente. La Ilustración cultivó el segundo a costa del primero, y produjo hombres que razonan bien y sienten mal.",
    },
    {
      type: "info",
      continues: true,
      title: "Schiller y la educación estética",
      body: "Entre ambos, Schiller ubica el **impulso lúdico** (Spieltrieb): el juego y el arte como el único territorio donde sensibilidad y razón se concilian sin que ninguna se imponga. De ahí la frase que resume el libro: el hombre sólo es plenamente hombre cuando juega, y sólo juega cuando es hombre en el pleno sentido.",
    },
    {
      type: "info",
      continues: true,
      title: "Schiller y la educación estética",
      body: "Para Schiller esa reconciliación no es un problema de estética individual sino un programa político. Sostiene que ninguna reforma institucional puede sostenerse sobre hombres mutilados, y que por eso el camino hacia la libertad política pasa por la belleza. Es la respuesta romántica más lúcida al fracaso de la Revolución.",
    },
    {
      type: "quiz",
      question: "¿Qué función cumple el impulso lúdico en Schiller?",
      options: ["Aliviar la disciplina que exige la vida moral", "Conciliar sensibilidad y razón sin jerarquía", "Sustituir la política por la educación del gusto", "Devolver al arte su antigua función religiosa"],
      answer: 1,
      explain: "El hombre moderno está partido entre un impulso sensible y uno formal, y la Ilustración cultivó el segundo a costa del primero. El juego es el único territorio donde se concilian, y por eso el camino hacia la libertad política pasa por la belleza.",
    },
    {
      type: "info",
      title: "Jena: los Schlegel y Novalis",
      body: "**August Wilhelm Schlegel** (1767–1845) y su hermano **Friedrich** (1772–1829) organizan en Jena, hacia 1798, el círculo que le da al movimiento su forma consciente. Con Novalis, Tieck, Schleiermacher y Caroline Schlegel publican la revista Athenäum, donde el Romanticismo se vuelve por primera vez un programa escrito.",
    },
    {
      type: "info",
      continues: true,
      title: "Jena: los Schlegel y Novalis",
      body: "Su forma característica es el **fragmento**: textos breves, aforísticos, deliberadamente incompletos. No es pereza ni pose. Si lo verdadero es infinito y está en devenir, un sistema cerrado sería una falsificación, y sólo el fragmento puede señalar hacia el todo sin pretender contenerlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Jena: los Schlegel y Novalis",
      body: "De esa autoconciencia permanente sale la **ironía romántica**: la obra que se sabe a la vez seria y una construcción arbitraria del artista, y que se interrumpe para mostrarse como hecha. El autor se compromete con lo que escribe y simultáneamente se eleva por encima, porque ninguna forma acabada puede estar a la altura de lo que busca.",
    },
    {
      type: "info",
      continues: true,
      title: "Jena: los Schlegel y Novalis",
      body: "Del círculo participa también **Novalis**, seudónimo de Friedrich von Hardenberg (1772–1801), cuya obra queda inconclusa por su muerte a los veintiocho. Suya es la imagen que se volvió el emblema del movimiento: la **flor azul** de Heinrich von Ofterdingen, el objeto de un anhelo que nunca se alcanza y que vale por el anhelo mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Jena: los Schlegel y Novalis",
      body: "Suyo es también el programa de \"romantizar el mundo\": dar a lo cotidiano un sentido elevado, a lo conocido la dignidad de lo desconocido, a lo finito una apariencia de infinito. No se trata de huir de la realidad hacia un más allá, sino de volver a cargar de misterio una realidad que la Ilustración había dejado sin espesor.",
    },
    {
      type: "quiz",
      question: "¿Por qué el círculo de Jena elige el fragmento como forma?",
      options: ["Porque escribían en revistas de poco espacio", "Porque un sistema cerrado falsea lo infinito", "Porque imitaban los aforismos de la Antigüedad", "Porque ninguno llegó a terminar una obra larga"],
      answer: 1,
      explain: "Si lo verdadero es infinito y está en devenir, sólo el fragmento puede señalar hacia el todo sin pretender contenerlo. De esa misma autoconciencia sale la ironía romántica: la obra que se interrumpe para mostrarse como construcción.",
    },
    {
      type: "info",
      title: "Rasgos y consecuencias",
      body: "De la primacía de la voluntad y de la autenticidad se sigue el enorme valor de la **sinceridad**. El motivo importa más que la consecuencia, y no traicionarse pasa a ser una obligación más fuerte que tener razón. Un adversario íntegro vale más que un aliado tibio, y el mártir de una causa falsa merece respeto.",
    },
    {
      type: "info",
      continues: true,
      title: "Rasgos y consecuencias",
      body: "Ese fetichismo del motivo tiene un reverso incómodo que la época no siempre advirtió. Si lo único que cuenta es la pureza de la intención, entonces no queda criterio para juzgar lo que la intención pura produce, y la convicción absoluta se vuelve por sí misma un título. Es un legado que el siglo XX iba a cobrar caro.",
    },
    {
      type: "info",
      continues: true,
      title: "Rasgos y consecuencias",
      body: "Conviene además una aclaración de vocabulario, porque la palabra circula en dos sentidos incompatibles. El **idealismo romántico** es el imperativo de actuar y crear según los propios ideales, y es una actitud moral. El idealismo filosófico de Fichte, Schelling o Hegel es una tesis sobre la relación entre pensamiento y ser. No son lo mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Rasgos y consecuencias",
      body: "Por último, la emoción, para ser auténtica, tiende a ser **violenta**. Hay anhelos que no se dejan justificar racionalmente y cada alma es irreductible a las demás, de modo que el conflicto no es un accidente a corregir sino la textura misma de la vida. Contra la armonía ilustrada, el Romanticismo asume que las cosas valiosas chocan entre sí.",
    },
    {
      type: "quiz",
      question: "¿Cuál es el reverso incómodo del culto romántico a la sinceridad?",
      options: ["Que vuelve imposible cualquier vida en común", "Que deja sin criterio para juzgar sus efectos", "Que obliga a renunciar a toda ambición política", "Que confunde la emoción con el conocimiento"],
      answer: 1,
      explain: "Si lo único que cuenta es la pureza de la intención, la convicción absoluta se vuelve por sí misma un título y no queda con qué evaluar sus efectos. Es un legado que el siglo XX iba a cobrar caro.",
    },
    {
      type: "info",
      title: "El Terror y el legado",
      body: "Una manera de leer la Revolución Francesa es que el **Terror es el momento en que la Ilustración se vuelve Romanticismo**. Lo que empieza como un proyecto de instituciones racionales termina en un tribunal que juzga intenciones, y el Comité de Salvación Pública gobierna invocando la voluntad general de Rousseau. Y la voluntad general no es la suma verificable de los votos: es lo que el pueblo querría si quisiera bien. Una vez admitido eso, quien dice conocerla puede prescindir de contarlos. La virtud se vuelve una cualidad interior que alguien certifica, y el desacuerdo deja de ser un error para volverse una falla del alma.",
    },
    {
      type: "info",
      continues: true,
      title: "El Terror y el legado",
      body: "El Romanticismo funciona entonces como el **alter ego de la Ilustración**: no su negación externa sino su sombra, producida por ella y alojada dentro. Deja como legado una subjetividad radical vivida como tormento permanente, y una desconfianza duradera hacia toda armonía prometida.",
    },
    {
      type: "info",
      continues: true,
      title: "El Terror y el legado",
      body: "Ninguno de sus herederos toma ese legado intacto. Cada uno retiene alguna pieza —la primacía de la voluntad, el valor de la autenticidad, la sospecha sobre el progreso, la idea de que el conflicto es constitutivo— y descarta las demás. Marx, Nietzsche, Freud, el existencialismo y el nacionalismo salen todos, de maneras incompatibles, de acá.",
    },
    {
      type: "match",
      question: "Uní cada figura con su aporte al Romanticismo",
      pairs: [
        { left: "Herder", right: "La lengua como alma de un pueblo" },
        { left: "Schiller", right: "El juego como reconciliación de razón y sentido" },
        { left: "Novalis", right: "La flor azul y el anhelo que no se alcanza" },
        { left: "Friedrich Schlegel", right: "El fragmento y la ironía romántica" },
        { left: "Rousseau", right: "La autenticidad y el modelo de la nostalgia" },
      ],
      explain: "El Romanticismo no es una escuela con tesis compartidas sino un ánimo que cada uno declina a su manera. Lo que los une es poner la voluntad, lo particular y lo histórico donde la Ilustración ponía la razón, lo universal y el método.",
    },
    {
      type: "info",
      continues: true,
      title: "El Terror y el legado",
      body: "Queda un intento de reconciliar las dos corrientes en vez de elegir, y es el más ambicioso de todos. Tomar de la Ilustración la exigencia de sistema y de razón, y del Romanticismo la historia, el conflicto y el devenir, para mostrar que no son adversarios sino momentos de un mismo movimiento. Ese intento se llama Hegel.",
    },
  ],
};
