export default {
  num: 18,
  transcript: 18,
  title: "Schelling: la naturaleza y el arte",
  source: "",
  feed: [
    {
      type: "info",
      title: "El discípulo que se adelanta",
      body: "**Friedrich Wilhelm Joseph von Schelling** (1775–1854) fue el más precoz de los tres grandes idealistas y el que más veces cambió de posición. Hijo de un pastor y orientalista, entró al seminario protestante de Tubinga —el Tübinger Stift— a los quince años, cuando la edad mínima era veinte, porque ya sabía griego, hebreo y árabe.",
    },
    {
      type: "info",
      continues: true,
      title: "El discípulo que se adelanta",
      body: "En Tubinga compartió habitación con otros dos becarios: **Hegel**, cinco años mayor, y **Hölderlin**. Los tres leían a Kant a escondidas, celebraban la Revolución Francesa y, según la leyenda, plantaron juntos un árbol de la libertad. De esa convivencia salió un texto breve y anónimo de 1796 que se conoce como el Programa sistemático más antiguo del idealismo alemán.",
    },
    {
      type: "info",
      continues: true,
      title: "El discípulo que se adelanta",
      body: "Ese fragmento —que se atribuye a uno de los tres sin acuerdo sobre cuál— ya contiene el programa entero de lo que viene. Reclama una filosofía que culmine en una idea estética, sostiene que el acto supremo de la razón es un acto estético y que la belleza reúne lo que el entendimiento separa, y pide una nueva mitología que vuelva sensible la filosofía para el pueblo.",
    },
    {
      type: "info",
      continues: true,
      title: "El discípulo que se adelanta",
      body: "Schelling publicó su primer trabajo sobre Fichte a los diecinueve años y llegó a la cátedra de Jena en 1798, con veintitrés, recomendado por Goethe. Fichte, que enseñaba ahí, lo consideraba su discípulo más brillante. En pocos años el discípulo iba a construir un sistema propio en contra del maestro.",
    },
    {
      type: "info",
      continues: true,
      title: "El discípulo que se adelanta",
      body: "Su vida personal quedó enredada con el círculo romántico de Jena. Se enamoró de **Caroline Schlegel**, la mujer de August Wilhelm Schlegel, la figura intelectual más aguda del grupo y catorce años mayor que él. Se casaron en 1803, después de un divorcio que Goethe ayudó a gestionar y que escandalizó a media Alemania.",
    },
    {
      type: "quiz",
      question: "¿Qué reclama el Programa sistemático más antiguo del idealismo alemán?",
      options: ["Una filosofía que culmine en una idea estética", "Una vuelta al método geométrico de Spinoza", "Una crítica del lenguaje anterior a toda razón", "Una fundación de la moral en el sentimiento"],
      answer: 0,
      explain: "El fragmento anónimo de 1796, escrito por Schelling, Hegel o Hölderlin, sostiene que el acto supremo de la razón es un acto estético y pide una nueva mitología que vuelva sensible la filosofía. Contiene el programa entero de lo que viene.",
    },
    {
      type: "info",
      title: "El problema de la naturaleza",
      body: "El punto de partida de Schelling es una insatisfacción con Fichte, y es una insatisfacción precisa. Si todo lo que hay procede de la acción originaria del Yo absoluto, ¿qué estatuto le queda a la naturaleza? En el sistema de Fichte la respuesta es incómoda: la naturaleza es un no-yo puesto por el Yo para tener frente a qué ejercer su libertad.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema de la naturaleza",
      body: "Es decir, la naturaleza no tiene realidad propia ni interés propio. Es material de la acción moral, resistencia necesaria para que haya deber, escenario de una obra cuyo único protagonista es el sujeto. Para una generación que estaba redescubriendo la naturaleza con asombro, eso resultaba filosóficamente pobre y estéticamente insoportable.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema de la naturaleza",
      body: "Schelling lo formula como un problema de simetría. Fichte explicó cómo el sujeto llega a poner un objeto, pero no cómo un mundo objetivo llega a producir algo como un sujeto. Una filosofía completa tiene que poder recorrer el camino en las dos direcciones, y el idealismo subjetivo sólo sabe hacer una.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema de la naturaleza",
      body: "Hay además un motivo de época. Schelling escribe en los años en que la electricidad, el magnetismo, el galvanismo y la química nueva están mostrando una naturaleza dinámica, atravesada por fuerzas y polaridades, que ya no se parece al mecanismo de relojería de Descartes y Newton. Esa naturaleza pide otra filosofía.",
    },
    {
      type: "quiz",
      question: "¿Qué le objeta Schelling al sistema de Fichte?",
      options: ["Que deja a la naturaleza sin realidad propia", "Que conserva la cosa en sí como un residuo", "Que no logra fundar la autonomía de la moral", "Que reduce la libertad a una ilusión necesaria"],
      answer: 0,
      explain: "Para Fichte la naturaleza es un no-yo puesto por el Yo para tener frente a qué ejercer su libertad: material de la acción moral, no algo con interés propio. Fichte explicó cómo el sujeto pone un objeto, pero no cómo un mundo objetivo produce un sujeto.",
    },
    {
      type: "info",
      title: "La Naturphilosophie",
      body: "Entre 1797 y 1799 Schelling publica las Ideas para una filosofía de la naturaleza, Del alma del mundo y el Primer esbozo de un sistema de la filosofía de la naturaleza. Ahí funda lo que se llamará **Naturphilosophie**, y que es la primera gran ruptura con Fichte aunque todavía no se presente como tal.",
    },
    {
      type: "info",
      continues: true,
      title: "La Naturphilosophie",
      body: "Su tesis puede resumirse en una fórmula que él mismo escribió: la naturaleza debe ser el espíritu visible, y el espíritu la naturaleza invisible. No son dos sustancias ni dos mundos, sino lo mismo en dos grados de desarrollo. La naturaleza no se opone al espíritu: es espíritu todavía dormido, inconsciente de sí.",
    },
    {
      type: "info",
      continues: true,
      title: "La Naturphilosophie",
      body: "De ahí se sigue la distinción que organiza toda la doctrina. Hay que separar la naturaleza como **productividad** —el proceso vivo, la actividad que produce— de la naturaleza como **producto**, las cosas fijas que encontramos. Lo segundo es lo que la ciencia estudia; lo primero es lo que la filosofía tiene que pensar.",
    },
    {
      type: "info",
      continues: true,
      title: "La Naturphilosophie",
      body: "Esa productividad no avanza en línea recta sino por **polaridad**: toda actividad genera su opuesto y se sostiene en la tensión entre los dos. El imán, con sus dos polos inseparables, es el modelo. Schelling lo generaliza a la electricidad, al magnetismo, a los procesos químicos y a la vida orgánica.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue Schelling dentro de la naturaleza misma?",
      options: ["La materia inerte de la materia viva", "Lo que produce de lo que está producido", "El orden mecánico del orden teleológico", "Lo que se percibe de lo que se piensa"],
      answer: 1,
      explain: "La naturaleza como productividad es el proceso vivo; como producto, las cosas fijas que encontramos. Lo segundo es lo que estudia la ciencia, lo primero es lo que la filosofía tiene que pensar. Y esa productividad avanza por polaridad, con el imán como modelo.",
    },
    {
      type: "info",
      continues: true,
      title: "La Naturphilosophie",
      body: "Y avanza por grados, que Schelling llama **potencias**. La materia, la luz, el organismo y finalmente la conciencia son escalones de un mismo proceso que se va replegando sobre sí. En el punto más alto, la naturaleza produce un ser en el que ella misma se vuelve consciente: en el hombre, la naturaleza abre los ojos y se mira.",
    },
    {
      type: "info",
      continues: true,
      title: "La Naturphilosophie",
      body: "La Naturphilosophie tuvo una fortuna doble. Inspiró a poetas, médicos y científicos románticos, y está detrás del descubrimiento del electromagnetismo por Oersted, que era discípulo suyo. Pero también acumuló especulaciones sin control empírico que la ciencia posterior descartó, y el descrédito que arrastró es en buena parte merecido.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la filosofía de la naturaleza que Schelling funda entre 1797 y 1799?",
      answers: ["Naturphilosophie"],
      explain: "Su fórmula: la naturaleza debe ser el espíritu visible, y el espíritu la naturaleza invisible. No son dos mundos sino lo mismo en dos grados, y en el hombre la naturaleza se vuelve consciente de sí.",
    },
    {
      type: "info",
      title: "El Sistema del idealismo trascendental",
      body: "En 1800, con veinticinco años, Schelling publica su obra más armada: el **Sistema del idealismo trascendental**. Es el libro donde ordena la relación entre las dos mitades de su filosofía y donde da el paso que lo va a separar definitivamente de Fichte.",
    },
    {
      type: "info",
      continues: true,
      title: "El Sistema del idealismo trascendental",
      body: "El planteo es de una simetría deliberada. Hay dos ciencias fundamentales y son complementarias. La filosofía de la naturaleza parte de lo objetivo y muestra cómo la naturaleza asciende hasta producir la inteligencia. La filosofía trascendental parte de lo subjetivo y muestra cómo el yo llega a ponerse un mundo objetivo.",
    },
    {
      type: "info",
      continues: true,
      title: "El Sistema del idealismo trascendental",
      body: "Ninguna de las dos es primera. Son dos recorridos del mismo arco en direcciones opuestas, y cada una encuentra en su punto de llegada el punto de partida de la otra. Esa reciprocidad es la respuesta de Schelling al idealismo subjetivo: el Yo ya no funda solo, sino que es uno de los dos extremos de un mismo proceso.",
    },
    {
      type: "info",
      continues: true,
      title: "El Sistema del idealismo trascendental",
      body: "La parte trascendental del libro reconstruye una historia de la conciencia por épocas, desde la sensación hasta la voluntad libre, y de ahí a la historia y al derecho. Hegel va a retomar ese formato siete años después en la Fenomenología del Espíritu, con un rigor mayor y sin reconocer demasiado la deuda.",
    },
    {
      type: "info",
      continues: true,
      title: "El Sistema del idealismo trascendental",
      body: "Pero lo decisivo está en la última sección, y es lo que nadie esperaba de un tratado de filosofía trascendental. Schelling sostiene que el sistema no se corona en el conocimiento ni en la moral, sino en el **arte**, y que la obra de arte es el único lugar donde el problema entero se resuelve efectivamente.",
    },
    {
      type: "classify",
      question: "En el Sistema de 1800, ¿cada rasgo es de la filosofía de la naturaleza o de la trascendental?",
      groups: ["Filosofía de la naturaleza", "Filosofía trascendental"],
      items: [
        { text: "Parte de lo objetivo", group: 0 },
        { text: "Muestra cómo la naturaleza produce la inteligencia", group: 0 },
        { text: "Su punto de llegada es el sujeto", group: 0 },
        { text: "Parte de lo subjetivo", group: 1 },
        { text: "Muestra cómo el yo se pone un mundo", group: 1 },
        { text: "Reconstruye la historia de la conciencia por épocas", group: 1 },
      ],
      explain: "Ninguna de las dos es primera: son el mismo arco recorrido en direcciones opuestas, y cada una encuentra en su llegada el punto de partida de la otra. Ésa es la respuesta de Schelling al idealismo subjetivo de Fichte.",
    },
    {
      type: "info",
      title: "El arte como órgano de la filosofía",
      body: "El argumento es el siguiente. Todo el sistema gira en torno a una contradicción: somos libres y a la vez la naturaleza es necesaria, actuamos con conciencia y a la vez algo actúa en nosotros sin que lo controlemos. La filosofía puede postular que en el fondo son lo mismo, pero no puede mostrarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "El arte como órgano de la filosofía",
      body: "En la obra de arte, en cambio, eso se vuelve visible. El artista trabaja con plena conciencia —elige, corrige, calcula— y sin embargo el resultado tiene una necesidad que él no puso y que muchas veces no puede explicar. La obra le sale mejor de lo que sabía hacer, y contiene más sentido del que le puso.",
    },
    {
      type: "info",
      continues: true,
      title: "El arte como órgano de la filosofía",
      body: "Eso es para Schelling la marca del **genio**: no la originalidad ni la fuerza, sino la coincidencia efectiva de lo consciente y lo inconsciente en un mismo producto. En la obra terminada, libertad y necesidad quedan reunidas en un objeto sensible que cualquiera puede mirar. Es la identidad, hecha cosa.",
    },
    {
      type: "info",
      continues: true,
      title: "El arte como órgano de la filosofía",
      body: "De ahí la conclusión que hizo famoso al libro: el arte es el **órgano** de la filosofía, y también su documento eterno. La filosofía puede pensar el absoluto pero no exhibirlo; el arte lo exhibe sin pensarlo. Por eso el arte no ilustra a la filosofía: la completa, y ocupa el lugar más alto del sistema.",
    },
    {
      type: "quiz",
      question: "¿Por qué el arte corona el sistema y no el conocimiento ni la moral?",
      options: ["Porque llega a más gente que la filosofía", "Porque reúne en un objeto libertad y necesidad", "Porque no depende de las formas de la sensibilidad", "Porque expresa lo particular y no lo universal"],
      answer: 1,
      explain: "La filosofía puede postular que consciente e inconsciente son lo mismo, pero no puede mostrarlo. El artista trabaja con plena conciencia y el resultado tiene una necesidad que él no puso: la identidad queda hecha cosa, visible para cualquiera.",
    },
    {
      type: "info",
      continues: true,
      title: "El arte como órgano de la filosofía",
      body: "Se entiende que este libro haya sido recibido como la filosofía oficial del Romanticismo. Los románticos de Jena venían sosteniendo desde la literatura que la poesía era la forma suprema del conocimiento; Schelling se los demostró desde la filosofía trascendental, con el aparato de Kant y Fichte.",
    },
    {
      type: "info",
      continues: true,
      title: "El arte como órgano de la filosofía",
      body: "Conviene medir la distancia con Kant, porque es enorme. Para Kant, en la Crítica del juicio, lo bello es un puente y un indicio: nos hace sentir una armonía entre naturaleza y libertad que no podemos conocer. Para Schelling ya no es un indicio de nada. Es la presentación efectiva de lo absoluto.",
    },
    {
      type: "quiz",
      question: "¿En qué se aparta Schelling de la Crítica del juicio de Kant?",
      options: ["En negar que exista un juicio de gusto universal", "En sostener que lo bello presenta el absoluto y no lo indica", "En hacer del genio una regla y no una excepción", "En separar lo bello de lo sublime como dos facultades"],
      answer: 1,
      explain: "Para Kant lo bello es un puente y un indicio: nos hace sentir una armonía entre naturaleza y libertad que no podemos conocer. Para Schelling ya no indica nada, porque lo presenta efectivamente. Por eso el arte es el órgano de la filosofía y no su ilustración.",
    },
    {
      type: "info",
      title: "La filosofía de la identidad y las rupturas",
      body: "A partir de 1801, con la Exposición de mi sistema de la filosofía, Schelling da un paso más y formula lo que se conoce como **filosofía de la identidad**. Si sujeto y objeto son dos direcciones de lo mismo, entonces hay que poder pensar ese mismo directamente, antes de que se separe en los dos.",
    },
    {
      type: "info",
      continues: true,
      title: "La filosofía de la identidad y las rupturas",
      body: "Lo llama el Absoluto, o la indiferencia de lo subjetivo y lo objetivo. No es ni espíritu ni naturaleza sino aquello de lo que ambos son grados, y en él ninguna de las dos determinaciones predomina. Todo lo que existe difiere sólo por la proporción entre los dos polos, nunca por su esencia.",
    },
    {
      type: "info",
      continues: true,
      title: "La filosofía de la identidad y las rupturas",
      body: "La correspondencia con Fichte, que venía tensa desde 1800, se corta en 1802: cada uno entendió que el otro había abandonado el problema. Fichte le reprocha haber convertido la filosofía en dogmatismo, en una doctrina sobre el ser en vez de una doctrina del saber. Schelling le reprocha no haber salido nunca de la conciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "La filosofía de la identidad y las rupturas",
      body: "La ruptura con Hegel llega después y es más dura, porque venían de Tubinga y habían dirigido juntos una revista. En el prólogo de la Fenomenología del Espíritu (1807), Hegel ridiculiza sin nombrarlo un absoluto en el que todas las diferencias se borran de un saque: la noche, escribe, en que todas las vacas son negras.",
    },
    {
      type: "info",
      continues: true,
      title: "La filosofía de la identidad y las rupturas",
      body: "La objeción es seria y no sólo una humorada. Si el Absoluto es indiferencia pura, no se entiende por qué habría de diferenciarse en algo, ni cómo se llega a él salvo por una intuición que se tiene o no se tiene. Schelling nunca le perdonó el pasaje y no volvieron a hablarse. Tenían treinta y siete años.",
    },
    {
      type: "quiz",
      question: "¿Qué le critica Hegel a la filosofía de la identidad?",
      options: ["Que su absoluto borra toda diferencia de un saque", "Que le concede demasiada autonomía a la naturaleza", "Que abandona el método trascendental por el histórico", "Que reintroduce a Dios como garante del conocimiento"],
      answer: 0,
      explain: "En el prólogo de la Fenomenología (1807) lo ridiculiza sin nombrarlo: la noche en que todas las vacas son negras. Si el absoluto es indiferencia pura, no se entiende por qué habría de diferenciarse, ni cómo se llega a él salvo por una intuición que se tiene o no.",
    },
    {
      type: "info",
      title: "La libertad y el fondo oscuro",
      body: "En 1809 Schelling publica las Investigaciones filosóficas sobre la esencia de la libertad humana, su último gran libro y el más leído hoy. El problema que ataca es el que ningún sistema idealista había resuelto: si todo procede del absoluto y todo es racional, ¿de dónde sale el mal?",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad y el fondo oscuro",
      body: "La respuesta habitual del idealismo —que el mal es carencia, negación, defecto de realidad— le resulta inaceptable. El mal no se vive como un menos. Se vive como una fuerza positiva, elegida y activa, y una filosofía que no puede dar cuenta de eso está describiendo otro mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad y el fondo oscuro",
      body: "Su propuesta es introducir una distinción dentro de Dios mismo: hay en Dios un **fondo** oscuro, un Grund que no es todavía razón ni orden, una voluntad ciega anterior a toda claridad, sobre la cual Dios mismo se constituye. La existencia se levanta siempre sobre algo que no es transparente para sí.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad y el fondo oscuro",
      body: "La libertad humana consiste entonces en poder invertir la relación entre esos dos principios: poner lo particular por encima de lo universal, el fondo por encima de la luz. Por eso el mal es real y es libre, y por eso sólo el hombre puede cometerlo. No es un defecto de ser sino una posibilidad del ser.",
    },
    {
      type: "quiz",
      question: "¿Por qué rechaza Schelling la idea de que el mal sea una carencia?",
      options: ["Porque contradice la bondad divina", "Porque el mal se vive como una fuerza elegida y activa", "Porque haría imposible cualquier castigo justo", "Porque el bien también sería entonces una carencia"],
      answer: 1,
      explain: "El mal no se vive como un menos. Una filosofía que lo explica como negación o defecto de realidad está describiendo otro mundo. De ahí la necesidad de un principio positivo del que el mal pueda salir.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad y el fondo oscuro",
      body: "Es el punto donde el idealismo se abre a algo que ya no controla. Un fondo irracional en el origen de todo, anterior a la razón y no deducible de ella, es exactamente lo que Schopenhauer, Nietzsche, Freud y Heidegger van a explorar cada uno a su manera. Heidegger le dedicó un curso entero a este texto.",
    },
    {
      type: "short",
      question: "¿Cómo llama Schelling al fondo oscuro, anterior a toda razón, sobre el que se levanta la existencia?",
      answers: ["Grund", "fondo"],
      explain: "Hay en Dios mismo una voluntad ciega anterior a toda claridad. La libertad humana consiste en poder invertir la relación entre ese fondo y la luz, y por eso el mal es real y es libre. Schopenhauer, Nietzsche, Freud y Heidegger van a explorar ese fondo cada uno a su manera.",
    },
    {
      type: "info",
      title: "Berlín, 1841",
      body: "El último acto tiene valor de escena. En 1841, con sesenta y seis años y después de dos décadas de silencio editorial, Schelling es llamado a Berlín por Federico Guillermo IV para ocupar la cátedra de Hegel, muerto diez años antes, con el encargo explícito de combatir su influencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Berlín, 1841",
      body: "Presenta ahí su **filosofía positiva**. Toda la filosofía anterior, la suya incluida, había sido negativa: dice qué son las cosas, su esencia, y eso puede hacerse a priori. Pero que algo exista no se deduce de ningún concepto. El hecho bruto de que haya mundo y no nada es anterior a la razón y la razón no puede alcanzarlo.",
    },
    {
      type: "quiz",
      question: "¿Qué separa la filosofía positiva de la negativa en el último Schelling?",
      options: ["Que una afirma a Dios y la otra lo niega", "Que la negativa dice qué son las cosas y no que existan", "Que la positiva se apoya en las ciencias empíricas", "Que la negativa procede por análisis y la otra por síntesis"],
      answer: 1,
      explain: "Toda la filosofía anterior, la suya incluida, decía la esencia de las cosas, y eso puede hacerse a priori. Pero que algo exista no se deduce de ningún concepto: el hecho bruto de que haya mundo y no nada es anterior a la razón.",
    },
    {
      type: "match",
      question: "Uní cada obra o momento con lo que aporta",
      pairs: [
        { left: "Ideas para una filosofía de la naturaleza", right: "La naturaleza como espíritu dormido" },
        { left: "Sistema del idealismo trascendental", right: "El arte como órgano de la filosofía" },
        { left: "Exposición de mi sistema", right: "El absoluto como indiferencia de sujeto y objeto" },
        { left: "Investigaciones sobre la libertad", right: "El fondo oscuro y la realidad del mal" },
        { left: "Berlín, 1841", right: "La existencia no se deduce de ningún concepto" },
      ],
      explain: "Schelling fue el más precoz de los idealistas y el que más veces cambió de posición. Cada etapa deja algo: la naturaleza con derecho propio, el arte en la cima del sistema, y finalmente un resto que la razón no alcanza.",
    },
    {
      type: "info",
      continues: true,
      title: "Berlín, 1841",
      body: "En esas clases estuvieron sentados, entre otros, **Kierkegaard**, **Friedrich Engels**, **Bakunin** y **Jacob Burckhardt**. Los cuatro se fueron decepcionados y los cuatro se llevaron algo. Kierkegaard anotó que se le iluminó el pensamiento al oír la palabra realidad, y de ahí sale buena parte de lo que vendrá después.",
    },
  ],
};
