export default {
  num: 20,
  transcript: 20,
  title: "Hegel: dialéctica, Espíritu e historia",
  source: "",
  feed: [
    {
      type: "info",
      title: "El que viene a reconciliar",
      body: "**Georg Wilhelm Friedrich Hegel** (1770–1831) nace en Stuttgart y muere en Berlín durante una epidemia de cólera. Estudió teología en el seminario de Tubinga con Hölderlin y Schelling, fue preceptor privado y director de un diario, y llegó tarde a la cátedra: publicó su primer gran libro a los treinta y siete.",
    },
    {
      type: "info",
      continues: true,
      title: "El que viene a reconciliar",
      body: "Cuatro obras ordenan su pensamiento. La Fenomenología del Espíritu (1807) recorre el itinerario de la conciencia hasta el saber absoluto. La Ciencia de la lógica (1812–1816) despliega las categorías del pensar. La Enciclopedia (1817) presenta el sistema entero, y los Principios de la filosofía del derecho (1821) su filosofía política.",
    },
    {
      type: "info",
      continues: true,
      title: "El que viene a reconciliar",
      body: "A eso se suman las Lecciones sobre la filosofía de la historia, publicadas póstumamente en 1837 a partir de apuntes de sus alumnos. De ahí sale casi todo lo que circula popularmente como hegelianismo, y conviene recordar que es material de clase reconstruido, no un libro que Hegel haya escrito.",
    },
    {
      type: "info",
      continues: true,
      title: "El que viene a reconciliar",
      body: "En octubre de 1806, mientras terminaba la Fenomenología, Napoleón entró en Jena tras derrotar al ejército prusiano. Hegel le escribe a un amigo que vio al emperador cabalgando por la ciudad y que fue como ver al alma del mundo a caballo. La frase condensa su idea de que la historia avanza a través de individuos que no saben lo que están haciendo.",
    },
    {
      type: "info",
      continues: true,
      title: "El que viene a reconciliar",
      body: "Su lugar en este curso es el de quien viene a **reconciliar**, aunque no de manera pacífica. Reconciliar las dos corrientes que la clase anterior dejó enfrentadas: la ilustrada, con su exigencia de razón y de sistema, y la romántica, con su historia, su conflicto y su devenir. Hegel sostiene que no son adversarias sino momentos de un mismo movimiento.",
    },
    {
      type: "quiz",
      question: "¿Qué se propone reconciliar Hegel?",
      options: ["La fe revelada con la razón demostrativa", "La razón ilustrada con la historia romántica", "El empirismo inglés con el racionalismo alemán", "La libertad individual con la propiedad privada"],
      answer: 1,
      explain: "Toma de la Ilustración la exigencia de razón y de sistema, y del Romanticismo la historia, el conflicto y el devenir. Su tesis es que no son adversarias sino momentos de un mismo movimiento. La reconciliación, eso sí, no es pacífica.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "Su punto de partida es el hueco que dejó Kant. La Crítica de la razón pura había negociado un compromiso: conocemos los fenómenos con validez universal, pero las cosas en sí quedan fuera. La ciencia queda fundada y la metafísica desalojada, y el precio es una frontera infranqueable en el centro del conocimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Esa solución dejó insatisfecha a toda una generación, como vimos con Fichte y Schelling. Si la cosa en sí es incognoscible, ¿por qué seguir postulándola? Es una frontera que la filosofía traza y declara al mismo tiempo intraspasable, y para trazarla parece necesitar mirar del otro lado.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Hegel entra en esa conversación y hace la apuesta más ambiciosa de todas. No va a suprimir la diferencia entre sujeto y objeto por decreto, como le reprochó a Schelling. Va a mostrar que esa diferencia se produce, se desarrolla y se supera a sí misma, y que recorrer ese proceso es justamente lo que la filosofía tiene que hacer.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Detrás está un problema que va a volver una y otra vez, y que los filósofos describen de mil maneras: mente y mundo, conciencia y ser, interior y exterior, sujeto y objeto. Todas nombran lo mismo: ¿cómo sé que lo que pienso corresponde a algo que no soy yo? Hegel lo llama el problema del puente.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Todo su pensamiento parte además de una constatación elemental: siempre hay opuestos. La razón y la pasión, el ser y el deber ser, el yo y el otro, el individuo y lo universal. La tradición había tratado la oposición como un error a corregir. Hegel la trata como el motor de lo real.",
    },
    {
      type: "quiz",
      question: "¿Qué le objeta Hegel al compromiso kantiano sobre la cosa en sí?",
      options: ["Que traza una frontera y la declara cerrada", "Que renuncia a fundar la ciencia natural moderna", "Que hace del sujeto el creador de sus objetos", "Que confunde el fenómeno con la mera apariencia"],
      answer: 0,
      explain: "Para trazar esa frontera la filosofía parece necesitar mirar del otro lado. Hegel no la suprime por decreto, como le reprochó a Schelling: muestra que la diferencia entre sujeto y objeto se produce, se desarrolla y se supera a sí misma.",
    },
    {
      type: "info",
      title: "La historia entra en la filosofía",
      body: "Su movimiento decisivo es tomar la **historia** y convertirla en un componente integral de la filosofía, no en un apéndice. Antes de él, la historia de la filosofía era el catálogo de los errores anteriores; después de él, es el desarrollo necesario de la verdad, y no se puede pensar sin ella.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia entra en la filosofía",
      body: "Se entiende la resistencia que eso provocaba. El modelo de verdad que todos querían era el matemático: que dos más dos sean cuatro no depende del siglo ni del país ni de quién lo diga. La historia, en cambio, trae siempre lo empírico y lo contingente, y parece contaminar cualquier pretensión de necesidad.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia entra en la filosofía",
      body: "Hegel invierte el argumento. Lo que parece contaminación es en realidad la única manera de que la verdad tenga contenido. Una verdad que valiera para todo tiempo y lugar no diría nada sobre ninguno; las verdades que importan —sobre la libertad, el derecho, el arte, Dios— son justamente las que se desarrollan.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia entra en la filosofía",
      body: "De ahí su aporte más duradero, y hay que nombrarlo con precisión. Se llama **historicismo**: la tesis de que las ideas, los valores y hasta los criterios de racionalidad tienen fecha, pertenecen a una época y se entienden desde ella. Nadie piensa fuera de su tiempo, y pretender hacerlo es la ilusión característica de cada tiempo.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la tesis de que las ideas y los valores pertenecen a una época y se entienden desde ella?",
      answers: ["historicismo"],
      explain: "Nadie piensa fuera de su tiempo, y pretender hacerlo es la ilusión característica de cada tiempo. Es el aporte más duradero de Hegel y el que sus herederos van a conservar, aun descartando todo lo demás.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia entra en la filosofía",
      body: "Es una idea de doble filo. De un lado libera: vacuna contra tomar las costumbres propias por naturaleza y muestra que lo que parecía eterno fue instituido. Del otro amenaza: si toda verdad es hija de su época, ¿con qué criterio decimos que una época se equivocó? Es el **problema del relativismo**, y va a atravesar los dos siglos siguientes.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia entra en la filosofía",
      body: "Hegel cree tener la respuesta. Cada época es parcial, sí, pero las épocas no se suceden al azar: se ordenan en una progresión con dirección. Ninguna es verdadera por sí sola y todas lo son como momentos del recorrido. Sus herederos van a quedarse con el historicismo y descartar la garantía de progreso, y ahí empieza el problema.",
    },
    {
      type: "quiz",
      question: "¿Cuál es el filo peligroso del historicismo?",
      options: ["Que vuelve imposible estudiar el pasado remoto", "Que deja sin criterio para juzgar una época", "Que hace del progreso una ley natural inevitable", "Que subordina la filosofía a la investigación empírica"],
      answer: 1,
      explain: "Si toda verdad es hija de su época, el juicio sobre las épocas se queda sin apoyo. Hegel cree resolverlo diciendo que las épocas se ordenan en una progresión con dirección; sus herederos se van a quedar con el historicismo y a descartar esa garantía.",
    },
    {
      type: "info",
      title: "La dialéctica",
      body: "¿Cómo se mueve ese proceso? A través de lo que Hegel llama **dialéctica**. La versión escolar —tesis, antítesis, síntesis— no es suya sino de un comentarista, y aunque sirve para empezar, oculta lo esencial: la contradicción no viene de afuera, sale de adentro de lo que se examina.",
    },
    {
      type: "info",
      continues: true,
      title: "La dialéctica",
      body: "El movimiento es más o menos éste. Se parte de una posición que se sostiene sola. Al desarrollarla con rigor, aparece que produce ella misma su opuesto y no puede sostenerse sin él. Y de esa crisis no se sale volviendo atrás ni eligiendo un bando, sino pasando a una posición nueva que conserva lo que ambas tenían de verdadero.",
    },
    {
      type: "quiz",
      question: "¿Qué oculta la versión escolar de tesis, antítesis y síntesis?",
      options: ["Que la síntesis nunca llega a ser definitiva", "Que la contradicción sale de adentro", "Que el proceso requiere siempre tres momentos", "Que Hegel la tomó de la lógica de los antiguos"],
      answer: 1,
      explain: "Esa fórmula no es de Hegel sino de un comentarista. Lo esencial es que la contradicción no se le aplica a una posición desde afuera: se parte de algo que se sostiene solo, y al desarrollarlo con rigor aparece que produce su propio opuesto.",
    },
    {
      type: "info",
      continues: true,
      title: "La dialéctica",
      body: "El nombre técnico de ese pasaje es **Aufheben**, y es una de esas palabras que hacen sufrir a los traductores. En alemán corriente significa tres cosas a la vez: elevar, cancelar y conservar. Hegel usa las tres. Lo superado queda cancelado como posición autónoma, conservado como momento, y elevado a un nivel más alto.",
    },
    {
      type: "info",
      continues: true,
      title: "La dialéctica",
      body: "Sirve el ejemplo del árbol frutal. La flor no es un error del capullo: el capullo tuvo que desaparecer para que hubiera flor, y la flor desaparece para que haya fruto. Ninguna de las tres es la verdad del árbol por separado, y sólo el proceso entero lo es. No hay contradicción entre ellas, hay desarrollo.",
    },
    {
      type: "short",
      question: "¿Qué palabra usa Hegel para el paso que cancela, conserva y eleva a la vez?",
      answers: ["Aufheben", "Aufhebung", "superación"],
      explain: "En alemán corriente significa las tres cosas, y Hegel usa las tres. Lo superado queda cancelado como posición autónoma, conservado como momento y elevado a un nivel más alto. La flor no es un error del capullo.",
    },
    {
      type: "info",
      continues: true,
      title: "La dialéctica",
      body: "También conviene ver que el movimiento no es parejo sino **a los saltos**, y que ahí Hegel introduce una idea que va a tener enorme fortuna: el pasaje **de cantidad a calidad**. El modelo es el agua que se calienta. Sube un grado, otro, otro, y aparentemente no pasa nada, hasta que a los cien grados deja de ser líquida.",
    },
    {
      type: "info",
      continues: true,
      title: "La dialéctica",
      body: "Nada indicaba el salto salvo la acumulación previa, y sin embargo lo que resulta no es más de lo mismo sino algo de otra clase. Marx va a tomar exactamente esta figura para pensar la revolución: no como un accidente, sino como el punto en que un cambio cuantitativo acumulado se vuelve un cambio de naturaleza.",
    },
    {
      type: "quiz",
      question: "¿Qué muestra el ejemplo del agua que hierve?",
      options: ["Que todo cambio real requiere una intervención", "Que lo acumulado da de golpe otra cosa", "Que la naturaleza también obedece a la dialéctica", "Que los procesos físicos son siempre reversibles"],
      answer: 1,
      explain: "Nada indica el salto salvo la acumulación previa, y lo que resulta no es más de lo mismo. Marx va a tomar exactamente esta figura del pasaje de cantidad a calidad para pensar la revolución.",
    },
    {
      type: "info",
      title: "Geist: el Espíritu",
      body: "**Geist** es el concepto más difícil y el más central. Se traduce a veces como mente y más frecuentemente como **espíritu**, pero conviene tener presente que en alemán no tiene la connotación religiosa ni fantasmal que arrastra en castellano: designa la vida consciente en general, individual y colectiva a la vez.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "Se puede pensar el Espíritu como una conciencia que no está alojada en ninguna cabeza en particular sino repartida en las prácticas, las instituciones, el arte, la religión y la lengua de una comunidad. No es la suma de los individuos ni algo que exista aparte de ellos: es lo que hay entre ellos y los constituye como quienes son.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "La fórmula de Hegel es \"el **yo que es un nosotros y el nosotros que es un yo**\". Es su manera de resolver la oposición entre individuo y totalidad sin sacrificar ninguno de los dos, que era exactamente el punto donde la Ilustración y el Romanticismo no lograban entenderse.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "El Espíritu tiene grados, y los nombres importan porque van a circular por todo el siglo XIX. El **Volksgeist** es el espíritu de un pueblo: la forma concreta que el Espíritu adopta en una nación, con su lengua, su derecho y su religión. El **Zeitgeist** es el espíritu de una época, lo que una generación da por evidente sin discutirlo.",
    },
    {
      type: "quiz",
      question: "¿Qué resuelve la fórmula «el yo que es un nosotros y el nosotros que es un yo»?",
      options: ["La distancia entre el pensamiento y el lenguaje", "La oposición entre individuo y totalidad", "El conflicto entre la fe y el saber", "La brecha entre la teoría y la práctica"],
      answer: 1,
      explain: "El Espíritu no es la suma de los individuos ni algo que exista aparte de ellos: es lo que hay entre ellos y los constituye. Ése era justamente el punto donde la Ilustración y el Romanticismo no lograban entenderse.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "Cuando Hegel ve a Napoleón en Jena y dice el alma del mundo a caballo, está diciendo exactamente esto: que en ese hombre concreto se encarna, sin que él lo sepa, un momento necesario del proceso. Napoleón cree estar conquistando; lo que hace, para Hegel, es difundir el código civil por Europa.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "Esa idea tiene un nombre: la **astucia de la razón**. Los individuos actúan por sus pasiones, sus intereses y sus ambiciones privadas, y del choque de todas esas voluntades resulta algo que ninguna se propuso. La historia usa las pasiones de los hombres para fines que los exceden, y nada grande se hizo nunca sin pasión.",
    },
    {
      type: "quiz",
      question: "¿Qué nombra la astucia de la razón?",
      options: ["Que los grandes hombres calculan mejor que el resto", "Que del choque de intereses sale lo que nadie quiso", "Que la filosofía descubre leyes ocultas de la historia", "Que el Estado disimula sus fines ante los ciudadanos"],
      answer: 1,
      explain: "Los individuos actúan por sus pasiones y ambiciones, y la historia las usa para fines que los exceden. Napoleón cree estar conquistando; lo que hace, para Hegel, es difundir el código civil por Europa. Nada grande se hizo nunca sin pasión.",
    },
    {
      type: "info",
      title: "Amo y esclavo",
      body: "La escena más citada de toda la obra de Hegel está en la Fenomenología y ocupa apenas unas páginas. Su punto de partida es que la autoconciencia no se alcanza a solas. Puedo saber que existo, pero saber quién soy exige que otro me lo reconozca, y por eso el otro no es un obstáculo sino una condición.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo",
      body: "Dos autoconciencias se encuentran y cada una exige de la otra el **reconocimiento**. Como ninguna quiere concederlo primero, la cosa deriva en una lucha a muerte. Pero matar al otro no sirve: un muerto no reconoce a nadie. La salida es que uno ceda por miedo y acepte servir, y ahí quedan constituidos el amo y el esclavo.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo",
      body: "El amo parece haber ganado. Obtiene el reconocimiento y goza de las cosas sin trabajarlas. Pero su triunfo se pudre solo: el reconocimiento que recibe viene de alguien a quien él no reconoce como igual, o sea que no vale nada. Y como no trabaja, su relación con el mundo pasa entera por el esclavo, del que depende.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo",
      body: "El esclavo, en cambio, tiene dos cosas que el amo perdió. Tuvo miedo a la muerte, y esa experiencia lo sacudió entero. Y trabaja: transforma la materia, y al hacerlo se ve a sí mismo en lo que produjo. El objeto trabajado es su conciencia hecha cosa, y por esa vía llega a una libertad que el amo no alcanza.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo",
      body: "La escena describe una estructura, no un episodio histórico. Se la ha leído como una parábola del trabajo, de la lucha de clases, de la relación colonial, del psicoanálisis y del deseo. Marx, Kojève, Sartre, Fanon, Lacan y Beauvoir la van a usar cada uno para lo suyo, y es probablemente el pasaje más influyente del siglo XIX.",
    },
    {
      type: "classify",
      question: "En la dialéctica del reconocimiento, ¿cada rasgo es del amo o del esclavo?",
      groups: ["Amo", "Esclavo"],
      items: [
        { text: "Goza de las cosas sin trabajarlas", group: 0 },
        { text: "Recibe reconocimiento de quien no reconoce", group: 0 },
        { text: "Depende del otro para su relación con el mundo", group: 0 },
        { text: "Cedió por miedo a la muerte", group: 1 },
        { text: "Se ve a sí mismo en lo que produjo", group: 1 },
        { text: "Llega a una libertad que el otro no alcanza", group: 1 },
      ],
      explain: "El triunfo del amo se pudre solo, porque un reconocimiento que viene de alguien a quien no se reconoce como igual no vale nada. El esclavo, en cambio, tuvo la experiencia del miedo y tiene el trabajo, y por esa vía transforma el mundo y se transforma.",
    },
    {
      type: "info",
      title: "La libertad en las instituciones",
      body: "En política, Hegel rompe con la tradición que este curso venía siguiendo. Para Hobbes, Locke y Rousseau la libertad se piensa desde el individuo, y el Estado es un artificio que los individuos construyen para limitar algo de su libertad natural a cambio de seguridad o de derechos.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad en las instituciones",
      body: "Para Hegel eso es un error de base, porque supone un individuo ya formado antes de toda relación. Nadie es libre en el vacío. Se es libre en una lengua que se recibió, con conceptos que no se inventaron, dentro de instituciones que hacen posible querer algo determinado. La libertad no se limita en la vida común: se realiza ahí.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad en las instituciones",
      body: "De ahí su definición, que suena escandalosa hasta que se la entiende: la libertad es el **reconocimiento de la necesidad**. No es resignación. Es que ser libre no consiste en que nada me determine —eso sería puro capricho— sino en comprender las determinaciones que me constituyen y hacerlas mías al asumirlas.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad en las instituciones",
      body: "Su filosofía política es por eso una teoría de la **eticidad**: la familia, la sociedad civil y el Estado como los tres ámbitos donde esa libertad concreta se realiza. Y su prueba de que la historia tiene dirección es una sola frase: los orientales sabían que uno es libre, los griegos y romanos que algunos lo son, nosotros que todos lo son.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad en las instituciones",
      body: "Conviene señalar la ambigüedad, porque va a costar cara. Un argumento que identifica la libertad con las instituciones existentes puede justificar las instituciones existentes. Hegel escribió que lo racional es real y lo real es racional, y esa frase se leyó tanto como una defensa del Estado prusiano como una exigencia de transformarlo.",
    },
    {
      type: "quiz",
      question: "¿Qué quiere decir que la libertad sea el reconocimiento de la necesidad?",
      options: ["Que hay que resignarse a lo que no se puede cambiar", "Que ser libre es asumir lo que me constituye", "Que sólo el Estado puede garantizar derechos reales", "Que la libertad natural precede a toda institución"],
      answer: 1,
      explain: "Para Hobbes, Locke y Rousseau la libertad se piensa desde el individuo y el Estado la limita. Para Hegel nadie es libre en el vacío: se es libre en una lengua recibida y dentro de instituciones que hacen posible querer algo determinado.",
    },
    {
      type: "info",
      title: "El búho de Minerva y la herencia",
      body: "En el prólogo de la Filosofía del derecho está la imagen que resume su idea de qué puede hacer la filosofía. El **búho de Minerva** levanta el vuelo al atardecer: la comprensión llega siempre cuando una forma de vida ya se completó. La filosofía no anticipa el futuro ni le da recetas al presente, lo piensa cuando ya pasó.",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva y la herencia",
      body: "Es una tesis modesta y también una limitación seria, y la primera cosa que sus herederos van a rechazar. Si la filosofía sólo llega tarde, entonces no sirve para transformar nada. Toda la generación siguiente va a escribir contra esa frase.",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva y la herencia",
      body: "Porque a su muerte, en 1831, el hegelianismo se parte en dos. Los **hegelianos de derecha** leen el sistema como una consagración de lo existente: si lo real es racional, el Estado prusiano y la religión establecida son la culminación del proceso, y no queda más que comprenderlo.",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva y la herencia",
      body: "Los **hegelianos de izquierda** —Feuerbach, Bauer, Strauss, el joven Marx— leen lo contrario. Si el motor de la historia es la contradicción, entonces ninguna forma presente es definitiva, y lo racional no es lo que hay sino lo que viene. El método es revolucionario aunque el sistema haya sido conservador.",
    },
    {
      type: "quiz",
      question: "¿En qué se separan los hegelianos de derecha y los de izquierda?",
      options: ["En si el Espíritu es individual o colectivo", "En si lo racional es lo que hay o lo que viene", "En si la dialéctica se aplica a la naturaleza", "En si la religión precede o sigue al Estado"],
      answer: 1,
      explain: "La derecha lee el sistema como consagración de lo existente: si lo real es racional, no queda más que comprenderlo. La izquierda lee que si el motor es la contradicción, ninguna forma presente es definitiva. El método es revolucionario aunque el sistema fuera conservador.",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva y la herencia",
      body: "Feuerbach da el primer paso decisivo con La esencia del cristianismo (1841): lo que llamamos Dios es la esencia del hombre proyectada afuera y adorada como algo ajeno, y por eso la teología es antropología mal entendida. El movimiento —tomar una figura de Hegel y darla vuelta poniendo lo material primero— es el que va a repetir su lector más famoso.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que nombra",
      pairs: [
        { left: "Aufheben", right: "Cancelar, conservar y elevar en un solo paso" },
        { left: "Geist", right: "La vida consciente repartida en una comunidad" },
        { left: "Volksgeist", right: "La forma que toma el Espíritu en una nación" },
        { left: "Astucia de la razón", right: "Las pasiones privadas al servicio de un fin mayor" },
        { left: "Búho de Minerva", right: "La comprensión que llega cuando la época terminó" },
      ],
      explain: "El sistema entero es un solo movimiento: la contradicción empuja, el Aufheben la resuelve conservándola, el Espíritu es el sujeto de ese recorrido y la filosofía sólo lo comprende una vez cumplido.",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva y la herencia",
      body: "Hegel es el último gran sistema de la filosofía moderna, y en cierto sentido su cierre. Reunió la razón ilustrada y la historia romántica en una sola arquitectura que pretendía contener todo lo pensable. Lo que sigue en este curso es el primero que aceptó el método y rechazó el sistema entero.",
    },
  ],
};
