export default {
  num: 11,
  transcript: 11,
  title: "La Ilustración francesa: Voltaire y la Enciclopedia",
  source: "",
  feed: [
    {
      type: "info",
      title: "Las Luces francesas",
      body: "En Francia el movimiento ilustrado se llama **Lumières**, «luces»: la misma imagen que en inglés y en alemán, pero con un matiz de combate que en Inglaterra no hacía falta. Francia sigue siendo, a mediados del siglo XVIII, una monarquía absoluta con censura eclesiástica activa, así que ilustrar significa aquí enfrentarse a un poder que todavía puede encarcelar, exiliar o quemar libros.",
    },
    {
      type: "info",
      continues: true,
      title: "Las Luces francesas",
      body: "Esa diferencia de contexto vuelve a la Ilustración francesa más polémica y más literaria que la inglesa. Sus autores no escriben tratados académicos sino cuentos, diálogos, artículos de diccionario, cartas: formas breves, ingeniosas, pensadas para circular y para eludir al censor. La filosofía se vuelve un género de entretenimiento culto, sin perder rigor.",
    },
    {
      type: "info",
      continues: true,
      title: "Las Luces francesas",
      body: "Esa elección de formas breves no es sólo prudencia frente al censor: responde también a un público distinto del inglés. En Francia, la vida intelectual se organiza en torno a los salones aristocráticos y burgueses, donde se lee en voz alta, se discute y se circula manuscrito antes de imprimir. Un texto ingenioso y corto rinde mejor en ese ambiente oral que un tratado sistemático.",
    },
    {
      type: "quiz",
      question: "La Ilustración francesa es más polémica que la inglesa porque…",
      options: [
        "sus autores no saben escribir tratados extensos",
        "actúa bajo una monarquía con censura eclesiástica activa",
        "carece de filósofos con formación universitaria",
        "Francia nunca tuvo contacto con la ciencia inglesa",
      ],
      answer: 1,
      explain: "A mediados del siglo XVIII Francia sigue siendo una monarquía absoluta con censura eclesiástica activa: ilustrar allí significa enfrentar un poder que puede encarcelar, exiliar o quemar libros, de ahí el tono más combativo y literario.",
    },
    {
      type: "info",
      title: "Voltaire: de Londres a Ferney",
      body: "**François-Marie Arouet**, conocido como **Voltaire** (1694–1778), es la figura central de esta Ilustración. Antes de sus treinta años ya pasó dos veces por la Bastilla por sus escritos satíricos contra la nobleza. En 1726 un conflicto con un aristócrata lo obliga a exiliarse en Inglaterra, donde pasa casi tres años decisivos para su formación.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "En Londres, Voltaire descubre lo que Inglaterra ya había resuelto: un Parlamento que limita al rey, una ciencia newtoniana libre de tutela eclesiástica, una filosofía lockeana que explica la mente sin apelar a ideas innatas, y una tolerancia religiosa práctica entre credos distintos. Vuelve a Francia convencido de que ese modelo es superior al propio.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "El resultado son las **Cartas filosóficas** (1734), también llamadas Cartas inglesas: veinticinco cartas que presentan al público francés la ciencia de Newton, la filosofía de Locke, la tolerancia religiosa inglesa y las costumbres políticas de un país que, a ojos de Voltaire, resolvió mejor que Francia el problema de convivir con la diferencia. El libro es prohibido y quemado apenas se publica: es demasiado evidente el contraste que traza con el absolutismo francés.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "Con los años Voltaire se instala en Ferney, cerca de la frontera suiza, desde donde puede escribir con relativa impunidad y organizar campañas públicas contra los abusos de la justicia y de la Iglesia, como el caso de Jean Calas, un protestante ejecutado injustamente en 1762. En 1764 publica el **Diccionario filosófico**, una obra de referencia organizada por entradas breves —«Dios», «tolerancia», «alma», «fanatismo»— que somete cada concepto tradicional a un examen irónico y devastador.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "El estilo de Voltaire es la ironía sostenida: no ataca de frente, sino que deja que el absurdo de una posición se revele por sí mismo cuando se la describe con precisión. Esa misma técnica gobierna su novela filosófica Cándido (1759), donde el optimismo metafísico que sostiene que «todo está bien en el mejor de los mundos posibles» se estrella una y otra vez contra catástrofes reales: terremotos, guerras, esclavitud.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "Cándido apunta, en particular, contra la filosofía de Leibniz —el racionalismo de la clase 7, con su tesis de que este es «el mejor de los mundos posibles» porque Dios, siendo perfecto, no pudo haber elegido otro—. Voltaire escribe la novela poco después del terremoto de Lisboa de 1755, que mató a decenas de miles de personas, y para él ese hecho basta para volver obscena cualquier justificación abstracta del mal en el mundo.",
    },
    {
      type: "quiz",
      question: "Cándido usa el desastre de Lisboa de 1755 para…",
      options: [
        "probar que Dios no existe en absoluto",
        "atacar la idea de que este es el mejor mundo posible",
        "defender el optimismo racionalista de Leibniz",
        "mostrar que la ciencia no explica los terremotos",
      ],
      answer: 1,
      explain: "Cándido apunta contra el optimismo metafísico de Leibniz —que este es «el mejor de los mundos posibles»—. El terremoto de Lisboa, con decenas de miles de muertos, vuelve para Voltaire obscena cualquier justificación abstracta del mal.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "En el caso Calas, Voltaire no se limita a escribir: organiza una campaña pública sostenida durante años, reúne testimonios, presiona a jueces y publica el Tratado sobre la tolerancia (1763) a partir de ese caso concreto. Logra en 1765 la rehabilitación póstuma de Calas, y ese episodio consolida su imagen pública como defensor de las víctimas del fanatismo judicial, más allá de sus libros.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire: de Londres a Ferney",
      body: "En religión, Voltaire es deísta, en la línea que ya trazó Inglaterra: cree en un Dios ordenador del universo, rechaza los dogmas de las Iglesias establecidas y denuncia el **fanatismo** como el mayor enemigo de la civilización. Su lema, repetido bajo distintas formas, es «aplastad a la infame», refiriéndose a la superstición organizada institucionalmente, no a la fe personal.",
    },
    {
      type: "quiz",
      question: "La campaña de Voltaire por el caso Calas fue, ante todo, un…",
      options: [
        "tratado abstracto sobre la tolerancia religiosa",
        "activismo judicial concreto contra el fanatismo",
        "intento de convertir a Calas al catolicismo",
        "pedido de amnistía general para todos los presos",
      ],
      answer: 1,
      explain: "Voltaire no se limita a escribir: reúne testimonios, presiona a la justicia y publica el Tratado sobre la tolerancia a partir del caso, hasta lograr en 1765 la rehabilitación póstuma de Calas. Es activismo, no sólo teoría.",
    },
    {
      type: "info",
      title: "Montesquieu y el espíritu de las leyes",
      body: "**Charles-Louis de Secondat, barón de Montesquieu** (1689–1755), aporta a la Ilustración francesa la dimensión política que a Voltaire le interesa menos. En **El espíritu de las leyes** (1748) analiza cómo las leyes de cada pueblo dependen de factores concretos —el clima, el territorio, las costumbres, la religión— y no de un modelo único y universal de buen gobierno.",
    },
    {
      type: "info",
      continues: true,
      title: "Montesquieu y el espíritu de las leyes",
      body: "Su aporte más influyente es la doctrina de la **separación de poderes**: el poder legislativo, el ejecutivo y el judicial deben estar en manos distintas, porque sólo el poder detiene al poder. Montesquieu toma el modelo inglés de gobierno mixto como referencia y lo convierte en una teoría general que influirá directamente en las constituciones liberales del siglo siguiente.",
    },
    {
      type: "info",
      continues: true,
      title: "Montesquieu y el espíritu de las leyes",
      body: "Montesquieu distingue además tres formas de gobierno según el principio que las anima: la república, sostenida por la virtud cívica; la monarquía, por el honor; el despotismo, por el miedo. No juzga que una sola forma sea válida para todos los pueblos: lo que le preocupa es que cualquier gobierno, incluida una monarquía moderada como la francesa, puede degenerar en despotismo si el poder deja de estar repartido y controlado.",
    },
    {
      type: "info",
      continues: true,
      title: "Montesquieu y el espíritu de las leyes",
      body: "Ese análisis comparativo, apoyado en un examen extenso de leyes antiguas y modernas, europeas y no europeas, es lo que distingue a Montesquieu de un simple panfletista político: pretende fundar una ciencia de la legislación, empírica y comparativa, en vez de derivar el buen gobierno de un solo principio racional abstracto, al modo en que lo haría un tratado more geometrico.",
    },
    {
      type: "quiz",
      question: "Para Montesquieu, la separación de poderes existe porque…",
      options: [
        "sólo el poder es capaz de detener al poder",
        "cada poder debe obedecer siempre al mismo rey",
        "la virtud cívica alcanza para evitar el abuso",
        "el clima de cada país determina sus leyes",
      ],
      answer: 0,
      explain: "Montesquieu formula la separación de poderes —legislativo, ejecutivo y judicial en manos distintas— porque sólo el poder detiene al poder: cualquier gobierno, aun una monarquía moderada, puede degenerar en despotismo si no está repartido.",
    },
    {
      type: "info",
      title: "La Enciclopedia y el enciclopedismo",
      body: "El proyecto más ambicioso de la Ilustración francesa es la **Enciclopedia, o Diccionario razonado de las ciencias, las artes y los oficios**, publicada entre 1751 y 1772 en volúmenes sucesivos. Su propósito declarado es reunir en un solo lugar todo el saber humano disponible, y ponerlo al alcance de cualquier lector capaz de leerlo, no sólo de las universidades y los círculos eclesiásticos.",
    },
    {
      type: "info",
      continues: true,
      title: "La Enciclopedia y el enciclopedismo",
      body: "Dirigen el proyecto **Denis Diderot** (1713–1784) y **Jean le Rond d'Alembert** (1717–1783). Diderot aporta la energía editorial y una escritura filosófica audaz que evoluciona hacia el materialismo; d'Alembert, matemático y físico, redacta el «Discurso preliminar» que presenta el mapa completo del conocimiento humano organizado según sus facultades: memoria, razón e imaginación.",
    },
    {
      type: "info",
      continues: true,
      title: "La Enciclopedia y el enciclopedismo",
      body: "El plan reúne a más de ciento cincuenta colaboradores —los llamados philosophes— entre los que figuran Voltaire, Montesquieu y Rousseau. Cada artículo técnico convive con remisiones internas que, muchas veces, dejan caer una crítica velada a la religión o a la monarquía bajo la excusa de describir un oficio o una máquina. Es una obra de saber y, a la vez, un arma política.",
    },
    {
      type: "info",
      continues: true,
      title: "La Enciclopedia y el enciclopedismo",
      body: "El artículo «**Filósofo**», escrito por Diderot a partir de un texto anterior de César Chesneau Dumarsais, define al filósofo ilustrado como quien actúa guiado por la razón y por la observación de la experiencia, y no por la pasión, la costumbre o la autoridad ciega. El filósofo, dice el artículo, no es un asceta apartado del mundo, sino un ciudadano razonable que busca el bien común dentro de la sociedad en la que vive.",
    },
    {
      type: "quiz",
      question: "El artículo «Filósofo» de la Enciclopedia define al filósofo como…",
      options: [
        "un asceta que se aparta de la vida social",
        "un ciudadano razonable que busca el bien común",
        "un experto que sólo domina la lógica formal",
        "un crítico que rechaza toda pasión humana",
      ],
      answer: 1,
      explain: "El artículo, escrito por Diderot, define al filósofo ilustrado como quien actúa guiado por la razón y la experiencia, no por la autoridad ciega: un ciudadano razonable dentro de la sociedad, no un sabio solitario apartado del mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "La Enciclopedia y el enciclopedismo",
      body: "El artículo insiste, además, en un punto polémico: el filósofo no necesita retirarse de la sociedad ni renunciar a las pasiones humanas para ser virtuoso, como pedía cierta tradición estoica o monástica. Le basta con someter esas pasiones al examen de la razón antes de actuar. Es un ideal de sociabilidad ilustrada, muy distinto del sabio solitario de la filosofía antigua.",
    },
    {
      type: "info",
      continues: true,
      title: "La Enciclopedia y el enciclopedismo",
      body: "Ese perfil —razón aplicada a la vida civil, y no encerrada en la especulación— resume el ideal que la Enciclopedia quiere difundir. La obra sufre censuras, suspensiones de su privilegio de impresión y hasta la condena del Papa, pero se completa igual, distribuida en parte de manera clandestina, y se convierte en el símbolo del **enciclopedismo**: la convicción de que organizar y divulgar el saber es en sí mismo un acto político.",
    },
    {
      type: "info",
      continues: true,
      title: "La Enciclopedia y el enciclopedismo",
      body: "El poder real de la Enciclopedia se percibe en la reacción que provoca: en 1759 el Consejo del Rey revoca su privilegio de impresión, acusándola de minar la moral y la autoridad religiosa, y el propio Papa Clemente XIII la condena en 1759 e incluye la obra en el Índice de libros prohibidos. Diderot, pese a todo, sigue editándola en secreto hasta terminar los últimos volúmenes, publicados de una sola vez en 1765 para eludir la censura previa.",
    },
    {
      type: "match",
      question: "Uní cada autor con su obra",
      pairs: [
        { left: "Voltaire", right: "Cartas filosóficas (1734): el modelo inglés para Francia" },
        { left: "Montesquieu", right: "El espíritu de las leyes (1748): la separación de poderes" },
        { left: "Diderot y d'Alembert", right: "La Enciclopedia (1751–1772): organizar todo el saber" },
        { left: "d'Holbach", right: "Sistema de la naturaleza (1770): el materialismo ateo" },
      ],
      explain: "Cuatro obras que resumen el repertorio francés: la admiración por Inglaterra, la ciencia política comparada, el proyecto enciclopédico colectivo y el punto más extremo al que llega la crítica religiosa ilustrada.",
    },
    {
      type: "info",
      title: "El materialismo francés",
      body: "De ese círculo de colaboradores surge la corriente más radical de la Ilustración continental: el **materialismo francés**, que sostiene que sólo existe la materia en movimiento, sin espíritu ni alma inmaterial, y que explica el pensamiento mismo como una función del cerebro. Diderot avanza en esa dirección en escritos como El sueño de d'Alembert, y otros colaboradores del círculo, como el barón d'Holbach, la llevan hasta el ateísmo declarado.",
    },
    {
      type: "info",
      continues: true,
      title: "El materialismo francés",
      body: "Ese materialismo va más lejos que el deísmo inglés o que el propio Voltaire, que siempre conserva la idea de un Dios ordenador. Marca el punto más extremo al que llega la crítica religiosa ilustrada en el continente, y es también el blanco que la reacción posterior —tanto religiosa como filosófica— señalará como la consecuencia lógica de llevar la razón hasta sus últimas consecuencias.",
    },
    {
      type: "info",
      continues: true,
      title: "El materialismo francés",
      body: "El barón d'Holbach lo expresa sin rodeos en el Sistema de la naturaleza (1770), publicado bajo seudónimo por el riesgo que implicaba firmarlo: el universo entero es materia en movimiento regida por leyes necesarias, sin lugar para un dios creador ni para un alma inmortal, y las religiones son, para él, invenciones humanas que explotan el miedo y la ignorancia con fines de dominación política y sacerdotal.",
    },
    {
      type: "quiz",
      question: "El materialismo francés va más lejos que el deísmo porque…",
      options: [
        "niega que la materia esté en movimiento",
        "descarta a Dios y no sólo la revelación",
        "acepta los milagros como pruebas racionales",
        "vuelve a fundar la moral en la revelación",
      ],
      answer: 1,
      explain: "El deísmo, incluso en Voltaire, conserva la idea de un Dios ordenador. El materialismo francés, con d'Holbach, va más lejos: sostiene que sólo existe la materia en movimiento y descarta directamente la existencia de un dios creador.",
    },
    {
      type: "info",
      title: "Voltaire contra Rousseau",
      body: "La Ilustración francesa no es un bloque homogéneo, y la disputa que mejor lo muestra es la que enfrenta a Voltaire con **Jean-Jacques Rousseau** (1712–1778). Ambos colaboran alguna vez en el mismo círculo de los philosophes, pero sus diagnósticos sobre la civilización son opuestos, y la distancia se vuelve pública y personal.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire contra Rousseau",
      body: "La ruptura se agrava, además, por un episodio personal: cuando Rousseau publica el Emilio (1762) y El contrato social (1762) y ambos son condenados y quemados en París y en Ginebra, Voltaire no lo defiende con la misma energía que puso en el caso Calas, y Rousseau llega a sospechar, probablemente sin fundamento sólido, que Voltaire conspira contra él. La disputa filosófica se mezcla así con un resentimiento que dura hasta la muerte de ambos, ocurrida el mismo año, 1778.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire contra Rousseau",
      body: "Rousseau, que ya sostuvo en el Discurso sobre el origen de la desigualdad (1755) que el progreso de las ciencias y las artes corrompió al ser humano en vez de perfeccionarlo, desconfía del optimismo racionalista que Voltaire representa. Para Rousseau, la civilización ilustrada genera desigualdad, vanidad y dependencia, no libertad.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire contra Rousseau",
      body: "Voltaire responde con desprecio irónico: tras leer el Discurso, le escribe a Rousseau que su libro «da ganas de andar a cuatro patas», y lo acusa de idealizar un estado de naturaleza que nunca existió. Para Voltaire, el progreso del conocimiento y de las costumbres, con todos sus defectos, es preferible a cualquier primitivismo imaginado.",
    },
    {
      type: "info",
      continues: true,
      title: "Voltaire contra Rousseau",
      body: "El enfrentamiento no es sólo de temperamentos: expone una fractura interna de la Ilustración misma, entre quienes confían en que la razón y el progreso material mejoran la condición humana, y quienes —como Rousseau— sospechan que ese mismo progreso encubre nuevas formas de sujeción. Esa sospecha rousseauniana anticipa, dentro del propio siglo ilustrado, las críticas que la Ilustración alemana y el Sturm und Drang le harán después a la razón calculadora.",
    },
    {
      type: "classify",
      question: "¿Cada postura es de Voltaire o de Rousseau?",
      groups: ["Voltaire", "Rousseau"],
      items: [
        { text: "El progreso de las ciencias corrompió al ser humano", group: 1 },
        { text: "El conocimiento y las costumbres, con defectos, son preferibles", group: 0 },
        { text: "La civilización genera desigualdad y dependencia", group: 1 },
        { text: "El fanatismo religioso es el principal enemigo a combatir", group: 0 },
        { text: "El estado de naturaleza no fue el paraíso que se imagina", group: 0 },
      ],
      explain: "Rousseau desconfía del progreso ilustrado: para él la civilización corrompió al ser humano libre e igual. Voltaire responde con desprecio irónico: prefiere el progreso imperfecto a cualquier primitivismo imaginado, y concentra su combate en el fanatismo.",
    },
    {
      type: "short",
      question: "¿Cómo se llama a los intelectuales comprometidos, como Voltaire o Montesquieu, que colaboran en la Enciclopedia?",
      answers: ["philosophes", "los philosophes"],
      explain: "Más de ciento cincuenta colaboradores, llamados philosophes, escriben la Enciclopedia: un perfil de filósofo aplicado a la vida civil, no encerrado en la especulación abstracta.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada eje con su idea central",
      pairs: [
        { left: "Voltaire", right: "Deísmo, ironía y campañas contra el fanatismo" },
        { left: "Montesquieu", right: "Separación de poderes y ciencia comparada de las leyes" },
        { left: "La Enciclopedia", right: "Reunir y divulgar todo el saber humano disponible" },
        { left: "Materialismo francés", right: "Sólo existe la materia en movimiento, sin Dios" },
        { left: "Rousseau", right: "La civilización corrompe; desconfía del progreso ilustrado" },
      ],
      explain: "Los cinco ejes de la Ilustración francesa: el combate irónico de Voltaire, la ciencia política de Montesquieu, el proyecto colectivo de la Enciclopedia, su extremo en el materialismo ateo, y la fractura interna que anticipa Rousseau.",
    },
    {
      type: "info",
      title: "El legado francés",
      body: "Hacia 1772, con la Enciclopedia terminada, la Ilustración francesa ya fijó su repertorio: la ironía como arma crítica, la separación de poderes como programa político, el saber organizado como proyecto colectivo y el materialismo como horizonte extremo de la razón. Ese repertorio se difunde por toda Europa, incluida Alemania, donde va a encontrar un clima intelectual distinto: menos cortesano, más universitario y más religioso.",
    },
    {
      type: "info",
      continues: true,
      title: "El legado francés",
      body: "Ese contraste no debe leerse como una jerarquía entre versiones «mejores» y «peores» de un mismo proyecto, sino como tres respuestas distintas a contextos políticos y religiosos distintos. Lo que Inglaterra resuelve con reforma gradual y Francia con confrontación abierta, Alemania va a intentar resolverlo con una reflexión más paciente sobre qué es, en rigor, ilustrarse —la pregunta con la que empieza la próxima clase, la de la Aufklärung y Mendelssohn.",
    },
  ],
};
