export default {
  num: 21,
  transcript: 21,
  title: "Marx: el último hegeliano",
  source: "",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Karl Marx** (1818–1883) nace en Tréveris, en el Rin prusiano, en una familia judía asimilada con una larga línea de rabinos por las dos ramas. Su padre se convirtió al protestantismo para poder ejercer de abogado. Estudió derecho y luego filosofía en Berlín, donde entró en el círculo de los jóvenes hegelianos, y se doctoró con una tesis sobre Demócrito y Epicuro.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Cerrada la carrera académica por sus posiciones políticas, se dedicó al periodismo y fue expulsado sucesivamente de Alemania, Francia y Bélgica hasta instalarse en Londres en 1849, donde vivió el resto de su vida. Trabajó durante décadas en la sala de lectura del Museo Británico, en la pobreza y con mala salud.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En 1844, en París, conoce a **Friedrich Engels** (1820–1895), y a partir de ese encuentro producen juntos buena parte de la obra. Marx vive casi siempre de la ayuda económica de Engels, cuya familia poseía fábricas textiles en Manchester: el teórico de la explotación fabril se sostuvo con las ganancias de una fábrica.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Su obra se divide en dos momentos que conviene distinguir. Los Manuscritos económico-filosóficos, escritos en 1844 y publicados recién en 1932, y La ideología alemana (1846) pertenecen a un Marx joven, filosófico y humanista. El capital (1867) es el Marx maduro, que ya no argumenta como filósofo sino como economista.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Entre esos dos extremos está el Manifiesto del Partido Comunista (1848), que no es ninguna de las dos cosas y es el texto que lo hizo célebre. Vale tener presente que la obra que más circuló durante un siglo es un panfleto de treinta páginas escrito por encargo, y que buena parte del Marx filosófico se leyó recién después de 1932.",
    },
    {
      type: "quiz",
      question: "¿Por qué conviene distinguir dos momentos en la obra de Marx?",
      options: ["Porque cambió de posición política tras 1848", "Porque el Marx filosófico se publicó recién en 1932", "Porque Engels reescribió sus primeros textos", "Porque abandonó el alemán por el inglés en Londres"],
      answer: 1,
      explain: "Los Manuscritos de 1844 salieron a la luz casi noventa años después. Durante un siglo, el Marx que circuló fue el del Manifiesto y El capital, y el vocabulario filosófico de la alienación se leyó recién en el siglo XX.",
    },
    {
      type: "info",
      title: "Lo que toma de Hegel",
      body: "Marx llega a la filosofía casi cincuenta años después de Hegel y toma de él el punto de partida más amplio: **todo es relacional**. Nada es lo que es por sí mismo, sino por el lugar que ocupa en un conjunto de relaciones. Un individuo, una institución o una idea sólo se entienden dentro de la totalidad en la que funcionan.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que toma de Hegel",
      body: "De ahí hereda también la desconfianza hacia la **reificación**: convertir en cosa fija y natural algo que sólo existe como relación histórica. Hegel la usaba contra las categorías de la metafísica; Marx la va a usar contra las categorías que la economía política de su tiempo daba por evidentes, empezando por el capital mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que toma de Hegel",
      body: "Y retiene, sobre todo, la centralidad de la historia y su movimiento por antagonismo. El motor no es la buena voluntad ni la acumulación de conocimiento: es la contradicción que una forma social lleva adentro y que la empuja hacia otra. La dialéctica, incluido el paso de cantidad a calidad, queda intacta.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que toma de Hegel",
      body: "Lo que rechaza es el sujeto de ese proceso. Para Hegel la historia es el despliegue del Espíritu, y las condiciones materiales son su manifestación. Marx invierte la relación: lo primero es cómo los hombres producen su vida, y las ideas, el derecho, la religión y la filosofía vienen después. Es el gesto que él mismo describió como poner a Hegel patas para arriba.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que toma de Hegel",
      body: "No es invertir el sentido de la historia sino cambiarle la base. En el prefacio a la Contribución a la crítica de la economía política (1859) resume la operación con el nombre que iba a quedar: **materialismo histórico**. Y aclara que la mistificación que la dialéctica sufre en manos de Hegel no impide en absoluto que él haya sido el primero en exponer su movimiento general.",
    },
    {
      type: "quiz",
      question: "¿Qué significa «poner a Hegel patas para arriba»?",
      options: ["Invertir el sentido en que avanza la historia", "Cambiarle la base sin tocar el movimiento", "Reemplazar la dialéctica por el método empírico", "Negar que la historia tenga una dirección propia"],
      answer: 1,
      explain: "La dialéctica, la totalidad y el movimiento por contradicción quedan intactos. Lo que cambia es qué está primero: para Hegel el Espíritu y sus manifestaciones materiales, para Marx cómo los hombres producen su vida y, después, las ideas.",
    },
    {
      type: "info",
      title: "De la aldea a la fábrica",
      body: "El factor decisivo del mundo moderno es, para Marx, la **industrialización**, y no es casual que lo vea así alguien que trabajó en Alemania, París, Bruselas y sobre todo en la Inglaterra que la estaba inventando. Es el hecho que ninguna filosofía anterior había tenido delante.",
    },
    {
      type: "info",
      continues: true,
      title: "De la aldea a la fábrica",
      body: "El mundo anterior era el **feudalismo**: descentralizado, agrario, con una nobleza que hereda tierra y un campesinado atado a ella. Las posiciones eran fijas y estaban justificadas por un orden divino, y la producción se organizaba en unidades pequeñas que apenas excedían la subsistencia.",
    },
    {
      type: "info",
      continues: true,
      title: "De la aldea a la fábrica",
      body: "La tecnología es lo que hace posible el vuelco. Permite construir fábricas y producir a una escala y una velocidad que ningún artesanado podía alcanzar, concentra población en ciudades y crea dos clases nuevas: una **burguesía** que posee los medios de producción y un **proletariado** que sólo posee su fuerza de trabajo y debe venderla.",
    },
    {
      type: "info",
      continues: true,
      title: "De la aldea a la fábrica",
      body: "Con la fábrica cambia además la relación con el tiempo y el espacio. Quien trabajaba la tierra seguía el ritmo de las estaciones y de la luz; quien entra a la fábrica obedece al reloj y a la máquina. El trabajo deja de ser una actividad con forma propia y se convierte en una cantidad de horas que se compra y se vende.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al mundo feudal o al industrial?",
      groups: ["Feudalismo", "Industrialización"],
      items: [
        { text: "Posiciones fijas justificadas por un orden divino", group: 0 },
        { text: "Producción agraria y descentralizada", group: 0 },
        { text: "El ritmo de las estaciones y de la luz", group: 0 },
        { text: "Dos clases definidas por los medios de producción", group: 1 },
        { text: "Concentración de población en ciudades", group: 1 },
        { text: "El trabajo como horas que se compran y se venden", group: 1 },
      ],
      explain: "La tecnología es lo que hace posible el vuelco: permite una escala que ningún artesanado alcanzaba, y con ella aparecen una burguesía que posee los medios de producción y un proletariado que sólo posee su fuerza de trabajo.",
    },
    {
      type: "info",
      title: "La alienación",
      body: "Los Manuscritos de 1844 describen esa condición con el concepto de **alienación** —Entfremdung, extrañamiento— en cuatro registros que se implican entre sí. El trabajador está alienado respecto del producto de su trabajo, que no le pertenece y se le enfrenta como algo ajeno y hostil.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación",
      body: "Está alienado respecto de la actividad misma, porque no elige qué hacer ni cómo, y el trabajo se le vuelve un medio para sobrevivir en vez de un fin. Está alienado respecto de los otros hombres, convertidos en competidores. Y está alienado respecto de lo que Marx llama su **ser genérico**.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación",
      body: "Ésa es la forma más filosófica y la que viene directamente de Feuerbach. Lo propio de la especie humana, para Marx, es producir libremente y de manera universal: no según la necesidad inmediata, como el animal, sino dando forma a la materia según cualquier medida, incluidas las leyes de la belleza.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación",
      body: "El trabajo fabril, reducido a la repetición de un gesto mínimo, cancela exactamente esa capacidad. La actividad que debería ser la expresión más alta de lo humano se convierte en aquello que lo rebaja, y el hombre se siente libre sólo en sus funciones animales —comer, dormir, procrear— y animal en su función propiamente humana.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación",
      body: "Este vocabulario, filosófico y casi existencial, es el sello del Marx joven, todavía heredero del humanismo de Feuerbach. La operación es la misma que Feuerbach había hecho con la religión: allí el hombre proyectaba su esencia en un Dios ajeno, acá la proyecta en un producto y un capital que se le vuelven en contra.",
    },
    {
      type: "short",
      question: "¿Cómo llama Marx a la condición del trabajador separado de su producto, su actividad y su especie?",
      answers: ["alienación", "Entfremdung", "extrañamiento"],
      explain: "Cuatro registros que se implican: respecto del producto, de la actividad, de los otros hombres y del ser genérico. Esta última es la más filosófica, y viene directamente de Feuerbach.",
    },
    {
      type: "info",
      title: "El Manifiesto",
      body: "El Manifiesto, publicado en febrero de 1848 —en vísperas de la primavera de los pueblos, el año de revoluciones que sacudió media Europa—, abre con una frase calculada: un fantasma recorre Europa, el fantasma del comunismo. La elección del vocabulario es deliberada.",
    },
    {
      type: "quiz",
      question: "¿En qué consiste la alienación respecto del ser genérico?",
      options: ["En perder el vínculo con la comunidad de origen", "En que el trabajo cancela la capacidad de dar forma libre", "En no poder heredar un oficio a los propios hijos", "En dejar de reconocerse en la clase a la que se pertenece"],
      answer: 1,
      explain: "Lo propio de la especie es producir libremente y según cualquier medida, incluidas las leyes de la belleza. El gesto fabril repetido cancela eso: el hombre se siente libre en sus funciones animales y animal en su función propiamente humana.",
    },
    {
      type: "info",
      continues: true,
      title: "El Manifiesto",
      body: "Un fantasma del pasado regresaría desde algo que ya ocurrió y se conoce. Éste viene del futuro: es la anticipación de algo que todavía no pasó y que ya produce miedo. El texto es a la vez teoría de la historia, programa político y profecía, y no distingue nunca entre lo que sucederá y lo que debería suceder.",
    },
    {
      type: "info",
      continues: true,
      title: "El Manifiesto",
      body: "Su tesis inicial es que la historia de toda sociedad hasta hoy es la historia de la **lucha de clases**. La relación entre opresores y oprimidos cambia de forma —amo y esclavo, señor y siervo, burgués y proletario— pero no de estructura, y es lo que explica el paso de una época a la siguiente.",
    },
    {
      type: "info",
      continues: true,
      title: "El Manifiesto",
      body: "A partir de acá, **clase** se vuelve la pregunta identitaria decisiva. No la nación, no la religión, no la familia, sino el lugar que uno ocupa en las relaciones de producción. Es un desplazamiento enorme respecto del siglo anterior, y explica buena parte de los conflictos políticos del siglo siguiente.",
    },
    {
      type: "info",
      continues: true,
      title: "El Manifiesto",
      body: "El Manifiesto le reconoce a la burguesía un papel revolucionario y hasta lo celebra: disolvió las jerarquías heredadas, revolucionó permanentemente los medios de producción y creó un mercado mundial. Todo lo sólido se desvanece en el aire, escribe, y todo lo sagrado es profanado. Pero al hacerlo produjo, ante todo, a sus propios sepultureros.",
    },
    {
      type: "info",
      title: "Valor, plusvalía y fetichismo",
      body: "El capital traduce el mismo diagnóstico a otro registro: ya no el de la filosofía humanista sino el de la crítica sistemática de la economía política. Marx retoma de la economía clásica, y de Ricardo en particular, la tesis de que el valor de una mercancía se mide por el tiempo de trabajo socialmente necesario para producirla.",
    },
    {
      type: "quiz",
      question: "¿Por qué el Manifiesto elige la palabra «fantasma»?",
      options: ["Porque el comunismo aún no tenía partido propio", "Porque anuncia algo del futuro y no del pasado", "Porque sus autores debían escribir en la clandestinidad", "Porque la burguesía negaba que el proletariado existiera"],
      answer: 1,
      explain: "Un fantasma del pasado vuelve desde algo que ya ocurrió y se conoce. Éste viene del futuro: es la anticipación de algo que todavía no pasó y que ya produce miedo. El texto no distingue nunca entre lo que sucederá y lo que debería suceder.",
    },
    {
      type: "info",
      continues: true,
      title: "Valor, plusvalía y fetichismo",
      body: "Y le agrega el paso que la economía clásica no había dado. La fuerza de trabajo es una mercancía peculiar, porque su uso produce más valor del que ella misma cuesta. El obrero cobra lo necesario para reproducirse, y en la jornada produce un valor equivalente a ese salario mucho antes de que el turno termine.",
    },
    {
      type: "info",
      continues: true,
      title: "Valor, plusvalía y fetichismo",
      body: "Todo lo que produce después es **plusvalía**, y queda para el capitalista. No hay engaño ni robo en el sentido corriente: el intercambio se hace a su valor y el contrato se cumple. La explotación no es una anomalía del sistema sino su funcionamiento normal, y eso es lo que la vuelve difícil de ver y difícil de reformar.",
    },
    {
      type: "info",
      continues: true,
      title: "Valor, plusvalía y fetichismo",
      body: "De ahí el **fetichismo de la mercancía**. En el mercado, las cosas parecen relacionarse entre sí por sus propias fuerzas —el precio sube, el mercado castiga, el valor se recupera— y las relaciones entre personas aparecen bajo la forma de relaciones entre cosas. Es la reificación hegeliana convertida en análisis económico.",
    },
    {
      type: "quiz",
      question: "¿Qué le reconoce el Manifiesto a la burguesía?",
      options: ["Haber sido una clase revolucionaria", "Haber ampliado los derechos políticos", "Haber terminado con la miseria del campo", "Haber unificado a Europa bajo una ley común"],
      answer: 0,
      explain: "Disolvió las jerarquías heredadas, revolucionó permanentemente la producción y creó un mercado mundial: todo lo sólido se desvanece en el aire. Pero al hacerlo produjo, ante todo, a sus propios sepultureros.",
    },
    {
      type: "info",
      continues: true,
      title: "Valor, plusvalía y fetichismo",
      body: "Entre el Marx de 1844 y el de El capital hay, para algunos intérpretes, una ruptura de fondo. **Louis Althusser** sostuvo que existe un corte epistemológico: el primero todavía habla de una esencia humana alienada, el segundo abandona esa antropología y analiza estructuras sin sujeto. Otros ven una sola línea con dos vocabularios.",
    },
    {
      type: "info",
      title: "Ideología, base y superestructura",
      body: "La ideología alemana aporta la pieza que falta. Su tesis es que las ideas dominantes de cada época son las ideas de la clase dominante: no porque alguien mienta deliberadamente, sino porque quien controla la producción material controla también los medios de producción intelectual.",
    },
    {
      type: "info",
      continues: true,
      title: "Ideología, base y superestructura",
      body: "Marx y Engels comparan el efecto de la **ideología** con el de una cámara oscura, el dispositivo óptico que proyecta la imagen invertida. La conciencia no refleja la vida real: la refleja al revés, presentando como natural y eterno lo que es histórico, y como interés general lo que es interés de una parte.",
    },
    {
      type: "short",
      question: "¿Cómo llama Marx al valor que el obrero produce por encima de su salario?",
      answers: ["plusvalía", "plusvalor"],
      explain: "La fuerza de trabajo es una mercancía peculiar: su uso produce más valor del que ella cuesta. No hay engaño, el contrato se cumple y el intercambio se hace a su valor. La explotación no es una anomalía del sistema sino su funcionamiento normal.",
    },
    {
      type: "info",
      continues: true,
      title: "Ideología, base y superestructura",
      body: "De ahí el par que organiza el materialismo histórico: la **base**, es decir la estructura económica —quién posee los medios de producción y en qué relaciones entra la gente para producir—, y la **superestructura**: el derecho, el Estado, la religión, la moral, el arte y la filosofía, que se levantan sobre ella.",
    },
    {
      type: "quiz",
      question: "¿Qué describe el fetichismo de la mercancía?",
      options: ["El deseo de acumular objetos por encima de lo útil", "Que las relaciones entre personas parecen relaciones entre cosas", "La creencia de que el dinero tiene un valor intrínseco", "La sustitución del valor de uso por el de cambio"],
      answer: 1,
      explain: "En el mercado las cosas parecen relacionarse por sus propias fuerzas: el precio sube, el mercado castiga, el valor se recupera. Es la reificación hegeliana convertida en análisis económico.",
    },
    {
      type: "info",
      continues: true,
      title: "Ideología, base y superestructura",
      body: "La base determina la conciencia, y no al revés. La consecuencia antropológica es fuerte: la naturaleza humana deja de ser fija y se vuelve **situacional**, moldeada por la posición que se ocupa. No hay un hombre en general del que se puedan deducir derechos o deberes, hay hombres situados en relaciones de producción determinadas.",
    },
    {
      type: "info",
      continues: true,
      title: "Ideología, base y superestructura",
      body: "Conviene marcar cuánto de esto es Hegel sin Espíritu. La totalidad relacional, el movimiento por contradicción, la conciencia que llega tarde y no se comprende a sí misma, el sentido que se realiza a espaldas de los agentes: todo está en Hegel. Lo que cambió es qué ocupa el lugar del sujeto de la historia.",
    },
    {
      type: "info",
      title: "Determinismo y el problema calvinista",
      body: "Ahí operan a la vez el determinismo y la totalidad heredados. El proletariado es la clase destinada a conducir la revolución porque su posición en la estructura la produce necesariamente, y la caída de la burguesía y la victoria del proletariado son igualmente inevitables.",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo y el problema calvinista",
      body: "Pero el Manifiesto cierra llamando a la acción: los comunistas declaran abiertamente que sus fines sólo pueden alcanzarse derrocando por la violencia todo el orden social existente. Y ahí aparece una tensión que el texto nunca resuelve. Si el resultado está asegurado por la estructura, ¿para qué militar?",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo y el problema calvinista",
      body: "Es un problema estructuralmente idéntico al del **calvinismo**. Si la salvación está predestinada, ¿por qué llevar una vida virtuosa? La respuesta calvinista fue que la conducta no causa la salvación pero es su signo. La respuesta marxista tendrá que ser alguna variante de eso, y ninguna versión resultó del todo estable.",
    },
    {
      type: "quiz",
      question: "¿Qué sostiene la teoría de la ideología?",
      options: ["Que las clases dominantes mienten deliberadamente", "Que quien controla la producción controla las ideas", "Que toda filosofía es un reflejo fiel de su época", "Que las ideas no tienen ningún efecto sobre la historia"],
      answer: 1,
      explain: "No hace falta que nadie mienta. La conciencia funciona como una cámara oscura: proyecta la imagen invertida, y presenta como natural y eterno lo que es histórico, y como interés general lo que es interés de una parte.",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo y el problema calvinista",
      body: "De esa grieta va a salir buena parte de la historia política del siglo siguiente. Si la revolución no llega sola, alguien tiene que apurarla; y si hay que apurarla, hace falta una organización que sepa antes que la clase lo que la clase necesita. Ese es el problema que hereda Lenin, y no es el único que quedó abierto.",
    },
    {
      type: "info",
      title: "Lo que cierra y lo que abre",
      body: "Con Marx termina este curso, y termina donde tenía que terminar. Empezó en 1517 con Lutero reclamando el derecho de cada creyente a interpretar por sí mismo, y llega a alguien que sostiene que lo que uno cree depende del lugar que ocupa en la producción. Entre las dos cosas está toda la modernidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que cierra y lo que abre",
      body: "Marx es el último gran sistema en el sentido moderno: pretende explicar la totalidad, tiene una dirección, promete una reconciliación final y hace de la razón el instrumento para alcanzarla. Es hegeliano hasta en la forma de negar a Hegel, y por eso pertenece a esta historia y no a la siguiente.",
    },
    {
      type: "quiz",
      question: "¿En qué se parece el determinismo marxista al problema calvinista?",
      options: ["En que ambos prometen una salvación colectiva", "En que el resultado asegurado vuelve rara la militancia", "En que los dos exigen una conversión personal previa", "En que ninguno admite excepciones individuales"],
      answer: 1,
      explain: "Si la salvación está predestinada, ¿por qué llevar una vida virtuosa? La respuesta calvinista fue que la conducta no la causa pero es su signo. Ninguna versión marxista de esa respuesta resultó del todo estable, y de esa grieta sale el problema que hereda Lenin.",
    },
    {
      type: "match",
      question: "Uní cada concepto con lo que nombra",
      pairs: [
        { left: "Plusvalía", right: "El valor producido por encima del salario" },
        { left: "Alienación", right: "El trabajo que se vuelve contra quien lo hace" },
        { left: "Ideología", right: "Las ideas de la clase que domina la producción" },
        { left: "Base", right: "Quién posee los medios y en qué relaciones se produce" },
        { left: "Fetichismo", right: "Las relaciones sociales bajo forma de cosas" },
      ],
      explain: "Todo el sistema es hegeliano sin Espíritu: la totalidad relacional, el movimiento por contradicción y el sentido que se realiza a espaldas de los agentes. Lo que cambió es qué ocupa el lugar del sujeto de la historia.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que cierra y lo que abre",
      body: "Lo que viene después es otra cosa. Alguien que no le va a discutir a Marx la economía ni a Hegel la dialéctica, sino que va a preguntar por qué habría que querer la verdad, de dónde salieron los valores que damos por buenos y qué queda cuando se descubre que nadie los puso ahí. Ese es el punto donde empieza el otro curso.",
    },
  ],
};
