export default {
  num: 3,
  transcript: 3,
  title: "Descartes: la duda y Dios como garante",
  source: "",
  feed: [
    {
      type: "info",
      title: "Dios con una función nueva",
      body: "Las clases anteriores mostraron dos transformaciones del pensamiento occidental en el siglo XVII: la nueva función de la conciencia individual en el plano religioso y político, y la nueva representación matemática de la naturaleza. Esta clase examina una tercera transformación, tan decisiva como las anteriores: la que se produce en la idea misma de Dios.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios con una función nueva",
      body: "Aunque Dios fue objeto de la filosofía desde la Antigüedad, la filosofía moderna le asigna una función nueva, que para algunos autores del período pasa a ser casi exclusiva: garantizar el conocimiento racional. Se estudia esa función en textos de **René Descartes** (1596–1650), sobre todo en sus Meditaciones metafísicas (1641).",
    },
    {
      type: "info",
      title: "El problema: por qué la razón necesita una garantía",
      body: "Los físicos del siglo XVII, partidarios de aplicar la geometría a la física, se presentaban como platónicos modernos: Galileo sostenía que para leer el libro de la naturaleza hacía falta conocer el idioma geométrico en que está escrito, y Descartes se negaba a aceptar en física principios que no fueran aceptados en matemática.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema: por qué la razón necesita una garantía",
      body: "El platonismo antiguo y el moderno coinciden en considerar la matemática como condición y modelo del conocimiento filosófico. Pero ahí termina la semejanza: la novedad moderna consiste en advertir que el conocimiento racional, incluida la matemática, requiere de una fundamentación ulterior que Platón nunca creyó necesaria.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema: por qué la razón necesita una garantía",
      body: "En los diálogos platónicos, la opinión (dóxa) y la ciencia (epistéme) son dos grados de conocimiento bien distinguidos: la primera es particular, contingente y dependiente de los sentidos, y por eso falible; la segunda es universal, necesaria, puramente racional y, por tanto, infalible. En ese marco no hay lugar para dudar de la validez del conocimiento racional ni para buscarle un garante.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema: por qué la razón necesita una garantía",
      body: "Esa duda y esa búsqueda son una novedad introducida por el racionalismo moderno que inaugura Descartes. Su actitud es la misma que caracteriza a los primeros filósofos modernos en general: desprenderse de las enseñanzas de la tradición para fundar, desde cero, una nueva ciencia.",
    },
    {
      type: "quiz",
      question: "La novedad del racionalismo moderno frente al de Platón es…",
      options: [
        "poner en duda la validez de la razón misma",
        "sostener que sólo los sentidos engañan",
        "negar que la matemática sea modelo de saber",
        "afirmar que la opinión supera a la ciencia",
      ],
      answer: 0,
      explain: "Para Platón, la ciencia (epistéme) es infalible por definición y no necesita garante. Descartes introduce algo nuevo: sospechar que incluso el conocimiento racional podría no ser confiable, y busca fundamentarlo con una garantía ulterior.",
    },
    {
      type: "info",
      title: "El relato cartesiano de la duda",
      body: "Tanto en el Discurso del método (1637) como en las Meditaciones metafísicas (1641), obra central de esta clase, Descartes explica las razones que lo llevaron a una crítica radical de la filosofía y las ciencias de su tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "El relato cartesiano de la duda",
      body: "En el Discurso relata en tono autobiográfico que fue criado en el estudio de las letras con la promesa de que estas darían \"un conocimiento claro y seguro de todo lo que es útil para la vida\" (Discurso, I). Esa promesa lo llevó a estudiar con entusiasmo durante años.",
    },
    {
      type: "info",
      continues: true,
      title: "El relato cartesiano de la duda",
      body: "Al terminar sus estudios, sin embargo, descubre que esa promesa no se había cumplido: lo aprendido le parece un cúmulo de errores e incertidumbres transmitido de generación en generación. Al modo del Sócrates platónico, Descartes relata así el descubrimiento de su propia ignorancia y la sospecha de la ignorancia ajena.",
    },
    {
      type: "info",
      continues: true,
      title: "El relato cartesiano de la duda",
      body: "Antes de emprender la crítica de sus opiniones, Descartes se prepara durante años: elabora las reglas de su método y las pone a prueba en problemas científicos concretos, y formula además una \"moral provisional\" que le permita orientarse en la vida práctica mientras dura la investigación.",
    },
    {
      type: "quiz",
      question: "La \"moral provisional\" de Descartes sirve para…",
      options: [
        "orientar la vida práctica mientras dura la duda",
        "reemplazar definitivamente a la ética tradicional",
        "demostrar la existencia de Dios",
        "fundamentar las leyes de la física",
      ],
      answer: 0,
      explain: "Mientras somete todas sus opiniones a duda, Descartes necesita reglas provisionales para actuar en la vida cotidiana sin quedar paralizado; esas reglas no pretenden validez definitiva, sólo orientar mientras dura la investigación.",
    },
    {
      type: "info",
      continues: true,
      title: "El relato cartesiano de la duda",
      body: "Como las opiniones adquiridas a lo largo de la vida son demasiadas para examinarlas una por una, Descartes no examina las opiniones mismas, sino sus fuentes: los cinco sentidos y la razón. Si logra poner en duda esas dos facultades, habrá puesto en duda indirectamente todo lo que se apoya en ellas.",
    },
    {
      type: "info",
      continues: true,
      title: "El relato cartesiano de la duda",
      body: "Para despejar el camino, propone entonces una regla metódica que en la vida corriente no tendría sentido: considerar provisionalmente falsa toda opinión sobre la que pueda caber la más mínima duda. Esta es la **duda metódica**, un recurso excepcional al servicio de encontrar un primer principio indudable.",
    },
    {
      type: "info",
      title: "Los cuatro argumentos de la duda",
      body: "La duda metódica se reduce a cuatro argumentos: dos ponen en cuestión el conocimiento sensible, y dos el conocimiento racional. El primero ya aparece en Platón: los sentidos engañan, como cuando un remo introducido en el agua se ve quebrado, y no conviene confiar en un mensajero que ya nos engañó una vez.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "El segundo argumento es el de los sueños: a veces resulta imposible distinguir si estamos percibiendo la realidad o soñando que la percibimos, porque muchos sueños vienen acompañados de la misma sensación de realidad que la vigilia. Con este argumento, Descartes pone en cuestión la existencia misma del mundo físico exterior, incluido el propio cuerpo.",
    },
    {
      type: "quiz",
      question: "El argumento del sueño pone en duda, sobre todo…",
      options: [
        "la existencia del mundo físico exterior",
        "la verdad de las proposiciones matemáticas",
        "la existencia de Dios",
        "la validez del silogismo aristotélico",
      ],
      answer: 0,
      explain: "Si no podemos distinguir con certeza la vigilia del sueño, no podemos estar seguros de nada referente al mundo exterior, incluido el propio cuerpo. Las verdades matemáticas, en cambio, siguen siendo ciertas incluso soñando.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "Los dos primeros argumentos no afectan, sin embargo, a los conocimientos racionales: \"aunque esté despierto o duerma, dos y tres juntos formarán siempre el número cinco, y el cuadrado jamás tendrá más de cuatro lados\" (Meditaciones, I, §7). Hacen falta otros argumentos para dudar también de la aritmética y la geometría.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "El tercer argumento observa que la experiencia de cometer errores de cálculo, propios o ajenos, puede llevarnos a desconfiar de nuestros razonamientos matemáticos. Pero esos razonamientos parten de axiomas que parecen evidentes por sí mismos, así que hace falta un argumento más radical para ponerlos en duda también a ellos.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "Ese cuarto argumento, el más radical de todos, es la hipótesis del genio maligno: quizás exista un ser muy poderoso y engañador que emplea todo su poder en hacerme errar sin que yo me dé cuenta. Con él la duda alcanza su punto máximo y se vuelve hiperbólica: ya nada escapa a la sospecha, ni siquiera lo que nos parece más evidente.",
    },
    {
      type: "quiz",
      question: "La hipótesis del genio maligno es más radical que las anteriores porque…",
      options: [
        "pone en duda hasta las verdades matemáticas",
        "sólo afecta a los conocimientos sensibles",
        "demuestra que Dios no existe",
        "se apoya en la experiencia de los sueños",
      ],
      answer: 0,
      explain: "Los dos primeros argumentos no tocaban la aritmética ni la geometría. El genio maligno, en cambio, alcanza incluso a esas verdades: podría hacernos sentir evidente algo falso, como que el cuadrado tiene cuatro lados.",
    },
    {
      type: "classify",
      question: "¿Cada argumento de la duda ataca el conocimiento sensible o el racional?",
      groups: ["Conocimiento sensible", "Conocimiento racional"],
      items: [
        { text: "Los sentidos engañan: el remo que se ve quebrado", group: 0 },
        { text: "No puedo distinguir la vigilia del sueño", group: 0 },
        { text: "A veces me equivoco en un cálculo", group: 1 },
        { text: "Un genio maligno podría engañarme hasta en la aritmética", group: 1 },
      ],
      explain: "Los dos primeros argumentos —engaño de los sentidos y sueño— sólo alcanzan al mundo exterior. Los dos últimos —error de cálculo y genio maligno— son los que ponen en duda, por primera vez, la aritmética y la geometría.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "Afirmaciones como \"el cuadrado tiene cuatro lados\" o \"el todo es mayor que la parte\" nos parecen ciertas e indudables. Pero la pregunta decisiva es si nos lo parecen porque son verdaderas, o porque un genio maligno nos hace sentir esa falsa seguridad. Mientras no se refute esa hipótesis, no hay manera de saberlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "Antes de introducir esta hipótesis, Descartes ya la había anticipado con la idea de un Dios todopoderoso que quisiera que el sujeto se equivocara siempre. Negar la existencia de ese Dios no resuelve nada, advierte, porque el problema puede formularse igual sin él.",
    },
    {
      type: "info",
      continues: true,
      title: "Los cuatro argumentos de la duda",
      body: "Cuanto menos poderoso sea el origen de mi ser —el destino, el azar, una cadena de causas naturales—, \"tanto más probable será que yo sea tan imperfecto que me engañe siempre\" (Meditaciones, I, §9). Ni siquiera un origen puramente natural o azaroso garantiza, por sí solo, que la razón funcione bien.",
    },
    {
      type: "info",
      title: "El cogito como límite del engaño",
      body: "El poder del genio maligno, sin embargo, tiene límites. En primer lugar, la duda es puramente teorética: alcanza solo a las opiniones, no a las decisiones ni a las acciones, que Descartes sigue orientando mientras dura la investigación por las reglas de su moral provisional. En segundo lugar, frente al genio cuento con mi libre albedrío: si no afirmo ni niego nada, el genio no tiene sobre qué actuar.",
    },
    {
      type: "info",
      continues: true,
      title: "El cogito como límite del engaño",
      body: "El límite decisivo, sin embargo, aparece en la Segunda Meditación: \"hay un engañador [...] muy poderoso y muy astuto que emplea toda su habilidad para engañarme siempre. No hay, pues, ninguna duda de que existo si me engaña [...] esta proposición: yo soy, yo existo, es necesariamente verdadera siempre que la pronuncio\" (Meditaciones, II, §4).",
    },
    {
      type: "info",
      continues: true,
      title: "El cogito como límite del engaño",
      body: "Esta certeza no puede ser producto del engaño del genio, porque mi existencia es una condición presupuesta por la propia hipótesis del engaño: para que algo sea engañado, tiene que existir. De ahí que \"yo soy, yo existo\" resulte necesariamente verdadero cada vez que se piensa. Este es el célebre **cogito** cartesiano.",
    },
    {
      type: "quiz",
      question: "El cogito resiste al genio maligno porque…",
      options: [
        "mi existencia es condición de que pueda ser engañado",
        "el genio maligno no existe en realidad",
        "pensar es siempre verdadero, nunca hay error",
        "Dios impide que el genio actúe sobre el pensamiento",
      ],
      answer: 0,
      explain: "Para que algo sea engañado, tiene que existir. Aunque casi todos mis juicios particulares puedan ser falsos, el hecho de que los piense —y por tanto que yo exista— es necesariamente verdadero cada vez que lo pienso.",
    },
    {
      type: "info",
      continues: true,
      title: "El cogito como límite del engaño",
      body: "Descartes determina de inmediato qué es ese yo que existe: una cosa que piensa, una **res cogitans**, una sustancia pensante finita —finita porque a veces se equivoca—. Aunque casi todos los juicios de esa sustancia puedan ser falsos bajo el poder del genio, el acto mismo de pensarlos existe con necesidad, y con él las proposiciones que lo expresan: pienso, luego existo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Descartes a la certeza indudable de la propia existencia como sujeto pensante?",
      answers: ["cogito", "el cogito"],
      explain: "\u00abYo soy, yo existo\u00bb es necesariamente verdadero cada vez que lo pienso, incluso bajo la hipótesis del genio maligno. Es el primer principio indudable sobre el que Descartes funda el resto del conocimiento.",
    },
    {
      type: "quiz",
      question: "Tras el cogito, Descartes determina que el yo que existe es…",
      options: [
        "una sustancia pensante, finita porque se equivoca",
        "una sustancia extensa idéntica al cuerpo",
        "una sustancia infinita e inmutable",
        "una mera ilusión del genio maligno",
      ],
      answer: 0,
      explain: "Descartes llama a esta sustancia pensante res cogitans, y la distingue de la res extensa, la sustancia material. Es finita porque, a veces, se equivoca en sus juicios particulares.",
    },
    {
      type: "info",
      continues: true,
      title: "El cogito como límite del engaño",
      body: "Esta certeza del cogito es el cimiento sobre el que Descartes se propone edificar el resto del conocimiento humano, incluidas las ciencias naturales. Pero es apenas el primer paso: queda por fundamentar la validez del conocimiento racional matemático, todavía puesto en cuestión por la hipótesis del genio maligno.",
    },
    {
      type: "info",
      title: "Dios como garante del conocimiento",
      body: "En la Tercera Meditación, Descartes advierte que la razón para dudar de la validez del conocimiento racional es, en el fondo, \"más bien ligera\": una hipótesis, según la cual quizás exista un ser poderoso que nos engaña. Para eliminarla por completo hace falta examinar si existe un Dios y, si existe, si puede ser engañador (Meditaciones, III, §5).",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "Descartes responde afirmativamente a la primera pregunta y niega la segunda: existe un Dios, y ese Dios, por definición, no puede ser engañador, porque el engaño es una imperfección incompatible con la perfección infinita de Dios. Con esta doble respuesta, la **veracidad divina** se convierte en garante último del conocimiento racional: lo que percibimos clara y distintamente ha de ser verdadero, porque de lo contrario Dios sería un engañador.",
    },
    {
      type: "quiz",
      question: "La veracidad divina garantiza que…",
      options: [
        "las ideas claras y distintas son verdaderas",
        "todos los sentidos son siempre confiables",
        "el genio maligno no puede existir",
        "Descartes nunca puede volver a equivocarse",
      ],
      answer: 0,
      explain: "Una vez demostrado que Dios existe y no engaña, lo que percibimos con claridad y distinción tiene que ser verdadero: de lo contrario, Dios sería cómplice de nuestro engaño, lo cual contradice su perfección.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "Esta demostración, sin embargo, enfrenta una objeción de método que la tradición bautizó como el **círculo cartesiano**: Descartes usa la claridad y distinción de las ideas para demostrar que Dios existe y no engaña, pero al mismo tiempo necesita la garantía divina para confiar en que lo claro y distinto es verdadero. Parece, entonces, que la prueba presupone lo que debía demostrar.",
    },
    {
      type: "quiz",
      question: "La objeción del círculo cartesiano señala que Descartes…",
      options: [
        "prueba a Dios con lo que Dios debía garantizar",
        "nunca llega a demostrar que Dios existe",
        "confunde el cogito con la existencia de Dios",
        "acepta sin prueba la existencia del genio maligno",
      ],
      answer: 0,
      explain: "Descartes usa la claridad y distinción de sus ideas para demostrar la existencia y veracidad de Dios, pero necesita esa misma garantía divina para confiar en que lo claro y distinto es verdadero: la prueba parece presuponer su propia conclusión.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "Descartes intenta salir de este círculo distinguiendo dos momentos: mientras pienso con claridad y distinción una demostración, no puedo dudar de ella, aunque no recuerde todavía si Dios existe; el problema surge solo cuando, pasado el momento de evidencia actual, quiero confiar en lo que recuerdo haber demostrado. Ahí es donde la garantía divina se vuelve necesaria, para sostener en el tiempo lo que la evidencia presente ya aseguraba por sí misma.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "Una vez asegurada la veracidad divina, Descartes dedica la Cuarta Meditación al origen del error: si Dios existe y no engaña, ¿de dónde vienen entonces nuestros errores? La respuesta cartesiana apela al desajuste entre una voluntad infinita, que puede afirmar o negar sin límites, y un entendimiento finito, que percibe con claridad solo un número limitado de cosas. El error surge cuando la voluntad se precipita a juzgar sobre lo que el entendimiento todavía no ve con claridad.",
    },
    {
      type: "quiz",
      question: "Si Dios no engaña, el origen del error humano está en…",
      options: [
        "una voluntad que se precipita a juzgar",
        "un entendimiento que siempre es infinito",
        "la intervención directa del genio maligno",
        "los sentidos, que engañan sin excepción",
      ],
      answer: 0,
      explain: "La voluntad humana es infinita y puede afirmar o negar sin límite, pero el entendimiento es finito y sólo percibe con claridad un número limitado de cosas. El error surge cuando la voluntad se adelanta a juzgar sobre lo que el entendimiento todavía no ve con claridad.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "Las Meditaciones Quinta y Sexta completan el edificio: la primera examina la esencia de los cuerpos, es decir, la extensión geométrica que la física matemática presupone; la segunda demuestra la existencia del mundo material, distinguiéndolo por fin, y con garantías, del sueño con el que se había abierto la duda metódica.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "Con la garantía divina establecida, Descartes puede resolver la duda metódica planteada al comienzo: los cuerpos existen y el conocimiento matemático de la naturaleza, elaborado con el método geométrico, resulta válido.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "La **res extensa**, la sustancia extensa que compone el mundo físico, queda así fundada racionalmente, junto con las **ideas innatas** —como la idea misma de Dios— que la razón encuentra en sí misma sin haberlas tomado de la experiencia sensible.",
    },
    {
      type: "match",
      question: "Uní cada concepto cartesiano con su función",
      pairs: [
        { left: "Duda metódica", right: "Buscar un primer principio indudable" },
        { left: "Genio maligno", right: "El argumento más radical de la duda" },
        { left: "Cogito", right: "La primera certeza: pienso, luego existo" },
        { left: "Veracidad divina", right: "Garantiza lo percibido con claridad" },
        { left: "Círculo cartesiano", right: "La objeción de método a esa garantía" },
      ],
      explain: "El recorrido cartesiano va de la duda más radical a la certeza mínima del cogito, y de ahí a la garantía divina que permite recuperar el resto del conocimiento, no sin la objeción de método que esa garantía enfrenta.",
    },
    {
      type: "info",
      continues: true,
      title: "Dios como garante del conocimiento",
      body: "De esta manera, la metafísica cartesiana cumple la función que Galileo no le había asignado a la física: fundamentar filosóficamente la certeza de que el universo, escrito en lenguaje matemático, puede ser conocido por una razón humana finita pero no engañada por su creador. La duda que abrió la clase termina resuelta en la certeza de un mundo racionalmente accesible.",
    },
  ],
};
