export default {
  num: 7,
  transcript: 7,
  title: "El racionalismo: ideas innatas y Leibniz",
  source: "",
  feed: [
    {
      type: "info",
      title: "Dos tradiciones, un diálogo",
      body: "Entre 1637 y 1780, la historia de la filosofía moderna suele describirse mediante dos etiquetas: **racionalismo continental** y **empirismo inglés**. Conviene usarlas con cuidado: no hay dos escuelas cerradas, sino un diálogo prolongado y complejo entre filósofos que comparten problemas y se responden unos a otros a lo largo de siglo y medio.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos tradiciones, un diálogo",
      body: "Con esa salvedad, ambas tradiciones pueden contraponerse esquemáticamente atendiendo a cuatro puntos: qué fuente del conocimiento privilegian, cómo conciben al sujeto que conoce, qué modelo de conocimiento toman como ideal, y qué problemas filosóficos les interesan. Esta clase se ocupa del **racionalismo**: su confianza en la razón, su tesis de las ideas innatas, y su versión más radical, la de Gottfried Wilhelm Leibniz (1646–1716).",
    },
    {
      type: "info",
      continues: true,
      title: "Dos tradiciones, un diálogo",
      body: "Los racionalistas sostienen que la razón, por sí sola, es capaz de conocer la realidad tal cual es, porque esa realidad está racionalmente estructurada. El conocimiento proveniente de los sentidos no les resulta confiable: algunos, como Leibniz, llegan a identificar las percepciones sensoriales con conceptos meramente confusos, inferiores en claridad al conocimiento racional puro.",
    },
    {
      type: "quiz",
      question: "Para los racionalistas, la razón puede conocer la realidad porque…",
      options: [
        "la realidad misma es racional",
        "los sentidos son más confiables que la razón",
        "toda verdad depende de la experiencia sensorial",
        "no existen verdades necesarias ni universales",
      ],
      answer: 0,
      explain: "Los racionalistas sostienen que la razón, por sí sola, puede conocer la realidad tal cual es, porque ésta se encuentra racionalmente estructurada; el conocimiento sensorial, en cambio, les resulta confuso y poco confiable.",
    },
    {
      type: "info",
      title: "Las ideas innatas",
      body: "El privilegio que el racionalismo otorga a la razón no depende sólo de su funcionamiento riguroso, sino sobre todo de una tesis de fondo: la razón sería portadora de **ideas innatas**, es decir, de conocimientos no adquiridos mediante la experiencia sensorial, presentes en la mente desde el nacimiento o incluso desde antes de él.",
    },
    {
      type: "info",
      continues: true,
      title: "Las ideas innatas",
      body: "Descartes había clasificado sus pensamientos en las Meditaciones metafísicas (1641) distinguiendo un tipo de ideas que «me parece que han nacido conmigo». La idea de Dios, sostiene allí, «ha nacido y ha sido producida conmigo a partir del momento en que he sido creado» (Meditaciones, III, § 37). También las ideas matemáticas, para Descartes, son innatas: no las aprendemos de la experiencia, las encontramos ya en nuestra propia razón cuando la examinamos con atención.",
    },
    {
      type: "info",
      continues: true,
      title: "Las ideas innatas",
      body: "Esta tesis del innatismo hace del racionalismo moderno un heredero de la doctrina platónica, según la cual conocer es en el fondo recordar: el alma racional habría contemplado directamente el mundo de las Ideas antes de nacer, y el aprendizaje consistiría en traer de vuelta a la conciencia lo que ya sabía. La razón, en ambos casos, no depende del mundo exterior para tener contenido propio.",
    },
    {
      type: "info",
      continues: true,
      title: "Las ideas innatas",
      body: "Frente al innatismo, los empiristas ingleses —que se estudiarán en la próxima clase— sostendrán que todo conocimiento sobre la realidad se adquiere a través de los sentidos, y que la mente antes de la experiencia es semejante a una tabla rasa, un papel en blanco donde los datos sensoriales pueden «imprimirse». Esa discusión sobre el origen de las ideas es el eje que separa a las dos tradiciones durante todo el período.",
    },
    {
      type: "info",
      continues: true,
      title: "Las ideas innatas",
      body: "El racionalismo continental de los siglos XVII y XVIII tiene en Descartes (1596–1650), Spinoza (1632–1677) y Leibniz (1646–1716) a sus tres figuras principales. Los tres coinciden en el privilegio de la razón sobre los sentidos y en la aspiración a un conocimiento more geometrico, pero difieren radicalmente en sus conclusiones: Descartes conserva la distinción entre sustancia pensante y sustancia extensa, Spinoza la disuelve en una sustancia única, y Leibniz la multiplica en una infinidad de sustancias simples.",
    },
    {
      type: "quiz",
      question: "Según el innatismo racionalista, el conocimiento no adquirido por los sentidos está…",
      options: [
        "presente en la mente desde antes de la experiencia",
        "completamente ausente hasta que la experiencia lo aporta",
        "reservado sólo a Dios, nunca a los seres humanos",
        "limitado a los conceptos matemáticos avanzados",
      ],
      answer: 0,
      explain: "Las ideas innatas son, para el racionalismo, conocimientos no adquiridos por los sentidos, presentes en la mente desde el nacimiento o incluso antes: Descartes las atribuye a Dios, al yo y a la matemática; Leibniz, a todo el conocimiento.",
    },
    {
      type: "info",
      title: "La matemática como modelo del conocimiento",
      body: "Los racionalistas encuentran en la matemática el modelo ideal de conocimiento, uno que debía generalizarse tanto en la nueva ciencia de la naturaleza como en la filosofía misma. Esto supone considerar a la matemática de un modo peculiar: haciendo abstracción de sus objetos particulares —números, figuras— y tratándola como una ciencia general de relaciones y proporciones, una **matemática universal** capaz de unificar todas las ciencias.",
    },
    {
      type: "info",
      continues: true,
      title: "La matemática como modelo del conocimiento",
      body: "La ventaja que los racionalistas encuentran en el conocimiento matemático es que se trata de un conocimiento **a priori**: universal, necesario e independiente de la experiencia. Una verdad matemática no depende de que la comprobemos empíricamente una y otra vez; se sigue con necesidad lógica de sus propias definiciones y axiomas, y por eso vale siempre y en todo lugar.",
    },
    {
      type: "info",
      continues: true,
      title: "La matemática como modelo del conocimiento",
      body: "El racionalismo tiende, en consecuencia, a abordar los problemas filosóficos desde un punto de vista metafísico: la existencia de Dios, la inmortalidad del alma o la estructura de las sustancias naturales se tratan con el mismo tipo de certeza que se busca en una demostración geométrica. Esta ambición de tratar la metafísica more geometrico, ya vista en Spinoza, encuentra en Leibniz a otro de sus grandes representantes, aunque con resultados muy distintos.",
    },
    {
      type: "quiz",
      question: "¿Por qué los racionalistas ven en la matemática el modelo ideal de conocimiento?",
      options: [
        "porque no depende de la experiencia",
        "porque describe con precisión los objetos sensibles",
        "porque sus verdades cambian según el contexto",
        "porque se basa en la observación repetida de casos",
      ],
      answer: 0,
      explain: "El conocimiento matemático es a priori: universal, necesario e independiente de la experiencia. Por eso los racionalistas lo toman como modelo a generalizar tanto en la física como en la filosofía misma.",
    },
    {
      type: "info",
      title: "Leibniz y la radicalización del innatismo",
      body: "Gottfried Wilhelm Leibniz (1646–1716) es el racionalista que lleva el innatismo hasta su forma más extrema: mientras Descartes admitía innatas sólo algunas ideas —Dios, el yo, las verdades matemáticas—, Leibniz sostiene que absolutamente todas nuestras ideas son innatas y ninguna es adquirida desde fuera. Lo que llamamos experiencia no introduce contenido nuevo en la mente: sólo ocasiona que despleguemos lo que ya estaba en ella de manera confusa.",
    },
    {
      type: "info",
      continues: true,
      title: "Leibniz y la radicalización del innatismo",
      body: "Esta tesis se apoya en la pieza central de la metafísica de Leibniz: la **mónada**, expuesta de forma sistemática en la Monadología (1714). Las mónadas son sustancias simples, sin partes, que constituyen los elementos últimos de toda la realidad: no tienen extensión ni pueden dividirse, y por eso mismo tampoco pueden generarse ni destruirse por procesos naturales, sino sólo por creación o aniquilación divina.",
    },
    {
      type: "short",
      question: "¿Cómo llama Leibniz a las sustancias simples, sin partes, que son los elementos últimos de la realidad?",
      answers: ["mónada", "mónadas", "monada", "monadas"],
      explain: "Las mónadas son sustancias simples y sin extensión: no pueden dividirse ni generarse por procesos naturales. Cada una representa el universo entero desde su propio punto de vista, con mayor o menor claridad.",
    },
    {
      type: "info",
      continues: true,
      title: "Leibniz y la radicalización del innatismo",
      body: "Cada mónada es como un punto de vista único sobre la totalidad del universo: contiene en sí, de manera más o menos clara, la representación de todo lo que existe, pasado, presente y futuro. Por eso ninguna mónada necesita recibir información del exterior para conocer: todo lo que puede llegar a saber ya está contenido en su propia naturaleza, esperando desplegarse. Las mónadas, dice Leibniz, «no tienen ventanas» por las que algo pueda entrar o salir.",
    },
    {
      type: "info",
      continues: true,
      title: "Leibniz y la radicalización del innatismo",
      body: "Las mónadas se diferencian entre sí por el grado de claridad con que representan el universo entero. Las más simples apenas perciben de manera confusa, casi como en un sueño sin conciencia de sí; el alma humana, en cambio, alcanza la **apercepción**, es decir la conciencia reflexiva de sus propias percepciones, y Dios, la mónada suprema, representa la totalidad con claridad absoluta y sin ninguna confusión. El universo entero es así una jerarquía continua de perspectivas sobre lo mismo.",
    },
    {
      type: "quiz",
      question: "Que las mónadas «no tengan ventanas» significa que…",
      options: [
        "no reciben ni envían nada al exterior",
        "no pueden pensar ni tener percepciones",
        "están encerradas físicamente unas con otras",
        "sólo existen mientras Dios las observa",
      ],
      answer: 0,
      explain: "Cada mónada contiene ya en su propia naturaleza todo lo que puede llegar a saber, como un punto de vista sobre el universo entero; por eso no necesita —ni puede— recibir ni transmitir nada a través de una ventana.",
    },
    {
      type: "info",
      continues: true,
      title: "Leibniz y la radicalización del innatismo",
      body: "Esta doctrina resuelve, a su manera, el problema de la individualidad: si cada mónada refleja el universo entero desde su propio punto de vista, no hay dos mónadas exactamente iguales, porque no hay dos puntos de vista idénticos sobre la misma totalidad. Leibniz llama a este principio el de los **indiscernibles**: dos sustancias que no se distinguieran por ninguna propiedad interna serían, en realidad, una sola.",
    },
    {
      type: "info",
      title: "Armonía preestablecida y principio de razón suficiente",
      body: "Si las mónadas no interactúan entre sí, ¿por qué el mundo se presenta como un conjunto ordenado y coherente, donde los cuerpos parecen afectarse mutuamente? Leibniz responde con la doctrina de la **armonía preestablecida**: Dios ha ajustado de antemano, desde la creación, el desarrollo interno de cada mónada para que coincida perfectamente con el de todas las demás, como relojes sincronizados que dan la hora exacta sin comunicarse entre sí.",
    },
    {
      type: "info",
      continues: true,
      title: "Armonía preestablecida y principio de razón suficiente",
      body: "Esta armonía explica también la relación entre el alma y el cuerpo, un problema que había resultado especialmente difícil para Descartes. Alma y cuerpo no interactúan causalmente entre sí, como parecía suponer el dualismo cartesiano; simplemente sus desarrollos internos, programados por Dios desde el origen, corren paralelos y coordinados, produciendo la ilusión de una interacción directa.",
    },
    {
      type: "quiz",
      question: "La armonía preestablecida explica la relación entre alma y cuerpo sin que…",
      options: [
        "haya interacción causal entre ellos",
        "el alma tenga ninguna influencia sobre la conducta",
        "Dios haya intervenido nunca en su desarrollo",
        "existan sustancias simples que los compongan",
      ],
      answer: 0,
      explain: "Para Leibniz, alma y cuerpo no interactúan causalmente, como suponía el dualismo cartesiano: sus desarrollos internos fueron ajustados por Dios desde el origen para coincidir siempre, como relojes sincronizados.",
    },
    {
      type: "info",
      continues: true,
      title: "Armonía preestablecida y principio de razón suficiente",
      body: "Detrás de la armonía preestablecida está el **principio de razón suficiente**, otro pilar de la filosofía de Leibniz: nada ocurre sin que haya una razón suficiente para que sea así y no de otro modo. Este principio completa al principio de no contradicción, propio de las verdades necesarias de la razón, y se aplica en cambio a las verdades de hecho, contingentes, que dependen de la elección divina entre infinitos mundos posibles.",
    },
    {
      type: "info",
      continues: true,
      title: "Armonía preestablecida y principio de razón suficiente",
      body: "Leibniz distingue así dos tipos de verdades. Las **verdades de razón** son necesarias: su opuesto es contradictorio, como ocurre con las verdades matemáticas, y se conocen mediante el análisis de las ideas que las componen. Las **verdades de hecho** son contingentes: su opuesto es posible, no contradictorio, y dependen en última instancia de por qué Dios eligió crear este mundo y no otro entre los infinitos que su entendimiento contempla.",
    },
    {
      type: "quiz",
      question: "El principio de razón suficiente se aplica, sobre todo, a…",
      options: [
        "las verdades de hecho, contingentes",
        "las verdades de razón, necesarias",
        "los axiomas indemostrables de la geometría",
        "las percepciones confusas de los sentidos",
      ],
      answer: 0,
      explain: "Las verdades de razón se rigen por el principio de no contradicción; las de hecho, contingentes, necesitan además una razón suficiente que explique por qué son así y no de otro modo, ligada a la elección divina.",
    },
    {
      type: "info",
      title: "La teodicea y el mejor de los mundos posibles",
      body: "El principio de razón suficiente conduce a Leibniz a su **teodicea**: la pregunta por cómo conciliar la existencia de un Dios todopoderoso y bondadoso con la presencia del mal en el mundo. Leibniz sostiene que Dios, antes de crear, contempla en su entendimiento infinitos mundos posibles, cada uno regido por sus propias leyes y consecuencias.",
    },
    {
      type: "info",
      continues: true,
      title: "La teodicea y el mejor de los mundos posibles",
      body: "Como Dios es perfecto, elige necesariamente crear aquel mundo que, sopesados todos los factores, resulta el mejor posible: no el que carece por completo de mal, algo lógicamente imposible dado que las criaturas son finitas e imperfectas, sino aquel en que la proporción entre bien y mal, entre orden y limitación, es óptima. De ahí la fórmula, tantas veces discutida, de que vivimos en «el mejor de los mundos posibles».",
    },
    {
      type: "info",
      continues: true,
      title: "La teodicea y el mejor de los mundos posibles",
      body: "Esta respuesta no pretende negar el sufrimiento humano, sino mostrar que es compatible con la sabiduría y la bondad divinas: un mal menor puede ser la condición necesaria de un bien mayor, del mismo modo en que una sombra en una pintura puede realzar, por contraste, la luz de otras partes del cuadro. La teodicea de Leibniz busca así preservar racionalmente la fe en un orden providencial, en pleno siglo del mecanicismo y la matemática universal.",
    },
    {
      type: "info",
      continues: true,
      title: "La teodicea y el mejor de los mundos posibles",
      body: "Leibniz distingue, además, tres tipos de mal dentro de su teodicea: el mal metafísico, que es simplemente la imperfección inevitable de toda criatura finita frente a la perfección infinita de Dios; el mal físico, es decir el sufrimiento y el dolor; y el mal moral, el pecado que resulta del uso indebido de la libertad. Sólo el primero es estrictamente necesario; los otros dos son consecuencias que Dios permite porque impedirlos exigiría sacrificar un bien mayor en el conjunto del mundo.",
    },
    {
      type: "quiz",
      question: "Para Leibniz, Dios elige crear «el mejor de los mundos posibles» porque…",
      options: [
        "tiene la mejor proporción entre bien y mal",
        "es el único mundo lógicamente posible",
        "es un mundo completamente libre de todo mal",
        "es el mundo que más se parece al anterior",
      ],
      answer: 0,
      explain: "Un mundo sin ningún mal es imposible porque las criaturas son finitas e imperfectas; Dios elige, entre infinitos mundos posibles, aquel con la mejor proporción entre bien y mal que su sabiduría puede lograr.",
    },
    {
      type: "info",
      title: "El innatismo de Leibniz frente a la tabla rasa",
      body: "La radicalización leibniziana del innatismo no significa que neguemos tener experiencias sensoriales, sino que niega que esas experiencias sean la fuente última de nuestras ideas. Lo que la experiencia hace, para Leibniz, es actuar como ocasión: despierta y hace explícitas verdades que la mente ya poseía de manera virtual, del mismo modo en que las vetas de una piedra de mármol predisponen, sin determinarlo por completo, el resultado que un escultor puede extraer de ella.",
    },
    {
      type: "info",
      continues: true,
      title: "El innatismo de Leibniz frente a la tabla rasa",
      body: "Esta imagen del mármol veteado —que Leibniz opone explícitamente a la del papel en blanco de los empiristas— resume la diferencia de fondo entre las dos tradiciones: para el racionalismo, la mente aporta activamente una estructura previa a cualquier experiencia; para el empirismo, esa estructura misma tendría que explicarse a partir de lo recibido por los sentidos. La discusión sobre cuál de las dos imágenes describe mejor a la mente humana atraviesa toda la filosofía moderna y llega, en el siglo XVIII, hasta la síntesis kantiana entre sensibilidad y entendimiento.",
    },
    {
      type: "classify",
      question: "¿Cada tesis sobre las ideas innatas es de Descartes o de Leibniz?",
      groups: ["Descartes", "Leibniz"],
      items: [
        { text: "La idea de Dios «ha nacido y ha sido producida» con nosotros", group: 0 },
        { text: "Sólo unas pocas ideas —Dios, el yo, la matemática— son innatas", group: 0 },
        { text: "Todas nuestras ideas son innatas, ninguna viene de fuera", group: 1 },
        { text: "La experiencia sólo hace explícito lo que ya sabíamos", group: 1 },
      ],
      explain: "Descartes admite innatas sólo algunas ideas privilegiadas; Leibniz radicaliza la tesis y sostiene que absolutamente todo el conocimiento humano es innato, y que la experiencia sólo ocasiona que lo desplieguen.",
    },
    {
      type: "info",
      title: "El lugar de Leibniz entre racionalismo y ciencia nueva",
      body: "Leibniz no rechaza la física mecanicista de su época: fue, junto con Newton, uno de los creadores del cálculo infinitesimal, y contribuyó decisivamente a la física matemática del siglo XVII. Pero, a diferencia de Spinoza, reserva un lugar para la **teleología**: mientras la física estudia sólo causas eficientes, la metafísica de las sustancias simples —las mónadas— puede seguir preguntando por los fines últimos de las cosas.",
    },
    {
      type: "info",
      continues: true,
      title: "El lugar de Leibniz entre racionalismo y ciencia nueva",
      body: "Esta convivencia entre mecanicismo físico y finalismo metafísico es posible porque, para Leibniz, ambos niveles de explicación son complementarios y no rivales: el mundo puede describirse en el lenguaje de las causas eficientes, propio de la física, y al mismo tiempo entenderse, en un nivel más profundo, como la realización del mejor orden posible elegido racionalmente por Dios.",
    },
    {
      type: "quiz",
      question: "A diferencia de Spinoza, Leibniz conserva un lugar para la teleología porque…",
      options: [
        "la reserva para la metafísica",
        "niega por completo que exista el mecanicismo",
        "cree que toda causa eficiente es también un fin",
        "rechaza el cálculo infinitesimal de Newton",
      ],
      answer: 0,
      explain: "Leibniz acepta que la física sólo estudia causas eficientes, pero reserva la pregunta por los fines para la metafísica de las sustancias simples: ambos niveles de explicación son, para él, complementarios.",
    },
    {
      type: "info",
      continues: true,
      title: "El lugar de Leibniz entre racionalismo y ciencia nueva",
      body: "Esta convivencia le permite a Leibniz sostener, contra el determinismo estricto de Spinoza, una noción de libertad divina y humana compatible con la razón suficiente: Dios elige libremente entre mundos posibles, aunque su elección esté guiada necesariamente por la sabiduría; los seres humanos actúan libremente cuando sus decisiones se siguen de motivos internos, aunque esos motivos tengan siempre, también ellos, una razón suficiente que los explica.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada término con su idea",
      pairs: [
        { left: "Mónada", right: "Sustancia simple que representa el universo entero" },
        { left: "Armonía preestablecida", right: "Dios coordina de antemano el desarrollo de cada mónada" },
        { left: "Principio de razón suficiente", right: "Nada ocurre sin una razón que lo explique" },
        { left: "Teodicea", right: "Concilia un Dios bueno con la existencia del mal" },
      ],
      explain: "Cuatro piezas de la metafísica de Leibniz: la mónada como elemento último, la armonía preestablecida que las coordina sin interacción, el principio de razón suficiente que rige lo contingente, y la teodicea que responde al problema del mal.",
    },
    {
      type: "info",
      continues: true,
      title: "El lugar de Leibniz entre racionalismo y ciencia nueva",
      body: "Con Leibniz, el racionalismo alcanza su forma más ambiciosa y sistemática: una metafísica capaz de explicar, a partir de unos pocos principios necesarios —la mónada, la armonía preestablecida, la razón suficiente—, tanto la estructura última de la realidad como la razón de ser del mal y el sufrimiento. Esa misma ambición será el blanco de las críticas empiristas que ocuparán la próxima clase.",
    },
  ],
};
