export default {
  num: 5,
  transcript: 5,
  title: "El individuo en la filosofía política moderna",
  source: "",
  feed: [
    {
      type: "info",
      title: "Del sacerdocio universal al individuo político",
      body: "La Reforma luterana había atribuido a la conciencia individual la función de juez competente en materia de verdad religiosa: cada creyente, y no sólo el Papa, podía interpretar las Escrituras. Esa novedad tiene consecuencias también en la filosofía política: desde el siglo XVII, el **individuo** se vuelve la pieza central para explicar la legitimidad de las instituciones políticas.",
    },
    {
      type: "info",
      continues: true,
      title: "Del sacerdocio universal al individuo político",
      body: "Los teóricos modernos del derecho natural —llamados **contractualistas**, entre ellos Thomas Hobbes (1588–1679), John Locke (1632–1704) y Jean-Jacques Rousseau (1712–1778)— intentan derivar racionalmente los derechos de los soberanos a partir de un pacto entre individuos libres e iguales que habitan, hipotéticamente, un **estado de naturaleza**. Frente a la tradición política antigua, la novedad es que los individuos se hacen ciudadanos por su propio consentimiento, no por naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "Del sacerdocio universal al individuo político",
      body: "Para entender el alcance de este cambio conviene contrastar, de manera esquemática, dos modelos de pensar la política: uno antiguo o **premoderno**, y otro **moderno**. Se trata de una simplificación —hay excepciones en ambos sentidos—, pero permite ver con claridad qué función nueva le asigna la modernidad al individuo.",
    },
    {
      type: "info",
      continues: true,
      title: "Del sacerdocio universal al individuo político",
      body: "Esta distinción de dos modelos no pretende clasificar exhaustivamente a todos los autores anteriores o posteriores al siglo XVII: hay textos premodernos que no encajan del todo en el modelo clásico, y textos modernos que defienden tesis contrarias al modelo moderno.",
    },
    {
      type: "info",
      continues: true,
      title: "Del sacerdocio universal al individuo político",
      body: "Sirve, sin embargo, para mostrar algo más profundo que una simple diferencia de doctrinas políticas: dos concepciones distintas del mundo y del ser humano, de las que las teorías políticas de cada época son, en buena medida, una consecuencia.",
    },
    {
      type: "quiz",
      question: "La novedad del contractualismo moderno es que los individuos se hacen ciudadanos por…",
      options: [
        "su propio consentimiento, mediante un pacto",
        "su lugar de nacimiento dentro de la polis",
        "la revelación divina transmitida por el Papa",
        "su pertenencia natural a una clase social",
      ],
      answer: 0,
      explain: "Los contractualistas —Hobbes, Locke, Rousseau— derivan la legitimidad política de un pacto entre individuos libres e iguales que consienten obedecer, y no de un lugar asignado de antemano por la naturaleza o la tradición.",
    },
    {
      type: "info",
      title: "El modelo clásico: el animal político",
      body: "El modelo clásico supone que el ser humano es por naturaleza un **animal político**, un animal cuya naturaleza lo destina a vivir en una polis. La forma más plena de socialidad sólo se alcanza si la vida de ese animal se rige por las leyes de un Estado, y la función de cada persona dentro de la comunidad está determinada de antemano por la naturaleza de las cosas.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo clásico: el animal político",
      body: "Esta concepción piensa la comunidad política como un organismo viviente, y a quienes participan de ella como sus «miembros», en un sentido casi biológico. El organismo se mantiene vivo mientras cada miembro —esclavos, artesanos, comerciantes, mujeres, ciudadanos— cumple la función que le corresponde según su naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo clásico: el animal político",
      body: "Se derrumba, en cambio, cuando alguno pretende ocupar el lugar de otro y abandona la función que le fue asignada. En este modelo, el concepto de un individuo independiente, con derechos propios anteriores a la comunidad, todavía no existe.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo clásico: el animal político",
      body: "La comparación con un organismo vivo no es meramente decorativa: implica que la posición de cada persona dentro de la comunidad —qué tareas realiza, qué derechos tiene, a quién obedece— no es algo que esa persona elija, sino algo que la naturaleza de las cosas le asigna de antemano, tal como un órgano del cuerpo no elige su función, sino que la cumple porque forma parte de un todo mayor que lo antecede y lo excede.",
    },
    {
      type: "quiz",
      question: "En el modelo clásico, ¿qué significa que cada persona sea un «miembro» de la polis?",
      options: [
        "que cumple la función que su naturaleza le asigna",
        "que puede elegir libremente su lugar en la sociedad",
        "que participa de un pacto entre iguales",
        "que es propietaria de su propio cuerpo",
      ],
      answer: 0,
      explain: "El modelo clásico piensa la comunidad como un organismo: cada «miembro» —esclavo, artesano, ciudadano— cumple la función que la naturaleza de las cosas le asigna, no una que elige; el individuo independiente todavía no existe.",
    },
    {
      type: "info",
      title: "El modelo moderno: el Estado como artefacto",
      body: "Los filósofos modernos, en cambio, sostienen que el Estado es un **artefacto** creado por los individuos para satisfacer racionalmente sus intereses particulares. No es un organismo que crece espontáneamente por la naturaleza gregaria del ser humano, sino el resultado de una técnica: un instrumento libremente construido mediante un acto voluntario de individuos aislados, libres e iguales, que así se transforman en ciudadanos.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo moderno: el Estado como artefacto",
      body: "Los antiguos entendían el Estado como el punto culminante de un crecimiento natural y gradual: de la familia a la aldea, de la aldea a la polis, un desarrollo continuo de la misma naturaleza social. Los modernos, en cambio, ven entre el estado de naturaleza y el Estado civil un corte cualitativo, un salto que sólo puede darse mediante un acto libre de las voluntades individuales: el **contrato**.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo moderno: el Estado como artefacto",
      body: "Para los antiguos no hay diferencia radical entre las leyes que rigen la polis y las que rigen el cosmos: la comunidad política es un microcosmos que refleja el macrocosmos natural. Para los modernos, en cambio, naturaleza y política son dos órdenes distintos —el natural o prepolítico, y el artificial o político— y sólo un pacto entre individuos libres puede fundar el paso de uno a otro.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo moderno: el Estado como artefacto",
      body: "Esta diferencia entre grado y salto cualitativo es decisiva. Si el Estado fuera sólo el estadio más complejo de un desarrollo natural que arranca en la familia, bastaría con dejar que la naturaleza siguiera su curso para que la organización política surgiera por sí sola.",
    },
    {
      type: "info",
      continues: true,
      title: "El modelo moderno: el Estado como artefacto",
      body: "Los modernos niegan justamente eso: para ellos ninguna cantidad de organización prepolítica —familias, aldeas, gremios— genera por acumulación un Estado, porque el Estado exige un acto deliberado y consciente que ningún crecimiento espontáneo puede reemplazar.",
    },
    {
      type: "quiz",
      question: "Para los modernos, el paso del estado de naturaleza al Estado civil es…",
      options: [
        "un salto cualitativo, no un crecimiento gradual",
        "el punto final de un desarrollo natural continuo",
        "un retroceso respecto de la vida en comunidad",
        "una ilusión, porque el Estado siempre existió",
      ],
      answer: 0,
      explain: "Los antiguos ven el Estado como la culminación de un crecimiento natural —familia, aldea, polis—; los modernos ven un corte cualitativo que sólo un acto deliberado, el contrato, puede producir.",
    },
    {
      type: "info",
      title: "Dos metafísicas detrás de dos políticas",
      body: "Estas dos concepciones políticas dependen de dos metafísicas distintas sobre el mundo natural. El modelo premoderno se asienta en una **metafísica de la permanencia**: un ser es tanto más perfecto cuanto menos necesita cambiar o depender de algo externo para realizar su esencia. Un ser perfecto es inmóvil, porque no le falta nada; un ser imperfecto tiende, se mueve, aspira a completarse.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos metafísicas detrás de dos políticas",
      body: "En esta metafísica, la razón —el lógos— es lo más perfecto, porque se satisface contemplándose a sí misma sin depender de objetos externos. Los cuerpos celestes, cuyo movimiento circular repite siempre lo mismo, son los seres naturales más perfectos; cuanto más se aleja algo de esa racionalidad estable, mayor es su imperfección e inestabilidad.",
    },
    {
      type: "quiz",
      question: "Para la metafísica antigua, un ser es tanto más perfecto cuanto…",
      options: [
        "menos necesita cambiar para realizar su esencia",
        "más veloz es su movimiento por el espacio",
        "más depende de otros seres para existir",
        "más se transforma a lo largo del tiempo",
      ],
      answer: 0,
      explain: "En la metafísica de la permanencia, un ser perfecto no necesita cambiar ni depender de nada externo para realizar su esencia; por eso los cuerpos celestes, de movimiento circular constante, son los más perfectos.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos metafísicas detrás de dos políticas",
      body: "El orden político clásico busca reproducir esa estabilidad cósmica: el mejor Estado es el más quieto, el que menos cambia, aquel en que cada miembro cumple sólo la función que su naturaleza le asigna.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos metafísicas detrás de dos políticas",
      body: "El modelo moderno, en cambio, se asienta en una **metafísica del cambio**: lo natural no es la permanencia sino el movimiento continuo de partes independientes. La naturaleza ya no es un orden jerárquico de sustancias perfectas e imperfectas, sino un conjunto de elementos simples e indivisibles que se mueven en un espacio infinito y homogéneo, como los átomos o los cuerpos que estudia la nueva física.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos metafísicas detrás de dos políticas",
      body: "De esta imagen atomista de la naturaleza se sigue la imagen moderna del individuo en el estado de naturaleza: una partícula aislada e independiente que se mueve para maximizar su propio beneficio. Como ya no hay paralelismo entre macrocosmos y microcosmos, las leyes físicas del movimiento no ofrecen ninguna garantía espontánea de orden político: la armonía entre individuos egoístas sólo puede lograrse mediante un pacto deliberado.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos metafísicas detrás de dos políticas",
      body: "Vale la pena notar la simetría entre esta transformación política y la transformación física estudiada en clases anteriores. Así como los físicos del siglo XVII reemplazan el cosmos jerárquico y finito de Aristóteles por un espacio homogéneo e infinito recorrido por cuerpos en movimiento, los filósofos políticos modernos reemplazan la comunidad orgánica y jerárquica de la polis por un conjunto de individuos homogéneos e iguales entre sí, cuyo orden ya no viene dado por la naturaleza sino que debe construirse artificialmente.",
    },
    {
      type: "info",
      continues: true,
      title: "Dos metafísicas detrás de dos políticas",
      body: "Por eso los modernos ya no pueden hacerse ilusiones sobre el origen espontáneo de las instituciones políticas: saben que éstas no se forman ni se conservan por sí solas, sino que existen únicamente porque los seres humanos deciden entrar en un orden artificial mediante un pacto, y se sostienen sólo mientras cumplen las obligaciones asumidas al suscribirlo. El pacto no describe un orden preexistente: lo inaugura y lo fundamenta desde cero.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde a la metafísica antigua o a la moderna?",
      groups: ["Metafísica antigua", "Metafísica moderna"],
      items: [
        { text: "Un ser perfecto es inmóvil y no depende de nada externo", group: 0 },
        { text: "La naturaleza es un movimiento continuo de partes independientes", group: 1 },
        { text: "El cosmos es un orden jerárquico de sustancias", group: 0 },
        { text: "Los individuos son átomos aislados en un espacio homogéneo", group: 1 },
        { text: "La política refleja el orden racional del universo", group: 0 },
        { text: "No hay garantía natural de armonía entre los individuos", group: 1 },
      ],
      explain: "La política clásica se apoya en una metafísica de la permanencia, con un cosmos jerárquico que la polis refleja; la moderna se apoya en una metafísica del cambio, con individuos atómicos cuya armonía sólo puede lograrse por pacto.",
    },
    {
      type: "info",
      title: "Del entendimiento a la voluntad",
      body: "Una clave de la diferencia entre ambos modelos es la facultad humana que cada uno privilegia: el modelo clásico confía en el **entendimiento**, el moderno en la **voluntad**. Para los antiguos existe una verdad objetiva sobre el orden natural, y quien mejor la conoce está autorizado a gobernar: el saber funciona como título de legitimidad política, cuya figura paradigmática es el rey-filósofo de la República de Platón.",
    },
    {
      type: "info",
      continues: true,
      title: "Del entendimiento a la voluntad",
      body: "Dentro de este modelo se supone que hay un saber objetivo sobre el orden natural que revela al mismo tiempo la clave del orden político correcto, y que quien posee ese saber está en condiciones de gobernar la polis: sólo el sabio conoce en qué consiste la justicia, y por eso sólo a él le corresponde establecer el orden estable de la comunidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Del entendimiento a la voluntad",
      body: "Esta confianza en el saber como fuente de autoridad se mantiene, con matices, hasta la Reforma: mientras la cristiandad reconoce la autoridad interpretativa del Papa, hay una verdad garantizada por la revelación y un único intérprete autorizado de ella. El libre examen luterano introduce una pregunta nueva —¿quién decide el verdadero sentido de las Escrituras, el Papa o la conciencia de cada creyente?— que desplaza ese punto de apoyo.",
    },
    {
      type: "info",
      continues: true,
      title: "Del entendimiento a la voluntad",
      body: "Esta pregunta no queda contenida en el terreno religioso: es una de las condiciones de las guerras de religión que asolarán Europa durante más de un siglo, y que sólo cesarán con el establecimiento del Estado moderno como poder capaz de garantizar la paz civil entre súbditos de credos distintos. La necesidad de fundar la obediencia política en algo que no dependa ya de una verdad religiosa compartida es, en ese sentido, uno de los motores históricos del contractualismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Del entendimiento a la voluntad",
      body: "Con ese desplazamiento, la autoridad deja de «descender» desde un lógos inmutable o desde el cielo, y pasa a «ascender» desde la conciencia de cada individuo. Cada conciencia se atribuye a sí misma el derecho de juzgar qué es justo. Los individuos son entonces como átomos preexistentes al orden político: libres e iguales en su derecho a interpretar la verdad, pero incapaces de converger espontáneamente en un orden común.",
    },
    {
      type: "info",
      continues: true,
      title: "Del entendimiento a la voluntad",
      body: "Por eso el modelo moderno desplaza la legitimidad política del entendimiento hacia la **voluntad**: ya no es el saber lo que autoriza a gobernar, sino el consentimiento de quienes se comprometen a obedecer. La autoridad política nace del pacto por el cual las voluntades individuales, libres e iguales, transfieren su derecho a una cabeza común: el Estado, entendido como un artefacto y no como un organismo natural.",
    },
    {
      type: "quiz",
      question: "El libre examen luterano desplaza la autoridad política porque…",
      options: [
        "traslada a cada conciencia el derecho a juzgar la verdad",
        "declara ilegítimos a todos los reyes cristianos",
        "prueba que la razón nunca alcanza la verdad",
        "devuelve al Papa el monopolio de la interpretación",
      ],
      answer: 0,
      explain: "Al preguntar quién interpreta las Escrituras, el libre examen traslada el punto de apoyo de la autoridad desde un intérprete único —el Papa, el lógos— hacia la conciencia de cada individuo, que empieza a fundar por sí misma el orden político.",
    },
    {
      type: "info",
      title: "Hobbes y Locke: dos usos del contrato",
      body: "Hobbes, en el Leviatán (1651), y Locke, en los Dos tratados sobre el gobierno civil (1689), representan dos maneras distintas de aplicar este esquema contractualista, aunque comparten su estructura básica: individuos libres e iguales en un estado de naturaleza, que mediante un pacto instituyen un poder político al que se comprometen a obedecer.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y Locke: dos usos del contrato",
      body: "Ambos parten del **individuo** como unidad última de análisis político, previa e independiente del Estado: no hay comunidad política natural, sino una construcción artificial que resulta de decisiones individuales. Esta prioridad del individuo sobre la comunidad es precisamente lo que separa al modelo moderno del modelo clásico, para el cual la comunidad es anterior y superior a cualquiera de sus miembros.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y Locke: dos usos del contrato",
      body: "A esta forma de pensar el individuo, el politólogo canadiense C. B. Macpherson (1911–1987) la denomina **individualismo posesivo**: la idea de que cada persona es propietaria de su propia persona y de sus capacidades, sin deberle nada a la sociedad por ellas, y que puede por tanto disponer libremente de sí misma —de su fuerza de trabajo, de sus bienes— para pactar con otros en pie de igualdad. Esa imagen del individuo como propietario de sí mismo es, según Macpherson, un supuesto de fondo compartido por Hobbes y Locke, más allá de las diferencias entre sus respectivas teorías del Estado.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y Locke: dos usos del contrato",
      body: "Esta lectura de Macpherson permite entender por qué el contractualismo moderno concibe el estado de naturaleza como un espacio de individuos ya plenamente formados, con capacidades e intereses propios, antes de cualquier vínculo político: la sociedad civil no crea al individuo, como sugería el modelo clásico al pensarlo como miembro de un organismo, sino que el individuo, ya completo, es quien crea la sociedad civil para proteger lo que ya le pertenece.",
    },
    {
      type: "short",
      question: "¿Cómo llama Macpherson a la idea de que cada persona es propietaria de sí misma y de sus capacidades?",
      answers: ["individualismo posesivo"],
      explain: "Macpherson usa esta categoría para describir un supuesto compartido por Hobbes y Locke: cada individuo es dueño de su propia persona y sus capacidades, sin deberle nada a la sociedad, y puede disponer de ellas para pactar con otros.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y Locke: dos usos del contrato",
      body: "Hobbes y Locke difieren, sin embargo, en el diagnóstico sobre ese estado de naturaleza y en el alcance del pacto que lo supera. Para Hobbes, el estado de naturaleza es una guerra de todos contra todos, y el pacto exige transferir casi sin reservas el derecho de cada uno a un soberano absoluto capaz de garantizar la paz. Para Locke, el estado de naturaleza ya incluye ciertos derechos naturales —a la vida, la libertad y la propiedad— que el pacto no crea sino que busca proteger mejor, y que ningún gobierno legítimo puede violar sin perder su autoridad.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencian Hobbes y Locke sobre el estado de naturaleza?",
      options: [
        "Locke ya reconoce derechos naturales que el pacto protege",
        "Hobbes lo describe como un lugar pacífico y ordenado",
        "Locke niega que exista ningún estado de naturaleza",
        "Hobbes sostiene que el pacto es innecesario",
      ],
      answer: 0,
      explain: "Para Hobbes el estado de naturaleza es una guerra de todos contra todos que exige un soberano casi absoluto; para Locke ya hay en él derechos naturales —vida, libertad, propiedad— que el pacto busca proteger, no crear.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada término con su idea",
      pairs: [
        { left: "Hobbes", right: "El estado de naturaleza es una guerra de todos contra todos" },
        { left: "Locke", right: "El pacto protege derechos naturales previos al Estado" },
        { left: "Macpherson", right: "Acuña la categoría de individualismo posesivo" },
        { left: "Individuo", right: "Unidad libre e igual, previa a cualquier vínculo social" },
      ],
      explain: "Hobbes y Locke aplican el mismo esquema contractualista en direcciones distintas; Macpherson muestra el supuesto que ambos comparten: el individuo como propietario de sí mismo, unidad última del análisis político moderno.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y Locke: dos usos del contrato",
      body: "La distinción entre modelo clásico y modelo moderno, con todo, es esquemática: sirve para mostrar una tendencia general de la filosofía política a partir del siglo XVII, no para clasificar rígidamente a cada autor de la época. El propio recorrido de este curso, de Hobbes a Rousseau, mostrará las variantes internas que ese modelo moderno admite sin perder su núcleo: el individuo como fuente última de la legitimidad política.",
    },
  ],
};
