export default {
  num: 17,
  transcript: null,
  title: "Plotino y el neoplatonismo: el Uno",
  source: "",
  feed: [
    {
      type: "info",
      title: "Quinientos años después",
      body: "Entre el escepticismo helenístico de la clase pasada y Plotino pasan casi quinientos años, durante los cuales el platonismo se mezcla cada vez más con ideas estoicas y aristotélicas, en lo que los historiadores llaman «platonismo medio». Plotino (204-270 d. C.), nacido en Egipto, estudia once años en Alejandría con un oscuro maestro, Amonio Sacas, y hacia el final de su vida enseña en Roma.",
    },
    {
      type: "info",
      continues: true,
      title: "Quinientos años después",
      body: "Su discípulo Porfirio recopila esas lecciones en un solo libro, las **Enéadas**, organizado en seis grupos de nueve tratados cada uno, de donde viene el nombre (ennéa significa «nueve» en griego).",
    },
    {
      type: "quiz",
      question: "¿De dónde viene el nombre de las Enéadas, el libro donde Porfirio recopila las lecciones de Plotino?",
      options: [
        "de que están organizadas en seis grupos de nueve tratados",
        "del nombre propio de la ciudad egipcia donde nació Plotino",
        "de que Plotino tardó nueve años exactos en escribirlas",
        "de una diosa griega llamada Ennea, protectora de la filosofía",
      ],
      answer: 0,
      explain: "Ennéa significa «nueve» en griego: Porfirio organiza las lecciones de Plotino en seis grupos de nueve tratados cada uno, y de esa estructura sale el nombre del libro entero.",
    },
    {
      type: "info",
      title: "El Uno: más allá del ser",
      body: "En la cima de todo lo que existe, Plotino ubica al **Uno**, que retoma directamente a la Forma del Bien de la República, de la Clase 6: algo «más allá del ser» mismo, tan simple que ni siquiera se lo puede pensar como una cosa entre otras. Cualquier predicado que se le aplique —bueno, sabio, existente— ya introduce una distinción que el Uno, por definición, no admite.",
    },
    {
      type: "info",
      title: "Del Uno al Alma: la emanación",
      body: "De ese Uno «brotan», en sucesión necesaria, dos niveles más de realidad. Primero el Nous o Intelecto, donde habitan las Formas platónicas ya como una multiplicidad organizada; después el Alma, que hace de puente entre lo inteligible y lo sensible, y que genera y anima el cosmos físico que conocemos. A este proceso Plotino lo llama **emanación**.",
    },
    {
      type: "quiz",
      question: "¿Por qué el Uno de Plotino está «más allá del ser», y no es simplemente el ser más perfecto?",
      options: [
        "porque cualquier predicado que se le aplique ya introduce una distinción",
        "porque, en realidad, Plotino niega por completo que el Uno exista",
        "porque el Uno es idéntico, sin ninguna diferencia, al mundo físico",
        "porque el Uno es sólo una de las muchas Formas platónicas",
      ],
      answer: 0,
      explain: "El Uno retoma a la Forma del Bien de Platón, «más allá del ser»: llamarlo «bueno» o «existente» ya lo distinguiría de otra cosa, y el Uno, por definición, es demasiado simple para admitir ninguna distinción interna.",
    },
    {
      type: "quiz",
      question: "En el sistema de Plotino, ¿qué función cumple el Alma entre las tres hipóstasis?",
      options: [
        "hace de puente entre lo inteligible y lo sensible, y genera el cosmos físico",
        "es superior al Uno mismo, la fuente última de toda la realidad",
        "contiene únicamente las Formas platónicas, sin ninguna otra función",
        "no tiene ninguna relación con el mundo físico que conocemos",
      ],
      answer: 0,
      explain: "El Uno es la fuente; el Nous contiene las Formas ya organizadas; el Alma media entre ese mundo inteligible y el mundo sensible, siendo la responsable directa de generar y animar el cosmos físico.",
    },
    {
      type: "info",
      continues: true,
      title: "Del Uno al Alma: la emanación",
      body: "La emanación no es una decisión, como la del Demiurgo de Platón que elige ordenar el mundo, ni una atracción, como la del Motor Inmóvil de Aristóteles: es un desbordamiento necesario, tan automático como que el sol irradia luz o el fuego irradia calor, sin que la fuente pierda nada de su propia perfección al hacerlo.",
    },
    {
      type: "classify",
      question: "¿Cada principio actúa con voluntad y propósito, o de manera automática y sin voluntad?",
      groups: ["Con voluntad o propósito", "Automático, sin voluntad"],
      items: [
        { text: "El Demiurgo (Platón): ordena la materia con un plan deliberado", group: 0 },
        { text: "El Uno (Plotino): emana por puro desbordamiento necesario", group: 1 },
        { text: "El Dios del Génesis: crea de la nada por su propia voluntad", group: 0 },
        { text: "La emanación: como el sol irradia luz, sin decidirlo", group: 1 },
      ],
      explain: "El Demiurgo y el Dios del Génesis actúan deliberadamente, con un plan o una voluntad. El Uno de Plotino no decide nada: todo brota de él con la misma necesidad automática con la que el sol irradia luz.",
    },
    {
      type: "info",
      title: "El regreso del alma",
      body: "Si todo emana del Uno, la tarea de cada alma individual es la inversa: volver sobre ese mismo camino, purificándose mediante la virtud y la contemplación filosófica, hasta alcanzar, en el mejor de los casos, una unión mística directa con el Uno. Porfirio cuenta en su biografía que el propio Plotino logró esa unión varias veces a lo largo de su vida.",
    },
    {
      type: "quiz",
      question: "Según la biografía escrita por Porfirio, ¿qué logró Plotino varias veces a lo largo de su vida?",
      options: [
        "una unión mística directa con el Uno",
        "la fundación de una segunda escuela filosófica en Egipto",
        "la traducción completa de los diálogos de Platón al latín",
        "un cargo político de alto rango en el imperio romano",
      ],
      answer: 0,
      explain: "Porfirio, su discípulo y biógrafo, sostiene que Plotino alcanzó varias veces en su vida la unión mística con el Uno, la meta final del recorrido de regreso que Plotino le propone al alma purificada.",
    },
    {
      type: "info",
      title: "Sólo se puede decir lo que el Uno no es",
      body: "Como el Uno está más allá de cualquier categoría, no hay ningún lenguaje positivo capaz de describirlo sin traicionarlo: llamarlo «bueno» o «existente» ya lo rebaja a la condición de una cosa entre otras. La única vía que le queda a la filosofía es la **vía negativa**: decir lo que el Uno no es, y dejar que, por descarte, se insinúe algo de lo que sí es, sin nombrarlo del todo.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que describe",
      pairs: [
        { left: "El Uno", right: "Más allá del ser, inefable, la fuente última de todo" },
        { left: "Emanación", right: "Un desbordamiento necesario, no una decisión ni un deseo" },
        { left: "Nous y Alma", right: "Las dos hipóstasis que median entre el Uno y el mundo físico" },
        { left: "Vía negativa", right: "Decir lo que el Uno no es, ya que nombrarlo lo rebajaría" },
      ],
      explain: "Las cuatro piezas arman un solo sistema: una fuente inefable, un proceso necesario que produce el resto de la realidad, dos niveles intermedios, y un método para hablar de lo que en rigor no se puede nombrar.",
    },
    {
      type: "info",
      title: "Lo que sigue",
      body: "Esta vía negativa, y toda la arquitectura del Uno, el Intelecto y el Alma, va a influir profundamente en los primeros filósofos cristianos, que necesitan un lenguaje capaz de hablar de un Dios trascendente sin reducirlo a una cosa más entre las cosas del mundo. Es exactamente el tema de la última clase de este curso.",
    },
  ],
};
