export default {
  num: 2,
  transcript: 2,
  title: "El orden moral antes de la filosofía: de Homero al lógos político",
  source: "",
  feed: [
    {
      type: "info",
      title: "El mundo de Homero: moira y honor",
      body: "Antes de que exista una palabra griega para «filosofía» o para «ética», Homero ya describe un cosmos con un cierto orden. Ese orden se llama **moira**, «destino» o «parte asignada». Cada quien, hasta los propios dioses, tiene su porción fijada, y transgredirla trae consecuencias. No es todavía un orden moral en sentido pleno, sino más bien un orden de límites: cada cosa tiene su lugar, y salirse de él desata el desastre.",
    },
    {
      type: "info",
      continues: true,
      title: "El mundo de Homero: moira y honor",
      body: "La justicia, en Homero, es todavía difusa. Aparece sobre todo como venganza de sangre y como respeto a ciertos deberes sagrados, la hospitalidad (xenía) entre anfitrión y huésped, el juramento dado. Cuando Paris viola la hospitalidad de Menelao y se lleva a Helena, desata la guerra de Troya, y los dioses castigan esa falta por vías personales y familiares, no por un tribunal ni por una ley escrita. Todavía no hay **nómos**.",
    },
    {
      type: "quiz",
      question: "En el mundo de Homero, ¿cómo se castiga la violación de un deber sagrado como la hospitalidad?",
      options: [
        "por vías personales y familiares, no por un tribunal",
        "por un tribunal ateniense que aplica la ley escrita",
        "no se castiga nunca, porque los dioses son indiferentes",
        "por una asamblea de ciudadanos que vota una sentencia",
      ],
      answer: 0,
      explain: "Todavía no existe el nómos. Cuando Paris viola la hospitalidad de Menelao, los dioses castigan la falta por vías personales y familiares —la guerra de Troya misma—, no mediante una institución legal.",
    },
    {
      type: "info",
      title: "Hesíodo: nace Díke",
      body: "Hesíodo, un campesino de Beocia que escribe hacia el 700 a. C., es el primero en hacer explícito lo que en Homero apenas se insinúa. Su poema Los trabajos y los días nace de un conflicto muy concreto: su hermano Perses sobornó a los jueces para quedarse con más de lo que le correspondía de la herencia paterna. Hesíodo no apela a un tribunal, porque no existe todavía, sino a los propios dioses.",
    },
    {
      type: "info",
      continues: true,
      title: "Hesíodo: nace Díke",
      body: "Hesíodo personifica la justicia como **Díke**, hija de Zeus, que se sienta junto a su trono y le informa de cada injusticia humana. Si los jueces de una ciudad dictan sentencias torcidas, Zeus no castiga solamente al culpable: envía hambruna, peste y esterilidad sobre la ciudad entera. La injusticia de unos pocos es, entonces, un asunto cósmico que compromete a toda la comunidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Hesíodo: nace Díke",
      body: "El mismo poema cuenta el mito de las cinco edades: una humanidad que declina desde una Edad de Oro sin trabajo ni vejez hasta la actual Edad de Hierro, la de Hesíodo, marcada por el esfuerzo y la injusticia. A diferencia de los presocráticos que vimos la clase pasada, Hesíodo no busca una causa natural para ese declive. Lo cuenta como un relato, no como una explicación.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue a la justicia de Hesíodo de la de Homero?",
      options: [
        "en Hesíodo, la injusticia de unos pocos castiga a toda la ciudad",
        "en Hesíodo, la justicia depende sólo de un tribunal humano",
        "en Hesíodo, los dioses ya no intervienen en los asuntos humanos",
        "en Hesíodo, cada persona tiene una porción de destino fija",
      ],
      answer: 0,
      explain: "Hesíodo hace explícito lo que Homero apenas insinúa: si los jueces fallan torcido, Zeus castiga a la comunidad entera con hambruna y peste. La injusticia deja de ser un asunto privado.",
    },
    {
      type: "info",
      title: "La tragedia: de la venganza a la ley",
      body: "Un siglo y medio después de Hesíodo, la tragedia ateniense pone en escena la misma pregunta con otra forma: qué pasa cuando alguien se excede de su porción, comete **hybris**, y qué fuerza restaura el equilibrio roto. Esquilo dramatiza ese proceso en su trilogía la Orestíada, la más antigua que se conserva completa, estrenada en Atenas en 458 a. C.",
    },
    {
      type: "info",
      continues: true,
      title: "La tragedia: de la venganza a la ley",
      body: "Agamenón, rey de Argos, vuelve victorioso de Troya y su esposa Clitemnestra lo asesina, en venganza por haber sacrificado a la hija de ambos antes de partir a la guerra. Años después, su hijo Orestes, empujado por el oráculo de Apolo, mata a Clitemnestra para vengar a su padre. Ha cometido matricidio, y las Erinias —diosas antiguas de la venganza de sangre— empiezan a perseguirlo sin descanso.",
    },
    {
      type: "quiz",
      question: "Antes de la intervención de Atenea, ¿qué lógica rige los crímenes de la familia de Agamenón?",
      options: [
        "cada asesinato exige un nuevo asesinato que lo vengue",
        "un tribunal de ciudadanos juzga cada crimen por separado",
        "los dioses perdonan automáticamente cualquier crimen familiar",
        "Zeus castiga a toda la ciudad de Argos con una plaga",
      ],
      answer: 0,
      explain: "Clitemnestra mata a Agamenón para vengar a su hija. Orestes, después, mata a Clitemnestra para vengar a su padre. La venganza de sangre no tiene freno propio: cada muerte exige la siguiente, hasta que Atenea interrumpe el ciclo con un tribunal.",
    },
    {
      type: "info",
      continues: true,
      title: "La tragedia: de la venganza a la ley",
      body: "Atenea resuelve el ciclo de un modo nuevo, en la última obra de la trilogía. Convoca un tribunal de ciudadanos atenienses, el Areópago, para juzgar a Orestes según la ley y no según la costumbre de la sangre. El voto queda empatado, y Atenea misma lo desempata a favor de la absolución.",
    },
    {
      type: "info",
      continues: true,
      title: "La tragedia: de la venganza a la ley",
      body: "Las Erinias aceptan el veredicto y se transforman en Euménides, las «benévolas», protectoras de la nueva ciudad. El mensaje es explícito: de ahora en más, los juicios se resuelven en un tribunal, con jueces y votos, no con matanzas privadas entre familias. Es, en el mito, el nacimiento de la justicia como institución política.",
    },
    {
      type: "quiz",
      question: "¿Qué cambia, según el mito de la Orestíada, cuando Atenea convoca el tribunal del Areópago?",
      options: [
        "la venganza de sangre privada se reemplaza por un juicio legal",
        "los dioses dejan de intervenir para siempre en los asuntos humanos",
        "Orestes es condenado a muerte por el matricidio cometido",
        "las Erinias destruyen la ciudad de Atenas en castigo",
      ],
      answer: 0,
      explain: "El ciclo de venganza familiar no tenía salida, porque cada muerte exigía la siguiente. El tribunal de ciudadanos, con voto y veredicto, reemplaza esa lógica por un juicio según la ley: el nacimiento mítico del nómos como institución.",
    },
    {
      type: "info",
      title: "La physis hereda el vocabulario de la justicia",
      body: "Volvamos a Anaximandro, de la clase anterior. Su único fragmento textual dice que las cosas «se pagan unas a otras penitencia y retribución por su injusticia, conforme al orden del tiempo». No es una metáfora suelta, sino el mismo vocabulario de Hesíodo —díke, retribución— aplicado ahora a un proceso físico, sin dioses de por medio. El orden cósmico sigue siendo un orden de justicia, pero empieza a explicarse solo.",
    },
    {
      type: "info",
      continues: true,
      title: "La physis hereda el vocabulario de la justicia",
      body: "Heráclito da un paso más explícito todavía. Escribe que hay que combatir por el nómos como por la muralla de la ciudad (DK B44), y que toda ley humana se nutre de una única ley divina (DK B114). También advierte que hay que apagar la **hybris** antes que un incendio (DK B43): la misma hybris que destruye a los héroes de la tragedia aparece ahora como un concepto filosófico, aplicable a cualquier ciudadano.",
    },
    {
      type: "quiz",
      question: "¿Qué hace Anaximandro con el vocabulario moral de Hesíodo?",
      options: [
        "lo aplica a un proceso físico, sin que intervengan los dioses",
        "lo rechaza por completo como propio de la mitología",
        "lo reserva únicamente para describir los juicios humanos",
        "lo atribuye en cambio a un dios nuevo, distinto de Zeus",
      ],
      answer: 0,
      explain: "Su fragmento habla de «injusticia» y «retribución» entre los elementos, el mismo vocabulario que usa Hesíodo para Zeus y Díke, pero ahora describe un proceso natural que no necesita intervención divina directa.",
    },
    {
      type: "short",
      question: "¿Cómo llama Heráclito, con una palabra griega, al exceso que hay que apagar «antes que un incendio»?",
      answers: ["hybris", "hibris"],
      explain: "Es el mismo exceso que destruye a los héroes de la tragedia —romper la propia porción, la moira—, convertido ya en un concepto filosófico aplicable a cualquier ciudadano, no sólo a los reyes del mito.",
    },
    {
      type: "info",
      title: "Nómos: la ley que hacen los hombres",
      body: "Con Heráclito llegamos a una palabra nueva, **nómos**: «ley», «costumbre», «convención». A diferencia de díke, un orden que viene dado y que se personifica en una diosa, el nómos es explícitamente algo que las ciudades se dan a sí mismas. Se puede escribir, votar, cambiar, comparar entre una ciudad y otra. La Orestíada ya lo dramatiza; Heráclito lo nombra.",
    },
    {
      type: "short",
      question: "¿Con qué palabra griega nombra Heráclito la ley humana, distinta de la díke divina?",
      answers: ["nomos", "nómos"],
      explain: "A diferencia de díke, un orden dado y personificado en una diosa, el nómos es explícitamente algo que las ciudades se dan a sí mismas: se escribe, se vota y se puede cambiar de una ciudad a otra.",
    },
    {
      type: "info",
      continues: true,
      title: "Nómos: la ley que hacen los hombres",
      body: "Esa distinción entre un orden dado y un orden hecho por los hombres pronto se vuelve un problema filosófico explícito. Si las leyes cambian de una ciudad a otra —lo que en Esparta es virtud, en Atenas puede ser delito—, ¿es la justicia misma un mero acuerdo humano, modificable? Es la pregunta con la que los sofistas van a abrir la próxima clase.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde a díke o a nómos?",
      groups: ["Díke", "Nómos"],
      items: [
        { text: "Personificada como hija de Zeus, que vigila desde su trono", group: 0 },
        { text: "Es la misma en todas las ciudades, porque no depende de los hombres", group: 0 },
        { text: "Se puede escribir, votar y modificar en una asamblea", group: 1 },
        { text: "Varía de una ciudad a otra según sus propias leyes", group: 1 },
        { text: "Heráclito la llama la muralla que hay que defender", group: 1 },
      ],
      explain: "Díke es un orden que se recibe, garantizado por los dioses; nómos es un orden que las ciudades se dan a sí mismas, y por eso puede cambiar de una a otra —la tensión que van a explotar los sofistas.",
    },
    {
      type: "match",
      question: "Uní cada fuente con su aporte a la pregunta por la justicia",
      pairs: [
        { left: "Homero", right: "La moira: cada quien tiene su porción fija, hasta los dioses" },
        { left: "Hesíodo", right: "Díke: la injusticia de unos pocos castiga a toda la ciudad" },
        { left: "Esquilo", right: "La Orestíada: el tribunal reemplaza la venganza de sangre" },
        { left: "Anaximandro", right: "Aplica el vocabulario de la justicia a un proceso físico" },
        { left: "Heráclito", right: "El nómos como ley humana, distinta de la díke divina" },
      ],
      explain: "De Homero a Heráclito la misma pregunta cambia de forma: primero un destino que se acepta, después una diosa que vigila, luego un tribunal que delibera, y por último una ley que los propios ciudadanos hacen y pueden rehacer.",
    },
    {
      type: "info",
      title: "Del mito al lógos",
      body: "En apenas tres siglos —de Homero, hacia el 750 a. C., a Heráclito, hacia el 500 a. C.— la pregunta por la justicia recorre un camino completo. Va de un destino que se acepta sin explicación, a una diosa que vigila desde el Olimpo, a un tribunal humano que delibera y vota, hasta una ley que la propia ciudad puede escribir y discutir.",
    },
    {
      type: "info",
      continues: true,
      title: "Del mito al lógos",
      body: "Ese camino corre en paralelo al que vimos la clase pasada sobre la physis. En ambos casos, lo que antes explicaban los dioses empieza a explicarse por sí mismo, sin dejar de ser por eso un orden. La physis y el nómos son, en el fondo, la misma pregunta aplicada a dos dominios distintos: qué hace que las cosas, y las ciudades, sean como son y no de otro modo. De esa tensión entre lo dado y lo hecho por los hombres arrancan, en la próxima clase, los sofistas.",
    },
  ],
};
