export default {
  num: 14,
  transcript: null,
  title: "Epicuro: el placer bien entendido",
  source: "",
  feed: [
    {
      type: "info",
      title: "Un mundo nuevo para la filosofía",
      body: "Aristóteles muere en 322 a. C., el mismo año en que empieza a desmoronarse el imperio que había forjado su alumno Alejandro Magno. El mundo griego cambia de escala: ya no son pequeñas ciudades-estado autogobernadas, sino enormes reinos helenísticos gobernados por generales de Alejandro. La pregunta política de Platón y Aristóteles, cómo organizar la mejor ciudad posible, pierde urgencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Un mundo nuevo para la filosofía",
      body: "En su lugar aparece una pregunta más íntima: cómo vivir bien un individuo, gobierne quien gobierne su ciudad. Las escuelas de este período, entre ellas la de Epicuro, comparten esa misma búsqueda de una serenidad que ya no depende de la vida pública.",
    },
    {
      type: "quiz",
      question: "¿Por qué cambia el centro de la filosofía después de Alejandro Magno?",
      options: [
        "porque la política pierde urgencia frente a la vida individual",
        "porque los griegos dejan por completo de hablar su propia lengua",
        "porque Aristóteles había prohibido discutir cualquier tema político",
        "porque las nuevas ciudades helenísticas eran mucho más pequeñas que Atenas",
      ],
      answer: 0,
      explain: "Ya no hay pequeñas ciudades autogobernadas sino grandes reinos gobernados por generales de Alejandro: la pregunta por la mejor organización política pierde urgencia frente a una pregunta más personal, cómo vivir bien cada quien.",
    },
    {
      type: "info",
      title: "El Jardín de Epicuro",
      body: "Epicuro (341-270 a. C.) llega a Atenas siendo joven y funda allí, hacia el 306 a. C., su propia escuela: un jardín donde vive junto a sus discípulos en una comunidad poco convencional para la época, que admite tanto a mujeres como a esclavos, algo que ni la Academia ni el Liceo hacían.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue a la comunidad que funda Epicuro en su Jardín?",
      options: [
        "admite a mujeres y esclavos, algo inusual en su época",
        "sólo admite a ciudadanos varones nacidos en Atenas",
        "exige a sus miembros renunciar a toda forma de propiedad privada",
        "funciona exclusivamente como una academia militar",
      ],
      answer: 0,
      explain: "A diferencia de la Academia de Platón y el Liceo de Aristóteles, el Jardín de Epicuro admite tanto a mujeres como a esclavos, una comunidad poco convencional para los estándares educativos de su época.",
    },
    {
      type: "info",
      title: "Átomos con un margen de libertad",
      body: "En física, Epicuro retoma el atomismo de Demócrito de la Clase 1: todo está hecho de átomos que caen eternamente en el vacío. Pero le suma una novedad decisiva, el **clinamen** o desviación: de vez en cuando, sin causa que lo explique, un átomo se desvía levemente de su caída recta. Sin ese margen de azar, razona Epicuro, todo estaría determinado de antemano, y no habría lugar para la libertad humana.",
    },
    {
      type: "quiz",
      question: "¿Para qué necesita Epicuro el clinamen, la desviación azarosa de los átomos?",
      options: [
        "para dejar un margen de indeterminación que haga posible la libertad",
        "para explicar por qué los átomos, en realidad, nunca se mueven",
        "para demostrar que Demócrito se había equivocado en todo",
        "para justificar la existencia de los dioses en su sistema físico",
      ],
      answer: 0,
      explain: "Si todos los átomos siguieran trayectorias estrictamente determinadas, como en Demócrito, todo el universo quedaría fijado de antemano. El clinamen introduce un margen de azar que deja lugar a la libertad humana.",
    },
    {
      type: "info",
      title: "Dioses que no se ocupan de nosotros",
      body: "Epicuro no niega que existan los dioses, pero los aleja por completo de los asuntos humanos. Son seres perfectos y dichosos que viven en los espacios entre los mundos, y ocuparse de nosotros, premiando, castigando, exigiendo sacrificios, sería incompatible con su propia felicidad perfecta. El miedo a un castigo divino, tan extendido en su época, es para Epicuro un miedo sin ningún fundamento.",
    },
    {
      type: "quiz",
      question: "Según Epicuro, ¿por qué no hay que temer el castigo de los dioses?",
      options: [
        "porque ocuparse de los asuntos humanos sería incompatible con su felicidad",
        "porque los dioses, en realidad, no existen en absoluto",
        "porque los dioses castigan sólo a quienes no practican ningún culto",
        "porque los dioses ya fueron reemplazados por los átomos de Demócrito",
      ],
      answer: 0,
      explain: "Epicuro no niega que existan los dioses: sostiene que son seres perfectos y dichosos para quienes premiar, castigar o exigir sacrificios sería incompatible con su propia felicidad. El miedo al castigo divino carece, entonces, de fundamento.",
    },
    {
      type: "info",
      title: "La muerte no es nada para nosotros",
      body: "El otro gran miedo que Epicuro quiere disolver es el de la muerte. Su argumento, en la Carta a Meneceo, es directo: «mientras existimos, la muerte no está presente, y cuando la muerte está presente, ya no existimos». La muerte no es una experiencia mala porque no es una experiencia de nada: es la ausencia total de sensación, y nada de lo que ya no se siente puede hacer daño.",
    },
    {
      type: "quiz",
      question: "¿Por qué sostiene Epicuro que la muerte «no es nada para nosotros»?",
      options: [
        "porque cuando ella llega, nosotros ya no existimos",
        "porque después de morir, según él, la vida continúa sin cambios",
        "porque sólo les ocurre a las personas que no filosofaron en vida",
        "porque los átomos del alma se reencarnan de inmediato en otro cuerpo",
      ],
      answer: 0,
      explain: "Mientras existimos, la muerte todavía no está presente; cuando la muerte llega, ya no existimos para experimentarla. Nunca coincidimos con ella, así que no hay ningún momento en que pueda hacernos daño.",
    },
    {
      type: "info",
      title: "El placer bien entendido",
      body: "Epicuro sostiene que el placer es el único bien en sí mismo, lo que le valió durante siglos una fama de defensor del exceso que no le corresponde. Distingue el placer «cinético», el de un proceso activo como comer algo delicioso, del placer «catastemático», el de un estado estable una vez satisfecha una necesidad. Este segundo tipo es el que de verdad vale la pena perseguir: la **ataraxia**, la serenidad de un cuerpo sin dolor y una mente sin perturbación.",
    },
    {
      type: "quiz",
      question: "¿Qué tipo de placer valora sobre todo Epicuro, contra la fama de defensor del exceso que se le atribuye?",
      options: [
        "el catastemático, un estado estable de calma sostenida",
        "el cinético, el de un proceso activo como un banquete prolongado",
        "cualquier placer, sea del tipo que sea o dure lo que dure",
        "ningún tipo de placer: para Epicuro, el placer es siempre nocivo",
      ],
      answer: 0,
      explain: "Epicuro distingue el placer cinético, ligado a un proceso activo, del catastemático, el estado estable de un cuerpo sin dolor y una mente sin perturbación: la ataraxia. Es este segundo tipo el que de verdad vale la pena buscar.",
    },
    {
      type: "short",
      question: "¿Cómo llama Epicuro a la serenidad de un cuerpo sin dolor y una mente sin perturbación?",
      answers: ["ataraxia"],
      explain: "Es el placer «catastemático», el estado estable que Epicuro valora por encima del placer «cinético» de cualquier proceso activo, por agradable que sea mientras dura.",
    },
    {
      type: "info",
      title: "Clasificar los deseos",
      body: "Para alcanzar esa serenidad, Epicuro clasifica los deseos en tres tipos. Los naturales y necesarios —comer, beber, descansar— son fáciles de satisfacer y hay que atenderlos. Los naturales pero no necesarios —una comida refinada en vez de una simple— se pueden disfrutar de vez en cuando, sin volverse indispensables. Los vanos —riqueza sin límite, fama, poder— nunca se satisfacen del todo, y perseguirlos sin freno es la receta segura para la infelicidad.",
    },
    {
      type: "quiz",
      question: "Según la clasificación de Epicuro, ¿qué tienen de particular los deseos «vanos», como la riqueza sin límite o la fama?",
      options: [
        "nunca se satisfacen del todo, sin importar cuánto se consiga",
        "son los más fáciles de satisfacer de los tres tipos de deseo",
        "coinciden exactamente con los deseos naturales y necesarios",
        "son los únicos deseos que Epicuro considera legítimos",
      ],
      answer: 0,
      explain: "A diferencia de los deseos naturales, que tienen un límite de satisfacción, los deseos vanos, riqueza sin fin, fama, poder, no se agotan nunca. Perseguirlos sin freno es, para Epicuro, la receta segura para la infelicidad.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al placer catastemático o al cinético?",
      groups: ["Placer catastemático", "Placer cinético"],
      items: [
        { text: "El de un estado estable, una vez satisfecha la necesidad", group: 0 },
        { text: "El de un proceso activo, como comer algo delicioso", group: 1 },
        { text: "La ataraxia, la serenidad sin ninguna perturbación", group: 0 },
        { text: "Se agota apenas termina la actividad que lo produce", group: 1 },
      ],
      explain: "El placer cinético dura lo que dura el proceso que lo genera; el catastemático es un estado que se sostiene una vez alcanzado. Epicuro valora sobre todo este segundo tipo, la ataraxia.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que describe",
      pairs: [
        { left: "Clinamen", right: "La desviación azarosa que abre lugar a la libertad" },
        { left: "Tetrapharmakos", right: "No temer a los dioses ni a la muerte; lo bueno es fácil" },
        { left: "Deseos vanos", right: "Riqueza, fama y poder: nunca se satisfacen del todo" },
        { left: "Ataraxia", right: "Serenidad de un cuerpo sin dolor y una mente sin perturbación" },
      ],
      explain: "Las cuatro piezas arman el mismo programa: una física que deja lugar a la libertad, una fórmula breve para recordar lo esencial, una crítica a los deseos que nunca se sacian, y la meta final, la serenidad.",
    },
    {
      type: "info",
      title: "El cuádruple remedio",
      body: "Esa filosofía entera se resume en una fórmula breve que los discípulos de Epicuro memorizaban, el **tetrapharmakos** o «cuádruple remedio»: no hay que temer a los dioses, no hay que temer a la muerte, lo bueno es fácil de conseguir, y lo malo es fácil de soportar. La próxima clase revisamos a los estoicos, la otra gran escuela helenística, que comparte con Epicuro la búsqueda de la serenidad pero llega a ella por un camino casi opuesto.",
    },
  ],
};
