export default {
  num: 18,
  transcript: null,
  title: "El logos griego y los Padres de la Iglesia",
  source: "",
  feed: [
    {
      type: "info",
      title: "Un vocabulario de ochocientos años",
      body: "Cuando el cristianismo empieza a expandirse por el Mediterráneo oriental en el siglo I, sus primeros pensadores educados escriben en griego y estudiaron en las mismas escuelas de retórica y filosofía que cualquier otro joven culto de su época. Se encuentran, entonces, con un problema concreto: cómo explicar quién es Cristo y qué es Dios usando las palabras que la filosofía griega ya venía puliendo desde hacía casi ochocientos años.",
    },
    {
      type: "info",
      title: "Filón: el primer puente",
      body: "Filón de Alejandría (ca. 20 a. C.-50 d. C.), un judío helenizado que nunca fue cristiano, es el primero en usar sistemáticamente el vocabulario griego del **logos** para explicar la relación entre un Dios trascendente y el mundo creado. Combinando ideas platónicas y estoicas, describe al Logos como una razón divina intermedia, ni del todo Dios ni del todo criatura, a través de la cual Dios crea y gobierna el cosmos.",
    },
    {
      type: "quiz",
      question: "¿Qué hace Filón de Alejandría con el concepto griego de logos?",
      options: [
        "lo usa como intermediario entre un Dios trascendente y el mundo creado",
        "lo rechaza por completo por considerarlo una idea pagana peligrosa",
        "lo aplica únicamente a describir el comportamiento de los animales",
        "lo identifica de manera literal con el Dios del Antiguo Testamento",
      ],
      answer: 0,
      explain: "Combinando ideas platónicas y estoicas, Filón describe al Logos como una razón divina intermedia, ni del todo Dios ni del todo criatura, que le permite explicar cómo un Dios trascendente crea y gobierna el mundo.",
    },
    {
      type: "info",
      title: "En el principio era el Logos",
      body: "Esa misma palabra griega abre, décadas después, el Evangelio de Juan: «en el principio era el Logos, y el Logos estaba junto a Dios, y el Logos era Dios». Es la misma palabra con la que Heráclito, en la Clase 1, nombraba la razón común detrás del cambio del cosmos, y con la que los estoicos, en la Clase 15, nombraban la razón que atraviesa todo lo que existe.",
    },
    {
      type: "info",
      continues: true,
      title: "En el principio era el Logos",
      body: "Juan la usa ahora para nombrar a Cristo mismo, preexistente, «que se hizo carne y habitó entre nosotros». La misma palabra que empezó nombrando un principio físico impersonal termina nombrando a una persona.",
    },
    {
      type: "quiz",
      question: "¿Qué tienen en común el logos de Heráclito, el de los estoicos y el de Juan?",
      options: [
        "los tres usan la misma palabra griega para la razón que ordena el cosmos",
        "los tres se refieren exactamente al mismo dios personal y encarnado",
        "los tres niegan por completo la existencia de cualquier tipo de orden",
        "los tres fueron escritos originalmente en la misma década histórica",
      ],
      answer: 0,
      explain: "Heráclito, los estoicos y Juan usan la misma palabra griega, logos, para nombrar la razón que ordena el cosmos, aunque el significado se transforma por completo en el camino: de principio físico impersonal a persona encarnada.",
    },
    {
      type: "info",
      title: "Semillas del logos en los filósofos paganos",
      body: "Justino Mártir (ca. 100-165 d. C.), que antes de convertirse había pasado por el estoicismo, el aristotelismo y el platonismo, da un paso todavía más generoso hacia la filosofía griega. Sostiene que el Logos estaba difundido, en semillas parciales —el **logos spermatikos**—, entre todos los seres humanos capaces de razonar.",
    },
    {
      type: "info",
      continues: true,
      title: "Semillas del logos en los filósofos paganos",
      body: "Por eso, sostiene Justino, Sócrates y Heráclito ya poseían una porción genuina de esa misma verdad, siglos antes de Cristo, aunque incompleta: en algún sentido, «cristianos antes de Cristo».",
    },
    {
      type: "quiz",
      question: "¿Qué sostiene Justino Mártir con su idea del logos spermatikos?",
      options: [
        "que Sócrates y Heráclito ya tenían una porción parcial de esa verdad",
        "que sólo los cristianos bautizados pueden acceder al logos",
        "que la filosofía griega es completamente incompatible con el cristianismo",
        "que el logos de Heráclito no tiene ninguna relación con el de Juan",
      ],
      answer: 0,
      explain: "El Logos, para Justino, estaba difundido en semillas parciales entre todos los seres capaces de razonar. Sócrates y Heráclito ya poseían una porción genuina de esa verdad, siglos antes de la encarnación de Cristo.",
    },
    {
      type: "info",
      title: "La filosofía como preparación",
      body: "Clemente de Alejandría (ca. 150-215 d. C.) lleva la idea un paso más lejos: la filosofía griega, sostiene, fue un regalo de Dios a los griegos, tan legítimo como la Ley que Dios le dio a los judíos, y cumplió durante siglos la función de un **paidagogos**, el esclavo que en Atenas acompañaba al niño camino a la escuela. Prepara el terreno para recibir el Evangelio, sin ser todavía el Evangelio mismo.",
    },
    {
      type: "quiz",
      question: "¿Qué función le atribuye Clemente de Alejandría a la filosofía griega, con la imagen del paidagogos?",
      options: [
        "la de preparar el terreno para el Evangelio, sin reemplazarlo",
        "la de sustituir por completo a la fe cristiana en la vida diaria",
        "la de ser un obstáculo que hay que superar antes de creer",
        "la de tener el mismo estatus legal que el propio Evangelio",
      ],
      answer: 0,
      explain: "El paidagogos no reemplaza al maestro: sólo acompaña al niño camino a la escuela. Del mismo modo, para Clemente, la filosofía griega preparó el terreno para el Evangelio, sin llegar a ser el Evangelio mismo.",
    },
    {
      type: "info",
      title: "No todos estaban de acuerdo",
      body: "No todos los cristianos veían esta síntesis con buenos ojos. Tertuliano (ca. 155-220 d. C.), en el norte de África, la rechaza de plano: «¿qué tiene que ver Atenas con Jerusalén?», pregunta célebremente, exigiendo una fe que no necesite el permiso de ningún filósofo griego para sostenerse.",
    },
    {
      type: "quiz",
      question: "Con la pregunta «¿qué tiene que ver Atenas con Jerusalén?», ¿qué postura defiende Tertuliano?",
      options: [
        "que la fe cristiana no necesita el aval de la filosofía griega",
        "que Atenas y Jerusalén son, en el fondo, la misma ciudad",
        "que la filosofía griega es superior a cualquier religión revelada",
        "que hay que estudiar geografía antigua antes de leer la Biblia",
      ],
      answer: 0,
      explain: "A diferencia de Justino o Clemente, Tertuliano rechaza de plano la síntesis entre filosofía griega y fe cristiana: exige una fe que se sostenga por sí misma, sin necesitar el permiso de ningún filósofo pagano.",
    },
    {
      type: "info",
      title: "Orígenes: el sistema más ambicioso",
      body: "Orígenes de Alejandría (ca. 185-253 d. C.) es el pensador cristiano más sofisticado de este primer período, profundamente formado en el platonismo de su época. En su tratado Sobre los principios intenta construir un sistema teológico completo —sobre Dios, el alma, la libertad y el fin de la historia— con el mismo rigor especulativo con el que Platón o Plotino habían construido los suyos.",
    },
    {
      type: "info",
      continues: true,
      title: "Orígenes: el sistema más ambicioso",
      body: "Algunas de sus ideas más audaces, como que todas las almas preexisten a su nacimiento o que al final de los tiempos hasta el propio demonio podría salvarse, resultaron demasiado atrevidas para la Iglesia posterior, que las condenó siglos después de su muerte. Orígenes muestra, mejor que nadie en esta clase, lo difícil que es trazar la frontera exacta entre pensar con la filosofía griega y pensar dentro de ella.",
    },
    {
      type: "quiz",
      question: "¿Por qué es un caso especialmente revelador el de Orígenes, dentro de esta clase?",
      options: [
        "porque muestra lo difícil que es separar la fe de la filosofía griega",
        "porque fue el único de los cuatro que nunca leyó ningún texto de Platón",
        "porque rechazó por completo cualquier influencia filosófica en su teología",
        "porque sus ideas fueron aceptadas sin ninguna controversia posterior",
      ],
      answer: 0,
      explain: "Orígenes construye un sistema teológico tan ambicioso como el de Platón o Plotino, pero algunas de sus ideas más audaces terminaron condenadas siglos después: la síntesis entre filosofía griega y fe cristiana no fue nunca un asunto sencillo ni cerrado.",
    },
    {
      type: "classify",
      question: "¿Cada postura está a favor o en contra de integrar la filosofía griega a la fe cristiana?",
      groups: ["A favor de integrarla", "En contra de integrarla"],
      items: [
        { text: "El Logos ya estaba, en semillas, en Sócrates y Heráclito (Justino)", group: 0 },
        { text: "¿Qué tiene que ver Atenas con Jerusalén? (Tertuliano)", group: 1 },
        { text: "La filosofía fue un regalo de Dios a los griegos (Clemente)", group: 0 },
        { text: "La fe no necesita el permiso de ningún filósofo pagano", group: 1 },
      ],
      explain: "Justino y Clemente ven en la filosofía griega una preparación legítima para el Evangelio. Tertuliano la rechaza de plano: para él, la fe cristiana tiene que sostenerse por sí misma, sin depender de ningún pensador pagano.",
    },
    {
      type: "match",
      question: "Uní cada pensador con su aporte a esta síntesis",
      pairs: [
        { left: "Filón de Alejandría", right: "El primer puente: el Logos como intermediario entre Dios y el mundo" },
        { left: "Justino Mártir", right: "El logos spermatikos: Sócrates y Heráclito ya tenían una porción" },
        { left: "Clemente de Alejandría", right: "La filosofía griega como paidagogos, preparación para el Evangelio" },
        { left: "Orígenes", right: "El sistema más ambicioso, y también el más controvertido" },
      ],
      explain: "De Filón a Orígenes, cuatro generaciones de pensadores van tejiendo, cada vez con más ambición, el mismo puente entre la filosofía griega y la fe cristiana, sin que la Iglesia posterior aceptara sin más cada uno de sus pasos.",
    },
    {
      type: "short",
      question: "¿Cómo llama Justino Mártir a las porciones parciales del Logos ya presentes en filósofos paganos como Sócrates?",
      answers: ["logos spermatikos", "semillas del logos"],
      explain: "El Logos completo se encarna recién en Cristo, pero para Justino ya estaba difundido en semillas parciales entre todos los seres humanos capaces de razonar, incluidos los filósofos griegos anteriores al cristianismo.",
    },
    {
      type: "info",
      title: "El círculo se cierra",
      body: "Empezamos este curso con Tales preguntando de qué está hecho el mundo, y con Heráclito nombrando logos a la razón oculta detrás de su cambio constante. Terminamos con ese mismo logos convertido en una persona, encarnada, que nace, sufre y muere. Es la misma palabra, atravesando ochocientos años y transformándose por completo, sin dejar nunca del todo de ser ella misma.",
    },
    {
      type: "info",
      continues: true,
      title: "El círculo se cierra",
      body: "Cómo conciliar exactamente a ese Dios encarnado con la trascendencia absoluta del Uno de Plotino, o con la inmutabilidad del Motor Inmóvil de Aristóteles, es la pregunta que va a ocupar a la filosofía cristiana durante los siglos siguientes: una historia que empieza justo donde termina este curso.",
    },
  ],
};
