export default {
  num: 1,
  transcript: 1,
  title: "Los presocráticos: physis y arché",
  source: "",
  feed: [
    {
      type: "info",
      title: "Qué es la filosofía presocrática",
      body: "«Presocráticos» es un rótulo que estos filósofos jamás usaron. Se lo aplican después los historiadores de la filosofía, empezando por el propio Aristóteles, para agrupar a quienes piensan antes de Sócrates: desde Tales, hacia el 600 a. C., hasta Demócrito, ya bien entrado el siglo V a. C. Es una etiqueta cómoda pero también arbitraria, que agrupa bajo un mismo nombre a pensadores separados por casi dos siglos y por cientos de kilómetros de distancia.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué es la filosofía presocrática",
      body: "La mayoría no viene de Atenas —que todavía no es un centro filosófico— sino de las colonias griegas dispersas por la costa jónica de Asia Menor y por el sur de Italia y Sicilia, la llamada Magna Grecia. Son ciudades en la encrucijada comercial entre Oriente y Occidente, en contacto con la astronomía babilónica y la geometría egipcia: un terreno fértil para preguntas nuevas sobre el mundo natural.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué es la filosofía presocrática",
      body: "Lo que estos pensadores indagan tiene un nombre técnico: **physis**, de phyein, «crecer» o «brotar». No significa simplemente «naturaleza» en el sentido de paisaje, sino el principio interno por el cual una cosa es lo que es y se comporta como se comporta —lo que hace que una semilla se convierta en árbol y no en piedra—. Preguntar por la physis de todas las cosas es preguntar qué la explica a todas por igual.",
    },
    {
      type: "quiz",
      question: "¿Por qué la etiqueta «presocráticos» es, en cierto sentido, arbitraria?",
      options: [
        "porque agrupa a pensadores separados por siglos y kilómetros",
        "porque ninguno de ellos escribió jamás un solo texto",
        "porque todos formaron parte de la misma escuela ateniense",
        "porque Sócrates fue en realidad discípulo de todos ellos",
      ],
      answer: 0,
      explain: "Es un rótulo retrospectivo que ellos mismos no usaban: reúne bajo un solo nombre a pensadores de Mileto, Éfeso, Elea o Abdera, activos entre el 600 y el 400 a. C., con poco más en común que haber pensado antes de Sócrates.",
    },
    {
      type: "info",
      title: "Los milesios: la pregunta por la physis",
      body: "Tales de Mileto, a quien la tradición —empezando por Aristóteles— considera el primer filósofo, sostiene que la physis de todas las cosas es el agua. No es un capricho: el agua se presenta en tres estados, sólido, líquido y vapor, y es indispensable para toda forma de vida. Se le atribuye además haber predicho un eclipse solar (585 a. C.); no se conserva ningún escrito suyo, y todo lo que sabemos de él llega por autores posteriores.",
    },
    {
      type: "quiz",
      question: "¿Por qué elige Tales el agua, y no cualquier otro elemento, como principio de todas las cosas?",
      options: [
        "porque cambia de estado y es indispensable para la vida",
        "porque así lo indicaban los oráculos consultados en Delfos",
        "porque el fuego le parecía un elemento poco confiable",
        "porque había calculado su peso atómico con precisión",
      ],
      answer: 0,
      explain: "El agua se presenta en tres estados —sólido, líquido, vapor— y es esencial para la vida vegetal y animal: una candidata razonable para quien busca una causa natural y observable, no una revelación religiosa.",
    },
    {
      type: "info",
      continues: true,
      title: "Los milesios: la pregunta por la physis",
      body: "Anaximandro, discípulo o socio de Tales, da un paso más abstracto: si el mundo tiene cualidades opuestas —húmedo y seco, caliente y frío—, ninguna puede ser más básica que su contraria. Propone entonces como principio algo sin cualidades determinadas, el **ápeiron**, «lo ilimitado», del que surgen los opuestos por separación. Se le atribuyen también el primer mapa del mundo conocido y una teoría rudimentaria del origen de los animales a partir de criaturas acuáticas.",
    },
    {
      type: "quiz",
      question: "¿Por qué Anaximandro rechaza un elemento concreto, como el agua, y propone el ápeiron?",
      options: [
        "porque ningún opuesto puede ser más básico que su contrario",
        "porque el agua no existía todavía en su época",
        "porque prefería explicaciones basadas en la religión",
        "porque quería coincidir exactamente con la física de Tales",
      ],
      answer: 0,
      explain: "Si el agua misma es húmeda, no puede explicar por qué también existe lo seco: ningún elemento con cualidades definidas puede ser más originario que su opuesto, así que el principio tiene que carecer de cualidades propias.",
    },
    {
      type: "info",
      continues: true,
      title: "Los milesios: la pregunta por la physis",
      body: "De Anaximandro se conserva, transmitida por Simplicio, la frase más antigua de la filosofía occidental: «de donde las cosas tienen su origen, allí vuelven a perecer según la necesidad, pues se pagan unas a otras penitencia y retribución por su injusticia, conforme al orden del tiempo». Vale la pena notarlo ya: incluso un principio físico como el ápeiron se describe con vocabulario legal y moral, justicia y penitencia. Es algo que vamos a seguir de cerca en la próxima clase.",
    },
    {
      type: "info",
      continues: true,
      title: "Los milesios: la pregunta por la physis",
      body: "Anaxímenes, el tercero de los milesios, vuelve a un elemento concreto —el aire— pero suma algo que a los otros dos les faltaba: un mecanismo explícito de transformación. El aire se condensa y se vuelve viento, nube, agua, tierra y piedra; se enrarece y se vuelve fuego. Por primera vez, la diversidad del mundo se explica por cambios de cantidad —más o menos densidad— de una sola sustancia, y no solo por su nombre.",
    },
    {
      type: "quiz",
      question: "¿Qué aporta Anaxímenes que Tales y Anaximandro todavía no tenían?",
      options: [
        "un mecanismo de condensación y rarefacción para el cambio",
        "la primera prueba matemática de un teorema geométrico",
        "el rechazo total de la existencia de un elemento único",
        "una teoría sobre la inmortalidad y reencarnación del alma",
      ],
      answer: 0,
      explain: "No se limita a nombrar el aire como elemento: explica cómo se transforma en los demás —se condensa en agua y tierra, se enrarece en fuego— dando el primer mecanismo causal explícito para el cambio.",
    },
    {
      type: "info",
      title: "Aristóteles bautiza el problema: arché",
      body: "Casi dos siglos después de Tales, cuando Aristóteles escribe la primera historia de la filosofía al comienzo de su Metafísica, bautiza en retrospectiva lo que buscaban los milesios: llama **arché** al principio único y permanente del que están hechas todas las cosas y al que vuelven cuando perecen. Tales, Anaximandro y Anaxímenes coinciden, además, en que hay un solo tipo de elemento básico, así que se los llama **monistas cualitativos**, aunque acepten que existen muchas cosas hechas de él.",
    },
    {
      type: "short",
      question: "¿Cómo llama Aristóteles, en retrospectiva, al principio último y permanente del que están hechas todas las cosas?",
      answers: ["arché", "arje"],
      explain: "Es el término con el que Aristóteles agrupa, casi dos siglos después, la pregunta de fondo de todos los presocráticos: qué hay debajo del cambio, ya sea agua, ápeiron, aire, fuego o átomos.",
    },
    {
      type: "info",
      continues: true,
      title: "Aristóteles bautiza el problema: arché",
      body: "Pero la pregunta por el arché tiene también una cara cuantitativa, distinta de la cualitativa: ¿el universo es, en número, una sola cosa —una esfera compacta y sin partes— o son numéricamente muchas las cosas que existen? Esta segunda pregunta parece obvia —cada quien es distinto de los demás— pero se vuelve un problema filosófico serio cuando los eleatas la lleven al extremo, más adelante en esta misma clase.",
    },
    {
      type: "quiz",
      question: "Si alguien dice que todo está hecho de un único elemento, pero que existen muchísimas cosas distintas hechas de él, ¿qué posición sostiene?",
      options: [
        "monismo cualitativo",
        "pluralismo cualitativo",
        "monismo cuantitativo",
        "pluralismo cuantitativo",
      ],
      answer: 0,
      explain: "La pregunta cualitativa es de qué tipo de cosa está hecho el mundo (uno o varios elementos); la cuantitativa es cuántas cosas distintas hay en número. Los milesios son monistas en la primera y pluralistas en la segunda.",
    },
    {
      type: "info",
      title: "Heráclito: el logos y el fuego",
      body: "Heráclito de Éfeso, de familia aristocrática, es célebre en la Antigüedad por lo oscuro y sentencioso de su estilo, que le valió el apodo de «el Oscuro», y por su carácter altivo y solitario: no funda escuela ni deja discípulos. Su libro, del que sólo sobreviven fragmentos citados por autores posteriores, abre con una idea que organiza todo lo demás: «aunque este logos es siempre verdadero, los hombres no llegan a comprenderlo […] y viven como si tuvieran un entendimiento privado» (DK B1-B2).",
    },
    {
      type: "quiz",
      question: "Para Heráclito, el logos es sobre todo…",
      options: [
        "el orden racional común que gobierna el cambio constante",
        "un dios personal que interviene en los asuntos humanos",
        "el nombre técnico del elemento fuego en su física",
        "la facultad del alma que permite hacer matemática",
      ],
      answer: 0,
      explain: "El mundo cambia sin parar, pero ese cambio no es caos: obedece a una razón o proporción común, el logos, que la mayoría de la gente ignora al vivir «como si tuviera un entendimiento privado».",
    },
    {
      type: "info",
      continues: true,
      title: "Heráclito: el logos y el fuego",
      body: "El fragmento que se hizo más famoso, «no se puede entrar dos veces en el mismo río», no es en realidad de Heráclito: es una radicalización posterior, atribuida a su seguidor Cratilo. Lo que Heráclito escribe (DK B12) es más sutil: «sobre quienes entran en los mismos ríos, fluyen aguas siempre distintas». El río sigue siendo el mismo río, con su nombre, su lugar y su forma, aunque el agua que lo compone cambie sin cesar: cambio y permanencia, juntos.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia el fragmento auténtico de Heráclito sobre el río de la frase popular «nunca te bañás dos veces en el mismo río»?",
      options: [
        "el original afirma que el río, pese al cambio, sigue siendo el mismo",
        "el original niega directamente que el agua fluya de verdad",
        "el original habla de un lago y no de un río en absoluto",
        "el original fue escrito varios siglos antes de que existiera Heráclito",
      ],
      answer: 0,
      explain: "La frase popular es una radicalización posterior, de su seguidor Cratilo. Heráclito dice que el agua cambia pero el río permanece: la misma idea de fondo del doble aspecto, cambio y orden a la vez.",
    },
    {
      type: "info",
      continues: true,
      title: "Heráclito: el logos y el fuego",
      body: "Heráclito elige el fuego como imagen de ese principio: «este orden del mundo, el mismo para todos, no lo hizo ningún dios ni ningún hombre, sino que fue siempre, es y será: fuego siempre vivo, que se enciende según medida y se apaga según medida» (DK B30). Y describe el conflicto entre opuestos como motor de todo: «la guerra es padre de todas las cosas y de todas rey» (DK B53) —no en sentido bélico literal, sino como tensión que sostiene cualquier equilibrio, como la cuerda de un arco.",
    },
    {
      type: "info",
      title: "Pitágoras: el número como arché",
      body: "Pitágoras, de la isla de Samos, funda en Crotona, en el sur de Italia, una comunidad a la vez religiosa y filosófica, con reglas de vida estrictas y una doctrina central: la metempsícosis, la transmigración del alma entre distintos cuerpos. No dejó nada escrito; casi todo lo que se le atribuye llega filtrado por sus seguidores. Descubre que los intervalos musicales armónicos corresponden a proporciones numéricas simples, y extiende esa intuición a todo el cosmos —palabra que significa, precisamente, «orden»—.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia el «orden» de Pitágoras del de Heráclito?",
      options: [
        "uno es matemático; el otro es una razón ligada al fuego",
        "uno niega el cambio; el otro lo acepta como real",
        "uno es griego; el otro proviene de Persia",
        "uno es escrito; el otro es una tradición solo oral",
      ],
      answer: 0,
      explain: "Ambos aceptan que el cambio es real y que está regido por un orden estable —el llamado doble aspecto—, pero Heráclito lo llama logos y lo asocia al fuego, mientras Pitágoras lo encuentra en proporciones numéricas.",
    },
    {
      type: "short",
      question: "¿Con qué palabra griega nombra Heráclito la razón común que gobierna el cambio?",
      answers: ["logos"],
      explain: "Logos —palabra, razón, proporción— es, para Heráclito, lo que hace que el flujo constante de las cosas no sea caos: una ley común que la mayoría no escucha.",
    },
    {
      type: "info",
      title: "Los eleatas: el ser inmóvil",
      body: "Parménides de Elea, en el sur de Italia, expone su filosofía en un poema, Sobre la naturaleza, donde una diosa le revela dos caminos posibles de investigación: «uno, que es y que no es posible que no sea, es el camino de la persuasión […]; el otro, que no es y que es necesario que no sea, ese te digo que es un sendero de todo en todo inescrutable» (DK B2). Sólo el primero es transitable: pensar el no-ser es, literalmente, no pensar nada.",
    },
    {
      type: "quiz",
      question: "¿En qué se apoya Parménides para negar que el cambio sea real?",
      options: [
        "en que pensar el paso del no-ser al ser es contradictorio",
        "en observaciones astronómicas sobre el movimiento de los astros",
        "en experimentos con agua, aire y fuego en distintas vasijas",
        "en el testimonio de los oráculos sobre el destino del cosmos",
      ],
      answer: 0,
      explain: "Su argumento es puramente lógico, no empírico: si algo cambia, pasa de no ser a ser o al revés, y pensar el no-ser es imposible. Por eso concluye que el ser tiene que ser uno, eterno e inmóvil.",
    },
    {
      type: "info",
      continues: true,
      title: "Los eleatas: el ser inmóvil",
      body: "De ahí Parménides deduce los «signos» del ser genuino (DK B8): «ingénito e imperecedero […] todo entero, único, inmóvil y sin fin». Y rechaza de plano la posición de quienes —sin nombrarlo, aunque muchos leen aquí una respuesta a Heráclito— piensan «que ser y no ser son lo mismo y no lo mismo» (DK B6): para Parménides no hay término medio entre ser y no ser, y quien lo busca «vaga confundido, con la mente errante».",
    },
    {
      type: "info",
      continues: true,
      title: "Los eleatas: el ser inmóvil",
      body: "Esto obliga a Parménides a desconfiar de los sentidos: si la experiencia dice que somos muchos y cambiantes, pero la razón concluye que todo es uno e inmutable, el error está en los sentidos. El mundo cambiante que perciben los sentidos pertenece, entonces, a la vía de la Opinión (dóxa): mera apariencia, no realidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Los eleatas: el ser inmóvil",
      body: "Zenón de Elea, su discípulo, defiende esa doctrina con un método nuevo: en vez de argumentar a favor del ser inmóvil, muestra que la posición contraria —creer en el movimiento y la pluralidad— lleva a contradicciones, un procedimiento que Aristóteles reconoce como el primer uso sistemático de la reducción al absurdo. Es su famosa paradoja: si Aquiles le da ventaja a una tortuga, nunca la alcanza, porque cada vez que llega a donde ella estaba, la tortuga ya avanzó un poco más.",
    },
    {
      type: "quiz",
      question: "¿Qué busca demostrar Zenón con la paradoja de Aquiles y la tortuga?",
      options: [
        "que el movimiento, pensado con rigor lógico, es contradictorio",
        "que las tortugas son, en la práctica, más veloces que Aquiles",
        "que el espacio físico no puede dividirse en partes iguales",
        "que Aquiles era, en realidad, un personaje puramente mítico",
      ],
      answer: 0,
      explain: "No niega la experiencia cotidiana del movimiento: quiere mostrar que, aplicada con rigor a un espacio infinitamente divisible, la razón lleva a conclusiones absurdas, defendiendo así por el absurdo el monismo de Parménides.",
    },
    {
      type: "classify",
      question: "¿Cada postura es de los milesios o de los eleatas?",
      groups: ["Milesios", "Eleatas"],
      items: [
        { text: "Buscan un elemento natural y observable como principio", group: 0 },
        { text: "Confían en la experiencia sensorial para conocer el mundo", group: 0 },
        { text: "Aceptan el cambio como un dato real que hay que explicar", group: 0 },
        { text: "Los sentidos son la vía de la Opinión, no del conocimiento", group: 1 },
        { text: "El cambio y la pluralidad son, en rigor, ilusorios", group: 1 },
        { text: "Sólo el razonamiento abstracto llega a la verdad", group: 1 },
      ],
      explain: "Los milesios confían en lo que observan y buscan un elemento concreto; los eleatas, en cambio, subordinan los sentidos a la lógica y terminan negando la realidad misma del cambio.",
    },
    {
      type: "info",
      title: "Los pluralistas: salvar el cambio",
      body: "Parménides deja un problema a quien quiera seguir haciendo filosofía natural: si el ser no puede surgir del no-ser, ¿cómo explicar que las cosas cambien? Empédocles, Anaxágoras y Demócrito responden con la misma estrategia: aceptan que ningún elemento último se genera ni se destruye, pero proponen que hay, desde siempre, varios elementos eternos que se combinan y separan, produciendo así la apariencia de cambio sin que nada nuevo llegue a ser de la nada.",
    },
    {
      type: "info",
      continues: true,
      title: "Los pluralistas: salvar el cambio",
      body: "Empédocles de Agrigento, en Sicilia, propone que todo está hecho de cuatro **raíces** (rhízomata): tierra, aire, fuego y agua. La palabra «elemento» la va a acuñar recién después Aristóteles. Esas raíces se combinan y separan por la acción de dos fuerzas cósmicas, el Amor y la Discordia, en una historia cósmica cíclica: fases de unión total bajo el Amor alternan con fases de disgregación total bajo la Discordia, y el mundo que conocemos es apenas un momento intermedio entre esos dos extremos.",
    },
    {
      type: "quiz",
      question: "El Amor y la Discordia de Empédocles, ¿son un mecanismo ciego o un principio con propósito?",
      options: [
        "no queda del todo claro; podrían ser las dos cosas",
        "son claramente mecanismos ciegos, como los átomos de Demócrito",
        "son claramente una mente cósmica consciente, como el nous",
        "son metáforas puramente poéticas sin ningún peso explicativo",
      ],
      answer: 0,
      explain: "Si se los lee como atracción y repulsión física —al modo del magnetismo— son mecánicos; si se los lee como una afinidad orientada a un fin, ya anuncian una explicación teleológica: la ambigüedad sigue discutiéndose.",
    },
    {
      type: "info",
      continues: true,
      title: "Los pluralistas: salvar el cambio",
      body: "Anaxágoras de Clazómenas, el primero en llevar la filosofía a Atenas —fue maestro de Pericles—, sostiene que hay tantos elementos básicos como tipos de sustancia, «semillas» de hueso, de piel, de sangre, y que «todo está en todo»: cada cosa contiene porciones de todas las demás, y lo que la define es cuál predomina. Para explicar por qué esa mezcla infinita no es un caos, introduce el **nous**, una mente separada de la materia que ordena las semillas.",
    },
    {
      type: "quiz",
      question: "¿Qué le reprocha después Platón a la solución de Anaxágoras?",
      options: [
        "que introduce el nous pero después lo usa poco",
        "que su física no incluye ningún tipo de elemento",
        "que niega por completo la existencia de una mente",
        "que copia sin citar la teoría atómica de Demócrito",
      ],
      answer: 0,
      explain: "Platón, en el Fedón, elogia la idea de una mente ordenadora, pero le reprocha no explotarla: una vez planteado el nous, Anaxágoras vuelve a explicar los fenómenos concretos de manera puramente mecánica.",
    },
    {
      type: "info",
      continues: true,
      title: "Los pluralistas: salvar el cambio",
      body: "Demócrito de Abdera completa el cuadro con el atomismo, heredado de su maestro Leucipo. Toda la realidad física está hecha de átomos: partículas indivisibles, eternas e infinitamente numerosas, que sólo se diferencian por su forma, tamaño y posición, y que se combinan al azar en el vacío. «Por convención lo dulce, por convención lo amargo […]; en realidad, átomos y vacío» (DK B9). El color, el sabor y la temperatura no son propiedades del átomo mismo, sino el efecto que sus combinaciones producen en quien percibe.",
    },
    {
      type: "info",
      continues: true,
      title: "Los pluralistas: salvar el cambio",
      body: "De ese materialismo estricto —nada de dioses ni de propósitos, sólo átomos y azar— Demócrito extrae, sin embargo, una ética serena: llama euthymía, «buen ánimo», al objetivo de la vida buena, un estado de calma interior que no depende de bienes externos ni de creencias sobrenaturales, y que va a anticipar de cerca al placer moderado de los epicúreos.",
    },
    {
      type: "classify",
      question: "¿Cada explicación es mecanicista o teleológica?",
      groups: ["Mecanicista", "Teleológica"],
      items: [
        { text: "Átomos que chocan y se combinan al azar en el vacío", group: 0 },
        { text: "Ningún propósito dirige la formación del mundo", group: 0 },
        { text: "Las cualidades sensibles dependen de quien percibe", group: 0 },
        { text: "Una mente (nous) ordena las semillas hacia un fin", group: 1 },
        { text: "El orden del cosmos responde a un propósito, no sólo a una causa", group: 1 },
      ],
      explain: "Demócrito explica todo por fuerzas ciegas y azar; Anaxágoras, en cambio, necesita una inteligencia ordenadora para que la mezcla infinita de semillas no sea un caos: las dos grandes respuestas que la filosofía occidental sigue discutiendo.",
    },
    {
      type: "match",
      question: "Uní cada presocrático con su aporte central",
      pairs: [
        { left: "Tales", right: "El agua como principio único de todas las cosas" },
        { left: "Anaximandro", right: "El ápeiron: un principio indefinido y sin límites" },
        { left: "Heráclito", right: "El logos: la razón común detrás del cambio constante" },
        { left: "Parménides", right: "El ser es uno, eterno e inmóvil; el cambio es ilusión" },
        { left: "Demócrito", right: "Átomos indivisibles que se combinan al azar" },
      ],
      explain: "De Tales a Demócrito, doscientos años de presocráticos van radicalizando la misma pregunta —qué hay debajo del cambio— hasta agotar casi todas las respuestas posibles: uno o muchos, elemento concreto o principio abstracto, azar o propósito.",
    },
    {
      type: "info",
      title: "El legado presocrático",
      body: "Entre Tales (ca. 600 a. C.) y Demócrito (ca. 400 a. C.) transcurren apenas doscientos años, pero en ellos queda planteada buena parte de la agenda con la que la filosofía occidental trabaja desde entonces. No es casual que las ciencias posteriores —astronomía, física, y mucho después química y biología— nazcan como derivaciones tardías de esta misma indagación sobre la physis.",
    },
    {
      type: "info",
      continues: true,
      title: "El legado presocrático",
      body: "Queda planteada, en primer lugar, una agenda **metafísica**: si el mundo es mecánico o teleológico, si hay un único principio o muchos. Queda planteada también una agenda **epistemológica**: los milesios y los pluralistas son, a grandes rasgos, empiristas que confían en los sentidos, mientras que Parménides y Zenón son los primeros racionalistas, que les niegan todo crédito —una tensión que va a recorrer el resto de la filosofía antigua.",
    },
    {
      type: "info",
      continues: true,
      title: "El legado presocrático",
      body: "Pero queda planteada, sobre todo, una tercera pregunta que todavía no respondimos: la de Anaximandro, «se pagan penitencia unas a otras por su injusticia», ya habla en términos de justicia y no sólo de física. Si el cosmos tiene un orden, ¿es ese orden también un orden moral? Es la pregunta que retomamos en la próxima clase, antes incluso de que exista una palabra griega para «ética».",
    },
  ],
};
