export default {
  num: 13,
  transcript: null,
  title: "Aristóteles: la vida buena y el término medio",
  source: "",
  feed: [
    {
      type: "info",
      title: "La función propia del ser humano",
      body: "Aristóteles empieza su Ética a Nicómaco preguntando cuál es el bien más alto para un ser humano, y responde con el argumento de la función (érgon). Así como el bien de un cuchillo es cortar bien, el bien de cualquier cosa depende de su función propia. La función propia del ser humano, lo que ningún otro ser vivo hace, es la actividad racional.",
    },
    {
      type: "info",
      title: "La eudaimonía no es un sentimiento",
      body: "De ahí sale la definición de **eudaimonía**, la palabra griega que se suele traducir como «felicidad»: no un estado de ánimo pasajero, sino la actividad del alma de acuerdo con la virtud, sostenida a lo largo de una vida completa. Una sola buena acción, o un solo día feliz, no alcanzan: hace falta toda una vida bien vivida.",
    },
    {
      type: "quiz",
      question: "¿En qué se apoya el argumento de la función para definir el bien humano?",
      options: [
        "en que el bien de algo depende de cumplir bien su función propia",
        "en una votación realizada entre los ciudadanos atenienses",
        "en un oráculo consultado especialmente para esta pregunta",
        "en la opinión personal de Alejandro Magno sobre la felicidad",
      ],
      answer: 0,
      explain: "Igual que el bien de un cuchillo es cortar bien, el bien de un ser humano depende de su función propia: la actividad racional, lo único que ningún otro ser vivo hace del mismo modo.",
    },
    {
      type: "quiz",
      question: "Para Aristóteles, ¿qué es la eudaimonía?",
      options: [
        "una actividad sostenida a lo largo de toda una vida",
        "un sentimiento intenso de alegría que dura sólo un instante",
        "la riqueza y el poder acumulados durante toda una vida",
        "el estado de ánimo que se logra evitando cualquier tipo de esfuerzo",
      ],
      answer: 0,
      explain: "No es un estado de ánimo pasajero: es la actividad del alma de acuerdo con la virtud, sostenida a lo largo de una vida entera. Un solo buen día, o una sola buena acción, no alcanzan para llamarla eudaimonía.",
    },
    {
      type: "info",
      title: "La virtud se aprende haciendo",
      body: "Contra Sócrates, que sostenía que la virtud es un tipo de conocimiento, Aristóteles insiste en que no basta con saber qué es la valentía para ser valiente. «Nos volvemos justos practicando actos justos, valientes practicando actos valientes»: la virtud es un hábito (hexis), una disposición estable que se forma por repetición, del mismo modo en que se aprende cualquier oficio.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia Aristóteles de Sócrates respecto de cómo se adquiere la virtud?",
      options: [
        "para Aristóteles, la virtud se forma por hábito, no basta con saberla",
        "para Aristóteles, la virtud es innata y no se puede modificar nunca",
        "para Aristóteles, sólo los filósofos pueden llegar a ser virtuosos",
        "para Aristóteles, la virtud no tiene ninguna relación con la conducta",
      ],
      answer: 0,
      explain: "Sócrates sostenía que la virtud es un tipo de conocimiento. Aristóteles responde que no basta con saber qué es la valentía para ser valiente: la virtud es un hábito que se forma practicando, como cualquier oficio.",
    },
    {
      type: "info",
      title: "El término medio",
      body: "Cada virtud moral, sostiene Aristóteles, es un término medio entre dos vicios: uno por exceso y otro por defecto. El valor es el término medio entre la cobardía, que teme demasiado, y la temeridad, que no teme lo suficiente. La generosidad es el término medio entre la tacañería y el derroche.",
    },
    {
      type: "info",
      continues: true,
      title: "El término medio",
      body: "Ese término medio no es un punto matemático fijo, igual para todos: depende de la persona, la situación y las circunstancias, y hay que determinarlo cada vez con buen juicio. Y hay acciones para las que no existe ningún término medio posible, porque ya son malas en sí mismas: no hay una cantidad moderada de asesinato o de traición.",
    },
    {
      type: "quiz",
      question: "Según la doctrina del término medio, ¿qué es el valor?",
      options: [
        "el término medio entre la cobardía y la temeridad",
        "el punto matemático exacto entre dos extremos numéricos",
        "un vicio por exceso frente a la prudencia razonable",
        "lo mismo que la temeridad, sólo que con otro nombre",
      ],
      answer: 0,
      explain: "La cobardía teme demasiado; la temeridad, muy poco. El valor es el término medio entre ambos vicios, uno por exceso y otro por defecto, aunque ese punto medio no sea el mismo para todas las personas ni situaciones.",
    },
    {
      type: "quiz",
      question: "¿Qué excepción reconoce Aristóteles a la doctrina del término medio?",
      options: [
        "algunas acciones son malas en sí mismas y no admiten término medio",
        "el término medio siempre es exactamente igual para todas las personas",
        "la doctrina no se aplica nunca a las virtudes, sólo a los vicios",
        "sólo los filósofos pueden determinar el término medio correcto",
      ],
      answer: 0,
      explain: "Acciones como el asesinato o la traición son malas en sí mismas: no existe una cantidad moderada de ellas. El término medio se aplica a las virtudes, no a acciones que ya son vicios sin importar su grado.",
    },
    {
      type: "info",
      title: "Sabiduría práctica: la phrónesis",
      body: "Ese buen juicio para encontrar el término medio en cada situación concreta tiene, para Aristóteles, un nombre propio: **phrónesis**, la sabiduría práctica. Es distinta de la sophía, la sabiduría teórica que contempla verdades universales e inmutables: la phrónesis se ocupa de lo particular y cambiante, y no se puede reducir a una fórmula general que sirva para cualquier caso.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la phrónesis de la sophía?",
      options: [
        "la phrónesis se ocupa de lo particular; la sophía, de lo universal",
        "la phrónesis es innata; la sophía se adquiere sólo por hábito",
        "la phrónesis sólo la tienen los sofistas; la sophía, los filósofos",
        "la phrónesis y la sophía son, en Aristóteles, exactamente lo mismo",
      ],
      answer: 0,
      explain: "La sophía contempla verdades universales e inmutables; la phrónesis se ocupa de lo particular y cambiante, buscando el término medio en cada situación concreta, algo que ninguna fórmula general puede resolver de antemano.",
    },
    {
      type: "short",
      question: "¿Cómo llama Aristóteles a la sabiduría práctica que permite hallar el término medio en cada situación concreta?",
      answers: ["phronesis", "fronesis"],
      explain: "Distinta de la sophía, sabiduría teórica sobre lo universal, la phrónesis se ocupa de lo particular y cambiante, y no se puede reducir a una fórmula general que sirva para cualquier caso.",
    },
    {
      type: "info",
      title: "¿Existe la debilidad de la voluntad?",
      body: "Sócrates sostenía que nadie hace el mal a sabiendas, sólo por ignorancia. Aristóteles matiza esa tesis: reconoce que la experiencia muestra personas que actúan en contra de su propio mejor juicio, la **akrasia** o debilidad de la voluntad. Pero sostiene que, en el momento exacto de actuar mal, el conocimiento de esa persona está de algún modo nublado, como el de alguien dormido o borracho: no lo pierde del todo, pero tampoco lo tiene disponible de verdad.",
    },
    {
      type: "classify",
      question: "¿Cada vicio es por exceso o por defecto respecto de su virtud?",
      groups: ["Vicio por exceso", "Vicio por defecto"],
      items: [
        { text: "Temeridad (frente al valor)", group: 0 },
        { text: "Cobardía (frente al valor)", group: 1 },
        { text: "Derroche (frente a la generosidad)", group: 0 },
        { text: "Tacañería (frente a la generosidad)", group: 1 },
      ],
      explain: "Cada virtud queda flanqueada por dos vicios opuestos: uno que se pasa de la medida (temeridad, derroche) y otro que se queda corto (cobardía, tacañería). La virtud es siempre el término medio entre ambos.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que describe",
      pairs: [
        { left: "Eudaimonía", right: "Actividad del alma según la virtud, a lo largo de una vida completa" },
        { left: "Hexis", right: "El hábito estable que se forma practicando una y otra vez" },
        { left: "Phrónesis", right: "El buen juicio para hallar el término medio en cada caso" },
        { left: "Akrasia", right: "Actuar en contra del propio mejor juicio" },
      ],
      explain: "Los cuatro términos describen distintas piezas de la misma ética: la meta (eudaimonía), cómo se forma la virtud (hexis), cómo se aplica en cada caso (phrónesis) y qué pasa cuando falla (akrasia).",
    },
    {
      type: "info",
      title: "El cierre del programa aristotélico",
      body: "Con esto se completa el recorrido por Aristóteles: sustancia, causas, Motor Inmóvil, alma y ahora ética, todo apoyado en las mismas herramientas de potencia y acto, observación y término medio. La próxima clase cambia de siglo y de escenario. Alejandro Magno ha muerto, el mundo griego se fragmenta, y la filosofía helenística busca la tranquilidad del individuo antes que el buen gobierno de la ciudad.",
    },
  ],
};
