export default {
  num: 6,
  transcript: null,
  title: "Platón: el mundo de las Formas",
  source: "",
  feed: [
    {
      type: "info",
      title: "Qué son las Formas",
      body: "La línea dividida de la clase pasada terminaba en un punto ciego: qué es exactamente eso que la nóesis conoce en su tramo más alto. La respuesta de Platón son las **Formas** (o Ideas): modelos eternos, inmutables e inmateriales, de los que las cosas sensibles son copias imperfectas. Hay una Forma de la Belleza, una de la Justicia, una del Círculo, y de cada una de ellas participan, de manera parcial, las muchas cosas bellas, justas o circulares que vemos.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué son las Formas",
      body: "En el Fedón, Platón defiende esta idea con un argumento sencillo. Dos palos pueden parecer iguales, pero ningún par de palos es perfectamente igual: uno siempre es, mirado de cerca, un poquito más largo. Y sin embargo entendemos perfectamente qué significa «igual» en sentido estricto. Esa noción perfecta no puede venir de la experiencia, que sólo ofrece igualdades aproximadas: tiene que ser algo que el alma ya conocía de antes, la Forma de la Igualdad misma.",
    },
    {
      type: "quiz",
      question: "¿Qué prueba, para Platón, el hecho de que ningún par de palos sea perfectamente igual y sin embargo entendamos qué es «igual»?",
      options: [
        "que la geometría es una ciencia inútil para la vida práctica",
        "que la noción perfecta de igualdad no viene de la experiencia",
        "que los sentidos nunca pueden equivocarse sobre las medidas",
        "que Heráclito tenía razón al negar cualquier tipo de orden",
      ],
      answer: 1,
      explain: "La experiencia sólo ofrece igualdades aproximadas, nunca perfectas. Si aun así entendemos qué es la igualdad en sentido estricto, esa noción tiene que venir de otro lado: el alma ya la conocía, la Forma de la Igualdad misma.",
    },
    {
      type: "info",
      title: "El Bien: el sol del mundo inteligible",
      body: "En la República, Platón compara a la Forma más alta de todas, la del **Bien**, con el sol. Así como el sol no sólo ilumina las cosas visibles sino que además las hace crecer y existir, el Bien no sólo permite conocer las demás Formas: les da su propio ser. Está, dice Platón en una frase célebre, «más allá del ser» —ni siquiera es una Forma más entre otras, sino la fuente de todas.",
    },
    {
      type: "quiz",
      question: "En la analogía del sol, ¿qué función cumple el Bien respecto de las demás Formas?",
      options: [
        "las hace conocibles y además les da su propio ser",
        "las destruye una por una hasta que sólo él queda",
        "las reemplaza por completo en el mundo sensible",
        "las vuelve visibles únicamente a los sofistas",
      ],
      answer: 0,
      explain: "Igual que el sol no sólo ilumina lo visible sino que lo hace crecer y existir, el Bien no sólo permite conocer las demás Formas: es la fuente de la que reciben su propio ser, «más allá del ser» mismo.",
    },
    {
      type: "info",
      title: "El mito de la caverna",
      body: "Para dramatizar el mismo recorrido, Platón imagina, también en la República, a unos prisioneros encadenados desde la infancia en una caverna, viendo sólo las sombras que proyecta un fuego a sus espaldas sobre la pared frente a ellos. Para esos prisioneros, esas sombras son toda la realidad que conocen.",
    },
    {
      type: "info",
      continues: true,
      title: "El mito de la caverna",
      body: "Uno de ellos es liberado a la fuerza y arrastrado hacia afuera. El proceso es doloroso: primero lo encandila el fuego, después la luz del sol. Sólo al final logra mirar el sol mismo, que representa al Bien, la fuente última de todo lo que ahora puede ver con claridad.",
    },
    {
      type: "info",
      continues: true,
      title: "El mito de la caverna",
      body: "Si ese prisionero liberado vuelve a la caverna para contarles a los demás lo que vio, no le van a creer. Peor todavía: como sus ojos ya no están acostumbrados a la oscuridad, va a parecer torpe frente a ellos, y si insiste demasiado, hasta pueden llegar a matarlo. Platón escribe esto años después de la ejecución de Sócrates, y no deja demasiadas dudas sobre a quién está pensando.",
    },
    {
      type: "quiz",
      question: "¿Qué le puede pasar, según el mito, al prisionero liberado que vuelve a la caverna a contar lo que vio?",
      options: [
        "que los demás no le crean, y hasta lleguen a matarlo",
        "que se vuelva automáticamente el gobernante de la caverna",
        "que recupere de inmediato la vista que tenía antes de salir",
        "que el fuego se apague apenas él vuelve a entrar",
      ],
      answer: 0,
      explain: "Sus ojos, acostumbrados ya a la luz del sol, lo hacen parecer torpe en la oscuridad. Platón, escribiendo después de la muerte de Sócrates, deja pocas dudas sobre en quién está pensando con esta escena.",
    },
    {
      type: "short",
      question: "¿Cómo se llama el mito de Platón sobre los prisioneros que sólo ven sombras proyectadas en una pared?",
      answers: ["la caverna", "caverna"],
      explain: "Los prisioneros toman las sombras por toda la realidad. El ascenso de uno de ellos hacia la luz del sol dramatiza el recorrido completo de la línea dividida, de la opinión al conocimiento del Bien.",
    },
    {
      type: "info",
      title: "Un problema que el propio Platón se plantea",
      body: "¿Cómo participan exactamente muchas cosas bellas de una sola Forma de la Belleza? En el diálogo Parménides, Platón hace que un Parménides ya anciano le señale a un Sócrates joven un problema serio, conocido después como el argumento del **Tercer Hombre**: si dos hombres son hombres porque se parecen a la Forma del Hombre, esa semejanza misma tendría que explicarse por una nueva Forma que englobe a los dos primeros y a la Forma original, y así hasta el infinito.",
    },
    {
      type: "quiz",
      question: "¿Qué problema plantea el argumento del Tercer Hombre contra la teoría de las Formas?",
      options: [
        "una regresión infinita de Formas para explicar cada semejanza",
        "que no existe ningún hombre real fuera de Atenas y Esparta",
        "que las Formas cambian de nombre según la ciudad que se visite",
        "que Sócrates no puede participar de la Forma del Hombre",
      ],
      answer: 0,
      explain: "Si dos cosas se parecen a una Forma por compartir un rasgo con ella, esa nueva semejanza exige otra Forma que la explique, y así sucesivamente sin final: una regresión infinita que la teoría original no había previsto.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al mundo sensible o al mundo de las Formas?",
      groups: ["Mundo sensible", "Mundo de las Formas"],
      items: [
        { text: "Cambia constantemente y nunca es del todo perfecto", group: 0 },
        { text: "Es eterno, inmutable e inmaterial", group: 1 },
        { text: "Se conoce por los sentidos, como opinión", group: 0 },
        { text: "Se conoce por la razón pura, como conocimiento", group: 1 },
        { text: "Las cosas sensibles participan de él de modo imperfecto", group: 1 },
      ],
      explain: "El mundo sensible se capta con los sentidos y siempre está en proceso de cambio; el mundo de las Formas se capta con la razón pura y permanece siempre igual a sí mismo, como modelo del que las cosas participan.",
    },
    {
      type: "match",
      question: "Uní cada elemento con lo que ilustra en la teoría de Platón",
      pairs: [
        { left: "Los palos iguales", right: "Ningún par de cosas sensibles es perfectamente igual" },
        { left: "El sol", right: "Imagen del Bien, que da el ser a las demás Formas" },
        { left: "La caverna", right: "El ascenso de la opinión al conocimiento, y el riesgo de volver" },
        { left: "El Tercer Hombre", right: "La autocrítica de Platón a su propia teoría de la participación" },
      ],
      explain: "Las cuatro imágenes atacan el mismo problema desde ángulos distintos: qué son las Formas, cómo se conocen, qué cuesta llegar a conocerlas, y qué grietas tiene la teoría que las explica.",
    },
    {
      type: "info",
      title: "Lo que queda en pie",
      body: "Platón no resuelve el problema del Tercer Hombre en ningún diálogo que se conserve, y los especialistas siguen discutiendo si lo consideró fatal para su teoría o apenas una dificultad técnica. Lo que sí queda firme hasta el final de su obra es la convicción de fondo: que detrás del mundo que cambia hay un orden inteligible y estable, y que conocerlo de verdad es la tarea más alta a la que puede aspirar una vida humana.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que queda en pie",
      body: "Falta todavía una pregunta: qué es, exactamente, eso en nosotros capaz de alcanzar ese conocimiento. La próxima clase la dedicamos al alma.",
    },
  ],
};
