export default {
  num: 3,
  transcript: 3,
  title: "Los sofistas: nómos, phýsis y el poder de la palabra",
  source: "",
  feed: [
    {
      type: "info",
      title: "Quiénes son los sofistas",
      body: "Hacia mediados del siglo V a. C., en el apogeo de la democracia ateniense, aparece una nueva figura: el sofista, un maestro itinerante que viaja de ciudad en ciudad enseñando **aretē**, la excelencia necesaria para triunfar en la vida pública, a cambio de una paga. Antes de ellos, nadie cobraba por enseñar sabiduría. Sócrates y Platón se lo van a reprochar durante siglos.",
    },
    {
      type: "info",
      continues: true,
      title: "Quiénes son los sofistas",
      body: "La demanda tiene una causa concreta. En una democracia donde las decisiones se votan en la asamblea y los juicios se deciden ante jurados populares, saber hablar en público —persuadir, argumentar, refutar— se vuelve una habilidad tan valiosa como cualquier oficio. Los sofistas responden a esa necesidad enseñando retórica, argumentación y, según ellos mismos, la propia virtud política.",
    },
    {
      type: "quiz",
      question: "¿Por qué surge la demanda de maestros como los sofistas justo en la Atenas democrática del siglo V a. C.?",
      options: [
        "porque saber persuadir en la asamblea y los tribunales se vuelve decisivo",
        "porque el Estado ateniense exigía un examen de filosofía para votar",
        "porque los templos dejaron de formar sacerdotes y hacía falta reemplazo",
        "porque las escuelas de Esparta habían cerrado sus puertas a los atenienses",
      ],
      answer: 0,
      explain: "En una democracia que decide por votación y juicio popular, saber hablar en público es una herramienta de poder real. Los sofistas profesionalizan la enseñanza de esa habilidad, algo que antes de ellos nadie cobraba por hacer.",
    },
    {
      type: "short",
      question: "¿Con qué palabra griega se nombra la excelencia o virtud que los sofistas prometían enseñar?",
      answers: ["arete", "areté", "aretē"],
      explain: "En Homero nombraba la excelencia de cualquier función, sin connotación moral. Con los sofistas se concentra en la virtud política, y se vuelve el centro de la disputa con Sócrates, que niega poder enseñarla mientras no se sepa qué es.",
    },
    {
      type: "info",
      title: "Protágoras: el hombre, medida de todas las cosas",
      body: "Protágoras de Abdera (ca. 490-420 a. C.), el más respetado de los sofistas, formula la frase que resume su filosofía: «el hombre es la medida de todas las cosas: de las que son, en cuanto que son, y de las que no son, en cuanto que no son» (DK B1). Lo que a mí me parece frío, a otro puede parecerle templado, y ninguno de los dos está simplemente equivocado. Cada percepción es verdadera para quien la tiene.",
    },
    {
      type: "info",
      continues: true,
      title: "Protágoras: el hombre, medida de todas las cosas",
      body: "La misma cautela se extiende a la religión. «Sobre los dioses no puedo saber ni que existen ni que no existen, ni qué forma tienen» (DK B4), escribe al comienzo de un tratado que le costó, según la tradición, ser expulsado de Atenas. No es ateísmo, sino agnosticismo declarado: suspende el juicio ante una pregunta que considera indecidible.",
    },
    {
      type: "quiz",
      question: "El relativismo de Protágoras («el hombre es la medida de todas las cosas») sostiene que…",
      options: [
        "cada percepción es verdadera para quien la tiene, sin un criterio único",
        "sólo los filósofos pueden acceder a la verdad objetiva del mundo",
        "la verdad depende exclusivamente de lo que decidan los dioses",
        "todas las percepciones son falsas salvo las confirmadas por la ciencia",
      ],
      answer: 0,
      explain: "Si lo que a mí me parece frío a otro le parece templado, ninguno está simplemente equivocado: no hay una verdad única e independiente de quien percibe, sino tantas medidas como observadores.",
    },
    {
      type: "info",
      continues: true,
      title: "Protágoras: el hombre, medida de todas las cosas",
      body: "En el diálogo que Platón le dedica, Protágoras defiende con un mito por qué la virtud política se puede enseñar a todos, y no sólo a unos pocos expertos. Cuenta que Zeus, viendo que los hombres se destruían entre sí por falta de organización política, repartió el pudor (aidós) y la justicia (díke) entre todos por igual, a diferencia de otras artes, reservadas a especialistas.",
    },
    {
      type: "quiz",
      question: "En el mito de Protágoras, ¿por qué Zeus reparte el pudor y la justicia entre todos los hombres, y no sólo entre unos pocos?",
      options: [
        "porque sin ellos ninguna ciudad logra sostenerse unida",
        "porque quería castigar a los especialistas en otras artes",
        "porque así lo exigía un oráculo consultado en Delfos",
        "porque los dioses no podían decidir a quién dárselos",
      ],
      answer: 0,
      explain: "A diferencia de otros oficios, reservados a especialistas, la virtud política tiene que repartirse entre todos: sin un mínimo de pudor y justicia compartidos, ninguna comunidad política puede sostenerse. Es, de hecho, un argumento a favor de la democracia.",
    },
    {
      type: "info",
      title: "Gorgias: el poder de la palabra",
      body: "Gorgias de Leontini (ca. 485-380 a. C.) es, ante todo, un maestro de retórica, no de virtud. En su Encomio de Helena defiende, como ejercicio retórico, a la mujer más culpada de la literatura griega: si Helena se fue con Paris fue por la fuerza del logos, un hechizo capaz de gobernar el alma como un fármaco gobierna el cuerpo, para bien o para mal.",
    },
    {
      type: "info",
      continues: true,
      title: "Gorgias: el poder de la palabra",
      body: "Ese mismo virtuosismo lo lleva, en el tratado Sobre el no-ser, a un extremo casi paródico. Argumenta, con toda la maquinaria de la lógica, que nada existe, que si algo existiera no podría conocerse, y que si pudiera conocerse no podría comunicarse a otro. Nadie, ni el propio Gorgias probablemente, toma esas tesis como una posición filosófica seria. Son una demostración de fuerza, la prueba de que la retórica puede defender cualquier posición.",
    },
    {
      type: "quiz",
      question: "¿Qué demuestra Gorgias al defender, en Sobre el no-ser, que nada existe?",
      options: [
        "que la retórica puede argumentar cualquier posición",
        "que efectivamente nada existe, ni siquiera el propio Gorgias",
        "que Parménides tenía razón al negar la realidad del cambio",
        "que el lenguaje humano es incapaz de nombrar ninguna cosa",
      ],
      answer: 0,
      explain: "Nadie toma en serio esas tres tesis como filosofía. Son, más bien, una exhibición de virtuosismo retórico: si se puede argumentar con rigor que nada existe, se puede argumentar cualquier cosa.",
    },
    {
      type: "info",
      title: "Nómos o phýsis: ¿quién manda?",
      body: "La distinción entre nómos y physis, que Heráclito ya insinuaba, se vuelve con los sofistas un arma de doble filo. Antifonte sostiene que las leyes son un acuerdo conveniente pero artificial: conviene respetarlas cuando hay testigos, porque violarlas trae castigo. Pero la physis, el propio interés, no deja de operar por debajo cuando nadie mira.",
    },
    {
      type: "info",
      continues: true,
      title: "Nómos o phýsis: ¿quién manda?",
      body: "Calicles, un personaje del diálogo Gorgias de Platón, lleva la idea todavía más lejos. Para él, el nómos es un invento de los débiles y de la mayoría, diseñado precisamente para atarle las manos a los pocos que, por naturaleza, son más fuertes y merecen más. La physis muestra en cualquier otra especie que el más fuerte domina al más débil; sólo la convención humana llama a eso «injusticia».",
    },
    {
      type: "quiz",
      question: "Para Calicles, ¿qué relación hay entre el nómos y la physis?",
      options: [
        "el nómos es un invento de los débiles para frenar a los fuertes",
        "el nómos expresa fielmente lo que la physis dicta en cada caso",
        "la physis no existe; sólo hay convenciones humanas variables",
        "el nómos y la physis siempre coinciden en todas las ciudades",
      ],
      answer: 0,
      explain: "Calicles invierte el argumento habitual: la physis muestra que el más fuerte domina, y llama «justicia» a eso. El nómos, para él, es sólo el modo en que la mayoría débil consigue atarle las manos a los pocos fuertes.",
    },
    {
      type: "classify",
      question: "¿Cada afirmación pone el peso en el nómos o en la phýsis?",
      groups: ["Nómos", "Phýsis"],
      items: [
        { text: "La virtud política mantiene unida a la ciudad (Protágoras)", group: 0 },
        { text: "Sin normas compartidas, los hombres se destruyen entre sí", group: 0 },
        { text: "Conviene respetar la ley sólo cuando hay testigos (Antifonte)", group: 1 },
        { text: "El más fuerte domina por naturaleza; la ley sólo lo frena (Calicles)", group: 1 },
        { text: "La ley es un invento de los débiles para protegerse de los fuertes", group: 1 },
      ],
      explain: "Protágoras defiende el nómos como lo que sostiene a la ciudad. Antifonte y Calicles invierten el argumento y ponen el peso en la physis, el interés o la fuerza natural, tratando la ley como una convención secundaria o hasta un obstáculo.",
    },
    {
      type: "match",
      question: "Uní cada sofista con su tesis central",
      pairs: [
        { left: "Protágoras", right: "El hombre es la medida de todas las cosas" },
        { left: "Gorgias", right: "La retórica puede defender cualquier posición" },
        { left: "Antifonte", right: "La ley conviene respetarla sólo si hay testigos" },
        { left: "Calicles", right: "El más fuerte domina por naturaleza, no por ley" },
      ],
      explain: "Los cuatro comparten el mismo terreno —el poder de la palabra y la pregunta por si la justicia es natural o convencional— pero llegan a conclusiones muy distintas, de la defensa de la democracia a su cuestionamiento más radical.",
    },
    {
      type: "info",
      title: "La sombra de los sofistas",
      body: "La fama de los sofistas no sobrevivió bien a la posteridad, y buena parte de la culpa es de Platón: en sus diálogos los pinta casi siempre como charlatanes que venden certezas que no tienen, indiferentes a si lo que enseñan es verdadero con tal de que convenza. La propia palabra «sofista» termina siendo, en español y otras lenguas, sinónimo de argumentador tramposo.",
    },
    {
      type: "info",
      continues: true,
      title: "La sombra de los sofistas",
      body: "Pero fueron, también, los primeros profesionales de la educación democrática: enseñaron a pensar los propios fundamentos de la ley, la religión y la moral como preguntas abiertas, no como datos heredados sin más. Esa misma actitud crítica es, en el fondo, terreno común con la figura que aparece justo después de ellos, y a la que la próxima clase le dedicamos entera: Sócrates.",
    },
  ],
};
