export default {
  num: 12,
  transcript: null,
  title: "Aristóteles: el alma como forma del cuerpo",
  source: "",
  feed: [
    {
      type: "info",
      title: "El alma no es una cosa aparte",
      body: "Frente a Platón, para quien el alma es una sustancia inmortal encerrada temporalmente en un cuerpo, Aristóteles propone algo distinto. El alma, dice en su tratado Sobre el alma, es «la actualidad primera de un cuerpo natural que tiene vida en potencia»: no una cosa dentro de otra cosa, sino la forma misma de un cuerpo vivo, aquello que lo organiza y lo hace estar vivo.",
    },
    {
      type: "info",
      continues: true,
      title: "El alma no es una cosa aparte",
      body: "A esta idea de que toda sustancia natural es, inseparablemente, forma y materia —nunca una sin la otra— se la llama después **hilemorfismo** (de hyle, materia, y morphé, forma). El alma es la forma; el cuerpo, la materia; juntos, y sólo juntos, son un ser vivo.",
    },
    {
      type: "quiz",
      question: "Para Aristóteles, ¿qué es el alma?",
      options: [
        "la forma de un cuerpo vivo, lo que lo organiza y lo hace estar vivo",
        "una sustancia inmortal, separada del cuerpo, que existió antes de él",
        "un tipo particular de átomo más fino que los demás",
        "el nombre griego para lo que hoy se llama sistema nervioso",
      ],
      answer: 0,
      explain: "A diferencia de Platón, para quien el alma es una sustancia aparte, Aristóteles la define como la forma de un cuerpo vivo: no algo encerrado dentro del cuerpo, sino aquello que organiza esa materia y la hace estar viva.",
    },
    {
      type: "info",
      title: "La analogía del ojo",
      body: "Aristóteles compara la relación entre alma y cuerpo con la relación entre la vista y el ojo: si el ojo fuera un animal completo, la vista sería su alma, y un ojo ciego sería, en un sentido importante, ya no un ojo de verdad, sino sólo su materia. De la misma manera, un cuerpo sin alma no es un cuerpo vivo con algo menos: es un cadáver, materia que perdió la forma que la organizaba.",
    },
    {
      type: "quiz",
      question: "En la analogía del ojo, ¿qué representa la vista?",
      options: [
        "lo que el alma es para el cuerpo entero",
        "lo que la materia es para cualquier sustancia",
        "un ejemplo de lo que Aristóteles llama causa eficiente",
        "la parte del alma exclusiva de las plantas",
      ],
      answer: 0,
      explain: "Si el ojo fuera un animal completo, la vista sería su alma: la forma que lo hace ser lo que es y funcionar como tal. Un ojo ciego, o un cuerpo sin alma, son sólo materia que perdió esa organización.",
    },
    {
      type: "info",
      title: "Tres niveles de alma",
      body: "Esta forma-alma no es la misma en todos los seres vivos: Aristóteles distingue tres niveles, cada uno más complejo que el anterior. El alma nutritiva, presente en plantas, animales y personas, se ocupa de la nutrición, el crecimiento y la reproducción. El alma sensitiva, presente en animales y personas, suma la percepción, el deseo y el movimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Tres niveles de alma",
      body: "El alma racional, exclusiva de los seres humanos, suma a las dos anteriores la capacidad de razonar y comprender. Cada nivel incluye al anterior: quien tiene alma racional también nutre su cuerpo y percibe el mundo, pero no al revés. Una planta no percibe nada, y un animal no razona sobre lo que percibe.",
    },
    {
      type: "quiz",
      question: "Según la jerarquía de Aristóteles, ¿qué tienen en común una planta, un animal y una persona?",
      options: [
        "las tres poseen alma nutritiva: se alimentan, crecen y se reproducen",
        "las tres poseen alma racional, aunque en distinto grado",
        "las tres perciben el mundo mediante los sentidos",
        "ninguna de las tres tiene ningún tipo de alma",
      ],
      answer: 0,
      explain: "El alma nutritiva es el nivel más básico, común a plantas, animales y personas. El alma sensitiva (percepción, deseo, movimiento) la suman animales y personas; la racional, sólo las personas.",
    },
    {
      type: "info",
      title: "De dónde viene el conocimiento",
      body: "A diferencia de Platón, para quien aprender es recordar un conocimiento que el alma ya tenía, Aristóteles sostiene que todo conocimiento empieza en los sentidos. Compara al intelecto, antes de aprender, con una tablilla de escribir en la que todavía no se escribió nada: no trae ningún contenido de fábrica, sólo la capacidad de recibirlo.",
    },
    {
      type: "quiz",
      question: "¿Con qué compara Aristóteles al intelecto humano antes de aprender algo?",
      options: [
        "con una tablilla de escribir en la que todavía no se escribió nada",
        "con un espejo que refleja directamente las Formas eternas",
        "con un río que fluye siempre en la misma dirección",
        "con un templo ya construido y completamente decorado",
      ],
      answer: 0,
      explain: "A diferencia de la anamnesis platónica, donde el alma ya trae un saber de antes, Aristóteles sostiene que el intelecto empieza vacío, como una tablilla sin escribir, y se llena únicamente a partir de la experiencia sensible.",
    },
    {
      type: "info",
      title: "Un cabo suelto: el intelecto agente",
      body: "Hay, sin embargo, un pasaje célebremente oscuro en el que Aristóteles distingue, dentro del intelecto, dos partes: una que recibe las formas de las cosas, el intelecto paciente, y otra que las «ilumina» y las hace pensables, el intelecto agente. A esta segunda la describe como separable, no mezclada con el cuerpo, e inmortal.",
    },
    {
      type: "info",
      continues: true,
      title: "Un cabo suelto: el intelecto agente",
      body: "Ni el propio Aristóteles desarrolla mucho más esta idea, y comentaristas posteriores —árabes, judíos y cristianos— van a discutir durante siglos qué quiso decir exactamente. Es, para un sistema tan cuidadoso como el suyo, una grieta notable: casi la única puerta que deja abierta a algo parecido a la inmortalidad personal que Platón defendía.",
    },
    {
      type: "quiz",
      question: "¿Por qué es tan discutido el pasaje sobre el intelecto agente en Aristóteles?",
      options: [
        "porque lo describe como separable e inmortal, sin explicarlo del todo",
        "porque niega por completo la existencia de cualquier tipo de intelecto",
        "porque lo identifica sin dudas con el Motor Inmóvil mismo",
        "porque afirma que sólo los filósofos griegos lo poseen",
      ],
      answer: 0,
      explain: "Aristóteles lo describe como separable, no mezclado con el cuerpo e inmortal, pero no desarrolla la idea. Comentaristas árabes, judíos y cristianos posteriores van a discutir durante siglos qué quiso decir exactamente.",
    },
    {
      type: "classify",
      question: "¿Cada afirmación sobre el alma es de Platón o de Aristóteles?",
      groups: ["Platón", "Aristóteles"],
      items: [
        { text: "El alma es una sustancia separable, previa al cuerpo", group: 0 },
        { text: "El alma es la forma del cuerpo, inseparable de él", group: 1 },
        { text: "Aprender es recordar un conocimiento anterior", group: 0 },
        { text: "Todo conocimiento empieza en la experiencia sensible", group: 1 },
        { text: "El alma entera sobrevive, inmortal, a la muerte del cuerpo", group: 0 },
      ],
      explain: "El desacuerdo de fondo sobre las Formas se repite en la psicología: para Platón el alma es una sustancia aparte y previa; para Aristóteles, la forma inseparable de un cuerpo vivo, conocida a partir de la experiencia.",
    },
    {
      type: "match",
      question: "Uní cada nivel o concepto con lo que le corresponde",
      pairs: [
        { left: "Alma nutritiva", right: "Nutrición, crecimiento y reproducción" },
        { left: "Alma sensitiva", right: "Percepción, deseo y movimiento" },
        { left: "Alma racional", right: "Razonar y comprender, exclusiva de las personas" },
        { left: "Intelecto agente", right: "El cabo suelto: ¿separable e inmortal, o parte de la forma?" },
      ],
      explain: "Los tres niveles forman una jerarquía acumulativa; el intelecto agente es la excepción que no termina de encajar del todo en ese esquema tan cuidadosamente construido.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la doctrina de que toda sustancia natural es, inseparablemente, forma y materia?",
      answers: ["hilemorfismo"],
      explain: "De hyle (materia) y morphé (forma): el alma es la forma de un cuerpo vivo, y ninguna de las dos puede existir realmente sin la otra en un ser vivo concreto.",
    },
    {
      type: "info",
      title: "Lo que sigue",
      body: "Esta psicología, apoyada en la observación y no en el recuerdo de otra vida, es coherente con el resto del proyecto aristotélico: empezar por lo que hay y explicar el cambio con las mismas herramientas de siempre, potencia y acto. La próxima clase aplicamos esas mismas herramientas a la pregunta por la vida buena.",
    },
  ],
};
