export default {
  num: 10,
  transcript: null,
  title: "Aristóteles: sustancia, causa y las cuatro preguntas",
  source: "",
  feed: [
    {
      type: "info",
      title: "De la Academia al Liceo",
      body: "Aristóteles nace en 384 a. C. en Estagira, al norte de Grecia, hijo de un médico de la corte macedonia. A los diecisiete años entra en la Academia de Platón, donde permanece veinte años, hasta la muerte de su maestro. Es después tutor del joven Alejandro Magno, y en 335 a. C. funda en Atenas su propia escuela, el **Liceo**, cuyos miembros discuten a menudo caminando por sus jardines, por lo que se los llama «peripatéticos».",
    },
    {
      type: "quiz",
      question: "¿Cuánto tiempo pasa Aristóteles como alumno en la Academia de Platón?",
      options: [
        "veinte años, hasta la muerte de su maestro",
        "apenas seis meses, antes de fundar su propia escuela",
        "toda su vida, sin llegar nunca a independizarse",
        "cinco años, antes de ser expulsado por Platón",
      ],
      answer: 0,
      explain: "Entra a los diecisiete años y permanece veinte, hasta la muerte de Platón. Es después tutor de Alejandro Magno, y en 335 a. C. funda su propia escuela en Atenas, el Liceo.",
    },
    {
      type: "info",
      title: "El primer desacuerdo: ¿dónde están las Formas?",
      body: "Aristóteles acepta buena parte del programa de su maestro —que el mundo tiene una estructura racional y que la ciencia busca lo universal, no lo particular— pero rechaza su pieza central. Para él no existen Formas separadas, en un mundo aparte del sensible: lo universal, «el hombre» o «la justicia», existe únicamente encarnado en los hombres y las acciones justas concretas, nunca por separado.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia Aristóteles de Platón respecto de lo universal?",
      options: [
        "para Aristóteles, lo universal existe sólo encarnado en las cosas concretas",
        "para Aristóteles, lo universal es más real que cualquier cosa particular",
        "para Aristóteles, no existe ningún tipo de conocimiento universal",
        "para Aristóteles, las Formas están todavía más separadas que para Platón",
      ],
      answer: 0,
      explain: "Aristóteles rechaza la pieza central de Platón, las Formas separadas: para él, «el hombre» o «la justicia» existen únicamente encarnados en los hombres y las acciones justas concretas, nunca en un mundo aparte.",
    },
    {
      type: "info",
      title: "La pregunta por la sustancia",
      body: "Ese desacuerdo lo lleva a reformular la pregunta central de la filosofía. Para Aristóteles, lo que existe en el sentido más pleno y primario es la **sustancia** (ousía): este caballo particular, este hombre particular, no «el caballo» o «el hombre» en general. Las cualidades, cantidades y relaciones sólo existen como propiedades de una sustancia; nunca flotan libres, separadas de ella.",
    },
    {
      type: "quiz",
      question: "Para Aristóteles, ¿qué es la sustancia primera (ousía)?",
      options: [
        "este caballo o este hombre particular y concreto",
        "el concepto general y abstracto de «caballo» o «hombre»",
        "una Forma eterna que existe en un mundo aparte",
        "el color o el tamaño de un caballo o un hombre",
      ],
      answer: 0,
      explain: "Lo que existe en sentido pleno y primario es siempre algo concreto y particular, este caballo o este hombre. Las cualidades, cantidades y relaciones sólo existen como propiedades de una sustancia, nunca separadas de ella.",
    },
    {
      type: "info",
      title: "Las cuatro causas",
      body: "Para explicar por completo cualquier cosa, sostiene Aristóteles, hay que poder responder cuatro preguntas distintas. ¿De qué está hecha? Es la causa material, el bronce de una estatua. ¿Qué forma tiene, qué la hace ser lo que es? Es la causa formal, la figura que el escultor tenía en mente.",
    },
    {
      type: "info",
      continues: true,
      title: "Las cuatro causas",
      body: "¿Qué la produjo? Es la causa eficiente, el propio escultor que trabaja el bronce. ¿Para qué existe, hacia qué fin tiende? Es la causa final, honrar a un héroe, por ejemplo. Las cuatro juntas, y no una sola, dan la explicación completa de cualquier cosa que exista.",
    },
    {
      type: "quiz",
      question: "Frente a una estatua de bronce, ¿cuál de estas es, para Aristóteles, la causa formal?",
      options: [
        "la figura o forma que el escultor tenía en mente antes de esculpir",
        "el bronce del que está hecha físicamente la estatua",
        "el escultor mismo, que trabaja el bronce con sus herramientas",
        "el homenaje a un héroe que la estatua busca honrar",
      ],
      answer: 0,
      explain: "El bronce es la causa material, el escultor la eficiente, y el homenaje que busca la causa final. La causa formal es específicamente la figura o estructura que hace que ese bronce sea una estatua y no otra cosa.",
    },
    {
      type: "info",
      title: "Potencia y acto",
      body: "Para explicar el cambio sin caer en las paradojas de Parménides, Aristóteles distingue entre lo que algo es en **potencia** y lo que es en **acto**. Una bellota es, en potencia, un roble: todavía no lo es, pero tiene la capacidad interna de llegar a serlo. El roble adulto es esa misma capacidad ya cumplida, en acto.",
    },
    {
      type: "quiz",
      question: "En la distinción de Aristóteles, ¿qué es una bellota respecto de un roble?",
      options: [
        "un roble en potencia, capaz de llegar a serlo",
        "un roble ya en acto, exactamente igual que el adulto",
        "algo completamente ajeno a lo que después será un roble",
        "una sustancia sin ninguna relación causal con el roble",
      ],
      answer: 0,
      explain: "La bellota todavía no es un roble, pero tiene la capacidad interna de llegar a serlo: es un roble en potencia. El roble adulto es esa misma capacidad ya cumplida, un roble en acto.",
    },
    {
      type: "classify",
      question: "¿Cada afirmación es de Platón o de Aristóteles?",
      groups: ["Platón", "Aristóteles"],
      items: [
        { text: "Las Formas existen separadas, en un mundo aparte", group: 0 },
        { text: "Lo universal existe sólo encarnado en las cosas concretas", group: 1 },
        { text: "La sustancia primera es este caballo o este hombre particular", group: 1 },
        { text: "El conocimiento verdadero es de las Formas, no de lo sensible", group: 0 },
        { text: "Hay que observar los casos concretos para llegar a lo universal", group: 1 },
      ],
      explain: "El desacuerdo de fondo es siempre el mismo: para Platón, lo universal es más real y vive separado; para Aristóteles, lo universal existe sólo encarnado en las cosas concretas, y se llega a él observándolas.",
    },
    {
      type: "match",
      question: "Uní cada causa aristotélica con su ejemplo en una estatua de bronce",
      pairs: [
        { left: "Causa material", right: "El bronce del que está hecha" },
        { left: "Causa formal", right: "La figura que la hace ser esa estatua" },
        { left: "Causa eficiente", right: "El escultor que la produjo" },
        { left: "Causa final", right: "El homenaje que busca honrar" },
      ],
      explain: "Las cuatro causas juntas, y no una sola, dan la explicación completa de la estatua: de qué está hecha, qué forma tiene, quién la hizo y para qué existe.",
    },
    {
      type: "short",
      question: "¿Cómo llama Aristóteles, en griego, a lo que existe en sentido pleno: este caballo o este hombre particular?",
      answers: ["ousia", "sustancia"],
      explain: "La ousía es la sustancia primera: un individuo concreto, nunca un concepto general ni una Forma separada. Todo lo demás —cualidades, cantidades, relaciones— existe sólo como propiedad de una sustancia.",
    },
    {
      type: "info",
      title: "Lo que sigue",
      body: "Esta misma distinción entre potencia y acto va a ser la herramienta con la que Aristóteles explique, en las próximas clases, desde el movimiento de los astros hasta la existencia de un Dios que no cambia nunca porque ya está completamente en acto: el Motor Inmóvil.",
    },
  ],
};
