export default {
  num: 16,
  transcript: null,
  title: "Los escépticos: la suspensión del juicio",
  source: "",
  feed: [
    {
      type: "info",
      title: "Pirrón: nada es más esto que aquello",
      body: "Pirrón de Elis (ca. 360-270 a. C.) acompaña a Alejandro Magno en su expedición a la India, donde entra en contacto con ascetas y filósofos locales que lo impresionan profundamente. De vuelta en Grecia, sostiene que las cosas son, en el fondo, indiferentes, inestables e indeterminadas: no hay manera de saber cómo son realmente, más allá de cómo nos aparecen.",
    },
    {
      type: "info",
      title: "De la akatalepsia a la ataraxia",
      body: "Si nada puede aprehenderse con certeza —**akatalepsia**—, la respuesta razonable no es afirmar ni negar nada, sino suspender el juicio, la epojé. Y lo sorprendente es que esa suspensión, lejos de generar inquietud, trae consigo la misma serenidad que buscan estoicos y epicúreos: la ataraxia. Pirrón no escribió una sola línea; se lo conoce por su discípulo Timón de Fliunte, y siglos después por Enesidemo y Sexto Empírico, que sistematizan sus argumentos.",
    },
    {
      type: "quiz",
      question: "¿Qué sostiene Pirrón sobre cómo son «realmente» las cosas, más allá de cómo nos aparecen?",
      options: [
        "que no hay manera de saberlo: son indeterminadas para nosotros",
        "que son exactamente como los sentidos las muestran, sin ninguna duda",
        "que sólo los filósofos griegos pueden conocerlas con certeza",
        "que son siempre distintas de como aparecen, sin ninguna excepción",
      ],
      answer: 0,
      explain: "Para Pirrón las cosas son indiferentes, inestables e indeterminadas: no hay ningún criterio disponible para decidir cómo son «en realidad», más allá de la manera en que se nos presentan en cada caso.",
    },
    {
      type: "quiz",
      question: "Según Pirrón, ¿qué trae consigo la suspensión del juicio (epojé) ante lo que no puede decidirse?",
      options: [
        "la ataraxia, la misma serenidad de otras escuelas",
        "una inquietud todavía mayor que la de no dudar de nada",
        "el aislamiento completo de cualquier forma de vida en sociedad",
        "la certeza absoluta sobre cómo son las cosas en realidad",
      ],
      answer: 0,
      explain: "Sorprendentemente, suspender el juicio en vez de forzar una respuesta trae la misma serenidad que buscan las otras escuelas helenísticas: la ataraxia, aunque cada una llegue a ella por un camino distinto.",
    },
    {
      type: "info",
      title: "Los modos para suspender el juicio",
      body: "Enesidemo reúne diez «modos» o argumentos estándar para llegar a la suspensión del juicio. Uno de los más simples dice que animales distintos perciben el mismo objeto de maneras incompatibles entre sí. Lo que a un ojo humano le resulta agradable puede repugnarle a otro animal, y no hay ningún criterio neutral para decidir cuál de las dos percepciones capta cómo es la cosa «en realidad».",
    },
    {
      type: "info",
      title: "Otra Academia: Arcesilao y Carnéades",
      body: "Casi al mismo tiempo, y de manera independiente, la propia Academia de Platón da un giro escéptico bajo la dirección de Arcesilao y, después, de Carnéades. Argumentan sobre todo contra los estoicos: niegan que exista un criterio infalible para distinguir una impresión verdadera de una falsa, y concluyen que no puede afirmarse ningún conocimiento con certeza absoluta.",
    },
    {
      type: "quiz",
      question: "¿Qué muestra el modo escéptico sobre la percepción animal, según Enesidemo?",
      options: [
        "que no hay un criterio neutral para decidir cuál percepción es correcta",
        "que sólo los seres humanos tienen percepciones confiables",
        "que los animales perciben siempre exactamente lo mismo que las personas",
        "que las percepciones de los animales son todas, sin excepción, falsas",
      ],
      answer: 0,
      explain: "Si un mismo objeto le resulta agradable a un animal y repugnante a otro, y no hay ningún punto de vista neutral desde el cual arbitrar, no queda ninguna base sólida para afirmar cómo es esa cosa «en realidad».",
    },
    {
      type: "quiz",
      question: "¿Contra qué escuela argumentan principalmente Arcesilao y Carnéades desde la Academia?",
      options: [
        "contra los estoicos, negando que exista un criterio infalible",
        "contra los epicúreos, negando la existencia de los átomos",
        "contra los pitagóricos, negando el valor de las matemáticas",
        "contra Aristóteles, negando la existencia de las cuatro causas",
      ],
      answer: 0,
      explain: "El blanco principal es la epistemología estoica, que proponía un criterio para distinguir impresiones verdaderas de falsas. Arcesilao y Carnéades niegan que ese criterio exista, y concluyen que ningún conocimiento es absolutamente cierto.",
    },
    {
      type: "info",
      title: "Una diferencia sutil pero importante",
      body: "Hay, sin embargo, una diferencia entre ambos escepticismos que los propios pirrónicos señalan con orgullo. Los académicos afirman, con cierta seguridad, que nada puede conocerse: una tesis negativa, pero tesis al fin. Los pirrónicos van un paso más allá y suspenden el juicio incluso sobre esa afirmación, sin comprometerse ni siquiera con la idea de que el conocimiento sea imposible.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia el escepticismo pirrónico del académico?",
      options: [
        "el pirrónico suspende el juicio incluso sobre si se puede conocer algo",
        "el pirrónico afirma con total seguridad que nada puede conocerse",
        "el académico suspende el juicio sobre absolutamente todo, sin excepción",
        "no hay ninguna diferencia real entre ambas formas de escepticismo",
      ],
      answer: 0,
      explain: "Los académicos sostienen, con cierta seguridad, que nada puede conocerse: ya es una tesis. Los pirrónicos suspenden el juicio incluso sobre esa tesis, sin comprometerse ni con la posibilidad ni con la imposibilidad del conocimiento.",
    },
    {
      type: "info",
      title: "Vivir sin certezas: el pithanon de Carnéades",
      body: "Si hay que suspender el juicio sobre todo, ¿cómo se puede actuar en la vida diaria? Carnéades propone un criterio práctico, el **pithanon** o «lo persuasivo»: sin afirmar que una impresión sea verdadera, se puede actuar guiado por la que resulte más plausible, sobre todo si esa plausibilidad resiste el examen y no entra en conflicto con otras impresiones.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al escepticismo académico o al pirrónico?",
      groups: ["Escepticismo académico", "Escepticismo pirrónico"],
      items: [
        { text: "Afirma que nada puede conocerse con certeza", group: 0 },
        { text: "Suspende el juicio incluso sobre si se puede conocer algo", group: 1 },
        { text: "Arcesilao y Carnéades son sus representantes", group: 0 },
        { text: "Pirrón y, después, Sexto Empírico son sus representantes", group: 1 },
        { text: "Propone el pithanon como guía práctica para actuar", group: 0 },
      ],
      explain: "El académico llega a una conclusión negativa firme: nada se puede conocer. El pirrónico desconfía incluso de esa conclusión, y suspende el juicio de manera más radical y consistente todavía.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que describe",
      pairs: [
        { left: "Akatalepsia", right: "Nada puede aprehenderse con certeza" },
        { left: "Epojé", right: "La suspensión del juicio ante lo que no puede decidirse" },
        { left: "Los diez modos", right: "Argumentos de Enesidemo: todo desacuerdo resulta irresoluble" },
        { left: "Pithanon", right: "Lo persuasivo: una guía para actuar sin afirmar certeza alguna" },
      ],
      explain: "Los cuatro términos arman el mismo argumento en distintas etapas: no se puede conocer nada con certeza, por eso hay que suspender el juicio, éstos son los argumentos que lo justifican, y así se puede seguir actuando de todos modos.",
    },
    {
      type: "info",
      title: "Un eco muy posterior",
      body: "El escepticismo antiguo va a resurgir con fuerza mucho después, en el siglo XVII, cuando Descartes use una duda parecida —aunque con un objetivo opuesto— como punto de partida de toda la filosofía moderna. La próxima clase deja atrás Atenas casi por completo y viaja hasta Roma, quinientos años más tarde, para conocer a Plotino y el nacimiento del neoplatonismo.",
    },
  ],
};
