export default {
  num: 4,
  transcript: null,
  title: "Sócrates: la pregunta que no se deja responder",
  source: "",
  feed: [
    {
      type: "info",
      title: "El problema socrático",
      body: "Sócrates (469-399 a. C.) no escribió una sola línea, y sin embargo es una de las figuras más influyentes de toda la filosofía. Todo lo que sabemos de él llega filtrado por otros: su discípulo Platón, que lo convierte en protagonista de casi todos sus diálogos; el historiador Jenofonte, que lo retrata más práctico y menos radical; y el comediógrafo Aristófanes, que en Las nubes lo ridiculiza como un sofista más, flotando en una canasta y enseñando a no pagar deudas.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema socrático",
      body: "Estas tres imágenes no siempre coinciden. A este problema de reconstruir al Sócrates real detrás de tantos retratos distintos se lo conoce como el «problema socrático». La versión que domina en esta clase es la de Platón, sobre todo la de sus diálogos más tempranos, considerados los más fieles al Sócrates histórico. Fue hoplita en dos campañas, Potidea y Delio, vivió en la pobreza, y pasó buena parte de su vida hablando con cualquiera en la plaza pública de Atenas.",
    },
    {
      type: "quiz",
      question: "¿Por qué se habla de un «problema socrático»?",
      options: [
        "porque Sócrates no escribió nada y lo conocemos por retratos distintos",
        "porque nadie sabe si Sócrates existió realmente como persona",
        "porque Sócrates cambió de opinión filosófica varias veces en su vida",
        "porque sus discípulos destruyeron todos sus escritos tras su muerte",
      ],
      answer: 0,
      explain: "Sócrates no dejó ningún texto propio. Todo lo que sabemos llega filtrado por Platón, Jenofonte y Aristófanes, que no siempre coinciden entre sí: reconstruir al Sócrates real detrás de esos retratos es justamente el problema.",
    },
    {
      type: "info",
      title: "El oráculo de Delfos",
      body: "Querefonte, amigo de juventud de Sócrates, viaja a Delfos y le pregunta al oráculo si existe alguien más sabio que Sócrates. La respuesta es que no. Sócrates, que se sabe ignorante, queda perplejo: ¿qué quiso decir el dios?",
    },
    {
      type: "info",
      continues: true,
      title: "El oráculo de Delfos",
      body: "Decide entonces salir a probar el oráculo equivocado. Interroga a políticos, poetas y artesanos famosos por su sabiduría, y descubre en cada uno el mismo patrón: creen saber cosas que en realidad no saben. Los artesanos sí dominan su oficio, pero de ahí concluyen, sin fundamento, que también entienden de los asuntos más importantes de la vida.",
    },
    {
      type: "quiz",
      question: "¿Qué concluye Sócrates después de interrogar a políticos, poetas y artesanos?",
      options: [
        "que todos creen saber lo que en realidad no saben",
        "que ninguno de ellos domina siquiera su propio oficio",
        "que el oráculo de Delfos se había equivocado por completo",
        "que la sabiduría verdadera sólo existe entre los sofistas",
      ],
      answer: 0,
      explain: "Los artesanos sí dominan su oficio, pero de ahí saltan, sin fundamento, a creerse sabios en los asuntos más importantes de la vida. Sócrates, en cambio, al menos sabe que no sabe: esa es toda su ventaja.",
    },
    {
      type: "info",
      continues: true,
      title: "El oráculo de Delfos",
      body: "Sócrates concluye, en la Apología, que su ventaja sobre todos ellos es mínima pero decisiva: ellos creen saber sin saber, y él, al menos, sabe que no sabe. Esa frase —resumida después, con más simplicidad de la que Sócrates usó, como «sólo sé que nada sé»— no es falsa modestia. Es el motor de todo su método.",
    },
    {
      type: "info",
      title: "El elenchos: preguntar hasta la aporía",
      body: "El método de Sócrates, el **elenchos**, consiste en preguntar «¿qué es X?» —la valentía, la piedad, la virtud— y examinar la respuesta con nuevas preguntas hasta encontrarle una contradicción. El interlocutor, convencido al principio de saber la respuesta, termina reconociendo que no puede sostenerla.",
    },
    {
      type: "info",
      continues: true,
      title: "El elenchos: preguntar hasta la aporía",
      body: "Ese callejón sin salida se llama **aporía**. En los diálogos más tempranos de Platón, casi ningún debate llega más lejos: no hay una definición final de la virtud, sólo el descubrimiento de que la que se tenía por segura no alcanza. Sócrates no lo vive como un fracaso, sino como el único punto de partida honesto, porque no se puede buscar en serio algo que ya se cree tener resuelto.",
    },
    {
      type: "quiz",
      question: "¿Qué es la aporía a la que suelen llegar los diálogos socráticos tempranos?",
      options: [
        "el momento en que el interlocutor no puede sostener su propia definición",
        "la respuesta final y correcta a la pregunta que se estaba discutiendo",
        "un tipo de discurso retórico que enseñaban los sofistas por dinero",
        "el castigo legal que recibía quien perdía un debate público en Atenas",
      ],
      answer: 0,
      explain: "El elenchos no suele terminar en una definición firme, sino en que el interlocutor, convencido al principio de saber la respuesta, reconoce que no puede sostenerla. Sócrates ve ese callejón sin salida como un punto de partida, no como una derrota.",
    },
    {
      type: "short",
      question: "¿Cómo se llama el método de preguntas y refutaciones con el que Sócrates examina las definiciones de sus interlocutores?",
      answers: ["elenchos", "elenco"],
      explain: "Preguntar «¿qué es X?» y refutar cada respuesta hasta encontrarle una contradicción: ese procedimiento, el elenchos, suele terminar en aporía, no en una definición firme.",
    },
    {
      type: "info",
      title: "Nadie hace el mal a sabiendas",
      body: "De ese método sale una tesis que va a marcar toda la ética antigua: la virtud es conocimiento. Si alguien supiera de verdad qué es lo bueno, sostiene Sócrates, actuaría en consecuencia; nadie elige el mal a sabiendas, sólo por ignorancia de lo que en verdad conviene. El malvado no es alguien que ve el bien y lo rechaza, sino alguien confundido sobre qué es el bien.",
    },
    {
      type: "info",
      continues: true,
      title: "Nadie hace el mal a sabiendas",
      body: "Esta tesis lo separa con nitidez de los sofistas de la clase pasada. Ellos cobran por enseñar una virtud política que presentan casi como una técnica, aplicable con éxito conozca uno o no la verdad de fondo. Sócrates, en cambio, no cobra, insiste en que no sabe, y busca una definición verdadera de la virtud antes de aceptar que alguien pueda enseñarla.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia Sócrates de los sofistas en su relación con la virtud?",
      options: [
        "ellos cobran por enseñarla; él insiste en que ni siquiera sabe qué es",
        "ellos la niegan por completo; él cree que se hereda por nacimiento",
        "ellos la reducen a la fuerza física; él la reduce sólo a la riqueza",
        "ellos la enseñan gratis; él cobra caro por sus lecciones privadas",
      ],
      answer: 0,
      explain: "Los sofistas cobran por enseñar una virtud política que presentan casi como una técnica. Sócrates no cobra, y antes de aceptar que se pueda enseñar exige saber, primero, qué es realmente la virtud, algo que él mismo confiesa no saber.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde a los sofistas o a Sócrates?",
      groups: ["Sofistas", "Sócrates"],
      items: [
        { text: "Cobran por enseñar la virtud política a cambio de una paga", group: 0 },
        { text: "Sostienen que la verdad depende de quien la percibe", group: 0 },
        { text: "Afirma no saber, y busca la verdad junto con su interlocutor", group: 1 },
        { text: "Cree que nadie hace el mal si conoce de verdad lo que es el bien", group: 1 },
        { text: "Viajan de ciudad en ciudad ofreciendo sus enseñanzas", group: 0 },
      ],
      explain: "A ojos de sus contemporáneos, Aristófanes incluido, Sócrates podía confundirse con un sofista más: discutía en público sobre los mismos temas. Pero no cobraba, no afirmaba tener respuestas, y buscaba una verdad única, no la persuasión más eficaz.",
    },
    {
      type: "info",
      title: "El juicio y la muerte",
      body: "En 399 a. C., Atenas lleva a juicio a Sócrates por impiedad —no creer en los dioses de la ciudad e introducir divinidades nuevas— y por corromper a la juventud. Detrás de los cargos formales hay, probablemente, sospechas políticas: varios de sus antiguos discípulos, entre ellos Alcibíades y Critias, habían estado ligados a episodios oscuros de la reciente guerra e incluso a un golpe oligárquico.",
    },
    {
      type: "info",
      continues: true,
      title: "El juicio y la muerte",
      body: "En su defensa —la Apología, tal como la reconstruye Platón— Sócrates no suplica clemencia. Dice que seguirá filosofando aunque lo condenen, y que «la vida sin examen no merece la pena ser vivida». El jurado lo declara culpable; cuando le toca proponer su propia pena, en vez de una multa razonable ofrece una simbólica, y el jurado opta por la muerte.",
    },
    {
      type: "quiz",
      question: "En su defensa ante el jurado, ¿qué actitud toma Sócrates según la Apología de Platón?",
      options: [
        "no pide clemencia y dice que seguirá filosofando",
        "pide perdón y promete abandonar la filosofía para siempre",
        "acusa a los propios jueces de haber cometido perjurio",
        "ofrece pagar una multa altísima para evitar la condena",
      ],
      answer: 0,
      explain: "Sócrates no suplica: sostiene que la vida sin examen no merece la pena ser vivida, y que seguirá haciendo lo mismo aunque lo condenen. Esa firmeza, más que los cargos en sí, termina de inclinar al jurado en su contra.",
    },
    {
      type: "info",
      continues: true,
      title: "El juicio y la muerte",
      body: "Condenado a muerte, Sócrates tiene ocasión de escapar: su amigo Critón ha sobornado a los guardias. En el diálogo que lleva su nombre, Sócrates se niega, y pone en boca de las Leyes de Atenas un argumento de peso: lo criaron, lo educaron y le permitieron vivir setenta años bajo su amparo, y huir ahora, aunque la sentencia sea injusta, sería traicionar el pacto que sostiene a toda la ciudad.",
    },
    {
      type: "quiz",
      question: "¿Por qué Sócrates se niega a escapar de la cárcel, según el argumento de las Leyes en el Critón?",
      options: [
        "porque huir traicionaría el pacto que lo unió siempre a su ciudad",
        "porque no confiaba en que Critón hubiera sobornado bien a los guardias",
        "porque prefería morir antes que vivir exiliado en otra ciudad griega",
        "porque temía que sus discípulos lo consideraran un cobarde",
      ],
      answer: 0,
      explain: "Las Leyes personificadas le recuerdan que lo criaron y educaron bajo su amparo durante setenta años: huir ahora, aunque la condena sea injusta, rompería el pacto que sostiene a toda la ciudad, no sólo a él mismo.",
    },
    {
      type: "match",
      question: "Uní cada nombre o concepto con lo que le corresponde en la vida de Sócrates",
      pairs: [
        { left: "Querefonte", right: "Consulta al oráculo si hay alguien más sabio que Sócrates" },
        { left: "Elenchos", right: "Preguntar y refutar hasta encontrar una contradicción" },
        { left: "Aporía", right: "El callejón sin salida en que termina buena parte del diálogo" },
        { left: "Critón", right: "Le ofrece a Sócrates escapar de la cárcel antes de la condena" },
      ],
      explain: "El recorrido de Sócrates va del oráculo que lo desconcierta, al método que inventa para entenderlo, al resultado típico de ese método, hasta la escena final en la que sostiene, con su propia vida, todo lo que predicó.",
    },
    {
      type: "info",
      title: "Lo que Sócrates deja abierto",
      body: "Sócrates muere sin haber definido con firmeza qué es la virtud, la piedad o la justicia. Deja, en cambio, un método, una pregunta y un ejemplo: que vale la pena examinar la propia vida aunque el precio sea alto, y que la filosofía no es un cuerpo de doctrinas para memorizar, sino una práctica que se sostiene con la propia conducta.",
    },
    {
      type: "info",
      continues: true,
      title: "Lo que Sócrates deja abierto",
      body: "Su discípulo más importante, Platón, va a tomar ese legado inconcluso y construir a partir de él un sistema filosófico propio, con una teoría del conocimiento, una metafísica y una política completas. Las próximas cinco clases están dedicadas enteramente a él.",
    },
  ],
};
