export default {
  num: 15,
  transcript: null,
  title: "Los estoicos: vivir conforme a la razón del cosmos",
  source: "",
  feed: [
    {
      type: "info",
      title: "De un naufragio a la Stoa",
      body: "Zenón de Citio (335-263 a. C.) llega a Atenas después de perder toda su mercancía en un naufragio, y termina estudiando filosofía casi por accidente: entra a una librería, escucha leer un pasaje sobre Sócrates, y queda fascinado. Estudia primero con los cínicos y con la Academia, y hacia el 300 a. C. funda su propia escuela, que da clases en la Stoa Poikile, el «pórtico pintado» del ágora ateniense. De ahí el nombre de **estoicos**.",
    },
    {
      type: "quiz",
      question: "¿De dónde viene el nombre «estoicos» para la escuela de Zenón de Citio?",
      options: [
        "de la Stoa Poikile, el pórtico ateniense donde daba sus clases",
        "del nombre propio de un antiguo rey griego llamado Estoico",
        "de una isla del Egeo donde Zenón había nacido",
        "de un templo dedicado a Zeus en el que se reunían a debatir",
      ],
      answer: 0,
      explain: "Zenón funda su escuela hacia el 300 a. C. y da clases en la Stoa Poikile, el «pórtico pintado» del ágora de Atenas. De ese pórtico, y no de ningún nombre propio, viene «estoicos».",
    },
    {
      type: "info",
      continues: true,
      title: "De un naufragio a la Stoa",
      body: "A Zenón lo sucede Cleantes, y a Cleantes, Crisipo de Solos, el sistematizador más importante de la escuela: se decía que «si Crisipo no hubiera existido, tampoco existiría la Estoa». Sus escritos originales casi no sobrevivieron, y buena parte de lo que sabemos del estoicismo temprano llega filtrado por citas de autores posteriores, muchas veces hostiles.",
    },
    {
      type: "info",
      title: "Un cosmos racional de punta a punta",
      body: "Para los estoicos, el cosmos entero es un ser vivo, racional y providente, atravesado por el logos, la misma palabra de Heráclito en la Clase 1, ahora llevada a sus últimas consecuencias. Lo llaman también pneuma, un aliento o soplo divino que impregna toda la materia y le da cohesión, tensión y orden. Nada ocurre por azar: todo sucede según una cadena causal necesaria, el destino (**heimarmene**).",
    },
    {
      type: "quiz",
      question: "Para los estoicos, ¿qué es el pneuma?",
      options: [
        "un aliento o soplo divino que impregna toda la materia y le da orden",
        "una fuerza puramente mecánica, sin ninguna relación con la razón",
        "el nombre técnico que le dan al alma sólo en los seres humanos",
        "un tipo particular de átomo heredado directamente de Demócrito",
      ],
      answer: 0,
      explain: "El pneuma es el aliento divino que atraviesa toda la materia y le da cohesión y orden, muy distinto de los átomos ciegos de Demócrito: para los estoicos, el cosmos entero es racional de punta a punta.",
    },
    {
      type: "info",
      title: "El destino y la libertad",
      body: "Si todo está determinado, ¿qué lugar queda para la libertad? Los estoicos responden que la necesidad no elimina la diferencia entre actuar de buena gana o a la fuerza. Igual que un cilindro, empujado, rueda según su propia forma, cada persona reacciona a los acontecimientos según su propio carácter: el destino empuja a todos por igual, pero cómo se responde a ese empujón sigue siendo, en un sentido importante, cosa de cada quien.",
    },
    {
      type: "quiz",
      question: "En la imagen estoica del cilindro empujado, ¿qué representa la forma propia del cilindro?",
      options: [
        "el carácter de cada persona, que determina cómo responde al destino",
        "el destino mismo, que empuja a todas las personas por igual",
        "la virtud, que sólo poseen unos pocos sabios excepcionales",
        "el azar puro, sin ninguna relación con la necesidad",
      ],
      answer: 0,
      explain: "El empujón es el mismo para todos, como el destino; pero cómo rueda cada cilindro depende de su propia forma, como el carácter de cada persona determina su respuesta particular a lo que el destino le presenta.",
    },
    {
      type: "info",
      title: "Vivir conforme a la naturaleza",
      body: "La ética estoica se resume en una fórmula: vivir conforme a la naturaleza, es decir, conforme a la razón, porque la razón es precisamente lo que distingue a la naturaleza humana del resto de los seres vivos. Es el mismo argumento de la función que usaba Aristóteles en la Clase 13, ahora puesto al servicio de una ética distinta. La virtud es el único bien verdadero; todo lo demás —salud, riqueza, reputación— son «indiferentes».",
    },
    {
      type: "quiz",
      question: "¿Qué significa, para los estoicos, «vivir conforme a la naturaleza»?",
      options: [
        "vivir conforme a la razón, lo propio de la naturaleza humana",
        "vivir aislado de cualquier contacto con otras personas",
        "vivir exclusivamente de lo que produce la tierra sin comercio",
        "vivir según los instintos animales más básicos y directos",
      ],
      answer: 0,
      explain: "La naturaleza humana se distingue del resto de los seres vivos por la razón: vivir conforme a la naturaleza es, entonces, vivir guiado por la razón, el mismo argumento de la función que usaba Aristóteles.",
    },
    {
      type: "info",
      continues: true,
      title: "Vivir conforme a la naturaleza",
      body: "Esos indiferentes no son todos iguales: la salud y la riqueza son «preferibles», y conviene elegirlas en igualdad de condiciones, pero ni la salud, ni la riqueza, ni ninguna otra cosa externa le aportan nada a la felicidad de quien las tiene. Sólo la virtud, que depende enteramente de uno mismo, puede hacer buena o mala a una vida.",
    },
    {
      type: "quiz",
      question: "¿Por qué la salud y la riqueza son «preferibles» pero no «buenas» para los estoicos?",
      options: [
        "porque conviene elegirlas, pero no aportan nada a la felicidad real",
        "porque en realidad son siempre peores que la enfermedad y la pobreza",
        "porque sólo los filósofos tienen derecho a poseer riqueza o salud",
        "porque los dioses las reparten sin ningún criterio racional",
      ],
      answer: 0,
      explain: "Conviene elegir la salud sobre la enfermedad, la riqueza sobre la pobreza, en igualdad de condiciones. Pero ninguna de las dos, por sí misma, hace mejor ni peor a una vida: sólo la virtud, que depende de uno mismo, puede hacerlo.",
    },
    {
      type: "info",
      title: "Las pasiones son juicios, no impulsos ciegos",
      body: "Para los estoicos, emociones como el miedo, la envidia o el deseo desmedido no son fuerzas irracionales que nos dominan desde afuera: son juicios, casi siempre juicios erróneos, que le atribuyen un valor exagerado a algo que en realidad es indiferente. El sabio no deja de sentir nada —los estoicos le reconocen «buenos sentimientos» genuinos, como la alegría serena—, pero corrige esos juicios equivocados y alcanza así la **apatheia**, la ausencia de pasiones perturbadoras.",
    },
    {
      type: "quiz",
      question: "Para los estoicos, ¿de dónde viene una pasión perturbadora como el miedo excesivo?",
      options: [
        "de un juicio erróneo que le da demasiado valor a algo indiferente",
        "de un desequilibrio puramente físico, sin ninguna relación con la razón",
        "de la falta absoluta de cualquier tipo de sentimiento",
        "de una virtud mal entendida por quien todavía no es sabio",
      ],
      answer: 0,
      explain: "El miedo excesivo nace de juzgar que algo indiferente, como perder la salud o la reputación, es en realidad terrible. El sabio corrige ese juicio, no elimina todo sentimiento: por eso alcanza la apatheia sin dejar de sentir alegría serena.",
    },
    {
      type: "info",
      title: "Ciudadanos del cosmos",
      body: "Como todos los seres humanos comparten la misma razón, los estoicos son los primeros en proponer una ética verdaderamente universal, más allá de la ciudad particular en la que a cada quien le toque nacer. Se llaman a sí mismos «ciudadanos del mundo» (kosmopolitai), y sostienen que la ley natural que comparten todos los hombres pesa tanto como la de cualquier ciudad, incluida Atenas.",
    },
    {
      type: "classify",
      question: "¿Cada cosa es, para los estoicos, un bien verdadero o un indiferente?",
      groups: ["Bien verdadero", "Indiferente"],
      items: [
        { text: "La salud del cuerpo", group: 1 },
        { text: "Actuar conforme a la razón", group: 0 },
        { text: "La riqueza y la buena reputación", group: 1 },
        { text: "La sabiduría práctica del sabio", group: 0 },
      ],
      explain: "Sólo la virtud, que depende enteramente de uno mismo, es un bien verdadero. La salud, la riqueza y la reputación son indiferentes preferibles: conviene elegirlas, pero no hacen mejor ni peor a quien las tiene.",
    },
    {
      type: "match",
      question: "Uní cada término estoico con lo que nombra",
      pairs: [
        { left: "Logos / pneuma", right: "La razón divina que atraviesa y ordena todo el cosmos" },
        { left: "Heimarmene", right: "El destino: la cadena causal necesaria de todo lo que ocurre" },
        { left: "Apatheia", right: "La ausencia de pasiones, lograda corrigiendo juicios erróneos" },
        { left: "Kosmopolitai", right: "Ciudadanos del mundo, unidos por la misma razón compartida" },
      ],
      explain: "Los cuatro términos describen un mismo sistema: un cosmos racional (logos), regido por una necesidad (heimarmene), frente al cual el sabio corrige sus juicios (apatheia) y reconoce una humanidad compartida (kosmopolitai).",
    },
    {
      type: "short",
      question: "¿Cómo llaman los estoicos al estado del sabio que ya no sufre pasiones perturbadoras, por haber corregido sus juicios erróneos?",
      answers: ["apatheia"],
      explain: "No es ausencia total de sentimiento: el sabio conserva «buenos sentimientos» genuinos, como la alegría serena. La apatheia es, específicamente, la ausencia de las pasiones que nacen de juicios equivocados sobre lo indiferente.",
    },
    {
      type: "info",
      title: "La próxima escuela",
      body: "La próxima clase conocemos a los escépticos, la tercera gran escuela helenística, que busca la misma serenidad que estoicos y epicúreos pero por un camino todavía más radical: dudar de todo.",
    },
  ],
};
