export default {
  num: 5,
  transcript: null,
  title: "Platón: opinión y conocimiento",
  source: "",
  feed: [
    {
      type: "info",
      title: "Quién es Platón",
      body: "Platón nace en Atenas hacia el 428 a. C., en una familia aristocrática con vínculos políticos de peso: su tío Critias fue uno de los líderes del golpe oligárquico que gobernó brevemente la ciudad. Conoce a Sócrates siendo joven y se convierte en uno de sus discípulos más cercanos; su ejecución en 399 a. C., cuando Platón tiene apenas veintiocho años, lo marca para siempre y lo aleja de cualquier ambición política convencional.",
    },
    {
      type: "info",
      continues: true,
      title: "Quién es Platón",
      body: "Tras viajar por el Mediterráneo, funda en Atenas, hacia el 387 a. C., la Academia, la primera institución de enseñanza superior de Occidente, donde va a formar entre otros a Aristóteles. Escribe en forma de diálogos, casi siempre con Sócrates como protagonista, y la pregunta de dónde termina el pensamiento del maestro y dónde empieza el del discípulo —el «problema socrático» de la clase anterior, visto ahora desde el otro lado— sigue abierta entre los especialistas.",
    },
    {
      type: "quiz",
      question: "¿Por qué la muerte de Sócrates es un punto de inflexión tan fuerte en la vida de Platón?",
      options: [
        "lo aleja de la política convencional y orienta su obra filosófica",
        "lo convierte de inmediato en gobernante de la ciudad de Atenas",
        "le impide viajar fuera de Atenas por el resto de su vida",
        "lo lleva a abandonar por completo la forma del diálogo escrito",
      ],
      answer: 0,
      explain: "Platón tenía apenas veintiocho años cuando la democracia ateniense ejecutó a su maestro. La experiencia lo aparta de la carrera política que su familia aristocrática esperaba de él y orienta el resto de su obra.",
    },
    {
      type: "info",
      title: "La paradoja de Menón",
      body: "En el diálogo Menón, Platón plantea un problema que parece cerrar cualquier posibilidad de aprender algo nuevo. Si ya conozco lo que busco, no necesito investigarlo. Y si no lo conozco en absoluto, no sé ni qué buscar, ni cómo reconocerlo si lo encuentro. La investigación, en cualquiera de los dos casos, parece imposible.",
    },
    {
      type: "quiz",
      question: "¿Cómo se formula la paradoja de Menón sobre la posibilidad de investigar?",
      options: [
        "es imposible investigar tanto si se sabe como si no se sabe",
        "nadie puede investigar más de un tema filosófico a la vez",
        "toda investigación exige antes haber consultado a un sofista",
        "sólo los dioses pueden investigar lo que todavía no existe",
      ],
      answer: 0,
      explain: "Es un dilema: conocer algo vuelve innecesaria la búsqueda, e ignorarlo del todo la vuelve imposible, porque no se sabría ni qué se está buscando ni cómo reconocerlo al encontrarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "La paradoja de Menón",
      body: "La salida que propone Platón es la **anamnesis**. El alma, inmortal, ya conoció alguna vez todas las cosas en una existencia previa a esta vida, y lo que llamamos «aprender» no es incorporar algo nuevo desde afuera, sino recordar lo que el alma ya sabía. Aprender es, literalmente, recolectar.",
    },
    {
      type: "info",
      title: "El esclavo y el cuadrado",
      body: "Para mostrarlo, Sócrates interroga en el diálogo a un esclavo de Menón, sin instrucción matemática alguna, sobre cómo construir un cuadrado del doble de área que otro dado. Sin darle ninguna respuesta, sólo con preguntas, lo va guiando hasta que el esclavo mismo llega a la solución correcta: el cuadrado construido sobre la diagonal del original tiene exactamente el doble de área.",
    },
    {
      type: "info",
      continues: true,
      title: "El esclavo y el cuadrado",
      body: "El esclavo, dice Sócrates, no aprendió nada de él. Sólo tenía dentro de sí, sin saberlo, la respuesta correcta, y las preguntas apenas se la hicieron recordar. La escena funciona como demostración práctica de la anamnesis, y de paso establece un método: enseñar no es transmitir información desde afuera, sino ayudar a otro a dar a luz lo que ya lleva dentro.",
    },
    {
      type: "quiz",
      question: "¿Qué demuestra, para Platón, la escena del esclavo y el cuadrado en el Menón?",
      options: [
        "que el esclavo recuerda un conocimiento que su alma ya tenía",
        "que cualquier persona puede aprender geometría en una sola clase",
        "que los esclavos son, en realidad, más inteligentes que sus amos",
        "que las matemáticas son una invención reciente de los sofistas",
      ],
      answer: 0,
      explain: "Sócrates no le enseña nada nuevo: sólo le hace preguntas, y el esclavo llega solo a la respuesta correcta. Para Platón, eso muestra que el alma ya poseía ese conocimiento, y aprender es recordarlo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Platón, en el Menón, al recordar del alma un conocimiento que ya tenía de una vida anterior?",
      answers: ["anamnesis", "anámnesis"],
      explain: "El alma, inmortal, ya conoció todas las cosas antes de esta vida: aprender no es incorporar algo nuevo, sino recordarlo. La escena del esclavo y el cuadrado en el Menón es la demostración práctica de esta idea.",
    },
    {
      type: "info",
      title: "Opinión verdadera y conocimiento",
      body: "Pero Platón todavía tiene que explicar una diferencia importante: alguien puede acertar una respuesta sin realmente saberla, por ejemplo, por una corazonada. ¿Es eso ya conocimiento? Platón dice que no: es apenas una **opinión verdadera**, y aunque acierte, no es todavía epistéme, conocimiento propiamente dicho.",
    },
    {
      type: "info",
      continues: true,
      title: "Opinión verdadera y conocimiento",
      body: "Compara esas opiniones verdaderas con las estatuas del mítico escultor Dédalo, tan realistas que, según la leyenda, se escapaban si no se las ataba: útiles mientras se quedan quietas, pero sin garantía de que sigan ahí. Lo que las fija en su lugar, y las convierte en conocimiento genuino, es un razonamiento que explique por qué son verdaderas, lo que Platón llama «atarlas con un razonamiento causal».",
    },
    {
      type: "quiz",
      question: "¿Qué le falta, para Platón, a una opinión verdadera para convertirse en conocimiento (epistéme)?",
      options: [
        "un razonamiento que explique por qué esa opinión es verdadera",
        "la aprobación de un tribunal de ciudadanos atenienses",
        "que la comparta la mayoría de la población de la ciudad",
        "nada: para Platón, opinión verdadera y conocimiento son lo mismo",
      ],
      answer: 0,
      explain: "Una opinión verdadera puede ser apenas una corazonada acertada, tan inestable como las estatuas de Dédalo, que se escapaban si no se las ataba. Sólo un razonamiento que explique por qué es verdadera la fija, y la vuelve conocimiento.",
    },
    {
      type: "info",
      title: "La línea dividida",
      body: "En la República, Platón organiza toda esta diferencia en una sola imagen: una línea dividida en cuatro segmentos, que separan dos mundos. El tramo inferior corresponde a la **dóxa**, la opinión, y se ocupa del mundo visible; el tramo superior corresponde a la **epistéme**, el conocimiento, y se ocupa del mundo inteligible.",
    },
    {
      type: "info",
      continues: true,
      title: "La línea dividida",
      body: "Dentro de la dóxa, el primer segmento es la eikasía, el nivel más bajo: conjeturas a partir de sombras, reflejos e imágenes. El segundo es la pístis, la creencia común en los objetos físicos mismos que proyectan esas sombras: los árboles, los animales, las personas que vemos todos los días.",
    },
    {
      type: "info",
      continues: true,
      title: "La línea dividida",
      body: "Dentro de la epistéme, el tercer segmento es la dianoia, el razonamiento matemático, que trabaja con objetos abstractos —números, figuras geométricas— a partir de hipótesis que no se cuestionan. El cuarto y último es la nóesis, la comprensión más alta, que llega hasta las Formas mismas sin apoyarse en ninguna hipótesis previa: el tema exacto de la próxima clase.",
    },
    {
      type: "classify",
      question: "¿Cada nivel corresponde a la dóxa o a la epistéme?",
      groups: ["Dóxa", "Epistéme"],
      items: [
        { text: "Conjeturas a partir de sombras y reflejos (eikasía)", group: 0 },
        { text: "Creencia en los objetos físicos que vemos todos los días (pístis)", group: 0 },
        { text: "Razonamiento matemático a partir de hipótesis (dianoia)", group: 1 },
        { text: "Comprensión directa de las Formas, sin hipótesis previas (nóesis)", group: 1 },
        { text: "Se ocupa del mundo visible y cambiante", group: 0 },
      ],
      explain: "Los dos tramos inferiores de la línea tratan sobre el mundo sensible; los dos superiores, sobre un mundo inteligible y estable. La frontera entre ambos es, para Platón, la frontera misma entre opinar y saber.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que describe",
      pairs: [
        { left: "Paradoja de Menón", right: "Parece imposible investigar lo que no se conoce en absoluto" },
        { left: "Anamnesis", right: "Aprender es recordar lo que el alma ya sabía" },
        { left: "Opinión verdadera", right: "Acierta, pero sin un razonamiento que explique por qué" },
        { left: "Línea dividida", right: "Cuatro segmentos que van de la sombra a la Forma" },
      ],
      explain: "Todo el recorrido responde a una sola pregunta: qué distingue a un acierto casual de un conocimiento genuino. La respuesta de Platón pasa por el alma que recuerda, y por un razonamiento que ata la opinión hasta volverla firme.",
    },
    {
      type: "info",
      title: "Lo que falta: las Formas",
      body: "Toda esta clase dio vueltas alrededor de una palabra que todavía no definimos con precisión: la Forma, ese objeto último de la nóesis en la cima de la línea dividida, aquello que el alma recuerda cuando alcanza el conocimiento genuino. La próxima clase le dedicamos toda nuestra atención.",
    },
  ],
};
