export default {
  num: 8,
  transcript: null,
  title: "Platón: justicia y la ciudad ideal",
  source: "",
  feed: [
    {
      type: "info",
      title: "Trasímaco: la justicia es el interés del más fuerte",
      body: "La República se abre con un desafío directo. Trasímaco, un sofista, irrumpe en la conversación para afirmar que la justicia no es más que «el interés del más fuerte»: cada gobierno hace las leyes en su propio beneficio, y llama «justo» a obedecerlas. La tesis recuerda de cerca a la de Calicles, de la Clase 3, aunque Trasímaco la formula todavía más cínicamente: quien comete injusticia y se sale con la suya vive mejor que el justo.",
    },
    {
      type: "quiz",
      question: "¿Qué sostiene Trasímaco al abrir la República?",
      options: [
        "que la justicia es, en cada ciudad, el interés del más fuerte",
        "que la justicia sólo existe si todos los ciudadanos son iguales",
        "que ningún gobierno tiene derecho a dictar leyes propias",
        "que la injusticia siempre termina siendo castigada por los dioses",
      ],
      answer: 0,
      explain: "Cada gobierno hace las leyes en su propio beneficio, dice Trasímaco, y llama «justo» a obedecerlas. Es una tesis cercana a la de Calicles: quien comete injusticia y se sale con la suya vive, para él, mejor que el justo.",
    },
    {
      type: "info",
      title: "La ciudad y el alma se explican una a la otra",
      body: "Para responderle, Sócrates propone un atajo. Como es difícil ver la justicia en el alma de una sola persona, conviene primero buscarla en algo más grande y más visible, una ciudad entera, y después aplicar lo que se aprenda ahí de vuelta al alma individual. Construye entonces, en el diálogo, una ciudad ideal, la kallípolis, «la ciudad hermosa».",
    },
    {
      type: "info",
      continues: true,
      title: "La ciudad y el alma se explican una a la otra",
      body: "Esa ciudad tiene tres clases sociales, que corresponden exactamente a las tres partes del alma de la clase pasada. Los productores, campesinos, artesanos y comerciantes, corresponden al apetito; los guerreros o guardianes, al ánimo; y los gobernantes-filósofos, a la razón.",
    },
    {
      type: "quiz",
      question: "¿Por qué construye Sócrates una ciudad ideal en la República, en vez de discutir directamente sobre el alma individual?",
      options: [
        "porque la justicia es más fácil de ver en algo grande y visible",
        "porque en Atenas estaba prohibido discutir sobre el alma humana",
        "porque Trasímaco se negó a seguir hablando sobre justicia",
        "porque quería fundar una ciudad real fuera de Atenas",
      ],
      answer: 0,
      explain: "El atajo metodológico consiste en buscar primero la justicia en algo más grande y visible, una ciudad entera, para después aplicar lo aprendido de vuelta al alma individual, más difícil de observar directamente.",
    },
    {
      type: "info",
      title: "La justicia como hacer lo propio",
      body: "La justicia, tanto en la ciudad como en el alma, consiste para Platón en que cada parte cumpla su función propia sin invadir la de las demás: los productores producen, los guerreros defienden, y los filósofos gobiernan guiados por el conocimiento del Bien. Cuando cada clase se queda en lo suyo, la ciudad entera funciona en armonía; cuando una clase usurpa el lugar de otra, aparece la injusticia.",
    },
    {
      type: "info",
      title: "¿Por qué gobiernan los filósofos?",
      body: "Sólo quien ha hecho el recorrido completo de la línea dividida y ha contemplado la Forma del Bien —el prisionero liberado de la caverna— está en condiciones de gobernar bien, porque conoce el verdadero criterio del bien común y no se deja arrastrar por su propio interés ni por la opinión de la mayoría. Por eso Platón concluye, en una frase célebre, que las ciudades no van a dejar de sufrir males hasta que los filósofos gobiernen, o los gobernantes se pongan a filosofar.",
    },
    {
      type: "quiz",
      question: "Para Platón, ¿en qué consiste la justicia dentro de la ciudad ideal?",
      options: [
        "en que cada clase social cumpla su función propia, sin invadir otras",
        "en que las tres clases sociales roten sus funciones cada año",
        "en que todos los ciudadanos ganen exactamente el mismo salario",
        "en que sólo los productores tengan derecho a votar leyes",
      ],
      answer: 0,
      explain: "Los productores producen, los guerreros defienden y los filósofos gobiernan: la armonía de la ciudad depende de que cada clase se quede en lo suyo. La injusticia aparece cuando una invade la función de otra.",
    },
    {
      type: "quiz",
      question: "¿Por qué sostiene Platón que sólo los filósofos están capacitados para gobernar?",
      options: [
        "porque conocen el Bien y no siguen sólo su interés propio",
        "porque son los ciudadanos con más fuerza física de toda la ciudad",
        "porque nacieron en las familias más ricas y poderosas de Atenas",
        "porque son los únicos que saben leer y escribir en toda la ciudad",
      ],
      answer: 0,
      explain: "Haber contemplado la Forma del Bien, el recorrido completo de la caverna, da un criterio del bien común que no depende del interés propio ni de la opinión de la mayoría. Esa es, para Platón, la única base sólida para gobernar.",
    },
    {
      type: "info",
      title: "Una mentira útil",
      body: "Para mantener unida a esta ciudad tan jerárquica, Platón imagina un mito fundacional que llama, sin rodeos, una «mentira noble»: a cada ciudadano se le dice que los dioses pusieron oro en el alma de los gobernantes, plata en la de los guerreros y bronce o hierro en la de los productores. La medida es tan incómoda para la sensibilidad moderna que sigue generando polémica sobre qué tan en serio la proponía el propio Platón.",
    },
    {
      type: "short",
      question: "¿Cómo llama Platón, en la República, a la mentira fundacional sobre el oro, la plata y el bronce en el alma de cada clase?",
      answers: ["mentira noble", "noble mentira"],
      explain: "El mito dice que los dioses pusieron oro en el alma de los gobernantes, plata en la de los guerreros y bronce o hierro en la de los productores, para justificar y sostener la jerarquía de la ciudad ideal.",
    },
    {
      type: "info",
      title: "Cuando la ciudad se degrada",
      body: "En el libro VIII, Platón describe cómo la ciudad ideal se va degradando en un ciclo de cuatro regímenes, cada uno peor que el anterior. La timocracia, gobierno de honor militar, degenera en oligarquía, gobierno de los ricos; la oligarquía, por su desigualdad creciente, estalla en democracia, gobierno de la libertad sin límites; y la democracia, por exceso de libertad y falta de autoridad, termina pariendo a un tirano.",
    },
    {
      type: "classify",
      question: "¿Cada elemento corresponde a la ciudad o al alma?",
      groups: ["La ciudad", "El alma"],
      items: [
        { text: "Productores: campesinos, artesanos, comerciantes", group: 0 },
        { text: "Apetito: desea comida, bebida y placer", group: 1 },
        { text: "Guardianes o guerreros", group: 0 },
        { text: "Ánimo: busca honor, se indigna ante la injusticia", group: 1 },
        { text: "Gobernantes-filósofos", group: 0 },
      ],
      explain: "La estructura de la ciudad ideal calca, clase por clase, la estructura tripartita del alma de la clase pasada: productores y apetito, guerreros y ánimo, filósofos y razón.",
    },
    {
      type: "match",
      question: "Uní cada régimen con lo que lo caracteriza",
      pairs: [
        { left: "Timocracia", right: "Gobierno del honor militar" },
        { left: "Oligarquía", right: "Gobierno de los ricos, con desigualdad creciente" },
        { left: "Democracia", right: "Gobierno de la libertad sin límites" },
        { left: "Tiranía", right: "Nace del exceso de libertad democrática" },
      ],
      explain: "El ciclo describe una degradación continua: cada régimen resuelve el exceso del anterior, pero cae en un exceso distinto, hasta terminar en el gobierno de un solo tirano, la forma más alejada de la ciudad ideal.",
    },
    {
      type: "info",
      title: "Lo que le falta a este sistema",
      body: "Toda esta arquitectura política y psicológica depende, en última instancia, de que el Bien exista y de que el cosmos tenga un orden racional que los filósofos puedan conocer. La próxima clase revisamos esa pregunta de fondo, la del origen mismo del cosmos, y hacemos un primer balance de toda la filosofía de Platón.",
    },
  ],
};
