export default {
  num: 21,
  transcript: 22,
  title: "Posestructuralismo francés: Derrida y la deconstrucción",
  source: "https://www.youtube.com/watch?v=nCGW_H7s7Q4",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Jacques Derrida** (1930-2004) nace en El-Biar, cerca de Argel, en una familia judía. En 1942, bajo las leyes raciales que el régimen de Vichy extiende a la Argelia colonial, es expulsado de la escuela por ser judío: la experiencia de la marginalidad —judío, argelino, colonial en la metrópoli— atraviesa buena parte de su obra posterior. Se forma en la Sorbona y en la École Normale Supérieure, donde rinde la agrégation de filosofía.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En 1967 publica de una sola vez los tres libros que fundan la deconstrucción: De la gramatología, La escritura y la diferencia y La voz y el fenómeno. Ese mismo año aparece también, dentro de La escritura y la diferencia, el texto que lo presenta al mundo anglosajón: La estructura, el signo y el juego en el discurso de las ciencias humanas, leído un año antes en una conferencia en la Universidad Johns Hopkins.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Enseña la mayor parte de su carrera en la École des Hautes Études en Sciences Sociales de París, y desde los años ochenta pasa temporadas regulares en universidades estadounidenses, sobre todo en Yale, donde entabla una amistad decisiva con el crítico literario **Paul de Man**. Muere en París en 2004.",
    },
    {
      type: "quiz",
      question: "¿Qué marca a Derrida desde su infancia argelina, según la clase?",
      options: [
        "La expulsión de la escuela por las leyes raciales de Vichy",
        "El exilio forzado de toda su familia a Francia en 1945",
        "La pérdida de su lengua materna durante la ocupación",
        "Una educación exclusivamente religiosa hasta los veinte años",
      ],
      answer: 0,
      explain: "En 1942, bajo las leyes raciales que Vichy extiende a la Argelia colonial, Derrida es expulsado de la escuela por ser judío. La experiencia de la marginalidad atraviesa buena parte de su obra posterior.",
    },
    {
      type: "info",
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "El posestructuralismo de Foucault deja abierta una pregunta que venía latente desde Lévi-Strauss: ¿es la estructura, alguna vez, un sistema realmente cerrado? Foucault desplaza la agencia al discurso, pero conserva un método —la arqueología, después la genealogía— que sigue describiendo totalidades, aunque sean totalidades que cambian en el tiempo. Derrida sospecha que ahí queda todavía un resto de sistema por desarmar.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "Dos preguntas organizan su entrada al posmodernismo, y están relacionadas entre sí: ¿se puede reemplazar a Dios? Y ¿se puede escapar de Hegel? En ambos casos la respuesta que se desprende de su obra es negativa, aunque el intento mismo de escapar sea, para él, filosóficamente necesario y nunca del todo inútil.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "Conviene distinguir tres capas de un mismo fenómeno. El **posmodernismo** es el rótulo general de una manera de pensar el mundo que se consolida sobre todo después de 1968, en ruptura con buena parte del pensamiento moderno. El **posestructuralismo** es una forma más específica de posmodernismo, la que nace de sondear las debilidades del estructuralismo desde adentro. La **deconstrucción** es la metodología y la filosofía particular de Derrida dentro de esa corriente, su ejemplo por excelencia.",
    },
    {
      type: "classify",
      question: "¿Cada término nombra el rótulo general, la corriente o el método de Derrida?",
      groups: ["Posmodernismo / posestructuralismo", "Deconstrucción"],
      items: [
        { text: "El rótulo general de una época que rompe con el pensamiento moderno", group: 0 },
        { text: "La corriente que nace de sondear las fallas del estructuralismo", group: 0 },
        { text: "El método particular de Derrida dentro de esa corriente", group: 1 },
        { text: "Desarma binarios jerarquizados como habla y escritura", group: 1 },
      ],
      explain: "El posmodernismo es el rótulo general de la época; el posestructuralismo, la forma específica que nace de sondear las debilidades del estructuralismo; la deconstrucción, la metodología y filosofía particular de Derrida dentro de esa corriente.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "La posmodernidad despega, simbólicamente, con 1968: en particular con la invasión de Praga por los tanques del Pacto de Varsovia y el aplastamiento del \"socialismo con rostro humano\", que funciona como el fin simbólico del marxismo como filosofía profundamente vivida —la última gran estructura, el último gran relato—. No es casual que la muerte del marxismo como sistema totalizador y el auge del posestructuralismo lleguen juntos.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "Derrida es el pensador emblemático de ese momento: por excelencia, alguien que **desarma** en lugar de construir, en la línea de Nietzsche. No ofrece un sistema, ni siquiera —como Foucault— una metodología positiva para escribir historia: pide, en cambio, aprender a leer, pensar y escribir de otro modo, tratando la vida entera como un **texto** que puede desarmarse.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "En 1979, **Jean-François Lyotard**, en La condición posmoderna, da la definición más citada de todo el movimiento: define lo posmoderno como incredulidad hacia los metarrelatos, escepticismo hacia los grandes relatos que hacen que todo encaje y tenga sentido. La posmodernidad es no creer que exista relato, filosofía o cosmovisión alguna capaz de reunirlo todo y mantenerlo unido.",
    },
    {
      type: "short",
      question: "¿Con qué palabra define Lyotard lo posmoderno frente a los grandes relatos?",
      answers: ["incredulidad"],
      explain: "Lyotard define lo posmoderno como incredulidad hacia los metarrelatos: escepticismo hacia los grandes relatos que pretenden hacer que todo encaje y tenga sentido, como el progreso o la emancipación marxista.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "Su prosa es difícil: mezcla el legado de Saussure con el de Heidegger, lee a Husserl, Nietzsche, Freud y Lévi-Strauss, e inventa términos jugando con las posibilidades del francés, lo que la vuelve casi intraducible.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: agotar a Hegel y a Lévi-Strauss",
      body: "Tony Judt la acusó de practicar \"una filosofía de oscurantismo narcisista\"; el fenomenólogo Robert Sokolowski la describió como algo que debía mencionarse en el panorama fenomenológico \"con cierta vergüenza, como una familia obligada a hablar de un tío excéntrico cuyas payasadas todos conocen pero a quien se evita nombrar en sociedad\".",
    },
    {
      type: "info",
      title: "Logocentrismo y la metafísica de la presencia",
      body: "Derrida llama **logocentrismo** a la tradición occidental que privilegia el habla —el logos, la palabra viva— por encima de la escritura, y que hace descansar el sentido en la proximidad entre pensamiento y voz: hablar parece garantizar que el yo real de quien habla está inmediatamente presente, con acceso directo a su propia interioridad.",
    },
    {
      type: "info",
      continues: true,
      title: "Logocentrismo y la metafísica de la presencia",
      body: "El logocentrismo es, a su vez, una variante de lo que Derrida llama la **metafísica de la presencia**: la convicción, nunca demostrada, de que el ser pleno de las cosas y del sentido se da en la presencia inmediata, y que todo lo mediado, diferido o ausente es una forma degradada de esa plenitud original. Desarmar esa jerarquía —presencia sobre ausencia, habla sobre escritura— es el primer movimiento de toda deconstrucción.",
    },
    {
      type: "quiz",
      question: "¿Por qué el habla parece más confiable que la escritura para el logocentrismo?",
      options: [
        "Porque hablar garantizaría acceso inmediato a la propia interioridad",
        "Porque la escritura fue inventada mucho después que el habla",
        "Porque sólo el habla puede transmitirse entre generaciones",
        "Porque la escritura depende siempre de una autoridad externa",
      ],
      answer: 0,
      explain: "El logocentrismo privilegia el habla porque hace descansar el sentido en la proximidad entre pensamiento y voz: hablar parecería garantizar que el yo real de quien habla está inmediatamente presente ante sí mismo.",
    },
    {
      type: "info",
      title: "Contra Lévi-Strauss: habla y escritura",
      body: "Derrida empieza por la autobiografía de Lévi-Strauss, Tristes trópicos, y por la relación entre **habla y escritura** en las culturas que Lévi-Strauss llama \"primitivas\". Lévi-Strauss presenta la introducción de la escritura como una pérdida de la inocencia, la llegada de la jerarquía, el control y la violencia: el habla sería inmediata y auténtica, la escritura, mediada y por eso menos auténtica.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra Lévi-Strauss: habla y escritura",
      body: "Derrida desarma ese binario con un procedimiento que se repite en toda su obra: encontrar un par de opuestos jerarquizado —habla y escritura, presencia y ausencia— y mostrar que el término subordinado no es un simple accidente del término privilegiado, sino su condición de posibilidad. Saussure, y detrás de él la metafísica occidental desde los griegos, había privilegiado el habla sobre la escritura por la misma razón que privilegia la presencia sobre la ausencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra Lévi-Strauss: habla y escritura",
      body: "Pero la presencia, sostiene Derrida, es una **ilusión**: el yo que habla ni siquiera está necesariamente presente ante sí mismo, un argumento que retoma de Freud y de la idea de un inconsciente que el sujeto no controla ni conoce del todo. El lenguaje es, en ese sentido, más ausencia que presencia; el significado es todo **diferencia**: las otras ausencias, los otros significantes posibles, son esenciales al significado de cualquiera de ellos.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra Lévi-Strauss: habla y escritura",
      body: "Derrida amplía entonces el concepto de texto para abarcar tanto la ausencia como la presencia, que ya no pueden desenredarse del todo: **todo se vuelve texto**, no sólo lo escrito en sentido estricto, sino cualquier gesto, coreografía o práctica que pueda leerse e interpretarse con ese mismo método.",
    },
    {
      type: "quiz",
      question: "En la lectura de Derrida, ¿qué es la escritura respecto del habla?",
      options: [
        "Su condición de posibilidad, no un accidente externo",
        "Un accidente prescindible que no afecta al habla",
        "Una copia degradada sin ninguna relación con el habla",
        "Un invento moderno ajeno a las culturas primitivas",
      ],
      answer: 0,
      explain: "Derrida repite un procedimiento: encontrar un binario jerarquizado y mostrar que el término subordinado —la escritura— no es un accidente del privilegiado, sino su condición de posibilidad.",
    },
    {
      type: "info",
      title: "El significado trascendental y la ausencia de centro",
      body: "En La estructura, el signo y el juego Derrida es respetuoso con Lévi-Strauss, pero sostiene que **no va lo suficientemente lejos**. Del lado del significante, \"gato\" es gato porque no es \"pato\" ni \"gasto\", pero tampoco \"casa\" ni \"bote\": las diferencias y ausencias que lo definen son, en principio, infinitas. Del lado del significado ocurre lo mismo: \"bueno\" es bueno porque no es \"malo\", pero tampoco alto, azul o limpio.",
    },
    {
      type: "info",
      continues: true,
      title: "El significado trascendental y la ausencia de centro",
      body: "Para el estructuralismo la relación entre significante y significado es arbitraria, pero el signo constituye igual una **unidad** estable. Derrida cuestiona esa unidad: para que existiera haría falta un **arché**, un primer principio, un fundamento absoluto —un **significado trascendental**— capaz de anclar el sistema entero. Y ese significado trascendental ocupa exactamente el lugar que dejó vacante Dios.",
    },
    {
      type: "info",
      continues: true,
      title: "El significado trascendental y la ausencia de centro",
      body: "La modernidad quiso reemplazar a Dios poniendo en su lugar la Historia, el Hombre, el sujeto. Derrida sostiene que no hay Dios, ni sustituto de Dios, ni primer principio que sostenga las cosas: no hay nada que **ancle** el sentido de manera definitiva. No sólo Dios está muerto, sino que la idea misma de que algo pudiera ocupar su lugar está muerta: es un **antifundacionalismo**, la tesis de la imposibilidad de todo fundamento último.",
    },
    {
      type: "quiz",
      question: "¿Qué lugar ocupa, para Derrida, el «significado trascendental»?",
      options: [
        "El que dejó vacante Dios como fundamento último del sentido",
        "El lugar de la conciencia individual que interpreta el signo",
        "El lugar de la historia como motor de todo cambio social",
        "El lugar del significante privilegiado dentro de cada signo",
      ],
      answer: 0,
      explain: "Para que el signo fuera una unidad estable haría falta un arché, un fundamento absoluto. Ese significado trascendental ocupa exactamente el lugar que dejó vacante Dios; Derrida niega que exista.",
    },
    {
      type: "info",
      title: "El juego",
      body: "Las estructuras necesitan un centro para contener el **juego** infinito de los significantes: sin significado trascendental, nada limita ese juego. Los significantes están siempre trabajando con, contra y en torno a otros; el significado nunca está del todo presente en un signo, siempre está en parte ausente, suspendido, diferido, aún por venir. El lenguaje es, por naturaleza, inestable.",
    },
    {
      type: "info",
      continues: true,
      title: "El juego",
      body: "Terry Eagleton ilustra esa lógica con el par hombre/mujer: la mujer es \"lo otro\" del hombre, su negativo, pero el hombre es lo que es sólo en virtud de excluir sin cesar a esa otra, definiéndose por antítesis; su identidad entera queda en riesgo en el mismo gesto con que busca afirmar su autonomía, porque su ser depende, parasitariamente, de aquello que excluye. Lo que queda afuera está también, de algún modo, adentro.",
    },
    {
      type: "info",
      continues: true,
      title: "El juego",
      body: "Los binarios centrales del estructuralismo —naturaleza y cultura, empírico y racional, sensible e inteligible— son, para Derrida, construcciones ideológicas que siempre pueden socavarse: nunca son tan limpios como se cree, y contienen a la vez las semillas de su propia negación y las de su reproducción en variaciones múltiples.",
    },
    {
      type: "quiz",
      question: "En el ejemplo de Eagleton, ¿por qué la identidad del hombre queda en riesgo?",
      options: [
        "Porque depende, para definirse, de aquello mismo que excluye",
        "Porque la mujer termina siendo idéntica al hombre con el tiempo",
        "Porque el lenguaje no permite nombrar ningún género con precisión",
        "Porque ambos términos son completamente independientes entre sí",
      ],
      answer: 0,
      explain: "El hombre se define por antítesis excluyendo a la mujer como «lo otro», pero su ser depende parasitariamente de aquello que excluye: lo que queda afuera está también, de algún modo, adentro.",
    },
    {
      type: "info",
      title: "Différance",
      body: "**Différance** combina los dos sentidos del verbo francés différer: diferir en el sentido de ser distinto, y diferir en el sentido de aplazar. El término permite moverse a la vez por el eje sincrónico y el diacrónico: el significado es siempre **distinto** de sí mismo y a la vez **aplazado**, todavía por venir, nunca decisivo ni cerrado.",
    },
    {
      type: "info",
      continues: true,
      title: "Différance",
      body: "A diferencia del estructuralismo, que sólo opera poniendo entre paréntesis la historia para mirar lo sincrónico, Derrida integra lo diacrónico dentro del significado mismo: el sentido está siempre por venir, porque la vida sigue, y no hay ningún punto en el que ese proceso pueda cerrarse del todo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Derrida al término que combina diferir-ser-distinto con diferir-aplazar?",
      answers: ["différance", "diferancia"],
      explain: "Différance combina los dos sentidos del verbo francés différer: el significado es siempre distinto de sí mismo y a la vez aplazado, todavía por venir, nunca decisivo ni cerrado.",
    },
    {
      type: "info",
      title: "Traza y suplemento",
      body: "La **traza** es el excedente de otros significados posibles que queda, a la vez presente y ausente, dentro de cualquier significante: significados de los que un signo parece carecer, pero de los que en realidad depende su propio sentido, un resto de lo que quedó atrás y que sigue actuando.",
    },
    {
      type: "info",
      continues: true,
      title: "Traza y suplemento",
      body: "Un concepto emparentado, tomado de la lectura que Derrida hace de Rousseau en De la gramatología, es el del **suplemento**. Rousseau describe la escritura como un suplemento peligroso del habla: algo añadido desde afuera a una plenitud —el habla viva, la presencia a sí— que existía, se supone, antes y sin necesidad de él.",
    },
    {
      type: "info",
      continues: true,
      title: "Traza y suplemento",
      body: "Derrida invierte el argumento: si el habla necesitó ese suplemento para conservarse y transmitirse más allá del momento en que se pronuncia, es porque nunca fue la plenitud autosuficiente que se le atribuye. La misma lógica se repite en toda la metafísica de la presencia: cada vez que algo se presenta como un simple añadido prescindible de un origen pleno, ese añadido termina revelando que el origen dependía de él desde siempre. El suplemento no se agrega a una plenitud ya dada: la constituye retroactivamente.",
    },
    {
      type: "quiz",
      question: "Para Derrida, ¿qué revela el suplemento sobre el origen al que se agrega?",
      options: [
        "Que ese origen nunca fue la plenitud autosuficiente que parecía",
        "Que el origen sigue siendo pleno pese al añadido posterior",
        "Que el suplemento es siempre prescindible y accesorio",
        "Que Rousseau tenía razón al ver la escritura como una pérdida",
      ],
      answer: 0,
      explain: "Si el habla necesitó del suplemento —la escritura— para conservarse más allá del instante en que se pronuncia, es porque nunca fue la plenitud autosuficiente que Rousseau le atribuía: el suplemento constituye retroactivamente el origen.",
    },
    {
      type: "info",
      title: "Aporía y bajo tachadura",
      body: "La **aporía**, o doble vínculo, es el momento en que el significado se **niega a sí mismo**: el lenguaje se socava hasta un punto muerto en el que parece no haber sentido posible, atrapado entre exigencias contradictorias.",
    },
    {
      type: "info",
      continues: true,
      title: "Aporía y bajo tachadura",
      body: "El terror estalinista ofrece un caso extremo: la consigna de vigilancia permanente —el enemigo puede estar en cualquier parte— convive con la certeza de que las leyes de hierro de la historia llevan inevitablemente a la utopía comunista. Si el futuro está predeterminado, no se entiende por qué haría falta vigilar; si hace falta vigilar todo el tiempo, el futuro no puede estar tan determinado.",
    },
    {
      type: "info",
      continues: true,
      title: "Aporía y bajo tachadura",
      body: "**Bajo tachadura** es el procedimiento de usar una palabra sin comprometerse del todo con ella, tachándola para señalar su inadecuación sin dejar de emplearla. Una anécdota conocida lo ilustra: al firmar una dedicatoria en un ejemplar de Dar la muerte, Derrida tachó la propia palabra \"muerte\", poniéndola literalmente bajo tachadura.",
    },
    {
      type: "quiz",
      question: "¿Qué es una aporía para Derrida?",
      options: [
        "El punto en que el lenguaje se socava entre exigencias contradictorias",
        "Un error lógico que la deconstrucción corrige con precisión",
        "Un sinónimo simple de la différance sin matices propios",
        "La ausencia total y definitiva de cualquier significado posible",
      ],
      answer: 0,
      explain: "La aporía, o doble vínculo, es el momento en que el significado se niega a sí mismo: como en el terror estalinista, atrapado entre la vigilancia permanente y la certeza de un futuro ya determinado.",
    },
    {
      type: "info",
      title: "Qué es deconstruir, en concreto",
      body: "El procedimiento, entonces, tiene una estructura reconocible. Primero se localiza un binario jerarquizado que la tradición da por natural —habla/escritura, hombre/mujer, presencia/ausencia—. Después se muestra que el término subordinado no es un accidente externo del privilegiado, sino su condición de posibilidad, aquello sin lo cual ni siquiera podría sostenerse.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué es deconstruir, en concreto",
      body: "El paso final no consiste en invertir la jerarquía —poner la escritura por encima del habla— sino en mostrar que ninguno de los dos términos puede fijarse en su lugar de manera estable: cada uno depende del otro, y esa dependencia mutua es lo que impide clausurar el sentido en cualquier dirección.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué es deconstruir, en concreto",
      body: "**Deconstruir no es destruir**: es desarmar, deshacer, no aplastar. Lo que se desarma es la **estabilidad**, el significado decisivo que se pretende sostener en su lugar; nada queda fijo, y los binarios que antes ordenaban la percepción quedan, después de la operación, en movimiento permanente.",
    },
    {
      type: "info",
      continues: true,
      title: "Qué es deconstruir, en concreto",
      body: "En una entrevista Derrida describió la deconstrucción como algo que **ocurre**, no como una técnica puramente lingüística o libresca: se pueden deconstruir gestos y coreografías, porque todo, en algún sentido, es un texto.",
    },
    {
      type: "quiz",
      question: "El paso final de deconstruir un binario jerarquizado consiste en…",
      options: [
        "mostrar que ninguno de los dos términos puede fijarse de modo estable",
        "invertir la jerarquía, poniendo el término subordinado primero",
        "eliminar por completo uno de los dos términos del binario",
        "demostrar que el binario nunca existió en la tradición occidental",
      ],
      answer: 0,
      explain: "Deconstruir no es invertir la jerarquía sino mostrar que cada término depende del otro: esa dependencia mutua impide clausurar el sentido en cualquier dirección. Deconstruir no es destruir, es desarmar la estabilidad.",
    },
    {
      type: "info",
      title: "Derrida y Paul de Man",
      body: "**Paul de Man**, mayor que Derrida —nació en 1919—, era belga flamenco de educación francesa y tenía veinte o veintiún años cuando los nazis ocuparon Bélgica, en mayo de 1940. Fue entonces periodista de diarios colaboracionistas nazis, entre aproximadamente 1940 y 1942.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Tras la guerra emigró a Estados Unidos, se doctoró en Harvard y conoció a Derrida en la conferencia de 1966 en Johns Hopkins, que fue en cierto modo el elogio fúnebre del estructuralismo y la cuna pública de la deconstrucción.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Se vuelven amigos íntimos y colaboradores. De Man, como profesor en Yale, convierte a esa universidad en centro de la crítica literaria deconstruccionista durante los años setenta, y sostiene que la literatura ni siquiera necesita de un crítico para deconstruirse: se deconstruye sola. Muere prematuramente de cáncer en 1983.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Poco después, un estudiante de posgrado que investigaba su obra descubre, en archivos de diarios belgas de la ocupación, que De Man había sido un escritor colaboracionista durante la guerra. Le hace llegar los textos a Derrida y le pide una respuesta.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Derrida responde con un artículo largo y desgarrador, Como el sonido del mar en el fondo de una caracola: la guerra de Paul de Man, que algunos leyeron como la bancarrota de la deconstrucción y otros como uno de los textos más conmovedores jamás escritos sobre la amistad intelectual.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Mi sentimiento fue, ante todo, el de una herida, un estupor y una tristeza que no quiero ni disimular ni exhibir. Durante casi veinte años no tuve la menor razón para sospechar que mi amigo pudiera ser el autor de tales artículos.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Derrida intenta, siendo él mismo judío, un análisis deconstruccionista de esos textos antisemitas de guerra, para mostrar que ningún significado determinado resulta posible en ellos y que el lenguaje dice siempre algo distinto de lo que dice. Uno de los artículos de De Man, de 1941, sostenía que la literatura occidental \"se ha salvaguardado de la influencia judía\" y que una eventual \"colonia judía aislada de Europa\" no acarrearía consecuencias deplorables para la vida literaria de Occidente.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "Derrida escribe: \"nada de lo que voy a decir cicatrizará la herida que sentí de inmediato al percibir en él lo que se ha señalado como antisemitismo reconocido\", y a la vez insiste en que el artículo entero está organizado, \"por otro lado\", como una acusación del antisemitismo vulgar.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida y Paul de Man",
      body: "El propio Derrida sostuvo que \"la deconstrucción ha representado siempre, para mí, la condición mínima necesaria para identificar y combatir el riesgo totalitario\": una filosofía nacida de una sensibilidad crítica de izquierda, diseñada para desarmar las pretensiones de verdad absoluta que llevaron a lugares como el nazismo y el estalinismo. Cómo se concilia esa autocomprensión con la defensa de De Man sigue siendo, para sus críticos, la pregunta abierta más incómoda de toda su obra.",
    },
    {
      type: "quiz",
      question: "¿Qué revela el caso de Paul de Man sobre la propia deconstrucción de Derrida?",
      options: [
        "Una tensión sin resolver entre la amistad y la propia filosofía",
        "Que Derrida rompió inmediatamente toda relación con De Man",
        "Que la deconstrucción resultó incompatible con la crítica literaria",
        "Que De Man nunca fue en realidad un colaborador nazi",
      ],
      answer: 0,
      explain: "Derrida, judío él mismo, intentó un análisis deconstruccionista de los textos antisemitas de su amigo sin negar la herida que sintió. La defensa dividió a los lectores entre bancarrota de la deconstrucción y texto conmovedor sobre la amistad.",
    },
    {
      type: "match",
      question: "Uní cada término de la deconstrucción con lo que nombra",
      pairs: [
        { left: "Logocentrismo", right: "Privilegiar el habla sobre la escritura, la voz sobre el texto" },
        { left: "Significado trascendental", right: "El centro o fundamento absoluto que ancla el sentido" },
        { left: "Différance", right: "El significado es a la vez distinto de sí y siempre aplazado" },
        { left: "Traza", right: "El excedente de otros sentidos, presente y ausente en el signo" },
        { left: "Deconstruir", right: "Desarmar la estabilidad de un binario, no destruirlo" },
      ],
      explain: "El logocentrismo privilegia la voz porque cree en una presencia plena del sentido; sin significado trascendental que la ancle, la différance vuelve todo signo distinto de sí y aplazado, cargado de la traza de lo que excluye. Deconstruir es desarmar esa estabilidad supuesta, no destruirla.",
    },
    {
      type: "info",
      title: "Cierre: el juego, la afirmación y el vacío",
      body: "Para Derrida la deconstrucción es política en un sentido preciso: es la resistencia y el antídoto contra el modo de pensar de las pretensiones de verdad absoluta que llevaron al totalitarismo. Que el significado esté siempre **en juego** no equivale a la ausencia de significado, ni al nihilismo, ni a la idea de que nada importa: es, según su propia descripción, una **afirmación gozosa** de la creatividad y del potencial humano.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el juego, la afirmación y el vacío",
      body: "Volverse hacia la presencia perdida o imposible del origen ausente —esta temática estructuralista de la inmediatez rota— es el lado triste, negativo, nostálgico, culpable, rousseauniano del pensamiento del juego, cuyo otro lado sería la afirmación nietzscheana, la afirmación gozosa del juego del mundo y de la inocencia del devenir; la afirmación de un mundo de signos sin falta, sin verdad y sin origen, ofrecido a una interpretación activa… y juega sin seguridad.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el juego, la afirmación y el vacío",
      body: "En vez de llorar el centro perdido, la deconstrucción propone regocijarse en la oportunidad y la creatividad que abre su ausencia. Pero, como la vanguardia, deja al final colgando: todo resulta posible, y sin embargo no queda nada estable a lo que aferrarse.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: el juego, la afirmación y el vacío",
      body: "Esa tensión entre desarmar el sentido y necesitar sentido para actuar en la historia es la que van a poner a prueba, poco después, las resistencias intelectuales del Este europeo: quienes vivieron el desmoronamiento real de un gran relato compartido y debieron reconstruir, contra el desencanto posmoderno, algo parecido a una verdad por la que valiera la pena resistir.",
    },
  ],
};
