export default {
  num: 18,
  transcript: 19,
  title: "Estructuralismo y antropología",
  source: "https://www.youtube.com/watch?v=k0ZLNVIrdcU",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "El **estructuralismo** no tiene un solo fundador sino un cruce de dos linajes que se encuentran en Nueva York durante la Segunda Guerra Mundial. El lingüista suizo **Ferdinand de Saussure** (1857-1913) enseña en Ginebra y muere sin publicar su obra mayor: el Curso de lingüística general es una compilación de apuntes de alumnos, editada por sus colegas Charles Bally y Albert Sechehaye y publicada póstumamente en 1916.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El lingüista ruso **Roman Jakobson** (1896-1982) funda de adolescente el Círculo Lingüístico de Moscú y después el de Praga (1926), y huye de la Europa ocupada por los nazis hasta Nueva York, donde en los años cuarenta se cruza con el antropólogo francés **Claude Lévi-Strauss** (1908-2009), también exiliado. De ese encuentro, mediado por el historiador de la ciencia **Alexandre Koyré**, sale la antropología estructural: sus obras centrales son Las estructuras elementales del parentesco (1949), Antropología estructural (1958), El pensamiento salvaje (1962) y la serie Mitológicas (cuatro volúmenes, 1964-1971).",
    },
    {
      type: "quiz",
      question: "¿Dónde y por qué se encuentran Jakobson y Lévi-Strauss?",
      options: [
        "En Nueva York, exiliados los dos de la Europa en guerra",
        "En Ginebra, como colegas de Saussure en la universidad",
        "En Praga, dentro del mismo Círculo Lingüístico fundado por él",
        "En Moscú, antes de que ninguno de los dos emigrara jamás",
      ],
      answer: 0,
      explain: "Jakobson huye de la Europa ocupada por los nazis y Lévi-Strauss también está exiliado: se cruzan en Nueva York en los años cuarenta, mediados por Alexandre Koyré. De ese encuentro nace la antropología estructural.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "El existencialismo francés y el marxismo revisionista habían insistido en un sujeto **incrustado** en estructuras históricas que lo preceden —arrojado a un mundo con el que sin embargo interactúa y al que moldea— sin perder por eso su responsabilidad. El estructuralismo hereda la idea de estructura, pero le retira ese resto de sujeto activo: la agencia individual y el sentido de la historia dejan de ser el punto de partida.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Es, en ese sentido, otra respuesta a la muerte de Dios: otro intento de llenar el vacío que deja la pérdida de un fundamento último. Pero a diferencia de la fenomenología, que buscaba ese fundamento en la intencionalidad de la conciencia, el estructuralismo lo busca en un **sistema** que antecede y organiza a los sujetos que lo habitan: signos que se relacionan entre sí, no conciencias que apuntan hacia un mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Por eso el estructuralismo es **antihumanista**, no en sentido normativo —no propone crueldad ni desprecio— sino descriptivo: el sujeto individual no está en el centro, no es la fuente del sentido ni lo que mantiene unido al sistema. Es un giro antirromántico: nada de voluntad ni de genio individual, mucha racionalidad y mucho sistema. La variable primaria deja de ser el tiempo o la subjetividad y pasa a ser la **estructura**.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "La inspiración común a todas las variantes del estructuralismo —lingüística, antropología, después psicoanálisis y crítica literaria— es la **lingüística estructural**: la apuesta de repensar cualquier fenómeno cultural tomando el lenguaje como modelo. Si el lenguaje es un sistema de diferencias sin términos positivos, tal vez el parentesco, el mito o la moda funcionen del mismo modo.",
    },
    {
      type: "quiz",
      question: "El estructuralismo es «antihumanista» en un sentido…",
      options: [
        "descriptivo: el sujeto no es el centro ni la fuente del sentido",
        "normativo: propone tratar con crueldad al individuo",
        "político: milita activamente contra los derechos humanos",
        "religioso: niega cualquier dignidad propia del ser humano",
      ],
      answer: 0,
      explain: "No es una posición moral sino descriptiva: el sujeto individual no está en el centro ni sostiene el sistema. Es un giro antirromántico, opuesto a la voluntad y al genio individual, hacia la estructura.",
    },
    {
      type: "info",
      title: "Saussure: la lengua como sistema de diferencias",
      body: "Saussure fija primero el objeto de la lingüística: **la lengua considerada en y por sí misma**, no el habla individual ni la historia de las palabras. Y da un segundo paso, más radical: **la lengua es forma, no sustancia**. No hay que buscar en ella cosas con propiedades intrínsecas, sino una red de diferencias que se sostienen unas a otras.",
    },
    {
      type: "info",
      continues: true,
      title: "Saussure: la lengua como sistema de diferencias",
      body: "El **signo lingüístico** tiene naturaleza dual: un **significante** (la secuencia de sonidos o letras) y un **significado** (el concepto al que remite). El signo es la unión de ambos, pero buena parte del trabajo de Saussure consiste en **desenredarlos**: mostrar que ninguno de los dos términos explica al otro por sí solo.",
    },
    {
      type: "info",
      continues: true,
      title: "Saussure: la lengua como sistema de diferencias",
      body: "La tesis que organiza todo lo demás es que **la relación entre significante y significado es arbitraria**. No hay ninguna ley física ni ninguna semejanza que exija que la secuencia de sonidos \"gato\" refiera a ese animal: lo confirma el hecho de que existan miles de lenguas con miles de palabras distintas para lo mismo. La relación es cuestión de **convención**, no de naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "Saussure: la lengua como sistema de diferencias",
      body: "Si la relación fuera solo arbitraria, cualquier cosa podría significar cualquier cosa en cualquier momento. Pero es además **estable**, y eso obliga a precisar el argumento: un significante significa no por parecerse a su significado, sino **por contraste** con los demás significantes del sistema. \"Gato\" significa lo que significa porque no es \"pato\", ni \"gasto\", ni \"perro\". El **valor** de un signo es siempre diferencial.",
    },
    {
      type: "quiz",
      question: "Si la relación entre significante y significado es arbitraria, ¿por qué no cambia todo el tiempo?",
      options: [
        "Porque el valor de cada signo depende de su contraste con otros",
        "Porque en realidad existe una semejanza natural con la cosa",
        "Porque una sola persona puede fijar el significado para siempre",
        "Porque el significante determina por sí solo al significado",
      ],
      answer: 0,
      explain: "«Gato» significa lo que significa porque no es «pato» ni «perro»: el valor es diferencial, no una semejanza con la cosa. Esa red de contrastes, sostenida por toda una comunidad, es lo que da estabilidad al sistema.",
    },
    {
      type: "info",
      continues: true,
      title: "Saussure: la lengua como sistema de diferencias",
      body: "Esa estabilidad depende de que el sistema sea un **todo holístico**: ningún elemento tiene significado al margen de su relación con los demás, y esa red de relaciones la sostiene una comunidad entera, no un individuo aislado. Nadie puede inventar una lengua privada que funcione: hace falta el acuerdo tácito de una comunidad de hablantes para que los valores se fijen y se mantengan.",
    },
    {
      type: "info",
      continues: true,
      title: "Saussure: la lengua como sistema de diferencias",
      body: "Saussure distingue además dos planos de estudio. El **diacrónico** sigue la lengua a través del tiempo, su evolución histórica. El **sincrónico** describe cómo funciona la lengua como sistema en un momento dado, sin referencia a su pasado. Son dos preguntas distintas, y el estructuralismo elige trabajar en el plano sincrónico: después de tanto insistir en la historia, se detiene el reloj para mirar el sistema en un corte transversal.",
    },
    {
      type: "info",
      continues: true,
      title: "Saussure: la lengua como sistema de diferencias",
      body: "El ejemplo que Saussure usa para esa distinción es el **ajedrez**: el estado de un tablero en un momento dado es comprensible por sí mismo, con independencia de las jugadas que lo produjeron. Quien siguió la partida entera no tiene, para describir esa posición, ninguna ventaja sobre quien la ve por primera vez. Del mismo modo, nadie presencia el origen del lenguaje: siempre se nace ya dentro de un sistema en marcha.",
    },
    {
      type: "short",
      question: "¿Cómo llama Saussure al plano que describe la lengua como sistema en un momento dado, sin referencia a su pasado?",
      answers: ["sincrónico", "sincronía"],
      explain: "El plano sincrónico, opuesto al diacrónico (la evolución en el tiempo). Como en el ajedrez: la posición del tablero se entiende sola, sin necesidad de conocer las jugadas anteriores. El estructuralismo elige trabajar ahí.",
    },
    {
      type: "info",
      title: "Esperanto: la lengua sin dueño",
      body: "El polaco **Ludwik Zamenhof**, oftalmólogo de formación, publicó en 1887 el proyecto de una lengua internacional bajo el seudónimo \"Doctor Esperanto\". Criado en una ciudad con varias comunidades lingüísticas en conflicto, buscaba un idioma sin excepciones gramaticales que nadie poseyera más que otro: un puente igualador entre hablantes de lenguas distintas. El esperanto sobrevive hasta hoy como lengua minoritaria, aunque no cumplió su ambición original de volverse universal.",
    },
    {
      type: "info",
      title: "De la lingüística a la semiología",
      body: "La lingüística estructural inspira un proyecto más amplio: la **semiología**, el estudio de los signos y sus leyes en cualquier sistema cultural, no solo en el lenguaje verbal. De ahí salen dos consecuencias que van a reaparecer una y otra vez: el significado es siempre **relacional**, y el lenguaje no expresa un sentido previo sino que lo **produce**. Los signos no reflejan el pensamiento: lo estructuran.",
    },
    {
      type: "info",
      continues: true,
      title: "De la lingüística a la semiología",
      body: "Ese programa entronca con el **formalismo ruso** —el estudio de la literatura como sistema de procedimientos, no como expresión de un contenido— y con el **Círculo Lingüístico de Praga**, que Jakobson funda en 1926 tras salir de una Rusia en guerra civil. Ambos grupos comparten con Saussure la misma apuesta: aislar la forma del sistema y describirla en sus propios términos, sin apelar al referente ni a la biografía del autor.",
    },
    {
      type: "info",
      continues: true,
      title: "De la lingüística a la semiología",
      body: "Jakobson deja Praga cuando los nazis ocupan Checoslovaquia en 1938 y llega, tras un rodeo por Escandinavia, a Nueva York. Ahí lo recibe **Alexandre Koyré**, historiador de la ciencia formado con Husserl y uno de los responsables de introducir la fenomenología en Francia. Koyré le presenta a **Claude Lévi-Strauss**, antropólogo francés también exiliado, que acababa de volver de un trabajo de campo en Brasil. Del cruce entre el método lingüístico de Jakobson y el material etnográfico de Lévi-Strauss nace la antropología estructural.",
    },
    {
      type: "quiz",
      question: "¿Qué produce la semiología, según la clase, respecto del sentido?",
      options: [
        "El lenguaje no expresa un sentido previo: lo produce",
        "El lenguaje se limita a reflejar un pensamiento ya formado",
        "Los signos dependen siempre de su parecido con la cosa",
        "El sentido existe siempre por fuera de cualquier sistema",
      ],
      answer: 0,
      explain: "La semiología extiende la lógica saussureana a cualquier sistema cultural: el significado es relacional y el lenguaje no expresa un sentido previo sino que lo estructura y lo produce.",
    },
    {
      type: "info",
      title: "Lévi-Strauss: la antropología estructural",
      body: "El proyecto de Lévi-Strauss es **descubrir las leyes profundas que gobiernan los sistemas culturales**: el parentesco, el mito, el ritual, la clasificación del mundo natural. Parte de una noción amplia de cultura —herramientas, instituciones, costumbres, arte, saber, lenguaje— y de la premisa, heredada de Freud, de que buena parte de esa cultura opera a nivel **inconsciente**: nadie decide conscientemente las reglas de parentesco de su sociedad.",
    },
    {
      type: "info",
      continues: true,
      title: "Lévi-Strauss: la antropología estructural",
      body: "La pregunta que organiza el programa es si otros sistemas culturales son \"sistemáticos\" del mismo modo que el lenguaje. Lévi-Strauss responde que sí, con una condición: hay que tratarlos, igual que a la lengua, como **simbolismo puro**, cuyas unidades no valen por sí mismas sino por su lugar dentro de una red de diferencias.",
    },
    {
      type: "quiz",
      question: "¿Qué premisa, heredada de Freud, sostiene el proyecto de Lévi-Strauss?",
      options: [
        "Que buena parte de la cultura opera a nivel inconsciente",
        "Que toda cultura reprime un instinto sexual originario",
        "Que la conciencia individual dirige las reglas de parentesco",
        "Que el inconsciente no tiene ninguna estructura propia",
      ],
      answer: 0,
      explain: "Nadie decide conscientemente las reglas de parentesco de su sociedad. Lévi-Strauss parte de que la cultura, como el lenguaje, opera en buena medida a nivel inconsciente: por eso se la puede tratar como un sistema de diferencias.",
    },
    {
      type: "info",
      title: "El parentesco como lenguaje",
      body: "El caso que desarrolla con más detalle es el **sistema de parentesco**: la manera en que una cultura organiza y da significado a las relaciones familiares. Su tesis es que el parentesco funciona como un lenguaje, cuyas unidades —tío, sobrino, cónyuge, cuñado— tienen valor solo por la coordinación de sus diferencias recíprocas, no por el lazo biológico de sangre que las acompaña.",
    },
    {
      type: "info",
      continues: true,
      title: "El parentesco como lenguaje",
      body: "Un caso que trabaja en detalle es el del **avunculado**, la relación entre el tío materno y el sobrino: su significado en una cultura dada no se explica por el parentesco de sangre en sí, sino por su posición dentro de todo el sistema de relaciones —incluidas las de afinidad, es decir las que se establecen por matrimonio y no por sangre—. Lévi-Strauss observa además que en las sociedades estudiadas son los hombres quienes intercambian a las mujeres, y no a la inversa: una asimetría estructural con consecuencias que la antropología feminista discutirá después.",
    },
    {
      type: "info",
      continues: true,
      title: "El parentesco como lenguaje",
      body: "Detrás de todo sistema de parentesco está el **tabú del incesto**, que Lévi-Strauss —siguiendo a Freud— lee como el límite que marca el pasaje de la naturaleza a la cultura: la primera regla que exige el intercambio con otro grupo en lugar de la reproducción dentro del propio. Es universal en su función (toda cultura lo tiene) aunque no en su contenido (qué cuenta como incesto varía).",
    },
    {
      type: "quiz",
      question: "¿Por qué el avunculado (tío materno y sobrino) no se explica por el lazo de sangre?",
      options: [
        "Su significado depende de su posición en todo el sistema",
        "Porque en realidad no existe ningún lazo biológico entre ambos",
        "Porque el parentesco varía según el clima de cada región",
        "Porque cada individuo define libremente su propio parentesco",
      ],
      answer: 0,
      explain: "El parentesco funciona como un lenguaje: sus unidades valen por la coordinación de sus diferencias recíprocas —incluidas las de afinidad, por matrimonio— y no por el vínculo de sangre que las acompaña.",
    },
    {
      type: "info",
      title: "El mito",
      body: "El análisis del **mito** es la otra gran contribución, y va a ser decisivo para Girard. Lévi-Strauss sostiene que los mitos de culturas distintas, incluidas las orales y sin escritura, son **variaciones de un número limitado de temas**, organizadas por estructuras constantes: como el lenguaje, el mito tiene unidades mínimas que se descomponen y se recombinan según una gramática propia.",
    },
    {
      type: "info",
      continues: true,
      title: "El mito",
      body: "Los mitos funcionan como **dispositivos para clasificar y ordenar la realidad**, y como **resoluciones imaginarias de contradicciones sociales reales** que de otro modo no tendrían salida: la vida y la muerte, la naturaleza y la cultura, lo crudo y lo cocido. La oposición binaria es la herramienta lógica básica con la que el mito procesa esas tensiones.",
    },
    {
      type: "info",
      continues: true,
      title: "El mito",
      body: "La consecuencia más radical de este análisis es que la mente que \"piensa\" el mito **no es la de un sujeto individual**: en cierto sentido, son los mitos los que se piensan a sí mismos a través de las personas que los cuentan. Es un descentramiento del sujeto tan fuerte como el de Saussure: el hablante no es el origen del sentido, sino el lugar donde una estructura que lo precede se actualiza.",
    },
    {
      type: "quiz",
      question: "¿Quién «piensa» el mito, según la conclusión más radical de Lévi-Strauss?",
      options: [
        "Los mitos se piensan a sí mismos a través de quien los cuenta",
        "Siempre un narrador individual, autor original del relato",
        "Un consejo de ancianos que decide su contenido en cada tribu",
        "Nadie: los mitos carecen de todo tipo de estructura interna",
      ],
      answer: 0,
      explain: "Es un descentramiento tan radical como el de Saussure: el narrador no es el origen del sentido, sino el lugar donde se actualiza una estructura mítica que lo precede y lo excede.",
    },
    {
      type: "info",
      title: "El bricolage",
      body: "Para explicar cómo opera el pensamiento mítico, Lévi-Strauss recurre en El pensamiento salvaje (1962) a la figura del **bricoleur**, el que arregla y construye con lo que tiene a mano. A diferencia del ingeniero, que diseña una herramienta nueva para cada problema a partir de conceptos abstractos, el bricoleur trabaja con un repertorio cerrado de piezas ya usadas —restos de construcciones y destrucciones anteriores— y las reordena para un uso distinto del que tuvieron.",
    },
    {
      type: "info",
      continues: true,
      title: "El bricolage",
      body: "El pensamiento mítico es **bricolage**: no inventa símbolos desde cero, reutiliza los que ya circulan en la cultura —animales, colores, direcciones cardinales, partes del cuerpo— y los recombina para producir sentidos nuevos. No es un pensamiento más pobre que el científico, sino un modo distinto de proceder: mientras la ciencia moderna crea conceptos, el mito reordena signos.",
    },
    {
      type: "short",
      question: "¿Cómo llama Lévi-Strauss a la figura que arregla con un repertorio cerrado de piezas ya usadas, en vez de diseñar herramientas nuevas?",
      answers: ["bricoleur"],
      explain: "El bricoleur: a diferencia del ingeniero, que crea conceptos nuevos para cada problema, trabaja con restos de construcciones anteriores y los reordena. El pensamiento mítico procede así: bricolage, no invención desde cero.",
    },
    {
      type: "info",
      title: "El pensamiento salvaje",
      body: "De ahí el título del libro: lo que Lévi-Strauss llama **pensée sauvage**, pensamiento salvaje, no es un estadio primitivo o inferior en una escala evolutiva hacia el pensamiento científico, sino una lógica alternativa, igual de rigurosa, que clasifica el mundo por las cualidades sensibles y concretas de las cosas —lo crudo y lo cocido, lo húmedo y lo seco— en vez de por magnitudes abstractas.",
    },
    {
      type: "info",
      continues: true,
      title: "El pensamiento salvaje",
      body: "Los sistemas de clasificación totémica, en los que un clan se asocia con un animal o una planta, no expresan una confusión entre personas y naturaleza, como suponía buena parte de la antropología evolucionista anterior: son taxonomías tan sistemáticas como la biología moderna, solo que organizadas con otro criterio. Con esto Lévi-Strauss discute directamente la jerarquía entre mentalidad \"primitiva\" y mentalidad \"civilizada\".",
    },
    {
      type: "quiz",
      question: "¿Qué es, para Lévi-Strauss, el «pensamiento salvaje» (pensée sauvage)?",
      options: [
        "Una lógica alternativa, tan rigurosa como la científica",
        "Un estadio primitivo e inferior camino al pensamiento científico",
        "Una confusión pura entre las personas y la naturaleza",
        "Un pensamiento sin ninguna clasificación ni sistema propio",
      ],
      answer: 0,
      explain: "No es un escalón inferior hacia la ciencia: es una lógica igual de rigurosa, que clasifica el mundo por cualidades sensibles y concretas —lo crudo y lo cocido— en vez de por magnitudes abstractas.",
    },
    {
      type: "info",
      title: "Críticas al estructuralismo",
      body: "Las objeciones se acumulan rápido. Si todo es un sistema de signos relacionándose con otros signos, la realidad pierde su espesor propio: el estructuralismo tiene sabor a **relativismo**, porque los valores solo tienen sentido en relación con otros valores dentro de un sistema dado, nunca en relación con algo exterior al sistema.",
    },
    {
      type: "info",
      continues: true,
      title: "Críticas al estructuralismo",
      body: "También se le reprocha la **disminución del sujeto y de la experiencia vivida**: al poner entre paréntesis tanto la historia como la vivencia individual, el estructuralismo esquiva el problema del puente entre sujeto y objeto en lugar de resolverlo. Es, además, **ahistórico** por diseño —trabaja en el plano sincrónico— y tiende a evitar los juicios de valor: describe sistemas, no los evalúa.",
    },
    {
      type: "info",
      continues: true,
      title: "Críticas al estructuralismo",
      body: "Y sin embargo el estructuralismo comparte algo con los movimientos que critica. Con el modernismo comparte la idea de la **arbitrariedad** del signo; con Hegel, la idea de que solo el **todo** da sentido a las partes. Lo que cambia es el signo de esas ideas: donde Hegel esperaba que el todo se revelara al final de la historia, el estructuralismo lo encuentra ya dado, funcionando, fuera del tiempo.",
    },
    {
      type: "classify",
      question: "¿Cada objeción es la crítica del relativismo o la del sujeto disminuido?",
      groups: ["Relativismo", "Sujeto disminuido"],
      items: [
        { text: "Los valores sólo tienen sentido dentro de un sistema dado", group: 0 },
        { text: "Se esquiva el puente entre sujeto y objeto, no se resuelve", group: 1 },
        { text: "Nada tiene sentido en relación con algo exterior al sistema", group: 0 },
        { text: "Se pone entre paréntesis la vivencia individual", group: 1 },
        { text: "El estructuralismo tiende a evitar los juicios de valor", group: 0 },
        { text: "Es ahistórico por diseño: trabaja en el plano sincrónico", group: 1 },
      ],
      explain: "Una familia de críticas apunta al relativismo: sin exterior al sistema, no hay cómo evaluar valores. La otra apunta a la disminución del sujeto y la historia vivida: el estructuralismo esquiva el problema sujeto-objeto en lugar de resolverlo.",
    },
    {
      type: "info",
      title: "Herencia: el giro lingüístico y la pregunta por el sujeto",
      body: "El estructuralismo deja planteado el llamado **giro lingüístico**: la apuesta por entender la historia, la literatura y la antropología en términos de lenguaje, como si toda la vida humana fuera, en el fondo, un constructo lingüístico. Es una apuesta poderosa y también estrecha, porque deja abierta una pregunta que el propio estructuralismo no puede responder: si el sujeto ya no es la fuente del sentido, ¿adónde fue a parar?",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: el giro lingüístico y la pregunta por el sujeto",
      body: "René Girard va a retomar el análisis del mito y de la diferenciación cultural de Lévi-Strauss, pero para preguntarse por la violencia que esas estructuras esconden. Michel Foucault y Jacques Derrida van a llevar el descentramiento del sujeto todavía más lejos, cuestionando no solo la centralidad del sujeto sino la estabilidad misma del sistema de signos que el estructuralismo daba por dado.",
    },
    {
      type: "match",
      question: "Uní cada concepto del estructuralismo con lo que nombra",
      pairs: [
        { left: "Signo lingüístico", right: "Significante y significado, unidos de forma arbitraria" },
        { left: "Valor diferencial", right: "Un signo significa por contraste con los demás del sistema" },
        { left: "Parentesco", right: "Un lenguaje cuyas unidades valen por sus diferencias" },
        { left: "Mito", right: "Variaciones de un número limitado de temas universales" },
        { left: "Bricolage", right: "Reordenar piezas ya usadas en vez de crear desde cero" },
      ],
      explain: "Todo el edificio estructuralista repite el mismo movimiento de Saussure: el sentido no está en las unidades mismas sino en la red de diferencias que las relaciona, ya sea en la lengua, el parentesco, el mito o el pensamiento mítico.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: el giro lingüístico y la pregunta por el sujeto",
      body: "El antropólogo **Clifford Geertz** resumió después la ambición última de Lévi-Strauss con una fórmula que sirve de cierre: La búsqueda de Lévi-Strauss no es, después de todo, la de los hombres —que no le importan demasiado—, sino la del Hombre como tal, por el que está fascinado.",
    },
  ],
};
