export default {
  num: 7,
  transcript: 8,
  title: "El leninismo: acelerar la historia",
  source: "https://www.youtube.com/watch?v=2F3PzB2iVa4",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "Vladímir Ilich Uliánov, conocido como **Lenin** (1870-1924), nace en Simbirsk, a orillas del Volga, en una familia acomodada de funcionarios. En 1887 su hermano mayor, Aleksandr, es ejecutado por participar en un complot para asesinar al zar Alejandro III: el episodio marca el ingreso de Lenin, entonces adolescente, en la actividad revolucionaria.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Estudia derecho, es expulsado de la Universidad de Kazán por participar en protestas estudiantiles y termina rindiendo los exámenes de manera libre. Detenido y desterrado a Siberia entre 1897 y 1900, pasa después buena parte de dos décadas en el exilio europeo —Múnich, Londres, Ginebra, Zúrich—, donde funda el periódico Iskra (1900) y escribe sus textos principales: **¿Qué hacer?** (1902), El imperialismo, fase superior del capitalismo (1916) y El Estado y la revolución (1917).",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Vuelve a Rusia en abril de 1917 y encabeza la Revolución de Octubre de ese mismo año. Preside el primer gobierno soviético hasta que una serie de derrames cerebrales, a partir de 1922, lo aparta progresivamente del poder. Muere en enero de 1924.",
    },
    {
      type: "info",
      title: "El problema que hereda: la Segunda Internacional",
      body: "Marx deja planteada una ley de la historia, pero no dice cuánto dura cada etapa ni qué hacer mientras se la espera. Ese vacío lo hereda el movimiento obrero organizado en la **Segunda Internacional**, fundada en París en 1889 tras la disolución de la Primera Internacional, que el propio Marx había presidido. Reúne bajo la ortodoxia marxista a los partidos socialistas y socialdemócratas de Europa.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la Segunda Internacional",
      body: "El teórico principal de esa ortodoxia es **Karl Kautsky** (1854-1938), apodado el \"papa del marxismo\": sostiene que el capitalismo colapsará por sus propias contradicciones internas, cada vez más agudas, y que el papel del partido es organizar a la clase obrera y esperar ese colapso, participando mientras tanto en elecciones y sindicatos. Es una ortodoxia paciente: la revolución llegará, pero no hay que apurarla.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la Segunda Internacional",
      body: "En 1899, **Eduard Bernstein** (1850-1932) rompe abiertamente con esa ortodoxia en Los presupuestos del socialismo: el capitalismo no se está desmoronando, las condiciones de los trabajadores mejoran, y el camino hacia el socialismo pasa por la reforma gradual, el sufragio y el parlamento, no por la revolución catastrófica. Es el **revisionismo**: revisar a Marx a la luz de la evidencia.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la Segunda Internacional",
      body: "Kautsky combate el revisionismo de Bernstein en nombre de la ortodoxia, pero en la práctica el partido socialdemócrata alemán se vuelve cada vez más parlamentario y gradualista. Lenin observa este debate desde el Imperio ruso y saca una conclusión distinta a la de ambos bandos: ni hay que revisar la meta, como Bernstein, ni esperar pasivamente, como Kautsky. Hay que organizar una vanguardia que empuje la historia.",
    },
    {
      type: "classify",
      question: "¿Cada posición es de Kautsky o de Bernstein?",
      groups: ["Kautsky", "Bernstein"],
      items: [
        { text: "El capitalismo va a colapsar por sus propias contradicciones", group: 0 },
        { text: "Mientras tanto, hay que organizar y esperar ese colapso", group: 0 },
        { text: "Las condiciones de los trabajadores en realidad mejoran", group: 1 },
        { text: "El camino al socialismo pasa por el parlamento, no la revolución", group: 1 },
        { text: "Hay que revisar el marxismo a la luz de la evidencia", group: 1 },
      ],
      explain: "Kautsky representa la ortodoxia paciente: el capitalismo caerá solo y el partido debe organizar y esperar. Bernstein rompe con eso en el revisionismo: la evidencia muestra mejoras, no colapso, y propone la vía reformista.",
    },
    {
      type: "info",
      title: "¿Se puede apurar la historia?",
      body: "El problema del tiempo, ya presente en Bergson, en Nietzsche, en Marx y en Hegel, vuelve aquí bajo otra forma: ¿el tiempo da vueltas sin rumbo o tiene una dirección? ¿está puntuado? ¿tiene duración? ¿es continuo o discreto? ¿se mueve necesariamente hacia adelante, en un sentido no sólo matemático sino normativo?",
    },
    {
      type: "info",
      continues: true,
      title: "¿Se puede apurar la historia?",
      body: "Aquí se parte de un marco de tiempo con sentido intenso de **direccionalidad**: el tiempo marxista, heredado de Hegel, se mueve hacia cierto telos. A esa direccionalidad se agrega ahora otro elemento, la **velocidad**. La pregunta que organiza esta clase es si se puede apurar la historia: existe una Historia con mayúscula, con su propia dinámica y sus propias leyes, cuyo rumbo se conoce; la duda es si se la puede empujar. Para Marx no hay retroceso posible —sólo se avanza—, pero no precisa cuánto dura cada etapa.",
    },
    {
      type: "info",
      title: "Aclaración de términos",
      body: "Conviene fijar el vocabulario, porque estos términos —comunismo, socialismo, socialdemocracia, leninismo, marxismo-leninismo, bolchevismo, menchevismo— cambian de sentido según el autor y el momento histórico. El **comunismo** es, para Marx, el fin de la historia: el momento en que los trabajadores, vueltos conscientes de clase, derrocan a la burguesía, abolen la propiedad privada y disuelven las fronteras nacionales, de modo que cada uno trabaja según su capacidad y recibe según su necesidad. Es el telos en el que todo antagonismo de clase queda **aufgehoben** —superado, en términos hegelianos—. El marxismo es la teoría que explica ese proceso.",
    },
    {
      type: "info",
      continues: true,
      title: "Aclaración de términos",
      body: "El **socialismo** abarca un espectro más amplio, desde cierta redistribución hasta algo casi sinónimo del comunismo; aquí se lo entiende como una forma menos consumada del comunismo, en la que todavía no toda la propiedad es colectiva. La **socialdemocracia** actual —Suecia, por ejemplo— es economía mixta con fuerte intervención estatal pero propiedad privada; no debe confundirse con la de Lenin y Luxemburg hacia 1900, que usan el término como sinónimo de comunismo: así se llamaban entonces los propios partidos comunistas.",
    },
    {
      type: "info",
      continues: true,
      title: "Aclaración de términos",
      body: "El **leninismo**, a veces marxismo-leninismo, sí introduce una distinción clara, porque Lenin modifica el marxismo de un modo específico que se desarrolla más abajo. **Bolchevismo** y **menchevismo** nombran los dos bandos en que se divide, en 1903, el partido comunista del Imperio zarista.",
    },
    {
      type: "match",
      question: "Uní cada término con su sentido en esta clase",
      pairs: [
        { left: "Comunismo", right: "El fin de la historia, sin propiedad privada" },
        { left: "Socialismo", right: "Una forma menos consumada del comunismo" },
        { left: "Socialdemocracia hacia 1900", right: "Sinónimo de comunismo, no de reforma" },
        { left: "Leninismo", right: "La modificación de Marx con la vanguardia" },
        { left: "Bolchevique", right: "La mayoría del partido, en ruso" },
      ],
      explain: "Estos términos cambian de sentido según el autor y la época: la socialdemocracia de 1900 no es la de Suecia hoy, y el leninismo es justamente la distinción que introduce algo nuevo respecto del marxismo clásico.",
    },
    {
      type: "info",
      title: "A la sombra de la Revolución Bolchevique",
      body: "Todo el siglo XIX transcurre a la sombra de la Revolución Francesa; todo el siglo XX transcurre a la sombra de la **Revolución Bolchevique**, y en muchos sentidos todavía se lidia con lo que significa vivir bajo esa sombra. Buena parte de la historia del pensamiento europeo del siglo XX es una respuesta a ese experimento radical ocurrido en lo que fue el Imperio ruso y se convierte en la Unión Soviética: discutiblemente, el acontecimiento seminal del siglo, lo cual no implica que fuera bueno, sino que su impacto fue dramático.",
    },
    {
      type: "info",
      continues: true,
      title: "A la sombra de la Revolución Bolchevique",
      body: "La pregunta que organiza esta clase es cómo se pasa del marxismo del Manifiesto Comunista a la Revolución Bolchevique y a la creación de la Unión Soviética.",
    },
    {
      type: "info",
      title: "Las influencias sobre Marx",
      body: "Sobre Marx confluyen dos series de influencias: las ideas de la Ilustración y de la Revolución Francesa —la Declaración de los Derechos del Hombre, los hombres nacen libres e iguales, la soberanía reside en el pueblo— y la **industrialización** del siglo XIX, con sus cambios materiales concretos: campesinos que migran del campo a la ciudad, urbanización, campesinos que se vuelven obreros fabriles, el paso de una economía de trueque a una economía monetaria que permite acumular capital.",
    },
    {
      type: "info",
      continues: true,
      title: "Las influencias sobre Marx",
      body: "Marx y Engels observan esto desde la parte de Europa —Alemania, Francia, Inglaterra— donde la Ilustración tuvo su forma más fuerte y la industrialización avanzaba más rápido; esa perspectiva no es representativa del resto de Europa, y menos del resto del mundo. Desde allí, las etapas de la historia parecen ir a toda velocidad.",
    },
    {
      type: "info",
      title: "Lenin y el Imperio zarista",
      body: "Lenin lee esta filosofía con seriedad, pero viene de otra parte de Europa —en rigor, de Eurasia, si se considera toda la extensión del Imperio zarista—. El Imperio ruso de fines del siglo XIX es un lugar donde la modernización apenas ocurre: fuerte tradición autocrática, jerarquía enquistada, un zar, la nobleza, el campesinado. El imperio es, en esencia, propiedad personal del zar: no hay monarquía constitucional, hay **feudalismo**. El capitalismo no ha llegado; la industrialización, tampoco.",
    },
    {
      type: "info",
      continues: true,
      title: "Lenin y el Imperio zarista",
      body: "Los siervos se emancipan recién en 1861 —tarde en términos europeos, aunque antes de que se aboliera la esclavitud en Estados Unidos—, y las condiciones de la emancipación hacen que su situación práctica cambie poco. Entre 1867 y 1897 la población de San Petersburgo se duplica: la gente migra a las ciudades sin infraestructura que lo sostenga —hacinamiento, epidemias de tifus, cólera, sífilis—, y las condiciones de trabajo en las fábricas son atroces. A los pocos obreros existentes se los explota horriblemente, pero la enorme mayoría del país sigue siendo campesinado.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo describe la Europa de Marx o el Imperio zarista de Lenin?",
      groups: ["Europa de Marx", "Imperio zarista"],
      items: [
        { text: "La industrialización ya avanza a toda velocidad", group: 0 },
        { text: "Las ideas de la Ilustración calaron con fuerza", group: 0 },
        { text: "El imperio es, en esencia, propiedad personal del zar", group: 1 },
        { text: "Los siervos recién se emancipan en 1861", group: 1 },
        { text: "La enorme mayoría del país sigue siendo campesina", group: 1 },
      ],
      explain: "Marx y Engels piensan la historia desde Alemania, Francia e Inglaterra, donde la industrialización corre rápido. Lenin actúa en un imperio donde el capitalismo casi no llegó y domina todavía la estructura feudal.",
    },
    {
      type: "info",
      title: "Los kruzhki y la lentitud de la conciencia de clase",
      body: "En la segunda mitad del siglo XIX se desarrolla una **intelligentsia revolucionaria**: gente como Lenin, que lee a Hegel, a Marx, a Voltaire, y tiene ideas sobre hacia dónde va la historia. Organizan los **kruzhki** (de kruzhok, \"círculo\" en ruso): círculos de lectura o grupos de estudio para educar a los trabajadores.",
    },
    {
      type: "info",
      continues: true,
      title: "Los kruzhki y la lentitud de la conciencia de clase",
      body: "Pero se trata de personas que viven en condiciones horribles, explotadas, que trabajan catorce o quince horas diarias y no siempre son alfabetas. Leer a Hegel resulta arduo incluso en condiciones favorables; hacerlo un obrero fabril analfabeto después de esa jornada es, en la práctica, casi imposible. Por eso la conquista de la conciencia de clase avanza con extrema lentitud.",
    },
    {
      type: "quiz",
      question: "¿Por qué los kruzhki no logran acelerar la conciencia de clase?",
      options: [
        "Llegan agotados de la fábrica y muchos no saben leer",
        "Los intelectuales no quieren compartir lo que leen",
        "El zar prohíbe cualquier tipo de reunión obrera",
        "Los obreros desconfían de las ideas extranjeras",
      ],
      answer: 0,
      explain: "Los kruzhki reúnen a obreros que trabajan catorce o quince horas diarias y no siempre son alfabetas: leer a Hegel es arduo incluso en buenas condiciones, así que la conciencia de clase avanza muy lento por esa vía.",
    },
    {
      type: "info",
      title: "Lenin, impaciente",
      body: "La versión breve: Lenin se frustra por la lentitud del proceso. El Manifiesto Comunista es, a la vez, un texto normativo —Marx cree que la revolución es deseable, los trabajadores del mundo deben unirse— y una predicción, una filosofía de la historia: eso es lo que va a suceder. Por eso Marx desprecia a los socialistas utópicos, como Fourier y Saint-Simon, y su \"¿no sería lindo si…?\": para él no se trata de un deseo sino de la **ciencia de las leyes de la historia**, que conduce inexorablemente a ese desenlace, sin necesidad de voluntarismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Lenin, impaciente",
      body: "La conciencia de clase, según esta fórmula marxista, deriva del ser social: la posición objetiva en la infraestructura socioeconómica determina la conciencia. Pero llegar a la conciencia de clase no es sólo constatar que la vida propia es miserable, sino comprender el todo, entender que nada se arregla de manera fragmentaria —es comprender a Hegel, \"lo verdadero es el todo\", ver cómo encajan las piezas—.",
    },
    {
      type: "info",
      continues: true,
      title: "Lenin, impaciente",
      body: "El problema es que Lenin observa que los trabajadores no llegan ahí rápido. Entienden perfectamente que sus condiciones son miserables y quieren mejor paga, jornadas más cortas, condiciones más higiénicas; pero no llegan a comprender la dialéctica histórica, cómo encajan las piezas del conjunto. Esa lentitud frustra a Lenin, y esa impaciencia es la clave para entender lo que sigue.",
    },
    {
      type: "info",
      title: "¿Qué hacer? (1902)",
      body: "De esa frustración concluye que hay que modificar la doctrina, porque esperar tomará demasiado tiempo. En 1902 escribe **Shto Delat** —¿Qué hacer?—, discutiblemente el texto más importante del siglo XX, no por ser el más brillante sino por su capacidad de torcer la historia. Expone, en esencia, un método para apurar la Historia con mayúscula: no cambia su dirección, sólo la empuja. El leninismo consiste en empujarla.",
    },
    {
      type: "quiz",
      question: "¿En qué consiste, exactamente, la modificación que Lenin le hace al marxismo?",
      options: [
        "Cambia la dirección de la historia, ya no va al comunismo",
        "Niega que exista una ciencia de las leyes de la historia",
        "No cambia el rumbo, sólo inventa un método para acelerarlo",
        "Sostiene que la revolución debe ser pacífica y gradual",
      ],
      answer: 2,
      explain: "Lenin no discute el telos marxista ni su dirección: los da por ciertos. Lo que aporta en ¿Qué hacer? es un método para apurar la Historia, porque a su ritmo natural tardaría demasiado.",
    },
    {
      type: "info",
      title: "\"Pensar en chico\": economismo, sindicalismo, espontaneidad",
      body: "Lenin observa que, cuando los obreros hacen una huelga —como la gran huelga textil de Petersburgo a fines del siglo XIX—, piden algo chico: jornada más corta, más vacaciones, mejor paga. No ven el cuadro completo ni piensan en derrocar el sistema entero. Lenin llama a esto **sindicalismo**, **economismo**, **espontaneidad**: pedidos inmediatos y materiales, no reflexionados críticamente a la luz de la totalidad histórica.",
    },
    {
      type: "info",
      continues: true,
      title: "\"Pensar en chico\": economismo, sindicalismo, espontaneidad",
      body: "El sindicalismo entiende que hay que actuar de manera colectiva para influir sobre los patrones, pero piensa como trabajador de un sindicato, no como revolucionario. El economismo es otro nombre para esa misma limitación: pedir mejoras que son menos que el derrocamiento revolucionario del sistema entero.",
    },
    {
      type: "quiz",
      question: "Para Lenin, ¿qué les falta a los reclamos que llama economismo o espontaneidad?",
      options: [
        "Captar la totalidad de cómo encajan las piezas del sistema",
        "Contar con el apoyo de los intelectuales marxistas",
        "Tener una organización mínima entre los obreros",
        "Reconocer que las condiciones de trabajo son malas",
      ],
      answer: 0,
      explain: "Lenin admite que los obreros entienden que sus condiciones son miserables y se organizan en sindicatos, pero eso no equivale a comprender la dialéctica histórica ni cómo encaja el conjunto.",
    },
    {
      type: "info",
      title: "El problema calvinista y el papel de los intelectuales",
      body: "El marxismo clásico plantea aquí el **problema del calvinismo**: si todo va a suceder de todos modos según las leyes de hierro de la historia, ¿para qué actuar? Lenin ofrece una respuesta y le asigna un papel a los intelectuales.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema calvinista y el papel de los intelectuales",
      body: "Pero los intelectuales marxistas enfrentan un dilema: quienes estudian de verdad a Marx y a Hegel son una élite que aprendió francés, alemán, quizá inglés, y tiene tiempo libre para atravesar la Fenomenología del espíritu. Esos que \"captan\" la teoría son, para Lenin, de **origen burgués**: no pertenecen a la clase llamada a liderar la revolución, ya están contaminados por su propia posición de clase, aunque tengan por eso mismo los recursos para estudiar a Hegel.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema calvinista y el papel de los intelectuales",
      body: "De ahí un impulso casi autodespreciativo en esa capa de intelectuales: al saberse burgueses de origen, y por lo tanto ajenos a la clase que la teoría designa como sujeto legítimo de la revolución, muchos sienten que su papel debería ser dar un paso al costado y dejar que el proletariado los lidere. Pero el proletariado, según el propio diagnóstico leninista, todavía no capta ese papel, porque sus condiciones históricas concretas no le permiten llegar solo a la comprensión de la totalidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema calvinista y el papel de los intelectuales",
      body: "Ese callejón sin salida —intelectuales que deberían callarse pero son los únicos que entienden, obreros que deberían liderar pero no llegan a la conciencia necesaria— es exactamente lo que la solución de Lenin va a resolver por la fuerza.",
    },
    {
      type: "quiz",
      question: "¿Cuál es la paradoja que Lenin enfrenta respecto de los intelectuales marxistas?",
      options: [
        "Son los únicos que entienden la teoría pero no son proletarios",
        "No existen intelectuales dispuestos a estudiar a Marx",
        "El proletariado los rechaza por su origen burgués",
        "La censura zarista les impide publicar sus ideas",
      ],
      answer: 0,
      explain: "Quienes de verdad captan a Marx y a Hegel son, por su formación, de origen burgués y no la clase llamada a liderar la revolución; el proletariado, a su vez, todavía no llega solo a esa comprensión total.",
    },
    {
      type: "info",
      title: "La vanguardia y el Partido",
      body: "La solución de Lenin es una **vanguardia** de **revolucionarios profesionales**, gente que hace de la agitación revolucionaria su ocupación. Toman la conciencia de clase, la comprensión correcta de la historia —es como si pudiera reificarse la conciencia, sostenerla como si fuera una cosa material— y se la llevan a los trabajadores, dándole así un arranque al ritmo, de otro modo lento, de la historia.",
    },
    {
      type: "info",
      continues: true,
      title: "La vanguardia y el Partido",
      body: "El leninismo, entonces, es una élite de revolucionarios profesionales, de origen en la intelligentsia burguesa, que consagra su vida a llevarles la conciencia de clase a los trabajadores y a acelerar el proceso revolucionario. Esa organización es el **Partido**, con mayúscula, en el mismo gesto con que se escribe la Historia con mayúscula: no un partido político cualquiera, sino una estructura a la que se le consagra la vida entera.",
    },
    {
      type: "info",
      continues: true,
      title: "La vanguardia y el Partido",
      body: "Ser comunista bajo Lenin no era una identidad festiva ni un gesto contracultural: implicaba jornadas de trabajo casi ininterrumpidas en condiciones de clandestinidad, con el riesgo constante de la cárcel o el destierro a Siberia. Ser miembro del Partido suponía estar dispuesto a morir por él, subordinarle la vida entera, postrarse ante él casi como ante una divinidad, y entregarse por completo al secreto y la conspiración, porque la alternativa inmediata a esa disciplina era, sin atenuantes, la prisión o el exilio interior.",
    },
    {
      type: "info",
      continues: true,
      title: "La vanguardia y el Partido",
      body: "Esa entrega no era retórica: la clandestinidad exigía identidades falsas, imprentas escondidas, reuniones que podían costar años de destierro si la policía secreta zarista las descubría. El Partido, en ese sentido, funciona como sustituto de vínculos que en otra vida ocuparían la familia o la religión: exige la misma lealtad total, y a cambio ofrece la certeza de estar del lado correcto de una ley histórica que, se cree, no puede finalmente perder.",
    },
    {
      type: "quiz",
      question: "Según la clase, ¿qué rol cumple el Partido, con mayúscula, para sus militantes?",
      options: [
        "Sustituye vínculos que otra vida daría a la familia o la religión",
        "Funciona apenas como un espacio de discusión política",
        "Es apenas una organización política más entre otras",
        "Exige lealtad sólo durante las campañas electorales",
      ],
      answer: 0,
      explain: "La entrega no es retórica: la clandestinidad exige identidades falsas e imprentas escondidas, y el Partido ofrece a cambio la certeza de estar del lado correcto de una ley histórica que no puede perder.",
    },
    {
      type: "info",
      title: "Citas de Lenin",
      body: "Hemos dicho que no podía haber conciencia socialdemócrata [es decir, verdadera conciencia comunista marxista] entre los obreros; había que llevársela **desde afuera**. La historia de todos los países muestra que la clase obrera, exclusivamente por sus propias fuerzas, solo es capaz de desarrollar conciencia sindical: la convicción de que hay que unirse en sindicatos, luchar contra los patrones, presionar al gobierno para que dicte las leyes laborales necesarias, etc.",
    },
    {
      type: "info",
      continues: true,
      title: "Citas de Lenin",
      body: "Que los obreros tengan sus sindicatos está bien —mejor que nada—, pero también hace falta una organización de revolucionarios profesionales:",
    },
    {
      type: "info",
      continues: true,
      title: "Citas de Lenin",
      body: "Esta organización de revolucionarios debe estar compuesta, ante todo, por personas que hagan de la actividad revolucionaria su profesión.",
    },
    {
      type: "quiz",
      question: "Para Lenin, ¿por qué la conciencia de clase debe llegarle al proletariado desde afuera?",
      options: [
        "Porque los obreros son incapaces de toda organización colectiva",
        "Porque sola no pasa de la simple conciencia sindical",
        "Porque la verdadera revolución debe venir de la burguesía",
        "Porque Marx había prohibido que los obreros se organizaran",
      ],
      answer: 1,
      explain: "Lenin acepta que los sindicatos son mejores que nada, pero cree que la clase obrera sola no pasa de la conciencia sindical. Captar la totalidad requiere la vanguardia de revolucionarios profesionales.",
    },
    {
      type: "info",
      title: "La escisión de 1903: bolcheviques y mencheviques",
      body: "En 1903 tiene lugar el **Segundo Congreso del Partido Obrero Socialdemócrata Ruso**, y el partido se parte. La escisión es crucial: se divide en **bolcheviques** y **mencheviques** (del ruso para \"mayoría\" y \"minoría\"). La mayoría acompaña la modificación de Lenin y coincide en la necesidad de apurar la historia; la minoría, los mencheviques, adopta la línea marxista más conservadora: hay que esperar a que la historia se despliegue, hay que confiar en ella.",
    },
    {
      type: "short",
      question: "¿Cómo se llama, en ruso, la facción minoritaria del partido tras la escisión de 1903?",
      answers: ["menchevique", "mencheviques"],
      explain: "En el Segundo Congreso de 1903 el partido se divide: bolchevique viene de mayoría, menchevique de minoría. Los mencheviques adoptan la línea más conservadora: esperar a que la historia se despliegue.",
    },
    {
      type: "info",
      title: "Rosa Luxemburg",
      body: "Los interlocutores más importantes de Lenin en esta cuestión son, discutiblemente, **Rosa Luxemburg** y **Georg Lukács**. Luxemburg, de una familia judía polaca de Zamość, entonces en el Imperio zarista, está en actividad revolucionaria desde la adolescencia; a los dieciocho huye a Zúrich para escapar de la cárcel, funda el Partido Socialdemócrata de Polonia y Lituania y luego se instala en Berlín, donde se convierte en una de las líderes del movimiento comunista alemán.",
    },
    {
      type: "info",
      continues: true,
      title: "Rosa Luxemburg",
      body: "Luxemburg ve con claridad la diferencia entre el caso ruso y el alemán, pero considera un **error** la modificación leninista del marxismo, por dos razones: hay que confiar en que las leyes de la historia se desplegarán por sí solas, dejando que los trabajadores lleguen a la conciencia de clase; y una élite dirigente siempre termina volviéndose conservadora, porque la verdadera energía revolucionaria viene del proletariado mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Rosa Luxemburg",
      body: "Encuentra el centralismo de Lenin demasiado cercano al **jacobinismo** de la Revolución Francesa, y cree que separa demasiado a la dirigencia del partido de los trabajadores a los que representa:",
    },
    {
      type: "info",
      continues: true,
      title: "Rosa Luxemburg",
      body: "La socialdemocracia [el movimiento comunista] no está unida a la organización del proletariado: **es** el proletariado mismo. El ultracentralismo que reclama Lenin está impregnado del espíritu estéril del capataz, no de un espíritu positivo y creativo. La preocupación de Lenin no es tanto hacer más fecunda la actividad del partido como controlarlo; estrechar el movimiento en vez de desarrollarlo, atarlo en vez de unificarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Rosa Luxemburg",
      body: "Para Luxemburg, lo inconsciente viene antes que lo consciente: la lógica del proceso histórico precede a la lógica subjetiva de quienes participan en él.",
    },
    {
      type: "quiz",
      question: "¿Por qué Rosa Luxemburg considera un error la modificación leninista del marxismo?",
      options: [
        "Porque toda élite dirigente termina volviéndose conservadora",
        "Porque el proletariado ruso ya tenía plena conciencia de clase",
        "Porque prefiere la vía parlamentaria antes que la revolucionaria",
        "Porque cree que Lenin subestima el papel de los intelectuales",
      ],
      answer: 0,
      explain: "Luxemburg da dos razones: las leyes de la historia se despliegan solas si se confía en los trabajadores, y toda élite dirigente termina volviéndose conservadora, porque la energía revolucionaria viene del proletariado mismo.",
    },
    {
      type: "info",
      title: "Georg Lukács",
      body: "De una generación más joven, **Lukács** es quizás el filósofo marxista húngaro más importante de su generación. Admira a Luxemburg, pero se pone del lado de Lenin en Historia y conciencia de clase, ensayo publicado después de la Revolución: sostiene que todo el sistema marxista se sostiene o cae con el principio de que la revolución surge de un punto de vista dominado por la **categoría de totalidad**. El sindicalismo, para Lukács, demuestra que no logra captar esa totalidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Georg Lukács",
      body: "En una palabra, el oportunismo confunde el estado psicológico real de conciencia de los proletarios con la conciencia de clase del proletariado.",
    },
    {
      type: "info",
      continues: true,
      title: "Georg Lukács",
      body: "Hay, para Lukács, una distinción entre lo empírico —cómo los obreros creen que piensan— y lo que, en sentido casi platónico, deberían pensar. Aunque admira a Luxemburg, considera que ella subestima el papel del Partido: para él, el Partido encarna la conciencia de clase, la unidad entre teoría y práctica, y esa unidad exige una disciplina de hierro.",
    },
    {
      type: "classify",
      question: "¿Cada posición es de Lenin o de Rosa Luxemburg?",
      groups: ["Lenin", "Luxemburg"],
      items: [
        { text: "Hace falta una vanguardia de revolucionarios profesionales", group: 0 },
        { text: "Hay que apurar la historia, no sentarse a esperarla", group: 0 },
        { text: "La conciencia de clase se le lleva al obrero desde afuera", group: 0 },
        { text: "El movimiento comunista es el proletariado mismo, no una élite", group: 1 },
        { text: "Toda élite dirigente termina volviéndose conservadora", group: 1 },
        { text: "El centralismo de partido se acerca al jacobinismo del Terror", group: 1 },
      ],
      explain: "Lenin quiere acelerar la historia con una vanguardia que aporte la conciencia desde afuera. Luxemburg confía en las leyes de la historia y en los trabajadores, y desconfía de toda élite dirigente.",
    },
    {
      type: "info",
      title: "Imperialismo, fase superior del capitalismo (1916)",
      body: "Durante los años de exilio en Zúrich, con la guerra mundial ya en curso, Lenin escribe El imperialismo, fase superior del capitalismo (1916). Sostiene que el capitalismo entró en una etapa nueva: el capital industrial se funde con el capital bancario en lo que llama **capital financiero**, la libre competencia cede paso a los monopolios, y las grandes potencias exportan capital hacia las colonias en busca de ganancias mayores, repartiéndose el mundo en zonas de influencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Imperialismo, fase superior del capitalismo (1916)",
      body: "La guerra de 1914, entonces, no es un accidente ni un choque de nacionalismos: es la consecuencia necesaria de esa etapa, una guerra entre potencias imperialistas por el reparto de los mercados coloniales. De ahí la idea, que Lenin repite al volver a Rusia en 1917, de que se trata de una guerra burguesa entre imperios, y de que los obreros de ningún país tienen motivo para morir por ella.",
    },
    {
      type: "info",
      continues: true,
      title: "Imperialismo, fase superior del capitalismo (1916)",
      body: "La teoría explica además, para Lenin, por qué el proletariado de los países más industrializados no se rebela como Marx había previsto: una parte de las ganancias coloniales permite a la burguesía comprar la paz social con salarios algo mejores para una capa de trabajadores, la llamada **aristocracia obrera**. Esa capa es, para Lenin, la base social del reformismo que critica en Bernstein y en buena parte de la Segunda Internacional.",
    },
    {
      type: "info",
      continues: true,
      title: "Imperialismo, fase superior del capitalismo (1916)",
      body: "En agosto de 1914 el quiebre ya se había producido: casi todos los partidos de la Segunda Internacional, incluido el socialdemócrata alemán, votan a favor de los créditos de guerra de sus propios gobiernos, traicionando el internacionalismo obrero que habían proclamado. Lenin llama a esa posición **socialchovinismo**, y desde el exilio exige lo contrario: convertir la guerra imperialista en guerra civil revolucionaria.",
    },
    {
      type: "quiz",
      question: "Para Lenin, ¿por qué la guerra de 1914 no es un choque accidental de nacionalismos?",
      options: [
        "Es la consecuencia necesaria de la etapa imperialista del capital",
        "Es una maniobra exclusiva de la aristocracia obrera europea",
        "Es resultado directo del asesinato del archiduque Francisco Fernando",
        "Es un conflicto religioso disfrazado de disputa territorial",
      ],
      answer: 0,
      explain: "El capital financiero, los monopolios y la exportación de capital a las colonias llevan a las potencias a repartirse el mundo; la guerra es la consecuencia de esa disputa por los mercados coloniales.",
    },
    {
      type: "short",
      question: "¿Cómo llama Lenin a la capa de trabajadores que la burguesía compra con las ganancias coloniales?",
      answers: ["aristocracia obrera"],
      explain: "Una parte de las ganancias del imperialismo permite salarios algo mejores para esa capa, y Lenin ve ahí la base social del reformismo que critica en Bernstein y en buena parte de la Segunda Internacional.",
    },
    {
      type: "info",
      title: "1905: el ensayo general",
      body: "La \"revolución de 1905\" en el Imperio zarista fue menos una revolución que una serie de huelgas, levantamientos campesinos y protestas de todo el espectro político: obreros, campesinos, intelectuales burgueses, reformistas y revolucionarios. Hay fermento, insatisfacción, rebelión contra la autoridad zarista, pero sin dirección unificada ni buena organización: algo parecido a 1848 en el Imperio austrohúngaro, y sin embargo algo quedó instalado.",
    },
    {
      type: "info",
      continues: true,
      title: "1905: el ensayo general",
      body: "En enero de 1905, la policía de San Petersburgo, bajo el zar Nicolás II, dispara contra una manifestación de trabajadores y mata a unas 130 personas: es el **Domingo Sangriento**, que radicaliza al país. Las protestas culminan en una huelga general en octubre; parece que las fuerzas cuasirrevolucionarias vencen, y el zar consiente crear una **Duma**, un cuerpo parlamentario, y algo parecido a una monarquía constitucional. Un año después el zar se echa atrás: fue una revolución incompleta, pero algo quedó en el aire.",
    },
    {
      type: "quiz",
      question: "¿Qué resultado tuvo finalmente la revolución de 1905?",
      options: [
        "El zar acepta crear la Duma, y luego se echa atrás",
        "El zar abdicó de inmediato tras el Domingo Sangriento",
        "Los soviets tomaron el poder en todo el imperio",
        "El ejército se negó a reprimir cualquier protesta",
      ],
      answer: 0,
      explain: "Tras el Domingo Sangriento y la huelga general de octubre, el zar consiente crear la Duma, casi una monarquía constitucional, pero un año después se echa atrás: fue una revolución incompleta.",
    },
    {
      type: "info",
      title: "1917: la Revolución de Febrero",
      body: "En 1914 estalla la Primera Guerra Mundial: el asesinato del archiduque Francisco Fernando por Gavrilo Princip, la declaración de guerra austrohúngara a Serbia, el ingreso del Imperio ruso del lado de Serbia y del alemán del lado austrohúngaro. La Revolución Bolchevique ocurre en medio de esa guerra: el imperio libra un conflicto externo y, a la vez, atraviesa una revolución interna.",
    },
    {
      type: "info",
      continues: true,
      title: "1917: la Revolución de Febrero",
      body: "La escena se traslada a **Petrogrado** —el nuevo nombre de San Petersburgo, que después será Leningrado y hoy vuelve a ser Petersburgo—. En febrero de 1917 la guerra lleva ya tres años; el imperio, empobrecido, sostiene un esfuerzo bélico atroz; es invierno, hay escasez de alimentos y una oscuridad casi permanente en esa latitud. La gente pasa hambre y ya no está segura de creer en el zar.",
    },
    {
      type: "info",
      continues: true,
      title: "1917: la Revolución de Febrero",
      body: "Estalla la **Revolución de Febrero** cuando los soldados empiezan a amotinarse y a negarse a combatir. El 2 de marzo de 1917 (calendario juliano, entonces vigente en Rusia), ante el motín, la escasez y las protestas masivas, **el zar Nicolás II abdica**: la dinastía Románov llevaba siglos en el trono, y de golpe, en plena guerra mundial, nadie sabe bien quién manda.",
    },
    {
      type: "quiz",
      question: "¿Qué hecho concreto marca el fin de la dinastía Románov en 1917?",
      options: [
        "La abdicación del zar Nicolás II el 2 de marzo",
        "La firma de la paz por separado en Brest-Litovsk",
        "La toma bolchevique del Palacio de Invierno",
        "La derrota militar total del ejército imperial",
      ],
      answer: 0,
      explain: "Ante el motín de los soldados, la escasez de alimentos y las protestas masivas en Petrogrado, Nicolás II abdica el 2 de marzo de 1917 (calendario juliano): siglos de dinastía terminan de golpe.",
    },
    {
      type: "info",
      title: "El doble poder",
      body: "Lo que sigue es un intento de instalar algo vagamente más democrático, mezclado con mucha anarquía, concentrado sobre todo en Petrogrado —hacia 1914 la clase obrera urbana del imperio era de unos 3 millones sobre unos 167, una minoría ínfima—. Surge el **doble poder**: por un lado, un gobierno provisional de fuerzas más burguesas y liberales; por otro, el **Soviet de Petrogrado**, más socialista y proletario. Aleksandr Kérenski, socialista y a la vez miembro del gobierno provisional, hace de enlace entre ambos.",
    },
    {
      type: "info",
      continues: true,
      title: "El doble poder",
      body: "Los campesinos, al principio entusiastas, empiezan a protestar y a negarse a entregar grano a las ciudades; las autoridades intentan requisarlo, crece el desencanto, y ese arreglo de poder dividido se acerca a la anarquía.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al Gobierno Provisional o al Soviet de Petrogrado?",
      groups: ["Gobierno Provisional", "Soviet de Petrogrado"],
      items: [
        { text: "Reúne a fuerzas más burguesas y liberales", group: 0 },
        { text: "Kérenski hace de enlace con el otro polo", group: 0 },
        { text: "Concentra a las fuerzas más socialistas y proletarias", group: 1 },
        { text: "Representa el ala más radical dentro del doble poder", group: 1 },
      ],
      explain: "En 1917 surge el doble poder en Petrogrado: el Gobierno Provisional, más burgués y liberal, y el Soviet de Petrogrado, más socialista y proletario, con Kérenski como enlace entre ambos.",
    },
    {
      type: "info",
      title: "El regreso de Lenin y Octubre",
      body: "Lenin está en Suiza, escribiendo, cuando estalla la revolución, y quiere volver a Petrogrado a toda costa. Tiene una idea central: salir ya de la guerra, que interpreta como una guerra burguesa entre imperios por la que los obreros no tienen motivo para morir. Quiere que el imperio se retire de inmediato, que los elementos radicales del Soviet no cooperen con el gobierno provisional, que se nacionalice toda la tierra y que todo el poder pase al Soviet de Petrogrado.",
    },
    {
      type: "info",
      continues: true,
      title: "El regreso de Lenin y Octubre",
      body: "Nada de esto es, para Lenin, un programa de mínima entre otros posibles: es la aplicación directa de la teoría del imperialismo que acaba de escribir en Zúrich. Si la guerra es un conflicto entre burguesías nacionales por el reparto colonial, entonces cualquier compromiso con el gobierno provisional —que sigue sosteniendo el esfuerzo bélico— equivale a colaborar con esa misma burguesía. De ahí la exigencia de ruptura total, sin matices, que sus propios camaradas bolcheviques reciben al principio con desconcierto.",
    },
    {
      type: "info",
      continues: true,
      title: "El regreso de Lenin y Octubre",
      body: "A los alemanes les conviene que el Imperio ruso deje de combatir, así que lo contrabandean en un vagón de tren sellado, junto con algunos camaradas bolcheviques, a través de la Europa en guerra hasta Petrogrado: Lenin llega en abril de 1917, en medio del caos.",
    },
    {
      type: "info",
      continues: true,
      title: "El regreso de Lenin y Octubre",
      body: "En junio, en un Congreso de los Soviets de toda Rusia, un dirigente menchevique pregunta si hay en Rusia algún partido capaz de tomar el poder ya; Lenin se pone de pie y responde: \"sí, existe tal partido\" —los bolcheviques, entonces un grupo pequeño para los estándares rusos, pero con Lenin muy confiado en su capacidad—.",
    },
    {
      type: "quiz",
      question: "Al volver a Petrogrado, ¿qué le exige Lenin al Soviet respecto del gobierno provisional?",
      options: [
        "Que no coopere y que todo el poder pase al Soviet",
        "Que forme una coalición amplia con los liberales",
        "Que espere a elecciones generales antes de actuar",
        "Que negocie una salida gradual y pactada de la guerra",
      ],
      answer: 0,
      explain: "Lenin pide salir ya de la guerra, que el Soviet no coopere con el gobierno provisional, nacionalizar la tierra y que todo el poder pase al Soviet: aplica directamente su teoría del imperialismo.",
    },
    {
      type: "info",
      title: "\"Encontré el poder tirado en la calle\"",
      body: "Después de un intento de golpe desde la derecha, protagonizado por el general Kornílov, y en medio de una anarquía creciente, el poder bolchevique dentro de los soviets sigue creciendo. Lenin dirá después que simplemente encontró el poder tirado en la calle y lo levantó: en una situación en que nadie sabía qué hacer, denunció todo compromiso e insistió en el radicalismo inmediato.",
    },
    {
      type: "info",
      continues: true,
      title: "\"Encontré el poder tirado en la calle\"",
      body: "El filósofo Slavoj Žižek, en la introducción a una compilación de escritos de Lenin de 1917 publicada en 2002, destaca esa audacia: la decisión de intervenir en una situación que nadie entendía y tomar el control con la certeza de que ese era el momento.",
    },
    {
      type: "info",
      title: "Un proletariado metafísico",
      body: "Cuando los bolcheviques toman el poder en **octubre de 1917**, eran una minoría ínfima: representaban un **proletariado metafísico**. No fue una revolución obrera —no había suficientes obreros para eso—, sino una revolución en nombre de los obreros, y ni siquiera de los obreros realmente existentes, sino de los que surgirían una vez apuradas las etapas de la historia. En la noche del 6 al 7 de noviembre, según el calendario actual, los bolcheviques toman el Palacio de Invierno en Petrogrado.",
    },
    {
      type: "quiz",
      question: "¿Por qué se llama proletariado metafísico al que representaban los bolcheviques en 1917?",
      options: [
        "Porque eran una mayoría abrumadora de obreros industriales",
        "Porque casi no había obreros, y se actuó en su nombre",
        "Porque los bolcheviques rechazaban la idea de clase social",
        "Porque el proletariado ruso era más culto que el occidental",
      ],
      answer: 1,
      explain: "La clase obrera urbana era una minoría ínfima, unos tres millones sobre ciento sesenta y siete. La toma del poder no fue una revolución obrera, sino en nombre de obreros que apenas existían.",
    },
    {
      type: "info",
      title: "Brest-Litovsk: la apuesta perdida",
      body: "Lenin firma luego una paz por separado con los alemanes en **Brest-Litovsk** (1918), que considera casi irrelevante porque cree que en cualquier momento los trabajadores del mundo se levantarán y derrocarán a sus gobiernos burgueses. El historiador Alexander Rabinowitch calificó esa apuesta como uno de los grandes errores de cálculo del siglo: Lenin confiaba en una revolución internacional inminente que no llegó a producirse.",
    },
    {
      type: "info",
      continues: true,
      title: "Brest-Litovsk: la apuesta perdida",
      body: "Al ver lo que hace Lenin, algunos mencheviques cruzan al otro bando, en especial **Trotsky**. Desde la óptica menchevique, los bolcheviques rompían las reglas del marxismo al no esperar a la historia; pero, cuando la cosa avanza, Trotsky les dice a los mencheviques que no lo acompañan:",
    },
    {
      type: "info",
      continues: true,
      title: "Brest-Litovsk: la apuesta perdida",
      body: "Sois individuos aislados y lamentables. Estáis en bancarrota. Vuestro papel ya está cumplido. Id adonde pertenecéis de ahora en más: al **basurero de la historia**.",
    },
    {
      type: "quiz",
      question: "¿Por qué el historiador Alexander Rabinowitch llama a Brest-Litovsk un gran error de cálculo?",
      options: [
        "Porque Lenin confiaba en una revolución mundial que no llegó",
        "Porque el ejército alemán nunca respetó los términos pactados",
        "Porque los mencheviques recuperaron el poder poco después",
        "Porque la paz se firmó sin que Lenin lo autorizara",
      ],
      answer: 0,
      explain: "Lenin considera casi irrelevante la paz de Brest-Litovsk porque cree que los trabajadores del mundo derrocarán pronto a sus gobiernos; esa revolución internacional inminente nunca llega a producirse.",
    },
    {
      type: "info",
      title: "Herencia: la enormidad y la contingencia",
      body: "La idea de una revolución obrera mundial no parecía entonces tan descabellada como hoy. En 1919 Lenin funda la **Internacional Comunista** (Comintern) para coordinar y exportar la revolución, y por un momento parece que puede prender: en Alemania, la revuelta espartaquista de enero de 1919 —en la que Rosa Luxemburg es asesinada por fuerzas paramilitares anticomunistas y su cuerpo arrojado a un canal de Berlín— estuvo cerca de imponerse en Berlín; en Hungría, Béla Kun proclama entre marzo y agosto de 1919 una **República Soviética Húngara**; algo similar, y más breve, ocurre en Eslovaquia.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: la enormidad y la contingencia",
      body: "Lo que sigue, con la consolidación de la Unión Soviética bajo Lenin, es el experimento de ingeniería social más vasto y penetrante jamás realizado sobre una población entera: la colectivización, la planificación centralizada de la economía, la construcción deliberada de instituciones —escuelas, sindicatos, la prensa entera— destinadas a producir un tipo de persona nuevo, acorde con la marcha de la historia tal como la entiende el Partido.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: la enormidad y la contingencia",
      body: "Todavía se discute la enormidad de ese experimento, la de la catástrofe que también produjo, y cómo un exceso de fe en la perfectibilidad humana puede desembocar en el aparato represivo del terror de Estado.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: la enormidad y la contingencia",
      body: "Pero el punto final no es esa catástrofe, sino la **contingencia histórica** y el papel a veces desproporcionado de los individuos. En febrero de 1917 Lenin está en Suiza escribiendo; decide volver a Rusia, y los alemanes aceptan contrabandearlo en un vagón sellado porque les conviene sacar al Imperio zarista de la guerra. Si algo le hubiera pasado a ese vagón, es discutible que hubiera existido la Revolución Bolchevique tal como ocurrió, y con ella buena parte del siglo XX que le siguió.",
    },
    {
      type: "quiz",
      question: "¿Qué tuvieron en común los intentos revolucionarios de Alemania y Hungría en 1919?",
      options: [
        "Estuvieron cerca de triunfar, pero terminaron derrotados",
        "Lograron instalar gobiernos comunistas muy duraderos",
        "Nunca contaron con apoyo de ningún sector obrero",
        "Fueron organizados en detalle desde Moscú por la Comintern",
      ],
      answer: 0,
      explain: "La revuelta espartaquista en Alemania, donde Luxemburg es asesinada, y la República Soviética Húngara de Béla Kun estuvieron cerca de imponerse, pero ambas terminan derrotadas en el mismo 1919.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que le corresponde",
      pairs: [
        { left: "¿Qué hacer? (1902)", right: "El texto donde Lenin expone su método" },
        { left: "Bolcheviques", right: "La mayoría que ganó la escisión de 1903" },
        { left: "Brest-Litovsk", right: "La paz por separado con Alemania en 1918" },
        { left: "Trotsky", right: "Cruzó del menchevismo al bolchevismo" },
        { left: "Comintern", right: "La Internacional fundada en 1919 para exportar la revolución" },
      ],
      explain: "El leninismo nace en ¿Qué hacer?, se institucionaliza en 1903 y llega al poder en 1917; Brest-Litovsk sella la salida de la guerra, Trotsky termina liderando junto a Lenin, y la Comintern intenta exportar el modelo.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: la enormidad y la contingencia",
      body: "El curso pasa ahora de la psicología de las masas revolucionarias a la del individuo: el psicoanálisis de Freud, que en esos mismos años elabora, desde Viena, otra manera de pensar lo que en el sujeto excede el control de la razón.",
    },
  ],
};
