export default {
  num: 13,
  transcript: 14,
  title: "La Escuela de Fráncfort",
  source: "https://www.youtube.com/watch?v=ntxMMezF804",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "La **Escuela de Fráncfort** nace en 1923 como el **Instituto de Investigación Social**, adscripto a la Universidad de Fráncfort, un centro que reúne a filósofos, sociólogos, musicólogos y psicólogos para producir lo que llamarán **teoría crítica**. Desde 1930 lo dirige **Max Horkheimer** (1895-1973), y su sello distintivo es la fusión deliberada de las grandes corrientes del pensamiento europeo de entreguerras: fenomenología, existencialismo, hegelianismo, psicoanálisis y marxismo, combinadas sin miedo al eclecticismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Sus miembros más influyentes son, además de Horkheimer, **Theodor Adorno** (1903-1969), compositor y musicólogo de formación antes que filósofo, y **Walter Benjamin** (1892-1940), ensayista y crítico literario que nunca llega a ser miembro pleno del Instituto pero cuya obra queda indisolublemente ligada a su proyecto. **Herbert Marcuse** (1898-1979), alumno de Heidegger, se suma en el exilio; **Wilhelm Reich** (1897-1957), psicoanalista disidente, se mueve en la órbita del grupo sin integrarlo formalmente.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Cuatro textos ordenan el programa: el ensayo de Horkheimer Teoría tradicional y teoría crítica (1937), que define el método; Dialéctica de la Ilustración, escrito por Adorno y Horkheimer en el exilio californiano en 1944 y publicado en 1947; La personalidad autoritaria (1950), estudio colectivo dirigido por Adorno; y Eros y civilización (1955), de Marcuse. Todos deben huir de Alemania en 1933 por su origen judío; el Instituto se reconstituye en el exilio, primero en Ginebra y París, luego en la Universidad de Columbia, en Nueva York.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue al proyecto intelectual de la Escuela de Fráncfort?",
      options: [
        "Funde fenomenología, marxismo y psicoanálisis sin miedo",
        "Se limita a aplicar el marxismo ortodoxo sin variantes",
        "Rechaza en bloque toda la filosofía alemana anterior a ella",
        "Separa de forma estricta filosofía, sociología y psicología",
      ],
      answer: 0,
      explain: "La teoría crítica se define por el eclecticismo deliberado: cruza fenomenología, existencialismo, hegelianismo, psicoanálisis y marxismo en un mismo proyecto interdisciplinario.",
    },
    {
      type: "info",
      title: "El problema heredado: el peso del compromiso en los años treinta",
      body: "El existencialismo francés había convertido la elección individual en el centro de la filosofía, con toda su angustia y su carga moral. La Escuela de Fráncfort hereda ese mismo clima —el fin de todo espacio neutral, la sensación de que no se puede hacer arte, filosofía o vida privada sin tomar posición política— pero lo piensa desde un contexto alemán más temprano y, en algún sentido, más determinante para el siglo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el peso del compromiso en los años treinta",
      body: "El grupo madura en la Alemania de Weimar (1919-1933), nacida tras la derrota en la Primera Guerra y el Tratado de Versalles (1919), que rediseña el mapa europeo según el principio de autodeterminación nacional y, al mismo tiempo, carga sobre Alemania la responsabilidad exclusiva de la guerra mediante la llamada cláusula de culpabilidad. Ese doble golpe —la catástrofe militar y la humillación moral— es el punto de partida psicológico de una generación que ve fracasar, a la vez, la revolución que casi ocurre en Alemania y la democracia liberal que efectivamente se instala.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el peso del compromiso en los años treinta",
      body: "Weimar es culturalmente deslumbrante y políticamente inestable: amenazada por derecha e izquierda, con el centro político desapareciendo y una crisis económica extrema que erosiona cualquier consenso. En 1933 el nazismo llega al poder por vía electoral, lo que deja una lección incómoda: nada en el mecanismo democrático impide, por sí solo, que una mayoría vote por el fascismo. Para entonces, sostener una posición neutral —no comprometerse— se ha vuelto, en los hechos, imposible.",
    },
    {
      type: "quiz",
      question: "¿Qué lección incómoda deja la llegada del nazismo al poder en 1933?",
      options: [
        "Que la vía electoral no impide que gane el fascismo",
        "Que Weimar careció por completo de elecciones libres",
        "Que el nazismo llegó sólo por un golpe militar directo",
        "Que la crisis económica alemana fue en realidad leve",
      ],
      answer: 0,
      explain: "El nazismo llega al poder por vía electoral en 1933: nada en el mecanismo democrático impide, por sí solo, que una mayoría vote por el fascismo. Weimar mostró que sostener una posición neutral se había vuelto imposible.",
    },
    {
      type: "info",
      title: "¿Qué es la teoría crítica?",
      body: "En Teoría tradicional y teoría crítica (1937), Horkheimer traza la distinción que da nombre a la escuela. La **teoría tradicional**, modelada sobre las ciencias naturales, se presenta como la descripción neutral de hechos por parte de un observador que queda fuera de lo que observa, sin intereses ni posición social propia. La **teoría crítica**, en cambio, parte de que el pensador está siempre ya inserto en la sociedad que analiza, y que ese lugar condiciona lo que puede ver; por eso no aspira solo a describir el mundo, sino a intervenir en su transformación.",
    },
    {
      type: "info",
      continues: true,
      title: "¿Qué es la teoría crítica?",
      body: "Por esa razón la teoría crítica se define como más **negativa que positiva**, no en sentido pesimista sino porque trabaja mejor desarmando sistemas que construyendo uno propio: critica con precisión, pero se niega deliberadamente a ofrecer un plano cerrado de la sociedad futura, incluida la utopía socialista hacia la que de todos modos se orienta.",
    },
    {
      type: "info",
      continues: true,
      title: "¿Qué es la teoría crítica?",
      body: "Rechaza cualquier teoría que prometa la reconciliación final de sujeto y objeto, y con eso rechaza, en particular, el telos hegeliano: toma de Hegel la **dialéctica** —la idea de que todo estado de cosas contiene la semilla de su propia contradicción— pero descarta que ese movimiento converja necesariamente en un final.",
    },
    {
      type: "info",
      continues: true,
      title: "¿Qué es la teoría crítica?",
      body: "De Heidegger, la Escuela retiene la idea de que no hay observación neutral posible: estar siempre ya en el mundo (Sorge, cuidado u ocupación) significa que ningún sujeto puede desentenderse de aquello que estudia. De ahí también su insistencia en la **praxis**, la acción cargada de teoría: no basta con describir ni con criticar, hay que intervenir, y la teoría misma debe entenderse como una forma de práctica social.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo describe a la teoría tradicional o a la teoría crítica?",
      groups: ["Teoría tradicional", "Teoría crítica"],
      items: [
        { text: "Observador neutral, sin intereses ni posición social", group: 0 },
        { text: "El pensador está siempre ya inserto en lo que analiza", group: 1 },
        { text: "Modelada sobre el método de las ciencias naturales", group: 0 },
        { text: "Se define como más negativa que positiva", group: 1 },
        { text: "Aspira sólo a describir el mundo tal como es", group: 0 },
        { text: "Aspira a intervenir en la transformación social", group: 1 },
      ],
      explain: "La teoría tradicional se presenta como descripción neutral, al modo de las ciencias naturales; la crítica parte de que el pensador está siempre inserto en la sociedad que estudia y por eso busca transformarla, no sólo describirla.",
    },
    {
      type: "info",
      title: "Walter Benjamin",
      body: "El más delicado del grupo en su sensibilidad, dividido entre su amistad con el estudioso del misticismo judío **Gershom Scholem** y su vínculo con Asja Lācis, militante bolchevique letona a la que sigue hasta Moscú. Su Diario de Moscú (invierno de 1926-1927) registra ese desgarro entre la tentación de afiliarse al Partido Comunista y su atracción por el misticismo judío, y de esa tensión nace una de sus observaciones más citadas: el comunismo **politiza el arte**, el fascismo **estetiza la política**.",
    },
    {
      type: "info",
      continues: true,
      title: "Walter Benjamin",
      body: "En La obra de arte en la época de su reproductibilidad técnica (1935) Benjamin sostiene que la fotografía y el cine, al multiplicar la obra sin original, disuelven su **aura** —esa cualidad de unicidad y presencia irrepetible que tenía la obra de arte tradicional— y abren, según el caso, una posibilidad emancipadora o una herramienta de propaganda de masas. En sus últimas Tesis sobre el concepto de historia (1940) describe la historia como un **ángel** empujado hacia el futuro por una tormenta que llama progreso, mientras mira hacia atrás un único cúmulo creciente de ruinas y catástrofes.",
    },
    {
      type: "quiz",
      question: "Según Benjamin, ¿qué le ocurre al «aura» de la obra de arte con la fotografía y el cine?",
      options: [
        "Se disuelve, porque la reproducción multiplica la obra",
        "Se intensifica, porque cada copia repite el original",
        "Permanece intacta, ya que el aura no depende del soporte",
        "Desaparece sólo en el cine, pero nunca en la fotografía",
      ],
      answer: 0,
      explain: "El aura es la cualidad de unicidad y presencia irrepetible de la obra tradicional. Al multiplicarla sin original, la reproducción técnica la disuelve, y eso abre, según el caso, una posibilidad emancipadora o una herramienta de propaganda.",
    },
    {
      type: "short",
      question: "¿Cómo llama Benjamin a la cualidad de unicidad y presencia irrepetible que la reproducción técnica disuelve?",
      answers: ["aura"],
      explain: "El aura: esa presencia irrepetible de la obra tradicional. La fotografía y el cine, al multiplicar la obra sin original, la disuelven, abriendo, según el caso, una posibilidad emancipadora o una herramienta de propaganda.",
    },
    {
      type: "info",
      title: "Theodor Adorno",
      body: "Viene de la música —estudia composición en Viena— antes que de la filosofía, y su tesis doctoral trata sobre la fenomenología de Husserl. Como todo el grupo, procede de la alta burguesía cultural alemana y se define como marxista, aunque con escaso contacto real con la clase obrera que su teoría reivindica.",
    },
    {
      type: "info",
      title: "Wilhelm Reich",
      body: "La figura más excéntrica del conjunto: un revolucionario sexual que sostiene que no puede haber liberación sexual bajo el capitalismo, y que el fracaso de los bolcheviques fue no haber atacado con suficiente radicalidad la moral sexual burguesa. En su obra sobre la psicología de masas del fascismo explora la represión sexual como condición de la sumisión autoritaria, pero deriva luego hacia la teoría del **orgón**, una supuesta energía vital acumulable en cajas especiales. Muere en 1957 en una cárcel federal estadounidense, tras un litigio con las autoridades sanitarias por esas afirmaciones.",
    },
    {
      type: "info",
      title: "Herbert Marcuse",
      body: "Menos estrafalario, aunque con preocupaciones afines sobre capitalismo y represión sexual. Estudia con Heidegger, y lee el marxismo como una filosofía cuyas raíces son, en el fondo, hegelianas. En el exilio estadounidense escribe Eros y civilización (1955), una respuesta directa a El malestar en la cultura de Freud.",
    },
    {
      type: "info",
      title: "El exilio y el Holocausto",
      body: "Judíos alemanes asimilados, de izquierda, profundamente identificados con la alta cultura alemana, todos deben huir del nazismo en 1933, lo que produce en ellos una crisis de identidad brutal: ser expulsados como \"no verdaderamente alemanes\" golpea con especial fuerza a quienes nunca se pensaron primero como judíos. Casi todos llegan a Estados Unidos. Benjamin, en cambio, huye a París, y cuando la ciudad cae en 1940 intenta cruzar a España para embarcar hacia Estados Unidos; llega al pueblo fronterizo el mismo día en que se cierra el paso, y se suicida esa noche.",
    },
    {
      type: "info",
      continues: true,
      title: "El exilio y el Holocausto",
      body: "Es en el exilio norteamericano donde Adorno, Horkheimer, Marcuse y Reich se enteran del Holocausto, un golpe existencial particular para intelectuales que se identificaban tan intensamente con la cultura que produjo el exterminio.",
    },
    {
      type: "info",
      continues: true,
      title: "El exilio y el Holocausto",
      body: "En Eros y civilización, escrito pensando en Auschwitz, Hiroshima y Nagasaki, Marcuse sostiene contra Freud que la represión no es un precio inevitable de la civilización: si el capitalismo desertiza el cuerpo para volverlo apto para el trabajo, reorganizar el trabajo para darle más espacio a Eros le restaría terreno a la pulsión de muerte. Hasta que se revierta esa tendencia represiva, escribe, la aniquilación seguirá siendo el destino más probable.",
    },
    {
      type: "info",
      title: "Dialéctica de la Ilustración",
      body: "El texto más denso e influyente del grupo no nace como libro sino como transcripción de conversaciones entre Adorno y Horkheimer en California, en 1944, recién enterados del Holocausto; se publica en 1947. Retoma la visión ilustrada —de Kant al marxismo clásico— de la razón como fuerza emancipadora que libera a la humanidad de la servidumbre autoimpuesta, y le opone una tesis incómoda: la Ilustración tuvo, desde el comienzo, un lado oscuro, y hay una línea que conecta ese proyecto racional con Auschwitz.",
    },
    {
      type: "info",
      continues: true,
      title: "Dialéctica de la Ilustración",
      body: "El argumento no es lineal sino dialéctico: usar la razón para comprender el mundo implica mirarlo como un objeto a moldear, y esa objetivación de la naturaleza termina rebotando sobre los propios seres humanos, que pasan también a ser tratados como objetos manipulables. La dominación del hombre sobre la naturaleza deriva en la dominación del hombre sobre el hombre, y de ahí en el sacrificio del individuo a la masa que sigue al líder fascista: la Ilustración, pensada para emancipar al sujeto, termina produciendo su disolución en el colectivo.",
    },
    {
      type: "info",
      title: "La razón instrumental",
      body: "Horkheimer da nombre técnico a ese proceso en Eclipse de la razón (1947): distingue una **razón objetiva**, capaz todavía de discutir fines y valores —qué vida vale la pena, qué es justo—, de una **razón instrumental**, que solo calcula los medios más eficientes para alcanzar cualquier fin dado, sin poder juzgar si ese fin mismo es racional. Cuando la razón se reduce a puro cálculo de medios, queda disponible para cualquier propósito, incluida la dominación total: la eficiencia técnica de un campo de exterminio no es, en ese sentido estricto, irracional.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la razón instrumental de la razón objetiva, para Horkheimer?",
      options: [
        "Sólo calcula medios eficaces, sin juzgar los fines mismos",
        "Sólo discute fines y valores, sin ocuparse de los medios",
        "Es la misma razón de siempre, con otro nombre técnico",
        "Rechaza cualquier forma de cálculo o eficiencia técnica",
      ],
      answer: 0,
      explain: "La razón objetiva discute fines y valores; la instrumental sólo calcula los medios más eficientes para cualquier fin dado, sin poder juzgar si ese fin es racional. Por eso queda disponible incluso para la dominación total.",
    },
    {
      type: "info",
      title: "La industria cultural",
      body: "Uno de los capítulos de Dialéctica de la Ilustración lleva por título \"La industria cultural\" y extiende el diagnóstico al entretenimiento de masas. El cine, la radio y las revistas ilustradas, sostienen Adorno y Horkheimer, no son un espacio libre de creación popular sino una industria que produce cultura según la misma lógica de estandarización que rige cualquier otra mercancía: fórmulas repetidas, finales previsibles, una variedad solo aparente que da la ilusión de elección donde en realidad hay un molde único.",
    },
    {
      type: "info",
      continues: true,
      title: "La industria cultural",
      body: "La función social de esa industria, para ambos autores, no es liberar sino adaptar: entretiene para que el tiempo libre reponga fuerzas de trabajo sin producir preguntas incómodas sobre el orden existente, y así la misma razón instrumental que organiza la fábrica organiza también el ocio. El resultado es una cultura de masas que promete individualidad y produce conformidad, la contracara exacta, en el terreno del consumo, de la conformidad autoritaria que otros trabajos del grupo estudian en el terreno político.",
    },
    {
      type: "quiz",
      question: "Para Adorno y Horkheimer, ¿qué función cumple la industria cultural?",
      options: [
        "Adaptar: entretiene sin producir preguntas incómodas",
        "Liberar: multiplica el arte popular libre de mercado",
        "Educar: forma un público crítico frente al poder vigente",
        "Documentar con total fidelidad los gustos populares reales",
      ],
      answer: 0,
      explain: "La industria cultural no libera sino que adapta: entretiene para reponer fuerzas de trabajo sin generar preguntas incómodas sobre el orden existente. Promete individualidad y produce conformidad.",
    },
    {
      type: "info",
      title: "La personalidad autoritaria",
      body: "Ya instalado en Estados Unidos, y con el ascenso del fascismo todavía reciente, Adorno dirige junto a otros investigadores el estudio La personalidad autoritaria (1950), un intento de responder empíricamente a una pregunta que la teoría por sí sola no puede zanjar: qué rasgos de carácter vuelven a una persona receptiva a la propaganda fascista, más allá de las condiciones económicas o políticas del momento.",
    },
    {
      type: "info",
      continues: true,
      title: "La personalidad autoritaria",
      body: "El equipo diseña una escala de actitudes —la llamada **escala F**, de fascismo potencial— y encuestas y entrevistas extensas para identificar un patrón recurrente: sumisión a la autoridad establecida, agresividad hacia quienes se apartan de la convención, rigidez frente a la ambigüedad, desconfianza generalizada y fascinación por el poder y la dureza. El estudio insiste en que ese patrón no es privativo de la Alemania nazi, sino un potencial latente en cualquier sociedad, incluida la democracia estadounidense de posguerra en la que se realiza la investigación.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la escala que diseñó el equipo de Adorno para medir el fascismo potencial de una persona?",
      answers: ["escala F", "escala f"],
      explain: "La escala F (de fascismo potencial): mide sumisión a la autoridad, agresividad hacia quienes se apartan de la convención, rigidez y fascinación por el poder. Un patrón que Adorno considera latente en cualquier sociedad, no sólo en la Alemania nazi.",
    },
    {
      type: "info",
      title: "Auschwitz y la poesía",
      body: "Para Adorno, Auschwitz no es un episodio aislado sino la revelación del sentido oculto de toda la modernidad: una historia que puede leerse, igual de bien, como progreso o como camino hacia el infierno. De ahí su afirmación más citada y más discutida: escribir poesía después de Auschwitz es un acto de barbarie.",
    },
    {
      type: "info",
      continues: true,
      title: "Auschwitz y la poesía",
      body: "Adorno termina matizando esa posición, en parte por la poesía del rumano de lengua alemana **Paul Celan**, sobreviviente del Holocausto que perdió a sus padres en él y que, siendo judío, elige seguir escribiendo en alemán después de la guerra. Su poema más conocido, Fuga de muerte, abre con una imagen que se volvió emblema de esa poesía posible después de Auschwitz: \"leche negra del alba, la bebemos de tarde, la bebemos al mediodía y de mañana, la bebemos de noche; bebemos y bebemos\".",
    },
    {
      type: "info",
      continues: true,
      title: "Auschwitz y la poesía",
      body: "Celan se suicida en París en 1970, poco después de una visita a Heidegger en su cabaña de la Selva Negra —un encuentro que vuelve a poner sobre la mesa, sin resolverla, la relación entre la filosofía de Heidegger y el nazismo.",
    },
    {
      type: "quiz",
      question: "¿Por qué Adorno termina matizando su afirmación sobre la poesía después de Auschwitz?",
      options: [
        "Por la poesía de Celan, sobreviviente que sigue escribiendo",
        "Porque cambia de opinión sobre el sentido de la historia",
        "Porque Celan lo convence de abandonar la teoría crítica",
        "Porque deja de considerar a Auschwitz un hecho central del siglo",
      ],
      answer: 0,
      explain: "La poesía de Paul Celan, sobreviviente del Holocausto que sigue escribiendo en alemán, matiza la afirmación de Adorno: muestra que sí es posible una poesía después de Auschwitz.",
    },
    {
      type: "match",
      question: "Uní cada pensador de la Escuela de Fráncfort con su aporte",
      pairs: [
        { left: "Horkheimer", right: "Distingue razón objetiva de razón instrumental" },
        { left: "Adorno", right: "Dirige el estudio de la personalidad autoritaria" },
        { left: "Benjamin", right: "El aura se disuelve con la reproducción técnica" },
        { left: "Marcuse", right: "En Eros y civilización, discute con Freud" },
        { left: "Reich", right: "Liga represión sexual y sumisión autoritaria" },
      ],
      explain: "Horkheimer aporta el vocabulario de la razón instrumental; Adorno mide el fascismo potencial con la escala F; Benjamin piensa el arte reproducido; Marcuse revisa a Freud desde el exilio; Reich liga sexualidad reprimida y autoritarismo.",
    },
    {
      type: "info",
      title: "Cierre: la herencia",
      body: "La Escuela de Fráncfort deja un diagnóstico incómodo, porque no distingue con nitidez entre los regímenes totalitarios y las democracias de mercado: para Horkheimer y Adorno, la razón instrumental y la industria cultural operan también en Occidente, con medios menos violentos pero con una lógica de fondo emparentada. Esa sospecha hacia la sociedad de consumo de posguerra, y la pregunta por qué hace a una personalidad susceptible al autoritarismo, alimentan directamente los debates posteriores sobre el poder, la ideología y el totalitarismo.",
    },
  ],
};
