export default {
  num: 11,
  transcript: 12,
  title: "El existencialismo heideggeriano",
  source: "https://www.youtube.com/watch?v=l1jzdqwMePs",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Martin Heidegger** (1889-1976) nace en Meßkirch, un pueblo católico del sur de Alemania al borde de la Selva Negra, con la que quedará asociado toda su vida: hoy todavía se peregrina a la cabaña en Todtnauberg donde escribió su libro mayor. Se forma para el sacerdocio, con estudios de teología, filología clásica y filosofía escolástica, antes de volcarse por completo a la filosofía en Friburgo. Es asistente de **Husserl** en Friburgo entre 1919 y 1923 y comparte con él, y con otros discípulos como Levinas, Edith Stein e Ingarden, el lema \"a las cosas mismas\" (zu den Sachen selbst).",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Como profesor, primero en Friburgo y luego en Marburgo, se vuelve rápidamente célebre por sus clases: hacia el final de su vida, en su homenaje por los ochenta años, Hannah Arendt diría que nadie había podido dar clase como él, y que nadie lo había logrado desde entonces. Es, en todo su porte, un **hombre del bosque** y no de la ciudad ni de los cafés: mira con desdén a los intelectuales urbanos, esquía, y se presenta en encuentros académicos con ropa de montaña.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En el célebre debate de Davos de 1929 con el filósofo Ernst Cassirer, la esposa de este lo describió como \"un hombrecito insignificante que entró con la torpeza de un campesino que ha tropezado en una corte real […] lo más inquietante era su seriedad mortal y su total falta de sentido del humor\".",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Atrae a numerosos estudiantes, pero hacia mediados de los años veinte corre el riesgo de perder su puesto porque no ha publicado nada. En 1926, bajo esa amenaza, se retira a la cabaña de Todtnauberg a escribir el libro que será **Ser y tiempo**. Husserl le envía cartas de aliento ese mismo año: le escribe que se alegra de verlo dedicado a la obra por la que llegará a ser quien es, y que nadie cree en él más firmemente.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El libro se había planeado en dos partes; la segunda nunca se escribe, y de la primera apenas se completan dos tercios. Cuando termina ese borrador, Heidegger lo envuelve en flores y se lo entrega a Husserl el 8 de abril de 1926, para su cumpleaños, con la dedicatoria \"en amistad y admiración\".",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El libro aparece en 1927 como Sein und Zeit. Es una obra de lectura casi imposible en un primer intento, porque Heidegger inventa un vocabulario filosófico propio, que juega con las posibilidades gramaticales y etimológicas del alemán: un psicólogo que asistió a uno de sus seminarios lo comparó con la experiencia de un marciano que se topa con un grupo de terrícolas e intenta comunicarse con ellos.",
    },
    {
      type: "quiz",
      question: "¿A quién le entrega Heidegger el borrador de Ser y tiempo en 1926?",
      options: [
        "A Husserl, envuelto en flores, para su cumpleaños",
        "A Cassirer, tras el debate filosófico de Davos",
        "A Hannah Arendt, como regalo de casamiento",
        "A la Academia Prusiana de Ciencias de Berlín",
      ],
      answer: 0,
      explain: "Bajo amenaza de perder el puesto por no haber publicado nada, Heidegger termina ese borrador y se lo entrega a Husserl el 8 de abril de 1926, envuelto en flores, para su cumpleaños, con la dedicatoria «en amistad y admiración».",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En 1928 sucede a Husserl en su cátedra de Friburgo. En 1933 asume el rectorado de esa universidad y se afilia al Partido Nazi; ese episodio, y lo que implica para leer el resto de su filosofía, exige un tratamiento propio y detenido. Tras la guerra, un tribunal de desnazificación le prohíbe enseñar durante varios años; en esa etapa de silencio público escribe los textos de su llamado \"giro\" tardío, entre ellos la Carta sobre el humanismo (1946) y el ensayo La pregunta por la técnica (1954). Muere en 1976 y se lo entierra en Meßkirch.",
    },
    {
      type: "info",
      title: "El problema heredado: el puente que Husserl creía haber cruzado",
      body: "Husserl había planteado el viejo **problema del puente** —cómo pasar del sujeto al objeto, cómo saber que el mundo existe realmente y no es una proyección de la conciencia— como la cuestión del **fundamento**: cómo sentirse en casa en el mundo, cómo sentir que hay algo estable en lo que apoyarse.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el puente que Husserl creía haber cruzado",
      body: "Su distinción entre la **actitud natural** y la **actitud fenomenológica** guarda un parentesco cercano con otra distinción, la del formalista ruso Shklovski entre **reconocer** algo y **verlo de verdad**: casi siempre se transita por la vida en un estado casi sonámbulo, sin ver realmente el mundo, y algo tiene que sacudir esa costumbre para que se vea de verdad. Para Shklovski ese sacudón lo produce el lenguaje poético; para Husserl, el procedimiento técnico de entrar en la actitud fenomenológica.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el puente que Husserl creía haber cruzado",
      body: "Husserl creía haber resuelto el problema del puente con la **intencionalidad**: la conciencia nunca está encerrada en una caja, siempre está ya alcanzando un objeto, como un verbo que necesita un objeto directo. La relación entre sujeto y objeto precede a las partes; no hay un momento anterior a ella. Donde Descartes decía ego cogito, \"yo pienso\", Husserl decía ego cogito cogitatum, \"yo pienso un objeto\": siempre hay un objeto.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el puente que Husserl creía haber cruzado",
      body: "Pero esa solución hacía un doble movimiento difícil de sostener: **objetivaba la subjetividad**, purificando el sujeto en un ego trascendental transparente y universal, y a la vez **subjetivaba la objetividad**, sosteniendo que no hay objeto sin sujeto. Hay un refrán, que circula en polaco, en ruso y en yidis, según el cual no se puede bailar en dos casamientos a la vez; Husserl pasa toda su obra intentando demostrar que sí se puede: quería, a la vez, toda la profundidad de la subjetividad y toda la firmeza de la objetividad, sin renunciar a ninguna de las dos.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema heredado: el puente que Husserl creía haber cruzado",
      body: "Heidegger fue alumno de doctorado y asistente de Husserl, quien depositó en él la esperanza de que continuara el proyecto fenomenológico. Pero cuando publica Ser y tiempo en 1927 no continúa ese proyecto: lo desvía en su raíz, y empieza por acusar a toda la tradición filosófica —incluido Husserl— de haber olvidado la pregunta más elemental de todas.",
    },
    {
      type: "quiz",
      question: "¿Qué intenta Husserl al «bailar en dos casamientos a la vez»?",
      options: [
        "Separar de una vez por todas el sujeto del objeto",
        "Unir la hondura del sujeto y la certeza del objeto",
        "Reducir el objeto a una mera ilusión de la mente del sujeto",
        "Renunciar por igual al sujeto y al objeto",
      ],
      answer: 1,
      explain: "Husserl objetiva la subjetividad (el ego trascendental) y subjetiva la objetividad (no hay objeto sin sujeto): quiere la profundidad del sujeto y la firmeza del objeto juntas. Heidegger dirá que eso está mal planteado desde el inicio.",
    },
    {
      type: "info",
      title: "El olvido del ser",
      body: "La acusación de Heidegger es que la filosofía moderna, obsesionada con la **epistemología** —cómo sé qué existe realmente, cómo estar seguro de la correspondencia entre lo que creo saber y lo que hay—, empezó por el lugar equivocado. Esa obsesión, inaugurada por Descartes, \"llegó demasiado pronto\": antes de preguntar qué significa **conocer**, había que preguntar qué significa **ser**. La filosofía occidental, sostiene, incurrió en un **Seinsvergessenheit**, un **olvido del ser**, que se remonta a los griegos antiguos y que ninguna epistemología posterior corrigió.",
    },
    {
      type: "quiz",
      question: "¿Qué le reprocha Heidegger a toda la filosofía moderna?",
      options: [
        "Haber olvidado por completo la pregunta por el ser",
        "Haber abandonado del todo la epistemología",
        "Haberse desentendido de la lógica formal",
        "Haber confiado demasiado en los griegos antiguos",
      ],
      answer: 0,
      explain: "Es el Seinsvergessenheit, el olvido del ser. Desde Descartes la filosofía se preguntó cómo conocemos y olvidó la pregunta primera: qué significa ser. Para Heidegger la ontología precede a la epistemología.",
    },
    {
      type: "info",
      title: "Sein y Seiendes: la diferencia ontológica",
      body: "El libro arranca de una distinción de vocabulario que en español, y también en inglés, es difícil de conservar: en inglés, de hecho, Sein y Seiendes colapsan en la misma palabra, \"being\", y toda la distinción con que arranca el libro se pierde en la traducción. **Sein** es el verbo \"ser\" sustantivado: **el ser** como tal, incontable, la pregunta por lo que significa que algo sea. **Ein Seiendes** es, en cambio, un **ente**, algo contable: una persona, una piedra, un martillo.",
    },
    {
      type: "info",
      continues: true,
      title: "Sein y Seiendes: la diferencia ontológica",
      body: "A esta distinción entre el ser y los entes Heidegger la llama **diferencia ontológica**, y sostiene que toda la filosofía anterior la pasó por alto, ocupándose de los entes y dando por sabido, sin preguntarlo nunca, qué quiere decir que algo \"sea\". Solo un tipo muy particular de ente puede plantear la pregunta por el ser: ni el gato, ni el abejorro, ni el jabalí pueden preguntarse qué significa ser, pero los seres humanos sí. Estamos, en ese sentido preciso, en una posición **privilegiada** entre todos los entes.",
    },
    {
      type: "quiz",
      question: "¿Cómo llama Heidegger a la distinción entre el ser (Sein) y los entes (Seiendes)?",
      options: [
        "Diferencia óntica, propia de cada disciplina científica",
        "Diferencia ontológica, el eje que la filosofía olvidó",
        "Diferencia trascendental, heredada directamente de Kant",
        "Diferencia fenomenológica, tomada en préstamo de Husserl",
      ],
      answer: 1,
      explain: "Heidegger llama diferencia ontológica a la distinción entre el ser y los entes, y sostiene que toda la filosofía anterior la pasó por alto, ocupándose de los entes sin preguntar nunca qué significa que algo «sea».",
    },
    {
      type: "info",
      continues: true,
      title: "Sein y Seiendes: la diferencia ontológica",
      body: "Para nombrar a ese ente que se pregunta por el ser, Heidegger evita deliberadamente palabras como \"sujeto\", \"conciencia\" o \"ser humano\", que arrastran toda la tradición cartesiana, y acuña **Dasein**, literalmente \"ser-ahí\" (Da, \"ahí\"; Sein, \"ser\"), que suele dejarse sin traducir. A diferencia de las mascotas, los animales de granja o cualquier otro ente natural, el Dasein es aquel que está ahí, en alguna parte, y en posición privilegiada porque puede preguntar qué significa el ser.",
    },
    {
      type: "quiz",
      question: "¿Por qué el Dasein ocupa una posición «privilegiada»?",
      options: [
        "Porque es inmortal, a diferencia de los animales",
        "Porque puede preguntar qué significa ser",
        "Porque contempla el mundo desde afuera",
        "Porque es un sujeto puro y transparente",
      ],
      answer: 1,
      explain: "Ni el gato ni el abejorro pueden interrogarse por el sentido del ser; sólo el Dasein. Esa capacidad de preguntar por el ser —estando ya dentro de una comprensión previa— es lo que nos distingue.",
    },
    {
      type: "short",
      question: "¿Con qué palabra, que significa «ser-ahí», reemplaza Heidegger al «sujeto» humano?",
      answers: ["Dasein"],
      explain: "Dasein: «ser-ahí» (Da, ahí; Sein, ser). Heidegger rechaza «sujeto» y «conciencia»; el Dasein es el ente que existe ahí, en el mundo, y que puede preguntar por el ser.",
    },
    {
      type: "info",
      continues: true,
      title: "Sein y Seiendes: la diferencia ontológica",
      body: "Plantear la pregunta por el ser exige ya tener una idea previa de lo que significa \"ser\": si no supiéramos nada del verbo, ni siquiera podríamos formular la pregunta. A esto lo llama **círculo hermenéutico**: hay que estar ya adentro de la comprensión del ser para poder interrogarla, y eso también es lo que nos hace especiales. Heidegger lo formula así:",
    },
    {
      type: "info",
      continues: true,
      title: "Sein y Seiendes: la diferencia ontológica",
      body: "El Dasein es un ente que no solo ocurre entre otros entes; más bien, se distingue ónticamente por el hecho de que, en su ser mismo, ese ser le es un problema. La comprensión del ser es ella misma un rasgo definitorio del ser del Dasein. El Dasein es ónticamente distintivo en que es ontológico.",
    },
    {
      type: "info",
      continues: true,
      title: "Sein y Seiendes: la diferencia ontológica",
      body: "De ahí que Heidegger invierta la fórmula cartesiana: no \"pienso, luego existo\", sino, en cierto sentido, \"existo, luego pienso\". La **ontología precede a la epistemología**: antes de preguntar cómo se conoce, hace falta ya estar instalado en una comprensión —por vaga que sea— de lo que significa ser.",
    },
    {
      type: "quiz",
      question: "¿Cómo invierte Heidegger la fórmula cartesiana «pienso, luego existo»?",
      options: [
        "Dice, en cierto sentido, que existo, luego pienso",
        "Dice que ni pienso ni existo, sólo interpreto",
        "Dice que pensar y existir son exactamente lo mismo",
        "Dice que primero hay que dudar de la propia existencia",
      ],
      answer: 0,
      explain: "Para Heidegger la ontología precede a la epistemología: antes de preguntar cómo se conoce, hace falta ya estar instalado en una comprensión previa de lo que significa ser. Es el círculo hermenéutico: hay que estar ya adentro para poder interrogarlo.",
    },
    {
      type: "info",
      title: "Siempre ya en el mundo",
      body: "El concepto más radical del libro es que el Dasein está **siempre ya en el mundo** (immer schon in der Welt sein), lo que Heidegger escribe con guiones: **ser-en-el-mundo**. Toda la cuestión sujeto/objeto está, para él, mal planteada desde el inicio, porque presupone una distancia entre ambos, un punto arquimediano fuera del mundo desde el cual un sujeto contemplaría un objeto, como si pudiera existir la posición de alguien que mira el mundo desde completamente afuera de él —la posición, en todo caso, de un astronauta que en verdad nunca deja de llevar su mundo consigo—.",
    },
    {
      type: "info",
      continues: true,
      title: "Siempre ya en el mundo",
      body: "Pero no hay tal distancia ni tal afuera: no hay manera de salir del mundo para preguntar si existe, porque siempre ya estamos adentro. Y no solo adentro: estamos **involucrados**, no somos neutrales, hacemos cosas, nos importan cosas, convivimos con otros entes. Donde Husserl creía resolver el problema del puente con la intencionalidad, Heidegger lo disuelve de otro modo: no hace falta puente porque nunca hubo brecha. Es una inversión completa del paradigma sujeto-objeto que domina la filosofía desde Descartes.",
    },
    {
      type: "quiz",
      question: "¿Cómo «disuelve» Heidegger el problema del puente sujeto-objeto?",
      options: [
        "Construye un puente mucho más firme que el de Husserl",
        "Niega que el objeto exista fuera del sujeto",
        "Muestra que no hay brecha, ya estamos en el mundo",
        "Demuestra la existencia del mundo con certeza",
      ],
      answer: 2,
      explain: "Donde Husserl tendía un puente con la intencionalidad, Heidegger dice que no hace falta puente porque no hay brecha: el Dasein está siempre ya en el mundo. La pregunta sujeto/objeto estaba mal planteada.",
    },
    {
      type: "info",
      title: "A la mano y ante los ojos",
      body: "La relación cotidiana con las cosas del mundo no es, primero y las más de las veces, contemplativa: es de **uso**. No se contempla la lapicera o el martillo como objetos neutros: se los usa. Heidegger llama a ese modo de darse **zuhanden**, \"a la mano\" (Zuhandenheit).",
    },
    {
      type: "info",
      continues: true,
      title: "A la mano y ante los ojos",
      body: "No se anda por el mundo contemplando abstractamente la taza, el cuchillo o la silla; se los usa sin pensarlos, y es apenas cuando falta algo —cuando no se encuentra la llave, cuando falla el objeto que hacía falta— que toda la trama de utensilios que rodea la vida cotidiana se hace, de golpe, visible como tal.",
    },
    {
      type: "info",
      continues: true,
      title: "A la mano y ante los ojos",
      body: "Solo cuando algo falla —cuando el martillo se rompe— el objeto se vuelve, en un modo secundario y deficiente, **vorhanden**, \"ante los ojos\", presente como cosa contemplada y ya no como herramienta transparente. Solo se ve realmente el martillo cuando deja de funcionar: es otra variación del mismo problema que plantea Shklovski, bajo qué condiciones se llega a ver de verdad algo que el uso cotidiano vuelve invisible.",
    },
    {
      type: "classify",
      question: "¿Cada situación es «a la mano» (zuhanden) o «ante los ojos» (vorhanden)?",
      groups: ["A la mano", "Ante los ojos"],
      items: [
        { text: "Usás el martillo sin prestarle atención", group: 0 },
        { text: "El martillo se rompe y recién ahí lo mirás", group: 1 },
        { text: "Escribís con la lapicera sin pensar en ella", group: 0 },
        { text: "Contemplás la lapicera como un objeto aparte", group: 1 },
        { text: "La silla te sostiene mientras hacés otra cosa", group: 0 },
        { text: "Algo falla y la cosa se vuelve objeto de examen", group: 1 },
      ],
      explain: "Primero y las más de las veces las cosas son zuhanden, «a la mano»: las usamos sin contemplarlas. Sólo cuando algo falla pasan a ser vorhanden, «ante los ojos», objetos de contemplación. Para Heidegger, ese modo contemplativo es secundario y deficiente.",
    },
    {
      type: "info",
      title: "Estar arrojado",
      body: "A esta condición de estar siempre ya en el mundo, sin haberla elegido, Heidegger la llama **Geworfenheit**, la **condición de arrojado**. Estamos siempre ya arrojados a un tiempo, un lugar y un cuerpo que no elegimos, sin que exista un \"antes\" desde el cual habernos decidido a entrar en el mundo. Esa arrojadidad es el punto de partida de toda existencia concreta, y sobre ella cada Dasein tiene, sin embargo, que decidir cómo va a ser.",
    },
    {
      type: "quiz",
      question: "¿Qué implica la «Geworfenheit» (condición de arrojado) del Dasein?",
      options: [
        "No elegimos el tiempo, el lugar ni el cuerpo en que existimos",
        "Elegimos libremente el momento en que vamos a nacer",
        "El Dasein decide su propio origen antes de existir",
        "El mundo se adapta siempre a lo que el Dasein necesita",
      ],
      answer: 0,
      explain: "Estamos siempre ya arrojados a un tiempo, un lugar y un cuerpo que no elegimos, sin que exista un «antes» desde el cual habernos decidido a entrar en el mundo. Sobre esa arrojadidad, cada Dasein tiene que decidir cómo va a ser.",
    },
    {
      type: "info",
      title: "Autenticidad e inautenticidad",
      body: "Arrojados al mundo, hay dos modos principales de existir en él. El primero, en el que se vive primero y las más de las veces, es la **inautenticidad** (Uneigentlichkeit): ceder la carga de decidir a la convención social, hacer lo que \"se hace\".",
    },
    {
      type: "info",
      continues: true,
      title: "Autenticidad e inautenticidad",
      body: "Heidegger llama a esa instancia impersonal **das Man**, el \"**se**\" o el \"uno\": lo que se dice, lo que se usa, lo que hace la gente, sin que haya nadie en particular que lo decida —el equivalente filosófico de la pregunta cotidiana sobre qué va a pensar la gente, formulada por nadie en particular y sin embargo obedecida por todos—.",
    },
    {
      type: "info",
      continues: true,
      title: "Autenticidad e inautenticidad",
      body: "El Dasein inauténtico vive **verfallen**, \"caído\" en el mundo, absorbido en el **Gerede**, la \"**habladuría**\", la charla sobre nada que ocupa el lugar de una decisión propia. Heidegger describe esa condición con dureza:",
    },
    {
      type: "info",
      continues: true,
      title: "Autenticidad e inautenticidad",
      body: "En el ser-uno-con-otro cotidiano, el Dasein está bajo la sujeción de los otros. No es él mismo; los otros le han quitado su ser […] Cada uno es el otro y ninguno es sí mismo. El \"uno\" […] es el \"nadie\" al que todo Dasein se ha entregado ya.",
    },
    {
      type: "info",
      continues: true,
      title: "Autenticidad e inautenticidad",
      body: "Es una forma de alienación respecto de un sí-mismo más propio, pero también resulta reconfortante: es más fácil dejarse llevar por la corriente que asumir la responsabilidad de decidir.",
    },
    {
      type: "quiz",
      question: "¿Qué es el «das Man» (el «se» impersonal) para Heidegger?",
      options: [
        "La instancia anónima que decide sin que nadie decida",
        "El grupo de amigos más cercano de cada persona",
        "La conciencia moral que juzga las propias acciones",
        "El Estado, que impone sus normas por la fuerza",
      ],
      answer: 0,
      explain: "Das Man es lo que se dice, lo que se usa, lo que hace la gente, sin que haya nadie en particular que lo decida. El Dasein inauténtico vive «caído», absorbido en la habladuría que ocupa el lugar de una decisión propia.",
    },
    {
      type: "info",
      title: "Finitud y ser-para-la-muerte",
      body: "El otro modo, la **autenticidad** (Eigentlichkeit), está ligado a la **temporalidad** y, sobre todo, a la **finitud**. Somos seres que no viven para siempre; nuestra condición es siempre ya **Sein zum Tode**, **ser-para-la-muerte**: avanzamos, desde que estamos arrojados en el mundo, hacia nuestra propia muerte. Vivir con autenticidad es mirar esa condición de frente, sin desviar la mirada; la inautenticidad, en cambio, es una manera cotidiana de huir de ella.",
    },
    {
      type: "info",
      continues: true,
      title: "Finitud y ser-para-la-muerte",
      body: "Encarar el ser-para-la-muerte produce **Angst**, angustia. Heidegger distingue con precisión la angustia del **miedo**: el miedo, como la conciencia husserliana, siempre tiene un objeto —se teme a algo concreto—, mientras que aquello ante lo cual se angustia el Dasein es la **nada**, precisamente el futuro inevitable de la propia existencia. Es una inquietud sin objeto ante la certeza de que un día se dejará de ser.",
    },
    {
      type: "quiz",
      question: "¿En qué se distingue la angustia (Angst) del miedo?",
      options: [
        "La angustia es siempre más intensa que el miedo común",
        "El miedo es racional y la angustia irracional",
        "El miedo tiene un objeto; la angustia, la nada",
        "La angustia se cura con el tiempo y el miedo no",
      ],
      answer: 2,
      explain: "El miedo, como el cogito, toma un objeto. La angustia no: aquello de lo que se angustia es la nada misma, nuestra propia finitud. Por eso deja al Dasein en la Unheimlichkeit, el no-estar-en-casa en el mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "Finitud y ser-para-la-muerte",
      body: "Esa angustia trae consigo la **Unheimlichkeit**, palabra que también usará Freud y que suele traducirse como \"lo siniestro\" pero que, literalmente, significa \"**no estar en casa**\" (de Heim, hogar). Confrontar la propia finitud vuelve extraño el mundo entero, porque quita todo suelo estable bajo los pies: es la misma falta de fundamento que atormentaba a la vanguardia y a Husserl, reformulada ahora como estructura de la existencia individual.",
    },
    {
      type: "short",
      question: "¿Cómo llama Heidegger al pavor sin objeto, ante la nada, que sacude al Dasein?",
      answers: ["Angst", "angustia"],
      explain: "Angst (angustia): a diferencia del miedo, no tiene objeto; su «objeto» es la nada, nuestra finitud. Nos deja en la Unheimlichkeit, el no-estar-en-casa en el mundo.",
    },
    {
      type: "info",
      title: "Resolución y \"mi-idad\"",
      body: "Heidegger no ofrece ningún incentivo cómodo para elegir la autenticidad: la describe en Ser y tiempo como una condición dura, incluso miserable, aunque resulta evidente que le parece más admirable que la vida inauténtica. Pero la muerte, precisamente porque cada quien la enfrenta en soledad —nadie puede morir la muerte de otro—, **individualiza**: es el único momento de auténtica **Jemeinigkeit**, de \"mi-idad\", lo que le pertenece a cada Dasein sin poder ser compartido ni delegado.",
    },
    {
      type: "info",
      continues: true,
      title: "Resolución y \"mi-idad\"",
      body: "Ser sacudido por la angustia puede llevar, entonces, a la **resolución** (Entschlossenheit), a tomar posesión de la propia existencia y asumir la responsabilidad de las elecciones que la definen. Aunque sea una condición miserable, y hasta heroica, tiene también un costado que empodera: al quedar a solas frente a la propia muerte, la angustia puede volverse el punto de partida de una vida decidida en primera persona. Ese será, de aquí en más, el gran tema del existencialismo: la responsabilidad por las propias elecciones, el elegirse a uno mismo y elegir cómo se va a ser en el mundo.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del modo auténtico o del inauténtico?",
      groups: ["Auténtico", "Inauténtico"],
      items: [
        { text: "Encara la propia muerte con los ojos abiertos", group: 0 },
        { text: "Cede la decisión a «lo que se hace»", group: 1 },
        { text: "Asume la responsabilidad de sus elecciones", group: 0 },
        { text: "Se pierde en la habladuría y lo trivial", group: 1 },
        { text: "La angustia lo sacude a la resolución", group: 0 },
        { text: "Se disuelve en el «se» impersonal (das Man)", group: 1 },
      ],
      explain: "El modo inauténtico es conformismo: ceder la decisión al «uno» (das Man), huir en la habladuría, ir con la corriente. El auténtico encara la finitud —el ser-para-la-muerte— y de esa angustia surge la resolución de asumir las propias elecciones. Heidegger dice no juzgar, pero es claro cuál admira.",
    },
    {
      type: "match",
      question: "Uní cada término de Ser y tiempo con lo que nombra",
      pairs: [
        { left: "Dasein", right: "El «ser-ahí»: el ente que puede preguntar por el ser" },
        { left: "Ser-en-el-mundo", right: "Estamos siempre ya en el mundo, sin distancia ni afuera" },
        { left: "Geworfenheit", right: "Estar arrojados a un tiempo y lugar que no elegimos" },
        { left: "Das Man", right: "El «se» impersonal: vivir según lo que se hace" },
        { left: "Sein zum Tode", right: "Ser-para-la-muerte: existir avanzando hacia la nada" },
      ],
      explain: "El vocabulario de Ser y tiempo: el Dasein está siempre ya arrojado (Geworfenheit) al mundo (ser-en-el-mundo); primero y las más de las veces vive inauténtico, disuelto en el «se» (das Man), hasta que la angustia ante el ser-para-la-muerte lo sacude a la autenticidad.",
    },
    {
      type: "info",
      title: "El giro tardío: técnica y lenguaje",
      body: "Tras el fin de la guerra y los años de prohibición de enseñar, el pensamiento de Heidegger se desplaza en lo que sus lectores llaman la **Kehre**, el **giro**. Deja en un segundo plano el vocabulario de Ser y tiempo —Dasein, autenticidad, angustia— y empieza a preguntarse cómo se manifiesta el ser en la época moderna, dominada por la técnica.",
    },
    {
      type: "info",
      continues: true,
      title: "El giro tardío: técnica y lenguaje",
      body: "En La pregunta por la técnica (1954) sostiene que la técnica moderna no es un conjunto neutro de herramientas, sino un modo de que el ser se revele: el **Gestell**, la \"**estructura de emplazamiento**\", que hace aparecer todo —ríos, bosques, incluso a los seres humanos— como **Bestand**, existencia disponible, \"material en reserva\" a explotar. El riesgo no es la técnica en sí misma, sino que ese modo particular de revelación oculte cualquier otro modo posible de relacionarse con el ser.",
    },
    {
      type: "quiz",
      question: "Para el Heidegger tardío, ¿qué hace la técnica moderna (el Gestell) con el mundo?",
      options: [
        "Lo hace aparecer como material disponible a explotar",
        "Lo devuelve a su estado natural, previo a toda técnica",
        "Lo vuelve completamente incomprensible para el Dasein",
        "Lo transforma en un objeto puramente contemplativo",
      ],
      answer: 0,
      explain: "El Gestell, la «estructura de emplazamiento», hace aparecer todo —ríos, bosques, hasta los seres humanos— como Bestand, existencia disponible o «material en reserva» a explotar. El riesgo es que ese modo de revelación oculte cualquier otro.",
    },
    {
      type: "info",
      continues: true,
      title: "El giro tardío: técnica y lenguaje",
      body: "Frente a eso, Heidegger vuelve al **lenguaje** y a la **poesía** —sobre todo a Hölderlin— como el lugar donde el ser todavía puede manifestarse de otro modo. En la Carta sobre el humanismo (1946) escribe que \"el lenguaje es la casa del ser\": no una herramienta que el Dasein usa para comunicarse, sino el medio en el que el ser mismo llega a mostrarse. La actitud que propone frente a la técnica no es rechazarla ni dominarla, sino la **Gelassenheit**, una forma de serenidad o abandono sereno ante lo que no se controla.",
    },
    {
      type: "quiz",
      question: "Frente al dominio de la técnica, ¿qué actitud propone el Heidegger tardío?",
      options: [
        "La Gelassenheit, una serenidad ante lo que no se controla",
        "El rechazo total de toda herramienta y toda máquina",
        "El dominio absoluto de la técnica por la voluntad humana",
        "La resolución angustiada de Ser y tiempo, sin cambios",
      ],
      answer: 0,
      explain: "No propone rechazar la técnica ni dominarla, sino la Gelassenheit, una forma de serenidad o abandono sereno ante lo que no se controla. Vuelve, para eso, al lenguaje y a la poesía como otro modo en que el ser puede manifestarse.",
    },
    {
      type: "info",
      title: "Conclusión: ¿queda un sujeto?",
      body: "La posición privilegiada del Dasein recuerda, en algún punto, a la del ego trascendental husserliano, pero con una diferencia decisiva: mientras que el ego trascendental de Husserl era radicalmente transparente a sí mismo, el Dasein **nunca es transparente**. Siempre está ocupado en algo, cuidando algo, huyendo de algo; partes de sí mismo le permanecen ocultas, y en esto Heidegger queda más cerca de Freud que de Husserl: hay mucha más oscuridad y grisura en la existencia concreta que en el ego trascendental luminoso que Husserl imaginaba.",
    },
    {
      type: "quiz",
      question: "A diferencia del ego trascendental de Husserl, ¿cómo es el Dasein para Heidegger?",
      options: [
        "Nunca es transparente: partes de sí le quedan ocultas",
        "Es tan luminoso y transparente como el ego husserliano",
        "Es un puro objeto, sin ninguna interioridad propia",
        "Es idéntico en todos los casos, sin variación posible",
      ],
      answer: 0,
      explain: "El Dasein nunca es transparente: siempre está ocupado en algo, cuidando algo, huyendo de algo, y partes de sí mismo le permanecen ocultas. En esto Heidegger queda más cerca de Freud que del Husserl del ego trascendental luminoso.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusión: ¿queda un sujeto?",
      body: "Por eso el filósofo francés Paul Ricœur cuenta a Heidegger, junto con Marx, Nietzsche y Freud, entre los \"**maestros de la sospecha**\": pensadores para quienes la nada, la ausencia, la huida y el ocultamiento son parte constitutiva de la condición humana, no accidentes que un método pueda disolver del todo. El momento de claridad, si llega, llega al ser sacudido por la angustia y la Unheimlichkeit, y es tan insoportable que no ofrece, por sí mismo, ningún incentivo para buscarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusión: ¿queda un sujeto?",
      body: "En 1928 Husserl se jubila de su cátedra en Friburgo y arregla que Heidegger lo suceda. Levinas, que estudió con ambos, describió después el peso de esa sucesión: \"su cátedra pasó a Martin Heidegger, su discípulo más original, cuyo nombre es hoy la gloria de Alemania\". Esa misma admiración hace más difícil, después, digerir el rectorado de 1933.",
    },
    {
      type: "match",
      question: "Uní cada término del giro tardío o del diagnóstico inicial con lo que nombra",
      pairs: [
        { left: "Seinsvergessenheit", right: "El olvido de la pregunta por el ser" },
        { left: "Diferencia ontológica", right: "La distinción entre el ser y los entes" },
        { left: "Gestell", right: "La técnica moderna como estructura de emplazamiento" },
        { left: "Bestand", right: "El mundo vuelto material en reserva, disponible" },
        { left: "Gelassenheit", right: "La serenidad ante lo que no se controla" },
      ],
      explain: "Del diagnóstico inicial —la filosofía occidental olvidó la pregunta por el ser, la diferencia ontológica— al giro tardío sobre la técnica: el Gestell revela el mundo como Bestand, material en reserva, y frente a eso Heidegger propone la Gelassenheit.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusión: ¿queda un sujeto?",
      body: "Queda, de todos modos, una pregunta abierta. Una lectura de Heidegger es un engrosamiento radical del sujeto humano en el Dasein: más oscuro, más denso, más existencial que el de Descartes, Kant o Husserl, pero sujeto al fin.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusión: ¿queda un sujeto?",
      body: "La otra lectura es que, una vez que ya no hay distancia entre sujeto y objeto, una vez que el Dasein está siempre ya en el mundo, **ya no queda, en sentido estricto, un sujeto** que pueda desarticularse limpiamente del objeto. El existencialismo francés hereda de Heidegger el vocabulario de la arrojadidad, la angustia y la libertad, pero también esa pregunta sin resolver sobre qué queda, después de todo esto, del sujeto clásico.",
    },
  ],
};
