export default {
  num: 15,
  transcript: 16,
  title: "*El segundo sexo* (Simone de Beauvoir)",
  source: "https://www.youtube.com/watch?v=UZEo2yV9AqI",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Simone de Beauvoir** (1908-1986) nace y muere en París, en el seno de una familia católica de clase alta. Pasa la infancia en el Boulevard Saint-Germain, en el centro de la ciudad. Hacia el final de la Primera Guerra Mundial su padre pierde buena parte de la fortuna familiar: sin dote para casar a las hijas, la vida que se esperaba de ella —matrimonio temprano, hogar burgués— deja de ser la única opción disponible.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Niña precoz y cuestionadora, pierde la fe religiosa en la adolescencia pero conserva de esa educación la idea de **trascendencia**: la posibilidad de cruzar una frontera hacia algo más allá de lo dado. En 1929, a los veintiuno, obtiene la agrégation de filosofía —el examen más exigente del sistema francés— en segundo lugar, detrás de **Jean-Paul Sartre**, siendo la persona más joven en aprobarlo hasta ese momento.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Publica La invitada (1943), su primera novela; Para una moral de la ambigüedad (1947), su tratado de ética existencialista; El segundo sexo (1949), en dos volúmenes; Los mandarines (1954), novela con la que gana el premio Goncourt; y Memorias de una joven formal (1958), el primer tomo de su autobiografía. Enseña filosofía en liceos antes de vivir de la escritura, y en 1945 integra, junto con Sartre y **Maurice Merleau-Ponty**, el comité fundador de la revista Les Temps modernes.",
    },
    {
      type: "quiz",
      question: "En el examen de agrégation de 1929, ¿qué lugar obtiene Beauvoir?",
      options: [
        "Segundo lugar, detrás de Sartre, siendo la más joven",
        "Primer lugar, por delante de Sartre y de todo el resto",
        "Un lugar intermedio, lejos de los primeros puestos",
        "No llega a aprobar el examen en su primer intento",
      ],
      answer: 0,
      explain: "Obtiene el segundo lugar, detrás de Sartre, siendo la persona más joven en aprobar la agrégation hasta ese momento: un examen exigentísimo del sistema francés.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "Beauvoir escribe con dos herramientas tomadas de otros: el existencialismo de Sartre y la lectura francesa de Hegel. De Sartre —a quien conoce en 1929 y con quien mantiene, hasta la muerte de él en 1980, una relación abierta y una conversación filosófica permanente— toma la distinción entre el **en-sí** (la cosa, que simplemente es) y el **para-sí** (la conciencia, que se hace a sí misma eligiendo).",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "De ahí también la idea de que existir es cargar con una libertad de la que no se puede abdicar sin caer en la **mala fe** (mauvaise foi): la mentira que uno se dice a sí mismo para no asumir esa libertad. Sartre había resumido el principio en una fórmula de 1946: **la existencia precede a la esencia**; nada en la naturaleza humana decide de antemano lo que alguien debe ser. Beauvoir aplica exactamente ese principio al caso de la mujer.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "De Hegel, y en particular de la **dialéctica del amo y el esclavo** de la Fenomenología del espíritu, toma la tesis de que ninguna conciencia se reconoce a sí misma en soledad: necesita ser reconocida por otra. Beauvoir combina ambas herencias para preguntar qué ocurre cuando, en esa lucha por el reconocimiento, un grupo entero queda fijado en el lugar del objeto y nunca alcanza a ser sujeto reconocido.",
    },
    {
      type: "quiz",
      question: "¿Qué principio sartreano aplica Beauvoir directamente al caso de la mujer?",
      options: [
        "Que la existencia precede a la esencia también en ella",
        "Que la esencia femenina antecede a toda su existencia",
        "Que sólo el hombre puede ejercer la libertad radical",
        "Que la mala fe es un rasgo exclusivamente femenino",
      ],
      answer: 0,
      explain: "Sartre: la existencia precede a la esencia, nada en la naturaleza humana decide de antemano lo que alguien debe ser. Beauvoir aplica exactamente ese principio al caso de la mujer: no hay una esencia femenina previa a su existencia.",
    },
    {
      type: "info",
      title: "Kojève y la lectura francesa de Hegel",
      body: "La vía por la que Hegel llega a este círculo no es directa: pasa por **Alexandre Kojève** (1902-1968), filósofo nacido en Moscú que dicta en París, entre 1933 y 1939, un seminario sobre la Fenomenología del espíritu que se vuelve legendario y se publica después, en 1947, como Introducción a la lectura de Hegel.",
    },
    {
      type: "info",
      continues: true,
      title: "Kojève y la lectura francesa de Hegel",
      body: "Kojève lee a Hegel con Heidegger de fondo: sostiene que el hombre nunca está frente a un mundo neutro, sino frente a **lo dado** (le donné), algo ya cargado de sentido antes de que lo pensemos. Lo humano es **negación de lo dado**: la capacidad de no conformarse con lo que hay, de actuar para transformarlo. Esa negatividad, para Kojève, es la libertad misma.",
    },
    {
      type: "info",
      continues: true,
      title: "Kojève y la lectura francesa de Hegel",
      body: "De ahí extrae su lectura del amo y el esclavo: en su origen, ningún ser humano es simplemente humano, es siempre o amo o esclavo, porque la autoconciencia sólo se constituye reconociéndose en otra conciencia. El amo, que arriesgó la vida en la lucha, obtiene un reconocimiento vacío, porque proviene de alguien a quien no reconoce como igual. Esta lectura, que en Hegel es un momento entre otros de la Fenomenología, se vuelve en Kojève la clave de toda la historia humana, y es la que Beauvoir traslada a la relación entre hombres y mujeres.",
    },
    {
      type: "info",
      continues: true,
      title: "Kojève y la lectura francesa de Hegel",
      body: "Sartre mismo había usado el par en-sí/para-sí y la categoría de la Mirada del Otro sin extenderlos sistemáticamente al problema del género: en El ser y la nada (1943) el Otro que me objetiva es, por defecto, un otro sin sexo marcado. Beauvoir toma exactamente ese andamiaje y pregunta qué ocurre cuando esa relación de mirada y objetivación se organiza, de modo estructural y no ocasional, entre hombres y mujeres.",
    },
    {
      type: "quiz",
      question: "Para Kojève, ¿en qué consiste lo específicamente humano frente a lo dado?",
      options: [
        "En la negación de lo dado: no conformarse y transformarlo",
        "En la aceptación pasiva y total de todo lo dado por el mundo",
        "En la contemplación desinteresada de lo dado, sin acción",
        "En la reducción de lo dado a puras leyes naturales",
      ],
      answer: 0,
      explain: "Lo humano es negación de lo dado (le donné): la capacidad de no conformarse con lo que hay, de actuar para transformarlo. Esa negatividad, para Kojève, es la libertad misma, y es la lectura que Beauvoir hereda de él.",
    },
    {
      type: "info",
      title: "La ética de la ambigüedad",
      body: "En Para una moral de la ambigüedad, Beauvoir da la formulación más clara de su ética. Trabaja contra dos determinismos: el de Marx, a quien admira pero cuya teleología histórica le deja poco margen a la elección individual, y el de Heidegger, de quien toma la aceptación de la **finitud** —somos seres para la muerte— como el marco dentro del cual toda decisión ocurre.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética de la ambigüedad",
      body: "Su tesis central es que el ser humano es, antes que nada, **negatividad**: una falta, un vacío que no puede llenarse con ninguna esencia dada de antemano, y que por eso mismo es la condición de posibilidad de crear valores. No hay valores fuera de esa creación humana. Como escribe, es siempre sobre la base de lo que ha sido que alguien decide lo que quiere ser: no se elige desde una hoja en blanco, sino desde una **facticidad** —un cuerpo, una historia, una situación— que la libertad no anula sino que asume.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética de la ambigüedad",
      body: "Esa posición se condensa en dos fórmulas suyas muy citadas. La primera define la ética como una conquista y no como un punto de partida. La segunda niega que libertad y moral sean términos en tensión, como si ser libre consistiera en librarse de toda obligación hacia los demás.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética de la ambigüedad",
      body: "La ética es el triunfo de la libertad sobre la facticidad.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética de la ambigüedad",
      body: "La segunda de esas fórmulas lo dice sin rodeos:",
    },
    {
      type: "info",
      continues: true,
      title: "La ética de la ambigüedad",
      body: "Quererse moral y quererse libre son una y la misma decisión.",
    },
    {
      type: "info",
      continues: true,
      title: "La ética de la ambigüedad",
      body: "La ética, para Beauvoir, presupone el fracaso: la vida está hecha de dilemas sin salida limpia, de situaciones en que no hay una elección inocente. Esa es la textura de toda decisión real, y también la textura de la novela con la que trabaja simultáneamente el mismo problema.",
    },
    {
      type: "quiz",
      question: "Para Beauvoir, ¿qué es el ser humano antes que nada?",
      options: [
        "Negatividad: un vacío sin esencia previa que crea valores",
        "Una esencia biológica fija que antecede a toda libertad",
        "Pura facticidad, sin ningún margen real para decidir",
        "Una síntesis final y estable entre libertad y necesidad",
      ],
      answer: 0,
      explain: "El ser humano es, antes que nada, negatividad: una falta que no puede llenarse con ninguna esencia dada de antemano, y que por eso es la condición de posibilidad de crear valores. No hay valores fuera de esa creación humana.",
    },
    {
      type: "info",
      title: "Los mandarines y el dilema de la posguerra",
      body: "Los mandarines (1954) es una novela con clave autobiográfica sobre el círculo de Sartre, Camus y Beauvoir en los años de la Liberación: los ajustes de cuentas con quienes colaboraron con Vichy, y sobre todo el dilema del **apoyo a la Unión Soviética**, cuando las alternativas parecían ser el fascismo derrotado o el estalinismo triunfante. Un personaje inspirado en Camus resume la apología del comunismo de esos años: frente a masas embrutecidas por la miseria, tratarlas \"como hombres\" es antes que nada alimentarlas, y perderse en un partido colectivo ofrece una paz que la libertad individual no da.",
    },
    {
      type: "info",
      continues: true,
      title: "Los mandarines y el dilema de la posguerra",
      body: "Los viajes de Beauvoir a Estados Unidos en esos años —y su relación con el escritor Nelson Algren, en Chicago— le dan un conocimiento directo de las relaciones raciales estadounidenses que no tenía. A partir de ahí piensa **tres casos del Otro** en paralelo: los judíos en la Europa del Holocausto, los negros en Estados Unidos, y las mujeres. Ese cruce comparativo, más que cualquier otra cosa, es el punto de partida de El segundo sexo.",
    },
    {
      type: "quiz",
      question: "¿Qué tres casos del Otro compara Beauvoir a partir de sus viajes a Estados Unidos?",
      options: [
        "Judíos en el Holocausto, negros en EE. UU. y mujeres",
        "Obreros, campesinos y burgueses de la posguerra europea",
        "Colonizados, prisioneros de guerra y exiliados políticos",
        "Niños, ancianos y personas con alguna discapacidad",
      ],
      answer: 0,
      explain: "A partir de su conocimiento directo de las relaciones raciales estadounidenses, piensa tres casos del Otro en paralelo: los judíos en la Europa del Holocausto, los negros en Estados Unidos, y las mujeres. Ese cruce es el punto de partida de El segundo sexo.",
    },
    {
      type: "info",
      title: "El segundo sexo (1949)",
      body: "El libro se publica primero por entregas en Les Temps modernes y después en dos volúmenes: Los hechos y los mitos y La experiencia vivida. Tiene implicaciones políticas que se despliegan durante décadas, pero su núcleo es un argumento filosófico que combina fenomenología, existencialismo y la lectura kojeviana de Hegel.",
    },
    {
      type: "info",
      continues: true,
      title: "El segundo sexo (1949)",
      body: "El primer volumen recorre, antes de llegar al argumento propio, las explicaciones que otros discursos habían dado de \"lo femenino\": la biología, el psicoanálisis, el materialismo histórico, y una larga reconstrucción histórica que va de la Antigüedad al Código Napoleónico. La conclusión que saca de ese recorrido es siempre la misma: ninguna de esas claves alcanza por sí sola, y todas describen efectos de una subordinación que ya estaba en marcha, no su causa originaria.",
    },
    {
      type: "info",
      continues: true,
      title: "El segundo sexo (1949)",
      body: "Cierra el volumen con un capítulo sobre los **mitos literarios de la mujer**, donde analiza cómo escritores como Montherlant, D. H. Lawrence, Claudel, Breton y Stendhal proyectan sobre la figura femenina una idealización o una condena que dice más de la angustia masculina frente a lo Otro que de ninguna mujer real. El mito, para Beauvoir, es otra forma de negarle a la mujer el estatuto de sujeto concreto.",
    },
    {
      type: "quiz",
      question: "¿Qué conclusión saca Beauvoir de revisar la biología, el psicoanálisis y el materialismo histórico?",
      options: [
        "Ninguna alcanza sola: describen efectos, no la causa",
        "La biología basta por sí sola para explicar todo",
        "El psicoanálisis es la única clave verdaderamente válida",
        "El materialismo histórico agota el problema por completo",
      ],
      answer: 0,
      explain: "Ninguna de esas claves alcanza por sí sola: todas describen efectos de una subordinación que ya estaba en marcha, no su causa originaria.",
    },
    {
      type: "info",
      title: "Punto de partida fenomenológico",
      body: "Como en Husserl y Heidegger, el punto de partida no es una conciencia abstracta sino un cuerpo situado: estamos siempre ya en el mundo y siempre ya en un cuerpo particular, con una historia y una biología propias. Beauvoir dedica largas descripciones fenomenológicas al cuerpo de la mujer —la pubertad, la menstruación, el embarazo— no para reducir la condición femenina a la biología, sino para mostrar que ninguna filosofía de la libertad puede empezar ignorando la situación corporal concreta desde la que se elige.",
    },
    {
      type: "info",
      continues: true,
      title: "Punto de partida fenomenológico",
      body: "Esa descripción no es una crítica de los hombres como individuos —Beauvoir es explícita en que le gustan los hombres, el deseo y el erotismo—, sino de las instituciones que fijan a la mujer en un lugar subordinado. El **matrimonio** le disgusta como institución; la **maternidad**, tal como la sociedad la organiza, le provoca un rechazo explícito, al punto de llamarla \"un extraño compromiso de narcisismo, altruismo, ensueño, mala fe y devoción\". No es rechazo del deseo ni del vínculo, sino de la forma social que los encierra.",
    },
    {
      type: "info",
      title: "\"¿Qué es una mujer?\" y la Otredad",
      body: "El libro arranca con una pregunta que ya contiene su respuesta: plantearla es significativo, porque nadie pregunta \"¿qué es un hombre?\" del mismo modo. El hombre se presenta como el **tipo absoluto, normativo, sin marca**; \"ser humano\" significa, en los hechos, \"hombre\". La mujer, en cambio, se define siempre de manera relativa y derivada respecto de él.",
    },
    {
      type: "info",
      continues: true,
      title: "\"¿Qué es una mujer?\" y la Otredad",
      body: "Ella se define y se diferencia con relación al hombre, y no éste con relación a ella; ella es lo inesencial frente a lo esencial. Él es el Sujeto, es lo Absoluto; ella es lo Otro.",
    },
    {
      type: "info",
      continues: true,
      title: "\"¿Qué es una mujer?\" y la Otredad",
      body: "Esta es la traducción, al problema del género, de la dialéctica del amo y el esclavo leída por Kojève: no hay autoconciencia sin reconocimiento por otro, y en esa estructura alguien queda fijado del lado del objeto. Beauvoir agrega que la categoría de lo Otro es tan originaria como la conciencia misma: todo grupo dominante necesita un Otro frente al cual definirse —el colonizador frente al colonizado, la burguesía frente a los obreros—, pero en el caso de hombres y mujeres esa relación atraviesa cada célula familiar, y no una frontera entre grupos separados.",
    },
    {
      type: "quiz",
      question: "Según Beauvoir, ¿cómo se presenta el hombre frente a la mujer en el orden simbólico?",
      options: [
        "Como el tipo absoluto y normativo, sin marca alguna",
        "Como una excepción, tan relativa y derivada como ella",
        "Como una figura secundaria frente a la norma femenina",
        "Como un igual estructural, sin jerarquía simbólica",
      ],
      answer: 0,
      explain: "El hombre se presenta como el tipo absoluto, normativo, sin marca: «ser humano» significa, en los hechos, «hombre». La mujer, en cambio, se define siempre de manera relativa y derivada respecto de él: es lo Otro.",
    },
    {
      type: "info",
      title: "No se nace mujer, se llega a serlo",
      body: "La tesis que resume el segundo volumen es la más citada del libro: **no se nace mujer, se llega a serlo**. Ningún destino biológico, psíquico o económico determina la figura que asume la hembra humana en la sociedad; es el conjunto de la civilización el que produce ese producto intermedio entre el macho y el castrado que se llama \"femenino\". Con esto Beauvoir no niega el cuerpo —lo describe con detalle— sino la idea de que el cuerpo dicte por sí solo un destino social.",
    },
    {
      type: "quiz",
      question: "¿Cuál es la frase más citada de El segundo sexo sobre la construcción de lo femenino?",
      options: [
        "No se nace mujer: se llega a serlo",
        "Se nace mujer: la biología decide el destino",
        "No se nace mujer: se elige serlo",
        "Se nace y se sigue siendo mujer siempre",
      ],
      answer: 0,
      explain: "No se nace mujer, se llega a serlo: ningún destino biológico, psíquico o económico determina la figura que asume la mujer en la sociedad; es el conjunto de la civilización el que produce ese lugar llamado «femenino».",
    },
    {
      type: "info",
      title: "La diferencia irreductible",
      body: "Beauvoir marca, sin embargo, un límite a la analogía con otras formas de otredad. A diferencia de la relación entre colonizador y colonizado, o entre clases, la división entre los sexos es, para ella, un dato biológico y no sólo un acontecimiento de la historia humana:",
    },
    {
      type: "info",
      continues: true,
      title: "La diferencia irreductible",
      body: "El vínculo que la une a su opresor no es comparable a ningún otro. La división de los sexos es un hecho biológico, no un acontecimiento de la historia humana.",
    },
    {
      type: "info",
      continues: true,
      title: "La diferencia irreductible",
      body: "El punto que le importa no es una esencia femenina, sino un hecho concreto: una mujer puede quedar embarazada y un hombre no, y esa vulnerabilidad no la hace desaparecer ningún cambio de costumbres. De ahí la centralidad, para ella, de la anticoncepción y del control sobre la propia reproducción como condición material de cualquier libertad femenina.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue, para Beauvoir, a la relación entre los sexos de otras formas de otredad?",
      options: [
        "Es también un hecho biológico, no sólo histórico",
        "Es puramente un acontecimiento cultural, sin base física",
        "No implica ninguna forma real de opresión concreta",
        "Se resuelve igual que la relación entre clases sociales",
      ],
      answer: 0,
      explain: "A diferencia del colonizador y el colonizado, o de las clases, la división entre los sexos es también un dato biológico, no sólo un acontecimiento de la historia humana: una mujer puede quedar embarazada y un hombre no.",
    },
    {
      type: "info",
      title: "El reconocimiento aplicado al género",
      body: "Retomando a Kojève, Beauvoir sostiene que un ser humano sólo es plenamente humano para sí y para los demás cuando es reconocido por otro. El drama de la relación entre los sexos es que el hombre necesita ese reconocimiento de la mujer, pero la ha reducido de antemano a objeto, y el reconocimiento de un objeto no satisface a nadie: hace falta el de un sujeto libre.",
    },
    {
      type: "info",
      continues: true,
      title: "El reconocimiento aplicado al género",
      body: "El amo, dice Kojève, nunca es simplemente un hombre: es siempre amo o esclavo. Beauvoir traslada esa estructura al vínculo entre los sexos: el rasgo básico atribuido a \"lo femenino\" es ser el Otro dentro de una totalidad cuyos dos términos, en rigor, se necesitan mutuamente para existir como tales.",
    },
    {
      type: "info",
      title: "Contra el reduccionismo: Marx y Freud",
      body: "Beauvoir toma en serio el marxismo y el psicoanálisis, las dos grandes teorías que en su época pretendían explicar la condición femenina, y a ambas las encuentra insuficientes.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el reduccionismo: Marx y Freud",
      body: "Contra el marxismo, objeta que reduce la opresión de la mujer a la propiedad privada y al conflicto de clases, cuando la relación entre los sexos no se deja derivar por completo de la estructura económica. Eso no significa que la propiedad y la desigualdad de clase no importen: significa que no alcanzan para explicar por qué la mujer es, específicamente, lo Otro. Además, el materialismo racionalista ignora la sexualidad: hay en el erotismo, escribe, \"una revuelta del instante contra el tiempo, del individuo contra lo universal\" que ninguna teoría puramente económica puede absorber.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra el reduccionismo: Marx y Freud",
      body: "Contra Freud, objeta el determinismo de fondo: reducir toda la vida psíquica a Eros, Tánatos y la represión deja afuera la elección existencial. La sexualidad importa —Beauvoir no la subestima—, pero la mujer, como cualquier sujeto, elige entre afirmar su trascendencia y refugiarse en el papel de objeto; no es el juguete pasivo de pulsiones que se le imponen desde afuera. Es escéptica, en particular, del valor que el psicoanálisis freudiano atribuye al falo como centro explicativo de la diferencia sexual.",
    },
    {
      type: "classify",
      question: "¿Cada objeción de Beauvoir apunta a Marx o a Freud?",
      groups: ["Objeción a Marx", "Objeción a Freud"],
      items: [
        { text: "Reduce la opresión a la propiedad privada y la clase", group: 0 },
        { text: "Reduce la vida psíquica a Eros, Tánatos y represión", group: 1 },
        { text: "Ignora la sexualidad y el erotismo como fuerza propia", group: 0 },
        { text: "Deja afuera la elección existencial de cada sujeto", group: 1 },
        { text: "No explica por qué la mujer es, específicamente, lo Otro", group: 0 },
        { text: "Da un valor excesivo al falo como centro explicativo", group: 1 },
      ],
      explain: "A Marx le objeta que la propiedad y la clase no bastan para explicar por qué la mujer es lo Otro, ni dan lugar a la sexualidad. A Freud, el determinismo que reduce todo a pulsiones y deja afuera la elección existencial.",
    },
    {
      type: "info",
      title: "Inmanencia, trascendencia y mala fe",
      body: "Beauvoir usa **inmanencia** y **trascendencia** de un modo cercano al en-sí y el para-sí de Sartre. La inmanencia es la vida encerrada en la repetición, en la facticidad, en lo dado; la trascendencia es la acción que transforma el mundo y proyecta hacia adelante. La pregunta que atraviesa el libro es si las mujeres pueden liberarse de la inmanencia a la que las instituciones las confinan y reclamar la trascendencia que, en la estructura patriarcal, queda reservada al hombre.",
    },
    {
      type: "info",
      continues: true,
      title: "Inmanencia, trascendencia y mala fe",
      body: "Pero Beauvoir no exime a las mujeres de responsabilidad: sostiene que ellas también pueden vivir en mala fe, aceptando el rol de objeto porque es más cómodo que asumir la propia libertad. Como escribe, si la mujer parece ser lo inesencial que nunca llega a ser esencial, es en parte porque ella misma no lleva a cabo el cambio que la volvería sujeto. La opresión y la renuncia a la libertad, aquí como en toda su ética, no se excluyen: la primera hace más difícil la segunda, pero no la vuelve imposible.",
    },
    {
      type: "info",
      continues: true,
      title: "Inmanencia, trascendencia y mala fe",
      body: "Igualdad, para Beauvoir, no significa identidad: no propone borrar el deseo, el erotismo ni las diferencias entre hombres y mujeres, sino fundarlos en el reconocimiento recíproco entre sujetos libres, y no en la fijación de uno de los dos términos en el lugar del objeto.",
    },
    {
      type: "match",
      question: "Repaso: uní cada término de Beauvoir con lo que nombra",
      pairs: [
        { left: "Kojève", right: "Lectura de Hegel: lo humano es negación de lo dado" },
        { left: "Inmanencia", right: "La vida encerrada en la repetición y lo dado" },
        { left: "Trascendencia", right: "La acción que transforma el mundo hacia adelante" },
        { left: "Lo Otro", right: "El lugar relativo y derivado que ocupa la mujer" },
        { left: "«No se nace mujer...»", right: "Se llega a serlo por obra de la civilización" },
      ],
      explain: "De Kojève hereda la negatividad como libertad; inmanencia y trascendencia son los polos entre los que se juega la libertad femenina; lo Otro nombra el lugar simbólico de la mujer, y la fórmula final resume que ese lugar se construye, no nace.",
    },
    {
      type: "info",
      title: "Cierre: reciprocidad y herencia",
      body: "El libro no termina en la reconciliación hegeliana de una síntesis final, pero sí en un tono más esperanzado que resignado: no promete que la libertad recíproca entre los sexos vaya a ocurrir, pero afirma que es posible. Cuando la mitad de la humanidad deje de estar sometida a la otra, escribe, la propia división entre los sexos podrá revelar por fin su sentido genuino, liberada del sistema de hipocresías que hoy la sostiene.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: reciprocidad y herencia",
      body: "El argumento final de Beauvoir es que mantener a la mujer en el lugar de objeto también encierra al hombre: el que necesita sentirse viril, superior e indispensable gasta una energía enorme en sostener ese personaje, y teme la libertad de la mujer porque teme, en el fondo, tomar posesión de la suya propia. La liberación de uno de los dos términos, en esta lectura, no resta libertad al otro: la hace posible.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: reciprocidad y herencia",
      body: "El segundo sexo circula primero en Francia entre polémicas —el Vaticano lo incluye en su índice de libros prohibidos— y llega con fuerza a Estados Unidos en los años sesenta, donde alimenta el feminismo de la llamada segunda ola: Betty Friedan lo cuenta entre las lecturas que la llevan a escribir La mística de la feminidad (1963), y autoras como Kate Millett lo retoman como fundamento filosófico del argumento de que \"lo personal es político\".",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: reciprocidad y herencia",
      body: "Décadas después, Judith Butler parte explícitamente de la fórmula \"no se nace mujer, se llega a serlo\" para su propia teoría de la identidad de género como algo performativo y no dado de antemano. La discusión que Butler abre es, en el fondo, la que Beauvoir misma había dejado pendiente: si la diferencia sexual biológica es de verdad irreductible, o si también ella es, hasta el fondo, un modo más en que \"se llega a ser\".",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: reciprocidad y herencia",
      body: "La propia Beauvoir no se queda en la sola escritura filosófica: en 1971 encabeza el Manifiesto de las 343, la declaración pública de mujeres que admiten haber abortado —entonces un delito en Francia— para forzar el debate sobre la legalización, y se vincula en esos años con el movimiento de liberación de las mujeres que el libro, veinte años antes, había contribuido a hacer posible.",
    },
  ],
};
