export default {
  num: 4,
  transcript: 5,
  title: "El marxismo",
  source: "https://www.youtube.com/watch?v=bdB0Lsa5T-g",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Karl Marx** (1818-1883) nace en Tréveris, en el Rin prusiano, en una familia judía asimilada con una larga línea de rabinos por ambas ramas; su padre se convierte al protestantismo por razones profesionales. Estudia derecho y después filosofía en Berlín, donde se acerca al círculo de los hegelianos de izquierda.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En 1843 se instala en París, donde al año siguiente conoce a **Friedrich Engels**: a partir de ese encuentro producen juntos buena parte de su obra. Expulsado de varios países, se instala en Londres en 1849, donde vive el resto de su vida investigando en la biblioteca del Museo Británico mientras la pobreza familiar le cuesta la vida a varios de sus hijos.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Vive casi siempre de la ayuda económica de Engels, cuya familia posee fábricas textiles en Manchester: el teórico de la explotación del proletariado depende, para poder escribir, de las ganancias de un capitalista industrial que es al mismo tiempo su amigo y coautor. Es una paradoja que él mismo no ignora, y que dice mucho sobre las condiciones materiales, nunca puramente intelectuales, en que se produce la teoría.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Su obra se divide en dos momentos que van a resultar centrales para este apunte. Los Manuscritos económico-filosóficos, escritos en 1844 pero publicados recién en el siglo XX, y La ideología alemana (con Engels, 1845-46, también póstuma) pertenecen al Marx joven, de vocabulario todavía filosófico y humanista. El Manifiesto del Partido Comunista (con Engels, 1848) es la bisagra política. El capital —tomo I en 1867, el único que llega a publicar; los tomos II y III los arma Engels después de su muerte, en 1885 y 1894— es la obra madura, sistemática y económica.",
    },
    {
      type: "info",
      title: "El problema que hereda: la dialéctica hegeliana",
      body: "Marx llega a la filosofía casi cincuenta años después de Hegel, y toma de él el punto de partida más amplio: **todo es relacional**. Nada puede entenderse aislado de otros elementos; todo tiene sentido sólo en el contexto del todo, y nada es nunca simplemente idéntico a sí mismo. La historia se mueve a través de choques y antagonismos: todo estado de cosas contiene en sí las semillas de su propia superación, como el pimpollo contiene la semilla del fruto que lo reemplazará.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la dialéctica hegeliana",
      body: "De ahí también hereda la desconfianza hegeliana hacia la **reificación**: convertir en cosa fija y separada algo que sólo existe en relación con un todo. Lo verdadero y lo falso, para Hegel, no pueden aislarse el uno del otro; están siempre mutuamente implicados. Y hereda la idea de que la historia es **irreversible**, que no hay vuelta atrás una vez que algo sucedió, y que se despliega en espiral, a saltos, hacia una reconciliación final.",
    },
    {
      type: "quiz",
      question: "«Reificar» quiere decir…",
      options: [
        "volver cosa fija algo que es relacional",
        "exagerar la importancia de una idea abstracta",
        "explicar un hecho por sus causas materiales",
        "repetir un argumento sin volver a examinarlo",
      ],
      answer: 0,
      explain: "Para Marx nada existe aislado ni es idéntico a sí mismo: por eso después va a tratar categorías como el salario o la propiedad privada, que la economía política ve como datos fijos y naturales, como relaciones históricas concretas.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la dialéctica hegeliana",
      body: "Esa misma sospecha frente a la reificación es la que Marx va a aplicar después a categorías que la economía política de su tiempo trata como si fueran cosas naturales y eternas: el salario, la propiedad privada, el mercado. Donde el economista clásico ve datos fijos de cualquier sociedad posible, Marx va a ver relaciones históricas concretas, propias de un momento determinado del desarrollo humano y no de la naturaleza humana en general.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la dialéctica hegeliana",
      body: "Ese telos final —el punto en que sujeto y objeto, hecho y valor, libertad y necesidad se funden— queda deliberadamente vago en Hegel. Marx va a especificarlo con toda precisión: no es un estado del Espíritu, sino una organización concreta de la producción y la propiedad. Entender qué volvió tan seductora esta promesa de un sentido total de la historia, para tantísima gente y durante tanto tiempo, no implica que Marx tuviera razón, pero es indispensable para entender el siglo que sigue.",
    },
    {
      type: "info",
      title: "Del idealismo al materialismo histórico",
      body: "Lo que los hegelianos de izquierda —Marx en particular— retienen de Hegel es la centralidad de la historia y su movimiento por antítesis y conflicto; lo que rechazan es su interpretación **metafísica**. Hay que tomar todo lo que en Hegel existe en el reino del Espíritu, de la idea, y bajarlo a la tierra: volverlo concreto, específico, material. Donde Hegel ve el despliegue de una idea, Marx ve el despliegue de las fuerzas y relaciones de producción.",
    },
    {
      type: "quiz",
      question: "¿Qué le conservan a Hegel los hegelianos de izquierda?",
      options: [
        "la dialéctica y la centralidad de la historia",
        "la metafísica del Espíritu como fundamento",
        "la confianza en el Estado como fin del proceso",
        "la idea de que la filosofía debe ser atemporal",
      ],
      answer: 0,
      explain: "El acuerdo es sobre la forma del movimiento —antagonismo, conflicto, historia como proceso—; el desacuerdo es sobre dónde ocurre: Marx baja todo eso a la tierra y lo llama materialismo histórico.",
    },
    {
      type: "info",
      continues: true,
      title: "Del idealismo al materialismo histórico",
      body: "En el prefacio a su Contribución a la crítica de la economía política (1859), Marx resume esa operación con el nombre que se le va a quedar: la **concepción materialista de la historia**, el materialismo histórico. No es la conciencia de los hombres la que determina su ser social, sino al revés: su ser social —su lugar en la producción— es lo que determina su conciencia. Todo lo que en Hegel era abstracto, en Marx se vuelve concreto y verificable.",
    },
    {
      type: "short",
      question: "¿Cómo llama Marx a su interpretación de la historia en el prefacio de 1859?",
      answers: ["materialismo histórico"],
      explain: "No es la conciencia la que determina el ser social, sino al revés: el lugar de cada quien en la producción es lo que determina su conciencia. Todo lo abstracto en Hegel se vuelve, así, concreto y verificable.",
    },
    {
      type: "info",
      title: "De la aldea a la fábrica: industrialización y nuevas clases",
      body: "Para Marx, el factor decisivo del mundo moderno es la **industrialización**, algo ligado a que trabaja y escribe en Alemania, París y Londres, donde la Revolución Industrial ya está en marcha, aunque a mediados del siglo XIX la mayor parte del mundo —incluida buena parte de Europa— todavía no está industrializada. Por eso conviene distinguir la modernidad como período de la **modernización**, el conjunto concreto y técnico de cambios que trae consigo la industria.",
    },
    {
      type: "info",
      continues: true,
      title: "De la aldea a la fábrica: industrialización y nuevas clases",
      body: "El mundo anterior era el **feudalismo**: descentralizado, agrario, con una nobleza que hereda propiedad y riqueza y un campesinado —antes siervo— atado a la tierra y al ciclo de las estaciones. La fábrica cambia esa estructura de raíz: quienes las construyen y poseen forman la **burguesía**, una clase que no hereda título ni fortuna sino que posee los medios de producción; quienes venden su trabajo por hora en ellas forman el **proletariado**, la nueva clase obrera urbana.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al feudalismo o al capitalismo industrial?",
      groups: ["Feudalismo", "Capitalismo industrial"],
      items: [
        { text: "La nobleza hereda título y propiedad", group: 0 },
        { text: "El campesinado atado a la tierra y las estaciones", group: 0 },
        { text: "Estructura descentralizada y agraria", group: 0 },
        { text: "La burguesía posee los medios de producción", group: 1 },
        { text: "El proletariado vende su trabajo por hora", group: 1 },
        { text: "La fábrica concentra a los trabajadores bajo un patrón", group: 1 },
      ],
      explain: "La fábrica reordena de raíz la vieja estructura agraria: ya no importa la sangre ni la tierra heredada, sino quién posee los medios de producción y quién vende su fuerza de trabajo.",
    },
    {
      type: "info",
      continues: true,
      title: "De la aldea a la fábrica: industrialización y nuevas clases",
      body: "La tecnología es lo que hace posible ese vuelco: permite construir fábricas y producir a una escala y una velocidad que ningún artesano individual, por hábil que sea, puede igualar trabajando solo con sus manos y sus herramientas. Eso obliga a concentrar a mucha gente en un mismo edificio, bajo un mismo patrón, y esa concentración misma —antes dispersa en talleres familiares y aldeas— es la que crea de la nada una clase social nueva y numerosa.",
    },
    {
      type: "info",
      continues: true,
      title: "De la aldea a la fábrica: industrialización y nuevas clases",
      body: "Con la fábrica llega también un cambio en la relación con el tiempo y el espacio del trabajo. Quien antes trabajaba la tierra estaba ligado a un ciclo que no controlaba pero que al menos podía seguir de principio a fin: sembrar, cuidar, ver crecer la planta, cosechar. En la fábrica, en cambio, se vende el propio tiempo por hora, y la tarea suele reducirse a una operación repetida sin fin en una **línea de montaje**, donde cada trabajador ejecuta sólo una parte mínima del proceso completo.",
    },
    {
      type: "info",
      title: "Alienación del trabajo",
      body: "Los Manuscritos de 1844 describen esa condición con el concepto de **alienación** (Entfremdung), en cuatro registros que se implican entre sí. El trabajador está alienado del **producto** de su trabajo, que pertenece a otro; de su propia **actividad productiva**, reducida a una tarea repetitiva en una línea de montaje; de su **ser genérico** (Gattungswesen), la capacidad creativa colectiva que para Marx define lo humano; y, en consecuencia, de **los demás**, con quienes ya no se relaciona sino a través del mercado de trabajo.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la separación entre el trabajador y lo que produce?",
      answers: ["alienación", "enajenación"],
      explain: "El obrero ya no está conectado a la totalidad de sembrar y cosechar, o de hacer el zapato de principio a fin: hace sólo una parte, para otro, y las ganancias van al dueño de la fábrica.",
    },
    {
      type: "info",
      continues: true,
      title: "Alienación del trabajo",
      body: "Es un trabajador deshumanizado, vendido por hora, sometido al ritmo de las máquinas: distinto del artesano de aldea que hace el zapato de principio a fin y se reconoce en su obra. Las ganancias de lo producido van a los dueños de la fábrica, no a quien lo produce.",
    },
    {
      type: "info",
      continues: true,
      title: "Alienación del trabajo",
      body: "De las cuatro formas de alienación, la del ser genérico es la que exige más comentario, porque es la más filosófica y la más ligada al humanismo del que parte Marx. Para él, lo que distingue a la especie humana de cualquier otro animal es la capacidad de transformar la naturaleza de manera libre y consciente, más allá de lo estrictamente necesario para sobrevivir: producir no sólo por necesidad inmediata, sino también, por ejemplo, \"según las leyes de la belleza\".",
    },
    {
      type: "info",
      continues: true,
      title: "Alienación del trabajo",
      body: "El trabajo fabril, reducido a la repetición de un gesto mínimo, cancela precisamente esa capacidad: la actividad que debería expresar lo más propiamente humano se vuelve indistinguible del funcionamiento de una máquina.",
    },
    {
      type: "match",
      question: "Uní cada forma de alienación con lo que describe",
      pairs: [
        { left: "Alienación del producto", right: "El objeto fabricado pertenece a otro, no a quien lo hizo" },
        { left: "Alienación de la actividad", right: "El trabajo se reduce a una tarea repetitiva y ajena" },
        { left: "Alienación del ser genérico", right: "Se pierde la capacidad libre y creativa de transformar la naturaleza" },
        { left: "Alienación de los demás", right: "El vínculo con otros pasa sólo por el mercado de trabajo" },
      ],
      explain: "Los Manuscritos de 1844 describen la alienación en estos cuatro registros, que se implican entre sí: perder el producto, la actividad, la propia naturaleza humana y el vínculo con los otros.",
    },
    {
      type: "info",
      continues: true,
      title: "Alienación del trabajo",
      body: "Este vocabulario de la alienación —filosófico, casi existencial— es el sello del Marx joven, todavía heredero del humanismo de **Ludwig Feuerbach**, quien había sostenido, poco antes, que Dios no es más que la proyección invertida de las mejores cualidades humanas puestas fuera del hombre y adoradas como ajenas. Marx traslada ese mismo esquema —algo propio del hombre que se le escapa y se le vuelve ajeno— del terreno de la religión al terreno del trabajo y la economía.",
    },
    {
      type: "info",
      title: "Manifiesto Comunista (1848)",
      body: "El Manifiesto, publicado en febrero de 1848 —la llamada \"primavera de los pueblos\", un año de revoluciones en toda Europa donde liberalismo y nacionalismo confluyen—, condensa tres influencias: el pensamiento ilustrado de los derechos del hombre, la filosofía romántica alemana —sobre todo Hegel— y la economía política de la industrialización.",
    },
    {
      type: "quiz",
      question: "El Manifiesto se vuelve inteligible cruzando tres tradiciones:",
      options: [
        "Ilustración, filosofía alemana y economía política",
        "Ilustración, romanticismo inglés y darwinismo social",
        "cristianismo primitivo, jacobinismo y anarquismo",
        "positivismo, nacionalismo y liberalismo económico",
      ],
      answer: 0,
      explain: "Los derechos del hombre vienen del pensamiento ilustrado; la historia con mayúscula, de Hegel y la filosofía romántica alemana; y la lectura de la industrialización, de la economía política. Aparece en 1848, el año de la primavera de los pueblos.",
    },
    {
      type: "info",
      continues: true,
      title: "Manifiesto Comunista (1848)",
      body: "Su primer movimiento es \"**poner a Hegel patas para arriba**\": no invertir el sentido de la historia, sino pasar del reino de lo ideal al de lo material, de lo abstracto y metafísico a lo concreto. En lugar del Geist, Marx ve **fuerzas socioeconómicas**. Engels lo resume diciendo que la dialéctica hegeliana estaba parada de cabeza y hay que ponerla sobre sus pies; Marx repite la imagen en el epílogo a la segunda edición alemana de El capital:",
    },
    {
      type: "classify",
      question: "¿Cada afirmación corresponde a Hegel o a Marx?",
      groups: ["Hegel", "Marx"],
      items: [
        { text: "El motor de la historia es el Geist", group: 0 },
        { text: "La dialéctica se mueve en el reino de la idea", group: 0 },
        { text: "El telos queda descrito en términos vagos", group: 0 },
        { text: "El motor son las fuerzas socioeconómicas", group: 1 },
        { text: "A la dialéctica hay que pararla sobre sus pies", group: 1 },
        { text: "El final de la historia se describe muy concretamente", group: 1 },
      ],
      explain: "Poner a Hegel patas para arriba no es hacer retroceder la historia: es mudarla del cielo de la metafísica al suelo de lo concreto, del Espíritu a la organización de la producción y la propiedad.",
    },
    {
      type: "info",
      continues: true,
      title: "Manifiesto Comunista (1848)",
      body: "La mistificación que la dialéctica sufre en manos de Hegel no impide en absoluto que haya sido el primero en exponer de manera amplia y consciente sus formas generales de movimiento. En él la dialéctica está parada de cabeza; hay que darla vuelta para descubrir el núcleo racional dentro de la envoltura mística.",
    },
    {
      type: "info",
      continues: true,
      title: "Manifiesto Comunista (1848)",
      body: "El Manifiesto es a la vez teoría de la historia, programa político y profecía, sin distinguir entre lo que sucederá y lo que debería suceder —un rasgo que hereda directamente de Hegel—. Empieza con la línea \"un espectro recorre Europa: el espectro del comunismo\": un Gespenst, un fantasma, y no del pasado sino del futuro. Los actores de esta historia no son individuos sino **clases**, definidas por su relación con los medios de producción.",
    },
    {
      type: "info",
      continues: true,
      title: "Manifiesto Comunista (1848)",
      body: "Esa elección de vocabulario es deliberada. Un fantasma del pasado regresaría desde algo que ya ocurrió y que se conoce; un fantasma del futuro anuncia algo que todavía no tiene forma pero que ya proyecta su sombra sobre el presente, algo que las clases dominantes temen sin poder nombrarlo del todo. El comunismo, en 1848, es apenas un puñado de grupúsculos dispersos; el Manifiesto habla de él, sin embargo, como si su triunfo ya estuviera escrito de antemano en la lógica misma de la historia.",
    },
    {
      type: "quiz",
      question: "«Un espectro recorre Europa»: ¿por qué esa palabra y no Geist?",
      options: [
        "Porque el fantasma no es del pasado sino del futuro",
        "Porque el Gespenst es la versión material del Geist",
        "Porque anuncia el regreso de una época perdida",
        "Porque nombra el miedo del obrero a la fábrica",
      ],
      answer: 0,
      explain: "Gespenst es literalmente un fantasma, y uno que todavía no llegó: lo que recorre Europa es algo por venir. El Manifiesto mezcla teoría de la historia, programa político y profecía, y en esa mezcla lo que sucederá y lo que debería suceder no se distinguen.",
    },
    {
      type: "info",
      continues: true,
      title: "Manifiesto Comunista (1848)",
      body: "\"Clase\" se vuelve, a partir de aquí, la pregunta identitaria decisiva: no la nación, no la religión, no la familia, sino el lugar que cada quien ocupa en el proceso de producción. Ser burgués o ser proletario no es una opinión ni una pertenencia cultural, sino una posición objetiva —poseer medios de producción o no poseerlos— que determina intereses materiales opuestos, más allá de lo que cada individuo crea sentir o pensar sobre su propia situación.",
    },
    {
      type: "info",
      title: "Lucha de clases",
      body: "\"La historia de toda sociedad hasta hoy es la historia de la **lucha de clases**\": la relación entre opresores y oprimidos, que toma formas distintas en cada época —patricios y plebeyos en Roma, señores y siervos en el feudalismo—. El enfrentamiento moderno entre burguesía y proletariado es, para Marx y Engels, el último de esa serie, porque así como el feudalismo dio paso al capitalismo, el capitalismo **contiene en sí las semillas de su propia destrucción**:",
    },
    {
      type: "info",
      continues: true,
      title: "Lucha de clases",
      body: "Lo que la burguesía produce, ante todo, son sus propios sepultureros. Su caída y la victoria del proletariado son igualmente inevitables.",
    },
    {
      type: "quiz",
      question: "«La burguesía produce sus propios sepultureros» significa que…",
      options: [
        "el capitalismo genera la clase que lo va a derribar",
        "los obreros mueren en las fábricas por descuido",
        "cada época entierra los símbolos de la anterior",
        "la nobleza recuperará el lugar que había perdido",
      ],
      answer: 0,
      explain: "Es la idea hegeliana de que todo estado de cosas contiene las semillas de su propia superación, ahora en clave material: al juntar obreros en las ciudades, el capitalismo fabrica al proletariado que lo va a enterrar.",
    },
    {
      type: "info",
      title: "El capital (1867): valor, plusvalía y fetichismo",
      body: "El capital traduce ese mismo diagnóstico a un registro distinto: ya no el de la filosofía humanista sino el de la crítica sistemática de la economía política, construida sobre dos décadas de investigación en el Museo Británico. Su punto de partida es la unidad más pequeña del sistema capitalista: la **mercancía**, que tiene a la vez un valor de uso —para qué sirve— y un valor de cambio —por cuánto de otra cosa se intercambia—.",
    },
    {
      type: "info",
      continues: true,
      title: "El capital (1867): valor, plusvalía y fetichismo",
      body: "Marx retoma de la economía clásica, y en particular de Ricardo, la tesis de que el valor de cambio de una mercancía se mide por el **trabajo socialmente necesario** para producirla. Pero introduce una distinción decisiva: lo que el obrero vende en el mercado no es su trabajo, sino su **fuerza de trabajo**, su capacidad de trabajar durante una jornada. El salario paga sólo lo necesario para reproducir esa capacidad —alimento, vivienda, descanso—.",
    },
    {
      type: "quiz",
      question: "¿Qué es exactamente lo que el obrero vende en el mercado, según Marx?",
      options: [
        "su fuerza de trabajo: la capacidad de trabajar la jornada",
        "su trabajo ya realizado, medido en horas concretas",
        "los productos que fabrica durante toda la jornada",
        "el tiempo libre que le queda fuera de la fábrica",
      ],
      answer: 0,
      explain: "La distinción es decisiva: el salario paga sólo lo necesario para reproducir esa capacidad —comida, vivienda, descanso—, no el valor que el obrero efectivamente produce trabajando.",
    },
    {
      type: "info",
      continues: true,
      title: "El capital (1867): valor, plusvalía y fetichismo",
      body: "Ahí aparece la **plusvalía**: en una jornada de trabajo, el obrero produce, mucho antes de que termine su turno, un valor equivalente a su propio salario; el resto de las horas trabajadas genera un valor adicional que el capitalista se apropia sin pagarlo, y que reaparece como ganancia. La plusvalía es, para Marx, el mecanismo preciso —no meramente moral— de la explotación capitalista.",
    },
    {
      type: "short",
      question: "¿Cómo llama Marx al valor que el capitalista se apropia sin pagarlo?",
      answers: ["plusvalía"],
      explain: "En una jornada, el obrero produce antes de que termine su turno un valor igual a su salario; el resto de las horas genera un valor extra que el capitalista se queda como ganancia.",
    },
    {
      type: "info",
      continues: true,
      title: "El capital (1867): valor, plusvalía y fetichismo",
      body: "Ese mismo sistema produce, además, el **fetichismo de la mercancía**: en el mercado, las mercancías parecen relacionarse entre sí de manera autónoma, a través de precios que suben y bajan por su cuenta, como si tuvieran vida propia. Esa apariencia oculta que detrás de cada precio hay relaciones sociales de trabajo entre personas concretas; el resultado es que las relaciones entre personas terminan revistiendo la forma engañosa de relaciones entre cosas.",
    },
    {
      type: "quiz",
      question: "El fetichismo de la mercancía consiste en que…",
      options: [
        "relaciones entre personas parecen relaciones entre cosas",
        "los objetos de lujo se vuelven símbolos de estatus social",
        "el dinero pierde su valor por la inflación constante",
        "los obreros idolatran los productos que ellos mismos hacen",
      ],
      answer: 0,
      explain: "En el mercado los precios parecen moverse solos, como si las mercancías tuvieran vida propia; esa apariencia oculta que detrás de cada precio hay relaciones sociales de trabajo entre personas concretas.",
    },
    {
      type: "info",
      continues: true,
      title: "El capital (1867): valor, plusvalía y fetichismo",
      body: "Entre el Marx de 1844 y el de El capital hay, para algunos intérpretes, una ruptura de fondo. **Louis Althusser** sostuvo que existe un **corte epistemológico** entre el humanismo filosófico del joven Marx —alienación, ser genérico— y la ciencia madura de la explotación —plusvalía, modo de producción—. Otros intérpretes prefieren ver continuidad: el fetichismo sería, en vocabulario económico riguroso, la misma alienación que los Manuscritos describían en términos filosóficos.",
    },
    {
      type: "classify",
      question: "¿Cada elemento corresponde al Marx joven o al Marx maduro?",
      groups: ["Marx joven", "Marx maduro"],
      items: [
        { text: "Los Manuscritos económico-filosóficos de 1844", group: 0 },
        { text: "El vocabulario de la alienación y el ser genérico", group: 0 },
        { text: "La ideología alemana", group: 0 },
        { text: "El capital y el análisis de la plusvalía", group: 1 },
        { text: "El modo de producción como categoría de análisis", group: 1 },
        { text: "La crítica sistemática de la economía política", group: 1 },
      ],
      explain: "Althusser habla de un corte epistemológico entre el humanismo filosófico del joven Marx y la ciencia madura de la explotación; otros prefieren ver continuidad, con el fetichismo como la alienación en vocabulario económico.",
    },
    {
      type: "info",
      title: "Ideología: la conciencia invertida",
      body: "La ideología alemana aporta la otra pieza que falta: la teoría de la **ideología**. Su tesis es que las ideas dominantes de cada época son, sencillamente, las ideas de la clase dominante, presentadas como verdades universales y eternas en lugar de como lo que son: la expresión de un interés de clase históricamente situado. La religión es el ejemplo mayor: \"la **religión es el opio de los pueblos**\", una droga que induce a aceptar el propio sufrimiento a cambio de una recompensa en un reino venidero.",
    },
    {
      type: "quiz",
      question: "¿Por qué la religión es «el opio de los pueblos»?",
      options: [
        "Porque adormece y hace aceptar la propia explotación",
        "Porque la financian directamente los dueños de las fábricas",
        "Porque une a los obreros por encima de las fronteras",
        "Porque es una superstición que la ciencia ya refutó",
      ],
      answer: 0,
      explain: "Es una droga que se agita frente a la gente, prometiendo una recompensa en un reino futuro a cambio de tolerar el sufrimiento presente: funciona como cualquier otra idea dominante que presenta un interés de clase como verdad universal.",
    },
    {
      type: "info",
      continues: true,
      title: "Ideología: la conciencia invertida",
      body: "Marx y Engels comparan el efecto de la ideología con el de una **cámara oscura**, el dispositivo óptico que proyecta la imagen del mundo invertida: así como esa imagen se ve cabeza abajo aunque el mundo esté derecho, la conciencia ideológica invierte la relación real entre la base material y las ideas, y hace aparecer como natural y eterno lo que es histórico y de clase.",
    },
    {
      type: "quiz",
      question: "¿Por qué Marx y Engels comparan la ideología con una cámara oscura?",
      options: [
        "Porque invierte la relación real entre la base y las ideas",
        "Porque oculta del todo la existencia de la lucha de clases",
        "Porque sólo funciona en sociedades sin tecnología",
        "Porque muestra la historia tal cual ocurrió en el pasado",
      ],
      answer: 0,
      explain: "La cámara oscura proyecta el mundo cabeza abajo aunque esté derecho; la ideología, del mismo modo, hace aparecer como natural y eterno lo que en realidad es histórico y de clase.",
    },
    {
      type: "info",
      title: "Base y superestructura",
      body: "De ahí el par conceptual que organiza el materialismo histórico: la **base**, la estructura socioeconómica —quién posee los medios de producción y quién vende su fuerza de trabajo—, y la **superestructura**, el arte, el derecho, la religión, la filosofía, la conciencia en general. Para Marx la base es determinante y la superestructura es derivada: la conciencia de clase de cada quien —burguesa o proletaria— deriva de su posición objetiva en el orden económico, no al revés.",
    },
    {
      type: "classify",
      question: "¿Cada elemento es de la base o de la superestructura?",
      groups: ["Base", "Superestructura"],
      items: [
        { text: "Ser dueño de una fábrica o vender tu trabajo", group: 0 },
        { text: "La distribución de los medios de producción", group: 0 },
        { text: "Tu posición en el orden económico", group: 0 },
        { text: "El arte y la cultura", group: 1 },
        { text: "La conciencia y el pensamiento", group: 1 },
        { text: "La religión que promete recompensa futura", group: 1 },
      ],
      explain: "La base es determinante y la superestructura, derivada: lo que determina cómo pensás es tu lugar en el orden socioeconómico. Por eso la naturaleza humana no es fija sino situacional, y por eso el dueño de fábrica tiene conciencia burguesa.",
    },
    {
      type: "info",
      title: "Determinismo, totalidad y el problema calvinista",
      body: "La base determina la conciencia, y la naturaleza humana deja de ser fija para volverse **situacional**, moldeada por la posición económica de cada quien. Hay, otra vez, una conflación hegeliana entre lo que sucederá y lo que debería suceder: los trabajadores alcanzarán la conciencia de clase, comprenderán que están explotados y que el problema no se resuelve individualmente, y se levantarán para derrocar a la burguesía. Cuando eso ocurra:",
    },
    {
      type: "quiz",
      question: "Que no haya distinción entre lo que sucederá y lo que debería suceder implica que…",
      options: [
        "la revolución es inevitable y también deseable",
        "el futuro depende sólo de lo que cada uno elija",
        "la moral no le interesa en absoluto a Marx",
        "la historia puede volver sobre sus pasos",
      ],
      answer: 0,
      explain: "Es la herencia hegeliana más pesada: hecho y valor se confunden. El proletariado no es una clase más: va a alcanzar la conciencia de clase y derrocar a la burguesía de manera inevitable y orgánica.",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo, totalidad y el problema calvinista",
      body: "Todo lo sólido se desvanece en el aire, todo lo sagrado es profanado, y el hombre se ve al fin obligado a mirar con ojos serenos sus condiciones reales de vida y sus relaciones con sus semejantes.",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo, totalidad y el problema calvinista",
      body: "Y el Manifiesto cierra con su llamado final:",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo, totalidad y el problema calvinista",
      body: "Los comunistas desdeñan ocultar sus opiniones y propósitos. Declaran abiertamente que sus fines sólo pueden alcanzarse mediante el derrocamiento violento de todo el orden social existente. Que tiemblen las clases dominantes ante una revolución comunista. Los proletarios no tienen nada que perder salvo sus cadenas. Tienen un mundo por ganar. ¡Trabajadores de todos los países, uníos!",
    },
    {
      type: "info",
      continues: true,
      title: "Determinismo, totalidad y el problema calvinista",
      body: "Ahí operan a la vez el **determinismo** y la **totalidad** hegelianos: el proletariado es la clase predestinada a conducir la revolución, y en el marxismo clásico esto ocurre de manera inevitable y orgánica, sin necesidad de agente que lo fuerce.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que nombra",
      pairs: [
        { left: "Plusvalía", right: "El valor extra que el capitalista se apropia sin pagarlo" },
        { left: "Proletariado", right: "Los que venden su fuerza de trabajo por hora en la fábrica" },
        { left: "Fetichismo de la mercancía", right: "Las relaciones entre personas parecen relaciones entre cosas" },
        { left: "Materialismo histórico", right: "El ser social determina la conciencia, y no al revés" },
        { left: "Alienación", right: "Perder la conexión con lo que uno mismo produce" },
      ],
      explain: "Las piezas encajan en un solo movimiento: el capitalismo produce plusvalía a costa del proletariado, esa relación se disfraza en el fetichismo de la mercancía, y todo eso se explica por las condiciones materiales y no por el Espíritu.",
    },
    {
      type: "info",
      title: "La herencia: el problema que Lenin hereda",
      body: "Ese determinismo deja planteado un problema estructuralmente idéntico al del **calvinismo**: si la salvación está predestinada, ¿para qué ir a la iglesia?, ¿para qué actuar si el resultado no depende de la acción? Si el proletariado va a llegar de todos modos a la conciencia de clase, ¿por qué haría falta organizarlo o apurarlo? Ese es exactamente el problema que **Lenin** va a heredar y va a intentar resolver, reemplazando la espontaneidad de las masas por la disciplina de un partido de vanguardia que apure lo que, en el marxismo clásico, debía llegar por su cuenta.",
    },
  ],
};
