export default {
  num: 1,
  transcript: 2,
  title: "La herencia de la Ilustración",
  source: "https://www.youtube.com/watch?v=VxATfoQJjzk",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "La **Ilustración** (en alemán, Aufklärung; en inglés, the age of reason o the age of light) es la etapa de la historia intelectual europea que va, a grandes rasgos, de fines del siglo XVII a 1789, año de la Revolución Francesa. No es una escuela unificada sino una constelación de filosofías que a menudo se contradicen entre sí.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Lo que sí comparten esas filosofías es un impulso común: someter a la razón todo lo que antes se aceptaba por tradición o autoridad, y preguntar de nuevo por la relación del hombre consigo mismo, con los demás, con el gobierno y con la naturaleza. Es ese impulso, más que una doctrina compartida, lo que permite hablar de \"la\" Ilustración en singular.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Uno de los conceptos que la época acuña, y que conviene mirar con sospecha, es el de **civilización**, siempre con una carga marcadamente **eurocéntrica**. Cuando estos filósofos hablan de una \"civilización mundial\" no piensan en el mundo entero, sino en Europa; no en toda Europa, sino en Francia; no en toda Francia, sino en París; y no en todo París, sino en cierto café frecuentado por un puñado de intelectuales que se creen representantes de la humanidad entera. La universalidad que la Ilustración predica tiene, desde el origen, un domicilio muy concreto.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Sus figuras centrales atraviesan casi siglo y medio: **René Descartes** (1596-1650), **Thomas Hobbes** (1588-1679), **John Locke** (1632-1704), **Voltaire** (1694-1778), **Jean-Jacques Rousseau** (1712-1778) e **Immanuel Kant** (1724-1804). De Descartes a Kant hay más de cien años: la Ilustración no es un momento sino un proceso largo, con etapas, escuelas nacionales y desacuerdos internos entre racionalistas continentales y empiristas británicos.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El proyecto que mejor resume su ambición es la **Encyclopédie** de Diderot y d'Alembert, publicada por entregas entre 1751 y 1772 pese a la censura real y a las suspensiones de su permiso de impresión: un intento de reunir y ordenar todo el conocimiento humano disponible, redactado por más de un centenar de colaboradores. Es el símbolo material de la fe ilustrada en que la razón, bien organizada en un solo objeto, puede volver accesible el saber entero a cualquiera que sepa leer.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "La Ilustración discute contra un mundo donde la autoridad última, en materia de conocimiento y de gobierno, era la tradición: la Escritura, la Iglesia, el derecho divino de los reyes, la filosofía escolástica heredada de Aristóteles y transmitida por siglos casi sin revisión de fondo. Frente a esa autoridad heredada, los ilustrados no oponen otra autoridad sino un método distinto: la razón individual, ejercida por cada quien y verificable por cualquiera que la aplique de la misma manera.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Ese giro tiene un correlato en la idea misma de tiempo. El mundo tradicional pensaba el tiempo como **cíclico** —estaciones, generaciones, el retorno ritual de lo mismo, la caída y la redención repetidas—; la Ilustración lo piensa, en cambio, como un tiempo que **avanza**, que acumula conocimiento y progresa de manera lineal e irreversible. Ese cambio en la figura del tiempo es, junto con la exaltación de la razón, el rasgo distintivo del pasaje entero a la modernidad, y va a ser también, más adelante, uno de los puntos que el Romanticismo va a discutirle con más fuerza.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al mundo tradicional o a la Ilustración?",
      groups: ["Mundo tradicional", "Ilustración"],
      items: [
        { text: "La autoridad última es la tradición y la Escritura", group: 0 },
        { text: "La autoridad última es la razón individual verificable", group: 1 },
        { text: "El tiempo es cíclico: estaciones, generaciones, retorno", group: 0 },
        { text: "El tiempo avanza y acumula conocimiento sin volver atrás", group: 1 },
        { text: "El saber se transmite casi sin revisión de fondo", group: 0 },
        { text: "El saber se somete a método y verificación de cada quien", group: 1 },
      ],
      explain: "La Ilustración no opone otra autoridad a la tradición sino un método: la razón individual, verificable por cualquiera que la aplique. Ese giro tiene su correlato en el tiempo: de lo cíclico se pasa a lo que avanza y progresa, un cambio que el Romanticismo va a discutir después.",
    },
    {
      type: "info",
      title: "La exaltación de la razón",
      body: "El movimiento clave de la Ilustración es la exaltación de la razón. Dios es **corrido a un costado**: pasa de ocupar un papel central en la explicación del mundo a uno secundario, y algo tiene que llenar ese espacio vacante —la **razón**—. El espíritu de la época es el regocijo en la razón, la fe en que, comprendiendo el mundo paso a paso, se lo puede también **moldear y mejorar** de manera deliberada, en vez de simplemente padecerlo.",
    },
    {
      type: "info",
      continues: true,
      title: "La exaltación de la razón",
      body: "Esta fe ocupa el lugar dominante que antes tenía el cristianismo, sin llegar a suprimirlo del todo. No se mata a Dios ni al cristianismo, pero ocurre lo que Max Weber va a llamar más tarde **Entzauberung**, **desencanto**: se deja atrás la sensación de que hay milagros, fuerzas inasibles, criaturas míticas, un más allá, para dar lugar a un mundo explicado enteramente por la razón y sus leyes. Hay una **sobriedad** deliberada en ese gesto: la idea de que el mundo pierde su magia no como una pérdida lamentable, sino como el precio necesario de comprenderlo.",
    },
    {
      type: "info",
      continues: true,
      title: "La exaltación de la razón",
      body: "Esa sobriedad puede vivirse de dos maneras opuestas, y ahí se juega buena parte de lo que el Romanticismo le va a discutir a la Ilustración. El ánimo de los ilustrados es **regocijarse** en el desencanto y en la razón que lo produce: cuanto más desencantado el mundo, más claro y manejable resulta. El Romanticismo, en cambio, va a encontrar ese mismo desencanto profundamente **decepcionante**: un mundo sin misterio es, para esa sensibilidad, un mundo empobrecido, no uno mejorado.",
    },
    {
      type: "quiz",
      question: "La idea central de la Ilustración es…",
      options: [
        "que el mundo es un misterio que la razón no alcanza",
        "que la razón puede comprender y mejorar el mundo",
        "que la fe revelada sigue siendo la fuente del saber",
        "que cada época tiene su verdad y no hay progreso",
      ],
      answer: 1,
      explain: "El movimiento clave es la exaltación de la razón: Dios es corrido a un costado y algo tiene que ocupar ese espacio. Como tenemos razón podemos comprender el mundo y, comprendiéndolo, moldearlo y mejorarlo. De ahí también el cambio en la concepción del tiempo: del tiempo cíclico al tiempo que avanza.",
    },
    {
      type: "short",
      question: "¿Cómo llama Max Weber al proceso por el que el mundo pierde su encantamiento?",
      answers: ["Entzauberung", "desencanto"],
      explain: "Entzauberung es el término de Weber para un mundo explicado enteramente por la razón y sus leyes, sin milagros ni fuerzas inasibles. La Ilustración vive ese desencanto con regocijo; el Romanticismo, como una pérdida.",
    },
    {
      type: "info",
      title: "Teleología, empirismo y las ciencias duras",
      body: "El término **teleología** viene del griego telos (fin, propósito) y logos (estudio o tratado): es la rama de la metafísica, formulada por **Aristóteles**, que explica un objeto o un proceso no sólo por su origen sino por el fin hacia el que se dirige, en función de su meta o propósito. La Ilustración hereda esa categoría, en principio ajena a la historia humana, y la aplica a la historia entera: el conocimiento y la sociedad tienen una dirección, un progreso hacia algo, del mismo modo en que una semilla se dirige hacia el árbol que será.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, empirismo y las ciencias duras",
      body: "El modelo de esta filosofía son las **ciencias duras**: entender al ser humano, la vida y la sociedad tal como los físicos, los astrónomos y los químicos entienden la naturaleza. **Isaac Newton** es el precursor decisivo de ese ideal: las leyes de la gravedad y del movimiento pueden descubrirse por observación y experimentación cuidadosas —se recogen datos, se observa lo que ocurre concretamente, se analiza—, sin necesidad de apelar a ninguna causa oculta o sobrenatural.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, empirismo y las ciencias duras",
      body: "De ese método, centrado en la experiencia sensorial y la observación como fuente de conocimiento, sale el **empirismo**; y del empirismo, más tarde, el **positivismo**: la pretensión de entender el mundo entero conforme a la observación empírica, sin encantamiento, sin fuerzas sobrenaturales, sin ningún residuo metafísico que la experiencia no pueda verificar. Es la misma teleología del progreso llevada hasta su forma más estricta: sólo cuenta como conocimiento aquello que puede comprobarse.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, empirismo y las ciencias duras",
      body: "Esta división entre el **racionalismo** de raíz cartesiana, que busca certezas deducidas por la sola razón, y el **empirismo** de raíz newtoniana y luego lockeana, que las busca en la experiencia acumulada, organiza buena parte del mapa filosófico del siglo. Descartes, el continente y la deducción geométrica de un lado; Newton, las islas británicas y la inducción experimental del otro: dos maneras distintas de perseguir el mismo ideal de certeza científica aplicada a todo lo humano.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, empirismo y las ciencias duras",
      body: "Newton publica sus Principios matemáticos de la filosofía natural en 1687, y ahí formula las leyes del movimiento y de la gravitación universal a partir de mediciones y cálculos, no de primeros principios racionales postulados de antemano. Ese logro —explicar por qué caen los cuerpos y por qué giran los planetas con una misma ley matemática— se vuelve el modelo a imitar: si la física pudo reducirse a leyes simples y verificables, ¿por qué no la moral, la política o la historia humana?",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, empirismo y las ciencias duras",
      body: "De ahí también la clara **teleología del progreso** que domina toda la época: cada salto del conocimiento se apoya en el anterior, y se asume que siempre se avanza, nunca se retrocede. Isaiah Berlin resume esa fe con la metáfora del **rompecabezas**: el mundo es un rompecabezas complejísimo, y aunque todavía no se colocaron todas las piezas, cada pieza ubicada acerca al todo, y cuantas más se colocan, más fácil resulta ubicar las que faltan. Es la imagen que mejor condensa el optimismo epistemológico ilustrado.",
    },
    {
      type: "quiz",
      question: "Que la Ilustración piense el conocimiento de modo teleológico significa que…",
      options: [
        "cambia de forma impredecible, sin dirección ni acumulación",
        "se explica por su origen y no por aquello a lo que tiende",
        "avanza hacia un fin y cada paso se apoya en el anterior",
        "vuelve siempre sobre los mismos problemas, sin avanzar",
      ],
      answer: 2,
      explain: "Teleología viene de telos (fin o propósito) y logos: explica algo por el objetivo hacia el que se dirige, no sólo por su origen. Aplicada al saber da una teleología del progreso, la que Isaiah Berlin ilustra con el rompecabezas: cada pieza colocada acerca al todo y facilita colocar las siguientes.",
    },
    {
      type: "quiz",
      question: "El logro de Newton que la Ilustración toma como modelo es…",
      options: [
        "deducir las leyes de la naturaleza a partir de la fe",
        "derivar leyes verificables de la observación y el cálculo",
        "explicar el movimiento por su fin o propósito último",
        "postular primero axiomas y deducir de ahí la física",
      ],
      answer: 1,
      explain: "Newton publica los Principios matemáticos en 1687 y formula las leyes del movimiento y la gravitación a partir de mediciones y cálculos, no de primeros principios racionales. Ese logro se vuelve el modelo: si la física se redujo a leyes simples y verificables, la época se pregunta por qué no la moral, la política o la historia.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que nombra",
      pairs: [
        { left: "Racionalismo", right: "La razón como fundamento y medida del conocimiento" },
        { left: "Empirismo", right: "El conocimiento se gana por la experiencia y la observación" },
        { left: "Positivismo", right: "Explicar el mundo sin nada sobrenatural ni metafísico" },
        { left: "Entzauberung", right: "El desencanto: se van los milagros y las fuerzas inasibles" },
      ],
      explain: "Racionalismo y empirismo son las dos vías del saber ilustrado: la razón como fundamento y la experiencia sensorial como fuente. Del empirismo —Newton como precursor— sale después el positivismo. Y el resultado de todo el movimiento es lo que Weber llamará Entzauberung: un mundo explicado por la razón, sin encantamiento.",
    },
    {
      type: "info",
      title: "Descartes y el fundamento del conocimiento",
      body: "En cierto sentido la filosofía moderna **empieza con Descartes**. Su idea principal era partir de una hoja en blanco, no aceptar nada por dado, y buscar un **fundamento sólido** para el conocimiento sobre el que después pudiera reconstruirse todo lo demás. Con ese gesto, la filosofía moderna se vuelve, ante todo, **epistemología**: el estudio de qué se puede saber y de cómo se lo sabe, antes que el estudio de qué hay.",
    },
    {
      type: "info",
      continues: true,
      title: "Descartes y el fundamento del conocimiento",
      body: "La pregunta que organiza esa epistemología es siempre la misma, formulada de mil maneras distintas: ¿cómo se sabe que el mundo es real y que existe?, ¿cómo se sabe que esta botella es real y no una proyección de la propia conciencia?, ¿cómo se pasa de lo interior a lo exterior, de la conciencia al ser, de la mente al mundo, de lo inmanente a lo trascendente? Son formas distintas de preguntar exactamente lo mismo: **¿cómo se sabe realmente qué es real?**",
    },
    {
      type: "info",
      continues: true,
      title: "Descartes y el fundamento del conocimiento",
      body: "El legado de Descartes es iniciar un experimento mental de **duda radical**: \"rechazar como absolutamente falso todo aquello en lo que pudiera suponer la menor razón de duda, para ver si no quedaba después algo enteramente indudable\"; \"deshacerme, una vez en la vida, de todas las opiniones que había adoptado y empezar de nuevo desde los cimientos\". ¿Cómo hallar entonces un fundamento que resista esa duda? Si se cree en Dios, la respuesta fácil sería que Dios no engañaría; pero Descartes imagina algo peor, un **genio maligno** empeñado en engañarlo en lugar de Dios.",
    },
    {
      type: "info",
      continues: true,
      title: "Descartes y el fundamento del conocimiento",
      body: "Descartes concluye que no puede estar seguro de la veracidad de sus pensamientos —quizá los puso ahí ese demonio—, pero sí de que está teniendo esos pensamientos, luego existe: el célebre **cogito, ergo sum**, \"pienso, luego existo\", una fórmula que va a reaparecer sin cesar en toda la filosofía posterior. Al final Descartes hace algo parecido a una trampa: recupera a Dios, y con él el mundo entero, mediante una prueba de la existencia divina que a muchos lectores posteriores les resulta poco convincente, aunque eso ya pertenece a otra discusión.",
    },
    {
      type: "quiz",
      question: "El cogito establece como indudable…",
      options: [
        "que mis pensamientos son verdaderos, porque son míos",
        "que existo, porque estoy teniendo pensamientos",
        "que el mundo exterior es real, porque lo percibo",
        "que Dios existe y por eso no puede engañarme",
      ],
      answer: 1,
      explain: "Aun si un genio maligno le hubiera puesto los pensamientos, Descartes no puede dudar de que los está teniendo: lo indudable no es el contenido del pensamiento, sino que hay alguien pensándolo. Recién después recupera a Dios, y con él el mundo entero, mediante una prueba que muchos lectores juzgan poco convincente.",
    },
    {
      type: "info",
      title: "Hobbes y el Leviatán",
      body: "**Thomas Hobbes** es el precursor de la **teoría del contrato social**, la vertiente más política de la Ilustración. En su larguísimo Leviatán (1651), la línea que lo resume es que la vida del hombre, en estado de naturaleza, es \"desagradable, brutal y breve\". Para Hobbes ese estado de naturaleza es un **estado de guerra**: los seres humanos están, según él, cableados para ser horribles entre sí, matándose y agrediéndose unos a otros en terror y violencia constantes, movidos por la codicia, el interés propio y el ansia de poder y riqueza, hasta que la sociedad viene a controlarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y el Leviatán",
      body: "Para acabar con esa pesadilla, Hobbes plantea que todos deben **ceder sus derechos naturales y su libertad a un Leviatán**, un gobernante absoluto que da paz y seguridad a cambio de la abdicación casi total de la libertad individual. Es un **juego de suma cero**: si se quiere seguridad, hay que ceder libertad, y no hay manera de tener las dos cosas a la vez en la cantidad que se desee.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y el Leviatán",
      body: "Hobbes llega a esa conclusión por un método que él mismo presenta como geométrico: parte de axiomas simples sobre la naturaleza humana —el miedo a la muerte violenta, el deseo de autoconservación— y deduce de ellos, paso a paso, la necesidad lógica del Estado absoluto, del mismo modo en que un teorema se deduce de sus postulados. Es la ciencia política soñada como una física de las pasiones humanas.",
    },
    {
      type: "quiz",
      question: "El método con que Hobbes funda al Leviatán consiste en…",
      options: [
        "partir de axiomas sobre la naturaleza humana y deducir el Estado",
        "observar muchos casos históricos y generalizar a partir de ellos",
        "partir de la revelación divina y deducir de ahí el gobierno",
        "consultar a los gobernados y deducir sus derechos naturales",
      ],
      answer: 0,
      explain: "Hobbes presenta su método como geométrico: parte de axiomas simples sobre la naturaleza humana —el miedo a la muerte violenta, el deseo de autoconservación— y deduce de ellos, paso a paso, la necesidad del Estado absoluto, como un teorema se deduce de sus postulados.",
    },
    {
      type: "info",
      title: "Locke: el consentimiento de los gobernados",
      body: "**John Locke** acepta el paso del estado de naturaleza al de sociedad civil, pero para él ese estado de naturaleza **no** era de guerra, sino de **libertad individual e igualdad natural**. La evolución hacia la sociedad no es, entonces, un abandono radical de todo entre ríos de sangre a cambio de la propia vida, como en Hobbes, sino un proceso **gradual**: la gente trabaja la tierra, adquiere propiedad privada, no quiere que se la roben, y decide que hace falta algún gobierno para protegerla.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el consentimiento de los gobernados",
      body: "Los derechos de una persona no chocan necesariamente con los de otra, y la gente puede razonar y llegar a acuerdos moderados para convivir sin necesidad de abdicar por completo, como en Hobbes, a un poder absoluto.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el consentimiento de los gobernados",
      body: "En sus Dos tratados sobre el gobierno (1689) sostiene que todo individuo posee derechos naturales a la igualdad, la vida, la libertad y la búsqueda de la felicidad; que la razón enseña que, siendo todos iguales e independientes, nadie debe dañar a otro; y que todos, dotados de razón, son competentes para participar en la elección de un gobierno propio.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el consentimiento de los gobernados",
      body: "El legado de Locke es doble: acepta el contrato social, pero rediseña sus condiciones. El estado de naturaleza no era guerra ni tampoco un paraíso, sino más bien una tabula rasa; y para proteger ciertos derechos, la gente forma gobiernos basados **sólo en el consentimiento de los gobernados**, nunca en el derecho divino de los reyes. Ese contrato, a diferencia del de Hobbes, **no es incondicional**: si los gobernantes abusan del poder, el pueblo conserva el derecho a reemplazarlos.",
    },
    {
      type: "classify",
      question: "¿Cada tesis es de Hobbes o de Locke?",
      groups: ["Hobbes", "Locke"],
      items: [
        { text: "El estado de naturaleza es una guerra de todos contra todos", group: 0 },
        { text: "El estado de naturaleza es de libertad e igualdad natural", group: 1 },
        { text: "Hay que ceder la libertad a un soberano absoluto", group: 0 },
        { text: "El gobierno se funda en el consentimiento de los gobernados", group: 1 },
        { text: "El contrato es incondicional: no hay vuelta atrás", group: 0 },
        { text: "Si los gobernantes abusan, el pueblo puede reemplazarlos", group: 1 },
      ],
      explain: "Los dos aceptan el contrato social, pero parten de estados de naturaleza opuestos: guerra y terror constantes en Hobbes, libertad e igualdad en Locke. De ahí que uno pida un Leviatán y una cesión definitiva de la libertad, y el otro un gobierno revocable, fundado en el consentimiento y no en el derecho divino de los reyes.",
    },
    {
      type: "info",
      title: "Los philosophes y el deísmo de Voltaire",
      body: "Estos pensadores son precursores de un nuevo tipo de filósofo del siglo XVIII, centrado en Francia: los **philosophes**. Como muestra la filosofía política ya descrita, es un modelo de filósofo **comprometido con el mundo** (engagé), que no pone entre paréntesis la vida real por preguntas abstractas de epistemología. Son cosmopolitas, seculares, humanistas, y unen teoría y **praxis** —palabra griega para la acción comprometida, teóricamente reflexionada—.",
    },
    {
      type: "info",
      continues: true,
      title: "Los philosophes y el deísmo de Voltaire",
      body: "Coquetean con reorientar a Dios en lo que llaman **deísmo**, y su figura clave es **Voltaire**. El deísmo es un espacio intermedio y moderado entre el Dios cristiano y el agnosticismo —el ateísmo todavía no está sobre la mesa, resulta demasiado radical incluso para los más audaces—: Dios existe, es maravilloso, creó el mundo, pero luego **se hizo a un lado**; dotó a los hombres de razón y los deja actuar; no es el titiritero que mueve todos los hilos desde arriba.",
    },
    {
      type: "info",
      continues: true,
      title: "Los philosophes y el deísmo de Voltaire",
      body: "Con este movimiento, Voltaire desplaza al **ser humano** al espacio antes ocupado por Dios, y no argumenta por la abolición de la religión sino por una amplísima **tolerancia**, contra la opresión y el absolutismo religiosos. Su lema es \"écrasez l'infâme\", \"aplastad la infamia\" —una versión tiránica del cristianismo, de la religión, de la superstición organizada—. Su Tratado sobre la tolerancia (1763) es deísta, contrario también al ateísmo, pero defensor de una tolerancia amplísima frente a cualquier ortodoxia.",
    },
    {
      type: "info",
      continues: true,
      title: "Los philosophes y el deísmo de Voltaire",
      body: "El precio de ese proyecto lo pagan sus propios artífices. Diderot pasa varios meses preso en Vincennes en 1749 por otro de sus escritos, y la Encyclopédie misma es suspendida más de una vez por la censura real, que le retira el permiso de impresión y obliga a sus editores a seguir trabajando de manera semiclandestina. La tolerancia que los philosophes reclaman no es un gesto abstracto: responde a una represión muy concreta que ellos mismos sufren.",
    },
    {
      type: "quiz",
      question: "El deísmo que defiende Voltaire sostiene que…",
      options: [
        "Dios no existe y la religión hay que abolirla",
        "Dios mueve todos los hilos de lo que nos pasa",
        "Dios creó el mundo y luego se hizo a un lado",
        "no hay manera de saber si Dios existe o no",
      ],
      answer: 2,
      explain: "El deísmo es un espacio intermedio y moderado entre el Dios cristiano y el agnosticismo —el ateísmo todavía es demasiado radical—: Dios existe y creó el mundo, pero nos dotó de razón y nos deja actuar; no es el titiritero que mueve los hilos. Voltaire no pide abolir la religión sino una amplísima tolerancia.",
    },
    {
      type: "info",
      title: "Rousseau",
      body: "Rousseau es el primero de varios personajes profundamente problemáticos que va a aparecer en este recorrido. Como escribió Charles Taylor, decir que Rousseau era difícil de tratar sería el gran eufemismo del siglo XVIII. De adolescente, huérfano y errante, vive de benefactoras —llega a ser amante de una de ellas—; en París conoce a **Diderot** y colabora con él en la gran **Encyclopédie**, ese intento de categorizar, organizar y hacer accesible el conocimiento humano que funciona como símbolo y metáfora de toda la actitud ilustrada.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau",
      body: "En la teoría del contrato social, Rousseau es **diametralmente opuesto a Hobbes**: para él el estado de naturaleza era un **estado de virtud**, y todo era bello y armonioso antes de que la propiedad corrompiera al hombre y lo volviera egoísta, arrogante y competitivo. Es, en ese sentido, un filósofo de la **nostalgia**: todo era mejor antes de la sociedad, pero no hay manera de volver atrás, y quien lo intente sólo estará jugando a algo que ya no puede ser real.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau",
      body: "En su Discurso sobre el origen de la desigualdad (1755) sitúa el origen de toda desigualdad en un solo gesto: el primer hombre que cercó un terreno y dijo \"esto es mío\", y encontró gente lo bastante simple como para creerle. A partir de ahí nacen la propiedad, la envidia, la competencia y, finalmente, la necesidad de un gobierno que proteja lo apropiado, ya no a todos por igual sino sobre todo a quien más tiene que proteger.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau",
      body: "Su Contrato social (1762) introduce la **voluntad general** como fuente de autoridad legítima, y esa fuente no es ninguna de las anteriores: no es el Leviatán de Hobbes, ni el consentimiento de los gobernados de Locke, ni la simple opinión mayoritaria. Tampoco es la suma de las voluntades particulares —a eso Rousseau lo llama la **voluntad de todos**—, sino lo que quiere el cuerpo político como tal, el **interés común**.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau",
      body: "Esa voluntad general es una concepción del **todo** que nadie logra definir con precisión, y que va a motivar después buena parte del Terror que sigue a la Revolución: si la autoridad legítima es \"lo que el pueblo quiere en su conjunto\" y no la suma de sus miembros individuales, queda abierta la pregunta de quién tiene autoridad para hablar en nombre de ese todo cuando los individuos concretos disienten entre sí.",
    },
    {
      type: "quiz",
      question: "En el contrato social de Rousseau, la autoridad se funda en…",
      options: [
        "un soberano absoluto que garantiza la paz y la seguridad",
        "el consentimiento revocable de los gobernados",
        "la voluntad general, el interés del cuerpo político",
        "la suma de las voluntades particulares de cada uno",
      ],
      answer: 2,
      explain: "Rousseau es diametralmente opuesto a Hobbes: el estado de naturaleza era virtud, y la propiedad corrompió al hombre. Y su voluntad general no es la suma de las voluntades particulares —eso es lo que él llama la voluntad de todos—, sino lo que quiere el cuerpo político como tal. Nadie la define con precisión, y después se la invocará para justificar el Terror.",
    },
    {
      type: "match",
      question: "Uní cada obra con el pensador que la escribió",
      pairs: [
        { left: "Hobbes", right: "Leviatán (1651): ceder la libertad a un soberano" },
        { left: "Locke", right: "Dos tratados sobre el gobierno (1689)" },
        { left: "Rousseau", right: "El contrato social (1762): la voluntad general" },
        { left: "Voltaire", right: "Tratado sobre la tolerancia (1763)" },
      ],
      explain: "Cuatro obras que fechan otros tantos momentos del recorrido: el Leviatán funda la teoría del contrato social del lado absolutista, los Dos tratados la rediseñan en clave de consentimiento, el Contrato social la lleva a la voluntad general, y el Tratado sobre la tolerancia expone el programa de Voltaire contra la opresión religiosa.",
    },
    {
      type: "info",
      title: "Kant: ¿qué es la Ilustración?",
      body: "**Kant** (1724-1804) dice, en un breve ensayo de 1784: la Ilustración es **la salida del hombre de su minoría de edad**. Su lema central es **sapere aude**, \"atrévete a saber\", ten el valor de usar tu propia razón sin someterte ciegamente a la autoridad ajena. Es un llamado a la acción, una exaltación de la responsabilidad y la capacidad de pensar por uno mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Kant: ¿qué es la Ilustración?",
      body: "Kant es a la vez un pensador de la **filosofía moral** y de la **epistemología**: su epistemología suele asociarse sobre todo a la Ilustración, mientras que su filosofía moral, construida en un registro casi opuesto, va a alimentar más adelante al Romanticismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Kant: ¿qué es la Ilustración?",
      body: "En epistemología, Kant parte de la pregunta cartesiana y se interroga qué es posible comprender del mundo: ¿cómo se sabe que este objeto está aquí y no es una proyección de la conciencia?, ¿hay un mundo en sí, o todo es proyección? Es el famoso debate entre **realismo** e **idealismo**, y Kant negocia un compromiso radical entre ambos: **sí hay un mundo real, con existencia independiente de la mente** —una **Ding an sich**, cosa en sí—, pero **no hay acceso directo** a ella, porque el mundo se procesa siempre a través de la conciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Kant: ¿qué es la Ilustración?",
      body: "De ahí su llamada **revolución copernicana**: así como Copérnico planteó que no es el Sol el que gira en torno a la Tierra sino la Tierra en torno al Sol, Kant sostiene que **no es la mente la que se conforma al mundo en sí, sino que lo que se ve del mundo debe conformarse a lo que la mente es capaz de procesar** —el tiempo, el espacio y la causalidad como estructuras que la conciencia impone de antemano a cualquier experiencia posible—.",
    },
    {
      type: "quiz",
      question: "La revolución copernicana de Kant consiste en sostener que…",
      options: [
        "la mente se conforma al mundo tal como es en sí mismo",
        "lo que vemos del mundo se conforma a nuestra mente",
        "no hay mundo real: todo es proyección de la conciencia",
        "el mundo es real y lo conocemos tal como es",
      ],
      answer: 1,
      explain: "Kant negocia un compromiso radical entre realismo e idealismo: sí hay un mundo con existencia independiente de la mente, una Ding an sich, pero no tenemos acceso a ella porque el mundo se procesa a través de nuestra conciencia. Como Copérnico invirtió qué gira alrededor de qué, Kant invierte qué se conforma a qué.",
    },
    {
      type: "info",
      title: "La Revolución Francesa",
      body: "El legado de la Ilustración es el **espíritu crítico** hacia la autoridad y el derecho a usar la propia razón. Ese legado culmina en julio de 1789 con la **Revolución Francesa** y su lema libertad, igualdad, fraternidad: sus ideas clave son la razón, el progreso, el contrato social, y un gobierno fundado no en el derecho divino de los reyes sino en el **consentimiento de los gobernados**.",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "La **Declaración de los Derechos del Hombre y del Ciudadano** (agosto de 1789) encarna esa filosofía política —en efecto, el acta de nacimiento del **liberalismo**—: los hombres nacen y permanecen libres e iguales en derechos; el fin de toda asociación política es la conservación de los derechos naturales e imprescriptibles del hombre —la libertad, la propiedad, la seguridad y la resistencia a la opresión—; la ley es la expresión de la voluntad general; nadie puede ser arrestado sino en los casos determinados por la ley; y todos son inocentes hasta que se pruebe su culpa.",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "El legado de la Revolución fue transformar a seres humanos que eran **súbditos** de un monarca —aquí \"súbdito\" en un sentido casi opuesto al que usan los filósofos: alguien poco menos que propiedad del monarca, sujeto a su voluntad— en **ciudadanos**, palabra revolucionaria y neologismo de la época: personas comprometidas y responsables, **creadoras** del gobierno, no ya peones ni posesiones de un soberano.",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "La Revolución fue también la invención de la **ideología** misma: ideas filosóficas llevadas a la vida real, y una conciencia revolucionaria empeñada en reordenar el cosmos entero —al punto de intentar reiniciar el calendario en el año uno—. Y surge de ahí un problema revolucionario clásico, formulado por **Robespierre**: ¿cómo pasar del viejo mundo al nuevo cuando los creadores de ese mundo nuevo ya están **contaminados**, formados por el viejo mundo opresivo que se quiere dejar atrás?",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "\"Hemos levantado el templo de la libertad con manos aún marchitas por la cadena del despotismo\", dice Robespierre, y esa frase anticipa exactamente el desenlace: el **Terror** (1793-1794), que muchos van a atribuir después a la propia idea rousseauniana de la voluntad general, sin criterio externo que la limite ni la corrija cuando se equivoca.",
    },
    {
      type: "quiz",
      question: "Convertir súbditos en ciudadanos significó que las personas…",
      options: [
        "cambiaron un monarca por otro, sin tocar su condición",
        "recuperaron los derechos que tenían en el estado de naturaleza",
        "quedaron sujetas a la ley divina y no a la del rey",
        "pasaron a crear el gobierno en vez de pertenecer al monarca",
      ],
      answer: 3,
      explain: "El súbdito era casi propiedad del monarca, sujeto a su voluntad; el ciudadano —neologismo revolucionario— es una persona comprometida y responsable, creadora del gobierno y no peón ni posesión. La Revolución fue además la invención de la ideología: ideas filosóficas llevadas a la vida real, hasta reiniciar el calendario en el año uno.",
    },
    {
      type: "quiz",
      question: "El problema que formula Robespierre sobre la Revolución es que…",
      options: [
        "los nuevos gobernantes repiten el derecho divino de los reyes",
        "quienes deben crear el mundo nuevo siguen formados por el viejo",
        "el pueblo no tiene forma de elegir a sus representantes",
        "la voluntad general coincide siempre con la de la mayoría",
      ],
      answer: 1,
      explain: "\"Hemos levantado el templo de la libertad con manos aún marchitas por la cadena del despotismo\", dice Robespierre: los creadores del mundo nuevo ya están contaminados por el viejo. Muchos atribuyen el Terror que sigue (1793-1794) a esa misma tensión, sin criterio externo que la corrija.",
    },
    {
      type: "info",
      title: "Modernidad, modernización, modernismo",
      body: "La Ilustración inaugura la **modernidad europea**, que culmina en 1789, fecha con que buena parte de los historiadores europeos la datan: la **modernidad** es, en ese sentido, un período histórico. La **modernización**, en cambio, son los cambios concretos y materiales ligados a ese período: avance tecnológico, industrialización, urbanización, migración del campo a la ciudad, creación de una clase obrera, capitalismo, paso de una economía de trueque a una monetaria, mejoras en las comunicaciones y el transporte.",
    },
    {
      type: "info",
      continues: true,
      title: "Modernidad, modernización, modernismo",
      body: "El **modernismo**, por último, es una **respuesta estética** a esos mismos cambios, en literatura, arte y filosofía: no describe los cambios técnicos sino la manera en que la cultura reacciona ante ellos. No son distinciones absolutas ni exclusivas entre sí, pero conviene fijarlas desde ahora, porque de aquí en más los tres términos se usan en ese sentido específico.",
    },
    {
      type: "info",
      continues: true,
      title: "Modernidad, modernización, modernismo",
      body: "El paso del taller artesanal a la fábrica textil, o del transporte a caballo al ferrocarril, ilustra bien la diferencia: son cambios de **modernización**, técnicos y verificables. Que un poeta o un pintor decida, frente a esos mismos cambios, romper con las formas heredadas y buscar un lenguaje nuevo pertenece, en cambio, al **modernismo**: una reacción, no una causa material.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que designa",
      pairs: [
        { left: "Modernidad", right: "El período que inaugura la Ilustración y culmina en 1789" },
        { left: "Modernización", right: "Industrialización, urbanización, capitalismo: cambios materiales" },
        { left: "Modernismo", right: "La respuesta estética en literatura, arte y filosofía" },
      ],
      explain: "No son distinciones absolutas, pero así se usan los términos: la modernidad es un período, la modernización son los cambios técnicos y materiales ligados a él —del campo a la ciudad, del trueque al dinero—, y el modernismo es la respuesta estética que llegará después.",
    },
    {
      type: "info",
      title: "La herencia: el optimismo ilustrado y su reverso",
      body: "El legado inmediato de la Ilustración es el **optimismo** en el poder de la razón: el conocimiento es bueno, progresivo, y permite comprender el mundo y sostenerlo mejor. Ese optimismo deja planteada, sin embargo, una pregunta que el Romanticismo va a instalar en el centro de la escena: ¿tiene la Ilustración un lado oscuro, un costo que su propio vocabulario no puede nombrar?",
    },
    {
      type: "match",
      question: "Repaso final: uní cada pensador con su aporte",
      pairs: [
        { left: "Descartes", right: "La duda radical y el cogito, ergo sum" },
        { left: "Hobbes", right: "El Leviatán: seguridad a cambio de libertad" },
        { left: "Locke", right: "El gobierno por consentimiento de los gobernados" },
        { left: "Rousseau", right: "La voluntad general y la nostalgia del estado de naturaleza" },
        { left: "Kant", right: "Sapere aude y la revolución copernicana" },
      ],
      explain: "Los cinco nombres que sostienen la clase: Descartes abre la epistemología moderna, Hobbes y Locke fundan el contrato social en direcciones opuestas, Rousseau lo lleva a la voluntad general —y de ahí al Terror—, y Kant formula el lema de la Ilustración y su compromiso entre realismo e idealismo.",
    },
    {
      type: "info",
      continues: true,
      title: "La herencia: el optimismo ilustrado y su reverso",
      body: "Goethe formula esa objeción, a propósito de Moses Mendelssohn, con una imagen que va a resumir por adelantado toda la crítica romántica: la razón ilustrada trata la belleza como el entomólogo a las mariposas —la atrapa, la clava con un alfiler, y entonces su color palidece hasta quedar una cáscara sin vida—. Todo muy bien organizado, todo muy comprensible, pero también, en el mismo gesto, algo irremediablemente muerto. Esa desconfianza frente a una razón que diseca lo que toca abre paso a la **rebelión romántica**.",
    },
  ],
};
