export default {
  num: 2,
  transcript: 3,
  title: "El legado del Romanticismo",
  source: "https://www.youtube.com/watch?v=-xeudCcrF8o",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "El **Romanticismo** es, ante todo, un movimiento alemán que se despliega aproximadamente entre 1770 y 1830, con centros en Königsberg, Weimar y Jena. Se lo llama también **Gegenaufklärung**, la contra-Ilustración: no una escuela con doctrina única, sino un ánimo compartido de rebelión contra el racionalismo ilustrado y su modelo de las ciencias duras.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Que ese ánimo cristalice sobre todo en los territorios de lengua alemana no es casual. A diferencia de Francia, unificada bajo una corona y una capital desde hace siglos, el mundo germánico de fines del siglo XVIII sigue fragmentado en cientos de principados, cortes y ciudades libres dentro del Sacro Imperio: sin un centro político único donde concentrar la energía intelectual, ésta se vuelca a la universidad, la poesía y la filosofía antes que a la vida pública y el salón parisino.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Sus figuras centrales incluyen a **Johann Georg Hamann** (1730-1788), **Johann Gottfried Herder** (1744-1803), **Friedrich Schiller** (1759-1805), **Johann Gottlieb Fichte** (1762-1814) y los hermanos **August Wilhelm Schlegel** (1767-1845) y **Friedrich Schlegel** (1772-1829). Kant y Rousseau, sin pertenecer al movimiento, le proveen buena parte de su material filosófico.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Antes del Romanticismo propiamente dicho hay una primera oleada literaria, el **Sturm und Drang** (\"tormenta e ímpetu\"), activa entre 1770 y comienzos de 1780 y bautizada por una obra de teatro homónima de Friedrich Maximilian Klinger (1776). Su emblema es Las cuitas del joven Werther (1774), de Goethe: la novela epistolar de un suicidio por amor tuvo tal poder de contagio que varias ciudades alemanas llegaron a prohibir su venta.",
    },
    {
      type: "quiz",
      question: "El Sturm und Drang, la oleada previa al Romanticismo, tiene como emblema…",
      options: [
        "el Fausto de Goethe, sobre un pacto con el diablo",
        "el Werther de Goethe, una novela sobre un suicidio por amor",
        "el Leviatán de Hobbes, sobre el estado de naturaleza",
        "la Encyclopédie de Diderot, sobre el saber humano",
      ],
      answer: 1,
      explain: "Las cuitas del joven Werther (1774) es el emblema del Sturm und Drang, la oleada previa al Romanticismo: la novela epistolar de un suicidio por amor tuvo tal poder de contagio que varias ciudades alemanas llegaron a prohibir su venta.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "La Ilustración parte de la idea de un tiempo progresivo: la razón permite comprender el mundo cada vez mejor, y ese conocimiento acumulado sirve para mejorarlo. Es un proyecto humanista que funda los derechos naturales en la capacidad racional del hombre, y que toma a las ciencias naturales —observación cuidadosa, cálculo, descubrimiento de patrones— como modelo para entender también la vida social, el amor y el arte.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "De esa fe se siguen varias creencias solidarias entre sí: que toda pregunta puede en principio ser respondida, que existe una verdad objetiva descubrible como la ley de la gravedad de Newton, y que el mundo es en esencia comprensible aunque falten piezas del rompecabezas. A eso se suma la idea de una **armonía de intereses**: cuanto más se comprende el mundo, mejor puede moldeárselo para todos, y la razón, se supone, conduce naturalmente a la virtud.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Ese optimismo, sin embargo, resulta emocionalmente insuficiente para buena parte de una generación. La racionalidad y la convergencia armónica entre el individuo y el colectivo dejan un residuo insatisfecho: es el mismo problema que después va a heredar el liberalismo político. El Romanticismo nace exactamente de esa insatisfacción.",
    },
    {
      type: "quiz",
      question: "La «armonía de intereses» que supone la Ilustración significa que…",
      options: [
        "el interés propio hay que sacrificarlo al del colectivo",
        "los ideales verdaderos chocan entre sí y hay que elegir",
        "lo que es bueno para uno puede ser bueno para todos",
        "el interés de cada uno es lo único que se puede conocer",
      ],
      answer: 2,
      explain: "El ánimo ilustrado supone que las cosas buenas van juntas: a medida que se comprende mejor el mundo se lo puede moldear para que sea mejor para todos, y los derechos del individuo se reconcilian con los del colectivo. El Romanticismo va a negar exactamente esto.",
    },
    {
      type: "info",
      title: "El Romanticismo como rebelión",
      body: "Si los géneros emblemáticos de la Ilustración son la teoría del contrato social y la Encyclopédie, los del Romanticismo son la **poesía** y, en buena medida, el teatro. Si el centro de la Ilustración es Francia, el centro del Romanticismo es **Alemania**. La idea de fondo sigue siendo el **desencanto** del mundo —el Entzauberung de Weber—: no hay reyes que gobiernen por derecho divino ni fuerzas sobrenaturales que otorguen gracia; sólo la mente humana, sobria y racional, tratando de comprender las cosas.",
    },
    {
      type: "info",
      continues: true,
      title: "El Romanticismo como rebelión",
      body: "Frente a las palabras clave de la Ilustración —civilización, razón, progreso— el Romanticismo opone otras: **pasión, belleza, anhelo, creación, voluntad**. Es un rechazo del racionalismo como virtud incuestionable, de la idea de que todas las preguntas tienen respuesta y de que todos los valores son compatibles entre sí. Hay un giro hacia el **alma individual**, que muchas veces entra en conflicto con otras almas: la verdad deja de ser algo que se descubre afuera, por experimentación, para ser algo que se produce adentro, un **acto de creación**.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de la Ilustración o del Romanticismo?",
      groups: ["Ilustración", "Romanticismo"],
      items: [
        { text: "La verdad está afuera y se descubre observando", group: 0 },
        { text: "La verdad se produce en el alma, es una creación", group: 1 },
        { text: "El modelo son las ciencias duras", group: 0 },
        { text: "El modelo son la poesía y el teatro", group: 1 },
        { text: "Palabras clave: civilización, razón, progreso", group: 0 },
        { text: "Palabras clave: pasión, belleza, anhelo, voluntad", group: 1 },
      ],
      explain: "El Romanticismo es una rebelión punto por punto, a veces llamada Gegenaufklärung, la contra-Ilustración: si el centro de la Ilustración es Francia, el suyo es Alemania; si el género ilustrado es la Encyclopédie, el suyo es la poesía. Rechaza que todas las preguntas tengan respuesta, que todas las virtudes sean compatibles y que los intereses puedan armonizarse.",
    },
    {
      type: "info",
      title: "El bosque, la oscuridad, la tormenta",
      body: "Hay también un giro estético hacia la naturaleza. Si la metáfora de la Ilustración está en su propio nombre —la luz, el siglo de las luces—, lo que el Romanticismo va a amar es la **oscuridad**: la niebla, las tormentas eléctricas, la lluvia cayendo sobre el bosque, el refugio en una cueva. Bosques oscuros y remotos, paisajes provincianos: la naturaleza deja de ser objeto de estudio para volverse espejo del alma.",
    },
    {
      type: "info",
      continues: true,
      title: "El bosque, la oscuridad, la tormenta",
      body: "El emblema pictórico de ese giro es El caminante sobre el mar de nubes (hacia 1818), de Caspar David Friedrich: una figura solitaria, vista de espaldas, contempla desde una cima un océano de niebla que no deja ver nada más allá. No hay ahí ningún dato científico sobre la montaña ni sobre el clima; hay una posición del alma frente a lo inconmensurable, lo que los románticos llaman más tarde el **sublime** natural.",
    },
    {
      type: "info",
      title: "Johann Georg Hamann y la crítica del lenguaje",
      body: "**Johann Georg Hamann**, apodado el \"mago del Norte\", vive en Königsberg y es amigo tanto de Kant como de Herder, a quien influye decisivamente. Su tesis central, dirigida contra la propia Crítica de la razón pura de Kant, es que no existe una razón pura, despojada de lenguaje: se piensa siempre en una lengua concreta, histórica y particular, nunca en abstracto. Llama a su objeción una **metacrítica** de la razón.",
    },
    {
      type: "info",
      continues: true,
      title: "Johann Georg Hamann y la crítica del lenguaje",
      body: "De ahí se sigue su rechazo de las clasificaciones ilustradas: los seres humanos son irreductiblemente únicos y singulares, y ningún sistema de principios generales —por más científico que se presente— puede dar cuenta de esa singularidad sin perderla en el camino. Lo primario para el ser humano no es el anhelo de paz y armonía, sino el anhelo de **intensidad, pasión y creación**.",
    },
    {
      type: "info",
      continues: true,
      title: "Johann Georg Hamann y la crítica del lenguaje",
      body: "Hamann escribe de manera deliberadamente oscura, fragmentaria, cargada de alusiones bíblicas y juegos de palabras: su prosa misma pone en práctica la tesis de que no hay pensamiento puro separable de un estilo, un cuerpo y una lengua concretos. Por eso se lo conoce como el \"mago del Norte\": comunica por sugerencia y enigma, no por argumento lineal, casi como una objeción viviente al ideal ilustrado de la claridad expositiva.",
    },
    {
      type: "quiz",
      question: "La metacrítica de Hamann contra Kant sostiene que…",
      options: [
        "no hay pensamiento posible fuera de una lengua concreta",
        "la razón pura existe, pero el lenguaje la distorsiona",
        "sólo la lógica formal garantiza un pensamiento válido",
        "cada individuo piensa con una razón distinta de los demás",
      ],
      answer: 0,
      explain: "Contra la Crítica de la razón pura de Kant, Hamann sostiene que no existe una razón pura despojada de lenguaje: se piensa siempre en una lengua concreta, histórica y particular, nunca en abstracto. Llama a esa objeción una metacrítica de la razón.",
    },
    {
      type: "info",
      title: "Rousseau, figura de transición",
      body: "**Rousseau** es la principal figura de transición entre ambos ánimos: según cuál Rousseau se lea, es un pensador ilustrado o uno romántico. En El contrato social es un teórico político que colabora con Diderot en la Encyclopédie; en sus Confesiones, el tono es marcadamente romántico. Sus ideas de gobierno pertenecen a la Ilustración; su autodescripción y su temperamento, al Romanticismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau, figura de transición",
      body: "Las Confesiones, escritas en su última década y publicadas después de su muerte, abren con la pretensión de mostrarse ante el lector tal cual es, sin ocultar ni embellecer nada, en una empresa que Rousseau presenta como no tenida antes por ningún otro escritor. Esa exposición radical del propio yo —sus vergüenzas, sus pequeños delitos, sus deseos inconfesables— funda buena parte de la autobiografía moderna, y es en sí misma un gesto romántico: la verdad de una vida no está en sus actos públicos sino en su interioridad más privada.",
    },
    {
      type: "quiz",
      question: "Rousseau es figura de transición porque…",
      options: [
        "escribió primero como romántico y después como ilustrado",
        "su política es ilustrada y su temperamento romántico",
        "abandonó la filosofía para irse a vivir al bosque",
        "sus dos libros sostienen la misma tesis con otro tono",
      ],
      answer: 1,
      explain: "Según cuál Rousseau se lea, es una figura por excelencia de la Ilustración o del Romanticismo: El contrato social es de un pensador ilustrado que colabora con Diderot en la Encyclopédie, y las Confesiones tienen un tono marcadamente romántico. Sus ideas sobre el gobierno son ilustradas; su autodescripción y su temperamento, no.",
    },
    {
      type: "info",
      title: "El modelo de la nostalgia",
      body: "Su idealización del estado de naturaleza se convierte en el **modelo de la nostalgia** en general: el anhelo por algo del pasado que en realidad nunca existió, reconstruido después en la imaginación. Los románticos usan para esto la palabra alemana **Sehnsucht**, un anhelo que se vuelve un fin en sí mismo. El objeto añorado importa menos que la **emoción del anhelo** hacia algo que nunca podrá alcanzarse del todo.",
    },
    {
      type: "quiz",
      question: "La nostalgia romántica, ese Sehnsucht, es el anhelo de…",
      options: [
        "un pasado que en realidad nunca existió",
        "un futuro mejor que la razón va a construir",
        "una patria perdida que se puede recuperar",
        "un objeto concreto que alguien te quitó",
      ],
      answer: 0,
      explain: "La nostalgia es el anhelo por algo del pasado que nunca existió: se lo imagina maravilloso, se cree que estuvo y se perdió, pero en verdad se lo recreó en la imaginación. Los románticos le dan un nombre alemán, Sehnsucht: el objeto añorado importa menos que la emoción de anhelar aquello que no puede alcanzarse del todo.",
    },
    {
      type: "short",
      question: "¿Cómo llaman los románticos al anhelo que se vuelve un fin en sí mismo?",
      answers: ["Sehnsucht"],
      explain: "Sehnsucht nombra el modelo romántico de la nostalgia: un anhelo por algo del pasado que en realidad nunca existió. El objeto añorado importa menos que la emoción misma de anhelar algo que nunca podrá alcanzarse del todo.",
    },
    {
      type: "info",
      title: "Conflictos y autenticidad",
      body: "Rousseau entra en conflicto con casi todo su círculo, incluido un cruce epistolar hostil con Voltaire, y se vuelve inspiración de comunas naturalistas que intentan volver a la naturaleza sin lograrlo nunca del todo: él mismo se limita a escribir sobre esa vuelta, no a practicarla. De esos conflictos y de esa idealización sale uno de los grandes temas que el Romanticismo hereda de él: la **virtud de la autenticidad**.",
    },
    {
      type: "info",
      continues: true,
      title: "Conflictos y autenticidad",
      body: "El Discurso sobre las ciencias y las artes sostiene que el hombre de sociedad ya no se atreve a mostrarse como es: vive compitiendo por lucirse, y el amor propio, la vanidad y el egocentrismo son la verdadera causa del descontento moderno. Esa corrupción no es natural, sino artificial: la produce la mirada ajena, y con ella la propiedad y la competencia. No hay virtud sin autenticidad, y la autenticidad exige distancia respecto de la sociedad.",
    },
    {
      type: "info",
      continues: true,
      title: "Conflictos y autenticidad",
      body: "\"Uno ya no se atreve a parecer lo que es; y bajo esa restricción perpetua, los hombres que forman el rebaño llamado sociedad, puestos en circunstancias similares, actuarán todos de manera similar, salvo que motivos más poderosos los inclinen de otro modo. Así, nunca se sabrá realmente con quién se está tratando.\"",
    },
    {
      type: "quiz",
      question: "Para Rousseau, lo que corrompe al burgués es…",
      options: [
        "la falta de educación en el uso de la razón",
        "una maldad que trae del estado de naturaleza",
        "el exceso de piedad natural hacia los otros",
        "la mirada de los demás, que lo obliga a fingir",
      ],
      answer: 3,
      explain: "El burgués compite por lucirse, y el amor propio, la vanidad y el egocentrismo nacen de la mirada ajena. No es natural sino artificial, obra de la sociedad y de la propiedad. De ahí la virtud que los románticos heredan: no hay virtud sin autenticidad, y la autenticidad exige distancia respecto de la sociedad.",
    },
    {
      type: "info",
      title: "Ser y devenir; la piedad natural",
      body: "Para Rousseau dos rasgos distinguen al hombre de las demás criaturas: la **libre agencia** y la apertura al **devenir**. Si la Ilustración pregunta cómo **son** las cosas —qué leyes rigen el mundo—, el Romanticismo pregunta por el **devenir**: el ser humano es una criatura singularmente indeterminada, que se autocrea. Rousseau agrega la **piedad** o compasión natural: en el estado de naturaleza idealizado el hombre sentía empatía espontánea por los demás, antes de que la sociedad y la propiedad lo volvieran vanidoso y calculador.",
    },
    {
      type: "info",
      title: "Kant, figura de las dos corrientes",
      body: "Kant también pertenece a ambas corrientes, según en cuál de sus dos grandes proyectos se ponga el foco. Su ensayo ¿Qué es la Ilustración? (1784) —sapere aude, atrévete a saber— lo ubica del lado ilustrado. Su Crítica de la razón pura (1781) negocia, en cambio, un compromiso entre el **realismo**, para el cual el mundo existe con independencia de la mente, y el **idealismo**, para el cual todo ocurre dentro de la conciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Kant, figura de las dos corrientes",
      body: "Kant sostiene que hay un mundo en sí —la **Ding an sich**—, pero sin acceso directo a él, porque sólo se lo conoce tal como la mente lo procesa, a través del tiempo, el espacio y la causalidad.",
    },
    {
      type: "match",
      question: "Uní cada posición con lo que sostiene sobre el mundo exterior",
      pairs: [
        { left: "Realismo", right: "El mundo es real y nuestra mente debe conformarse a él" },
        { left: "Idealismo", right: "Todo está en la cabeza y no hay manera de salir de ella" },
        { left: "Kant", right: "Hay una cosa en sí, pero sólo se accede a cómo se aparece" },
      ],
      explain: "Kant negocia un compromiso entre las dos: cree que hay un mundo en sí, su Ding an sich, pero también que no hay acceso directo a él porque no se puede salir de la propia cabeza. Sólo se comprende la realidad tal como se conforma a las estructuras de la mente.",
    },
    {
      type: "quiz",
      question: "En el compromiso de Kant entre racionalismo y empirismo, la mente…",
      options: [
        "recibe datos y les impone tiempo, espacio y causalidad",
        "recibe datos y los registra tal como llegan del mundo",
        "produce sus ideas sin necesidad de datos sensoriales",
        "deduce las leyes de la física por pura lógica interna",
      ],
      answer: 0,
      explain: "Hay receptividad —se reciben datos sensoriales empíricos del mundo— y a la vez espontaneidad: se imponen sobre esos datos las estructuras de la conciencia, en particular el tiempo, el espacio y la causalidad. Ni el empirismo puro, que sólo registra, ni el racionalismo puro, que deduce sin mirar.",
    },
    {
      type: "info",
      title: "Filosofía moral: deber, intención, dignidad",
      body: "Lo que el Romanticismo toma de Kant es, en cambio, su **filosofía moral**, construida en un registro casi opuesto al de su epistemología. Para que haya moralidad, sostiene Kant, tiene que haber **libre albedrío**: no puede demostrarse, pero se lo postula como condición de posibilidad de la ética. Actuar moralmente es actuar por sentido del **deber**, no por simple inclinación, y la prueba de ese deber es una versión del **imperativo categórico**: preguntarse qué pasaría si todos actuaran según el principio que se está por seguir.",
    },
    {
      type: "info",
      continues: true,
      title: "Filosofía moral: deber, intención, dignidad",
      body: "Lo que cuenta moralmente, para Kant, es la **intención**, no la consecuencia: una vez que se actúa, las acciones entran en redes de causalidad que exceden cualquier control, y el agente no puede hacerse responsable de todo lo que termina desencadenando. Alguien puede actuar con la mejor intención posible y aun así provocar, sin culpa moral, un desastre que no estaba en condiciones de prever.",
    },
    {
      type: "info",
      continues: true,
      title: "Filosofía moral: deber, intención, dignidad",
      body: "De ahí también su idea de **dignidad**: no sólo la razón, sino el libre albedrío, es lo que hace al ser humano un **fin en sí mismo** y nunca un simple medio. Tratar a otra persona como un objeto —manipularla, instrumentalizarla para un fin ajeno— es, para Kant, la falta moral por excelencia, porque niega precisamente lo que hace de esa persona un agente y no una cosa. Su fórmula es tajante:",
    },
    {
      type: "info",
      continues: true,
      title: "Filosofía moral: deber, intención, dignidad",
      body: "Todo lo que puede ser reemplazado por otra cosa de valor equivalente tiene un precio; aquello que está por encima de todo precio y no admite equivalente tiene dignidad.",
    },
    {
      type: "quiz",
      question: "Si alguien actúa por deber y de todos modos provoca un desastre, para Kant…",
      options: [
        "la acción es inmoral: contaban las consecuencias",
        "hay que repararlo antes de juzgar la intención",
        "la acción sigue siendo moral: contaba la intención",
        "no se puede evaluar moralmente lo que hizo",
      ],
      answer: 2,
      explain: "Una vez que se actúa, las acciones entran en redes de causalidad que exceden cualquier control. Lo que se evalúa es la voluntad de actuar por sentido del deber, y la prueba es el imperativo categórico: ¿qué pasaría si todos actuaran según ese mismo principio? Los románticos van a llevar esa primacía de la voluntad al extremo.",
    },
    {
      type: "info",
      title: "El legado kantiano: la primacía de la voluntad",
      body: "El legado kantiano para el Romanticismo es la **primacía de la voluntad**: si hay libre albedrío, entonces importa sobre todo la elección, la intención, el motivo. Kant escribía como un racionalista sobrio y moderado, pero los románticos toman esa idea de la voluntad y la elevan a **valor absoluto**: la creación como imperativo existencial, el devenir en aquello que cada quien puede llegar a ser. El modelo deja de ser la ciencia para pasar a ser el **arte**.",
    },
    {
      type: "match",
      question: "Repaso: uní cada término de Kant con lo que nombra",
      pairs: [
        { left: "Sapere aude", right: "Atrévete a saber: usá tu propia razón" },
        { left: "Ding an sich", right: "La cosa en sí, el mundo tal como no lo conocemos" },
        { left: "Libre albedrío", right: "No se puede demostrar, pero hay que postularlo" },
        { left: "Imperativo categórico", right: "¿Y si todos actuaran según ese principio?" },
        { left: "Dignidad", right: "Lo que no admite equivalente ni reemplazo" },
      ],
      explain: "Los cinco están en la clase por razones distintas: sapere aude es la definición de Ilustración, la Ding an sich el límite de la epistemología, y los otros tres el andamiaje de la filosofía moral. Y ahí está la bisagra: la Ilustración toma de Kant su epistemología, y los románticos su filosofía moral, construida en cierto sentido de manera opuesta.",
    },
    {
      type: "info",
      title: "Del cogito al volo",
      body: "Los románticos toman el cogito, ergo sum cartesiano —\"pienso, luego existo\"— y lo invierten en **\"volo, ergo sum\"**: \"quiero, luego existo\". La subjetividad ya no se funda en la cognición sino en el **deseo y la voluntad**. **Fichte**, discípulo de Kant, lo resume con una fórmula que va a repetirse durante todo el siglo: \"ser libre no es nada; **devenir libre** lo es todo\".",
    },
    {
      type: "info",
      continues: true,
      title: "Del cogito al volo",
      body: "Fichte lleva el gesto kantiano un paso más allá del propio Kant. En su Doctrina de la ciencia (1794) parte de un **Yo** que se pone a sí mismo por un acto libre y originario, y que a la vez se opone un **no-Yo** —el mundo, lo otro— para poder reconocerse frente a él.",
    },
    {
      type: "info",
      continues: true,
      title: "Del cogito al volo",
      body: "El sujeto no encuentra el mundo dado de antemano: en algún sentido se lo produce, precisamente para tener frente a qué ejercer su libertad y su acción. Esa prioridad del acto libre sobre cualquier dato ya recibido es lo que los románticos leen como la primera filosofía consecuente de la voluntad.",
    },
    {
      type: "quiz",
      question: "Pasar del cogito al volo significa fundar la subjetividad en…",
      options: [
        "el pensamiento, no en la experiencia sensible",
        "el deseo y la voluntad, no en el pensamiento",
        "la razón compartida, no en el alma individual",
        "el cuerpo y sus sensaciones, no en la mente",
      ],
      answer: 1,
      explain: "Los románticos toman el cogito ergo sum cartesiano y lo contraponen con volo ergo sum: quiero, deseo, luego existo. Fichte lo dice sin rodeos: ser libre no es nada, devenir libre lo es todo. Todo gira alrededor del devenir y del deseo.",
    },
    {
      type: "quiz",
      question: "En la Doctrina de la ciencia, el Yo de Fichte se opone a un no-Yo para…",
      options: [
        "tener algo frente a lo cual ejercer su libertad y su acción",
        "demostrar que el mundo exterior no existe realmente",
        "someterse a las leyes que ese no-Yo le impone desde afuera",
        "fundar una ciencia empírica de la naturaleza física",
      ],
      answer: 0,
      explain: "Fichte parte de un Yo que se pone a sí mismo por un acto libre y originario, y que se opone un no-Yo —el mundo, lo otro— para poder reconocerse frente a él. El sujeto no encuentra el mundo dado de antemano: en algún sentido se lo produce, precisamente para tener frente a qué ejercer su libertad.",
    },
    {
      type: "info",
      title: "Friedrich Schiller y la educación estética",
      body: "**Friedrich Schiller** —dramaturgo del Sturm und Drang con Los bandidos (1781) antes de volverse el gran teórico estético del Romanticismo— intenta resolver la tensión entre razón y pasión con un tercer término. En sus Cartas sobre la educación estética del hombre (1795) distingue un **impulso sensible** (Stofftrieb), atado a lo material y cambiante, y un **impulso formal** (Formtrieb), atado a la ley racional; ninguno de los dos alcanza por sí solo para hacer libre al hombre.",
    },
    {
      type: "info",
      continues: true,
      title: "Friedrich Schiller y la educación estética",
      body: "Entre ambos, Schiller ubica el **impulso lúdico** (Spieltrieb): el juego y el arte como el único territorio donde sensibilidad y razón se concilian sin que una domine a la otra. En un ensayo posterior distingue la poesía **ingenua**, la del artista todavía en armonía con la naturaleza, de la poesía **sentimental**, la del artista moderno que ya la perdió y la añora conscientemente.",
    },
    {
      type: "info",
      continues: true,
      title: "Friedrich Schiller y la educación estética",
      body: "Para Schiller esa reconciliación no es sólo un problema de estética individual: es también un programa político. Sostiene que ninguna reforma institucional puede volver libre a un pueblo cuyo carácter no fue antes educado por el arte, porque las instituciones sólo funcionan si encuentran ciudadanos capaces de sostener la libertad sin caer ni en la barbarie del instinto puro ni en la rigidez de la sola razón. La educación estética es, en ese sentido, la condición previa de cualquier educación política.",
    },
    {
      type: "info",
      continues: true,
      title: "Friedrich Schiller y la educación estética",
      body: "Esa búsqueda de equilibrio entre pasión y forma es también lo que distancia a Schiller, en su etapa madura, del propio Sturm und Drang de su juventud. Junto con Goethe, ya instalados los dos en Weimar, funda lo que se conoce como el **clasicismo de Weimar**: un intento de templar el ímpetu romántico con la serenidad y la proporción que ambos admiran en el arte griego, sin renunciar por eso a la centralidad de la libertad y el sentimiento.",
    },
    {
      type: "match",
      question: "Uní cada impulso de Schiller con lo que designa",
      pairs: [
        { left: "Stofftrieb", right: "El impulso sensible, atado a lo material y cambiante" },
        { left: "Formtrieb", right: "El impulso formal, atado a la ley racional" },
        { left: "Spieltrieb", right: "El impulso lúdico: el juego donde se concilian razón y pasión" },
      ],
      explain: "Ninguno de los dos primeros alcanza por sí solo para hacer libre al hombre: el sensible lo somete a la materia, el formal a la sola razón. Entre ambos, Schiller ubica el impulso lúdico, el Spieltrieb: el juego y el arte como el único territorio donde sensibilidad y razón se concilian sin que una domine a la otra.",
    },
    {
      type: "quiz",
      question: "Para Schiller, la poesía sentimental se distingue de la ingenua en que…",
      options: [
        "es la del artista moderno, que perdió esa armonía",
        "es la del artista antiguo, en armonía con la naturaleza",
        "es la que ningún poeta romántico se anima a escribir",
        "es la que sólo admite temas amorosos y nunca otros",
      ],
      answer: 0,
      explain: "Schiller distingue la poesía ingenua, la del artista todavía en armonía con la naturaleza, de la sentimental, la del artista moderno que ya la perdió y la añora conscientemente.",
    },
    {
      type: "info",
      title: "Los hermanos Schlegel y el romanticismo de Jena",
      body: "**August Wilhelm Schlegel** (1767-1845) y su hermano **Friedrich Schlegel** (1772-1829) organizan en Jena, junto con Novalis y Tieck, el círculo que le da nombre técnico al movimiento: publican la revista **Athenäum** (1798-1800), su órgano doctrinario. Ahí Friedrich Schlegel define la **poesía romántica** como una \"poesía universal progresiva\": un género que nunca se completa, que mezcla géneros, que reflexiona sobre sí mismo mientras se escribe.",
    },
    {
      type: "info",
      continues: true,
      title: "Los hermanos Schlegel y el romanticismo de Jena",
      body: "De esa autorreflexión permanente sale la **ironía romántica**: la obra que se sabe a la vez seria y una construcción arbitraria del artista, capaz de desmontarse a sí misma en cualquier momento. August Wilhelm, además, traduce a Shakespeare al alemán y fija buena parte del canon con el que el Romanticismo alemán lee la literatura extranjera.",
    },
    {
      type: "info",
      continues: true,
      title: "Los hermanos Schlegel y el romanticismo de Jena",
      body: "Del círculo de Jena participa también **Novalis**, seudónimo de Georg Philipp Friedrich von Hardenberg, cuya obra queda inconclusa por su muerte temprana pero que deja la imagen que mejor resume el anhelo romántico: la **flor azul**, un objeto de deseo que aparece en sueños y que el protagonista de su novela persigue sin encontrarlo nunca del todo. Es la Sehnsucht hecha símbolo: el anhelo que vale más por sí mismo que por cualquier objeto que pudiera saciarlo.",
    },
    {
      type: "quiz",
      question: "La ironía romántica que definen los Schlegel es la idea de que la obra…",
      options: [
        "se sabe una construcción arbitraria, capaz de desmontarse",
        "burla a su público con juegos de palabras constantes",
        "nunca puede tomarse en serio ni comunicar nada real",
        "imita con precisión las reglas del arte clásico griego",
      ],
      answer: 0,
      explain: "De la autorreflexión permanente que Friedrich Schlegel exige a la «poesía universal progresiva» —un género que nunca se completa y mezcla géneros— sale la ironía romántica: la obra que se sabe a la vez seria y una construcción arbitraria del artista, capaz de desmontarse a sí misma en cualquier momento.",
    },
    {
      type: "info",
      title: "Herder: lengua, pueblo y nación",
      body: "Así como del ánimo ilustrado sale el liberalismo, del Romanticismo sale el **nacionalismo**. La fuente principal es **Johann Gottfried Herder**, que en su Tratado sobre el origen del lenguaje (1772) y en sus Ideas para una filosofía de la historia de la humanidad (1784-1791) sostiene que los hombres existen para expresarse, y que esa expresión se transmite ante todo por la **lengua**.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "Para Herder, lo que distingue a un pueblo es su lengua propia: las palabras que una persona comparte con las demás son un vínculo irreductible, no traducible sin pérdida a otra lengua. De ahí su tesis más incómoda para el optimismo ilustrado: cada época y cada pueblo tiene su propio centro de gravedad, y no debe medirse con la vara de las épocas posteriores. Contra la teleología del progreso, Herder propone un pluralismo de culturas igualmente válidas en su propio tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "Para acceder a ese centro de gravedad ajeno hace falta un método distinto del de las ciencias duras: no medir ni clasificar desde afuera, sino un ejercicio de **empatía histórica**, meterse por así decirlo dentro de la piel de una época o un pueblo distintos para comprenderlos en sus propios términos, no en los del observador. Ese método empático, más que cualquier doctrina política puntual, es lo que Herder lega al historicismo del siglo siguiente, incluido el de Hegel.",
    },
    {
      type: "quiz",
      question: "Para comprender a un pueblo distinto, el método que propone Herder es…",
      options: [
        "medirlo y clasificarlo con las categorías de las ciencias duras",
        "meterse por empatía en sus propios términos históricos",
        "esperar a que ese pueblo alcance el nivel de la propia época",
        "traducir su lengua a la lengua dominante para compararlo",
      ],
      answer: 1,
      explain: "Herder propone un método distinto del de las ciencias duras: no medir ni clasificar desde afuera, sino un ejercicio de empatía histórica, meterse en la piel de una época o un pueblo para comprenderlos en sus propios términos. Contra la teleología del progreso, defiende un pluralismo de culturas igualmente válidas en su tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "Herder: lengua, pueblo y nación",
      body: "La consecuencia política de esa idea es enorme: si cada pueblo tiene un alma propia expresada en su lengua, entonces los pueblos con lengua e historia comunes tienen, en principio, derecho a una existencia política propia. De esa premisa, más filosófica que partidaria en el propio Herder, se alimentan después los nacionalismos lingüísticos del siglo XIX que reclaman un Estado para cada comunidad de habla.",
    },
    {
      type: "quiz",
      question: "El nacionalismo romántico de Herder parte de la idea de que…",
      options: [
        "las naciones se forman por un contrato entre iguales",
        "una nación vale por el territorio que logra defender",
        "la razón universal borra las diferencias entre pueblos",
        "las naciones tienen alma propia, como los individuos",
      ],
      answer: 3,
      explain: "Así como del ánimo ilustrado sale el liberalismo, del Romanticismo sale el nacionalismo: si cada alma individual es irreductible, también lo es la de cada nación. Los hombres existen para expresarse, la expresión se transmite mediante la lengua, y por eso la lengua compartida es el vínculo decisivo.",
    },
    {
      type: "info",
      title: "Consecuencias y rasgos del Romanticismo",
      body: "De la primacía de la voluntad y la autenticidad se sigue el enorme valor de la **sinceridad**: el motivo importa más que la consecuencia, y no traicionar los propios ideales se vuelve un imperativo absoluto, aunque cueste la vida. De ahí el potencial trágico de la época —los duelos por amor, el sacrificio por la persona amada—: **la tragedia es endémica a la condición humana** cuando dos ideales igualmente puros chocan entre sí.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "Ese fetichismo del motivo por encima de la consecuencia tiene, sin embargo, un reverso incómodo, que la propia época no siempre advierte: si lo único que cuenta es la pureza de la intención, un acto puede provocar un desastre objetivo y aun así reclamar justificación moral plena, porque bastaría con haber querido bien. La misma lógica que produce héroes capaces de morir por un ideal produce también fanáticos incapaces de admitir que su ideal causó daño.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "**Nota sobre \"idealismo\".** El idealismo romántico es el imperativo de actuar y crear según los propios ideales. En Hegel y en Marx, en cambio, \"idealismo\" nombra algo distinto: lo que pertenece al reino de lo metafísico, por oposición a lo concreto y empírico. Conviene distinguir ambos sentidos desde ahora.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "La emoción, para ser auténtica, tiende a ser **violenta**: hay anhelos que no se dejan justificar racionalmente, y cada alma individual es irreductiblemente singular y preciosa. Esa desconfianza frente al racionalismo clasificador la resume **Goethe** con una imagen dirigida contra Moses Mendelssohn: la razón ilustrada trata la belleza como el entomólogo a las mariposas, la atrapa y la clava con un alfiler, hasta que todo su color se escurre y queda como muerta bajo el vidrio.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "De ahí también dos rasgos que van a marcar toda la estética romántica: la **poesía** como expresión de lo que no puede decirse de otro modo, y la idea de lo **sublime**, aquello demasiado vasto o intenso para ser puesto en palabras.",
    },
    {
      type: "classify",
      question: "¿Cada uso de «idealismo» es el romántico o el metafísico?",
      groups: ["Romántico", "Metafísico"],
      items: [
        { text: "El imperativo de actuar y crear según tus ideales", group: 0 },
        { text: "Vivir auténticamente conforme a lo que uno cree", group: 0 },
        { text: "Estar dispuesto a sacrificarse por un ideal", group: 0 },
        { text: "Lo que pertenece al reino de lo metafísico", group: 1 },
        { text: "Lo que se opone a lo concreto y lo empírico", group: 1 },
        { text: "El sentido que va a importar con Hegel y Marx", group: 1 },
      ],
      explain: "El idealismo romántico es una ética: vivir y crear según los propios ideales, no traicionarlos a ningún costo. El idealismo metafísico es una tesis sobre qué hay: lo que pertenece al reino de las ideas por oposición a lo concreto y empírico. Con Hegel y Marx sólo va a importar el segundo.",
    },
    {
      type: "info",
      title: "La Revolución Francesa y el Terror",
      body: "Una manera de leer la Revolución Francesa es que el **Terror es el momento en que la Ilustración se vuelve Romanticismo**: lo que empieza como un proyecto racional de implementar el liberalismo y la Declaración de los Derechos del Hombre deriva, entre 1793 y 1794, en una violencia que ya no responde a ningún cálculo racional sino a la misma lógica de la voluntad absoluta y sin freno que cultiva el ánimo romántico.",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa y el Terror",
      body: "El Comité de Salvación Pública gobierna entonces invocando, precisamente, la voluntad general de Rousseau: no la suma verificable de votos individuales, sino una voluntad del pueblo entero que sus dirigentes dicen encarnar sin necesidad de que cada ciudadano la ratifique. Quien se opone no disiente de una mayoría contable, sino de la Nación como totalidad, y por eso puede ser tratado no como adversario político sino como enemigo a eliminar: la pureza revolucionaria, como la autenticidad romántica, no admite matices.",
    },
    {
      type: "quiz",
      question: "Leer el Terror como el momento en que la Ilustración se vuelve Romanticismo quiere decir que…",
      options: [
        "los revolucionarios eran románticos desde el principio",
        "un proyecto racional termina en una orgía de sangre",
        "la Declaración de Derechos era un texto romántico",
        "el Romanticismo alemán provocó la Revolución francesa",
      ],
      answer: 1,
      explain: "Lo que empezó como un intento ilustrado y racional de implementar el liberalismo y la Declaración de los Derechos del Hombre se transforma en el Terror de 1793-94. No es que los actores cambiaran de bando: es que la fetichización del motivo y el desprecio por las consecuencias —rasgos románticos— se apoderan de un proyecto que se pensaba puramente racional.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada figura con lo que aporta al Romanticismo",
      pairs: [
        { left: "Rousseau", right: "La autenticidad y la nostalgia del estado de naturaleza" },
        { left: "Kant", right: "La primacía de la voluntad y el libre albedrío" },
        { left: "Fichte", right: "Ser libre no es nada; devenir libre lo es todo" },
        { left: "Herder", right: "El alma de las naciones y la lengua como vínculo" },
        { left: "Dostoievski", right: "El hombre del subsuelo, que no quiere ser racional" },
      ],
      explain: "Las cinco piezas del legado: Rousseau da la autenticidad y el modelo de la nostalgia, Kant la primacía de la voluntad que los románticos llevan al extremo, Fichte el pasaje del ser al devenir, Herder el salto del alma individual al alma de las naciones, y Dostoievski la crítica más ceñida a la razón ilustrada, lo que Shestov llamó la verdadera crítica de la razón pura.",
    },
    {
      type: "info",
      title: "Conclusiones: el legado del Romanticismo",
      body: "El Romanticismo funciona como el **alter ego de la Ilustración** y deja como legado una subjetividad radical vivida como tormento permanente. De ahí salen, entre otros, **Nietzsche** —un pensador posromántico—, el **irracionalismo** entendido como virtud en sí misma, buena parte del **existencialismo** posterior y elementos que van a reaparecer en el **psicoanálisis** freudiano.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "Ninguno de esos herederos toma el legado romántico intacto: cada uno retiene alguna pieza —la primacía de la voluntad, el valor de la autenticidad, la desconfianza hacia la razón calculadora, la fascinación por lo oscuro y lo instintivo— y la separa del resto del sistema. Es, en ese sentido, menos una escuela que se transmite entera que una caja de herramientas conceptuales que el siglo siguiente va a desarmar y reutilizar por partes.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "Una de las críticas más explícitas del ideal ilustrado desde esta sensibilidad la da **Dostoievski**, escritor posromántico y protoexistencialista. Sus Memorias del subsuelo son, en ese sentido, casi un tratado: el filósofo Lev Shestov llegó a llamarlas la verdadera \"crítica de la razón pura\", no la de Kant. El hombre del subsuelo dice:",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "Verán, señores, la razón es sin duda una cosa excelente, pero la razón no es más que razón, y satisface únicamente la capacidad racional del hombre, mientras que los deseos son una manifestación de la vida entera. El hombre a veces es extremadamente aficionado al sufrimiento, hasta la pasión. La civilización no hace más que desarrollar en el hombre la capacidad para una mayor variedad de sensaciones, y absolutamente nada más; y a través del desarrollo de esa capacidad, el hombre puede llegar incluso a encontrar placer en el derramamiento de sangre.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "**Hegel** va a intentar reconciliar exactamente esta tensión entre razón ilustrada y voluntad romántica, tomando de cada lado lo que el otro le niega: la historia como componente de la filosofía, y la reconciliación como su meta declarada.",
    },
  ],
};
