export default {
  num: 22,
  transcript: 23,
  title: "\"Antipolítica\" y la filosofía de la disidencia",
  source: "https://www.youtube.com/watch?v=94b025iHtAw",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "Esta clase se mueve del oeste al este de Europa, de Francia a Polonia y Checoslovaquia, en el mismo período posterior a 1968. El centro está en cuatro figuras: **Leszek Kołakowski** (1927-2009), filósofo polaco expulsado del Partido Comunista en 1966; **Adam Michnik** (n. 1946), su alumno, historiador y activista encarcelado varias veces; **Jan Patočka** (1907-1977), fenomenólogo checo, alumno de Husserl y de Heidegger; y **Václav Havel** (1936-2011), dramaturgo checoslovaco, preso político y luego primer presidente poscomunista de su país.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El texto que organiza la clase es el ensayo de Havel El poder de los sin poder (1978), escrito en la clandestinidad y dedicado a la memoria de Patočka. A su lado están la **Carta 77**, documento colectivo firmado el 1.º de enero de 1977, y el ensayo del húngaro **György Konrád**, difundido en samizdat a comienzos de los ochenta, que le da nombre a la corriente entera: Antipolítica.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "El dato que funciona como emblema es la muerte de Patočka en marzo de 1977: pocas semanas después de convertirse en uno de los tres primeros voceros de la Carta 77, un hombre de 69 años y salud frágil es sometido a interrogatorios policiales agotadores y no sobrevive. Su funeral se transforma en un acto de movilización que el régimen intenta reprimir.",
    },
    {
      type: "match",
      question: "Uní cada figura con su país y su rol en la disidencia",
      pairs: [
        { left: "Kołakowski", right: "Filósofo polaco expulsado del Partido Comunista en 1966" },
        { left: "Michnik", right: "Alumno de Kołakowski, historiador y activista encarcelado" },
        { left: "Patočka", right: "Fenomenólogo checo, alumno de Husserl y de Heidegger" },
        { left: "Havel", right: "Dramaturgo checoslovaco, preso político y luego presidente" },
      ],
      explain: "Las dos parejas polacas —Kołakowski y su alumno Michnik— y las dos checas —Patočka y Havel— organizan esta clase, que se mueve del oeste al este de Europa en el período posterior a 1968.",
    },
    {
      type: "info",
      title: "El problema que la disidencia hereda",
      body: "La crítica posestructuralista más radical —la que desarma la noción de significado estable, de sujeto autónomo y de verdad como correspondencia— deja abierta una pregunta más práctica que teórica: si la verdad, la realidad y la subjetividad son, como sugieren los posmodernistas, construcciones discursivas entre otras, ¿qué fundamento le queda a la **responsabilidad**? ¿Sobre qué base se puede resistir a un poder que también manipula el lenguaje y fabrica su propia versión de lo real?",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que la disidencia hereda",
      body: "En Europa del Este esa pregunta no llega por la vía de la teoría, sino por la experiencia directa de vivir bajo regímenes que gobiernan fabricando una realidad oficial que nadie cree pero que todos repiten. La filosofía de la disidencia que surge allí en los años setenta responde justo donde el posestructuralismo dejó la pregunta abierta: afirmando que verdad y subjetividad no se oponen, sino que se fundan mutuamente, y que esa fundación se llama responsabilidad.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que la disidencia hereda",
      body: "Hay además un segundo problema heredado, más concreto: el **colapso del marxismo** como ideología viva, como el último de los grandes relatos capaces de dar sentido y dirección a la historia. Ese colapso, consumado en 1968, deja un vacío que la disidencia del Este llena con un lenguaje distinto: el de los derechos humanos y la verdad vivida, no el de una nueva utopía histórica.",
    },
    {
      type: "quiz",
      question: "¿Dónde responde la filosofía de la disidencia a la pregunta que deja abierta el posestructuralismo?",
      options: [
        "En la experiencia directa de vivir bajo una realidad oficial fabricada",
        "En seminarios universitarios sobre teoría literaria francesa",
        "En la reforma económica de los partidos comunistas del Este",
        "En la traducción al checo de los textos de Derrida y Foucault",
      ],
      answer: 0,
      explain: "En Europa del Este la pregunta por el fundamento de la responsabilidad no llega por la teoría, sino por vivir bajo regímenes que gobiernan fabricando una realidad oficial que nadie cree pero que todos repiten.",
    },
    {
      type: "info",
      title: "Polonia: de 1956 a 1968",
      body: "En octubre de 1956, meses después del discurso secreto de Jrushchov sobre los crímenes de Stalin, Polonia vive el llamado **Octubre polaco**: un giro reformista dentro del propio Partido Comunista que parece inaugurar una etapa de marxismo revisionista, crítico del estalinismo pero todavía convencido de la posibilidad de un socialismo humano.",
    },
    {
      type: "info",
      continues: true,
      title: "Polonia: de 1956 a 1968",
      body: "Diez años después, en 1966, **Kołakowski** —entonces profesor en Varsovia, revisionista, aún miembro del Partido— es invitado por sus propios estudiantes a dar una conferencia por el aniversario. La charla es durísima: ninguna de las promesas del Octubre se cumplió, y el régimen ya no está lleno de creyentes, sino de oportunistas que llegan al poder por lo que Kołakowski llama **selección negativa**, un mecanismo por el cual son los menos capaces de conciencia y responsabilidad quienes ascienden. La dirigencia lo expulsa del Partido.",
    },
    {
      type: "short",
      question: "¿Cómo llama Kołakowski al mecanismo por el que ascienden los menos capaces de conciencia?",
      answers: ["selección negativa"],
      explain: "Selección negativa: un mecanismo por el cual son los menos capaces de conciencia y responsabilidad quienes ascienden en el régimen. Kołakowski lo describe en 1966, poco antes de ser expulsado del Partido por decirlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Polonia: de 1956 a 1968",
      body: "En marzo de 1968, los estudiantes de Kołakowski —entre ellos Michnik, todos de la generación nacida después de la guerra— se rebelan contra la censura. El régimen reprime con violencia y encarcela a buena parte de los líderes, bajo la etiqueta oficial de campaña \"antisionista\", eufemismo de una persecución antisemita. Fue el fin de la fe en un marxismo reformable: eran precisamente los estudiantes que leían al joven Marx quienes quedaban desengañados.",
    },
    {
      type: "info",
      continues: true,
      title: "Polonia: de 1956 a 1968",
      body: "Meses más tarde, en agosto de 1968, la **invasión del Pacto de Varsovia** aplasta el experimento del \"socialismo con rostro humano\" en Checoslovaquia. Los dos hechos —la represión de marzo en Polonia y la invasión de agosto— cierran, para toda una generación, la posibilidad de reformar el comunismo desde adentro.",
    },
    {
      type: "quiz",
      question: "¿Qué cierran juntos, para esa generación, marzo y agosto de 1968?",
      options: [
        "La posibilidad de reformar el comunismo desde adentro",
        "La posibilidad de una guerra abierta entre bloques",
        "La circulación de la Carta 77 dentro de Checoslovaquia",
        "El acceso de Kołakowski a la cátedra de Varsovia",
      ],
      answer: 0,
      explain: "La represión de los estudiantes en marzo en Polonia y la invasión del Pacto de Varsovia en agosto en Checoslovaquia cierran, juntas, la fe en un marxismo reformable desde dentro del propio sistema.",
    },
    {
      type: "info",
      title: "El fin del marxismo como el último gran relato",
      body: "Para la generación de los padres, mayores de cuarenta, que le habían dado la vida entera a esa cosmovisión, renunciar al marxismo era experimentar la negación de la propia biografía. La sensación generalizada es de colapso total: el pensamiento que prometía llevar hacia una utopía queda sin destino, sin nada previsto para reemplazarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "El fin del marxismo como el último gran relato",
      body: "De esas cenizas surgen dos respuestas distintas a un lado y otro de la cortina de hierro. En Europa Occidental, el vacío lo ocupa en buena medida el posestructuralismo francés, que sigue leyendo la historia en clave de sospecha hacia todo sistema cerrado. En Europa del Este, en cambio, surge algo distinto: una filosofía de la **verdad vivida**, menos interesada en desarmar sistemas que en sostener, contra el régimen, que hay algo real que defender.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde a la respuesta de Europa Occidental o de Europa del Este?",
      groups: ["Europa Occidental", "Europa del Este"],
      items: [
        { text: "Sospecha hacia todo sistema cerrado, incluida la verdad", group: 0 },
        { text: "Filosofía de la verdad vivida, algo real que defender", group: 1 },
        { text: "El vacío lo llena en buena medida el posestructuralismo", group: 0 },
        { text: "El vacío lo llena el lenguaje de los derechos humanos", group: 1 },
      ],
      explain: "Al colapsar el marxismo como último gran relato, Occidente responde desarmando sistemas con el posestructuralismo francés; el Este responde sosteniendo, contra el régimen, que la verdad y la responsabilidad son algo real.",
    },
    {
      type: "info",
      title: "Checoslovaquia: la Normalización",
      body: "Después de la Primavera de Praga y la invasión, nadie en Checoslovaquia puede sostener que los tanques soviéticos llegaron a pedido de alguien: el nuevo régimen neoestalinista es evidentemente impuesto desde afuera. Aun así, la población en general lo acepta y no se resiste. Al período que sigue se lo llama, con un eufemismo más, **Normalización**.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: la Normalización",
      body: "El nuevo gobierno instalado por Moscú desvía una parte importante del presupuesto de inversión hacia el consumo, y el nivel de vida sube. La lectura que se hace después es dura: buena parte de la sociedad checoslovaca cambia su libertad por bienes de consumo y estabilidad doméstica, en un pacto tácito de resignación a cambio de bienestar material.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: la Normalización",
      body: "La metáfora que circula para describir ese régimen es la parábola del **Gran Inquisidor** de Dostoievski, en Los hermanos Karamázov: Cristo vuelve a la Tierra durante la Inquisición y es encarcelado de inmediato, porque el Inquisidor sabe que la gente no quiere la libertad que él ofrece, sino seguridad y pan asegurado. El secreto final del Inquisidor es que él mismo no cree en Dios. Aplicada al comunismo tardío, la lectura es que el Partido ya no cree en el comunismo, y todos lo saben, y aun así todos repiten el lenguaje oficial.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: la Normalización",
      body: "El símbolo de ese lenguaje fingido es la fórmula con que se llamó oficialmente a la invasión de 1968: **\"asistencia fraternal\"**. Bajo la Normalización no hay terror sistemático ni juicios-espectáculo como en el estalinismo puro, pero tampoco hay creyentes: hay una sociedad entera que sabe que vive una mentira colectiva y que, aun así, la sostiene.",
    },
    {
      type: "quiz",
      question: "¿Cuál es, según la parábola del Gran Inquisidor aplicada al comunismo tardío?",
      options: [
        "Que el propio Partido ya no cree en el comunismo, y todos lo saben",
        "Que la Iglesia católica dirigía en secreto la política checoslovaca",
        "Que el pueblo exige más libertad de la que el régimen tolera",
        "Que Cristo habría apoyado sin reservas la invasión de 1968",
      ],
      answer: 0,
      explain: "El secreto del Inquisidor es que no cree en Dios; aplicado al comunismo tardío, la lectura es que el Partido ya no cree en el comunismo, y todos lo saben, y aun así todos repiten el lenguaje oficial.",
    },
    {
      type: "info",
      title: "Helsinki y el lenguaje de los derechos humanos",
      body: "En 1975, en pleno período de distensión de la Guerra Fría, se firman los **Acuerdos de Helsinki**: las potencias occidentales reconocen las fronteras europeas de posguerra a cambio de que el bloque soviético se comprometa, sobre el papel, a respetar los derechos humanos y las libertades fundamentales. Los gobiernos comunistas firman sin intención de cumplir, pero ese gesto tiene una consecuencia que no previeron.",
    },
    {
      type: "info",
      continues: true,
      title: "Helsinki y el lenguaje de los derechos humanos",
      body: "Tras el colapso de la fe en el marxismo, ese lenguaje universal y abstracto de los **derechos humanos** llena el vacío ideológico: es el idioma que la disidencia del Este usa para exigirle al régimen que cumpla lo que él mismo firmó, sin necesidad de proponer un sistema político alternativo ni una vuelta al capitalismo.",
    },
    {
      type: "quiz",
      question: "¿Qué consecuencia imprevista tienen los Acuerdos de Helsinki de 1975?",
      options: [
        "Le dan a la disidencia un lenguaje para exigir lo que el régimen firmó",
        "Provocan de inmediato la caída de los gobiernos comunistas del Este",
        "Anulan por completo las fronteras de posguerra reconocidas allí",
        "Instalan tropas occidentales de observación en los países firmantes",
      ],
      answer: 0,
      explain: "Los gobiernos comunistas firman Helsinki sin intención de cumplir, pero eso les da a los disidentes un lenguaje universal y abstracto —los derechos humanos— para exigirles que respeten lo que ellos mismos firmaron.",
    },
    {
      type: "info",
      title: "El episodio que activa a Havel",
      body: "A mediados de los setenta surge en Checoslovaquia una banda de rock, los **Plastic People of the Universe**, influida por la contracultura occidental y por Velvet Underground. Su mánager, **Ivan Jirous**, historiador del arte y organizador carismático, entiende que ese grupo y la \"segunda cultura\" alternativa que representa van a necesitar el respaldo de una figura intelectual con conexiones fuera del país. Recurre a **Václav Havel**, dramaturgo ya conocido, con vínculos con filósofos como Patočka.",
    },
    {
      type: "info",
      continues: true,
      title: "El episodio que activa a Havel",
      body: "Havel escucha una grabación de la banda y tiene lo que describe como una epifanía: comprende que, más allá de la calidad musical o del vocabulario vulgar de las letras, la verdad está del lado de esos músicos, y que lo que enfrentan no es una disputa entre facciones políticas sino un ataque del sistema totalitario contra la libertad espiritual e intelectual como tal. Poco después toda la banda es arrestada. Havel moviliza a Patočka y a otros intelectuales para pedir apoyo internacional; los músicos igual van presos, pero el episodio pone en marcha algo mayor.",
    },
    {
      type: "quiz",
      question: "¿Qué comprende Havel al escuchar a los Plastic People of the Universe?",
      options: [
        "Que se ataca la libertad espiritual, más allá del gusto musical",
        "Que la banda merecía apoyo sólo por su calidad musical",
        "Que el conflicto era una simple disputa entre facciones políticas",
        "Que el régimen tenía razón en perseguir letras tan vulgares",
      ],
      answer: 0,
      explain: "Havel comprende que, más allá de la calidad musical o el vocabulario de las letras, la verdad está del lado de esos músicos: lo que enfrentan es un ataque del sistema totalitario contra la libertad espiritual e intelectual como tal.",
    },
    {
      type: "info",
      title: "La Carta 77",
      body: "A fines de 1976 Havel impulsa una carta que pida al gobierno checoslovaco respetar lo que había firmado en Helsinki, concebida no como oposición política sino como **declaración moral**. El 1.º de enero de 1977 se publica la **Carta 77**, firmada inicialmente por 242 personas: no propone ningún sistema alternativo, no tiene membresía formal ni estructura de partido, y se define como una comunidad libre de personas de distintas convicciones unidas por la voluntad de que se respeten los derechos humanos.",
    },
    {
      type: "info",
      continues: true,
      title: "La Carta 77",
      body: "De ahí sale el término **antipolítica**: la idea de que hacer oposición política dentro del sistema es ya ensuciarse las manos con su lógica, y que el único terreno genuinamente independiente está fuera de la política, en una fuerza moral que la trasciende. György Konrád le da nombre y desarrollo teórico a la noción en su ensayo homónimo, pero la practican en los hechos Havel, Patočka y los firmantes de la Carta.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la idea de que oponerse dentro del sistema ya ensucia las manos, y que hay que actuar fuera de la política?",
      answers: ["antipolítica"],
      explain: "Antipolítica: hacer oposición política dentro del sistema es ya ensuciarse con su lógica; el único terreno independiente está fuera de la política, en una fuerza moral que la trasciende. Konrád le da nombre; Havel y Patočka la practican.",
    },
    {
      type: "info",
      title: "Michnik y la sociedad civil como estrategia",
      body: "En Polonia, **Michnik** llega a una conclusión paralela por otro camino. En un ensayo influyente de mediados de los setenta sostiene que buscar reformar el Partido desde adentro, como había intentado la generación revisionista, es una vía agotada, y que también lo es soñar con derrocarlo por la fuerza. Propone en cambio construir, con paciencia y al margen del Estado, instituciones **independientes**: publicaciones clandestinas, universidades volantes, sindicatos libres, redes de ayuda mutua.",
    },
    {
      type: "info",
      continues: true,
      title: "Michnik y la sociedad civil como estrategia",
      body: "Esa estrategia —organizar una **sociedad civil** autónoma en los intersticios del sistema, en lugar de disputarle el poder al Estado de manera frontal— es la versión polaca de la antipolítica, y va a ser el método efectivo detrás de **Solidaridad** en los ochenta. Michnik y Havel llegan así, desde tradiciones distintas, a una misma conclusión estratégica: el cambio no se logra tomando el poder, sino construyendo, ya ahora, los espacios donde se vive como si el poder no tuviera la última palabra.",
    },
    {
      type: "quiz",
      question: "¿En qué se parecen las estrategias de Michnik y de Havel?",
      options: [
        "Ambos apuestan a construir espacios independientes de poder",
        "Ambos proponen derrocar al régimen por la vía armada",
        "Ambos confían en que el Partido se reforme desde adentro",
        "Ambos rechazan cualquier lenguaje de derechos humanos",
      ],
      answer: 0,
      explain: "Michnik propone una sociedad civil independiente en Polonia; Havel, la antipolítica y vivir en la verdad en Checoslovaquia. Desde tradiciones distintas llegan a la misma conclusión: construir ya los espacios donde el poder no tenga la última palabra.",
    },
    {
      type: "info",
      title: "Jan Patočka: filósofo y vocero",
      body: "**Patočka** había sido, en 1933, alumno de Husserl y también de Heidegger, y su obra entera puede leerse como un diálogo entre ambos. Durante la ocupación nazi y bajo el estalinismo se mantuvo al margen, sin colaborar pero sin resistir tampoco: se retiró a su estudio. Tradujo al checo la Fenomenología del espíritu de Hegel, fue expulsado de la universidad por el régimen estalinista, volvió con la Primavera de Praga y fue jubilado por la fuerza durante la Normalización.",
    },
    {
      type: "info",
      continues: true,
      title: "Jan Patočka: filósofo y vocero",
      body: "Jubilado, sigue enseñando en privado, en su departamento: durante los años setenta dirige un seminario clandestino donde se lee, en voz alta y en alemán, Ser y tiempo de Heidegger. Cuando Havel le pide ser uno de los tres primeros voceros de la Carta 77, acepta pese a no haberse expuesto nunca así. Muere semanas después, en marzo de 1977, tras los interrogatorios policiales.",
    },
    {
      type: "info",
      title: "La montaña de Śnieżka",
      body: "En 1978, contactos entre los firmantes de la Carta 77 y disidentes polacos permiten un encuentro en la cima del monte **Śnieżka**, en la frontera entre ambos países: allí se reúnen Havel, Michnik y otros, entre ellos Jacek Kuroń. Del encuentro sale un pedido de Michnik a Havel: un ensayo con sus ideas sobre la resistencia cotidiana, para publicarlo en samizdat en Polonia. Meses después llega a Varsovia, cruzando la frontera de mano en mano, el manuscrito de El poder de los sin poder.",
    },
    {
      type: "info",
      title: "La parábola del verdulero",
      body: "El ensayo de Havel se organiza alrededor de una imagen: un verdulero checoslovaco pone cada día en su vidriera el cartel \"¡Trabajadores del mundo, uníos!\". Nadie lo cree —ni los clientes, ni el régimen, ni el propio verdulero—, y todos saben que los demás tampoco lo creen. Aun así, el cartel se sigue poniendo, porque negarse tiene un costo: delaciones, interrogatorios, pérdida de privilegios para los hijos.",
    },
    {
      type: "info",
      continues: true,
      title: "La parábola del verdulero",
      body: "Havel plantea una hipótesis: si un día todos los verduleros retiraran el cartel a la vez, eso sería el comienzo de una revolución. De ahí concluye que el verdulero no es tan impotente como parece, y que, por serlo, es también **responsable**, y en algún sentido cómplice, de que el sistema siga funcionando. El texto es deliberadamente antipopulista: no exime a nadie, y traza la línea entre víctima y sostén del régimen atravesando a cada persona por igual.",
    },
    {
      type: "quiz",
      question: "¿Por qué el verdulero no es, para Havel, tan impotente como parece?",
      options: [
        "Porque si todos dejaran el cartel a la vez, habría revuelta",
        "Porque en realidad tiene poder político dentro del Partido",
        "Porque puede elegir libremente el precio de su mercadería",
        "Porque el régimen depende económicamente de su comercio",
      ],
      answer: 0,
      explain: "Si un día todos los verduleros retiraran el cartel a la vez, eso sería el comienzo de una revolución. Por eso el verdulero es también responsable, y en algún sentido cómplice, de que el sistema siga funcionando.",
    },
    {
      type: "info",
      continues: true,
      title: "La parábola del verdulero",
      body: "Havel llama a esa situación **vivir en la mentira**: no solo la mentira pública sobre la fe en el sistema, sino la mentira más profunda que cada uno se dice a sí mismo sobre su propia impotencia. Frente a eso propone **vivir en la verdad**: la ruptura con el papel que el sistema espera de cada uno, un gesto que retoma de Heidegger la idea de autenticidad pero la vuelve explícitamente moral, ligada al llamado de la conciencia y a la responsabilidad por las consecuencias.",
    },
    {
      type: "info",
      title: "La polis paralela y el costo de la verdad",
      body: "De la misma comunidad de la Carta 77 sale la idea, formulada por Václav Benda, de una **\"polis paralela\"**: una sociedad autoorganizada donde se practican, a escala reducida, formas de vida y de trabajo regidas por la verdad y no por la mentira oficial. Vivir en la verdad, sin embargo, no es gratuito ni moralmente sencillo.",
    },
    {
      type: "info",
      continues: true,
      title: "La polis paralela y el costo de la verdad",
      body: "En una de sus piezas breves de los años setenta, protagonizada por su alter ego **Ferdinand Vaněk**, Havel muestra esa ambigüedad: un intelectual disidente que perdió su empleo consigue trabajo en una cervecería gracias a un capataz que, a cambio, debe informar semanalmente sobre él a la policía secreta. El capataz le pide a Vaněk que escriba los informes él mismo, ya que es escritor; Vaněk se niega por principio, y el capataz estalla, acusándolo de dejarlo cargar con la parte sucia mientras él queda con las manos limpias.",
    },
    {
      type: "info",
      continues: true,
      title: "La polis paralela y el costo de la verdad",
      body: "Ese pasaje muestra que en el sistema **todos están implicados** de algún modo: el capataz, el disidente y el régimen mismo. No hay elecciones inocentes, y sostener un principio tiene siempre un costo que otro paga.",
    },
    {
      type: "quiz",
      question: "¿Qué muestra el episodio de Vaněk y el capataz de la cervecería?",
      options: [
        "Que todos quedan implicados, sin elecciones inocentes",
        "Que sólo el capataz carga con la culpa moral del sistema",
        "Que negarse a informar a la policía no tiene ningún costo",
        "Que Vaněk logra escapar por completo de la vigilancia policial",
      ],
      answer: 0,
      explain: "El capataz, el disidente y el régimen mismo quedan todos implicados: sostener un principio —negarse a escribir los informes— tiene siempre un costo, y ese costo lo termina pagando otro, el capataz.",
    },
    {
      type: "info",
      title: "La verdad como algo real",
      body: "Havel no llega a estas ideas desde el liberalismo occidental, sino desde una forma de heideggerianismo que le transmite Patočka. Insiste en que la verdad es algo **real**, y una prueba de eso es que la mentira también lo es: en el modelo del verdulero, la realidad de la verdad se verifica por contraste con la realidad de la mentira que la sostiene.",
    },
    {
      type: "info",
      continues: true,
      title: "La verdad como algo real",
      body: "Kołakowski llega a una conclusión emparentada por otra vía: el problema del puente entre sujeto y objeto sigue siendo insoluble, ningún intento de fundar una verdad absoluta tiene éxito, pero abandonar la búsqueda de la verdad equivale a abandonar la ética. Hay que seguir buscando aunque la meta no sea del todo alcanzable. En ambos, una **subjetividad robusta** no relativiza la verdad: la funda. Verdad y subjetividad quedan unidas por la responsabilidad.",
    },
    {
      type: "match",
      question: "Uní cada concepto de la disidencia con lo que nombra",
      pairs: [
        { left: "Selección negativa", right: "Ascienden los menos capaces de conciencia y responsabilidad" },
        { left: "Vivir en la mentira", right: "Repetir un lenguaje ritualizado que nadie cree, ni el propio hablante" },
        { left: "Antipolítica", right: "Resistir desde una fuerza moral, fuera de la lógica del poder" },
        { left: "Sociedad civil", right: "Instituciones independientes construidas al margen del Estado" },
        { left: "Vivir en la verdad", right: "Romper con el papel que el sistema espera de cada uno" },
      ],
      explain: "Bajo la selección negativa y la mentira compartida, la disidencia responde con antipolítica: construir sociedad civil (Michnik) y vivir en la verdad (Havel), dos caminos hacia una misma conclusión, unidos por la responsabilidad.",
    },
    {
      type: "info",
      title: "Herencia: 1989 y después",
      body: "La revolución de 1989 confirma en los hechos lo que la disidencia había sostenido en la clandestinidad. Havel, liberado a mediados de los ochenta tras años de prisión, es elegido primer presidente poscomunista de Checoslovaquia en diciembre de ese año. En su primer discurso ante el Congreso de Estados Unidos afirma que la conciencia precede al ser, invirtiendo deliberadamente la fórmula marxista según la cual el ser social determina la conciencia: el punto de partida sigue siendo el sujeto y su responsabilidad, no las condiciones materiales.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: 1989 y después",
      body: "Ese vocabulario —verdad como algo que se vive y no solo se argumenta, subjetividad fundada en la responsabilidad, sociedad civil construida desde abajo— queda disponible como contrapunto para cuando la propia noción de verdad vuelva a ponerse en cuestión, ya no desde la crítica filosófica de las estructuras sino desde la manipulación política directa de la realidad.",
    },
  ],
};
