export default {
  num: 24,
  transcript: 25,
  title: "De la modernidad a la posmodernidad",
  source: "https://www.youtube.com/watch?v=teqykibLJwE",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "La **posmodernidad** no tiene una fecha de nacimiento única, pero admite una convencional: 1979, año en que Jean-François Lyotard publica La condición posmoderna. Es la reacción, tardía, de una generación de pensadores franceses y alemanes ante la catástrofe totalitaria del siglo XX: si el nazismo y el estalinismo fueron, cada uno a su modo, la Ilustración vuelta ingeniería social a gran escala, la pregunta que hereda la segunda mitad del siglo es qué queda de la razón, la verdad y el progreso después de esa catástrofe.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Los nombres que definen esa respuesta —**Jean-François Lyotard** (1924-1998), **Jean Baudrillard** (1929-2007), **Fredric Jameson** (1934-2024) y **Jürgen Habermas** (n. 1929)— no coinciden en el diagnóstico: los tres primeros leen la modernidad como un proyecto agotado; Habermas, en cambio, la defiende como un proyecto **inacabado**, no fracasado. Esa discusión —¿hay que abandonar la Ilustración o completarla?— organiza buena parte del pensamiento europeo de fin de siglo y sigue abierta en el debate contemporáneo sobre la posverdad.",
    },
    {
      type: "classify",
      question: "¿Cada pensador lee la modernidad como agotada o como inacabada?",
      groups: ["Proyecto agotado", "Proyecto inacabado"],
      items: [
        { text: "Lyotard", group: 0 },
        { text: "Baudrillard", group: 0 },
        { text: "Jameson", group: 0 },
        { text: "Habermas", group: 1 },
      ],
      explain: "Lyotard, Baudrillard y Jameson leen la modernidad como un proyecto agotado que hay que abandonar o superar. Habermas es el gran disidente: la defiende como un proyecto inacabado, no fracasado, que todavía puede completarse.",
    },
    {
      type: "info",
      title: "El problema que hereda: dos sentidos de \"verdad\"",
      body: "En noviembre de 2019, durante el primer juicio político a Donald Trump, el teniente coronel **Alexander Vindman** testificó ante el Congreso sobre una llamada telefónica en la que Trump había presionado al presidente ucraniano Volodímir Zelenski para que investigara a un rival político suyo. Vindman, que había llegado de niño a Estados Unidos huyendo de la Ucrania soviética, abrió su testimonio agradeciéndole a su padre haberlo sacado de la Unión Soviética, y afirmó que en ese país no había que tener miedo de decir la verdad.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: dos sentidos de \"verdad\"",
      body: "Esa invocación de la \"verdad\" no era la del inglés corriente, ni la de la correspondencia entre un enunciado y los hechos: era la verdad tal como la usaron los disidentes del comunismo, empezando por **Václav Havel**, la verdad como aquello que salva, que da sentido a la vida, que funda la subjetividad, aquello por lo que se vive y se muere. Esa doble acepción —la epistemológica y la existencial— recorre toda la historia intelectual posterior a la Ilustración y permite seguir su hilo hasta el presente.",
    },
    {
      type: "quiz",
      question: "¿Qué sentido de \"verdad\" invoca Vindman al testificar ante el Congreso?",
      options: [
        "El existencial de los disidentes del comunismo del Este",
        "El puramente jurídico de un testimonio bajo juramento",
        "El matemático de una demostración lógica formal",
        "El literario de una metáfora sin pretensión de verdad",
      ],
      answer: 0,
      explain: "No era la verdad como mera correspondencia entre un enunciado y los hechos, sino la verdad tal como la usaron los disidentes del comunismo, empezando por Havel: aquello que funda la subjetividad, por lo que se vive y se muere.",
    },
    {
      type: "info",
      title: "La Ilustración como historia de amor",
      body: "La Ilustración se contrasta con el Romanticismo, pero es en sí misma una historia romántica: una historia de amor con la **razón humana** y su potencial, la capacidad de razonar, pensar y comprender el mundo tal como es. De ahí el concepto cartesiano del yo como \"el que piensa\": lo que nos hace humanos es ser seres pensantes, y la verdad es algo a lo que se llega por la razón.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como historia de amor",
      body: "La Ilustración reemplaza a Dios y la tradición por la ciencia, la racionalidad y la exaltación del potencial humano: el júbilo por la capacidad de asir el mundo, conocer su verdad y así mejorarlo. Es la base del **liberalismo político**: porque los seres humanos están dotados de razón y pueden alcanzar la verdad, merecen crear su propio gobierno; la soberanía popular depende de respetarlos como seres pensantes.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como historia de amor",
      body: "Su ánimo era menos fogoso que el romántico, más de calma, clasificación y orden: la analogía del **rompecabezas** de Isaiah Berlin —el mundo como un gran rompecabezas cuyas piezas, puestas una a una, acercan al todo— capta ese sentido de movimiento hacia adelante, donde cada pieza bien puesta es un paso y nunca un retroceso. Más que una ideología, es un ánimo y una actitud.",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración como historia de amor",
      body: "Debajo de todo acecha la amenaza de la **ausencia de Dios**. Zygmunt Bauman describe a Dios en una prolongada licencia de la que puede volver o no: la amenaza de la falta de suelo, la **Bodenlosigkeit** que atraviesa el curso entero. Sin Dios, ¿qué funda al mundo? ¿Cómo asegurar siquiera que lo que se ve corresponde con lo que hay? ¿Puede la razón estar a la altura de esa pregunta?",
    },
    {
      type: "short",
      question: "¿Cómo llama Arendt a la falta de fundamento que acecha bajo el optimismo racional moderno?",
      answers: ["bodenlosigkeit", "falta de suelo"],
      explain: "Bodenlosigkeit: la falta de suelo. Bauman describe a Dios «en una prolongada licencia» de la que puede volver o no. Reaparece en el Dasein sin fundamento de Heidegger y, después, en la posverdad contemporánea.",
    },
    {
      type: "info",
      title: "Teleología, subjetividad y estructura",
      body: "Con Hegel y Marx se intensifica el tiempo lineal en un **cronotopo historicista**: el tiempo se vuelve Historia con mayúscula, que avanza hacia un **telos**. A la vez asciende la **subjetividad**: el yo psicoanalítico, el fenomenológico, el existencialista —pienso, quiero, deseo—, todos dependientes de la creencia en un yo. La modernidad elabora, mientras Dios se desvanece, la tensión entre subjetividad y telos, entre la historia y el yo.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, subjetividad y estructura",
      body: "El **estructuralismo** entra después, ya en el siglo XX, como fuente alternativa de orden y sentido: un giro de lo diacrónico a lo **sincrónico** que no rechaza el tiempo lineal, sino que lo pone entre paréntesis. Una vez asimilado ese bracketing hegeliano y husserliano, ya no se abandona.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología, subjetividad y estructura",
      body: "Desde la Ilustración, la historia intelectual vuelve una y otra vez sobre su verdadero legado: ¿hubo demasiada racionalidad, o la clase equivocada de racionalidad? Filosóficamente da telos y subjetividad; políticamente, el liberalismo y el ascenso de **nación** y **clase** como categorías modernas que median entre lo singular y lo universal: las capas intermedias —religión, etnia, nación, clase— con que se piensan el mundo y la identidad en cuanto se sale de la filosofía pura.",
    },
    {
      type: "quiz",
      question: "¿Qué hace el estructuralismo con el tiempo lineal de Hegel y Marx?",
      options: [
        "Lo pone entre paréntesis para mirar lo sincrónico, sin rechazarlo",
        "Lo rechaza por completo y lo declara filosóficamente inválido",
        "Lo intensifica todavía más que el propio marxismo",
        "Lo reemplaza directamente por una teoría del eterno retorno",
      ],
      answer: 0,
      explain: "El estructuralismo entra como fuente alternativa de orden: un giro de lo diacrónico a lo sincrónico que no rechaza el tiempo lineal, sino que lo pone entre paréntesis. Una vez asimilado ese bracketing, ya no se abandona.",
    },
    {
      type: "info",
      title: "Cómo se mueven las ideas: el encuentro",
      body: "La historia intelectual suele tratarse como si ciertas ideas fueran monopolio de un grupo, o se hubieran originado puramente en él. Pero es radicalmente cosmopolita: las ideas se mueven, y una vez dichas no se sabe adónde irán, quién las escuchará ni quién escuchará a quien las escuchó. Nadie vive en una burbuja de vidrio: circulan por rutas improbables y coincidentes a lo largo del tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "Cómo se mueven las ideas: el encuentro",
      body: "Se mueven, muchas veces, por **encuentro**: un cruce biográfico documentable. Engels y Marx se conocen; Beauvoir y Sartre; Jakobson y Lévi-Strauss; Angela Davis y Marcuse; Frantz Fanon y Sartre; Havel y Michnik. De esos encuentros surge algo nuevo, y así se mueve la historia intelectual: por eso resulta impredecible. Uno de esos encuentros, el de **Jan Patočka** y el filósofo polaco **Krzysztof Michalski**, vuelve más adelante en esta clase.",
    },
    {
      type: "info",
      title: "La vanguardia y el salto",
      body: "La **vanguardia** responde de la manera más radical al ascenso del nacionalismo y a la recreación del mapa de Europa en Estados nacionales tras la Primera Guerra, con un internacionalismo agresivo y apasionado: usar todas las lenguas posibles, declarar passé las fronteras y toda limitación. Es un momento inspirador y mágico, pero breve.",
    },
    {
      type: "info",
      continues: true,
      title: "La vanguardia y el salto",
      body: "Se agota menos por el internacionalismo que por un **nihilismo radical** vivido como libertad radical —todo es posible, sin red de contención: otra vez la Bodenlosigkeit—, la misma vacuidad que después comparte Sartre bajo el nombre de libertad. En cierto momento la vanguardia salta del nihilismo y la contingencia radicales al **utopismo** y el determinismo radicales, uniéndose a la revolución.",
    },
    {
      type: "info",
      continues: true,
      title: "La vanguardia y el salto",
      body: "En eso es un metónimo de la modernidad entera: empieza en la disrupción y la fragmentación y anhela la **totalidad**, busca fundamento, reconoce la falta de suelo e intenta superarla: cómo reconstruir un hogar en un mundo sin Dios.",
    },
    {
      type: "quiz",
      question: "¿Por qué la vanguardia funciona como metónimo de la modernidad entera?",
      options: [
        "Porque empieza fragmentada y termina anhelando la totalidad",
        "Porque rechazó siempre cualquier forma de internacionalismo",
        "Porque nunca coqueteó con ninguna forma de utopismo político",
        "Porque se mantuvo al margen de la política durante todo el siglo",
      ],
      answer: 0,
      explain: "La vanguardia salta del nihilismo y la contingencia radicales al utopismo y el determinismo, uniéndose a la revolución: empieza en la disrupción y la fragmentación y termina anhelando la totalidad, como la modernidad entera.",
    },
    {
      type: "info",
      title: "Totalitarismo: la Ilustración enloquecida",
      body: "Con el nazismo, el estalinismo y el totalitarismo se llega a la **ingeniería social a gran escala**: el proyecto ilustrado enloquecido, el Frankenstein de la modernidad. La idea de que todo puede ser ingeniado, incluidos los seres humanos; todo categorizado, esculpido, perfeccionado, calculado, controlado, dominado, optimizado.",
    },
    {
      type: "info",
      continues: true,
      title: "Totalitarismo: la Ilustración enloquecida",
      body: "El atractivo era el mismo que seducía del marxismo y el hegelianismo: la **totalidad**, \"la supremacía omnipresente del todo sobre las partes\", en la fórmula de Lukács, sentida como una manera de superar la falta de suelo.",
    },
    {
      type: "info",
      title: "El existencialismo frente a la culpa",
      body: "El existencialismo, en la versión de Sartre, mira esa vacuidad y responde que hay que crearse actuando, fundar la propia identidad eligiendo. La carga de elegir deja en **angustia** y en una culpa omnipresente: la culpa es, en el existencialismo, lo que el poder es para Foucault —está en todas partes, inherente a elegir, y a menudo ninguna elección disponible resulta inocente.",
    },
    {
      type: "info",
      continues: true,
      title: "El existencialismo frente a la culpa",
      body: "El excomunista **Arthur Koestler**, autor de Oscuridad al mediodía, el gran relato novelado sobre los juicios de Moscú, lo formula en la antología El dios que fracasó: cada excomunista lleva un esqueleto en el armario de su conciencia, y sumados formarían galerías más laberínticas que las catacumbas de París.",
    },
    {
      type: "quiz",
      question: "¿A qué compara la clase la culpa en el existencialismo de Sartre?",
      options: [
        "Al poder en Foucault: está en todas partes, inherente a elegir",
        "A la angustia en Kierkegaard, ajena a cualquier elección concreta",
        "A la responsabilidad en Kant, fundada en un deber universal",
        "Al pecado original cristiano, heredado sin elección posible",
      ],
      answer: 0,
      explain: "La culpa es, en el existencialismo, lo que el poder es para Foucault: está en todas partes, inherente a elegir, y a menudo ninguna elección disponible resulta inocente.",
    },
    {
      type: "info",
      title: "Patočka y la generosidad hacia Heidegger",
      body: "En ese contexto puede leerse la sorprendente generosidad de **Jan Patočka** hacia el compromiso de Heidegger con el nazismo. Patočka siempre supo lo que Heidegger había hecho: estuvo en Friburgo en 1933, vivió la guerra bajo ocupación nazi y vio morir a amigos en el Holocausto. Cuando en 1976 se publicó la entrevista que Heidegger había dado a Der Spiegel diez años antes, los estudiantes de Patočka le hicieron llegar una copia y grabaron su respuesta, notablemente generosa: hoy es obvio qué fue el nazismo, pero un alemán en 1933 quizá sintió que no tenía más opción que probarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka y la generosidad hacia Heidegger",
      body: "El politólogo búlgaro **Ivan Krastev**, que creció bajo el comunismo, señaló algo revelador: Patočka también perdonó a sus amigos checos estalinistas —parte de su círculo de disidentes, al final de su vida, había sido a la vez estalinista y víctima del estalinismo—. ¿Por qué no perdonar entonces también el nazismo de Heidegger? Era el Zeitgeist, y quienes sobrevivieron a ambos totalitarismos sabían que muy pocos habían salido con las manos limpias: casi todos, para sobrevivir, habían hecho algún compromiso.",
    },
    {
      type: "quiz",
      question: "¿Qué paralelo señala Krastev sobre la generosidad de Patočka?",
      options: [
        "Patočka también perdonó a amigos checos, a la vez cómplices y víctimas",
        "Patočka nunca perdonó a nadie comprometido con un régimen totalitario",
        "Patočka sólo conoció el nazismo, nunca convivió con estalinistas",
        "Patočka exigió siempre juicios formales antes de cualquier perdón",
      ],
      answer: 0,
      explain: "Patočka también perdonó a amigos checos de su círculo de disidentes que habían sido, a la vez, estalinistas y víctimas del estalinismo: casi nadie, en esos totalitarismos, había salido con las manos limpias.",
    },
    {
      type: "info",
      title: "Por qué Heidegger sigue importando",
      body: "Heidegger sigue siendo decisivo pese a lo que hizo —o justamente por eso— porque su filosofía fue el momento en que siglos de paradigma sujeto-objeto quedaron superados en una filosofía de la **incrustación** (embeddedness). El Dasein no era un cogito cartesiano, una conciencia pensante aislada, sino un ser incrustado en el mundo, involucrado, que cuida, que está arrojado, que hace cosas y moldea el mundo aun mientras es moldeado por él.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué Heidegger sigue importando",
      body: "La **Geworfenheit**, el estar-arrojado, describe esa condición de estar siempre ya arrojados a un tiempo, un lugar y una historia que no se eligen —nadie elige cuándo y dónde nace—, pero desde ese lugar se elige, y de esa elección se es responsable. El Dasein es a la vez radicalmente arrojado y radicalmente sin fundamento, porque vivir auténticamente es no estar nunca del todo en casa.",
    },
    {
      type: "quiz",
      question: "¿Qué reemplaza Heidegger con la idea del Dasein como incrustación?",
      options: [
        "El paradigma sujeto-objeto de un cogito cartesiano aislado",
        "La distinción entre habla y escritura de la tradición occidental",
        "El concepto de metarrelato acuñado después por Lyotard",
        "La noción marxista de base y superestructura",
      ],
      answer: 0,
      explain: "El Dasein no es un cogito cartesiano, una conciencia pensante aislada, sino un ser incrustado en el mundo, involucrado, que cuida, que está arrojado. Con eso Heidegger supera siglos de paradigma sujeto-objeto.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué Heidegger sigue importando",
      body: "Estas preguntas se intensifican porque el siglo XX es un baño de sangre. Los mismos filósofos que se creían herederos de la cima de la civilización europea vieron esa civilización convertirse en barbarie. Heidegger da una historicidad —alternativa a la de Hegel— necesaria para aprehender un siglo en el que, otra vez, los cambios de escala se vuelven cambios de tipo.",
    },
    {
      type: "info",
      continues: true,
      title: "Por qué Heidegger sigue importando",
      body: "Algunas cifras, siempre provisorias: el Gran Terror soviético de 1937-38 causa unas 680.000 ejecuciones; las hambrunas de la colectivización, entre 1931 y 1933, unos tres millones y medio de muertos en la Ucrania soviética, millón y medio en Kazajistán, medio millón en Rusia; entre uno y medio y tres millones mueren en el Gulag; los regímenes nazi y estalinista matan juntos, entre 1933 y 1945, unos catorce millones de personas solo entre el Báltico y el mar Negro; la Segunda Guerra, en conjunto, unos cuarenta millones. Una escala que aturde.",
    },
    {
      type: "info",
      title: "Del estructuralismo al posestructuralismo",
      body: "El posmodernismo nombra, en su sentido más amplio, la manera de pensar que se consolida sobre todo después de 1968, en ruptura con buena parte del pensamiento moderno; el **posestructuralismo** es una forma más específica de esa ruptura. El estructuralismo había prometido algo a lo que aferrarse: una estructura estable, aunque el significado no fuera inmanente sino relacional.",
    },
    {
      type: "info",
      continues: true,
      title: "Del estructuralismo al posestructuralismo",
      body: "El posestructuralismo dice que no: no hay sistema cerrado, y por lo tanto no hay estructura estable ni significado determinado posible. Para **Jacques Derrida**, una estructura estable exige un **significado trascendental** —un centro, un dios, inmanente o trascendente— que sostenga el sistema, y ese centro no existe. El lenguaje es inestable y el significado titila; pero eso no es un déficit de significado, sino, si acaso, un excedente.",
    },
    {
      type: "info",
      continues: true,
      title: "Del estructuralismo al posestructuralismo",
      body: "Los críticos objetan que un exceso de significado equivale a ninguno, como si múltiples autoridades fueran ninguna autoridad. Derrida respondería que infinito no es lo mismo que nada, del mismo modo que para Foucault \"en todas partes\" no es lo mismo que \"en ninguna\": la dispersión radical del sentido, o del poder, no es su ausencia.",
    },
    {
      type: "quiz",
      question: "¿Cómo respondería Derrida a la objeción de que el exceso de significado equivale a ninguno?",
      options: [
        "Que infinito no equivale a nada, como pasa con el poder en Foucault",
        "Aceptando la objeción y renunciando al significado trascendental",
        "Sosteniendo que el lenguaje, en realidad, sí tiene un centro fijo",
        "Diciendo que la dispersión del sentido equivale siempre a su ausencia",
      ],
      answer: 0,
      explain: "Derrida respondería que infinito no es lo mismo que nada, así como para Foucault «en todas partes» no es lo mismo que «en ninguna»: la dispersión radical del sentido, o del poder, no es su ausencia.",
    },
    {
      type: "info",
      title: "Lyotard: el fin de los grandes relatos",
      body: "**Jean-François Lyotard** fija, con La condición posmoderna (1979), la definición más citada del posmodernismo: la incredulidad hacia los **metarrelatos**. Un metarrelato, o gran relato, es la clase de historia que la Ilustración y sus herederos —el progreso, la emancipación, la dialéctica hegeliana o marxista— contaban para que todo encajara y tuviera sentido dentro de un único relato con dirección.",
    },
    {
      type: "info",
      continues: true,
      title: "Lyotard: el fin de los grandes relatos",
      body: "Lo posmoderno, para Lyotard, es dejar de creer que exista un relato, una filosofía o una cosmovisión capaz de reunir todo bajo ese hilo único. No propone reemplazar el gran relato por otro: propone resignarse a **pequeños relatos** (petits récits), locales y provisorios, del tipo de los \"juegos de lenguaje\" de Wittgenstein, sin pretensión de validez universal ni de punto final.",
    },
    {
      type: "quiz",
      question: "¿Qué propone Lyotard en lugar de un nuevo gran relato?",
      options: [
        "Pequeños relatos locales y provisorios, sin validez universal",
        "Reemplazar el marxismo por otro metarrelato equivalente",
        "Volver al racionalismo ilustrado en su forma más pura",
        "Una síntesis final que reúna todos los relatos anteriores",
      ],
      answer: 0,
      explain: "Lyotard no propone reemplazar el gran relato por otro: propone resignarse a pequeños relatos, locales y provisorios, del tipo de los juegos de lenguaje de Wittgenstein, sin pretensión de validez universal.",
    },
    {
      type: "info",
      title: "Baudrillard: el simulacro",
      body: "**Jean Baudrillard** lleva la crisis de la representación un paso más allá en Simulacros y simulación (1981). Su punto de partida es una fábula: un mapa que reproduce el territorio a escala exacta, hasta cubrirlo por completo; con el tiempo el territorio se deteriora y solo queda el mapa. Baudrillard invierte la fábula: en el mundo contemporáneo ya no hay territorio previo al mapa. El **simulacro** no copia una realidad preexistente: la precede y la produce.",
    },
    {
      type: "info",
      continues: true,
      title: "Baudrillard: el simulacro",
      body: "A eso llama **hiperrealidad**: un mundo saturado de imágenes, simulacros y modelos que ya no remiten a nada fuera de sí mismos, y que resultan, para quien los vive, más reales que cualquier referente que pudieran tener. La pregunta por si una imagen es fiel a los hechos deja de tener sentido cuando la imagen misma reemplaza a los hechos como criterio de lo real.",
    },
    {
      type: "quiz",
      question: "En la fábula invertida de Baudrillard, ¿qué pasa entre el mapa y el territorio?",
      options: [
        "Ya no hay territorio previo: el simulacro precede y produce lo real",
        "El mapa se deteriora primero y el territorio permanece intacto",
        "El territorio y el mapa coinciden siempre a la perfección",
        "El mapa desaparece por completo y sólo queda el territorio",
      ],
      answer: 0,
      explain: "Baudrillard invierte la fábula clásica del mapa que cubre el territorio: en el mundo contemporáneo ya no hay territorio previo al mapa. El simulacro no copia una realidad preexistente, la precede y la produce.",
    },
    {
      type: "info",
      title: "Jameson: el capitalismo tardío",
      body: "**Fredric Jameson** sostiene, en su ensayo sobre el posmodernismo como \"lógica cultural del capitalismo tardío\" (1984), que el posmodernismo no es una moda estética entre otras, sino la **superestructura** que corresponde a una etapa nueva del capitalismo: la del capital multinacional y financiero, que el economista Ernest Mandel había llamado \"capitalismo tardío\", tercera fase después del capitalismo de mercado y del capitalismo monopolista-imperialista.",
    },
    {
      type: "info",
      continues: true,
      title: "Jameson: el capitalismo tardío",
      body: "De ahí sus diagnósticos: el **pastiche** reemplaza a la parodia —se imita un estilo sin la distancia crítica que supone burlarse de él—; se pierde la **historicidad**, la capacidad de situar el presente en una secuencia con sentido; el afecto se debilita. La tarea que Jameson propone frente a esto es un **mapeo cognitivo**: reconstruir, dentro de un sistema económico vuelto inabarcable, algún modo de representarse el propio lugar en él.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue al pastiche de la parodia, según Jameson?",
      options: [
        "El pastiche imita un estilo sin la distancia crítica de burlarse de él",
        "El pastiche siempre incluye una crítica política explícita",
        "La parodia sólo puede darse en la literatura, nunca en otras artes",
        "No hay ninguna diferencia real entre pastiche y parodia",
      ],
      answer: 0,
      explain: "El pastiche reemplaza a la parodia: se imita un estilo sin la distancia crítica que supone burlarse de él. Es uno de los diagnósticos de Jameson sobre la lógica cultural del capitalismo tardío.",
    },
    {
      type: "info",
      title: "Habermas: la modernidad como proyecto inacabado",
      body: "**Jürgen Habermas** es el gran disidente de este diagnóstico. En una conferencia de 1980 que tituló \"la modernidad, un proyecto inacabado\", sostiene que el error no está en el proyecto ilustrado sino en haberlo abandonado a mitad de camino. La modernidad diferenció esferas de valor —la ciencia, la moral, el arte— antes fundidas en la religión y la tradición, y ese proceso conserva, para Habermas, un potencial emancipatorio que todavía no se agotó.",
    },
    {
      type: "info",
      continues: true,
      title: "Habermas: la modernidad como proyecto inacabado",
      body: "Frente a Lyotard, Baudrillard y Jameson, que leen la modernidad como agotada o disuelta en simulacro, Habermas propone completarla mediante una **razón comunicativa**: no la razón instrumental que calcula medios para fines dados, sino la que se ejerce en el diálogo, cuando los participantes buscan entenderse y justificar sus posiciones ante otros. Abandonar el proyecto ilustrado, para él, es quedarse sin herramientas para distinguir el mejor argumento del más fuerte.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue a la razón comunicativa de Habermas de la razón instrumental?",
      options: [
        "Se ejerce en el diálogo, buscando entenderse mutuamente",
        "Calcula únicamente los medios más eficaces para un fin fijo",
        "Depende sólo de la autoridad de quien tiene más poder",
        "Rechaza cualquier forma de argumentación entre personas",
      ],
      answer: 0,
      explain: "La razón instrumental calcula medios para fines dados; la razón comunicativa se ejerce en el diálogo, cuando los participantes buscan entenderse y justificar sus posiciones ante otros. Sin ella no hay cómo distinguir el mejor argumento del más fuerte.",
    },
    {
      type: "info",
      title: "Bauman: la modernidad líquida",
      body: "Marx fue, en cierto modo, prematuro cuando escribió que \"todo lo sólido se desvanece en el aire\": no era del todo cierto en 1848, pero sí bajo la posmodernidad. **Zygmunt Bauman** describe la modernidad como el intento de reemplazar los viejos sólidos por sólidos nuevos y mejores; a la posmodernidad la llama **modernidad líquida**: el momento en que se abandona ese reemplazo y se abraza directamente la fluidez, lo efímero, lo que no llega a solidificarse en nada.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la modernidad líquida de la modernidad sólida, en Bauman?",
      options: [
        "Abandona el reemplazo de sólidos por otros y abraza la fluidez",
        "Reemplaza los viejos sólidos por otros todavía más firmes",
        "Es sinónimo exacto de lo que Marx llamó capitalismo tardío",
        "Devuelve a la sociedad la certeza que tenía antes de la Ilustración",
      ],
      answer: 0,
      explain: "La modernidad quería reemplazar los viejos sólidos por sólidos nuevos y mejores; la modernidad líquida abandona ese proyecto y abraza directamente la fluidez, lo efímero, lo que no llega a solidificarse en nada.",
    },
    {
      type: "info",
      title: "Derrida: hauntología y los espectros de Marx",
      body: "Derrida insistiría en que la **deconstrucción** es la condición mínima necesaria para identificar y combatir el riesgo totalitario que anida en todo significado trascendental. Pero trae también un riesgo propio: si no hay verdad determinada, ¿qué queda por lo cual luchar, a qué aferrarse?",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida: hauntología y los espectros de Marx",
      body: "Al final de su vida vuelve a Marx y a Hegel en Espectros de Marx (años noventa), un ensayo sobre la imposibilidad de despedirse de ellos: \"hay más de uno, tiene que haber más de uno\", escribe, sobre los múltiples espectros de Marx. Lo llama **hauntología**, ontología del fantasma: la necesidad de reclamar la herencia de los espíritus heterogéneos de Marx, que van a seguir rondando.",
    },
    {
      type: "info",
      continues: true,
      title: "Derrida: hauntología y los espectros de Marx",
      body: "Foucault dice algo parecido, más conciso: escapar de verdad a Hegel exige apreciar con exactitud el precio de desprenderse de él, saber hasta qué punto sigue cerca, y reconocer que buena parte de lo que permite pensar contra Hegel sigue siendo, de algún modo, hegeliano.",
    },
    {
      type: "short",
      question: "¿Cómo llama Derrida a la ontología del fantasma con que Marx sigue rondándonos?",
      answers: ["hauntología", "hauntologia"],
      explain: "Hauntología: un juego con «ontología» y el verbo inglés «to haunt». En Espectros de Marx Derrida sostiene que hay más de un espectro de Marx, y que ninguno se deja despedir del todo.",
    },
    {
      type: "info",
      title: "Posverdad",
      body: "El posmodernismo, nacido de una sensibilidad crítica de izquierda, terminó volviéndose también un arma de la derecha. Arendt había distinguido la mentira **premoderna** —un desgarrón en la tela de la realidad que un observador atento podía localizar— de la mentira de las ideologías totalitarias del siglo XX: ya no un desgarrón sino una reconstrucción completa de la realidad, sin costuras, más creíble que la verdad empírica porque edita toda la arbitrariedad y el azar de lo real.",
    },
    {
      type: "info",
      continues: true,
      title: "Posverdad",
      body: "La **posverdad** es otra clase de mentira todavía: no ofrece una versión falsa pero coherente del mundo, como la ideología totalitaria, sino que socava la idea misma de que exista algo como la verdad. Un día una versión, al día siguiente otra: cada quien con sus hechos y sus hechos alternativos. Es un nivel nuevo de Bodenlosigkeit, y devuelve actualidad a la pregunta de los disidentes del comunismo sobre si debe existir algo como la verdad.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia la posverdad de la mentira totalitaria que describió Arendt?",
      options: [
        "No ofrece un mundo coherente: socava que exista la verdad",
        "Es exactamente la misma mentira, sólo que con otro nombre",
        "Es más fácil de desmentir porque siempre es igual a sí misma",
        "Sólo circula en regímenes democráticos, nunca en autoritarios",
      ],
      answer: 0,
      explain: "La ideología totalitaria ofrecía una mentira coherente, sin costuras. La posverdad es otra cosa: no ofrece una versión falsa pero coherente, sino que socava la idea misma de que exista algo como la verdad.",
    },
    {
      type: "info",
      continues: true,
      title: "Posverdad",
      body: "El arco filosófico va, así, de la **epistemología** a la **ontología** y a la **ética**: de la verdad como correspondencia entre sujeto y objeto a la verdad como aquello que se contrasta con la mentira, la autenticidad frente a la inautenticidad. En el medio queda la historia, porque para entonces todo lo que se discute es ya profundamente histórico.",
    },
    {
      type: "info",
      title: "Patočka, Michalski y la verdad como responsabilidad",
      body: "**Adam Michnik** y el filósofo **Krzysztof Michalski** eran estudiantes de Leszek Kołakowski en Varsovia cuando, en marzo de 1968, empezaron las manifestaciones: Michnik fue encarcelado, y el gobierno echó a todos del departamento de Filosofía. Muchos, Kołakowski entre ellos, emigraron; Michalski volvió a una universidad sin sus amigos ni el director bajo el que quería escribir una tesis sobre Heidegger. Un amigo de Kołakowski lo envió entonces a **Jan Patočka**, en Praga.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka, Michalski y la verdad como responsabilidad",
      body: "Michalski había nacido en 1948; Patočka, en 1907: más de cuarenta años los separaban, pero los unía la convicción de que Heidegger podía ser, en el bloque comunista de los años setenta, un antídoto contra Hegel: el pensador que ayudaba a ver que puede haber sentido sin totalidad, y alguna verdad sin que la historia avance inexorablemente hacia un telos.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka, Michalski y la verdad como responsabilidad",
      body: "Escribiendo su tesis por correspondencia con Patočka, Michalski sentía que Heidegger le había dado el sentido del peso de cada paso de su vida, el sentido de la vida como responsabilidad. Eso fue también lo que Patočka tomó de él: una filosofía de la **responsabilidad**, porque estar siempre ya en el mundo implica ser siempre ya responsable de él —la responsabilidad no es una relación contingente con esto o aquello, sino un rasgo ontológico del Dasein mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka, Michalski y la verdad como responsabilidad",
      body: "El sentido y la verdad, decía Patočka, quizá no sean cosas que se puedan asir con las manos, pero eso no significa renunciar a buscarlos: es la responsabilidad de seguir buscando. Lo escribió en sus Ensayos heréticos sobre la filosofía de la historia, cuyo primer capítulo Michalski logró contrabandear a Polonia. El movimiento de Kołakowski, Patočka y Michalski sostiene, en definitiva, que una subjetividad robusta no relativiza la verdad: la funda, y verdad y subjetividad se conectan a través de la responsabilidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Patočka, Michalski y la verdad como responsabilidad",
      body: "Tras la muerte de Patočka, en 1977, a consecuencia de un interrogatorio policial, Michalski consiguió una beca en el archivo de Husserl, en Alemania, y convenció a un colega con pasaporte occidental de entrar en Checoslovaquia para contrabandear el archivo de Patočka. Ese proyecto se convirtió en el núcleo del **Instituto de Ciencias Humanas** de Viena, donde el archivo permanece.",
    },
    {
      type: "match",
      question: "Uní cada pensador con su diagnóstico de la posmodernidad",
      pairs: [
        { left: "Lyotard", right: "Incredulidad hacia los metarrelatos; pequeños relatos locales" },
        { left: "Baudrillard", right: "El simulacro precede y produce la realidad: la hiperrealidad" },
        { left: "Jameson", right: "La superestructura cultural del capitalismo tardío" },
        { left: "Habermas", right: "La modernidad es un proyecto inacabado, no fracasado" },
        { left: "Bauman", right: "La modernidad líquida: se abraza la fluidez sin fijarse en nada" },
      ],
      explain: "Lyotard, Baudrillard y Jameson leen la modernidad como agotada, cada uno con su propio diagnóstico: metarrelatos caídos, simulacro sin territorio, superestructura del capitalismo tardío. Habermas disiente: hay que completarla. Bauman la describe, ya sin ese debate, como pura fluidez.",
    },
    {
      type: "info",
      title: "Cierre: perdón, testimonio y la autobiografía de Dios",
      body: "Queda, para cerrar, el perdón, con Dios otra vez de fondo. Arendt reconoce que es **Jesús** quien descubre el perdón como categoría; y no es la única que perdona algo que podría no perdonarse: Derrida perdona a Paul de Man, y ambos, Arendt y Derrida, terminan escribiendo sobre el perdón. En La condición humana Arendt sostiene que el acto de perdonar nunca puede predecirse: es la única reacción capaz de actuar de nuevo, de un modo inesperado, sin quedar condicionada por lo que la provocó.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: perdón, testimonio y la autobiografía de Dios",
      body: "El puesto de asistente de Husserl que dejó Edith Stein lo heredó Heidegger, pero el hilo que la conecta con el resto de esta historia pasa por otro lado: Stein estaba enamorada del otro alumno polaco de Husserl, **Roman Ingarden**. Durante la Primera Guerra ella era una patriota alemana fervorosa y él, un patriota polaco, y esa diferencia se interpuso entre ambos.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: perdón, testimonio y la autobiografía de Dios",
      body: "Ingarden termina casándose con una mujer polaca. El día que recibe esa noticia, Stein le pide que queme todas sus cartas; él no lo hace. Stein se convierte al catolicismo, se hace monja carmelita, y en 1942 es deportada y asesinada en Auschwitz por su origen judío.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: perdón, testimonio y la autobiografía de Dios",
      body: "Años después, enseñando en Cracovia, Ingarden conoce a un sacerdote interesado en la fenomenología, **Karol Wojtyła**, y le habla de Stein; Wojtyła le pide una clase privada sobre su obra. Una década más tarde, convertido en el papa **Juan Pablo II**, canoniza a Edith Stein: la declara santa el 11 de octubre de 1998, en la Plaza de San Pedro, describiéndola como alguien que \"con todo su ser, buscó la verdad\" —la misma palabra con que se abrió esta clase, y el mismo hilo que atraviesa todo el curso.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: perdón, testimonio y la autobiografía de Dios",
      body: "Ese mismo Juan Pablo II fue mecenas del Instituto de Ciencias Humanas que Michalski había fundado en torno al archivo de Patočka. En una conferencia sobre el legado de la Ilustración organizada allí, tras escuchar durante varios días exposiciones sobre la razón, la racionalidad y la capacidad humana de hallar la verdad, cerró el encuentro con una observación: todo eso —la Ilustración, la modernidad entera— no era, a fin de cuentas, más que un breve momento en la autobiografía de Dios.",
    },
  ],
};
