export default {
  num: 17,
  transcript: 18,
  title: "Marxismo revisionista y existencialismo",
  source: "https://www.youtube.com/watch?v=Rh2FjZu2pNc",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "El **marxismo revisionista** nombra, en este contexto, un fenómeno muy específico: un conjunto de intentos, concentrados entre **1956 y 1968**, de repensar el marxismo desde adentro después del estalinismo, inyectándole una noción más robusta de la subjetividad y la responsabilidad individual. No debe confundirse con el revisionismo kantiano de **Eduard Bernstein**, a principios del siglo veinte, que discutía la inevitabilidad económica del colapso capitalista; este es un fenómeno posterior y distinto, centrado en la relación entre determinismo histórico y culpa moral.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Sus protagonistas trabajan en focos separados que terminan por converger: el húngaro **Georg Lukács**, el italiano **Antonio Gramsci** —leído recién en esos años más allá de Italia—, el polaco **Leszek Kołakowski**, el Grupo Praxis en Yugoslavia, y en Checoslovaquia **Karel Kosík**, **Ludvík Vaculík** y **Milan Kundera**. Todos releen a **Hegel a través de Heidegger y de Sartre**, y buscan en el marxismo un lugar para la elección individual que el determinismo histórico parecía haber cancelado.",
    },
    {
      type: "quiz",
      question: "¿En qué se distingue el marxismo revisionista de 1956-1968 del revisionismo de Bernstein?",
      options: [
        "No discute economía sino determinismo histórico y culpa",
        "Ambos son en rigor el mismo debate repetido dos veces",
        "Bernstein también parte de releer a Heidegger y Sartre",
        "Se concentra en Europa occidental y no en el bloque del Este",
      ],
      answer: 0,
      explain: "Bernstein discutía, a principios de siglo, si el colapso capitalista era económicamente inevitable. El revisionismo de posguerra es otro fenómeno: repiensa la relación entre determinismo histórico y responsabilidad moral tras el estalinismo.",
    },
    {
      type: "info",
      title: "El problema que hereda",
      body: "El trasfondo que pesa sobre todo el período es el **estalinismo** y su terror: ¿cómo fue posible que el marxismo del Manifiesto comunista (1848) desembocara en mazmorras donde se torturaba a la gente hasta arrancarle confesiones grotescas de crímenes que no había cometido? El terror estalinista llega a su pico en la URSS hacia 1937, y se repite en Europa del Este, entre los países que se vuelven comunistas tras la Segunda Guerra, sobre todo entre **1948 y 1953**: los mismos juicios-espectáculo, la misma maquinaria de confesiones forzadas.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "El lenguaje de esos juicios era, en sí mismo, filosóficamente sintomático: un fiscal podía preguntar \"en su odio infinito por el glorioso pueblo amante de la paz de la hermosa República Socialista, ¿de qué otras maneras intentó sabotear su bello y pacífico futuro?\", y el acusado respondía \"sí, en mi odio infinito…\".",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "La suspensión de la razón necesaria para sostener la autenticidad de esos juicios es extrema, y esa abdicación de la razón es lo que toda esta filosofía tiene que explicar: un marxismo que empezó siendo, en su pretensión, razón y comprensión científica de la historia terminó exigiendo la cancelación total del juicio propio.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda",
      body: "Dos textos teóricos, escritos antes de 1956 pero recuperados con urgencia durante el período, funcionan como el punto de apoyo desde el que los revisionistas repiensan el marxismo: Historia y conciencia de clase (1923), de Lukács, y los Cuadernos de la cárcel de Gramsci, escritos entre 1929 y 1935 y publicados recién después de la guerra. Ambos habían intentado, cada uno a su modo, dar a la superestructura —la cultura, la conciencia, la ideología— un peso propio que el marxismo más mecánico les negaba.",
    },
    {
      type: "quiz",
      question: "¿Qué revela, según la clase, el lenguaje mismo de los juicios-espectáculo estalinistas?",
      options: [
        "Una aplicación consecuente del método científico marxista",
        "Un simple error de traducción entre el ruso y otras lenguas",
        "Una abdicación de la razón que el marxismo debe explicar",
        "La ausencia total de ideología detrás de las condenas",
      ],
      answer: 2,
      explain: "El acusado repite el odio infinito que le atribuye el fiscal. Un marxismo que se presentaba como razón y comprensión científica de la historia terminó exigiendo la cancelación total del juicio propio: esa abdicación es lo que el revisionismo tiene que explicar.",
    },
    {
      type: "info",
      title: "El estalinismo y el terror",
      body: "El terror estalinista se repite en Europa del Este en los años posteriores a 1948, con arrestos masivos, prisiones, tortura y ejecuciones organizadas como juicios-espectáculo. Entre los casos más documentados están el juicio a **Rudolf Slánský** en Praga (1951-1952) y el de **Milada Horáková** (1950), ambos con sentencias de muerte dictadas antes de que el juicio siquiera empezara en los hechos.",
    },
    {
      type: "info",
      continues: true,
      title: "El estalinismo y el terror",
      body: "Un testimonio del siglo veintiuno ilustra la misma lógica en otro contexto: el escritor ucraniano **Stanislav Aséyev**, estudiante de filosofía capturado por separatistas y soldados rusos en el Donbás y torturado durante dos años y medio, describe en The Torture Camp on Paradise Street una escena que dialoga directamente con la noción sartreana de la **mirada del otro**.",
    },
    {
      type: "info",
      continues: true,
      title: "El estalinismo y el terror",
      body: "Cuando el guardia que le había confiscado sus escritos le grita si vivirá para verlo desaparecer, Aséyev entiende que puede verse reflejado en esos ojos: un hombre descubre quién es a través de la experiencia de ser visto por otro, y sólo en la mirada consciente de un verdugo —no en los gritos ni en la súplica de clemencia, a los que ya está acostumbrado— puede uno verse, de verdad, como víctima.",
    },
    {
      type: "quiz",
      question: "¿Con qué noción sartreana dialoga el testimonio de Aséyev sobre su verdugo?",
      options: [
        "La mirada del otro, que revela quién se es al ser visto",
        "La mala fe, el autoengaño para negar la libertad propia",
        "La facticidad, el límite dado dentro del que se es libre",
        "El decisionismo, la obligación de elegir en toda situación",
      ],
      answer: 0,
      explain: "Aséyev se descubre víctima al verse reflejado en la mirada consciente del guardia, no en sus gritos: es la mirada del otro sartreana, que cosifica y a la vez revela quién se es.",
    },
    {
      type: "info",
      title: "Sartre y la polarización de entreguerras",
      body: "Para entender por qué tantos intelectuales de Europa del Este llegan al comunismo convencidos, hay que volver a la **traición de Múnich** (septiembre de 1938): Chamberlain le entrega a Hitler los Sudetes checoslovacos —\"les traigo paz para nuestro tiempo\", en sus célebres últimas palabras—. Checoslovaquia había sido el único de los Estados surgidos de Versalles que sostuvo una democracia liberal funcional durante toda la entreguerra, y esa misma democracia liberal la vendió.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre y la polarización de entreguerras",
      body: "Cuando el Ejército Rojo libera Praga en 1945, el contraste —la democracia liberal nos traicionó, Stalin nos liberó— se vuelve formativo, sobre todo para quienes nacieron en los años veinte.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre y la polarización de entreguerras",
      body: "En febrero de 1945, en **Yalta**, Roosevelt, Churchill y Stalin dividen Europa en esferas de influencia, preludio de la Cortina de Hierro. Hacia 1948 los regímenes estalinistas se consolidan en todo el bloque oriental, y se repite el patrón soviético de 1937: arrestos, terror, juicios-espectáculo.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre y la polarización de entreguerras",
      body: "Sartre, mientras tanto, recorre un camino propio: ya en El existencialismo es un humanismo (1946) muestra simpatía por la Revolución Rusa sin animarse a afiliarse al partido comunista; es un **\"compañero de ruta\"**, apologista del estalinismo que no denuncia el terror ni siquiera cuando alcanza a colegas de Europa del Este, porque en un mundo partido en dos cree que no se puede traicionar a la URSS, la única esperanza disponible. Hacia 1960, en su Crítica de la razón dialéctica, declara al marxismo \"la filosofía insuperable de nuestro tiempo\", con el existencialismo llenando sus huecos.",
    },
    {
      type: "info",
      continues: true,
      title: "Sartre y la polarización de entreguerras",
      body: "Así, Sartre se mueve de una libertad radical hacia el determinismo marxista, mientras sus contemporáneos de Europa del Este recorren el camino inverso: del compromiso estalinista hacia una posición cada vez más existencialista. Ambos recorridos convergen, en algún punto intermedio, durante los años sesenta, y ese encuentro es el núcleo del proyecto revisionista.",
    },
    {
      type: "quiz",
      question: "¿Por qué recorren caminos inversos Sartre y los intelectuales de Europa del Este?",
      options: [
        "En realidad ambos recorren exactamente el mismo camino",
        "Convergen desde extremos opuestos hacia un punto medio",
        "Sartre jamás llegó a simpatizar con el comunismo soviético",
        "Los del Este nunca creyeron de verdad en el estalinismo",
      ],
      answer: 1,
      explain: "Sartre va de la libertad radical hacia el determinismo marxista; sus contemporáneos del Este van del compromiso estalinista hacia el existencialismo. Ese cruce, hacia los años sesenta, es el núcleo del revisionismo.",
    },
    {
      type: "info",
      title: "Lukács y la reificación",
      body: "**Georg Lukács** (1885-1971) nace y muere en Budapest. En 1919 es comisario adjunto de Cultura en la efímera República Soviética Húngara de Béla Kun, y al caer esta pasa a un exilio que lo lleva por Viena y Moscú antes de volver a Hungría después de la Segunda Guerra. Es, con enorme distancia, el pensador que mejor ilumina la matriz hegeliana escondida dentro del marxismo.",
    },
    {
      type: "info",
      continues: true,
      title: "Lukács y la reificación",
      body: "Su libro Historia y conciencia de clase (1923) parte de un pasaje breve de El capital —el **fetichismo de la mercancía**— y lo convierte en una categoría social general: la **reificación** (Verdinglichung). Bajo el capitalismo, las relaciones entre personas asumen la apariencia de relaciones entre cosas: el tiempo, la capacidad de trabajo, hasta las cualidades humanas se vuelven magnitudes cuantificables e intercambiables. La conciencia misma queda **reificada**: deja de experimentarse como agente y pasa a contemplar un mundo social que aparece como un mecanismo ajeno, regido por leyes tan fijas como las de la naturaleza.",
    },
    {
      type: "info",
      continues: true,
      title: "Lukács y la reificación",
      body: "La salida que propone Lukács retoma, de manera explícita, la ambición hegeliana de reunir sujeto y objeto. El **proletariado**, sostiene, ocupa una posición única: es a la vez el sujeto de la historia (la clase que puede transformar la sociedad) y el objeto reificado por excelencia (mano de obra vendida como mercancía). Por eso puede, en principio, ser el \"**sujeto-objeto idéntico**\" de la historia: el punto de vista de clase desde el cual la sociedad deja de verse como un conjunto de cosas separadas y se revela como una **totalidad** producida por la actividad humana, y por lo tanto transformable.",
    },
    {
      type: "info",
      continues: true,
      title: "Lukács y la reificación",
      body: "Moscú condena Historia y conciencia de clase como desviación idealista poco después de su publicación, y Lukács firma una autocrítica pública sin abandonar del todo, en privado, sus tesis centrales. Continúa trabajando como crítico literario y filósofo en la Hungría comunista de posguerra, hasta que en octubre de 1956, durante la revolución húngara, acepta ser ministro de Cultura en el gobierno de **Imre Nagy**. Tras la invasión soviética es deportado a Rumania junto con el resto del gobierno depuesto, y sólo regresa a Hungría al año siguiente.",
    },
    {
      type: "info",
      continues: true,
      title: "Lukács y la reificación",
      body: "Frente a los intentos de sintetizar el marxismo con la fenomenología o el existencialismo —el tipo de síntesis que Sartre busca en la Crítica de la razón dialéctica—, Lukács mantiene una posición estrictamente ortodoxa: el marxismo, sostiene, tiene que partir del objeto, de las condiciones materiales, y llegar de ahí al sujeto; empezar en cambio por \"la relación\" misma, como hace la fenomenología cuando dice que al principio está la intencionalidad, es evadir la elección entre materialismo e idealismo en lugar de resolverla. Para Lukács hay que elegir un punto de partida, no combinar los dos.",
    },
    {
      type: "short",
      question: "¿Cómo llama Lukács a que las relaciones humanas asuman apariencia de relaciones entre cosas bajo el capitalismo?",
      answers: ["reificación", "Verdinglichung"],
      explain: "La reificación (Verdinglichung): el tiempo, el trabajo, hasta las cualidades humanas se vuelven magnitudes cuantificables. La conciencia deja de sentirse agente y contempla el mundo social como un mecanismo ajeno.",
    },
    {
      type: "quiz",
      question: "¿Por qué el proletariado puede ser, para Lukács, el «sujeto-objeto idéntico» de la historia?",
      options: [
        "Es la única clase con acceso directo a la razón pura",
        "Está fuera del capitalismo y por eso lo puede juzgar",
        "Es a la vez la clase que transforma y mercancía reificada",
        "Ninguna otra clase social sufre alienación alguna",
      ],
      answer: 2,
      explain: "El proletariado es sujeto de la historia (puede transformar la sociedad) y a la vez objeto reificado (mano de obra vendida como mercancía). Por eso, para Lukács, su punto de vista revela la totalidad como producto humano transformable.",
    },
    {
      type: "info",
      title: "Gramsci y la hegemonía",
      body: "**Antonio Gramsci** (1891-1937), cofundador del Partido Comunista Italiano en 1921, es arrestado por el régimen fascista de Mussolini en 1926: el fiscal pide explícitamente impedir que ese cerebro funcione durante veinte años. Pasa el resto de su vida en prisión, donde escribe, entre 1929 y 1935, los Cuadernos de la cárcel, publicados recién después de la guerra y sólo difundidos ampliamente fuera de Italia durante los años del marxismo revisionista.",
    },
    {
      type: "info",
      continues: true,
      title: "Gramsci y la hegemonía",
      body: "Su aporte central es el concepto de **hegemonía**: una clase dominante no gobierna sólo por la fuerza del Estado, sino sobre todo produciendo el **consenso** de los gobernados a través de la **sociedad civil** —la escuela, la Iglesia, la prensa, las instituciones culturales—, de modo que su propia visión del mundo termine pareciendo simple sentido común. La hegemonía es, en ese sentido, un poder que no necesita mostrarse como poder.",
    },
    {
      type: "info",
      continues: true,
      title: "Gramsci y la hegemonía",
      body: "De ahí se sigue que cada clase produce sus propios **intelectuales orgánicos**, encargados de articular y organizar su visión del mundo, a diferencia de los intelectuales \"tradicionales\" que se presentan como neutrales por encima de las clases. Para Gramsci, ninguna transformación social duradera puede lograrse sin que la clase que la impulsa forme sus propios intelectuales orgánicos, capaces de disputar la hegemonía cultural y no sólo el poder del Estado.",
    },
    {
      type: "info",
      continues: true,
      title: "Gramsci y la hegemonía",
      body: "De la observación de que en Rusia el Estado lo era casi todo y la sociedad civil apenas existía, mientras que en Europa occidental la sociedad civil forma una red densa y bien defendida, Gramsci saca una distinción estratégica: la **guerra de maniobra**, el asalto frontal y rápido al Estado que funcionó en la Revolución rusa de 1917, no puede repetirse donde la sociedad civil sostiene la hegemonía dominante con sus propias trincheras culturales.",
    },
    {
      type: "info",
      continues: true,
      title: "Gramsci y la hegemonía",
      body: "Ahí hace falta, en cambio, una **guerra de posición**: una disputa lenta y prolongada por el sentido común, las instituciones y la cultura, previa a cualquier disputa por el poder político.",
    },
    {
      type: "info",
      continues: true,
      title: "Gramsci y la hegemonía",
      body: "Esta distinción entre base económica y superestructura con autonomía propia —la idea de que la cultura y la ideología no son un mero reflejo pasivo de las relaciones de producción, sino un terreno de lucha con su propia eficacia histórica— es exactamente el espacio que los revisionistas de los años sesenta necesitan para pensar la responsabilidad moral dentro del marxismo sin abandonar el marxismo.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde a la hegemonía de Gramsci o a la reificación de Lukács?",
      groups: ["Hegemonía (Gramsci)", "Reificación (Lukács)"],
      items: [
        { text: "Poder que gobierna produciendo consenso, no sólo fuerza", group: 0 },
        { text: "Las relaciones humanas toman apariencia de cosas", group: 1 },
        { text: "Se disputa en la sociedad civil: escuela, prensa, Iglesia", group: 0 },
        { text: "La conciencia deja de sentirse agente del mundo social", group: 1 },
        { text: "Da lugar a los intelectuales orgánicos de cada clase", group: 0 },
        { text: "El proletariado es a la vez sujeto y objeto de la historia", group: 1 },
      ],
      explain: "Gramsci piensa el poder cultural que produce consenso sin mostrarse como poder; Lukács piensa cómo el capitalismo vuelve cosa a la conciencia misma. Ambos abren, cada uno a su modo, un espacio para la superestructura que el revisionismo necesitaba.",
    },
    {
      type: "info",
      title: "La escala del experimento y la muerte de Stalin",
      body: "Nunca antes se había intentado, a esta escala, reingeniar seres humanos: penetrar en las almas y producir un hombre nuevo en una sociedad nueva, a lo largo de buena parte del planeta. La magnitud del experimento, y la de su catástrofe, sigue sin estar del todo asimilada.",
    },
    {
      type: "info",
      continues: true,
      title: "La escala del experimento y la muerte de Stalin",
      body: "**Stalin muere en 1953.** Sigue un período de parálisis y duelo colectivo, sin certeza sobre lo que su muerte significa ni sobre quién va a tomar el poder. El trotskista polaco **Ludwik Hass**, condenado durante el terror y sobreviviente de diecisiete años en el Gulag, resumía después el método que le permitió resistir: repetirse que Stalin, como todos, iba a morir algún día, y que él iba a sobrevivirlo. Lo sobrevivió, y por mucho.",
    },
    {
      type: "info",
      title: "1956: el discurso secreto y la fecha de quiebre",
      body: "El momento crítico en la historia intelectual del período no es marzo de 1953, sino **febrero de 1956**, cuando el sucesor de Stalin, **Nikita Jrushchov**, pronuncia ante el XX Congreso del Partido el llamado \"**discurso secreto**\" —secreto sólo durante las horas que tardó en filtrarse al resto del mundo—. Leído hoy no suena tan radical: Jrushchov habla de \"excesos, distorsiones, errores\", de un culto a la personalidad que desvió al marxismo-leninismo, sin llegar a decir que las purgas fueran una catástrofe ni que los ajusticiados fueran inocentes.",
    },
    {
      type: "info",
      continues: true,
      title: "1956: el discurso secreto y la fecha de quiebre",
      body: "Pero el solo hecho de admitir un **error**, de que alguna purga no era exigida por las leyes de hierro de la necesidad histórica, resulta demoledor para los creyentes, porque hasta entonces Stalin había sido **infalible**, la Historia hecha hombre.",
    },
    {
      type: "info",
      continues: true,
      title: "1956: el discurso secreto y la fecha de quiebre",
      body: "Žižek describe así la diferencia entre el líder estalinista y el fascista: cuando el fascista termina de hablar y la multitud aplaude, se reconoce a sí mismo como destinatario del aplauso; el estalinista también aplaude, porque el verdadero destinatario no es él, sino el gran dios de la Historia del que él mismo es apenas un servidor humilde. Tras el discurso siguen las **rehabilitaciones**: presos liberados, veredictos anulados, y hasta la restitución póstuma del carné del Partido a quienes ya habían sido ejecutados, para que sus deudos pudieran conservarlos en \"buena posición\" comunista.",
    },
    {
      type: "info",
      continues: true,
      title: "1956: el discurso secreto y la fecha de quiebre",
      body: "El año 1956 no se agota en el discurso secreto: en junio estallan en Polonia las protestas obreras de **Poznań**, reprimidas con muertos, que llevan meses después al ascenso de **Władysław Gomułka** y a una liberalización parcial conocida como el \"Octubre polaco\"; y entre octubre y noviembre estalla la **revolución húngara**, aplastada por tanques soviéticos apenas semanas después de que Lukács acepte integrar el gobierno de Nagy. Ambos episodios convierten a 1956 en la fecha que, más que cualquier otra, parte en dos la historia intelectual del comunismo europeo.",
    },
    {
      type: "quiz",
      question: "¿Por qué el discurso secreto de Jrushchov resulta demoledor para los creyentes, aunque suene moderado?",
      options: [
        "Anuncia por primera vez que las purgas fueron una catástrofe",
        "Declara inocentes a todos los ajusticiados en los juicios",
        "Propone abandonar por completo el marxismo-leninismo",
        "Admite un error, y Stalin había sido infalible hasta entonces",
      ],
      answer: 3,
      explain: "Jrushchov habla apenas de «excesos» y «distorsiones», sin llamar catástrofe a las purgas. Pero admitir un solo error basta para resquebrajar la fe: Stalin había sido la Historia hecha hombre, infalible por definición.",
    },
    {
      type: "info",
      title: "Pelar la cebolla: del estalinismo al joven Marx",
      body: "Empieza entonces un replanteo del marxismo por capas sucesivas. Primero se deja de lado a Stalin: fue una distorsión, un culto a la personalidad. ¿Y entonces? Se vuelve a **Lenin**, hasta sospechar que las raíces del estalinismo ya estaban ahí, y se lo deja de lado también para volver a **Marx**.",
    },
    {
      type: "info",
      continues: true,
      title: "Pelar la cebolla: del estalinismo al joven Marx",
      body: "El paso siguiente es notar que la lectura leninista se apoyó demasiado en el **Marx tardío**, el de las leyes económicas objetivas, y demasiado poco en el **joven Marx**, el de los Manuscritos económico-filosóficos de 1844, ocupado sobre todo por la **alienación** y su superación mediante la praxis. Desde ahí se vuelve a leer a **Hegel**, y a Hegel a través de Heidegger y Sartre.",
    },
    {
      type: "info",
      continues: true,
      title: "Pelar la cebolla: del estalinismo al joven Marx",
      body: "Es un movimiento como el de pelar una cebolla: si algo salió mal, la respuesta debe estar en Marx mismo, no fuera de él, del mismo modo en que un creyente relee la Biblia antes de abandonar la fe. El marxismo sigue siendo, para estos pensadores, la idea más bella y liberadora que la humanidad produjo; si algo falló, la falla estuvo en el plano de ejecución, no en el texto fundador.",
    },
    {
      type: "info",
      continues: true,
      title: "Pelar la cebolla: del estalinismo al joven Marx",
      body: "Filosóficamente, estos exestalinistas que repiensan su marxismo buscan todos lo mismo: dónde trazar la frontera entre el determinismo histórico y la responsabilidad individual. Si quienes vitoreaban las ejecuciones de sus amigos lo hacían porque creían en la necesidad de hierro de esas purgas, y esa necesidad no era tan de hierro, entonces hay sangre en las manos de todos. La pregunta que ya organizaba el comienzo del curso —dónde está la línea entre necesidad histórica y libertad— vuelve aquí con una **urgencia moral** que antes no tenía, porque de esa línea depende ahora cuán culpable es cada uno.",
    },
    {
      type: "quiz",
      question: "¿Por qué el paso de Stalin al «joven Marx» se compara con pelar una cebolla?",
      options: [
        "Porque cada capa revela que Marx mismo estaba equivocado",
        "Porque el proceso termina, sin excepción, en Lenin",
        "Porque no hay ningún orden entre las capas que se pelan",
        "Cada capa descartada busca la falla sin abandonar al autor",
      ],
      answer: 3,
      explain: "Primero se descarta a Stalin, luego a Lenin, y se llega al joven Marx: si algo falló, debe estar en el texto fundador o en su ejecución, nunca fuera de él, como un creyente que relee la Biblia antes de perder la fe.",
    },
    {
      type: "info",
      title: "Kołakowski: valores y responsabilidad",
      body: "El polaco **Leszek Kołakowski** (1927-2009), expulsado del Partido Comunista en 1966 y del país poco después, es de los primeros en insistir en que hay que hallar, dentro del marxismo, un lugar para la elección individual y los valores morales: las personas son las únicas creadoras de valores, sostiene, independientemente de que se acepte o se niegue una visión determinista del mundo. No descarta el determinismo, pero lo somete a un límite.",
    },
    {
      type: "info",
      continues: true,
      title: "Kołakowski: valores y responsabilidad",
      body: "Nadie está libre de responsabilidad porque sus acciones individuales sean sólo un fragmento del proceso histórico. No es cierto que la filosofía de la historia determine nuestras elecciones fundamentales: eso lo hace nuestra sensibilidad moral. No somos comunistas porque hayamos reconocido el comunismo como necesidad histórica; somos comunistas porque nos hemos puesto del lado de los oprimidos contra los opresores, de los pobres contra sus amos, de los perseguidos contra sus perseguidores.",
    },
    {
      type: "info",
      continues: true,
      title: "Kołakowski: valores y responsabilidad",
      body: "No es una posición cómoda dentro de la tradición: Marx y Engels desconfiaban del socialista utópico que apela al sentimiento moral; el Manifiesto presenta al comunismo como necesidad histórica, no como elección ética. Kołakowski responde que se está del lado de los oprimidos porque se elige estarlo, y agrega el argumento de fondo que sostiene a todo el revisionismo: frente a la devastación de la Segunda Guerra, el marxismo seguía siendo la única esperanza disponible, y abandonarlo del todo no dejaba nada en su lugar.",
    },
    {
      type: "quiz",
      question: "Para Kołakowski, ¿por qué alguien se hace comunista?",
      options: [
        "Porque reconoce que el comunismo es inevitable según la Historia",
        "Porque el Manifiesto lo presenta como una elección sentimental",
        "Porque no queda ninguna otra alternativa política disponible",
        "Porque elige el lado de los oprimidos, no la necesidad histórica",
      ],
      answer: 3,
      explain: "Contra Marx y Engels, que desconfiaban del socialismo apelado al sentimiento moral, Kołakowski sostiene que somos comunistas porque nos ponemos del lado de los oprimidos: una elección ética, no un cálculo de necesidad histórica.",
    },
    {
      type: "info",
      title: "La alienación y el Grupo Praxis (Yugoslavia)",
      body: "El término **alienación** vuelve al centro de la discusión: el estalinismo no la resolvió, la llevó a un extremo inimaginable. Ese diagnóstico es el punto de partida del **Grupo Praxis** en Yugoslavia, reunido en torno a la revista homónima entre 1964 y 1974, que recorre el mismo movimiento de pelar capas hacia el joven Marx.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación y el Grupo Praxis (Yugoslavia)",
      body: "Sus propuestas concretas —la autogestión obrera de las fábricas— son menos centrales que su preocupación teórica: superar la alienación mediante la **praxis**, entendida como acción teóricamente informada, existencialmente plena y desalienante, no mero pensamiento. Mihailo Marković la formula así:",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación y el Grupo Praxis (Yugoslavia)",
      body: "El supuesto filosófico fundamental es que el hombre es esencialmente un ser de praxis: capaz de actividad libre y creadora por la que transforma el mundo, realiza sus facultades potenciales y satisface las necesidades de otros. Esa discrepancia entre la existencia actual y la esencia potencial del individuo es la alienación. La tarea básica de la filosofía es analizarla críticamente e indicar los pasos prácticos hacia la autorrealización.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación y el Grupo Praxis (Yugoslavia)",
      body: "En esta fórmula resuenan Sartre (el en-sí y el para-sí, facticidad y trascendencia) y Kojève (el hombre como negación de lo dado). A esta corriente se la llama **humanismo marxista**: inyectarle al marxismo una subjetividad más carnal y moralmente inflexionada sin abandonarlo.",
    },
    {
      type: "info",
      continues: true,
      title: "La alienación y el Grupo Praxis (Yugoslavia)",
      body: "Gajo Petrović sostiene que sólo la revolución dirigida a abolir toda explotación y superar toda autoalienación merece llamarse revolución en sentido pleno; también aquí resuena Beauvoir, en la idea de trascender y volverse sujeto pleno en lugar de objeto sobre el que otros actúan. El grupo funda la Escuela de Verano de Korčula (Croacia, 1969-1972), donde llegan a coincidir Marcuse y Heidegger.",
    },
    {
      type: "quiz",
      question: "¿Qué entiende el Grupo Praxis por «praxis», a diferencia de la mera práctica?",
      options: [
        "Cualquier trabajo manual realizado dentro de una fábrica",
        "La obediencia disciplinada a las directivas del Partido",
        "Un concepto exclusivamente teórico, ajeno a toda acción",
        "Una acción plena, informada y a la vez desalienante",
      ],
      answer: 3,
      explain: "Para el Grupo Praxis, el ser humano es esencialmente un ser de praxis: actividad libre y creadora, teóricamente informada, que supera la alienación entre lo que se es y lo que se podría ser. No basta pensar: hay que actuar de ese modo.",
    },
    {
      type: "info",
      title: "Checoslovaquia: entusiasmo, terror y resistencia a desestalinizar",
      body: "En febrero de 1948 los comunistas toman el poder en Checoslovaquia con enorme entusiasmo popular: en las elecciones libres de 1946 habían obtenido el 38 %, la primera minoría del país. **Milan Kundera**, parte de esa generación de jóvenes estalinistas formados bajo la impresión de la traición de Múnich, describiría después ese febrero como un momento en que los comunistas tomaron el poder no con sangre sino con los vítores de casi la mitad de la población, y agrega que esa mitad era, además, la más dinámica y la más inteligente.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: entusiasmo, terror y resistencia a desestalinizar",
      body: "Su contemporáneo **Karel Kosík**, comentando el juicio a Slánský en 1951, escribía entonces que sólo bandidos cosmopolitas como los acusados podían atreverse contra la alianza con la Unión Soviética.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: entusiasmo, terror y resistencia a desestalinizar",
      body: "Esta generación se resiste especialmente a desestalinizar: cuando en otros países se derriban las estatuas de Stalin después de 1953, en Checoslovaquia no. El discurso secreto los obliga, sin embargo, a reunirse en el Congreso de la Unión de Escritores de 1956, donde declaran que su generación creció con el nombre de Stalin en los labios, que sus mejores amigos murieron en campos nazis pronunciando ese nombre, y que no van a disculparse ni a avergonzarse. Encontrar un lenguaje por fuera del estalinismo para criticar al estalinismo resulta casi imposible, porque el lenguaje estalinista era el único disponible.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: entusiasmo, terror y resistencia a desestalinizar",
      body: "Empiezan entonces a tomar prestado el vocabulario del existencialismo: oponen la conciencia de clase a la conciencia moral, \"el pueblo\" como colectivo singular a \"las personas\" en plural, y en lugar de verdades objetivas hablan de responsabilidad. Una generación más joven, a principios de los sesenta, les reclama abiertamente qué clase de gente eran, que dejaron ir a sus amigos a las cámaras de tortura y encima lo vitorearon.",
    },
    {
      type: "info",
      continues: true,
      title: "Checoslovaquia: entusiasmo, terror y resistencia a desestalinizar",
      body: "Empieza así la autocrítica: **Ladislav Mňačko** admite que todos, en algún momento, mientras arrestaban a sus amigos, gritaron para que los apedrearan, y que ahora hace falta hablar de por qué ocurrió y de quiénes son.",
    },
    {
      type: "info",
      title: "Kosík: razón y conciencia",
      body: "**Karel Kosík** produce la versión filosóficamente más elaborada del revisionismo checo, apoyada en una relectura de Marx y Hegel a través de Heidegger: estamos siempre ya arrojados a la historia, que tiene su propio impulso, pero también estamos involucrados activamente en ella, en un modelo interactivo entre individuo e historia.",
    },
    {
      type: "info",
      continues: true,
      title: "Kosík: razón y conciencia",
      body: "Desde el momento en que estos factores históricos deterministas conducen la historia hacia una meta con fatal inevitabilidad y ley de hierro, entramos en conflicto: ¿cómo armonizar esa inexorabilidad con el esfuerzo humano y con el sentido de la actividad humana? Esta antinomia entre las leyes de la historia y la historia humana no se ha resuelto satisfactoriamente.",
    },
    {
      type: "info",
      continues: true,
      title: "Kosík: razón y conciencia",
      body: "Si nos reducimos a meros objetos de leyes de hierro, abdicamos la responsabilidad moral; sin descartar del todo el determinismo, hace falta ese modelo interactivo. En una charla de 1967 titulada Razón y conciencia, Kosík recurre a la historia de un reformador religioso quemado en la hoguera en 1450, a quien en prisión le aconsejan que, si el concilio eclesiástico le dice que sólo tiene un ojo, admita que el concilio tiene razón. El prisionero responde que sabe, por su propia razón, que tiene dos ojos, y que negar la razón es una traición a la conciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Kosík: razón y conciencia",
      body: "El caso de **Otto Katz**, alto dirigente juzgado junto con Slánský, ilustra la contracara de esa traición: su declaración final, exigiendo para sí el castigo máximo, está tomada casi textualmente de Oscuridad al mediodía, la novela de Koestler que había expuesto precisamente el mecanismo de los juicios de Moscú de los años treinta. Traducida a muchos idiomas, esa retórica llega a Praga, Katz mismo la reproduce ante el tribunal, se la creen, y lo ahorcan. La pérdida de la unidad entre razón y conciencia, escribe Kosík, desemboca en el nihilismo puro.",
    },
    {
      type: "info",
      continues: true,
      title: "Kosík: razón y conciencia",
      body: "En ese mismo congreso de 1967, **Ludvík Vaculík** se dirige a escritores y dirigentes del Partido diciendo que, si hoy le preguntaran si puede realizarse el sueño marxista, tendría que responder, con toda buena voluntad, que simplemente no lo sabe. Esa admisión de duda frente a las leyes de hierro resulta el enunciado más radical de la jornada, y Vaculík es expulsado del Partido de inmediato.",
    },
    {
      type: "quiz",
      question: "¿Qué defiende el prisionero de 1450 que Kosík recuerda en «Razón y conciencia»?",
      options: [
        "Que hay que obedecer siempre a la autoridad del concilio",
        "Que la razón individual jamás puede equivocarse en nada",
        "Que ver con los propios ojos no prueba nada por sí solo",
        "Que negar lo que ve la razón es traicionar la conciencia",
      ],
      answer: 3,
      explain: "Aunque el concilio le exija admitir que sólo tiene un ojo, el prisionero se aferra a lo que sabe por su propia razón. Kosík usa la parábola para pensar los juicios-espectáculo: someter la razón al poder es traicionar la conciencia.",
    },
    {
      type: "match",
      question: "Uní cada pensador del marxismo revisionista con su aporte",
      pairs: [
        { left: "Lukács", right: "La reificación: la conciencia contempla el mundo como cosa" },
        { left: "Gramsci", right: "La hegemonía: el consenso producido por la sociedad civil" },
        { left: "Kołakowski", right: "Somos comunistas por elección moral, no por necesidad" },
        { left: "Grupo Praxis", right: "Superar la alienación mediante una praxis desalienante" },
        { left: "Kosík", right: "Un modelo interactivo entre la historia y la conciencia" },
      ],
      explain: "Cada uno abre, a su modo, un espacio para la subjetividad dentro del marxismo: Lukács y Gramsci desde la superestructura, Kołakowski desde la elección ética, el Grupo Praxis desde la praxis desalienante, Kosík desde la interacción entre determinismo e historia humana.",
    },
    {
      type: "info",
      title: "Cierre: la Primavera de Praga y sus secuelas",
      body: "El marxismo revisionista, en conjunto, intenta inyectarle al hegelianismo marxista una subjetividad más robusta, permanece obsesionado con la relación entre determinismo y responsabilidad, y desemboca en una filosofía de raíz heideggeriana según la cual estamos siempre ya incrustados en la historia —nunca actuamos desde una tabula rasa— pero también la moldeamos con nuestras acciones: un modelo interactivo, no una calle de una sola mano.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la Primavera de Praga y sus secuelas",
      body: "Tras las expulsiones del congreso de escritores, cae **Antonín Novotný** y asume **Alexander Dubček**, que adopta abiertamente el marxismo revisionista. En la primavera y el verano de **1968**, dirigencia e intelectuales se alían, se abren rehabilitaciones públicas, y se intenta construir un \"socialismo con rostro humano\": la creencia de que esa tercera vía —un humanismo marxista desalienante— podía realizarse de verdad.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la Primavera de Praga y sus secuelas",
      body: "Nunca se sabrá si podía, porque en **agosto de 1968** los tanques del Pacto de Varsovia entran en Praga y aplastan el experimento. El comunismo siguió dos décadas más en Europa del Este, pero, paradójicamente, esos tanques mataron ahí al marxismo como filosofía profundamente vivida y creída.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la Primavera de Praga y sus secuelas",
      body: "Kosík, Vaculík y Kundera —el joven estalinista entusiasta vuelto revisionista crítico— se convierten después en los disidentes y exiliados de los años setenta y ochenta. En 1975, mientras la policía secreta checa registraba su departamento, confiscó dos manuscritos larguísimos de Kosík sobre la verdad y la praxis, mil páginas en un solo ejemplar, escritas antes de las computadoras y sin fotocopiadoras de por medio.",
    },
    {
      type: "info",
      continues: true,
      title: "Cierre: la Primavera de Praga y sus secuelas",
      body: "Kosík le escribió entonces a Sartre, que publicó una respuesta de apoyo en Le Monde aunque no tuviera poder alguno sobre la policía checa. Kundera lo resumiría después: en esos años, escribirle a Sartre era el último recurso disponible para un intelectual, y cuando Sartre murió, en 1980, ya no quedó nadie a quien dirigir semejante carta.",
    },
  ],
};
