export default {
  num: 3,
  transcript: 4,
  title: "Hegel y el cronotopo historicista",
  source: "https://www.youtube.com/watch?v=EozQmkpHKUc",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**Georg Wilhelm Friedrich Hegel** (1770-1831) nace en Stuttgart y muere en Berlín durante una epidemia de cólera. Estudia teología en el seminario de Tubinga, donde comparte habitación con el poeta **Hölderlin** y con **Schelling**: los tres son adolescentes cuando estalla la **Revolución Francesa** en 1789, y los tres la viven como el acontecimiento que parte la historia en dos.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Cuatro obras ordenan su pensamiento. La Fenomenología del Espíritu (1807), que recorre el itinerario de la conciencia hasta el saber absoluto. La Ciencia de la lógica (1812-1816), el corazón técnico del sistema. La Enciclopedia de las ciencias filosóficas (1817), el sistema completo en compendio. Y los Rasgos fundamentales de la filosofía del derecho (1821), su filosofía política.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "A eso se suman las Lecciones sobre la filosofía de la historia, publicadas póstumamente en 1837 a partir de apuntes de sus alumnos. De ahí sale casi todo lo que se cita popularmente sobre \"el sentido de la historia\" en Hegel. Enseña en Jena, dirige un colegio en Núremberg, pasa por Heidelberg y desde 1818 ocupa la cátedra de Berlín, donde se convierte en el filósofo oficial de Prusia.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "En octubre de 1806, mientras termina la Fenomenología, Napoleón entra en Jena tras derrotar al ejército prusiano. Hegel le escribe a un amigo que vio al emperador cabalgando por la ciudad y lo llama el **alma del mundo**: para Hegel, el movimiento de la historia universal estaba pasando por Jena en ese momento.",
    },
    {
      type: "info",
      title: "El problema que Hegel hereda",
      body: "Para entender qué viene a resolver Hegel hay que recordar dónde lo dejó **Kant**. En la Crítica de la razón pura (1781), Kant había negociado un compromiso: hay un mundo real, independiente de la mente —la **Ding an sich**, la cosa en sí—, pero no tenemos acceso a él. Sólo conocemos el fenómeno, el mundo tal como nuestra conciencia lo procesa.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Hegel hereda",
      body: "Esa solución dejó a toda una generación insatisfecha. Si la cosa en sí es incognoscible, ¿por qué seguir postulándola? Es una frontera que la filosofía traza y después declara infranqueable. **Fichte** y **Schelling**, los inmediatos herederos de Kant, intentan cada uno a su modo disolver esa frontera: si el sujeto no puede salir hacia el objeto, tal vez sujeto y objeto sean, en el fondo, lo mismo.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que Hegel hereda",
      body: "Hegel entra en esa conversación y hace la apuesta más ambiciosa de todas. No va a suprimir la diferencia entre sujeto y objeto por decreto: va a mostrar que esa diferencia **se produce y se supera en el tiempo**, que es un momento de un proceso. La cosa en sí no sería un límite permanente del conocimiento, sino una etapa que la conciencia todavía no atravesó.",
    },
    {
      type: "quiz",
      question: "A diferencia de Kant, para Hegel la diferencia entre sujeto y objeto…",
      options: [
        "es una frontera permanente que ningún conocimiento puede cruzar",
        "no existe en absoluto: sujeto y objeto son la misma cosa",
        "se produce y se supera con el paso del tiempo",
        "sólo puede resolverse apelando a una fe religiosa compartida",
      ],
      answer: 2,
      explain: "Kant deja la Ding an sich como límite infranqueable del conocimiento. Fichte y Schelling intentan disolver esa frontera diciendo que sujeto y objeto son, en el fondo, lo mismo. Hegel hace algo distinto: muestra que esa diferencia se produce y se supera en el tiempo, que es una etapa que la conciencia todavía no atravesó.",
    },
    {
      type: "info",
      title: "Hegel y el impulso de reconciliación",
      body: "Hegel va a ser el que llega con un tema de **reconciliación** —aunque no de manera muy pacífica—: reconciliación entre las corrientes ilustrada y romántica, entre el individuo y la sociedad, entre la razón y la pasión. El impulso de todo su pensamiento tiene que ver con la **superación de las divisiones**, con la superación de las contradicciones.",
    },
    {
      type: "info",
      continues: true,
      title: "Hegel y el impulso de reconciliación",
      body: "Todo su pensamiento parte de una constatación: siempre hay opuestos. La razón y la pasión, el ser y el deber ser, el yo y el otro, el individuo y lo universal. La pregunta que organiza su obra entera es cómo juntar esas cosas, y la respuesta tiene una ambición desmedida: unirlo todo.",
    },
    {
      type: "info",
      continues: true,
      title: "Hegel y el impulso de reconciliación",
      body: "Hegel comparte el impulso ilustrado de hacer de la filosofía algo parecido a una ciencia, pero quiere hacerlo de otra manera, porque siente que la Ilustración fue **demasiado escéptica y superficial**: buena para desarmar la fe, buena para desencantar, pero sin dar suficiente profundidad a cambio. Desarma más de lo que entrega.",
    },
    {
      type: "quiz",
      question: "El impulso que organiza todo el pensamiento de Hegel es…",
      options: [
        "desconfiar de la razón y devolverle su lugar a la pasión",
        "superar las divisiones y las contradicciones",
        "elegir entre la Ilustración y el Romanticismo",
        "describir el mundo sin intervenir en él",
      ],
      answer: 1,
      explain: "Razón y pasión, el ser y el deber ser, el yo y el otro, el individuo y lo universal: frente a cada par de opuestos, Hegel no elige un polo. Quiere reconciliarlos, y no de manera muy pacífica.",
    },
    {
      type: "quiz",
      question: "¿Qué le reprocha Hegel a la Ilustración?",
      options: [
        "Que desarma la fe sin dar profundidad a cambio",
        "Que convirtió la filosofía en una ciencia exacta",
        "Que puso la historia en el centro de la filosofía",
        "Que se dejó llevar por el entusiasmo romántico",
      ],
      answer: 0,
      explain: "Demasiado escéptica y superficial: buena para desencantar, buena para desarmar la fe, pero desarma más de lo que entrega. Hegel comparte su ambición de hacer de la filosofía una ciencia, pero quiere que además dé algo a cambio.",
    },
    {
      type: "info",
      title: "El problema del puente",
      body: "La pregunta epistemológica va a volver una y otra vez: ¿cómo sé que la taza existe de verdad y no es una proyección de mi conciencia? ¿Cómo sé que esta silla está realmente ahí? ¿Cómo se pasa del **sujeto al objeto**? Es el **problema del puente**: el problema que intentaron resolver Descartes, Kant, todos. Ahí estás, dentro de tu cabeza, y ahí está el mundo afuera: ¿cómo encontrás ese puente mágico de adentro hacia afuera?",
    },
    {
      type: "info",
      continues: true,
      title: "El problema del puente",
      body: "Los filósofos lo describen de mil maneras —mente y mundo, conciencia y ser, inmanente y trascendente, interior y exterior, sujeto y objeto—, pero son todas formas de hablar de lo mismo: nadie puede salir de su propia cabeza. Hegel quiere elevar la filosofía a ciencia y **resolver el problema del puente**: unir sujeto y objeto, con una pizca de misticismo añadida.",
    },
    {
      type: "quiz",
      question: "¿En qué consiste el «problema del puente»?",
      options: [
        "En pasar del sujeto al objeto sin salir de la propia cabeza",
        "En conciliar la fe religiosa con los hallazgos de la ciencia",
        "En unir el pasado con el futuro en una misma historia",
        "En traducir a un lenguaje común lo que dicen los filósofos",
      ],
      answer: 0,
      explain: "Mente y mundo, conciencia y ser, interior y exterior: son todas maneras de nombrar lo mismo. Se está adentro de la propia cabeza y el mundo está afuera. Descartes y Kant ya habían intentado tender ese puente; Hegel quiere cruzarlo elevando la filosofía a ciencia.",
    },
    {
      type: "info",
      title: "La historia como componente de la filosofía",
      body: "Uno de los elementos centrales de su proyecto de conectar sujeto y objeto es tomar la **historia** y convertirla en un componente integral y constitutivo de la filosofía misma. Esto puede sonar obvio, pero no lo era. La filosofía, viniendo de la tradición griega antigua, tendía a enfocarse en lo **atemporal y universal**: ese ideal de que dos más dos es cuatro.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia como componente de la filosofía",
      body: "Todos los filósofos quieren llegar a una noción de verdad tan cierta como esa, y lo que la vuelve tan atractiva —el hombre del subsuelo de Dostoievski protestará precisamente contra eso— es que es **universal y atemporal**: vale siempre, en todas partes, para todos.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia como componente de la filosofía",
      body: "La historia, en cambio, siempre trae lo empírico y contingente: las cosas cambian, se despliegan distinto en un lugar y en otro. Hegel toma la historia —que tradicionalmente se intentaba **purgar** de la filosofía— y la vuelve componente integral. Su unión de sujeto y objeto va a implicar **moverse a través de la historia**, con esa conciencia del tiempo que pasa.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de la verdad atemporal que buscaba la filosofía griega o de la historia que Hegel le incorpora?",
      groups: ["Verdad atemporal", "Historia"],
      items: [
        { text: "Vale siempre, en todas partes y para todos", group: 0 },
        { text: "El modelo es que dos más dos es cuatro", group: 0 },
        { text: "Contra eso protesta el hombre del subsuelo", group: 0 },
        { text: "Trae lo empírico y lo contingente", group: 1 },
        { text: "Las cosas se despliegan distinto en cada lugar", group: 1 },
        { text: "La filosofía intentaba purgarla de su terreno", group: 1 },
      ],
      explain: "La tradición griega buscaba lo atemporal y universal, y por eso trataba de expulsar lo histórico. Hegel hace exactamente lo contrario: mete la historia adentro de la filosofía, porque unir sujeto y objeto exige moverse a través del tiempo.",
    },
    {
      type: "info",
      title: "Historicismo: la verdad tiene fecha",
      body: "Esto tiene una consecuencia que conviene nombrar con precisión, porque es el aporte más duradero de Hegel. Se llama **historicismo**: la tesis de que los fenómenos humanos —una idea, una institución, una obra de arte, una moral— sólo se comprenden situándolos en el momento del desarrollo histórico al que pertenecen. No hay verdades filosóficas flotando fuera del tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "Historicismo: la verdad tiene fecha",
      body: "Es una idea de doble filo, y por eso va a atravesar todo el curso. De un lado libera: vacuna contra tomar las costumbres propias por naturaleza, muestra que lo que parece eterno tiene fecha de nacimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Historicismo: la verdad tiene fecha",
      body: "Del otro amenaza: si toda verdad es hija de su época, ¿qué queda del criterio para decir que una época se equivocó? Ese es el **problema del relativismo histórico**, y va a reaparecer en Nietzsche, en Weber, en toda la crisis del siglo XX.",
    },
    {
      type: "info",
      continues: true,
      title: "Historicismo: la verdad tiene fecha",
      body: "Hegel cree tener la respuesta: cada época es parcial, sí, pero las épocas se ordenan en una progresión con dirección. Ninguna es verdadera por sí sola; todas juntas, vistas desde el final, componen la verdad. Es una salida elegante y depende enteramente de que exista ese final. Cuando el final se vuelva increíble —y se va a volver—, el historicismo quedará sin red.",
    },
    {
      type: "quiz",
      question: "El problema del relativismo histórico que abre el historicismo es que…",
      options: [
        "falta un criterio para decir que una época se equivocó",
        "las épocas antiguas resultan siempre superiores a las modernas",
        "ya no se puede escribir la historia de ningún período",
        "las instituciones pierden toda influencia sobre las personas",
      ],
      answer: 0,
      explain: "Si toda verdad es hija de su época, ¿qué queda del criterio para decir que una época se equivocó? Hegel cree tener la respuesta: cada época es parcial, pero todas juntas, vistas desde el final, componen la verdad. Cuando ese final se vuelva increíble, el historicismo queda sin red.",
    },
    {
      type: "info",
      title: "El cronotopo",
      body: "El término **cronotopo** no es de Hegel: lo acuña mucho después el crítico ruso **Mijaíl Bajtín**, en un ensayo de fines de los años treinta sobre las formas del tiempo en la novela.",
    },
    {
      type: "info",
      continues: true,
      title: "El cronotopo",
      body: "Del griego chronos (tiempo) y topos (lugar), nombra la manera en que una obra o una época **fusiona el espacio y el tiempo** en una sola imagen del mundo: no un tiempo abstracto por un lado y un escenario por otro, sino una forma indivisible de habitar ambos.",
    },
    {
      type: "info",
      continues: true,
      title: "El cronotopo",
      body: "Aplicado a Hegel, hablar de un **cronotopo historicista** es decir que su filosofía no es un conjunto de tesis sino una forma del tiempo: un tiempo direccional, acumulativo, que va hacia algún lado y arrastra el espacio consigo. Es la forma-tiempo que la modernidad hereda de la Ilustración —el progreso— pero cargada de tensión, conflicto y saltos.",
    },
    {
      type: "quiz",
      question: "El cronotopo que Bajtín describe, aplicado a Hegel, nombra…",
      options: [
        "funde el espacio y el tiempo en una sola imagen",
        "un tiempo cíclico que vuelve siempre sobre lo mismo",
        "un espacio sin ninguna relación con el paso del tiempo",
        "la separación estricta entre historia y geografía",
      ],
      answer: 0,
      explain: "Cronotopo, del griego chronos y topos, nombra la manera en que una obra o una época fusiona espacio y tiempo en una sola imagen del mundo. Aplicado a Hegel, hablar de un cronotopo historicista es decir que su filosofía es una forma del tiempo: direccional, acumulativo, que arrastra el espacio consigo.",
    },
    {
      type: "info",
      title: "Ser y devenir: el movimiento como esencia",
      body: "Junto con esto aparece algo central del Romanticismo: el Sein frente al Werden, el **ser frente al devenir**. Fichte lo había formulado así: \"ser libre no es nada; devenir libre lo es todo\". La acción es central, y también este cambio en el tiempo: no se trata de lo que \"es\" de manera atemporal y estática, sino de lo que **se mueve, de lo que deviene**. Para Hegel siempre estamos **deviniendo**, siempre estamos en camino; todo está en movimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Ser y devenir: el movimiento como esencia",
      body: "Es un pensamiento inquieto, casi ansioso. Todo tiene que moverse siempre; no hay lugar para el reposo, y detenerse es una forma del error. Nunca hay satisfacción posible con lo que hay, nunca un punto donde tomar aire: siempre se está en camino, siempre en proceso. Ese movimiento de **convertirse en otra cosa** es lo esencial.",
    },
    {
      type: "quiz",
      question: "Que Hegel privilegie el Werden sobre el Sein significa que…",
      options: [
        "lo esencial es lo que deviene, no lo que ya es",
        "sólo existe aquello que se percibe en el presente",
        "el cambio es una ilusión frente al ser verdadero",
        "la libertad se alcanza y después queda garantizada",
      ],
      answer: 0,
      explain: "El par es Sein frente al Werden: el ser frente al devenir. Fichte ya lo había dicho: «ser libre no es nada; devenir libre lo es todo». Nunca se llega a un reposo, nunca se puede tomar aire: siempre se está en camino, siempre convirtiéndose en otra cosa.",
    },
    {
      type: "info",
      title: "De cantidad a calidad",
      body: "Con Hegel siempre te movés, pero no a un ritmo calmo y parejo, sino a los saltos: un estallido, luego una desaceleración, luego otro estallido. Se oye mucho en Hegel sobre la **transformación de la cantidad en calidad**. La idea es que hay momentos en que los cambios de escala se vuelven tan grandes que son, de hecho, cambios de **tipo**: cuando los cambios de grado se vuelven cambios de clase.",
    },
    {
      type: "info",
      continues: true,
      title: "De cantidad a calidad",
      body: "El modelo es el **agua que hierve**: tenés agua fría, la calentás un poco, no parece cambiar; la calentás un poco más, sigue igual; y de golpe, al llegar al punto de ebullición —100 °C—, ¡bam!, la cantidad se transforma en calidad, el agua cambia de forma y se vuelve vapor. Ese único grado entre 99 y 100 no es distinto del que va de 65 a 66, pero ahí se produce el **salto**. Para Hegel, toda la vida va a ser así.",
    },
    {
      type: "quiz",
      question: "El agua que hierve ilustra que…",
      options: [
        "acumular grados termina en un cambio de clase",
        "todo cambio verdadero es gradual y sin sobresaltos",
        "la naturaleza repite siempre los mismos ciclos",
        "medir con precisión es la única forma de conocer",
      ],
      answer: 0,
      explain: "El grado que va de 99 a 100 no es distinto del que va de 65 a 66, y sin embargo ahí el agua se vuelve vapor. Así se mueve todo para Hegel: no a ritmo parejo, sino a los saltos, cuando la cantidad acumulada se transforma en calidad.",
    },
    {
      type: "info",
      title: "Geist: el Espíritu",
      body: "**Geist** es el próximo gran concepto de Hegel. A veces traducido como \"mente\", pero más frecuentemente como \"**espíritu**\", conviene dejarlo en alemán porque no traduce con precisión. Es uno de esos conceptos cruciales que quedan deliberadamente vagos. Su meta es un **sistema unificado y omniabarcador**, una gran visión de qué es el universo y de cómo se mueve la historia, fundada no en el mundo material sino en esta cosa llamada Geist.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "Podés pensar el Espíritu como una especie de espíritu individual que, sin embargo, abarca todo el universo: imaginate el universo como una entidad animada, con alma. Cuando decís \"Espíritu\", pensá en **espíritu de equipo** (team spirit). Hegel va a tomar la idea del todo, de la vida social colectiva, y a dignificarla como fundamento filosófico absoluto; va a hablar del Espíritu como otros filósofos hablaron de Dios.",
    },
    {
      type: "short",
      question: "¿Qué palabra usa Hegel para el espíritu que anima al todo?",
      answers: ["Geist", "espíritu"],
      explain: "Geist se traduce a veces como «mente» y más seguido como «espíritu», pero conviene dejarlo en alemán: ninguna traducción da con la idea de un universo entero animado, con alma, que se vuelve claro para sí mismo a través de la historia.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "La frase de Hegel es: \"**el yo que es un nosotros y el nosotros que es un yo**\", y eso es el Espíritu: una manera de reunir al individuo y al todo. Para Hegel, el Geist es el **poder del todo**, y todo es **relacional**: las cosas no tienen significado tomadas por separado, en aislamiento; todo es parte de la relación con el todo.",
    },
    {
      type: "quiz",
      question: "«El yo que es un nosotros y el nosotros que es un yo» quiere decir que…",
      options: [
        "todo es relacional, nada vale por separado",
        "el individuo debe disolverse del todo en la masa",
        "el Estado siempre tiene razón frente al individuo",
        "cada conciencia está encerrada en sí misma",
      ],
      answer: 0,
      explain: "Pensá en el espíritu de equipo: las cosas no tienen significado tomadas en aislamiento, sino en su relación con el todo. Hegel apoya en el Espíritu lo que otros filósofos apoyaron en Dios, y desde ahí explica la agencia individual y la vida social.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "El Espíritu tiene grados, y los nombres importan porque van a circular por todo el siglo XIX. El **Volksgeist** es el espíritu de un pueblo: esa forma particular que el Espíritu adopta en una nación, su lengua, su arte, sus leyes. El **Weltgeist** es el Espíritu del mundo, el sujeto último de la historia universal.",
    },
    {
      type: "quiz",
      question: "El Volksgeist se distingue del Weltgeist en que…",
      options: [
        "es el espíritu de un pueblo, no de todo el mundo",
        "es el espíritu del mundo entero, no el de una nación",
        "son dos nombres distintos para exactamente lo mismo",
        "sólo se aplica a los pueblos germánicos y cristianos",
      ],
      answer: 0,
      explain: "El Espíritu tiene grados: el Volksgeist es el espíritu de un pueblo, esa forma particular que adopta en una nación, su lengua, su arte, sus leyes. El Weltgeist es el Espíritu del mundo, el sujeto último de la historia universal.",
    },
    {
      type: "info",
      continues: true,
      title: "Geist: el Espíritu",
      body: "Cuando Hegel ve a Napoleón en Jena y dice \"el alma del mundo a caballo\", está diciendo exactamente eso: que en ese hombre concreto se encarna, por un momento, el movimiento de la historia entera.",
    },
    {
      type: "info",
      title: "La dialéctica",
      body: "¿Cómo se mueve la historia? De esa manera inquieta y a los saltos, a través de lo que Hegel llama **dialéctica**. Se la interpreta de varios modos, pero la idea inicial es: la dialéctica es lo que ocurre cuando las **contradicciones se encuentran**. Siempre hay algún choque, algún antagonismo que empuja la historia hacia adelante.",
    },
    {
      type: "info",
      continues: true,
      title: "La dialéctica",
      body: "Cuando una posición demuestra ser inestable y algo la niega, este paso a una posición nueva se llama **negación determinada** de la primera. El adjetivo hace todo el trabajo: la negación no es un \"no\" abstracto que deja la nada, es un \"no\" que conserva la marca de aquello que niega. Por eso la dialéctica avanza en lugar de destruir. Lo negado sigue actuando dentro de lo que viene después.",
    },
    {
      type: "quiz",
      question: "La «negación determinada» de la dialéctica de Hegel es un «no» que…",
      options: [
        "conserva la marca de lo que niega, no lo borra",
        "borra por completo la posición anterior, sin dejar rastro",
        "sólo aparece cuando chocan dos posiciones externas entre sí",
        "detiene el movimiento de la historia hasta nuevo aviso",
      ],
      answer: 0,
      explain: "Cuando una posición demuestra ser inestable y algo la niega, ese paso se llama negación determinada: no es un «no» abstracto que deja la nada, sino uno que conserva la marca de lo que niega. Por eso la dialéctica avanza en lugar de destruir.",
    },
    {
      type: "info",
      title: "El ejemplo del árbol frutal",
      body: "El ejemplo más claro que da Hegel es el crecimiento de un árbol frutal: hay una semilla, luego un brote, en primavera el pimpollo, después la hoja, luego la flor, y por fin el fruto. Cuando llega el fruto, este **cancela la flor**: no tenés flor y fruto al mismo tiempo; el fruto llega como negación dialéctica de la flor.",
    },
    {
      type: "info",
      continues: true,
      title: "El ejemplo del árbol frutal",
      body: "La flor es superada, suplantada, cancelada, pero no de modo que desaparezca por completo: es llevada a un nivel superior, se acerca a su **telos** —el fin al que siempre apuntó—. En la semilla de manzana, el telos es la manzana.",
    },
    {
      type: "quiz",
      question: "Que el fruto «cancele» a la flor significa que…",
      options: [
        "la niega y a la vez la conserva más arriba",
        "la borra por completo, como si nunca hubiera estado",
        "convive con ella hasta que el árbol da su fruto",
        "vuelve a empezar el ciclo desde la semilla",
      ],
      answer: 0,
      explain: "No hay flor y fruto al mismo tiempo: el fruto llega como negación de la flor. Pero la flor no desaparece, es llevada a un nivel superior, más cerca del telos que ya estaba en la semilla. A ese paso Hegel lo llama negación determinada.",
    },
    {
      type: "info",
      title: "Aufheben: elevar, cancelar, preservar",
      body: "El verbo que usa Hegel para este movimiento es **aufheben** (sustantivo: Aufhebung), que nunca se tradujo bien: a veces \"sublevar/sublimar\", a veces \"superar\", a veces \"suprimir\" —todas inadecuadas—. Literalmente es **levantar, llevar hacia arriba, elevar a un nivel superior; negar de un modo que a la vez preserva; abolir sin cancelar del todo; eliminar pero conservar como elemento de una síntesis**.",
    },
    {
      type: "info",
      continues: true,
      title: "Aufheben: elevar, cancelar, preservar",
      body: "La historia se despliega siempre de este modo dialéctico, como la semilla que se hace árbol y florece y da fruto: una progresión hacia adelante, hacia arriba y en espiral, porque siempre hay alguna contradicción, antítesis, antagonismo o tensión que empuja al estadio siguiente.",
    },
    {
      type: "short",
      question: "¿Qué verbo alemán reúne negar, preservar y elevar a la vez?",
      answers: ["aufheben", "Aufhebung"],
      explain: "Ninguna traducción le alcanzó: «superar», «suprimir», «sublimar». Aufheben es levantar y llevar hacia arriba, abolir sin cancelar del todo, eliminar conservando como elemento de una síntesis. Así avanza la historia: hacia adelante, hacia arriba y en espiral.",
    },
    {
      type: "info",
      title: "Una advertencia sobre \"tesis-antítesis-síntesis\"",
      body: "Esa tríada, que todo el mundo asocia a Hegel, **él prácticamente no la usa**. Se popularizó en el siglo XIX a partir de exposiciones simplificadas de sus comentaristas y quedó pegada a su nombre. Conviene desconfiar de ella: sugiere un esquema mecánico de tres casilleros, cuando lo propio de Hegel es que la contradicción **surge desde adentro** de cada posición, no que se le oponga otra desde afuera.",
    },
    {
      type: "quiz",
      question: "La tríada «tesis-antítesis-síntesis», asociada de forma automática a Hegel…",
      options: [
        "viene de sus comentaristas del siglo XIX, casi no la usa él",
        "es la fórmula que Hegel repite en cada capítulo de su obra",
        "fue acuñada por Bajtín para describir el cronotopo hegeliano",
        "reemplaza al concepto de Aufhebung en su sistema maduro",
      ],
      answer: 0,
      explain: "Esa tríada se popularizó en el siglo XIX a partir de exposiciones simplificadas de sus comentaristas y quedó pegada a su nombre, pero él prácticamente no la usa. Conviene desconfiar de ella: sugiere un esquema mecánico, cuando lo propio de Hegel es que la contradicción surge desde adentro de cada posición.",
    },
    {
      type: "info",
      title: "Amo y esclavo: la lucha por el reconocimiento",
      body: "El pasaje más famoso de la Fenomenología es la **dialéctica del amo y el esclavo**, y es donde mejor se ve cómo funciona todo lo anterior. La pregunta de partida es cómo una conciencia llega a ser consciente de sí. La respuesta de Hegel es que no puede sola: necesita ser **reconocida** por otra conciencia. La autoconciencia es constitutivamente social.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo: la lucha por el reconocimiento",
      body: "Pero ese reconocimiento no llega por acuerdo, llega por **lucha**. Dos conciencias se enfrentan y cada una busca que la otra la reconozca sin reconocerla a su vez. Es una lucha a muerte, y se resuelve cuando una de las dos **teme más a la muerte que a la servidumbre**: cede, y se vuelve siervo. La otra, la que estuvo dispuesta a morir, se vuelve amo.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo: la lucha por el reconocimiento",
      body: "El resultado se invierte. El amo consigue lo que quería y descubre que no le sirve: es reconocido por alguien a quien él no reconoce como igual, o sea, por nadie. Además vive del trabajo ajeno y pierde todo contacto con la realidad. Su victoria lo vuelve dependiente de aquel a quien domina.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo: la lucha por el reconocimiento",
      body: "El siervo, en cambio, trabaja. Y al trabajar sobre la materia la transforma, se ve reflejado en lo que produce, se **forma** a sí mismo en ese proceso. La conciencia que avanza en la historia es la del siervo, no la del amo: para Hegel la libertad se conquista trabajando, no venciendo.",
    },
    {
      type: "info",
      continues: true,
      title: "Amo y esclavo: la lucha por el reconocimiento",
      body: "Estas páginas tuvieron una descendencia enorme. Marx va a leer ahí la relación entre el capital y el trabajo. En los años treinta, en París, **Alexandre Kojève** dicta un seminario sobre la Fenomenología que lee toda la historia humana como esa lucha por el reconocimiento, y por sus clases pasan Sartre, Lacan, Bataille, Merleau-Ponty. Buena parte del pensamiento francés del siglo XX sale de ese pasaje.",
    },
    {
      type: "quiz",
      question: "En la dialéctica del amo y el esclavo, la victoria del amo termina siendo…",
      options: [
        "una dependencia de alguien que no lo reconoce",
        "una libertad plena que ya no necesita del otro",
        "el punto de partida de un reconocimiento mutuo e igualitario",
        "irrelevante, porque la historia avanza por la fuerza bruta",
      ],
      answer: 0,
      explain: "El amo consigue lo que quería y descubre que no le sirve: es reconocido por alguien a quien él no reconoce como igual, o sea, por nadie. Vive del trabajo ajeno y pierde contacto con la realidad. El siervo, en cambio, se forma trabajando la materia: la libertad se conquista trabajando, no venciendo.",
    },
    {
      type: "info",
      title: "La historia del mundo según Hegel",
      body: "La Fenomenología recorre toda la historia universal, que para Hegel —muy elitista, europeo y alemán— es: la **Grecia antigua**; la **Roma antigua** (muy inferior a Grecia, en su lectura); un salto directo hasta la **Revolución Francesa** (porque, según él, nada significativo ocurre en el medio); y luego su desarrollo intelectual más profundo en la **filosofía alemana**. Eso es todo: Grecia, Roma, salto a la Revolución Francesa, y los filósofos alemanes. Esa es la historia entera del mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "La historia del mundo según Hegel",
      body: "En las Lecciones sobre la filosofía de la historia lo formula como una sola tesis: \"la historia universal es el **progreso en la conciencia de la libertad**\". Y le pone una escala descarnada: en los despotismos orientales, uno solo era libre —el déspota—; entre griegos y romanos, algunos eran libres; entre los pueblos germánicos y cristianos, todos lo son. El eurocentrismo no es un descuido en Hegel, sino parte de la estructura del argumento.",
    },
    {
      type: "quiz",
      question: "¿Qué hace Hegel con los siglos que van de Roma a la Revolución Francesa?",
      options: [
        "Los pasa por alto, sin nada significativo",
        "Los estudia como la etapa central del Espíritu",
        "Los considera una caída que hay que revertir",
        "Los reparte entre Grecia y la filosofía alemana",
      ],
      answer: 0,
      explain: "Grecia antigua, Roma (muy inferior en su lectura), salto directo a la Revolución Francesa y después la interpretación más profunda en la filosofía alemana. Esa es la historia entera del mundo: un recorrido tan elitista como europeo y alemán.",
    },
    {
      type: "info",
      title: "La astucia de la razón",
      body: "Queda una pregunta incómoda: si la historia va hacia la libertad, ¿por qué está hecha de guerras, ambición y carnicería? La respuesta de Hegel es la **List der Vernunft**, la **astucia de la razón**. Los grandes individuos históricos —César, Napoleón— persiguen sus pasiones privadas, su gloria, su poder; y sin saberlo ejecutan el designio del Espíritu. La razón universal se sirve de las pasiones particulares como de un instrumento.",
    },
    {
      type: "info",
      continues: true,
      title: "La astucia de la razón",
      body: "De ahí esa frase suya de que **nada grande se ha hecho en el mundo sin pasión**. Y de ahí también la imagen del \"matadero\" de la historia: los pueblos y los individuos son el material que se consume en el camino.",
    },
    {
      type: "info",
      continues: true,
      title: "La astucia de la razón",
      body: "La objeción que se le hará después es evidente: si el sufrimiento tiene sentido dentro del plan, deja de haber algo que reprocharle a la historia.",
    },
    {
      type: "quiz",
      question: "La «astucia de la razón» explica que los grandes individuos históricos…",
      options: [
        "persiguen su gloria y sin saberlo sirven al Espíritu",
        "actúan siempre con un cálculo consciente del bien común",
        "carecen de toda pasión propia y sólo ejecutan órdenes",
        "frenan sin darse cuenta el avance de la historia universal",
      ],
      answer: 0,
      explain: "César, Napoleón: persiguen sus pasiones privadas, su gloria, su poder, y sin saberlo ejecutan el designio del Espíritu. La razón universal se sirve de las pasiones particulares como de un instrumento. De ahí la frase de que nada grande se ha hecho en el mundo sin pasión.",
    },
    {
      type: "info",
      title: "El búho de Minerva",
      body: "Sólo se puede entender el todo **mirando hacia atrás**. De ahí esa célebre línea del prefacio a la Filosofía del derecho: \"el búho de Minerva emprende su vuelo al caer el crepúsculo\" (Minerva es el nombre romano de Atenea, diosa de la sabiduría). Sólo mirando hacia atrás podemos entender de qué se trataba algo; no se puede entender mirando hacia adelante. **El sentido llega sólo en retrospectiva.**",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva",
      body: "En ese mismo prefacio está la frase más discutida de Hegel: \"**lo que es racional es real, y lo que es real es racional**\". Leída de un modo, es conservadora: lo que existe está justificado, incluido el Estado prusiano que le pagaba el sueldo.",
    },
    {
      type: "info",
      continues: true,
      title: "El búho de Minerva",
      body: "Leída de otro, es crítica: \"real\" (wirklich) no es todo lo que meramente existe, sino lo que realiza su concepto; lo que no lo realiza está condenado a caer. De esa ambigüedad van a salir las dos escuelas de sus herederos.",
    },
    {
      type: "quiz",
      question: "La frase «lo que es racional es real» admite una lectura crítica porque…",
      options: [
        "«real» es sólo lo que realiza su propio concepto",
        "«racional» significa simplemente lo que decide el Estado",
        "Hegel la escribió para atacar abiertamente al Estado prusiano",
        "sólo se aplica a lo ocurrido durante la Revolución Francesa",
      ],
      answer: 0,
      explain: "Leída de un modo, la frase es conservadora: lo que existe está justificado, incluido el Estado prusiano. Leída de otro, es crítica: «real» (wirklich) no es todo lo que meramente existe, sino lo que realiza su concepto; lo que no lo realiza está condenado a caer. De esa ambigüedad salen las dos escuelas de sus herederos.",
    },
    {
      type: "info",
      title: "Contra Kant: la moral no está en la intención",
      body: "Ahí está la polémica de Hegel con la moral kantiana. Para Kant, actuar éticamente es usar el libre albedrío para obrar según el deber moral; una vez que actuás no controlás todas las consecuencias, pero eso no es tu culpa: lo que importa es el motivo. Hegel dice que esa es una noción **completamente inadecuada** de la moralidad, porque las acciones, no ocasionalmente sino la mayoría de las veces, tienen consecuencias que exceden con mucho su intención.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra Kant: la moral no está en la intención",
      body: "Su objeción de fondo es que la moral kantiana es **vacía** y **abstracta**. El imperativo categórico te dice que no te contradigas, pero no te dice qué hacer: es una forma sin contenido. Y te imagina como un individuo aislado deliberando en el vacío, cuando en realidad nunca decidís desde cero, sino desde adentro de una familia, una profesión, un pueblo, una lengua.",
    },
    {
      type: "info",
      continues: true,
      title: "Contra Kant: la moral no está en la intención",
      body: "Hegel marca esa diferencia con dos palabras que en alemán se distinguen y en castellano cuesta separar. **Moralität**, moralidad, es la de Kant: la conciencia individual frente al deber. **Sittlichkeit**, que se suele traducir como **eticidad**, es la vida ética ya encarnada en instituciones y costumbres compartidas. Para Hegel lo segundo es superior a lo primero, y no al revés.",
    },
    {
      type: "quiz",
      question: "Para Hegel, la Sittlichkeit es superior a la Moralität porque…",
      options: [
        "es la vida ética ya encarnada en instituciones compartidas",
        "prescinde por completo de cualquier institución o costumbre",
        "exige un cálculo racional más estricto que el de Kant",
        "sólo se aplica a los gobernantes y no a los ciudadanos",
      ],
      answer: 0,
      explain: "Moralität es la de Kant: la conciencia individual frente al deber. Sittlichkeit, que se suele traducir como eticidad, es la vida ética ya encarnada en instituciones y costumbres compartidas. Para Hegel nadie decide desde cero: siempre se decide desde adentro de una familia, una profesión, un pueblo.",
    },
    {
      type: "classify",
      question: "¿Cada tesis sobre la moral es de Kant o de Hegel?",
      groups: ["Kant", "Hegel"],
      items: [
        { text: "Lo que hace buena a una acción es el motivo", group: 0 },
        { text: "No sos culpable de lo que no podías controlar", group: 0 },
        { text: "Actuar bien es obrar según el deber moral", group: 0 },
        { text: "Las acciones casi siempre desbordan su intención", group: 1 },
        { text: "El sentido de un acto aparece recién mirando atrás", group: 1 },
        { text: "El búho de Minerva vuela al caer el crepúsculo", group: 1 },
      ],
      explain: "Para Kant, obrar éticamente es usar el libre albedrío según el deber, y lo que se escapa de las manos no es culpa propia. Hegel considera esa noción completamente inadecuada: si las consecuencias exceden la intención la mayoría de las veces, el sentido sólo llega en retrospectiva.",
    },
    {
      type: "info",
      title: "La libertad en las instituciones",
      body: "En la Filosofía del derecho (1821) eso se vuelve un programa político. La libertad no es la ausencia de trabas —hacer lo que se me antoje—, porque un individuo que sólo sigue sus impulsos es el menos libre de todos: está a merced de cualquier cosa que se le cruce. La libertad verdadera es **querer racionalmente lo que las instituciones de un pueblo libre hacen posible**.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad en las instituciones",
      body: "Por eso su Estado tiene tres momentos que se van englobando. La **familia**, donde el vínculo es el afecto y todavía no hay individuos plenos. La **sociedad civil** (bürgerliche Gesellschaft), el terreno del mercado, el trabajo y el interés privado, donde cada uno persigue lo suyo y todos dependen de todos sin saberlo. Y el **Estado**, que no es la suma de los intereses privados sino el momento en que lo universal se vuelve consciente de sí.",
    },
    {
      type: "info",
      continues: true,
      title: "La libertad en las instituciones",
      body: "Hegel ya ve la falla del segundo momento: la sociedad civil genera riqueza y, en el mismo movimiento, genera una masa de gente empobrecida que él llama la **plebe** (Pöbel), y admite que no encuentra dentro de su sistema el modo de resolverlo. Marx va a partir de ese punto.",
    },
    {
      type: "match",
      question: "Uní cada momento del Estado hegeliano con lo que lo define",
      pairs: [
        { left: "Familia", right: "El vínculo es el afecto; todavía no hay individuos plenos" },
        { left: "Sociedad civil", right: "El mercado, el trabajo y el interés privado de cada uno" },
        { left: "Estado", right: "Lo universal que se vuelve consciente de sí mismo" },
      ],
      explain: "Los tres momentos se van englobando: la familia, la sociedad civil (bürgerliche Gesellschaft) y el Estado, que no es la suma de los intereses privados. Hegel ya ve la falla del segundo momento: genera riqueza y, en el mismo movimiento, una masa empobrecida que llama la plebe (Pöbel), sin encontrar la manera de resolverlo. Marx va a partir de ese punto.",
    },
    {
      type: "info",
      title: "Libertad como reconocimiento de la necesidad",
      body: "Las implicaciones para la libertad humana: **todo sucede como debe suceder**. El Espíritu tiene su propio impulso objetivo; **la libertad es el reconocimiento de la necesidad**. Y lo único inmoral, para Hegel, es **oponerse** a ese gran proceso mundial del movimiento del Espíritu en el tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "Libertad como reconocimiento de la necesidad",
      body: "Para Hegel, la alienación es no comprender tu propia existencia individual en el contexto del Geist, del todo. La alienación entre sujeto y objeto se supera mediante la progresión dialéctica: al final se llega a ese punto-telos, esa meta al final de la historia donde todas las contradicciones quedan sintetizadas dialécticamente hasta desaparecer.",
    },
    {
      type: "info",
      continues: true,
      title: "Libertad como reconocimiento de la necesidad",
      body: "Nunca vimos que esto ocurra en la vida real, pero es el **momento místico** al que apunta: un punto en el que sujeto y objeto, libertad y necesidad, interior y exterior, contingencia y necesidad, razón y pasión, pensamiento y ser, todo se sintetiza. Hegel intenta llevarte a un punto donde no hay distinción entre el ser y el deber ser, entre hecho y valor.",
    },
    {
      type: "quiz",
      question: "«La libertad es el reconocimiento de la necesidad» implica que…",
      options: [
        "ser libre es entender por qué todo pasa como pasa",
        "la libertad consiste en elegir entre opciones reales",
        "sólo es libre quien logra torcer el curso del mundo",
        "la necesidad histórica vuelve imposible la moral",
      ],
      answer: 0,
      explain: "El Espíritu tiene su propio impulso objetivo y todo sucede como debe suceder. Por eso lo único inmoral es oponerse a ese proceso, y la alienación es no entender la propia existencia individual dentro del todo.",
    },
    {
      type: "match",
      question: "Uní cada concepto con lo que nombra",
      pairs: [
        { left: "Geist", right: "El poder del todo: «el yo que es un nosotros»" },
        { left: "Dialéctica", right: "El choque de contradicciones que empuja la historia" },
        { left: "Aufhebung", right: "Negar conservando, elevando a un nivel superior" },
        { left: "Telos", right: "El fin que ya estaba en el comienzo, como la manzana en la semilla" },
        { left: "Búho de Minerva", right: "El sentido de algo sólo se entiende en retrospectiva" },
      ],
      explain: "Las piezas encajan entre sí: el Geist se despliega por dialéctica, cada estadio se supera por Aufhebung camino a su telos, y el conjunto sólo se deja ver desde el final.",
    },
    {
      type: "info",
      title: "La herencia: hegelianos de derecha y de izquierda",
      body: "Hegel muere en 1831 y sus discípulos se parten casi de inmediato en dos, según cuál de las dos lecturas de \"lo racional es real\" adopten. Los **hegelianos de derecha** leen que el proceso ya culminó: el Estado prusiano y el cristianismo son la realización del Espíritu, y no queda mucho por hacer salvo comprenderlo.",
    },
    {
      type: "info",
      continues: true,
      title: "La herencia: hegelianos de derecha y de izquierda",
      body: "Los **hegelianos de izquierda**, o jóvenes hegelianos, leen lo contrario: si el criterio es la racionalidad, entonces todo lo existente está bajo sospecha, y el método dialéctico es un arma crítica.",
    },
    {
      type: "info",
      continues: true,
      title: "La herencia: hegelianos de derecha y de izquierda",
      body: "**David Strauss** aplica el método a los evangelios en su Vida de Jesús (1835) y los lee como mito. **Ludwig Feuerbach**, en La esencia del cristianismo (1841), da el paso decisivo: Dios no creó al hombre, el hombre proyectó en Dios sus propios atributos; la teología es antropología encubierta.",
    },
    {
      type: "info",
      continues: true,
      title: "La herencia: hegelianos de derecha y de izquierda",
      body: "De ese grupo sale **Marx**, que hacia 1843-1844 escribe su crítica de la filosofía del derecho de Hegel y formula la operación decisiva: conservar la dialéctica y cambiarle el sujeto. Donde Hegel puso el Espíritu, Marx va a poner las relaciones materiales de producción. La historia sigue siendo dialéctica, direccional y necesaria; sólo que ya no la mueve una idea.",
    },
    {
      type: "match",
      question: "Uní cada nombre con lo que aporta a la herencia de Hegel",
      pairs: [
        { left: "Hegelianos de derecha", right: "El proceso ya culminó: el Estado prusiano lo realiza" },
        { left: "Hegelianos de izquierda", right: "Todo lo existente queda bajo sospecha crítica" },
        { left: "Strauss", right: "Lee los evangelios como mito en su Vida de Jesús" },
        { left: "Feuerbach", right: "Dios es una proyección de los atributos humanos" },
        { left: "Marx", right: "Cambia el Espíritu por las relaciones materiales de producción" },
      ],
      explain: "Hegel muere en 1831 y sus discípulos se parten según cuál lectura de «lo racional es real» adopten. Strauss y Feuerbach abren el camino crítico, y de ese grupo sale Marx: conserva la dialéctica —direccional y necesaria— pero le cambia el sujeto, del Espíritu a las relaciones materiales de producción.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada pieza del tramo final de la clase",
      pairs: [
        { left: "Amo y esclavo", right: "La lucha por el reconocimiento; el siervo se forma trabajando" },
        { left: "Astucia de la razón", right: "Las pasiones privadas cumplen, sin saberlo, el plan del Espíritu" },
        { left: "Sittlichkeit", right: "La vida ética encarnada en instituciones, superior a la Moralität" },
        { left: "Hegelianos de izquierda", right: "Tratan lo existente con sospecha; de ahí sale Marx" },
        { left: "Filosofía del derecho", right: "Familia, sociedad civil y Estado: los tres momentos de la libertad" },
      ],
      explain: "Cinco piezas del tramo final: el amo y el esclavo muestran que la libertad se conquista trabajando, la astucia de la razón explica el motor pasional de la historia, la Sittlichkeit corrige a Kant desde las instituciones, y de la lectura crítica de los hegelianos de izquierda sale Marx.",
    },
    {
      type: "info",
      title: "Conclusiones: la seducción del todo",
      body: "La seducción de Hegel es la **seducción del todo**. El lema, en cierto sentido, de la Fenomenología es das Wahre ist das Ganze: \"**lo verdadero es el todo**\". Sólo se puede comprender todo junto; todo está interrelacionado, todo es mutuamente dependiente. En cierto modo el determinismo importa menos que la **totalidad**: hay que mirar el universo como totalidad, y la totalidad sólo puede verse desde el final, por lo que el sentido llega sólo en retrospectiva.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: la seducción del todo",
      body: "El poeta polaco Czesław Miłosz llamará a esto la \"**mordida hegeliana**\": lo peculiarmente seductor de esta idea de totalidad. Hannah Arendt dirá que la filosofía de Hegel fue el último intento de reunir de verdad sujeto y objeto, ser y pensamiento, aunque nadie podía estar seguro de si era una **morada** para la realidad o una **prisión** para la realidad.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: la seducción del todo",
      body: "Esa alternativa entre morada y prisión organiza las reacciones posteriores. Del lado de la morada se ubican Marx y quienes necesitan una historia con dirección para fundar la acción política. Del lado de la prisión, Kierkegaard, que le reprocha haber construido un sistema imponente en el que nadie podría vivir, y Nietzsche, que pondrá en duda que la historia tenga sentido alguno.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: la seducción del todo",
      body: "Isaiah Berlin describió el sistema entero con una imagen: Es como un bosque muy oscuro, y quienes entran en él rara vez vuelven para contarnos lo que han visto.",
    },
  ],
};
