export default {
  num: 19,
  transcript: 20,
  title: "La violencia y lo sagrado: René Girard",
  source: "https://www.youtube.com/watch?v=PTz65ixvjjc",
  feed: [
    {
      type: "info",
      title: "Coordenadas",
      body: "**René Girard** (1923-2015) nace en Avignon. Se forma primero como archivista y paleógrafo en la École des Chartes de París, y sólo después, ya doctorado en historia en Estados Unidos, se reconvierte a la crítica literaria. Enseña en varias universidades norteamericanas y pasa las últimas décadas de su carrera en Stanford. En 2005 es elegido miembro de la Academia Francesa.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Su obra se organiza en torno a un núcleo de libros. Mentira romántica y verdad novelesca (1961) formula el deseo mimético a partir de la novela europea —Cervantes, Stendhal, Flaubert, Dostoievski, Proust—.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "La violencia y lo sagrado (1972) extiende esa intuición a la antropología de la religión y el sacrificio. Cosas ocultas desde la fundación del mundo (1978) y El chivo expiatorio (1982) completan el sistema con su lectura de los textos bíblicos y de la revelación cristiana.",
    },
    {
      type: "info",
      continues: true,
      title: "Coordenadas",
      body: "Girard construye, como Hegel o Marx antes que él, un **sistema**: una teoría única —la llamada teoría mimética— que aspira a dar cuenta a la vez de la literatura, la antropología, la religión y la historia de la violencia colectiva. Es contemporáneo de Foucault y de Derrida, pero su ambición corre en sentido inverso a la de ellos: donde el posestructuralismo desarma sistemas, Girard construye uno.",
    },
    {
      type: "quiz",
      question: "¿Qué distingue el proyecto de Girard del de Foucault y Derrida, sus contemporáneos?",
      options: [
        "Construye un sistema total, igual que Hegel o Marx",
        "Desarma los sistemas, igual que Foucault y Derrida",
        "Se limita a la crítica literaria, sin ir más allá",
        "Comparte con ellos el rechazo pleno del sujeto",
      ],
      answer: 0,
      explain: "Como Hegel o Marx, Girard construye una teoría única —la teoría mimética— que aspira a explicar literatura, antropología, religión e historia. Foucault y Derrida, en cambio, desarman sistemas en vez de construirlos.",
    },
    {
      type: "info",
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Girard piensa en diálogo directo con **Claude Lévi-Strauss** y el estructuralismo antropológico. La tesis estructuralista central sostiene que el significado no es intrínseco ni inmanente, sino puramente **relacional** —las palabras significan porque no son otras palabras—, y que esa relación es sin embargo **estable**, porque descansa en la interdependencia sincrónica de un sistema cerrado. Para Lévi-Strauss la cultura entera se entiende por analogía con el lenguaje: es un sistema de signos.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Ese estructuralismo trae de vuelta, en otra clave, la ambición hegeliana de **totalidad** —comprender todo junto, dentro de un sistema donde nada queda afuera—, pero sin **Geist** y sin telos: una totalidad sincrónica, no un despliegue en el tiempo. El sujeto individual queda radicalmente descentrado: no es fuente ni fin del significado, que se produce en la estructura misma, con independencia de cualquier conciencia particular.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Lévi-Strauss aplica ese marco al mito: los mitos del mundo entero comparten una gramática universal, son variaciones de un número limitado de temas, y se organizan en unidades mínimas —los **mitemas**— combinadas según reglas inherentes a la mente humana.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Son dispositivos para clasificar la realidad y resoluciones imaginarias de conflictos sociales reales. Terry Eagleton resume el resultado: la mente que piensa los mitos no es la de ningún sujeto individual, sino que los mitos se piensan a sí mismos a través de la gente, y no al revés.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Un hallazgo de Lévi-Strauss resulta decisivo para Girard: los mitos tienden a empezar con una **crisis de diferenciación**. No es crisis cuando hay demasiada diferencia, sino demasiado poca: cuando se borran las fronteras entre sagrado y profano, entre aristocracia y campesinado, entre dioses y mortales. La diferencia es el esqueleto que sostiene el orden cultural; cuando esos límites se difuminan, surge la ansiedad.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Girard acepta la premisa estructuralista —la cultura funciona por dinámicas estructurales, no por la agencia de un sujeto— pero rompe con Lévi-Strauss en un punto capital: sostiene que hay una **realidad anterior a la estructura**, un nivel que el análisis de los signos no alcanza a tocar, análogo a la cosa en sí kantiana.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Para Girard, Lévi-Strauss se queda en el fenómeno, en la forma de los mitos, y nunca llega a la sustancia que los produce: ese déficit es el punto exacto en el que arranca su propio proyecto.",
    },
    {
      type: "info",
      continues: true,
      title: "El problema que hereda: la respuesta al estructuralismo",
      body: "Esa voluntad de trascender la forma y volver a lo real distingue a Girard de sus contemporáneos posestructuralistas. Escribe en la misma época que Foucault y Derrida, pero desconfía de la premisa que ambos van a radicalizar: que quizá no haya sujeto, ni sustancia, ni verdad estable detrás del juego de los signos.",
    },
    {
      type: "quiz",
      question: "¿En qué rompe Girard con Lévi-Strauss, aunque comparta su punto de partida estructural?",
      options: [
        "Sostiene que hay una realidad anterior a la estructura misma",
        "Niega que el significado sea relacional dentro del sistema",
        "Rechaza por completo la existencia de crisis de diferenciación",
        "Sostiene que los mitos no tienen ninguna gramática común",
      ],
      answer: 0,
      explain: "Girard acepta que la cultura funciona por dinámicas estructurales, pero sostiene que hay un nivel anterior a la estructura, análogo a la cosa en sí kantiana, que el análisis de los signos no alcanza a tocar: la víctima real.",
    },
    {
      type: "info",
      title: "El deseo mimético",
      body: "El título de su primer libro nombra ya la tesis. La \"mentira romántica\" es la ilusión de que el deseo nace espontáneamente en el individuo, de manera autónoma y original; la \"verdad novelesca\" es lo que revelan las grandes novelas cuando se las lee con atención: que ese deseo está siempre mediado por otro. Los grandes novelistas son, para Girard, quienes desenmascaran esa mentira sin necesariamente nombrarla.",
    },
    {
      type: "info",
      continues: true,
      title: "El deseo mimético",
      body: "La intuición fundante es que **el deseo es mimético**: no se desea algo porque el deseo brote espontáneamente del sujeto, sino porque se **imita el deseo de otro**. El deseo tiene siempre una estructura triangular, nunca una línea recta entre un sujeto y un objeto.",
    },
    {
      type: "info",
      continues: true,
      title: "El deseo mimético",
      body: "El triángulo tiene tres puntas: un **sujeto** que desea, un **objeto** deseado, y un **modelo** o **mediador**, otro sujeto cuyo deseo se imita. El impulso no nace en el objeto, relativamente indiferente para Girard, sino en la relación entre el sujeto y el mediador: éste mira al mediador como representante de una plenitud de ser que a él le falta, e imita e internaliza sus deseos.",
    },
    {
      type: "info",
      continues: true,
      title: "El deseo mimético",
      body: "El objeto se vuelve deseable, entonces, no por sus cualidades propias sino porque **otro lo desea**: dos niños en una habitación con juguetes disponibles de sobra van a querer el mismo, precisamente el que en ese momento está en la mano del otro. El deseo, para Girard, se determina siempre desde afuera, nunca desde el interior autónomo de un sujeto que elige libremente su objeto.",
    },
    {
      type: "info",
      continues: true,
      title: "El deseo mimético",
      body: "Esta estructura triangular genera **competencia**, sobre todo cuando el objeto es escaso o no puede repartirse sin conflicto. El deseo mimético escala primero a **rivalidad mimética** y, sin nada que la frene, a **violencia mimética**: tres momentos que se funden entre sí, gobernados todos por la misma dinámica de imitación recíproca entre rivales.",
    },
    {
      type: "quiz",
      question: "En el triángulo del deseo mimético, ¿de dónde nace el impulso hacia el objeto?",
      options: [
        "De la relación entre el sujeto y el mediador que imita",
        "De las cualidades intrínsecas y objetivas del objeto mismo",
        "De una elección racional y autónoma del propio sujeto",
        "De una necesidad biológica ajena a cualquier otro sujeto",
      ],
      answer: 0,
      explain: "El objeto es relativamente indiferente para Girard: el impulso nace en la relación con el mediador, que representa una plenitud de ser que al sujeto le falta. Se desea lo que el otro desea, no el objeto por sí mismo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Girard a la tesis de que no deseamos algo espontáneamente, sino que imitamos el deseo de otro?",
      answers: ["deseo mimético"],
      explain: "El deseo mimético: la estructura triangular con un sujeto, un objeto y un modelo o mediador. El deseo siempre está mediado por otro, nunca es una línea recta entre el sujeto y lo que desea.",
    },
    {
      type: "info",
      title: "El escándalo: el mediador como obstáculo",
      body: "La rivalidad escala hacia lo que Girard llama el **escándalo**: el mediador se vuelve simultáneamente modelo y obstáculo. Se lo admira e imita, y a la vez se lo odia porque se interpone en el camino hacia el objeto. Es una relación ambivalente, casi sadomasoquista, análoga en su estructura a la dialéctica hegeliana del amo y el esclavo.",
    },
    {
      type: "info",
      continues: true,
      title: "El escándalo: el mediador como obstáculo",
      body: "Lo que agrava o frena esta dinámica es la distancia social entre sujeto y mediador. En la **mediación externa** esa distancia es grande —un noble y un siervo enamorados de la misma persona no compiten en rigor: la distancia social actúa como freno—. En la **mediación interna**, en cambio, la distancia se colapsa lo suficiente como para que la rivalidad escale sin inhibición alguna.",
    },
    {
      type: "info",
      continues: true,
      title: "El escándalo: el mediador como obstáculo",
      body: "Don Quijote ejemplifica la mediación externa en su forma más pura: imita a Amadís de Gaula, modelo de caballero situado en un pasado literario inalcanzable, sin posibilidad de rivalidad directa con él. Julien Sorel, en Rojo y negro de Stendhal, o Emma Bovary imitan en cambio modelos próximos y contemporáneos —Napoleón, las heroínas de sus lecturas—, y esa cercanía vuelve el deseo competitivo y propenso al escándalo.",
    },
    {
      type: "classify",
      question: "¿Cada caso corresponde a mediación externa o interna?",
      groups: ["Mediación externa", "Mediación interna"],
      items: [
        { text: "Don Quijote imitando a Amadís de Gaula", group: 0 },
        { text: "Julien Sorel imitando a Napoleón", group: 1 },
        { text: "Un noble y un siervo enamorados de la misma persona", group: 0 },
        { text: "Emma Bovary imitando a las heroínas de sus novelas", group: 1 },
        { text: "Un modelo situado en un pasado literario inalcanzable", group: 0 },
        { text: "Rivalidad que escala sin ninguna inhibición social", group: 1 },
      ],
      explain: "En la mediación externa la gran distancia social frena la rivalidad, como con Amadís o entre un noble y un siervo. En la mediación interna el modelo está cerca —contemporáneo, alcanzable— y la rivalidad se desinhibe sin freno.",
    },
    {
      type: "info",
      continues: true,
      title: "El escándalo: el mediador como obstáculo",
      body: "La disolución histórica de la nobleza y de las jerarquías tradicionales, junto con la movilidad social moderna, multiplicó las condiciones de mediación interna: cuando caen los límites y todos compiten formalmente por lo mismo, la rivalidad se desinhibe. Y como es un mecanismo de imitación recíproca, cada rival se vuelve a la vez sujeto y modelo del otro, lo cual borra todavía más las diferencias entre ambos.",
    },
    {
      type: "info",
      continues: true,
      title: "El escándalo: el mediador como obstáculo",
      body: "Ese colapso de las diferencias entre rivales alimenta, en un círculo, la misma crisis de diferenciación que Lévi-Strauss describía para el mito. El objeto original se vuelve irrelevante: toda la energía pasa a la rivalidad misma.",
    },
    {
      type: "info",
      continues: true,
      title: "El escándalo: el mediador como obstáculo",
      body: "El deseo de poseer lo que el otro tiene se convierte, en el límite, en el deseo de **ser** el otro. Es la antesala de lo que Girard llama la **crisis sacrificial**: una crisis de las distinciones que sostienen el orden cultural entero.",
    },
    {
      type: "info",
      title: "El mecanismo del chivo expiatorio",
      body: "La crisis mimética generalizada —donde todos compiten violentamente con todos y las diferencias se han borrado— sólo encuentra salida, según Girard, mediante el **mecanismo del chivo expiatorio**: la comunidad entera desvía su violencia recíproca hacia una **víctima sustituta**, elegida de manera más o menos arbitraria. El sacrificio de esa víctima **unifica** a todos en su contra y restaura, de un solo golpe, el orden roto.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanismo del chivo expiatorio",
      body: "La hipótesis puede sonar excesiva como esquema abstracto, pero Girard la sostiene con casos históricos concretos: la caza de brujas y la persecución de herejes en la temprana modernidad europea, los linchamientos raciales en el sur de Estados Unidos.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanismo del chivo expiatorio",
      body: "También los juicios-espectáculo del estalinismo, donde la multitud pide la muerte de \"traidores\" y \"fascistas\". En todos los casos, la ira social se proyecta sobre una víctima que concentra, sin merecerlo especialmente, la responsabilidad del desorden colectivo.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanismo del chivo expiatorio",
      body: "La solidaridad de un grupo, sostiene Girard, requiere casi siempre un enemigo: la violencia interna se proyecta hacia afuera, sobre un sustituto simbólico. El impulso no es sólo destructivo, es también purificador: la sociedad busca **limpiarse** de aquello que percibe como fuente de su propio desorden, de ahí la lógica de las \"purgas\" en su doble sentido, literal y político.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanismo del chivo expiatorio",
      body: "La turba que ejecuta el sacrificio no se percibe a sí misma como agente de nada: se experimenta como pasiva, reactiva, arrastrada por una víctima a la que atribuye toda la iniciativa del conflicto. Sólo hay lugar, en esa lógica, para una causa única y exclusiva: el chivo expiatorio.",
    },
    {
      type: "quiz",
      question: "¿Qué función cumple, para Girard, el sacrificio de la víctima sustituta?",
      options: [
        "Unifica a la comunidad en su contra y restaura el orden roto",
        "Castiga de manera justa al verdadero culpable del conflicto",
        "Sólo aumenta el caos, sin ningún efecto sobre la comunidad",
        "Se limita a repartir el conflicto entre todos por igual",
      ],
      answer: 0,
      explain: "La violencia recíproca de todos contra todos se desvía hacia una víctima elegida más o menos arbitrariamente. Su sacrificio unifica a la comunidad en su contra y restaura, de un solo golpe, el orden que la crisis mimética había roto.",
    },
    {
      type: "info",
      continues: true,
      title: "El mecanismo del chivo expiatorio",
      body: "Ese acto fundacional trae, de manera inmediata, calma, reconciliación y una sensación de unanimidad: la comunidad se experimenta a sí misma como vaciada de su propio veneno. Girard llama a ese momento la fundación misma de la civilización, atribuida retrospectivamente a fuerzas que exceden el control humano.",
    },
    {
      type: "info",
      title: "La doble transferencia",
      body: "El mecanismo descansa en una mala atribución. La turba **transfiere su propia violencia** hacia la víctima y la proyecta como si fuera propiedad de ésta: a diferencia de Freud, para quien la violencia se reprime en el inconsciente, en Girard la violencia se **traslada** a un sustituto externo.",
    },
    {
      type: "info",
      continues: true,
      title: "La doble transferencia",
      body: "La víctima queda identificada como causa del desorden, atribución que se confirma retrospectivamente por una lógica circular: si su muerte trajo la paz, su existencia previa debió causar el caos.",
    },
    {
      type: "info",
      continues: true,
      title: "La doble transferencia",
      body: "Es lo que Girard llama la **doble transferencia**: a la misma víctima se le atribuye ser causa del desorden anterior y causa del orden posterior. Aunque su elección fue arbitraria, esa doble atribución le confiere una potencia mística que la convierte en algo **sagrado**, con mayúscula: un rol divino.",
    },
    {
      type: "info",
      continues: true,
      title: "La doble transferencia",
      body: "El teólogo Robert Hamerton-Kelly la describió como el malentendido primordial por el que la turba identifica mal las causas de su propio desorden y de su propia paz recién ganada.",
    },
    {
      type: "info",
      continues: true,
      title: "La doble transferencia",
      body: "Lo Sagrado, en la teoría de Girard, no es otra cosa que la personificación y reificación de la violencia colectiva a través de la figura de la víctima. La violencia sale de la turba, pasa por la víctima, y **vuelve** a la turba transformada en cultura, incluida la religión misma, que Girard lee como la institucionalización de ese mecanismo original.",
    },
    {
      type: "quiz",
      question: "¿Qué es la «doble transferencia» en la teoría de Girard?",
      options: [
        "Atribuirle a la víctima el desorden previo y el orden posterior",
        "Transferir la violencia de la víctima de vuelta hacia la turba",
        "Repartir la culpa del conflicto entre dos víctimas distintas",
        "Trasladar el conflicto de una generación a la siguiente",
      ],
      answer: 0,
      explain: "A la misma víctima, elegida arbitrariamente, se le atribuye ser causa del desorden anterior y causa del orden que trajo su muerte. Esa doble atribución le confiere una potencia mística: se vuelve sagrada.",
    },
    {
      type: "info",
      title: "Prohibición, rito y mito",
      body: "Tres instituciones culturales sostienen, para Girard, el orden fundado en ese primer asesinato colectivo. La **prohibición** actúa en negativo: previene el resurgimiento del conflicto mimético recayendo sobre los objetos que no pueden dividirse en paz, y mantiene fijas las categorías de sagrado y profano, de clase y de género.",
    },
    {
      type: "info",
      continues: true,
      title: "Prohibición, rito y mito",
      body: "El **rito** es la contraparte positiva de la prohibición: reactualiza, de forma controlada y simbólica, el sacrificio original —sacrificios de animales, quemas rituales, desfiles conmemorativos— y renueva así el efecto ordenador de la violencia fundacional sin necesidad de repetirla en su forma letal.",
    },
    {
      type: "info",
      continues: true,
      title: "Prohibición, rito y mito",
      body: "El **mito**, para Girard, es el más importante de los tres porque es también el que mejor revela y mejor oculta el mecanismo. Coincide con Lévi-Strauss en que el mito trae pensamiento diferencial después de una crisis de indiferenciación, pero le reprocha quedarse en el nivel del significante sin llegar a la víctima real que hay debajo.",
    },
    {
      type: "info",
      continues: true,
      title: "Prohibición, rito y mito",
      body: "Su definición es precisa: **el mito es el relato del asesinato del chivo expiatorio, contado desde el punto de vista de los asesinos**, de modo que santifica y justifica la violencia fundadora presentándola como necesaria para expulsar un mal previo.",
    },
    {
      type: "quiz",
      question: "¿Por qué el mito es, para Girard, el más importante de los tres —prohibición, rito, mito—?",
      options: [
        "Porque a la vez revela y oculta mejor que ningún otro el mecanismo",
        "Porque es el único de los tres que previene el conflicto mimético",
        "Porque no guarda ninguna relación con el sacrificio original",
        "Porque, a diferencia de los otros dos, no santifica la violencia",
      ],
      answer: 0,
      explain: "El mito cuenta el asesinato del chivo expiatorio desde el punto de vista de los asesinos, santificando la violencia fundadora. Por eso es, para Girard, el que mejor revela el mecanismo —y también el que mejor lo oculta.",
    },
    {
      type: "info",
      title: "La crisis de diferenciación como clave histórica",
      body: "La crisis de diferenciación permite pensar episodios históricos concretos con una lógica poco intuitiva. El antisemitismo nazi, por ejemplo, se dirige con particular virulencia contra los judíos alemanes de los años treinta, que estaban abrumadoramente asimilados, hablaban alemán como lengua propia y eran en muchos casos indistinguibles de sus vecinos no judíos, a diferencia de las comunidades judías de Europa del Este, más diferenciadas y menos integradas.",
    },
    {
      type: "info",
      continues: true,
      title: "La crisis de diferenciación como clave histórica",
      body: "Leída como crisis de diferenciación, la ansiedad cultural se dispara precisamente cuando la diferencia se **borra**, no cuando persiste con claridad.",
    },
    {
      type: "info",
      continues: true,
      title: "La crisis de diferenciación como clave histórica",
      body: "La misma lógica sirve para pensar la persecución histórica de minorías sexuales o la ansiedad social frente a identidades que desafían categorías binarias establecidas: la hostilidad se intensifica en el momento en que las fronteras que ordenaban la percepción social empiezan a disolverse, no cuando están firmemente establecidas.",
    },
    {
      type: "quiz",
      question: "¿Por qué el antisemitismo nazi se ceba, con particular virulencia, en los judíos alemanes más asimilados?",
      options: [
        "Porque la ansiedad se dispara cuando la diferencia se borra",
        "Porque esos judíos mantenían costumbres más diferenciadas",
        "Porque eran, de hecho, el grupo con menor presencia social",
        "Porque su asimilación no guardaba relación alguna con la crisis",
      ],
      answer: 0,
      explain: "Leída como crisis de diferenciación, la ansiedad se dispara precisamente cuando la diferencia se borra, no cuando persiste con claridad: por eso la violencia recae con más fuerza sobre los más asimilados, no sobre los más distintos.",
    },
    {
      type: "info",
      title: "La salida: leer desde la víctima",
      body: "Girard sostiene que sí es posible deconstruir el mito y llegar a la realidad que oculta: basta con contar la misma historia desde el punto de vista de la víctima en lugar del de la turba. La referencia a lo real está siempre alojada, para él, en la víctima; los mitos revelan la verdad que ocultan si se los lee a contrapelo, invirtiendo el relato que hacen los perseguidores.",
    },
    {
      type: "info",
      continues: true,
      title: "La salida: leer desde la víctima",
      body: "De esta tesis surge su defensa, explícitamente católica, del cristianismo. El relato de la Pasión rompe con la lógica mítica porque cuenta el asesinato —el de Jesús— desde el punto de vista **del asesinado** y no de quienes lo condenaron: el lector se identifica con la víctima, que se revela divina precisamente a través de su ejecución injusta.",
    },
    {
      type: "info",
      continues: true,
      title: "La salida: leer desde la víctima",
      body: "Ese giro reformula la muerte de Dios que atraviesa todo el curso: para Girard lo decisivo no es que Dios esté muerto, sino que los seres humanos **lo hemos matado** y necesitamos reconocerlo. La condición humana es, en su lectura, fundamentalmente irracional y opaca a sí misma; sus motivos verdaderos permanecen ocultos y exigen un trabajo activo de desciframiento.",
    },
    {
      type: "info",
      continues: true,
      title: "La salida: leer desde la víctima",
      body: "Frente al pesimismo freudiano, que no ofrece salida a la represión, Girard sostiene que existe un camino más allá del sacrificio: identificarse con la víctima permite acceder a una verdad que el mito siempre ocultó, y que sólo el relato cristiano —al menos en la lectura que Girard propone— pone plenamente a la vista.",
    },
    {
      type: "quiz",
      question: "¿Por qué el relato de la Pasión rompe, para Girard, con la lógica mítica habitual?",
      options: [
        "Cuenta el asesinato desde el punto de vista del asesinado",
        "Es el único relato antiguo que no incluye ninguna víctima",
        "Convence a la turba de que su violencia estuvo justificada",
        "Evita nombrar tanto a la víctima como a sus perseguidores",
      ],
      answer: 0,
      explain: "El mito santifica la violencia desde el punto de vista de los asesinos. La Pasión, en cambio, cuenta la ejecución de Jesús desde el punto de vista del asesinado: el lector se identifica con la víctima, no con la turba.",
    },
    {
      type: "match",
      question: "Uní cada término de la teoría mimética de Girard con lo que nombra",
      pairs: [
        { left: "Deseo mimético", right: "Se desea lo que otro desea, no el objeto en sí mismo" },
        { left: "Escándalo", right: "El mediador se vuelve a la vez modelo y obstáculo" },
        { left: "Chivo expiatorio", right: "La víctima sustituta cuyo sacrificio restaura el orden" },
        { left: "Doble transferencia", right: "A la víctima se le atribuye el desorden y el orden" },
        { left: "Mito", right: "El asesinato contado desde el punto de vista de los asesinos" },
      ],
      explain: "El deseo mimético escala a rivalidad y a escándalo; sin freno, la crisis colectiva se resuelve con un chivo expiatorio al que la doble transferencia vuelve sagrado; el mito es el relato de ese asesinato contado por quienes lo cometieron.",
    },
    {
      type: "info",
      title: "Herencia: entre la antropología y la crítica cultural",
      body: "La teoría mimética tuvo una recepción dispar. En antropología y estudios religiosos alimentó lecturas del sacrificio y del ritual alejadas de la ortodoxia académica de Lévi-Strauss.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: entre la antropología y la crítica cultural",
      body: "En el terreno de las ideas contemporáneas, la tesis del deseo mediado por el modelo de otro fue explícitamente reivindicada por pensadores formados en la órbita de Stanford —el caso más citado es el del inversor Peter Thiel—, que la aplicaron al análisis del deseo de imitación en mercados y redes sociales.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: entre la antropología y la crítica cultural",
      body: "El término griego **pharmakos**, la figura del chivo expiatorio en la tragedia ática, veneno y remedio a la vez, que Girard recupera para nombrar la ambivalencia de la víctima sagrada, tiene un pariente cercano en el **pharmakon** que trabajará Derrida: ya no aplicado a una víctima sacrificial, sino a la escritura misma. Es un cruce involuntario entre dos proyectos que se declaran, por lo demás, opuestos.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: entre la antropología y la crítica cultural",
      body: "Esa diferencia de temperamento organiza el resto del curso. Mientras Foucault y Derrida diagnostican en toda institución moderna un dispositivo de poder o un juego de significantes sin fondo último, Girard busca debajo de las instituciones una violencia fundadora concreta y localizable en el tiempo.",
    },
    {
      type: "info",
      continues: true,
      title: "Herencia: entre la antropología y la crítica cultural",
      body: "Ambos diagnósticos coinciden, sin embargo, en un punto: las instituciones que se presentan como racionales y benignas —el manicomio, la prisión, el ritual, el mito— esconden, bajo la superficie, una historia de exclusión que el discurso oficial no cuenta.",
    },
  ],
};
