// Clase 13 (transcripción) — El existencialismo francés
// App Clase 12. Feed: 'info', 'quiz', 'classify' (comparar), 'match' (conectar), 'short'.
// Tono: resumen fiel de la clase. Preguntas exigentes, con distractores plausibles.
//
// NUMERACIÓN: num (app) = transcript - 1. El archivo se nombra por transcript.
export default {
  num: 12,
  transcript: 13,
  title: "El existencialismo francés",
  source: "https://www.youtube.com/watch?v=G9Ovu6Lxo28",
  feed: [
    {
      type: "info",
      tag: "Panorama",
      title: "Condenados a elegir",
      body: "El existencialismo francés, sobre todo Jean-Paul Sartre, lleva la fenomenología a sus últimas consecuencias. Toma el Dasein de Heidegger en su versión más subjetivista: en un mundo del que Dios está ausente, no hay naturaleza humana previa; estamos arrojados y abandonados, y debemos crearnos eligiendo. El imperativo moral no es qué elegimos, sino que elijamos, cargando con la responsabilidad.",
    },
    {
      type: "info",
      tag: "Fábula",
      title: "El hipopótamo que debe decidir",
      body: "Sartre empieza —dice la clase— con un cuento infantil. Todos los animales bailan, juegan y corren… pero no el hipopótamo, que mira desde afuera. Hasta que la manada vuelve y lo invita: «¡vení con nosotros!». Y el hipopótamo no sabe: ¿se queda?, ¿va? Lo crucial es que debe decidir por sí mismo. A eso lo llamaremos decisionismo.",
    },
    {
      type: "info",
      tag: "Recap",
      title: "De Husserl a Heidegger a Sartre",
      body: "La fenomenología cruzaba el puente sujeto-objeto con la intencionalidad. Heidegger da el giro radical: no hay puente que cruzar, porque el Dasein está siempre ya en el mundo, sin distancia ni afuera. Heidegger dejó abierta una pregunta: ¿el Dasein radicaliza o disuelve al sujeto? Sartre toma la versión radicalmente subjetivista: el Dasein es aún más sujeto.",
    },
    {
      type: "quiz",
      question: "¿Cómo lee Sartre el Dasein de Heidegger?",
      options: [
        "Como la disolución definitiva y total del sujeto",
        "Como un sujeto aún más radical y subjetivo",
        "Como un simple objeto entre otros objetos",
        "Como un regreso a la cosa en sí kantiana",
      ],
      answer: 1,
      explain: "Heidegger dejaba abierta la pregunta de si el Dasein radicaliza o disuelve al sujeto. Sartre toma la versión radicalmente subjetivista: el Dasein es aún más sujeto, fuente de todo sentido y de toda elección.",
    },
    {
      type: "info",
      tag: "Contexto",
      title: "El centro que no aguanta",
      body: "Los años de entreguerras traen una polarización radical: la izquierda se radicaliza, la derecha se radicaliza y el centro desaparece. Nazismo (1933-45) y estalinismo de fondo en todo el que piensa; en las «tierras de sangre» mueren millones de no combatientes. Ese es el contexto de la obsesión de Sartre con la elección: las apuestas son altísimas y todos están involucrados.",
    },
    {
      type: "info",
      tag: "Biografía",
      title: "Sartre y Simone de Beauvoir",
      body: "Sartre es prolífico en muchos géneros; escribir es para él una vocación y un imperativo moral. Le dan el Nobel y lo rechaza por burgués. En 1929 conoce a Simone de Beauvoir estudiando para la agrégation: por primera vez ella siente que alguien la iguala. Frecuentan el Café de Flore y pactan una relación abierta. Dos de las grandes mentes del siglo pensarán toda su vida en diálogo.",
    },
    {
      type: "info",
      tag: "Compromiso",
      title: "Literatura comprometida",
      body: "Sartre sirve de meteorólogo, cae prisionero —y aprovecha para estudiar Ser y tiempo—, y luego milita en la Resistencia mientras termina El ser y la nada. Tras la guerra funda la revista Les Temps modernes y defiende la littérature engagée, la literatura comprometida: el pensador debe involucrarse en el mundo y tomar posición, no retirarse a la torre de marfil ni a una cabaña en el bosque.",
    },
    {
      type: "quiz",
      question: "¿Qué defiende Sartre con la «literatura comprometida» (engagée)?",
      options: [
        "Que el escritor debe involucrarse en el mundo",
        "Que el arte debe ser puro y ajeno a la política",
        "Que hay que retirarse a escribir en soledad",
        "Que la literatura debe imitar a la ciencia",
      ],
      answer: 0,
      explain: "Contra la torre de marfil y la cabaña en el bosque, Sartre sostiene que los pensadores deben tomar posición e involucrarse en su época. Lo proclama al fundar Les Temps modernes en 1945.",
    },
    {
      type: "info",
      tag: "Muerte de Dios",
      title: "Arrojados y abandonados",
      body: "Sartre toma con mortal seriedad la muerte de Dios y la absurdidad de un mundo sin Él. Sigue a Dostoievski: «si Dios no existe, todo está permitido». Ya no hay un cielo de valores garantizados; somos nosotros quienes los creamos. Heidegger enfatizaba el estar-arrojado (Geworfenheit); Sartre enfatiza el abandono: arrojados al mundo y abandonados por el Dios que no existe.",
    },
    {
      type: "quiz",
      question: "Para Sartre, ¿qué se sigue de tomarse en serio la muerte de Dios?",
      options: [
        "Que hay que restaurar un orden moral religioso",
        "Que somos nosotros los creadores de los valores",
        "Que la moral sigue existiendo intacta sin Dios",
        "Que ya nada de lo que hagamos tiene la menor importancia",
      ],
      answer: 1,
      explain: "«Si Dios no existe, todo está permitido» (Dostoievski). Sin un cielo de valores, somos nosotros quienes los creamos, y quedamos arrojados y abandonados. Sartre reprocha al moralismo laico querer suprimir a Dios «al menor costo posible».",
    },
    {
      type: "info",
      tag: "Existencia",
      title: "La existencia precede a la esencia",
      body: "Dios garantizaba una naturaleza humana, una esencia previa de lo humano. Sartre lo invierte: la existencia precede a la esencia. No hay naturaleza humana a priori; primero somos arrojados al mundo y luego, eligiendo, elaboramos nuestra propia esencia al existir. Somos pura posibilidad hasta que actuamos: «el hombre no es nada más que lo que hace de sí mismo».",
    },
    {
      type: "quiz",
      question: "«La existencia precede a la esencia» quiere decir que…",
      options: [
        "nacemos con una naturaleza humana ya fijada",
        "primero existimos y luego nos creamos",
        "la esencia de las cosas es más real que su existencia",
        "sólo existe aquello que podemos definir con conceptos",
      ],
      answer: 1,
      explain: "Dios garantizaba una esencia humana previa. Sin Él no hay naturaleza a priori: primero somos arrojados al mundo y después, eligiendo, elaboramos nuestra esencia. Somos pura posibilidad hasta que actuamos.",
    },
    {
      type: "info",
      tag: "Nada",
      title: "La nada como libertad radical",
      body: "Arrojados para definirnos, empezamos como pura posibilidad, como nada. Para Heidegger lo esencial de esa nada era el ser-para-la-muerte; Sartre enfatiza la nada como libertad radical, más cerca del nihilismo de la vanguardia: todo es posible y, por ende, sin fundamento. La nada, lo aún no determinado, es el espacio para crear y crearnos. No es deprimente: es liberador.",
    },
    {
      type: "info",
      tag: "En-sí / para-sí",
      title: "Lo hecho y lo posible",
      body: "Somos dos cosas a la vez, con ecos de Bergson. El en-sí (en soi) es lo ya establecido e inerte: lo que ocurrió y quiénes hemos sido, muy cerca de la facticidad; no se puede deshacer. El para-sí (pour soi) es lo fluido: la negación interna, la posibilidad de trascender hacia el futuro. El presente es la frontera entre el pasado inmutable y la nada por delante.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al en-sí o al para-sí?",
      groups: ["En-sí", "Para-sí"],
      items: [
        { text: "Lo ya establecido e inerte que no se deshace", group: 0 },
        { text: "Lo fluido y dinámico, pura posibilidad", group: 1 },
        { text: "Quiénes hemos sido hasta este momento", group: 0 },
        { text: "La posibilidad de trascender hacia el futuro", group: 1 },
        { text: "Está muy cerca de la facticidad de la situación", group: 0 },
        { text: "Es la negación interna, la nihilación de lo dado", group: 1 },
      ],
      explain: "El en-sí es lo hecho, lo inerte, lo que no puede cambiarse; el para-sí es la conciencia como actividad, la posibilidad de ir más allá de quien uno ha sido. Somos libres porque no sólo somos en-sí, sino también para-sí: siempre más que nuestra facticidad.",
    },
    {
      type: "info",
      tag: "Facticidad",
      title: "Libertad dentro de la situación",
      body: "La libertad de Sartre no es absoluta al modo mágico: como en Heidegger, estamos siempre ya en una situación dada. Puedo elegir caminar, correr o saltar, pero no volar. Hay contingencia radical y una libertad casi total; el «casi» es lo que Sartre llama la facticidad de la situación: lo ya dado, lo que no elegí, y que sin embargo no anula mi libertad de elegir.",
    },
    {
      type: "quiz",
      question: "¿Qué nombra la «facticidad de la situación» en Sartre?",
      options: [
        "Los límites dados dentro de los que somos libres",
        "La ausencia total de cualquier límite a la acción",
        "El destino que determina de antemano la vida",
        "Las leyes morales que Dios dejó escritas",
      ],
      answer: 0,
      explain: "Somos libres, pero dentro de una situación dada: puedo caminar, correr o saltar, pero no volar. La facticidad es ese «casi» que recorta la libertad casi total —lo ya dado, lo que no elegí— sin anularla.",
    },
    {
      type: "info",
      tag: "Decisionismo",
      title: "No elegir también es elegir",
      body: "Volvemos al hipopótamo. En cualquier situación debemos elegir, y no elegir también es una elección. Aquí el existencialismo de Sartre se vuelve controvertido: el imperativo moral no es qué elegimos —no hay código que lo diga—, sino que elijamos y asumamos la responsabilidad de esa elección. No hay realidad sino en la acción: somos sólo lo que hacemos.",
    },
    {
      type: "short",
      question: "¿Cómo llamamos a la idea de que, arrojados a una situación, cada uno debe decidir por sí mismo —y no decidir también es decidir?",
      answers: ["decisionismo"],
      explain: "Decisionismo: como el hipopótamo que debe decidir solo si se queda o se va. En toda situación estamos obligados a elegir; lo que importa no es qué elegimos, sino que asumamos la elección.",
    },
    {
      type: "info",
      tag: "Mala fe",
      title: "El autoengaño (mauvaise foi)",
      body: "De ahí la mauvaise foi, la mala fe. No es el sentido coloquial de actuar con motivos ocultos: es autoengaño, una mentira que nos decimos a nosotros mismos. Suele ser refugiarse en una doctrina determinista para evadir la responsabilidad —«no podía hacer otra cosa», «así soy yo»—, tratándose falsamente como un objeto. Es análoga al das Man de Heidegger.",
    },
    {
      type: "quiz",
      question: "En Sartre, ¿en qué consiste la «mala fe» (mauvaise foi)?",
      options: [
        "Actuar con motivos ocultos hacia los demás",
        "Autoengañarse para evadir la responsabilidad",
        "Mentirle deliberadamente a otra persona",
        "Perder la fe religiosa tras la muerte de Dios",
      ],
      answer: 1,
      explain: "No es el sentido coloquial. Es un autoengaño: mentirse a uno mismo, casi siempre refugiándose en un determinismo —«no podía hacer otra cosa», «así soy yo»— para negar la propia libertad y no cargar con la responsabilidad de elegir.",
    },
    {
      type: "short",
      question: "¿Cómo llama Sartre al autoengaño con que negamos nuestra libertad para no cargar con la responsabilidad?",
      answers: ["mala fe", "mauvaise foi"],
      explain: "La mala fe (mauvaise foi): mentirse a uno mismo, tratarse como un objeto determinado —«tenía que ser así»— para escapar de la responsabilidad de elegir. Es análoga al das Man de Heidegger.",
    },
    {
      type: "info",
      tag: "Responsabilidad",
      title: "Libertad absoluta, responsabilidad absoluta",
      body: "Libertad absoluta es responsabilidad absoluta: al elegir, dice Sartre, soy «un legislador para toda la humanidad», y de ahí la angustia. La angustia sartreana difiere de la heideggeriana: menos ligada a la finitud y la muerte, más a la carga insoportable de la responsabilidad. Y hay situaciones sin elecciones inocentes —el joven que debe optar entre su madre enferma y la Resistencia—.",
    },
    {
      type: "classify",
      question: "¿Cada énfasis es más de Heidegger o de Sartre?",
      groups: ["Heidegger", "Sartre"],
      items: [
        { text: "El estar-arrojado (Geworfenheit)", group: 0 },
        { text: "El abandono por un Dios ausente", group: 1 },
        { text: "La angustia nace sobre todo de la finitud", group: 0 },
        { text: "La angustia nace sobre todo de la responsabilidad", group: 1 },
        { text: "La nada es ante todo el ser-para-la-muerte", group: 0 },
        { text: "La nada es ante todo libertad radical", group: 1 },
      ],
      explain: "Comparten el vocabulario —arrojados, la nada, la angustia—, pero con otro acento. Heidegger: estar-arrojado, ser-para-la-muerte, angustia ante la finitud. Sartre: abandono por el Dios ausente, la nada como libertad radical, angustia ante la responsabilidad de elegir.",
    },
    {
      type: "match",
      question: "Uní cada término del existencialismo de Sartre con lo que nombra",
      pairs: [
        { left: "Existencia y esencia", right: "Primero existimos; luego, eligiendo, nos creamos" },
        { left: "En-sí", right: "Lo ya establecido e inerte: la facticidad, lo hecho" },
        { left: "Para-sí", right: "Lo fluido: la posibilidad de trascender hacia el futuro" },
        { left: "Mala fe", right: "Autoengaño para evadir la responsabilidad de elegir" },
        { left: "Decisionismo", right: "En toda situación hay que elegir; importa que elijamos" },
      ],
      explain: "Sin Dios, la existencia precede a la esencia: somos en-sí (lo hecho) y para-sí (la posibilidad de trascenderlo). Condenados a la libertad, debemos decidir (decisionismo) y asumir la responsabilidad; huir de ella tratándonos como cosa determinada es mala fe.",
    },
    {
      type: "info",
      tag: "Cierre",
      title: "La conciencia de una nación",
      body: "Sartre elaboró su decisionismo bajo la ocupación nazi, frente a elecciones imposibles. Durante décadas fue percibido como «la conciencia de su nación» y de Europa. La ironía: usó su libertad radical para abrazar el determinismo marxista y calló ante los crímenes del estalinismo —«la gran ausencia», dice Judt—. Cuando murió, en 1980, un diario tituló: «Francia ha perdido su conciencia».",
    },
  ],
};
