export default {
  num: 1,
  transcript: 2,
  title: "La herencia de la Ilustración",
  source: "https://www.youtube.com/watch?v=VxATfoQJjzk",
  feed: [
    {
      type: "info",
      title: "Introducción",
      body: "El siguiente curso recorre la historia intelectual europea desde los orígenes de la modernidad hasta los debates contemporáneos sobre la posmodernidad y la posverdad. A través de la lectura y discusión de algunos de los pensadores más influyentes de los siglos XIX y XX, exploraremos cómo las grandes transformaciones políticas, sociales y culturales dieron forma a nuevas maneras de comprender al ser humano, la sociedad y la historia.",
    },
    {
      type: "info",
      continues: true,
      title: "Introducción",
      body: "Partiendo de la Ilustración, el Romanticismo y Hegel, seguiremos el hilo que conduce a Nietzsche y a la crisis de los fundamentos tradicionales de la cultura occidental, para luego abordar autores y corrientes como Marx, Lenin, Freud, Kafka, Husserl, Heidegger, Sartre, Beauvoir, Arendt, Adorno, Derrida y Foucault, entre otros.",
    },
    {
      type: "info",
      continues: true,
      title: "Introducción",
      body: "El trasfondo histórico será la profunda ruptura inaugurada por la modernidad europea, generalmente asociada a la Revolución Francesa de 1789, que transformó la relación entre los individuos, la tradición, la religión y el progreso. Analizaremos cómo distintos pensadores intentaron comprender y responder a problemas como la secularización, la alienación, la subjetividad, el sentido de la historia y las crisis políticas del siglo XX.",
    },
    {
      type: "info",
      title: "La Ilustración",
      body: "La Ilustración (en alemán, Aufklärung; en inglés, \"the age of reason\" o \"the age of light\") es una etapa de la historia intelectual europea de fines del siglo XVII y el XVIII, que culmina en la Revolución Francesa. Traerá conceptos nuevos, uno de los cuales es civilización, con una noción muy eurocéntrica: cuando estos filósofos hablan de \"civilización mundial\", no piensan en el mundo, sino en Europa; no en toda Europa, sino en Francia; no en toda Francia, sino en París; no en todo París, sino en cierto café frecuentado por un puñado de intelectuales",
    },
    {
      type: "info",
      continues: true,
      title: "La Ilustración",
      body: "La Ilustración es un término laxo para filosofías que en varios sentidos se contradicen entre sí. Plantea preguntas sobre la relación del hombre consigo mismo, con los demás, con el gobierno y con la naturaleza.",
    },
    {
      type: "info",
      title: "La exaltación de la razón",
      body: "El movimiento clave es la exaltación de la razón. En la Ilustración, Dios es corrido a un costado. Pasa de un papel central a uno menor, y algo tiene que ocupar ese espacio: la razón.",
    },
    {
      type: "info",
      continues: true,
      title: "La exaltación de la razón",
      body: "El espíritu o mood de la Ilustración es el regocijo en la razón, el culto a la razón, la fe en la razón humana.  El movimiento general: como tenemos razón, podemos comprender el mundo —no todo hoy, pero progresivamente cada vez más—, y al comprenderlo podemos moldearlo, mejorarlo, hacerlo funcionar más eficientemente. Esto trae además un cambio en la concepción del tiempo, y un rango distintivo del paso a la modernidad: del tiempo cíclico al tiempo que avanza o progresivo.",
    },
    {
      type: "quiz",
      question: "La idea central de la Ilustración es…",
      options: [
        "que el mundo es un misterio que la razón no alcanza",
        "que la razón puede comprender y mejorar el mundo",
        "que la fe revelada sigue siendo la fuente del saber",
        "que cada época tiene su verdad y no hay progreso",
      ],
      answer: 1,
      explain: "El movimiento clave es la exaltación de la razón: Dios es corrido a un costado y algo tiene que ocupar ese espacio. Como tenemos razón podemos comprender el mundo y, comprendiéndolo, moldearlo y mejorarlo. De ahí también el cambio en la concepción del tiempo: del tiempo cíclico al tiempo que avanza.",
    },
    {
      type: "info",
      title: "Teleología y las ciencias duras",
      body: "El termino teleología proviene de las palabras griegas telos (fin o propósito) y logos (estudio o tratado). Concepto forjado por Aristóteles, esta rama o cateogría de la metafísica busca explicar los eventos o la naturaleza de un objeto no solo por su origen, sino por el objetivo hacia el que se dirigen, en función de su fin, propósito o meta.",
    },
    {
      type: "info",
      continues: true,
      title: "Teleología y las ciencias duras",
      body: "El modelo de toda la filosofía ilustrada son las ciencias duras: entender al ser humano, la vida y la sociedad como los físicos, astrónomos y químicos entienden la naturaleza. De ahí una clara teleología del progreso: cada salto del conocimiento se apoya en lo anterior y siempre se avanza. Isaiah Berlin usa la metáfora del rompecabezas: el mundo es un rompecabezas complejísimo, y aunque aún no colocamos todas las piezas, pero cada pieza nos acerca al todo, y cuantas más colocamos, más fácil resulta colocar las siguientes.",
    },
    {
      type: "quiz",
      question: "Que la Ilustración piense el conocimiento de modo teleológico significa que…",
      options: [
        "cambia de forma impredecible, sin dirección ni acumulación",
        "se explica por su origen y no por aquello a lo que tiende",
        "avanza hacia un fin y cada paso se apoya en el anterior",
        "vuelve siempre sobre los mismos problemas, sin avanzar",
      ],
      answer: 2,
      explain: "Teleología viene de telos (fin o propósito) y logos: explica algo por el objetivo hacia el que se dirige, no sólo por su origen. Aplicada al saber da una teleología del progreso, la que Isaiah Berlin ilustra con el rompecabezas: cada pieza colocada acerca al todo y facilita colocar las siguientes.",
    },
    {
      type: "info",
      title: "El desplazo de Dios por la razón",
      body: "Esta fe en la razón ocupa el lugar dominante que tenía el cristianismo. No matamos a Dios ni al cristianismo, pero ocurre algo que Max Weberllamará Entzauberung, desencanto. Dejamos atrás la sensación de que hay milagros, fuerzas inasibles, criaturas míticas, un más allá, dioses o al menos un Dios, para dar lugar a un mundo explicado por la razón. Hay una sobriedad en ello. Puede vivirse de dos maneras: el ánimo de los ilustrados era regocijarse en el desencanto y en la razón; pero, como veremos con el Romanticismo, mucha gente lo encontrará profundamente decepcionante.",
    },
    {
      type: "info",
      continues: true,
      title: "El desplazo de Dios por la razón",
      body: "Hablaremos de racionalidad, racionalismo y empirismo (la idea de que el conocimiento se gana por la experiencia sensorial y la observación). Isaac Newton fue un precursor importante: las leyes de la física, la gravedad y el movimiento pueden descubrirse por observación y experimentación cuidadosas —recogés datos, observás lo que ocurre concretamente, lo analizás—. Del empirismo saldrá luego el positivismo: entender el mundo conforme a la observación empírica, sin encantamiento, sin fuerzas sobrenaturales, sin nada metafísico.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que nombra",
      pairs: [
        { left: "Racionalismo", right: "La razón como fundamento y medida del conocimiento" },
        { left: "Empirismo", right: "El conocimiento se gana por la experiencia y la observación" },
        { left: "Positivismo", right: "Explicar el mundo sin nada sobrenatural ni metafísico" },
        { left: "Entzauberung", right: "El desencanto: se van los milagros y las fuerzas inasibles" },
      ],
      explain: "Racionalismo y empirismo son las dos vías del saber ilustrado: la razón como fundamento y la experiencia sensorial como fuente. Del empirismo —Newton como precursor— sale después el positivismo. Y el resultado de todo el movimiento es lo que Weber llamará Entzauberung: un mundo explicado por la razón, sin encantamiento.",
    },
    {
      type: "info",
      title: "Descartes: el comienzo de la filosofía moderna",
      body: "En cierto sentido la filosofía moderna empieza con Descartes. Su idea pricipal era partir de una hoja en blanca, no aceptar nada por dado y ver dónde se puede encontrar un fundamento sólido para el conocimiento.",
    },
    {
      type: "info",
      continues: true,
      title: "Descartes: el comienzo de la filosofía moderna",
      body: "La filosofía moderna se ocupa, ante todo, de la epistemología (el estudio del conocimiento): ¿cómo sabemos algo?, ¿cómo sé que el mundo es real, que existe?, ¿cómo sé que esta botella es real y no una proyección de mi conciencia?, ¿cómo paso de lo interior a lo exterior, de la conciencia al ser, de la mente al mundo, de lo inmanente a lo trascendente? Son distintas maneras de preguntar lo mismo: ¿cómo sé realmente qué es real?",
    },
    {
      type: "info",
      title: "Cogito, ergo sum",
      body: "El legado de Descartes es iniciar un experimento mental de duda radical: \"rechazar como absolutamente falso todo aquello en lo que pudiera suponer la menor razón de duda, para ver si no quedaba después algo enteramente indudable\"; \"deshacerme, una vez en la vida, de todas las opiniones que había adoptado y empezar de nuevo desde los cimientos\". ¿Cómo hallar un fundamento sólido?  Si creés en Dios, dirás \"Dios no me engañaría\"; pero ¿y si hay un genio maligno en vez de Dios, intentando engañarte?",
    },
    {
      type: "info",
      continues: true,
      title: "Cogito, ergo sum",
      body: "Descartes concluye: no puedo estar seguro de la veracidad de mis pensamientos (quizá los puso un demonio), pero sí de que estoy teniendo esos pensamientos, luego existo. El famoso cogito, ergo sum (\"pienso, luego existo\"), frase que hay que aprender y que reaparecerá sin cesar. Al final Descartes hace algo de trampa: recupera a Dios y con él el mundo entero, con una prueba de la existencia de Dios que me resulta poco convincente; pero eso lo dejamos.",
    },
    {
      type: "quiz",
      question: "El cogito establece como indudable…",
      options: [
        "que mis pensamientos son verdaderos, porque son míos",
        "que existo, porque estoy teniendo pensamientos",
        "que el mundo exterior es real, porque lo percibo",
        "que Dios existe y por eso no puede engañarme",
      ],
      answer: 1,
      explain: "Aun si un genio maligno le hubiera puesto los pensamientos, Descartes no puede dudar de que los está teniendo: lo indudable no es el contenido del pensamiento, sino que hay alguien pensándolo. Recién después recupera a Dios, y con él el mundo entero, mediante una prueba que la propia clase juzga poco convincente.",
    },
    {
      type: "info",
      title: "Hobbes y el Leviatán",
      body: "Thomas Hobbes fue precursor de la teoría del contrato social, la parte más política de la Ilustración. En su larguísimo Leviatán, su línea más famosa es: \"la vida del hombre es desagradable, brutal y breve\". Para Hobbes, el estado de naturaleza es un estado de guerra: estamos cableados para ser horribles, matándonos y violándonos unos a otros en terror y violencia constantes, hasta que la sociedad viene a controlarlo. Nos mueven la codicia, el interés propio, el ansia de poder y riqueza.",
    },
    {
      type: "info",
      continues: true,
      title: "Hobbes y el Leviatán",
      body: "Para acabar con esa pesadilla, Hobbes plantea que todos deben ceder sus derechos naturales y su libertad a un Leviatán, un gobernante absoluto que da paz y seguridad a cambio de la abdicación de la libertad, en un juego de suma cero: si querés seguridad, cedés libertad.",
    },
    {
      type: "info",
      title: "Locke: el consentimiento de los gobernados",
      body: "John Locke acepta el paso del estado de naturaleza al de cultura, pero para él el estado de naturaleza no era de guerra, sino de libertad individual e igualdad natural. La evolución no es un abandono radical de todo entre ríos de sangre a cambio de la propia vida, sino gradual: la gente trabaja la tierra, adquiere propiedad privada, no quiere que se la roben, decide que hace falta algún gobierno para protegerla. Los derechos de una persona no chocan necesariamente con los de otra, y la gente puede razonar y llegar a acuerdos moderados para convivir.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el consentimiento de los gobernados",
      body: "En sus Dos tratados sobre el gobierno dice que todo individuo posee derechos naturales a la igualdad, la vida, la libertad y la búsqueda de la felicidad; la razón enseña que, siendo todos iguales e independientes, no deben dañarse; y todos, dotados de razón, son competentes para participar en la elección de un gobierno.",
    },
    {
      type: "info",
      continues: true,
      title: "Locke: el consentimiento de los gobernados",
      body: "El legado de Locke: acepta el contrato social; el estado de naturaleza no era guerra ni paraíso, más bien una tabula rasa; para proteger ciertos derechos, la gente forma gobiernos basados solo en el consentimiento de los gobernados, no en el derecho divino de los reyes. Este contrato no es incondicional (como sí lo era para Hobbes): si los gobernantes abusan del poder, el pueblo tiene derecho a reemplazarlos.",
    },
    {
      type: "classify",
      question: "¿Cada tesis es de Hobbes o de Locke?",
      groups: [
        "Hobbes",
        "Locke",
      ],
      items: [
        { text: "El estado de naturaleza es una guerra de todos contra todos", group: 0 },
        { text: "El estado de naturaleza es de libertad e igualdad natural", group: 1 },
        { text: "Hay que ceder la libertad a un soberano absoluto", group: 0 },
        { text: "El gobierno se funda en el consentimiento de los gobernados", group: 1 },
        { text: "El contrato es incondicional: no hay vuelta atrás", group: 0 },
        { text: "Si los gobernantes abusan, el pueblo puede reemplazarlos", group: 1 },
      ],
      explain: "Los dos aceptan el contrato social, pero parten de estados de naturaleza opuestos: guerra y terror constantes en Hobbes, libertad e igualdad en Locke. De ahí que uno pida un Leviatán y una cesión definitiva de la libertad, y el otro un gobierno revocable, fundado en el consentimiento y no en el derecho divino de los reyes.",
    },
    {
      type: "info",
      title: "Los philosophes y el deísmo de Voltaire",
      body: "Estos son precursores del nuevo tipo de filósofo del siglo XVIII, centrado en Francia: los philosophes. Como muestra la filosofía política, es un modelo de filósofo comprometido con el mundo (engagé), que no pone entre paréntesis la vida real por preguntas abstractas de epistemología. Son cosmopolitas, seculares, humanistas, y unen teoría y praxis (palabra griega para acción comprometida, teóricamente inflexionada).",
    },
    {
      type: "info",
      continues: true,
      title: "Los philosophes y el deísmo de Voltaire",
      body: "Coquetean con reorientar a Dios en lo que llaman deísmo, y la figura clave aquí es Voltaire. El deísmo es un espacio intermedio y moderado entre el Dios cristiano y el agnosticismo (el ateísmo aún no está sobre la mesa, es demasiado radical): Dios existe, es maravilloso, creó el mundo, pero luego se hizo a un lado; nos dotó de razón y nos deja actuar; no es el titiritero que mueve todos los hilos.",
    },
    {
      type: "info",
      continues: true,
      title: "Los philosophes y el deísmo de Voltaire",
      body: "Con esto, Voltaire mueve al ser humano al espacio de Dios y argumenta no por la abolición de la religión, sino por una amplia tolerancia, contra la opresión y el absolutismo religiosos. Su lema: \"écrasez l'infâme\", \"aplastad la infamia\" —una versión tiránica del cristianismo, de la religión, de la superstición—. Su Tratado sobre la tolerancia (1763) es deísta, contrario también al ateísmo, pero a favor de una amplísima tolerancia.",
    },
    {
      type: "quiz",
      question: "El deísmo que defiende Voltaire sostiene que…",
      options: [
        "Dios no existe y la religión hay que abolirla",
        "Dios mueve todos los hilos de lo que nos pasa",
        "Dios creó el mundo y luego se hizo a un lado",
        "no hay manera de saber si Dios existe o no",
      ],
      answer: 2,
      explain: "El deísmo es un espacio intermedio y moderado entre el Dios cristiano y el agnosticismo —el ateísmo todavía es demasiado radical—: Dios existe y creó el mundo, pero nos dotó de razón y nos deja actuar; no es el titiritero que mueve los hilos. Voltaire no pide abolir la religión sino una amplísima tolerancia.",
    },
    {
      type: "info",
      title: "Rousseau",
      body: "Rousseau es el primero de muchos personajes profundamente problemáticos que encontraremos. Como dice Charles Taylor: \"decir que Rousseau era difícil de tratar sería el gran eufemismo del siglo XVIII\". De adolescente huérfano y errante, vive de benefactores (se vuelve amante de una benefactora); en París conoce a Diderot y colaboran en la gran Encyclopédie, intento de categorizar, organizar y hacer accesible el conocimiento humano: símbolo y metáfora de toda la actitud ilustrada.",
    },
    {
      type: "info",
      continues: true,
      title: "Rousseau",
      body: "En la teoría del contrato social, es diametralmente opuesto a Hobbes: para él el estado de naturaleza era un estado de virtud; todo era bello y perfecto antes de que la propiedad corrompiera al hombre y lo volviera egoísta, arrogante y competitivo. Es un filósofo de la nostalgia: todo era maravilloso antes de la sociedad, pero no se puede volver. Su contrato social introduce la voluntad general, fuente de autoridad: no es el Leviatán, ni el consentimiento de los gobernados, ni la opinión mayoritaria. Tampoco es la suma de las voluntades particulares —eso es lo que Rousseau llama la voluntad de todos—, sino lo que quiere el cuerpo político como tal, el interés común: una concepción del todo que nadie define con precisión y que motivará el Terror tras la Revolución.",
    },
    {
      type: "quiz",
      question: "En el contrato social de Rousseau, la autoridad se funda en…",
      options: [
        "un soberano absoluto que garantiza la paz y la seguridad",
        "el consentimiento revocable de los gobernados",
        "la voluntad general, el interés del cuerpo político",
        "la suma de las voluntades particulares de cada uno",
      ],
      answer: 2,
      explain: "Rousseau es diametralmente opuesto a Hobbes: el estado de naturaleza era virtud, y la propiedad corrompió al hombre. Y su voluntad general no es la suma de las voluntades particulares —eso es lo que él llama la voluntad de todos—, sino lo que quiere el cuerpo político como tal. Nadie la define con precisión, y después se la invocará para justificar el Terror.",
    },
    {
      type: "info",
      title: "Kant: ¿qué es la Ilustración?",
      body: "Kant dice: la Ilustración es nuestra salida de la inmadurez. Su lema central es sapere aude, \"atrévete a saber\", ten el valor de usar tu propia razón. Es un llamado a la acción, una exaltación de nuestra responsabilidad y capacidad de pensar por nosotros mismos, sin someternos ciegamente a la autoridad.  Kant es un pensador de la filosofía moral y de la epistemología: su epistemología suele asociarse a la Ilustración, y su filosofía moral al Romanticismo.",
    },
    {
      type: "info",
      title: "Epistemología de Kant",
      body: "En epistemología, Kant parte de Descartes y se pregunta qué podemos comprender del mundo: ¿cómo sé que este teléfono está aquí y no es una proyección de mi conciencia?, ¿hay un mundo en sí, o todo es proyección? Es el famoso debate realismo/idealismo, y Kant negocia un compromiso radical: sí hay un mundo real, con existencia independiente de la mente —una Ding an sich, cosa en sí—, pero no tenemos acceso a ella, porque el mundo se procesa a través de nuestra conciencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Epistemología de Kant",
      body: "Y hace su revolución copernicana: así como Copérnico plantea que no es el Sol el que gira en torno a la Tierra, sino la Tierra en torno al Sol, Kant dice que no es nuestra mente la que se conforma al mundo en sí, sino que lo que vemos del mundo debe conformarse a lo que nuestra mente es capaz de procesar.",
    },
    {
      type: "quiz",
      question: "La revolución copernicana de Kant consiste en sostener que…",
      options: [
        "la mente se conforma al mundo tal como es en sí mismo",
        "lo que vemos del mundo se conforma a nuestra mente",
        "no hay mundo real: todo es proyección de la conciencia",
        "el mundo es real y lo conocemos tal como es",
      ],
      answer: 1,
      explain: "Kant negocia un compromiso radical entre realismo e idealismo: sí hay un mundo con existencia independiente de la mente, una Ding an sich, pero no tenemos acceso a ella porque el mundo se procesa a través de nuestra conciencia. Como Copérnico invirtió qué gira alrededor de qué, Kant invierte qué se conforma a qué.",
    },
    {
      type: "info",
      title: "La Revolución Francesa",
      body: "El legado de la Ilustración es el espíritu crítico hacia la autoridad y el derecho a usar la razón. Todo culmina en julio de 1789 con la Revolución Francesa y su lema libertad, igualdad, fraternidad: sus ideas clave son la razón, el progreso, el contrato social,  y un gobierno basado no en el derecho divino de los reyes sino en el consentimiento de los gobernados.",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "La Declaración de los Derechos del Hombre y del Ciudadano (agosto de 1789) encarna esta filosofía política —en efecto, el origen del liberalismo—: \"los hombres nacen y permanecen libres e iguales en derechos; el fin de toda asociación política es la conservación de los derechos naturales e imprescriptibles del hombre: la libertad, la propiedad, la seguridad y la resistencia a la opresión; la ley es la expresión de la voluntad general; nadie puede ser arrestado sino en los casos determinados por la ley; todos inocentes hasta probarse su culpa\".",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "El legado de la Revolución fue transformar a seres humanos que eran súbditos de un monarca (aquí \"súbdito\" en un sentido antitético al de los filósofos: casi propiedad del monarca, sujeta a su voluntad) en ciudadanos —palabra revolucionaria, otro neologismo—: personas comprometidas y responsables, creadoras del gobierno, no peones ni posesiones del monarca. La Revolución fue también la invención de la ideología misma: ideas filosóficas llevadas a la vida real, y la conciencia revolucionaria de reordenar el cosmos (literalmente intentan reiniciar el calendario en el año uno).",
    },
    {
      type: "info",
      continues: true,
      title: "La Revolución Francesa",
      body: "Y surge un problema revolucionario clásico, formulado por Robespierre: ¿cómo pasar del viejo mundo al nuevo cuando los creadores de ese mundo nuevo ya están contaminados, formados por el viejo mundo opresivo? \"Hemos levantado el templo de la libertad con manos aún marchitas por la cruz del despotismo.\" Y desembocará en el Terror (1793-94), que muchos empezarán a atribuir a la idea rousseauniana de la voluntad general. (Para comulgar con el Terror, recomiendo la película Danton, de Andrzej Wajda.)",
    },
    {
      type: "quiz",
      question: "Convertir súbditos en ciudadanos significó que las personas…",
      options: [
        "cambiaron un monarca por otro, sin tocar su condición",
        "recuperaron los derechos que tenían en el estado de naturaleza",
        "quedaron sujetas a la ley divina y no a la del rey",
        "pasaron a crear el gobierno en vez de pertenecer al monarca",
      ],
      answer: 3,
      explain: "El súbdito era casi propiedad del monarca, sujeto a su voluntad; el ciudadano —neologismo revolucionario— es una persona comprometida y responsable, creadora del gobierno y no peón ni posesión. La Revolución fue además la invención de la ideología: ideas filosóficas llevadas a la vida real, hasta reiniciar el calendario en el año uno.",
    },
    {
      type: "info",
      title: "Modernidad, modernización, modernismo",
      body: "La Ilustración inaugura la modernidad europea, que culmina en 1789 (fecha con que los historiadores europeos la datan): la modernidad es un período. La modernización son los cambios concretos ligados a ella: avance tecnológico, industrialización, urbanización, migración del campo a la ciudad, creación de obreros, capitalismo, paso de una economía de trueque a una monetaria, mejoras en comunicaciones y transporte —cambios técnicos y materiales—. El modernismo es una respuesta estética (en literatura, arte, filosofía). No son distinciones absolutas, pero así se usan los términos.",
    },
    {
      type: "match",
      question: "Uní cada término con lo que designa",
      pairs: [
        { left: "Modernidad", right: "El período que inaugura la Ilustración y culmina en 1789" },
        { left: "Modernización", right: "Industrialización, urbanización, capitalismo: cambios materiales" },
        { left: "Modernismo", right: "La respuesta estética en literatura, arte y filosofía" },
      ],
      explain: "No son distinciones absolutas, pero así se usan los términos: la modernidad es un período, la modernización son los cambios técnicos y materiales ligados a él —del campo a la ciudad, del trueque al dinero—, y el modernismo es la respuesta estética que llegará después.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada pensador con su aporte",
      pairs: [
        { left: "Descartes", right: "La duda radical y el cogito, ergo sum" },
        { left: "Hobbes", right: "El Leviatán: seguridad a cambio de libertad" },
        { left: "Locke", right: "El gobierno por consentimiento de los gobernados" },
        { left: "Rousseau", right: "La voluntad general y la nostalgia del estado de naturaleza" },
        { left: "Kant", right: "Sapere aude y la revolución copernicana" },
      ],
      explain: "Los cinco nombres que sostienen la clase: Descartes abre la epistemología moderna, Hobbes y Locke fundan el contrato social en direcciones opuestas, Rousseau lo lleva a la voluntad general —y de ahí al Terror—, y Kant formula el lema de la Ilustración y su compromiso entre realismo e idealismo.",
    },
    {
      type: "info",
      title: "Conclusión: el optimismo ilustrado",
      body: "El legado de la Ilustración es el optimismo en el poder de la razón: el conocimiento es bueno, progresivo, y nos permite comprender y sostener mejor el mundo.  La próxima clase nos preguntaremos: ¿tiene la Ilustración un lado oscuro? Como diría Goethe de Moses Mendelssohn: \"todo muy bien, pero trata la belleza como el entomólogo a las mariposas: la atrapa, la clava con un alfiler, su color palidece y queda una cáscara sin vida\". En la próxima unidad hablaremos de la rebelión romántica.",
    },
  ],
};
