// Clase 19 (transcripción) — Estructuralismo y antropología
// App Clase 18. Feed: 'info', 'quiz', 'classify' (comparar), 'match' (conectar), 'short'.
// Tono: resumen fiel de la clase. Preguntas exigentes, con distractores plausibles.
//
// NUMERACIÓN: num (app) = transcript - 1. El archivo se nombra por transcript.
export default {
  num: 18,
  transcript: 19,
  title: "Estructuralismo y antropología",
  source: "https://www.youtube.com/watch?v=k0ZLNVIrdcU",
  feed: [
    {
      type: "info",
      tag: "Panorama",
      title: "La palabra clave es «estructura»",
      body: "El estructuralismo es otra respuesta a la muerte de Dios, otro modo de llenar el vacío. Pero, a diferencia del humanismo marxista que le inyectaba subjetividad al marxismo, hace el movimiento opuesto: es antihumanista, en sentido descriptivo. El sujeto individual no está en el centro ni es la fuente del sentido. La variable primaria no es el tiempo ni la subjetividad, sino un sistema de signos. Su modelo: la lingüística.",
    },
    {
      type: "info",
      tag: "Saussure",
      title: "La lengua es forma, no sustancia",
      body: "El origen es Ferdinand de Saussure, cuyo libro fundacional son apuntes de sus alumnos, publicados tras su muerte. Su tesis revolucionaria: la lengua considerada en y por sí misma es el único objeto de la lingüística, y es forma, no sustancia. Es una ciencia de la forma: un sistema de diferencias, no de sustancias. Ningún elemento significa al margen de su relación con el todo.",
    },
    {
      type: "info",
      tag: "El signo",
      title: "Significante, significado, arbitrariedad",
      body: "El signo une un significante (la palabra, sus letras y sonidos) y un significado (el referente). Y su relación es arbitraria: no hay ley natural que ligue los sonidos «gato» a ese animal —lo prueban las muchas lenguas con palabras distintas para lo mismo—. El significante significa por diferencia: «gato» significa porque no es «pato», «gasto» ni «perro». Es convención, no naturaleza.",
    },
    {
      type: "quiz",
      question: "¿Qué significa que el signo lingüístico sea «arbitrario»?",
      options: [
        "Que cada persona elige libremente qué significan las palabras",
        "Que no hay lazo natural entre el sonido y su referente",
        "Que el lenguaje carece por completo de reglas",
        "Que el significado cambia a cada instante",
      ],
      answer: 1,
      explain: "No hay ley física que ligue los sonidos «gato» a ese animal —lo prueban las muchas lenguas con palabras distintas para lo mismo—. El significante significa por diferencia: «gato» no es «pato» ni «perro». Es convención, no naturaleza.",
    },
    {
      type: "short",
      question: "En el signo de Saussure, ¿cómo se llama la parte «sonora» —la palabra, sus letras y sonidos—, frente al significado?",
      answers: ["significante"],
      explain: "El significante (la palabra, los sonidos), frente al significado (el referente). El signo une a ambos, pero de manera arbitraria; y el significante significa por diferencia con los demás, no por un lazo natural.",
    },
    {
      type: "info",
      tag: "Estable",
      title: "Arbitraria pero estable",
      body: "Pese a esa arbitrariedad radical, la relación es estable: no nos despertamos un día y «gato» ya no significa gato. ¿Por qué? Porque se sostiene en la estructura de la lengua, un sistema holístico (eco de Hegel: «lo verdadero es el todo»). Ningún elemento tiene significado al margen del todo. Y hace falta una comunidad para fijar esos valores: un individuo solo no puede.",
    },
    {
      type: "info",
      tag: "Sincronía",
      title: "Sincrónico y diacrónico",
      body: "Saussure distingue tajantemente el plano diacrónico (el eje del tiempo, la evolución de la lengua) del sincrónico (el eje de la simultaneidad, el sistema en un momento dado). El estructuralismo trabaja en el plano sincrónico: tras tanto inyectar historia en la filosofía, ahora se para en pura simultaneidad. Como en el ajedrez: la posición actual se describe sin conocer las jugadas previas.",
    },
    {
      type: "classify",
      question: "¿Cada cosa pertenece al plano sincrónico o al diacrónico?",
      groups: ["Sincrónico", "Diacrónico"],
      items: [
        { text: "El sistema de la lengua en un momento dado", group: 0 },
        { text: "La evolución de la lengua con el tiempo", group: 1 },
        { text: "El eje de la simultaneidad", group: 0 },
        { text: "El eje del tiempo y el cambio histórico", group: 1 },
        { text: "El tablero de ajedrez tal como está ahora", group: 0 },
        { text: "La secuencia de jugadas que llevó a esa posición", group: 1 },
      ],
      explain: "El plano diacrónico es el del tiempo: cómo evoluciona la lengua. El sincrónico es el de la simultaneidad: cómo funciona el sistema en un instante. Como en el ajedrez, la posición actual se describe sin conocer las jugadas previas. El estructuralismo trabaja en el plano sincrónico, poniendo la historia entre paréntesis.",
    },
    {
      type: "info",
      tag: "Esperanto",
      title: "Una lengua que nadie posea",
      body: "Una curiosidad: el esperanto, inventado por Ludwik Zamenhof —oftalmólogo y fabricante de lentes, otra vez la obsesión con ver claro—. Criado en un entorno multilingüe y con conflicto étnico, imaginó una lengua internacional que nadie poseyera más que otro, fácil, sin excepciones, un puente igualador. La empezó a los quince y publicó como «Dr. Esperanto», «Dr. Esperanza». Ganó impulso, pero no salvó al mundo.",
    },
    {
      type: "info",
      tag: "Semiología",
      title: "El lenguaje produce el sentido",
      body: "La lingüística se vuelve el modelo para repensarlo todo, y lleva a la semiología: el estudio de los signos y sus leyes. Ideas centrales: separar significante y significado, mirar lo sincrónico (el sistema como todo), el significado como relacional. De ahí una inversión decisiva: el lenguaje no expresa ni refleja un significado ya dado, sino que lo produce; los signos estructuran el pensamiento.",
    },
    {
      type: "quiz",
      question: "¿Cuál es la «inversión» clave del estructuralismo sobre el lenguaje?",
      options: [
        "El lenguaje refleja un significado que ya existía",
        "El lenguaje produce el significado, no lo refleja",
        "El lenguaje es un simple instrumento neutral",
        "El lenguaje deriva de la biología del cerebro",
      ],
      answer: 1,
      explain: "En vez de expresar o reflejar un significado pregado, el lenguaje lo produce: los signos estructuran el pensamiento. De ahí se sigue el descentramiento del sujeto, más producido por el lenguaje que a la inversa.",
    },
    {
      type: "short",
      question: "¿Cómo se llama la ciencia general de los signos y sus leyes a la que apunta el estructuralismo?",
      answers: ["semiología", "semiótica"],
      explain: "La semiología (o semiótica): el estudio de los signos, con la lingüística como modelo. Su idea central es que los signos significan por sus relaciones mutuas, y que el lenguaje no refleja el significado, lo produce.",
    },
    {
      type: "info",
      tag: "El encuentro",
      title: "Jakobson y Lévi-Strauss en Nueva York",
      body: "Todo depende de un encuentro. Roman Jakobson —lingüista que había fundado los círculos de Moscú y de Praga, judío huyendo del nazismo— llega a Nueva York, y allí Alexandre Koyré le presenta a Claude Lévi-Strauss, antropólogo también exiliado, con trabajo de campo en Latinoamérica. De ese encuentro legendario nace la antropología estructural. Sin él, toda una historia intelectual no habría ocurrido.",
    },
    {
      type: "info",
      tag: "Lévi-Strauss",
      title: "La antropología estructural",
      body: "La meta de Lévi-Strauss: descubrir las leyes profundas que gobiernan los sistemas culturales. Parte de una noción amplia de cultura (herramientas, instituciones, arte, lenguaje) y de una premisa freudiana: mucho de la cultura opera a nivel inconsciente. ¿Qué aprende de la lingüística? A tratar la cultura como simbolismo, y a preguntar por cada sistema si es, como la lengua, verdaderamente sistemático.",
    },
    {
      type: "info",
      tag: "Parentesco",
      title: "«El parentesco es un lenguaje»",
      body: "El sistema de parentesco funciona como un lenguaje: sus unidades tienen valor sólo por la coordinación de sus diferencias. No existe en los lazos objetivos de sangre, sino en la conciencia humana, como un sistema arbitrario de representaciones que hay que leer como un todo —el ejemplo del avunculado—. Aparece el tabú del incesto (freudiano). Y todo gira en torno a binarios: crudo/cocido, alto/bajo.",
    },
    {
      type: "quiz",
      question: "¿Por qué dice Lévi-Strauss que «el sistema de parentesco es un lenguaje»?",
      options: [
        "Porque se transmite oralmente entre generaciones",
        "Porque sus unidades valen por diferencia, no por sangre",
        "Porque cada cultura usa las mismas palabras de parentesco",
        "Porque el parentesco es idéntico en todas las lenguas",
      ],
      answer: 1,
      explain: "Como los signos, las relaciones de parentesco no valen por lazos objetivos de sangre, sino por su lugar en un sistema de diferencias, en la conciencia humana. Es un sistema arbitrario de representaciones que hay que leer como un todo.",
    },
    {
      type: "info",
      tag: "El mito",
      title: "Los mitos se piensan solos",
      body: "Su trabajo sobre el mito será clave. Los mitos de todas las culturas son variaciones de un número acotado de temas, con estructuras universales; funcionan como un lenguaje, combinables según una gramática inherente a la mente. Y algo radical: la mente que «piensa» el mito no es la de un sujeto individual; en cierto sentido, los mitos se piensan a sí mismos a través de las personas. El sujeto queda descentrado.",
    },
    {
      type: "quiz",
      question: "¿Qué implica el «descentramiento del sujeto» en Lévi-Strauss?",
      options: [
        "Que cada individuo crea libremente sus propios mitos",
        "Que los mitos se piensan a sí mismos a través nuestro",
        "Que sólo los genios producen la cultura",
        "Que el sujeto controla por completo el lenguaje",
      ],
      answer: 1,
      explain: "La mente que «piensa» el mito no es la de un sujeto individual: en cierto sentido los mitos se piensan a sí mismos a través de nosotros. El sujeto es más producido por el lenguaje que a la inversa: deja de ser la fuente del sentido.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del estructuralismo o del existencialismo?",
      groups: ["Estructuralismo", "Existencialismo"],
      items: [
        { text: "El sujeto es descentrado, producido por el sistema", group: 0 },
        { text: "El sujeto es la fuente del sentido y elige", group: 1 },
        { text: "La variable primaria es un sistema de signos", group: 0 },
        { text: "La variable primaria es la libertad y la elección", group: 1 },
        { text: "Trabaja en el plano sincrónico, sin historia", group: 0 },
        { text: "El tiempo y la angustia están en el centro", group: 1 },
      ],
      explain: "El existencialismo pone al sujeto —su libertad, su elección, su angustia en el tiempo— en el centro. El estructuralismo hace el movimiento opuesto, antihumanista: descentra al sujeto (producido por el sistema, no su fuente), pone entre paréntesis la historia y trabaja en el plano sincrónico. La variable primaria ya no es la subjetividad, sino la estructura.",
    },
    {
      type: "match",
      question: "Uní cada término del estructuralismo con lo que nombra",
      pairs: [
        { left: "Significante y significado", right: "Se unen de modo arbitrario; significan por diferencia" },
        { left: "Sincronía", right: "El sistema en un momento dado, no su evolución" },
        { left: "Lengua como forma", right: "Un sistema de diferencias, no de sustancias" },
        { left: "Parentesco", right: "Un lenguaje: vale por relaciones, no por la sangre" },
        { left: "Descentramiento del sujeto", right: "El sujeto es producido por el lenguaje, no su fuente" },
      ],
      explain: "Las piezas encajan: la lengua es forma (diferencias), el signo une significante y significado de modo arbitrario, el análisis se para en la sincronía, y Lévi-Strauss extiende el modelo a la cultura —el parentesco como lenguaje— hasta descentrar al sujeto, que ya no es fuente sino producto del sistema.",
    },
    {
      type: "info",
      tag: "Cierre",
      title: "El giro lingüístico",
      body: "Las críticas: relativismo, abolición del sujeto y de la experiencia, ahistoricismo, dispersión de la agencia. Pero el estructuralismo abre el «giro lingüístico»: se relee toda la vida humana —historia, literatura, cultura— según el modelo del lenguaje, y todo se vuelve un constructo lingüístico. La relación precede a las partes. Y queda una pregunta: si el sujeto quedó aplastado, ¿adónde fue? La próxima clase, Girard.",
    },
  ],
};
