// Clase 15 (transcripción) — Hannah Arendt: el totalitarismo y la naturaleza del mal
// App Clase 14. Feed: 'info', 'quiz', 'classify' (comparar), 'match' (conectar), 'short'.
// Tono: resumen fiel de la clase. Preguntas exigentes, con distractores plausibles.
//
// NUMERACIÓN: num (app) = transcript - 1. El archivo se nombra por transcript.
export default {
  num: 14,
  transcript: 15,
  title: "Hannah Arendt: totalitarismo y el mal",
  source: "https://www.youtube.com/watch?v=Naev-AFcN5k",
  feed: [
    {
      type: "info",
      tag: "Panorama",
      title: "Pensar el totalitarismo y el mal",
      body: "Hannah Arendt, alumna de Heidegger y judía alemana exiliada, escribe la gran interpretación del totalitarismo del siglo XX. En Los orígenes del totalitarismo rastrea de dónde viene el horror; en el libro sobre Eichmann acuña «la banalidad del mal». Su lectura es profundamente universalista: el mal no es cosa de «cierto tipo de gente», sino un potencial de la modernidad que todos llevamos.",
    },
    {
      type: "info",
      tag: "Frankfurt",
      title: "En la conversación de Frankfurt",
      body: "Arendt entra en el debate de Adorno y Horkheimer sobre si el totalitarismo es una desviación de la modernidad o su culminación (odia a Adorno, aunque es muy cercana a Benjamin). Donde ellos hablaban de «la manada», ella la desenreda en dos categorías distintas y nuevas: la turba y las masas. También estaba en EE. UU. en 1943, cuando llegó la noticia del Holocausto.",
    },
    {
      type: "info",
      tag: "Biografía",
      title: "El abismo de 1943",
      body: "Nació en 1906, judía alemana asimilada; a los dieciocho fue a estudiar con Heidegger, con una sólida formación clásica. En 1933 la arrestan; escapa de Alemania y en 1941 llega a Nueva York. En una entrevista dirá que lo decisivo no fue 1933, sino 1943, al conocerse Auschwitz: «fue como si se abriera un abismo. Todo lo demás podía enmendarse; esto no. Esto no debería haber ocurrido».",
    },
    {
      type: "quiz",
      question: "Para Arendt, ¿cuál fue el momento decisivo?",
      options: [
        "1933, cuando los nazis conquistaron el poder",
        "1943, al conocerse la noticia de Auschwitz",
        "1919, con el Tratado de Versalles",
        "1961, con el juicio a Eichmann",
      ],
      answer: 1,
      explain: "«Lo decisivo no fue 1933, sino el día en que supimos de Auschwitz, en 1943.» Antes se podía pensar que todo, en política, podía enmendarse; esto no. «Fue como si se abriera un abismo: esto no debería haber ocurrido.»",
    },
    {
      type: "info",
      tag: "Los orígenes",
      title: "Nazismo y estalinismo, hermanos",
      body: "Los orígenes del totalitarismo, escrita en el exilio (1945-50), se divide en tres partes: antisemitismo, imperialismo y totalitarismo. Nace de una intuición: hay una similitud esencial entre nazismo y estalinismo, justo cuando se combaten a muerte. Dos fenómenos antitéticos pero profundamente parecidos, y ambos nuevos en la historia. El trasfondo es siempre la alienación moderna.",
    },
    {
      type: "quiz",
      question: "¿Cuál es la intuición central de Los orígenes del totalitarismo?",
      options: [
        "Que el nazismo fue mucho peor que el estalinismo",
        "Que nazismo y estalinismo son muy parecidos",
        "Que el totalitarismo es un fenómeno muy antiguo",
        "Que sólo Alemania podía producir el totalitarismo",
      ],
      answer: 1,
      explain: "Arendt intuye una similitud esencial entre nazismo y estalinismo justo cuando se combaten a muerte: dos fenómenos antitéticos pero profundamente parecidos, y ambos nuevos en la historia. El totalitarismo es un tipo de régimen inédito.",
    },
    {
      type: "info",
      tag: "Dreyfus",
      title: "Cuando la política sale a la calle",
      body: "Un punto de inflexión es el caso Dreyfus: un oficial francés judío, incriminado por traición y condenado en 1894 (su inocencia se probaría luego). Lo que captura a Arendt no es Dreyfus ni la corrupción de la élite, sino las masas gritando en la calle «¡muerte a los judíos!». Es la política saliendo a la calle, y el fracaso del liberalismo: si fracasa en Francia, patria de la Ilustración, fracasó sin más.",
    },
    {
      type: "info",
      tag: "Turba y masas",
      title: "Dos grupos, no sinónimos",
      body: "Arendt vuelve técnicos dos términos. La turba (mob) son los gánsteres: el reverso oscuro de la burguesía, resentidos por sentirse excluidos, con los valores burgueses depurados de hipocresía —y la burguesía se deleita en secreto con su irreverencia—. Las masas son la mayoría antes políticamente inactiva e indiferente, sin organización ni interés común, a la que nadie había pensado en movilizar.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de la «turba» o de las «masas»?",
      groups: ["La turba (mob)", "Las masas"],
      items: [
        { text: "Son los gánsteres, el reverso de la burguesía", group: 0 },
        { text: "La mayoría antes inactiva e indiferente", group: 1 },
        { text: "Resentidos por sentirse excluidos de la sociedad", group: 0 },
        { text: "Sin organización ni interés común que las una", group: 1 },
        { text: "Encarnan los valores burgueses sin la hipocresía", group: 0 },
        { text: "Nadie había pensado en movilizarlas antes", group: 1 },
      ],
      explain: "La turba es una minoría activa y resentida, el reverso criminal de la burguesía, que se deleita en secreto con ella. Las masas son la mayoría apática e inorganizada. El drama moderno: las masas salen por fin al escenario, pero lideradas por la turba y no del lado del liberalismo.",
    },
    {
      type: "info",
      tag: "Imperialismo",
      title: "La primera etapa del dominio burgués",
      body: "La segunda parte lee el imperialismo en clave casi marxista. El capital no es el dinero para comprar café, sino dinero para invertir y hacer más dinero; funciona como «pecado original». La acumulación de capital superfluo empuja a una expansión constante. Para Lenin el imperialismo es la última etapa del capitalismo; para Arendt, la primera del dominio burgués, y salva un tiempo al Estado-nación de la turba dándole algo que hacer.",
    },
    {
      type: "quiz",
      question: "¿En qué se diferencia Arendt de Lenin sobre el imperialismo?",
      options: [
        "Para ella es la última etapa del capitalismo",
        "Para ella es la primera etapa del dominio burgués",
        "Para ella no guarda relación alguna con el capitalismo",
        "Para ella es un invento del siglo veinte",
      ],
      answer: 1,
      explain: "Para Lenin el imperialismo era la última etapa del capitalismo; para Arendt es la primera del dominio burgués. La acumulación de capital superfluo empuja a la expansión, y el imperialismo salva temporalmente al Estado-nación de la turba dándole algo que hacer.",
    },
    {
      type: "info",
      tag: "Superfluos",
      title: "Volverse innecesarios",
      body: "La tercera parte va a la destrucción de la subjetividad: cómo los seres humanos se vuelven superfluos, innecesarios. Ocurre de dos maneras: por la apatridia —quedarse sin Estado— y por la atomización y el conformismo. Ese volverse superfluo, para Arendt, es la condición sobre la que se monta el exterminio: primero sobran, después se los elimina.",
    },
    {
      type: "info",
      tag: "Apatridia",
      title: "Un pasaporte para ser humano",
      body: "La Primera Guerra —imperios disueltos, fronteras nuevas, el pasaporte obligatorio— crea multitudes de apátridas. De golpe hace falta un pasaporte «para ser un ser humano». Y la Declaración de los Derechos del Hombre y del Ciudadano no se sostiene: sin un Estado que los haga cumplir, no hay «derechos del hombre», sólo derechos de ciudadanos. Esa carencia total de derechos fue precondición del exterminio.",
    },
    {
      type: "quiz",
      question: "Según Arendt, ¿por qué no existen «derechos del hombre»?",
      options: [
        "Porque los seres humanos por sí solos no merecen derechos",
        "Porque sólo hay derechos de ciudadanos, no de humanos",
        "Porque la Declaración de 1789 nunca fue escrita",
        "Porque los derechos vienen sólo de Dios",
      ],
      answer: 1,
      explain: "Sin un Estado que los garantice, los «derechos del hombre» no se sostienen: sólo existen derechos de ciudadanos. El apátrida, reducido a «nada más que un ser humano», queda sin derechos, y esa carencia total fue precondición del exterminio.",
    },
    {
      type: "short",
      question: "¿Cómo llama Arendt a la condición de quien, sin un Estado que lo ampare, queda sin derechos?",
      answers: ["apatridia", "apátrida"],
      explain: "La apatridia (ser apátrida). Tras la Primera Guerra, de golpe «hace falta un pasaporte para ser un ser humano»: sin ciudadanía no hay derechos, y esa carencia total fue una precondición del exterminio.",
    },
    {
      type: "info",
      tag: "Extinción del yo",
      title: "Muertos antes de morir",
      body: "No sólo las víctimas se vuelven superfluas: también los perpetradores, reclutados de masas atomizadas que, a cambio del fin de su aislamiento, entregan su yo. La subjetividad se extingue en unas y otros, y antes de la muerte física: para cuando los llevaban a las cámaras de gas, «ya estaban muertos». El campo, al volver la muerte anónima, le roba su sentido —polémica con Heidegger, para quien morir era lo único propio—.",
    },
    {
      type: "info",
      tag: "Fronteras",
      title: "Tres fronteras borradas",
      body: "El totalitarismo borra tres distinciones. Verdad y falsedad: la ideología arma un mundo ficticio pero de consistencia lógica, sin la contingencia de lo real. Público y privado: no queda espacio para hacerse a un lado; importa hasta qué pensás. Verdugos y víctimas: como toda subjetividad se extingue, cada uno delata al otro, y todos son a la vez infinitamente poderosos e infinitamente vulnerables.",
    },
    {
      type: "quiz",
      question: "¿Qué afirma Arendt, polémicamente, sobre la subjetividad en el totalitarismo?",
      options: [
        "Que sólo las víctimas conservan intacto su yo",
        "Que el yo se extingue en víctimas y en verdugos",
        "Que los perpetradores refuerzan su individualidad",
        "Que el terror no afecta la vida interior",
      ],
      answer: 1,
      explain: "Para Arendt la subjetividad se destruye tanto en las víctimas como en los perpetradores —masas atomizadas que entregan su yo a cambio del fin del aislamiento—, y antes de la muerte física: «para cuando los llevaban a las cámaras de gas, ya estaban muertos».",
    },
    {
      type: "info",
      tag: "Todo es posible",
      title: "Los campos como laboratorio",
      body: "Junto a esto, el totalitarismo rechaza los límites de lo posible y cree en la omnipotencia humana: tomar al pie de la letra que «si Dios ha muerto, todo está permitido». El cinismo moral —todo está permitido— descansa en la convicción de que todo es posible. Los campos de concentración y exterminio son los laboratorios en los que se verifica esa creencia fundamental.",
    },
    {
      type: "info",
      tag: "Eichmann",
      title: "Del mal radical al mal banal",
      body: "Los orígenes hablaba del mal radical: absoluto, imperdonable, que ya no se explica por motivos como la codicia o el poder. Pero en 1961, cubriendo el juicio de Adolf Eichmann en Jerusalén, Arendt parece cambiar: la escalofría la discrepancia entre la monstruosidad del acto y la mediocridad del hombre. Eichmann no es un monstruo, sino un burócrata que no puede decir una frase que no sea un cliché.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo corresponde al «mal radical» o a la «banalidad del mal»?",
      groups: ["Mal radical", "Banalidad del mal"],
      items: [
        { text: "El mal absoluto, imperdonable e incastigable", group: 0 },
        { text: "Brota de la pura incapacidad de pensar", group: 1 },
        { text: "Excede todo motivo humano comprensible", group: 0 },
        { text: "Su agente es un burócrata mediocre, no un monstruo", group: 1 },
        { text: "Emerge cuando todos se han vuelto superfluos", group: 0 },
        { text: "Se expresa en puros clichés, sin una idea propia", group: 1 },
      ],
      explain: "En Los orígenes, Arendt describe el mal radical: absoluto, más allá de todo motivo, que emerge cuando los seres humanos se vuelven superfluos. Ante Eichmann parece cambiar: el mal banal no viene de una maldad monstruosa, sino de la incapacidad de pensar de un burócrata que sólo repite clichés.",
    },
    {
      type: "short",
      question: "¿Con qué expresión resume Arendt el mal de Eichmann —un burócrata que no piensa, no un monstruo?",
      answers: ["banalidad del mal"],
      explain: "La banalidad del mal. El horror no está en un monstruo demoníaco, sino en la mediocridad de un burócrata incapaz de pensar por sí mismo y de ponerse en el lugar de otro. Para Arendt eso no lo excusa: lo hace peor, porque el mayor crimen es no pensar.",
    },
    {
      type: "match",
      question: "Uní cada concepto de Arendt con lo que nombra",
      pairs: [
        { left: "La turba (mob)", right: "Los gánsteres: el reverso resentido de la burguesía" },
        { left: "Las masas", right: "La mayoría antes inactiva, sin interés común que la una" },
        { left: "Apatridia", right: "Sin Estado no hay derechos: antesala del exterminio" },
        { left: "Mal radical", right: "El mal absoluto, imperdonable, que excede todo motivo" },
        { left: "Banalidad del mal", right: "El mal que brota de la incapacidad de pensar" },
      ],
      explain: "El arco del libro: el fracaso del liberalismo saca a la calle a la turba y a las masas; la apatridia vuelve superfluos a los seres humanos; y el resultado es un mal primero radical y luego, en Eichmann, banal —el del que ha dejado de pensar—.",
    },
    {
      type: "info",
      tag: "Cierre",
      title: "Un universalismo del mal",
      body: "Arendt rechaza explicar el Holocausto por el «carácter nacional»: nada volvía asesinos a los alemanes ni víctimas a los judíos. El totalitarismo explota un potencial de las masas alienadas de la modernidad que todos llevamos con nosotros. De ahí que no deje dormir tranquilo. Su imperativo moral es que pensemos —el gran crimen de Eichmann fue no pensar—; y dijo: «me avergüenzo de ser humana».",
    },
  ],
};
