// Clase 11 (transcripción) — La fenomenología
// App Clase 10. Feed: 'info', 'quiz', 'classify' (comparar), 'match' (conectar), 'short'.
// Tono: resumen fiel de la clase. Preguntas exigentes, con distractores plausibles.
//
// NUMERACIÓN: num (app) = transcript - 1. El archivo se nombra por transcript.
export default {
  num: 10,
  transcript: 11,
  title: "La fenomenología",
  source: "https://www.youtube.com/watch?v=8OCDFEn_hRE",
  feed: [
    {
      type: "info",
      tag: "Panorama",
      title: "El tercer rebelde y la sed de certeza",
      body: "Edmund Husserl es el tercero del trío que se rebela contra el positivismo —con Bergson y Freud— y el más difícil, porque queda a un pelo de aquello que rechaza. Contra el vértigo moderno de la falta de fundamento no busca, como la vanguardia, libertad sin suelo, sino lo contrario: un suelo absoluto, claridad epistemológica y verdad cierta. Funda la fenomenología.",
    },
    {
      type: "info",
      tag: "Falta de suelo",
      title: "El miedo a quedarse sin fundamento",
      body: "La Primera Guerra hace arder Europa: «todo lo sólido se desvanece en el aire», caen cuatro imperios, de golpe hace falta pasaporte y nadie sabe cuáles son las reglas nuevas. La vanguardia vivió esa caída libre como éxtasis y como terror. Husserl siente el mismo problema moderno —¿dónde empezar?, ¿de qué podemos estar seguros?—, pero lo vive como una urgencia por hallar fundamento.",
    },
    {
      type: "info",
      tag: "Alter ego",
      title: "El reverso de la vanguardia",
      body: "Nadie es más alter ego de la vanguardia que Husserl: si ella era ruptura salvaje, sexo y experimentación, él es un burgués aburridísimo entregado sólo a pensar. Pero está del otro lado de los mismos problemas: comparte la subjetividad radical de Freud y el maximalismo vanguardista de ir hasta el final. La vanguardia caerá con el estalinismo; los fenomenólogos, con el nazismo.",
    },
    {
      type: "quiz",
      question: "¿En qué sentido es Husserl el «alter ego» de la vanguardia?",
      options: [
        "Comparte su estética de ruptura y su vida bohemia",
        "Enfrenta el mismo problema con la respuesta opuesta",
        "Rechaza de plano la idea de una subjetividad radical",
        "Cree, como ella, que el mundo puede crearse de la nada",
      ],
      answer: 1,
      explain: "Comparten época y problema —la falta de fundamento, la subjetividad radical, el maximalismo—, pero donde la vanguardia salta a la caída libre sin suelo, Husserl busca desesperadamente un suelo absoluto de certeza.",
    },
    {
      type: "info",
      tag: "Biografía",
      title: "Anteojos, ojos y una barba",
      body: "Husserl nació en 1859 —la generación de Bergson y Freud— en Moravia, un judío germanoparlante que se convierte al protestantismo. Empieza en la matemática. Tuvo una obsesión reveladora: no con los marcos de los anteojos, sino con las lentes, con ver claro. ¿Se puede ver el mundo con tal precisión como para estar seguro de que es real? Witkacy dijo que era «anteojos, ojos y una barba flotando en el espacio».",
    },
    {
      type: "info",
      tag: "El puente",
      title: "Sujeto y objeto, otra vez",
      body: "Vuelve el problema del puente: ¿cómo sé que esta taza es real y no una proyección de mi conciencia? Estoy siempre dentro de mi cabeza, sin modo de salir a verificar cómo se ven las cosas desde afuera. Se parte de la primera persona: yo soy el sujeto, todo lo demás es objeto. La fenomenología quiere cruzar ese puente sin renunciar a la certeza.",
    },
    {
      type: "info",
      tag: "Positivismo",
      title: "Contra la «vista desde ninguna parte»",
      body: "La fenomenología es una rebelión subjetivista contra el objetivismo fanático de la ciencia decimonónica: contra el sueño de una «vista desde ninguna parte», un punto de vista sin sujeto, puro objeto. Emmanuel Levinas, alumno de Husserl, decía que el positivismo aspiraba al reino de los objetos puros, «como un salto a la nada». La fenomenología invierte esa actitud y devuelve el sujeto al centro.",
    },
    {
      type: "quiz",
      question: "Para Husserl y Levinas, ¿qué le faltaba al positivismo decimonónico?",
      options: [
        "El rigor matemático de sus muchas mediciones",
        "El sujeto: soñaba un conocimiento sin nadie",
        "La fe en el progreso indefinido de la ciencia",
        "La atención a la lógica y a sus leyes puras",
      ],
      answer: 1,
      explain: "El positivismo aspiraba a una «vista desde ninguna parte», puro objeto sin sujeto —«un salto a la nada», decía Levinas—. La fenomenología invierte esa actitud: devuelve el sujeto al centro del conocimiento.",
    },
    {
      type: "info",
      tag: "Psicologismo",
      title: "Ni objeto puro ni pura mente",
      body: "Pero Husserl también rechaza el psicologismo: la idea de que todo se reduce a cómo funciona nuestra mente, que la lógica, la verdad y la evidencia son meras leyes de la psique. Eso también le resulta insatisfactorio. Busca un lugar entre el positivismo y el psicologismo, y por eso es tan difícil de entender: se rebela contra cosas de las que queda a un pelo de distancia.",
    },
    {
      type: "classify",
      question: "¿Cada postura corresponde al positivismo o al psicologismo?",
      groups: ["Positivismo", "Psicologismo"],
      items: [
        { text: "Aspira a una «vista desde ninguna parte», sin sujeto", group: 0 },
        { text: "Reduce la verdad y la lógica a leyes de la mente", group: 1 },
        { text: "Toma como modelo la física y el laboratorio", group: 0 },
        { text: "Cree que sólo son seguras las reglas de la mente", group: 1 },
        { text: "Expulsa todo elemento subjetivo del conocimiento", group: 0 },
        { text: "Hace de la psique la medida de todo lo cierto", group: 1 },
      ],
      explain: "Husserl rechaza los dos extremos: el positivismo diluye el sujeto en el objeto puro; el psicologismo diluye el objeto en la mente. La fenomenología busca un lugar entre ambos, sin renunciar ni a la subjetividad ni a la verdad objetiva.",
    },
    {
      type: "info",
      tag: "Descartes sí",
      title: "Empezar en cero, como Descartes",
      body: "Husserl admira a Descartes: cree que hizo la pregunta correcta —vaciar la mente de todo lo dado y preguntar «empezando por nada, ¿de qué puedo estar seguro?»—. Como él, quiere partir de cero absoluto, sin suponer nada. La certeza cartesiana del cogito —que estoy pensando— es su modelo: un fundamento indudable desde el cual reconstruirlo todo.",
    },
    {
      type: "info",
      tag: "Kant no",
      title: "El «fatalismo» de Kant",
      body: "Con Kant, en cambio, Husserl es despectivo. No tolera que sea «radical en su moderación»: sí, hay un mundo real, pero la cosa en sí (Ding an sich) es inalcanzable, así que dejémosla de lado y concentrémonos en lo que sí podemos conocer. Para Husserl eso es fatalismo, rendición. Él es el «yes we can» epistemológico: sí se puede alcanzar la cosa real y la verdad absoluta.",
    },
    {
      type: "quiz",
      question: "¿Por qué Husserl rechaza la solución de Kant?",
      options: [
        "Porque Kant niega que exista un mundo real",
        "Porque renunciar a la cosa en sí le parece rendición",
        "Porque Kant reduce toda verdad al funcionamiento mental",
        "Porque Kant empieza su filosofía desde cero",
      ],
      answer: 1,
      explain: "Kant admite un mundo real pero declara inalcanzable la cosa en sí y propone concentrarse en lo conocible. A Husserl esa renuncia le resulta insoportable: cree que sí se puede llegar a la verdad absoluta.",
    },
    {
      type: "info",
      tag: "Vocabulario",
      title: "Inmanente, trascendente, trascendental",
      body: "Tres términos que Husserl distingue con cuidado. Lo inmanente está adentro de la conciencia; lo trascendente, del otro lado de su frontera, afuera. «Trascendental» es otra cosa: siguiendo a Kant, nombra las condiciones de posibilidad de que la mente alcance el objeto —qué hace posible cruzar la frontera—. De ahí su término clave: el ego trascendental.",
    },
    {
      type: "info",
      tag: "Método",
      title: "Un método, no una teoría",
      body: "Lo que Husserl ofrece es menos una teoría que un método: una manera de intentar ver el mundo. Quiere una ciencia rigurosa, pero no positivista —romper con el empirismo y a la vez fundar todas las demás ciencias—. Empieza con dos cosas: el mundo, horizonte único en el que los objetos se nos aparecen, y el yo, aquel a quien el mundo le es dado.",
    },
    {
      type: "info",
      tag: "El yo",
      title: "El ego empírico y el trascendental",
      body: "Husserl distingue dos yo. El empírico es el que somos en la vida real: cada uno distinto, contingente, con su cuerpo y su historia. El trascendental es lo más íntimo y esencial de cada uno y, a la vez, universal, el mismo para todos. Como el agua: sabe distinta en cada lugar, pero hay un H₂O común. El ego trascendental es ese «H₂O» del yo.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del yo empírico o del trascendental?",
      groups: ["Yo empírico", "Yo trascendental"],
      items: [
        { text: "Es particular: cada persona tiene el suyo", group: 0 },
        { text: "Es universal: el mismo para todos", group: 1 },
        { text: "Depende del cuerpo, la historia y el lugar", group: 0 },
        { text: "Es como el H₂O común a toda agua", group: 1 },
        { text: "Es contingente y cambia de una vida a otra", group: 0 },
        { text: "Es lo más íntimo y esencial de cada uno", group: 1 },
      ],
      explain: "El yo empírico es el particular y contingente de la vida real; el trascendental es a la vez lo más profundo de cada uno y algo universal, el mismo para todos —como el agua, distinta en cada lugar y sin embargo H₂O—. La fenomenología trabaja con este segundo yo.",
    },
    {
      type: "info",
      tag: "Intencionalidad",
      title: "La conciencia estalla hacia el objeto",
      body: "¿Cómo alcanza el yo al objeto? No como el yo cartesiano, encerrado sin ventanas en su caja. Su estructura es la intencionalidad (término que Husserl toma de Brentano): la conciencia siempre está dirigida hacia algo, alcanzando y agarrando el objeto, como una cuerda con una flecha magnética. La conciencia es siempre conciencia de algo.",
    },
    {
      type: "info",
      tag: "Intencionalidad",
      title: "Al principio está la relación",
      body: "El movimiento clave: no se deriva el sujeto del objeto ni al revés; al principio está la relación entre ambos, imposible de desconectar, y la intencionalidad es el puente. Donde Kant dejaba inalcanzable la cosa en sí, Husserl lanza su consigna: ir «a las cosas mismas», a los objetos tal como se nos aparecen y se nos dan en la experiencia.",
    },
    {
      type: "short",
      question: "¿Cómo llama Husserl a la estructura de la conciencia que siempre está dirigida hacia un objeto?",
      answers: ["intencionalidad"],
      explain: "La intencionalidad: la conciencia es siempre conciencia de algo, estalla hacia el objeto. Husserl toma el término de Brentano. Es el puente que conecta sujeto y objeto, contra la imagen de la mente como caja cerrada.",
    },
    {
      type: "info",
      tag: "Reducción",
      title: "De la actitud natural a la fenomenológica",
      body: "La reducción fenomenológica es el gesto por el cual uno pasa de la actitud natural —esa en la que damos por sentado, ingenuamente, que el mundo existe— a la actitud fenomenológica, un estado superior en el que reflexionamos sobre los contenidos de la conciencia. Es un método profundamente descriptivo: describir con exactitud cómo se nos dan las cosas.",
    },
    {
      type: "info",
      tag: "Bracketing",
      title: "Poner el mundo entre paréntesis",
      body: "El primer paso es tomar la pregunta «¿existe el mundo?, ¿es real?» y ponerla entre paréntesis: el famoso bracketing. No es dudar ni ser escéptico —eso sería Descartes—: es suspender la pregunta, dejarla a un lado sin borrarla, para concentrarse en describir los objetos tal como se dan a la conciencia pura. (Sus críticos dicen que Husserl nunca la saca del paréntesis.)",
    },
    {
      type: "quiz",
      question: "El «bracketing» fenomenológico consiste en…",
      options: [
        "demostrar con certeza que el mundo externo existe",
        "dudar de todo, como en el método de Descartes",
        "suspender la pregunta por la existencia del mundo",
        "negar que los objetos existan fuera de la mente",
      ],
      answer: 2,
      explain: "Bracketing no es dudar ni negar: es poner la pregunta por la existencia entre paréntesis, dejarla en suspenso para describir con pureza cómo aparecen las cosas a la conciencia. La pregunta sigue ahí; sólo se corrió a un lado.",
    },
    {
      type: "match",
      question: "Uní cada término de la fenomenología con lo que nombra",
      pairs: [
        { left: "Intencionalidad", right: "La conciencia siempre dirigida hacia un objeto" },
        { left: "Ego trascendental", right: "El yo universal y esencial, el mismo para todos" },
        { left: "Bracketing", right: "Suspender la pregunta por la existencia del mundo" },
        { left: "Reducción fenomenológica", right: "El paso de la actitud natural a la fenomenológica" },
        { left: "«Las cosas mismas»", right: "Los objetos tal como se nos aparecen y se dan" },
      ],
      explain: "Las piezas del método: la conciencia alcanza el mundo por la intencionalidad; para verlo con pureza uno hace la reducción, pone entre paréntesis su existencia (bracketing) y se eleva al ego trascendental, para describir «las cosas mismas», los objetos tal como se dan.",
    },
    {
      type: "info",
      tag: "Transparencia",
      title: "El sujeto todo luz",
      body: "Para Husserl el sujeto humano sigue siendo la fuente de todo sentido, y al llegar a la conciencia pura se vuelve absolutamente transparente para sí mismo: todo claridad, nada oculto. Es el contraste exacto con Freud, su alter ego: para Freud lo esencial del yo es lo más oculto, el inconsciente; para Husserl, lo más claro.",
    },
    {
      type: "quiz",
      question: "Frente a Freud, ¿cómo concibe Husserl el fondo del yo?",
      options: [
        "Como algo oculto que se resiste a la conciencia",
        "Como algo absolutamente transparente y claro",
        "Como una ilusión que conviene disolver",
        "Como un mecanismo material y reificado",
      ],
      answer: 1,
      explain: "Son alter egos: para Freud lo esencial del yo es el inconsciente, lo más oculto; para Husserl, al alcanzar la conciencia pura el sujeto se vuelve todo luz, transparente para sí mismo y fuente de todo sentido.",
    },
    {
      type: "info",
      tag: "Cierre",
      title: "Fe en la razón contra la barbarie",
      body: "En 1933 los nazis expulsan a Husserl por «no ario», y él se encierra a clarificar obsesivamente la reducción. Cree que Europa cayó en la barbarie por una pérdida de fe en la razón, y que mostrar que sí se puede alcanzar la verdad absoluta salvaría al mundo. Para él era todo o nada: o la claridad epistemológica pura, o el manicomio. La próxima clase: Heidegger.",
    },
  ],
};
