// Clase 12 (transcripción) — El existencialismo heideggeriano
// App Clase 11. Feed: 'info', 'quiz', 'classify' (comparar), 'match' (conectar), 'short'.
// Tono: resumen fiel de la clase. Preguntas exigentes, con distractores plausibles.
//
// NUMERACIÓN: num (app) = transcript - 1. El archivo se nombra por transcript.
export default {
  num: 11,
  transcript: 12,
  title: "El existencialismo heideggeriano",
  source: "https://www.youtube.com/watch?v=l1jzdqwMePs",
  feed: [
    {
      type: "info",
      tag: "Panorama",
      title: "Heidegger da vuelta el tablero",
      body: "Martin Heidegger, alumno y heredero elegido de Husserl, invierte toda la filosofía moderna. La pregunta primera no es cómo conocer, sino qué significa ser. Y el viejo problema del puente entre sujeto y objeto se disuelve: no hay brecha que cruzar, porque estamos siempre ya en el mundo. Su libro, Ser y tiempo (1927), reescribe la filosofía en un lenguaje propio.",
    },
    {
      type: "info",
      tag: "Biografía",
      title: "El hombre del bosque",
      body: "Nació en 1889 en Meßkirch, un pueblito católico al borde de la Selva Negra, con la que se lo asocia toda la vida. Formado para el sacerdocio, con base en teología y en los griegos antiguos. Hombre del bosque, no de los cafés: esquía y desdeña a los intelectuales urbanos. Como docente hechizaba; Arendt diría: «nadie había podido dar clase como vos, y nadie ha podido desde entonces».",
    },
    {
      type: "info",
      tag: "Husserl",
      title: "Bailar en dos casamientos",
      body: "Husserl había intentado «bailar en dos casamientos a la vez»: objetiva la subjetividad (con el ego trascendental, un yo puro y universal) y a la vez subjetiva la objetividad (no hay objeto sin sujeto). Quiere toda la hondura del sujeto y toda la certeza del objeto, sin renunciar a ninguna. Depositó en el joven Heidegger la esperanza de continuar ese proyecto.",
    },
    {
      type: "quiz",
      question: "¿Qué intenta Husserl al «bailar en dos casamientos a la vez»?",
      options: [
        "Separar de una vez por todas el sujeto del objeto",
        "Unir la hondura del sujeto y la certeza del objeto",
        "Reducir el objeto a una mera ilusión de la mente del sujeto",
        "Renunciar por igual al sujeto y al objeto",
      ],
      answer: 1,
      explain: "Husserl objetiva la subjetividad (el ego trascendental) y subjetiva la objetividad (no hay objeto sin sujeto): quiere la profundidad del sujeto y la firmeza del objeto juntas. Heidegger dirá que eso está mal planteado desde el inicio.",
    },
    {
      type: "info",
      tag: "Ser y tiempo",
      title: "La cabaña y el libro",
      body: "Hacia 1926, en riesgo de perder su puesto por no haber publicado nada, Heidegger se retira a una cabaña en Todtnauberg, en la Selva Negra, y escribe Ser y tiempo. Envuelve el borrador en flores y se lo dedica a Husserl «en amistad y admiración». Aparece en 1927, en un lenguaje filosófico nuevo, poético y casi intraducible, que juega con la gramática y las etimologías del alemán.",
    },
    {
      type: "info",
      tag: "Olvido del ser",
      title: "Todos fueron en la dirección equivocada",
      body: "¿De qué trata el libro? Del ser, como tal. La primera jugada de Heidegger, condescendiente: todos los filósofos olvidaron lo más importante. La filosofía moderna, desde Descartes, se obsesionó con la epistemología —cómo sé qué existe—, y eso «llegó demasiado pronto». Antes de preguntar qué es conocer hay que preguntar qué es ser. Es el Seinsvergessenheit, el olvido del ser.",
    },
    {
      type: "quiz",
      question: "¿Qué le reprocha Heidegger a toda la filosofía moderna?",
      options: [
        "Haber olvidado la pregunta por el ser",
        "Haber abandonado del todo la epistemología",
        "Haberse desentendido de la lógica formal",
        "Haber confiado demasiado en los griegos antiguos",
      ],
      answer: 0,
      explain: "Es el Seinsvergessenheit, el olvido del ser. Desde Descartes la filosofía se preguntó cómo conocemos y olvidó la pregunta primera: qué significa ser. Para Heidegger la ontología precede a la epistemología.",
    },
    {
      type: "info",
      tag: "Ser y ente",
      title: "Sein y Seiendes",
      body: "Una distinción que en alemán es clara y en otras lenguas se pierde. Sein es el ser como tal, incontable: qué significa ser. Ein Seiendes es un ente, contable: los seres humanos, uno, dos, tres. La pregunta clave: ¿qué clase de entes pueden interrogarse por el sentido del ser? El gato no puede, el abejorro no puede. Sólo nosotros: estamos en una posición privilegiada.",
    },
    {
      type: "info",
      tag: "Dasein",
      title: "El «ser-ahí»",
      body: "Heidegger evita «ser humano» y rechaza el lenguaje de «sujeto» y «conciencia». Los reemplaza por Dasein, que literalmente es «ser-ahí» (Da, ahí; Sein, ser), y suele dejarse sin traducir. Nosotros somos Dasein: estamos ahí, en el mundo, y en posición privilegiada porque, a diferencia de los animales o los dinosaurios, podemos preguntar qué significa el ser.",
    },
    {
      type: "quiz",
      question: "¿Por qué el Dasein ocupa una posición «privilegiada»?",
      options: [
        "Porque es inmortal, a diferencia de los animales",
        "Porque puede preguntar qué significa ser",
        "Porque contempla el mundo desde afuera",
        "Porque es un sujeto puro y transparente",
      ],
      answer: 1,
      explain: "Ni el gato ni el abejorro pueden interrogarse por el sentido del ser; sólo el Dasein. Esa capacidad de preguntar por el ser —estando ya dentro de una comprensión previa— es lo que nos distingue.",
    },
    {
      type: "short",
      question: "¿Con qué palabra, que significa «ser-ahí», reemplaza Heidegger al «sujeto» humano?",
      answers: ["Dasein"],
      explain: "Dasein: «ser-ahí» (Da, ahí; Sein, ser). Heidegger rechaza «sujeto» y «conciencia»; el Dasein es el ente que existe ahí, en el mundo, y que puede preguntar por el ser.",
    },
    {
      type: "info",
      tag: "Hermenéutica",
      title: "«Existo, luego pienso»",
      body: "Para preguntar «¿qué es el ser?» ya hay que tener una idea preliminar de lo que significa «ser»: si no, ni siquiera podríamos formular la pregunta. Eso es el círculo hermenéutico: ya estamos adentro. Si Descartes decía «pienso, luego existo» y Husserl «pienso un objeto», Heidegger invierte: existo, luego pienso. La ontología precede a la epistemología.",
    },
    {
      type: "info",
      tag: "Ser-en-el-mundo",
      title: "Siempre ya en el mundo",
      body: "El concepto más radical: estamos siempre ya en el mundo (immer schon in der Welt sein). Por eso no tiene sentido preguntar si el mundo existe. Toda la cuestión sujeto/objeto está mal planteada, porque supone una distancia, un punto fuera del mundo desde el cual mirarlo. Pero no hay afuera ni distancia: estamos dentro e involucrados, haciendo cosas, con otros.",
    },
    {
      type: "quiz",
      question: "¿Cómo «disuelve» Heidegger el problema del puente sujeto-objeto?",
      options: [
        "Construye un puente mucho más firme que el de Husserl",
        "Niega que el objeto exista fuera del sujeto",
        "Muestra que no hay brecha; ya estamos en el mundo",
        "Demuestra la existencia del mundo con certeza",
      ],
      answer: 2,
      explain: "Donde Husserl tendía un puente con la intencionalidad, Heidegger dice que no hace falta puente porque no hay brecha: el Dasein está siempre ya en el mundo. La pregunta sujeto/objeto estaba mal planteada.",
    },
    {
      type: "info",
      tag: "Estar-arrojado",
      title: "Geworfenheit",
      body: "Esta condición de estar siempre ya en el mundo la nombra con una palabra magnífica: Geworfenheit, la condición de arrojado (thrownness). Hay algo violento en ello: estamos siempre ya arrojados a un tiempo y un lugar que no elegimos. No hay un «antes» ni un «afuera»; nos encontramos ya lanzados a una existencia que no empezamos.",
    },
    {
      type: "info",
      tag: "Zuhanden",
      title: "A la mano y ante los ojos",
      body: "Primero y las más de las veces no contemplamos las cosas: las usamos. No «vemos» el martillo, los anteojos, la taza: los manejamos. Son zuhanden, «a la mano». Sólo cuando algo falla —el martillo se rompe— pasan a ser vorhanden, «ante los ojos», objetos de contemplación. Recién vemos de verdad el martillo cuando se rompe: un modo secundario y deficiente de relación.",
    },
    {
      type: "classify",
      question: "¿Cada situación es «a la mano» (zuhanden) o «ante los ojos» (vorhanden)?",
      groups: ["A la mano", "Ante los ojos"],
      items: [
        { text: "Usás el martillo sin prestarle atención", group: 0 },
        { text: "El martillo se rompe y recién ahí lo mirás", group: 1 },
        { text: "Escribís con la lapicera sin pensar en ella", group: 0 },
        { text: "Contemplás la lapicera como un objeto aparte", group: 1 },
        { text: "La silla te sostiene mientras hacés otra cosa", group: 0 },
        { text: "Algo falla y la cosa se vuelve objeto de examen", group: 1 },
      ],
      explain: "Primero y las más de las veces las cosas son zuhanden, «a la mano»: las usamos sin contemplarlas. Sólo cuando algo falla pasan a ser vorhanden, «ante los ojos», objetos de contemplación. Para Heidegger, ese modo contemplativo es secundario y deficiente.",
    },
    {
      type: "info",
      tag: "Inautenticidad",
      title: "El «se» impersonal (das Man)",
      body: "Una vez arrojados, tenemos que decidir cómo ser. El primer modo, en el que vivimos casi siempre, es inauténtico: conformismo, ceder la carga de decidir a «lo que se hace». Es el das Man, el impersonal «se»/«uno»: lo que hace la gente, nadie y todos a la vez. El Dasein caído (verfallen) se pierde en la habladuría (Gerede) sobre nada. Es alienante, pero reconfortante.",
    },
    {
      type: "info",
      tag: "Autenticidad",
      title: "Ser-para-la-muerte",
      body: "El otro modo, menos deficiente, es la autenticidad. No es fría y técnica como en Husserl: es tensa, emocional y oscura. Se liga a la finitud: somos seres finitos, siempre ya arrojados y siempre ya avanzando hacia nuestra propia muerte. Nuestra condición es Sein zum Tode, ser-para-la-muerte. Vivir con autenticidad es mirar la muerte con los ojos bien abiertos; la inautenticidad es huir de esa conciencia.",
    },
    {
      type: "info",
      tag: "Angustia",
      title: "Angustia, miedo y «no estar en casa»",
      body: "Confrontar el ser-para-la-muerte es aterrador. Ahí surge la Angst, la angustia. La distinción es clave: el miedo toma un objeto (a las arañas, a los aviones); la angustia no tiene objeto —aquello de lo que se angustia es la nada misma, el futuro inevitable de la existencia finita—. De ahí la Unheimlichkeit: literalmente, «no estar en casa» en el mundo.",
    },
    {
      type: "quiz",
      question: "¿En qué se distingue la angustia (Angst) del miedo?",
      options: [
        "La angustia es siempre más intensa que el miedo común",
        "El miedo es racional y la angustia irracional",
        "El miedo tiene un objeto; la angustia, la nada",
        "La angustia se cura con el tiempo y el miedo no",
      ],
      answer: 2,
      explain: "El miedo, como el cogito, toma un objeto. La angustia no: aquello de lo que se angustia es la nada misma, nuestra propia finitud. Por eso deja al Dasein en la Unheimlichkeit, el no-estar-en-casa en el mundo.",
    },
    {
      type: "short",
      question: "¿Cómo llama Heidegger al pavor sin objeto, ante la nada, que sacude al Dasein?",
      answers: ["Angst", "angustia"],
      explain: "Angst (angustia): a diferencia del miedo, no tiene objeto; su «objeto» es la nada, nuestra finitud. Nos deja en la Unheimlichkeit, el no-estar-en-casa en el mundo.",
    },
    {
      type: "info",
      tag: "Resolución",
      title: "La muerte que individualiza",
      body: "La muerte nos individualiza, porque cada uno muere solo: es nuestro único momento de auténtica «mi-idad» (Jemeinigkeit), lo que nos pertenece sólo a nosotros. Ser sacudidos por la angustia a estar solos frente a nuestra propia nada es miserable, casi heroico, pero también empodera: puede llevarnos a la resolución (Entschlossenheit) de asumir la responsabilidad de nuestras elecciones. Ese será el gran tema del existencialismo.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es del modo auténtico o del inauténtico?",
      groups: ["Auténtico", "Inauténtico"],
      items: [
        { text: "Encara la propia muerte con los ojos abiertos", group: 0 },
        { text: "Cede la decisión a «lo que se hace»", group: 1 },
        { text: "Asume la responsabilidad de sus elecciones", group: 0 },
        { text: "Se pierde en la habladuría y lo trivial", group: 1 },
        { text: "La angustia lo sacude a la resolución", group: 0 },
        { text: "Se disuelve en el «se» impersonal (das Man)", group: 1 },
      ],
      explain: "El modo inauténtico es conformismo: ceder la decisión al «uno» (das Man), huir en la habladuría, ir con la corriente. El auténtico encara la finitud —el ser-para-la-muerte— y de esa angustia surge la resolución de asumir las propias elecciones. Heidegger dice no juzgar, pero es claro cuál admira.",
    },
    {
      type: "match",
      question: "Uní cada término de Ser y tiempo con lo que nombra",
      pairs: [
        { left: "Dasein", right: "El «ser-ahí»: el ente que puede preguntar por el ser" },
        { left: "Ser-en-el-mundo", right: "Estamos siempre ya en el mundo, sin distancia ni afuera" },
        { left: "Geworfenheit", right: "Estar arrojados a un tiempo y lugar que no elegimos" },
        { left: "Das Man", right: "El «se» impersonal: vivir según lo que se hace" },
        { left: "Sein zum Tode", right: "Ser-para-la-muerte: existir avanzando hacia la nada" },
      ],
      explain: "El vocabulario de Ser y tiempo: el Dasein está siempre ya arrojado (Geworfenheit) al mundo (ser-en-el-mundo); primero y las más de las veces vive inauténtico, disuelto en el «se» (das Man), hasta que la angustia ante el ser-para-la-muerte lo sacude a la autenticidad.",
    },
    {
      type: "info",
      tag: "Cierre",
      title: "¿Queda todavía un sujeto?",
      body: "El Dasein reemplaza al ego trascendental y al sujeto. Pero mientras el ego de Husserl era radicalmente transparente, el Dasein nunca lo es: siempre está en algo, huyendo, tentado por la inautenticidad, con partes ocultas para sí. Ahí Heidegger está más cerca de Freud, es un «maestro de la sospecha». Y deja una pregunta que quedará abierta de aquí en más: sin distancia entre sujeto y objeto, ¿queda todavía un sujeto?",
    },
  ],
};
