export default {
  num: 2,
  transcript: 3,
  title: "El legado del Romanticismo",
  source: "https://www.youtube.com/watch?v=-xeudCcrF8o",
  feed: [
    {
      type: "info",
      title: "Recapitulando",
      body: "El ánimo de la Ilustración parte de la idea de un tiempo progresivo: avanzamos hacia adelante, y eso es bueno; nos movemos hacia cosas mejores, aprendemos cada vez más sobre el mundo, y cuanto más aprendemos, más construimos sobre nuestro conocimiento. A través del uso de la razón alcanzamos una comprensión mayor, y con esa razón vamos a poder hacer del mundo un lugar mejor.",
    },
    {
      type: "info",
      continues: true,
      title: "Recapitulando",
      body: "Es un movimiento profundamente humanista y centrado en el ser humano: somos especiales porque tenemos razón. Tenemos derechos naturales, y los merecemos, porque somos criaturas dotadas de razón, porque somos humanos y no hormigas, mariposas ni orugas. Los pensadores ilustrados (Hobbes, Locke, Rousseau) diferían sobre cómo se pasa del estado de naturaleza al estado de cultura o civilización, pero estaban unidos por la creencia en la posibilidad de algún orden racional y de una comprensión del mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "Recapitulando",
      body: "El modelo de la Ilustración era que la vida humana —la ciencia, el amor, el arte, la política, el comportamiento social— puede entenderse, en el fondo, según el modelo de las ciencias naturales.  La idea es que, mediante la observación científica cuidadosa, uno puede descubrir cómo funcionan las cosas: conocimiento empírico, observar algo concreto que ocurre en tiempo real, tomar notas, calcular, descubrir los patrones, y así empujar el conocimiento un poco más lejos.",
    },
    {
      type: "info",
      title: "El ánimo ilustrado: clasificación, razón, optimismo",
      body: "De aquí se siguen varias creencias:\n• Todas las preguntas pueden, en algún momento, por alguien, en algún lugar y de algún modo, ser respondidas.\n• El conocimiento es posible y deseable. La verdad está ahí afuera: existe algo así como una verdad objetiva, y puede descubrirse, del mismo modo en que Newton descubrió la ley de la gravedad.\n• El mundo es en esencia comprensible, aunque todavía no hayamos armado todas las piezas del rompecabezas.",
    },
    {
      type: "info",
      continues: true,
      title: "El ánimo ilustrado: clasificación, razón, optimismo",
      body: "También estaba la idea de una armonía de intereses: a medida que adquirimos más conocimiento y comprensión del mundo, podemos moldearlo de modo que sea mejor para todos; los derechos del individuo y los del colectivo pueden reconciliarse; las cosas buenas pueden ir juntas. Y hay un sentido implícito de que la razón conduce a la virtud: como somos seres dotados de razón, razonablemente vamos a querer comportarnos bien.",
    },
    {
      type: "quiz",
      question: "La «armonía de intereses» que supone la Ilustración significa que…",
      options: [
        "el interés propio hay que sacrificarlo al del colectivo",
        "los ideales verdaderos chocan entre sí y hay que elegir",
        "lo que es bueno para uno puede ser bueno para todos",
        "el interés de cada uno es lo único que se puede conocer",
      ],
      answer: 2,
      explain: "El ánimo ilustrado supone que las cosas buenas van juntas: a medida que comprendemos mejor el mundo podemos moldearlo para que sea mejor para todos, y los derechos del individuo se reconcilian con los del colectivo. Va con un supuesto implícito: como somos seres dotados de razón, razonablemente vamos a querer comportarnos bien. El Romanticismo va a negar exactamente esto.",
    },
    {
      type: "info",
      title: "El Romanticismo como rebelión",
      body: "El Romanticismo entra como una rebelión contra ese ánimo. A veces se lo llama Gegenaufklärung, la contra-Ilustración. Como todo en la vida, ante cualquier cosa que domina surge una rebelión en contra. Si los géneros ilustrativos de la Ilustración son la teoría del contrato social y la Encyclopédie de Diderot, los del Romanticismo van a ser la poesía y, en cierta medida, el teatro.",
    },
    {
      type: "info",
      continues: true,
      title: "El Romanticismo como rebelión",
      body: "Si el centro de la Ilustración es Francia, el centro del Romanticismo va a ser Alemania. La idea de fondo es la del desencanto del mundo —lo que Weber llama Entzauberung—: el mundo ya no es mágico, los reyes no gobiernan por derecho divino, no hay fuerzas sobrenaturales que otorguen gracia o castigo. Somos seres humanos que, de manera sobria y racional, usamos la mente para comprender el mundo.",
    },
    {
      type: "info",
      continues: true,
      title: "El Romanticismo como rebelión",
      body: "Y resulta que ese ánimo, alegre y optimista al menos para algunos, buena parte del tiempo es emocionalmente insatisfactorio. Ese es el problema del desencanto —y, como veremos más adelante, también el problema del liberalismo—: toda esa racionalidad y la suposición de una convergencia de intereses entre el individuo y el colectivo terminan resultando insatisfactorias para el corazón.",
    },
    {
      type: "info",
      title: "Las palabras clave del Romanticismo",
      body: "Si las palabras clave de la Ilustración eran civilización, razón, progreso, las del Romanticismo van a ser pasión, belleza, anhelo, creación, voluntad. El Romanticismo es una reacción contra las ciencias duras como modelo, contra el racionalismo como virtud incuestionable. Es un rechazo de la idea de que todas las preguntas pueden responderse, de que todas las virtudes son compatibles entre sí, de que los intereses pueden armonizarse.",
    },
    {
      type: "info",
      continues: true,
      title: "Las palabras clave del Romanticismo",
      body: "Hay un giro hacia el valor precioso del alma individual, que muchas veces estará en conflicto con otras almas individuales. La verdad no es algo que se descubra afuera mediante la experimentación científica: es algo que se produce en nuestra alma, un acto de creación.",
    },
    {
      type: "classify",
      question: "¿Cada rasgo es de la Ilustración o del Romanticismo?",
      groups: [
        "Ilustración",
        "Romanticismo",
      ],
      items: [
        { text: "La verdad está afuera y se descubre observando", group: 0 },
        { text: "La verdad se produce en el alma, es una creación", group: 1 },
        { text: "El modelo son las ciencias duras", group: 0 },
        { text: "El modelo son la poesía y el teatro", group: 1 },
        { text: "Palabras clave: civilización, razón, progreso", group: 0 },
        { text: "Palabras clave: pasión, belleza, anhelo, voluntad", group: 1 },
      ],
      explain: "El Romanticismo es una rebelión punto por punto, a veces llamada Gegenaufklärung, la contra-Ilustración: si el centro de la Ilustración es Francia, el suyo es Alemania; si el género ilustrado es la Encyclopédie, el suyo es la poesía. Rechaza que todas las preguntas tengan respuesta, que todas las virtudes sean compatibles y que los intereses puedan armonizarse.",
    },
    {
      type: "info",
      title: "El bosque, la oscuridad, la tormenta",
      body: "Hay un gran idealismo en torno a la naturaleza y a internarse en el bosque. Si la metáfora de la Ilustración está inscripta en la propia palabra —la luz, el siglo de las luces—, lo que los románticos van a amar es la oscuridad, y especialmente el mal tiempo: la niebla, las tormentas eléctricas, los rayos dramáticos, la lluvia cayendo en el bosque, refugiarse en una cueva. Bosques oscuros, provincianos, lejanos: de nuevo, es un ánimo. El Romanticismo va a idealizar la naturaleza.",
    },
    {
      type: "info",
      title: "Rousseau, figura de transición",
      body: "Ya hay figuras de transición, y Rousseau es la principal: según cuál Rousseau se lea, es una figura por excelencia de la Ilustración o del Romanticismo. Si se lee El contrato social, es un pensador ilustrado crucial, alguien que trabaja con Diderot en la Encyclopédie. Si se leen sus Confesiones —y les aseguro que tiene mucho que confesar; era un tipo bastante despreciable en varios sentidos—, el tono es marcadamente romántico. Sus ideas sobre el gobierno son las de un filósofo ilustrado; su autodescripción y su temperamento son mucho más románticos.",
    },
    {
      type: "info",
      title: "El modelo de la nostalgia",
      body: "Su idealización y su nostalgia por volver al estado de naturaleza se convierten en el modelo de la nostalgia en general. La nostalgia es el anhelo por algo del pasado que en realidad nunca existió: eso que imaginás que habría sido maravilloso, que creés que estuvo y se perdió, pero que en verdad recreaste en tu mente. Hay una palabra alemana elegante que usan los románticos, Sehnsucht: ese anhelo que se convierte en una cosa en sí misma. El objeto, en cierto sentido, importa menos; lo que cuenta es la emoción del anhelo por aquello que nunca podrá alcanzarse del todo.",
    },
    {
      type: "quiz",
      question: "La nostalgia romántica, ese Sehnsucht, es el anhelo de…",
      options: [
        "un pasado que en realidad nunca existió",
        "un futuro mejor que la razón va a construir",
        "una patria perdida que se puede recuperar",
        "un objeto concreto que alguien te quitó",
      ],
      answer: 0,
      explain: "La nostalgia es el anhelo por algo del pasado que nunca existió: lo imaginás maravilloso, creés que estuvo y se perdió, pero en verdad lo recreaste en tu mente. Los románticos le dan un nombre alemán, Sehnsucht, y ahí está el giro: el anhelo se vuelve una cosa en sí misma. El objeto importa menos que la emoción de anhelar aquello que no puede alcanzarse del todo.",
    },
    {
      type: "info",
      title: "\"Difícil de tratar\"",
      body: "Rousseau cae en conflictos dramáticos con casi todo el mundo. Tiene ese intercambio de cartas con Voltaire en el que su carta es, básicamente, \"te odio, te odio, te odio\". La gente o ama o detesta a Rousseau, pero es un personaje fascinante. Se vuelve inspiración de comunas naturalistas: su idea de volver a la naturaleza como forma de escapar de la alienación respecto de uno mismo —uno quisiera poder volver, pero no hay manera de volver—. ¿Vas a ir a vivir como un salvaje, solo en el bosque? Él no lo hace; solo habla de ello.",
    },
    {
      type: "quiz",
      question: "Rousseau es figura de transición porque…",
      options: [
        "escribió primero como romántico y después como ilustrado",
        "su política es ilustrada y su temperamento romántico",
        "abandonó la filosofía para irse a vivir al bosque",
        "sus dos libros sostienen la misma tesis con otro tono",
      ],
      answer: 1,
      explain: "Según cuál Rousseau leas, es una figura por excelencia de la Ilustración o del Romanticismo: El contrato social es de un pensador ilustrado que colabora con Diderot en la Encyclopédie, y las Confesiones tienen un tono marcadamente romántico. Sus ideas sobre el gobierno son ilustradas; su autodescripción y su temperamento, no. Y al bosque nunca se fue: sólo hablaba de ello.",
    },
    {
      type: "info",
      title: "Ser y devenir; la piedad natural",
      body: "Para Rousseau, dos cosas distinguen al hombre de las demás criaturas: la libre agencia humana y esta apertura al devenir. Si la Ilustración trata de comprender cómo son las cosas —qué significa que el mundo sea de cierta manera, si podemos descubrir las leyes de la física—, los románticos van a decir: no se trata del ser, sino del devenir. Somos seres singularmente indeterminados, seres que se autocrean; el devenir nos da una enorme agencia.",
    },
    {
      type: "info",
      continues: true,
      title: "Ser y devenir; la piedad natural",
      body: "Rousseau tiene además su palabra francesa para la piedad o compasión: el hombre como criatura sensible que sentía empatía natural por los demás en ese estado de naturaleza idealizado que nadie vio ni experimentó jamás —hasta que llegan la sociedad y la propiedad y nos convierten en materialistas superficiales, esnobs y ostentosos, vanidosos, egocéntricos y llenos de amor propio—.",
    },
    {
      type: "info",
      title: "La virtud de la autenticidad",
      body: "Una de las cosas que los románticos toman de Rousseau es la virtud de la autenticidad, un gran tema romántico. El Primer discurso plantea que el burgués es siempre otro y nunca él mismo: vivimos en un mundo donde competimos por lucirnos, donde el amor propio, el orgullo, la vanidad, la presunción y el egocentrismo son la verdadera causa de nuestro descontento.",
    },
    {
      type: "info",
      continues: true,
      title: "La virtud de la autenticidad",
      body: "Responsable de ello es la sociedad, el hecho de que ya no vivimos en el estado de naturaleza: eso creó esta corrupción, este amor propio. No es natural; es artificial, una vanidad nacida de la mirada de los demás. La propiedad es corruptora: nos lleva a la competencia y a la vanidad. La sociedad es falsificadora: nos hace fingir ser distintos de quienes somos. No hay virtud sin autenticidad, y la autenticidad exige un retiro de la sociedad.",
    },
    {
      type: "info",
      continues: true,
      title: "La virtud de la autenticidad",
      body: "Citas del Discurso sobre las ciencias y las artes de Rousseau: \"Uno ya no se atreve a parecer lo que es; y bajo esa restricción perpetua, los hombres que forman el rebaño llamado sociedad, puestos en circunstancias similares, actuarán todos de manera similar, salvo que motivos más poderosos los inclinen de otro modo. Así, nunca se sabrá realmente con quién se está tratando.\"",
    },
    {
      type: "quiz",
      question: "Para Rousseau, lo que corrompe al burgués es…",
      options: [
        "la falta de educación en el uso de la razón",
        "una maldad que trae del estado de naturaleza",
        "el exceso de piedad natural hacia los otros",
        "la mirada de los demás, que lo obliga a fingir",
      ],
      answer: 3,
      explain: "El burgués es siempre otro y nunca él mismo: competimos por lucirnos, y el amor propio, la vanidad y la presunción nacen de la mirada ajena. No es natural sino artificial, obra de la sociedad y de la propiedad. De ahí la virtud que los románticos heredan: no hay virtud sin autenticidad, y la autenticidad exige un retiro de la sociedad.",
    },
    {
      type: "info",
      title: "Kant: figura de las dos corrientes",
      body: "Kant también es una figura crucial tanto de la Ilustración como del Romanticismo, según en qué Kant se ponga el foco. Kant nos da la mejor definición de Ilustración, en su ensayo ¿Qué es la Ilustración? (que obtuvo el segundo premio en el concurso, y que leen esta semana): Sapere aude, atrévete a saber, ten el valor de usar tu propia razón.",
    },
    {
      type: "info",
      title: "La Crítica de la razón pura (1781)",
      body: "La Crítica de la razón pura trata de los límites de la razón humana, pero no de un modo pesimista: trata de lo que podemos y no podemos conocer racionalmente. ¿Qué podemos comprender del mundo? ¿Existe el mundo con independencia de cómo lo percibimos? ¿Cómo sé que esta botella de agua existe y no es una proyección de mi imaginación? ¿Cómo sé cómo es el mundo con independencia de la mente, si nunca puedo salir de mi mente?",
    },
    {
      type: "info",
      continues: true,
      title: "La Crítica de la razón pura (1781)",
      body: "• El realismo decía: sí, el mundo es real, existe, y nuestra mente debe conformarse a lo que él es.\n• El idealismo decía: no, todo está dentro de nuestra cabeza; quién sabe qué ocurre afuera, no hay manera de salir.\n\nKant llega y negocia un compromiso. Dice: sí, el mundo es real, creo que hay un mundo en sí mismo fuera de las estructuras de nuestra mente —su famosa 'Ding an sich', la cosa en sí—, pero no tenemos acceso directo a ella.",
    },
    {
      type: "info",
      continues: true,
      title: "La Crítica de la razón pura (1781)",
      body: "Como no podemos salir de nuestra propia cabeza, solo podemos comprender la realidad tal como se conforma a las estructuras de nuestra mente. La 'Ding an sich', en cierto sentido, es un concepto vacío: el mundo tal como no es conocido. Solo tenemos acceso al mundo tal como se nos aparece.",
    },
    {
      type: "info",
      continues: true,
      title: "La Crítica de la razón pura (1781)",
      body: "Kant negocia también el compromiso entre racionalismo y empirismo (que podemos dejar entre paréntesis por ahora): recibimos datos sensoriales empíricos del mundo —hay una receptividad—, pero también imponemos espontáneamente sobre esos datos las estructuras de nuestra conciencia, en particular el tiempo, el espacio y la causalidad, que están como \"cableados\" de fábrica",
    },
    {
      type: "match",
      question: "Uní cada posición con lo que sostiene sobre el mundo exterior",
      pairs: [
        { left: "Realismo", right: "El mundo es real y nuestra mente debe conformarse a él" },
        { left: "Idealismo", right: "Todo está en nuestra cabeza y no hay manera de salir" },
        { left: "Kant", right: "Hay una cosa en sí, pero sólo accedemos a cómo se aparece" },
      ],
      explain: "Kant negocia un compromiso entre las dos: cree que hay un mundo en sí, su Ding an sich, pero también que no tenemos acceso directo a él porque no podemos salir de nuestra propia cabeza. Sólo comprendemos la realidad tal como se conforma a las estructuras de nuestra mente, así que la cosa en sí es casi un concepto vacío: el mundo tal como no es conocido.",
    },
    {
      type: "quiz",
      question: "En el compromiso de Kant entre racionalismo y empirismo, la mente…",
      options: [
        "recibe datos y les impone tiempo, espacio y causalidad",
        "recibe datos y los registra tal como llegan del mundo",
        "produce sus ideas sin necesidad de datos sensoriales",
        "deduce las leyes de la física por pura lógica interna",
      ],
      answer: 0,
      explain: "Hay receptividad —recibimos datos sensoriales empíricos del mundo— y a la vez espontaneidad: imponemos sobre esos datos las estructuras de nuestra conciencia, en particular el tiempo, el espacio y la causalidad, que vienen «cableadas» de fábrica. Ni el empirismo puro, que sólo registra, ni el racionalismo puro, que deduce sin mirar.",
    },
    {
      type: "info",
      title: "Lo que los románticos toman de Kant: la filosofía moral",
      body: "La filosofía moral kantiana dice que, para que haya moralidad, tiene que haber libre albedrío. Sin libre albedrío humano no podemos hablar de ética. Como no podemos demostrar el libre albedrío, pero lo necesitamos, lo vamos a tener que postular, dice Kant. Dejamos de intentar probarlo y digamos que está ahí. (Y ya que estamos, digamos también que Dios existe.) Lo importante es que solo un individuo con libre albedrío puede tomar decisiones morales.",
    },
    {
      type: "info",
      title: "El deber, la intención, el imperativo categórico",
      body: "La moral kantiana es, en el fondo, simple: actuar moralmente es actuar por sentido del deber moral, y no solo según lo que a uno le apetece. Hay que templar el hecho de que quizás tengas ganas de robar algo, pero eso no estaría bien. Si no estás seguro de si actuás por gusto o por deber, hay una pregunta de prueba que podés hacerte: ¿qué pasaría si todos actuaran según el principio con el que estoy por actuar? Si la respuesta es \"sería un desastre\", entonces no es algo bueno de hacer. Esa es una versión del imperativo categórico.",
    },
    {
      type: "info",
      continues: true,
      title: "El deber, la intención, el imperativo categórico",
      body: "Lo que importa para Kant son las intenciones. Actuar moralmente es actuar por sentido del deber, hacer lo que uno sabe que es correcto. Ahora bien, podés actuar con intenciones moralmente puras y aun así provocar un desastre. Kant dice: no es tu culpa. Una vez que actuás, tus acciones entran en complejas redes de causalidad y sobre eso no podés hacer nada. Para evaluar moralmente una acción, lo que cuenta es la intención, la voluntad. Los románticos van a tomar esta idea de la voluntad y a llevarla al extremo.",
    },
    {
      type: "quiz",
      question: "Si actuás por deber y de todos modos provocás un desastre, para Kant…",
      options: [
        "la acción es inmoral: contaban las consecuencias",
        "hay que repararlo antes de juzgar la intención",
        "la acción sigue siendo moral: contaba la intención",
        "no se puede evaluar moralmente lo que hiciste",
      ],
      answer: 2,
      explain: "El camino al infierno está empedrado de buenas intenciones, y Kant dice: no es tu culpa. Una vez que actuás, tus acciones entran en redes de causalidad que no controlás. Lo que se evalúa es la voluntad de actuar por sentido del deber, y la prueba es el imperativo categórico: ¿qué pasaría si todos actuaran según el principio con el que estoy por actuar? Los románticos van a llevar esa primacía de la voluntad al extremo.",
    },
    {
      type: "info",
      title: "Dignidad, libertad y voluntad",
      body: "Para Kant, libertad y moralidad se definen mutuamente; todo gira en torno a los motivos. La moralidad no puede hallarse en nada exterior a la voluntad humana. Esto atañe también a la dignidad humana: no es solo la razón la que nos da dignidad, sino el hecho de que tenemos libre albedrío. De ahí su famoso principio moral fundamental: tratar siempre a la otra persona como un sujeto, como un agente, y no como un objeto, no como una cosa. Y su célebre definición: Todo lo que puede ser reemplazado por otra cosa de valor equivalente tiene un precio; aquello que está por encima de todo precio y no admite equivalente tiene dignidad.",
    },
    {
      type: "match",
      question: "Repaso: uní cada término de Kant con lo que nombra",
      pairs: [
        { left: "Sapere aude", right: "Atrévete a saber: usá tu propia razón" },
        { left: "Ding an sich", right: "La cosa en sí, el mundo tal como no lo conocemos" },
        { left: "Libre albedrío", right: "No se puede demostrar, pero hay que postularlo" },
        { left: "Imperativo categórico", right: "¿Y si todos actuaran según ese principio?" },
        { left: "Dignidad", right: "Lo que no admite equivalente ni reemplazo" },
      ],
      explain: "Los cinco están en la clase por razones distintas: sapere aude es la definición de Ilustración, la Ding an sich el límite de la epistemología, y los otros tres el andamiaje de la filosofía moral. Y ahí está la bisagra de la clase: la Ilustración toma de Kant su epistemología, y los románticos su filosofía moral, construida en cierto sentido de manera opuesta.",
    },
    {
      type: "info",
      title: "El legado kantiano en el Romanticismo: la primacía de la voluntad",
      body: "El Romanticismo va a dedicar mucho tiempo a hablar de la necesidad de actuar, de la creación como imperativo existencial: este devenir aquello en lo que podemos convertirnos. El destino, en cierto sentido, importa menos que el acto mismo de creación. La verdad no es necesariamente algo que se halla o se comprende: es algo que se crea; no algo que descubrís en un laboratorio, sino algo que producís. El modelo es el arte, no la ciencia.",
    },
    {
      type: "info",
      title: "Del cogito al volo",
      body: "Los románticos toman el cogito ergo sum cartesiano —\"pienso, luego existo\"— y lo contraponen con \"quiero/deseo, luego existo\". En lugar de fundar la subjetividad en la cognición, en el pensar, la fundan en el deseo, en la voluntad. Distintas maneras de contraponer razón y pasión: no es cogito ergo sum, es volo ergo sum.",
    },
    {
      type: "info",
      continues: true,
      title: "Del cogito al volo",
      body: "Fichte, discípulo de Kant, dice: ante la sola mención de la palabra \"libertad\", mi corazón se abre y florece; ante la palabra \"necesidad\", se contrae dolorosamente. Para él, ser libre no es nada; devenir libre es el cielo. Todo gira en torno al devenir, al deseo.",
    },
    {
      type: "quiz",
      question: "Pasar del cogito al volo significa fundar la subjetividad en…",
      options: [
        "el pensamiento, no en la experiencia sensible",
        "el deseo y la voluntad, no en el pensamiento",
        "la razón compartida, no en el alma individual",
        "el cuerpo y sus sensaciones, no en la mente",
      ],
      answer: 1,
      explain: "Los románticos toman el cogito ergo sum cartesiano y lo contraponen con volo ergo sum: quiero, deseo, luego existo. Es la contraposición de razón y pasión llevada al fundamento mismo del sujeto. Fichte lo dice sin rodeos: ser libre no es nada, devenir libre es el cielo. Todo gira alrededor del devenir y del deseo.",
    },
    {
      type: "info",
      title: "Consecuencias y rasgos del Romanticismo",
      body: "De aquí surgen: el enorme valor de la sinceridad; el motivo como más importante que la consecuencia; el imperativo de no traicionar jamás los propios ideales a ningún costo. Los ideales chocan; a veces dos hombres aman a la misma mujer y deben batirse a duelo, y uno debe morir, porque la tragedia es endémica a la condición humana. Ese es el momento romántico por excelencia: lo importante es no traicionar tus ideales.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "Nota al margen sobre el \"idealismo\". Hay un idealismo romántico —el imperativo de actuar y crear según tus ideales, de vivir auténticamente conforme a ellos—. Cuando lleguemos a Hegel y Marx, hablaremos del idealismo en otro sentido: como aquello que pertenece al reino de lo metafísico, por oposición a lo concreto y empírico. Conviene anotar esa distinción.",
    },
    {
      type: "classify",
      question: "¿Cada uso de «idealismo» es el romántico o el metafísico?",
      groups: [
        "Romántico",
        "Metafísico",
      ],
      items: [
        { text: "El imperativo de actuar y crear según tus ideales", group: 0 },
        { text: "Vivir auténticamente conforme a lo que uno cree", group: 0 },
        { text: "Estar dispuesto a sacrificarse por un ideal", group: 0 },
        { text: "Lo que pertenece al reino de lo metafísico", group: 1 },
        { text: "Lo que se opone a lo concreto y lo empírico", group: 1 },
        { text: "El sentido que va a importar con Hegel y Marx", group: 1 },
      ],
      explain: "La clase se detiene a marcar esta distinción porque las dos acepciones van a convivir en el curso. El idealismo romántico es una ética: vivir y crear según tus ideales, no traicionarlos a ningún costo. El idealismo metafísico es una tesis sobre qué hay: lo que pertenece al reino de las ideas por oposición a lo concreto y empírico. Con Hegel y Marx sólo va a importar el segundo.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "La emoción debe ser directa y auténtica, lo que a menudo significa que es violenta. Hay anhelos que no pueden justificarse racionalmente. Las personas son irreductiblemente singulares, únicas; cada alma individual es preciosa. Johann Georg Hamann, amigo de Kant y de Herder, dice que esas clasificaciones y principios de ordenamiento que nos llegan de la Ilustración científica carecen de sentido, porque los seres humanos son irreductiblemente únicos y singulares. Lo primario no es necesariamente que anhelemos paz, armonía y contento: lo primordial es este anhelo de intensidad, de pasión, de creación violenta.",
    },
    {
      type: "info",
      continues: true,
      title: "Consecuencias y rasgos del Romanticismo",
      body: "Recuerden la crítica de Goethe —el gran poeta romántico alemán— a Moses Mendelssohn (que ganó el primer premio en aquel concurso): dice que trata la belleza como el entomólogo trata a las mariposas —la capturás, la ponés bajo el vidrio, la analizás, y entonces todo el color se escurre y todo lo que era espectacular queda como muerto por tu racionalismo científico—.",
    },
    {
      type: "info",
      title: "Consecuencias: sacrificio, poesía, lo sublime",
      body: "Hay que estar dispuesto a sacrificarse por un ideal, con esa fetichización del motivo y ese desprecio por las consecuencias; como pueden imaginar, esto puede desembocar en consecuencias desastrosas. Está la noción de la poesía como expresión del alma, como expresión de lo que no puede expresarse, de la belleza y el tormento; la idea de lo sublime, aquello demasiado precioso y bello como para ser puesto en palabras.",
    },
    {
      type: "info",
      title: "Del Romanticismo al nacionalismo",
      body: "Así como del ánimo ilustrado obtenemos el liberalismo, del Romanticismo vamos a obtener el nacionalismo. Es una historia mucho más larga, pero la versión breve es: así como los individuos tienen almas irreductibles, también las naciones tienen almas irreductibles. Buena parte de esto viene del filósofo romántico alemán Johann Gottfried Herder y sus doctrinas del expresionismo, de la pertenencia y de la incompatibilidad de los verdaderos ideales. Los hombres existen para expresarse, y la expresión se transmite mediante la palabra. Lo especialmente importante de las naciones, para Herder, era la lengua: las palabras que una persona comparte con otras son un vínculo especial.",
    },
    {
      type: "quiz",
      question: "El nacionalismo romántico de Herder parte de la idea de que…",
      options: [
        "las naciones se forman por un contrato entre iguales",
        "una nación vale por el territorio que logra defender",
        "la razón universal borra las diferencias entre pueblos",
        "las naciones tienen alma propia, como los individuos",
      ],
      answer: 3,
      explain: "Así como del ánimo ilustrado sale el liberalismo, del Romanticismo sale el nacionalismo: si cada alma individual es irreductible, también lo es la de cada nación. Herder lo apoya en sus doctrinas del expresionismo y de la pertenencia: los hombres existen para expresarse, la expresión se transmite mediante la palabra, y por eso la lengua compartida es el vínculo decisivo.",
    },
    {
      type: "info",
      title: "La Revolución Francesa y el Terror",
      body: "Una manera de entender la Revolución Francesa es que el Terror es el momento en que la Ilustración se convierte en Romanticismo: lo que empezó como un intento ilustrado y racional de implementar algo parecido al liberalismo y la Declaración de los Derechos del Hombre se transforma en una orgía de sed de sangre durante el Terror (1793–1794).",
    },
    {
      type: "quiz",
      question: "Leer el Terror como el momento en que la Ilustración se vuelve Romanticismo quiere decir que…",
      options: [
        "los revolucionarios eran románticos desde el principio",
        "un proyecto racional termina en una orgía de sangre",
        "la Declaración de Derechos era un texto romántico",
        "el Romanticismo alemán provocó la Revolución francesa",
      ],
      answer: 1,
      explain: "Lo que empezó como un intento ilustrado y racional de implementar el liberalismo y la Declaración de los Derechos del Hombre se transforma en el Terror de 1793-94. No es que los actores cambiaran de bando: es que la fetichización del motivo y el desprecio por las consecuencias —rasgos románticos— se apoderan de un proyecto que se pensaba puramente racional.",
    },
    {
      type: "match",
      question: "Repaso final: uní cada figura con lo que aporta al Romanticismo",
      pairs: [
        { left: "Rousseau", right: "La autenticidad y la nostalgia del estado de naturaleza" },
        { left: "Kant", right: "La primacía de la voluntad y el libre albedrío" },
        { left: "Fichte", right: "Ser libre no es nada; devenir libre es el cielo" },
        { left: "Herder", right: "El alma de las naciones y la lengua como vínculo" },
        { left: "Dostoievski", right: "El hombre del subsuelo, que no quiere ser racional" },
      ],
      explain: "Las cinco piezas del legado: Rousseau da la autenticidad y el modelo de la nostalgia, Kant la primacía de la voluntad que los románticos llevan al extremo, Fichte el pasaje del ser al devenir, Herder el salto del alma individual al alma de las naciones, y Dostoievski la crítica más ceñida a la razón ilustrada, lo que Shestov llamó la verdadera crítica de la razón pura.",
    },
    {
      type: "info",
      title: "Conclusiones: el legado del Romanticismo",
      body: "El Romanticismo surge como una suerte de alter ego de la Ilustración y nos deja un legado de subjetividad radical como tormento eterno. Tendrá muchos sucesores:\n• Nietzsche, una especie de pensador posromántico.\n• El irracionalismo como virtud en sí misma.\n• El existencialismo, que va a tomar mucho del Romanticismo.\n• Elementos presentes también en el psicoanálisis freudiano.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "Mi encarnación favorita de esta crítica de la Ilustración por parte del Romanticismo es Dostoievski, un escritor posromántico y protoexistencialista (igual que Nietzsche, si vamos a categorizarlo). Las Memorias del subsuelo son su diatriba contra la Ilustración, en cierto modo la crítica más explícita y ceñida; los animo a leer el libro entero. El hombre del subsuelo no quiere ser racional, y es consciente de su deseo de no serlo. Esto es lo que el filósofo Lev Shestov llama la verdadera crítica de la razón pura —no Kant, sino Dostoievski—. Dice el hombre del subsuelo:",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "Verán, señores, la razón es sin duda una cosa excelente, pero la razón no es más que razón, y satisface únicamente la capacidad racional del hombre, mientras que los deseos son una manifestación de la vida entera. El hombre a veces es extremadamente aficionado al sufrimiento, hasta la pasión. La civilización no hace más que desarrollar en el hombre la capacidad para una mayor variedad de sensaciones, y absolutamente nada más; y a través del desarrollo de esa capacidad, el hombre puede llegar incluso a encontrar placer en el derramamiento de sangre.",
    },
    {
      type: "info",
      continues: true,
      title: "Conclusiones: el legado del Romanticismo",
      body: "Seguimos en la próxima sesión, cuando pasemos a Hegel.",
    },
  ],
};
