// Diccionario filosófico. Cada entrada se auto-linkea en las cards:
// agregar una entrada acá la vuelve clicable en todo el contenido.
//
// Campos:
//   term  : nombre canónico que se muestra en el modal
//   aka   : formas que aparecen en el texto y deben detectarse (incluí el canónico)
//   kind  : 'autor' | 'concepto' | 'obra' | 'evento'
//   when  : fechas de referencia (autor: nacimiento–muerte; concepto/obra/evento: época)
//   body  : explicación breve y en profundidad

export const GLOSSARY = {
  // ---------- autores ----------
  descartes: {
    term: "René Descartes",
    aka: ["Descartes", "René Descartes"],
    kind: "autor",
    when: "1596–1650",
    body: "Filósofo y matemático francés, considerado el padre de la filosofía moderna. Su método de duda radical buscó un fundamento indudable para el conocimiento y lo halló en el sujeto que piensa (cogito, ergo sum). Inauguró el giro hacia la epistemología y la subjetividad que domina el pensamiento moderno.",
  },
  nietzsche: {
    term: "Friedrich Nietzsche",
    aka: ["Nietzsche", "Friedrich Nietzsche"],
    kind: "autor",
    when: "1844–1900",
    body: "Filósofo alemán, posromántico y protoexistencialista. Proclamó que «Dios ha muerto» para describir el derrumbe de los fundamentos religiosos y metafísicos de la cultura europea. Da nombre al curso: el punto donde el desplazamiento ilustrado de Dios se vuelve su negación explícita.",
  },
  weber: {
    term: "Max Weber",
    aka: ["Max Weber", "Weber"],
    kind: "autor",
    when: "1864–1920",
    body: "Sociólogo y economista alemán, uno de los fundadores de la sociología moderna. Acuñó la idea de Entzauberung («desencanto del mundo») para nombrar el proceso por el cual la racionalización moderna expulsa lo mágico y lo sagrado de la experiencia.",
  },
  hobbes: {
    term: "Thomas Hobbes",
    aka: ["Thomas Hobbes", "Hobbes"],
    kind: "autor",
    when: "1588–1679",
    body: "Filósofo político inglés. En el Leviatán (1651) describe el estado de naturaleza como una guerra de todos contra todos y sostiene que solo un soberano absoluto puede garantizar la paz. Precursor de la teoría del contrato social, en su versión más pesimista.",
  },
  locke: {
    term: "John Locke",
    aka: ["John Locke", "Locke"],
    kind: "autor",
    when: "1632–1704",
    body: "Filósofo inglés, padre del liberalismo político. En sus Dos tratados sobre el gobierno (1689) funda el poder en el consentimiento de los gobernados y defiende un contrato social revocable: si el gobernante abusa, el pueblo puede reemplazarlo.",
  },
  voltaire: {
    term: "Voltaire",
    aka: ["Voltaire"],
    kind: "autor",
    when: "1694–1778",
    body: "Seudónimo de François-Marie Arouet, escritor y philosophe francés. Defensor del deísmo y, sobre todo, de la tolerancia contra el fanatismo religioso. Su lema «écrasez l'infâme» («aplastad la infamia») resume su combate contra la superstición y el absolutismo.",
  },
  rousseau: {
    term: "Jean-Jacques Rousseau",
    aka: ["Jean-Jacques Rousseau", "Rousseau"],
    kind: "autor",
    when: "1712–1778",
    body: "Filósofo ginebrino. Invierte a Hobbes: para él el estado de naturaleza era de virtud, y la propiedad corrompió al hombre. Su concepto de voluntad general (El contrato social, 1762) fundó una idea de soberanía popular que más tarde se invocaría para justificar el Terror.",
  },
  kant: {
    term: "Immanuel Kant",
    aka: ["Immanuel Kant", "Kant"],
    kind: "autor",
    when: "1724–1804",
    body: "Filósofo alemán, figura central de la Ilustración. En epistemología distinguió el fenómeno (lo que conocemos) de la cosa en sí (Ding an sich), inaccesible. Su «revolución copernicana» sostiene que el objeto se conforma a la mente, no al revés. Definió la Ilustración como la salida del hombre de su inmadurez.",
  },
  berlin: {
    term: "Isaiah Berlin",
    aka: ["Isaiah Berlin"],
    kind: "autor",
    when: "1909–1997",
    body: "Historiador de las ideas británico. Usó la metáfora del rompecabezas para describir la fe ilustrada en el progreso: cada pieza de conocimiento acerca al todo y facilita la siguiente. También estudió la Contra-Ilustración y el pluralismo de valores.",
  },
  newton: {
    term: "Isaac Newton",
    aka: ["Isaac Newton", "Newton"],
    kind: "autor",
    when: "1643–1727",
    body: "Físico y matemático inglés. Sus leyes del movimiento y la gravitación encarnaron el ideal ilustrado: el mundo puede descifrarse mediante observación y experimentación cuidadosas. Precursor del empirismo y del optimismo científico del siglo XVIII.",
  },
  diderot: {
    term: "Denis Diderot",
    aka: ["Diderot"],
    kind: "autor",
    when: "1713–1784",
    body: "Philosophe francés, director de la Encyclopédie, obra emblemática de la Ilustración que buscaba reunir todo el saber humano de forma racional y ordenada. Colaboró con Rousseau antes de distanciarse de él. Encarna el espíritu enciclopédico, secular y comprometido de la Ilustración francesa.",
  },
  fichte: {
    term: "Johann Gottlieb Fichte",
    aka: ["Fichte"],
    kind: "autor",
    when: "1762–1814",
    body: "Filósofo idealista alemán, discípulo de Kant. Radicalizó la primacía de la voluntad: «ser libre no es nada; devenir libre es el cielo». Ante la palabra libertad su corazón florecía; ante necesidad, se contraía. Puente entre la moral kantiana y el énfasis romántico en el deseo y la autocreación.",
  },
  herder: {
    term: "Johann Gottfried Herder",
    aka: ["Johann Gottfried Herder", "Herder"],
    kind: "autor",
    when: "1744–1803",
    body: "Filósofo romántico alemán, padre intelectual del nacionalismo. Sostuvo que los hombres existen para expresarse y que la expresión se transmite por la palabra. Lo esencial de una nación no es la sangre ni la raza, sino el suelo y sobre todo la lengua. Odiaba el cosmopolitismo ilustrado.",
  },
  hamann: {
    term: "Johann Georg Hamann",
    aka: ["Johann Georg Hamann", "Hamann"],
    kind: "autor",
    when: "1730–1788",
    body: "Filósofo alemán, amigo de Kant y de Herder, y crítico temprano de la Ilustración. Sostuvo que las clasificaciones y principios de ordenamiento racionales carecen de sentido, porque los seres humanos son irreductiblemente únicos y singulares. Figura de la Contra-Ilustración (Gegenaufklärung).",
  },
  goethe: {
    term: "Johann Wolfgang von Goethe",
    aka: ["Goethe"],
    kind: "autor",
    when: "1749–1832",
    body: "Poeta y escritor alemán, gran figura del Romanticismo. Criticó al racionalismo estético diciendo que trata la belleza como el entomólogo a las mariposas: la captura, la analiza y todo el color se escurre. Su Werther fue el emblema del héroe romántico apasionado.",
  },
  dostoievski: {
    term: "Fiódor Dostoievski",
    aka: ["Dostoievski"],
    kind: "autor",
    when: "1821–1881",
    body: "Novelista ruso, posromántico y protoexistencialista. Sus Memorias del subsuelo son una de las críticas más ceñidas a la Ilustración: contra la fe en que la razón basta y en que dos más dos son cuatro, reivindica el deseo, el capricho y la libertad irracional del hombre.",
  },
  shestov: {
    term: "Lev Shestov",
    aka: ["Lev Shestov", "Shestov"],
    kind: "autor",
    when: "1866–1938",
    body: "Filósofo ruso del irracionalismo religioso. Sostuvo que la Crítica de la razón pura de Kant no critica la razón sino que la defiende; la verdadera crítica de la razón pura, decía, son las Memorias del subsuelo de Dostoievski.",
  },

  // ---------- conceptos ----------
  ilustracion: {
    term: "Ilustración",
    aka: ["Ilustración", "Aufklärung"],
    kind: "concepto",
    when: "fines s. XVII – XVIII",
    body: "Movimiento intelectual europeo que exalta la razón como vía para comprender y mejorar el mundo. Desplaza a Dios del centro del pensamiento, confía en el progreso y culmina políticamente en la Revolución Francesa de 1789. Reúne filosofías diversas y a veces contradictorias.",
  },
  entzauberung: {
    term: "Entzauberung (desencanto)",
    aka: ["Entzauberung", "desencanto"],
    kind: "concepto",
    when: "concepto de Weber, s. XX",
    body: "«Desencantamiento del mundo»: el proceso por el cual la explicación racional y empírica expulsa a los milagros, lo mágico y lo sagrado. Weber lo describe como rasgo de la modernidad. Los ilustrados lo vivían con regocijo; los románticos, como una pérdida.",
  },
  cogito: {
    term: "Cogito, ergo sum",
    aka: ["cogito, ergo sum", "cogito", "pienso, luego existo"],
    kind: "concepto",
    when: "Descartes, 1637 / 1641",
    body: "«Pienso, luego existo». Punto de certeza que sobrevive a la duda radical: aunque un genio maligno me engañara sobre todo, no puede engañarme sobre el hecho de que estoy pensando. La existencia del sujeto pensante es la primera verdad indudable de la filosofía moderna.",
  },
  contrato_social: {
    term: "Contrato social",
    aka: ["contrato social"],
    kind: "concepto",
    when: "s. XVII–XVIII",
    body: "Teoría que explica el paso del estado de naturaleza a la sociedad organizada como un pacto. Cada pensador lo imagina distinto: para Hobbes justifica al soberano absoluto; para Locke, el gobierno por consentimiento; para Rousseau, la voluntad general.",
  },
  estado_naturaleza: {
    term: "Estado de naturaleza",
    aka: ["estado de naturaleza"],
    kind: "concepto",
    when: "s. XVII–XVIII",
    body: "Situación hipotética de la humanidad antes del gobierno y la sociedad. Es puramente imaginaria —no hay acceso a ella—, así que funciona como espejo de cada filosofía: guerra para Hobbes, libertad e igualdad para Locke, virtud perdida para Rousseau.",
  },
  leviatan: {
    term: "Leviatán",
    aka: ["Leviatán"],
    kind: "obra",
    when: "Hobbes, 1651",
    body: "Obra mayor de Hobbes y nombre del soberano absoluto que propone: un poder al que los individuos ceden sus derechos a cambio de seguridad. Su tesis: sin ese poder común, la vida es «desagradable, brutal y breve».",
  },
  consentimiento: {
    term: "Consentimiento de los gobernados",
    aka: ["consentimiento de los gobernados"],
    kind: "concepto",
    when: "Locke, 1689",
    body: "Idea de que la legitimidad del gobierno no proviene del derecho divino de los reyes, sino del acuerdo de quienes son gobernados. Base del liberalismo y de la Declaración de los Derechos del Hombre. Implica que el poder es condicional y revocable.",
  },
  liberalismo: {
    term: "Liberalismo",
    aka: ["liberalismo"],
    kind: "concepto",
    when: "desde fines s. XVIII",
    body: "Tradición política nacida de Locke y de la Revolución Francesa: derechos naturales del individuo (libertad, propiedad, seguridad), gobierno por consentimiento y límites al poder. La Declaración de 1789 es uno de sus documentos fundacionales.",
  },
  deismo: {
    term: "Deísmo",
    aka: ["deísmo"],
    kind: "concepto",
    when: "s. XVIII",
    body: "Posición intermedia entre el Dios cristiano y el agnosticismo: Dios existe y creó el mundo, pero luego se retiró y no interviene como un titiritero. Permite conservar un orden moral sin superstición ni absolutismo religioso. Voltaire es su figura clave.",
  },
  philosophes: {
    term: "Philosophes",
    aka: ["philosophes"],
    kind: "concepto",
    when: "Francia, s. XVIII",
    body: "Los filósofos franceses de la Ilustración: cosmopolitas, seculares y comprometidos con el mundo (engagé). Unen teoría y praxis y no se encierran en la epistemología abstracta. Voltaire, Diderot y Rousseau están entre ellos.",
  },
  voluntad_general: {
    term: "Voluntad general",
    aka: ["voluntad general"],
    kind: "concepto",
    when: "Rousseau, 1762",
    body: "Concepto central de El contrato social de Rousseau: no es la suma de intereses individuales ni la mera mayoría, sino una idea del «todo» social como fuente de autoridad. Su indeterminación la volvió peligrosa: se la invocó para legitimar el Terror.",
  },
  terror: {
    term: "El Terror",
    aka: ["Terror"],
    kind: "evento",
    when: "1793–1794",
    body: "Fase radical de la Revolución Francesa, marcada por ejecuciones masivas en nombre de la virtud republicana y la voluntad general. Robespierre fue su figura central. Suele leerse como el «lado oscuro» de la razón revolucionaria llevada al extremo.",
  },
  sapere_aude: {
    term: "Sapere aude",
    aka: ["sapere aude"],
    kind: "concepto",
    when: "lema retomado por Kant, 1784",
    body: "«Atrévete a saber». Frase de Horacio que Kant convierte en lema de la Ilustración: ten el valor de servirte de tu propio entendimiento sin la tutela de una autoridad. No es un llamado revolucionario, sino a la mayoría de edad intelectual.",
  },
  ding_an_sich: {
    term: "Ding an sich (cosa en sí)",
    aka: ["Ding an sich", "cosa en sí"],
    kind: "concepto",
    when: "Kant, 1781",
    body: "La «cosa en sí»: la realidad tal como es, con independencia de la mente. Kant afirma que existe, pero que no tenemos acceso a ella: solo conocemos el fenómeno, el mundo ya filtrado por las estructuras de nuestra percepción y entendimiento.",
  },
  rev_copernicana: {
    term: "Revolución copernicana (de Kant)",
    aka: ["revolución copernicana"],
    kind: "concepto",
    when: "Kant, 1781",
    body: "Giro epistemológico por analogía con Copérnico: así como la Tierra gira en torno al Sol y no al revés, no es la mente la que se adapta al mundo, sino lo que percibimos del mundo lo que se conforma a las categorías de la mente.",
  },
  rev_francesa: {
    term: "Revolución Francesa",
    aka: ["Revolución Francesa"],
    kind: "evento",
    when: "1789–1799",
    body: "Culminación política de la Ilustración. Sustituye el derecho divino por el consentimiento de los gobernados y convierte súbditos en ciudadanos. Inventa la ideología como proyecto de reordenar la sociedad según la razón, y desemboca en el Terror.",
  },
  modernizacion: {
    term: "Modernización",
    aka: ["modernización"],
    kind: "concepto",
    when: "desde s. XVIII",
    body: "Los cambios materiales y técnicos ligados a la modernidad: industrialización, urbanización, capitalismo, economía monetaria, mejoras en transporte y comunicaciones. Se distingue de la modernidad (el período) y del modernismo (la respuesta estética).",
  },
  modernidad: {
    term: "Modernidad",
    aka: ["modernidad"],
    kind: "concepto",
    when: "desde 1789",
    body: "El período histórico que abre la Ilustración, datado por los historiadores europeos en 1789. No confundir con modernización (los cambios materiales) ni con modernismo (la respuesta estética en arte y literatura).",
  },
  modernismo: {
    term: "Modernismo",
    aka: ["modernismo"],
    kind: "concepto",
    when: "fines s. XIX – XX",
    body: "La respuesta estética a la modernidad en literatura, arte y filosofía. Se distingue de la modernidad (el período) y de la modernización (los cambios materiales que le dan origen).",
  },
  empirismo: {
    term: "Empirismo",
    aka: ["empirismo"],
    kind: "concepto",
    when: "s. XVII–XVIII",
    body: "Doctrina según la cual el conocimiento se gana por la experiencia sensorial y la observación. Newton es su modelo científico. Del empirismo derivará el positivismo, que entiende el mundo solo según la observación, sin nada metafísico.",
  },
  positivismo: {
    term: "Positivismo",
    aka: ["positivismo"],
    kind: "concepto",
    when: "s. XIX",
    body: "Heredero del empirismo: solo cuenta como conocimiento lo verificable por la observación empírica, sin fuerzas sobrenaturales ni metafísica. Encarna la aspiración ilustrada de entender la sociedad con el rigor de las ciencias naturales.",
  },
  romanticismo: {
    term: "Romanticismo",
    aka: ["Romanticismo"],
    kind: "concepto",
    when: "fines s. XVIII – s. XIX",
    body: "Rebelión contra el ánimo ilustrado. Frente a la razón, el progreso y la civilización, exalta la pasión, la belleza, el anhelo, la creación y la voluntad. Su centro es Alemania, y su imaginario, el bosque y la tormenta. La verdad no se descubre: se crea en el alma individual. De él nacerá el nacionalismo.",
  },
  gegenaufklarung: {
    term: "Contra-Ilustración (Gegenaufklärung)",
    aka: ["Gegenaufklärung", "contra-Ilustración"],
    kind: "concepto",
    when: "fines s. XVIII",
    body: "Nombre del Romanticismo entendido como reacción contra la Ilustración. Rechaza el racionalismo como virtud incuestionable, la idea de que toda pregunta puede responderse y la de que los intereses pueden armonizarse. Reivindica el alma singular frente a la clasificación científica.",
  },
  stimmung: {
    term: "Stimmung (talante)",
    aka: ["Stimmung"],
    kind: "concepto",
    when: "término alemán",
    body: "«Talante» o estado de ánimo. La clase usa la palabra para subrayar que la Ilustración y el Romanticismo no son solo doctrinas, sino climas anímicos: una alegre, clasificatoria y optimista; la otra apasionada, nostálgica y volcada a la oscuridad y el anhelo.",
  },
  sehnsucht: {
    term: "Sehnsucht (anhelo)",
    aka: ["Sehnsucht"],
    kind: "concepto",
    when: "término romántico alemán",
    body: "Anhelo que se convierte en una cosa en sí misma. El objeto deseado importa menos que la emoción del anhelo por aquello que nunca podrá alcanzarse del todo. Es el tono afectivo del Romanticismo, ligado a la nostalgia por un pasado idealizado que nunca existió.",
  },
  ser_devenir: {
    term: "Ser y devenir",
    aka: ["ser y devenir", "devenir"],
    kind: "concepto",
    when: "distinción retomada por el Romanticismo",
    body: "Si la Ilustración pregunta cómo son las cosas (el ser), el Romanticismo pregunta qué podemos llegar a ser (el devenir). El hombre es un ser singularmente indeterminado que se autocrea. Distinción clave que reaparecerá en Nietzsche y en Heidegger.",
  },
  autenticidad: {
    term: "Autenticidad",
    aka: ["autenticidad"],
    kind: "concepto",
    when: "tema romántico, desde Rousseau",
    body: "Virtud romántica tomada de Rousseau: ser uno mismo frente al «velo engañoso de la cortesía». La sociedad y la propiedad corrompen al fomentar la vanidad y la competencia por lucirse; nadie se atreve a parecer lo que es. No hay virtud sin autenticidad, y esta exige un retiro de la sociedad.",
  },
  libre_albedrio: {
    term: "Libre albedrío",
    aka: ["libre albedrío"],
    kind: "concepto",
    when: "Kant, filosofía moral",
    body: "Para Kant, condición de toda moralidad: sin libre albedrío no hay ética, porque solo un individuo libre toma decisiones morales. No puede demostrarse, así que se lo postula. Junto con la razón, funda la dignidad humana. Los románticos lo radicalizan como primacía de la voluntad.",
  },
  imperativo_categorico: {
    term: "Imperativo categórico",
    aka: ["imperativo categórico"],
    kind: "concepto",
    when: "Kant, 1785",
    body: "Criterio moral kantiano: actuar solo según principios que podrías querer como ley universal. La prueba práctica: ¿qué pasaría si todos actuaran según el principio con el que estoy por actuar? Si el resultado sería un desastre, la acción no es moral. Lo que cuenta es la intención, no la consecuencia.",
  },
  volo_ergo_sum: {
    term: "Volo ergo sum",
    aka: ["volo ergo sum"],
    kind: "concepto",
    when: "inversión romántica del cogito",
    body: "«Quiero, deseo, luego existo». Los románticos contraponen esta fórmula al cogito ergo sum cartesiano: en lugar de fundar la subjetividad en el pensamiento, la fundan en el deseo y la voluntad. Expresa la primacía romántica de la pasión sobre la razón.",
  },
  nacionalismo: {
    term: "Nacionalismo",
    aka: ["nacionalismo"],
    kind: "concepto",
    when: "desde s. XIX",
    body: "Herencia política del Romanticismo, como el liberalismo lo es de la Ilustración: si cada individuo tiene un alma irreductible, también la tiene cada nación. En Herder se funda no en la sangre ni la raza, sino en el suelo y sobre todo en la lengua, contra el cosmopolitismo ilustrado.",
  },
  sublime: {
    term: "Lo sublime",
    aka: ["sublime"],
    kind: "concepto",
    when: "estética romántica",
    body: "Aquello demasiado precioso y bello para ser puesto en palabras. Junto con la poesía como expresión del alma, define la estética romántica: el arte debe expresar lo auténtico —agonía, desesperación, anhelo místico— más que representar o clasificar el mundo.",
  },
  hombre_subsuelo: {
    term: "El hombre del subsuelo",
    aka: ["hombre del subsuelo"],
    kind: "concepto",
    when: "Dostoievski, 1864",
    body: "Narrador de las Memorias del subsuelo de Dostoievski. No quiere ser racional y es consciente de ese deseo: se rebela incluso contra que dos más dos sean cuatro, si lo encuentra opresivo. Encarna la crítica romántica y protoexistencialista a la fe ilustrada en la razón.",
  },

  // ---------- obras / figuras culturales ----------
  montana_magica: {
    term: "La montaña mágica",
    aka: ["La montaña mágica"],
    kind: "obra",
    when: "Thomas Mann, 1924",
    body: "Novela de Thomas Mann. Su personaje Settembrini encarna —de forma casi caricaturesca— el optimismo ilustrado: la fe en la razón, el progreso y la palabra. Sirve para retratar tanto la grandeza como los límites del espíritu de la Ilustración.",
  },
  settembrini: {
    term: "Settembrini",
    aka: ["Settembrini"],
    kind: "concepto",
    when: "personaje, 1924",
    body: "Personaje de La montaña mágica de Thomas Mann: un humanista que defiende «la razón, el análisis, la acción, el progreso». Descrito como «la Ilustración que habla demasiado», condensa el ideal —y el exceso— ilustrado.",
  },
  critica_razon_pura: {
    term: "Crítica de la razón pura",
    aka: ["Crítica de la razón pura"],
    kind: "obra",
    when: "Kant, 1781",
    body: "Obra mayor de Kant sobre los límites del conocimiento racional: qué podemos y qué no podemos conocer. Allí distingue el fenómeno de la cosa en sí y formula la revolución copernicana. Larga y técnica; el propio Kant la resumió en los Prolegómenos a toda metafísica futura.",
  },
  discurso_ciencias_artes: {
    term: "Discurso sobre las ciencias y las artes",
    aka: ["Discurso sobre las ciencias y las artes"],
    kind: "obra",
    when: "Rousseau, 1750",
    body: "«Primer discurso» de Rousseau: sostiene que el progreso de las ciencias y las artes corrompe las costumbres. Denuncia el «velo engañoso de la cortesía» y la vida social como falsificación del yo. De aquí toman los románticos la virtud de la autenticidad.",
  },
  memorias_subsuelo: {
    term: "Memorias del subsuelo",
    aka: ["Memorias del subsuelo"],
    kind: "obra",
    when: "Dostoievski, 1864",
    body: "Novela corta de Dostoievski, diatriba contra la Ilustración leída como crítica romántica de la razón. Su narrador, el hombre del subsuelo, reivindica el deseo irracional frente al cálculo, y se rebela contra la idea de que dos más dos deban ser cuatro.",
  },
};
