// Diccionario filosófico. Cada entrada se auto-linkea en las cards:
// agregar una entrada acá la vuelve clicable en todo el contenido.
//
// Campos:
//   term  : nombre canónico que se muestra en el modal
//   aka   : formas que aparecen en el texto y deben detectarse (incluí el canónico)
//   kind  : 'autor' | 'concepto' | 'obra' | 'evento'
//   when  : fechas de referencia (autor: nacimiento–muerte; concepto/obra/evento: época)
//   body  : explicación breve y en profundidad

export const GLOSSARY = {
  // ---------- autores ----------
  descartes: {
    term: "René Descartes",
    aka: ["Descartes", "René Descartes"],
    kind: "autor",
    when: "1596–1650",
    body: "Filósofo y matemático francés, considerado el padre de la filosofía moderna. Su método de duda radical buscó un fundamento indudable para el conocimiento y lo halló en el sujeto que piensa (cogito, ergo sum). Inauguró el giro hacia la epistemología y la subjetividad que domina el pensamiento moderno.",
  },
  nietzsche: {
    term: "Friedrich Nietzsche",
    aka: ["Nietzsche", "Friedrich Nietzsche"],
    kind: "autor",
    when: "1844–1900",
    body: "Filósofo alemán, posromántico y protoexistencialista. Proclamó que «Dios ha muerto» para describir el derrumbe de los fundamentos religiosos y metafísicos de la cultura europea. Da nombre al curso: el punto donde el desplazamiento ilustrado de Dios se vuelve su negación explícita.",
  },
  weber: {
    term: "Max Weber",
    aka: ["Max Weber", "Weber"],
    kind: "autor",
    when: "1864–1920",
    body: "Sociólogo y economista alemán, uno de los fundadores de la sociología moderna. Acuñó la idea de Entzauberung («desencanto del mundo») para nombrar el proceso por el cual la racionalización moderna expulsa lo mágico y lo sagrado de la experiencia.",
  },
  hobbes: {
    term: "Thomas Hobbes",
    aka: ["Thomas Hobbes", "Hobbes"],
    kind: "autor",
    when: "1588–1679",
    body: "Filósofo político inglés. En el Leviatán (1651) describe el estado de naturaleza como una guerra de todos contra todos y sostiene que solo un soberano absoluto puede garantizar la paz. Precursor de la teoría del contrato social, en su versión más pesimista.",
  },
  locke: {
    term: "John Locke",
    aka: ["John Locke", "Locke"],
    kind: "autor",
    when: "1632–1704",
    body: "Filósofo inglés, padre del liberalismo político. En sus Dos tratados sobre el gobierno (1689) funda el poder en el consentimiento de los gobernados y defiende un contrato social revocable: si el gobernante abusa, el pueblo puede reemplazarlo.",
  },
  voltaire: {
    term: "Voltaire",
    aka: ["Voltaire"],
    kind: "autor",
    when: "1694–1778",
    body: "Seudónimo de François-Marie Arouet, escritor y philosophe francés. Defensor del deísmo y, sobre todo, de la tolerancia contra el fanatismo religioso. Su lema «écrasez l'infâme» («aplastad la infamia») resume su combate contra la superstición y el absolutismo.",
  },
  rousseau: {
    term: "Jean-Jacques Rousseau",
    aka: ["Jean-Jacques Rousseau", "Rousseau"],
    kind: "autor",
    when: "1712–1778",
    body: "Filósofo ginebrino. Invierte a Hobbes: para él el estado de naturaleza era de virtud, y la propiedad corrompió al hombre. Su concepto de voluntad general (El contrato social, 1762) fundó una idea de soberanía popular que más tarde se invocaría para justificar el Terror.",
  },
  kant: {
    term: "Immanuel Kant",
    aka: ["Immanuel Kant", "Kant"],
    kind: "autor",
    when: "1724–1804",
    body: "Filósofo alemán, figura central de la Ilustración. En epistemología distinguió el fenómeno (lo que conocemos) de la cosa en sí (Ding an sich), inaccesible. Su «revolución copernicana» sostiene que el objeto se conforma a la mente, no al revés. Definió la Ilustración como la salida del hombre de su inmadurez.",
  },
  berlin: {
    term: "Isaiah Berlin",
    aka: ["Isaiah Berlin"],
    kind: "autor",
    when: "1909–1997",
    body: "Historiador de las ideas británico. Usó la metáfora del rompecabezas para describir la fe ilustrada en el progreso: cada pieza de conocimiento acerca al todo y facilita la siguiente. También estudió la Contra-Ilustración y el pluralismo de valores.",
  },
  newton: {
    term: "Isaac Newton",
    aka: ["Isaac Newton", "Newton"],
    kind: "autor",
    when: "1643–1727",
    body: "Físico y matemático inglés. Sus leyes del movimiento y la gravitación encarnaron el ideal ilustrado: el mundo puede descifrarse mediante observación y experimentación cuidadosas. Precursor del empirismo y del optimismo científico del siglo XVIII.",
  },
  diderot: {
    term: "Denis Diderot",
    aka: ["Diderot"],
    kind: "autor",
    when: "1713–1784",
    body: "Philosophe francés, director de la Encyclopédie, obra emblemática de la Ilustración que buscaba reunir todo el saber humano de forma racional y ordenada. Colaboró con Rousseau antes de distanciarse de él. Encarna el espíritu enciclopédico, secular y comprometido de la Ilustración francesa.",
  },
  fichte: {
    term: "Johann Gottlieb Fichte",
    aka: ["Fichte"],
    kind: "autor",
    when: "1762–1814",
    body: "Filósofo idealista alemán, discípulo de Kant. Radicalizó la primacía de la voluntad: «ser libre no es nada; devenir libre es el cielo». Ante la palabra libertad su corazón florecía; ante necesidad, se contraía. Puente entre la moral kantiana y el énfasis romántico en el deseo y la autocreación.",
  },
  herder: {
    term: "Johann Gottfried Herder",
    aka: ["Johann Gottfried Herder", "Herder"],
    kind: "autor",
    when: "1744–1803",
    body: "Filósofo romántico alemán, padre intelectual del nacionalismo. Sostuvo que los hombres existen para expresarse y que la expresión se transmite por la palabra. Lo esencial de una nación no es la sangre ni la raza, sino el suelo y sobre todo la lengua. Odiaba el cosmopolitismo ilustrado.",
  },
  hamann: {
    term: "Johann Georg Hamann",
    aka: ["Johann Georg Hamann", "Hamann"],
    kind: "autor",
    when: "1730–1788",
    body: "Filósofo alemán, amigo de Kant y de Herder, y crítico temprano de la Ilustración. Sostuvo que las clasificaciones y principios de ordenamiento racionales carecen de sentido, porque los seres humanos son irreductiblemente únicos y singulares. Figura de la Contra-Ilustración (Gegenaufklärung).",
  },
  goethe: {
    term: "Johann Wolfgang von Goethe",
    aka: ["Goethe"],
    kind: "autor",
    when: "1749–1832",
    body: "Poeta y escritor alemán, gran figura del Romanticismo. Criticó al racionalismo estético diciendo que trata la belleza como el entomólogo a las mariposas: la captura, la analiza y todo el color se escurre. Su Werther fue el emblema del héroe romántico apasionado.",
  },
  dostoievski: {
    term: "Fiódor Dostoievski",
    aka: ["Dostoievski"],
    kind: "autor",
    when: "1821–1881",
    body: "Novelista ruso, posromántico y protoexistencialista. Sus Memorias del subsuelo son una de las críticas más ceñidas a la Ilustración: contra la fe en que la razón basta y en que dos más dos son cuatro, reivindica el deseo, el capricho y la libertad irracional del hombre.",
  },
  shestov: {
    term: "Lev Shestov",
    aka: ["Lev Shestov", "Shestov"],
    kind: "autor",
    when: "1866–1938",
    body: "Filósofo ruso del irracionalismo religioso. Sostuvo que la Crítica de la razón pura de Kant no critica la razón sino que la defiende; la verdadera crítica de la razón pura, decía, son las Memorias del subsuelo de Dostoievski.",
  },

  // ---------- conceptos ----------
  ilustracion: {
    term: "Ilustración",
    aka: ["Ilustración", "Aufklärung"],
    kind: "concepto",
    when: "fines s. XVII – XVIII",
    body: "Movimiento intelectual europeo que exalta la razón como vía para comprender y mejorar el mundo. Desplaza a Dios del centro del pensamiento, confía en el progreso y culmina políticamente en la Revolución Francesa de 1789. Reúne filosofías diversas y a veces contradictorias.",
  },
  entzauberung: {
    term: "Entzauberung (desencanto)",
    aka: ["Entzauberung", "desencanto"],
    kind: "concepto",
    when: "concepto de Weber, s. XX",
    body: "«Desencantamiento del mundo»: el proceso por el cual la explicación racional y empírica expulsa a los milagros, lo mágico y lo sagrado. Weber lo describe como rasgo de la modernidad. Los ilustrados lo vivían con regocijo; los románticos, como una pérdida.",
  },
  cogito: {
    term: "Cogito, ergo sum",
    aka: ["cogito, ergo sum", "cogito", "pienso, luego existo"],
    kind: "concepto",
    when: "Descartes, 1637 / 1641",
    body: "«Pienso, luego existo». Punto de certeza que sobrevive a la duda radical: aunque un genio maligno me engañara sobre todo, no puede engañarme sobre el hecho de que estoy pensando. La existencia del sujeto pensante es la primera verdad indudable de la filosofía moderna.",
  },
  contrato_social: {
    term: "Contrato social",
    aka: ["contrato social"],
    kind: "concepto",
    when: "s. XVII–XVIII",
    body: "Teoría que explica el paso del estado de naturaleza a la sociedad organizada como un pacto. Cada pensador lo imagina distinto: para Hobbes justifica al soberano absoluto; para Locke, el gobierno por consentimiento; para Rousseau, la voluntad general.",
  },
  estado_naturaleza: {
    term: "Estado de naturaleza",
    aka: ["estado de naturaleza"],
    kind: "concepto",
    when: "s. XVII–XVIII",
    body: "Situación hipotética de la humanidad antes del gobierno y la sociedad. Es puramente imaginaria —no hay acceso a ella—, así que funciona como espejo de cada filosofía: guerra para Hobbes, libertad e igualdad para Locke, virtud perdida para Rousseau.",
  },
  leviatan: {
    term: "Leviatán",
    aka: ["Leviatán"],
    kind: "obra",
    when: "Hobbes, 1651",
    body: "Obra mayor de Hobbes y nombre del soberano absoluto que propone: un poder al que los individuos ceden sus derechos a cambio de seguridad. Su tesis: sin ese poder común, la vida es «desagradable, brutal y breve».",
  },
  consentimiento: {
    term: "Consentimiento de los gobernados",
    aka: ["consentimiento de los gobernados"],
    kind: "concepto",
    when: "Locke, 1689",
    body: "Idea de que la legitimidad del gobierno no proviene del derecho divino de los reyes, sino del acuerdo de quienes son gobernados. Base del liberalismo y de la Declaración de los Derechos del Hombre. Implica que el poder es condicional y revocable.",
  },
  liberalismo: {
    term: "Liberalismo",
    aka: ["liberalismo"],
    kind: "concepto",
    when: "desde fines s. XVIII",
    body: "Tradición política nacida de Locke y de la Revolución Francesa: derechos naturales del individuo (libertad, propiedad, seguridad), gobierno por consentimiento y límites al poder. La Declaración de 1789 es uno de sus documentos fundacionales.",
  },
  deismo: {
    term: "Deísmo",
    aka: ["deísmo"],
    kind: "concepto",
    when: "s. XVIII",
    body: "Posición intermedia entre el Dios cristiano y el agnosticismo: Dios existe y creó el mundo, pero luego se retiró y no interviene como un titiritero. Permite conservar un orden moral sin superstición ni absolutismo religioso. Voltaire es su figura clave.",
  },
  philosophes: {
    term: "Philosophes",
    aka: ["philosophes"],
    kind: "concepto",
    when: "Francia, s. XVIII",
    body: "Los filósofos franceses de la Ilustración: cosmopolitas, seculares y comprometidos con el mundo (engagé). Unen teoría y praxis y no se encierran en la epistemología abstracta. Voltaire, Diderot y Rousseau están entre ellos.",
  },
  voluntad_general: {
    term: "Voluntad general",
    aka: ["voluntad general"],
    kind: "concepto",
    when: "Rousseau, 1762",
    body: "Concepto central de El contrato social de Rousseau: no es la suma de intereses individuales ni la mera mayoría, sino una idea del «todo» social como fuente de autoridad. Su indeterminación la volvió peligrosa: se la invocó para legitimar el Terror.",
  },
  terror: {
    term: "El Terror",
    aka: ["Terror"],
    kind: "evento",
    when: "1793–1794",
    body: "Fase radical de la Revolución Francesa, marcada por ejecuciones masivas en nombre de la virtud republicana y la voluntad general. Robespierre fue su figura central. Suele leerse como el «lado oscuro» de la razón revolucionaria llevada al extremo.",
  },
  sapere_aude: {
    term: "Sapere aude",
    aka: ["sapere aude"],
    kind: "concepto",
    when: "lema retomado por Kant, 1784",
    body: "«Atrévete a saber». Frase de Horacio que Kant convierte en lema de la Ilustración: ten el valor de servirte de tu propio entendimiento sin la tutela de una autoridad. No es un llamado revolucionario, sino a la mayoría de edad intelectual.",
  },
  ding_an_sich: {
    term: "Ding an sich (cosa en sí)",
    aka: ["Ding an sich", "cosa en sí"],
    kind: "concepto",
    when: "Kant, 1781",
    body: "La «cosa en sí»: la realidad tal como es, con independencia de la mente. Kant afirma que existe, pero que no tenemos acceso a ella: solo conocemos el fenómeno, el mundo ya filtrado por las estructuras de nuestra percepción y entendimiento.",
  },
  rev_copernicana: {
    term: "Revolución copernicana (de Kant)",
    aka: ["revolución copernicana"],
    kind: "concepto",
    when: "Kant, 1781",
    body: "Giro epistemológico por analogía con Copérnico: así como la Tierra gira en torno al Sol y no al revés, no es la mente la que se adapta al mundo, sino lo que percibimos del mundo lo que se conforma a las categorías de la mente.",
  },
  rev_francesa: {
    term: "Revolución Francesa",
    aka: ["Revolución Francesa"],
    kind: "evento",
    when: "1789–1799",
    body: "Culminación política de la Ilustración. Sustituye el derecho divino por el consentimiento de los gobernados y convierte súbditos en ciudadanos. Inventa la ideología como proyecto de reordenar la sociedad según la razón, y desemboca en el Terror.",
  },
  modernizacion: {
    term: "Modernización",
    aka: ["modernización"],
    kind: "concepto",
    when: "desde s. XVIII",
    body: "Los cambios materiales y técnicos ligados a la modernidad: industrialización, urbanización, capitalismo, economía monetaria, mejoras en transporte y comunicaciones. Se distingue de la modernidad (el período) y del modernismo (la respuesta estética).",
  },
  modernidad: {
    term: "Modernidad",
    aka: ["modernidad"],
    kind: "concepto",
    when: "desde 1789",
    body: "El período histórico que abre la Ilustración, datado por los historiadores europeos en 1789. No confundir con modernización (los cambios materiales) ni con modernismo (la respuesta estética en arte y literatura).",
  },
  modernismo: {
    term: "Modernismo",
    aka: ["modernismo"],
    kind: "concepto",
    when: "fines s. XIX – XX",
    body: "La respuesta estética a la modernidad en literatura, arte y filosofía. Se distingue de la modernidad (el período) y de la modernización (los cambios materiales que le dan origen).",
  },
  empirismo: {
    term: "Empirismo",
    aka: ["empirismo"],
    kind: "concepto",
    when: "s. XVII–XVIII",
    body: "Doctrina según la cual el conocimiento se gana por la experiencia sensorial y la observación. Newton es su modelo científico. Del empirismo derivará el positivismo, que entiende el mundo solo según la observación, sin nada metafísico.",
  },
  positivismo: {
    term: "Positivismo",
    aka: ["positivismo"],
    kind: "concepto",
    when: "s. XIX",
    body: "Heredero del empirismo: solo cuenta como conocimiento lo verificable por la observación empírica, sin fuerzas sobrenaturales ni metafísica. Encarna la aspiración ilustrada de entender la sociedad con el rigor de las ciencias naturales.",
  },
  romanticismo: {
    term: "Romanticismo",
    aka: ["Romanticismo"],
    kind: "concepto",
    when: "fines s. XVIII – s. XIX",
    body: "Rebelión contra el ánimo ilustrado. Frente a la razón, el progreso y la civilización, exalta la pasión, la belleza, el anhelo, la creación y la voluntad. Su centro es Alemania, y su imaginario, el bosque y la tormenta. La verdad no se descubre: se crea en el alma individual. De él nacerá el nacionalismo.",
  },
  gegenaufklarung: {
    term: "Contra-Ilustración (Gegenaufklärung)",
    aka: ["Gegenaufklärung", "contra-Ilustración"],
    kind: "concepto",
    when: "fines s. XVIII",
    body: "Nombre del Romanticismo entendido como reacción contra la Ilustración. Rechaza el racionalismo como virtud incuestionable, la idea de que toda pregunta puede responderse y la de que los intereses pueden armonizarse. Reivindica el alma singular frente a la clasificación científica.",
  },
  stimmung: {
    term: "Stimmung (talante)",
    aka: ["Stimmung"],
    kind: "concepto",
    when: "término alemán",
    body: "«Talante» o estado de ánimo. La clase usa la palabra para subrayar que la Ilustración y el Romanticismo no son solo doctrinas, sino climas anímicos: una alegre, clasificatoria y optimista; la otra apasionada, nostálgica y volcada a la oscuridad y el anhelo.",
  },
  sehnsucht: {
    term: "Sehnsucht (anhelo)",
    aka: ["Sehnsucht"],
    kind: "concepto",
    when: "término romántico alemán",
    body: "Anhelo que se convierte en una cosa en sí misma. El objeto deseado importa menos que la emoción del anhelo por aquello que nunca podrá alcanzarse del todo. Es el tono afectivo del Romanticismo, ligado a la nostalgia por un pasado idealizado que nunca existió.",
  },
  ser_devenir: {
    term: "Ser y devenir",
    aka: ["ser y devenir", "devenir"],
    kind: "concepto",
    when: "distinción retomada por el Romanticismo",
    body: "Si la Ilustración pregunta cómo son las cosas (el ser), el Romanticismo pregunta qué podemos llegar a ser (el devenir). El hombre es un ser singularmente indeterminado que se autocrea. Distinción clave que reaparecerá en Nietzsche y en Heidegger.",
  },
  autenticidad: {
    term: "Autenticidad",
    aka: ["autenticidad"],
    kind: "concepto",
    when: "tema romántico, desde Rousseau",
    body: "Virtud romántica tomada de Rousseau: ser uno mismo frente al «velo engañoso de la cortesía». La sociedad y la propiedad corrompen al fomentar la vanidad y la competencia por lucirse; nadie se atreve a parecer lo que es. No hay virtud sin autenticidad, y esta exige un retiro de la sociedad.",
  },
  libre_albedrio: {
    term: "Libre albedrío",
    aka: ["libre albedrío"],
    kind: "concepto",
    when: "Kant, filosofía moral",
    body: "Para Kant, condición de toda moralidad: sin libre albedrío no hay ética, porque solo un individuo libre toma decisiones morales. No puede demostrarse, así que se lo postula. Junto con la razón, funda la dignidad humana. Los románticos lo radicalizan como primacía de la voluntad.",
  },
  imperativo_categorico: {
    term: "Imperativo categórico",
    aka: ["imperativo categórico"],
    kind: "concepto",
    when: "Kant, 1785",
    body: "Criterio moral kantiano: actuar solo según principios que podrías querer como ley universal. La prueba práctica: ¿qué pasaría si todos actuaran según el principio con el que estoy por actuar? Si el resultado sería un desastre, la acción no es moral. Lo que cuenta es la intención, no la consecuencia.",
  },
  volo_ergo_sum: {
    term: "Volo ergo sum",
    aka: ["volo ergo sum"],
    kind: "concepto",
    when: "inversión romántica del cogito",
    body: "«Quiero, deseo, luego existo». Los románticos contraponen esta fórmula al cogito ergo sum cartesiano: en lugar de fundar la subjetividad en el pensamiento, la fundan en el deseo y la voluntad. Expresa la primacía romántica de la pasión sobre la razón.",
  },
  nacionalismo: {
    term: "Nacionalismo",
    aka: ["nacionalismo"],
    kind: "concepto",
    when: "desde s. XIX",
    body: "Herencia política del Romanticismo, como el liberalismo lo es de la Ilustración: si cada individuo tiene un alma irreductible, también la tiene cada nación. En Herder se funda no en la sangre ni la raza, sino en el suelo y sobre todo en la lengua, contra el cosmopolitismo ilustrado.",
  },
  sublime: {
    term: "Lo sublime",
    aka: ["sublime"],
    kind: "concepto",
    when: "estética romántica",
    body: "Aquello demasiado precioso y bello para ser puesto en palabras. Junto con la poesía como expresión del alma, define la estética romántica: el arte debe expresar lo auténtico —agonía, desesperación, anhelo místico— más que representar o clasificar el mundo.",
  },
  hombre_subsuelo: {
    term: "El hombre del subsuelo",
    aka: ["hombre del subsuelo"],
    kind: "concepto",
    when: "Dostoievski, 1864",
    body: "Narrador de las Memorias del subsuelo de Dostoievski. No quiere ser racional y es consciente de ese deseo: se rebela incluso contra que dos más dos sean cuatro, si lo encuentra opresivo. Encarna la crítica romántica y protoexistencialista a la fe ilustrada en la razón.",
  },

  // ---------- obras / figuras culturales ----------
  montana_magica: {
    term: "La montaña mágica",
    aka: ["La montaña mágica"],
    kind: "obra",
    when: "Thomas Mann, 1924",
    body: "Novela de Thomas Mann. Su personaje Settembrini encarna —de forma casi caricaturesca— el optimismo ilustrado: la fe en la razón, el progreso y la palabra. Sirve para retratar tanto la grandeza como los límites del espíritu de la Ilustración.",
  },
  settembrini: {
    term: "Settembrini",
    aka: ["Settembrini"],
    kind: "concepto",
    when: "personaje, 1924",
    body: "Personaje de La montaña mágica de Thomas Mann: un humanista que defiende «la razón, el análisis, la acción, el progreso». Descrito como «la Ilustración que habla demasiado», condensa el ideal —y el exceso— ilustrado.",
  },
  critica_razon_pura: {
    term: "Crítica de la razón pura",
    aka: ["Crítica de la razón pura"],
    kind: "obra",
    when: "Kant, 1781",
    body: "Obra mayor de Kant sobre los límites del conocimiento racional: qué podemos y qué no podemos conocer. Allí distingue el fenómeno de la cosa en sí y formula la revolución copernicana. Larga y técnica; el propio Kant la resumió en los Prolegómenos a toda metafísica futura.",
  },
  discurso_ciencias_artes: {
    term: "Discurso sobre las ciencias y las artes",
    aka: ["Discurso sobre las ciencias y las artes"],
    kind: "obra",
    when: "Rousseau, 1750",
    body: "«Primer discurso» de Rousseau: sostiene que el progreso de las ciencias y las artes corrompe las costumbres. Denuncia el «velo engañoso de la cortesía» y la vida social como falsificación del yo. De aquí toman los románticos la virtud de la autenticidad.",
  },
  memorias_subsuelo: {
    term: "Memorias del subsuelo",
    aka: ["Memorias del subsuelo"],
    kind: "obra",
    when: "Dostoievski, 1864",
    body: "Novela corta de Dostoievski, diatriba contra la Ilustración leída como crítica romántica de la razón. Su narrador, el hombre del subsuelo, reivindica el deseo irracional frente al cálculo, y se rebela contra la idea de que dos más dos deban ser cuatro.",
  },

  // ---------- Clase 3: Hegel ----------
  hegel: {
    term: "G. W. F. Hegel",
    aka: ["Hegel", "G. W. F. Hegel"],
    kind: "autor",
    when: "1770–1831",
    body: "Filósofo idealista alemán. Buscó reconciliar las divisiones de la modernidad —sujeto y objeto, individuo y todo— haciendo de la historia un componente de la filosofía. En la Fenomenología del espíritu (1807) narra el ascenso dialéctico de la conciencia hacia el Geist. Su lema: «lo verdadero es el todo».",
  },
  napoleon: {
    term: "Napoleón Bonaparte",
    aka: ["Napoleón"],
    kind: "autor",
    when: "1769–1821",
    body: "Militar y emperador francés. Difundió por Europa muchas de las reformas de la Revolución. Al verlo entrar en Jena en 1806, Hegel lo llamó «el Espíritu del Mundo a caballo»: la encarnación, para él, de la dirección que tomaba la historia.",
  },
  arendt: {
    term: "Hannah Arendt",
    aka: ["Hannah Arendt", "Arendt"],
    kind: "autor",
    when: "1906–1975",
    body: "Filósofa política alemana, luego estadounidense. Dijo que la filosofía de Hegel fue el último intento de reunir ser y pensamiento, sin saber si era una «morada» o una «prisión» para la realidad. Más adelante en el curso, con el totalitarismo y la «banalidad del mal».",
  },
  geist: {
    term: "Geist (Espíritu)",
    aka: ["Geist"],
    kind: "concepto",
    when: "Hegel, s. XIX",
    body: "El «Espíritu»: el poder del todo, mejor dejado en alemán. No es un individuo ni una sustancia material, sino la vida social colectiva elevada a fundamento. Hegel lo resume como «el yo que es un nosotros y el nosotros que es un yo»: todo significado es relacional, viene del contexto del todo.",
  },
  dialectica: {
    term: "Dialéctica",
    aka: ["dialéctica", "materialismo dialéctico"],
    kind: "concepto",
    when: "Hegel, s. XIX",
    body: "El motor del movimiento histórico: ocurre cuando las contradicciones se encuentran. Una posición se vuelve inestable, algo la niega (negación determinada) y se pasa a un estadio superior que a la vez cancela, preserva y eleva al anterior. La historia avanza así, en espiral, a los saltos.",
  },
  aufhebung: {
    term: "Aufhebung (aufheben)",
    aka: ["Aufhebung", "aufheben"],
    kind: "concepto",
    when: "Hegel, s. XIX",
    body: "Verbo intraducible del corazón de la dialéctica: negar de un modo que a la vez preserva y eleva. Abolir sin cancelar del todo; conservar algo como momento de una síntesis superior. Como el fruto que cancela la flor pero la lleva a su verdad. (También, banalmente, «levantar» algo del piso.)",
  },
  telos: {
    term: "Telos",
    aka: ["telos"],
    kind: "concepto",
    when: "concepto griego, retomado por Hegel",
    body: "El fin o meta que está ya codificado en el comienzo de una cosa. En la semilla de manzana el telos es la manzana: no será una ciruela. La historia, para Hegel, se despliega hacia un telos donde todas las contradicciones —sujeto y objeto, libertad y necesidad— se sintetizan.",
  },
  amo_esclavo: {
    term: "Dialéctica del amo y el esclavo",
    aka: ["dialéctica del amo y el esclavo", "amo y el esclavo", "amo y esclavo"],
    kind: "concepto",
    when: "Hegel, 1807",
    body: "El pasaje más influyente de la Fenomenología. El amo parece todopoderoso, pero se invierte: depende del esclavo para su reconocimiento y solo lo obtiene de un objeto que él mismo cosificó, así que queda insatisfecho. El esclavo, al transformar el mundo con su trabajo, se subjetiva. Nadie es idéntico a sí mismo: toda identidad está mediada.",
  },
  reconocimiento: {
    term: "Reconocimiento",
    aka: ["reconocimiento"],
    kind: "concepto",
    when: "Hegel, 1807",
    body: "Idea clave de la dialéctica del amo y el esclavo: no hay identidad en sí misma, siempre necesita ser reconocida por otro. Solo un sujeto puede otorgar reconocimiento; por eso el amo, que redujo al esclavo a objeto, no logra el reconocimiento que busca. La identidad es siempre mediada por la mirada del otro.",
  },
  alienacion: {
    term: "Alienación",
    aka: ["alienación"],
    kind: "concepto",
    when: "Hegel; luego Marx",
    body: "El gran problema de la modernidad. En Hegel, no comprender la propia existencia individual dentro del Geist, del todo; toda la Fenomenología busca superarla. Marx la volverá concreta: el trabajador alienado de los productos de su trabajo y de sí mismo bajo el capitalismo.",
  },
  cantidad_calidad: {
    term: "De cantidad a calidad",
    aka: ["transformación de la cantidad en calidad", "cantidad en calidad"],
    kind: "concepto",
    when: "Hegel, s. XIX",
    body: "La idea de que los cambios de grado, al acumularse, producen un salto a otra clase de cosa. El modelo es el agua que hierve: un grado más, de 99 a 100, y salta a vapor. Así se mueve la historia hegeliana: no a ritmo parejo, sino a estallidos, con saltos cualitativos.",
  },
  buho_minerva: {
    term: "El búho de Minerva",
    aka: ["búho de Minerva"],
    kind: "concepto",
    when: "Hegel, 1820",
    body: "«El búho de Minerva emprende su vuelo al caer el crepúsculo». Minerva es la diosa de la sabiduría: el sentido de las cosas solo se comprende en retrospectiva, mirando hacia atrás, nunca hacia adelante. De aquí la crítica de Hegel a la moral kantiana de la pura intención.",
  },
  mordida_hegeliana: {
    term: "La «mordida hegeliana»",
    aka: ["mordida hegeliana"],
    kind: "concepto",
    when: "Czesław Miłosz, s. XX",
    body: "Expresión del poeta polaco Miłosz para lo peculiarmente seductor del hegelianismo: la idea de totalidad y direccionalidad —que todo, al final, encaja y va a alguna parte— de la que, una vez atrapado, es muy difícil soltarse. Berlin decía que a los rusos «les das un poco de Hegel y se emborrachan».",
  },
  fenomenologia_espiritu: {
    term: "Fenomenología del espíritu",
    aka: ["Fenomenología del espíritu", "Fenomenología"],
    kind: "obra",
    when: "Hegel, 1807",
    body: "Obra mayor de Hegel, terminada en Jena. Narra el ascenso de la conciencia por estadios de madurez —hasta volverse autoconciencia y fusionarse con el Geist—, superando la alienación. Notoriamente difícil: Herzen dijo que no es un libro que se lea, sino una experiencia que se atraviesa.",
  },
  toma_bastilla: {
    term: "Toma de la Bastilla",
    aka: ["toma de la Bastilla", "Bastilla"],
    kind: "evento",
    when: "14 de julio de 1789",
    body: "Asalto a la fortaleza-prisión de París que simboliza la caída del Ancien Régime y el inicio de la Revolución Francesa. Para Hegel, ejemplo de la irreversibilidad de la historia: no se puede «des-tomar» la Bastilla.",
  },

  // ---------- Clase 4: Marx ----------
  marx: {
    term: "Karl Marx",
    aka: ["Karl Marx", "Marx"],
    kind: "autor",
    when: "1818–1883",
    body: "Filósofo, economista político y revolucionario prusiano, de familia judía asimilada; murió en Londres. Puso a Hegel «patas para arriba»: reemplazó el Espíritu por las fuerzas socioeconómicas. Con Engels escribió el Manifiesto Comunista (1848). Su modelo lee la historia como lucha de clases movida por la economía.",
  },
  engels: {
    term: "Friedrich Engels",
    aka: ["Friedrich Engels", "Engels"],
    kind: "autor",
    when: "1820–1895",
    body: "Pensador y empresario alemán, coautor y sostén de Marx, a quien conoció en un café de París en 1844. Ayudó a formular el materialismo dialéctico y a difundir y editar la obra de Marx, incluido El capital.",
  },
  feuerbach: {
    term: "Ludwig Feuerbach",
    aka: ["Feuerbach"],
    kind: "autor",
    when: "1804–1872",
    body: "Filósofo alemán, figura de los jóvenes hegelianos. Usó los métodos de Hegel contra sus conclusiones metafísicas, en clave materialista (la religión como proyección humana). Influyó en el giro de Marx del idealismo al materialismo.",
  },
  lenin: {
    term: "Vladímir Lenin",
    aka: ["Lenin"],
    kind: "autor",
    when: "1870–1924",
    body: "Revolucionario ruso, dirigente de la Revolución de Octubre de 1917. Vendrá a resolver el «problema calvinista» del marxismo clásico: si la revolución es inevitable, ¿para qué actuar? Su respuesta —el partido de vanguardia— se verá más adelante en el curso.",
  },
  jovenes_hegelianos: {
    term: "Jóvenes hegelianos",
    aka: ["jóvenes hegelianos", "hegelianos de izquierda"],
    kind: "concepto",
    when: "Alemania, 1830s–1840s",
    body: "Grupo de filósofos y periodistas (Feuerbach, Bauer) que adoptaron los métodos de Hegel pero se opusieron a sus conclusiones. Ejemplifican una ley de la historia intelectual: quien escribe un texto no tiene el monopolio de su interpretación; los textos son provocaciones al pensamiento.",
  },
  materialismo: {
    term: "Materialismo",
    aka: ["materialismo"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "Contra el idealismo de Hegel, la tesis de que lo determinante no son las ideas ni el espíritu, sino las condiciones materiales y socioeconómicas. Marx habla de materialismo dialéctico: la dialéctica hegeliana bajada del cielo a la tierra, vuelta concreta.",
  },
  industrializacion: {
    term: "Industrialización",
    aka: ["industrialización"],
    kind: "concepto",
    when: "s. XVIII–XIX",
    body: "El paso a la producción fabril con tecnología y a gran escala. Para Marx es el factor decisivo del comportamiento social moderno: concentra a la gente en las ciudades, crea la burguesía y el proletariado y transforma toda la estructura social.",
  },
  feudalismo: {
    term: "Feudalismo",
    aka: ["feudalismo"],
    kind: "concepto",
    when: "Edad Media europea",
    body: "El orden previo al capitalismo: mundo descentralizado y rural, con una nobleza terrateniente y un campesinado atado a la tierra y al ciclo de las estaciones. Para Marx, dio paso al capitalismo así como este engendrará su propia superación.",
  },
  capitalismo: {
    term: "Capitalismo",
    aka: ["capitalismo"],
    kind: "concepto",
    when: "desde s. XVIII–XIX",
    body: "Orden económico basado en la propiedad privada de los medios de producción, el trabajo asalariado y la acumulación de capital. Para Marx produce naturalmente explotación y alienación, y contiene las semillas de su propia destrucción: engendra al proletariado que lo enterrará.",
  },
  burguesia: {
    term: "Burguesía",
    aka: ["burguesía"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "La clase que posee las fábricas y los medios de producción y emplea trabajo ajeno. No se define por el título heredado (como la nobleza) sino por ser empleadora y acumular capital. Su antagonista es el proletariado.",
  },
  proletariado: {
    term: "Proletariado",
    aka: ["proletariado", "proletarios"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "La clase de los obreros urbanos que, sin poseer medios de producción, venden su trabajo por hora. Alienada de los productos de su trabajo, es —para Marx— la clase predestinada a tomar conciencia, derrocar a la burguesía y liderar la revolución.",
  },
  capital: {
    term: "Capital",
    aka: ["capital"],
    kind: "concepto",
    when: "Marx, El capital, 1867",
    body: "No cualquier dinero, sino dinero que se invierte para hacer más dinero. La burguesía acumula capital con el fin de generar más capital. Casi fetichizado, es el motor del sistema y la fuente de la explotación del trabajo.",
  },
  mercancia: {
    term: "Mercancía",
    aka: ["mercancía", "mercancías"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "Bajo el capitalismo, las relaciones entre personas se convierten en relaciones entre cosas guiadas por la ganancia: el ser humano mismo, que se vende por hora, se vuelve mercancía. Eco de Kant: la persona tratada como medio y no como fin.",
  },
  lucha_clases: {
    term: "Lucha de clases",
    aka: ["lucha de clases"],
    kind: "concepto",
    when: "Marx y Engels, 1848",
    body: "«La historia de toda sociedad hasta hoy es la historia de la lucha de clases.» El motor de la historia es el antagonismo entre opresores y oprimidos, que hoy enfrenta a burguesía y proletariado en el que Marx cree que será el último gran conflicto.",
  },
  base_superestructura: {
    term: "Base y superestructura",
    aka: ["base y superestructura", "superestructura"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "La base es la estructura socioeconómica (¿trabajador o dueño de fábrica?); la superestructura, el arte, la cultura, la conciencia y las ideas. Para Marx la base es determinante y la superestructura, derivada: tu posición en el orden económico determina cómo pensás.",
  },
  conciencia_clase: {
    term: "Conciencia de clase",
    aka: ["conciencia de clase"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "El momento en que los trabajadores comprenden que la burguesía los explota y que el problema no se resuelve sin que todos se levanten. En el marxismo clásico se desarrolla orgánicamente, derivada de la posición objetiva en el orden socioeconómico.",
  },
  dictadura_proletariado: {
    term: "Dictadura del proletariado",
    aka: ["dictadura del proletariado"],
    kind: "concepto",
    when: "Marx, s. XIX",
    body: "Período de transición tras el derrocamiento de la burguesía, necesario porque esta no cederá voluntariamente su propiedad. Precede a la abolición de la propiedad privada y de las fronteras nacionales y a la sociedad comunista: de cada cual según su capacidad, a cada cual según su necesidad.",
  },
  religion_opio: {
    term: "«La religión es el opio de los pueblos»",
    aka: ["opio de los pueblos", "religión es el opio"],
    kind: "concepto",
    when: "Marx, 1844",
    body: "Para Marx y Engels, la religión funciona como una droga que se agita frente a la gente para inducirla a aceptar su propio sufrimiento y explotación, prometiéndole una recompensa en el reino venidero. Por eso adormece la conciencia de clase.",
  },
  manifiesto_comunista: {
    term: "Manifiesto Comunista",
    aka: ["Manifiesto Comunista", "Manifiesto"],
    kind: "obra",
    when: "Marx y Engels, 1848",
    body: "Texto fundacional del marxismo, a la vez teoría de la historia, programa político y profecía. Abre con «Un espectro recorre Europa» y cierra con «¡Trabajadores de todos los países, uníos!». No distingue entre lo que sucederá y lo que debería suceder.",
  },
  primavera_pueblos: {
    term: "Primavera de los pueblos",
    aka: ["primavera de los pueblos"],
    kind: "evento",
    when: "1848",
    body: "Ola de revoluciones por toda Europa en 1848, confluencia de liberalismo y nacionalismo: los distintos pueblos reclaman su propia nación. La mayoría fue sofocada, pero en ese clima —casi sin que nadie lo notara— apareció el Manifiesto Comunista.",
  },

  // ---------- Clase 5: Nietzsche ----------
  wagner: {
    term: "Richard Wagner",
    aka: ["Richard Wagner", "Wagner"],
    kind: "autor",
    when: "1813–1883",
    body: "Compositor alemán con un culto a su alrededor. Creó una ópera específicamente alemana, basada en el mito y lo grandioso, e introdujo el leitmotiv; convirtió la sala de ópera en un templo. Amigo idolatrado del joven Nietzsche —que le dedicó su primer libro— y luego objeto de una ruptura apasionada.",
  },
  bergson: {
    term: "Henri Bergson",
    aka: ["Henri Bergson", "Bergson"],
    kind: "autor",
    when: "1859–1941",
    body: "Filósofo francés del tiempo y la vida, primero del trío antipositivista (con Freud y Husserl). Formado como matemático, piensa el tiempo como un flujo continuo (la durée), no como una fila de instantes. Contra el mecanicismo, defiende el élan vital, la intuición y la contingencia. Judío, rechazó la exención que le ofrecieron los nazis y murió en 1941.",
  },
  muerte_dios: {
    term: "La muerte de Dios",
    aka: ["muerte de Dios", "Dios ha muerto"],
    kind: "concepto",
    when: "Nietzsche, 1882",
    body: "«Dios ha muerto. Y nosotros lo hemos matado.» No es la tesis atea «no hay Dios», sino la constatación de que algo ocurrió: se derrumbó la creencia en un orden que daba sentido, propósito y unidad al mundo. Dios es esa creencia; su muerte es descubrir que el mundo ideal no existe. Irreversible.",
  },
  nihilismo: {
    term: "Nihilismo",
    aka: ["nihilismo", "nihilista"],
    kind: "concepto",
    when: "Nietzsche, s. XIX",
    body: "Otro nombre de la muerte de Dios: cuando los valores supremos pierden su valor y los principios que organizaban la realidad dejan de organizarla. No se resuelve instituyendo un Dios sustituto, porque la raíz de la crisis está justamente en ese intento. Para Nietzsche, el cristianismo mismo es una religión nihilista.",
  },
  ubermensch: {
    term: "Übermensch",
    aka: ["Übermensch"],
    kind: "concepto",
    when: "Nietzsche, 1883",
    body: "«Super-persona», palabra intraducible. No es un superhombre ya realizado, sino una meta imaginaria: aquello que el hombre debe superarse a sí mismo para llegar a ser. «El hombre es algo que debe ser superado»: una cuerda tendida sobre un abismo, un puente entre la bestia y el Übermensch.",
  },
  eterno_retorno: {
    term: "Eterno retorno",
    aka: ["eterno retorno"],
    kind: "concepto",
    when: "Nietzsche, 1882",
    body: "Idea sin acuerdo sobre su sentido. Tres lecturas: kantiana (vivir cada instante como si fuera a repetirse eternamente); del todo (cada momento es integral al conjunto, y solo el Übermensch tiene la fuerza de abrazarlo); y una cercana a Bergson (la eternidad como núcleo continuo del tiempo, distinta de la infinitud).",
  },
  moral_esclavos: {
    term: "Moral de esclavos",
    aka: ["moral de esclavos"],
    kind: "concepto",
    when: "Nietzsche, 1887",
    body: "La inversión que convierte la debilidad en virtud. El esclavo resentido concibe al amo como malo y a sí mismo como bueno y puro, y así santifica su propia opresión con la promesa de una recompensa venidera. Nietzsche la ve en el cristianismo («los mansos heredarán la tierra») y en la democracia.",
  },
  nacimiento_tragedia: {
    term: "El nacimiento de la tragedia",
    aka: ["El nacimiento de la tragedia"],
    kind: "obra",
    when: "Nietzsche, 1872",
    body: "Primer libro de Nietzsche, dedicado a Wagner, cuyas óperas presenta como herederas de la tragedia griega. Sostiene que el arte es «la única actividad verdaderamente metafísica» y que solo como fenómeno estético puede justificarse el mundo.",
  },
  gaya_ciencia: {
    term: "La gaya ciencia",
    aka: ["La gaya ciencia"],
    kind: "obra",
    when: "Nietzsche, 1882",
    body: "Obra donde un «loco» anuncia la muerte de Dios. Wissenschaft en sentido amplio: la «ciencia alegre». Introduce también, hacia el final, el pensamiento del eterno retorno.",
  },
  zaratustra: {
    term: "Así habló Zaratustra",
    aka: ["Así habló Zaratustra", "Zaratustra"],
    kind: "obra",
    when: "Nietzsche, 1883–1885",
    body: "Libro muy melódico, protagonizado por un profeta —alter ego de Nietzsche— que baja de las montañas a anunciar el Übermensch y el imperativo de aspirar a la grandeza. Cada pasaje cierra con «así habló Zaratustra».",
  },
  mas_alla_bien_mal: {
    term: "Más allá del bien y del mal",
    aka: ["Más allá del bien y del mal"],
    kind: "obra",
    when: "Nietzsche, 1886",
    body: "Obra donde Nietzsche sostiene que lo bueno y lo malo, lo verdadero y lo falso, están insidiosamente entrelazados —quizá sean, en su esencia, una sola cosa—. Nos fuerza a cuestionar las categorías morales en que vivimos.",
  },
  sobre_historia: {
    term: "Sobre la utilidad y el perjuicio de la historia para la vida",
    aka: ["Sobre la utilidad y el perjuicio de la historia para la vida", "Sobre la utilidad y el perjuicio de la historia"],
    kind: "obra",
    when: "Nietzsche, 1874",
    body: "Segunda de las Consideraciones intempestivas. Sostiene que demasiada historia enferma: solo los fuertes la soportan. Envidia a las vacas, felices en su presentismo, y ataca a Hegel por divinizar la historia como «proceso mundial».",
  },
  guerra_franco_prusiana: {
    term: "Guerra franco-prusiana",
    aka: ["guerra franco-prusiana"],
    kind: "evento",
    when: "1870–1871",
    body: "Guerra provocada por Bismarck para unificar los Estados alemanes en un Imperio, declarado en 1871. Nietzsche sirvió en ella como camillero médico y volvió con la salud arruinada, de la que nunca se recuperó del todo.",
  },

  // ---------- Clase 6: Bergson ----------
  spencer: {
    term: "Herbert Spencer",
    aka: ["Herbert Spencer", "Spencer"],
    kind: "autor",
    when: "1820–1903",
    body: "Filósofo positivista inglés. Sostenía que el único conocimiento sólido está en las ciencias, era utilitarista en ética y creía en la evolución y en la perfectibilidad humana. Fue la principal influencia positivista del joven Bergson, y más tarde el blanco central de su revuelta.",
  },
  cantor: {
    term: "Georg Cantor",
    aka: ["Georg Cantor", "Cantor"],
    kind: "autor",
    when: "1845–1918",
    body: "Matemático alemán, creador de la teoría de conjuntos. Formuló en 1878 la hipótesis del continuo y distinguió distintos tipos de infinito. Bergson toma de él la distinción entre lo discreto (los enteros) y lo continuo (los puntos de la recta) para pensar el tiempo.",
  },
  einstein: {
    term: "Albert Einstein",
    aka: ["Albert Einstein", "Einstein"],
    kind: "autor",
    when: "1879–1955",
    body: "Físico alemán, autor de la teoría de la relatividad. A principios del siglo XX polemizó con Bergson sobre la naturaleza del tiempo: Einstein lo mide por instantes; Bergson insiste en que el tiempo real es flujo (durée), porque solo así cabe en él la contingencia y el libre albedrío.",
  },
  freud: {
    term: "Sigmund Freud",
    aka: ["Sigmund Freud", "Freud"],
    kind: "autor",
    when: "1856–1939",
    body: "Médico y creador del psicoanálisis, a quien el curso dedica una clase más adelante. Junto con Bergson y Husserl integra el trío de rebeldes contra el positivismo: cada uno señala una dimensión de la vida —el tiempo, el inconsciente, la conciencia— que la ciencia empírica no alcanza a captar.",
  },
  husserl: {
    term: "Edmund Husserl",
    aka: ["Edmund Husserl", "Husserl"],
    kind: "autor",
    when: "1859–1938",
    body: "Filósofo alemán, fundador de la fenomenología, tratado más adelante en el curso. Como Bergson, empezó como matemático (Cantor fue mentor suyo) y forma parte del trío antipositivista. Su «reducción fenomenológica» busca, como la risa en Bergson, apartar los velos para ver la realidad misma.",
  },
  duree: {
    term: "Durée (duración)",
    aka: ["durée", "duración"],
    kind: "concepto",
    when: "Bergson, desde 1889",
    body: "El tiempo tal como lo vivimos: un flujo dinámico, irreversible y continuo, no una fila de instantes. La durée no puede contarse ni dividirse en puntos sin traicionarla —cortarla es «pasar un cuchillo a través de una llama»—. Es una multiplicidad cualitativa, ligada a la conciencia y al libre albedrío.",
  },
  elan_vital: {
    term: "Élan vital",
    aka: ["élan vital", "fuerza vital"],
    kind: "concepto",
    when: "Bergson, 1907",
    body: "El «impulso vital»: la fuerza creadora que empuja la vida y la evolución. No sigue un programa preplaneado ni una meta fija, sino que avanza por líneas divergentes, como un proyectil que estalla y dispersa fragmentos en todas direcciones. Es la respuesta de Bergson al finalismo y al mecanicismo.",
  },
  multiplicidad_cualitativa: {
    term: "Multiplicidad cualitativa",
    aka: ["multiplicidad cualitativa"],
    kind: "concepto",
    when: "Bergson, 1889",
    body: "El modo de ser del tiempo vivido, opuesto a la multiplicidad cuantitativa de los números. Sus momentos no están separados como los enteros (1, 2, 3), sino que «se penetran unos a otros» y se funden en un todo orgánico, sin huecos ni fronteras duras. De ella brota, para Bergson, el acto libre.",
  },
  intuicion: {
    term: "Intuición (vs. intelecto)",
    aka: ["intuición", "intelecto"],
    kind: "concepto",
    when: "Bergson, 1907",
    body: "La última dualidad de Bergson. El intelecto es analítico y externo: ve en piezas y partes, sirve para la materia inerte, pero tiene «una incapacidad natural para comprender la vida». La intuición —forma sofisticada del instinto— aprehende lo vivo desde adentro, holísticamente, de un solo golpe. Se necesitan ambos, pero la intuición es superior.",
  },
  mecanicismo: {
    term: "Mecanicismo",
    aka: ["mecanicismo", "mecanicista"],
    kind: "concepto",
    when: "supuesto ilustrado-positivista",
    body: "La idea de que la naturaleza funciona como una máquina cuyas partes encajan, y que se comprende el todo comprendiendo las partes (una bicicleta: engranajes, ruedas, tornillos). Bergson lo acepta para la materia inerte, pero lo rechaza para la vida: no podemos entender lo vivo como entendemos una bicicleta.",
  },
  finalismo: {
    term: "Finalismo",
    aka: ["finalismo"],
    kind: "concepto",
    when: "criticado por Bergson, 1907",
    body: "La teleología aplicada a la vida: la idea de que esta se mueve hacia un telos ya dado. La imagen es la semilla de manzana, que trae «precableada» la manzana y no se volverá otra cosa. Bergson lo rechaza porque, cuanto más determinismo, menos libre albedrío: la evolución no tiene un programa preescrito.",
  },
  contingencia: {
    term: "Contingencia",
    aka: ["contingencia", "contingencia radical"],
    kind: "concepto",
    when: "Bergson, s. XX",
    body: "Lo opuesto del determinismo: que siempre hay múltiples posibilidades, y que el accidente y la elección tienen un papel. Bergson la liga al tiempo como flujo abierto. El ser vivo introduce en el mundo una «contingencia radical»; en Hannah Arendt eso se llamará natalidad.",
  },
  vitalismo: {
    term: "Vitalismo",
    aka: ["vitalismo"],
    kind: "concepto",
    when: "fines s. XIX – s. XX",
    body: "Corriente que pone la vida y su impulso creador —no la materia ni el mecanismo— en el centro de la filosofía. En Bergson toma la forma del élan vital y la primacía de la intuición. Paradójicamente, los nazis admiraban su vitalismo, aunque él era judío y lo rechazó.",
  },
  evolucion_creadora: {
    term: "La evolución creadora",
    aka: ["La evolución creadora"],
    kind: "obra",
    when: "Bergson, 1907",
    body: "Obra mayor de Bergson. Ataca de nuevo a Spencer y refuta dos ideas hermanas: el finalismo (la vida hacia un telos dado) y el mecanicismo (la naturaleza como máquina). Frente a ellas propone el élan vital: la evolución es pluridimensional y creadora, avanza por líneas divergentes.",
  },
  la_risa: {
    term: "La risa",
    aka: ["La risa"],
    kind: "obra",
    when: "Bergson, 1900",
    body: "Ensayo célebre sobre lo cómico. Es humorístico lo que carece de autoconciencia, lo que revela por su rigidez «puro mecanismo, automatismo, movimiento sin vida». La risa es un correctivo social que rompe ese mecanismo —cercano a la desfamiliarización— y nos deja ver la realidad con más claridad.",
  },

  // ---------- Clase 7: Leninismo ----------
  luxemburg: {
    term: "Rosa Luxemburg",
    aka: ["Rosa Luxemburg", "Luxemburg"],
    kind: "autor",
    when: "1871–1919",
    body: "Revolucionaria marxista de familia judía polaca, luego líder del comunismo alemán. Brillante e intransigente, criticó la modificación leninista: hay que confiar en las leyes de la historia y en los trabajadores, y toda élite termina volviéndose conservadora. Fue asesinada en Berlín en 1919 y su cuerpo arrojado a un río.",
  },
  lukacs: {
    term: "Georg Lukács",
    aka: ["Georg Lukács", "Lukács"],
    kind: "autor",
    when: "1885–1971",
    body: "Filósofo marxista húngaro. En Historia y conciencia de clase se pone del lado de Lenin: todo el marxismo se sostiene sobre la categoría de totalidad, que el sindicalismo no logra captar. Para él el Partido es la encarnación de la conciencia de clase y sabe lo que piensan los obreros antes que ellos mismos.",
  },
  trotsky: {
    term: "León Trotsky",
    aka: ["León Trotsky", "Trotsky"],
    kind: "autor",
    when: "1879–1940",
    body: "Revolucionario ruso. Antes menchevique, cruzó al bolchevismo y fue clave en la toma del poder; mandó a los mencheviques «al basurero de la historia». Defendió la revolución permanente frente al «socialismo en un solo país» de Stalin, que lo persiguió hasta México, donde un agente suyo lo mató con un piolet.",
  },
  que_hacer: {
    term: "¿Qué hacer? (Shto Delat)",
    aka: ["¿Qué hacer?", "Shto Delat"],
    kind: "obra",
    when: "Lenin, 1902",
    body: "Texto donde Lenin modifica el marxismo para apurar la historia. Sostiene que la clase obrera, librada a sí misma, solo alcanza «conciencia sindical»: la verdadera conciencia hay que llevársela desde afuera, mediante una organización de revolucionarios profesionales. Quizá el escrito más influyente del siglo XX por su capacidad de torcer la historia.",
  },
  partido_vanguardia: {
    term: "Vanguardia (leninista)",
    aka: ["vanguardia leninista", "vanguardia de revolucionarios profesionales", "partido de vanguardia", "revolucionarios profesionales"],
    kind: "concepto",
    when: "Lenin, 1902",
    body: "La élite de revolucionarios profesionales que, en la teoría de Lenin, hace de la agitación su oficio y le lleva la conciencia de clase al proletariado para acelerar la revolución. Se organiza en el Partido, con mayúscula: consagración total, disciplina de hierro y vida conspirativa.",
  },
  bolcheviques: {
    term: "Bolcheviques",
    aka: ["bolcheviques", "bolchevismo"],
    kind: "concepto",
    when: "desde 1903",
    body: "La facción (de «mayoría» en ruso) que, en la escisión de 1903, apoyó la modificación de Lenin y la idea de apurar la historia. Bajo su dirección se toma el poder en octubre de 1917. Se oponen a los mencheviques, partidarios de esperar a que la historia se despliegue.",
  },
  mencheviques: {
    term: "Mencheviques",
    aka: ["mencheviques", "menchevismo"],
    kind: "concepto",
    when: "desde 1903",
    body: "La facción (de «minoría» en ruso) que, en 1903, rechazó la modificación leninista y sostuvo una línea marxista más conservadora: hay que esperar a que maduren las condiciones y confiar en las leyes de la historia, no forzar la revolución desde una vanguardia.",
  },
  economismo: {
    term: "Economismo (pensar en chico)",
    aka: ["economismo", "espontaneidad", "sindicalismo"],
    kind: "concepto",
    when: "Lenin, 1902",
    body: "Los nombres que da Lenin al «pensar en chico» de los obreros: pedir mejoras inmediatas —mejor paga, jornada más corta— en vez de derrocar el sistema. La espontaneidad es acción sin reflexión crítica; el sindicalismo, organizarse como gremio y no como revolucionarios. Para Lenin, síntoma de que falta la conciencia de la totalidad.",
  },
  comunismo: {
    term: "Comunismo",
    aka: ["comunismo"],
    kind: "concepto",
    when: "telos marxista",
    body: "Para Marx, el fin de la historia: los trabajadores, ya conscientes de clase, derrocan a la burguesía, abolen la propiedad privada y las fronteras nacionales, y cada uno trabaja según su capacidad y recibe según su necesidad. Todo el antagonismo de clase queda aufgehoben (superado). Hacia 1900, «socialdemocracia» se usaba como sinónimo.",
  },
  proletariado_metafisico: {
    term: "Proletariado metafísico",
    aka: ["proletariado metafísico"],
    kind: "concepto",
    when: "Rusia, 1917",
    body: "Expresión de la clase para lo que los bolcheviques representaban en 1917: casi no había obreros (unos 3 millones sobre 167). No fue una revolución obrera, sino en nombre de los obreros —incluso de los que recién surgirían una vez apurada la industrialización—. Un proletariado más postulado que real.",
  },
  soviet: {
    term: "Soviet",
    aka: ["Soviet de Petrogrado", "soviet"],
    kind: "concepto",
    when: "Rusia, 1905 / 1917",
    body: "Consejo de trabajadores, soldados y marineros. Tras la abdicación del zar en 1917 surge el «doble poder»: un gobierno provisional burgués y el Soviet de Petrogrado, más socialista y proletario. Lenin exigirá «todo el poder a los soviets». Dará su nombre a la Unión Soviética.",
  },
  revolucion_bolchevique: {
    term: "Revolución Bolchevique",
    aka: ["Revolución Bolchevique", "Revolución de Octubre"],
    kind: "evento",
    when: "octubre / noviembre de 1917",
    body: "Toma del poder por los bolcheviques en Petrogrado, en plena Primera Guerra, que desemboca en la creación de la Unión Soviética. La clase la llama el acontecimiento seminal del siglo XX: todo el pensamiento europeo posterior es, en algún sentido, una respuesta a ese experimento radical.",
  },
  brest_litovsk: {
    term: "Paz de Brest-Litovsk",
    aka: ["Brest-Litovsk"],
    kind: "evento",
    when: "1918",
    body: "Paz por separado que Lenin firma con Alemania para sacar a Rusia de la Primera Guerra. La consideraba insignificante porque creía que los trabajadores del mundo se levantarían en cualquier momento. El historiador Rabinowitch la llama «el mayor error del siglo XX»: esa revolución internacional nunca llegó.",
  },

  // ---------- Clase 8: Freud ----------
  stalin: {
    term: "Iósif Stalin",
    aka: ["Iósif Stalin", "Stalin"],
    kind: "autor",
    when: "1878–1953",
    body: "Dirigente soviético que ganó la lucha de poder tras la muerte de Lenin (1924). Declaró el «socialismo en un solo país» frente a la revolución permanente de Trotsky. Bajo su mando crece un Estado totalitario de nuevo tipo, con ingeniería social a gran escala y terror masivo.",
  },
  anna_freud: {
    term: "Anna Freud",
    aka: ["Anna Freud"],
    kind: "autor",
    when: "1895–1982",
    body: "Hija menor de Sigmund Freud y una de sus discípulas más importantes, teórica del psicoanálisis por derecho propio, sobre todo del psicoanálisis infantil y de los mecanismos de defensa del yo.",
  },
  inconsciente: {
    term: "Inconsciente",
    aka: ["inconsciente"],
    kind: "concepto",
    when: "Freud, desde 1900",
    body: "Para Freud, la parte sumergida y más importante de la vida mental: todo lo esencial ocurre allí (el primado del inconsciente). Es como un armario oscuro donde se arroja lo demasiado perturbador para la conciencia; se llena toda la vida y nada desaparece, solo se lo empuja adentro, de donde vuelve disfrazado.",
  },
  represion: {
    term: "Represión",
    aka: ["represión", "retorno de lo reprimido"],
    kind: "concepto",
    when: "Freud, desde 1900",
    body: "El empuje de los deseos inaceptables hacia el inconsciente. Para Freud, crecer es reprimir y vivir es reprimir. Pero el yo es un sistema energético cerrado: lo reprimido no desaparece, vuelve por otra vía —el retorno de lo reprimido—, como culpa, síntoma neurótico o sublimación. «Lo que echás por la puerta vuelve por la ventana.»",
  },
  psicoanalisis: {
    term: "Psicoanálisis",
    aka: ["psicoanálisis"],
    kind: "concepto",
    when: "Freud, término desde 1896",
    body: "El proceso por el que se induce al inconsciente a revelarse. Es, radicalmente, solo hablar: analista y analizante, asociación libre en el diván, varias veces por semana. No lo arregla todo, pero deja lidiar con lo que se escurre por las grietas. Es el poder de las palabras —y algo muy burgués, por el tiempo y el dinero que exige—.",
  },
  complejo_edipo: {
    term: "Complejo de Edipo",
    aka: ["complejo de Edipo"],
    kind: "concepto",
    when: "Freud, desde 1899",
    body: "Del Edipo Rey griego, destinado a matar a su padre y casarse con su madre. Etapa formativa en que el niño desea a la madre, resiente al padre y hasta desea secretamente su muerte. A Freud le basta con que ese deseo titile o aparezca en un sueño; se reprime enseguida, pero, como todo lo reprimido, vuelve a salir.",
  },
  ello_yo_superyo: {
    term: "Ello, yo y superyó",
    aka: ["ello", "das Es", "yo (freudiano)", "das Ich", "superyó", "das Über-Ich"],
    kind: "concepto",
    when: "Freud, 1923",
    body: "Las tres instancias del aparato psíquico. El ello (das Es) es puro deseo inconsciente; el superyó (das Über-Ich) es la conciencia moral, fuente de culpa y sociedad internalizada; el yo (das Ich) media sin descanso entre ambos. De ese conflicto perpetuo se sigue que vivimos, siempre, en tensión con nosotros mismos.",
  },
  eros_tanatos: {
    term: "Eros y Tánatos",
    aka: ["Eros", "Tánatos", "pulsión de muerte", "pulsión de vida"],
    kind: "concepto",
    when: "Freud, 1920",
    body: "Las dos pulsiones «cableadas» del ello, que se aceptan como los postulados de la geometría. Eros es la pulsión de vida —deseo, sexo, placer—; Tánatos, la pulsión de muerte —agresión, ira—. Son universales y primordiales. Freud reprocha a los marxistas ignorar a Tánatos: la agresión es anterior al capitalismo.",
  },
  libido: {
    term: "Libido",
    aka: ["libido"],
    kind: "concepto",
    when: "Freud, desde 1900",
    body: "La energía del deseo, sustancia del ello. La sexualidad freudiana es amplísima: va mucho más allá del coito genital. Como el yo es un sistema cerrado, la libido se traslada de una conducta a otra (sublimación) pero no desaparece: si se la reprime en un lado, reaparece en otro.",
  },
  malestar_civilizacion: {
    term: "El malestar en la civilización",
    aka: ["El malestar en la civilización"],
    kind: "obra",
    when: "Freud, 1930",
    body: "La civilización —vivir juntos— se basa en reprimir tanto Eros como Tánatos. Donde Hobbes cambiaba libertad por seguridad, Freud dice que la sociedad cambia felicidad por seguridad: el principio de placer está necesariamente reñido con el principio de realidad. No hay «felices para siempre».",
  },
  principio_placer: {
    term: "Principio de placer / de realidad",
    aka: ["principio de placer", "principio de realidad"],
    kind: "concepto",
    when: "Freud, desde 1911",
    body: "El principio de placer empuja a la satisfacción inmediata del deseo; el principio de realidad lo frena para poder convivir. La tensión entre ambos es insalvable: reprimir el placer es el precio de la vida en sociedad, y por eso la felicidad plena y la civilización no pueden coexistir.",
  },
  totalitarismo: {
    term: "Totalitarismo",
    aka: ["totalitarismo", "totalitario"],
    kind: "concepto",
    when: "desde el estalinismo, s. XX",
    body: "Régimen de nuevo tipo basado en una ideología con pretensión de verdad absoluta, terror, monopolio de la comunicación y las armas y, sobre todo, un Estado panóptico que borra la distinción entre lo público y lo privado. Toma al pie de la letra la perfectibilidad ilustrada e intenta «reingeniar» a las personas. Reaparecerá con Arendt.",
  },

  // ---------- Clase 9: Modernismo y vanguardia ----------
  baudelaire: {
    term: "Charles Baudelaire",
    aka: ["Charles Baudelaire", "Baudelaire"],
    kind: "autor",
    when: "1821–1867",
    body: "Poeta francés, origen de la primera ola del modernismo. Rechaza que el arte represente solo lo bello: debe abrazar también lo feo, lo obsceno y el lado oscuro. Abre la «crisis de la representación» y el giro hacia adentro, a una subjetividad que no siempre es amable.",
  },
  kafka: {
    term: "Franz Kafka",
    aka: ["Franz Kafka", "Kafka"],
    kind: "autor",
    when: "1883–1924",
    body: "Escritor judío germanoparlante de Praga, profeta de la alienación. En La metamorfosis, Gregor Samsa despierta convertido en insecto: irreconocible para sí mismo. Expresó como nadie el sentirse alienado de todas las identidades. Su alienación es más psicológica que la estructural de Marx.",
  },
  metamorfosis: {
    term: "La metamorfosis",
    aka: ["La metamorfosis"],
    kind: "obra",
    when: "Kafka, 1915–16",
    body: "Relato de Kafka contemporáneo de las Lecciones de Freud. Gregor Samsa despierta «de sueños intranquilos» transformado en un insecto monstruoso. Plantea la pregunta modernista: ¿seguís siendo vos si no hay un yo estable? El giro a la subjetividad radical no da una subjetividad estable, sino la más inestable.",
  },
  saussure: {
    term: "Ferdinand de Saussure",
    aka: ["Ferdinand de Saussure", "Saussure"],
    kind: "autor",
    when: "1857–1913",
    body: "Lingüista suizo, padre del estructuralismo lingüístico. Su Curso de lingüística general (redactado por sus alumnos tras su muerte) sostiene que la lengua es forma y convención, y que el signo une significante y significado de manera arbitraria. Base teórica de la vanguardia y de todo el estructuralismo posterior.",
  },
  jakobson: {
    term: "Roman Jakobson",
    aka: ["Roman Jakobson", "Jakobson"],
    kind: "autor",
    when: "1896–1982",
    body: "Lingüista y teórico ruso, uno de los grandes del estructuralismo. En 1915 ayuda a fundar el estudio del lenguaje poético y su naturaleza autónoma. Años después, en «Sobre una generación que dilapidó a sus poetas», narra el destino trágico de sus amigos vanguardistas.",
  },
  shklovski: {
    term: "Víktor Shklovski",
    aka: ["Víktor Shklovski", "Shklovski"],
    kind: "autor",
    when: "1893–1984",
    body: "Teórico del formalismo ruso. Acuñó la ostranénie (extrañamiento): el arte debe volver extrañas las cosas cotidianas para despertarnos de la percepción automática, «hacer que la piedra se sienta pétrea». La alienación es a la vez enfermedad y cura.",
  },
  marinetti: {
    term: "Filippo Marinetti",
    aka: ["Filippo Marinetti", "Marinetti"],
    kind: "autor",
    when: "1876–1944",
    body: "Fundador del futurismo italiano, ligado a la máquina, la velocidad y la agresión (llegó a decir que la guerra es hermosa). Proclamó las «palabras en libertad». Deriva a la derecha: se une a Mussolini y al fascismo. Jakobson lo llamó «un hombre absolutamente inadecuado para la vida».",
  },
  tzara: {
    term: "Tristan Tzara",
    aka: ["Tristan Tzara", "Tzara"],
    kind: "autor",
    when: "1896–1963",
    body: "Poeta judío rumano, fundador del dadaísmo en Suiza. «Dada nace en medio de la mezcla cosmopolita de Dios y el burdel»: rebelión estética sin sistema, pura libertad que no apunta a nada fuera de sí. «Estoy contra los sistemas; el sistema más aceptable es, en principio, ninguno.»",
  },
  maiakovski: {
    term: "Vladímir Maiakovski",
    aka: ["Vladímir Maiakovski", "Maiakovski"],
    kind: "autor",
    when: "1893–1930",
    body: "Poeta futurista ruso, pasarela entre la vanguardia y la Revolución Comunista. De voz imponente y presencia deslumbrante, encarnó el culto de la juventud y del futuro. Se quitó la vida en 1930: «la barca del amor se estrelló contra lo cotidiano». Su fin simboliza el de toda la vanguardia.",
  },
  vanguardia: {
    term: "Vanguardia (avant-garde)",
    aka: ["vanguardia", "avant-garde", "alto modernismo"],
    kind: "concepto",
    when: "desde la Primera Guerra Mundial",
    body: "La segunda ola del modernismo: un salto por encima del yo hacia una temporalidad experimental. Rompe el vínculo entre palabra y cosa, hace de la forma todo y pasa del arte-representación al arte-transformación —un martillo para crear vida—. Audaz, juvenil, internacionalista y adicta a los manifiestos.",
  },
  crisis_representacion: {
    term: "Crisis de la representación",
    aka: ["crisis de la representación"],
    kind: "concepto",
    when: "modernismo, desde s. XIX",
    body: "La pregunta que abre el modernismo (según Pericles Lewis): ¿cómo representar el mundo? ¿El arte debe ser un espejo objetivo, o mostrar las cosas «desde adentro», como se ven subjetivamente? La vanguardia la lleva al extremo: quizás el arte no deba representar nada en absoluto.",
  },
  estructuralismo_linguistico: {
    term: "Estructuralismo lingüístico",
    aka: ["estructuralismo lingüístico"],
    kind: "concepto",
    when: "Saussure, 1907–1911",
    body: "La teoría de Saussure de que la lengua es forma y convención, y que todo significado es relacional: un signo vale por su diferencia con los demás, dentro de un sistema. Volverá una y otra vez en el curso; la vanguardia la usa para desprender las palabras de las cosas.",
  },
  signo_linguistico: {
    term: "Significante y significado",
    aka: ["significante", "significado", "signo lingüístico"],
    kind: "concepto",
    when: "Saussure, 1907–1911",
    body: "El signo une un significante (los sonidos, la palabra) y un significado (la referencia), de manera arbitraria: «perro» refiere a un perro solo por convención y por contraste con «gato» o «cerro». La vanguardia corta ese vínculo —la palabra «como tal»— y convierte las palabras en cosas.",
  },
  ostranenie: {
    term: "Ostranénie (extrañamiento)",
    aka: ["ostranénie", "extrañamiento", "desfamiliarización"],
    kind: "concepto",
    when: "Shklovski, 1917",
    body: "El extrañamiento o desfamiliarización: usar el lenguaje de modo no transparente para volver raras las cosas cotidianas y despertarnos de la percepción automática, «hacer que la piedra se sienta pétrea». Es a la vez veneno y antídoto, y emparienta con la risa de Bergson y la reducción de Husserl.",
  },
  arte_transformacion: {
    term: "Arte como transformación",
    aka: ["arte como transformación", "arte-transformación"],
    kind: "concepto",
    when: "vanguardia, s. XX",
    body: "El giro más radical de la vanguardia: cortado el vínculo entre significante y significado, el arte ya no representa la vida, la crea. «No es un espejo de la vida, es un martillo para crear vida.» Del arte como representación al arte como transformación —y, con ello, a una caída libre sin suelo—.",
  },
  formalismo_ruso: {
    term: "Formalismo ruso",
    aka: ["formalismo ruso", "formalismo"],
    kind: "concepto",
    when: "Rusia, desde 1915",
    body: "Escuela teórica (Jakobson, Shklovski, Brik) que estudia el lenguaje poético poniendo «entre paréntesis» la referencia, para ver cómo funciona el lenguaje en sí. El lenguaje poético llama la atención sobre su propio significante: es la «puesta al desnudo del procedimiento». De aquí sale la ostranénie.",
  },
  futurismo: {
    term: "Futurismo",
    aka: ["futurismo", "futuristas"],
    kind: "concepto",
    when: "desde 1909",
    body: "Movimiento de vanguardia. El italiano (Marinetti) exalta la tecnología, la velocidad y la agresión, y deriva al fascismo; el ruso (Jlébnikov, Kruchónij) se absorbe en la palabra «como tal», cortada de su referente. Culto de la juventud, del futuro y del escándalo; adicto a los manifiestos.",
  },
  dadaismo: {
    term: "Dadaísmo",
    aka: ["dadaísmo", "Dadá", "Dada"],
    kind: "concepto",
    when: "desde 1916",
    body: "Vanguardia fundada por Tristan Tzara en Suiza, definida como «la reificación de la contingencia»: nada está predeterminado, cualquier cosa puede pasar en cualquier momento, y eso se vuelve una cosa. Rebelión estética sin sistema, pura libertad que no apunta a nada fuera de sí.",
  },
  surrealismo: {
    term: "Surrealismo",
    aka: ["surrealismo", "surrealista"],
    kind: "concepto",
    when: "desde 1924",
    body: "Vanguardia que vuelve a lo freudiano con el automatismo psíquico: la asociación libre exenta de toda preocupación estética o moral. Max Ernst define el collage como «el acoplamiento de dos realidades que en apariencia no pueden acoplarse»: juntar lo que no va junto.",
  },
  manifiesto: {
    term: "Manifiesto (de vanguardia)",
    aka: ["manifiesto de vanguardia", "manifiestos"],
    kind: "concepto",
    when: "vanguardia, s. XX",
    body: "El gran género de la vanguardia, que «produce más manifiestos que arte»: proclamas audaces que rechazan toda regla —gramática, puntuación, tradición— y anuncian el mundo nuevo. Del futurista ruso de 1912: «arrojar a Pushkin, Dostoievski y Tolstói por la borda del barco de la modernidad».",
  },
};
